- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/kotlin-extractor/src/main/kotlin/utils/Iterable.kt
We had a lot of uses of find which looked for a subtype, but then had to cast (seemingly unsafely) the result to that subtype. This pulls all the casts out into a utility function.
> Kotlin: Implement and use fun <T,reified S: T> Iterable<T>.findSubType

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/test/kotlin/library-tests/arrays/arrayIterators.expected
- java/ql/test/kotlin/library-tests/arrays/arrayIterators.kt
- java/ql/test/kotlin/library-tests/arrays/arrayIterators.ql
- java/ql/test/kotlin/library-tests/arrays/test.expected
This PR fixes the extraction of calls to `Array::iterator` function. These iterators were only extracted correctly in `for` loops before. Additionally, iterators of arrays of primitive types are also fixed.
> Kotlin: fix array iterator extraction

- ql/ql/src/codeql_ql/ast/Ast.qll
- ql/ql/src/codeql_ql/ast/internal/Predicate.qll
Predicate references in prameterized modules will resolve to multiple predicates, that's a feature (for now).  
This fixes a FP in the consistency test related to that.
> QL: remove consistency errors related to resolving multiple predicates from parameterized modules

- javascript/extractor/lib/typescript/src/ast_extractor.ts
- javascript/ql/test/library-tests/TypeScript/Types/tests.expected
This re-enables type extraction inside conditional types, i.e. types of form `X extends Y ? A : B`, which are relevant for extracting MaD typings from `.d.ts` files.
This was originally disabled in https://github.com/github/codeql/pull/1295 to avoid divergence issues when extracting the type property graph. However, in https://github.com/github/codeql/pull/3781 we stopped extracting the type property graph entirely, so the previous mitigation should no longer be needed.
I verified that [this code](https://github.com/GoogleChromeLabs/comlink/blob/41eb437b877ce943b7e41636f7ce555b59c1d3a5/dist/comlink.d.ts#L63), which originally caused problems, still works after this change. [Evaluation](https://github.com/github/codeql-dca-main/issues/6483) also looks fine.
> JS: Enable type extraction inside conditional types again

- docs/codeql/support/reusables/versions-compilers.rst
- javascript/extractor/lib/typescript/package.json
- javascript/extractor/lib/typescript/src/ast_extractor.ts
- javascript/extractor/lib/typescript/src/main.ts
- javascript/extractor/lib/typescript/src/type_table.ts
- javascript/extractor/lib/typescript/yarn.lock
- javascript/extractor/src/com/semmle/js/extractor/Main.java
- javascript/extractor/src/com/semmle/ts/extractor/TypeScriptASTConverter.java
- javascript/ql/lib/change-notes/2022-05-24-typescript-4-8.md
- javascript/ql/test/library-tests/TypeScript/Types/printAst.expected
- javascript/ql/test/library-tests/TypeScript/Types/tests.expected
- javascript/ql/test/library-tests/TypeScript/Types/tst.ts
https://devblogs.microsoft.com/typescript/announcing-typescript-4-8
The most tricky part was [a change to the syntax tree representation](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#decorators-are-placed-on-modifiers-on-typescripts-syntax-trees).   
The `modifiers` property that we rely on in `TypeScriptASTConverter.java` might disappear at a later time.  
The fix at that point will be to use `ts.canHaveModifiers()` and `ts.getModifiers()`.   
TypeScript changed how illegal decorators are stored between 4.8.1-RC and 4.8.2 ([this PR](https://github.com/microsoft/TypeScript/pull/50343)). So I had to fix that.  
Otherwise it was an uneventful update.  
There's not much new, and what's new doesn't affect us, except that we get slightly more precise types from …
> JavaScript: Update to TypeScript 4.8

- swift/codegen/schema.yml
- swift/ql/lib/codeql/swift/generated/Callable.qll
- swift/ql/lib/codeql/swift/generated/GetImmediateParent.qll
- swift/ql/lib/codeql/swift/generated/Raw.qll
- swift/ql/lib/swift.dbscheme
- swift/ql/test/library-tests/controlflow/graph/Cfg.expected
- swift/ql/test/library-tests/parent/no_double_parents.expected
- swift/ql/test/library-tests/parent/parent.expected
`RebindSelfInConstructorExpr` marking the `self` `VarDecl` as a child was causing a double parent problem.
The change in order in the `Callable` children is mainly cosmetic now, but will have more meaning after generating `PrintAst` (where we want `self` before the other params).
> Swift: fix double parent

- java/ql/lib/semmle/code/java/security/OverlyLargeRangeQuery.qll
- javascript/ql/lib/semmle/javascript/security/OverlyLargeRangeQuery.qll
- python/ql/lib/semmle/python/security/OverlyLargeRangeQuery.qll
- ruby/ql/lib/codeql/ruby/security/OverlyLargeRangeQuery.qll
The overly-large-range query would produce an extremely big alert message on some regexps from `natalie-lang/natalie`.  
This fixes it.  
I capped the range at 50 chars, because that broke no tests in the existing test-suite.
> put a limit on the length of the equivalent range in overly-large-range

- java/ql/lib/semmle/code/java/security/regexp/ExponentialBackTracking.qll
- javascript/ql/lib/semmle/javascript/security/regexp/ExponentialBackTracking.qll
- python/ql/lib/semmle/python/security/regexp/ExponentialBackTracking.qll
- ruby/ql/lib/codeql/ruby/security/regexp/ExponentialBackTracking.qll
I did a followup evaluation to https://github.com/github/codeql/pull/10062, which found [a performance issue in a single project](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/redosPrefix-chakra-singlethread/reports#query-run-timings-per-source-and-query-single-threaded).   
Fixed by making the `rankState()` predicate smaller by including a simple context.  
All evaluations look good: [JavaScript](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/fixRank-js/reports), [Python](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/fixRank-py/reports), [Java](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/fixRank-java/reports), [Ruby](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/fixRank-rb/reports).
> fix performance issue in the ReDoS query

- java/kotlin-extractor/generate_dbscheme.py
- java/kotlin-extractor/src/main/kotlin/Label.kt
- java/kotlin-extractor/src/main/kotlin/TrapWriter.kt
- java/kotlin-extractor/src/main/kotlin/utils/TypeResults.kt
All DbType* types extend it, and `Label`s require their argument to be a subtype of it.
This gives us a little more type-safety / compiler-checked-documentation, but also I think it will make it easier to write a "cast is safe" internal query.
> Kotlin: Add AnyDbType

- java/kotlin-extractor/src/main/kotlin/utils/TypeSubstitution.kt
It looks like it was safe, but it was hard to see why, and may become unsafe following future kotlinc changes.
`classifierOrNull` is defined as
```
val IrType.classifierOrNull: IrClassifierSymbol?
get() = when (this) {
is IrSimpleType -> classifier
else -> null
}
```
so this is behaviour-preserving.
> Kotlin: Remove a cast from substituteTypeAndArguments

- java/ql/lib/semmle/code/java/dataflow/TypeFlow.qll
- java/ql/lib/semmle/code/java/dispatch/VirtualDispatch.qll
The first commit allows dispatch to methods defined on abstract classes for which we don't have any subclasses. Normally, ruling out abstract classes as the type to dispatch to is fine, as the dispatch targets are inherited by one or more subclasses and thus allowing the dispatch, but for abstract classes intended to be extended outside the analysed source this isn't the case, which left a few glaring holes in our dispatch relation.
The second commit fixes a minor bug in TypeFlow (included as separate commit for visibility, as the code is immediately refactored).
The third commit refactors the code a bit, and also includes upcasts to raw types and unbound parameterised types as interesting starting points for TypeFlow, thus improving our dispatch precision a little bit.
> Java: A couple of small virtual dispatch fixes

- docs/codeql/codeql-overview/codeql-tools.rst
Include links to changelogs, releases, and source code.
See internal issue for context.
> Docs: Add CodeQL standard packs and bundle to CodeQL tools page

- javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll
- javascript/ql/test/library-tests/frameworks/data/test.expected
- javascript/ql/test/library-tests/frameworks/data/test.js
- javascript/ql/test/library-tests/frameworks/data/test.ql
- python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModels.qll
- ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModels.qll
This adds some features related to generics, to support generating MaD typings from `.d.ts` files and similar.
To track types through generics, we encode all the paths leading from some type to all uses of its type variables.
For example for this type,
```ts
interface Node<T> {
value: T | undefined;
resolve(): Promise<T>;
next: Node<T>;
}
```
we'd generate the following rows in a table "type variable" table of form `name;path`:
```
Node.T;Member[value]
Node.T;Member[resolve].ReturnValue.Awaited
Node.T;Member[next].TypeVar[Node.T]
```
Suppose we want to record how to obtain an instance of `ImportantObject` from `mylib`, given this declaration
```ts
export function create(): Node<ImportantObject[]>;
```
we'd generate this type-definition row:
``` …
```
> Support type variables in MaD typings

- swift/codegen/lib/ql.py
- swift/codegen/lib/schema.py
- swift/codegen/schema.yml
- swift/codegen/test/test_cppgen.py
- swift/codegen/test/test_ql.py
- swift/codegen/test/test_qlgen.py
- swift/codegen/test/test_schema.py
- swift/ql/lib/codeql/swift/generated/ParentChild.qll
- swift/ql/lib/codeql/swift/generated/Raw.qll
- swift/ql/lib/codeql/swift/generated/decl/AbstractFunctionDecl.qll
- swift/ql/lib/codeql/swift/generated/decl/ExtensionDecl.qll
- swift/ql/lib/codeql/swift/generated/decl/NominalTypeDecl.qll
- swift/ql/lib/codeql/swift/generated/expr/AbstractClosureExpr.qll
- swift/ql/test/extractor-tests/declarations/all.expected
- swift/ql/test/extractor-tests/declarations/declarations.swift
- swift/ql/test/library-tests/ast/PrintAst.expected
- swift/ql/test/library-tests/ast/declarations.swift
This required a fix in codegen, as order of bases as written in `schema.yml` was not preserved, so the order of children coming from different bases was off in the AST printer. This implied changing the type of `bases` in `schema.Class` from `Set` to `List`, and removing sorting of `bases` in `ql.Class`.
Commit by commit review is encouraged.
> Swift: add generic type parameters to AST children

- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/kotlin-extractor/src/main/kotlin/utils/Iterable.kt
Pulls another cast out into a utility function.
> Kotlin: Implement and use singleOrNullSubType

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/kotlin-extractor/src/main/kotlin/comments/CommentExtractor.kt
- java/ql/test/kotlin/library-tests/comments/comments.expected
- java/ql/test/kotlin/library-tests/comments/comments.kt
This PR (i) handles the extraction of doc comments assigned to anonymous init blocks, (ii) improves extraction messages, and (iii) improves code quality.
> Kotlin: Fix issues in comment extraction

- swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPrivate.qll
This tiny simplification was made possible by https://github.com/github/codeql/pull/10111 .
> Swift: Clean up the URL.init model.

- swift/ql/lib/codeql/swift/elements/decl/TypeDecl.qll
I hope this makes life a bit easier for you @geoffw0.
> Swift: Add `getBaseTypeDecl` to `TypeDecl`

- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
I think we'll end up giving a warning/error later, but that's better than having a cast throw now.
> Kotlin: Remove another cast

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
> Kotlin: Refactor extractConstructorCall

- swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.ql
Very minor follow-up to https://github.com/github/codeql/pull/10061, taking advantage of https://github.com/github/codeql/pull/10254.
@MathiasVP
> Swift: Use TypeDecl.getABaseTypeDecl().

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/modules_rec.rb
When debugging a performance problem related to the call graph, I noticed that `trackInstance` could yield multiple results for top-level `self` accesses. This PR removes multiplicity by ruling out top-level accesses in `trackModule`, which means that in
```rb
def foo
end
self.foo
```
the `self` qualifier will only get type `Object` and not `Class`.
> Ruby: Exclude top-level `self` accesses from `trackModule`

- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
> Kotlin: Refactor kotlinFunctionToJavaEquivalent

- cpp/ql/lib/experimental/semmle/code/cpp/semantic/analysis/SignAnalysisCommon.qll
This predicate was clearly supposed to _not_ be inlined.
Before:
```ql
Evaluated recursive predicate SignAnalysisCommon#5ca83560::SignExpr::getSign#0#dispred#ff@a481b3wo in 81422ms on iteration 3 (delta size: null).
Evaluated relational algebra for predicate SignAnalysisCommon#5ca83560::SignExpr::getSign#0#dispred#ff@a481b3wo on iteration 3 running pipeline order_500000 with tuple counts:
20500   ~13%    {3} r1 = JOIN SignAnalysisCommon#5ca83560::semExprSign#1#ff#prev_delta WITH project#SemanticExpr#0e61f670::SemUnaryExpr#ffff#3_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Rhs.1, Lhs.1
8000    ~9%    {2} r2 = JOIN r1 WITH SignAnalysisCommon#5ca83560::CastSignExpr#class#ff ON FIRST 2 OUTPUT Lhs.0, Lhs.2
0    ~0%    {3} r3 = JOIN SignAnalysisCommon#5ca83560::semSsaSign#2#fff#prev_delta WITH …
```
> C++: Fix join in sign analysis

- go/ql/src/Security/CWE-322/InsecureHostKeyCallback.ql
- go/ql/src/change-notes/2022-08-29-add-security-severity.md
- java/ql/src/Frameworks/JavaEE/EJB/EjbContainerInterference.ql
- java/ql/src/Frameworks/JavaEE/EJB/EjbFileIO.ql
- java/ql/src/Frameworks/JavaEE/EJB/EjbNative.ql
- java/ql/src/Frameworks/JavaEE/EJB/EjbReflection.ql
- java/ql/src/Frameworks/JavaEE/EJB/EjbSecurityConfiguration.ql
- java/ql/src/Frameworks/JavaEE/EJB/EjbSerialization.ql
- java/ql/src/Frameworks/JavaEE/EJB/EjbSetSocketOrUrlFactory.ql
- java/ql/src/change-notes/2022-08-29-remove-security-tag.md
- python/ql/src/Security/CWE-730/PolynomialReDoS.ql
- python/ql/src/Security/CWE-730/ReDoS.ql
- python/ql/src/Security/CWE-730/RegexInjection.ql
- python/ql/src/change-notes/2022-08-29-missing-security-severity.md
I stumbled upon a query that had a missing `@tag security`.  
So I took a look at the results of `ql/missing-security-metadata`, and added the missing tags were I could.  
[There still some queries with missing @security-severity](https://github.com/github/codeql/security/code-scanning?query=pr%3A10180+tool%3ACodeQL+is%3Aopen+rule%3Aql%2Fmissing-security-metadata), but they are also not tagged with any CWEs, so I'm not sure what to set the value to.
> Add missing security tags

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
I'm not entirely happy with this, but it at least meets the goal of removing the cast.
> Kotlin: Remove cast from extractRawMethodAccess

- .github/workflows/ql-for-ql-build.yml
See also https://github.com/github/codeql-action/pull/1234
Since the introduction of TRAP caching, the CodeQL Action now does `codeql resolve languages` to find languages that support TRAP caching. This is failing for QL4QL because we aren't passing the `--search-path` to find the custom extractor in this call. This PR adds that in.
> QL4QL: Add `--search-path` to `codeql resolve languages` calls

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
It turns out that this was really behaving as a nullness check.
> Kotlin: Remove cast in extractGeneratedClass

- ql/ql/src/codeql_ql/style/NodeName.qll
- ql/ql/src/queries/style/ConsistentCasing.ql
- ql/ql/test/queries/style/Misspelling/Misspelling.expected
E.g. having both `InstanceOfExpr` and `InstanceofExpr` is confusing.  The should use consistent casing.  
The query detects when the same kind of node (e.g. class, predicate, newtype) have different names only differ in casing.  
I changed `NodeName.qll` to treat more things as having the same "kind". 
You can see the new alerts here: https://github.com/github/codeql/security/code-scanning?query=pr%3A10209+tool%3ACodeQL+is%3Aopen+rule%3Aql%2Fnames-only-differing-by-case
> QL: add query detecting consistent casing of names

- ruby/ql/lib/codeql/ruby/ast/internal/Module.qll
The syntax_suggest library redefines Kernel.require/require_relative. Somehow this causes performance issues on ruby/ruby. As a workaround we exclude 'require' and 'require_relative'.
> Ruby: exclude 'require' and 'require_relative' definitions from call graph

- csharp/tools/tracing-config.lua
Disable shared compilation for `dotnet publish` (like `dotnet build` and `dotnet msbuild`).
Update: Extended to also cover `dotnet {pack,run,test}`.
> C#: Also inject `/p:UseSharedCompilation=false` into `dotnet publish`

- .github/workflows/codeql-analysis.yml
Instead, rely on the tracer to inject the flag.
> C#: No longer manually disable shared compilation in `codeql-analysis.yml`

- docs/codeql/ql-language-reference/index.rst
- docs/codeql/ql-language-reference/modules.rst
- docs/codeql/ql-language-reference/name-resolution.rst
- docs/codeql/ql-language-reference/signatures.rst
This is a draft of the reference entry for parameterised modules and signatures.
fixes https://github.com/github/codeql-core/issues/2447
> parameterised modules in the QL language reference

- java/ql/lib/semmle/code/java/security/ImplicitPendingIntents.qll
- java/ql/src/change-notes/2022-09-01-implicit-pendingintents-new-sinks.md
- java/ql/test/query-tests/security/CWE-927/ImplicitPendingIntentsTest.java
- java/ql/test/stubs/google-android-9.0.0/android/app/AlarmManager.java
This PR adds new sinks related to `AlarmManager` to the query Use of implicit PendingIntents.
This adds coverage for CVE-2021-0599.
> Java: Add new AlarmManager sinks to Use of implicit PendingIntents

- .github/workflows/csv-coverage-metrics.yml
- cpp/autobuilder/Semmle.Autobuild.Cpp.Tests/BuildScripts.cs
- docs/codeql/codeql-cli/creating-codeql-databases.rst
No longer needed with the new tracer.
> Docs: No longer mention required `/p:UseSharedCompilation=false`

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/calls.rb
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/superclasses.expected
Call targets were missing for singleton method calls inside uncalled singleton methods:
```rb
class Singletons
def self.singleton_a
self.singleton_b # missing call target, when there is no call to `singleton_a`
end
def self.singleton_b
end
end
```
> Ruby: Add missing edges to the call graph for singleton methods

- csharp/ql/integration-tests/all-platforms/dotnet_build/Program.cs
- csharp/ql/integration-tests/all-platforms/dotnet_build/dotnet_build.csproj
- csharp/ql/integration-tests/all-platforms/dotnet_build/test.py
- csharp/ql/integration-tests/all-platforms/qlpack.yml
This PR adds an initial C# integration test. Follow-up PRs will add more.
> C#: Add `dotnet build` integration test

- java/ql/lib/semmle/code/java/dataflow/TypeFlow.qll
TypeFlow is calculating type bounds through universal flow, and thus uses recursion through forall. Least fixpoint semantics means that we previously didn't get any bounds for SCCs. This PR fixes this by applying SCC reduction and calculating type bounds on the resulting DAG. This improves virtual dispatch precision.
The existing recursion-through-forall-by-way-of-edge-ranking is refactored into a parameterised module.
> Java: Support SCCs in TypeFlow.

- java/ql/src/experimental/Security/CWE/CWE-625/PermissiveDotRegex.qhelp
- java/ql/src/experimental/Security/CWE/CWE-625/PermissiveDotRegex.ql
- java/ql/src/experimental/Security/CWE/CWE-625/PermissiveDotRegexQuery.qll
- java/ql/src/experimental/Security/CWE/CWE-625/Regex.qll
Fixes some docs in the experimental query "Permissive dot regex" merged in https://github.com/github/codeql/pull/9873.
> Java: Documentation fixes in the "Permissive dot regex" experimental query

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
Thanks to the new join-order analyzer in VS Code for reporting this:
Before
```
Evaluated relational algebra for predicate DataFlowDispatch#36b84300::parameterMatch#2#ff@281bdfu5 with tuple counts:
23338949   ~0%    {2} r1 = JOIN DataFlowDispatch#36b84300::Cached::TParameterPosition#f WITH DataFlowDispatch#36b84300::Cached::TArgumentPosition#f CARTESIAN PRODUCT OUTPUT Lhs.0, Rhs.0
65011   ~0%    {2} r2 = JOIN r1 WITH DataFlowDispatch#36b84300::Cached::TAnyParameterPosition#f ON FIRST 1 OUTPUT Lhs.0, Lhs.1
65010   ~0%    {2} r3 = r2 AND NOT DataFlowDispatch#36b84300::Cached::TSelfArgumentPosition#f(Lhs.1)
23338949   ~0%    {2} r4 = JOIN DataFlowDispatch#36b84300::Cached::TParameterPosition#f WITH DataFlowDispatch#36b84300::Cached::TArgumentPosition#f CARTESIAN PRODUCT OUTPUT Rhs.0, Lhs.0 …
```
> Ruby: Fix bad join in `parameterMatch`

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
useClassSource already checks to see if it is given an anonymous object, and behaves accordingly.
> Kotlin: Remove some redundant code

- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
It's now simpler, and doesn't require we ask the Kotlin compiler to build as many types for us.
> Kotlin: Rewrite array type extraction

- javascript/ql/lib/semmle/javascript/ApiGraphs.qll
- javascript/ql/lib/semmle/javascript/dataflow/Sources.qll
- javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll
- javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll
- javascript/ql/test/ApiGraphs/custom-entry-point/index.js
- javascript/ql/test/ApiGraphs/typed/NodeOfType.expected
- javascript/ql/test/library-tests/TypeScript/HasUnderlyingType/HasUnderlyingType.expected
- javascript/ql/test/library-tests/frameworks/Redux/test.expected
- python/ql/lib/semmle/python/ApiGraphs.qll
- python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModels.qll
- python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModelsSpecific.qll
- python/ql/test/library-tests/ApiGraphs/py3/test_entry_point.py
- python/ql/test/library-tests/ApiGraphs/py3/verifyApiGraphs.ql
- ruby/ql/lib/codeql/ruby/ApiGraphs.qll
- ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModels.qll
- ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModelsSpecific.qll
- ruby/ql/test/library-tests/dataflow/api-graphs/test1.rb
- ruby/ql/test/library-tests/dataflow/api-graphs/use.ql
- ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
- ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql
- ruby/ql/test/library-tests/dataflow/summaries/summaries.rb
Adds the following hook in `ModelInput` as way to contribute type-definitions from CodeQL.
```ql
/**
* A unit class for adding additional type model rows from CodeQL models.
*/
class TypeModel extends Unit {
/**
* Gets a data-flow node that is a source of the type `package;type`.
*/
DataFlow::Node getASource(string package, string type) { none() }
/**
* Gets a data flow node that is a sink of the type `package;type`,
* usually because it is an argument passed to a parameter of that type.
*/
DataFlow::Node getASink(string package, string type) { none() }
}
```
For example, one of the use-cases could be in https://github.com/github/codeql/pull/10090 where it would look something like this
```ql
class AttachmentInstanceType extends ModelInput::TypeModel {
override DataFlow::LocalSourceNode …
```
> Add TypeModel hook for adding MaD type-defs from CodeQL

- cpp/ql/lib/experimental/semmle/code/cpp/semantic/SemanticExprSpecific.qll
I could have sworn that I saw you fix this at some point @rdmarsh2 🤔.
> C++: Remove CP in `getAPhiInput`

- swift/ql/lib/codeql/swift/security/SensitiveExprs.qll
- swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.ql
- swift/ql/src/queries/Security/CWE-311/CleartextTransmission.ql
- swift/ql/test/query-tests/Security/CWE-311/CleartextStorageDatabase.expected
- swift/ql/test/query-tests/Security/CWE-311/CleartextTransmission.expected
- swift/ql/test/query-tests/Security/CWE-311/SensitiveExprs.expected
- swift/ql/test/query-tests/Security/CWE-311/testCoreData.swift
- swift/ql/test/query-tests/Security/CWE-311/testSend.swift
This is a simple improvement that didn't make it into the original PR of the two `cleartext-*` queries.  Removes some false positive results.
> Swift: Add encryption barriers to the two swift/cleartext-* queries

- javascript/ql/lib/semmle/javascript/security/dataflow/TypeConfusionThroughParameterTamperingQuery.qll
- javascript/ql/src/change-notes/2022-09-07-type-confusion-bugfix.md
- javascript/ql/test/query-tests/Security/CWE-843/TypeConfusionThroughParameterTampering.expected
- javascript/ql/test/query-tests/Security/CWE-843/tst.js
Fixes a bunch of issues with the TypeThroughThroughParameterTampering query:
- `Array.isArray` was incorrectly recognized (kudos to @erik-krogh for spotting that)
- We override `Configuration.isBarrier` without calling `super`, meaning that all barrier guards stop working. This footgun should really be fixed in general, but for now I'm just fixing the query.
- The test case was wrong. It used `req.query` as the source, which is always an object and can not itself be the cause of type confusion (only its properties can).
> JS: bugfixes in TypeThroughThroughParameterTampering

- javascript/ql/lib/semmle/javascript/security/dataflow/CodeInjectionCustomizations.qll
- javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/CodeInjection.expected
- javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/HeuristicSourceCodeInjection.expected
- javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/tst.js
Recognizes the sink for CVE-2022-36010
[Evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/spreadFunction__nightly-old__CustomSuite/reports).   
One new TP.
> JS: recognize calls to `Function` when spread arguments are used 

- ruby/ql/lib/codeql/ruby/ApiGraphs.qll
Computing this predicate in full can sometimes be expensive, so inline instead (like in JavaScript).
> Ruby: Inline `getAValueReachableFromSource`

- javascript/ql/lib/change-notes/2022-08-09-mermaid.md
- javascript/ql/lib/semmle/javascript/frameworks/Markdown.qll
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/UnsafeHtmlConstruction.expected
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/main.js
Recognizes the sink for CVE-2022-36036 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/mermaid__nightly-old__code-scanning/reports).
> JS: add a markdown step through the `mermaid` library

- cpp/ql/lib/experimental/semmle/code/cpp/semantic/analysis/RangeAnalysis.qll
We were getting a bad standard order in `unequalIntegralSsa`:
```ql
Evaluated relational algebra for predicate RangeAnalysis#5b9c51c9::unequalIntegralSsa#5#fffff@b4a4e4wt on iteration 178 running pipeline standard with tuple counts:
146327387   ~0%    {4} r1 = JOIN SemanticType#38838c10::SemUnsignedIntegerType::getByteSize#ff#join_rhs WITH RangeAnalysis#5b9c51c9::bounded#7#fffffff#reorder_3_0_1_2_4_5_6#prev ON FIRST 1 OUTPUT true, Rhs.1, Rhs.2, Rhs.3
0   ~0%    {3} r2 = JOIN r1 WITH RangeAnalysis#5b9c51c9::bounded#7#fffffff#reorder_3_0_1_2_4_5_6#prev_delta ON FIRST 4 OUTPUT Lhs.1, Lhs.2, Lhs.3
0   ~0%    {5} r3 = JOIN r2 WITH RangeAnalysis#5b9c51c9::unequalFlowStepIntegralSsa#5#fffff_20134#join_rhs ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Rhs.2, Rhs.4, (Lhs.2 + Rhs.3)
```
And due to the non-linear …
> C++: Avoid bad standard order in range analysis

- cpp/ql/lib/experimental/semmle/code/cpp/rangeanalysis/Bound.qll
- cpp/ql/lib/experimental/semmle/code/cpp/semantic/SemanticExprSpecific.qll
- cpp/ql/test/experimental/library-tests/rangeanalysis/rangeanalysis/RangeAnalysis.expected
The first argument to `idOf` was suggested by Dave.
Does this solve your problems, @rdmarsh2?
> C++: Don't use `getUniqueId` in range analysis

- cpp/ql/lib/change-notes/2022-09-08-implicit-read-flowstates.md
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking2/TaintTrackingImpl.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking2/TaintTrackingImpl.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking3/TaintTrackingImpl.qll
- csharp/ql/lib/change-notes/2022-09-08-implicit-read-flowstates.md
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking2/TaintTrackingImpl.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking3/TaintTrackingImpl.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking4/TaintTrackingImpl.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking5/TaintTrackingImpl.qll
- java/ql/lib/change-notes/2022-09-08-implicit-read-flowstates.md
- java/ql/lib/semmle/code/java/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
- java/ql/lib/semmle/code/java/dataflow/internal/tainttracking2/TaintTrackingImpl.qll
- java/ql/lib/semmle/code/java/dataflow/internal/tainttracking3/TaintTrackingImpl.qll
- java/ql/test/library-tests/dataflow/state/A.java
- java/ql/test/library-tests/dataflow/state/test.ql
- python/ql/lib/change-notes/2022-09-08-implicit-read-flowstates.md
- python/ql/lib/semmle/python/dataflow/new/internal/tainttracking1/TaintTrackingImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/tainttracking2/TaintTrackingImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/tainttracking3/TaintTrackingImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/tainttracking4/TaintTrackingImpl.qll
- ruby/ql/lib/change-notes/2022-09-08-implicit-read-flowstates.md
- ruby/ql/lib/codeql/ruby/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/tainttrackingforlibraries/TaintTrackingImpl.qll
- swift/ql/lib/codeql/swift/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
The first commit adds a test that fails because implicit reads weren't allowed in sinks or additional taint steps that used FlowStates.
The second commit fixes the issue.
> Dataflow: Fix implicit reads in taint tracking when FlowStates are used

- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPublic.qll
- python/ql/lib/semmle/python/dataflow/new/internal/ImportResolution.qll
- python/ql/lib/semmle/python/dataflow/new/internal/ImportStar.qll
Part 1: Moving the current logic into its own internal module. Hopefully this will make the PR that removes the dependence on points-to easier to review (and less likely to conflict with other changes).
> Python: Clean up module resolution

- javascript/ql/lib/semmle/javascript/NodeModuleResolutionImpl.qll
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/UnsafeHtmlConstruction.expected
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/lib/package.json
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/lib/src/MyNode.ts
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/lib2/index.ts
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/lib2/package.json
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/lib2/src/MyNode.ts
Gets a TP/TN for CVE-2022-36036.  
Recognizes files that aren't exported under the "." path as a "main module", if we can't find anything else.  
Also looks in all subfolders if we can't directly find the file.  
The basename must match, and both the file and the path are equally deep (and exactly one level down).   
This handles if e.g. Rollup moves the compiled files from one folder to another (e.g. `lib` or `dist`).  
---- 
[Evaluation looks OK. ](https://github.com/github/codeql-dca-main/blob/data/erik-krogh/moreMains__nightly-old__code-scanning__1/reports) 
There are 2 new resolved imports. One is an FP, but that's due to us not extracting the file that is supposed to be imported (I'll check that later).  
There are a bunch of new library-inputs, they seem reasonable.  
The new …
> JS: find a main module in more cases

- java/ql/lib/semmle/code/java/security/regexp/NfaUtils.qll
- javascript/ql/lib/semmle/javascript/security/regexp/NfaUtils.qll
- python/ql/lib/semmle/python/security/regexp/NfaUtils.qll
- ruby/ql/lib/codeql/ruby/security/regexp/NfaUtils.qll
I just learned that `class X instanceof Y {` inside a parameterized module is allowed.  
So now I'm using it.  
Evaluations were uneventful: [Ruby](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/paramClass-rb/reports), [Java](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/paramClass-java__1/reports), [Python](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/paramClass-py/reports), [JavaScript](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/paramClass-js/reports).
> ReDoS: convert RelevantState to a class in the PrefixConstruction module

- go/Makefile
- go/codeql-tools/linux64/compiler-tracing.spec
- go/codeql-tools/osx64/compiler-tracing.spec
- go/codeql-tools/win64/compiler-tracing.spec
These are not needed anymore, and from 2.11.0 on we will not ship a CLI that can read these files.
> Go: Remove the legacy tracer configuration files.

- cpp/ql/lib/semmle/code/cpp/pointsto/PointsTo.qll
We've wanted to replace the `PointsTo` library for a long time now, as it performs poorly on very large projects.  Unfortunately its still used in quite a few queries* so we can't get rid of it or even formally deprecate it.  But we've had external query developers try to use it, so I feel even just adding a warning to the library somewhere will be worthwhile.
`*` - `cpp/file-never-closed` and similar queries; a handful of queries that use `CallGraph.qll`; and a couple of `jsf` rules.  None of these queries are included in the normal query sets, so we actually have quite a lot to gain by modernizing them at some point.
> C++: Put a warning on the PointsTo library.

- python/ql/lib/change-notes/2022-09-12-deprecate-pointsto.md
- python/ql/lib/semmle/python/essa/SsaDefinitions.qll
- python/ql/lib/semmle/python/objects/TObject.qll
- python/ql/lib/semmle/python/pointsto/Base.qll
- python/ql/lib/semmle/python/pointsto/Filters.qll
- python/ql/lib/semmle/python/pointsto/PointsToContext.qll
- python/ql/lib/semmle/python/protocols.qll
I'm looking through some of the results of this yet-to-be-merged QL-for-QL query: https://github.com/github/codeql/pull/8454  
I know the Python teams wants to deprecate the points-to code, so I tried to see if I could deprecate some unused code in Python. 
No query/test depend on any of the code I've deprecated. 
There was some more code I initially tried to deprecate. However, it was being used in internal queries (that QL-for-QL can't see).
> PY: deprecate a bunch of unused code 

- javascript/ql/lib/semmle/javascript/security/dataflow/PrototypePollutingAssignmentQuery.qll
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/tst.js
Gets a TN for CVE-2020-28441
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/protoList__default__CustomSuite/reports).
> JS: recognize a list of bad strings as a sanitizer for `js/prototype-polluting-assignment`

- javascript/ql/lib/semmle/javascript/PackageExports.qll
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/lib.js
Gets a TP/FP for CVE-2020-28471
[Evaluation hints towards a performance regression](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/exportNew__nightly-old__code-scanning/reports).  
Which disappeared when I tried [the same evaluation single-threaded](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/exportNew-single-threaded/reports) 🤷
> JS: recognize returning an instance of a class as exporting that class

- swift/rules.bzl
- swift/tools/prebuilt/BUILD.bazel
Also remove the tentative way compilation was expected to be fixed on macOS ARM without really working.
In the future we will create universal binaries (which requires compiling our prebuilt package for ARM as well), but until then we must require the developer to pass `--cpu=darwin_x86_64` to the build command when building on an ARM macOS platform like the M1. This will be printed out explicitly now if it's not the case.
> Swift: print a helpful message on macOS ARM

- ruby/ql/lib/codeql/ruby/AST.qll
- ruby/ql/lib/codeql/ruby/ast/internal/Scope.qll
- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/methods.ql
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/modules.ql
- ruby/ql/test/library-tests/modules/modules.rb
- ruby/ql/test/library-tests/modules/superclasses.expected
In
```rb
class << x
...
end
```
the scope of `x` is not the singleton class itself, but rather the outer scope.
> Ruby: Adjust the scope of singleton class targets

- swift/rules.bzl
- swift/tools/prebuilt/BUILD.bazel
Reverts github/codeql#10399
This breaks bumping codeql on the internal repository. Some internal change is required to bring this back.
> Revert "Swift: print a helpful message on macOS ARM"

- java/ql/lib/semmle/code/java/security/OverlyLargeRangeQuery.qll
- javascript/ql/lib/semmle/javascript/security/OverlyLargeRangeQuery.qll
- javascript/ql/test/query-tests/Security/CWE-020/SuspiciousRegexpRange/tst.js
- python/ql/lib/semmle/python/security/OverlyLargeRangeQuery.qll
- ruby/ql/lib/codeql/ruby/security/OverlyLargeRangeQuery.qll
Fixes #10394
[Evaluation (JS) looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-10410-252394__nightly-old__CustomSuite/reports).  
Significantly better performance, and removal of a bunch of ranges that seem to purposely use unicode-chars.
> JS: don't report every non-ascii range in js/overly-large-range

- cpp/ql/src/Architecture/General Class-Level Information/HubClasses.ql
We are phasing our upper-case variable names: https://github.com/github/codeql-core/issues/2157
> remove upper-case variable name from `HubClasses`

- docs/codeql/codeql-cli/creating-codeql-query-suites.rst
- Add examples to filter on `@id`
- Add examples that include regexes
- Add examples that include both lists and single elements
- Add some `import` examples
- Remove mention of `eval` since it is not a user-facing instruction
A few things to note:
1. I do not have a good explanation of why you need `- exclude: {}` before an include instruction after a suite.
2. If there is a use case for someone to actually write an `eval` instruction, then I will add the deleted paragraph back and also create an example for it.
> Tweak the query suites documentation

- swift/ql/lib/qlpack.lock.yml
- swift/ql/src/qlpack.lock.yml
This fixes some existing CI failures in `main` around unresolved packages. Those failures still shouldn't have happened even without a lock file, but this will fix `main` while I investigate the underlying cause.
> Add lock files for Swift packs

- cpp/ql/src/Architecture/General Class-Level Information/InheritanceDepthDistribution.ql
- cpp/ql/src/Architecture/General Top-Level Information/GeneralStatistics.ql
- cpp/ql/src/Architecture/Refactoring Opportunities/ClassesWithManyDependencies.ql
- cpp/ql/src/Architecture/Refactoring Opportunities/ComplexFunctions.ql
- cpp/ql/src/Metrics/Namespaces/AbstractNamespaces.ql
- cpp/ql/src/Metrics/Namespaces/ConcreteNamespaces.ql
- cpp/ql/src/Metrics/Namespaces/HighAfferentCouplingNamespaces.ql
- cpp/ql/src/Metrics/Namespaces/HighDistanceFromMainLineNamespaces.ql
- cpp/ql/src/Metrics/Namespaces/HighEfferentCouplingNamespaces.ql
- cpp/ql/src/Metrics/Namespaces/StableNamespaces.ql
- cpp/ql/src/Metrics/Namespaces/UnstableNamespaces.ql
The previous problem (https://github.com/github/codeql/pull/10417) was apparently just hiding more.
> remove several upper-case `NamedExpression` variable names

- ruby/ql/lib/upgrades/4ba51641799d2aaa315c7323931e2dd2a94c9f9d/locations_default.ql
Before
```
Evaluated relational algebra for predicate #select#query#ffffff@3e1dedi5 with tuple counts:
30411461   ~0%    {6} r1 = locations_default AND NOT #select#query#ffffff#antijoin_rhs(Lhs.0, Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5)
30840645   ~4%    {2} r2 = SCAN #select#query#ffff OUTPUT In.0, In.3
515559   ~1%    {3} r3 = JOIN r2 WITH #select#query#ffffff#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Lhs.1
515559   ~0%    {5} r4 = JOIN r3 WITH locations_default ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Rhs.4, Rhs.5
2397708060   ~0%    {9} r5 = JOIN r4 WITH locations_default_1023#join_rhs ON FIRST 1 OUTPUT Lhs.1, 0, Rhs.1, Lhs.2, Lhs.0, Lhs.3, Lhs.4, Rhs.2, Rhs.3
515559   ~4%    {6} r6 = JOIN r5 WITH query#f0820431::body_statement#3#bff ON FIRST 3 OUTPUT Lhs.3, Lhs.4, Lhs.7, Lhs.8, Lhs.5, Lhs.6 …
```
> Ruby: Fix bad join-order in DB upgrade script

- java/ql/lib/change-notes/2022-09-06-notificationcompat-summaries.md
- java/ql/lib/semmle/code/java/frameworks/android/Notifications.qll
- java/ql/test/library-tests/frameworks/android/notification/Test.java
- java/ql/test/stubs/google-android-9.0.0/androidx/core/app/NotificationBuilderWithBuilderAccessor.java
- java/ql/test/stubs/google-android-9.0.0/androidx/core/app/NotificationCompat.java
- java/ql/test/stubs/google-android-9.0.0/androidx/core/app/RemoteInput.java
- java/ql/test/stubs/google-android-9.0.0/androidx/versionedparcelable/CustomVersionedParcelable.java
- java/ql/test/stubs/google-android-9.0.0/androidx/versionedparcelable/VersionedParcelable.java
Adds summaries for [`NotificationCompat`](https://developer.android.com/reference/androidx/core/app/NotificationCompat) ands its inner classes [`NotificationCompat$Builder`](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder), [`NotificationCompat$Action`](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Action), and [`NotificationCompat$Action$Builder`](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Action.Builder).
This adds coverage for CVE-2022-24886.
> Java: Add summaries for NotificationCompat and its inner classes

- java/ql/lib/change-notes/2022-09-07-implicit-pendingintents-compat-sinks.md
- java/ql/lib/semmle/code/java/security/ImplicitPendingIntents.qll
- java/ql/test/query-tests/security/CWE-927/ImplicitPendingIntentsTest.java
- java/ql/test/stubs/google-android-9.0.0/android/app/AppComponentFactory.java
- java/ql/test/stubs/google-android-9.0.0/android/app/AutomaticZenRule.java
- java/ql/test/stubs/google-android-9.0.0/android/service/notification/Condition.java
- java/ql/test/stubs/google-android-9.0.0/android/service/notification/StatusBarNotification.java
- java/ql/test/stubs/google-android-9.0.0/android/service/notification/ZenPolicy.java
- java/ql/test/stubs/google-android-9.0.0/androidx/core/app/AlarmManagerCompat.java
- java/ql/test/stubs/google-android-9.0.0/androidx/core/app/CoreComponentFactory.java
- java/ql/test/stubs/google-android-9.0.0/androidx/core/app/NotificationManagerCompat.java
- java/ql/test/stubs/google-android-9.0.0/androidx/remotecallback/CallbackReceiver.java
- java/ql/test/stubs/google-android-9.0.0/androidx/slice/Clock.java
- java/ql/test/stubs/google-android-9.0.0/androidx/slice/builders/impl/TemplateBuilderImpl.java
- java/ql/test/stubs/google-android-9.0.0/androidx/slice/compat/CompatPermissionManager.java
Following #10318, this PR adds sinks related to Compat classes (`androidx.core.app.{Notification,Alarm}ManagerCompat`) to the Implicit PendingIntents query.
> Java: Add Implicit PendingIntents sinks for Compat classes

- cpp/ql/src/Architecture/General Class-Level Information/HubClasses.ql
- cpp/ql/src/PointsTo/TaintedFormatStrings.ql
This builds on https://github.com/github/codeql/pull/10420, apologies for not spotting all of these at once!
> C++: remove more upper-case variable names

- java/ql/src/Architecture/Refactoring Opportunities/HubClasses.ql
Upper-case variable names are deprecated. Warnings were not correctly displayed for `NamedExpressions`, hence we missed some occurrences.
> Java: remove upper-case variable name

- javascript/ql/src/meta/extraction-metrics/FileData.ql
- javascript/ql/src/meta/extraction-metrics/PhaseTimings.ql
Upper-case variable names are deprecated. Warnings were not correctly displayed for `NamedExpressions`, hence we missed some occurrences.
> JavaScript: remove upper-case variable names

- ql/ql/src/codeql_ql/style/NodeName.qll
We were missing the results that were fixed in e.g. https://github.com/github/codeql/pull/10439.  
All the errors that Code-scanning complains about are fixed by the above PR.
> QL: recognize the names from all VarDefs

- docs/codeql/reusables/download-github-database.rst
We have an incorrect link in a reusable snippet about downloading CodeQL databases using the GitHub REST API. The link should point to https://docs.github.com/en/rest/code-scanning#get-a-codeql-database-for-a-repository.
> Correct link to API docs for 'Get a CodeQL database for a repository'

- docs/ql-design-patterns.md
Had to change the example away from Go, since their libs have not been
updated to use `instanceof` yet (but I'll make a PR from them shortly)
> Docs: Use `instanceof` in `::Range` pattern description

- swift/ql/test/query-tests/Security/CWE-311/testURL.swift
Update the test for `swift/cleartext-transmission`.  I thought we were missing taint to the result on line 21 for some reason, but it turns out this is just result deduplication - we don't allow taint flow through taint sinks because that can lead to reporting the same issue a silly number of times.  In this case the sink on line 20 for the sensitive data `passwd` is reported.
> Swift: Update test for swift/cleartext-transmission

- docs/codeql/ql-language-reference/ql-language-specification.rst
- Remove references to `queries.xml`. It is still supported, but we don't want people using it.
- Add reference to `codeql-pack.yml`. It is just an alias for `qlpack.yml` and not being used.
- Remove reference to `libraryPathDependencies` and use `dependencies` instead.
Note that this section does not give a complete description of library paths. That will be a part of the "Developing a codeql pack" article that is forthcoming.
> Updates the library path section of the CodeQL spec

- javascript/ql/src/RegExp/RegExpAlwaysMatches.ql
- javascript/ql/src/change-notes/2022-09-13-regexp-always-matches-fp.md
- javascript/ql/test/query-tests/RegExp/RegExpAlwaysMatches/RegExpAlwaysMatches.expected
- javascript/ql/test/query-tests/RegExp/RegExpAlwaysMatches/tst.js
I noticed some FPs in vscode while investigating a timeout.
This query is not currently tagged as a security query, but it's one of those queries that could be security relevant in some contexts, so it's worth maintaining a low FP rate for it.
> JS: Fix FP in js/regexp/always-matches

- python/ql/lib/change-notes/2022-09-12-CallNode-getArgByName.md
- python/ql/lib/semmle/python/Flow.qll
- python/ql/test/experimental/dataflow/coverage/argumentPassing.py
I was rather surprised when I learned we don't allow this currently. I think this is a minor thing, as it's not a very common pattern to pass your arguments like this, but no reason we shouldn't handle this correctly.
see https://github.com/github/codeql/blob/1c15fc5600c0a566c1938f6a4c84319a6bb0eba3/python/ql/lib/semmle/python/Exprs.qll#L185-L197
We might want to consider deprecating or changing `getKeyword`/`getAKeyword` on the AST `Call` class.
> Python: Allow `CallNode.getArgByName` for keyword args after `**kwargs`

- csharp/tools/tracing-config.lua
It turns out that the current solution for `dotnet run` doesn't work as intended, so removing the support altogether.
If we want support for `dotnet run` it is not sufficient to prepend or append to the compiler argument list (we basically need to 'inject' in the middle of the provided arguments).
From the description of [dotnet run](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-run) we see that everything after `--` is provided as command line arguments to the program.
This means that the LUA tracer will re-write
```bash
dotnet run -- hello
```
into
```bash
dotnet run -- hello -p:UseSharedCompilation=false
```
That is, the shared compilation flag is injected as a program input.
If we want proper support for `dotnet run` we need to rewrite the command line arguments and …
> C#: Remove `dotnet run` support in LUA tracer.

- java/ql/lib/semmle/code/Location.qll
This was always supposed to pick one of several candidate non-source locations (usually for a generic type instantiation), but since `getFile().toString()` just produces the basename of the class file actually the results would almost always tie and all of the candidate locations would be returned. Use the full class file path as a tiebreaker instead.
> Java: really return a unique location for non-source entities

- go/ql/lib/semmle/go/security/InsecureRandomness.qll
- go/ql/lib/semmle/go/security/Xss.qll
The `Sanitizer` class in `insecure-randomness` was never used. The fix was to add a `isSanitizer()` predicate to the configuration.  
The `Source` class for the `Xss` classes was never used.  
This class isn't useful with the current queries, so I've deprecated it.  
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-10475-0-go/reports)
> Go: Fix source/sanitizer class that were never used 

- javascript/ql/src/Security/CWE-367/FileSystemRace.ql
- javascript/ql/test/query-tests/Security/CWE-367/tst.js
[Evaluation shows that a bunch of benign results got removed](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-10471-fb5a04__nightly-old__CustomSuite/reports).  
And that was the point of this PR.
> JS: filter out "file read after existence check" from js/file-system-race

- swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.ql
- swift/ql/test/query-tests/Security/CWE-311/CleartextStorageDatabase.expected
- swift/ql/test/query-tests/Security/CWE-311/SensitiveExprs.expected
- swift/ql/test/query-tests/Security/CWE-311/testRealm.swift
Fix missing results in `swift/cleartext-storage-database`.  This is something of a change in philosophy, that any write to a class derived from `RealmSwiftObject` (i.e. something that is to be use with a Realm database) is now considered a sink.  We no longer look for evidence (that we may or may not reliably find) that the `RealmSwiftObject` is truly written to the database, because why would it not be?
> Swift: Fix missing results in swift/cleartext-storage-database

- ruby/ql/consistency-queries/DataFlowConsistency.ql
- ruby/ql/lib/codeql/ruby/ast/internal/Module.qll
- ruby/ql/lib/codeql/ruby/controlflow/BasicBlocks.qll
- ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll
- ruby/ql/lib/codeql/ruby/controlflow/ControlFlowGraph.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
- ruby/ql/test/library-tests/dataflow/global/Flow.expected
- ruby/ql/test/library-tests/dataflow/global/instance_variables.rb
- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/calls.rb
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/superclasses.expected
This PR rewrites the call graph computation in the following ways:
1. Remove temporary fix for `require` and `require_relative` methods.
2. No longer resolve instance methods based on flow through `self` (closed-world assumption); instead rely on the type hierarchy, and allow dispatch to any overrides (open-world assumption), as long as the type is not known exactly (such as when constructed with `new`).
3. Improve precision for singleton methods defined on objects, such as `def x.foo; end`, by taking overriding redefinitions into account:
```rb
def x.foo; end
def x.foo; end
x.foo # now only resolves to the latter definition
```
5. Add missing call targets for singleton methods defined on parameters (including `self`):
```rb
def add_singleton x
def x.singleton; end
end
add_singleton y …
```
> Ruby: Rework call graph implementation

- python/ql/lib/change-notes/2022-09-12-getStarArg-first.md
- python/ql/lib/semmle/python/Exprs.qll
- python/ql/lib/semmle/python/Flow.qll
Besides my intended use in the new call-graph PR, these member-predicates only seems to be used in this part of points-to:
https://github.com/github/codeql/blob/2436b060f1a330b02f333bf99d716bff1f02f0da/python/ql/lib/semmle/python/pointsto/PointsTo.qll#L1142-L1167
I couldn't see any reason that we should give up altogether if there are multiple `*args` arguments. Including the first one looks like a win to me!
> Python: `getStarArg` gives first `*args` argument

- python/ql/test/query-tests/Security/CWE-022-TarSlip/TarSlip.expected
- python/ql/test/query-tests/Security/CWE-022-TarSlip/tarslip.py
This doesn't change results, but makes the test-code more valid
> Python: Fix imports for tarslip tests

- ruby/ql/lib/codeql/ruby/ast/internal/Module.qll
Before
```
Evaluated relational algebra for predicate Module#fe82a56b::lookupMethodOrConst0#2#fff#antijoin_rhs@e23c32nf with tuple counts:
118006   ~0%    {3} r1 = SCAN Module#fe82a56b::getMethodOrConst#2#fff OUTPUT In.1, In.0, In.2
35267848   ~3%    {4} r2 = JOIN r1 WITH project#Module#fe82a56b::getMethodOrConst#2#fff_10#join_rhs ON FIRST 1 OUTPUT Lhs.1, Lhs.0, Lhs.2, Rhs.1
21883   ~0%    {5} r3 = JOIN r2 WITH Module#fe82a56b::Cached::getAPrependedModule#1#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.3, Lhs.0, Lhs.1, Lhs.2
7  ~16%    {3} r4 = JOIN r3 WITH Module#fe82a56b::getAncestors#1#ff ON FIRST 2 OUTPUT Lhs.2, Lhs.3, Lhs.4
return r4
```
After
```
Evaluated relational algebra for predicate Module#fe82a56b::lookupMethodOrConst0#2#fff#antijoin_rhs@839f6a1k with tuple counts:
118006  ~1%    {3} r1 = …
```
> Ruby: Fix bad join-order

- swift/codegen/generators/cppgen.py
- swift/codegen/generators/qlgen.py
- swift/codegen/lib/schema.py
- swift/codegen/test/test_cppgen.py
- swift/codegen/test/test_qlgen.py
- swift/ql/lib/codeql/swift/generated/ParentChild.qll
- swift/ql/lib/codeql/swift/generated/Raw.qll
- swift/ql/lib/swift.dbscheme
This makes the result of code generation independent of the order in which classes are defined in the schema, and makes additional topological sorting not required.
Being independent from schema order will be important for reviewing the move to a pure python schema, as generated code will be left untouched.
In this PR the changes to the generated code is only about order. The topological sorting used takes into account the directory grouping (so that for example all `Expr` get bunched together) which was not the case before, hence the order difference.
> Swift: move toposort in `schema.py`

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/kotlin-extractor/src/main/kotlin/utils/Logger.kt
This issue seems to be specific to IR that's produced by some plugins, I couldn't find a way to test it.
> Kotlin: Catch exception thrown by kotlinc

- ql/ql/src/codeql_ql/ast/Ast.qll
- ql/ql/src/queries/style/AlertMessage.ql
Each commit should describe itself. 
The `getASubExpression` predicate was outlined to try and improve a bad join-order 
I wasn't that succesful in improving the join-order, there is still a query specific predicate that takes ~7s on my machine.   
But there are still a few other queries that are slower, so it shouldn't affect the total runtime that much. 
These improvements finds ~~97~~ 181 more violations (see the code-scanning results).  
I'll look at fixing these in other PRs. E.g. [this upcoming one for C++](https://github.com/github/codeql/pull/10507).
> QL: improve the `ql/alert-message-style-violation` query. 

- ruby/ql/lib/codeql/ruby/Regexp.qll
- ruby/ql/lib/codeql/ruby/regexp/internal/DebugRegExpConfiguration.ql
- ruby/ql/lib/codeql/ruby/regexp/internal/RegExpConfiguration.qll
It is often convenient to be able to debug flow from `RegExpConfiguration`, so this PR adds a debug query for doing just that.
> Ruby: Add query for debugging regexp flow

- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowImplConsistency.qll
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplConsistency.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplConsistency.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplConsistency.qll
- docs/ql-libraries/dataflow/dataflow.md
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplConsistency.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplConsistency.qll
- ruby/ql/consistency-queries/DataFlowConsistency.ql
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplConsistency.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/test/library-tests/dataflow/global/Flow.expected
- ruby/ql/test/library-tests/dataflow/global/instance_variables.rb
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplConsistency.qll
Post-update nodes are used to enable flow out through arguments:
```rb
def taint_field x
x.field = "taint"
end
taint_field(y)
sink(y.field)
```
There is flow from "taint" to the field `field` on post-update node for `y` in the call to `taint_field`, written `(post) y [field]`, and from `(post) y [field]` in the call to `taint_field` to `y [field]` in the call to `sink`, and finally to `y.field` in the call to `sink`. 
However, when the argument is a compound expression, such as
```rb
taint_field(if b then x else y)
sink(y.field)
```
we fail to track flow, since there is no connection between `(post) if b then x else y` and the access to `y` in `sink(y.field)`.
This PR fixes that, by also adding post-update nodes for `x` and `y` in `if b then x else y`, and let those nodes have *two* …
> Ruby: Add post-update nodes for compound arguments

- java/ql/lib/semmle/code/java/controlflow/Guards.qll
- java/ql/lib/semmle/code/java/security/regexp/NfaUtilsSpecific.qll
- java/ql/src/Violations of Best Practice/Naming Conventions/Shadowing.qll
- The unused predicate in `NfaUtilsSpecific.qll` was not used anywhere, and people are not expected to use predicates from a `Specific.qll` file.  
- The `guardControls_v2` predicate in `Guards.qll` was only ever called by itself, and it was documented as being internal, so I deprecated it.  
- The `initializedToField` predicate was unused. It was in the `src/` folder, and it couldn't be imported from the outside, so I deleted it.
> Java: Delete some unused code

- ruby/ql/lib/codeql/ruby/ast/Constant.qll
- ruby/ql/lib/codeql/ruby/experimental/Rbi.qll
- ruby/ql/test/library-tests/experimental/Rbi.ql
These changes are mostly in service of better parameter type modelling - they should make more sense in the context of the models-as-data manager PR for a Ruby typegraph implementation.
> Ruby: RBI library changes to support models-as-data model generation

- ql/ql/src/codeql/GlobalValueNumbering.qll
- ql/ql/src/queries/style/AlertMessage.ql
`don't repeat the alert-location as a link` is not currently part of the style guide, and I don't think it needs to be.  
(It's covered under: Keep the message concise).  
I tried to use GVN when I created [don't repeat the alert-location as a link](https://github.com/github/codeql/commit/76fef28c32eef22346f3c417ba55e9f45c5c8048).  
But that seemed to run into an infinite loop (I stopped it after ~100.000 iterations).  
/cc @MathiasVP
> QL: A few more improvements to `ql/alert-message-style-violation`

- docs/codeql/codeql-cli/about-codeql-packs.rst
Makes table easier to read. As discussed with @felicitymay.
Note that there are still a few internal properties that are used in our core packs, but I am not mentioning (eg- `groups`, `mlModels`). These are internal use only and I didn't want to clutter the descriptions with these extra properties.
> Update qlpack properties descriptions

- csharp/ql/lib/semmle/code/csharp/dataflow/ExternalFlow.qll
The original solution joined on Callable and elementSpec based on name, which lead to a quite large intermediate relation.
The tuples counts in all the screenshots below are based on the *rappayne_webgoat* database.
The tuple counts for the original solution can be seen here:
To improve the join ordering and to keep the intermediate relations as small as possible, we use the following observations
- When we want to use *specific* specs (ie. a spec that directly targets a callable), we would like to join Callable and elementSpec on three columns in one go (namespace, type and name).
- When we want to use specs that are valid for all overrides (subtypes = true), we need project the elementSpec relation (on subtypes = true as this is relatively small subset) and join on Callable name. …
> C#: Fix join order in InterpretedCallable characteristic predicate.

- cpp/ql/lib/experimental/semmle/code/cpp/semantic/SemanticExprSpecific.qll
- cpp/ql/lib/experimental/semmle/code/cpp/semantic/SemanticSSA.qll
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp
This PR adds bounds for the following case:
```ql
void foo(char* p, unsigned index, char* end) {
if(p + index < end) {
use(*(p + index)); // <-- In here we now know that `p + index` is bounded by `end`
}
}
```
This is motivated by [CVE-2016-10160](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-10160), and the first commit adds a reduced version of that vulnerability (and indeed after this PR we correctly identify this CVE).
The reason we didn't find the issue in the first commit is as follows:
Currently, on `main`, the range-analysis library didn't spot that the pointer-arithmetic expression `p + index` in the `p + index > end` guard is identical to the one being used for the store operation in `p[index] = '\0'`, and so we didn't realize that there's an off-by-one error here.
In …
> C++: Fix missing bounds in range analysis

- docs/codeql/codeql-cli/creating-codeql-databases.rst
- docs/codeql/support/reusables/versions-compilers.rst
Minor updates to the documentation to reflect our recommendation to use Python 3 to run the CodeQL extractor for Python analysis.
> Minor updates to reflect recommendations for Python support

- swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql
- swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.expected
- swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.swift
Fix the recent regression in `swift/string-length-conflation`.  It appears to have been caused by the 2nd parameter of `index(_:offsetBy:)` being renamed from `n` to `distance`.  *Hopefully* this kind of thing won't be too common, or we might have to change our strategy a little.
> Swift: fix regression.

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/ql/test/kotlin/library-tests/annotation-accessor-result-type/PrintAst.expected
- java/ql/test/kotlin/library-tests/annotation-accessor-result-type/PrintAst.qlref
- java/ql/test/kotlin/library-tests/annotation-accessor-result-type/test.expected
- java/ql/test/kotlin/library-tests/annotation-accessor-result-type/test.kt
- java/ql/test/kotlin/library-tests/annotation-accessor-result-type/test.ql
As documented at https://kotlinlang.org/docs/annotations.html#constructors, annotation properties of type KClass get rewritten when targeting the JVM.
> Kotlin: annotation properties should be java.lang.Class not KClass

- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/calls.rb
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/superclasses.expected
This PR documents some (corner) cases that our call graph construction currently doesn't handle.
> Ruby: Add call graph tests for unsupported constructs

- java/ql/lib/semmle/code/java/security/StaticInitializationVectorQuery.qll
As the comment suggests, it looks like `ArrayUpdateConfig` was meant to be value flow rather than taint flow, and this makes a big performance difference. Also, since we don't car about specific sinks, we might as well add an out-barrier on sinks for a little bit of added performance.
> Java: Improve performance of StaticInitializationVector.

- ruby/ql/lib/codeql/ruby/ast/Module.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.ql
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
This PR implements call-sensitive instance method resolution, using [the data-flow library's built-in support](https://github.com/github/codeql/blob/main/docs/ql-libraries/dataflow/dataflow.md#virtual-dispatch-with-call-context).
For example, in
```rb
class A
def method1 x
sink x
end
def method2 x
method1 x
end
end
class B < A
def method1 x
non_sink x
end
end
B.new.method2(taint)
```
we will no longer report flow from `taint` to `sink` (but still to `non_sink`).
> Ruby: Context sensitive instance method resolution

- cpp/ql/lib/semmle/code/cpp/commons/Strcat.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/internal/SSAConstruction.qll
- cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/IRConstruction.qll
- cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SSAConstruction.qll
- cpp/ql/src/Best Practices/Magic Constants/MagicConstants.qll
- cpp/ql/src/Security/CWE/CWE-457/UninitializedVariables.qll
- csharp/ql/src/experimental/ir/implementation/unaliased_ssa/internal/SSAConstruction.qll
I'm looking through some of the results of this yet-to-be-merged QL-for-QL query: https://github.com/github/codeql/pull/8454.  
The code I've deleted/deprecated are not used by any query (including test queries).  
You got plenty of unused code in public libraries (for completeness I assume). I haven't touched those.  
C# is included because of a shared SSA file.
> C: deprecate/delete some unused code 

- csharp/ql/lib/semmle/code/csharp/dataflow/internal/CallableReturns.qll
- csharp/ql/lib/semmle/code/csharp/security/cryptography/EncryptionKeyDataFlowQuery.qll
I'm looking through some of the results of this yet-to-be-merged QL-for-QL query: https://github.com/github/codeql/pull/8454.  
The code I've deleted/deprecated is not used by any query (including test queries).  
You got plenty of unused code in public libraries (for completeness I assume). I haven't touched those.
> C#: deprecate/delete some unused code

- cpp/ql/lib/experimental/semmle/code/cpp/dataflow/ProductFlow.qll
- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp
It's super difficult to properly fix the FP I added in https://github.com/github/codeql/pull/10572. So for now I've decided to just block all flow through back-edges of phi nodes (as suggested by `@aschackmull`) since this one _one_ of the things that had to be present in order to get an FP here.
> C++: Fix FPs on `cpp/invalid-pointer-deref`

- docs/ql-libraries/dataflow/dataflow.md
- ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
- ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll
- ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll
- ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected
- ruby/ql/test/library-tests/dataflow/array-flow/array_flow.rb
- ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
- ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql
- ruby/ql/test/library-tests/dataflow/summaries/summaries.rb
Commit-by-commit review is encouraged.
In Ruby, reads with known indices, such as
```rb
a[0]
```
give rise to two read steps; one that reads `TSingletonContent(TKnownElementContent(0))` and one that reads `TSingletonContent(TUnknownElementContent())` (if data is stored at an unknown index, it _might_ be `0`).
Since `[]` is just a method call, it means we have two flow summaries for `[]`:
```
Argument[self].Argument[0] -> ReturnValue
Argument[self].Argument[?] -> ReturnValue
```
This works well for reads, however for [reverse stores](https://github.com/github/codeql/blob/main/docs/ql-libraries/dataflow/dataflow.md#example-2)
```rb
a[0][1] = x
```
it means that we will get store steps into `a` with both `TSingletonContent(TKnownElementContent(0))` and …
> Ruby: Fix spurious flow through reverse stores

- java/ql/lib/change-notes/2022-09-20-CompilationUnit-getATypeInScope.md
- java/ql/lib/change-notes/2022-09-20-CompilationUnit-simple-name-type.md
- java/ql/lib/semmle/code/java/CompilationUnit.qll
- java/ql/src/Advisory/Documentation/ImpossibleJavadocThrows.ql
- java/ql/test/query-tests/Javadoc/ImpossibleJavadocThrows.expected
- java/ql/test/query-tests/Javadoc/ImpossibleJavadocThrows.java
This predicate is mainly helpful for Javadoc queries and for queries which check whether the name of an element shadows another type.
Resolves #4119
It makes probably most sense to implement the logic requested there for `CompilationUnit`, as done in this PR because there it is also possible to account for shadowing between different kinds of imports (though this is currently not implemented by this PR).
This PR is a bit experimental and does not have a dedicated test; feedback is appreciated.
> Java: Add `CompilationUnit.getATypeInScope()`

- ql/ql/src/codeql_ql/style/AcronymsShouldBeCamelCaseQuery.qll
- ql/ql/src/qlpack.yml
`getURL` is a language feature, so it should be allowed as an upper-case acronym.
> QL: allow getURL as an acronym

- ql/ql/src/codeql_ql/ast/internal/Module.qll
- ql/ql/src/codeql_ql/ast/internal/Predicate.qll
- ql/ql/src/queries/diagnostics/EmptyConsistencies.ql
The query was starting to get noisy on e.g. https://github.com/github/codeql/pull/10592 
With these changes the query reports nothing on `main` (and nothing on the PR above).
> QL: adjust the consistency query to not be noisy on parameterised modules

- javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll
- python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModels.qll
- ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModels.qll
- ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
- ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql
- ruby/ql/test/library-tests/dataflow/summaries/summaries.rb
Adds `TypeModel.getAnApiNode`. This allows contributing to a type definition when we already have an API node at hand. 
The existing predicates, `getSource` and `getSink`, contribute entry points to ensure an API node is going to exist, but must these can not themselves depend on API graphs.
> Add TypeModel.getAnApiNode

- cpp/ql/lib/experimental/semmle/code/cpp/dataflow/ProductFlow.qll
- cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.cpp
- cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.qhelp
- cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.ql
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/OverrunWriteProductFlow.expected
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/test.cpp
We merged https://github.com/github/codeql/pull/10398 before we really finished off the `OverrunWriteProductFlow.ql` query. In particular:
- Its tests weren't all annotated.
- It was highlighting any flow from an `(allocation, size)` pair to an `ArrayFunction` operation regardless of whether the operation was dangerous or not.
- It was missing metadata and qhelp.
This PR fixed all of those rings. Commit-by-commit review is encouraged:
- https://github.com/github/codeql/commit/51758aa928113d810acf72269b07f2d1c0cf3770 adds more tests and adds annotations.
- https://github.com/github/codeql/commit/ccbbb5754e78b809133b69d6f18657ad696d9d08 does the majority of the work of this PR: it turns the query into a query that's finding vulnerabilities instead of being a testing query for the …
> C++: Make `OverrunWriteProductFlow` raise alerts on overflows

- python/ql/lib/change-notes/2022-09-28-api-subscript.md
- python/ql/lib/semmle/python/ApiGraphs.qll
- python/ql/lib/semmle/python/dataflow/new/internal/LocalSources.qll
- python/ql/lib/semmle/python/frameworks/Flask.qll
- python/ql/lib/semmle/python/frameworks/Stdlib.qll
- python/ql/src/experimental/semmle/python/frameworks/Django.qll
- python/ql/src/experimental/semmle/python/frameworks/NoSQL.qll
This is currently a draft that should allow us to discuss the following questions:
- does the resulting user code look as nice as we hoped?
- do we need the ability to refer to object and index? (I believe an `API::SubscriptNode` similar to `API::CallNode` could solve this.)
- does this design interfere with plans to harmonise implementations across languages? (Currently no)
- should the access path be `getItem` rather than `getSubscript`? Especially if we add the option to to say `getItem("cookie")`.
> Python: add subscript to API graphs

- csharp/ql/consistency-queries/DataFlowConsistency.ql
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
- csharp/ql/test/library-tests/dataflow/global/DataFlow.expected
- csharp/ql/test/library-tests/dataflow/global/DataFlowPath.expected
- csharp/ql/test/library-tests/dataflow/global/GetAnOutNode.expected
- csharp/ql/test/library-tests/dataflow/global/GlobalDataFlow.cs
- csharp/ql/test/library-tests/dataflow/global/TaintTracking.expected
- csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.expected
- csharp/ql/test/library-tests/dataflow/local/DataFlowStep.expected
- csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected
This is the C# version of: https://github.com/github/codeql/pull/10444
That is, we can now identify flow out through arguments where expressions are inlined.
Assume we have
```csharp
public class SimpleClass
{
public string field = "";
}
public void TaintField(SimpleClass sc)
{
sc.field = "taint source";
}
```
then flow out via `x` and `y` are tracked correctly in the following pseudo example.
```csharp
SimpleClass x = ...
SimpleClass y = ...
TaintField(b ? x : y);
Sink(x.field);
Sink(y.field);
``` 
Furthermore, we also track flow out of expressions like
```csharp
TaintField((SimpleClass)x) // Cast expressions
TaintField(x ?? y) // Null Coalescing expressions
TaintField(x!) // Suppress nullable warning expressions
TaintField(y = x) // Assignment expressions
TaintField(choice switch "x" => …
```
> C#: Postupdate notes for ternary expressions.

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/test/library-tests/dataflow/global/Flow.expected
- ruby/ql/test/library-tests/dataflow/global/instance_variables.rb
This is a follow up of https://github.com/github/codeql/pull/10444
There is flow from "taint" to the field `field` on post-update node for `x` in the call to `taint_field`.
```ruby
def taint_field x
x.field = "taint"
end
taint_field(y = x)
sink(x.field)
```
> Ruby: Postupdate notes for assignment expressions.

- javascript/ql/lib/semmle/javascript/security/SensitiveActions.qll
- javascript/ql/test/query-tests/Security/CWE-798/HardcodedCredentials.expected
- javascript/ql/test/query-tests/Security/CWE-798/HardcodedCredentials.js
First I spent some time learning how backreferences work in regular expressions. 
Then I wrote `repeats the same char more than 10 times` in a comment. 
Then Copilot wrote the entire implementation..... 
There were a whole bunch of FPs in https://github.com/octokit/octokit-next.js/ that are fixed by this PR.  
[Evaluation was unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-10636-0a5ff1__nightly-old__CustomSuite/reports)
> JS: recognize another kind of dummy passwords to fix an FP in hardcoded-credentials

- java/kotlin-extractor/src/main/java/com/semmle/extractor/java/OdasaOutput.java
"0.0 last-modified 0" and "0.0 last-modified 123" were giving different comparisons depending on which way round they were.
> Kotlin: Make newerThan symmetric

- .github/workflows/qhelp-pr-preview.yml
[Here’s an example](https://github.com/github/codeql/pull/10008#issuecomment-1210861535) of a qhelp preview that the workflow generates. 
If you don't want this for your language then please speak up before this is merged. You can always opt-out later with a paths-ignore property if needed.
> Run QLHelp preview for all languages

- ruby/ql/lib/codeql/ruby/ast/internal/Synthesis.qll
Before, we would be recursive in all of `MethodCall::getMethodName`:
```
Evaluated named local Synthesis#d9ff06b1::AssignOperationDesugar::SetterAssignOperation::getCallKind#ffff#shared#3@Synthesi in 9803ms on iteration 14 (size: 31006941).
Evaluated relational algebra for predicate Synthesis#d9ff06b1::AssignOperationDesugar::SetterAssignOperation::getCallKind#ffff#shared#3@Synthesi on iteration 14 running pipeline main with tuple counts:
256419  ~1%    {2} r1 = SCAN Call#841c84e8::MethodCall::getMethodName#0#dispred#ff#prev_delta OUTPUT In.1, In.0
31006941  ~8%    {4} r2 = JOIN r1 WITH Synthesis#d9ff06b1::MethodCallKind#ffff#prev ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Rhs.2, Rhs.3
return r2
```
Now, we have restricted that to be only the relevant method names.
> Ruby: Reduce size of input predicate for non-linear recursion

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/calls.rb
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/superclasses.expected
https://github.com/github/codeql/pull/10002 follow-up.
> Ruby: Account for `protected` methods in call graph

- ruby/ql/lib/change-notes/2022-09-23-yaml-load-file.md
- ruby/ql/lib/codeql/ruby/security/UnsafeDeserializationCustomizations.qll
- ruby/ql/test/query-tests/security/cwe-502/unsafe-deserialization/UnsafeDeserialization.expected
- ruby/ql/test/query-tests/security/cwe-502/unsafe-deserialization/UnsafeDeserialization.rb
In semi-recent versions of ruby the `YAML` module is an alias of `Psych`.
https://ruby-doc.com/stdlib-3.0.1/libdoc/yaml/rdoc/YAML.html
> Ruby: treat `Psych` and `YAML` as aliases for rb/unsafe-deserialization

- java/ql/src/Advisory/Documentation/ImpossibleJavadocThrows.ql
Fixes a cartesian product in the `canThrow` predicate, where `callable` wasn't bound in one side of the disjunct.
> Java: Fix cartesian product

- ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
- ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected
- ruby/ql/test/library-tests/dataflow/array-flow/array_flow.rb
As pointed out by @asgerf, the inherent imprecision when comparing floats (and complex numbers) makes them unsuitable for tracking precise hash index information. We therefore simply treat reads and stores with float/complex indices as unknown indices.
> Ruby: Do not attempt to track precise hash indices for floats and complex numbers

- python/ql/test/query-tests/Security/CWE-078-CommandInjection/options
- python/ql/test/query-tests/Security/CWE-079-Jinja2WithoutEscaping/options
- python/ql/test/query-tests/Security/CWE-209-StackTraceExposure/options
- python/ql/test/query-tests/Security/CWE-215-FlaskDebug/options
- python/ql/test/query-tests/Security/CWE-327-InsecureProtocol/options
- python/ql/test/query-tests/Security/CWE-601-UrlRedirect/options
- python/ql/test/query-tests/Security/CWE-732-WeakFilePermissions/options
These were only needed for points-to.
If they only contained `--max-import-depth`, I've removed the `options` file entirely.
> Python: Remove last `-p ../lib/` in `options` files

- javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll
- python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModels.qll
- ruby/ql/lib/codeql/ruby/ApiGraphs.qll
- ruby/ql/lib/codeql/ruby/ast/Constant.qll
- ruby/ql/lib/codeql/ruby/ast/Module.qll
- ruby/ql/lib/codeql/ruby/ast/internal/Module.qll
- ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll
- ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll
- ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll
- ruby/ql/lib/codeql/ruby/frameworks/ActiveResource.qll
- ruby/ql/lib/codeql/ruby/frameworks/GraphQL.qll
- ruby/ql/lib/codeql/ruby/frameworks/Rails.qll
- ruby/ql/lib/codeql/ruby/frameworks/Railties.qll
- ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModels.qll
- ruby/ql/src/queries/analysis/Definitions.ql
- ruby/ql/test/library-tests/modules/modules.ql
The effect of these changes was not quite what I had hoped for, presumably because the evaluator automatically avoids recomputing some of the expensive predicates during whole-suite evaluation. But it does make up for some of the slow-down on `gitlabhq` reported on https://github.com/github/codeql/pull/10090.
I also think the changes are worthwhile, because we are guaranteed to not reevaluate the predicates during interactive execution in VS Code.
> Ruby: Prevent reevaluation of expensive predicates

- java/ql/src/utils/stub-generator/Stubs.qll
- java/ql/test/query-tests/Stubs/Minimal/MinimalStubsFromSource.expected
Add line break after all stubbed annotations to avoid malformed code
See https://github.com/github/codeql/pull/8695\#discussion_r985674245
> Java: Fix stub generator

- cpp/ql/lib/experimental/semmle/code/cpp/dataflow/ProductFlow.qll
- cpp/ql/lib/semmle/code/cpp/models/implementations/Allocation.qll
- cpp/ql/lib/semmle/code/cpp/models/interfaces/Allocation.qll
- cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql
This PR does two things:
- It adds a couple of new interface classes, `HeuristicAllocationExpr` and `HeuristicAllocationFunction`, that complement the already existing `AllocationExpr` and `HeuristicAllocation` classes with functions that we think may perform allocations.
- It switched the new `cpp/invalid-pointer-deref` query to use `HeuristicAllocationExpr` instead of `AllocationExpr` as a source of flow.
Currently, the heuristics used for detecting an `HeuristicAllocationFunction` is:
1. The function name matches `%alloc%`
2. It returns a pointer type
3. We can find a unique parameter of `unsigned` integral type
In addition, a `HeuristicAllocationFunction` is recognized as a `realloc`-like function if, in addition to the above, it:
1. Matches the name `%realloc%`, and
2. We can find a …
> C++: Recognize allocation functions heuristically

- cpp/ql/test/library-tests/ir/range-analysis/RangeAnalysis.ql
- cpp/ql/test/library-tests/ir/range-analysis/SimpleRangeAnalysis_tests.cpp
- cpp/ql/test/library-tests/ir/range-analysis/test.cpp
- cpp/ql/test/library-tests/ir/range-analysis/test_util.h
This PR copy/pastes almost all the tests we had for `SimpleRangeAnalysis` into a testfile that's exercised by the new range-analysis library, and then moves the file over to use InlineExpectationsTest.
Commit-by-commit review recommended:
- https://github.com/github/codeql/commit/c4c7c95db2889bbc19c4d46c6a6bf91054b8077d does the copy/paste. Nothing else is going on in this commit.
- https://github.com/github/codeql/commit/d14b2c2880c1a53dc6c5fd96c0b1b848d0c0cc84 makes it possible for the expected values to have whitespace in them. This is needed to print expected values containing bounds with a `toString` that contains spaces (for example if a bound is `call to foo` + 42).
- Finally, https://github.com/github/codeql/commit/56b5010f6b505ad03af1b36d2a20fd6d2921d4b6 converts the file to …
> C++: Port SimpleRangeAnalysis tests to the new range-analysis

- swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Url.qll
- swift/ql/test/library-tests/dataflow/flowsources/FlowSources.expected
- swift/ql/test/library-tests/dataflow/flowsources/FlowSources.ql
- swift/ql/test/library-tests/dataflow/flowsources/string.swift
- swift/ql/test/library-tests/dataflow/flowsources/url.swift
Add `URL.resourceBytes`, `URL.lines` and `URL.resourceBytes.lines` as taint sources.
I haven't used Models-As-Data because it doesn't currently support member variables in Swift.  When that changes we should be able to simplify the model itself to three lines of CSV.
> Swift: URL taint sources

- java/ql/lib/change-notes/2022-09-20-CompilationUnit-getATypeInScope.md
- java/ql/lib/change-notes/2022-09-20-CompilationUnit-simple-name-type.md
- java/ql/lib/semmle/code/java/CompilationUnit.qll
- java/ql/src/Advisory/Documentation/ImpossibleJavadocThrows.ql
- java/ql/test/query-tests/Javadoc/ImpossibleJavadocThrows.expected
- java/ql/test/query-tests/Javadoc/ImpossibleJavadocThrows.java
Reverts #10498, but keeps #10640.
The performance impact of `getATypeInScope` is too high (it produces a cartesian product of all `CompilationUnit`s with all types in `java.lang`), we will need to reconsider this feature. @Marcono1234 let us know if you can think of an alternative.
> Java: Revert #10489 and #10640

- swift/ql/src/queries/Security/CWE-079/UnsafeWebViewFetch.ql
- swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql
- swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.ql
- swift/ql/src/queries/Security/CWE-311/CleartextTransmission.ql
- swift/ql/src/queries/Security/CWE-328/WeakSensitiveDataHashing.ql
- swift/ql/src/queries/Security/ECB-Encryption/ECBEncryption.ql
- swift/ql/test/query-tests/Security/CWE-311/testSend.swift
Use the new `ClassOrStructDecl` (from https://github.com/github/codeql/pull/10595 by @MathiasVP), in place of `ClassDecl` and `StructDecl` in all Swift queries.  I consider this more robust in several ways:
- when the query + test were written with the wrong one (out of `class` / `struct`).  Such a mistake is hard to spot but will mean we find no results in real world usage.  I've made this mistake myself, twice, and I've seen someone else make it as well.
- an alternative solution would be to check all current QL for Swift diligently.
- if something in a standard library changes between `struct` and `class` in future.
- if the QL is reused (copy-pasted) to match a different thing in the standard library in future.
The downside is minimal - if there is a thing matching the standard …
> Swift: Use ClassOrStructDecl

- csharp/ql/integration-tests/all-platforms/dotnet_run/test.py
- csharp/tools/tracing-config.lua
Invocations like
```
dotnet run --no-build arg
```
would incorrectly be rewritten to
```
dotnet run -p:UseSharedCompilation=false -- --no-build arg
```
With this PR, they instead get rewritten to
```
dotnet run -p:UseSharedCompilation=false --no-build arg
```
> C#: Recognize options to `dotnet run` in tracer when injecting `-p:UseSharedCompilation=false`

- ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
- ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll
- ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected
As pointed out by @asgerf, we no longer need `PairValueContent`, after `SynthHashSplatArgumentNode` was introduced (it was originally not there at the time when `PairValueContent` got introduced).
> Ruby: Remove `PairValueContent`

- cpp/ql/src/Likely Bugs/Conversion/CastArrayPointerArithmetic.ql
The joins in this predicate turned out to be quite bad after I tried to switch to IR use-use dataflow instead of AST dataflow. This PR should hopefully prevent the optimizer from trying to do a join on the base type.
> C++: Fix potentially bad join

- java/ql/src/experimental/Security/CWE/CWE-078/ExecTainted.java
- java/ql/src/experimental/Security/CWE/CWE-078/ExecTainted.qhelp
Porting over guidance for ExecTainted.ql so that it is also included alongside experimental version.
> Java Guidance: ExecTainted.ql (experimental version)

- csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
- java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
- ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll
- ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected
- ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected
- ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
- ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql
- ruby/ql/test/library-tests/dataflow/summaries/summaries.rb
- swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll
Conjunctive `With(out)Content` models-as-data specifications such as
```
input = Argument[self].WithoutElement[0!].WithoutElement[1!] and
output = Argument[self]
```
did not work.
With this PR they do.
> Data flow: Take conjunctive `With(out)Contents` into account in `prohibitsUseUseFlow`

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/calls.rb
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/superclasses.expected
We were previously not handling cases like this:
```rb
class A
def self.singleton; end
end
class B < A
end
B.singleton # should resolve to B#singleton
class C < A
def self.singleton; end
end
C.singleton # should resolve to C#singleton
```
DCA shows 20k new call edges, and those I sampled looked legit.
> Ruby: Take overrides into account for singleton methods defined on modules

- ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll
- ruby/ql/test/library-tests/frameworks/action_controller/params-flow.ql
Semantic merge conflict between https://github.com/github/codeql/pull/10538 and https://github.com/github/codeql/pull/10673
> Ruby: fix use of deprecated class

- ruby/ql/lib/codeql/ruby/frameworks/http_clients/Excon.qll
- ruby/ql/lib/codeql/ruby/frameworks/http_clients/Faraday.qll
- ruby/ql/lib/codeql/ruby/frameworks/http_clients/HttpClient.qll
- ruby/ql/lib/codeql/ruby/frameworks/http_clients/Httparty.qll
- ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll
- ruby/ql/lib/codeql/ruby/frameworks/http_clients/OpenURI.qll
- ruby/ql/lib/codeql/ruby/frameworks/http_clients/RestClient.qll
- ruby/ql/lib/codeql/ruby/frameworks/http_clients/Typhoeus.qll
- ruby/ql/lib/codeql/ruby/frameworks/stdlib/Pathname.qll
As these libraries are used by multiple queries, it makes sense to cache them.
> Ruby: Cache use of `DataFlowImplFor(Pathname|HttpClientLibraries)`

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/test/kotlin/library-tests/exprs/funcExprs.expected
- java/ql/test/kotlin/library-tests/exprs/funcExprs.ql
This PR fixes false positives with the "Missing Override annotation" check.
> Kotlin: Extract `override` modifier on SAM methods

- ruby/ql/lib/codeql/ruby/ast/internal/Module.qll
- ruby/ql/lib/codeql/ruby/ast/internal/Synthesis.qll
- ruby/ql/lib/codeql/ruby/controlflow/internal/Completion.qll
Rewritten to use explicit recursion instead of (implicit) `fastTC`. See each commit for details.
> Ruby: Avoid computing full `fastTC` for `AstNode::getParent`

- cpp/ql/src/Security/CWE/CWE-121/UnterminatedVarargsCall.ql
- cpp/ql/src/change-notes/2022-10-06-unterminated-variadic-call.md
- cpp/ql/test/query-tests/Security/CWE/CWE-121/semmle/tests/UnterminatedVarargsCall.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-121/semmle/tests/more_tests.cpp
- cpp/ql/test/query-tests/Security/CWE/CWE-121/semmle/tests/tests.c
`cpp/unterminated-variadic-call` is a heuristic query - it looks for cases where a variadic call looks like its missing a sentinel to end the variadic arguments (such as a `0` at the end) by comparing with other calls to the same variadic function.  The threshold of calls required to establish such a pattern is currently just 50%, with many real-world false positive results being backed by only 50-70% of calls as evidence - while the query has `@precision medium`.
This PR increases the threshold from 50% to 80%, greatly improving precision, though there will still be some false positive results even after the change.  The query `@precision` is left at `medium`, but I feel it's a more honest `medium` now whereas before this change it should perhaps have been `low`.  The alert message has …
> C++: Tune cpp/unterminated-variadic-call

- .github/workflows/qhelp-pr-preview.yml
The command to gather the changed files uses NULL character terminated "lines", therefore we should supply the `-z` flag to `basename` as well. Otherwise we end up calling `git grep -l "\n"` which would list all files containing a newline.
This should fix errors on `qhelp.inc` files like in https://github.com/github/codeql/actions/runs/3214105642/jobs/5261655998 .
> CI: fix qhelp preview

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/ql/test/kotlin/library-tests/parameter-defaults/PrintAst.expected
- java/ql/test/kotlin/library-tests/parameter-defaults/erasure.ql
- java/ql/test/kotlin/library-tests/parameter-defaults/test.kt
Previously because extractClassInstance didn't use the declaration stack, we wouldn't notice that it was legal to refer to its type variable in the context of extracting a specialised method <-> method source-decl edge. This led to erasing the types of the source-decl, so that e.g. Map.put(...) would have signature (Object, Object) not (K, V) as it should.
> Kotlin: fix type variable erasure inside default function values

- ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll
- ruby/ql/lib/codeql/ruby/frameworks/data/ModelsAsData.qll
I think the adapter class fits more naturally in `ModelsAsData.qll`.
> Ruby: Move `SummarizedCallableFromModel` into `ModelsAsData.qll`

- ruby/ql/lib/codeql/ruby/ApiGraphs.qll
- ruby/ql/lib/codeql/ruby/frameworks/Core.qll
- ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
- ruby/ql/test/library-tests/dataflow/array-flow/type-tracking-array-flow.expected
- ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected
Adds the local field step to type-tracking, such that any write to an instance variable can flow to a read.
```rb
class Foo
def foo(x)
@field = Bar.new
end
def bar
@field # 'Bar.new' flows here
end
end
```
For the time being it doesn't take inheritance into account.
This initially caused a regression in `opal`. Investigating it I noticed some dubious API graph edges, and concluded that we should not propagate use/def nodes through self-argument passing.
I wonder if we should remove self-argument passing from type-tracking altogether, since some parts of the call-graph construction also block this. But tracking of singleton methods still relies on self-argument passing so I didn't go that far in this PR, and just blocked it directly in API graphs instead.
Also marks the unary `*` operator …
> Ruby: summarize unary splat operators and add local field step

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/integration-tests/posix-only/kotlin/java_modifiers/libsrc/extlib/A.java
- java/ql/integration-tests/posix-only/kotlin/java_modifiers/test.expected
- java/ql/integration-tests/posix-only/kotlin/java_modifiers/test.kt
- java/ql/integration-tests/posix-only/kotlin/java_modifiers/test.py
- java/ql/integration-tests/posix-only/kotlin/java_modifiers/test.ql
This change fixes false positives reported by `java/non-overriding-package-private`
> Kotlin: extract `protected` modifier from java class files

- docs/codeql/support/reusables/frameworks.rst
- python/ql/lib/semmle/python/Frameworks.qll
- python/ql/lib/semmle/python/frameworks/Mysql.qll
- python/ql/lib/semmle/python/frameworks/Pymssql.qll
- python/ql/lib/semmle/python/frameworks/internal/PEP249Impl.qll
- python/ql/src/change-notes/2022-10-10-pep249-executemany-modeling.md
- python/ql/src/change-notes/2022-10-10-pymssql-modeling.md
- python/ql/test/library-tests/frameworks/pymssql/ConceptsTest.ql
- python/ql/test/library-tests/frameworks/pymssql/pep249.py
- python/ql/test/library-tests/frameworks/pymysql/pep249.py
This PR is actually 2 major features:
* 4ee71ae Python: Add support for `pymssql` package
* dba42d6 Python: Model `executemany` on PEP-249 DB APIs
I just stuck them together, since it was only the modeling of `pymssql` that made me realize we were missing the `executemany` calls :flushed:
> Python: DB Modeling: Add `pymssql` and `executemany` in general

- swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/CustomUrlSchemes.qll
- swift/ql/test/library-tests/dataflow/flowsources/FlowSources.expected
- swift/ql/test/library-tests/dataflow/flowsources/customurlschemes.swift
As explained [here](https://github.com/OWASP/owasp-mastg/blob/b7a93a2e5e0557cc9a12e55fc3f6675f6986bb86/Document/0x06h-Testing-Platform-Interaction.md#testing-custom-url-schemes-mstg-platform-3), iOS apps can receive arbitrary URLs from other apps in the following functions if they register a custom URL scheme:
* [`application(_:open:options:`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application?language=swift)
* [`application(_:handleOpen:)`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622964-application?language=swift)
* [`application(_:open:sourceApplication:annotation:)`](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623073-application?language=swift)
Note that the last two are deprecated, but …
> Swift: Add taint sources for custom URL scheme URLs

- python/ql/lib/semmle/python/dataflow/new/internal/TypeTracker.qll
- python/ql/lib/semmle/python/dataflow/new/internal/TypeTrackerSpecific.qll
- ruby/ql/lib/codeql/ruby/typetracking/TypeTracker.qll
- ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
To reduce non-linear recursion during call graph construction, like we already have `flowStepCall` and `flowStepNoCall`.
> Type tracking: Split up `levelStep` into `levelStepCall` and `levelStepNoCall`

- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This is the final piece of syntactic compatibility needed to do the AST to IR dataflow rewrite.
Note that `uninitializedNode` is already present in the non-experimental IR dataflow library, and is implemented as `none()` with a deprecated predicate. However, we have [1 query](https://github.com/github/codeql/blob/af79139c3008e533e6583c91585bccffe02039ae/cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql#L46) that currently uses uninitialized nodes, so to ease the transition I've added a proper implementation of this concept in the experimental IR dataflow library.
> C++: Add `UninitializedNode` to experimental IR dataflow

- ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/instance_fields.rb
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/superclasses.expected
Fixes a bug in how the type-tracking associates a singleton class with its target module.
[Evaluation](https://github.com/github/codeql-dca-main/issues/7754) looks good, about 4k new call edges, and neutral performance. There are 4 new alerts from `rb/weak-cryptographic-algorithm` which correctly point out that DES is used, although it seems intentional in that codebase.
> Ruby: bugfix in type-tracking singleton class resolution

- csharp/ql/src/Telemetry/ExternalApi.qll
- csharp/ql/src/Telemetry/SupportedExternalSinks.ql
- csharp/ql/src/Telemetry/SupportedExternalSources.ql
- csharp/ql/src/Telemetry/SupportedExternalTaint.ql
- csharp/ql/src/Telemetry/UnsupportedExternalAPIs.ql
- java/ql/src/Telemetry/ExternalApi.qll
- java/ql/src/Telemetry/SupportedExternalSinks.ql
- java/ql/src/Telemetry/SupportedExternalSources.ql
- java/ql/src/Telemetry/SupportedExternalTaint.ql
- java/ql/src/Telemetry/UnsupportedExternalAPIs.ql
It turns out that there are some minor issues with the number of reported results by the telemetry queries.
The queries are supposed to *limit* the results to the top 1k most relevant (most frequent) results.
However, the ordering (ranking) was based on the callables themselves and not the string representation used for the result. Unfortunately, the string representation is not a precise description of a callable, which means that multiple callables can map to the same description causes slight inconsistencies in the *ranking* (ie. we can risk getting less than 1k results even though there result set we try to limit is bigger than 1k).
For C# some examples cases are callables of the same name in subclasses of the same name, but nested in classes with different names.
To solve this the …
> C#/Java: Limit telemetry results.

- docs/codeql/codeql-for-visual-studio-code/setting-up-codeql-in-visual-studio-code.rst
This PR consists of a small change to the CodeQL extension installation instructions. Instead of just pointing the user to the "More actions" menu in VS Code, I described the menu icon as an ellipsis to clarify the process for new VS Code users.
> Add clarity to CodeQL extension installation

- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
I realise this is in experimental code, but it fixes a QL-for-QL alert that's showing up in other PRs under "Unchanged files with check annotations".
> C++: use explicit `this`

- ruby/ql/lib/codeql/ruby/frameworks/Rails.qll
- ruby/ql/src/change-notes/2022-10-12-rails-render-file.md
I came across this sink and noticed it wasn't modelled yet. Treats the `file:` keyword argument of the `render` method as a file system access, and thus a sink for path injection.
I ran [evaluation](https://github.com/github/codeql-dca-main/issues/7779) on some Rails projects, and it finds a couple of new sinks and some new path-injections alerts (in what seems to be intentionally-insecure code).
> Ruby: treat render 'file:' argument as a file system access

- java/ql/lib/semmle/code/java/security/regexp/NfaUtils.qll
- javascript/ql/lib/semmle/javascript/security/regexp/NfaUtils.qll
- javascript/ql/lib/semmle/javascript/security/regexp/NfaUtilsSpecific.qll
- python/ql/lib/semmle/python/security/regexp/NfaUtils.qll
- python/ql/lib/semmle/python/security/regexp/NfaUtilsSpecific.qll
- ruby/ql/lib/codeql/ruby/security/regexp/NfaUtils.qll
- ruby/ql/lib/codeql/ruby/security/regexp/NfaUtilsSpecific.qll
> ReDoS: Spelling nfautils

- ruby/ql/lib/codeql/ruby/frameworks/ActiveSupport.qll
- ruby/ql/test/library-tests/frameworks/active_support/ActiveSupportDataFlow.expected
- ruby/ql/test/library-tests/frameworks/active_support/active_support.rb
https://api.rubyonrails.org/classes/Pathname.html
> Ruby: model `Pathname#existence` extension from `ActiveSupport`

- csharp/ql/lib/semmle/code/cil/DataFlow.qll
- csharp/ql/lib/semmle/code/cil/Method.qll
- csharp/ql/lib/semmle/code/cil/Ssa.qll
- csharp/ql/lib/semmle/code/cil/Stubs.qll
- csharp/ql/lib/semmle/code/cil/internal/SsaImpl.qll
- csharp/ql/lib/semmle/code/csharp/commons/Disposal.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/TaintTrackingPrivate.qll
This PR adds CIL SSA definitions to `DataFlow::Node`, just like we already have SSA definitions for source code.
The motivation for adding SSA definitions into `DataFlow::Node` in the first place is to avoid having to compute all phi-node input/output combinations up front. For example, if we have
```mermaid
graph TD;
A-->phi;
B-->phi;
C-->phi;
phi-->D;
phi-->E;
phi-->F;
```
then we would have to generate 9 flow steps (quadratic), as opposed to 6 (linear).
> C#: Include CIL SSA definitions in `DataFlow::Node`

- csharp/ql/lib/semmle/code/csharp/Assignable.qll
- csharp/ql/lib/semmle/code/csharp/exprs/Access.qll
- csharp/ql/lib/semmle/code/csharp/frameworks/Format.qll
- csharp/ql/src/API Abuse/DisposeNotCalledOnException.ql
- csharp/ql/src/Useless code/DefaultToStringQuery.qll
`AssignableRead::getAReachableRead` is worst-case quadratic, so we should never attempt to evaluate it in full.
Significant speed-up on `dotnet/aspnetcore`:
source | a_m | a_std | b_m | b_std | diff | relative
-- | -- | -- | -- | -- | -- | --
Median (excl. partials) |   |   |   |   | -1 | -0.00814
Overall (excl. partials) | 9276 |   | 8595 |   | -680.7 | -0.0734
  |   |   |   |   |   |  
dotnet__aspnetcore | 1857 | 61.73 | 1226 | 36.5 | -630.7 | -0.34
dotnet__roslyn | 1124 | 0 | 1092 | 0 | -32 | -0.0285
dotnet__efcore | 1104 | 0 | 1075 | 0 | -29 | -0.0263
OrchardCMS__OrchardCore | 387 | 0 | 378 | 0 | -9 | -0.0233
DynamoDS__Dynamo | 172 | 0 | 168 | 0 | -4 | -0.0233
jerryhoff__WebGoat.NET | 58 | 0 | 57 | 0 | -1 | -0.0172
DeafLight__SilentLux.AutoFixture.Moq.Xunit2 | 133 | 0 | 131 | 0 | -2 | …
> C#: Deprecate `AssignableRead::getAReachableRead`

- ruby/ql/lib/codeql/ruby/security/regexp/PolynomialReDoSCustomizations.qll
- ruby/ql/test/query-tests/security/cwe-1333-polynomial-redos/PolynomialReDoS.expected
- ruby/ql/test/query-tests/security/cwe-1333-polynomial-redos/PolynomialReDoS.rb
CVE-2021-22880: Recognizes the sink (TP with https://github.com/github/codeql/pull/10782). 
CVE-2022-30122: One step closer to the sink. 
[Evaluation looks OK](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-10798-0-ruby/reports).  
There is a hint towards a performance regression, but I couldn't replicate locally.  
And [a repeat](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-10798-0-ruby__1/reports) shows a smaller regression, and in other projects 🤷
> Rb: add case-when expressions as a sink to rb/polynomial-redos

- swift/codegen/generators/qlgen.py
- swift/extractor/infra/SwiftDispatcher.h
- swift/ql/lib/codeql/swift/controlflow/internal/Completion.qll
- swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll
- swift/tools/tracing-config.lua
> Spelling swift

- docs/codeql/support/reusables/frameworks.rst
- docs/codeql/support/reusables/versions-compilers.rst
This was just copied from the other languages, with links updated and checked.
A minor question is whether we could specify the RoR version supported (7.0). None of the other languages do this so I decided to leave this out @hmac.
> Ruby: Update supported languages and frameworks

- ruby/ql/lib/codeql/ruby/ast/internal/Module.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
Various performance improvements, most notable reducing input relations for non-linear recursion in `getTarget`.
These performance improvements are a prerequisite for getting acceptable slow-downs when adding [flow through constructors](https://github.com/github/codeql/pull/10714), but I thought it would be better to pull out these changes into a separate PR.
> Ruby: Call graph performance improvements

- java/ql/test/kotlin/library-tests/ministdlib/MiniStdLib.kt
- java/ql/test/kotlin/library-tests/ministdlib/MyClass.kt
- java/ql/test/kotlin/library-tests/ministdlib/classes.expected
- java/ql/test/kotlin/library-tests/ministdlib/classes.ql
- java/ql/test/kotlin/library-tests/ministdlib/options
This should make it easier to diagnose certain kinds of problems.
> Kotlin: Add a ministdlib test

- cpp/ql/lib/semmle/code/cpp/security/FlowSources.qll
- cpp/ql/test/query-tests/Security/CWE/CWE-129/SAMATE/ImproperArrayIndexValidation/ImproperArrayIndexValidation.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextBufferWrite.expected
This PR repairs the `FlowSources.qll` library for IR-based use-use dataflow. In fact, this PR is mostly just a cleanup of the library. Prior to this PR, the library basically re-implemented the mapping from `FunctionInput`/`FunctionOutput` to `DataFlow` nodes. This PR deletes all this re-implemented logic and forwards it to the implementation in `ModelUtil`.
> C++: Prepare `FlowSources.qll` for IR-based use-use dataflow

- ruby/ql/test/library-tests/modules/modules.expected
This change is due to a8fdda65fbbbf5b5d55f49b7715c6a71c3e15427.
> Ruby: Update test fixture

- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll
- java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
- java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImplSpecific.qll
- java/ql/test/library-tests/dataflow/synth-global/A.java
- java/ql/test/library-tests/dataflow/synth-global/test.expected
- java/ql/test/library-tests/dataflow/synth-global/test.ql
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll
- python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImplSpecific.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
- swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll
- swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImplSpecific.qll
This allows MaD summaries that resp. reads or writes from some global state, e.g. a database, such that jump steps are inserted between the synthesized function bodies.
This allows us to add models for `storeInDb` and `readFromDb` such that we have flow in the following case even if there's no path between `foo` and `bar`:
```
foo() {
storeInDb(tainted);
}
bar() {
sink(readFromDb());
}
```
> Dataflow: Add support for synthetic global fields in MaD.

- ruby/ql/lib/change-notes/2022-10-14-digest-model.md
- ruby/ql/lib/codeql/ruby/ApiGraphs.qll
- ruby/ql/lib/codeql/ruby/frameworks/Core.qll
- ruby/ql/lib/codeql/ruby/frameworks/core/Digest.qll
- ruby/ql/lib/codeql/ruby/security/OpenSSL.qll
- ruby/ql/test/query-tests/security/cwe-327/BrokenCryptoAlgorithm.expected
- ruby/ql/test/query-tests/security/cwe-327/broken_crypto.rb
CVE-2019-5420: TP/TN
[An evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-10832-0-ruby/reports) shows good performance.  
The `rb/weak-cryptographic-algorithm` query has many new results with this change, but the results seem reasonable given the query.
> RB: add model for the `Digest` and `OpenSSL::Digest` modules

- javascript/ql/src/Security/CWE-367/FileSystemRace.ql
- javascript/ql/src/change-notes/2022-10-04-fix-loops-file-system-race.md
- javascript/ql/test/query-tests/Security/CWE-367/tst.js
[Evaluation shows that we loose a bunch of results](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-10768-7500a3__nightly-old__CustomSuite/reports), but that was the point.  
In the lost results the file-check doesn't dominate the file-access.  
In most cases that's from the file-check being inside a conditional.  
The point of the PR was originally just to remove FPs from the check/access being inside a loop.   
But I like removing these other results too, so I want to keep this.
> JS: fix that js/file-system-race could have FPs related to loops

- cpp/ql/src/experimental/Security/CWE/CWE-078/WordexpTainted.c
- cpp/ql/src/experimental/Security/CWE/CWE-078/WordexpTainted.qhelp
- cpp/ql/src/experimental/Security/CWE/CWE-078/WordexpTainted.ql
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-078/WordexpTainted.expected
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-078/WordexpTainted.qlref
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-078/test.cpp
This is my first query for C/C++ I think, so there is likely some improvement possible.
> Add query for tainted `wordexp` calls.

- ruby/ql/lib/codeql/ruby/Concepts.qll
- ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll
- ruby/ql/lib/codeql/ruby/security/XSS.qll
- ruby/ql/src/change-notes/2022-10-14-actiondispatch-response.md
- ruby/ql/test/library-tests/frameworks/ActionController.expected
- ruby/ql/test/library-tests/frameworks/ActionController.ql
- ruby/ql/test/library-tests/frameworks/ActionDispatch.expected
- ruby/ql/test/library-tests/frameworks/ActionView.expected
- ruby/ql/test/library-tests/frameworks/app/controllers/comments_controller.rb
- ruby/ql/test/query-tests/security/cwe-079/ReflectedXSS.expected
- ruby/ql/test/query-tests/security/cwe-079/app/controllers/foo/bars_controller.rb
Model the various methods on `ActionDispatch::Response` which set parts of the HTTP response. I've added a new concept `Http::Server::HeaderWriteAccess` which represents a write to a header in a HTTP response. The reason for this is that the existing concept, `HttpResponse`, describes an entire HTTP response, whereas these methods just set _part_ of the response.
There are currently no queries that use this concept, but that's just because I can't think off the top of my head which queries it would apply to.
Besides headers, we also model `response.body = ...` and `response.send_file ...`, which are regular `HttpResponse` instances.
> Ruby: Model ActionDispatch::Response

- swift/ql/src/queries/Security/CWE-321/HardcodedEncryptionKey.qhelp
- swift/ql/src/queries/Security/CWE-321/HardcodedEncryptionKey.ql
- swift/ql/src/queries/Security/CWE-321/HardcodedEncryptionKey.swift
- swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.expected
- swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.qlref
- swift/ql/test/query-tests/Security/CWE-321/test.swift
Hardcoded keys should not be used for creating encryption ciphers. Data encrypted using hardcoded keys are more vulnerable to the possibility of recovering them.
The rule currently supports all ciphers that the CryptoSwift API provides, but we can always extend it further if more cophers are added.
> Swift: detect hardcoded encryption keys

- swift/codegen/generators/qlgen.py
- swift/codegen/lib/ql.py
- swift/codegen/templates/ql_test_class.mustache
- swift/codegen/test/test_qlgen.py
- swift/ql/test/extractor-tests/generated/File/File.expected
- swift/ql/test/extractor-tests/generated/File/File.ql
- swift/ql/test/extractor-tests/generated/expr/ImplicitConversionExpr/ImplicitConversionExpr.expected
- swift/ql/test/extractor-tests/generated/expr/ImplicitConversionExpr/ImplicitConversionExpr.ql
- swift/ql/test/extractor-tests/generated/type/BuiltinType/BuiltinType.expected
- swift/ql/test/extractor-tests/generated/type/BuiltinType/BuiltinType.ql
In those kinds of tests the results may have different final classes that are not necessarily visible (or tested) solely through the string representation. For better testing and reading of expected results, `getQlPrimaryClasses` is added in these cases.
> Swift: show QL class in generated tests on collapsed hierarchies

- swift/ql/lib/codeql/swift/elements/Location.qll
- swift/ql/lib/codeql/swift/elements/UnknownLocation.qll
- swift/ql/test/library-tests/elements/location/location.expected
- swift/ql/test/library-tests/elements/location/location.ql
- swift/ql/test/library-tests/elements/location/location.swift
In a debug query I was outputting `Location.toString()` and just getting a bunch of strings `"DbLocation"` (from the base `Element.toString`).  This PR adds a `Location.toString()` implementation similar to what CPP and other languages have.
> Swift: Give Location a useful toString

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/src/Likely Bugs/Format/NonConstantFormat.ql
- cpp/ql/test/query-tests/Likely Bugs/Format/NonConstantFormat/NonConstantFormat.expected
NOTE: This PR also contains the commits from https://github.com/github/codeql/pull/10818. Only the very last commit is new. (That PR was necessary to actually run [this](https://github.com/github/codeql/blob/main/cpp/ql/test/query-tests/Likely%20Bugs/Format/NonConstantFormat/performance.c) test).
> C++: Prepare `cpp/non-constant-format` for IR-based use-use dataflow

- ruby/ql/lib/codeql/ruby/security/XSS.qll
No longer needed after https://github.com/github/codeql/pull/10559.
> Ruby: Remove redundant additional flow step from `OrmTracking::Configuration`

- docs/codeql/support/reusables/frameworks.rst
I've added the suggested frameworks to this list, however these frameworks have *partial* support so it's not clear to me which if any of these should be added. Putting this PR up here for discussion, and I don't feel too strongly about whether this should be included in the GA release.
> Ruby: Add more frameworks to the list of supported frameworks

- ruby/actions/create-extractor-pack/action.yml
This fixes most `set-output` and `save-state` warnings in Ruby CI jobs.
> CI: update actions/cache to v3

- java/ql/test/kotlin/query-tests/UselessNullCheck/Test.kt
- java/ql/test/kotlin/query-tests/UselessNullCheck/UselessNullCheck.expected
This PR adds a test case for the useless null check. An issue is correctly reported on the sample code, but the experience could be improved. The reported variable name doesn't exist in the code, it's a compiler generated variable. Also, the kotlin compiler already warns on this issue, which makes our finding somewhat redundant.
> Kotlin: Add test for useless null check on safe calls

- ql/extractor/src/extractor.rs
- ql/node-types/src/lib.rs
- ql/ql/src/codeql_ql/ast/Ast.qll
- ql/ql/src/codeql_ql/ast/internal/AstNodes.qll
- ql/ql/src/codeql_ql/ast/internal/Builtins.qll
- ql/ql/src/codeql_ql/ast/internal/Module.qll
- ql/ql/src/codeql_ql/ast/internal/Predicate.qll
- ql/ql/src/codeql_ql/dataflow/DataFlow.qll
- ql/ql/src/codeql_ql/style/DeadCodeQuery.qll
- ql/ql/src/queries/bugs/InconsistentDeprecation.ql
- ql/ql/src/queries/diagnostics/EmptyConsistencies.ql
- ql/ql/src/queries/style/ConsistentCasing.ql
- ql/ql/src/queries/style/MissingOverride.ql
- ql/ql/src/queries/style/RegexpInsteadOfPattern.ql
- ql/ql/src/queries/style/UseInstanceofExtension.ql
> Spelling ql

- java/kotlin-extractor/src/main/java/com/semmle/extractor/java/OdasaOutput.java
- java/ql/integration-tests/linux-only/kotlin/custom_plugin/diagnostics.expected
- java/ql/integration-tests/linux-only/kotlin/custom_plugin/diagnostics.ql
Rather than using lock files and rewriting TRAP file, and storing the metadata in a .metadata file, we now encode the metadata in the filename and rename all but the newest TRAP file so that the importer doesn't see them.
So we might end up with e.g.
```
Text.members#0.0-1664381081060-java.trap.gz
Text.members#55.0-1658481279000-java.trap-old.gz
Text.members#55.0-1664381081060-java.trap-old.gz
```
For now, you can go back to the old system by setting
```
CODEQL_EXTRACTOR_JAVA_TRAP_LOCKING=true
```
in the environment.
> Kotlin: Implement lockless TRAP writing

- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/FunctionBodyFeatures.qll
- javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountNosqlInjection.ql
- javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountSqlInjection.ql
> Spelling ml

- docs/codeql/ql-language-reference/expressions.rst
- docs/codeql/ql-language-reference/signatures.rst
> Spelling frontend

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/calls.rb
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/superclasses.expected
Since https://github.com/github/codeql/pull/10705, we apply an open-world assumption when resolving calls to singleton method, just like with calls to instance methods, so we should no longer track module accesses into `self` parameters. This removes false positive call graph edges like
```rb
class SingletonA
def self.singleton1
end
def self.call_singleton1
singleton1
end
def self.call_call_singleton1
call_singleton1
end
end
class SingletonB < SingletonA
def self.singleton1
end
def self.call_singleton1
singleton1 # should not be able to target `SingletonA:::singleton1` and `SingletonC:::singleton1`
end
end
class SingletonC < SingletonA
def self.singleton1
end
def self.call_singleton1
singleton1 # should not be able to target `SingletonA:::singleton1` and `SingletonB:::singleton1`
end
end …
```
> Ruby: Block for steps into `self` parameters in `trackModuleAccess`

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
Refactored to follow the same pattern as for singleton methods. This allows for subsequent similar call-context-sensitive singleton resolution (follow-up PR), and may as well reduce tuple duplication (the same method may otherwise be looked up in many sub classes).
DCA confirms no changes to the call graph.
> Ruby: Refactor call graph logic for singleton methods

- java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt
- java/kotlin-extractor/src/main/kotlin/LinesOfCode.kt
- java/kotlin-extractor/src/main/kotlin/comments/CommentExtractor.kt
- java/kotlin-extractor/src/main/kotlin/utils/IrVisitorLookup.kt
- java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_4_32/Psi2Ir.kt
- java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_5_20/Psi2Ir.kt
- java/ql/integration-tests/posix-only/kotlin/logs/index_logs.py
- java/ql/integration-tests/posix-only/kotlin/logs/logs.expected
We were giving warnings about comments, when we were actually trying to populate numlines.
> Kotlin: Refactor PSI handling

- ruby/ql/lib/codeql/ruby/frameworks/Files.qll
- ruby/ql/test/query-tests/security/cwe-022/PathInjection.expected
- ruby/ql/test/query-tests/security/cwe-022/tainted_path.rb
CVE-2020-8161: Recognize the sink.
[Evaluation was very uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-10888-0-ruby/reports).
> Ruby: add model for Dir.glob and other Dir methods

- swift/integration-tests/posix-only/hello-world/Bodies.expected
- swift/integration-tests/posix-only/hello-world/Bodies.ql
- swift/tools/tracing-config.lua
For some reason `-experimental-skip-non-inlinable-function-bodies-without-types`
is passed to the frontend, which will skip extraction of most bodies.
By suppressing that option the problem goes away.
> Swift: fix missing extraction of function bodies in SPM builds

- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_4_32/getKotlinType.kt
- java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_7_0/getKotlinType.kt
- java/ql/integration-tests/posix-only/kotlin/enhanced-nullability/NotNull.java
- java/ql/integration-tests/posix-only/kotlin/enhanced-nullability/Test.java
- java/ql/integration-tests/posix-only/kotlin/enhanced-nullability/test.expected
- java/ql/integration-tests/posix-only/kotlin/enhanced-nullability/test.py
- java/ql/integration-tests/posix-only/kotlin/enhanced-nullability/test.ql
- java/ql/integration-tests/posix-only/kotlin/enhanced-nullability/user.kt
Otherwise we'll mistake `@NotNull Integer` for `int` and similar, causing a mismatch vs. Java signatures.
> Kotlin: ignore enhanced nullability when extracting primitive types

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/integration-tests/posix-only/kotlin/java-interface-redeclares-tostring/Test.java
- java/ql/integration-tests/posix-only/kotlin/java-interface-redeclares-tostring/test.expected
- java/ql/integration-tests/posix-only/kotlin/java-interface-redeclares-tostring/test.py
- java/ql/integration-tests/posix-only/kotlin/java-interface-redeclares-tostring/test.ql
- java/ql/integration-tests/posix-only/kotlin/java-interface-redeclares-tostring/user.kt
- java/ql/test/kotlin/library-tests/java-kotlin-collection-type-generic-methods/test.expected
Due to a probable compiler bug (?) the redeclaration looks like a fake symbol, leading to Java dispatching against a declaration that Kotlin doesn't believe exists.
> Kotlin: extract interface redeclarations of `Object` methods

- misc/bazel/cmake/README.md
- misc/bazel/cmake/setup.cmake
Also added a small `README.md` file.
> Bazel/CMake: make cmake runnable from outside the workspace

- swift/ql/src/queries/Summary/FlowSources.ql
- swift/ql/src/queries/Summary/SensitiveExprs.ql
- swift/ql/src/queries/Summary/SummaryStats.ql
I wrote these queries to assess the progress we're making identifying flow sources and sensitive expressions in real world Swift snapshots.  I intend to track these things fairly often in the near-mid future, so it would be convenient to have the queries in the public repo.  I don't think there's any harm in letting curious users see them as well.
It might be nice to have `LinesOfCode.ql` and `LinesOfUserCode.ql` summary queries as well as all (?) other languages do, but I don't think we extract the data for them yet.
> Swift: Add some summary queries.

- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/CustomUrlSchemes.qll
Fix `UrlRemoteFlowSource` name clash (with [`UrlRemoteFlowSource` in `Url.qll`](https://github.com/github/codeql/blob/main/swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Url.qll#LL21)) and add qldoc comment.  I'm not aware of any consequences the name clash was having, but it can't be a good thing.
> Swift: Fix UrlRemoteFlowSource name clash

- cpp/ql/src/Best Practices/Likely Errors/CommaBeforeMisleadingIndentation.ql
C++: Fix rare performance issue on `cpp/comma-before-misleading-indentation`.  The issue was `_Call#39248e3c::Call::getAnArgument#0#dispred#ff__Expr#ef463c5d::Expr::getFullyConverted#0#dispred#f__#higher_order_body` exploding (found on `nba-emu_NanoBoyAdvance`), which I interpret to mean that `normalizeExpr` was just getting too big on deep `Expr` trees (probably with lots of co-located hidden `Expr`s).
The new solution calculates the lowest relevant column number first (`min(getCandidateColumn(e))`), which should be less affected by co-located `Expr`s.  Then in the main calculation that follows a lot of `Expr`s can be culled early using this relation.
Its unfortunately more code than before but I've tried to explain in the comments.
I'll run DCA on this, but here are some local stats: …
> C++: Fix performance issue on cpp/comma-before-misleading-indentation

- javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll
`reachesReturn` would in some cases track the returned value out to call sites, which doesn't lead anywhere. It could also track into callees via return edges, but that's not useful either, since summaries take care of flow through callees.
This fixes a performance issue raised by https://github.com/github/codeql/issues/10937 (but it's possible there are more underlying issues to be fixed)
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/reaches-return-__default__code-scanning__1/reports) looks neutral
> JS: Do not track returned values out of the enclosing function

- docs/codeql/codeql-for-visual-studio-code/exploring-data-flow-with-path-queries.rst
Document the changes in this PR: https://github.com/github/vscode-codeql/pull/1568
> Docs: Mention new navigation commands

- javascript/ql/src/Security/CWE-313/PasswordInConfigurationFile.ql
- javascript/ql/test/query-tests/Security/CWE-313/tst.yml
From some FP reports shared on Slack. 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-10988-0-javascript/reports).
> JS: remove some FPs in `js/password-in-configuration-file`

- change-notes/1.20/analysis-javascript.md
- change-notes/1.23/analysis-cpp.md
- change-notes/1.24/analysis-javascript.md
- csharp/old-change-notes/2020-08-26-implicit-array-lengths.md
- docs/change-notes.md
- docs/ql-libraries/dataflow/dataflow.md
- go/old-change-notes/2020-11-12-zipslip-sanitizers.md
- go/old-change-notes/2021-01-12-model-couchbase.md
- java/old-change-notes/2021-02-23-deprecated-jcenter-bintray.md
- java/ql/lib/CHANGELOG.md
- java/ql/lib/change-notes/released/0.1.0.md
- java/ql/lib/change-notes/released/0.3.1.md
- java/ql/lib/change-notes/released/0.4.0.md
- java/ql/src/CHANGELOG.md
- java/ql/src/change-notes/released/0.0.10.md
- javascript/old-change-notes/2021-07-14-querystring.md
- javascript/ql/src/CHANGELOG.md
- javascript/ql/src/change-notes/released/0.0.10.md
- python/ql/src/Security/CWE-327/README.md
> Spelling code scanning product

- java/kotlin-extractor/src/main/java/com/semmle/util/trap/pathtransformers/PathTransformer.java
The standard code wants to normalise it to C:/!unknown-binary-location/... which is particularly annoying for cross-platform test output.
> Kotlin: Handle /!unknown-binary-location/... paths specially on Windows

- java/kotlin-extractor/src/main/java/com/semmle/util/trap/pathtransformers/PathTransformer.java
On Windows, we don't want a C: prefix on these either.
> Kotlin: Handle /modules/... paths specially too

- java/kotlin-extractor/kotlin_plugin_versions.py
We thought that 1.7.20-Beta > 1.7.20, and so tried to use 1.7.0's extractor with 1.7.20.
> Kotlin: Ignore tags when comparing versions

- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/ql/integration-tests/posix-only/kotlin/needless-java-wildcards/Test.java
- java/ql/integration-tests/posix-only/kotlin/needless-java-wildcards/kConsumer.kt
- java/ql/integration-tests/posix-only/kotlin/needless-java-wildcards/test.expected
- java/ql/integration-tests/posix-only/kotlin/needless-java-wildcards/test.py
- java/ql/integration-tests/posix-only/kotlin/needless-java-wildcards/test.ql
- java/ql/integration-tests/posix-only/kotlin/needless-java-wildcards/user.kt
For example, Java code might use `HasOutVariance<? extends String>`, or `HasInVariance<? super Object>`, both of which are needless wildcards and which the Kotlin extractor would previously have refused to reintroduce due to their not specifying a larger type than their bound. However this led to inconsistency with Java extraction, which extracts the type as it appears in source.
This seems to particularly happen with generated code, e.g. the output of the Kotlin protobuf compiler.
> Kotlin: reintroduce pointless wildcards when a Java declaration explicitly uses them

- go/ql/src/Diagnostics/SuccessfullyExtractedFiles.ql
- go/ql/test/query-tests/Diagnostics/SuccessfullyExtractedFiles.expected
Switch the successfully extracted files query to the `location, message` results format so that we get rich location information when exporting the results of this query to SARIF.  Previously the query used the `message` results format, which meant the interpreted results lacked a location.
> Go: Extract locations of successfully extracted files

- swift/ql/lib/codeql/swift/elements/decl/AbstractFunctionDecl.qll
- swift/ql/lib/codeql/swift/elements/decl/MethodDecl.qll
- swift/ql/lib/codeql/swift/elements/decl/TypeDecl.qll
- swift/ql/src/queries/Security/CWE-079/UnsafeWebViewFetch.ql
- swift/ql/test/library-tests/elements/decl/abstractfunctiondecl/abstractfunctiondecl.expected
- swift/ql/test/library-tests/elements/decl/abstractfunctiondecl/abstractfunctiondecl.ql
- swift/ql/test/library-tests/elements/decl/abstractfunctiondecl/abstractfunctiondecl.swift
Add `MethodDecl.hasQualifiedName` helper predicates (two variants) plus `AbstractFunctionDecl.hasName` (not so useful but feels like its missing).
There's a test to prove we do the right thing in some tricky cases like nested classes, protocols and extensions.  I have only _used_ the new predicates in one query so far (as a proof of concept), but I expect it to be useful in many more places and I intend to follow up with a PR updating existing queries.
> Swift: Add MethodDecl.hasQualifiedName

- ruby/ql/lib/codeql/ruby/security/CodeInjectionCustomizations.qll
- ruby/ql/src/queries/security/cwe-094/CodeInjection.ql
- ruby/ql/test/query-tests/security/cwe-094/CodeInjection.expected
- ruby/ql/test/query-tests/security/cwe-094/CodeInjection.rb
I was missing a `otherSink.getNode() = sink.getNode()` in the de-duplication, so it would only select a single sink for a given source. 
I found this while adding a test as a response to [this comment](https://github.com/github/codeql/pull/10883#discussion_r1003811977). 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-10968-0-ruby/reports) :phew:
> RB: fix rb/code-injection

- swift/extractor/infra/file/TargetFile.cpp
- swift/extractor/remapping/SwiftOutputRewrite.cpp
With the change to `std::filesystem` some path concatenations were translated to appending, which is not the same. In case rhs is absolute `lhs / rhs == rhs`, while concatenating treats `rhs` as if it was relative. The same behaviour can be obtained in `std::filesystem` by using `lhs / rhs.relative_path()`.
> Swift: fix remapping

- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPublic.qll
- swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImplSpecific.qll
- swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
- swift/ql/test/library-tests/dataflow/dataflow/test.swift
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/query-tests/Security/CWE-079/UnsafeWebViewFetch.expected
We had forgotten to generalize the code in a couple of places when we added flow through MaD summaries. This PR fixes these issues.
cc @atorralba this PR should make https://github.com/github/codeql/pull/10954 unnecessary.
> Swift: Fix flow out of summarized callables

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/integration-tests/posix-only/kotlin/generic-extension-property/User.java
- java/ql/integration-tests/posix-only/kotlin/generic-extension-property/test.expected
- java/ql/integration-tests/posix-only/kotlin/generic-extension-property/test.kt
- java/ql/integration-tests/posix-only/kotlin/generic-extension-property/test.py
- java/ql/integration-tests/posix-only/kotlin/generic-extension-property/test.ql
This arises when a generic class extends one of its parameters; for example, `class G<T> { val T.v; get() = 1 }`, where specialisation `G<List>` should generate a method specialisation `getV(List)`.
> Kotlin: specialise extension receivers the same as other function parameters

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/ql/integration-tests/all-platforms/kotlin/kotlin_java_lowering_wildcards/JavaUser.java
- java/ql/integration-tests/all-platforms/kotlin/kotlin_java_lowering_wildcards/kotlindefns.kt
- java/ql/integration-tests/all-platforms/kotlin/kotlin_java_lowering_wildcards/test.expected
In the process I also fix the missed case where suppression can be switched off using a parameterized annotation.
> Kotlin: fix wildcard suppression where the annotation applies to a parent type/argument.

- csharp/ql/integration-tests/qlpack.yml
- go/ql/config/legacy-support/qlpack.yml
- java/ql/consistency-queries/qlpack.yml
- java/ql/integration-tests/linux-only/kotlin/qlpack.yml
- java/ql/integration-tests/posix-only/kotlin/qlpack.yml
- misc/legacy-support/cpp/qlpack.yml
- misc/legacy-support/csharp/qlpack.yml
- misc/legacy-support/java/qlpack.yml
- misc/legacy-support/javascript/qlpack.yml
- misc/legacy-support/python/qlpack.yml
- python/tools/recorded-call-graph-metrics/ql/qlpack.yml
- ql/ql/test/callgraph/packs/other/qlpack.yml
- swift/integration-tests/qlpack.yml
- swift/integration-tests/runner.py
This is an initial stab at just removing all references to the deprecated key. I note though that a bunch of these files are named `legacy-xyz` -- I don't know what these are doing or if they have a reason to use the deprecated key (compatibility with an old `codeql`?)
> qlpacks: libraryPathDependencies -> dependencies

- python/ql/test/library-tests/essa/ssa-compute/UseUse.ql
- python/ql/test/library-tests/essa/ssa-compute/test.py
I initially created this as a dataflow test, but then realized it could just be an ESSA test. I couldn't find any existing ESSA tests though :| so created a new dir for it.
@yoff let me know if you think this should actually be under our dataflow tests, since the adjacent use-use was only added to serve the new dataflow lib.
> Python: Add failing ESSA use-use test

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/test/kotlin/library-tests/inherited-collection-implementation/Test.java
- java/ql/test/kotlin/library-tests/inherited-collection-implementation/test.expected
- java/ql/test/kotlin/library-tests/inherited-collection-implementation/test.ql
- java/ql/test/kotlin/library-tests/inherited-collection-implementation/user.kt
In this circumstance the compiler seems to generate a specialised version of the implementing function with its argument type replaced by the interface-implementing child class' type parameter. However it stores a back-pointer to the real declared function, which we should use as the call target.
> Kotlin: fix method types when an inherited method implements a collection type

- ql/ql/src/codeql_ql/ast/Ast.qll
- ql/ql/src/codeql_ql/ast/internal/Type.qll
This PR makes no difference now, but it will once I introduce the shared ReDoS pack.  
The problem comes e.g. from me importing `RegExpTreeView` (defined by each language) through some of the shared implementations.  
Because we collapse the instances of the parameterized modules there is no way of preventing that cross-talk between the modules.  
The consequence was e.g. that a reference `DataFlow::Configuration` in a Python query resolved too `DataFlow::Configuration` from JavaScript.  
The change is ugly, but it seems to work (the consistency queries are empty).
> QL: prevent some cross-talk between modules

- javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll
Saves an additional 15s (out of ~6 minutes) when running the code-scanning suite on the database from https://github.com/github/codeql/issues/10937 
[Evaluation looks somewhat uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-10986-21e7e2__default__code-scanning/reports).   
I'm pretty sure the cache size is just noise.
> JS: push more context into load/store steps from the exploratory flow-analysis

- csharp/ql/consistency-queries/SsaConsistency.ql
- ruby/ql/consistency-queries/SsaConsistency.ql
- shared/ssa/codeql/ssa/Ssa.qll
Possible now that class signatures are supported.
> SSA: Turn consistency predicates into `query` predicates

- .github/workflows/ruby-build.yml
- go/ql/src/qlpack.lock.yml
- go/ql/test/qlpack.lock.yml
- ruby/ql/lib/qlpack.lock.yml
- ruby/ql/src/qlpack.lock.yml
- ruby/ql/test/qlpack.lock.yml
- shared/ssa/codeql-pack.lock.yml
Update the lock files to include the `codeql/ssa` library and replace ad-hoc pack create command with a proper `codeql pack install` command now the ssa library has been published.
> Ruby: update dependencies

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
The equivalent of https://github.com/github/codeql/pull/10358, but for singleton methods instead of instance methods. For example, in
```rb
class A
def self.singleton_method1 x
sink x
end
def self.singleton_method2 x
singleton_method1 x
end
end
class B < A
def self.singleton_method1 x
non_sink x
end
end
B.singleton_method2 taint
```
we will no longer report flow from `taint` to `sink` (but still to `non_sink`).
> Ruby: Call-context sensitivity for singleton method calls

- csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
- shared/ssa/codeql/ssa/Ssa.qll
These predicates are currently only used by C#, and since I plan to also expose phi-read nodes, we would have to expose 4 versions of the same predicate (with/without phi-reads, with/without uncertain reads), and one could argue that we should then also have with/without uncertain writes, which just doesn't scale.
Instead, it will be up to the users of the shared SSA library to post-filter the use-use relations.
> SSA: Deprecate `*NoUncertainReads` predicates

- swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/WebView.qll
- swift/ql/test/library-tests/dataflow/flowsources/FlowSources.expected
- swift/ql/test/library-tests/dataflow/flowsources/webview.swift
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/webview.swift
Adds taint sources for JS-native bridges in WebViews. These are objects where JavaScript running in the WebView can execute native code, which can be exploited by malicious websites, or external attackers through XSS vulnerabilities, if it performs sensitive actions.
> Swift: WebView JS-native bridge sources

- ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
https://github.com/github/codeql/pull/11066 follow-up.
> Ruby: Avoid calls to deprecated SSA predicates

- csharp/ql/consistency-queries/SsaConsistency.ql
- ruby/ql/consistency-queries/SsaConsistency.ql
- shared/ssa/codeql/ssa/Ssa.qll
> Revert "SSA: Turn consistency predicates into `query` predicates"

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/test/kotlin/library-tests/parameter-defaults/PrintAst.expected
- java/ql/test/kotlin/library-tests/parameter-defaults/test.kt
This is the constructor case of https://github.com/github/codeql/pull/10909
> Kotlin vararg constructors: don't call a default-parameter constructor just because there are no varargs

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/test/library-tests/dataflow/ssa-flow/ssa-flow.expected
- ruby/ql/test/library-tests/dataflow/ssa-flow/ssa-flow.ql
- ruby/ql/test/library-tests/dataflow/ssa-flow/ssa_flow.rb
- Add missing flow from post-update nodes into phi nodes.
- Prevent flow from reads into phi nodes when use-use flow is prohibited.
> Ruby: Fix flow steps into phi nodes

- swift/ql/lib/codeql/swift/dataflow/Ssa.qll
https://github.com/github/codeql/pull/11066 follow-up.
Since there are no actual uncertain reads in Swift, we can simply use existing predicates.
> Swift: Avoid calls to deprecated SSA predicates

- ql/ql/src/codeql_ql/dependency/DependencyPath.qll
- ql/ql/src/queries/explore/DependencyPath.ql
Adds an explorative query for visualising how a given predicate/class/file depends on a given predicate or class.
By "explorative" I mean it's not intended to run in CI. It's a query you have to adapt to your needs and run locally.
Dependencies introduced by magic are not known to the query.
To use the query:
- Build the QL4QL extractor and extract a database for the relevant CodeQL library
- Modify `ql/src/queries/explore/DependencyPath.ql` and run it
---
For example, here I ran it to answer how `RE::RegExpTerm` depends on `isLocalSource`:
> QL4QL: Add DependencyPath.ql query

- cpp/ql/lib/semmle/code/cpp/commons/Buffer.qll
- cpp/ql/test/query-tests/Security/CWE/CWE-119/SAMATE/VeryLikelyOverrunWrite.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowBuffer.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowStatic.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/tests.cpp
https://github.com/github/codeql/pull/10833 prepared the `buffer.qll` library for use-use flow. In the end, the PR ended up being a lot more complicated than I had anticipated.
After thinking a bit about this, I reached the conclusion that this is all because of the added use of `asIndirectExpr` to convert an expression to a `DataFlow::Node` in the buffer library. The complexity comes from the fact that, if `n` is the dataflow node tracking `*p`, then there's flow from that node to the indirect node tracking `*(++p)`. So by using `node.asIndirectExpr` in the buffer library we would have dataflow through operations that incremented a pointer.
This required a bunch of complexity: It required the need for `localFlowIncrStep` (to track _how much_ the pointer was incremented), and because this …
> C++: Simplify `buffer.qll` repair

- swift/ql/lib/codeql/swift/Unit.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplSpecific.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
- swift/ql/lib/swift.qll
This removes the necessity of importing an internal dataflow file to be able to use the `Unit` class.
> Swift: Move the Unit class to its own file

- cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/VeryLikelyOverrunWrite.expected
We forgot to accept this change in the .expected file before we merged https://github.com/github/codeql/pull/11042.
> C++: Accept test change

- cpp/ql/src/change-notes/2022-11-03-av-rule-76.md
- cpp/ql/src/jsf/4.10 Classes/AV Rule 76.ql
- cpp/ql/test/query-tests/jsf/4.10 Classes/AV Rule 76/AV Rule 76.expected
- cpp/ql/test/query-tests/jsf/4.10 Classes/AV Rule 76/AV Rule 76.qlref
- cpp/ql/test/query-tests/jsf/4.10 Classes/AV Rule 76/test.cpp
The rule wasn't finding anything. The problem was that
```ql
c.getAMemberFunction() instanceof CopyConstructor and
c.getAMemberFunction() instanceof CopyAssignmentOperator
```
was returning compiler generated implicit assignment operators and copy constructors too.
> Fix AV Rule 76

- csharp/ql/src/Metrics/Summaries/LinesOfCode.ql
- java/ql/src/Metrics/Summaries/LinesOfCode.ql
- ql/ql/src/queries/summary/LinesOfUserCode.ql
- ql/ql/src/queries/summary/NumberOfFilesExtractedWithErrors.ql
- ql/ql/src/queries/summary/NumberOfSuccessfullyExtractedFiles.ql
- ruby/ql/src/queries/summary/LinesOfUserCode.ql
- ruby/ql/src/queries/summary/NumberOfFilesExtractedWithErrors.ql
- ruby/ql/src/queries/summary/NumberOfSuccessfullyExtractedFiles.ql
The story of this PR is that I saw "lines" and "Lines" here and wanted to fix the inconsistency :)
```
|                         Metric                          | Value |
+---------------------------------------------------------+-------+
| Total lines of Ruby code in the database                |     9 |
| Total Lines of user written Ruby code in the database   |     9 |
| Total number of files that were extracted with errors   |     0 |
| Total number of files that were extracted without error |     2 |
```
> Summary metrics: Improve consistency of naming

- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/WebView.qll
The `getName = getName` join was happening too early,
before the methods themselves have been enumerated.
> Swift: fix bad join order in WebView/JsExportedSource

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/test/library-tests/dataflow/fields/partial-definition-diff.expected
- cpp/ql/test/library-tests/dataflow/fields/partial-definition-ir.expected
It's somewhat difficult for me to gauge whether the test result are ok. Once I fix the configuration (separate PR), the reported inline IR results do seem to be a strict superset of the AST results.
Fixes: https://github.com/github/codeql-c-team/issues/1341
> C++: Turn `IndirectArgumentOutNode` into a `PartialDefinitionNode`

- java/ql/lib/semmle/code/java/ControlFlowGraph.qll
- java/ql/lib/semmle/code/java/Expr.qll
- java/ql/lib/semmle/code/java/Member.qll
- java/ql/lib/semmle/code/java/Type.qll
- java/ql/lib/semmle/code/java/dataflow/NullGuards.qll
- java/ql/lib/semmle/code/java/dataflow/SSA.qll
- java/ql/lib/semmle/code/java/dataflow/TypeFlow.qll
- java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
- java/ql/lib/semmle/code/java/dispatch/DispatchFlow.qll
- java/ql/lib/semmle/code/java/dispatch/ObjFlow.qll
- java/ql/lib/semmle/code/java/frameworks/Rmi.qll
- java/ql/lib/semmle/code/java/frameworks/jackson/JacksonSerializability.qll
> Java: Fix some join-orders.

- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
- csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected
- csharp/ql/test/library-tests/dataflow/fields/J.cs
- csharp/ql/test/library-tests/dataflow/local/DataFlowStep.expected
- csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected
- Add missing flow from post-update nodes into phi nodes.
- Prevent flow from reads into phi nodes when use-use flow is prohibited.
> C#: Fix flow steps into phi/uncertain def nodes

- .github/actions/fetch-codeql/action.yml
- .github/workflows/compile-queries.yml
- go/ql/src/Metrics/FLinesOfCode.ql
- go/ql/src/Metrics/FLinesOfComment.ql
- go/ql/src/experimental/CWE-400/DatabaseCallInLoop.ql
- go/ql/src/experimental/InconsistentCode/DeferInLoop.ql
- swift/ql/lib/codeql/swift/controlflow/internal/Completion.qll
This new workflow uses the latest stable release of CodeQL to check the formatting of all `*/ql/{src,lib,test}/**/*.{qll,ql}` files, and check that all `*/ql/src/**/*.ql` files compile without without warnings.  
And I've drive-by fixed some compiler warnings such that the new CI workflow passes. 
I investigated whether I wanted to use the `--check-only` flag while checking compilation.  
Not using `--check-only` populates the cache, which makes subsequent much faster, but using `--check-only` is faster when there is no cache.  
I ended up going for an approach where I get the best of both worlds. 
When this workflow runs in a PR it uses `--check-only`, but when the code is merged to main it populates the cache from there.  
So the average PR will get a cache hit on all queries that …
> add workflow that checks compilation of all queries with the latest stable release

- cpp/ql/lib/semmle/code/cpp/commons/Buffer.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
Removes this large TC I saw on openjdk when evaluating `BadlyBoundedWrite.ql`:
```
[2022-11-03 20:23:46] (5s) Starting to evaluate predicate #Buffer#61e3d199::localFlowToExprStep#2Plus#ff/2@7c04651e = HOP fastTC(17471850)
[2022-11-03 20:24:09] (28s)  >>> Relation #Buffer#61e3d199::localFlowToExprStep#2Plus#ff: 312912206 rows using 611 MB
```
Instead we get this nice and fast cached predicate:
```
Tuple counts for DataFlowUtil#47741e1f::localExprFlowStep#2#ff/2@ebe6dafb after 3.4s:
20455857 ~0%      {2} r1 = SCAN DataFlowUtil#47741e1f::simpleLocalFlowStep#2#ff OUTPUT In.1, In.0
11981993 ~26%     {2} r2 = JOIN r1 WITH project#DataFlowUtil#47741e1f::localStepsToExpr#3#fff ON FIRST 1 OUTPUT Lhs.1, Rhs.1 'e2'
2480227  ~45%     {2} r3 = JOIN r2 WITH …
```
> C++: Improve `Buffer.qll` performance

- ruby/ql/src/change-notes/2022-11-04-weak-crypto-hash.md
- ruby/ql/src/queries/security/cwe-327/BrokenCryptoAlgorithm.ql
- ruby/ql/test/query-tests/security/cwe-327/BrokenCryptoAlgorithm.expected
- ruby/ql/test/query-tests/security/cwe-327/broken_crypto.rb
Weak hash algorithms such as MD5 and SHA1 are often used in non security sensitive contexts and reporting all uses is far too noisy.
Fixes: https://github.com/github/codeql/issues/11107
> Ruby: Improve weak crypto query

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
I am guessing this was intended, since otherwise `Position::toString` is always empty.
> C++: Let `(Indirect|Direct)Position` be sub classes of `Position`

- codeql-workspace.yml
- javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml
- javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/qlpack.yml
- javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml
- javascript/ql/experimental/adaptivethreatmodeling/test/qlpack.yml
This fixes the ATM PR checks, which [broke on main](https://github.com/github/codeql/actions/runs/3392995797/jobs/5639827326) as a result of the JavaScript pack being updated to use `${workspace}` in https://github.com/github/codeql/pull/11004.
> ATM: Fix CodeQL pack workspace references

- swift/ql/lib/codeql/swift/elements/expr/ApplyExpr.qll
- swift/ql/src/queries/Security/CWE-079/UnsafeWebViewFetch.ql
- swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql
Add and use a predicate `ApplyExpr.getArgumentByParamName` (please say if you can think of a cleaner name for it).  This makes it easier to get an argument by its parameter name, rather than the argument name (which is often anonymous) or index (usually the preferred method, but sometimes varies across the functions of interest).
This will be used in a couple of upcoming queries in addition to the two I've updated here.
> Swift: Add and use ApplyExpr.getArgumentByParamName.

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/test/kotlin/library-tests/jvmoverloads-annotation/PrintAst.expected
- java/ql/test/kotlin/library-tests/jvmoverloads_flow/test.expected
This avoids extracting the default value expression in more than one place, which causes inconsistencies for e.g. anonymous classes, which expect to have a single `new` expression associated.
> Kotlin: use `$default` functions to implement `@JvmOverloads`

- java/kotlin-extractor/src/main/kotlin/ExternalDeclExtractor.kt
Previously individual top-level file declarations relied on their corresponding file-class to declare their `File` instance, but this can be scuppered by a Java extractor replacing that file-class and identifying a different file location.
> Kotlin: always populate the `files` table

- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/ql/integration-tests/all-platforms/kotlin/kotlin_java_lowering_wildcards/JavaDefns2.java
- java/ql/integration-tests/all-platforms/kotlin/kotlin_java_lowering_wildcards/kotlinuser.kt
- java/ql/integration-tests/all-platforms/kotlin/kotlin_java_lowering_wildcards/test.expected
- java/ql/integration-tests/all-platforms/kotlin/kotlin_java_lowering_wildcards/test.py
- java/ql/integration-tests/all-platforms/kotlin/kotlin_java_lowering_wildcards/test.ql
This fixes two mistakes: return-type extraction not imposing a wildcard where a Java prototype explicitly uses one, and nested wildcard detection quietly failing due to not looking through a `JavaWildcardType` correctly.
I add a variant of the `kotlin_java_lowering_wildcards` test where Java prototypes are only seen from Kotlin, to be sure extraction is working as expected.
> Kotlin: fix extraction of Java nested wildcards; wildcards in return types

- swift/ql/src/queries/Security/CWE-916/InsufficientHashIterations.qhelp
- swift/ql/src/queries/Security/CWE-916/InsufficientHashIterations.ql
- swift/ql/src/queries/Security/CWE-916/InsufficientHashIterations.swift
- swift/ql/test/query-tests/Security/CWE-916/InsufficientHashIterations.expected
- swift/ql/test/query-tests/Security/CWE-916/InsufficientHashIterations.qlref
- swift/ql/test/query-tests/Security/CWE-916/test.swift
Using hash functions with less than 1,000 iterations is not secure. That scheme is vulnerable to password cracking attacks due to having an insufficient level of computational effort.
The rule currently supports all ciphers that the CryptoSwift API provides, but we can always extend it further if more cophers are added.
> Swift: detect hash functions with low # of iterations

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/consistency-queries/callArgs.ql
- java/ql/lib/semmle/code/java/Element.qll
- java/ql/test/kotlin/library-tests/classes/PrintAst.expected
- java/ql/test/kotlin/library-tests/exprs/PrintAst.expected
- java/ql/test/kotlin/library-tests/exprs/exprs.expected
- java/ql/test/kotlin/library-tests/exprs_typeaccess/PrintAst.expected
- java/ql/test/kotlin/library-tests/methods/exprs.expected
Additionally a consistency check is also added to compare argument count of calls with the parameter count of the call targets.
> Kotlin: Extract missing arguments of enum constructor calls

- java/ql/test/library-tests/multiply-bounded-wildcards/Test.java
- java/ql/test/library-tests/multiply-bounded-wildcards/test.expected
- java/ql/test/library-tests/multiply-bounded-wildcards/test.ql
- java/ql/test/library-tests/wildcards-and-captured-types/Test.java
- java/ql/test/library-tests/wildcards-and-captured-types/test.ql
This exercises several cases of variables bounded both by a wildcard and by a bound on the type parameter, checking that the extractor strips the wildcards and captures to decide on a concrete type for the parameters and return values.
> Java: Add test for multiply-bounded wildcards

- java/ql/lib/semmle/code/java/security/regexp/NfaUtils.qll
- javascript/ql/lib/semmle/javascript/security/regexp/NfaUtils.qll
- javascript/ql/test/query-tests/Security/CWE-116/IncompleteSanitization/IncompleteMultiCharacterSanitization.expected
- javascript/ql/test/query-tests/Security/CWE-116/IncompleteSanitization/tst-multi-character-sanitization.js
- python/ql/lib/semmle/python/security/regexp/NfaUtils.qll
- ruby/ql/lib/codeql/ruby/security/regexp/NfaUtils.qll
The `cc = getCanonicalCharClass(term)` predicate got a char-class for the canonical representative `term`, so it was not meant to be used unless you already had the canonical representative.  
That wasn't how it was used in `js/incomplete-multi-character-sanitization`, which caused a FN when [I converted the regex code to a shared pack](https://github.com/github/codeql/pull/11061).  
(Some sorting got slightly changed, which changed the canonicalization a tiny bit).  
Evaluation looks good: [Python](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11071-2-python/reports), [Ruby](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11071-3-ruby__1/reports), [Java](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11071-0-java/reports), …
> ReDoS: fix canonicalization in NfaUtils

- swift/ql/src/queries/Security/CWE-760/ConstantSalt.qhelp
- swift/ql/src/queries/Security/CWE-760/ConstantSalt.ql
- swift/ql/src/queries/Security/CWE-760/ConstantSalt.swift
- swift/ql/test/query-tests/Security/CWE-760/ConstantSalt.expected
- swift/ql/test/query-tests/Security/CWE-760/ConstantSalt.qlref
- swift/ql/test/query-tests/Security/CWE-760/test.swift
Constant salts should not be used for password hashing. Data hashed using constant salts are vulnerable to dictionary attacks, enabling attackers to recover the original input.
The rule currently supports all ciphers that the CryptoSwift API provides, but we can always extend it further if more APIs are added.
> Swift: detect the use of constant salts

- java/ql/src/Violations of Best Practice/Dead Code/UnreadLocal.ql
- java/ql/test/kotlin/query-tests/UnreadLocal/UnreadLocal.expected
- java/ql/test/kotlin/query-tests/UnreadLocal/UnreadLocal.qlref
- java/ql/test/kotlin/query-tests/UnreadLocal/test.kt
Based on https://github.com/github/codeql/pull/11014.
> Kotlin: exclude loop variables on ranges from 'unused locals' check

- docs/codeql/writing-codeql-queries/about-data-flow-analysis.rst
- docs/codeql/writing-codeql-queries/creating-path-queries.rst
When looking at the preview of the new Ruby articles, I realized that we were missing a couple of links in general articles.
This PR adds those links.
@aibaars - this is targeted at the 2.11.3 branch as I don't think this is urgent and the docs updates can wait until the next release of the CLI.
> Ruby: add a couple of missing links to a new article

- docs/codeql/ql-language-reference/ql-language-specification.rst
This adds `instanceof` in classes to the QLSpec. I haven't added versions because this has been in the language for so long that it should be available for any supported version.
> QL Spec: Add instanceof in classes

- cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/ref.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.ql
Remaining cases where IR use-use dataflow seems to perform worse than AST dataflow:
* https://github.com/github/codeql/blob/89c5e3df1f5453c7fe3c6e70c6243ef4c4b0f4a1/cpp/ql/test/library-tests/dataflow/dataflow-tests/ref.cpp#L59
* https://github.com/github/codeql/blob/89c5e3df1f5453c7fe3c6e70c6243ef4c4b0f4a1/cpp/ql/test/library-tests/dataflow/dataflow-tests/ref.cpp#L65
* https://github.com/github/codeql/blob/89c5e3df1f5453c7fe3c6e70c6243ef4c4b0f4a1/cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp#L92
* https://github.com/github/codeql/blob/89c5e3df1f5453c7fe3c6e70c6243ef4c4b0f4a1/cpp/ql/test/library-tests/dataflow/dataflow-tests/true_upon_entry.cpp#L13
* https://github.com/github/codeql/blob/89c5e3df1f5453c7fe3c6e70c6243ef4c4b0f4a1/cpp/ql/test/library-tests/dataflow/dataflow-tests/ …
> C++: Fix the use-use dataflow configuration in `dataflow/dataflow-tests`

- java/ql/lib/change-notes/2022-10-19-android-startactivities-summaries.md
- java/ql/lib/semmle/code/java/dataflow/FlowSummary.qll
- java/ql/lib/semmle/code/java/frameworks/android/Intent.qll
- java/ql/test/library-tests/frameworks/android/intent/TestStartActivityToGetIntent.java
Uses `SyntheticCallable`s and `SyntheticGlobal`s to pair each `startActivities` call to `getIntent` calls in the components targeted by the intent(s).
Props to @aschackmull for this, which is the proper solution to the problem we discussed in https://github.com/github/codeql/pull/10660#discussion_r986814913.
> Java: Add flow summaries for startActivities

- ruby/ql/lib/codeql/ruby/regexp/internal/RegExpConfiguration.qll
Thanks to DCA for [highlighting the fact](https://github.com/github/codeql-dca-main/tree/data/hvitved/PR-11087-4-ruby__3/reports#stage-timings) that we were recomputing the flow summary compilation.
> Ruby: Avoid stage recomputation

- .github/workflows/swift.yml
- swift/actions/print-unextracted/action.yml
- swift/extractor/print_unextracted/BUILD.bazel
- swift/extractor/print_unextracted/main.cpp
Currently unextracted entities can be printed with
```bash
bazel run //swift/extractor/print_unextracted
```
This is also run by the build jobs and printed in the action logs:
Current unextracted entities:
```
Unextracted Decls:
OpaqueTypeDecl
PoundDiagnosticDecl
MissingMemberDecl
Unextracted Stmts:
FailStmt
PoundAssertStmt
Unextracted Exprs:
RegexLiteralExpr
ObjectLiteralExpr
OverloadedDeclRefExpr
DynamicMemberRefExpr
DynamicSubscriptExpr
UnresolvedSpecializeExpr
PropertyWrapperValuePlaceholderExpr
AppliedPropertyWrapperExpr
PostfixUnaryExpr
ArrowExpr
CodeCompletionExpr
EditorPlaceholderExpr
PackExpr
Unextracted Patterns:
Unextracted Types:
ErrorType
UnresolvedType
PlaceholderType
OpaqueTypeArchetypeType
SequenceArchetypeType
SILFunctionType
SILBlockStoragType
SILBoxType
SILTokenType …
```
> Swift: print unextracted entities

- swift/ql/lib/codeql/swift/dataflow/FlowSources.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/String.qll
- swift/ql/src/queries/Summary/FlowSources.ql
- swift/ql/src/queries/Summary/SummaryStats.ql
- swift/ql/test/library-tests/dataflow/flowsources/FlowSources.expected
- swift/ql/test/library-tests/dataflow/flowsources/string.swift
Adds a `LocalFlowSource` class to complement `RemoteFlowSource` (both under a `FlowSource` parent class, as it is in CPP).
Adds a handful of local (and remote) flow sources for `String`s, demonstrating that this is all working correctly.  At some point we will want local flow sources for user input as well, but this requires a bit more research and is probably not a high priority.
> Swift: Add LocalFlowSource class and a few sources.

- .github/workflows/compile-queries.yml
I changed all the cache keys so it won't hit the old caches.  
I didn't find a way to have `actions/cache` run in a "read-only" mode, so I'm using different cache keys depending on whether the workflow runs in a PR or on `main`.  
When running on this PR the cache is empty, so the workflow is slow.  
But this PR should help get better cache hits in the future.
> CI: try only to fill the compilation cache from main in the compile-queries workflow

- ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll
- ruby/ql/test/library-tests/dataflow/local/TaintStep.expected
Fixes a bug in the default taint steps, which caused us to miss some taint steps out of collections.
[Evaluation](https://github.com/github/codeql-dca-main/issues/8429) shows 538 new tainted nodes and 5 new alerts. 1 of the new alerts seem plausible and the other 4 are due to a missed sanitizer which will most likely be fixed by https://github.com/github/codeql/pull/11114.
> Ruby: handle knownOrUnkown in default taint step

- javascript/ql/lib/semmle/javascript/PackageExports.qll
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/sublib/other.js
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/sublib/sub.js
Recognizes the sources for CVE-2022-37616.  
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11095-0-javascript__1/reports).
> JS: recognize more re-exported values as exported

- csharp/ql/src/utils/model-generator/CaptureSinkModels.ql
- csharp/ql/src/utils/model-generator/CaptureSourceModels.ql
- csharp/ql/src/utils/model-generator/internal/CaptureModels.qll
- csharp/ql/src/utils/model-generator/internal/CaptureModelsSpecific.qll
- csharp/ql/src/utils/model-generator/internal/CaptureSummaryFlow.qll
- java/ql/src/utils/model-generator/CaptureSinkModels.ql
- java/ql/src/utils/model-generator/CaptureSourceModels.ql
- java/ql/src/utils/model-generator/internal/CaptureModels.qll
- java/ql/src/utils/model-generator/internal/CaptureModelsSpecific.qll
- java/ql/src/utils/model-generator/internal/CaptureSummaryFlow.qll
Let's undo the configuration footgun firing. We shouldn't have all of the model generation configurations active at the same time.
Also includes a minor strengthening of the Java to-sink source definition (pushed in some magic).
cc: @tamasvajk @michaelnebel
> Java/C#: Split active configurations for model generator

- .github/workflows/compile-queries.yml
Followup to https://github.com/github/codeql/pull/11162
> CI: compile-queries: use cache when running on main, and support more base-branches

- swift/codegen/lib/schema/defs.py
- swift/codegen/test/test_schema.py
This is to avoid problems like [this one](https://github.com/github/codeql/pull/11190#discussion_r1018122475).
> Swift: avoid wrongly using `doc` instead of `desc` for properties

- csharp/ql/src/utils/model-generator/internal/CaptureModels.qll
- csharp/ql/src/utils/model-generator/internal/CaptureModelsSpecific.qll
- java/ql/src/utils/model-generator/internal/CaptureModels.qll
- java/ql/src/utils/model-generator/internal/CaptureModelsSpecific.qll
Variable-capture-as-jump-steps discards the call context, which is crucial to sink model generation precision.
> Java: Improve sink model generation precision by excluding variable capture.

- cpp/ql/test/library-tests/dataflow/taint-tests/taint.ql
The complexity seems a left-over from before these tests were turned into inline expectation tests, where the aim seems to have been to have exactly one sink node for each `sink` call. Multiple sink nodes for the same `sink` call are not made visible in the inline expecation tests, and I am not conviced this was very useful before, so remove the complexity.
> C++: Simplify dataflow taint test query

- cpp/ql/test/TestUtilities/dataflow/FlowTestCommon.qll
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.ql
- cpp/ql/test/library-tests/dataflow/taint-tests/arrayassignment.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/bsd.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/constructor_delegation.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/copyableclass.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/copyableclass_declonly.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/format.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/map.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/movableclass.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/set.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/smart_pointer.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/standalone_iterators.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/string.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/stringstream.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/structlikeclass.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/swap1.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/swap2.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/taint.ql
- cpp/ql/test/library-tests/dataflow/taint-tests/vector.cpp
This makes it easier to fix the library tests for me, and we should probably keep these around anyway until we remove the AST-based dataflow library.
> C++: Re-introduce the `ast` annotations in the taint tests and related test infrastructure

- .github/workflows/ql-for-ql-build.yml
- .github/workflows/ql-for-ql-dataset_measure.yml
- .github/workflows/ql-for-ql-tests.yml
`set-output` is deprecated and will stop working soon: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 
CodeQL-action was updated to the latest `main` (with the patch that adds `ql` as another language).
> QL-for-QL: don't use the deprecated set-output feature in github-actions

- ruby/ql/lib/codeql/ruby/security/UnsafeShellCommandConstructionCustomizations.qll
- ruby/ql/test/query-tests/security/cwe-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected
- ruby/ql/test/query-tests/security/cwe-078/UnsafeShellCommandConstruction/impl/unsafeShell.rb
Inspired by CVE-2021-33473 (recognizes a sink there). 
[Evaluation looks OK](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11191-0-ruby__2/reports).  
There is one new result, which looks benign (and there was already an alert on the line below).
> RB: add join(" ") calls as a sink for rb/shell-command-constructed-from-input

- swift/ql/src/queries/Security/CWE-1204/StaticInitializationVector.qhelp
- swift/ql/src/queries/Security/CWE-1204/StaticInitializationVector.ql
- swift/ql/src/queries/Security/CWE-1204/StaticInitializationVector.swift
- swift/ql/test/query-tests/Security/CWE-1204/StaticInitializationVector.expected
- swift/ql/test/query-tests/Security/CWE-1204/StaticInitializationVector.qlref
- swift/ql/test/query-tests/Security/CWE-1204/test.swift
Using a static initialization vector (IV) for encryption is not secure. To maximize encryption and prevent dictionary attacks, IVs should rather be unique and unpredictable (e.g., randomly generated).
The rule currently supports all ciphers that the CryptoSwift API provides, but we can always extend it further if more APIs are added.
> Swift: detect the use of static initialization vectors

- swift/ql/src/queries/Security/CWE-259/ConstantPassword.qhelp
- swift/ql/src/queries/Security/CWE-259/ConstantPassword.ql
- swift/ql/src/queries/Security/CWE-259/ConstantPassword.swift
- swift/ql/test/query-tests/Security/CWE-259/ConstantPassword.expected
- swift/ql/test/query-tests/Security/CWE-259/ConstantPassword.qlref
- swift/ql/test/query-tests/Security/CWE-259/test.swift
Deriving password-based encryption keys using hard-coded passwords is insecure, because the generated key may be easily discovered. Data hashed using constant salts are vulnerable to dictionary attacks, enabling attackers to recover the original input.
The rule currently supports all ciphers that the CryptoSwift API provides, but we can always extend it further if more APIs are added.
> Swift: detect the use of constant passwords for password-based encryption

- javascript/ql/lib/semmle/javascript/security/internal/SensitiveDataHeuristics.qll
- javascript/ql/test/query-tests/Security/CWE-312/CleartextLogging.expected
- javascript/ql/test/query-tests/Security/CWE-312/passwords.js
- python/ql/lib/semmle/python/security/internal/SensitiveDataHeuristics.qll
- ruby/ql/lib/codeql/ruby/security/internal/SensitiveDataHeuristics.qll
Fixes #11148
Evaluations were uneventful: [Ruby](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11178-2-ruby/reports), [Python](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11178-1-python/reports), [JavaScript](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11178-0-javascript/reports)
> JS/RB/PY: Recognize `passcode` as sensitive

- swift/extractor/print_unextracted/main.cpp
- swift/extractor/translators/TranslatorBase.h
This was still printing explicitly ignored classes.
Here's the current output:
```
Unextracted Expr subclasses:
RegexLiteralExpr
Unextracted Type subclasses:
ErrorType
UnresolvedType
SequenceArchetypeType
ParameterizedProtocolType
TypeVariableType
```
> Swift: fix printing of unextracted entities

- .github/workflows/compile-queries.yml
- .github/workflows/js-ml-tests.yml
- .github/workflows/ruby-qltest.yml
- .github/workflows/swift.yml
We now have [this format check](https://github.com/github/codeql/blob/main/.github/workflows/compile-queries.yml#L49) which checks all the languages all the time, so there's no need for language specific format checks.
> CI: remove langauge specific format checks

- csharp/ql/lib/semmle/code/csharp/Type.qll
- csharp/ql/src/Telemetry/ExternalApi.qll
- csharp/ql/src/Telemetry/ExternalLibraryUsage.ql
- csharp/ql/src/meta/frameworks/UnsupportedExternalAPIs.ql
- csharp/ql/test/query-tests/Telemetry/LibraryUsage/ExternalLibraryUsage.expected
- csharp/ql/test/query-tests/Telemetry/LibraryUsage/SupportedExternalTaint.expected
- csharp/ql/test/query-tests/Telemetry/SupportedExternalSinks/SupportedExternalSinks.expected
- csharp/ql/test/query-tests/Telemetry/SupportedExternalSources/SupportedExternalSources.expected
It turns out that the Telemetry we emit for API calls in C# needs to be changed.
- We have removed the (assembly) file name as the same method can be located in different assemblies across version, which clutters the picture of the usage.
- We have aligned the counting to only count *calls* and not the possible (runtime) dispatch targets.
- We now only consider callables that are effectively public.
This should align the implemetation a bit better with Java.
With respect to testing of the PR
- The unit tests behaves as expected (the coverage is not optimal, but still a good indication that everything works as expected).
- I have tried to run some of the queries locally against .NET Runtime and .NET EfCore and the results looks reasonable (ie. the results doesn't contain any "noise", but …
> C#: Telemetry query updates.

- .github/workflows/compile-queries.yml
The previous approach worked on my local machine, but apparently that didn't translate to the cloud.  
So now I'm using the `find` command instead, which checks formatting on all files.  
For some reason the previous approach skipped a lot of files, and I'm not sure why.
> CI: use `find` in the format check to fix it

- ql/ql/src/codeql_ql/performance/VarUnusedInDisjunctQuery.qll
- ql/ql/src/queries/performance/VarUnusedInDisjunct.ql
- ql/ql/src/queries/style/OverrideAny.ql
All current results are benign because the type of the unmentioned parameter is small.  
But it is very hard to statically determine that the  type is small. (E.g. one is an abstract class, where all (transitive) overrides are small).  
The fix to remove the alert for the benign results is just to insert `exists(param)` instead of `any()`.   
I did try to remove the `pred.hasAnnotation("override")` restriction, but that just gave me more noise.
> QL: Query for detecting unused parameter in override methods

- cpp/ql/lib/semmle/code/cpp/models/implementations/StdString.qll
Follow-up to https://github.com/github/codeql/pull/11212. I played around a bit in that PR with:
```codeql
int getAnIteratorParameterIndex() { this.getParameter(result).getType() instanceof Iterator }
```
and
```codeql
int getAnIteratorParameterIndex() { this.getParameter(result).getUnspecifiedType() instanceof Iterator }
```
I eventually went for the first, but never tested that on the use-use dataflow feature branch. Turns out that doesn't work, as the iterator is typedef'ed in `basic_string` in out taint tests. So, we either need `getUnspecifiedType` or make sure the typedef is recoginzed as an iterator. The latter seems safer, as the C++ standard does not guarantee that `basic_string::iterator` needs to be a typedef.
> C++: Recognize `basic_string::iterator` as an iterator

- config/identical-files.json
- shared/regex/change-notes/2022-09-26-initial-version.md
- shared/regex/codeql-pack.lock.yml
- shared/regex/codeql/regex/OverlyLargeRangeQuery.qll
- shared/regex/codeql/regex/RegexTreeView.qll
- shared/regex/codeql/regex/nfa/BadTagFilterQuery.qll
- shared/regex/codeql/regex/nfa/ExponentialBackTracking.qll
- shared/regex/codeql/regex/nfa/NfaUtils.qll
- shared/regex/codeql/regex/nfa/RegexpMatching.qll
- shared/regex/codeql/regex/nfa/SuperlinearBackTracking.qll
- shared/regex/qlpack.yml
This PR introduces a new shared `regex` pack containing various shared code that analyze regular expressions.   
All these analyses depend on a single `RegexTreeViewSig` signature, that describes a regex as a tree structure.  
I don't expect that a shared regex parser will ever make it into this pack.  
This is just the shared pack, there are separate PRs that will integrate this shared pack with each language (see bottom).   
A complete PR, that combines all the part, can be found here: https://github.com/github/codeql/pull/10604 (ugly commit history). 
I ended up basing locations on `hasLocationInfo` as not all languages had `Location` objects for all the regex terms.  
This also required some small rewrites in the implementation.  
The class hierarchy inside `RegexTreeViewSig` was …
> ReDoS: add a shared regex pack

- python/ql/lib/semmle/python/Concepts.qll
- ruby/ql/lib/change-notes/2022-11-10-arel-sql.md
- ruby/ql/lib/codeql/ruby/Concepts.qll
- ruby/ql/lib/codeql/ruby/frameworks/Arel.qll
- ruby/ql/lib/codeql/ruby/security/SqlInjectionCustomizations.qll
- ruby/ql/lib/codeql/ruby/security/SqlInjectionQuery.qll
- ruby/ql/src/change-notes/2022-11-10-arel-sql.md
- ruby/ql/src/queries/security/cwe-089/SqlInjection.ql
- ruby/ql/test/library-tests/frameworks/arel/SqlConstruction.expected
- ruby/ql/test/library-tests/frameworks/arel/SqlConstruction.ql
- ruby/ql/test/query-tests/security/cwe-089/ArelInjection.rb
- ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected
The [docs for `Arel.sql` say](https://api.rubyonrails.org/classes/Arel.html):
> Great caution should be taken to avoid SQL injection vulnerabilities. This method should not be used with unsafe values such as request parameters or model attributes.
This also updates `rb/sql-injection` to:
1. use `...Query.qll` and `...Customizations.qll` files like other queries
2. consider `SqlConstruction`s as sinks
So reviewing the individual commits may make it a bit easier to review the new parts.
Plus a drive-by Python comment fix.
> Ruby: add `SqlConstruction` concept, and implement it for calls to `Arel.sql`

- swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Data.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/InputStream.qll
- swift/ql/lib/codeql/swift/security/XXE.qll
- swift/ql/lib/codeql/swift/security/XXEQuery.qll
- swift/ql/src/queries/Security/CWE-611/XXE.qhelp
- swift/ql/src/queries/Security/CWE-611/XXE.ql
- swift/ql/src/queries/Security/CWE-611/XXEBad.swift
- swift/ql/src/queries/Security/CWE-611/XXEGood.swift
- swift/ql/test/query-tests/Security/CWE-311/CleartextTransmission.expected
- swift/ql/test/query-tests/Security/CWE-311/testSend.swift
- swift/ql/test/query-tests/Security/CWE-611/XXETest.ql
- swift/ql/test/query-tests/Security/CWE-611/testXXE.swift
Adds a new query to cover XXE vulnerabilities. Only covers `XMLParser` sinks for now, follow up PRs will add more sinks in third-party libraries.
Note that the CSV summaries added for the classes `Data` and `InputStream` are the bare minimum for the XXE tests to work properly. These classes need proper modeling, which deserve their own PRs.
> Swift: Add new query for XML External Entities (XML) vulnerabilities

- csharp/ql/consistency-queries/SsaConsistency.ql
- ruby/ql/consistency-queries/SsaConsistency.ql
- shared/ssa/codeql/ssa/Ssa.qll
Reverts github/codeql#11074
Only to be merged once type signatures are supported.
> Revert "Revert "SSA: Turn consistency predicates into `query` predicates""

- java/ql/src/Telemetry/ExtractorInformation.ql
This will give info about which kotlinc versions are used.
> Java/Kotlin: Add compilation info to telemetry

- go/extractor/trap/labels.go
- go/extractor/trap/trapwriter.go
The TRAP writer already buffers writes before emitting to file, but running gzip compression is also fairly costly (especially if you only do it a couple of bytes at a time). Thus, this injects another buffer that collects the emitted tuples in string form, and only triggers gzip compression once the buffer is full. In my local testing, this buffering was actually more beneficial than the one between gzip and file (likely because the gzip writer already emits data in chunks), but that one is still beneficial.
> Go: Optimize trap.Writer by buffering gzip writes

- java/kotlin-extractor/src/main/kotlin/utils/Logger.kt
- java/ql/src/Telemetry/ExtractorInformation.ql
This isn't as simple as counting them, as `CODEQL_EXTRACTOR_KOTLIN_DIAGNOSTIC_LIMIT` means that they don't all get written. Also discovered that we weren't writing the message about having hit the limit to the database, so that's now done too.
> Kotlin: Add total number of diagnostics to telemetry

- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/ATMConfig.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointCharacteristics.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointTypes.qll
This PR simply follows the chain of logic that determines that an endpoint is not a sink [here](https://github.com/github/codeql/blob/387e57546bf7352f7c1cfe781daa1a3799b7063e/javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/ExtractEndpointData.qll#L75), and converts all the reasoning into `EndpointCharacteristic`s. These new characteristics will get used in [the next PR](https://github.com/github/ml-ql-adaptive-threat-modeling/issues/2098) to select endpoints as negative training samples.
Timing checks:
- ✅ KPI timing experiment: https://github.com/github/codeql-dca-main/issues/8438
- ✅ The local runtime of `endpoint_large_scale/ExtractEndpointData` and `endpoint_large_scale/ExtractEndpointDataTraining` are not impacted
closes …
> Non-sink endpoint characteristics

- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointCharacteristics.qll
In response to my own comment: https://github.com/github/codeql/pull/11174#discussion_r1018036893
> ATM: remove superfluous class in EndpointCharacteristics hierarchy

- cpp/ql/test/library-tests/dataflow/smart-pointers-taint/taint.ql
- cpp/ql/test/library-tests/dataflow/smart-pointers-taint/test.cpp
I had previously omitted this, as I had not looked at the smart pointer test yet.
> C++: Reintroduce the AST testing configuration for the smart pointer test too

- csharp/ql/src/Security Features/CWE-114/AssemblyPathInjection.ql
- csharp/ql/src/Security Features/CWE-321/HardcodedEncryptionKey.ql
- csharp/ql/test/query-tests/Security Features/CWE-114/AssemblyPathInjection/AssemblyPathInjection.expected
- csharp/ql/test/query-tests/Security Features/CWE-321/HardcodedSymmetricEncryptionKey/HardcodedSymmetricEncryptionKey.expected
Something I randomly stumbled upon a while ago.  
The two queries look very much like `@kind path-problems` queries, and can easily be converted to that format, but they were `@kind problem` queries for some reason? 
[This blackbird search](https://cs.github.com/github/codeql?q=path%3A%2F.*%5C%2Fsrc%5C%2F.*%5C.ql%2F+%2Fwhere+.*%5C.hasFlow%5C%28%2F+) helped me find them. 
Does this need a change-note?
> C#: update cs/assembly-path-injection cs/hardcoded-key to path-problems

- swift/ql/lib/codeql/swift/dataflow/FlowSteps.qll
- swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPrivate.qll
Adds the abstract class `AdditionalTaintStep` to allow creating flow steps that apply to all taint tracking configurations.
> Swift: Add `AdditionalTaintStep`

- .pre-commit-config.yaml
- swift/integration-tests/posix-only/cross-references/test.py
- swift/integration-tests/posix-only/frontend-invocations/test.py
- swift/integration-tests/posix-only/hello-world/test.py
- swift/integration-tests/posix-only/partial-modules/test.py
- swift/integration-tests/runner.py
- swift/schema.py
While PEP8 mandates those, they look bad in the schema file.
`autopep8` already ignores those, and they were single newlines at some point until an overeager IDE has "fixed" them at some point without me realizing.
Also, the pre-commit configuration was updated to take `schema.py` into account.
> Swift: remove double newlines in schema

- swift/codegen/generators/cppgen.py
- swift/codegen/test/test_cppgen.py
IPA classes are not only those explicitly marked with `@synth` in the schema, but also those non-final classes that only have `@synth` descendants.
> Swift: remove IPA classes from `cppgen`

- java/ql/src/utils/stub-generator/Stubs.qll
It appears that compiled `.class` files are able to contain identifiers that are not valid in Java source code. 
For instance, when stubing `okhttp`, I ran into several identifiers beginning with `-deprecated_`.
This PR excludes these identifiers from being stubbed.
> Java: Stub generator: Exclude invalid identifiers from generated stubs

- csharp/ql/consistency-queries/SsaConsistency.ql
- csharp/ql/lib/semmle/code/csharp/dataflow/SSA.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
- csharp/ql/test/library-tests/dataflow/ssa/SSAPhiRead.expected
- csharp/ql/test/library-tests/dataflow/ssa/SSAPhiRead.ql
- csharp/ql/test/library-tests/dataflow/ssa/Test.cs
- ruby/ql/consistency-queries/SsaConsistency.ql
- ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
- ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected
- ruby/ql/test/library-tests/dataflow/local/Nodes.expected
- ruby/ql/test/library-tests/dataflow/local/TaintStep.expected
- ruby/ql/test/library-tests/dataflow/local/local_dataflow.rb
- ruby/ql/test/library-tests/variables/parameter.expected
- ruby/ql/test/library-tests/variables/ssa.expected
- ruby/ql/test/library-tests/variables/ssa.ql
- ruby/ql/test/library-tests/variables/ssa.rb
- ruby/ql/test/library-tests/variables/varaccess.expected
- ruby/ql/test/library-tests/variables/variable.expected
- ruby/ql/test/library-tests/variables/varscopes.expected
- shared/ssa/codeql/ssa/Ssa.qll
- swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
This PR follows up on https://github.com/github/codeql/pull/10035 by exposing "phi read" definitions in the shared SSA library.
The motivation for exposing phi reads is to be able to avoid the same potential combinatorial explosion that we also avoid by including normal phi nodes in the data flow graph:
```mermaid
graph TD;
A-->read_phi;
B-->read_phi;
C-->read_phi;
read_phi-->D;
read_phi-->E;
read_phi-->F;
```
Assuming that `A,...,F` read the same underlying variable as `read_phi`, one can reduce the number of data flow edges from 9 (quadratic) to 6 (linear) by including the `read_phi` join-point.
This PR does not actually include read-phis in the data flow graph for any languages (follow-up work, e.g. https://github.com/github/codeql/pull/10927), it merely exposes them.
The old API …
> SSA: Expose phi-read nodes

- .github/workflows/compile-queries.yml
The cache was append-only, so it would keep monotonically increasing in size.  
It started at ~60mb, but it had grown to ~250mb.  
This PR makes sure that only the cache objects needed are preserved.  
The CodeQL CLI accepts a `--compilation-cache` option where it additionally reads cache objects from.  
But the CLI will still populate the relevant cache folders. 
Thereby effectively moving the relevant cache from the directory specified `--compilation-cache` into the relevant folders.  
In a [test run](https://github.com/github/codeql/actions/runs/3480558055/jobs/5820513882) this decreased the cache size from 251mb to 62mb.   
(See the cache read and cache write steps).  
This was inspired by DCA that uses `--compilation-cache` to achieve the same effect.
> CI: clean up the cache when compiling on main

- cpp/ql/test/query-tests/Security/CWE/CWE-078/SAMATE/ExecTainted/ExecTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-114/SAMATE/UncontrolledProcessOperation/UncontrolledProcessOperation.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowDestination.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-319/UseOfHttp/UseOfHttp.expected
I forgot to accept these test changes in https://github.com/github/codeql/pull/11218.
There are no result changes. This is just changing some paths.
> C++: Accept test changes on the use-use flow branch

- .github/workflows/compile-queries.yml
- go/ql/examples/snippets/incompleteswitchoverenum.ql
The cache read doesn't hit anything, but I think that's from the `path:` changing.  
The cache write looks fine, and is slightly larger than before, so it seems to be working. 
Test run simulating what happens when running on `main`: https://github.com/github/codeql/actions/runs/3492067983/jobs/5845431720
> CI: Also compile the `examples` folder

- cpp/ql/src/Likely Bugs/Conversion/CastArrayPointerArithmetic.ql
Before:
```ql
[2022-11-17 18:08:23] Evaluated non-recursive predicate #select#cpe#1235#ffff@306862je in 40917ms (size: 10).
Evaluated relational algebra for predicate #select#cpe#1235#ffff@306862je with tuple counts:
700124  ~0%    {3} r1 = JOIN DataFlowImpl#9021cc4c::PathNode::getNode#0#dispred#ff WITH DataFlowImpl#9021cc4c::PathNode#f ON FIRST 1 OUTPUT Lhs.0, Lhs.1, Lhs.0
9754  ~0%    {4} r2 = JOIN r1 WITH DataFlowImpl#9021cc4c::flowsTo#5#fffff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Lhs.1, Lhs.2
9754  ~0%    {4} r3 = JOIN r2 WITH DataFlowImpl#9021cc4c::PathNode#f ON FIRST 1 OUTPUT Lhs.0, Lhs.1, Lhs.2, Lhs.3
9754  ~3%    {6} r4 = JOIN r3 WITH DataFlowImpl#9021cc4c::PathNode::getNode#0#dispred#ff ON FIRST 1 OUTPUT Lhs.2, Lhs.1, Lhs.3, Lhs.0, Rhs.1, Lhs.0
9754  ~4%    {6} r5 = JOIN r4 …
```
> C++: Fix join order in `cpp/upcast-array-pointer-arithmetic`

- ql/ql/src/codeql_ql/ast/Ast.qll
- ql/ql/test/printAst/Foo.qll
- ql/ql/test/printAst/printAst.expected
Fixes this FP: https://github.com/github/codeql/security/code-scanning/77304
> QL: fix non-attached annotations for newtype branches

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/test/library-tests/dataflow/fields/partial-definition-diff.expected
- cpp/ql/test/library-tests/dataflow/fields/partial-definition-ir.expected
- cpp/ql/test/library-tests/dataflow/taint-tests/smart_pointer.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
This implements https://github.com/github/codeql/pull/5196, but for IR-based use-use dataflow library. The motivation for this "hack" is to get flow in the following example (which I've taken from our library tests):
```cpp
class C_const_member_function {
char* data_;
public:
char* data() const { return data_; }
};
void test_with_const_member(char* source) {
C_const_member_function c;
memcpy(c.data(), source, 16);
sink(c.data()); // $ ast,ir
}
```
and apparently, this was also the missing flow for some of the smart pointer tests 🎉.
> C++: Fix flow out of const member functions

- .github/workflows/ql-for-ql-tests.yml
- .github/workflows/ruby-qltest.yml
We now have a combined workflow that does the same thing for all languages in one go, and which does it faster (thanks to caching).  
ATM still have their specific compilation check as their queries aren't covered by the combined workflow. 
ATM queries have compilation warnings by design, so the combined workflow cannot work for their queries.
> QL/RB: delete language specific codeql query compile checks

- java/ql/lib/change-notes/2022-11-21-paths-get-fix.md
- java/ql/lib/semmle/code/java/security/Files.qll
- java/ql/test/library-tests/paths/Test.java
Adds a MaD row for `Path.getParent`, and fixes the row for `Paths.get` to correctly take into account the varargs without requiring implicit read steps.
> Java: Fix a couple of taint models for `java.nio.file.Path(s)`

- cpp/ql/lib/change-notes/2022-11-16-must-flow.md
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/MustFlow.qll
- cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql
- cpp/ql/src/Likely Bugs/OO/UnsafeUseOfThis.ql
- cpp/ql/test/query-tests/Critical/UnsafeUseOfThis/UnsafeUseOfThis.expected
- cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnStackAllocatedMemory/ReturnStackAllocatedMemory.expected
The `MustFlow` library was previously defined in terms of the IR-based dataflow nodes, and implicitly relied on the assumption that all relevant instructions had dataflow nodes.
On the feature branch, this is no longer the case. Thus, we cannot use the dataflow nodes, and we have to use the IR directly.
Sadly, this is a breaking change. I think this is okay, however, because:
1. I haven't seen any uses of it outside the two queries we have in Code Scanning that use it.
2. It's really easy to transition from the dataflow nodes to the instructions (since the library was already using the IR-based dataflow library).
> C++: Repair `MustFlow` library for use-use flow

- .github/workflows/ruby-build.yml
Restoring the `.cache` folders meant that some old `target` folders was restored (specifically the `0.4.4-dev` folder).  
Even though there are no files in there (my cache job cleans them up), the folders are still there, and are picked up by `PACK_FOLDER=$(readlink -f target/packs/codeql/ruby-queries/*)` in the `compile-queries` job.  
The fix is simple: delete the entire `target/packs` folder.  
There is nothing but empty folders anyway.  
Example failing workflow: https://github.com/github/codeql/actions/runs/3518802552/jobs/5898153387
Found when testing the improved workflow in this PR: https://github.com/github/codeql/pull/10782  
(I also got the fix in that PR).
> Ruby: delete the target/packs folder in the `compile-queries` job

- .github/workflows/csharp-qltest.yml
- .gitignore
- csharp/.gitignore
- csharp/actions/create-extractor-pack/action.yml
- csharp/ql/lib/semmle/code/csharp/controlflow/internal/Completion.qll
- csharp/scripts/create-extractor-pack.sh
This PR adds a job for executing C# QL tests directly in this repo, like we do for Ruby. That is, we
- Fetch a nightly `codeql` CLI.
- Build the C# extractor.
- Execute tests with the nightly CLI, using the freshly built C# extractor and the bundled (legacy) ASP extractor.
Additionally, we make use of Actions cache to cache the compilation cache (like Ruby), and we dispatch the workload onto two `ubuntu-latest-xl` machines (Ruby only uses one).
Comparison:
- The internal `C# Language Tests`, which uses one `ubuntu-latest-xl` machine, typically takes 1h20min.
- The tests introduced by this PR typically take 20 min on a cold cache, and 10 min on a warm cache.
In addition to achieving a very significant speedup, running the tests in this repo also means that external contributors will have …
> C#: Add workflow for running QL tests

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/test/library-tests/syntax-zoo/dataflow-ir-consistency.expected
These instructions aren't used for dataflow. So there's no need to allocate `DataFlow::Node`s for them.
> C++: Ignore more instructions in dataflow

- javascript/ql/lib/semmle/javascript/security/regexp/PolynomialReDoSCustomizations.qll
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialBackTracking.expected
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialReDoS.expected
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/lib/lib.js
CVE-2022-21222: TP
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11072-0-javascript/reports).
> JS: poly-redos: don't sanitize calls through substring calls that just remove the start

- javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeShellCommandConstructionCustomizations.qll
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/lib/subLib/index.js
CVE-2022-40764: TP/TN
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-11082-40032f__nightly-old__code-scanning/reports).
> JS: treat arrays that gets executed with shell:true as a sink for `js/shell-command-constructed-from-input`

- .github/actions/cache-query-compilation/action.yml
[The actions cache is currently filling up with loads of useless `codeql-compile-*` caches that will never be read](https://github.com/github/codeql/actions/caches).  
Currently our oldest cache is 22 hours old, everything older has been evicted from the actions cache.   
My solution is to not save the compilation cache when running on PRs, but only do it on pushes to `main`.  
That way we only save the caches that we expect to read.  
Read-only caches is not a feature currently supported by `actions/cache`, so I'm using my own fork.  
We should go back to `actions/cache` once https://github.com/actions/cache/pull/995 (or similar) has been merged.
> CI: use read-only-cache when running on a PR

- java/ql/lib/semmle/code/java/security/ImplicitPendingIntents.qll
- java/ql/src/change-notes/2022-11-22-bitwise-implicit-intent-flags.md
- java/ql/test/query-tests/security/CWE-927/ImplicitPendingIntentsTest.java
This fixes spurious results when `PendingIntent.FLAG_IMMUTABLE` is correctly used on a `PendingIntent` but it goes through a bitwise operation, which previously broke taint flow.
> Java: Consider taint through bitwise operations on PendingIntent flags

- swift/extractor/remapping/SwiftOpenInterception.macOS.cpp
This issue has slipped during a recent refactoring: https://github.com/github/codeql/pull/10987/files#diff-c5ab26a06a93c4507a834859a6a56878d5bfe16c4d7cbac4afc4f081d46f461aL63-R64
> Swift: fix remapping bug

- swift/extractor/SwiftExtractor.cpp
After upgrading to Xcode 14.1 we started getting incomplete extractions as the extractor would fail to remap its own Swift modules to the modules from the original compiler.
The remapping was not happening because the extractor was aborting early thus not producing the required modules.
I observed that the extractor started crashing because it could not archive the source file with a "permission denied" error message: this is unlikely event, so we decided to `abort` in such cases.
Further, I noticed that several processes tried to archive the same source file concurrently, and this is likely the cause of this erroneous behaviour.
I did relax this "constraint" and I cannot see any issues anymore.
Related fix that should go together with this one https://github.com/github/codeql/pull/11381
> Swift: do not abort if cannot archive a source file

- .github/workflows/csharp-qltest.yml
These unit tests were part of the old `C# Language Tests` run; so we should include them in the new setup.
> C#: Also include extractor unit tests in `csharp-qltest.yml`

- ql/node-types/src/lib.rs
- ruby/node-types/src/lib.rs
Dbscheme case-splits are only valid for `int` columns on defining tables.
This fix doesn't actually affect Ruby/QL (so the dbschemes haven't changed), but for other tree-sitter grammars it could generate invalid dbschemes by creating case-splits for columns in auxiliary tables.
> Ruby/QL: only create dbscheme case-splits for columns on defining tables

- swift/codegen/lib/schema/schema.py
- swift/codegen/test/test_schema.py
This was causing hardly debuggable errors because names are transformed to underscored lowercase names in the dbscheme and back to camelcase for trap emission classes, which is not a noop in case uppercase acronyms (like SIL or ABI) are in the name.
This makes the error be surfaced early with a helpful message.
> Swift: reject uppercase acronyms in schema

- cpp/ql/src/Security/CWE/CWE-611/Xerces.qll
- cpp/ql/test/query-tests/Security/CWE/CWE-611/XXE.expected
I'm not completely sure if this is the optimal fix, so I happily discuss that. I does restore all the missing results.
> C++: Fix CWE-611 XXE query to work with use-use dataflow

- javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml
- javascript/ql/experimental/adaptivethreatmodeling/model/qlpack.yml
- javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/qlpack.yml
- javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml
This will allow us to populate a description in the UI (example: https://github.com/orgs/codeql/packages/container/javascript-experimental-atm-queries/49184568?tag=0.4.0), making it easier to see at a glance what the pack does.  The UI will be updated as of the next release of the pack.
> ATM: Add descriptions to ML-powered packs

- .github/workflows/csharp-qltest.yml
- cpp/autobuilder/Semmle.Autobuild.Cpp.Tests/BuildScripts.cs
- cpp/autobuilder/Semmle.Autobuild.Cpp/CppAutobuilder.cs
- cpp/autobuilder/Semmle.Autobuild.Cpp/Program.cs
- csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs
- csharp/autobuilder/Semmle.Autobuild.CSharp/CSharpAutobuilder.cs
- csharp/autobuilder/Semmle.Autobuild.CSharp/DotNetRule.cs
- csharp/autobuilder/Semmle.Autobuild.CSharp/Program.cs
- csharp/autobuilder/Semmle.Autobuild.CSharp/StandaloneBuildRule.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/AutobuildOptions.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/Autobuilder.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/BuildCommandAutoRule.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/BuildCommandRule.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/MsBuildRule.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/Project.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/ProjectOrSolution.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/Solution.cs
I wanted to include the C++ Windows Autobuilder tests in the CI PR check. It turned out that those tests are not working, and I realized that we need to distinguish between C# autobuilder options and C++ autobuilder options (the C++ tests were failing due to a missing `CODEQL_EXTRACTOR_CSHARP_OPTION_BUILDLESS` environment variable, which has nothing to do with C++).
So this PR make such a splitting, and adds the appropriate `dotnet test` CI invocation.
> C#: Split `AutobuildOptions` into C#/C++ specific classes

- ruby/ql/lib/codeql/ruby/frameworks/ActiveStorage.qll
- ruby/ql/lib/codeql/ruby/frameworks/PosixSpawn.qll
- ruby/ql/lib/codeql/ruby/frameworks/Railties.qll
- ruby/ql/lib/codeql/ruby/frameworks/core/IO.qll
- ruby/ql/lib/codeql/ruby/frameworks/stdlib/Open3.qll
I noticed an `override DataFlow::Node getAnArgument` in classes that `extends DataFlow::CallNode`.   
That is just a foot-gun waiting to happen if `DataFlow::CallNode` gets an `getAnArgument` predicate, so I changed those classes to `instanceof DataFlow::CallNode`.  
Drive-by cleanup of imports in `Open3.qll` based on feedback from QL-for-QL.
> Rb: use `instanceof` instead of `extends` on `DataFlow::CallNode` in some case

- cpp/ql/lib/semmle/code/cpp/security/TaintTracking.qll
- cpp/ql/src/jsf/4.09 Style/Naming.qll
- csharp/ql/campaigns/Solorigate/lib/Solorigate.qll
- csharp/ql/lib/experimental/code/csharp/Cryptography/NonCryptographicHashes.qll
- java/ql/lib/semmle/code/java/frameworks/Properties.qll
- java/ql/lib/semmle/code/java/frameworks/Rmi.qll
- java/ql/lib/semmle/code/java/frameworks/apache/Exec.qll
- java/ql/lib/semmle/code/java/security/ExternalProcess.qll
- java/ql/lib/semmle/code/java/security/RelativePaths.qll
- java/ql/lib/semmle/code/java/security/SqlUnescapedLib.qll
- java/ql/src/Violations of Best Practice/Dead Code/DeadLocals.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/ATMConfig.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/AdaptiveThreatModeling.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/BaseScoring.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/CoreKnowledge.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointFeatures.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointScoring.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/FunctionBodyFeatures.qll
- javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountAlertsAndSinks.qll
- javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/Exclusions.qll
- javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/ExtractEndpointDataTraining.qll
- javascript/ql/test/tutorials/Validating RAML-based APIs/Osprey.qll
- javascript/ql/test/tutorials/Validating RAML-based APIs/RAML.qll
- python/ql/lib/semmle/python/TestUtils.qll
- ql/ql/src/codeql_ql/ast/Ast.qll
- ql/ql/src/queries/style/NonDocBlock.ql
- ql/ql/test/queries/style/NonDocBlock/Foo.qll
- ql/ql/test/queries/style/NonDocBlock/NonDocBlock.expected
- ql/ql/test/queries/style/NonDocBlock/NonDocBlock.qlref
This would have caught a recent QLDoc check that I spent way too long trying to fix, where I didn't realise that the top-level comment was not a QLDoc.
I also fixed a whole bunch of the issues found by the query.   
Not all, some results are benign.  
And also some improvements to how we match up QLDoc in QL-for-QL.
> QL: improve the "this block-comment should have been a QLDoc"-query

- cpp/ql/src/Security/CWE/CWE-611/XXE.ql
- cpp/ql/src/Security/CWE/CWE-611/Xerces.qll
- cpp/ql/test/query-tests/Security/CWE/CWE-611/XXE.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-611/tests2.cpp
This commit ensures stack allocated parsers are also handled. Currently missing are the cases where the parser is assigned to global variable, as this requires indirect flow through global variables, which we know is currently missing from use-use dataflow.
> C++: Fix CWE-611 XXE query to work with use-use dataflow - take 2

- swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/NSData.qll
- swift/ql/test/library-tests/dataflow/flowsources/FlowSources.expected
- swift/ql/test/library-tests/dataflow/flowsources/nsdata.swift
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/TaintInline.expected
- swift/ql/test/library-tests/dataflow/taint/nsdata.swift
- swift/ql/test/library-tests/dataflow/taint/nsmutabledata.swift
Note that models requiring flow through code blocks have been left out (see `TODO` comments).
> Swift: Add models for NSData and NSMutableData

- docs/codeql/codeql-cli/creating-codeql-databases.rst
- docs/codeql/codeql-for-visual-studio-code/working-with-codeql-packs-in-visual-studio-code.rst
- docs/codeql/codeql-language-guides/abstract-syntax-tree-classes-for-working-with-java-programs.rst
- docs/codeql/codeql-language-guides/analyzing-data-flow-in-java.rst
- docs/codeql/codeql-language-guides/codeql-for-java.rst
- docs/codeql/codeql-overview/system-requirements.rst
- docs/codeql/query-help/codeql-cwe-coverage.rst
- docs/codeql/query-help/index.rst
- docs/codeql/reusables/extractors.rst
- docs/codeql/reusables/kotlin-beta-note.rst
- docs/codeql/reusables/kotlin-java-differences.rst
- docs/codeql/support/reusables/frameworks.rst
Note that the content design plan noted possible additions to https://codeql.github.com/docs/codeql-cli/extractor-options/; I could not find a suitable place
> Adds Kotlin (beta) content

- .github/workflows/ruby-build.yml
I've been looking at bit at [how we use cache in our CI](https://github.com/github/codeql/actions/caches), and I've noticed that the cargo caches are big 
(e.g. [here](https://github.com/github/codeql/actions/runs/3532847226/jobs/5927713764) where just the Windows cargo cache is ~900MB).   
There is a limit of 10GB cache pr. repo, and when the cache goes over the 10GB limit then the oldest caches are evicted, and there is lot of cache eviction right now.  
With this PR I'm caching the compiled extractor, and if there's a cache hit on the extractor, then the cargo cache is skipped completely.   
This should ensure less cache evictions throughout `github/codeql`, which can potentially speed up all workflows that use caches.
> Ruby: cache the compiled extractor in the build tests

- java/ql/lib/semmle/code/java/dispatch/VirtualDispatch.qll
When we have a combination of a good manual model for a callable and low confidence in the virtual dispatch to source targets, then we want to only use the model and disregard the source dispatch.
Selecting these cases involves a good deal of heuristics, and this PR tweaks this by allowing source dispatch to implementations of interfaces (with suitable flow models) unless those interfaces are from a different project, i.e. typically some interface in a library that the code depends on.
The reasoning is that if a library interface has flow models then it's likely because it comes with typically used default implementations of that interface, which makes any custom implementations unlikely dispatch targets if we don't have other indications that such a custom implementation might be in use …
> Java: Adjust the prioritisation between MaD and source dispatch.

- java/kotlin-extractor/build.py
We were globbing with a * in the filename, but that is not necessary.
> Kotlin build system: Refactor jar-finder

- java/ql/src/experimental/Security/CWE/CWE-089/MyBatisCommonLib.qll
- java/ql/test/experimental/query-tests/security/CWE-089/src/main/MyBatisAnnotationSqlInjection.expected
- java/ql/test/experimental/query-tests/security/CWE-089/src/main/MybatisSqlInjection.java
- java/ql/test/experimental/query-tests/security/CWE-089/src/main/MybatisSqlInjectionService.java
- java/ql/test/experimental/query-tests/security/CWE-089/src/main/SqlInjectionMapper.java
Add binding between annotation and sink-param.
In below case, the rule `MyBatisAnnotationSqlInjection.ql` will find a vulnerability at `parameter name` in function `testParamAnno1()`. That is false positive.
```java
@Select("select * from user_info where name = #{name} and age = ${age}")
String testParamAnno1(@Param("name") String name, Integer age);
@Select("select * from user_info where age = #{age}")
String testParamAnno2(@Param("age") String age);
```
The root cause is, `isMybatisXmlOrAnnotationSqlInjection()` find `annotation @Param` in `testParamAnno2()` and bind it to `${age}` in `@Select("select * from user_info where name = #{name} and age = ${age}")` when processing `parameter name in testParamAnno1()`. So it raise a vulnerability to `name` when it saw `${age}` binding with …
> Java: Add binding between annotation and sink-param in MyBatis SQL Injection query

- java/ql/lib/semmle/code/java/regex/RegexTreeView.qll
- python/ql/lib/semmle/python/RegexTreeView.qll
- ruby/ql/lib/codeql/ruby/regexp/RegExpTreeView.qll
The `additional` keyword is used in modules that implement a signature to indicate that a feature is not required by the signature.  
In the future it will become a compiler warning if they are missing, so we should fix them.  
It's not an issue for JS, as the `RegexTreeView` module is simply created by importing all of `javascript` into that module.
> ReDoS: add missing additional keywords

- java/ql/lib/semmle/code/java/frameworks/Mockito.qll
With mockito 3 this class was moved to `org.mockito.junit.MockitoJUnitRunner` and removed in mockito 4.
> Java: Add new Mockito runner class location.

- ruby/ql/lib/codeql/ruby/frameworks/ActiveSupport.qll
- ruby/ql/test/library-tests/frameworks/active_support/ActiveSupportDataFlow.expected
- ruby/ql/test/library-tests/frameworks/active_support/active_support.rb
Adds taint flow from arg to return value. This is not a general purpose sanitizer for XSS https://api.rubyonrails.org/v7.0.4/classes/ERB/Util.html#method-c-json_escape
> Ruby: model ActiveSupport `json_escape` flow

- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/test.cpp
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/test.c
These demonstrate that the barrier on the sue-use dataflow feature branch is broken.
> C++: Add more tests that exercise the default taint barrier implementation

- .github/workflows/go-tests-other-os.yml
- .github/workflows/go-tests.yml
- go/Makefile
Lowers the CI turn-around time from 2+ hours to 5-10 minutes on QL changes.  
The Mac/Windows tests are way slower than the Linux tests, so I've changed it such that they only run on changes outside the `go/ql/` directory.  
Even though they are still slower than the Linux tests, they should complete within an hour (see the runs below).  
I haven't tested the final configuration with a warm cache, so the CI should be faster once this PR is merged.  
I tried to use `macos-latest-xl` runners, but during testing the jobs just kept queuing, so I reverted back to `macos-latest`.  
There is now a format check that checks all `.qll`/`.ql` files on all PRs, so the language specific format check is redundant, and I've therefore deleted it.  
The CI runs will get faster than what you can see below …
> GO: get the Go CI to go fast!

- ruby/ql/lib/codeql/ruby/security/StackTraceExposureCustomizations.qll
- ruby/ql/lib/codeql/ruby/security/StackTraceExposureQuery.qll
- ruby/ql/src/change-notes/2022-11-14-stack-trace-exposure.md
- ruby/ql/src/queries/security/cwe-209/StackTraceExposure.qhelp
- ruby/ql/src/queries/security/cwe-209/StackTraceExposure.ql
- ruby/ql/src/queries/security/cwe-209/examples/StackTraceExposure.rb
- ruby/ql/test/query-tests/security/cwe-209/StackTraceExposure.expected
- ruby/ql/test/query-tests/security/cwe-209/StackTraceExposure.qlref
- ruby/ql/test/query-tests/security/cwe-209/StackTraceExposure.rb
This gives us coverage of CWE-209.
It's a fairly direct port of the Python version of this query:
- Sources are calls to `backtrace` on exception variables, and calls to `Kernel#caller`.
- Sinks are bodies of HTTP responses.
One obvious idea for improving the query would be to define a sink for expressions inside `<%= ... %>` tags in view templates. Do we have a succinct way of expressing that, e.g. a concept?
> Ruby: add stack-trace exposure query

- .github/workflows/swift.yml
- swift/actions/run-integration-tests/action.yml
- swift/actions/run-ql-tests/action.yml
- swift/integration-tests/runner.py
* the QL compilation cache action is used for ql and integration tests
* all caches (Bazel and QL) are populated on push
For the moment because of an internal issue with caching in order to populate the cache we need to actually run the tests. When that issue is resolved, we can create cache populating jobs on push that only compile QL and do not actually do any swift compilation.
Also, the effect of this change will only be visible once merged, as PRs like this only use the cache in read-only mode, so we need the push trigger to start doing its magic.
> Swift: cache more aggressively in CI

- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/WebView.qll
- swift/ql/src/queries/Security/CWE-094/UnsafeJsEval.ql
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/webview.swift
- swift/ql/test/query-tests/Security/CWE-094/UnsafeJsEval.expected
Models for `WKUserScript`, replacing a workaround in the `swift/unsafe-js-eval` query.
> Swift: models for WKUserScript

- .github/workflows/swift.yml
- swift/actions/run-integration-tests/action.yml
I merged https://github.com/github/codeql/pull/11364 and observed the workflows running on `main` to see if everything went as it should.  
I noticed two issues:  
- In [this workflow ](https://github.com/github/codeql/actions/runs/3565278550/jobs/5990271356) there was an issue: `Cache already exists`, because the same cache keys was used for two different caches.  
- [This job ran](https://github.com/github/codeql/actions/runs/3565278550/jobs/5990232692), but there's no reason for it to run.   
Both should be fixed here.
> Swift: CI cache fixes

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/test/library-tests/dataflow/params/params-flow.expected
- ruby/ql/test/library-tests/dataflow/params/params_flow.rb
This was something I needed in my [second-order-command-injection WIP branch](https://github.com/github/codeql/pull/11236).  
Precise flow through splat parameters is hard in the general case.  
But if we special-case to the situration where both the argument and the parameter are in the first position, then it's easy.  
[Evaluation looks OK](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-11398-c95432__nightly__code-scanning/reports).  
The easiest way to see the impact is to look at the new call-edges. Those new edges mostly appear from the receiver being tracked more precisely.  
E.g. [here](https://github.com/github/codeql-dca-main/blob/data/erik-krogh/pr-11398-c95432__nightly__code-scanning/reports/alert-meta-comparison.md#-rbmetacall-graph-for-fastlane__fastlane-2) …
> Rb: add some more flow through splat parameters 

- docs/codeql/codeql-language-guides/codeql-for-cpp.rst
- docs/codeql/codeql-language-guides/codeql-for-csharp.rst
- docs/codeql/codeql-language-guides/codeql-for-go.rst
- docs/codeql/codeql-language-guides/codeql-for-ruby.rst
- docs/codeql/codeql-language-guides/conversions-and-classes-in-cpp.rst
- docs/codeql/codeql-language-guides/expressions-types-and-statements-in-cpp.rst
- docs/codeql/codeql-language-guides/functions-in-cpp.rst
- docs/codeql/codeql-language-guides/refining-a-query-to-account-for-edge-cases.rst
This pull request updates the language guides for C/C++ to remove references to LGTM.
As far as I can tell, most of the references can be removed without substitution. If I've misjudged this, please let me know.
This is one of many pull requests. I've raised a separate pull request to update the "Basic query" articles so that they guide users through get started running queries in VS Code. This should help offset the removal of the links to the query console: https://github.com/github/codeql/pull/11423.
> LGTM deprecation: updates to CodeQL for C/C++ articles 

- docs/codeql/codeql-language-guides/analyzing-control-flow-in-python.rst
- docs/codeql/codeql-language-guides/analyzing-data-flow-in-python.rst
- docs/codeql/codeql-language-guides/codeql-for-python.rst
- docs/codeql/codeql-language-guides/codeql-library-for-python.rst
- docs/codeql/codeql-language-guides/expressions-and-statements-in-python.rst
- docs/codeql/codeql-language-guides/functions-in-python.rst
- docs/codeql/codeql-language-guides/using-api-graphs-in-python.rst
This pull request updates the language guides for Python to remove references to LGTM.
As far as I can tell, most of the references can be removed without substitution. If I've misjudged this, please let me know.
This is one of many pull requests. I've raised a separate pull request to update the "Basic query" articles so that they guide users through get started running queries in VS Code. This should help offset the removal of the links to the query console: https://github.com/github/codeql/pull/11423.
> LGTM deprecation: updates to CodeQL for Python articles

- docs/codeql/codeql-language-guides/annotations-in-java.rst
- docs/codeql/codeql-language-guides/codeql-for-java.rst
- docs/codeql/codeql-language-guides/codeql-library-for-java.rst
- docs/codeql/codeql-language-guides/javadoc.rst
- docs/codeql/codeql-language-guides/overflow-prone-comparisons-in-java.rst
- docs/codeql/codeql-language-guides/types-in-java.rst
This pull request updates the language guides for Java to remove references to LGTM.
As far as I can tell, most of the references can be removed without substitution. If I've misjudged this, please let me know.
This is one of many pull requests. I've raised a separate pull request to update the "Basic query" articles so that they guide users through get started running queries in VS Code. This should help offset the removal of the links to the query console: https://github.com/github/codeql/pull/11423.
> LGTM deprecation: updates to CodeQL for Java articles

- swift/ql/src/queries/Security/CWE-1204/StaticInitializationVector.ql
- swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql
- swift/ql/src/queries/Security/CWE-259/ConstantPassword.ql
- swift/ql/src/queries/Security/CWE-760/ConstantSalt.ql
- swift/ql/src/queries/Security/CWE-916/InsufficientHashIterations.ql
Use `ApplyExpr.getArgumentWithLabel` to simplify some query QL.
Note that the QL does not have exactly the same meaning as what we had before - because parameter names and argument names are different things in Swift.  Using argument names is preferred though, because they're generally more stable (being part of the external API), plus the QL in these cases is cleaner after the change.
The tests for these queries should verify correctness (they're fairly thorough), in addition I have ad-hoc checked the argument names do indeed match expectations using other sources such as API docs as well.  In [one case](https://github.com/krzyzanowskim/CryptoSwift/blob/main/Sources/CryptoSwift/ChaCha20.swift#L31) I believe we may now catch results that we would have missed before.
I will do a DCA run to …
> Swift: Simplify some QL.

- swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPrivate.qll
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
Local taint should include local dataflow and simple summaries through library code. Otherwise, incomplete local taint paths are generated, which makes `TaintTracking::localTaint` et al not very usable.
> Swift: Fix local taint

- csharp/ql/integration-tests/posix-only/inherit-env-vars/Program.cs
- csharp/ql/integration-tests/posix-only/inherit-env-vars/build.sh
- csharp/ql/integration-tests/posix-only/inherit-env-vars/proj.csproj.no_auto
- csharp/ql/integration-tests/posix-only/inherit-env-vars/test.py
An integration test for verifying that all environment variables get passed through the C# auto-builder.
> C#: Add integration test that checks whether env vars are passed through autobuilder

- swift/actions/build-and-test/action.yml
Followup from: https://github.com/github/codeql/pull/11466#event-7912611963 
See e.g. this crashing workflow: https://github.com/github/codeql/actions/runs/3574550538/jobs/6009956577
> Swift: don't crash on non-existing cache

- java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
- java/ql/lib/semmle/code/java/Element.qll
- java/ql/src/Advisory/Naming/NamingConventionsRefTypes.ql
- java/ql/src/change-notes/2022-11-25-NamingConventionsRefTypes-kotlin.md
- java/ql/test/kotlin/library-tests/reflection/reflection.expected
- java/ql/test/kotlin/query-tests/NamingConventionsRefTypes/NamingConventionsRefTypes.expected
We used to get alerts for the class around a local function, a lambda, or a function reference, which we give name "". Now those are marked as compiler-generated, and the query ignores compiler-generated types.
> Kotlin: Enable java/misnamed-type query

- docs/codeql/ql-language-reference/expressions.rst
This adds the `language[monotonicAggregates]` annotation so that the example compiles.
Related: https://github.com/github/codeql/issues/11361 https://github.com/github/codeql/discussions/7263
> Docs: Add missing `language[monotonicAggregates]` annotation

- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/String.qll
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/TaintInline.expected
- swift/ql/test/library-tests/dataflow/taint/string.swift
- swift/ql/test/query-tests/Security/CWE-079/UnsafeWebViewFetch.expected
- swift/ql/test/query-tests/Security/CWE-079/UnsafeWebViewFetch.swift
If a `String` is tainted, then all its fields should be tainted including computed properties such as `utf8`. This support follows a similar solution to what we do with [URLs](https://github.com/github/codeql/pull/10774) using `TaintInheritingContent`.
> Swift: add `String` taint steps

- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/ATMConfig.qll
- javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointCharacteristics.qll
- javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/ExtractEndpointDataTraining.qll
- javascript/ql/experimental/adaptivethreatmodeling/src/NosqlInjectionATM.ql
- javascript/ql/experimental/adaptivethreatmodeling/src/SqlInjectionATM.ql
- javascript/ql/experimental/adaptivethreatmodeling/src/TaintedPathATM.ql
- javascript/ql/experimental/adaptivethreatmodeling/src/XssATM.ql
- javascript/ql/experimental/adaptivethreatmodeling/test/endpoint_large_scale/EndpointFeatures.ql
- `getEndpoints` → `appliesToEndpoint`
- `getImplications` → `hasImplications`
- `getAlerts` → `hasAlert`
Partially addresses https://github.com/github/ml-ql-adaptive-threat-modeling/issues/2136
> Rename predicates to fit style guide

- java/ql/src/Likely Bugs/Serialization/NonSerializableField.ql
- java/ql/src/change-notes/2022-11-25-NonSerializableField-kotlin.md
It now ignores compiler-generated classes
> Kotlin: Enable java/non-serializable-field for Kotlin

- python/ql/src/meta/analysis-quality/CallGraph.ql
I simply had forgotten that the callable didn't have a valid location, since that's not how it work with the new call graph :face_exhaling:
> Python: Fix `py/meta/points-to-call-graph`

- .github/workflows/js-ml-tests.yml
The turnaround is faster just from running on an XL worker, even though I'm doing both QL compilation and qltest as a single job.  
And when the cache is populated, then it will get way faster (in the best case).
> ATM: use the query compilation cache in the ATM qltest

- javascript/ql/lib/semmle/javascript/ApiGraphs.qll
Replaces `MkAsyncFunctionResult` with the `MkDef` node for the function's synthetic return node.
[Evaluation](https://github.com/github/codeql-dca-main/issues/8910) was quiet.
> JS: Remove MkAsyncFunctionResult

- javascript/ql/src/Security/CWE-918/examples/RequestForgeryBad.js
- javascript/ql/src/Security/CWE-918/examples/RequestForgeryGood.js
Updates the Javascript `RequestForgery` examples to use the WHATWG `URL` API, given the `URL` Node library is discouraged and soon to be deprecated.
While in here, I've changed the `var` assignments to `const` and `let` (which I have no strong opinions on... just feels more idiomatic JS in 2022).
> fix: use WHATWG URL for JS examples

- docs/codeql/codeql-language-guides/codeql-library-for-typescript.rst
- docs/codeql/codeql-language-guides/navigating-the-call-graph.rst
- docs/codeql/codeql-language-guides/using-flow-labels-for-precise-data-flow-analysis.rst
- docs/codeql/codeql-language-guides/using-type-tracking-for-api-modeling.rst
- docs/codeql/codeql-language-guides/working-with-source-locations.rst
Now that it's easier to search for the remaining references to LGTM, I found a few more in these articles. Apologies to the Java and JavaScript teams for missing these articles in the earlier PRs.
> LGTM deprecation: a few more references missed in earlier PRs

- csharp/ql/src/Telemetry/SupportedExternalApis.ql
- csharp/ql/src/change-notes/2022-12-01-supported-external-apis-query.md
- csharp/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.cs
- csharp/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.expected
- csharp/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.qlref
- csharp/ql/test/query-tests/Telemetry/SupportedExternalApis/options
- java/ql/src/Telemetry/SupportedExternalApis.ql
- java/ql/src/change-notes/2022-12-01-supported-external-apis-query.md
- java/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.expected
- java/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.java
- java/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.qlref
This PR adds a `SupportedExternalApis.ql` telemetry query, which complements the existing [UnsupportedExternalAPIs.ql](https://github.com/github/codeql/blob/6ae10c5171aaac2903d9bdf6fef9600a471067fd/java/ql/src/Telemetry/UnsupportedExternalAPIs.ql) query.  The addition of this query is based on discussion with @michaelnebel. 
- This PR currently only adds the query for Java, should it be added for C# as well?
- I've never added a telemetry query before, so let me know if there's anything else that needs to be included beyond the query and tests. (e.g. change note?)
> Java/C#: add SupportedExternalApis telemetry query

- .github/workflows/csharp-qltest.yml
- .github/workflows/js-ml-tests.yml
- .github/workflows/ruby-qltest.yml
- swift/actions/run-ql-tests/action.yml
We sometimes have failing C# CI jobs because of OOM (e.g. https://github.com/github/codeql/actions/runs/3595112804/jobs/6054199494). This PR tries to avoid that, by leaving more memory for the OS.
> CI: Change `--ram` value from 52G to 50G in `codeql` tests

- csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
- go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
- java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
- swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll
As discussed with @aschackmull, it is best to have at most one `ParameterNode` per `ParameterPosition` and `DataFlowCallable`. This PR ensures that each `DataFlowCallable` has at most one `ParameterNode` with hash-splat `ParameterPosition`.
> Ruby: At most one hash-splat `ParameterNode` per callable

- swift/actions/run-integration-tests/action.yml
This way we can get logs also in case we cancelled the job due to a test hanging indefinitely (which is happening from time to time to the Xcode test).
> Swift: always upload integration test logs

- java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
- java/ql/test/kotlin/library-tests/java_and_kotlin_internal/Java.java
- java/ql/test/kotlin/library-tests/java_and_kotlin_internal/Kotlin.kt
- java/ql/test/kotlin/library-tests/java_and_kotlin_internal/visibility.expected
Turns out kotlinc only adds this sort of name mangling to class member functions
> Kotlin: Don't add name mangling to top-level internal functions

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
In preparation for https://github.com/github/codeql/pull/10714.
- When determining whether a parameter may be the receiver of a call, use must-flow instead of may-flow.
- When restricting the possible call targets based on an argument, consider all possible argument types (may flow) instead of requiring a unique argument type (must flow).
- When a call context cannot provide any argument types, and the argument is the receiver of the call, still use an open-world assumption for `self` inside the callee.
I checked some of the now missing results from DCA, and they looked like false positives.
> Ruby: Rework call-context sensitivity logic

- shared/typetracking/change-notes/2022-12-01-initial-version.md
- shared/typetracking/codeql/typetracking/TypeTracking.qll
- shared/typetracking/qlpack.yml
There's still some followup work to be done here to allow a proper join-order in the call-graph-recursive case, but this should support the regular linear-recursive use-cases. (The interface has been prepared for this case mirroring the Ruby/Python setup.)
Note that for `TypeBackTracker.step` I've switched the meaning of `this` and `result` to match the qldoc (keeping the existing order was simply too confusing). Since most use-cases are wrapped in the language-specific `backtrack` predicates then the switch should be easily adapted.
> Shared: Add a qlpack with a parameterized module defining type-trackers.

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll
This is a simple refactoring that introduces a `Node` class that exists before computing any SSA. This is a necessary step for my ongoing work on IR dataflow through iterators.
> C++: Introduce a pre-SSA `DataFlow::Node` class

- go/ql/lib/change-notes/2022-12-6-may-have-side-effects-return-stmt.md
- go/ql/lib/semmle/go/Stmt.qll
The previous code only worked when the return statement only has one returned expression.
> Fix `mayHaveSideEffects` for `ReturnStmt`

- javascript/ql/experimental/adaptivethreatmodeling/test/endpoint_large_scale/ContradictoryEndpointCharacteristics.expected
- javascript/ql/experimental/adaptivethreatmodeling/test/endpoint_large_scale/ContradictoryEndpointCharacteristics.ql
Adds a test that surfaces endpoints with a set of characteristics that are logically incompatible with one another (e.g one high-confidence characteristic that implies a non-sink and another that implies a sink). If the test surfaces any such endpoints, this is a hint that some of our endpoint characteristics may be need to be adjusted.
Note that this test currently reveals several high-confidence negative characteristics that apply to some known sinks. We should experiment with lowering the confidence of these characteristics, so that they don't contribute negative training examples. These known exceptions are hard-coded in the test, similarly to `FilteredTruePositives.ql`, to make it easy to find all currently-known problems so we can fix them.
Closes …
> ATM: Test for contradictory endpoint characteristics

- javascript/ql/lib/semmle/javascript/dataflow/internal/AccessPaths.qll
- javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected
- javascript/ql/test/library-tests/TaintTracking/refinement-sanitizer.js
Fixes the strange behavior observed in https://github.com/github/codeql/issues/11488, where adding additional uses of a variable changes how it's sanitized.
[Evaluation](https://github.com/github/codeql-dca-main/issues/9071) looks quiet. A few tainted nodes disappeared in a context where they are guarded by `typeof v === 'number'`, so this fixes some spurious flow.
> JS: handle rephined variable in access path

- csharp/ql/lib/semmle/code/csharp/frameworks/microsoft/Owin.qll
- csharp/ql/src/change-notes/2022-12-05-owin-uri-fix.md
- csharp/ql/src/change-notes/2022-12-05-owin-uri-fix.md.
As per the API documentation, OwinRequest Uri property should not be in all caps.
https://learn.microsoft.com/en-us/previous-versions/aspnet/mt152058(v=vs.113)
> csharp: URI should be Uri in Owin.qll library.

- java/ql/lib/change-notes/2022-12-05-kotlin-path-sanitizer.md
- java/ql/lib/semmle/code/java/frameworks/kotlin/IO.qll
- java/ql/lib/semmle/code/java/frameworks/kotlin/Text.qll
- java/ql/lib/semmle/code/java/security/PathSanitizer.qll
- java/ql/test/library-tests/pathsanitizer/Test.java
- java/ql/test/library-tests/pathsanitizer/TestKt.kt
- java/ql/test/library-tests/pathsanitizer/options
Adapts `PathSanitizer.qll` so that it works properly on Kotlin codebases too. Mainly handles `$default` methods (which have a different name) and extension methods (which have a different declaring type and receiver position).
Note the considerable amount of `MISSING/SPURIOUS` alerts in the Kotlin test: all are due to an extraction error where `String.equals` and `Path.toString` are extracted as `Object.equals` and `Object.toString` respectively, causing the local taint flow calculations (which are needed for many sanitizers/guards) to fail.
> Kotlin: Adapt PathSanitizer

- java/ql/src/Security/CWE/CWE-079/AndroidWebViewSettingsEnabledJavaScript.qhelp
- java/ql/src/Security/CWE/CWE-079/AndroidWebViewSettingsEnabledJavaScript.ql
- java/ql/src/Security/CWE/CWE-079/WebSettingsDisableJavascript.java
- java/ql/src/Security/CWE/CWE-079/WebSettingsEnableJavascript.java
- java/ql/src/change-notes/2022-11-12-websettings-setjavascript-enabled.md
- java/ql/test/query-tests/security/CWE-079/semmle/tests/SetJavascriptEnabled.java
- java/ql/test/query-tests/security/CWE-079/semmle/tests/WebViewSetEnabledJavaScript.expected
- java/ql/test/query-tests/security/CWE-079/semmle/tests/WebViewSetEnabledJavaScript.qlref
- java/ql/test/query-tests/security/CWE-079/semmle/tests/options
Add a query for detecting the enabling of JavaScript execution in Android WebViews.
> Java: Query for detecting enabling Javascript in Android WebSettings

- cpp/ql/lib/semmle/code/cpp/models/implementations/StdString.qll
Changing `StdBasicStringIterator` to a non-extending subtype (and afterwards deleting it) had unintended behavior on the use-use flow feature branch, and I couldn't come up with a simple fix without also breaking Coding Standards.
So for now I think it's best to just keep this class around.
> C++: Reintroduce `StdBasicStringIterator`

- ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
@alexrford needs something like this in order to define synthesized parameter nodes as flow barriers.
> Ruby: Add `SummarizedCallable::getParameter`

- docs/codeql/writing-codeql-queries/river-answer-1-path.ql
- docs/codeql/writing-codeql-queries/river-answer-2-abstract-class.ql
- docs/codeql/writing-codeql-queries/river-answer-3-datatypes.ql
I noticed ql-for-ql throw some style complaints during https://github.com/github/codeql/pull/11612 -- I guess we might as well show official-style-compliant (tm) CodeQL!
The docstring reword is a bit awkward, since usually classes are either singleton (document with `The ...`) or have potentially lots of entries (document with `A[n] ...`), whereas here there are exactly two shores, so `One of` is indeed more natural.
> Docs: Make river-crossing example comply with the CodeQL style guide

- swift/ql/src/queries/Summary/SummaryStats.ql
I've been using a number I call "taint reach" to help measure our progress on taint flow modelling.  It seems useful enough we might as well add it to the `SummaryStats.ql` query so that its generally available.
"taint reach" is defined as the number of dataflow nodes that taint reaches, from a remote or local flow source, per million total dataflow nodes.
> Swift: Add taint reach to SummaryStats.ql.

- cpp/ql/src/Security/CWE/CWE-311/CleartextBufferWrite.ql
Fix a performance issue with `cpp/cleartext-storage-buffer`, that was causing it to fail on several LGTM projects.  The issue was that one of the constraints on the sink (that the written buffer is a `SensitiveExpr`) was only expressed in the query, not in the dataflow configuration.  The solution is to define the sources properly.  Following that and a bit more cleanup, I also believe the result is more readable than what we had before.
Improves performance on `mruby_mruby` locally from ~750s to ~45s.
I will also do a DCA run on this pull request.
> C++: Performance fix for cpp/cleartext-storage-buffer

- cpp/ql/test/library-tests/syntax-zoo/dataflow-ir-consistency.expected
This new check was added in https://github.com/github/codeql/pull/11564, and the same failures are present on `main`. I suspect this is bad IR generation.
> C++: Accept dataflow consistency changes

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
While investigating some query changes, I noticed that it can be the case that a single local step can step from a node `n1` representing the an expression, to a node `n2` that represents the expression's first conversion. Because `n.asExpr` then resolves to the unconverted expression, the result will be an expression `e` such that `localExprFlowStep(e, e)` holds 😱.
The fix is to add another level of recursion that ensures that we always step to a different expression. This is done in a3285653aebb514c4f31ac46b14dd8854654addb. 52bf39bcf93e07ff7d95edb9bdf9543a0955131b fixes a performance shown by the join-order detection in DCA. It turns out the `*` in the `localExprFlow` relation wasn't turned into a `fastTC` by the compiler, and it resulted in quite a few iterations that looked like: …
> C++: Prevent an `Expr` from stepping to itself in IR dataflow

- cpp/ql/lib/change-notes/2022-12-09-generalize-argv-source.md
- cpp/ql/lib/semmle/code/cpp/security/FlowSources.qll
This matches `isUserInput` and handles cases where `argv` has a different name, which is allowed.
> C++: Generalize the `ArgvSource` flow source

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
Turns out the `simpleLocalFlowStep` relation wasn't cached 😱. This PR fixes this.
> C++: Better caching for IR-based use-use dataflow

- java/ql/lib/change-notes/2022-10-17-android-activity-alias.md
- java/ql/lib/semmle/code/java/frameworks/android/Android.qll
- java/ql/lib/semmle/code/xml/AndroidManifest.qll
- java/ql/test/library-tests/frameworks/android/activity-alias/AndroidManifest.xml
- java/ql/test/library-tests/frameworks/android/activity-alias/Example2Activity.java
- java/ql/test/library-tests/frameworks/android/activity-alias/ExampleActivity.java
- java/ql/test/library-tests/frameworks/android/activity-alias/TestActivityAlias.expected
- java/ql/test/library-tests/frameworks/android/activity-alias/TestActivityAlias.ql
- java/ql/test/library-tests/frameworks/android/activity-alias/TestActivityAliasExports.expected
- java/ql/test/library-tests/frameworks/android/activity-alias/TestActivityAliasExports.ql
- java/ql/test/library-tests/frameworks/android/activity-alias/options
Android supports `<activity-alias>` elements which alias `<activity>` elements. This PR adds the `AndroidActivityAliasXmlElement` class to add support for activity aliases.
> Java: Add library support for activity-alias elements in AndroidManifest.qll

- cpp/ql/lib/semmle/code/cpp/security/FlowSources.qll
- cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowDestination.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-129/semmle/ImproperArrayIndexValidation/ImproperArrayIndexValidation.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextBufferWrite.expected
This fixes the test regression on `cpp/command-line-injection`.
> C++: Recognize indirect `argv` accesses as flow sources for use-use dataflow

- java/ql/lib/qlpack.yml
- java/ql/lib/semmle/code/java/dispatch/DispatchFlow.qll
- shared/typetracking/codeql/typetracking/TypeTracking.qll
This should be a strict precision improvement for virtual dispatch of lambdas and related anonymous and sufficiently private classes.
The previous implementation did a one-step approximation to the greatest fixpoint and used a very simplistic call-context oblivious flow graph. The new implementation approximates the smallest fixpoint instead, and uses type-trackers to avoid call-context mismatch. On the jdk, the smallest fixpoint is reached in 4 iterations, so 6 seems like a reasonable choice (they been quite fast to compute in all the cases I've tested locally). There's lots of potential follow-up work, but this seems like a good improvement on its own.
> Java: Switch DispatchFlow to typetracking.

- cpp/ql/lib/experimental/semmle/code/cpp/semantic/SemanticExprSpecific.qll
- cpp/ql/lib/experimental/semmle/code/cpp/semantic/analysis/SignAnalysisCommon.qll
- cpp/ql/lib/semmle/code/cpp/commons/Printf.qll
- cpp/ql/lib/semmle/code/cpp/commons/Scanf.qll
- cpp/ql/src/JPL_C/LOC-4/Rule 23/MismatchedIfdefs.ql
- cpp/ql/test/query-tests/Metrics/Dependencies/TestPackage.qll
- swift/ql/lib/codeql/swift/elements/expr/ArithmeticOperation.qll
- swift/ql/lib/codeql/swift/elements/expr/LogicalOperation.qll
Uses `instanceof` clauses in more classes as preparation for enabling a QL-for-QL query that suggests using `instanceof`. 
Some of this was written automatically, some was written manually.  
Evaluations:  
- [CPP](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11630-0-cpp/reports): There is some performance noise, but I can't replicate locally (I tried to replicate the `cpp/badly-bounded-write` regression reported by stage-timings, there was nothing), so I think we're good?    
- [Swift](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11630-7-swift__2/reports): Some more performance noise, but in a positive direction, so that's good? 🤷
> Swift/C++: Use instanceof in more places

- java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll
This PR updates `isJdkInternal` in `CaptureModelsSpecific.qll` with additional packages.
These additions are based on the results of running the below query against jdk8 and jdk11 databases. 
Let me know if any of these updates look incorrect.
```
from DataFlowTargetApi dfta, string package
where package = dfta.getDeclaringType().getPackage().toString()
select package order by package
```
> Java: update `isJdkInternal`

- javascript/ql/src/Security/CWE-352/MissingCsrfMiddleware.qhelp
- javascript/ql/src/Security/CWE-352/MissingCsrfMiddleware.ql
- javascript/ql/src/Security/CWE-352/examples/MissingCsrfMiddlewareBad.js
- javascript/ql/src/Security/CWE-352/examples/MissingCsrfMiddlewareGood.js
Fixes https://github.com/github/codeql/issues/11682.
The `csurf` package has been deprecated, so it would be best not to use it in examples and recommendations. This PR replaces it with the `csrf` function from the `lusca` package.
Also updates the query to recognize [tiny-csrf](https://www.npmjs.com/package/tiny-csrf):
> This is a tiny csrf library meant to replace what csurf used to do [before it was deleted](https://github.com/expressjs/csurf). It is almost a drop-in replacement.
Given the low number of users for that package, I am hesitant to actually recommend it in the qhelp, which is why I went with the more popular `lusca` package.
> JS: Update MissingCsrfMiddleware after 'csurf' deprecation

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll
- cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/uninitialized.expected
- cpp/ql/test/library-tests/dataflow/source-sink-tests/sources-and-sinks.cpp
Previously, we weren't getting flow in the following example on the use-use feature branch:
```cpp
char xs[2];
xs[0] = source();
xs[1] = 0;
sink(xs[0]);
```
because the assignment to `xs[1]` was seen as overwriting the contents of `xs`, and thus the assignment `xs[0] = source();` was dead according to SSA.
This PR fixes this by recognizing that some writes are "uncertain" (i.e., we don't know if they completely overwrite a piece of memory), and ensures that we have flow from uncertain definition's prior definition to the variable being defined.
I was actually planning on putting up this PR _after_ https://github.com/github/codeql/pull/11626 had been merged, but seeing as there are some performance issues with that PR I might as well put this on up now (as this PR is largely unrelated to …
> C++: Flow through uncertain writes

- go/ql/test/library-tests/semmle/go/Types/Method_hasQualifiedName2.expected
- go/ql/test/library-tests/semmle/go/Types/Method_hasQualifiedName2.ql
There is a test for `hasQualifiedName/2` and a test for `hasQualifiedName/3`, but both were using `hasQualifiedName/3`.
> Fix test to use `hasQualifiedName/2`

- ruby/ql/lib/change-notes/2022-11-30-rails-globalid.md
- ruby/ql/lib/codeql/ruby/frameworks/GlobalId.qll
- ruby/ql/test/library-tests/frameworks/globalid/GlobalId.expected
- ruby/ql/test/library-tests/frameworks/globalid/GlobalId.ql
- ruby/ql/test/library-tests/frameworks/globalid/globalid.rb
https://github.com/rails/globalid
I don't think we get a huge amount of value from this, but it may let us resolve a few more `OrmInstantiation`s.
Use of unsigned global IDs may be a signal that the application is vulnerable to IDOR. `GlobalID::Locator.locate` can handle both signed and unsigned IDs, so use of this method is not necessarily a signal that unsigned IDs are used. Use of `GlobalID::Identification#to_global_id` is a stronger signal, though I haven't tested how noisy or useful this would be as a query yet.
`GlobalID::Identification` uses are restricted to `ActiveRecord` models so far, but we could in theory extend this to any class including the module.
> Ruby: model `rails/globalid` component

- ruby/ql/lib/change-notes/2022-12-14-constructor-flow.md
- ruby/ql/lib/codeql/ruby/ast/Call.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
- ruby/ql/src/queries/analysis/Definitions.ql
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
- ruby/ql/test/library-tests/dataflow/global/Flow.expected
- ruby/ql/test/library-tests/dataflow/global/TypeTrackingInlineTest.expected
- ruby/ql/test/library-tests/dataflow/global/instance_variables.rb
- ruby/ql/test/query-tests/analysis/Definitions.expected
As discussed with @asgerf offline, we have decided to model flow through `initialize` constructors in the following way:
- When we see a call to `C.new(x1, ..., xn)`, pretend that it is actually a call to `C#initialize(x1, ..., xn)`, but only if `C` does not define it's own `self.new` method (in which case we dispatch to that instead).
- Introduce a new return kind, `NewReturnKind`, and
- let all calls to `new` accept only `NewReturnKind` (and not `NormalReturnKind`),
- let user-defined `self.new` methods have return kind `NewReturnKind` instead of `NormalReturnKind`, and
- let `initialize` methods have `NewReturnKind` for all post-update accesses to `self` (and still have `NormalReturnKind` for normal returns, in case someone were to invoke `initialize` directly).
This means that if we …
> Ruby: Model flow through `initialize` constructors

- cpp/ql/lib/semmle/code/cpp/models/interfaces/Allocation.qll
- cpp/ql/lib/semmle/code/cpp/models/interfaces/Deallocation.qll
Clarify `Allocation.qll` and `Deallocation.qll` to encourage use of `AllocationExpr` / `DeallocationExpr` as the primary way to use these libraries.
The diff is messy because I've swapped the order of predicates so that `AllocationExpr` / `DeallocationExpr` come first (thus will be read first by someone browsing the QL from the top).  The only bit that's actually different is the addition of `Note:`... in two places.
> C++: Clarify Allocation.qll and Deallocation.qll

- cpp/ql/src/Best Practices/Likely Errors/OffsetUseBeforeRangeCheck.ql
Fix performance of `cpp/offset-use-before-range-check` (showing up on `petsc/petsc`).  This was an easy fix, the issue lied with `beforeArrayAccess` and `afterArrayAccess` being explored in the wrong order.
I will start a DCA run on this pull request to confirm there are no unexpected side-effects.
> C++: Fix cpp/offset-use-before-range-check performance.

- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/WebView.qll
Fix a `RemoteFlowSource` performance issue.  This was particularly visible on `freeotp-ios`, where evaluating `RemoteFlowSource` was taking twice as long due to this part blowing up.
Note that the case immediately above already has `pragma`s like the ones I introduce.
We should check DCA results before merging.
> Swift: Fix RemoteFlowSource performance issue.

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/modules/ancestors.expected
- ruby/ql/test/library-tests/modules/callgraph.expected
- ruby/ql/test/library-tests/modules/calls.rb
- ruby/ql/test/library-tests/modules/methods.expected
- ruby/ql/test/library-tests/modules/modules.expected
- ruby/ql/test/library-tests/modules/superclasses.expected
Implements the changes suggested by @asgerf on https://github.com/github/codeql/pull/10714.
> Ruby: Recognize custom `self.new` methods that return `self.allocate`

- go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll
This builds on https://github.com/github/codeql/pull/11697 and supersedes https://github.com/github/codeql/pull/11125.
>  Go: Use any() to stub getCallbackParameter/ReturnType and getSyntheticGlobalType

- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
https://github.com/github/codeql/pull/10714 follow-up.
> Ruby: Fix bug in call-sensitivity logic for `initialize` calls

- cpp/ql/lib/semmle/code/cpp/commons/Buffer.qll
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowBuffer.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/tests.cpp
- cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/VeryLikelyOverrunWrite.expected
This PR basically changes `Buffer.qll`'s `getBufferSize` back to its original implementation before we started doing use-use flow. In https://github.com/github/codeql/pull/11042 I made a controversial: changing the `getBufferSize` predicate to return the maximum buffer size, instead of returning a unique buffer size (if any). It turns out this change (i.e., `unique` -> `max`) was needed because `localExprFlowStep` was broken and had cases where `localExprFlowStep(e, e)` was true (which broke uniqueness in most cases). This was fixed in https://github.com/github/codeql/pull/11640, and we can now go back to `unique` again.
> C++: Use `unique` in `getBufferSize`

- .github/workflows/atm-check-query-suite.yml
I just opened https://github.com/github/codeql/pull/11660, where I noticed that the `Check query suite` ATM check was the slowest ATM check.  
This should speed it up significantly.
> ATM: speedup the "ATM - Check query suite" CI job

- cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test3.cpp
This fixes FNs _and_ reduces result duplication tremendously 🎉.
DCA looks fine.
> C++: Use `asExpr` in `cpp/cleartext-transmission`

- cpp/ql/src/Security/CWE/CWE-313/CleartextSqliteDatabase.ql
This fixes most of the FNs in the internal repository.
> C++: Prepare `cpp/cleartext-storage-database` for use-use flow

- javascript/extractor/src/com/semmle/js/extractor/HTMLExtractor.java
The class `com.semmle.util.data.Option` is going away. Switch the single cross-repo call that mentions it to use the new Option-less overload that was introduced in semmle-code PR 44626.
> remove com.semmle.util.data.Option from from extractor code interface II

- java/ql/lib/semmle/code/java/frameworks/android/WebView.qll
- java/ql/src/Security/CWE/CWE-079/AndroidWebViewAddJavascriptInterface.qhelp
- java/ql/src/Security/CWE/CWE-079/AndroidWebViewAddJavascriptInterface.ql
- java/ql/src/Security/CWE/CWE-079/AndroidWebViewAddJavascriptInterfaceExample.java
- java/ql/src/change-notes/2022-11-15-android-webview-addjavascript-interface.md
- java/ql/test/query-tests/security/CWE-079/semmle/tests/WebViewAddJavascriptInterface.expected
- java/ql/test/query-tests/security/CWE-079/semmle/tests/WebViewAddJavascriptInterface.java
- java/ql/test/query-tests/security/CWE-079/semmle/tests/WebViewAddJavascriptInterface.qlref
- java/ql/test/query-tests/security/CWE-079/semmle/tests/options
Added a query to detect invocations of `addJavascriptInterface`, which can lead to cross-site scripting.
> Java: Query for detecting addJavascriptInterface method calls

- go/CONTRIBUTING.md
- go/README.md
Removes references to lgtm.com within the "go" folder. This PR also includes some cleanup of the README file within the "go" folder.
> Remove references to lgtm.com in Go folder

- javascript/ql/src/Security/CWE-754/examples/UnvalidatedDynamicMethodCallGood.js
- javascript/ql/test/query-tests/Security/CWE-754/UnvalidatedDynamicMethodCall3.js
The example used a method called `put`, but the correct method is `set` according to the [referenced MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map). Using `put` the code returns:
```
actions.put("play", function play(data) {
^
TypeError: actions.put is not a function
at Object.<anonymous> (/Users/jacola/devel/tmpnodejs/index.js:5:9)
at Module._compile (node:internal/modules/cjs/loader:1205:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
at Module.load (node:internal/modules/cjs/loader:1068:32)
at Module._load (node:internal/modules/cjs/loader:909:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
at node:internal/main/run_main_module:23:47
Node.js v19.1.0
```
> Fix javascript syntax

- ql/generator/src/main.rs
- ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll
- ruby/generator/src/main.rs
- ruby/ql/lib/codeql/ruby/ast/internal/TreeSitter.qll
QL-for-QL complained about it.  
It makes sense for the top-level comment to be a QLDoc instead of a block-comment, so I fixed it.
> QL/RB: make top TreeSitter.qll comment into a qldoc

- ql/ql/src/codeql_ql/style/DeadCodeQuery.qll
- ql/ql/test/queries/style/DeadCode/Foo.qll
Fixes this FP https://github.com/github/codeql/security/code-scanning/77411 
And an FP that appeared [here](https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/security/PathSanitizer.qll#L15) when testing locally.
> QL: improve the dead-code query

- ql/ql/src/codeql_ql/ast/Ast.qll
- ql/ql/test/printAst/Foo.qll
- ql/ql/test/printAst/printAst.expected
With this change `EmptyConsistencies.ql` is empty (when the other QL-for-QL PRs have also been merged).  
There are many fixed spurious errors: https://github.com/github/codeql/pull/11762/checks?check_run_id=10209875313
> QL: fix `getAnnotation()` for new-type branches with parameters

- java/ql/src/Security/CWE/CWE-079/AndroidWebViewAddJavascriptInterface.ql
- java/ql/src/Security/CWE/CWE-079/AndroidWebViewSettingsEnabledJavaScript.ql
- java/ql/src/Security/CWE/CWE-200/AndroidWebViewSettingsFileAccess.ql
Use the `java/android/` prefix for the IDs of Android queries.
These haven't been part of any release yet, so the change shouldn't cause any trouble.
> Java: Fix new Android queries' IDs

- cpp/ql/src/Security/CWE/CWE-313/CleartextSqliteDatabase.ql
When there happened to be a conversion on the sink node (such as a conversion to `void*`) the implicit reads added by `allowImplicitRead` wouldn't fire since the type of the node wouldn't be a `Class` (but instead, it would be whatever the result of the conversion was).
This PR fixes the last FNs on the `cpp/cleartext-storage-database` query in the internal repo.
> C++: Fix implicit reads on `cpp/cleartext-storage-database`

- ql/ql/src/codeql-suites/ql-code-scanning.qls
- ql/ql/src/codeql_ql/style/UseInstanceofExtensionQuery.qll
- ql/ql/src/queries/bugs/PathProblemQuery.ql
- ql/ql/src/queries/performance/ClassPredicateDoesntMentionThis.ql
- ql/ql/src/queries/style/OverridingParameterName.ql
- ql/ql/src/queries/style/ToStringInQueryLogic.ql
- ql/ql/src/queries/style/UseInstanceofExtension.ql
- ql/ql/test/queries/style/UseInstanceofExtension/Foo.qll
- ql/ql/test/queries/style/UseInstanceofExtension/UseInstanceofExtension.expected
- ql/ql/test/queries/style/UseInstanceofExtension/UseInstanceofExtension.qlref
The `ql/suggest-instanceof-extension` query should now suggest using `instanceof` in more places, as it no longer require that the class has predicates that just "forwards" to a range field.  
New medium precision queries that are now enabled:  
- `ql/unmentioned-guard`: No results. 
- `ql/order-by-const`: No results. 
- `ql/path-problem-query`: No results. 
- `ql/cand-missing-nomagic`: A few new results, mostly in copies of the shared dataflow library. I think they look OK. 
- `ql/regex-pattern`: No results. 
- `ql/to-string-in-logic`: A few results. They look OK to me as warnings, but no need to fix the existing results.  I'll change it to a warning query. 
- `ql/suggest-instanceof-extension`: I've fixed most of the results found by this query. The remaining results are mostly in …
> QL4QL: enable medium precision queries, and make the "suggest instanceof" query louder 

- ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.ql
We currently get this error on main: `This predicate has weaker binding sets than the predicate it overrides. The overridden predicate is declared by SummarizedCallable. (semantics.ql:17,22-39)`.  
I think it's a semantic merge conflict of some kind, because the PR that introduced that line compiles just fine: https://github.com/github/codeql/pull/10899
> Ruby: Fix compile error in test

- csharp/codeql-extractor.yml
- go/codeql-extractor.yml
- ql/codeql-extractor.yml
- ruby/codeql-extractor.yml
- swift/codeql-extractor.yml
This PR specifies GitHub API and SCC language names in the `codeql-extractor.yml` file for extractor packs defined within `github/semmle-code`.  These properties define how language autodetection and baseline information is computed.
This functionality was introduced in CodeQL CLI 2.11.4, and lets us avoid hardcoding this information in the CLI.  The overall goal is to minimise the number of places we need to modify to define a new language.
> Specify language names in extractor packs

- cpp/ql/lib/semmle/code/cpp/valuenumbering/GlobalValueNumberingImpl.qll
This silences a number of warnings related to GVN deprecation.
> C++: Mark a number of private predicates in the GVN library as deprecated

- cpp/downgrades/23f7cbb88a4eb29f30c3490363dc201bc054c5ff/exprs.ql
- cpp/downgrades/73af5058c6899dcdb05754c27ca966aeb3a68c94/exprs.ql
A 0 value for the expression kind is not valid, as 0 does not occur in the relevant case split. This should have been the value of `@errorexpr`, which is 1.
> C++: Fix the expression kind in two of the downgrade scripts

- .github/workflows/check-change-note.yml
The new query, which runs regardless of draft or label status, will fail if any `.md` files are added to the `change-notes` directory but don't start with YYYY-MM-DD.
Tested by running:
- `gh api 'repos/github/codeql/pulls/11504/files' --paginate --jq '[.[].filename | select(test("/change-notes/.*[.]md$"))] | all(test("/change-notes/[0-9]{4}-[0-9]{2}-[0-9]{2}.*[.]md$"))'` – #11504 had a badly formatted filenane, and the command produces `false`.
- `gh api 'repos/github/codeql/pulls/11248/files' --paginate --jq '[.[].filename | select(test("/change-notes/.*[.]md$"))] | all(test("/change-notes/[0-9]{4}-[0-9]{2}-[0-9]{2}.*[.]md$"))'` – I picked a PR with a correctly-formatted change-note filename, and the command produces `true`.
> CI: fail if a changenote filename doesn't have the right format

- java/ql/lib/change-notes/2023-01-05-fix-mad-typos.md
- java/ql/lib/ext/org.springframework.jdbc.object.model.yml
This PR fixes a couple typos in the MaD row `name` columns for `MappingSqlQuery` and `MappingSqlQueryWithParameters`.
The documentation for [`MappingSqlQuery`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/object/MappingSqlQuery.html) and for [`MappingSqlQueryWithParameters`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/object/MappingSqlQueryWithParameters.html) do not contain `BatchSqlUpdate` methods, but the constructors for each of these classes does take an “sql” argument as the second parameter.
Let me know if a change note is unneeded for this.
> Java: fix typos in MaD row `name` columns for `MappingSqlQuery` and `MappingSqlQueryWithParameters`

- go/extractor/cli/go-autobuilder/go-autobuilder.go
- go/extractor/cli/go-autobuilder/go-autobuilder_test.go
The `go version` command may output warnings prior to outputting the version string. For example, it may produce the following output
```
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
go version go1.18.9 linux/amd64
```
if `GOPATH` is set to `GOROOT`. This currently causes the Go extractor to fail:
```
Expected 'go version' output of the form 'go1.2.3'; got 'set'
```
This PR changes the implementation of the `getEnvGoVersion` function so that it finds the last line of output from `go version` and uses that.
> Go: Handle output from `go version` more gracefully

- python/downgrades/503c0516fba2e5da9570f00eb34ef43025ecb8fb/py_exprs.ql
- python/downgrades/503c0516fba2e5da9570f00eb34ef43025ecb8fb/py_stmts.ql
When new kinds are inserted, new indices exists that do not correspond to any old indices.
These were previously mapped, now they are not.
We need tests in this area...
> Python: fix downgrade script

- ruby/ql/lib/codeql/ruby/frameworks/Core.qll
- ruby/ql/lib/codeql/ruby/frameworks/core/Base64.qll
- ruby/ql/lib/codeql/ruby/security/UnsafeDeserializationCustomizations.qll
- ruby/ql/lib/codeql/ruby/security/UnsafeDeserializationQuery.qll
- ruby/ql/src/change-notes/2023-01-06-stdin-as-deserialization-source.md
- ruby/ql/src/queries/security/cwe-502/UnsafeDeserialization.ql
- ruby/ql/test/library-tests/dataflow/local/TaintStep.expected
- ruby/ql/test/query-tests/security/cwe-502/unsafe-deserialization/UnsafeDeserialization.expected
- ruby/ql/test/query-tests/security/cwe-502/unsafe-deserialization/UnsafeDeserialization.rb
Gets a TP for CVE-2022-32511  
Evaluations ([rails-projects](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-11581-b8a18b__rails-projects__code-scanning/reports), [nightly](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/stdin__nightly__code-scanning/reports)) look good.   
The only change in results are from the drive-by changes, and those new/lost results look good. 
[MRVA evaluation](https://github.com/github/codeql-dca-main/issues/9728#issuecomment-1371346937) on 1000 projects.  
4 results in 3 projects, that look OK to me.  
2 of the results are in `spec/` folders, and are benign, and the last ones could use something safer than `Yaml.load()`.  
So in conclusion I think it looks good.
> Rb: add stdin as source for unsafe-deserialization

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-089/SqlTainted/SqlTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-114/semmle/UncontrolledProcessOperation/UncontrolledProcessOperation.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/argv/argvLocal.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/funcs/funcsLocal.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextFileWrite.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-497/SAMATE/PotentiallyExposedSystemData.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-497/semmle/tests/ExposedSystemData.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-497/semmle/tests/PotentiallyExposedSystemData.expected
This fixes a performance problem I observed on `cmake`. The problem happened in the `getBufferSize`'s predicate, where we have a case that searches backwards through expressions using `DataFlow::localExprFlowStep`. The code that exhibited the performance problem looked _something_ like:
```cpp
void foo() {
int a[65536];
a[0] = ...;
a[1] = ...;
...
a[65535] = ...;
for(int i = 0; i < ...; ++i) {
use(a[i]);
}
}
```
and, while `DataFlow::localFlowStep` would handle this code perfectly well, the `DataFlow::localExprFlowStep` predicate (which has an additional transitive closure internally to step to the nearest `DataFlow::Node` that has an `asExpr()` result) would explode because the node that received flow from one assignment (i.e., `a[k] = ...;`) to the next (i.e., `a[k+1] = ...;`) wouldn't …
> C++: Map more expressions to `OperandNode`s

- csharp/ql/lib/semmle/code/csharp/dataflow/ExternalFlow.qll
- java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll
In this PR we delete the deprecated `[Source|Sink|Summary]ModelCsv` and related predicates.
This might cause the field teams tool to break.
> C#/Java: Delete deprecated ModelCsv classes and related predicates.

- javascript/ql/src/Declarations/MissingThisQualifier.ql
Fixes a query run that took an hour.  
Which is now down to seconds. 
[Performance is good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/missingThis-default-missingThis/reports).
> JS: fix bad join-order in js/missing-this-qualifier

- javascript/ql/lib/semmle/javascript/security/regexp/PolynomialReDoSCustomizations.qll
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialBackTracking.expected
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialReDoS.expected
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/polynomial-redos.js
In `js/polynomial-redos`.  
`x.replace(/\s/g, "")` and `x.replace(/\s+/g, "")` are effectively the same, and we now recognize that.  
CVE-2018-25061: TP
Evaluations were uneventful: [nightly](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-11852-90f9e3__nightly-old__code-scanning/reports) [default](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-11852-90f9e3__default__code-scanning/reports).
> JS: recognize an infinite repetition of a char-class like regex as a char-class like regex

- swift/extractor/infra/file/BUILD.bazel
- swift/extractor/infra/file/PathHash.h.fixed
- swift/extractor/infra/file/PathHash.h.workaround
Previous to this patch the code contained a workaround for the standard
defect
https://cplusplus.github.io/LWG/issue3657
where `std::filesystem::path` did not have a `std::hash` implementation.
This patch allows compiling against versions of the STL that contain the
fix to the above issue. This is done by running the compiler against
code defining `std::hash<std::filesystem::path>`: if compilation
succeeds, it means the fix is not there and we need to use the
workaround, contained in `PathHash.h.workaround`. Otherwise, the fix is
there and we use `PathHash.h.fixed` instead, which only includes the
standard headers included by `PathHash.h.workaround`, so that one is a
drop-in replacement of the other.
> Swift: make compilation with newer STL possible

- java/ql/lib/change-notes/2022-01-13-android-javascriptinterface-parameters-remote-sources.md
- java/ql/lib/semmle/code/java/dataflow/FlowSources.qll
- java/ql/lib/semmle/code/java/frameworks/android/Android.qll
- java/ql/lib/semmle/code/java/frameworks/android/WebView.qll
- java/ql/test/library-tests/dataflow/taintsources/AndroidExposedObject.java
- java/ql/test/stubs/google-android-9.0.0/android/webkit/JavascriptInterface.java
In Android, methods annotated `android.webkit.JavascriptInterface` are exposed to the JavaScript running in the WebView.
Therefore, the parameters to the exposed methods may come from untrusted sources.
> Java: Add parameters of methods annotated @JavascriptInterface as remote flow sources

- .github/workflows/ql-for-ql-build.yml
- .github/workflows/ql-for-ql-dataset_measure.yml
- .github/workflows/ql-for-ql-tests.yml
The codeql-action update was just cherry-picking the "all QL as a language"-commit on top of the latest `main`. 
---- 
With CodeQL 2.12.0 `codeql pack create` no longer creates a `.cache/` folder. 
It instead creates a `queries/` folder that contains `*.qlx` files that mirror the queries in `src/`.  
These are now placed next to the `.ql` files in `src/`.  
CodeQL still complains a bit, but everything seems to work 🤷
> QL: move queries folder instead of .cache folder now that we got .qlx

- javascript/ql/lib/semmle/javascript/PrintAst.qll
- javascript/ql/test/library-tests/AST/Decorators/printAst.expected
- javascript/ql/test/library-tests/AST/Decorators/printAst.ql
- javascript/ql/test/library-tests/AST/Decorators/tsconfig.json
- javascript/ql/test/library-tests/AST/Decorators/tst.ts
- javascript/ql/test/library-tests/TypeScript/TypeAnnotations/printAst.expected
- javascript/ql/test/library-tests/TypeScript/Types/printAst.expected
I noticed some issues in the AST viewer while watching this video https://www.youtube.com/watch?v=VrF1RwnJzBk&t=1346s (link is timestamped, you can see the issue).  
This fixes these issues. 
1: There is an internal [private class DecoratorList](https://github.com/github/codeql/blob/4e1f772f23a1b7a91d139284a0acc74dde25c4b4/javascript/ql/lib/semmle/javascript/Variables.qll#L675) that shouldn't appear in the PrintAst output, because there are already direct links to the individual decorators.  
2: The `ParameterNode` class in `PrintAst.qll` didn't handle cases where the parameter had child nodes in the ast (which is the case for destructuring parameters).
> JS: Fixup some problems in PrintAST

- go/ql/lib/ext/archive_tar.model.yml
- go/ql/lib/ext/builtin.model.yml
- go/ql/lib/ext/dummy.model.yml
- go/ql/lib/ext/net_http.model.yml
- go/ql/lib/qlpack.yml
- go/ql/lib/semmle/go/dataflow/ExternalFlow.qll
- go/ql/lib/semmle/go/dataflow/ExternalFlowExtensions.qll
- go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll
- go/ql/lib/semmle/go/frameworks/stdlib/ArchiveTar.qll
- go/ql/lib/semmle/go/frameworks/stdlib/NetHttp.qll
- go/ql/lib/semmle/go/security/FlowSources.qll
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/completetest.ext.yml
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/completetest.ql
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/sinks.ext.yml
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/sinks.ql
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/srcs.ext.yml
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/srcs.ql
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/steps.ext.yml
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/steps.ql
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlowVarArgs/Flows.ext.yml
- go/ql/test/library-tests/semmle/go/dataflow/ExternalFlowVarArgs/Flows.ql
- go/ql/test/library-tests/semmle/go/dataflow/VarArgsWithFunctionModels/Flows.ql
In this PR we
- Introduce extensible predicates (`summaryModel`, `sourceModel`, `sinkModel` and `neutralModel`) with the same naming convention as for C#, Java and Python, which is to be used to MaD models.
- Update the qlpack `lib/qlpack.yml` (codeql/go-all) to include all data extension definitions in `model.yml` files in the `ext` folder. 
- Convert the existing CSV MaD models into data extensions.
- Migrate the unit tests to use the implicitly loaded data extensions files `ext.yml` for loading relevant MaD models.
- Delete `[Summary|Sink|Source]ModelCsv` classes, cleanup the validation and comments (aligning with C# and Java).
As an example, the data extension
```yml
extensions:
- addsTo:
pack: codeql/go-all
extensible: sourceModel
data:
- ["net/http", "Request", True, "Cookie", "", …
```
> Go: Models as Data using extensions.

- java/ql/src/Security/CWE/CWE-502/UnsafeDeserialization.qhelp
Related https://github.com/github/codeql/issues/11603
> [Java] Document fixes for deserialization vulnerabilities by framework

- .github/actions/os-version/action.yml
- .github/workflows/ql-for-ql-build.yml
- .github/workflows/ql-for-ql-dataset_measure.yml
- .github/workflows/ql-for-ql-tests.yml
- .github/workflows/ruby-build.yml
- ruby/actions/create-extractor-pack/action.yml
We ran into problem with mismatching GLIBC versions due to binaries having been built with a newer OS version, stored in the cache, and later used from the cache on an older OS. This pull request should solve that issue by including the OS version in the cache keys.
@erik-krogh
> QL/Ruby: include OS version in cache keys for Rust binaries

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-190/AllocMultiplicationOverflow/AllocMultiplicationOverflow.expected
- cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
- cpp/ql/test/library-tests/dataflow/fields/partial-definition-diff.expected
- cpp/ql/test/library-tests/dataflow/fields/partial-definition-ir.expected
- cpp/ql/test/library-tests/dataflow/source-sink-tests/sources-and-sinks.cpp
Previously, we failed to identify that flow can come out of functions with a signature like [readv](https://man7.org/linux/man-pages/man2/readv.2.html). This PR fixes this.
Slightly more generally, this PR fixes problems related to getting flow out of a function like:
```cpp
void foo(const char** p);
```
since it's perfectly possible for `foo` to write to `*p`.
Luckily, everything in dataflow was already setup to handle the flow. We just didn't didn't add dataflow nodes representing the outgoing flow for such arguments.
There are a lot of new results (and no lost results 🎉!). I've checked all the SAMATE once, and they all seem to be in tests that we're expected to flag. Similarly, the results on real code also look like things the queries are expected to find (but which we didn't find …
> C++: `PostUpdateNode`s for const-pointer arguments

- cpp/ql/src/Critical/MissingCheckScanf.ql
The `cpp/missing-check-scanf` query wasn't doing the forwards-then-backwards style step-relation style that we know performs well. This PR rewrites the query to be more obviously fast. The most important part is to ensure that the forwards-backwards flow predicates is defined as a single-column predicate.
The version currently on main is defined using forwards-backwards flow predicates defined as member predicates. This means that they carry an implicit extra argument which slows down the transitive closures.
DCA doesn't show any improvements. I'm guessing this is because we just don't have any projects that hit the possible slowness.
> C++: Speedup `cpp/missing-check-scanf`

- cpp/ql/lib/definitions.qll
- cpp/ql/lib/semmle/code/cpp/Location.qll
This fixes an absolutely horrible join in `definitionOf` (which is used for go-to-definition in VSCode).
Before:
```ql
Tuple counts for _Include#feab3531::Include#f_Location#bd5c7591::Location::getContainer#0#dispred#bf_Location#bd5c759__#antijoin_rhs/2@77c30cqt after 20m18s:
223926      ~0%     {2} r1 = SCAN _Element#496c7fc2::Element::isInMacroExpansion#0#dispred#f__Element#496c7fc2::Element::getLocation#0__#shared OUTPUT In.1 'arg1', In.0 'arg0'
223926      ~0%     {2} r2 = JOIN r1 WITH Include#feab3531::Include#f ON FIRST 1 OUTPUT Lhs.0 'arg1', Lhs.1 'arg0'
223926      ~0%     {3} r3 = JOIN r2 WITH preprocdirects ON FIRST 1 OUTPUT Rhs.2, Lhs.1 'arg0', Lhs.0 'arg1'
223926      ~1%     {4} r4 = JOIN r3 WITH Location#bd5c7591::Location::getStartLine#0#dispred#bf ON FIRST 1 OUTPUT Lhs.0, …
```
> C++: Fix bad join in `definitionOf`

- java/ql/src/Security/CWE/CWE-327/BrokenCryptoAlgorithm.java
Fix a small typo in the "good/bad" Java code example associated with a CWE-327 CodeQL alert. Noticed this while discussing the alert with a developer.
> Fix small typo in good/bad code sample.

- javascript/ql/lib/semmle/javascript/ApiGraphs.qll
- javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeShellCommandConstructionCustomizations.qll
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/lib/lib.js
CVE-2022-22984: TP
[Evaluation was unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-11858-326bed__nightly-old__code-scanning/reports).
> JS: track shell:true more in js/shell-command-constructed-from-input

- swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
- swift/ql/lib/codeql/swift/security/CleartextLogging.qll
- swift/ql/lib/codeql/swift/security/CleartextLoggingQuery.qll
- swift/ql/src/queries/Security/CWE-312/CleartextLogging.qhelp
- swift/ql/src/queries/Security/CWE-312/CleartextLogging.ql
- swift/ql/src/queries/Security/CWE-312/CleartextLoggingBad.swift
- swift/ql/src/queries/Security/CWE-312/CleartextLoggingGood.swift
- swift/ql/test/query-tests/Security/CWE-312/CleartextLoggingTest.ql
- swift/ql/test/query-tests/Security/CWE-312/cleartextLoggingTest.swift
Currently we don't have flow through autoclosures in [`OsLogInterpolation`](https://developer.apple.com/documentation/os/osloginterpolation), hence the `MISSING` test cases.
Also, we don't support Array content flow yet, which means sinks that are elements of a varidic parameter cannot be modeled with MaD yet, causing a few more `MISSING` test cases in the `print` and `NSLog` functions.
Note that everything related to `OSLog` is declared in an `os` package in the real world, so we'll need to revisit its MaD rows and stubs when we can actually add support for packages/namespaces.
> Swift: Add Cleartext Logging query

- .github/workflows/ql-for-ql-tests.yml
- .github/workflows/ruby-build.yml
- ql/rust-toolchain.toml
- ql/tools/qltest.cmd
- ruby/tools/qltest.cmd
You can see a Windows failure with Ruby here: https://github.com/github/codeql/actions/runs/3930931476/jobs/6721610060
Originally found when I added Windows/Mac CI tests to QL-for-QL.  
Some drive-by QL-for-QL maintenance.
> QL/Ryby: fix qltest on Windows

- java/ql/src/Security/CWE/CWE-023/PartialPathTraversalGood.java
- java/ql/src/Security/CWE/CWE-023/PartialPathTraversalRemainder.inc.qhelp
The Java recommendation example for the "Partial path traversal vulnerability from remote" query doesn't seem right to me. Indeed, the following statement doesn't compile, since `dir.getCanonicalPath()` returns a String:
```
dir.getCanonicalPath().toPath()
```
Maybe the author wanted to state `dir.getCanonicalFile().toPath()`, which would compile, but is useless compared to `dir.getCanonicalPath()`.
Moreover, `parent.getCanonicalFile().toPath()` or `parent.getCanonicalPath()` will **not** be slash-terminated, contrary to what the description says. From what I can see (and test), the correct fix is to concatenate `File.separator` to the parent canonical path.
This is linked to #9742.
> Fix partial path traversal Java example

- ql/Cargo.lock
- ql/extractor/Cargo.toml
- ql/generator/Cargo.toml
Not the latest version (4.1), because that would require changes to the rust code.
> QL: update clap to 3.0 in QL-for-QL

- ql/Cargo.lock
- ql/extractor/Cargo.toml
- ql/generator/Cargo.toml
This reverts commit d072ed969e689e64d48a8f7b9d754203a7a86dec.
For some reason the build failed after I merged the `clap` update: https://github.com/erik-krogh/ql/pull/new/revertClap. 
I don't know why, and a hope a simple revert can fix it.
> QL: Revert "update clap to 3.0 in QL-for-QL"

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DefaultTaintTrackingImpl.qll
- cpp/ql/src/Security/CWE/CWE-190/TaintedAllocationSize.ql
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/ArithmeticTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/IntegerOverflowTainted.expected
Targets the use-use dataflow feature branch. Also undoes the changes from https://github.com/github/codeql/pull/11413 in favour of something that works for both upper bounds and equality.
> C++: Fix spurious results in default taint tracking

- python/ql/src/experimental/Security/CWE-022bis/TarSlipImprov.ql
- python/ql/test/experimental/query-tests/Security/CWE-022/TarSlip.expected
Fixing a bug in an experimental query (a recently accepted submission, I introduced the bug myself through a suggestion).
I was reminded of this today while looking at experimental queries. I planned to do it as part of promotion, but since that did not happen as quickly as I had hoped, I think it is wiser to just fix the bug now.
> Python: fix bug  in `py/tarslip-extended`

- csharp/tools/pre-finalize.cmd
- csharp/tools/pre-finalize.sh
`codeql database index-files` will by default find all files within the `source-location-prefix` as specified in the WIP database.  
If what you really want is to extract the files under the current working directory, then you need to specify `--working-dir=."`.   
I think that is what you want, and it's also what the pre-finalize script for Go is doing.  
I'm not sure how I would add a test for this.  
I just fixed a related error in Ruby/QL: https://github.com/github/codeql/pull/11884, which is how I found this (by searching for other uses of `codeql database index-files`).
> C#: add --working-dir=. to pre-finalize

- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowImplConsistency.qll
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplConsistency.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplConsistency.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplConsistency.qll
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplConsistency.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplConsistency.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplConsistency.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplConsistency.qll
When the two new consistency checks where added in https://github.com/github/codeql/pull/11564 it was not possible to exclude any nodes from these checks.
Due to the way the new Python call graph violates these checks currently, we need a way to exclude some results while figuring out how to avoid violating these. Since some of the violations are outside the test folder, it's not just possible to accept the (massive) changes to the .expected files, since the results would depend on the locations of your local Python installation.
TL;DR; I would like to have these available as a short term workaround for Python.
> DataFlow: Add `uniqueParameterNodePositionExclude`

- swift/ql/lib/codeql/swift/dataflow/Ssa.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
- swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
- swift/ql/test/library-tests/dataflow/dataflow/FlowConfig.qll
- swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
- swift/ql/test/library-tests/dataflow/dataflow/test.swift
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/url.swift
Data flow through optional binding, that is:
```
if let x = [optional expression] {
...
```
First there are lots of tests, because I was nervous about edge cases.  It turns out `switch case` has the trickiest cases, and we don't support that yet, `if let` wasn't so bad (I intend to come back to `switch case` at a later date).
The change itself, in `DataFlowPrivate.qll`, is straightforward.  I also had to generalize a case in `Ssa.qll`s `variableWrite` predicate, allowing all variables declared in patterns to be Ssa variables, not just those with an associated `PatternBindingDecl` (i.e. a top level `let x = y` or `var x = y` statement).  I think this is reasonable but I'd appreciate @MathiasVP s view.
TODO:
> Swift: Data flow through optional binding

- swift/ql/lib/codeql/swift/controlflow/CfgNodes.qll
- swift/ql/lib/codeql/swift/dataflow/Ssa.qll
- swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
- swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
- swift/ql/test/library-tests/dataflow/dataflow/test.swift
This PR continues #11836.
The first commit adds a test case that shows that we need to support more CFG node types when calculating optional binding flow (namely, property getter nodes).
The second commit adds support for that, and generalizes to more CFG node types just in case.
> Swift: Support more CFG node types in optional binding flow

- docs/codeql/ql-language-reference/name-resolution.rst
- docs/codeql/ql-language-reference/ql-language-specification.rst
Signatures and global modules were missing from the handbook and language specification.
> document new namespaces

- cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/argv/argvLocal.c
- cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/argv/argvLocal.expected
These duplicate the `i9` and `i91` tests slightly earlier in the same file, but use an explicit `if` instead of the ternary operator.
These demonstrate that the missing results for the `i9` and `i91` tests on the use-use dataflow feature branch are not due to the use of the ternary operator. As these tests might be useful in general, this PR targets `main`.
> C++: Add some additional uncontrolled format string tests

- ruby/ql/lib/codeql/ruby/ast/Operation.qll
- ruby/ql/lib/codeql/ruby/security/UnsafeCodeConstructionCustomizations.qll
- ruby/ql/lib/codeql/ruby/security/UnsafeShellCommandConstructionCustomizations.qll
- ruby/ql/test/query-tests/security/cwe-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected
- ruby/ql/test/query-tests/security/cwe-078/UnsafeShellCommandConstruction/impl/unsafeShell.rb
- ruby/ql/test/query-tests/security/cwe-094/UnsafeCodeConstruction/UnsafeCodeConstruction.expected
- ruby/ql/test/query-tests/security/cwe-094/UnsafeCodeConstruction/impl/unsafeCode.rb
Recognizes the sink for CVE-2021-21305 
Drive-by addition of the same sink to the `usafe-command-construction` query. 
[An evaluation good performance and some new results in a single project](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-11909-0-ruby/reports).  
It seems that backticks actually executes JS code within that project, which we don't recognize.  
But that is unrelated to the addition of this sink.
> Rb: recognize string concatenations as sinks for unsafe-code-construction

- cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
- cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/uninitialized.expected
This works on `main`, but reports a FP on the use-use flow feature-branch.
> C++: Add testcase with looping behavior

- docs/codeql/reusables/supported-versions-compilers.rst
- Updated the supported version of Go in documentation (Go 1.18 -> Go 1.19) 
- Updated the supported version of Java in documentation (Java 18 -> Java 19)
> Update supported language versions in documentation

- swift/ql/lib/codeql/swift/security/CleartextLogging.qll
Use the new classes from `NumericType.qll` in `CleartextLogging.qll` (follow-up for https://github.com/github/codeql/pull/11841)
> Swift: Use numeric types in CleartextLogging.qll.

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll
- cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected
This PR refactors the dataflow code for flow out of functions through parameters.
Flow out of parameters are achieved by:
1. Defining a unique "last use" of a parameter in a function
2. Identify that "last use" as a return-like dataflow node whose output node is the (post-update node of the) argument in a call to the function.
On the feature branch (and on `main`) we use the IRs `ReturnIndirectionInstruction` to define the "last use" of each parameter (i.e., step 1). This is simple for parameters that the IR considers worthy of a `ReturnIndirectionInstruction`, but for the upcoming PR that adds flow out of iterators this won't work (since parameters of iterator types don't get a `ReturnIndirectionInstruction`).
So instead, we use the shared SSA library to define a new "last use" for the …
> C++: Refactor flow out of parameters

- javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeShellCommandConstructionCustomizations.qll
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/lib/lib.js
CVE-2022-25923: TP
[Evaluation was unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-11859-b3a91b__nightly-old__code-scanning/reports).
> JS: slightly broaden the regular expression that recognizes bad string-concats used as shell commands

- .github/dependabot.yml
Dependabot is able to understand cargo workspaces, so it's not necessary
to enumerate each workspace member. It should be enough to configure it
with the workspace root directory. This will hopefully ensure that the
Cargo.lock file gets updated correctly.
> Ruby: Simplify dependabot config

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TaintTrackingUtil.qll
- cpp/ql/lib/semmle/code/cpp/models/implementations/Iterator.qll
- cpp/ql/lib/semmle/code/cpp/models/implementations/StdSet.qll
- cpp/ql/lib/semmle/code/cpp/models/implementations/StdString.qll
- cpp/ql/lib/semmle/code/cpp/models/interfaces/FormattingFunction.qll
The taint-model interpretation code had a weird case that implemented something along the lines of:
> If the model says that there's incoming flow from a dereference, then I'm also going to assume that there's incoming flow from the pointer.
(and similarly for the outgoing flow).
As far as I can see, these rules only existed to fix some models that were missing flow into arguments that didn't have indirections (for example, because the function actually took a non-pointer like argument), but for some reason used `input.asParameterDeref(...)` in their models.
This PR fixes those models and simplifies the taint-model interpretation code.
> C++: Fix models and simplify taint flow

- cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
- cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/uninitialized.expected
Similar to https://github.com/github/codeql/pull/11963, but this one is actually looping with AST def-use dataflow.
> C++: Add another looping dataflow test

- docs/codeql/codeql-for-visual-studio-code/analyzing-your-projects.rst
- docs/codeql/codeql-for-visual-studio-code/exploring-data-flow-with-path-queries.rst
- docs/codeql/reusables/vs-code-basic-instructions/run-quick-query-2.rst
The next version of the VS Code extension will rename the `CodeQL: Run Query` command to `CodeQL: Run Query on Selected Database`.
> Rename VS Code Extension Run Query command

- javascript/ql/lib/semmle/javascript/NodeModuleResolutionImpl.qll
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/otherlib/package.json
- javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/otherlib/src/otherlibimpl.js
Recognizes the source for CVE-2022-25948 
We failed to resolve [this main path](https://github.com/harttle/liquidjs/blob/527858fc14840dcc331ed9759cf50eda21945305/package.json#L5.) to [this file](https://github.com/harttle/liquidjs/blob/527858fc14840dcc331ed9759cf50eda21945305/src/liquid.ts). 
[An evaluation seems OK with performance](https://github.com/github/codeql-dca-main/blob/data/erik-krogh/PR-11906-0-javascript/reports/alert-comparison.md). And no change in results.
> JS: expand what is parsed as the stem of a pathexpr

- ruby/ql/src/queries/security/cwe-1333/ReDoSIntroduction.inc.qhelp
See: 
- https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
- https://bugs.ruby-lang.org/issues/19104
- https://www.computer.org/csdl/proceedings-article/sp/2021/893400a543/1oak988ThvO
There was an earlier PR, but I'm trying again to see if the qhelp preview works now. 
**Edit:** nope. Probably because the change in in a shared `inc.qhelp` file.
> RB: add note in ReDoS qhelp that Ruby 3.2 has fixed ReDoS

- swift/ql/src/queries/Security/CWE-760/ConstantSalt.ql
- swift/ql/test/query-tests/Security/CWE-760/ConstantSalt.expected
- swift/ql/test/query-tests/Security/CWE-760/rncryptor.swift
Add RNCryptor sinks to `swift/constant-salt`. This PR is related to  https://github.com/github/codeql/pull/11905 and https://github.com/github/codeql/pull/11911 .
I have also made `NumberLiteral` a source for this query, to support the very lazy (but all too plausible) initializer `Data(0)` used in some of the tests.
> Swift: Add RNCryptor sinks to swift/constant-salt

- swift/ql/src/queries/Security/CWE-321/HardcodedEncryptionKey.ql
- swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.expected
- swift/ql/test/query-tests/Security/CWE-321/rncryptor.swift
Add RNCryptor sinks to `swift/hardcoded-key`.  This PR is very similar to https://github.com/github/codeql/pull/11905 but for the methods where an encryption key is specified, rather than a password.
I have upgraded the query from dataflow to taint tracking so that it can track flow through conversions such as `Data("string")`.  In principle this means we could get false positive results where a constant string is "mixed" with enough random data to make it a sufficiently random key overall.  In practice `swift/constant-password` already uses taint tracking so I don't expect this to be a problem, and if we do see it when our testing scales up (e.g. with MRVA), we can add sanitizers or otherwise restrict flow to find the right balance.
> Swift: Add RNCryptor sinks to swift/hardcoded-key

- go/extractor/util/util.go
This was likely harmlessly causing `go get` reruns, since most (all?) real dependency errors cause `go list` to exit with a nonzero return code in any case.
Requested in https://github.com/github/codeql/issues/11991
> Go: Fix DepErrors test

- cpp/ql/src/Likely Bugs/Format/NonConstantFormat.ql
The sanitizer in the `cpp/non-constant-format` query was very fragile: it's supposed to look at the type of the node, and mark it as a sanitizer if the type reveals that the node could not possible hold a string.
This was easy to do before we introduced indirect dataflow nodes: we could just mark all non-pointer nodes as sanitizers because we were tracking a value of type `char*`. However, when we track indirect nodes as well, those nodes can have type `char` (since we're tracking the indirection of the `char`).
So when we introduced indirect nodes, we modified the sanitizer to not sanitize indirect nodes (for instance, by saying that `node.asIndirectExpr()` shouldn't exist). However, this relies on _all_ indirect nodes having a result for `asIndirectExpr()` which doesn't have to be true …
> C++: Positively phrased sanitizer in `cpp/non-constant-format`

- swift/ql/src/queries/Security/CWE-1204/StaticInitializationVector.ql
- swift/ql/test/query-tests/Security/CWE-1204/StaticInitializationVector.expected
- swift/ql/test/query-tests/Security/CWE-1204/rncryptor.swift
Add RNCryptor sinks to `swift/static-initialization-vector`. This PR is related to https://github.com/github/codeql/pull/11905 and others.
I have also extended the sources for this query to cover more types of constants.  I think once all four RNCryptor PRs are merged, I will go back and try to make the sources more consistent between these similar queries.
> Swift: add RNCryptor sinks to swift/static-initialization-vector

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
We were not getting flow out of functions that were missing `return` statements since they might not have a `ReturnInstruction`.
After this PR, we (ab)use the generated `UnreachedInstruction` to assign an index in the final basic block so that SSA will ensure that we have flow out of the (invalid) function.
> C++: Flow out of invalid functions

- .github/dependabot.yml
Doing the same thing as was done here for Ruby:  https://github.com/github/codeql/pull/11969
> QL: fixup the dependabot config for QL-for-QL

- javascript/ql/lib/semmle/javascript/frameworks/ClientRequests.qll
- javascript/ql/test/library-tests/frameworks/ClientRequests/ClientRequests.expected
- javascript/ql/test/library-tests/frameworks/ClientRequests/axiosTest.js
An internal user found this omission.  
Axios is used a bunch as a browser library, where it's used as a global variable ([stats](https://www.jsdelivr.com/package/npm/axios)). This adds support for that.   
I added an `EntryPoint` for the global `axios` variable, such that the existing API-graph based implementation just worked.  
[Evaluation looks good.](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-12014-e3455a__nightly-old__code-scanning__2/reports). 
It fixes a bad join-order that had sneaked into `ClientRequest::AxiosUrlRequest`, so analysis of `microsoft/vscode` is now twice as fast as before (not a fluke, I confirmed locally).
> JS: add support for axios used as a global variable

- java/ql/integration-tests/all-platforms/java/gradle-sample/test.py
- java/ql/integration-tests/all-platforms/java/partial-gradle-sample/test.py
These test don't currently work under java 17 which will be the default for our CI in future.
These are currently due to crashes within the version of gradle used for these tests.
> Use Java 11 for some integration tests

- java/ql/lib/change-notes/2023-01-27-update-queryproducer-sinks.md
- java/ql/lib/ext/org.hibernate.model.yml
- java/ql/lib/ext/org.hibernate.query.model.yml
This PR updates the package for `QueryProducer` sinks to `org.hibernate.query` instead of `org.hibernate`.
According to the [docs](https://javadoc.io/doc/org.hibernate/hibernate-core/5.4.9.Final/org/hibernate/query/QueryProducer.html) and the [`HibernateQueryProducer`](https://github.com/github/codeql/blob/6c0b50c69691cf7a14d3ec3a3400c487022971a0/java/ql/lib/semmle/code/java/frameworks/Hibernate.qll#L9) type in `Hibernate.qll`, the package for `QueryProducer` should be `org.hibernate.query`.
MRVA shows new results from the `java/sql-injection` query after this update is made.
Let me know if there is any reason why these should not be updated.
> Java: update package for `QueryProducer` sinks

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
- cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-089/SqlTainted/SqlTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-114/semmle/UncontrolledProcessOperation/UncontrolledProcessOperation.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowDestination.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/argv/argvLocal.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/funcs/funcsLocal.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextBufferWrite.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextFileWrite.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-497/SAMATE/PotentiallyExposedSystemData.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-497/semmle/tests/ExposedSystemData.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-497/semmle/tests/PotentiallyExposedSystemData.expected
This PR reduces the number of SSA reads by not considering conversions as reads. This partially fixes the looping behavior observed in https://github.com/github/codeql/pull/11963 (but it doesn't fix the one observed in https://github.com/github/codeql/pull/11975).
It should also provide a small speedup boost since we're reducing the amount of reads considered in the SSA phase.
Commit-by-commit review recommended. The meat of the PR is in 9de8d5c501e9f3da470228e403d09588393fee61 (which includes conversions from the set of uses). However, I saw a number of missing results from _just_ that commit, and it took some time to debug why. The reason is as follows:
We mark a number of ad-hoc things as conversions for iterator flow (to handle temporary variables created by rvalue-to-lvalue …
> C++: Don't count every conversion as a use

- cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/Operand.qll
- cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/Operand.qll
- cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/Operand.qll
- csharp/ql/src/experimental/ir/implementation/raw/Operand.qll
- csharp/ql/src/experimental/ir/implementation/unaliased_ssa/Operand.qll
I've been wanting this predicate for a while, but never really bothered to add it. But I finally got around to it 😄.
I'm planning to use this predicate for some dataflow stuff in an upcoming PR.
> C++: Add `getCall` predicate to `ArgumentOperand`

- cpp/ql/lib/semmle/code/cpp/models/implementations/Iterator.qll
We've talked about making our model classes public for a long time, and I'm now reaching a point where I need to use some of them for dataflow. So this PR makes the iterator-related models public.
The main concern with making such classes public is that they expose some of our internal modelling since they extend various abstract model classes (such as `DataFlowFunction`), and we don't want users to depend on this relationship.
So this PR exposes the bare minimum classes (i.e., whether they're `MemberFunction`s, `Operator`s, etc.), but delegates all the model behavior to a private class.
> C++: Make iterator classes public

- docs/codeql/reusables/download-github-database.rst
The additional slash causes the request to fail.
`gh api /repos/openjdk/jdk/code-scanning/codeql/databases/` fails:
```
gh api /repos/openjdk/jdk/code-scanning/codeql/databases/
{
"message": "Not Found",
"documentation_url": "https://docs.github.com/rest"
}
gh: Not Found (HTTP 404)
```
While `gh api /repos/openjdk/jdk/code-scanning/codeql/databases` works.
> Fix errorneous slash

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-359/semmle/tests/PrivateCleartextWrite.expected
- cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/ArithmeticUncontrolled/ArithmeticUncontrolled.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/ArithmeticTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected
This fixes the missing subpaths I observed while looking at the dataflow paths in more detail.
> C++: Fix missing subpaths when displaying dataflow paths

- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Url.qll
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/url.swift
Models taint through the fields of a [`URLRequest`](https://developer.apple.com/documentation/foundation/urlrequest) object.
> Swift: Add taint for URLRequest fields

- java/ql/lib/semmle/code/java/security/SensitiveResultReceiverQuery.qll
- java/ql/src/Security/CWE/CWE-927/SensitiveResultReceiver.java
- java/ql/src/Security/CWE/CWE-927/SensitiveResultReceiver.qhelp
- java/ql/src/Security/CWE/CWE-927/SensitiveResultReceiver.ql
- java/ql/src/change-notes/2023-01-12-sensitive-result-receiver.md
- java/ql/test/query-tests/security/CWE-927/SensitiveResultReceiver.java
- java/ql/test/query-tests/security/CWE-927/SensitiveResultReceiver.ql
Part of CWE-927. 
Covers cases in which a ResultReceiver is obtained from some untrusted source, and then sensitive data is sent through it.
> Java: Add query for leaking sensitive data through a ResultReceiver

- docs/codeql/ql-language-reference/annotations.rst
This PR adds a short description on the `pragma[assume_small_delta]` annotation.
> Document pragma[assume_small_delta]

- cpp/ql/src/Critical/MissingCheckScanf.ql
The issues were:
* `revFlow`: `revFlow` joins `fwdFlow` on `vn`.
* `Node.getASuccessor()`: `MkNode` self-join on `vn`.
* `hasFlow/5`: `MkNode` self-join on `vn`.
> C++: Fix join order in `cpp/missing-check-scanf`

- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/WebView.qll
- swift/ql/test/library-tests/dataflow/flowsources/FlowSources.expected
- swift/ql/test/library-tests/dataflow/flowsources/webview.swift
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/webview.swift
Adds a new source modeling the navigation action of a user in a WebView. This works under the assumption that the links present in the WebView are untrusted (that is, users can create their own links and those are displayed to the other users). Although that assumption may not always be correct, I think it makes sense to have this not-so-fine-grained source, more so considering the few sources we have modeled until now.
This also adds a few taint steps so that the added source is actually useful.
> Swift: Add new source and flow step related to WkWebView

- csharp/ql/test/library-tests/csharp11/NameofScope.cs
- csharp/ql/test/library-tests/csharp11/PrintAst.expected
- csharp/ql/test/library-tests/csharp11/nameofScope.expected
- csharp/ql/test/library-tests/csharp11/nameofScope.ql
In this PR we test the extended scope `nameof`. That is, parameters and type parameters are in scope for `nameof` in attribute declarations.
> C# 11: Nameof on attribute declarations.

- docs/codeql/ql-language-reference/name-resolution.rst
This PR is the first of three planned modifications of the documentation for shadowing (see https://github.com/github/codeql-core/issues/3099).
In a second PR, I will adjust the language specification to match the handbook.
In a third PR, I will add module signature member defaults.
> shadowing in the handbook

- docs/codeql/ql-language-reference/name-resolution.rst
This statement in the documentation is no longer true. As it is hard to update in a succinct way, and because it is not really required (this is in an example section after all), I have decided to simply remove it. The **namespaces** section above should provide all the necessary information.
> remove statement about namespaces from documentation that no longer holds

- docs/codeql/ql-language-reference/name-resolution.rst
- docs/codeql/ql-language-reference/ql-language-specification.rst
- docs/codeql/ql-language-reference/signatures.rst
This is the last bit of shadowing work (assuming https://github.com/github/codeql/pull/12075 is merged), and fixes https://github.com/github/codeql-core/issues/3099.
> document module signature member defaults

- docs/codeql/ql-language-reference/aliases.rst
QL doesn't allow types to be declared in lower case, so the example did not compile.
> Change type name to upper case

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/test/experimental/query-tests/Security/CWE/CWE-359/semmle/tests/PrivateCleartextWrite.expected
- cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
- cpp/ql/test/library-tests/dataflow/taint-tests/vector.cpp
- cpp/ql/test/query-tests/Security/CWE/CWE-078/SAMATE/ExecTainted/ExecTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowDestination.expected
Ideally, this PR would just be adding the one disjunct to `isIteratorUse` that I've added in 88338bdfcf92b3704908203cdb440f0d9c4399cc, but the `isIteratorUse` code was assuming that we had the `Operand` that represented the actual dereference when using the iterator (i.e., the operand representing `*it` for some iterator `it`). This is obviously not true if the iterator is passed to a function (which then writes to the iterator), so I had to shuffle things around in `isChiBeforeIteratorUse` and extend `indirectConversionFlowStep` to treat dereferences as conversions (when the indirection index is changed accordingly).
The change to `indirectConversionFlowStep` looks like this is giving us a bunch of new good results on Samate 🎉 (and AFAICT, it's also responsible for the small changes to …
> C++: Flow out of writes to iterators

- swift/ql/lib/codeql/swift/frameworks/AEXML.qll
- swift/ql/lib/codeql/swift/frameworks/Alamofire/Alamofire.qll
- swift/ql/lib/codeql/swift/frameworks/Libxml2.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/CustomUrlSchemes.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Data.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/FilePath.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/InputStream.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/NsData.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/NsUrl.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/String.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Url.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/UrlSession.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/WebView.qll
While working on models I noticed that many of the files were missing a documenting comment at the top.
> Swift: QLDoc models files consistently.

- csharp/extractor/Semmle.Extraction/TrapWriter.cs
This PR makes source archive creation more resilient to exceptions thrown by file operations. 
Fixes https://github.com/github/codeql/issues/12066.
> C#: Change handled exception in `TrapWriter.ArchiveContents`

- go/Makefile
- go/ql/src/experimental/CWE-285/PamAuthBad.go
- go/ql/src/experimental/CWE-285/PamAuthGood.go
- go/ql/src/experimental/CWE-321/HardcodedKeysBad.go
- go/ql/src/experimental/CWE-321/HardcodedKeysGood.go
We have some .go files that gofmt can't parse because they don't start
with "package". This was intentional, as they are fragments to be
included in .qhelp files. They don't affect the return code as gofmt
doesn't change their formatting, so this wasn't changing the result of
the check. However, it was confusing that when the check failed because
some other files weren't formatted correctly, the user would see the
stderr complaining about those files, so we capture stderr.
It would be an improvement to print which files are not formatted
correctly, but that was beyond my abilities with bash and makefiles.
> Fix files that gofmt can't parse

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/test/library-tests/dataflow/taint-tests/vector.cpp
- cpp/ql/test/library-tests/syntax-zoo/dataflow-ir-consistency.expected
Turns out that we had hardcoded the `container -> iterator` function to receive the container via the qualifier object, when in reality it may very well come from other parameter positions. For example, the `std::back_inserter` function takes a container as the first argument and returns an iterator for the container.
This PR slightly generalizes the predicate that recognizes this situation. Ideally, we'd be able to delegate this work to `ModelUtil.qll`, but the predicates in that file work with `DataFlow::Node`s, and we've yet to construct the actual dataflow nodes at this stage in the analysis. Instead, we only have `Node0`s, so we have to slightly reinvent `ModelUtil.qll` in this piece of code.
As a follow-up in the future, we could consider creating a parameterized-module version of …
> C++: Teach iterator flow about `std::back_inserter`

- java/ql/lib/change-notes/2023-02-06-dataflow-deadcode.md
- java/ql/lib/semmle/code/java/Constants.qll
- java/ql/lib/semmle/code/java/Expr.qll
- java/ql/lib/semmle/code/java/dataflow/RangeUtils.qll
- java/ql/lib/semmle/code/java/dataflow/SSA.qll
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowNodes.qll
- java/ql/lib/semmle/code/java/dispatch/WrappedInvocation.qll
- java/ql/src/Likely Bugs/Collections/ArrayIndexOutOfBounds.ql
- java/ql/src/change-notes/2023-02-06-index-out-of-bounds-constant.md
- java/ql/test/query-tests/RangeAnalysis/A.java
- java/ql/test/query-tests/RangeAnalysis/ArrayIndexOutOfBounds.expected
Refactors the compile-time constant computation, such that we can reuse it for more general constant calculations.
Use this to define a trivial dead-code guard and apply it to data flow nodes to filter all flow through dead code.
It was necessary to reshuffle the dependencies between SSA, virtual dispatch, and data flow nodes a bit in order to be able to refer to SSA from data flow nodes. This means that field SSA uses a slightly lower precision virtual dispatch in the determination of uncertain updates of field-SSA variables. This is in line with what's also done in C#.
> Java: Apply deadcode guard to data flow nodes.

- ruby/Cargo.lock
The 0.20.9 version caused a stack overflow error on the mongo-ruby-driver repository.
See also: https://github.com/tree-sitter/tree-sitter/issues/2071
> Ruby: downgrade tree-sitter to 0.20.7

- ruby/ql/lib/codeql/Locations.qll
- ruby/ql/lib/codeql/ruby/frameworks/Rails.qll
Computing `Location::toString` in full is not desirable, as it puts a lot of pressure on the string pool.
Before
```
[2023-02-06 19:16:47] Evaluated non-recursive predicate Locations#e31d5b03::Location::toString#0#dispred#ff@3dda59o1 in 80206ms (size: 31304525).
Evaluated relational algebra for predicate Locations#e31d5b03::Location::toString#0#dispred#ff@3dda59o1 with tuple counts:
31304525  ~1%    {2} r1 = SCAN Locations#e31d5b03::Location::hasLocationInfo#5#dispred#ffffff OUTPUT In.0, (In.1 ++ "@" ++ toString(In.2) ++ ":" ++ toString(In.3) ++ ":" ++ toString(In.4) ++ ":" ++ toString(In.5))
return r1
```
After
```
[2023-02-06 18:50:57] Evaluated non-recursive predicate Rails#a086b70b::LocalAssignsHashSyntheticGlobal#ffff@1931101m in 194ms (size: 8515).
Evaluated relational algebra for …
```
> Ruby: Avoid computing `Location::toString` in full

- cpp/ql/lib/semmle/code/cpp/security/SensitiveExprs.qll
Similar to https://github.com/github/codeql/pull/12106: We replace a combination of `toLowerCase()` and `matches` with a case-insensitive regexp match.
> C++: Avoid unnecessary calls to `toLowerCase()`

- go/ql/lib/semmle/go/Comments.qll
- go/ql/lib/semmle/go/frameworks/Logrus.qll
- go/ql/lib/semmle/go/frameworks/Revel.qll
- go/ql/lib/semmle/go/security/SensitiveActions.qll
- go/ql/src/Security/CWE-209/StackTraceExposure.ql
- go/ql/src/Security/CWE-295/DisabledCertificateCheck.ql
- go/ql/src/Security/CWE-327/InsecureTLS.ql
- go/ql/src/experimental/CWE-942/CorsMisconfiguration.ql
This is especially useful if it avoids temporary string construction, such as `toLowerCase().matches(...)`
Thanks to @nickrolfe for pointing us in this direction
> Go: Consolidate repeated calls to `matches` and `regexpMatch`

- docs/codeql/codeql-for-visual-studio-code/about-telemetry-in-codeql-for-visual-studio-code.rst
Updates the document describing what telemetry we collect from the CodeQL VS Code extension.
Don't be afraid to suggest rewriting what I've put here. I wasn't really sure how to fit in with the existing style. I also wasn't sure how to split information between the "what we include" and "what we don't include" sections.
@jf205 and @github/code-scanning-secexp
> Update telemetry privacy document for UI interaction and exceptions

- cpp/ql/test/library-tests/dataflow/taint-tests/arrayassignment.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/map.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
- cpp/ql/test/library-tests/dataflow/taint-tests/taint.ql
This resolves a few missing taint sinks, but I'm not sure if they were testing special handling for single-field structs before. @MathiasVP IIRC you did something special for single-field structs when adding field flow into the def-use IR dataflow, should we reimplement that instead of adding this case?
> C++: allow read steps at the sink in IR taint test

- csharp/ql/test/library-tests/csharp11/PrintAst.expected
- csharp/ql/test/library-tests/csharp11/StructDefault.cs
This is a test only PR.
In C# 11 it is allowed to declare structs that doesn't initialise all fields/properties.
> C# 11: Check that we get AST for structs that doesn't initialise all fields.

- go/ql/src/Security/CWE-117/LogInjection.ql
- go/ql/src/change-notes/2023-02-09-log-injection-precision.md
This is a cherry-picked commit from #11739 which downgrades the precision of the `go/log-injection` query to `medium`. This is in line with the same query for other languages.
> Go: Downgrade `go/log-injection` precision to medium

- docs/codeql/reusables/supported-versions-compilers.rst
- java/kotlin-extractor/kotlin_plugin_versions.py
- java/ql/lib/change-notes/2023-02-08-kotlin-1.8.20.md
I don't think there's any need for the CI version to be one of the versions we build extractors for, so I've removed that check.
> Kotlin: 1.8.10 and 1.8.20 are supported, and use 1.8.10 for CI

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
- cpp/ql/test/query-tests/Security/CWE/CWE-129/semmle/ImproperArrayIndexValidation/ImproperArrayIndexValidation.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/globalVars/UncontrolledFormatStringThroughGlobalVar.expected
- cpp/ql/test/query-tests/Security/CWE/CWE-326/InsufficientKeySize.expected
Also revert the changes to default taint tracking and `TaintedAllocationSize.ql` as these are no longer needed with the above mapping.
> C++: Map operand nodes that are only used once onto the related instruction node

- csharp/extractor/Semmle.Extraction.CSharp.Standalone/AssemblyCache.cs
The code always throws a `PlatformNotsupportedException` and can be considered dead.
> C#: Delete dead assembly load code.

- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
Follow-up from https://github.com/github/codeql/pull/11171#issuecomment-1416330327
> C++: Do not mark global indirect flow as spurious in dataflow tests

- docs/codeql/codeql-for-visual-studio-code/analyzing-your-projects.rst
The next version of the VS Code extension will rename some actions on the query history menu.
> Rename Query History Actions

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/test/library-tests/dataflow/dataflow-tests/BarrierGuard.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
- cpp/ql/test/library-tests/dataflow/dataflow-tests/dispatch.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/example.c
- cpp/ql/test/library-tests/dataflow/dataflow-tests/has-parameter-flow-out.ql
- cpp/ql/test/library-tests/dataflow/dataflow-tests/lambdas.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/ref.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
The first commit adds a new inline-expectations test that shows which parameters we generate return nodes for, and the second commit fixes the spurious return nodes (which was really the motivation for this PR 😂).
> C++: Fix spurious flow-through

- swift/codegen/README.md
- swift/codegen/codegen.py
This allows running `codegen.py` in isolation, without needing `bazel run //swift/codegen`. This is mainly intended for debugging.
When running like this, the user is required to make sure python dependencies are installed. You can do so with
```bash
pip3 install -r swift/codegen/requirements.txt
```
> Swift: make `codegen` run also outside `bazel`

- csharp/ql/test/library-tests/csharp11/PrintAst.expected
- csharp/ql/test/library-tests/csharp11/RelaxedShift.cs
- csharp/ql/test/library-tests/csharp11/relaxedShift.expected
- csharp/ql/test/library-tests/csharp11/relaxedShift.ql
In this PR we test the relaxed requirements for shift operators.
It is no longer required that the second operand is an in `int` or implicitly convertible to int.
> C# 11: Test of relaxed shift operator requirements.

- docs/codeql/ql-language-reference/annotations.rst
This PR adds a short description and example for the `pragma[inline_late]` annotation.
> QLDocs: Document inline_late pragma

- java/ql/lib/semmle/code/java/security/Xxe.qll
- java/ql/lib/semmle/code/java/security/XxeLocalQuery.qll
- java/ql/lib/semmle/code/java/security/XxeQuery.qll
- java/ql/lib/semmle/code/java/security/XxeRemoteQuery.qll
- java/ql/src/Security/CWE/CWE-611/XXE.ql
- java/ql/src/Security/CWE/CWE-611/XXELocal.qhelp
- java/ql/src/Security/CWE/CWE-611/XXELocal.ql
- java/ql/src/change-notes/2023-02-09-xxe-local.md
Adds a version of the XXE query that uses local sources. This helps to cover (at least) the following CVEs:
* CVE-2020-2138
* CVE-2021-21701
> Java: Add local version of the XXE query

- javascript/ql/lib/change-notes/2023-02-12-express-ws.md
- javascript/ql/lib/semmle/javascript/frameworks/WebSocket.qll
- javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/CodeInjection.expected
- javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/HeuristicSourceCodeInjection.expected
- javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/express.js
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-12159-0-javascript__1/reports).  
Recognizes the source for CVE-2020-23256
> JS: add express-ws as a source

- javascript/ql/lib/semmle/javascript/NodeModuleResolutionImpl.qll
- javascript/ql/lib/semmle/javascript/PackageExports.qll
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialBackTracking.expected
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialReDoS.expected
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/lib/subLib5/main.js
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/lib/subLib5/subclass.js
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/lib/subLib6/index.js
- javascript/ql/test/query-tests/Security/CWE-400/ReDoS/lib/subLib6/package.json
CVE-2017-16138: TP
Recognize an `index.js` file that is sibling to a `package.json` as being exported when no `main:` field is set in the `package.json`.  
And better tracking of class-constructors when finding library inputs. 
[Evaluation looks OK](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-12170-0-javascript__1/reports).  
I'm quite sure the performance improvement is spurious.
> JS: More library inputs

- javascript/ql/lib/semmle/javascript/security/dataflow/RequestForgeryCustomizations.qll
- javascript/ql/test/experimental/Security/CWE-918/SSRF.expected
- javascript/ql/test/experimental/Security/CWE-918/check-path.js
- javascript/ql/test/query-tests/Security/CWE-918/RequestForgery.expected
- javascript/ql/test/query-tests/Security/CWE-918/serverSide.js
Fixes an FP found internally.  
[Evaluation shows OK performance, and no change in results](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-11959-3cece5__nightly-old__code-scanning/reports).
> JS: add encodeURIComponent as a sanitizer for request-forgery

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This PR makes use of the `Content` approximation mechanism that was added by Tom [here](https://github.com/github/codeql/pull/11635). It _should_ be a strict performance boost (and it's part of the performance fixes I'm doing for Nelson and vim).
There's a lot of ongoing (and unanswered questions) so far about what makes a good `Content` approximation. This PR just uses the same scheme as used by the other languages. I did experiment with slight variations (using the _last_ character and using the first 2 or 3 letters in the name), but they were either equally good or slightly worse.
> C++: Use `Content` approximation

- javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssCustomizations.qll
- javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/XssThroughDom.expected
- javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/xss-through-dom.js
CVE-2018-19048: TN
We don't model flow through unknown functions, so adding `HtmlSanitizer` as a sanitizer should't be needed.  
However, if we spuriously find flow through the function (e.g. because the library ships with it's own copy of `DOMPurify`, where we spuriously find flow through), then we need the sanitizer.  
[The evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-12166-0-javascript/reports) shows some lost results where we had spurious flow through a (good) sanitizer, and around neutral performance.
> JS: add `HtmlSanitizer` as a sanitizer DOMBasedXss

- javascript/ql/lib/semmle/javascript/MembershipCandidates.qll
- javascript/ql/test/experimental/Security/CWE-918/SSRF.expected
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/lib/lib.js
CVE-2019-10778: TP
[Evaluation was unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-12171-0-javascript/reports).
> JS: dont recognize regexps that match dot as sanitizers

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This PR fixes a performance problem on the use-use flow branch.
One of the things the dataflow library computes is the possible set of tails for an access path that starts with a specific `Content`. We have modelled a read of (or write to) a union using a `Content` branch defined by the union type itself (so that you can write to one union member and read it off another).
The problem is that this makes the set of tails for a union `Content` the a lot larger than the set of tails for a specific Field (since there's just 1 `Content` value per union in the database).
Performance-wise the best fix would be to model unions as we model regular struct fields (as this would increase the discrimination factor by creating a `Content` branch for each field in the union instead of 1 `Content` branch …
> C++: Better discrimination for union `Content`s

- python/ql/lib/change-notes/2023-02-15-import-star-package.md
- python/ql/lib/semmle/python/dataflow/new/internal/ImportResolution.qll
- python/ql/test/experimental/import-resolution/main.py
- python/ql/test/experimental/import-resolution/package/subpackage2/__init__.py
(:pear: with @tausbn)
A fix of import resolution regression for `from <pkg> import *`, where `<pkg>` is a package, such that actual imports are made from the `<pkg>/__init__.py` file.
> Python: Fix `from <pkg> import *` import resolution

- csharp/ql/integration-tests/all-platforms/msbuild/Program.cs
- csharp/ql/integration-tests/all-platforms/msbuild/test.csproj
- csharp/ql/integration-tests/all-platforms/msbuild/test.py
This PR adds an integration test for C# which uses MSBuild.
> C#: Add an integration test which uses MSBuild

- java/ql/src/utils/flowtestcasegenerator/FlowTestCase.qll
- java/ql/src/utils/flowtestcasegenerator/FlowTestCaseUtils.qll
- java/ql/src/utils/flowtestcasegenerator/GenerateFlowTestCase.py
This PR allows the test generator to accept a yml file or a diretory of yml files containing MaD specifications as input. 
Also, the generated "return type" of a constuctor is now considered to be the constructed type.
> Java: Test generator improvements

- cpp/autobuilder/Semmle.Autobuild.Cpp.Tests/BuildScripts.cs
- csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/BuildActions.cs
- csharp/autobuilder/Semmle.Autobuild.Shared/MsBuildRule.cs
- csharp/scripts/create-extractor-pack.sh
**Summary**
The C# autobuilder does not currently work super well on Arm-based Macs:
1. The `create-extractor-pack.sh` script always targets x86 on macOS.
1. The autobuilder depends on `mono` and `msbuild`: `mono` to run `nuget.exe` and `msbuild` to build projects that require it. However, on arm64, `mono` does not ship with `msbuild`. This results in the following error:
```
[2023-02-10 13:53:51] [build-stdout] Exit code 1: An error occurred trying to start process 'msbuild' with working directory '[..]'. No such file or directory
```
1. Furthermore, the `msbuild` path is hardcoded in Nuget when run using `mono`. However, since `mono` doesn't ship with `msbuild` on osx-arm64, we always end up with the following error:
```
[2023-02-10 17:02:00] [build-stdout] MSBuild auto-detection: using …
```
> C#: Improve C# autobuilder compatibility with Arm-based Macs

- csharp/ql/lib/change-notes/2023-02-14-checked-operators.md
- csharp/ql/lib/semmle/code/csharp/Callable.qll
- csharp/ql/test/library-tests/csharp11/CheckedOperators.cs
- csharp/ql/test/library-tests/csharp11/PrintAst.expected
- csharp/ql/test/library-tests/csharp11/checkedOperators.expected
- csharp/ql/test/library-tests/csharp11/checkedOperators.ql
- csharp/ql/test/library-tests/dispatch/CallGraph.expected
- csharp/ql/test/library-tests/dispatch/GetADynamicTarget.expected
- csharp/ql/test/library-tests/dispatch/ViableCallable.cs
- csharp/ql/test/library-tests/dispatch/viableCallable.expected
In this PR we
- Introduce library support for `checked` operators (extractor support had already been implemented).
- Use the stored *method name* as the function name of an operator instead of hardcoding the name in the QL library code.
- Add appropriate tests.
There is compile time check that ensures that a *regular* operator i always defined, when a *checked* variant is defined.
```csharp
public class Number
{
public int Value { get; }
public static Number operator checked +(Number n1, Number n2) =>
new Number(checked(n1.Value + n2.Value));
public static Number operator +(Number n1, Number n2) =>
new Number(n1.Value + n2.Value);
}
```
Should we structure this differently: Eg `AddOperator` could contains all (both *checked* and *regular* operators and then `CheckedAddOperator` could …
> C#: Checked operator support.

- csharp/extractor/Semmle.Extraction.CSharp/Entities/Modifier.cs
- csharp/extractor/Semmle.Extraction.CSharp/Entities/Modifiers.cs
- csharp/ql/lib/change-notes/2023-02-16-requiredmembers.md
- csharp/ql/lib/semmle/code/csharp/Member.qll
- csharp/ql/lib/semmle/code/dotnet/Declaration.qll
- csharp/ql/test/library-tests/csharp11/PrintAst.expected
- csharp/ql/test/library-tests/csharp11/RequiredMembers.cs
- csharp/ql/test/library-tests/csharp11/requiredMembers.expected
- csharp/ql/test/library-tests/csharp11/requiredMembers.ql
In C# 11 it is possible to declare a *field* or *property* as `required`, which means that the entity needs to be initialised by the constructors or using *object initialisation* syntax.
```csharp
public class MyClass {
public required object X;
}
...
var c = new MyClass() { X = new object() }
...
```
> C# 11: Required fields and properties.

- CODEOWNERS
As agreed in the retro, we'll make all dynamic team members responsible for PRs
> Update CODEOWNERS for dynamic teams

- java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll
This PR moves `javax.swing%` and `java.awt%` from `isJdkInternal` to an `isInfrequentlyUsed` predicate for clarity.
> Java: move java.awt and javax.swing from `isJdkInternal` to `isInfrequentlyUsed`

- go/ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll
- go/ql/src/change-notes/2023-02-17-integer-conversion-fix.md
- go/ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.go
Previously in order to sanitize based on a guard, we required a check of the form `if valToConvert < limit`, where `limit` had a value not greater than the max value of the conversion target type... with the source signedness. So for example we would accept `valToConvert <= MaxInt32` but not `valToConvert <= MaxUint32` to protect a conversion `uint32(valToConvert)`, even though either works to ensure we're within the target upper bound and either lacks a `>= 0` check.
The query doesn't currently try to spot the need to check `>= 0` prior to converting signed-to-unsigned, and this PR doesn't change that; it just pegs the high threshold to the sink's max value, not the combination of source signedness and sink bit-size.
> Go integer conversion: check against sink, not source signedness

- java/ql/src/utils/flowtestcasegenerator/FlowTestCase.qll
- java/ql/src/utils/flowtestcasegenerator/FlowTestCaseUtils.qll
- Revert previous change (in https://github.com/github/codeql/pull/12195) to constructor return types; as constructors are supposed to be modeled using Argument[-1] rather than ReturnValue
- Fix generation of ambiguous calls when one of the conflicting methods is overridden
> Java: Test generator fixes

- .github/actions/cache-query-compilation/action.yml
When I inlined the JavaScript code into `cache-query-compilation` I forgot to port the "output" part of the code.  
So the compilation-cache-dir was never set, and thus the cache was broken.  
Unrelated:  
The cache directory just moved in the latest nightly, which means our use of the compilation cache would have broken anyway.  
This PR should fix both.
> CI: Fix CI use of the compilation cache

- misc/scripts/shared-code-metrics.py
This script measures the amount of code sharing in the CodeQL repo, and displays the package dependencies.
Sample output:
Generated on 2023-02-03 16:25:12.551688
| Language | Non-shared files | Non-shared lines of code | Imported files | Imported lines of code | Shared code % |
| -------- | ---------------- | ------------------------ | -------------- | ---------------------- | ------------- |
| cpp | 1761 | 121839 | 46 | 19776 | 13.96 |
| csharp | 1465 | 91281 | 55 | 23697 | 20.61 |
| go | 503 | 42928 | 12 | 9904 | 18.75 |
| java | 1615 | 97371 | 32 | 16641 | 14.60 |
| javascript | 1619 | 119286 | 33 | 16801 | 12.35 |
| python | 1398 | 86161 | 32 | 16230 | 15.85 |
| ql | 159 | 14211 | 8 | 9734 | 40.65 |
| ruby | 535 | 55640 | 37 | 18421 | 24.87 |
| swift | 1074 | 33454 | 15 | 12378 | …
> Script to generate shared code metrics

- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
- swift/ql/lib/codeql/swift/elements/expr/ArithmeticOperation.qll
- swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
- swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
- swift/ql/test/library-tests/dataflow/dataflow/test.swift
- swift/ql/test/library-tests/elements/expr/arithmeticoperation/arithmeticoperation.expected
- swift/ql/test/library-tests/elements/expr/arithmeticoperation/arithmeticoperation.ql
- swift/ql/test/library-tests/elements/expr/arithmeticoperation/arithmeticoperation.swift
Add tests, a class for, and taint through, unary `+`.  Unary `+` is a Swift operator that takes a number and returns ... that number.
> Swift: Add unary +

- swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPrivate.qll
- swift/ql/test/library-tests/dataflow/taint/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/simple.swift
Adds tests and taint flow through arithmetic.  Before this PR we had flow through `+` on `String`s only, a rather conservative position.  We want taint through other types such as `Integer`s, and through other arithmetic operators such as `-`.
After this PR I will create a follow-up for taint through `+=` and friends, which builds on the changes here but is a separate chunk of work with a bit of its own complexity.  More of the tests will pass after that.
> Swift: Taint through arithmetic

- csharp/extractor/Semmle.Extraction.CSharp/SymbolExtensions.cs
- csharp/ql/lib/change-notes/2023-02-22-modifierextraction.md
It looks like we are missing out on the extraction of some modifiers. More specifically, we were missing the extraction of modifiers for enums and delegates.
They could have been added as special cases, but instead we could consider to just extract all member modifiers.
> C#: Generalise modifier extraction from symbols.

- csharp/ql/src/Telemetry/ExternalApi.qll
- csharp/ql/src/Telemetry/SupportedExternalApis.ql
- csharp/ql/src/Telemetry/UnsupportedExternalAPIs.ql
- csharp/ql/src/meta/frameworks/UnsupportedExternalAPIs.ql
- java/ql/src/Telemetry/ExternalApi.qll
- java/ql/src/Telemetry/SupportedExternalApis.ql
- java/ql/src/Telemetry/UnsupportedExternalAPIs.ql
It turns out that all uses of `isSupported` also includes logic to cater for neutrals. In this PR we put this into the `isSupported` predicate itself.
Thank you @starcke!
> C#/Java: Re-factor the `isSupported` predicate.

- ql/ql/src/codeql_ql/StructuredLogs.qll
I agonised a bit over how exactly to represent the timestamps (32 bits would not suffice), but I think there should be enough precision to represent these accurately enough as floats.
> QL: Add predicates for timestamps and locations

- ql/ql/src/codeql_ql/StructuredLogs.qll
- ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll
- ql/ql/src/queries/performance/LargeTupleSum.ql
The first commit adds a parameterized module for "folding" over an evaluation of a recursive predicate, and the next commit adds a very simple query that test that the fold operation works as expected.
I think there are likely still some corner cases in the visitor that I haven't got right, but at least it seems to do the right thing most of the time 🤞.
> QL: Add a visitor for traversing recursive evaluations

- ql/ql/src/codeql_ql/StructuredLogs.qll
- ql/ql/src/experimental/queries/PredicateSummaries.ql
- ql/ql/src/queries/performance/LargeJoinOrder.ql
Adding a few bits & pieces. The interesting thing is that `PipeLine.getCount(int i, string ra)` also gives you the line of text from the corresponding RA in case you want it.
> Add classes and predicates to StructuredLogs

- ql/ql/src/codeql_ql/StructuredLogs.qll
- ql/ql/src/experimental/RA.qll
- ql/ql/src/queries/performance/LargeJoinOrder.ql
- ql/ql/test/experimental/raparser.expected
This PR does a bunch of things, and a non-hackathon version would have properly split this up into multiple commits (or even multiple PRs!) ... but oh well :shipit:
> QL: Extend the join-order badness query to recursive predicates

- csharp/ql/lib/qlpack.yml
- csharp/ql/lib/semmle/code/csharp/File.qll
- ruby/ql/lib/codeql/files/FileSystem.qll
- shared/util/codeql/util/FileSystem.qll
Avoids duplicating the logic and documentation for file system predicates.
This PR applies the new shared implementation to C# and Ruby only. I encourage other languages to follow suit (ping @github/codeql-swift , @github/codeql-c , @github/codeql-go , @github/codeql-java , @github/codeql-python, @github/codeql-javascript  ).
> Util: Add shared file system implementation

- ql/ql/src/queries/performance/LargeJoinOrder.ql
This PR fixes a missing ordering conjunct in the recursive join order metric computations. I also slightly refactored some of the predicates to reduce duplication in the process.
> QL: More fixes to the join-order query

- javascript/ql/lib/semmle/javascript/NPM.qll
- javascript/ql/lib/semmle/javascript/NodeModuleResolutionImpl.qll
- javascript/ql/lib/semmle/javascript/PackageExports.qll
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/UnsafeHtmlConstruction.expected
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/lib2/package.json
- javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/lib2/src/MyNode.ts
CVE-2022-36036: TP 
And simplify some of the related code.   
I just had to change an existing test slightly to test the new behavior. 
[Evaluation was unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-12189-0-javascript/reports).
> JS: also consider relative exports when finding library inputs

- swift/actions/run-integration-tests/action.yml
- swift/third_party/load.bzl
No changes to the Swift frontend library headers, so no changes to the extractor seem to be required.
> Swift: update to 5.7.3

- docs/codeql/codeql-language-guides/detecting-a-potential-buffer-overflow.rst
All queries that use SSA import `semmle.code.cpp.controlflow.SSA` explicitly, except for the last one. Also import the library there. Note that this is not strictly necessary, as the library is transitively imported via `import cpp`.
> Make "Detecting a potential buffer overflow" example more uniform

- javascript/ql/lib/semmle/javascript/Expr.qll
- javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected
- javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/lib/lib.js
- javascript/ql/test/query-tests/Security/CWE-089/untyped/SqlInjection.expected
- javascript/ql/test/query-tests/Security/CWE-089/untyped/koarouter.js
Fixes #11667
The `appliesTo` change didn't change the result of any tests, but that feels like a lucky coincidence (because the nodes were `instanceof DataFlow::BarrierGuardNode` anyway).  
Evaluations were uneventful:   
- [nightly on code-scanning with meta queries](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/moreSan__nightly-old__code-scanning__1/reports)
- [default on code-scanning](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/moreSan__default__code-scanning__2/reports)
> JS: Sanitizer for `sanitizer(x) === true`

- python/ql/test/experimental/library-tests/CallGraph/InlineCallGraphTest.expected
- python/ql/test/experimental/library-tests/CallGraph/code/runtime_decision.py
Since the import resolution was fixed, but tests not rerun, these
expectations were not updated to reflect that we now handle them
properly :muscle:
> Python: Fix expected of call-graph after merge

- cpp/ql/lib/semmle/code/cpp/dataflow/new/TaintTracking.qll
Using the IR version directly gives errors about conflicting imports if both DataFlow and TaintTracking are imported.
> C++: Use correct DataFlow import in new TaintTracking.qll

- cpp/ql/lib/semmle/code/cpp/models/implementations/Gets.qll
This was causing missing flow [here](https://github.com/github/codeql/pull/12316#discussion_r1118883897). The problematic case was:
```cpp
char password[1024];
gets(password); // BAD
```
the source was any `FlowSource`, and the sink was the indirect output of `gets`. And because only the direct return value was specified as being a `LocalFlowSource` we didn't catch this (trivial) flow.
> C++: Make `gets` indirect output a LocalFlowSource

- csharp/ql/lib/change-notes/2023-02-28-staticfieldwrites.md
- csharp/ql/src/Likely Bugs/StaticFieldWrittenByInstance.ql
- csharp/ql/test/query-tests/Likely Bugs/StaticFieldWrittenByInstance/StaticFieldWrittenByInstance.cs
- csharp/ql/test/query-tests/Likely Bugs/StaticFieldWrittenByInstance/StaticFieldWrittenByInstance.expected
It turns out that the query `cs/static-field-written-by-instance` reports false positives if a static property writes to static field.
That is, the example below leads to a false positive. This is fixed in this PR.
```csharp
static object backingField;
static object StaticProp
{
get
{
return backingField ?? (backingField = new object()); // OK
}
}
```
> C#: Update query to handle static field writes from properties.

- cpp/ql/test/examples/docs-examples/README.md
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/exercise1.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/exercise1.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/exercise2.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/exercise2.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/exercise4.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/exercise4.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-expr.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-expr.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-getenv.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-getenv.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-param.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-param.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-no-flow.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-no-flow.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen.cpp
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/gethostbyname.cpp
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/index-flow-from-ntohl.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/index-flow-from-ntohl.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/ntohl.cpp
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/printf-format-not-hard-coded.expected
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/printf-format-not-hard-coded.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/printf.cpp
This is on top of the commits from https://github.com/github/codeql/pull/12316. The only relevant commit is 549ebcf703d4211af20c7dec9a663aa1c6d73c8c. Initial attempt of rewriting the example dataflow queries from the docs for the new use-use dataflow library. As I ran into some problems with the queries along the way, these are actually tests. If the queries here look sensible, the next step is to update the documentation.
Note that I've been rather strict with the indirect expressions, and I've always used `asIndirectExpr(1)`, and not `asIndirectExpr()`. I'm not completely sure that makes sense, so feedback on that would be useful.
> C++: Add tests for all dataflow examples that occur in our docs

- javascript/extractor/src/com/semmle/js/extractor/FileExtractor.java
- javascript/extractor/src/com/semmle/js/extractor/Main.java
- javascript/extractor/tests/vue/output/trap/rails.html.erb.trap
CVE-2022-3704: TP
The file-extension check only works on the last part of the extension, so I had to change my implementation.  
We already have a filter for which files to extract, so I just put `.erb` as an extension we support, but then use the filter to ensure it's only `.html.erb` files that are considered. 
I didn't test the previous PR for this well enough.  
[Evaluation on nightly was very unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-12190-25a846__nightly__code-scanning/reports). 
[Evaluation on a bunch of rails projects was very eventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-12190-25a846__rails-projects__code-scanning__1/reports).  
Lots of new results (in `.html.erb` files), slightly worse performance (from extracting …
> JS: Actually extract `.html.erb` files.  

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
As of https://github.com/github/codeql/pull/12316 this predicate isn't used anymore.
> C++: Remove dead code

- csharp/extractor/Semmle.Extraction.CSharp/Entities/Modifier.cs
- csharp/extractor/Semmle.Extraction.CSharp/Entities/Modifiers.cs
- csharp/extractor/Semmle.Extraction.CSharp/SymbolExtensions.cs
- csharp/ql/lib/change-notes/2023-02-17-filescopedtypes.md
- csharp/ql/lib/semmle/code/csharp/Member.qll
- csharp/ql/lib/semmle/code/dotnet/Declaration.qll
- csharp/ql/test/library-tests/csharp11/FileScoped1.cs
- csharp/ql/test/library-tests/csharp11/FileScoped2.cs
- csharp/ql/test/library-tests/csharp11/FileScoped3.cs
- csharp/ql/test/library-tests/csharp11/FileScoped4.cs
- csharp/ql/test/library-tests/csharp11/PrintAst.expected
- csharp/ql/test/library-tests/csharp11/fileScoped.expected
- csharp/ql/test/library-tests/csharp11/fileScoped.ql
In this PR we make support for `file` scoped types. These types are only *visible* in the file where they are declared.
```csharp
file class C1 { }
```
> C# 11: Support for `file` scoped types.

- javascript/ql/lib/semmle/javascript/security/dataflow/ReflectedXssCustomizations.qll
The Core team is planning to make some changes to the join orderer that causes a join order regression for the `isLocalHeaderDefinition` predicate. This PR adds pragmas to prevent the compiler from picking the bad join order.
> ReflectedXss: Prevent bad join order

- csharp/extractor/Semmle.Extraction.CSharp/Entities/Conversion.cs
- csharp/extractor/Semmle.Extraction.CSharp/Entities/Method.cs
- csharp/extractor/Semmle.Extraction.CSharp/Entities/UserOperator.cs
- csharp/ql/lib/change-notes/2023-02-27-explicitinterfacemember.md
- csharp/ql/lib/semmle/code/csharp/Callable.qll
- csharp/ql/test/library-tests/csharp11/PrintAst.expected
- csharp/ql/test/library-tests/csharp11/StaticInterfaceMembers.cs
- csharp/ql/test/library-tests/csharp11/staticInterfaceMembers.expected
- csharp/ql/test/library-tests/csharp11/staticInterfaceMembers.ql
In this PR we implement proper support (to align with the implementation for methods) for explicit implementation of interface operator members.
Prior to this PR the implementation of `+` in the example below was not identified as being neither `public` nor an implementation of `+` from the `INumber<T>` interface.
```csharp
public interface INumber<T> where T : INumber<T>
{
static abstract T operator +(T left, T right);
}
public class Complex : INumber<Complex>
{
static Complex INumber<Complex>.operator +(Complex left, Complex right) =>
new Complex { Real = left.Real + right.Real, Imaginary = left.Imaginary + right.Imaginary };
}
```
> C# 11: Support for explicit interface implementations of operators.

- docs/codeql/codeql-language-guides/using-api-graphs-in-python.rst
Motivated by [this comment](https://github.com/github/codeql/pull/11570#discussion_r1100407159) (although it does not directly address this comment, the interaction in that PR highlighted that `CallNode` should be documented.)
> Python: Document `API::CallNode`

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
This was the only predicate in the use-use dataflow library that was flagged by Schack's regexp. Indeed, it looks like a true positive:
```ql
rec SsaInternalsCommon#3c4fa02d::Cached::convertsIntoArgumentRev#1#f(unique numbered_tuple instr) :- 
SENTINEL SsaInternalsCommon#3c4fa02d::Cached::convertsIntoArgumentFwd#1#f
SENTINEL project#SsaInternalsCommon#3c4fa02d::Cached::isSink#2#ff
[[[ BASE CASE ]]]
{1} r1 = JOIN SsaInternalsCommon#3c4fa02d::Cached::convertsIntoArgumentFwd#1#f WITH project#SsaInternalsCommon#3c4fa02d::Cached::isSink#2#ff ON FIRST 1 OUTPUT Lhs.0 'instr'
return r1
[[[ SEMINAIVE VARIANT - STANDARD ORDER]]]
{3} r2 = _SsaInternalsCommon#3c4fa02d::Cached::convertsIntoArgumentFwd#1#f__DataFlowPrivate#fbdd7bd7::getAUse__#loop_invariant_prefix AND NOT …
```
> C++: Disable a bad standard order

- swift/ql/test/library-tests/dataflow/taint/libraries/nsstring.swift
Additional `NSString` taint test cases.  Conversion between `NSString` and `String` / `Data` (and back again) is common so I wanted some additional testing around it.
> Swift: Additional NSString taint test cases

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/type-bugs.expected
In https://github.com/github/codeql/pull/11198 Tom added phi nodes for uses in the shared SSA library, but we haven't yet reaped the benefit of those in C++ since we've been using the backwards compatibility wrappers he made. This PR makes use of those new phi nodes for uses. It should give us a small performance boost 🤞.
[The first commit](d845cd7233117c805c9ac105b246eab8ccc04aff) does the real work, and the [second commit](34f8d4d3ebe549cc77d5b1a369c2583c4dc87a36) fixes a bug exposed by the tests.
> C++: Include "phi reads" in `DataFlow::Node`

- cpp/ql/test/library-tests/syntax-zoo/aliased_ssa_consistency.expected
- cpp/ql/test/library-tests/syntax-zoo/assignexpr.cpp
- cpp/ql/test/library-tests/syntax-zoo/conditional_destructors.cpp
- cpp/ql/test/library-tests/syntax-zoo/constmemberaccess.cpp
- cpp/ql/test/library-tests/syntax-zoo/constructorinitializer.cpp
- cpp/ql/test/library-tests/syntax-zoo/cpp11.cpp
- cpp/ql/test/library-tests/syntax-zoo/dataflow-consistency.expected
- cpp/ql/test/library-tests/syntax-zoo/dataflow-ir-consistency.expected
- cpp/ql/test/library-tests/syntax-zoo/defconstructornewexpr.cpp
- cpp/ql/test/library-tests/syntax-zoo/defdestructordeleteexpr.cpp
- cpp/ql/test/library-tests/syntax-zoo/deleteexpr.cpp
- cpp/ql/test/library-tests/syntax-zoo/ellipsisexceptionhandler.cpp
- cpp/ql/test/library-tests/syntax-zoo/exceptionhandler.cpp
- cpp/ql/test/library-tests/syntax-zoo/fieldaccess.cpp
- cpp/ql/test/library-tests/syntax-zoo/ir.cpp
- cpp/ql/test/library-tests/syntax-zoo/membercallexpr.cpp
- cpp/ql/test/library-tests/syntax-zoo/membercallexpr_args.cpp
- cpp/ql/test/library-tests/syntax-zoo/ms_try_mix.cpp
- cpp/ql/test/library-tests/syntax-zoo/newexpr.cpp
- cpp/ql/test/library-tests/syntax-zoo/nonmembercallexpr.c
- cpp/ql/test/library-tests/syntax-zoo/parameterinitializer.cpp
- cpp/ql/test/library-tests/syntax-zoo/pmcallexpr.cpp
- cpp/ql/test/library-tests/syntax-zoo/raw_consistency.expected
- cpp/ql/test/library-tests/syntax-zoo/staticlocals.cpp
- cpp/ql/test/library-tests/syntax-zoo/staticmembercallexpr.cpp
- cpp/ql/test/library-tests/syntax-zoo/staticmembercallexpr_args.cpp
- cpp/ql/test/library-tests/syntax-zoo/stmt_expr.cpp
- cpp/ql/test/library-tests/syntax-zoo/unaliased_ssa_consistency.expected
These were due to several functions occurring that would have the same TRAP key. By making the functions static or wrapping the defining class in an anonymous namespace the TRAP keys will differ from each other.
> C++: Silence some more bogus consistency errors in syntax zoo

- ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll
The Core team is planning to make some changes to the join orderer that causes a join order regression for the `controllerTemplateFile` predicate. This PR restructures the predicate slightly to prevent the join order regression.
Old predicate with current join orderer:
```
Evaluated non-recursive predicate ActionController#32b59475::controllerTemplateFile#2#ff@829c7fc9 in 512ms (size: 382).
Evaluated relational algebra for predicate ActionController#32b59475::controllerTemplateFile#2#ff@829c7fc9 with tuple counts:
8048121   ~4%    {2} r1 = JOIN locations_default_10#join_rhs WITH FileSystem#df18ed9a::Make#FileSystem#e91ad87f::Input#::Container::getRelativePath#0#dispred#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1
4258   ~2%    {2} r2 = JOIN r1 WITH …
```
> ActionController: Prevent bad join

- cpp/ql/lib/semmle/code/cpp/Declaration.qll
The QLDoc already mentions that this predicate is deprecated.
> C++: Properly deprecate `hasQualifiedName` by using the `deprecated` keyword

- swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql
Update `swift/string-length-conflation` to taint tracking, so that it benefits from flow through arithmetic operations without special cases (now that taint does indeed support these cases).  This may introduce new (hopefully good) results, though it doesn't in the MRVA top 100 so I think this will be rare.
> Swift: Update swift/string-length-conflation to taint tracking

- swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPrivate.qll
- swift/ql/lib/codeql/swift/elements/expr/ArithmeticOperation.qll
- swift/ql/lib/codeql/swift/elements/expr/BitwiseOperation.qll
- swift/ql/test/library-tests/dataflow/taint/core/LocalTaint.expected
- swift/ql/test/library-tests/dataflow/taint/core/Taint.expected
- swift/ql/test/library-tests/dataflow/taint/core/simple.swift
- swift/ql/test/library-tests/elements/expr/arithmeticoperation/arithmeticoperation.expected
- swift/ql/test/library-tests/elements/expr/arithmeticoperation/arithmeticoperation.swift
- swift/ql/test/library-tests/elements/expr/bitwiseopration/bitwiseoperation.expected
- swift/ql/test/library-tests/elements/expr/bitwiseopration/bitwiseoperation.ql
- swift/ql/test/library-tests/elements/expr/bitwiseopration/bitwiseoperation.swift
Fill some gaps in our arithmetic / bitwise operations modelling:
- overflow arithmetic operations (such as `&+`); they are now treated as variants of the corresponding basic operator (such as `+`).
- overflow bitwise operations (`&<<` and `&>>`); they are now treated as variants of the corresponding basic operator (`<<` or `>>`).
- pointwise bitwise operations (such as `.&`); modelled by new classes, but considered members of the bitwise operations.
- taint flow through bitwise operations.
> Swift: Fill some gaps in arithmetic / bitwise operations modelling

- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
- swift/ql/lib/codeql/swift/frameworks/StandardLibrary/PointerTypes.qll
- swift/ql/test/library-tests/dataflow/taint/libraries/data.swift
- swift/ql/test/library-tests/dataflow/taint/libraries/nsstring.swift
- swift/ql/test/library-tests/dataflow/taint/libraries/unsafepointer.swift
- swift/ql/test/library-tests/elements/type/pointertypes/pointers.swift
- swift/ql/test/library-tests/elements/type/pointertypes/pointertypes.expected
- swift/ql/test/library-tests/elements/type/pointertypes/pointertypes.ql
- swift/ql/test/query-tests/Security/CWE-089/SqlInjection.expected
- swift/ql/test/query-tests/Security/CWE-089/sqlite3_c_api.swift
Permit data flow out through pointer arguments whose contents is modified in the function.  The main change is in `DataFlowPrivate.qll`.  The rest of the changes are adding a `PointerTypes.qll` library to identify pointer types, and lots of testing.
Questions:
- we could restrict `modifiable` to only include _mutable_ pointers, but I think this might introduce edge cases where there really is output through a non-mutable pointer??? (e.g. where the pointee is of immutable type but itself _refers_ to something mutable?)
- alternatively it might be right to widen `modifiable` to include `BoundGenericType`s, as these I think are very similar things to `NominalType`s.  All of the pointers I've modelled are either `NominalType` (which were already part of `modifiable`) or `BoundGenericType`, so …
> Swift: Permit data flow out through pointer arguments

- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
- go/ql/lib/semmle/go/dataflow/internal/DataFlowImpl.qll
- go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
In the process of adding more dataflow to C/C++ we've seen a large performance regression on a codebase that contains code like:
```cpp
void foo(int opcode, A* a) {
switch(opcode) {
case 0: /*...*/ break;
case 1: /*...*/ break;
...
case N: /*...*/ break;
}
}
```
where the code inside `/* ... */` causes the dataflow library to create a giant number of access paths:
<details>
| #  | n  | stage | nodes | field | conscand | states | tuples  | config                   |
|----|----|-------|-------|-------|----------|--------|---------|--------------------------|
| 1  | 10 | 1 Fwd | 95703 | 234   | -1       | 1      | 116835  | TaintedPathConfiguration |
| 2  | 15 | 1 Rev | 29976 | 111   | -1       | 1      | 41712   | TaintedPathConfiguration |
| 3  | 20 | 2 Fwd | 24169 | 85    | 147      | 1 …
> Dataflow: Add a language specific term to `join` and `branch`

- ruby/ql/lib/codeql/ruby/security/StoredXSSQuery.qll
- ruby/ql/lib/codeql/ruby/security/XSS.qll
- ruby/ql/src/queries/security/cwe-079/StoredXSS.ql
This PR converts the Stored XSS query to use the [new data flow interface](https://github.com/github/codeql/pull/12186). It may serve as inspiration for other similar rewrites, until our documentation has been updated.
> Ruby: Rewrite Stored XSS query to use new data flow interface

- cpp/ql/lib/semmle/code/cpp/Declaration.qll
- cpp/ql/lib/semmle/code/cpp/Function.qll
- cpp/ql/lib/semmle/code/cpp/commons/Alloc.qll
- cpp/ql/src/experimental/Security/CWE/CWE-415/DoubleFree.ql
- cpp/ql/test/library-tests/CPP-205/elements.expected
- cpp/ql/test/library-tests/CPP-205/elements.ql
- cpp/ql/test/library-tests/allocators/allocators.expected
- cpp/ql/test/library-tests/allocators/allocators.ql
- cpp/ql/test/library-tests/noexcept/copy_from_prototype/copy_from_prototype.expected
- cpp/ql/test/library-tests/noexcept/copy_from_prototype/copy_from_prototype.ql
Small follow-up to https://github.com/github/codeql/pull/12387
> C++: Add `deprecated` to predicates that are deprecated according to the QLDoc

- csharp/ql/integration-tests/all-platforms/dotnet_build/test.py
- csharp/ql/integration-tests/all-platforms/dotnet_pack/test.py
- csharp/ql/integration-tests/all-platforms/dotnet_publish/test.py
- csharp/ql/integration-tests/all-platforms/dotnet_run/test.py
- csharp/ql/integration-tests/all-platforms/msbuild/test.py
- csharp/ql/integration-tests/posix-only/dotnet_test/test.py
- csharp/ql/integration-tests/posix-only/inherit-env-vars/test.py
This PR adds calls to `check_diagnostics()` to all remaining integration tests to ensure that they do not produce any diagnostics, as expected (since they should all succeed).
> C#: Add diagnostic checks to all remaining integration tests

- csharp/extractor/Semmle.Util/ToolStatusPage.cs
- csharp/ql/integration-tests/all-platforms/diag_dotnet_incompatible/diagnostics.expected
- csharp/ql/integration-tests/all-platforms/diag_missing_project_files/diagnostics.expected
- csharp/ql/integration-tests/all-platforms/diag_missing_xamarin_sdk/diagnostics.expected
- csharp/ql/integration-tests/posix-only/diag_autobuild_script/diagnostics.expected
- csharp/ql/integration-tests/posix-only/diag_multiple_scripts/diagnostics.expected
- csharp/ql/integration-tests/windows-only/diag_autobuild_script/diagnostics.expected
- csharp/ql/integration-tests/windows-only/diag_multiple_scripts/diagnostics.expected
This PR changes the visibility of diagnostics emitted by the C# autobuilder so that they are used everywhere that we support by default (which applies to all existing diagnostics).
> C#: Make diagnostics visible everywhere

- cpp/ql/test/query-tests/Critical/MissingCheckScanf/MissingCheckScanf.expected
- cpp/ql/test/query-tests/Critical/MissingCheckScanf/test.cpp
See https://github.com/github/codeql/issues/12412 for the initial report.
> C++: add false positives to `MissingCheckScanf` test

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
- cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp
- cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
We've seen a number of weird results when using the IR version of the `UninitializedNode` class. This should hopefully fix the weirdness.
> C++: Fix `asUninitialized`

- python/ql/test/experimental/dataflow/coverage/argumentPassing.py
This is a bit of an edge case, but allowed. Since we currently don't
provide information on positional only arguments, we can't do much to
solve it right now.
> Python: Add test of keyword argument with same name as positional-only parameter

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This PR implements the predicate added to the shared dataflow library in https://github.com/github/codeql/pull/12236. The goal is to identify which `switch` statements read from/write a given parameter in many branches, which we've seen can cause a large number of access paths to be generated for certain projects.
I've started two DCA runs: One "normal" DCA run that compares the base branch with this PR (to inspect any performance or result changes), and one that just runs on this branch (since the problematic project will probably still OOM on the base branch, thus not even getting to running on this PR's branch).
> C++: Implement `getAdditionalFlowIntoCallNodeTerm`

- cpp/ql/src/Critical/OverflowDestination.ql
- cpp/ql/src/Likely Bugs/Memory Management/NtohlArrayNoBound.ql
- cpp/ql/src/Likely Bugs/Memory Management/NtohlArrayNoBound.qll
- cpp/ql/src/Security/CWE/CWE-020/ExternalAPIs.qll
- cpp/ql/src/Security/CWE/CWE-020/ExternalAPIsSpecific.qll
- cpp/ql/src/Security/CWE/CWE-020/IRUntrustedDataToExternalAPI.ql
- cpp/ql/src/Security/CWE/CWE-020/UntrustedDataToExternalAPI.ql
- cpp/ql/src/Security/CWE/CWE-020/ir/ExternalAPIs.qll
- cpp/ql/src/Security/CWE/CWE-020/ir/ExternalAPIsSpecific.qll
- cpp/ql/src/Security/CWE/CWE-129/ImproperArrayIndexValidation.ql
- cpp/ql/src/Security/CWE/CWE-190/ArithmeticUncontrolled.ql
- cpp/ql/src/Security/CWE/CWE-295/SSLResultConflation.ql
- cpp/ql/src/Security/CWE/CWE-311/CleartextBufferWrite.ql
- cpp/ql/src/Security/CWE/CWE-311/CleartextFileWrite.ql
- cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql
- cpp/ql/src/Security/CWE/CWE-313/CleartextSqliteDatabase.ql
- cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.ql
- cpp/ql/src/Security/CWE/CWE-326/InsufficientKeySize.ql
- cpp/ql/src/Security/CWE/CWE-497/ExposedSystemData.ql
- cpp/ql/src/change-notes/2023-03-08-deprecated-dataflow-configurations.md
- cpp/ql/src/experimental/Security/CWE/CWE-078/WordexpTainted.ql
- cpp/ql/src/experimental/Security/CWE/CWE-190/AllocMultiplicationOverflow.ql
Targeting the use-use dataflow feature branch, because I cannot be bothered to solve any merge conflicts when doing this on `main`.
> C++: Convert a number of data flow based queries to use `ConfigSig`

- csharp/autobuilder/Semmle.Autobuild.Shared/Autobuilder.cs
This provides some extra resilience where the autobuilder runs more than once at the same time.
> C#: Append process id to diagnostics filename

- go/ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll
- go/ql/src/Security/CWE-681/IncorrectIntegerConversionQuery.ql
- go/ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.ql
This was amended as part of https://github.com/github/codeql/pull/12186, but the conversion was inadequate because the new implementation didn't work when a sink (type conversion) led directly to a non-`localTaintStep` step, such as a store step or an interprocedural step. Here I move the sink back one step to the argument of the type conversion and sanitize the result of the conversion instead, to ensure there is always a unique local successor to a sink.
This should eliminate unexpected extra results that resulted from https://github.com/github/codeql/pull/12186. Independently there are also *lost* results that stem from needing a higher `fieldFlowBranchLimit` that are not addressed in this PR, but raising that limit is a performance risk and so I will address this separately.
> Go: fix incorrect-integer-conversion sanitizer

- cpp/ql/lib/semmle/code/cpp/Declaration.qll
Turns out this predicate can still be very large even with the restrictions mentioned in its QLDoc:
```
Evaluated relational algebra for predicate Declaration#4bfb53be::DirectAccessHolder::thisCouldAccessMember#3#dispred#ffff@8a38e2tm with tuple counts:
918297       ~7%    {4} r1 = JOIN _Declaration#4bfb53be::DirectAccessHolder::isFriendOfOrEqualTo#1#dispred#ff_10#join_rhs__Class#bacd9__#shared WITH Declaration#4bfb53be::DirectAccessHolder::isFriendOfOrEqualTo#1#dispred#ff ON FIRST 2 OUTPUT Lhs.0, Lhs.2, Lhs.3, Lhs.1
7885675       ~0%    {4} r2 = JOIN Declaration#4bfb53be::everyoneCouldAccessMember#3#fff_201#join_rhs WITH Declaration#4bfb53be::DirectAccessHolder::thisCanAccessClassTrans#fff_102#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Rhs.2
8803972       ~2%    {4} r3 = r1 UNION r2 …
```
> C++: Inline `thisCouldAccessMember`

- ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
This ensures that for every subclass of `Expr` in the ast library, there exists some corresponding `FooNode` class in the public dataflow library that is more specific than `ExprNode`.
> Ruby: ensure that all Ast `Expr`s have a dataflow node type more precise than `ExprNode`

- go/extractor/diagnostics/diagnostics.go
- go/ql/integration-tests/all-platforms/go/diagnostics/build-constraints-exclude-all-go-files/diagnostics.expected
- go/ql/integration-tests/all-platforms/go/diagnostics/package-not-found-with-go-mod/diagnostics.expected
- go/ql/integration-tests/all-platforms/go/diagnostics/package-not-found-without-go-mod/diagnostics.expected
Small update to source name and message for two diagnostics. This also updates the expected test output, which was erroneously not updated after a previous change in error message.
> The source name of a diagnostic should not change

- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/exercise4.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-expr.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-getenv.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-flow-from-param.ql
- cpp/ql/test/examples/docs-examples/analyzing-data-flow-in-cpp/fopen-no-flow.ql
- docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp-new.rst
- docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp.rst
- docs/codeql/codeql-language-guides/codeql-for-cpp.rst
First attempt at writing a docs page for the new use-use dataflow library. Before looping in the docs people and James, it's seems sensible to get feedback from @github/codeql-c-analysis. This is cloned from the original C/C++ doc on dataflow, which describes a library we are going to deprecate in the near future.
Note that I dropped the `exprNode(expr)` and `parameterNode(param)` from the documentation compared to the original version. I did this as there are no equivalents for indirect expressions and parameters.
> C++: Add copy of dataflow docs for new use-use dataflow library

- cpp/ql/src/Security/CWE/CWE-313/CleartextSqliteDatabase.ql
This PR reduces the set of sinks considered in the `cpp/cleartext-storage-database` query. Previously we used "all functions prefixed with `sqlite`", and after this PR it's confined to a specific set of functions. This fixes a performance issue I was seeing on a database that had a particularly bad naming convention of prefixing their own functions with `sqlite` 😂.
I've added two additional commits that each should provide a small performance boost.
> C++: Restrict sinks in `cpp/cleartext-storage-database`

- javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java
The `extract` method may return `null`:
```java
/** @return the number of lines of code extracted, or {@code null} if the file was cached */
public ParseResultInfo extract(File f, ExtractorState state) throws IOException {
```
> JS: fix NPE

- swift/ql/src/queries/Summary/SummaryStats.ql
I had hoped this would magically fix the regression in the taint reach statistic.  It didn't.  Still, updating this query is a small step in the right direction.
> Swift: Update swift/summary/summary-statistics to DataFlow::ConfigSig

- cpp/ql/lib/change-notes/2023-03-13-mergepathgraph.md
- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlow.qll
- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlow.qll
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlow.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
- csharp/ql/lib/change-notes/2023-03-13-mergepathgraph.md
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlow.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll
- go/ql/lib/change-notes/2023-03-13-mergepathgraph.md
- go/ql/lib/semmle/go/dataflow/internal/DataFlow.qll
- go/ql/lib/semmle/go/dataflow/internal/DataFlowImpl.qll
- java/ql/lib/change-notes/2023-03-13-mergepathgraph.md
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll
- python/ql/lib/change-notes/2023-03-13-mergepathgraph.md
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlow.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll
- ruby/ql/lib/change-notes/2023-03-13-mergepathgraph.md
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlow.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlow.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll
This adds a convenience module that allows easy combination of 2 PathGraph modules as a disjoint union in order to display the results of two separate flow computations in a path-problem query.
> Dataflow: Add MergePathGraph module.

- javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectQuery.qll
- javascript/ql/lib/semmle/javascript/security/dataflow/RequestForgeryCustomizations.qll
- javascript/ql/lib/semmle/javascript/security/dataflow/ServerSideUrlRedirectQuery.qll
- javascript/ql/lib/semmle/javascript/security/dataflow/SqlInjectionQuery.qll
- javascript/ql/lib/semmle/javascript/security/dataflow/TaintedPathCustomizations.qll
- javascript/ql/src/change-notes/2023-03-07-html-sanitizer-for-sql.md
- javascript/ql/test/query-tests/Security/CWE-089/untyped/DatabaseAccesses.expected
- javascript/ql/test/query-tests/Security/CWE-089/untyped/SqlInjection.expected
- javascript/ql/test/query-tests/Security/CWE-089/untyped/html-sanitizer.js
The following queries now recognize HTML sanitizers as propagating taint: `js/sql-injection`,
`js/path-injection`, `js/server-side-unvalidated-url-redirection`, `js/client-side-unvalidated-url-redirection`,
and `js/request-forgery`.
[Evaluation](https://github.com/github/codeql-dca-main/issues/11479) was uneventful.
> JS: Add html sanitizers as a taint step in a few queries

- csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll
- go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
- go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll
- java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
- java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImplSpecific.qll
- python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImplSpecific.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
- swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll
- swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImplSpecific.qll
If we have a flow summary for, say, a method that passes its first argument into the first parameter of its second argument:
```ql
input = Argument[0] and
output = Parameter[0].Argument[1]
```
and we are modeling the call-back as being passed into itself (as a `self/this` argument), then we are currently missing a post-update node for the implicit self argument. Adding this is relevant when modeling captured variable flow using field flow.
> Data flow: Synthesize post-update nodes for callback arguments inside summarized callables

- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This PR supersede https://github.com/github/codeql/pull/12477 and (hopefully) contains the correct performance fix.
On certain projects containing heavily macro-expanded code like:
```cpp
*x = source();
use(x[0]);
use(x[1]);
...
use(x[i]);
use(x[i+1]);
...
use(x[N]);
```
we hit a performance problem caused by each expression of the form `x[i]` being stepped to from `*x = source()` in certain cases in the expression-only local flow relation.
To see why this is the case, consider the transitive closure over `localStepFromNonExpr` in `localStepsToExpr`. We start at `n2` for which `n.asExpr()` exists. For example, `n2` in the above example could be `x[i]` in any of the `use(x[i])` above. We then step to a dataflow predecessor of `n2`. In the above code fragment, thats the indirect node …
> C++: Map some indirect nodes to expressions in `localExprFlowStep`

- ruby/ql/lib/change-notes/2023-03-13-initalize-flow.md
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
- ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
- ruby/ql/test/library-tests/dataflow/global/Flow.expected
- ruby/ql/test/library-tests/dataflow/global/TypeTrackingInlineTest.expected
- ruby/ql/test/library-tests/dataflow/global/instance_variables.rb
We were missing data flow through `initialize` calls in cases like
```rb
class Foo
def self.bar
new(taint) # calls Foo#initialize
end
def initialize x
sink x
end
end
```
> Ruby: Add missing flow through `self.new` constructor calls

- javascript/ql/lib/semmle/javascript/frameworks/React.qll
- javascript/ql/test/library-tests/frameworks/ReactJS/higherOrderComponent.jsx
Recognises React components wrapped in `React.forwardRef`.
> JS: Handle forwardRef in React

- java/ql/lib/semmle/code/java/PrintAst.qll
- java/ql/test/library-tests/printAst/A.java
- java/ql/test/library-tests/printAst/PrintAst.expected
Javadoc comments might be linked to multiple elements. In these cases the AST node of these comments have multiple parents, which means we can't print a well-formed tree. This PR fixes this issue by introducing distinct AST nodes for these comment-element pairs.
> Java: Fix printAST to handle javadoc belonging to multiple elements

- cpp/ql/lib/experimental/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll
- cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplCommon.qll
- go/ql/lib/semmle/go/dataflow/internal/DataFlowImplCommon.qll
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplCommon.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplCommon.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplCommon.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplCommon.qll
Since we do not support field flow when resolving lambdas, we may as well skip nodes that expect data to be stored inside a field.
> Data flow: Exclude `expectsContent` nodes from lambda flow

- swift/ql/lib/codeql/swift/elements/type/NominalType.qll
- swift/ql/test/library-tests/elements/type/nominaltype/nominaltype.expected
`NominalType.getABaseType` had an unnecessarily restricted return type, that was hiding base types that are a `typealias`.
> Swift: Fix result type of NominalType.getABaseType.

- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll
Identified via https://github.com/github/codeql/pull/12519.
> Swift: Fix `SummaryCall::getEnclosingCallable`

- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll
- python/ql/test/experimental/dataflow/TestUtil/DataFlowConsistency.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
We wanted to ensure that a callable did not have multiple parameters with same parameter position. Originally we fixed this in both Ruby and Python by introducing flow between the synthetic and the normal hash-splat/**kwargs parameters. 
However, since that made things more complex to understand, in this PR I revert those fixes, and instead solve it by introducing a new parameter position (like already discussed).
_(draft PR to check that tests pass before requesting review)_
> Python/Ruby: Use new parameter position for synthetic hash-splat instead

- csharp/ql/lib/semmle/code/csharp/dispatch/Dispatch.qll
- csharp/ql/test/library-tests/dispatch/CallContext.expected
- csharp/ql/test/library-tests/dispatch/CallGraph.expected
- csharp/ql/test/library-tests/dispatch/GetADynamicTarget.expected
- csharp/ql/test/library-tests/dispatch/ViableCallable.cs
- csharp/ql/test/library-tests/dispatch/viableCallable.expected
In this PR, we
- Fix issue with dispatch to implementations of virtual interface members for generics.
- Make support for virtual dispatch of operators (Operators are now considered Overridables).
From C# 11 it is possible to declare abstract and virtual operators (see the example below), which means that operator calls no longer only have static call targets. We have implemented support for dynamic call targeting for operators in C#.
```csharp
public interface I<T> where T : I<T>
{
static abstract T operator +(T x, T y);
static virtual T operator -(T x, T y) => throw null;
}
public class C : I<C>
{
public static C operator +(C x, C y) => throw null;
public static C operator /(C x, C y) => throw null;
}
```
> C#: Support for virtual dispatch for operators.

- cpp/ql/test/library-tests/ir/range-analysis/SimpleRangeAnalysis_tests.cpp
This demonstrates a missing bound from nested phi nodes.
> C++: Add `range` call to test

- cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll
- cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
- csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll
- go/ql/lib/semmle/go/dataflow/internal/DataFlowImpl.qll
- java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll
- python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll
- ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll
- swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll
It turns out that implementing the `getAFeature()` predicate can lead to a compile error (as seen in https://github.com/github/codeql/pull/12535).
In this PR we make a small re-factor (workaround) to avoid the use of an empty predicate in an IPA type branch, which solves the compilation issue.
> DataFlow: Workaround empty predicate usage in IPA branch.

- java/ql/lib/semmle/code/java/PrintAst.qll
- java/ql/test/kotlin/library-tests/jvmoverloads-annotation/PrintAst.expected
We now look not only at how many parameters each callable has, but what its full signature is. This allows us to give a consistent order to
```
Test(Throwable) { ... }
Test(String) { ... }
```
> Java: PrintAst: Improve the ranking of callables

- go/ql/lib/semmle/go/security/ExternalAPIs.qll
- go/ql/src/change-notes/2023-03-16-untrusted-data-write-only-args.md
These functions (and doubtless many others) are write-only with respect to their receiver argument, so it doesn't really make sense to flag externally-controlled data flowing there.
> Go: exclude `net/http.Header.Set` and `.Del` from `go/untrusted-data-to-external-api`

- docs/codeql/reusables/supported-versions-compilers.rst
- javascript/extractor/lib/typescript/package.json
- javascript/extractor/lib/typescript/src/main.ts
- javascript/extractor/lib/typescript/src/type_table.ts
- javascript/extractor/lib/typescript/yarn.lock
- javascript/extractor/src/com/semmle/js/extractor/Main.java
- javascript/extractor/src/com/semmle/ts/extractor/TypeScriptASTConverter.java
- javascript/ql/lib/change-notes/2023-01-27-typescript-5-0.md
- javascript/ql/test/library-tests/TypeScript/Types/printAst.expected
- javascript/ql/test/library-tests/TypeScript/Types/tests.expected
- javascript/ql/test/library-tests/TypeScript/Types/tst.ts
A straight-forward upgrade. 
Tests should start passing after an internal PR has been merged.
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/ts50__typescript-full__code-scanning/reports).  
~~I got the CI to run on the internal PR (I think), so this is not ready to merge before the internal PR has been merged, even though the CI might be green.~~   
Internal PR merged, everything running on `main` and passing 👍
> JS: Add support for TypeScript 5.0

- javascript/ql/lib/semmle/javascript/frameworks/Express.qll
- javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/ServerSideUrlRedirect.expected
- javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/express.js
CVE-2022-2237: Recognize the source
I'm hoping the code is self-explanatory.  
[Evaluation was unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-12518-a72436__nightly-old__code-scanning/reports).
> JS: recognize more express URL related sources

- ql/ql/src/queries/style/DataFlowConfigModuleNaming.ql
- ql/ql/test/queries/style/DataFlowConfigModuleNaming/DataFlowConfigModuleNaming.expected
- ql/ql/test/queries/style/DataFlowConfigModuleNaming/DataFlowConfigModuleNaming.qlref
- ql/ql/test/queries/style/DataFlowConfigModuleNaming/Test.qll
Adds a style check to detect modules implementing `DataFlow::ConfigSig`(/`StateConfig`/`FullStateConfig`) and do not end with `Config`.
This can help maintain a consistent naming convention as we refactor dataflow configurations now that #12186 has been merged.
PR to bring files into compliance: #12578
> QL: add a check to enforce naming convention for new `DataFlow::ConfigSig` modules
