github/codeql

python/ql/test/experimental/dataflow/variable-capture/collections.py

We could handle this case specially, by having
a different implementation for `for`, but the
wider issue would remain.

python: add test for captured variables in lists

---

cpp/ql/lib/change-notes/2023-03-20-boost-deprecated-dataflow-configurations.md
cpp/ql/lib/semmle/code/cpp/security/boostorg/asio/protocols.qll
cpp/ql/src/Likely Bugs/Protocols/TlsSettingsMisconfiguration.ql
cpp/ql/src/Likely Bugs/Protocols/UseOfDeprecatedHardcodedProtocol.ql

I'm not sure if it's worth running DCA, as the modified queries do not have an associated precision.

C++: Refactor `BoostorgAsio` to use `DataFlow::ConfigSig`

---

java/ql/lib/semmle/code/java/regex/RegexTreeView.qll
python/ql/lib/qlpack.yml
python/ql/lib/semmle/python/RegexTreeView.qll
python/ql/src/qlpack.yml

My own followup to https://github.com/github/codeql/pull/12169 
Evaluations look uneventful: [Python](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-12550-1-python/reports), [Java](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-12550-0-java/reports).

Java/Python: use Number.qll to parse hex numbers in regex parsing

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll

This PR remove `revFlowAlias` and `revFlowApAlias` predicates from the dataflow library. The `revFlowAlias` and `revFlowApAlias` predicates were introduced to prevent the compiler from joining on constant node columns. With recent changes to the join ordering heuristic to avoid joins on constant columns, these alias predicates are no longer needed.

Dataflow: Remove revFlowAlias and revFlowApAlias predicates

---

swift/extractor/main.cpp

InitializeSwiftModules.h is included twice. The others are simply unused.

Swift: Cleanup: Remove some unused #includes.

---

swift/ql/lib/codeql/swift/elements/decl/TypeDecl.qll

This fixes the formatting of `swift/ql/lib/codeql/swift/elements/decl/TypeDecl.qll`.
CodeQL 2.12.5 had some changes to the formatter.

Swift: Fix formatting of TypeDecl.qll

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplCommon.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowImplCommon.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
java/ql/lib/semmle/code/java/ControlFlowGraph.qll
java/ql/lib/semmle/code/java/dataflow/SSA.qll
java/ql/lib/semmle/code/java/dataflow/internal/BaseSSA.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplCommon.qll
java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
java/ql/lib/semmle/code/java/frameworks/JaxWS.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplCommon.qll
python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplCommon.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplCommon.qll
swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll

Past-me had left this lying in a local branch and presumably just neglected to make it into a PR. It looks reasonable, so here goes.

Java/dataflow: Misc performance fixes

---

ql/ql/src/queries/diagnostics/EmptyConsistencies.ql

It's starting to fail a little too much: https://github.com/github/codeql/pull/12615/files 
Should be re-enabled once QL-for-QL is (hopefully) better at parameterized modules.

QL: disable the consistency check

---

ql/ql/src/codeql_ql/StructuredLogs.qll
ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll

The extractor got updated at some point without the updated `TreeSitter.qll` file getting committed.  
I just ran `ql/scripts/create-extractor-pack.sh`, and re-generated the `TreeSitter.qll` file with that.

QL: regen TreeSitter.qll

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/rangeanalysis/SignAnalysisCommon.qll
java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/SignAnalysisCommon.qll

The value of a long ought to always be convertible to a float, so that case does nothing (it's been around for a long time and git forensics indicate a possible cause, but it's not entirely clear).
The int case is also useless even though it isn't empty in the C# case, but in those cases (large unsigned ints) it is covered by `getNonIntegerValue` and hence still irrelevant.

Java/C#: Remove useless disjuncts.

---

.github/workflows/ruby-build.yml
ruby/doc/HOWTO.md
ruby/extractor/rust-toolchain.toml
ruby/extractor/src/bin/extractor.rs

This should not affect our support for systems with older glibc versions (e.g. Centos 7), and it will allow us to use newer library versions and Cargo features.
In addition, I've added a specific test that runs the extractor in a Centos 7 container, to ensure that we don't break this compatibility in future.

Ruby: Bump rust toolchain to 1.68

---

cpp/ql/lib/experimental/semmle/code/cpp/semantic/SemanticType.qll

I wasn't able to construct a testcase where this had any effect since all my attempts with tests like:
```cpp
void test() {
bool b = false;
range(b); // $ range===0
}
```
failed 😕. However, surely bool to int conversions _should_ be included in this predicate @rdmarsh2?

C++: `bool` -> `int` are safe conversions

---

.github/workflows/check-change-note.yml

The current “needs change note” CI check does not fail when there is no change note and we only make changes in `.yml` files (MaD/external models). This PR updates the change note check to account for this situation.
Please let me know if there is anything else that needs to be changed/tested for this update (I've never updated a CI workflow before, so I'm not sure if I'm missing anything 🙂).  
(cc @atorralba)

CI: Add yml files to change note check

---

java/ql/lib/change-notes/2023-03-20-nativesql-summary.md
java/ql/lib/ext/java.sql.model.yml

This PR adds `java.sql.Connection#nativeSQL(String)` as a summary model. This model was discovered via heuristics.

Java: add sql summary model discovered with heuristics

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll

This PR instantiates access paths for stage 1 of the dataflow library with a proper unit type. With recent changes to the join orderer to avoid joins on constant columns and DIL to RA term translation optimisations, the previous trick to prevent the optimiser from inferring that access paths were constant is no longer needed. 
The initial Java DCA experiment showed a significant regression for `palatable__lambda` but it didn't reproduce in subsequent reruns.

Dataflow: Instantiate stage 1 access paths with proper unit type

---

java/ql/lib/change-notes/2023-03-23-jndi-sanitizer.md
java/ql/lib/semmle/code/java/security/JndiInjection.qll
java/ql/lib/semmle/code/java/security/JndiInjectionQuery.qll

Currently it's not possible to modify the definition of JndiInjectionFlowConfig sanitizer when performing Customizations. This PR adds a class JndiInjectionSanitizer that will be used whenever Customizations are needed for the sanitizer.

Java : Add JndiInjection Sanitizer Class

---

java/ql/lib/change-notes/2023-03-22-deprecate-webviewdubuggingenabledquery.md
java/ql/lib/semmle/code/java/security/AndroidCertificatePinningQuery.qll
java/ql/lib/semmle/code/java/security/AndroidIntentRedirectionQuery.qll
java/ql/lib/semmle/code/java/security/ImproperIntentVerificationQuery.qll
java/ql/lib/semmle/code/java/security/SensitiveKeyboardCacheQuery.qll
java/ql/lib/semmle/code/java/security/UnsafeAndroidAccessQuery.qll
java/ql/lib/semmle/code/java/security/WebviewDebuggingEnabledQuery.qll
java/ql/lib/semmle/code/java/security/WebviewDubuggingEnabledQuery.qll
java/ql/src/Security/CWE/CWE-489/WebviewDebuggingEnabled.ql
java/ql/src/Security/CWE/CWE-749/UnsafeAndroidAccess.ql
java/ql/src/Security/CWE/CWE-940/AndroidIntentRedirection.ql
java/ql/test/query-tests/security/CWE-489/webview-debugging/WebviewDebuggingEnabled.ql
java/ql/test/query-tests/security/CWE-749/UnsafeAndroidAccessTest.ql
java/ql/test/query-tests/security/CWE-940/AndroidIntentRedirectionTest.ql

This refactors `Query.qll` libraries related to Android to use the new dataflow module api.

Java: Refactor Android `Query.qll` libraries to new dataflow api

---

cpp/ql/lib/experimental/semmle/code/cpp/rangeanalysis/ExtendedRangeAnalysis.qll
cpp/ql/lib/experimental/semmle/code/cpp/rangeanalysis/extensions/StrlenLiteralRangeExpr.qll
cpp/ql/test/experimental/library-tests/rangeanalysis/strlenliteral/StrlenLiteralRange.expected
cpp/ql/test/experimental/library-tests/rangeanalysis/strlenliteral/StrlenLiteralRange.ql
cpp/ql/test/experimental/library-tests/rangeanalysis/strlenliteral/test.cpp

While determining the range of the return value of `strlen` is difficult in the general case, we can precisely and efficiently determine the range when the argument is a literal string. This extra precision can help reduce false positives in some queries.

C++: Add StrlenLiteralRangeExpr

---

cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.ql

Before on Wireshark:
```
[2023-03-27 12:59:25] Evaluated non-recursive predicate OverrunWriteProductFlow#fb5ce006::isSinkPairImpl#5#fffff@2ba90584 in 99742ms (size: 52640).
Evaluated relational algebra for predicate OverrunWriteProductFlow#fb5ce006::isSinkPairImpl#5#fffff@2ba90584 with tuple counts:
1047588019  ~1%    {3} r1 = JOIN DataFlowUtil#47741e1f::InstructionNode#fff_20#join_rhs WITH OverrunWriteProductFlow#fb5ce006::bounded#3#fff_102#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Rhs.2
67558965  ~0%    {4} r2 = JOIN r1 WITH Instruction#577b6a83::CallInstruction::getArgument#fbf_201#join_rhs ON FIRST 1 OUTPUT Rhs.2, Lhs.1, Lhs.2, Rhs.1
613572640  ~0%    {5} r3 = JOIN r2 WITH ArrayFunction#ca0b6b68::ArrayFunction::hasArrayWithVariableSize#2#dispred#fff_201#join_rhs ON FIRST 1 OUTPUT …
```

C++: Fix join-order problem in cpp/overrun-write

---

ruby/ql/lib/codeql/ruby/ast/internal/Call.qll
ruby/ql/lib/codeql/ruby/ast/internal/Synthesis.qll
ruby/ql/lib/codeql/ruby/printAst.qll
ruby/ql/test/library-tests/ast/AstDesugar.expected
ruby/ql/test/library-tests/ast/calls/calls.expected
ruby/ql/test/library-tests/controlflow/graph/Cfg.expected
ruby/ql/test/library-tests/controlflow/graph/Nodes.expected

This PR changes the order in which children of synthesized nodes are being rendered in Print AST, from using the location to using the index into their parent (i.e., evaluation order). Since blocks were previously using index `-2`, I had to change that to have blocks be printed after ordinary arguments.
I also spotted an [off-by-one error](https://github.com/github/codeql/pull/12612/files#diff-d52a329ae12c686b2596e20d1bf873c2729439c1d5524915250d2344eacafec1R821), which has been fixed here as well.

Ruby: Order synthetic children in PrintAST based on their index instead of location

---

docs/codeql/codeql-language-guides/functions-in-python.rst

A noted in https://github.com/github/codeql/issues/12512
This replaces the reference to type inference with one to the API graph and adds a link.

python: Fix link to type inference

---

python/ql/src/Expressions/IncorrectComparisonUsingIs.ql

see triage [here](https://github.com/github/codeql-python-team/issues/628#issuecomment-1328933001)
- no longer try to interpret the class of operands
- simply alert in clear bad cases of uninterned literals
- surprisingly(?), all tests still pass

python: port `py/comparison-using-is`

---

ruby/ql/lib/codeql/ruby/ast/internal/Module.qll
ruby/ql/test/library-tests/modules/ancestors.expected
ruby/ql/test/library-tests/modules/methods.expected
ruby/ql/test/library-tests/modules/modules.expected
ruby/ql/test/library-tests/modules/superclasses.expected
ruby/ql/test/library-tests/modules/unresolved_subclass.rb

Previously we were unable to generate a qualified name for `module A::B::C` unless we could find the definition of `A::B` somewhere. This means that references to that module would fail to resolve, for example:
```rb
class A::B::C
end
class X < A::B::C # <- fail to resolve base class
end
```
This PR extends the approach from https://github.com/github/codeql/pull/10928, and like that PR, doesn't try to fix the problem in general, just fix what can be done without overhauling constant resolution.
Whenever a module/class is declared in the top-level, we assume we've seen a definition of each of the modules mentioned in the scope expression. So in the above example, we assume the existence of a module `A` and `A::B`.
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/alway …

RB: always resolve toplevel namespaces to their locally qualified name

---

java/ql/lib/semmle/code/java/security/GroovyInjectionQuery.qll
java/ql/lib/semmle/code/java/security/JexlInjectionQuery.qll
java/ql/lib/semmle/code/java/security/JndiInjectionQuery.qll
java/ql/lib/semmle/code/java/security/MvelInjectionQuery.qll
java/ql/lib/semmle/code/java/security/OgnlInjectionQuery.qll
java/ql/lib/semmle/code/java/security/SpelInjectionQuery.qll
java/ql/lib/semmle/code/java/security/SqlInjectionQuery.qll
java/ql/lib/semmle/code/java/security/TemplateInjectionQuery.qll
java/ql/lib/semmle/code/java/security/XsltInjectionQuery.qll
java/ql/lib/semmle/code/java/security/regexp/RegexInjectionQuery.qll
java/ql/src/Security/CWE/CWE-074/JndiInjection.ql
java/ql/src/Security/CWE/CWE-074/XsltInjection.ql
java/ql/src/Security/CWE/CWE-089/SqlConcatenated.ql
java/ql/src/Security/CWE/CWE-089/SqlTainted.ql
java/ql/src/Security/CWE/CWE-094/GroovyInjection.ql
java/ql/src/Security/CWE/CWE-094/JexlInjection.ql
java/ql/src/Security/CWE/CWE-094/MvelInjection.ql
java/ql/src/Security/CWE/CWE-094/SpelInjection.ql
java/ql/src/Security/CWE/CWE-094/TemplateInjection.ql
java/ql/src/Security/CWE/CWE-730/RegexInjection.ql
java/ql/src/Security/CWE/CWE-917/OgnlInjection.ql
java/ql/test/query-tests/security/CWE-074/JndiInjectionTest.ql
java/ql/test/query-tests/security/CWE-074/XsltInjectionTest.ql
java/ql/test/query-tests/security/CWE-094/GroovyInjectionTest.ql
java/ql/test/query-tests/security/CWE-094/JexlInjectionTest.ql
java/ql/test/query-tests/security/CWE-094/MvelInjectionTest.ql
java/ql/test/query-tests/security/CWE-094/SpelInjectionTest.ql
java/ql/test/query-tests/security/CWE-094/TemplateInjectionTest.ql
java/ql/test/query-tests/security/CWE-730/RegexInjectionTest.ql
java/ql/test/query-tests/security/CWE-917/OgnlInjectionTest.ql

Refactor `Query.qll` files for queries involving injection to use the new dataflow module API.

Java: Refactor injection queries to new dataflow API

---

java/ql/lib/change-notes/2023-03-28-deprecated-exectainted.md
java/ql/lib/semmle/code/java/security/CommandLineQuery.qll
java/ql/lib/semmle/code/java/security/RequestForgeryConfig.qll
java/ql/src/Security/CWE/CWE-078/ExecTainted.ql
java/ql/src/Security/CWE/CWE-078/ExecUnescaped.ql
java/ql/src/experimental/Security/CWE/CWE-078/ExecTainted.ql

- Refactor CommandLineQuery.qll to the new dataflow api
- Refactor RequestForgeryConfig.qll to make the configuration public

Java: Refactor CommandLineQuery.qll and RequestForgeryConfig.qll

---

swift/extractor/infra/SwiftDispatcher.h

This change fixes all of the VALUE_NOT_IN_TYPE errors I'm seeing with the integration tests on macOS.

Swift: consider declarations from non-swift modules as lazy

---

cpp/ql/lib/change-notes/2023-03-30-bufferaccess.md
cpp/ql/lib/semmle/code/cpp/security/BufferAccess.qll

Adds the `getSizeExpr` predicate to `BufferAccess`, which returns the `Expr` corresponding to the size of the buffer access. This is useful as `getSize()` will only have a result if the size is a constant.
Fixes https://github.com/github/codeql/issues/12597

C++: Add getSizeExpr and getSizeMult predicates to BufferAccess

---

javascript/ql/src/Security/CWE-295/DisablingCertificateValidation.ql
javascript/ql/src/change-notes/2023-03-27-disabling-certificate-validation.md
javascript/ql/test/query-tests/Security/CWE-295/DisablingCertificateValidation.expected
javascript/ql/test/query-tests/Security/CWE-295/tst.js

The `DisablingCertificateValidation.ql` query has been improved by checking `createServer` from `https` for disabled certificate validation.

JS: Improved coverage for disabled certificate validation

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/test/library-tests/dataflow/operators/Operator.cs
csharp/ql/test/library-tests/dataflow/operators/operatorFlow.expected
csharp/ql/test/library-tests/dataflow/operators/operatorFlow.ql

In this PR we introduce support for (local) data flow in explicitly checked and unchecked expressions
```csharp
var z1 = checked(x + y);
...
var z2 = unchecked(x + y);
```
Furthermore, we introduce data flow tests for operators in general and operators utilising the checked and unchecked expression construct.

C#: Dataflow via checked and unchecked expressions.

---

swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll

Add missing import in `ExternalFlow.qll`.  This should have been part of https://github.com/github/codeql/pull/12642 .

Swift: Add missing import.

---

cpp/ql/lib/experimental/semmle/code/cpp/rangeanalysis/extensions/RangeNode.qll

This PR adds a `RangeNode` class, which can be included in any path query to see the calculated ranges of variables.
I've found this useful, so I wanted to see if you would be interested in something like this upstream, but no worries if you don't think something like this should be merged.
I'm also not sure which folder this should go in, and if all the helper predicates are fine here or should be moved somewhere else (or removed).

C++: Add RangeNode class

---

cpp/ql/src/Likely Bugs/Memory Management/SuspiciousCallToStrncat.ql

Before:
```ql
Evaluated relational algebra for predicate #select#cpe#1#f@f2abad8d with tuple counts:
888    ~0%    {2} r1 = SCAN Buffer#834c97d7::BufferSizeExpr::getArg#0#dispred#bf OUTPUT In.1, In.0
888    ~0%    {2} r2 = JOIN r1 WITH Access#8878f617::Access::getTarget#0#dispred#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1
888    ~2%    {3} r3 = JOIN r2 WITH SuspiciousCallToStrncat#a7ff8513::interestingCallWithArgs#3#fff_102#join_rhs ON FIRST 1 OUTPUT Rhs.2, Lhs.1, Rhs.1
0    ~0%    {1} r4 = JOIN r3 WITH Access#8878f617::Access::getTarget#0#dispred#ff ON FIRST 2 OUTPUT Lhs.2
3797254    ~0%    {3} r5 = SCAN Expr#ef463c5d::Expr::getValue#0#dispred#ff OUTPUT In.0, In.1, toInt(In.1)
3797254    ~0%    {2} r6 = SCAN r5 OUTPUT In.2, In.0
876120    ~0%    {2} r7 = JOIN r6 WITH …
```

C++: Fix join order in `cpp/unsafe-strncat`

---

ql/ql/src/codeql_ql/ast/Ast.qll
ql/ql/test/type/type.expected

Previously this would return both the `ClassCharType` and `ClassType`.
I noticed some FPs when using the `DependencyPath.ql` query, which were caused by the query assuming that `Class.getType()` would only return its `ClassType`. I think that's the more obvious behavior, hence this PR.

QL: Make Class.getType() only return ClassType

---

javascript/ql/src/Security/CWE-916/InsufficientPasswordHash.qhelp

This broke in https://github.com/github/codeql/pull/12666 The qhelp probably needs a more substantial update, as an example has been added which is not referred to in the qhelp.

JS: Fix qhelp after file rename

---

java/ql/src/Security/CWE/CWE-023/PartialPathTraversalBad.java
java/ql/src/Security/CWE/CWE-023/PartialPathTraversalGood.java
java/ql/src/Security/CWE/CWE-023/PartialPathTraversalRemainder.inc.qhelp
java/ql/test/query-tests/security/CWE-023/semmle/tests/PartialPathTraversalTest.java

The original wouldn't compile, and the fix made by #11899 is sub-optimal.
This keeps the entire comparision using the Java `Path` object, which is optimal.
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>

Fix partial path traversal Java example Again

---

javascript/ql/lib/semmle/javascript/frameworks/CryptoLibraries.qll

- Use API graphs instead of local DataFlow
- Use set literals
- Prefer chaining over local variables in some cases
[Evaluation](https://github.com/github/codeql-dca-main/issues/12214) was neutral.

JS: Modernize crypto libraries

---

javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java

Now targeting `codeql-cli-2.12.6`.

JS: only set the file in the diagnostics message if the file is within the source root

---

ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll
ruby/ql/test/library-tests/frameworks/http_clients/HttpClients.expected
ruby/ql/test/library-tests/frameworks/http_clients/HttpClients.ql
ruby/ql/test/library-tests/frameworks/http_clients/NetHttp.rb

Previously the `NetHttpRequest` charpred expected to find an access to the response body. As a result, the class would not get instantiated in cases where we can't find an access to the response body.
This logic has now been moved into the corresponding member predicate.
Also refactored the test to not make the same assumption.
[Evaluation](https://github.com/github/codeql-dca-main/issues/12203) shows neutral perf and 106 new SSRF sinks.
Commit-by-commit review recommended mainly due to the test refactoring.

Ruby: Minor fix in NetHttpRequest

---

cpp/ql/lib/change-notes/2023-04-04-repeated-initializers.md
cpp/ql/lib/semmle/code/cpp/PrintAST.qll
cpp/ql/lib/semmle/code/cpp/Variable.qll
cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/exprs/Lambda.qll
cpp/ql/lib/semmle/code/cpp/exprs/Literal.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedElement.qll
cpp/ql/lib/semmle/code/cpp/valuenumbering/HashCons.qll
cpp/ql/test/library-tests/ir/ir/PrintAST.expected
cpp/ql/test/library-tests/literals/aggregate_literals/arrays.ql
cpp/ql/test/library-tests/literals/aggregate_literals/arrays_child_exprs.ql
cpp/ql/test/library-tests/literals/aggregate_literals/classes.ql
cpp/ql/test/library-tests/literals/aggregate_literals/classes_child_exprs.ql

Small follow-up after https://github.com/github/codeql/pull/12755

C++: Deprecate single-parameter `getFieldExpr` and `getElementExpr`

---

swift/ql/lib/codeql/swift/security/CleartextStorageDatabaseQuery.qll
swift/ql/lib/codeql/swift/security/StringLengthConflationExtensions.qll
swift/ql/lib/codeql/swift/security/StringLengthConflationQuery.qll
swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql
swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.ql

My assumption was that I could freely rewrite the string length conflation query, as the `lib`-part will not have ended up in any (beta) release yet, as the `lib`-part was created only two weeks ago. In the case of all other queries where the configuration lives in `lib` I took the approach of properly deprecating the configuration class.
I'm not sure whether `TStringType` should actually be public. I made it private for now.
Note that the QLDoc CI failure is expected. We're omitting QLDoc for predicates that implement a signature and our tooling currently expects QLDoc although this can be taken from the signature. This is a known issue. See also here: https://github.com/github/codeql/pull/12541#discussion_r1142013715

Swift: Update final two queries to use `DataFlow::ConfigSig`

---

swift/ql/test/library-tests/dataflow/dataflow/DataFlow.ql
swift/ql/test/library-tests/dataflow/dataflow/DataFlowInline.ql
swift/ql/test/library-tests/dataflow/dataflow/FlowConfig.qll
swift/ql/test/library-tests/dataflow/taint/core/Taint.ql
swift/ql/test/library-tests/dataflow/taint/core/Taint.qll
swift/ql/test/library-tests/dataflow/taint/core/TaintInline.ql
swift/ql/test/library-tests/dataflow/taint/libraries/Taint.qll
swift/ql/test/library-tests/dataflow/taint/libraries/TaintInline.ql

Convert dataflow / taint tests to `DataFlow::ConfigSig`.
@jketema

Swift: Convert dataflow / taint tests to DataFlow::ConfigSig.

---

ruby/extractor/Cargo.lock

The 0.20.10 release includes the [fix](https://github.com/tree-sitter/tree-sitter/pull/1952) for a [stackoverflow](https://github.com/tree-sitter/tree-sitter/issues/2071) we observed.

Ruby: update tree-sitter to 0.20.10

---

cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.ql
cpp/ql/src/experimental/Security/CWE/CWE-193/ConstantSizeArrayOffByOne.ql
cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql

Based on https://github.com/MathiasVP/ql/commit/c5bb7fa59d83fe7dbcc7c2ad492756160f0b7eee.

C++: Fix number of join order problems in memory corruption queries

---

.github/workflows/fast-forward.yml

To be used by maintainers as part of the release process, keeping the tracking branch (currently `lgtm.com`) up to date with the latest `codeql-cli-*` branch.

Actions: Add workflow to fast-forward tracking branch for latest CodeQL release

---

docs/codeql/reusables/supported-versions-compilers.rst
javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java

Resolve the conflict in `docs/codeql/reusables/supported-versions-compilers.rst` in favour of supporting both Ruby 3.2 and TypeScript 5.0.

Merge `rc/3.9` back to `main`

---

go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
go/ql/test/library-tests/semmle/go/dataflow/HiddenNodes/test.expected
go/ql/test/library-tests/semmle/go/dataflow/HiddenNodes/test.go
go/ql/test/library-tests/semmle/go/dataflow/HiddenNodes/test.ql

This mirrors behaviours in other languages with MaD summaries

Go: hide summary nodes from path explanations

---

javascript/ql/lib/semmle/javascript/ApiGraphs.qll
javascript/ql/lib/semmle/javascript/frameworks/Redux.qll
javascript/ql/lib/semmle/javascript/internal/CachedStages.qll
javascript/ql/test/library-tests/frameworks/Redux/accessPaths.js
javascript/ql/test/library-tests/frameworks/Redux/test.expected
javascript/ql/test/library-tests/frameworks/Redux/test.ql

This deals with a performance issue in the Redux model, and expands on API graphs to give us the means to fix it without losing data flow.
The Redux model generates an edge out of a `useSelector` call:
```js
useSelector(state => state.x) // state.x propagates out to the return value of useSelector
```
These edges are used to compute access paths, which means spurious edges can quickly become a performance issue.
The problem occurs when `useSelector` is wrapped in another function. Since the callback was tracked globally, the return values from all the callbacks would propagate into the wrapper function and from there back out to all the call sites.
```js
function wrapper(fn) {
return useSelector(fn);
}
wrapper(state => state.x); // both state.x and state.y would propagate here …
```

JS: add getForwardingFunction and use to sharpen useSelector model

---

javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java
javascript/ql/integration-tests/all-platforms/diagnostics/syntax-error/diagnostics.expected

The diagnostics location was supposed to be 1-based column numbers, but we were using 0-based column numbers.  
See backref for more context.

JS: use 1-based column locations for diagnostics

---

ql/ql/src/queries/performance/MissingNoinline.ql

See some FPs on this PR https://github.com/github/codeql/pull/12804

QL: Don't warn about cached predicates possibly being inlined

---

csharp/ql/test/TestUtilities/InlineFlowTest.qll
csharp/ql/test/library-tests/cil/dataflow/TaintTracking.ql
csharp/ql/test/library-tests/csharp7/GlobalTaintTracking.ql
csharp/ql/test/library-tests/dataflow/async/Async.ql
csharp/ql/test/library-tests/dataflow/callablereturnsarg/Common.qll
csharp/ql/test/library-tests/dataflow/callablereturnsarg/DataFlow.ql
csharp/ql/test/library-tests/dataflow/callablereturnsarg/TaintTracking.ql
csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.expected
csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.ql
csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected
csharp/ql/test/library-tests/dataflow/fields/FieldFlow.ql
csharp/ql/test/library-tests/dataflow/global/Common.qll
csharp/ql/test/library-tests/dataflow/global/DataFlow.ql
csharp/ql/test/library-tests/dataflow/global/DataFlowPath.ql
csharp/ql/test/library-tests/dataflow/global/TaintTracking.ql
csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.ql
csharp/ql/test/library-tests/dataflow/operators/operatorFlow.expected
csharp/ql/test/library-tests/dataflow/operators/operatorFlow.ql
csharp/ql/test/library-tests/dataflow/patterns/PatternFlow.ql
csharp/ql/test/library-tests/dataflow/tuples/Tuples.expected
csharp/ql/test/library-tests/dataflow/tuples/Tuples.ql
csharp/ql/test/library-tests/frameworks/EntityFramework/Dataflow.ql
csharp/ql/test/library-tests/frameworks/JsonNET/Json.ql
csharp/ql/test/library-tests/frameworks/NHibernate/DataFlow.ql
csharp/ql/test/library-tests/security/dataflow/flowsources/StoredFlowSources.ql

In this PR we refactor
- Unit tests
- Inline flow test framework
to the new data flow API.
Note that the inline flow test output has changed. The inline flow tests had two similar configurations in scope during execution which caused the duplicate nodes and edges (these are now removed from the test output).

C#: Re-factor data flow unit tests to use the new API.

---

java/ql/lib/change-notes/2023-03-28-cmdi-queries-models-as-data.md
java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll
java/ql/lib/semmle/code/java/security/CommandLineQuery.qll
java/ql/src/Security/CWE/CWE-078/ExecTainted.ql
java/ql/src/Security/CWE/CWE-078/ExecTaintedLocal.ql
java/ql/src/Security/CWE/CWE-078/ExecUnescaped.ql
java/ql/src/experimental/Security/CWE/CWE-078/ExecTainted.ql

Adds the `command-injection` sink kind in Models as Data. Uses it in the queries `java/command-line-injection` and `java/concatenated-command-line`.
Also refactors the queries related to command injection so that they are more extensible.

Java: Add command-injection sink kind and refactor command injection queries

---

csharp/ql/lib/semmle/code/csharp/security/dataflow/ExternalAPIsQuery.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/HardcodedCredentialsQuery.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/LDAPInjectionQuery.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/LogForgingQuery.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/MissingXMLValidationQuery.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/ReDoSQuery.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/RegexInjectionQuery.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/ResourceInjectionQuery.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/SqlInjectionQuery.qll
csharp/ql/src/Security Features/CWE-020/UntrustedDataToExternalAPI.ql
csharp/ql/src/Security Features/CWE-089/SecondOrderSqlInjection.ql
csharp/ql/src/Security Features/CWE-089/SqlInjection.ql
csharp/ql/src/Security Features/CWE-090/LDAPInjection.ql
csharp/ql/src/Security Features/CWE-090/StoredLDAPInjection.ql
csharp/ql/src/Security Features/CWE-099/ResourceInjection.ql
csharp/ql/src/Security Features/CWE-112/MissingXMLValidation.ql
csharp/ql/src/Security Features/CWE-117/LogForging.ql
csharp/ql/src/Security Features/CWE-730/ReDoS.ql
csharp/ql/src/Security Features/CWE-730/RegexInjection.ql
csharp/ql/src/Security Features/CWE-798/HardcodedConnectionString.ql
csharp/ql/src/Security Features/CWE-798/HardcodedCredentials.ql
csharp/ql/test/query-tests/Security Features/CWE-798/HardcodedConnectionString.expected

In this PR we refactor some more queries to use the new data flow API instead of relying on extending `TaintTracking::Configuration`.
- In the HardCodedConnectionString refactor the expected unit test output for edges/nodes needs to be updated as the now deprecated tainttracking configuration from ExternalApiQuery added nodes and edges to the dataflow graph (but these should be irrelevant for the HardcodedConnectionString query).

C#: Re-factor queries to use the new API.

---

java/ql/lib/change-notes/2023-04-13-sensitive-actions-fix-regex.md
java/ql/lib/semmle/code/java/security/SensitiveActions.qll
java/ql/test/library-tests/sensitive-actions/Test.java
java/ql/test/library-tests/sensitive-actions/test.expected
java/ql/test/library-tests/sensitive-actions/test.ql

The first commit adds tests for the `SensitiveActions.qll` library. The second commit fixes a bug in the regular expression used in the `getCommonSensitiveInfoRegex` predicate .
Fixes https://github.com/github/codeql/issues/7636.

Java: Add tests for SensitiveActions and fix getCommonSensitiveInfoRegex

---

swift/ql/lib/codeql/swift/security/ConstantPasswordExtensions.qll
swift/ql/lib/codeql/swift/security/ConstantSaltExtensions.qll
swift/ql/lib/codeql/swift/security/ECBEncryptionExtensions.qll
swift/ql/lib/codeql/swift/security/HardcodedEncryptionKeyExtensions.qll
swift/ql/lib/codeql/swift/security/InsecureTLSExtensions.qll
swift/ql/lib/codeql/swift/security/InsufficientHashIterationsExtensions.qll
swift/ql/lib/codeql/swift/security/StaticInitializationVectorExtensions.qll
swift/ql/lib/codeql/swift/security/WeakSensitiveDataHashingExtensions.qll

Add MaD/CSV extension points to the eight encryption queries.  Use them in two of the queries (I intend to take this a bit further at some point).  Fix a few other bits and pieces around sinks for better reliability and consistency.

Swift: Add CSV extension points to the encryption queries.

---

cpp/ql/src/Likely Bugs/RedundantNullCheckSimple.ql
cpp/ql/src/change-notes/2023-04-13-redundant-null-check.md
cpp/ql/test/query-tests/Likely Bugs/RedundantNullCheckSimple/RedundantNullCheckSimple.expected

The query produces fantastic results, but has been sitting without a precision for years now with the message:
```ql
/*
* Note: this query is not assigned a precision yet because we don't want it
* to be included in query suites until its performance is well understood.
*/
```
However, I don't see any reason why this query should perform poorly. It only uses libraries that we're already evaluating as part of the Code Scanning suite.
In fact, I'm so confident in its performance that I've converted it to a `path-problem` query to help me understand the alerts that the query produces. In all cases, the query has been right so far 🎉

C++: Promote `cpp/redundant-null-check-simple` to Code Scanning

---

cpp/ql/lib/semmle/code/cpp/security/BufferAccess.qll

I noticed that `buf[x]` where `x` is not a constant was not being treated as a `BufferAccess`. I feel like this restriction is unnecessary, so I've removed it. Most queries with `BufferAccess` will likely call `getSize()`, which will filter these results out and so there will be no change there. But any queries that don't call `getSize()`, or are specifically looking for `not exists(bufferAccess.getSize())`, will have many more results.

C++: Consider ArrayExpr with non-constant size expressions as a BufferAccess

---

ruby/ql/lib/codeql/ruby/ApiGraphs.qll
ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll
ruby/ql/lib/codeql/ruby/frameworks/ActiveResource.qll
ruby/ql/lib/codeql/ruby/frameworks/ActiveStorage.qll
ruby/ql/lib/codeql/ruby/frameworks/GraphQL.qll
ruby/ql/lib/codeql/ruby/frameworks/Twirp.qll
ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModelsSpecific.qll

Places join-order restrictions on API graphs to more reliably get a good join order at the use-sites. This is done by caching more predicates, and placing inline facade predicates in front to enforce a good join ordering at the call site.
While working on adding better support for instance members in API graphs, I noticed the join order in some library models would go haywire seemingly at random, and this PR is meant to stop that from happening.
To explain, a chain of API-graph calls should be evaluated from left to right. For example,
```ql
API::getTopLevelMember("Bar").getAMethodCall("baz")
```
Should be evaluated by first finding uses of `Bar` and then calls to `baz` on those objects.
But sometimes it gets evaluated backwards, by starting at calls to `baz` and then checking if their …

Ruby: restrict join order of API graph predicates

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/src/Critical/DoubleFree.cpp
cpp/ql/src/Critical/DoubleFree.qhelp
cpp/ql/src/Critical/DoubleFree.ql
cpp/ql/src/Critical/FlowAfterFree.qll
cpp/ql/src/Critical/UseAfterFree.ql
cpp/ql/src/change-notes/2023-04-11-double-free.md
cpp/ql/src/change-notes/2023-04-11-use-after-free.md
cpp/ql/src/experimental/Security/CWE/CWE-415/DoubleFree.ql
cpp/ql/test/query-tests/Critical/MemoryFreed/DoubleFree.expected
cpp/ql/test/query-tests/Critical/MemoryFreed/DoubleFree.qlref
cpp/ql/test/query-tests/Critical/MemoryFreed/MemoryFreed.expected
cpp/ql/test/query-tests/Critical/MemoryFreed/MemoryMayNotBeFreed.expected
cpp/ql/test/query-tests/Critical/MemoryFreed/MemoryNeverFreed.expected
cpp/ql/test/query-tests/Critical/MemoryFreed/UseAfterFree.expected
cpp/ql/test/query-tests/Critical/MemoryFreed/UseAfterFree.qlref
cpp/ql/test/query-tests/Critical/MemoryFreed/test_free.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/UseAfterFree.expected
cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/test.cpp

This PR adds a simple query for detecting CWE 415 (double free) and updated existing use-after-free query to be based on IR use-use dataflow. 
Based on my MRVA runs, I've tentatively put the queries at precision medium. Most FPs I've seen have been due to us not realizing that a path is infeasible because of a call to `exit(0)` (or related functions). Based on those findings, I expect that both queries can be put at precision high once https://github.com/github/codeql/pull/11356 has been merged.
--------------------
Todo: 
Future ideas:

C++: Implement use-after-free and double-free queries using the new IR use-use dataflow

---

ql/ql/src/codeql_ql/ast/Ast.qll

This PR suggests updating the regexes used in `QueryDoc.getQueryName()` and in `QueryDoc.getQueryId()/getQueryLanguage()`.
The regex in `QueryDoc.getQueryName()` does not work when non-word characters, such as `/`, are used in the query name. For example, it doesn't work with [`@name Depending upon JCenter/Bintray as an artifact repository`](https://github.com/github/codeql/blob/d94ed1b4a31243f9050902b1a3c7c2a7cbd546a6/java/ql/src/Security/CWE/CWE-1104/MavenPomDependsOnBintray.ql#L2).
This PR proposes updating this regex to allow for any character.
The regex in `QueryDoc.getQueryId()/getQueryLanguage()` does not work when a second `/` is used in the id. For example, it doesn't work with [`@id java/maven/dependency-upon-bintray`](https://github.com/github/codeql/blob/d94ed1b4a31243f9050902b …

QL: update regexes used in `QueryDoc.getQueryName()` and in `QueryDoc.getQueryId()/getQueryLanguage()`

---

cpp/ql/src/Critical/MissingCheckScanf.ql
cpp/ql/test/query-tests/Critical/MissingCheckScanf/MissingCheckScanf.expected
cpp/ql/test/query-tests/Critical/MissingCheckScanf/test.cpp

This PR rewrites the `cpp/missing-check-scanf` query to use the new use-use based dataflow library.
When we introduced the query https://github.com/github/codeql/pull/10163 it was deemed too difficult to use dataflow for the query since we couldn't properly mark one `scanf` as being a sanitizer of another call to `scanf`. However, this is now completely trivial with use-use flow. That makes the query a perfect fit for dataflow now 🎉
I've also changed the query to only raise an alert if a variable isn't initialized prior to the `scanf` call. This removes a very large number of results, and I think this is for the better.
I'm running a difference query on MRVA now to see the impact of this change.

C++: Use the new dataflow library in `cpp/missing-check-scanf`

---

javascript/ql/lib/semmle/javascript/InclusionTests.qll
javascript/ql/lib/semmle/javascript/StringOps.qll

Add pragmas to prevent join order regressions (specifically joins on the low-cardinality integer `arg` column) from planned tweaks to the join ordering heuristic.

Prevent JS join order regression

---

cpp/ql/src/Critical/UseAfterFree.ql

Before:
```ql
[2023-04-18 09:17:24] Evaluated non-recursive predicate _ValueNumberingInternal#c9f42560::tvalueNumber#1#ff_10#join_rhs_project#Instruction#577b6a83::Initia__#loop_invariant_prefix@ae046923 in 3903ms (size: 130544).
Evaluated relational algebra for predicate _ValueNumberingInternal#c9f42560::tvalueNumber#1#ff_10#join_rhs_project#Instruction#577b6a83::Initia__#loop_invariant_prefix@ae046923 with tuple counts:
533787724  ~0%    {2} r1 = JOIN ValueNumberingInternal#c9f42560::tvalueNumber#1#ff_10#join_rhs WITH ValueNumberingInternal#c9f42560::tvalueNumber#1#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1
130544  ~0%    {2} r2 = JOIN r1 WITH project#Instruction#577b6a83::InitializeParameterInstruction#ff ON FIRST 1 OUTPUT Lhs.1, Lhs.0
return r2
```
After:
```ql
[2023-04-18 …
```

C++: Fix bad self-join in `cpp/use-after-free`

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll

These instructions aren't used for any dataflow purposes, so there's no need to generate dataflow nodes for them.

C++: Ignore a few more instructions in dataflow

---

java/ql/lib/change-notes/2022-10-06-log-injection-sanitizers.md
java/ql/lib/semmle/code/java/security/LogInjection.qll
java/ql/test/query-tests/security/CWE-117/LogInjectionTest.java

Addresses https://github.com/github/codeql/discussions/10702.
Note that this has two shortcomings that could become sources of FNs:
1. It considers a valid sanitizer a replacement of just `\n` or `\r` instead of both.
2. It considers a valid guard a regex match of anything containing `\n` or `\r` and not matching `[^%]`. This means something like `matches("\n")` is considered a valid guard, when it isn't.

Java: Add line break sanitizers to java/log-injection

---

swift/ql/lib/codeql/swift/controlflow/CfgNodes.qll
swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll
swift/ql/lib/codeql/swift/dataflow/Ssa.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
swift/ql/lib/codeql/swift/elements/KeyPathComponent.qll
swift/ql/test/library-tests/controlflow/graph/Cfg.expected
swift/ql/test/library-tests/controlflow/graph/consistency.expected
swift/ql/test/library-tests/controlflow/graph/consistency.ql
swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/test.swift

This PR implements dataflow-support for key-path expressions. This has been made possible thanks for Sasha's recent [PR](https://github.com/github/codeql/pull/12784) which extracted the right things 🎉.
After this PR, we model a key-path expression as a lambda with a sequence of read steps. For example, consider this snippet:
```swift
func testKeyPath() {
let s = S(x: source())
let f = \S.x
sink(s[keyPath: f])
}
```
this is now modelled like we model:
```swift
func testKeyPath() {
let s = S(x: source())
let f = { (s : S) in s.x }
sink(f(s))
}
```
There's still some future work to be done: I've only supported simple field lookups inside those key-path chains. We also need to handle wrapping and unwrapping of optionals, and writeable key-path expressions. All of this should be fairly …

Swift: Dataflow for keypaths

---

.github/workflows/go-tests-other-os.yml
.github/workflows/go-tests.yml
go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.expected
go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.ql
go/ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.expected
go/ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.ql

Some of the expected test results introduced in https://github.com/github/codeql/pull/12750 are platform-specific. This PR excludes those functions from the tests. It also (horrifyingly) turns out that the results differ between Go 1.20.0 and Go 1.20.3, so this PR updates the tests to run on the latest patch version of Go 1.20.

Go: Fix platform specific tests

---

.github/workflows/go-tests-other-os.yml
.github/workflows/go-tests.yml
go/extractor/cli/go-autobuilder/go-autobuilder.go
go/extractor/util/util.go
go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.expected
go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.ql
go/ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.expected
go/ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.ql

The main method of `go-autobuilder.go` was almost 400 lines long, and it wasn't clear which variables depended on which other variables, which ones would be used again, etc. This is a very simple refactor to factor different calculations out into their own functions. I recommend reviewing it commit-by-commit.

Go: Refactor autobuilder

---

swift/ql/lib/codeql/swift/security/CleartextLoggingQuery.qll
swift/ql/lib/codeql/swift/security/CleartextStorageDatabaseQuery.qll
swift/ql/lib/codeql/swift/security/CleartextStoragePreferencesQuery.qll
swift/ql/lib/codeql/swift/security/CleartextTransmissionQuery.qll
swift/ql/lib/codeql/swift/security/PathInjectionQuery.qll
swift/ql/lib/codeql/swift/security/PredicateInjectionQuery.qll
swift/ql/lib/codeql/swift/security/SqlInjectionQuery.qll
swift/ql/lib/codeql/swift/security/UncontrolledFormatStringQuery.qll
swift/ql/lib/codeql/swift/security/UnsafeJsEvalQuery.qll
swift/ql/lib/codeql/swift/security/UnsafeWebViewFetchQuery.qll
swift/ql/lib/codeql/swift/security/XXEQuery.qll
swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.ql
swift/ql/src/queries/Security/CWE-312/CleartextStoragePreferences.ql

Delete deprecated classes in Swift, before the public beta.  After public beta we will have a short (1 release) deprecation cycle, after general release we will have the full (1 year) deprecation cycle.  It seems best to start from a clean state.
This excludes files shared with other languages (these things will follow the normal deprecation cycle in sync with other languages) and `BarrierGuard` in `DataFlowPublic.qll` (coupled to the above).
I've also renamed a couple of dataflow modules for different queries that had ended up with the same names - not ideal if someone ever wants to use them together for whatever reason.

Swift: Delete deprecated classes

---

ruby/ql/lib/codeql/ruby/ast/internal/Synthesis.qll

This PR distributes the `parent = TMethodCallSynth(al, -1, _, _, _)` conjunct into the disjunction to ensure each disjunct binds the same fields to allow the join orderer more freedom when choosing the join order. This prevents a planned join ordering tweak from causing a join order regression.

Prevent Ruby join order regression

---

java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll

This adds `%/test/%` to the list of ignored paths defined in CaptureModelsSpecific.qll. This helps resolve avoid including test cases when a project places tests in locations other than `src/test`

Java: Add `*/test/*` to model generator's list of ignored paths

---

ruby/ql/lib/codeql/ruby/ApiGraphs.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/test/library-tests/dataflow/helpers/dataflow.expected

Adds a new kind of API node, `MkModuleObject` to represent a module/class object, (`MkModuleInstance` is coming in a future PR).
This also refactors the generation of subclass edge so that subclass edges target the `MkModuleObject` node. The `use` predicate associates uses with a `MkModuleObject`. (This is similar to how `MkClassInstance` works in JS)
This is a mostly semantics-preserving change, except we now perform a `trackUseNode` step to the subclass edge generation.
Also contains a bugfix in `DataFlow::ModuleNode.getAnImmediateReference` that was needed to associate `MkModuleObject` to its uses.
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/api-graph-class__nightly__code-scanning/reports) shows good performance and 3 new sinks (which are due to the addition …

Ruby: add API node representing a module/class object

---

python/ql/src/experimental/Security/CWE-611/SimpleXmlRpcServer.ql

This file was being flagged by McAfee as an `Exploit-Generic.src` trojan. We have attempted to report this to Mcafee without success so far. I've therefore modified this file to avoid the false positive detection. It turned out to be quite straightforward - the heuristic appears to be including the words "SimpleXMLRPCServer" and "DoS" on the same line.
I've resolved this by expanding the acronym to "denial of service", and used virustotal to show that it was flagged before but not afterwards.
Before:
https://www.virustotal.com/gui/file/046515358490621ca7494c0d9da0b9d4cf8e136342858e950c689fbc46f03ba9
After:
https://www.virustotal.com/gui/file/68fad1baaa66a3e717ec7c03f6ca317b2bc2fd2c1f7d17272df6ce210b5ccf96?nocache=1
/cc @adityasharad @panoslith

Update `SimpleXmlRpcServer.ql` to avoid incorrect detection as a trojan by Mcafee

---

swift/extractor/invocation/SwiftDiagnosticsConsumer.cpp
swift/extractor/invocation/SwiftDiagnosticsConsumer.h
swift/extractor/main.cpp

Reverts github/codeql#12760
We have observed crashes related to this piece of code in some DCA runs, specifically on MovieSwiftUI after the 5.8 upgrade. It's better for the moment to revert this and do some more testing on this.

Revert "Swift: route compiler diagnostics through our log"

---

ruby/ql/lib/codeql/ruby/ast/internal/Synthesis.qll

```
Evaluated relational algebra for predicate Synthesis#d9ff06b1::DestructuredAssignDesugar::LhsWithReceiver::getSynthKind#0#dispred#ff@0c55fb0w on iteration 4 running pipeline order_500000 with tuple counts:
0   ~0%    {2} r1 = JOIN Synthesis#d9ff06b1::ConstantWriteAccessKind#ff#prev_delta WITH Constant#c70e4e0a::ScopeResolutionConstantAccess::getName#0#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1
0   ~0%    {2} r2 = JOIN r1 WITH Constant#c70e4e0a::ScopeResolutionConstantAccess::getScopeExpr#0#dispred#ff#prev ON FIRST 1 OUTPUT Lhs.0, Lhs.1
0   ~0%    {4} r3 = JOIN Call#841c84e8::MethodCall::getMethodName#0#dispred#ff#prev_delta WITH Call#841c84e8::Call::getNumberOfArguments#0#dispred#ff#prev ON FIRST 1 OUTPUT Lhs.1, false, Rhs.1, Lhs.0
0   ~0%    {2} r4 = JOIN r3 WITH …
```

Ruby: Fix bad join in `DestructuredAssignDesugar`

---

swift/extractor/SwiftExtractor.cpp

It turns out mangled names can sometimes be too long. While this code will eventually be replaced by our own mangling, we need to use hashing to cut down the names and avoid crashes right away.
Module and decl names are preserved in the trap file names for debuggability.

Swift: use hashing for lazy decl trap file names

---

swift/ql/src/queries/Security/CWE-094/UnsafeJsEval.ql

Downgrade `swift/unsafe-js-eval` to `@precision medium`, because in https://github.com/github/codeql-c-team/issues/1099 I found false positive results for this query in three projects.
Fixing the FPs should come out of https://github.com/github/codeql-c-team/issues/1268 .  I've added a note to that issue to upgrade this query back to `@precision high` it's done.

Swift: Downgrade swift/unsafe-js-eval to precision medium.

---

csharp/ql/lib/ext/System.IO.model.yml
csharp/ql/lib/semmle/code/csharp/dataflow/ExternalFlow.qll
csharp/ql/lib/semmle/code/csharp/security/dataflow/flowsinks/ExternalLocationSink.qll
csharp/ql/src/change-notes/2023-04-05-external-location-sinks.md
csharp/ql/test/query-tests/Security Features/CWE-312/CleartextStorage.cs
csharp/ql/test/query-tests/Security Features/CWE-312/CleartextStorage.expected
csharp/ql/test/query-tests/Security Features/CWE-312/options
csharp/ql/test/query-tests/Security Features/CWE-359/ExposureOfPrivateInformation.cs
csharp/ql/test/query-tests/Security Features/CWE-359/ExposureOfPrivateInformation.expected
csharp/ql/test/query-tests/Security Features/CWE-359/options

Adds sinks for local filesystem writes to `ExternalLocationSink` (used by the `cs/cleartext-storage` and `cs/exposure-of-sensitive-information` queries).

C#: Add local filesystem writes as External Location sinks

---

swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.ql
swift/ql/src/queries/Security/CWE-312/CleartextStoragePreferences.ql

Upgrade two queries to `@precision high`.  Justified by a lack of FPs found on the MRVA top 1000 projects.  This is important as `@precision medium` queries will not show up in the [default] `swift-code-scanning.qls` suite.
A related PR, https://github.com/github/codeql/pull/12836/ , temporarily downgrades a query that does currently show false positive results.

Swift: Upgrade two queries to precision high.

---

swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImplSpecific.qll
swift/ql/test/library-tests/controlflow/graph/Cfg.expected

I don't think this really has any big impacts on analysis, but at least it removes a TODO from the codebase 🎉

Swift: Implement `isAbnormalExitType`

---

ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll

Before
```
Evaluated relational algebra for predicate ActionController#32b59475::controllerTemplateFile#2#ff@6f4b2395 with tuple counts:
31304524   ~0%    {2} r1 = JOIN locations_default_10#join_rhs WITH FileSystem#df18ed9a::Make#FileSystem#e91ad87f::Input#::Container::getRelativePath#0#dispred#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1
34453   ~3%    {2} r2 = JOIN r1 WITH DataFlowPublic#e1781e31::ModuleNode::getLocation#0#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1
1236   ~0%    {2} r3 = JOIN r2 WITH ActionController#32b59475::ActionControllerClass#f ON FIRST 1 OUTPUT Lhs.0, InverseAppend(("" ++ "app/controllers/"),"_controller.rb",Lhs.1)
1236   ~1%    {2} r4 = SCAN r3 OUTPUT In.0, ("" ++ "app/views/layouts/" ++ In.1 ++ "%")
1320   ~1%    {3} r5 = JOIN r2 WITH …
```

Ruby: Fix bad join in `controllerTemplateFile`

---

swift/ql/src/queries/Security/CWE-079/UnsafeWebViewFetch.qhelp

It appears we forgot to get a doc review for the query `swift/unsafe-webview-fetch` in the [original PR here](https://github.com/github/codeql/pull/9964).  With public beta coming up, it's time to remedy that.  This PR is a space for that doc review and any changes that come from it.

Swift: Doc review for swift/unsafe-webview-fetch

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll

This PR prevents flow into `self` parameters when tracking blocks in the call graph construction. Additionally, we also recognize calls to blocks via `.call` and not just `yield`.

Ruby: Prevent flow into `self` in `trackBlock`

---

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp

I haven't investigated what's going on yet, but this test is a minified version of a result I was seeing on MRVA.

C++: Add FP for `cpp/invalid-pointer-deref`

---

java/ql/lib/semmle/code/java/Member.qll

I'll need this predicate for some future work, but I thought it made sense to add on its own.

Java: Add SrcCallable.isImplicitlyPublic convenience predicate.

---

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp

Once again: I have no idea why we're getting these FPs when very similar cases are properly handled further up in the file 😂. But I'll leave fixing (and even _understanding_) them to a future PR.

C++: Add more FPs for `cpp/invalid-pointer-deref`

---

go/ql/lib/semmle/go/security/Xss.qll
go/ql/src/experimental/CWE-79/HTMLTemplateEscapingPassthrough.ql
go/ql/test/experimental/CWE-79/HTMLTemplateEscapingPassthrough.expected
go/ql/test/experimental/CWE-79/HTMLTemplateEscapingPassthrough.go
go/ql/test/query-tests/Security/CWE-079/ReflectedXssGood.go
go/ql/test/query-tests/Security/CWE-079/StoredXssGood.go

Based on the documentation for `html/template` templates, they automatically escape inputs and are therefore not prone to XSS attacks. However, we do not currently treat the relevant functions from `html/template` as sanitisers for the XSS queries and therefore can end up with false positives. This PR adds a new `Sanitizer` to the shared XSS library which identifies calls to `ExecuteTemplate` and `Execute` that the tainted value flows to as sanitisers. I have also extended the tests with cases for this.

Go: Add `html/template` functions as sanitisers for XSS queries

---

javascript/ql/lib/semmle/javascript/frameworks/Bundling.qll
javascript/ql/lib/semmle/javascript/security/regexp/RegExpTreeView.qll

Recognizes webpack bundles in more cases, and ignores bundles in the ReDoS queries.
[Evaluation](https://github.com/github/codeql-dca-main/issues/12551) shows good performance, and as expected some results inside of webpack bundles are no longer reported.

JS: Ignore more webpack modules

---

javascript/extractor/src/com/semmle/js/parser/JSONParser.java
javascript/extractor/tests/json/output/trap/comments.json.trap
javascript/ql/src/change-notes/2023-04-28-json-with-comments.md
javascript/ql/test/library-tests/JSON/JSONError.expected

Our parser already supports comments and simply treats them as recoverable parse errors. This means the JSON files would be fully extracted, but the errors would be reported in two places:
- As diagnostic message suggesting that something went wrong. This was actually misleading because the file was in fact fully extracted.
- As syntax errors in the `SyntaxError.ql` query. For this use-case I just don't think anyone actually cares.
Rather than marking the errors as "non-reportable" or something like that, we just stop recording them, with the rationale that there is simply no use-case for this information anymore.

JS: Stop complaining about comments in JSON files

---

javascript/ql/lib/semmle/javascript/frameworks/Next.qll
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/react-use-router-lib.js
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/react-use-router.js

I can't find the reason but `DataFlow::moduleMember("next/router", "useRouter").getACall()` doesn't detect a function call if `useRouter` comes from other file.
`API::moduleImport("next/router").getMember("useRouter").getACall()` can resolve this situation like this.
a.js
```
let router = require("next/router");
export let myUseRouter = router.useRouter;
```
b.js
```
import { myUseRouter } from './a'
const router = myUseRouter() // <- want to detect this
```

JS: Track interfile useRouter

---

javascript/ql/lib/semmle/javascript/DOM.qll
javascript/ql/lib/semmle/javascript/frameworks/Angular2.qll
javascript/ql/test/library-tests/DOM/Customizations.expected
javascript/ql/test/library-tests/DOM/querySelectorAll.js
javascript/ql/test/library-tests/frameworks/Angular2/source.component.ts
javascript/ql/test/library-tests/frameworks/Angular2/test.expected

- Handles iteration over DOM element collections, as in `querySelectorAll('foo').forEach(node => ...)`
- Recognizes `nativeElement` in Angular2 apps
[Evaluation](https://github.com/github/codeql-dca-main/issues/12717) looks fine, showing 4 new sinks

JS: Add a few more DOM element sources

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll
cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplCommon.qll
csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowImpl.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowImplCommon.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplCommon.qll
java/ql/src/utils/modelgenerator/internal/CaptureModels.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplCommon.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplCommon.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplCommon.qll

In data flow we're tracking both a type and an access path. These two things are somewhat intertwined as we want to be able to reestablish the tracked type after a store-to-read step sequence.
We used to achieve this by merging the type into the front of the access paths resulting in a list of the form `(typ1, content1) :: (typ2, content2) :: ... :: nil(typn)`. This refactor pulls the front type out of the access path, such that it becomes an explicit pair rather than being merged with `Content`. We still need the types nested inside the access path tails, so now, instead of being a list of `TypedContent`s, access paths are a list of `Content`s where each nested tail is paired with a `DataFlowType`, i.e. `(typ1, content1 :: (typ2, content2 :: ... :: (typn, nil)) ... ))`.
In the automaton …

Dataflow: Refactor access paths to split TypedContent into an explicit pair

---

java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll

This PR fixes the model generator when it's generating sinks that are `InstanceParameterNode`s. Previously it generated `input` columns like `Argument[-1]`,  but they should be `Argument[this]`.

Java: Fix sink model generator for instance parameters

---

cpp/ql/lib/change-notes/2023-04-28-static-local-dataflow.md
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
cpp/ql/test/library-tests/syntax-zoo/dataflow-ir-consistency.expected
cpp/ql/test/query-tests/Likely Bugs/Format/NonConstantFormat/NonConstantFormat.expected
cpp/ql/test/query-tests/Likely Bugs/Format/NonConstantFormat/test.cpp

This adds the necessary flow steps for dataflow through static local variables.
Thanks to https://github.com/github/codeql/pull/12900, we now treat static locals just like we treat globals. So the only real change necessary was to replace any occurrence of `x instanceof GlobalOrNamespaceVariable` with `x instanceof Cpp::GlobalOrNamespaceVariable or x instanceof Cpp::StaticLocalVariable`. I've factored this out to a `GlobalLikeVariable` class to reduce the diff.
Commit-by-commit review recommended: First we add some tests, then we make the necessary changes and accept test changes, and finally we fix an inconsistency that showed up.

C++: Dataflow for static local variables

---

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/OverrunWriteProductFlow.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/test.cpp

This demonstrates a false positive caused by a problem with synchronizing the two configurations in the product-flow library across function calls. The first projection of the graph transfers flow into the second `call_memset` call, and the second projection of the graph transfers flow into the first `call_memset` call.

C++: Add testcase with `cpp/overrun-write` FP

---

csharp/ql/lib/semmle/code/cil/Attribute.qll

Make all implicit this call receivers explicit to align with internal style guidelines.

C#: Make implicit this receivers explicit

---

cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedElement.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedInitialization.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedStmt.qll

Make all implicit this call receivers explicit to align with internal style guidelines.
Automatically generated from results of QL-for-QL implicit this query as follows:
```
$CODEQL database create $LANG-db -l ql -s $CODEQL_PATH/$LANG/ql --search-path $CODEQL_PATH/ql/extractor-pack
$CODEQL database analyze $LANG-db --format=csv --output=$LANG $CODEQL_PATH/ql/ql/src/queries/style/ImplicitThis.ql
python3 insert-explicit-this.py $LANG $CODEQL_PATH/$LANG/ql $CODEQL
```
using the [insert-explicit-this.py](https://gist.github.com/kaspersv/184e4b26b96102cfabcd7298d783dd03) script to interpret the results and insert explicit this receivers.

C++: Make implicit this receivers explicit

---

python/ql/lib/semmle/python/security/dataflow/ChainedConfigs12.qll
python/ql/src/Security/CWE-020-ExternalAPIs/ExternalAPIs.qll
python/ql/src/Variables/Undefined.qll
python/ql/src/experimental/semmle/python/Concepts.qll
python/ql/src/external/DefectFilter.qll

Make all implicit this call receivers explicit to align with internal style guidelines.

Python: Make implicit this receivers explicit

---

javascript/ql/lib/semmle/javascript/security/CryptoAlgorithms.qll
python/ql/lib/semmle/python/concepts/CryptoAlgorithms.qll
ruby/ql/lib/codeql/ruby/security/CryptoAlgorithms.qll

Make implicit this call receivers explicit to align with internal style guidelines.

JS, Python, Ruby: Make implicit this receivers explicit

---

go/extractor/cli/go-autobuilder/go-autobuilder.go
go/extractor/cli/go-autobuilder/go-autobuilder_test.go
go/extractor/cli/go-bootstrap/go-bootstrap.go
go/extractor/cli/go-tokenizer/go-tokenizer.go
go/extractor/diagnostics/diagnostics.go
go/extractor/extractor.go
go/extractor/gomodextractor.go
go/extractor/srcarchive/projectlayout_test.go
go/extractor/trap/trapwriter.go

Step 1 of https://github.com/github/codeql-go-team/issues/329.
Integration tests look tricky. I will instead use unit tests in `ql/go/extractor/cli/go-autobuilder/go-autobuilder_test.go` and some manual end-to-end testing. Once other languages have also implemented this flag we can set up everything up to make integration testing possible.

Go: Add `go-autobuilder --identify-environment`

---

cpp/ql/lib/change-notes/2023-04-28-indirect-barrier-node.md
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/BarrierGuard.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.ql

In the rewrite to use-use flow for C/C++ we added a concept of an indirect node which represents "the value you'd get by dereferencing the value of the expression represented by this node". These are the nodes accessible using the `Node::asIndirectExpr()` predicate which returns an `IndirectExprNode` (instead of an `ExprNode`).
These new `IndirectExprNode`s couldn't be marked as barriers with a barrier guard because the predicate offered by the `BarrierGuard` parameterized module had the signature:
```ql
ExprNode getABarrierNode();
```
which meant that an `IndirectExprNode`s was never the result of this predicate.
To resolve the above issue, I've added a new predicate to the `BarrierGuard` parameterized module with the signature:
```ql
IndirectExprNode getAnIndirectBarrierNode();
```
the …

C++: Barrier guards API for indirect expressions

---

csharp/ql/lib/semmle/code/csharp/security/dataflow/UnsafeDeserializationQuery.qll
csharp/ql/src/Security Features/CWE-502/UnsafeDeserializationUntrustedInput.ql
csharp/ql/test/query-tests/Security Features/CWE-502/UnsafeDeserializationUntrustedInputNewtonsoftJson/UnsafeDeserializationUntrustedInput.expected

In this PR we re-factor the configurations in the UnsafeDeserializationQuery.
There are no alerts diff when running the queries on all DCA projects.
The unit test shows a small difference in the produced data flow graph edges: I am a bit uncertain, why that is the case, but there is pretty big difference in how the data flow graph is constructed between the old and the new version. In the old version of the code all sources and sinks are added by extending a "global" configuration. This produces a set of nodes and edges used for data flow analysis in the entire graph - which I suppose might create more superfluous edges as the configurations get intertwined. However, when using the new API, the graphs are constructed separately for each configuration and then merged afterwards.
I think we …

C#: Re-factor the UnsafeDeserializationQuery to use the new API.

---

python/ql/lib/qlpack.yml
python/ql/src/qlpack.yml
python/ql/test/experimental/meta/ConceptsTest.qll
python/ql/test/library-tests/ApiGraphs/py2/use.ql
python/ql/test/qlpack.yml
python/ql/test/query-tests/Functions/ModificationOfParameterWithDefault/test.ql

Enable warnings for member predicate calls with implicit this receivers for Python to prevent them from reappearing.

Python: Enable implicit this warnings

---

cpp/ql/lib/experimental/semmle/code/cpp/dataflow/ProductFlow.qll
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/OverrunWriteProductFlow.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/test.cpp

The experimental "product dataflow library" already synchronizes the two paths when the enclosing callable changes, but the synchronization point didn't check that we entered through the same call. This gave FPs such as the one I added in https://github.com/github/codeql/pull/12989.
This PR fixes this class of FPs by checking that we entered through the same function call whenever we flow into a function. Similarly, we check that we leave through the same function call in the two paths.

C++: Synchronize product dataflow paths on function entry points

---

docs/codeql/codeql-language-guides/customizing-library-models-for-java.rst
java/documentation/library-coverage/cwe-sink.csv
java/ql/lib/change-notes/2023-05-03-url-open-stream-as-experimental.md
java/ql/lib/ext/com.google.common.io.model.yml
java/ql/lib/ext/experimental/com.google.common.io.model.yml
java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll
java/ql/src/experimental/Security/CWE/CWE-036/OpenStream.ql

This PR switches the `url-open-stream` models to `experimentalSink Model` since they are only used in the experimental query, `java/openstream-called-on-tainted-url`.
Specifically, this PR:
- Switches the `url-open-stream` models to `experimentalSinkModel` and activates them in the `java/openstream-called-on-tainted-url` query.
- Removes `url-open-stream` from the _Customizing Library Models for Java_ documentation.
- Removes `url-open-stream` from the `getInvalidModelKind` predicate in the `ModelValidation` module.
- Removes the CWE related to the `url-open-stream` kinds from the `cwe-sink.csv` file which is used in the framework coverage reports.
Let me know if the change note needs any edits. Should I specifically mention the removal of CWE-036 from the framework coverage report in the …

Java: switch `url-open-stream` sink models to `experimentalSinkModel`

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/ModulusAnalysis.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisStage.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeUtils.qll

Recursion through `forall` and `forex` needs special care in QL. During the modulus-analysis phase of the IR-based range analysis such care is already taken, but the same level of care wasn't taken in the main range analysis module. This resulted in horrible antijoins on some projects. Here is one such example:
```ql
Tuple counts for antijoin_rhs#3/9@i7#L1#982a1web after 31.3s:
259071899 ~88%        {11} r1 = JOIN boundedPhiCandValidForEdge#9#fffffffff#prev_delta WITH SemanticSSA#aa9d1d08::SemSsaReadPositionPhiInputEdge::phiInput#2#dispred#fff_102#join_rhs ON FIRST 1 OUTPUT Lhs.0 'arg0', Lhs.1 'arg1', Lhs.2 'arg2', Lhs.3 'arg3', Lhs.4 'arg4', Lhs.5 'arg5', Lhs.6 'arg6', Lhs.7 'arg7', Lhs.8 'arg8', Rhs.1, Rhs.2
83255000  ~80%        {11} r2 = r1 AND NOT …
```

C++: Work around poor codegen for `forex` in IR-based range analysis

---

.github/workflows/tree-sitter-extractor-test.yml
shared/tree-sitter-extractor/rust-toolchain.toml
shared/tree-sitter-extractor/src/extractor/simple.rs
shared/tree-sitter-extractor/src/node_types.rs

Fix the clippy CI check for the shared extractor by fixing a few issues and ignoring some that seem too noisy to me. I've also pinned the rust version to 1.68 (same as the Ruby and QL extractors) so that the clippy version doesn't change suddenly and break the CI check.

Shared: Fix clippy in shared extractor

---

csharp/extractor/Semmle.Extraction.CSharp/Extractor/CompilerVersion.cs
csharp/ql/integration-tests/posix-only/warn_as_error/Errors.ql
csharp/ql/integration-tests/posix-only/warn_as_error/Program.cs
csharp/ql/integration-tests/posix-only/warn_as_error/WarnAsError.csproj
csharp/ql/integration-tests/posix-only/warn_as_error/build.sh
csharp/ql/integration-tests/posix-only/warn_as_error/test.py

This PR ensures that the extractor never treats warnings as errors. Since the extractor may be using another version of Roslyn than the actual build, our extractor may produce warnings that the actual build doesn't.
DCA run confirms that we now have less extraction errors:

C#: Never treat warnings as error in the extractor

---

docs/codeql/codeql-language-guides/customizing-library-models-for-java.rst

In this PR we adjust the public documentation for neutrals.
This is due to the changes on: https://github.com/github/codeql/pull/12931

Java: Update customizing library models for java documentation.

---

java/ql/lib/semmle/code/java/Type.qll

This was found to be needed for certain extreme corner-cases when testing disabling the standard order.
As it's just materialising a filter on an already materialised predicate as a loop-invariant (this already happened to be used in the std order, btw), it is pretty much as safe as perf tweaks go, and I've also inspected the RA, which only amounts to a tiny diff - promoting the current standard order to be used for all delta sizes.

Java: Minor perf fix for typePrefixContainsAux1.

---

java/ql/lib/qlpack.yml
java/ql/src/qlpack.yml
java/ql/test/qlpack.yml

Enable warnings for member predicate calls with implicit this receivers for Java to prevent them from reappearing.

Java: Enable implicit this receiver warnings

---

csharp/ql/src/experimental/Security Features/backdoor/PotentialTimeBomb.ql
csharp/ql/test/experimental/Security Features/backdoor/PotentialTimeBomb.expected

There are no alerts diff when running the queries on all DCA projects.
The unit test shows a small difference in the produced data flow graph edges: I am a bit uncertain, why that is the case, but there is pretty big difference in how the data flow graph is constructed between the old and the new version. In the old version of the code all sources and sinks are added by extending a "global" configuration. This produces a set of nodes and edges used for data flow analysis in the entire graph - which I suppose might create/remove edges as the configurations get intertwined. However, when using the new API, the graphs are constructed separately for each configuration and then merged afterwards.
I think we can accept this discrepancy, since this doesn't affect the produced results in the unit …

C#: Re-factor the experimental PotentialTimeBomb to use new API.

---

javascript/ql/examples/queries/dataflow/DecodingAfterSanitization/DecodingAfterSanitizationGeneralized.ql

The alert message was broken by [this commit](https://github.com/github/codeql/commit/368f84785b7c232628a3e07e948c965e4ab074bb). But since this is an example query it seems to have gone unnoticed.

JS: Fix broken message in example query

---

javascript/ql/lib/semmle/javascript/security/dataflow/SecondOrderCommandInjectionCustomizations.qll

Add pragma to prevent join order regressions from planned tweaks to the join ordering heuristic.

JS: Prevent join order regression

---

python/ql/test/experimental/dataflow/variable-capture/dataflow-consistency.expected

I am guessing this was introduced via a semantic merge conflict.

Python: Update expected test output

---

go/extractor/diagnostics/diagnostics.go
go/ql/integration-tests/all-platforms/go/diagnostics/package-not-found-with-go-mod/diagnostics.expected
go/ql/integration-tests/all-platforms/go/diagnostics/package-not-found-without-go-mod/diagnostics.expected

error is reserved for when the build fails.

Go: Downgrade go/autobuilder/package-not-found diagnostic to warning

---

ruby/ql/lib/codeql/ruby/frameworks/core/Gem.qll
ruby/ql/lib/qlpack.yml
ruby/ql/src/qlpack.yml
ruby/ql/src/queries/meta/internal/TaintMetrics.qll
ruby/ql/test/library-tests/dataflow/api-graphs/use.ql
ruby/ql/test/qlpack.yml

Enable warnings for member predicate calls with implicit `this` receivers for Ruby to prevent them from reappearing.

Ruby: Enable implicit this warnings

---

csharp/ql/lib/qlpack.yml
csharp/ql/src/qlpack.yml
csharp/ql/test/qlpack.yml

Enable warnings for member predicate calls with implicit this receivers for C# to prevent them from reappearing.

C#: Enable implicit this receiver warnings

---

cpp/ql/lib/qlpack.yml
cpp/ql/lib/semmle/code/cpp/controlflow/StackVariableReachability.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisStage.qll
cpp/ql/src/qlpack.yml
cpp/ql/test/qlpack.yml

Enable warnings for member predicate calls with implicit this receivers for C++ to prevent them from reappearing.

C++: Enable implicit this warnings

---

cpp/ql/lib/semmle/code/cpp/models/implementations/Allocation.qll

Just a simple refactoring that we can now do now that we can specify member predicates in signature classes 🎉. No functionality has been changed in this PR.

C++: Cleanup `CallAllocationExprBase` with module signature members

---

swift/ql/lib/codeql/swift/elements/AvailabilityInfo.qll
swift/ql/lib/codeql/swift/elements/KeyPathComponent.qll
swift/ql/lib/codeql/swift/elements/Locatable.qll
swift/ql/lib/codeql/swift/elements/PlatformVersionAvailabilitySpec.qll
swift/ql/lib/codeql/swift/elements/decl/ExtensionDecl.qll
swift/ql/lib/codeql/swift/elements/expr/IdentityExpr.qll
swift/ql/lib/codeql/swift/elements/expr/UnresolvedDeclRefExpr.qll
swift/ql/lib/codeql/swift/elements/expr/UnresolvedDotExpr.qll
swift/ql/lib/codeql/swift/elements/pattern/BindingPattern.qll
swift/ql/lib/codeql/swift/elements/pattern/ParenPattern.qll
swift/ql/lib/codeql/swift/elements/type/TypeRepr.qll

Make implicit this call receivers explicit to align with internal style guidelines.

Swift: Make implicit this receivers explicit

---

ql/ql/src/codeql_ql/style/ImplicitThisQuery.qll
ql/ql/test/queries/style/ImplicitThis/Bad2.qll
ql/ql/test/queries/style/ImplicitThis/ImplicitThis.expected
ql/ql/test/queries/style/ImplicitThis/Okay.qll

Update `ql/implicit-this` query to flag implicit this receivers in all files, including files without any explicit this receivers. This restriction was originally added to reduce noise, but since all implicit this receivers should now have been converted to explicit this receivers, it is safe to remove the restriction.

Remove ql/implicit-this restriction to files with explicit this

---

go/codeql-tools/identify-environment.cmd
go/codeql-tools/identify-environment.sh

This adds scripts that the CLI can use to call the go autobuilder with the `--identify-environment` flag. This is similar to `autobuild.cmd` and `autobuild.sh`, which they are based on.

Go: Add identify-environment scripts

---

cpp/ql/lib/semmle/code/cpp/models/implementations/Allocation.qll
cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/OverrunWriteProductFlow.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/test.cpp

This expands the set of sources for `cpp/overrun-write` by including heuristic allocation sources. On MRVA this gives about 40 new results - all of which look like good results 🎉.
As an extra bonus I expanded the heuristic to also consider function names including `"Alloc"` (instead of just `"alloc"`). This makes us catch allocations such as these ones: https://github.com/tianocore/edk2/blob/5215cd5baf6609e54050c69909273b7f5161c59e/BaseTools/Source/C/DevicePath/DevicePathUtilities.c#L729-L729 and https://github.com/NVIDIA/open-gpu-kernel-modules/blob/6dd092ddb7c165fb1ec48b937fa6b33daa37f9c1/src/nvidia/src/kernel/platform/nbsi/nbsi_init.c#L2656-L2656

C++: Use heuristic allocation functions in `cpp/overrun-write`

---

javascript/ql/lib/qlpack.yml
javascript/ql/lib/semmle/javascript/frameworks/AngularJS/AngularJSCore.qll
javascript/ql/src/qlpack.yml
javascript/ql/test/qlpack.yml
javascript/ql/test/tutorials/Validating RAML-based APIs/query1.ql
javascript/ql/test/tutorials/Validating RAML-based APIs/query2.ql
javascript/ql/test/tutorials/Validating RAML-based APIs/query3.ql
javascript/ql/test/tutorials/Validating RAML-based APIs/query4.ql

Enable warnings for member predicate calls with implicit this receivers for Javascript to prevent them from reappearing.

JS: Enable implicit this receiver warnings

---

ql/ql/src/codeql/Locations.qll
ql/ql/src/codeql_ql/style/UseSetLiteralQuery.qll
ql/ql/src/qlpack.yml
ql/ql/test/callgraph/Foo.qll
ql/ql/test/callgraph/callgraph.expected

Enable warnings for member predicate calls with implicit this receivers for QL-for-QL to prevent them from reappearing.

QL: Enable implicit this receiver warnings

---

javascript/ql/test/tutorials/Validating RAML-based APIs/RAML.qll

Not sure how this last implicit this slipped through, but it was [caught by QL-for-QL](https://github.com/github/codeql/security/code-scanning/82840).

JS: Make implicit this receivers explicit

---

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp
cpp/ql/test/library-tests/ir/range-analysis/test.cpp

Also add reduced range analysis test case that seems to expose the underlying reason for the FP.

C++: Add FP test case for `cpp/invalid-pointer-deref`

---

javascript/ql/src/Security/CWE-078/examples/unsafe-shell-command-construction.js
javascript/ql/src/Security/CWE-078/examples/unsafe-shell-command-construction_fixed.js

This seems more realistic, since the asynchronous APIs would return immediately before actually having taken effect.

JavaScript: Use synchronous APIs in examples for js/shell-command-constructed-from-input.

---

python/ql/lib/semmle/python/dataflow/new/internal/TypeTracker.qll
ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll
ruby/ql/lib/codeql/ruby/regexp/internal/RegExpTracking.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTracker.qll

When https://github.com/github/codeql/pull/11879 switched from using global data flow to using type tracking, for identifying regular expressions, we lost flow through built-in string methods. This is because the conjunct
```ql
TaintTracking::localTaintStep(nodeFrom, nodeTo) and
nodeFrom.(DataFlowPrivate::SummaryNode).getSummarizedCallable() instanceof String::SummarizedCallable
```
doesn't work in type tracking, where we don't have flow-through. Instead, we should be using `FlowSummaryImpl::Private::Steps::summaryThroughStepTaint`, which this PR does.
Moreover, this PR improves on performance by strengthening the initial forwards/backwards pruning, which also revealed a bug in the existing `TypeBackTracker::getACompatibleTypeTracker` predicate.
DCA shows a nice speedup on …

Ruby: Improvements to `RegExpTracking`

---

javascript/ql/src/Security/CWE-915/PrototypePollutingAssignment.inc.qhelp
javascript/ql/src/Security/CWE-915/examples/PrototypePollutingAssignmentFixed2.js

QHelp preview doesn't handle `.inc` file changes too well, so ignore the comment below. 
The commits messages should explain what is changed.

JS: fixup in the qhelp for `js/prototype-polluting-assignment`

---

java/ql/lib/semmle/code/java/security/XmlParsers.qll
java/ql/src/change-notes/2023-05-15-xpath-xxe-sink.md
java/ql/test/query-tests/security/CWE-611/XPathExpressionTests.java
java/ql/test/query-tests/security/CWE-611/XXE.expected

We had `XPathExpression.evaluate` as an XXE sink, but we didn't have `XPath.evaluate`, which does functionally the same. This PR solves that.

Java: Add `XPath.evaluate` as XXE sink

---

cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/OverrunWriteProductFlow.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/test.cpp

This PR fixes a class of false positives involving flow through back edges for the `cpp/overrun-write` query. The fix is identical to the one applied to the `cpp/invalid-pointer-deref` in [this PR](https://github.com/github/codeql/pull/10593).
Keeping this as a draft until I can run it on DCA.

C++: Block flow through back-edges in `cpp/overrun-write`

---

swift/actions/build-and-test/action.yml

Note that we no longer check whether we're on a macOS runner explicitly since Bazel can automatically determine which tests are compatible (e.g. the XCode autobuild tests depend on `//swift/xcode-autobuilder`, which has a `target_compatible_with = ["@platforms//os:macos"]` attribute).

Swift: Use `...` to find and run all Bazel tests instead of having list them.

---

java/ql/integration-tests/all-platforms/java/diagnostics/java-version-too-old/test.py

This will prevent future failures of this test.

Java: Hide GHA variables in `java-version-too-old` test

---

cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp

This seems to reproduce some strange pointer/pointee conflation that @jketema and I were seeing on a project with the `cpp/invalid-pointer-deref` query. This may also be related to the pointer/pointee conflation I saw with `@andersfugmann`.

C++: Add example with conflation in dataflow

---

swift/ql/lib/codeql/swift/security/CleartextLoggingExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextStorageDatabaseExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextStoragePreferencesExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextTransmissionExtensions.qll
swift/ql/lib/codeql/swift/security/SensitiveExprs.qll
swift/ql/test/query-tests/Security/CWE-311/CleartextTransmission.expected
swift/ql/test/query-tests/Security/CWE-311/SensitiveExprs.expected
swift/ql/test/query-tests/Security/CWE-311/testRealm.swift
swift/ql/test/query-tests/Security/CWE-311/testSend.swift

Add tests for and fix some FPs caused by the sensitive data library.  These patterns have been observed in real world projects at various times.
In addition to removing likely FPs, the regexp changes do introduce a few new possible results (e.g. matching `mob_num`, `home_no`, `fax_num`), but based on a large MRVA run I don't expect this to have a big impact.
I should probably run DCA on this PR to confirm it removes the three FP results that show up there.

Swift: Fix some FPs from the sensitive data library

---

swift/ql/src/queries/Security/CWE-321/HardcodedEncryptionKey.swift

@GeekMasher pointed out that `UInt8.random` uses a "cryptographically secure algorithm _whenever possible_.", which isn't the kind of thing we want to suggest for cryptographic use-cases. So this PR rewrites the recommendation to use `SecRandomCopyBytes` instead.
I also found some more discussions of this online: https://forums.swift.org/t/random-data-uint8-random-or-secrandomcopybytes/56165/3. They seem to agree with the choice of `SecRandomCopyBytes`.

Swift: Recommend a proper source of randomness in `swift/hardcoded-key`

---

java/ql/integration-tests/all-platforms/java/diagnostics/java-version-too-old/test.py
java/ql/integration-tests/all-platforms/java/diagnostics/java-version-too-old/toolchains.xml

Follow-up to #13180 which didn't fix the `java-version-too-old` enough to prevent test failures in future work. This change now also makes sure that the test completely disregards any `toolchain.xml` files that may be present on a given system.

Java: Use empty toolchains.xml for java-version-too-old

---

cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/OverrunWriteProductFlow.expected

This fixes the performance regression we got from https://github.com/github/codeql/pull/13099.
Keeping this in draft until we can run DCA.

C++: Restrict flow-state space of `cpp/overrun-write`

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
ruby/ql/test/library-tests/modules/ancestors.expected
ruby/ql/test/library-tests/modules/callgraph.expected
ruby/ql/test/library-tests/modules/calls.rb
ruby/ql/test/library-tests/modules/methods.expected
ruby/ql/test/library-tests/modules/modules.expected
ruby/ql/test/library-tests/modules/superclasses.expected

This PR generalizes the existing logic for identifying methods with flow-through to also include implicit `self` parameters.

Ruby: Include `self` parameters in type tracking flow-through logic

---

java/ql/src/Telemetry/AutomodelFrameworkModeCharacteristics.qll
java/ql/src/Telemetry/AutomodelFrameworkModeExtractCandidates.ql
java/ql/src/Telemetry/AutomodelFrameworkModeExtractNegativeExamples.ql
java/ql/src/Telemetry/AutomodelFrameworkModeExtractPositiveExamples.ql

The exported `name` metadata parameter used to wrongly contain the _parameter_ name, but should've contained the _method_ name.
This fixes the bug, and exports the parameter name as `parameterName` metadata parameter.

Java: Automodel Extraction Parameter Name Fix

---

cpp/ql/lib/experimental/semmle/code/cpp/dataflow/ProductFlow.qll

Note that `Config1` was already marked as `private`.

C++: Add forgotten `private` specifiers in product flow

---

swift/codeql-extractor.yml
swift/ql/lib/qlpack.yml
swift/ql/src/qlpack.yml

These new versions are rather arbitrary, but probably better than `0.0.0`.

Swift: bump all versions to 0.1.0

---

docs/codeql/codeql-language-guides/codeql-library-for-javascript.rst
javascript/ql/test/tutorials/Introducing the JavaScript libraries/query17.qll
javascript/ql/test/tutorials/Introducing the JavaScript libraries/tests.expected
javascript/ql/test/tutorials/Introducing the JavaScript libraries/tst.js

Fixes https://github.com/github/codeql/issues/13174
The documentation will need an overhaul once JS starts using the shared data flow library, so I'd rather not spend too much time on perfecting it. Just making sure it's not blatantly wrong.

JS: remove mention of TrackedNode from docs

---

cpp/ql/lib/experimental/semmle/code/cpp/dataflow/ProductFlow.qll

This PR speeds up the experimental product flow library in three steps:
1. The first commit implements Schack's suggestion from https://github.com/github/codeql/pull/9997#discussion_r963513863
2. The second commit applies manual magic to the transitive closures of the `localPathStep` calls in the forward direction,
3. ... and the last commit does the same in the reverse direction.
This seems to speed up the analysis quite a lot. For example, running `cpp/invalid-pointer-deref` on https://github.com/ptitSeb/box64 goes from ~30 min to ~5 min. There's still something weird on that project, but at least it's a lot more manageable now.
I haven't run DCA on it yet, but I'll do so once Actions feels better 😅.

C++: Speedup product dataflow

---

.vscode/tasks.json
CODEOWNERS
misc/scripts/accept-expected-changes-from-ci.py

This script can be used to go over `codeql test run` expected/actual log
output from actions CI checks for a PR, and apply patches locally to
make the tests pass.
Designed for use by GitHub employees, since it needs access to internal CI runs. Just run this tool while the branch for the PR is checked out!
You need the `gh` cli tool installed and authenticated.
Example can be seen in https://github.com/github/codeql/pull/12950

Misc: Add script to accept `.expected` changes from CI

---

cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected

This'll probably need a DCA experiment?

C++: Implement the `subpaths` query predicate for `cpp/invalid-pointer-deref`

---

.github/workflows/check-change-note.yml

fixes https://github.com/github/codeql-core/issues/3534
Changed regexp in the check-change-note change to accept change notes like:
```
["cpp/ql/lib/change-notes/released/0.7.1.md","cpp/ql/src/change-notes/2023-04-11-double-free.md","cpp/ql/src/change-notes/2023-04-11-use-after-free.md","cpp/ql/src/change-notes/released/0.6.1.md","csharp/ql/campaigns/Solorigate/lib/change-notes/released/1.5.1.md","csharp/ql/campaigns/Solorigate/src/change-notes/released/1.5.1.md","csharp/ql/lib/change-notes/released/0.6.1.md","csharp/ql/src/change-notes/released/0.6.1.md","go/ql/lib/change-notes/released/0.5.1.md","go/ql/src/change-notes/released/0.5.1.md","java/ql/lib/change-notes/2022-09-22-stringjoiner-summaries.md","java/ql/lib/change-notes/2022-10-06-log-injection-sanitizers.md","java/ql/lib/change-no …
```

Change regexp to include released change-notes pattern

---

cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql

This is copied from `cpp/overrun-write`.
Will need DCA experiment.

C++: Use range analysis-based `hasSize` predicate in `cpp/invalid-pointer-deref`

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.ql
cpp/ql/test/query-tests/Security/CWE/CWE-078/SAMATE/ExecTainted/ExecTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected

This PR fixes the conflation identified in https://github.com/github/codeql/pull/13182.
Turns out the problem was something we've actually seen before. Consider this code
```cpp
void increment_and_call_sink(int** buf2) {
*buf2 += 10;
sink(buf2);
}
void call_increment_and_call_sink(int** buf1) {
increment_and_call_sink(buf1);
}
void test_conflation_regression() {
int* buf = source();
call_increment_buf(&buf);
}
```
We got spurious flow from `source()` to `sink(buf)`. This shouldn't happen since the tainted value is `*buf`. However, we were getting flow in this case because the post-update node corresponding to the value of `buf1` after leaving `increment_and_call_sink` re-entered `increment_and_call_sink` and got dereferenced an additional time in the `*buf2 += ...` operation.
This PR …

C++: Fix pointer/pointee conflation

---

swift/ql/lib/codeql/swift/frameworks/StandardLibrary/FilePath.qll
swift/ql/test/library-tests/dataflow/taint/libraries/files.swift
swift/ql/test/library-tests/dataflow/taint/libraries/string.swift

Add a fairly thorough taint model for [`FilePath`](https://developer.apple.com/documentation/system/filepath).  The model existed already, but only modelled one function.  Some tests already existed as well, these have been moved into their own test file and expanded upon (but not every single modelled method has a test).
Probably deserves a DCA run...

Swift: Taint model for FilePath

---

swift/integration-tests/linux-only/autobuilder/unsupported-os/diagnostics.expected
swift/integration-tests/osx-only/autobuilder/failure/diagnostics.expected
swift/integration-tests/osx-only/autobuilder/no-build-system/diagnostics.expected
swift/integration-tests/osx-only/autobuilder/no-swift-with-spm/diagnostics.expected
swift/integration-tests/osx-only/autobuilder/no-swift/diagnostics.expected
swift/integration-tests/osx-only/autobuilder/no-xcode-with-spm/diagnostics.expected
swift/integration-tests/osx-only/autobuilder/only-tests-with-spm/diagnostics.expected
swift/integration-tests/osx-only/autobuilder/only-tests/diagnostics.expected
swift/logging/SwiftDiagnostics.cpp
swift/logging/SwiftDiagnostics.h
swift/logging/tests/assertion-diagnostics/diagnostics.expected

Diagnostics can include either a `plaintextMessage` or a `markdownMessage`. For plaintext messages, we can also include `helpLinks` (whereas for Markdown, the links are embedded in the message). We're using Markdown everywhere, and I noticed all our helpLinks have a `""` as the only link. To "fix" that, this PR drops support for `plaintextMessage` and `helpLinks` in the Swift extractor entirely.

Swift: Drop support for plaintext diagnostics (and `helpLinks`). 

---

docs/codeql/ql-language-reference/ql-language-specification.rst

This is part of https://github.com/github/codeql-core/issues/2452
I have taken inspiration from the section about modules for the basic structure.
Adding this grammar is a bit tricky, because it is quite far removed from how we actually do things in practice (see e.g. https://github.com/github/semmle-code/pull/46155). Similar to alias definitions, in reality, we folded the grammar rules for type signatures into class declarations, the grammar rules for predicate signatures into predicate declarations, and the grammar rules for module signatures into module declarations. We then disentangle them in `AntlrToQL`. However, we don't want to expose this to the users.
Therefore, the review should take into account that this grammar is essentially "made up" for the QL specification.

add syntax for signature definitions to QL specification

---

swift/ql/lib/codeql/swift/elements/AstNode.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Collection.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/CustomUrlSchemes.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/FilePath.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/NsData.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/NsString.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Sequence.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/String.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Url.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/WebView.qll
swift/ql/lib/codeql/swift/frameworks/Xml/AEXML.qll
swift/ql/lib/codeql/swift/security/CleartextLoggingExtensions.qll
swift/ql/lib/codeql/swift/security/PathInjectionExtensions.qll
swift/ql/lib/codeql/swift/security/XXEExtensions.qll

Use `asNominalTypeDecl` more:
- to resolve methods and variables declared in extensions correctly.  We've had models fail in both tests and real world query runs in the past because they were looking for something in a particular named type declaration, but that thing was actually in an extension of it.
- to avoid needing special case disjuncts to do so.
Some of these changes could affect results, so I'll do a DCA run to be safe.

Swift: Use asNominalTypeDecl more.

---

ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll

This should not give rise to spurious flow (flow in via one call and out via another call), since we are limited to callbacks that are direct arguments (e.g. blocks).

Ruby: Allow for flow through callbacks to summarized methods in type tracking

---

javascript/ql/lib/semmle/javascript/frameworks/ActionsLib.qll
javascript/ql/lib/semmle/javascript/security/dataflow/IndirectCommandInjectionCustomizations.qll
javascript/ql/src/change-notes/2023-05-17-indirect-shell.md
javascript/ql/test/query-tests/Security/CWE-078/IndirectCommandInjection/command-line-parameter-command-injection.js

I'm not sure if the previous behavior was intentional or not, but we had no test for "command argument, but not shell interpreted", so it seems like it was unintentional.  
Fixing the behavior revealed that `ExecActionsCall` had no implementation of `isShellInterpreted`.  
/cc @max-schaefer

JS: require arguments to be shell interpreted to be flagged by indirect-command-injection

---

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/OverrunWriteProductFlow.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-119/test.cpp

... and also a drive-by fix to a test annotation that I forgot to update when we fixedit in https://github.com/github/codeql/pull/12997.

C++: Add FP testcase for `cpp/overrun-write`

---

ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll

Similar to https://github.com/github/codeql/pull/13231.

Ruby: Allow for flow out of callbacks passed to summarized methods in type tracking

---

go/ql/src/RedundantCode/DeadStoreOfField.ql

Fixes a regression caused by https://github.com/github/codeql/pull/11732

Hotfix: Go: count passing to a vararg function as escaping

---

java/ql/lib/change-notes/2023-05-22-inputstreamwrapper-transitive.md
java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll

The `inputStreamWrapper` predicate considers constructors of a type that implements `java.io.InputStream` that receive a bulk-data-like argument (like another stream) to be likely dataflow steps. This PR makes it so that it also considers implementations of `java.io.InputStream` transitively, to cover cases like [`org.apache.commons.io.input.BOMInputStream`](https://commons.apache.org/proper/commons-io/javadocs/api-2.4/org/apache/commons/io/input/BOMInputStream.html).

Java: Make inputStreamWrapper consider supertypes transitively

---

java/ql/lib/change-notes/2023-05-17-change-hostnamesanitizingprefix-regex.md
java/ql/lib/semmle/code/java/security/RequestForgery.qll
java/ql/test/query-tests/security/CWE-918/SanitizationTests.java

Adds a check to make sure the sanitizing prefix is not the second `/` in the `://` of a protocol specifier.

Java: Add constraint to `HostnameSanitizingPrefix` to prevent false negatives in SSRF queries

---

cpp/ql/test/TestUtilities/dataflow/FlowTestCommon.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.ql
cpp/ql/test/library-tests/dataflow/fields/ASTConfiguration.qll
cpp/ql/test/library-tests/dataflow/fields/IRConfiguration.qll
cpp/ql/test/library-tests/dataflow/fields/flow.expected
cpp/ql/test/library-tests/dataflow/fields/flow.ql
cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.ql
cpp/ql/test/library-tests/dataflow/fields/path-flow.ql
cpp/ql/test/library-tests/dataflow/smart-pointers-taint/taint.expected
cpp/ql/test/library-tests/dataflow/smart-pointers-taint/taint.ql
cpp/ql/test/library-tests/dataflow/taint-tests/taint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.ql

This also rewrites all uses of flow test common to use `DataFlow::ConfigSig`.
Note that the removed deprecated aliases are 14 months old by now and, hence, can be safely removed.

C++: Rewrite flow test common to use inline expectation test module

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/vector.cpp
cpp/ql/test/query-tests/Critical/MemoryFreed/UseAfterFree.expected

When we have IR like:
```cpp
r1(glval<char **>) = VariableAddress[x]  :
r2(char **)        = Load[x]             : &:r1, m
```
we reuse the dataflow node for `r2` to represent the dataflow node for the indirection node of `r1` with indirection index 1 (i.e., the node that represents the value you get from dereferencing `r1` once).
This is implemented by this disjunct in the charpred for `IndirectOperand` on `main`:
```ql
this.(OperandNode).getOperand() = Ssa::getIRRepresentationOfIndirectOperand(operand, indirectionIndex)
```
That is, `this` is used to represent the dataflow node for the indirect operand whose underlying operand is `operand` and whose indirection index is `indirectionIndex`. However, this line is only correct when `indirectionIndex` is 1 (because in that case the IR may …

C++: Fix more pointer/pointee conflation

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ProductFlow.qll
cpp/ql/src/experimental/Likely Bugs/ArrayAccessProductFlow.ql
cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.ql
cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql

This PR moves the experimental product-dataflow library out of the experimental directory. This is a necessary step before we can promote any of the new experimental queries that depend on it out of experimental.
I'm happy to bikeshed on the QLDoc I've added if you can think of something that sounds better 😅.

C++: Promote the product-dataflow library out of experimental

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll

In preparation for https://github.com/github/codeql/pull/12964.

Ruby: Include underlying SSA parameter definition in `localFlowSsaParamCaptureInput`

---

java/ql/lib/change-notes/2023-05-23-java-nio-file-files-copy-models-tweak.md
java/ql/lib/ext/java.nio.file.model.yml
java/ql/test/query-tests/security/CWE-022/semmle/tests/TaintedPath.expected
java/ql/test/query-tests/security/CWE-022/semmle/tests/mad/Test.java

Avoid considering generic `[Input|Output]Stream` arguments as file-related sinks, since they could be other things (like `ByteArray[Input|Output]Stream`s).

Java: Tweak java.nio.file.Files.copy models

---

javascript/ql/test/tutorials/Introducing the JavaScript libraries/query12.qll
javascript/ql/test/tutorials/Introducing the JavaScript libraries/tests.expected
javascript/ql/test/tutorials/Introducing the JavaScript libraries/tst.js

Just noticed that `query12.qll` was missing a `+` in the getASuccessor predicate and added a test case for the query in the test file `tst.js`, confirming that the query finds an invocation then.

Fix "Introducing the JavaScript libraries" query12.qll and add test case

---

ql/ql/src/queries/bugs/NameClashInSummarizedCallable.ql
ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll
ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll
ruby/ql/src/change-notes/2023-05-24-delete-name-clash.md
ruby/ql/test/library-tests/dataflow/local/TaintStep.expected

Fixes an issue where the summaries for `delete` and `assoc` had multiple implementations that applied to each others' call sites.
We had code like this:
```codeql
// Array.qll
private class DeleteUnknownSummary extends DeleteSummary {
DeleteUnknownSummary() {
this = "delete" and
not exists(DataFlow::Content::getKnownElementIndex(mc.getArgument(0)))
}
...
}
// String.qll
private class DeleteSummary extends SimpleSummarizedCallable {
DeleteSummary() { this = ["delete", "delete_prefix", "delete_suffix"] + ["", "!"] }
}
```
The existence of `DeleteSummary` in `String.qll` means all method calls named `delete` are associated with the summary whose underlying string value is `delete`. This means `DeleteUnknownSummary`, if it exists, ends up applying to all calls named `delete`, regardless of …

Ruby: fix some name clashes between summarized callables

---

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp

Test case shows that the store may occur before the pointer update, and the number of indirections still seem to be off-by-one 😕 
Also make the formatting in the test file more uniform while we're here.

C++: Add `cpp/invalid-pointer-deref` FP test case

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DefaultTaintTrackingImpl.qll

The internal `asExpr(Node)` predicate found in the `ExprFlowCached` module is used as a more generous version of `Node.asExpr` that's used to ensure good performance on large sequences of array access operations (see https://github.com/github/codeql/pull/12507 for a slightly longer explanation of this).
However, it turns out we have another place where we do a lot of `Expr` to `Expr` flow: Namely in `DefaultTaintTracking` 😭. So this PR uses this more generous `asExpr` predicate in `DefaultTaintTracking` to make sure that we don't generate many duplicated results on every use of an array access whose base is `argv`.

C++: Fix result duplication on `DefaultTaintTracking`

---

python/ql/src/meta/analysis-quality/SummarizedCallableCallSites.ql
ruby/ql/src/queries/meta/SummarizedCallableCallSites.ql

Adds meta-queries which are similar to `CallGraph.ql`, except they show calls to `SummarizedCallable`.

Ruby/Python: add meta-queries for calls to summarised callables

---

ruby/ql/lib/codeql/ruby/ast/internal/Call.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
ruby/ql/src/change-notes/2023-05-26-super-and-flow-through.md

Fixes two unrelated bugs that I'm putting in the same PR to be a bit more economical about evaluations:
- Fixes the name of super calls in singleton methods. Super calls have the name of the enclosing method, but this did not work for singleton methods.
- Fixes the flow-through logic in type-tracking when dealing with `new` calls. We model `new` calls as targeting `initialize` methods with a different return kind. This caused the bug where `new` would appear to return one of its arguments if the `initialize` method returned one of its parameters.

Ruby: two bug fixes

---

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/IRBlock.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/IRBlock.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/IRBlock.qll
csharp/ql/src/experimental/ir/implementation/raw/IRBlock.qll
csharp/ql/src/experimental/ir/implementation/unaliased_ssa/IRBlock.qll

Since we merged https://github.com/github/codeql/pull/12900 the Foundations teams internal performance measurements have been OOM'ing when analyzing Wireshark because they're running their experiments with ~6GB of RAM (unlike our DCA analysis of Wireshark which uses a much larger runner).
The analysis was OOM'ing because of the use of the `shortestDistances` HOP. This use was introduced in https://github.com/github/codeql/commit/8368c37781d5fae810f856cf9b1e04f586225a9f to get around an issue where Eclipse was OOM'ing because the log file was too large 😅.
This PR reverts https://github.com/github/codeql/commit/8368c37781d5fae810f856cf9b1e04f586225a9f and replaces the transitive closure of `adjacentInBlock` (which also was OOM'ing when I tried it locally) with an `EquivalenceRelation`-based …

C++: Reduce memory pressure from `getInstruction`

---

cpp/ql/test/library-tests/ir/range-analysis/RangeAnalysis.ql
cpp/ql/test/library-tests/ir/range-analysis/SimpleRangeAnalysis_tests.cpp
cpp/ql/test/library-tests/ir/range-analysis/test.cpp

For a while we were confused about this range-analysis test:
```cpp
void* f3_get(int n);
void f3() {
int n = 0;
while (f3_get(n)) n+=2;
for (int i = 0; i < n; i += 2) {
range(i); // $ range=>=0 SPURIOUS: range="<=call to f3_get-1" range="<=call to f3_get-2"
}
}
```
because the inline-expectations test annotation seemed to suggest that range-analysis was claiming that `i` was bounded upper bounded by the return value of the call to `f3_get` (which totally didn't make any sense). However, as @jketema correctly hypothesized, this was actually caused by the fact that we were using `Instruction.getAst` to obtain a string-representation of the bound. Dropping the use of `getAst` (as I've done in PR) reveals what's really going on:
```cpp
void* f3_get(int n);
void f3() {
int n = 0;
while …
```

C++: Change range-analysis test to not use `getAst`

---

csharp/extractor/Semmle.Extraction.CSharp/Extractor/Extractor.cs
csharp/ql/integration-tests/all-platforms/cshtml/Files.expected
csharp/ql/integration-tests/all-platforms/cshtml/Files.ql
csharp/ql/integration-tests/all-platforms/cshtml/Program.cs
csharp/ql/integration-tests/all-platforms/cshtml/Views/Home/Index.cshtml
csharp/ql/integration-tests/all-platforms/cshtml/cshtml.csproj
csharp/ql/integration-tests/all-platforms/cshtml/test.py
csharp/ql/lib/change-notes/2023-05-30-source-generators.md
csharp/tools/tracing-config.lua

This PR
- adds all the `.cs` files in the `GeneratedFilesOutputDirectory` to the extracted files,
- modifies the tracing script to run the extractor AFTER the compiler invocation (so that we can inspect the generated files)

C#: Extract source files generated by source generators

---

docs/codeql/codeql-language-guides/using-flow-labels-for-precise-data-flow-analysis.rst

Fixes https://github.com/github/codeql/issues/13175
Flow through global variables is less precise than for locals, so the barrier used in the example doesn't work unless the code is put into a function.

JS: Avoid using global vars in documentation examples

---

cpp/ql/src/experimental/Security/CWE/CWE-193/ConstantSizeArrayOffByOne.ql

Before:
```ql
Tuple counts for ConstantSizeArrayOffByOne#f6a3dbf4::pointerArithOverflow0#5#fffff/5@e762307m after 1m48s:
96500      ~0%     {2} r1 = JOIN project#RangeAnalysisImpl#edd69a76::Public::semBounded#5#fffbf_102#join_rhs WITH num#Bound#63ed7326::TBoundZero#f ON FIRST 1 OUTPUT Lhs.1, f2i(Lhs.2)
99000      ~1%     {2} r2 = JOIN r1 WITH EquivalenceRelation#Instruction#577b6a83::Instruction#SemanticExprSpecific#ad5ae873::SemanticExprConfig::idOrSafeConversion#::getEquivalenceClass#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1 'bound'
16500      ~0%     {2} r3 = JOIN r2 WITH Instruction#577b6a83::BinaryInstruction::getRight#0#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'pai', Lhs.1 'bound'
16000      ~0%     {3} r4 = JOIN r3 WITH …
```

C++: Fix join in `pointerArithOverflow0`

---

ruby/ql/lib/ide-contextual-queries/printCfg.ql

This query enables the `CodeQL: View CFG` command in the VSCode extension.

Ruby: add print-cfg query

---

cpp/ql/src/experimental/Security/CWE/CWE-193/ConstantSizeArrayOffByOne.ql

Various containers in the standard library apply the small string optimization, and we can't currently reason about the path conditions that makes it clear that these accesses are safe. So for now we decided to just exclude them from the query to reduce the number of results.

C++: Exclude `StdNamespace` sources in `cpp/constant-size-array-off-by-one`

---

swift/extractor/SwiftExtractor.cpp
swift/extractor/infra/BUILD.bazel
swift/extractor/infra/SwiftMangledName.cpp
swift/extractor/infra/SwiftMangledName.h
swift/extractor/mangler/SwiftMangler.cpp
swift/extractor/mangler/SwiftMangler.h
swift/extractor/translators/SwiftVisitor.h

Our mangler is split in two version:
* `SwiftTrapMangler`, with the same behaviour as the previous `SwiftMangler`, constructing mangled names with trap label references
* `SwiftRecursiveMangler` that replaces trap label references with recursive calls to its own `mangle` functions, effectively rolling out the entire chain of references
The latter is used to create lazy trap file names. Hashing is used to avoid excessively long filenames.

Swift: replace internal swift mangler with our own

---

docs/codeql/codeql-for-visual-studio-code/running-codeql-queries-at-scale-with-mrva.rst

Once we're able to merge https://github.com/github/codeql-variant-analysis-action/pull/820, we'll no longer need these permissions.

Remove GITHUB_TOKEN permissions note since it's no longer required

---

cpp/ql/lib/semmle/code/cpp/Macro.qll

Make `Macro.getName()` more efficient.  Inspired by @MathiasVP s comment [here](https://github.com/github/codeql/pull/13190#discussion_r1210637896).  Macro names get a lot of use in CPP, so I'll do a DCA run to be sure this is safe.

C++: Make Macro.getName() more efficient.

---

java/ql/src/Security/CWE/CWE-730/ReDoS.qhelp
javascript/ql/src/Performance/ReDoS.qhelp
python/ql/src/Security/CWE-730/ReDoS.qhelp
ruby/ql/src/queries/security/cwe-1333/ReDoS.qhelp

[It's not great how it's rendered now. ](https://codeql.github.com/codeql-query-help/javascript/js-redos/#example)

ReDoS: fix whitespace in the samples in ReDoS.qhelp

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll

This PR is a copy of #13323, rebased on the 2.12.7 branch.
For a given type, we count the number of indirect dataflow nodes a value of a given type needs by counting how many indirections exist on the type (i.e., `int` has 0 indirections, `int*` and `int&` has 1, etc.). However, if a malformed type exists in the database (i.e., an indirect type `t` such that `t.getBaseType() = t`) then the predicate that counts indirections goes into an infinite loop.
This PR swaps out the manual recursion with a use of the `shortestDistances` HOP which doesn't suffer from this problem. On normal (i.e., acyclic) types this shouldn't change any behavior, and on a malformed type with cycles this won't cause infinite recursion. That is, if there is a non-cyclic path all the way to the base type this path …

C++: Use the shortestDistances HOP to count indirections (rebased copy of #13323)

---

java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll

This PR adds an error message in `getInvalidModelKind` for when an outdated sink kind is used and includes instructions on alternate names. 
This was [suggested](https://github.com/github/codeql/pull/12916#pullrequestreview-1423193912) by @aeisenberg for the [Java sink revamp](https://github.com/github/codeql/pull/12916).
Let me know if I should add something similar for other languages (e.g. [JavaScript](https://github.com/github/codeql/pull/13157), [C#](https://github.com/github/codeql/pull/13158)). If so, I'll create a shared version of this in https://github.com/github/codeql/pull/13324.

Java: add error message for outdated sink kinds in `getInvalidModelKind`

---

go/Makefile
go/extractor/cli/go-autobuilder/go-autobuilder.go
swift/tools/BUILD.bazel
swift/tools/identify-environment.cmd
swift/tools/identify-environment.sh

The forthcoming `resolve environment` command in the CLI invokes these scripts. Currently only Go supports this fully and already has such a script (although it was left out of the distribution until now), while this PR adds stubs for the other languages.

Shared: Add stubs for `identify-environment` scripts

---

misc/bazel/cmake/cmake.bzl
swift/BUILD.bazel
swift/CMakeLists.txt
swift/extractor/BUILD.bazel
swift/logging/tests/assertion-diagnostics/BUILD.bazel
swift/tools/autobuilder-diagnostics/BUILD.bazel
swift/xcode-autobuilder/BUILD.bazel

The bazel -> cmake generator is currently not capable of handling separate included generated cmake files making use of common C/C++ dependencies.
To work around this limitation, a single generated cmake is now in place. Long-term, we should either:
* make the cmake generator handle common dependencies gracefully, or
* make the cmake generation aspect travel up `pkg_` rules `srcs` attributes
so to avoid having to list the targets to be generated in the top-level `BUILD` file.
Other things fixed:
* removed some warning spam about redefined `BAZEL_CURRENT_REPOSITORY`
* fixed the final link step, that was failing because `libswiftCore.so` was not being linked.

Swift: fix cmake generation

---

cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp

This avoids some counter-intuitive paths where we would seemingly jump back to an earlier instruction, which might actually have been in bounds.

C++: Ensure that the sink instruction occurs last in `cpp/invalid-pointer-deref`

---

csharp/ql/src/Bad Practices/Implementation Hiding/ExposeRepresentation.ql
csharp/ql/src/Complexity/ComplexCondition.ql
csharp/ql/test/query-tests/Bad Practices/Implementation Hiding/ExposeRepresentation/ExposeRepresentation.expected

```
Most expensive predicates for completed query ComplexCondition.ql:
time  | evals |   max @ iter | predicate
------|-------|--------------|----------
22.5s |       |              | Location#a178a2aa::Location::toString#0#dispred#ff@736e93jb
4.2s |       |              | locations_default_234501#join_rhs@ad8924cn
2s |       |              | boundedFastTC:ExprOrStmtParent#051be664::Cached::parent#2#ff_10#higher_order_body:project#Callable#f85cebf6::Callable::getBody#0#dispred#ff@37a64ask
2s |       |              | boundedFastTC:ExprOrStmtParent#051be664::Cached::parent#2#ff_10#higher_order_body:Callable#f85cebf6::Constructor::getInitializer#0#dispred#ff_1#higher_order_body@6cf8660h
```
It's not just slow, it also results in a lot of string-pool insertions:
```
Evaluated non-recursive …
```

C#: avoid calls to `Location::toString()`

---

java/ql/src/Metrics/Summaries/LinesOfCode.ql
java/ql/src/Metrics/Summaries/LinesOfCodeKotlin.ql
java/ql/src/change-notes/2023-06-05-lines-of-code.md

We were giving the sum of all lines for both languages, but labelling it as "Total lines of Java code in the database", which was confusing.
Now we give separate sums for Kotlin and Java lines.

Java/Kotlin: Split lines of code by language

---

java/ql/test/library-tests/dispatch/CallableViaSummary.java
java/ql/test/library-tests/dispatch/viaSummary.expected
java/ql/test/library-tests/dispatch/viaSummary.ql

Type tracking in Java is used to enhance the dispatch relation by establishing flow to certain callables, thereby making them viable callables.
This test shows that type tracking can step through flow summaries and establish flow to a lambda inside an `ArrayList`. A second, empty `ArrayList` from which no dispatch happens, serves to show that the flow was necessary for the dispatch to occur.

java: test type tracking through flow summaries

---

java/ql/lib/change-notes/2023-05-19-path-injection-sinks-mad.md
java/ql/lib/ext/java.io.model.yml
java/ql/lib/ext/java.nio.file.model.yml
java/ql/lib/ext/java.nio.model.yml
java/ql/lib/semmle/code/java/security/TaintedPathQuery.qll
java/ql/lib/semmle/code/java/security/ZipSlipQuery.qll
java/ql/src/Security/CWE/CWE-022/TaintedPath.ql
java/ql/src/Security/CWE/CWE-022/TaintedPathLocal.ql
java/ql/src/experimental/Security/CWE/CWE-073/FilePathInjection.ql
java/ql/test/experimental/query-tests/security/CWE-073/FilePathInjection.expected
java/ql/test/query-tests/Telemetry/SupportedExternalSinks/SupportedExternalSinks.expected

Migrates path injection sinks to models-as-data format. This is a simplification of #12886 to avoid introducing changes in alerts.
The existing `PathCreation` classes can't be removed because doing so would cause alert wobble in the path injection queries. See their `getReportingNode` predicates.
Note that the accepted test expectation changes only happen in an experimental query, where alert wobble shouldn't be a problem.

Java: Migrate path injection sinks to models-as-data (simplified)

---

csharp/extractor/Semmle.Extraction.CSharp.Standalone/Extractor.cs

This PR changes standalone extraction to allow unsafe code. I don't think this change is observable through the extracted DB, but the underlying Roslyn compilation object reported corresponding (avoidable) diagnostics.

C#: Change standalone extraction to allow unsafe code

---

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll
python/ql/lib/semmle/python/dataflow/new/internal/TypeTracker.qll
ruby/ql/lib/codeql/ruby/ApiGraphs.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll
ruby/ql/lib/codeql/ruby/frameworks/Rack.qll
ruby/ql/lib/codeql/ruby/frameworks/actioncontroller/Filters.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTracker.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
ruby/ql/test/library-tests/dataflow/local/Nodes.ql
ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected

This PR is about porting the join-order improvement from https://github.com/github/codeql/pull/12979 to the type tracking library shared between Ruby and Python. The motivation for Ruby is to be able to get rid of canonical return nodes, which were only introduced to avoid bad joins during type tracking (and dually, to have steps from parameter nodes to their corresponding SSA node be simple local flow steps instead of call steps).
The join-order from https://github.com/github/codeql/pull/12979 is implemented in the first commit, and it is about getting exactly this join-order in the various step relations:
```ql
TypeTracker step(TypeTracker t, LocalSourceNode nodeFrom, LocalSourceNode nodeTo) {
exists(StepSummary summary |
step(nodeFrom, _, summary) and
result = t.append(summary) and …
```

Ruby: Remove canonical return nodes

---

javascript/ql/lib/semmle/javascript/Regexp.qll
javascript/ql/src/change-notes/2023-06-01-restrict-regex-search-function.md
javascript/ql/test/query-tests/RegExp/RegExpAlwaysMatches/tst.js
javascript/ql/test/query-tests/Security/CWE-020/MissingRegExpAnchor/MissingRegExpAnchor.expected
javascript/ql/test/query-tests/Security/CWE-020/MissingRegExpAnchor/tst-UnanchoredUrlRegExp.js
javascript/ql/test/query-tests/Security/CWE-730/RegExpInjection.expected
javascript/ql/test/query-tests/Security/CWE-730/RegExpInjection.js

Reduces the FP rate of various RegExp queries by sharpening the criteria for when a call named `search` is assumed to call `String.prototype.search`. This method isn't very commonly used compared to other methods named `search`.
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/restrict-regex-__nightly__code-scanning/reports) looks good, and fixes 31 spurious regexp-injection sinks and fixes 1 FP regexp-injection alert.

JS: Be more conservative about flagging "search" call arguments as regex

---

ruby/extractor/Cargo.lock
ruby/extractor/Cargo.toml

Reverts github/codeql#13399
Extraction seems to be failing on DCA but the cause has not yet been confirmed. Since DCA was not run on the above PR I'm opening this PR in case it needs to be reverted.

Revert "Ruby: update tree-sitter-ruby"

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp

This is a much simpler solution to the problem described in https://github.com/github/codeql/pull/13326. Instead of tweaking the generated IR, we identify the problematic case in dataflow SSA and modify the `hasIndexInBlock` predicate so that the use of `p` that represents the result of `p++` has the same index as the use of `p` that represents the value read by `p++`. Specifically, the IR for `x = p++` looks like:
```cpp
r1(glval<int>) = VariableAddress[x]     :
r2(glval<int>) = VariableAddress[p]     :
r3(int)        = Load[p]                : &:r2, m1
r4(int)        = Constant[1]            :
r5(int)        = Add                    : r3, r4
m2(int)        = Store[p]               : &:r2, r5
r7(int)        = CopyValue              : r3
m3(int)        = Store[x]               : &:r1, r7 …
```

C++: Fix the `++` problem

---

python/ql/src/experimental/Security/CWE-074/paramiko/paramiko.ql

When I made this PR I had forgotten that we actually use a different name for the real query :facepalm: anyway, think this change will still be good :+1:
https://github.com/github/codeql/blob/b5bbe6314463b80cd2bbf9a0c749b70b30c21db9/python/ql/src/Security/CWE-078/CommandInjection.ql#L10

Python: Avoid duplicated query-id

---

csharp/extractor/Semmle.Extraction.CSharp.Standalone/BuildAnalysis.cs

Standalone extraction collects possible references for the compilation. These assemblies go through some deduplication logic. This logic was not applied to `System.Private.CoreLib.dll`. The PR makes sure there's at most one `System.Private.CoreLib.dll` added to the compilation. ~Additionally it adds assemblies next to this `System.Private.CoreLib.dll` to the possible references.~

C#: Make sure System.Private.CoreLib is added only once as a reference in standalone extraction

---

javascript/ql/lib/semmle/javascript/security/TaintedObject.qll
javascript/ql/test/query-tests/Security/CWE-089/untyped/DatabaseAccesses.expected
javascript/ql/test/query-tests/Security/CWE-089/untyped/SqlInjection.expected
javascript/ql/test/query-tests/Security/CWE-089/untyped/mongoose.js

2 things:  
1) I was looking at `findByIdAndUpdate`, and I was surprised we flag the second argument as a NoSQL sink.   
See doc: https://mongoosejs.com/docs/tutorials/findoneandupdate.html. The second argument is the data given to the update function, so I'm unsure how that could be unsafe? 
2) A friend of mine likes to use `mongoose.Types.ObjectId.isValid` as a sanitizer for NoSQL injection.  
The function checks if an input is a string of a certain length, so it is a nice sanitizer for object-injection in general.  
I therefore decided to put it in `TaintedObject.qll`, let me know if you want it somewhere else.    
[The function is used a decent amount in the wild.](https://github.com/search?type=code&q=mongoose.Types.ObjectId.isValid)
[Evaluation looks …

JS: remove the second argument of findByIdAndUpdate as a NoSQL sink

---

java/ql/src/Telemetry/AutomodelApplicationModeCharacteristics.qll
java/ql/src/Telemetry/AutomodelApplicationModeExtractCandidates.ql
java/ql/src/Telemetry/AutomodelApplicationModeExtractNegativeExamples.ql
java/ql/src/Telemetry/AutomodelApplicationModeExtractPositiveExamples.ql
java/ql/src/Telemetry/AutomodelFrameworkModeCharacteristics.qll
java/ql/src/Telemetry/AutomodelFrameworkModeExtractCandidates.ql
java/ql/src/Telemetry/AutomodelFrameworkModeExtractNegativeExamples.ql
java/ql/src/Telemetry/AutomodelFrameworkModeExtractPositiveExamples.ql
java/ql/src/Telemetry/AutomodelJavaUtil.qll
java/ql/src/Telemetry/AutomodelSharedGetCallable.qll
java/ql/src/Telemetry/AutomodelSharedUtil.qll

This adds application mode extraction queries, using the legacy implementation as a guideline. We expect the behaviour to be mostly equal, but with some differences
- this includes an `UninterestingToModelCharacteristic` implementation that excludes some well-known frameworks. These would otherwise make up a large fraction of the candidates and we suggest removing them, as we now have framework mode.
- this limits the number of negative examples to at most 100 per class, as the negative examples could otherwise easily outweigh the candidates by a factor of 15-20x — this seemed overkill, given that only a handful ever make it into our prompts.
When reviewing this, feel free to run the extraction on a DB locally and tell us if you spot anything that should/shouldn't be a candidate, or +/- …

Java: Add QL support for automodel application mode

---

csharp/ql/lib/semmle/code/csharp/dataflow/FlowSummary.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll

In this PR we remove the *jump return kind* and related functionality as it is no longer used.
The last/only use case was re-factored into using *synthetic globals* instead: https://github.com/github/codeql/pull/13147
The only question is, whether we should deprecate this instead of deleting it?
I can't imagine anyone is using it (famous last words).

C#: Remove jump step

---

csharp/ql/src/Security Features/CWE-022/ZipSlip.qhelp
csharp/ql/src/Security Features/CWE-022/ZipSlip.ql
csharp/ql/src/change-notes/2023-06-16-zipslip-rename.md
go/ql/src/Security/CWE-022/ZipSlip.qhelp
go/ql/src/Security/CWE-022/ZipSlip.ql
go/ql/src/change-notes/2023-06-16-zipslip-rename.md
java/ql/src/Security/CWE/CWE-022/ZipSlip.qhelp
java/ql/src/Security/CWE/CWE-022/ZipSlip.ql
java/ql/src/change-notes/2023-06-16-zipslip-rename.md
javascript/ql/src/Security/CWE-022/ZipSlip.qhelp
javascript/ql/src/Security/CWE-022/ZipSlip.ql
javascript/ql/src/change-notes/2023-06-16-zipslip-rename.md
python/ql/src/change-notes/2023-06-16-zipslip-rename.md
python/ql/src/experimental/Security/CWE-022/ZipSlip.qhelp
python/ql/src/experimental/Security/CWE-022/ZipSlip.ql
ruby/ql/src/change-notes/2023-06-16-zipslip-rename.md
ruby/ql/src/experimental/cwe-022-zipslip/ZipSlip.qhelp
ruby/ql/src/experimental/cwe-022-zipslip/ZipSlip.ql

All filesystem operations, not just writes, with paths built from untrusted archive entry names are dangerous.

C#/Go/Java/JS/Python/Ruby: Update the description and qhelp of the Zipslip query

---

java/ql/src/Telemetry/AutomodelApplicationModeCharacteristics.qll
java/ql/src/Telemetry/AutomodelEndpointTypes.qll
java/ql/src/Telemetry/AutomodelFrameworkModeCharacteristics.qll
java/ql/src/Telemetry/AutomodelJavaUtil.qll
java/ql/src/Telemetry/AutomodelSharedCharacteristics.qll

This PR refactors code relevant to `automodel` to only use the native mad kinds.
I wonder: should we put in test for the existing queries with `.expected` files for the extraction queries?

Java: clean up mad kinds use

---

swift/third_party/load.bzl
swift/third_party/swift-llvm-support/patches/remove-result-of.patch

`std::result_of` was removed in C++20, though the actual removal from the STL library implementations seems to depend on the version. For example using xcode 14.2 one gets away with a deprecation warning, but xcode 14.3 will fail.
As Swift 5.8.1 is still compiled with C++14, we cannot replace `std::result_of` with `std::invoke_result` in the prebuilding patches just yet, but we can do that for the extractor itself, patching the prebuilt package.

Swift: remove `std::result_of` from swift headers

---

swift/ql/lib/CHANGELOG.md
swift/ql/lib/change-notes/2023-05-25-dataprotocol-models.md
swift/ql/lib/change-notes/2023-05-25-fix-ast-and-cfg-inconsistencies.md
swift/ql/lib/change-notes/2023-05-30-shared-sensitive.md
swift/ql/lib/change-notes/released/0.1.1.md
swift/ql/lib/codeql-pack.release.yml
swift/ql/lib/qlpack.yml
swift/ql/src/CHANGELOG.md
swift/ql/src/change-notes/released/0.1.1.md
swift/ql/src/codeql-pack.release.yml
swift/ql/src/qlpack.yml

The release preparation and post-release workflows were not updated for the Swift beta, in which Swift was promoted out of experimental.  This PR runs the post-release step for 2.13.3 and the release step for 2.13.4 manually, to prepare new versions of the Swift packs for 2.13.4.

Release preparation for Swift

---

cpp/ql/lib/change-notes/2023-06-19-delete-container-url.md
cpp/ql/lib/semmle/code/cpp/File.qll

Depends on internal PR (see backref).

CPP: delete the deprecated Container::getURL predicates

---

go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/completetest.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/sinks.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/srcs.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/test.go
go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/vendor/github.com/nonexistent/test/stub.go

The failure of models-as-data to deal with pointer content was highlighted in https://github.com/github/codeql/discussions/13415. This PR adds tests showing the problem.

Go: Add failing tests for MaD with pointer content

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll
cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowImpl.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll

Python and Ruby have been (ab)using `CastNode` to do this. Go now has a use-case as well, so I have made a proper language-specific hook.

Dataflow: add language-specific hook for breaking up big step relation

---

csharp/ql/lib/semmle/code/csharp/dataflow/ExternalFlow.qll
go/ql/lib/semmle/go/dataflow/ExternalFlow.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll
go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/completetest.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalFlow/test.go

This is based on https://github.com/github/codeql/pull/13453 and fixes the failing tests added in that PR.

Go: Add models-as-data content for pointer content

---

ql/ql/src/queries/style/FieldOnlyUsedInCharPred.ql
ql/ql/test/queries/style/FieldOnlyUsedInCharPred/FieldOnlyUsedInCharPred.expected
ql/ql/test/queries/style/FieldOnlyUsedInCharPred/FieldOnlyUsedInCharPred.qll
ql/ql/test/queries/style/FieldOnlyUsedInCharPred/FieldOnlyUsedInCharPred.qlref

FP spotted on https://github.com/github/codeql/pull/13509.

QL: Exclude overridden fields from `FieldOnlyUsedInCharPred.ql`

---

javascript/ql/src/Security/CWE-094/examples/comment_issue_good.yml

The use of the single quote effectively prevents the attack highlighted in the Expression injection in Actions [query](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-094/ExpressionInjection.qhelp) help it also prevents it from working effectively since using single quotes will effectively print `$BODY` because the variable is not expanded.
Double quotes will allow the expansion of the variable while still preventing the attack

JS: Single quote was preventing the shell from expanding the BODY variable in Expression injection in Actions example

---

ql/ql/src/codeql_ql/ast/internal/Predicate.qll

```
[2023-06-22 10:44:20] (92s) Tuple counts for Predicate#23818b54::Cached::resolveSelfClassCalls#2#ff/2@06fd3bf5 after 1m9s:
30500      ~567%     {3} r1 = JOIN Ast#8e1d5bcf::ClassPredicate::getName#0#dispred#ff WITH Ast#8e1d5bcf::PredicateOrBuiltin::getArity#0#dispred#ff ON FIRST 1 OUTPUT Lhs.0 'p', Lhs.1, Rhs.1
26500      ~573%     {4} r2 = JOIN r1 WITH Ast#8e1d5bcf::Class::getAClassPredicate#0#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.2, Lhs.0 'p', Lhs.1, Rhs.1
3059915597 ~605%     {4} r3 = JOIN r2 WITH Ast#8e1d5bcf::Call::getNumberOfArguments#0#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'mc', Lhs.2, Lhs.1 'p', Lhs.3
20999389   ~701%     {3} r4 = JOIN r3 WITH Ast#8e1d5bcf::MemberCall::getMemberName#0#dispred#ff ON FIRST 2 OUTPUT Lhs.0 'mc', Lhs.2 'p', Lhs.3
20995877   ~711% …
```

QL: Fix bad join

---

go/ql/lib/change-notes/2023-06-20-function-model-path-nodes.md
go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
go/ql/test/experimental/CWE-134/DsnInjection.expected
go/ql/test/experimental/CWE-134/DsnInjectionLocal.expected
go/ql/test/experimental/CWE-918/SSRF.expected
go/ql/test/library-tests/semmle/go/frameworks/Beego/ReflectedXss.expected
go/ql/test/query-tests/Security/CWE-022/TaintedPath.expected
go/ql/test/query-tests/Security/CWE-022/ZipSlip.expected
go/ql/test/query-tests/Security/CWE-078/CommandInjection.expected
go/ql/test/query-tests/Security/CWE-078/StoredCommand.expected
go/ql/test/query-tests/Security/CWE-079/ReflectedXss.expected
go/ql/test/query-tests/Security/CWE-079/StoredXss.expected
go/ql/test/query-tests/Security/CWE-089/SqlInjection.expected
go/ql/test/query-tests/Security/CWE-327/UnsafeTLS.expected
go/ql/test/query-tests/Security/CWE-338/InsecureRandomness/InsecureRandomness.expected
go/ql/test/query-tests/Security/CWE-352/ConstantOauth2State.expected

It was highlighted in https://github.com/github/codeql/discussions/13415 that we don't put steps from functions modeled using `DataFlow::FunctionModel` or `TaintTracking::FunctionModel` in path summaries, which can be confusing. This PR does that, showing both inputs and outputs. Here are screenshots showing the option of just inputs as well.
Inputs only:
Both inputs and outputs:
Note: as discussed in https://github.com/github/codeql/discussions/13415, step 3 in the second picture goes back to the definition of the variable being tainted, in a way which is quite counter-intuitive. This is a consequence of our use of def-use flow.
The downside of doing both is that any path which goes through the definition of sample (step 3 in the second picture) will have it in the path explanation, even …

Go: show FunctionModel steps in path summaries

---

ruby/ql/lib/codeql/ruby/regexp/internal/ParseRegExp.qll

Fix some minor QLDoc errors in `ParseRegExp.qll`.  Spotted while porting this library to Swift.
@erik-krogh

Ruby: Fix some QLDoc errors in ParseRegExp.qll

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/PrintIRFieldFlowSteps.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/PrintIRUtilities.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TaintTrackingUtil.qll
cpp/ql/lib/semmle/code/cpp/models/implementations/Strcpy.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/self_parameter_flow.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/test_self_parameter_flow.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test_self_parameter_flow.ql
cpp/ql/test/library-tests/dataflow/dataflow-tests/uninitialized.expected
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowDestination.expected

This PR fixes two conflation issues that were giving us a bunch of FPs on https://github.com/lief-project/lief.
The first fix is very simple (see 153df2cc82307833bee07ac75e260303cce399e5), and the second fix took a couple of days of debugging (see 7c32721238892ef0f900648188d5dca08fd0b3f8) 😂.

C++: Fix more conflation in dataflow

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/self-Iterator.cpp

As an alternative to https://github.com/github/codeql/pull/13445. Instead of excluding iterators whose `value_type` is itself, we recognize the case in dataflow and provide a sensible default.
@rdmarsh2 what do you think of this approach instead?

C++: Dataflow fix for the self-iterators issue

---

ruby/ql/lib/codeql/ruby/frameworks/Sinatra.qll

Just like it is [bad to compute `Location::toString`](https://github.com/github/codeql/pull/12117) in full, it's also bad to compute `locationRelativePathToString` in full, as it puts a lot of pressure on the string pool:
```
[2023-06-23 13:48:23] Evaluated non-recursive predicate Sinatra#e09174a3::Sinatra::locationRelativePathToString#1#ff@683a25ce in 34682ms (size: 8048121).
Evaluated relational algebra for predicate Sinatra#e09174a3::Sinatra::locationRelativePathToString#1#ff@683a25ce with tuple counts:
8048122  ~0%    {6} r1 = SCAN locations_default OUTPUT In.1, In.0, toString(In.5), toString(In.2), toString(In.3), toString(In.4)
8048121  ~0%    {2} r2 = JOIN r1 WITH FileSystem#df18ed9a::Make#FileSystem#e91ad87f::Input#::Container::getRelativePath#0#dispred#ff ON FIRST 1 OUTPUT Lhs.1, …
```

Ruby: Reduce string pool pressure by late-inlining `locationRelativePathToString`

---

ruby/ql/consistency-queries/AstConsistency.ql
ruby/ql/consistency-queries/CfgConsistency.ql
ruby/ql/consistency-queries/DataFlowConsistency.ql

Flags nodes with multiple `toString`s.

Ruby: Add `toString` functionality consistency queries

---

csharp/ql/consistency-queries/AstConsistency.qll
csharp/ql/consistency-queries/CfgConsistency.ql
csharp/ql/consistency-queries/DataFlowConsistency.ql

Flags nodes with multiple `toString`s.

C#: Add `toString` functionality consistency queries

---

ql/ql/src/codeql_ql/ast/Ast.qll
ql/ql/src/codeql_ql/style/DeadCodeQuery.qll
ql/ql/test/queries/style/DeadCode/DeadCode.expected
ql/ql/test/queries/style/DeadCode/Foo.qll

Removes some FPs seen on https://github.com/github/codeql/pull/13509.

QL: Improve dead-code query

---

csharp/downgrades/qlpack.yml
csharp/ql/campaigns/Solorigate/lib/qlpack.yml
csharp/ql/campaigns/Solorigate/src/qlpack.yml
csharp/ql/campaigns/Solorigate/test/qlpack.yml
csharp/ql/consistency-queries/qlpack.yml
csharp/ql/examples/qlpack.yml
csharp/ql/integration-tests/qlpack.yml

This PR enables implicit this warnings for remaining C# QL packs.

C#: Enable implicit this warnings for remaining packs

---

ruby/downgrades/qlpack.yml
ruby/ql/consistency-queries/qlpack.yml
ruby/ql/examples/qlpack.yml
ruby/ql/integration-tests/all-platforms/qlpack.yml

This PR enables implicit this warnings for remaining Ruby QL packs.

Ruby: Enable implicit this warnings for remaining packs

---

ql/ql/consistency-queries/qlpack.yml
ql/ql/examples/qlpack.yml
ql/ql/test/callgraph/packs/lib/qlpack.yml
ql/ql/test/callgraph/packs/other/qlpack.yml
ql/ql/test/callgraph/packs/src/qlpack.yml
ql/ql/test/qlpack.yml

This PR enables implicit this warnings for remaining QL-for-QL packs.

QL: Enable implicit this warnings for remaining packs

---

cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp

Fixes a family of FPs like the one exposed by `test31` (which I simplified to `test31_simple` in the first commit). The simple version of the FP looks like:
```cpp
void test31_simple1(unsigned size, unsigned src_pos)
{
char *xs = new char[size];
if (src_pos > size) {
src_pos = size;
}
if(src_pos < size) {
xs[src_pos] = 0;
}
}
```
in order to find invalid pointer addresses, the query finds a pair of nodes `(n1, n2)` such that there exists a pointer-arithmetic instruction `pai` such that
1. `n1` flows from the allocation and is equal to the left-side of `pai`, and
2. `n2` non-strictly upper-bounds the right-hand side of the `pai`
Those two conditions are satisfied by the above snippet where `n1` is `xs` in the `xs[src_pos] = 0` and `n2` is the `src_pos` in `xs[src_pos] = 0`. However, the …

C++: Add barriers to `cpp/invalid-pointer-deref`

---

javascript/downgrades/qlpack.yml
javascript/ql/examples/qlpack.yml
javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml
javascript/ql/experimental/adaptivethreatmodeling/model/qlpack.yml
javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/qlpack.yml
javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml
javascript/ql/experimental/adaptivethreatmodeling/test/qlpack.yml
javascript/ql/integration-tests/all-platforms/qlpack.yml

This PR enables implicit this warnings for remaining Javascript QL packs.

Javascript: Enable implicit this warnings for remaining packs

---

csharp/ql/consistency-queries/TypeConsistency.qll
csharp/ql/lib/semmle/code/csharp/AnnotatedType.qll
csharp/ql/lib/semmle/code/csharp/Generics.qll
csharp/ql/lib/semmle/code/csharp/Type.qll
csharp/ql/lib/semmle/code/csharp/TypeRef.qll
csharp/ql/lib/semmle/code/csharp/Unification.qll
csharp/ql/lib/semmle/code/dotnet/Generics.qll

This PR:
- Makes `NullableType` a subtype of `ConstructedType`.
- Fixes unintended fan-out in `TypeRef::getReferencedType` when there are multiple `UnknownType`s in the database.
- Adds a safe-guard in the GVN construction for types to prevent blow-up when a type has multiple type parameters/arguments at the same index.
- Adds consistency queries for checking uniqueness (and existence) of GVN types.
Before this PR, the uniqueness query would yield results on MRVA top-1000; after this PR it doesn't.

C#: Avoid combinatorial explosions in GVN construction for types

---

go/downgrades/qlpack.yml
go/external-packs/codeql/suite-helpers/0.0.2/qlpack.yml
go/ql/config/legacy-support/qlpack.yml
go/ql/examples/qlpack.yml
go/ql/integration-tests/all-platforms/go/qlpack.yml
go/ql/integration-tests/linux-only/go/qlpack.yml

This PR enables implicit this warnings for remaining Go QL packs.

Go: Enable implicit this warnings for remaining packs

---

.github/workflows/check-implicit-this.yml

This PR adds a workflow to verify that all QL packs in `github/codeql` have the `warnOnImplicitThis` property configured to `true`. The workflow is initially configured to trigger manually, until I have verified the workflow and `warnOnImplicitThis` has been configured to `true` for all remaining packs.

Add workflow to check for warnOnImplicitThis

---

java/ql/integration-tests/all-platforms/java/android-sample-old-style-kotlin-build-script-no-wrapper/project/build.gradle.kts
java/ql/integration-tests/all-platforms/java/android-sample-old-style-kotlin-build-script-no-wrapper/test.expected
java/ql/integration-tests/all-platforms/java/android-sample-old-style-kotlin-build-script/project/build.gradle.kts
java/ql/integration-tests/all-platforms/java/android-sample-old-style-kotlin-build-script/test.expected
java/ql/integration-tests/all-platforms/java/android-sample-old-style-no-wrapper/project/build.gradle
java/ql/integration-tests/all-platforms/java/android-sample-old-style-no-wrapper/test.expected
java/ql/integration-tests/all-platforms/java/android-sample-old-style/project/build.gradle
java/ql/integration-tests/all-platforms/java/android-sample-old-style/test.expected

They were all failing for me like:
```
[autobuild] /home/ian/code/dev/target/codeql-java-integration-tests/ql/java/ql/integration-tests/all-platforms/java/android-sample-old-style-no-wrapper/project/src/main/AndroidManifest.xml:5: Error: Main must extend android.app.Activity [Instantiatable]
[autobuild]         <activity android:name="Main" android:exported="true">
[autobuild]                                 ~~~~
[autobuild]    Explanation for issues of type "Instantiatable":
[autobuild]    Activities, services, broadcast receivers etc. registered in the manifest
[autobuild]    file (or for custom views, in a layout file) must be "instantiatable" by
[autobuild]    the system, which means that the class must be public, it must have an
[autobuild]    empty public constructor, and if it's an …
```

Java: Tweak some android tests

---

python/downgrades/qlpack.yml
python/ql/consistency-queries/qlpack.yml
python/ql/examples/qlpack.yml
python/tools/recorded-call-graph-metrics/ql/qlpack.yml

This PR enables implicit this warnings for remaining Python QL packs.

Python: Enable implicit this warnings for remaining packs

---

cpp/downgrades/qlpack.yml
cpp/ql/examples/qlpack.yml
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/qlpack.yml

This PR enables implicit this warnings for remaining CPP QL packs.

CPP: Enable implicit this warnings for remaining packs

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticSSA.qll
cpp/ql/test/library-tests/ir/range-analysis/test.cpp

This modifies the test to add an additional basic block to the loop, exposing a bug in the previous logic where the source and destination edges were reversed.

C++: fix irreducible control flow logic

---

.pre-commit-config.yaml
swift/third_party/load.bzl
swift/third_party/swift-llvm-support/patches/add-constructor-to-Compilation.patch
swift/third_party/swift-llvm-support/patches/remove-redundant-operators.patch

This is not required yet, but may be as soon as we start including SIL headers.

Swift: fix all upstream headers for C++20

---

csharp/ql/src/Telemetry/ExternalApi.qll
csharp/ql/test/query-tests/Telemetry/LibraryUsage/ExternalLibraryUsage.cs
csharp/ql/test/query-tests/Telemetry/LibraryUsage/ExternalLibraryUsage.expected
csharp/ql/test/query-tests/Telemetry/LibraryUsage/SupportedExternalTaint.expected

This fixes the name of reported external APIs for nested types. The `getDeclaringType().getUnboundDeclaration()`'s `toString()` method reports the name of the type, but not the name of the declaring type. This results in missing information in the `UnsupportedExternalAPIs.ql` query.
For example, previously it would report:
```
GitHub.Nested#NestedClass.Test()
```
However, the `NestedClass` class does not exist in the namespace and is only a nested type within `MyFirstClass`. The correct name should be:
```
GitHub.Nested#MyFirstClass+NestedClass.Test()
```
This name also matches the format of MaD.

C#: Fix external API name for nested types

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll

Before:
```ql
[2023-06-28 09:29:51] Evaluated non-recursive predicate DataFlowImplCommon#59e7a193::Cached::argumentNode#3#fff@8606bd35 in 1945ms (size: 1366058).
Evaluated relational algebra for predicate DataFlowImplCommon#59e7a193::Cached::argumentNode#3#fff@8606bd35 with tuple counts:
764401   ~0%    {3} r1 = JOIN DataFlowPrivate#fbdd7bd7::DirectPosition#ff_10#join_rhs WITH Instruction#577b6a83::CallInstruction::getArgumentOperand#fff_102#join_rhs ON FIRST 1 OUTPUT Rhs.2, Lhs.1, Rhs.1
764401   ~0%    {3} r2 = JOIN r1 WITH DataFlowPrivate#fbdd7bd7::PrimaryArgumentNode#fff_20#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.2, Lhs.1
65   ~0%    {3} r3 = SCAN DataFlowPrivate#fbdd7bd7::IndirectionPosition#fff OUTPUT In.2, In.0, In.1
180518864   ~0%    {3} r4 = JOIN r3 WITH …
```

C++: Fix join in `argumentOf`

---

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt

This isn't supported in Kotlin 2 mode, but removing this code doesn't affect any tests.

Kotlin: Remove a use of ObsoleteDescriptorBasedAPI

---

python/ql/lib/semmle/python/dataflow/new/internal/TypeTracker.qll
ruby/ql/lib/codeql/Locations.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTracker.qll

Removes a few proxy predicates, now that `pragma[inline_late]` is allowed on member predicates.

Ruby/Python: Use `inline_late` on member predicates

---

swift/third_party/load.bzl

Using the latest build without [an old patch](https://github.com/dsp-testing/codeql-swift-artifacts/pull/16).

Swift: bump Swift build, NFC

---

java/ql/src/Telemetry/ExternalApi.qll
java/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.expected
java/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.java

This fixes the name of reported external APIs for nested types. The `toString()` method of `getSourceDeclaration()` would report the name of a type, but not the name of the enclosing type. This results in missing information in the `UnsupportedExternalAPIs.ql` query.
For example, previously it would report:
```
org.zapodot.junit.db.Builder#build()
```
However, the `Builder` class does not exist in the package and is only a nested type within `EmbeddedDatabaseRule`. The correct name should be:
```
org.zapodot.junit.db.EmbeddedDatabaseRule$Builder#build()
```
This name also matches the format of MaD.

Java: Fix external API name for nested types

---

.github/workflows/check-implicit-this.yml

Enable CI check for implicit this warnings for all PRs that modify `qlpack.yml` files. 
Test run to validate failure: https://github.com/github/codeql/actions/runs/5412179604/jobs/9835932651.
Test run to validate success: https://github.com/github/codeql/actions/runs/5411315549/jobs/9833893355

Enable implicit this warning CI checks

---

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/constant-size/ConstantSizeArrayOffByOne.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/constant-size/test.cpp

Adds reduced versions of the FPs we've seen [here](https://github.com/github/codeql/pull/13116#issuecomment-1607338581).

C++: Add `cpp/constant-array-overflow` FPs

---

cpp/ql/src/Security/CWE/CWE-119/OverrunWriteProductFlow.ql
cpp/ql/test/query-tests/Security/CWE/CWE-119/SAMATE/OverrunWriteProductFlow.expected

Two performance improvements:
- First, we add a barrier to the configuration that computes the set of valid states. This is valid because the set barrier is also present in the product-flow configuration (which consumes those states). This speeds up the stage that computes the set of states for the product-flow configuration.
- Second, we use the above dataflow configuration to prune the product-flow configuration.
This last point fixes a timeout I was seeing on a project locally.

C++: Speed up `cpp/overrun-write`

---

csharp/extractor/Semmle.Extraction.CSharp.Standalone/BuildAnalysis.cs

`Directory.Build.props` is oftentimes required for `dotnet restore` to succeed. The comment on top of the renaming logic says it was renamed to help `dotnet restore`, but I haven't found projects where I could repro the failure when the file is not removed. On the other hand I found many where it causes issues.
This change has significant impact on the standalone-traced dependency comparison query results. The below results ignore assembly versions (just the names are considered). 9 out of the 30 top MRVA projects show similar changes. The values show the number of assembly names that are in both/only traced/only standalone DBs. 
```diff
Results for JamesNK/Newtonsoft.Json
Query Dependencies.ql:
-  Result count - both/traced/standalone: 185/13/327
+  Result count - both/traced/standalone: …
```

C#: Remove the renaming of `Directory.Build.props` from standalone extraction

---

ruby/ql/lib/codeql/ruby/frameworks/Sqlite3.qll
ruby/ql/test/library-tests/frameworks/sqlite3/Sqlite3.expected

This pointed to the database instance rather than the SQL statement. In practice I don't think that this would have caused us to lose results in most cases since the statement preparation also counts as a sink.

Ruby: fix sqlite3 `PreparedStatementExecution.getSql()` predicate

---

cpp/ql/src/Security/CWE/CWE-119/OverrunWriteProductFlow.ql
cpp/ql/test/query-tests/Security/CWE/CWE-119/SAMATE/OverrunWriteProductFlow.expected

The barrier I added in https://github.com/github/codeql/pull/13623 had some unexpected result changes that I don't fully understand. So this PR reverts the barrier, but keeps the additional conjunct added to `isSourcePair`. This should still provide a speed boost, but without impacting results in any way 🤞.
Note that the changes to .expected matches the changes we saw in https://github.com/github/codeql/pull/13623.

C++: Revert parts of #13623

---

cpp/ql/src/Security/CWE/CWE-190/ComparisonWithWiderType.ql
cpp/ql/src/change-notes/2023-06-29-improve-comparison-wider-type.md
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/ComparisonWithWiderType/ComparisonWithWiderType.expected
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/ComparisonWithWiderType/test.c

The provided example case is not detected because the value `INT16_MAX + 1` can be represented with 16 bits. To account for the overflow that happens before the comparison we need to determine if the value can be represented by the type of the lesser operand. We do this by adjusting the size of the lesser operand if it is signed to ensure that the check
`upperBound(conv).log2() > (getComparisonSize(small) * 8 - getComparisonSizeAdjustment(small))` holds.
```cpp
...
uint32_t big_num = INT32_MAX;
char buf[big_num];
int16_t bytes_received = 0;
int max_get = INT16_MAX + 1;
// BAD: 'bytes_received' is compared with a value of a wider type.
// 'bytes_received' overflows before  reaching 'max_get',
// causing an infinite loop
while (bytes_received < max_get)
bytes_received += get_from_input(buf, …
```

C++: Account for the signedness of the lesser operand in `cpp/comparison-with-wider-type`

---

csharp/ql/lib/semmle/code/csharp/dataflow/FlowSummary.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll
csharp/ql/lib/semmle/code/csharp/frameworks/EntityFramework.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll
go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.expected
go/ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.expected
java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImplSpecific.qll
python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImplSpecific.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
ruby/ql/test/library-tests/dataflow/local/TaintStep.expected
swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImplSpecific.qll

In this PR we try to align then printing of summary component stacks with their textual representation as they would like, when being used in an access path (for MaD models).
Furthermore, it turns out that the existing printer `getComponentStack` is not up to date for all languages. This is also fixed in this PR.

Re-factor printing of summary component stacks.

---

csharp/ql/src/Telemetry/ExternalApi.qll
java/ql/src/Telemetry/ExternalApi.qll

It turns out that the Java and C# Telemetry queries on API usage still produces to much data.
In this PR we limit the number of APIs being reported only to the top-100 that matches the reporting criteria.

Java/C#: Reduce the amount of telemetry being produced.

---

swift/ql/lib/change-notes/2023-07-04-swap.md
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/ManualMemoryManagement.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/StandardLibrary.qll
swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/test.swift

Add a dataflow model for [`swap(_:_:)`](https://developer.apple.com/documentation/swift/swap(_:_:)).

Swift: Add dataflow model for 'swap'

---

cpp/ql/src/Security/CWE/CWE-119/OverrunWriteProductFlow.ql

The issue that caused us to revert the earlier PR has now been fixed and we're seeing no new timeouts when running on QA 🎉.

C++: Move `cpp/overrun-write` back to `medium` precision

---

docs/codeql/reusables/supported-versions-compilers.rst

Should only be merged/deployed after CodeQL 2.13.5 release.

Docs: update supported Swift versions

---

python/ql/lib/semmle/python/Concepts.qll
python/ql/lib/semmle/python/frameworks/MarkupSafe.qll
python/ql/lib/semmle/python/security/dataflow/XxeCustomizations.qll
python/ql/test/library-tests/frameworks/markupsafe/taint_test.py
python/ql/test/query-tests/Security/CWE-611-Xxe/Xxe.expected
python/ql/test/query-tests/Security/CWE-611-Xxe/test.py

This Pull Request adds support for `markupsafe` as a sanitizer of the XXE query.

Python: Add `markupsafe` as XXE sanitizer

---

ruby/ql/src/queries/diagnostics/PerformanceDiagnostics.ql

Adds a query that outputs some numbers that can be used to help narrow down the cause of performance issues in a codebase, without leaking any actual code or identifiers from the codebase.
The query has `@kind table` and isn't part of any query suite. I put it in the `diagnostics` folder because it seems like a diagnostic query, but it doesn't have `@kind diagnostics` like the other queries there.

Ruby: performance diagnostics query

---

csharp/extractor/Semmle.Extraction.CSharp.Standalone/BuildAnalysis.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/DotNet.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/Properties/AssemblyInfo.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/Runtime.cs
csharp/extractor/Semmle.Extraction.Tests/Runtime.cs
csharp/extractor/Semmle.Util/DictionaryExtensions.cs

In this PR we re-write how the standalone extractor finds the .NET runtime DLLs that will be included in the extraction.
Prior to this change, the standalone extractor tried to derive, where the runtime DLLs were located by inspecting the location of the `dotnet` executable based on the `$PATH`.
It is probably a better solution to use `dotnet --list-runtimes` to get the locations of all installed runtimes (also including ASP.NET Core).
In this PR the standalone extractor is rewritten to use the information from `dotnet --list-runtimes` to pick the *newest* .NET Runtime and include it in the extraction.
If a project is a ASP.NET Core project, we would like to also include the ASP.NET Core DLLs. This PR prepares for this change.

C#: Use dotnet --list-runtimes to find runtime locations.

---

csharp/extractor/Semmle.Extraction.CSharp.Standalone/BuildAnalysis.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/DotNet.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/ProgressMonitor.cs

The PR takes into account the `nuget.config` file in the repo, when doing `dotnet restore` on individual packages. If there are multiple `nuget.config` files, we're looking for one in the root folder.
On `dotnet/wcf`, this change helps restore 3 out of the 7 previously not restored packages.

C#: Use `nuget.config` file for `dotnet restore` fallback logic

---

swift/extractor/infra/SwiftTagTraits.h
swift/third_party/load.bzl

The prebuild binary change adds `CodeQLSwiftVersion.h` header, see https://github.com/dsp-testing/codeql-swift-artifacts/pull/18

Swift: 5.9 preparation

---

cpp/ql/src/Likely Bugs/Memory Management/UninitializedLocal.ql
cpp/ql/src/change-notes/2023-07-03-improve-uninitialized-local.md
cpp/ql/test/query-tests/Security/CWE/CWE-457/semmle/tests/UninitializedLocal.expected
cpp/ql/test/query-tests/Security/CWE/CWE-457/semmle/tests/test.cpp

This eliminates FPs such as casting a variable explicitly to void type. E.g.
``` C
(void) x;
```
Developers use this cast to supress compiler warnings on unused variables.

C++: exclude uninitialized uses inside pure expression statements

---

swift/ql/lib/change-notes/2023-07-06-url-models.md
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Url.qll
swift/ql/test/library-tests/dataflow/taint/libraries/CONSISTENCY/CfgConsistency.expected
swift/ql/test/library-tests/dataflow/taint/libraries/url.swift

Greatly expand taint models for `URL`.  Includes tests, and models for contained classes `URLResource` and `URLResourceValues`.

Swift: Expand taint models for URL

---

java/ql/lib/ext/android.webkit.model.yml
java/ql/lib/semmle/code/java/security/UnsafeAndroidAccess.qll
java/ql/src/change-notes/2023-07-10-unsafe-android-access-apply.md
java/ql/test/query-tests/security/CWE-749/UnsafeActivityKt.kt

After https://github.com/github/codeql/pull/13702, we can now support WebViews that get their dangerous attributes set inside an `apply` block in Kotlin.
This also expands some `WebView` models by allowing subtypes.

Java: Add support for Kotlin's `apply` to java/android/unsafe-android-wevbiew-fetch

---

go/ql/lib/change-notes/2023-07-05-parameter-nodes-for-unused-parameters.md
go/ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll
go/ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getExitNode.expected

An alternative approach to https://github.com/github/codeql/pull/13664

Go: make `ParameterNode`s for unused parameters #2 (make a disjoint class for unused ones)

---

cpp/ql/lib/change-notes/2023-07-12-default-stateconfigsig-predicates.md
cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlow.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlow.qll
csharp/ql/lib/change-notes/2023-07-12-default-stateconfigsig-predicates.md
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlow.qll
go/ql/lib/change-notes/2023-07-12-default-stateconfigsig-predicates.md
go/ql/lib/semmle/go/dataflow/internal/DataFlow.qll
java/ql/lib/change-notes/2023-07-12-default-stateconfigsig-predicates.md
java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll
python/ql/lib/change-notes/2023-07-12-default-stateconfigsig-predicates.md
python/ql/lib/semmle/python/dataflow/new/internal/DataFlow.qll
ruby/ql/lib/change-notes/2023-07-12-default-stateconfigsig-predicates.md
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlow.qll
swift/ql/lib/change-notes/2023-07-12-default-stateconfigsig-predicates.md
swift/ql/lib/codeql/swift/dataflow/internal/DataFlow.qll

Adds default implementations of the `isBarrier/2` and `isAdditionalFlowStep/4` predicates of `StateConfigSig` in the DataFlow library.
CodeQL now supports default predicates that use parameters in module signatures. Previously this was not supported and it was necessary to add default implementations to modules implementing `StateConfigSig` manually.

DataFlow: Add default implementations of isBarrier/2 and isAddiitonalFlowStep/4

---

cpp/ql/src/Critical/FlowAfterFree.qll
cpp/ql/src/Likely Bugs/Conversion/CastArrayPointerArithmetic.ql
cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql
cpp/ql/src/Security/CWE/CWE-119/OverrunWriteProductFlow.ql
cpp/ql/src/experimental/Security/CWE/CWE-193/ConstantSizeArrayOffByOne.ql
swift/ql/lib/codeql/swift/security/StringLengthConflationQuery.qll

These now have default implementations that are also `none()`

C++/Swift: Remove `none()` dataflow configuration predicates

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll

This bug was causing a performance regression found in the latest QA run. Let's see how its fix affects performance elsewhere.

Dataflow: Fix forceHighPrecision for length-2 prefixes.

---

swift/ql/src/change-notes/2023-06-23-redos-query.md
swift/ql/src/queries/Security/CWE-1333/ReDoS.qhelp
swift/ql/src/queries/Security/CWE-1333/ReDoS.ql
swift/ql/src/queries/Security/CWE-1333/ReDoSIntroduction.inc.qhelp
swift/ql/src/queries/Security/CWE-1333/ReDoSReferences.inc.qhelp
swift/ql/test/query-tests/Security/CWE-1333/ReDoS.expected
swift/ql/test/query-tests/Security/CWE-1333/ReDoS.qlref
swift/ql/test/query-tests/Security/CWE-1333/ReDoS.swift

Adds a query for REDOS (Regular Expression Denial Of Service), built atop the regular expressions library from https://github.com/github/codeql/pull/13470.
At present there are significant limitations (the largest of which being that the regex library doesn't support regular expression literals yet), but I believe the query adds value in its current state, and will find more results as we improve the library.
TODO:

Swift: Query for REDOS (Regular Expression Denial Of Service)

---

ruby/ql/lib/codeql/ruby/ApiGraphs.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/src/change-notes/2023-06-29-api-graph-explicit-proc-lambda.md
ruby/ql/test/library-tests/dataflow/api-graphs/VerifyApiGraphExpectations.expected
ruby/ql/test/library-tests/dataflow/api-graphs/explicit-proc.rb

- Treats `Proc.new` as an explicit lambda creation, alongside `proc` and `lambda` calls.
- Makes API graphs step through such lambda creations when backtracking
Should fix the issue brought up here: https://github.com/github/codeql/pull/13483/files#diff-4eabe9f52cd51fcb0f830d178af3fb1a36df1e623ae2acbf4a2b25f968e9ee7fR25

Ruby: Improve support for explicit proc-creation

---

ruby/ql/lib/codeql/ruby/frameworks/rack/internal/App.qll

Ruby: Use API graphs asCallable() instead of Proc.new workaround

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticExprSpecific.qll

This fixes the performance issues on three projects that were timing out on QA

C++: Exclude invalid functions from new range analysis

---

ruby/ql/lib/change-notes/2023-07-05-rack-response.md
ruby/ql/lib/codeql/ruby/frameworks/Rack.qll
ruby/ql/lib/codeql/ruby/frameworks/rack/internal/Request.qll
ruby/ql/lib/codeql/ruby/frameworks/rack/internal/Utils.qll
ruby/ql/test/library-tests/dataflow/local/TaintStep.expected
ruby/ql/test/library-tests/frameworks/rack/Rack.expected
ruby/ql/test/library-tests/frameworks/rack/Rack.ql
ruby/ql/test/library-tests/frameworks/rack/rack.rb

A `Rack::Request` instance is typically constructed from an `env` parameter to the rack application method and contains request parameters and cookies.
We also add `Rack::Utils.parse_query` as a taint step, this converts a query string like `"foo=bar&baz=qux"` into a hash like `{"foo"=>"bar", "baz"=>"qux"}`.

Ruby: add `Rack::Request` params and cookies as remote input sources

---

cpp/ql/lib/change-notes/2023-06-29-deprecate-ast-dataflow.md
cpp/ql/lib/semmle/code/cpp/dataflow/DataFlow.qll
cpp/ql/lib/semmle/code/cpp/dataflow/DataFlow2.qll
cpp/ql/lib/semmle/code/cpp/dataflow/DataFlow3.qll
cpp/ql/lib/semmle/code/cpp/dataflow/DataFlow4.qll
cpp/ql/lib/semmle/code/cpp/dataflow/TaintTracking.qll
cpp/ql/lib/semmle/code/cpp/dataflow/TaintTracking2.qll
cpp/ql/test/library-tests/dataflow/dataflow-edge-tests/additionalEdges.expected
cpp/ql/test/library-tests/dataflow/dataflow-edge-tests/standardEdges.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/has-parameter-flow-out.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/localFlow.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test-number-of-outnodes.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.expected
cpp/ql/test/library-tests/dataflow/fields/partial-definition-diff.expected
cpp/ql/test/library-tests/dataflow/fields/partial-definition.expected
cpp/ql/test/library-tests/dataflow/smart-pointers-taint/taint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.expected
docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp.rst

All of our queries use IR dataflow now (hopefully!).

C++: Deprecate AST dataflow

---

swift/ql/lib/change-notes/2023-07-10-regex-mode-flags.md
swift/ql/lib/codeql/swift/regex/internal/ParseRegex.qll
swift/ql/test/library-tests/regex/parse.expected
swift/ql/test/library-tests/regex/redos_variants.swift
swift/ql/test/library-tests/regex/regex.ql
swift/ql/test/library-tests/regex/regex.swift

Recognize regular expression parse mode flags in Swift.  For example in `(?i)foo`, the `(?i)` specifies a case-insensitive match of the rest of the regular expression `foo`.
This improves the accuracy of the REDOS and bad HTML filtering queries (and others to come).
Limitations:
1. does not support alternative ways of setting the parse mode, i.e. using function calls / parameters outside of the regex string itself (this will be high priority follow-up work)
2. does not support modes specified in regex literals (because we don't support regex literals yet)
3. does not support setting the mode in the middle of a regex `foo(?i)bar`, which is allowed in Swift
4. does not support setting the mode only for a portion of a regex `(?i:foo)bar`, which is allowed in Swift
5. does not support turning …

Swift: Recognize regular expression parse mode flags

---

java/ql/lib/semmle/code/java/security/ArithmeticTaintedQuery.qll
java/ql/lib/semmle/code/java/security/ImproperValidationOfArrayIndexQuery.qll
java/ql/lib/semmle/code/java/security/LogInjectionQuery.qll
java/ql/lib/semmle/code/java/security/NumericCastTaintedQuery.qll
java/ql/lib/semmle/code/java/security/RequestForgeryConfig.qll

In certain projects there can be a lot of source-to-source flow, which can cause a cartesian explosion in the number of results for queries that already tends to have many results for such projects. A recent QA run identified these 5 queries to be the worst offenders in this regard.
Should fix https://github.com/github/codeql-java-team/issues/325

Java: Exclude source-to-source flow in 5 queries.

---

swift/ql/lib/codeql/swift/security/regex/RegexInjectionExtensions.qll
swift/ql/lib/codeql/swift/security/regex/RegexInjectionQuery.qll
swift/ql/src/change-notes/2023-07-04-regex-injection.md
swift/ql/src/queries/Security/CWE-730/RegexInjection.qhelp
swift/ql/src/queries/Security/CWE-730/RegexInjection.ql
swift/ql/src/queries/Security/CWE-730/RegexInjectionBad.swift
swift/ql/src/queries/Security/CWE-730/RegexInjectionGood.swift
swift/ql/test/query-tests/Security/CWE-730/RegexInjection.expected
swift/ql/test/query-tests/Security/CWE-730/RegexInjection.qlref
swift/ql/test/query-tests/Security/CWE-730/tests.swift

Adds a query for regular expression injection, that is, constructing a regular expression from unsanitized user input.  This is fairly straightforward as the vulnerability is a simple injection issue and we already have a regular expressions library that identifies points where regular expressions are evaluated.  It turns out we also want to identify points where regular expressions are constructed in advance of evaluation, so as to get clean and reliable alerts, so we do that as well.
There are a handful of test results that are false positives or not detected.  We have follow-up issues to address all of these, and in the case of the false positives I do not believe they will be noisy in real world projects before we address them.
TODO:

Swift: Query for regular expression injection

---

swift/ql/lib/codeql/swift/regex/Regex.qll
swift/ql/lib/codeql/swift/regex/internal/RegexTracking.qll
swift/ql/test/query-tests/Security/CWE-1333/ReDoS.expected
swift/ql/test/query-tests/Security/CWE-1333/ReDoS.swift

Refactor the regex library data flow tracking.  This is necessary in order to (in a future PR) track mode flags through regular expression objects cleanly.
Before:
- `RegexUseConfig` tracked flow from string literals -> regex evaluation.
- in some cases regex evaluation occurs directly on the string: `string literal --> RegexEval`.
- more commonly a `Regex` object is created from the string, to be evaluated later; this was treated as an additional flow step, so the config actually tracked flow through both string and `Regex` objects: `string literal --> Regex constructor --> RegexEval`.
After:
- a new `RegexTracking.qll` file is introduced for the data flow configs.
- a new `RegexCreation` class models the creation of `Regex` objects, rather than being modelled ad-hoc.
- data flow is …

Swift: Refactor regex library

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ProductFlow.qll
cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/AllocationToInvalidPointer.qll
cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/InvalidPointerToDereference.qll
cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/RangeAnalysisUtil.qll
cpp/ql/src/experimental/Security/CWE/CWE-193/InvalidPointerDeref.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/AllocationToInvalidPointer.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/AllocationToInvalidPointer.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerToDereference.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerToDereference.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp

This PR splits the `cpp/invalid-pointer-deref` query into smaller files that each represent a phase of the query:
- `AllocationToInvalidPointer.qll` tracks the flow from an allocation to the pointer-arithmetic expression. The file exposes 1 predicate: `pointerAddInstructionHasBounds`.
- `InvalidPointerToDereference.qll` tracks flow from the pointer-arithmetic expression to the dereference. The file exposes 1 predicate: `operationIsOffBy`.
- `InvalidPointerDeref.ql` is the actual query that imports those two new "libraries" and implements the final dataflow configuration.
The first commit does another round of restructuring to prepare the file splitting. The actual splitting is done in 5099de5b3dbee131146b1bb2f88085721c4e89fb (which is simply moving stuff into separate files and fixing a …

C++: Split `cpp/invalid-pointer-deref` into more files

---

ql/ql/src/queries/performance/MissingNoinline.ql
ql/ql/test/queries/performance/MissingNoInline/MissingNoInline.expected
ql/ql/test/queries/performance/MissingNoInline/MissingNoInline.qlref
ql/ql/test/queries/performance/MissingNoInline/Test.qll

Fixes the FP surfaced [here](https://github.com/github/codeql/security/code-scanning/84853).

QL: Fix FP in `ql/missing-noinline`

---

java/ql/src/Telemetry/AutomodelAlertSinkUtil.qll
java/ql/src/Telemetry/AutomodelAlertSinks.ql
java/ql/src/Telemetry/AutomodelAlertSinksPerQuery.ql
java/ql/src/Telemetry/AutomodelCountGeneratedSinks.ql
java/ql/src/Telemetry/AutomodelJavaUtil.qll
java/ql/src/Telemetry/AutomodelSinkModelMrvaQueries.ql

Adds two queries for gathering metrics on the number of alerts (for a selection of queries) that arise from models with the `ai-generated` provenance.
Also adds `pragma[nomagic]` to one of the utility predicates, as it would otherwise cause an inefficient join order to appear.

Java: Add metric queries for counting sinks coming from models

---

swift/ql/lib/codeql/swift/frameworks/StandardLibrary/CustomUrlSchemes.qll

We don't recognize [`UIApplication.LaunchOptionsKey.url`](https://developer.apple.com/documentation/uikit/uiapplication/launchoptionskey/1622996-url) correctly for the purposes of a taint source in [`OversecuredVulnerableiOSApp`](https://github.com/oversecured/OversecuredVulnerableiOSApp/blob/deaec03a80483bb6cac782610f38cbbbdb920e20/OVIA/AppDelegate.swift#LL10C1-L10C1) (and likely other projects) because the enclosing struct `UIApplication.LaunchOptionsKey` is not associated with `url`.  Handily, the type of `url` also equals `UIApplication.LaunchOptionsKey`.  So for the time being, lets use that instead to make sure we're looking at the right thing called `url`.
I'll do some further experiments (including a DCA run) to verify this really does improve real world results...

Swift: Pragmatic fix for CustomUrlSchemes.qll.

---

swift/ql/lib/change-notes/2023-07-19-regex-mode-flags -more.md
swift/ql/lib/codeql/swift/regex/Regex.qll
swift/ql/lib/codeql/swift/regex/internal/ParseRegex.qll
swift/ql/lib/codeql/swift/regex/internal/RegexTracking.qll
swift/ql/test/library-tests/regex/parse.expected
swift/ql/test/library-tests/regex/regex.swift

Track regular expression parse modes set in code (we already support parse modes set with special syntax inside the regular expression string itself).
There's quite a lot here.  Everything is complicated by the fact these flags work in two different ways:
- for `Regex`, you create the `Regex` object first then set the flags using method calls on it.
- `Regex(...).ignoresCase(true).firstMatch(...)`
- for `NSRegularExpression` objects, the flags are values which pass into the `NSRegularExpression` initializer (via an array argument).
- `NSRegularExpression(..., options: [.caseInsensitive]).firstMatch(...)`
I suggest readers begin at `RegexParseModeConfig` in `RegexTracking.qll`, which tracks parse mode flags themselves from wherever they are created or set (i.e. either method above) all the …

Swift: Track regular expression parse modes set in code

---

java/ql/lib/change-notes/2023-07-19-inputstream-dispatch.md
java/ql/lib/ext/java.io.model.yml
java/ql/lib/semmle/code/java/dispatch/VirtualDispatch.qll

Adds `java.io.InputStream` as a valid target class for low-confidence dispatch consideration.
Also adds a summary model for `InputStream.read()`, which offers a high-confidence alternative for this method.

Java: Avoid low-confidence dispatch to InputStream methods

---

cpp/ql/test/library-tests/ir/ssa/aliased_ssa_ir.expected
cpp/ql/test/library-tests/ir/ssa/aliased_ssa_ir_unsound.expected
cpp/ql/test/library-tests/ir/ssa/ssa.cpp
cpp/ql/test/library-tests/ir/ssa/unaliased_ssa_ir.expected
cpp/ql/test/library-tests/ir/ssa/unaliased_ssa_ir_unsound.expected

This is technically already covered by the raw IR tests, but the frontend update is giving me regressions on the Phi and Chi nodes, so I'd like to have an explicit SSA test for this.

C++: Add IR SSA test case for the ternary operator

---

cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/AllocationToInvalidPointer.qll
cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/InvalidPointerToDereference.qll

This PR does two things (both suggested by @jketema):
1. 108cd7f078d652e230ea4fa2c5a46d48e02b66cd replaces less than ideal identifier names such as `sink1` with `allocSink`, and `sink2` with `sizeSink` etc. These were originally named to match the first (resp. second) projection of the product-flow configuration, but I do see that this is ideal.
2. 83aef6fc167ea1abf831d065e66ac12683bd4e25 replaces the words `x is non-strictly upper bounded by y` with `x <= y` to ease readability.
Since this doesn't actually change any behavior of the query it should be fine to merge this without a DCA run.
This will slightly conflict with https://github.com/github/codeql/pull/13774, but since that PR only adds QLDoc in the top of the files it should be trivial to fix those conflicts.

C++: Improve names of identifiers in `cpp/invalid-pointer-deref`

---

java/ql/src/Telemetry/AutomodelApplicationModeCharacteristics.qll
java/ql/src/Telemetry/AutomodelApplicationModeExtractCandidates.ql
java/ql/src/Telemetry/AutomodelFrameworkModeCharacteristics.qll
java/ql/src/Telemetry/AutomodelFrameworkModeExtractCandidates.ql
java/ql/src/Telemetry/AutomodelSharedCharacteristics.qll

Excludes candidates for `Argument[this]` where we already have a model that covers a different argument of the containing call.

Java: Exclude qualifier argument for existing models

---

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp

This may be related to the discussion we had [here](https://github.com/github/codeql/pull/13792#issuecomment-1647460792).

C++: Add `cpp/invalid-pointer-deref` false negative

---

swift/ql/lib/change-notes/2023-07-24-forced-unwrap.md
swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPublic.qll
swift/ql/test/library-tests/dataflow/dataflow/CONSISTENCY/CfgConsistency.expected
swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/FlowConfig.qll
swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/test.swift
swift/ql/test/library-tests/dataflow/taint/core/Taint.expected
swift/ql/test/query-tests/Security/CWE-079/UnsafeWebViewFetch.expected

We have `EnumContent` in Swift dataflow now.  It's not supported in models-as-data.  This PR addresses this, and also adds proper flow through `!` for unwrapping optional content (which is a kind of `EnumContent`).
The latter part may well affect other tests I haven't run locally so I'm relying on the PR checks to catch that.  I also will do a DCA run once the tests are passing.

Swift: Support EnumContent in models-as-data

---

swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Sequence.qll
swift/ql/test/library-tests/dataflow/taint/libraries/string.swift

Use enum content in `withContiguousStorageIfAvailable` model.  This (and similar models to come) was the motivation for https://github.com/github/codeql/pull/13795/ , but could not be done in https://github.com/github/codeql/pull/12416/ as that was not available then.

Swift: Use enum content in withContiguousStorageIfAvailable model.

---

java/ql/consistency-queries/diags.ql
java/ql/lib/change-notes/2023-07-14-getCompilationInfo.md
java/ql/lib/semmle/code/java/Diagnostics.qll

Diagnostics can be easier to read if you see them in the order in which they were generated. By selecting the compilation and indexes, they get sorted by the testsuite driver.
`d.getCompilationInfo(c, f, i)` would be a bit more natural as `d = c.getDiagnostic(f, i)`, but currently we don't import Diagnostic into the default ('import java') namespace, and I don't think it's worth changing that for this.

Java: Improve the diagnostics consistency query

---

csharp/ql/integration-tests/all-platforms/dotnet_no_args_inject/Program.cs
csharp/ql/integration-tests/all-platforms/dotnet_no_args_inject/dotnet_build.csproj
csharp/ql/integration-tests/all-platforms/dotnet_no_args_inject/test.py
csharp/tools/tracing-config.lua

**Summary**
This PR modifies the tracer configuration for C# to limit when strings that look like `dotnet` sub-command names cause extra arguments to be injected into the command.
**What problem does this solve?**
The goal of the tracer configuration is to detect calls to `dotnet build` and other similar sub-commands and inject additional arguments to the call that we require for the C# extractor to work correctly. However, the implementation of this detection is over-eager and will also erroneously detect e.g. `dotnet new solution --name build` and inject the extra arguments, which is not valid here. 
**How does this fix it?**
- We introduce a new variable `inSubCommandPosition`, which is initially `true`. 
- We only check for sub-command names like `build` that should trigger injection …

C#: Limit detection of sub-command names in tracer configuration

---

java/ql/src/Telemetry/AutomodelApplicationModeCharacteristics.qll
java/ql/src/Telemetry/AutomodelFrameworkModeCharacteristics.qll

The problem was that endpoints that are modeled as both sinks, as well as _not a summary_ were treated as erroneous. In fact, this is not a contradiction at all.

Java: Automodel Fix, Prevent Some Erroneous Endpoints

---

go/ql/test/query-tests/Diagnostics/CONSISTENCY/UnexpectedFrontendErrors.expected
go/ql/test/query-tests/Diagnostics/ExtractionErrors.expected

The output of the Go compiler has changed between Go 1.20.5 and Go 1.20.6, making some tests fail. I manually verified this by downloading 1.20.5 and comparing the output.

Go: Compiler error messages changed in Go 1.20.6

---

java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll
java/ql/test/library-tests/dataflow/field-value/A.java
java/ql/test/library-tests/dataflow/field-value/test.expected
java/ql/test/library-tests/dataflow/field-value/test.ql
java/ql/test/library-tests/dataflow/partial/test.expected
java/ql/test/library-tests/dataflow/partial/testRev.expected

Sometimes, directly tainting `FieldValueNodes` of non-static fields is useful (e.g. sources). With this change, we allow flow out of them even if their field isn't static.

Java: Allow flow out of FieldValueNodes for non-static fields

---

java/kotlin-extractor/src/main/kotlin/utils/Logger.kt

We were escaping '/', but I don't think there is any need to do so. It just happens to have a nice escape in the spec. Escaping it made filenames annoying to work with.
I've also added escaping for the other control characters that we're meant to escape.

Kotlin: Tweak our JSON escaping

---

docs/codeql/writing-codeql-queries/catch-the-fire-starter.rst
docs/codeql/writing-codeql-queries/crown-the-rightful-heir.rst
docs/codeql/writing-codeql-queries/find-the-thief.rst

Minor fix to the indentation in the answers to some of the QL tutorials! 📝
For example, the current unindented answers on https://codeql.github.com/docs/writing-codeql-queries/crown-the-rightful-heir/#exercise-2 are difficult to read 📖

Docs: Fix indentation in tutorial examples

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlow.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlow.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlow.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlow.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlow.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlow.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlow.qll

`MergePathGraph3::PathGraph` wasn't compatible with `MergePathGraph3::PathNode`. This created a problem when making a `MergePathGraph3` of a `MergePathGraph3`, for example.

Dataflow: MergePathGraph3 signature fix

---

java/ql/src/Telemetry/AutomodelFrameworkModeCharacteristics.qll

1. There was an unintended limitation to only consider `ExplicitParameterNode`s in framework mode, but skipped the `this` parameter. This PR fixes the problem. I'll add a test case to the currently open [test PR](https://github.com/github/codeql/pull/13788) once this is merged.
2. In framework mode we also skipped the parameters of interface methods without bodies — this PR fixes the problem as well. However, I'm not 100% sure this is the best way to fix this (it might have unintended consequences) and would appreciate thoughts from the Java team. We could, for instance, try to keep our changes to the `DataFlow::ParameterNode` types local to the automodel code (if needed).

Java: Support Argument[this] and parameters of bodiless interface methods in framework mode metadata extraction

---

go/ql/test/query-tests/Diagnostics/CONSISTENCY/UnexpectedFrontendErrors.expected
go/ql/test/query-tests/Diagnostics/ExtractionErrors.expected

This is a backport of https://github.com/github/codeql/pull/13824.

Backport: Compiler error messages changed in Go 1.20.6

---

cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/InvalidPointerToDereference.qll
cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/RangeAnalysisUtil.qll
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp

The FN added in https://github.com/github/codeql/pull/13815 demonstrates that the changes in https://github.com/github/codeql/pull/13792 was not the way to go. This PR reverts that PR. I have another PR ready locally that fixes the FPs that were also fixed by this now-reverted PR which I'll open once this has been merged.
cc @jketema.

C++: Revert #13792

---

java/ql/lib/change-notes/2023-07-19-inputstream-wrapper-steps.md
java/ql/lib/semmle/code/java/JDK.qll
java/ql/lib/semmle/code/java/dataflow/FlowSteps.qll
java/ql/lib/semmle/code/java/dataflow/RangeAnalysis.qll
java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
java/ql/lib/semmle/code/java/dispatch/VirtualDispatch.qll
java/ql/lib/semmle/code/java/frameworks/InputStream.qll
java/ql/lib/semmle/code/java/frameworks/javaee/ejb/EJBRestrictions.qll
java/ql/lib/semmle/code/java/frameworks/spring/SpringController.qll
java/ql/test/library-tests/dataflow/stream-read/A.java
java/ql/test/library-tests/dataflow/stream-read/test.expected
java/ql/test/library-tests/dataflow/stream-read/test.ql

Adds taint steps for two situations:
* When an anonymous instantiation of `InputStream` is tainted by a variable captured in its `read(bytes[])` (and similar) methods, e.g.
```java
InputStream in = source();
InputStream wrapper = new InputStream() {
@Override
public int read() throws IOException {
return 0;
}
@Override
public int read(byte[] b) throws IOException {
return in.read(b);
}
};
sink(wrapper);
```
* When a subtype of `InputStream` is instantiated with a tainted `InputStream` that gets assigned to a class field, e.g.
```java
static class MyStream extends InputStream {
private InputStream wrapped;
MyStream(InputStream wrapped) {
this.wrapped = wrapped;
}
@Override
public int read() throws IOException {
return 0;
}
@Override
public int read(byte[] b) throws IOException {
return …
```

Java: Add taint steps for InputStream wrappers

---

swift/ql/lib/change-notes/2023-07-17-nsuseractivity-referrer-url.md
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/CustomUrlSchemes.qll
swift/ql/test/library-tests/dataflow/flowsources/CONSISTENCY/CfgConsistency.expected
swift/ql/test/library-tests/dataflow/flowsources/FlowSourcesInline.ql
swift/ql/test/library-tests/dataflow/flowsources/customurlschemes.swift

Add tests for the `TaintInheritingContent` defined in `CustomUrlSchemes.qll`.
Add one case I think was missing - [`NSUserActivity.referrerURL`](https://developer.apple.com/documentation/foundation/nsuseractivity/2875762-referrerurl).  @atorralba do you agree with this change or was it left our for a reason?
More significantly, these tests draw attention to the fact we don't model Swift `Set`s properly yet.  This will probably come after array and dictionary improvements but we need to get around to it.

Swift: CustomUrlSchemes test enhancements and minor model improvement

---

java/ql/lib/semmle/code/java/security/MaybeBrokenCryptoAlgorithmQuery.qll
java/ql/src/change-notes/2023-08-01-maybebrokencrypto-barrier.md

The current barrier was phrased negatively, so it was catching and blocking all sorts of nodes - in particular it was effectively disabling field flow, which in the context of https://github.com/github/codeql/pull/13478 also means disabling capture flow. This seems unintentional, and I hope we can achieve most of the intended effect with a less restrictive and positively phrased barrier that similarly blocks flow through very generic code without getting into performance trouble.

Java: Make the barrier in java/potentially-weak-cryptographic-algorithm less restrictive

---

docs/codeql/reusables/supported-frameworks.rst

Part of: https://github.com/github/docs-content/issues/10115
Updates the supported frameworks for Java to add Project Lombok. 
Question for technical reviewers - I guessed at the category to be "Utility library" but let me know if it should be something else!

Update supported frameworks

---

go/ql/lib/semmle/go/dataflow/internal/DataFlowDispatch.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll

Try to also deal with the case that we are calling a function through a variable that it has been assigned to.

Go: Avoid using getTarget() as it may not exist

---

docs/codeql/codeql-language-guides/customizing-library-models-for-javascript.rst
javascript/ql/lib/semmle/javascript/frameworks/Vue.qll
javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll
javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll
javascript/ql/test/library-tests/frameworks/data/test.expected
javascript/ql/test/library-tests/frameworks/data/test.js
javascript/ql/test/library-tests/frameworks/data/test.ql
python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModels.qll
python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModelsSpecific.qll
python/ql/test/library-tests/frameworks/data/test.expected
python/ql/test/library-tests/frameworks/data/test.py
python/ql/test/library-tests/frameworks/data/test.ql
ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModels.qll
ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModelsSpecific.qll
ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql
ruby/ql/test/library-tests/dataflow/summaries/summaries.rb

Adds a `Fuzzy` token to the identifying access path for all dynamic languages, which will match, loosely speaking, an arbitrary series of operations.
For example, suppose we wanted to add a SQL injection sink for the `query` method in the `mysql` package, but we don't have a detailed enough knowledge of the library to do this precisely. So we just write the model like this:
```
mysql; Fuzzy.Member[query].Argument[0]; sql-injection
```
This would match all `query` calls whose receiver is an object that appears to come from the `mysql` package. The latter criterion comes from "tracking through an arbitrary series of operations".
This can serve as a foundation for a dedicated extension point for fuzzy models. An entry in such a fuzzy model might simply look like:
```
mysql; query; …
```

Dynamic: add Fuzzy token

---

javascript/ql/src/Security/CWE-730/ServerCrash.qhelp
javascript/ql/src/Security/CWE-730/examples/server-crash.BAD.js
javascript/ql/src/Security/CWE-730/examples/server-crash.GOOD-A.js
javascript/ql/src/Security/CWE-730/examples/server-crash.GOOD-B.js

The examples now use `fs.access` instead of the deprecated `fs.exists`. I have also rewritten the async/await example, since as of Node.js v15 the default behaviour for uncaught exceptions has changed to terminating the process instead of logging a warning, making the previous advice incorrect.

JavaScript: Improve qhelp for js/server-crash.

---

go/ql/lib/change-notes/2023-07-28-logrus-with-context.md
go/ql/lib/semmle/go/frameworks/Logrus.qll
go/ql/test/library-tests/semmle/go/concepts/LoggerCall/logrus.go

This isn't output by the default formatters (though a custom formatter could potentially output things stored in it)
Fixes https://github.com/github/codeql/issues/13828

Don't treat logrus' WithContext method as a logging function

---

cpp/ql/src/Critical/UseAfterFree.cpp

* Remove the mismatch between `new` and `free` and use `delete` instead
* Make the function `void`, so people copying the code will not forget to add a `return`.
* Balance out the `...` for omitted code.
This was flagged up by a user on the GHSL slack.

C++: Improve use-after-free example code

---

swift/ql/lib/codeql/swift/frameworks/StandardLibrary/CustomUrlSchemes.qll

Reverts github/codeql#13757 since the underlying issue appears to have been fixed.

Revert "Swift: Pragmatic fix for CustomUrlSchemes.qll."

---

java/ql/lib/ext/threatmodels/supported-threat-models.model.yml
java/ql/lib/ext/threatmodels/threat-model-grouping.model.yml
java/ql/lib/qlpack.yml
java/ql/lib/semmle/code/java/dataflow/ExternalFlowConfiguration.qll
java/ql/test/library-tests/dataflow/threat-models/Empty.java
java/ql/test/library-tests/dataflow/threat-models/threat-models1.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models1.ql
java/ql/test/library-tests/dataflow/threat-models/threat-models2.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models2.ext.yml
java/ql/test/library-tests/dataflow/threat-models/threat-models2.ql

This PR covers the very initial work on supported threat models as describes in: https://github.com/github/code-scanning/pull/10356
In this PR we introduce some of the extensible predicates (and small helper predicates) needed to *glue* together the work made by CodeQL Experiences team and the CodeQL static languages teams.
The CodeQL experiences team will work on populating the extensible `supportedThreatModel` predicate with tuples via the workflow configuration.
The CodeQL static languages team will work on incorporating the support threat models into the existing framework (and some queries).
Even though the code is *dead* as it is now, it would be good to have it merged to allow CodeQL experiences and the CodeQL static team to work in parallel.
For now we just add some basic testing …

Java: Threat Models

---

java/ql/lib/change-notes/2023-08-07-randomdatasource-typo-fix.md
java/ql/lib/semmle/code/java/security/RandomDataSource.qll

In `RandomDataSource.qll`, `StdlibRandomSource::getOutput` contains a typo which makes queries relying on `StdlibRandomSource` improperly model calls to `java.util.Random#nextBytes`. This fixes the typo to the correct method name.

Java: Fix typo in `StdlibRandomSource::getOutput`

---

java/ql/lib/ext/java.nio.file.model.yml

This PR removes some duplicated MaD models.
The `move`, `delete`, and `newOutputStream` duplicates were added in [#12366](https://github.com/github/codeql/pull/12366/files#diff-86d04a6763c9430c278a1ecbbb6b6d61b682456dbf7773b939876ce1a5ea803e). 
The `newInputStream` duplicate was added in [#12727](https://github.com/github/codeql/pull/12727/files#diff-86d04a6763c9430c278a1ecbbb6b6d61b682456dbf7773b939876ce1a5ea803e).
The `deleteIfExists` duplicate was added in [#12691](https://github.com/github/codeql/pull/12691/files#diff-86d04a6763c9430c278a1ecbbb6b6d61b682456dbf7773b939876ce1a5ea803e).
Since these are older ai models, I believe whatever caused the duplication has already been fixed, but cc @kaeluka @jhelie in case you think the cause for this needs to be investigated further.

Java: remove duplicate models

---

java/ql/src/Telemetry/AutomodelApplicationModeExtractCandidates.ql
java/ql/src/Telemetry/AutomodelCandidateFilter.yml
java/ql/src/Telemetry/AutomodelFrameworkModeExtractCandidates.ql
java/ql/src/Telemetry/AutomodelJavaUtil.qll
java/ql/src/qlpack.yml

This is a first tak at how to add runtime filtering to the automodel candidate queries. I am not super up to speed in CodeQL so feedback is welcome.
This is used by the data extension as seen here: https://github.com/github/vscode-codeql/pull/2670

Add option to filter automodel queries

---

misc/scripts/accept-expected-changes-from-ci.py

I guess there has been a rename of the URL from `/jobs/` to `/job/`, since the script has been working previously.

Misc: Fixup `accept-expected-changes-from-ci.py`

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll

This PR fixes the taint-regressions surfaced by the upgrade of the C/C++ frontend [here](https://github.com/github/codeql/pull/13716). It should be safe to merge this PR before merging https://github.com/github/codeql/pull/13716.

C++: Fix taint-flow in preparation for frontend upgrade

---

csharp/ql/lib/semmle/code/csharp/Stmt.qll

Before
```
Evaluated recursive predicate Stmt#3baf294a::TryStmt::getATriedElement#ff@8254eapb in 6096ms on iteration 4 (delta size: 592145).
Evaluated relational algebra for predicate Stmt#3baf294a::TryStmt::getATriedElement#ff@8254eapb on iteration 4 running pipeline standard with tuple counts:
204507  ~0%    {2} r1 = SCAN Stmt#3baf294a::TryStmt::getATriedElement#ff#prev_delta OUTPUT In.1, In.0
204507  ~0%    {3} r2 = JOIN r1 WITH _@callable#f_ControlFlowElement#9501aa28::ControlFlowElement::getEnclosingCallable#0#dispred#ff_10#j__#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Lhs.1
17844283  ~0%    {3} r3 = JOIN r2 WITH ControlFlowElement#9501aa28::ControlFlowElement::getEnclosingCallable#0#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Lhs.2
592145  ~0%    {2} r4 = JOIN r3 WITH …
```

C#: Fix bad join order

---

docs/codeql/reusables/supported-frameworks.rst
swift/ql/lib/change-notes/2023-08-08-ui-text-input.md
swift/ql/lib/codeql/swift/frameworks/UIKit/UITextField.qll
swift/ql/test/library-tests/dataflow/flowsources/uikit.swift

Add flow sources for [`UITextInput`](https://developer.apple.com/documentation/uikit/uitextinput), [`UITextFieldDelegate`](https://developer.apple.com/documentation/uikit/uitextfielddelegate) and [`UITextViewDelegate`](https://developer.apple.com/documentation/uikit/uitextviewdelegate).
I've also added `UIKit` to `supported-frameworks.rst` since, I think, we now model enough of it to claim coverage (and there's likely more to come).
On the MRVA top 1000, we find 94 new taint sources - a sample of which LGTM (though only perhaps half use the data anywhere).  DCA run to follow...

Swift: Flow sources for UITextInput

---

javascript/ql/src/Security/CWE-770/examples/MissingRateLimitingGood.js

My friend likes to copy-paste the default values presented in the QHelp when he fixes an error, so I think it's best if the default values presented are reasonable.  
And we saw an example where the previous defaults were so low that a test-suite started failing, and the issue therefore took longer to fix. 
The new defaults are taken from the express-rate-limit documentation: https://github.com/express-rate-limit/express-rate-limit#examples 
My friend doesn't seem to appreciate the new QHelp, he likes it just as much as the previous one.  
But I think these new defaults are more reasonable, and less likely to cause failures if people are copy-pasting our suggested defaults.

JS: change the defaults in the qhelp for missing-rate-limit to something more reasonable

---

swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImplSpecific.qll
swift/ql/test/library-tests/dataflow/dataflow/CONSISTENCY/CfgConsistency.expected
swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/FlowConfig.qll
swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/test.swift

I noticed we were missing models-as-data syntax for tuple content.  This isn't actually used in any models yet (outside of the test), but it seems good to fill the gap.

Swift: Models-as-data support for tuple content

---

go/ql/test/query-tests/RedundantCode/CompareIdenticalValues/constants.go

The `constants.go` file has a build tag which means that it doesn't get compiled on `arm64` and therefore the `ptrsize` constant is undefined in `tst.go`, causing the consistency test to fail.
This PR updates the build tags for `constants.go` so that it gets included on `arm64` as well.

Make `CompareIdenticalValues` test work on arm64

---

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt

They were being stringified into `null` strings before. Now we check for nullness, and return null if appropriate.

Kotlin: Handle null parent IDs in getFunctionLabel correctly

---

csharp/extractor/Semmle.Extraction.CSharp.Standalone/BuildAnalysis.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/DotNet.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/ProgressMonitor.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/Runtime.cs
csharp/extractor/Semmle.Extraction.Tests/Runtime.cs

In this PR we
- Fix an issue with the path detection for .NET runtimes used in the *standalone* extractor (I made a mistake in the orignal regular expression for matching paths, such that paths with whitespaces would not be matched correctly).
- Added a bit of extra logging information.
- Minor re-factor of the `ProgressMonitor`.

C#: .NET Runtime path detection (bugfix).

---

python/ql/lib/analysis/DefinitionTracking.qll
python/ql/lib/change-notes/2023-08-10-fix-alias-locations.md
python/ql/test/library-tests/locations/imports/import_statements.py
python/ql/test/library-tests/locations/imports/imports.expected
python/ql/test/library-tests/locations/imports/imports.ql

The computation of nice location for import statements did not take aliases into account.
This has causes problems for some of our downstream CI.
See also https://github.com/github/codeql-team/issues/2260

Python: fix nice locations for import aliases

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
ruby/ql/test/library-tests/dataflow/array-flow/type-tracking-array-flow.expected

Extracted from https://github.com/github/codeql/pull/11725. Aligns Ruby with how JavaScript handles captured variables in type tracking.

Ruby: Make type tracking flow-insensitive for captured variables

---

docs/codeql/ql-language-reference/ql-language-specification.rst

Fixes https://github.com/github/codeql-core/issues/3783.

QL language specs: declarations can shadow dbscheme types and preds

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp

This PR implements two dataflow improvements. The combination of the two effects means we won't have new FPs on the `cpp/invalid-pointer-deref` after the frontend upgrade that @jketema is working on.
- The first commit improves out detection of which writes are considered "certain" (i.e., which completely overwrites an allocation) by using value numbering. Previously, we'd detect that that `x = 0` in:
```cpp
int x = source();
x = 0;
sink(x);
```
overwrites an entire allocation because it writes directly to a `VariableAddressInstruction`. Thus we wouldn't report flow from `source` to `sink`.
However, we didn't detect that in the case of `*p = 0` in:
```cpp
int x = source();
int* p = &x;
*p = 0;
sink(*p);
```
since `*p = 0` wrote to the result of a `LoadInstruction` (and not a …

C++: Remove more dataflow FPs after frontend upgrade

---

go/extractor/cli/go-autobuilder/go-autobuilder.go

We had only previously tested this with e.g. installed go 1.20.5 >= go.mod request `go 1.20`; now we have go 1.21.0 which shouldn't elicit a warning because 1.21.0 is equal to the go.mod request `go 1.21`.

Go: Don't warn when Go version exactly matches go.mod

---

cpp/autobuilder/Semmle.Autobuild.Cpp.Tests/BuildScripts.cs
csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs
csharp/autobuilder/Semmle.Autobuild.Shared/CommandBuilder.cs
csharp/ql/integration-tests/all-platforms/standalone/Files.expected
csharp/ql/integration-tests/all-platforms/standalone/Files.ql
csharp/ql/integration-tests/all-platforms/standalone/Program.cs
csharp/ql/integration-tests/all-platforms/standalone/standalone.csproj
csharp/ql/integration-tests/all-platforms/standalone/test.py

This PR adds an integration test that runs the standalone extractor. The integration test was failing on Windows with the message:
```
Initializing database at C:\a\semmle-code\semmle-code\target\codeql-csharp-integration-tests\ql\csharp\ql\integration-tests\all-platforms\standalone\test-db.
Running build command: [C:\a\semmle-code\semmle-code\target\intree\codeql  integration  tests  dist  csharp\csharp\tools\autobuild.cmd]
[2023-07-12 14:56:48] [build-stdout] CodeQL C# autobuilder
[2023-07-12 14:56:48] [build-stdout] Working directory: C:\a\semmle-code\semmle-code\target\codeql-csharp-integration-tests\ql\csharp\ql\integration-tests\all-platforms\standalone
[2023-07-12 14:56:48] [build-stdout] Running cmd.exe /C ^"C:\a\semmle-code\semmle-code\target\intree\codeql  integration  tests …
```

C#: Add integration test for standalone extraction

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisStage.qll
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/constant-size/ConstantSizeArrayOffByOne.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/constant-size/test.cpp
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/InvalidPointerDeref.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/pointer-deref/test.cpp
cpp/ql/test/library-tests/ir/range-analysis/test.cpp

I was seeing a lot of FPs related to subtraction on the `cpp/invalid-pointer-deref` query on MRVA. This turned out to be because we still inferred very imprecise ranges similar to what we removed in the case of addition [in an earlier PR](https://github.com/github/codeql/pull/12673).
This PR replaces those imprecise ranges with much more precise ranges computed by non-linear recursion.

C++: Support subtraction in the new range analysis

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisStage.qll

Was this what you had in mind @aschackmull?

C++: Fix original delta calculation for subtraction in new range analysis

---

swift/ql/test/library-tests/ast/PrintAst.expected
swift/ql/test/library-tests/controlflow/graph/Cfg.expected

I think https://github.com/github/codeql/pull/13910 and https://github.com/github/codeql/pull/13836 conflicted. This PR fixes the `.expected` files

Swift: Fix expected files after a semantic merge conflict

---

java/kotlin-extractor/src/main/kotlin/ExternalDeclExtractor.kt
java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
java/kotlin-extractor/src/main/kotlin/TrapWriter.kt
java/kotlin-extractor/src/main/kotlin/utils/ClassNames.kt
java/kotlin-extractor/src/main/kotlin/utils/ExternalDecls.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_4_32/getFileClassFqName.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_7_0/getFileClassFqName.kt

In Kotlin 2 mode, when the parent is a (multi)file class, we see the parent as just an `IrExternalPackageFragment` and have to do some extra work to extract it.

Kotlin: Handle Kotlin 2 parents better

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll

MaD for C# uses `Argument[x]` for `out/ref` returns (see `summaryPostUpdateNodeIsOutOrRef`), so this PR aligns `getMadRepresentationSpecific` with that format.

C#: Fix `getMadRepresentationSpecific`

---

java/ql/lib/semmle/code/java/dataflow/RangeAnalysis.qll

Before:
```
Evaluated recursive predicate RangeAnalysis#2dea8027::boundFlowCond#5#ffffff@cf4ddf18 in 788999ms on iteration 2 (delta size: 100).
Evaluated relational algebra for predicate RangeAnalysis#2dea8027::boundFlowCond#5#ffffff@cf4ddf18 on iteration 2 running pipeline standard with tuple counts:
301830   ~0%    {6} r1 = SCAN RangeAnalysis#2dea8027::boundFlowCond#5#ffffff#prev_delta OUTPUT In.5, In.4, In.0, In.1, In.2, In.3
12734   ~0%    {6} r2 = JOIN r1 WITH GuardsLogic#2bffeb61::implies_v2#4#ffff_2301#join_rhs ON FIRST 2 OUTPUT Rhs.2, Lhs.2, Lhs.3, Lhs.4, Lhs.5, Rhs.3
12734   ~0%    {6} r3 = JOIN r2 WITH Guards#69cd2c5b::Guard#f ON FIRST 1 OUTPUT Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5, Lhs.0
301830   ~3%    {6} r4 = SCAN RangeAnalysis#2dea8027::boundFlowCond#5#ffffff#prev_delta OUTPUT …
```

Java: Join-order fix in RangeAnalysis.

---

java/ql/lib/change-notes/2023-08-15-add-dashes-to-sha-algorithms.md
java/ql/lib/semmle/code/java/security/Encryption.qll

Update `getSecureAlgorithmName` to accommodate dashes in the name of the `SHA` algorithms.

Java: Add dashes to SHA algorithm names in `Encryption.qll`

---

java/ql/lib/semmle/code/java/regex/RegexFlowConfigs.qll

This seems to fix https://github.com/github/codeql/discussions/13752 
(Someone else confirm that?) 
Other languages already have a similar limitation in how they track regular expressions.  
[An evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-13916-0-java/reports) looks slightly weird, but I think it's good.

Java: limit field flow when tracking regex strings

---

cpp/ql/src/Security/CWE/CWE-120/BadlyBoundedWrite.ql
cpp/ql/src/change-notes/2023-08-09-badly-bounded-write.md
cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/BadlyBoundedWrite.expected
cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/tests2.cpp

A recent fix to the CodeQL evaluator broke the FP fix to `BadlyBoundedWrite` that was introduced in https://github.com/github/codeql/pull/13929. The `BadlyBoundedWrite` fix will have to be re-done in another way, but for now I'm rolling back the expected test output so we get all tests on `main` passing.
It's not obviously a good idea to delete the change note. The change may still have an effect but just not an effect that can be observed on the test case. What do you all think?

C++: Accept regression in test after evaluator fix

---

.github/workflows/go-tests-other-os.yml
.github/workflows/go-tests.yml
go/extractor/cli/go-autobuilder/go-autobuilder.go
go/go.mod
go/ql/lib/semmle/go/Scopes.qll
go/ql/lib/semmle/go/dataflow/internal/TaintTrackingUtil.qll
go/ql/lib/semmle/go/frameworks/Stdlib.qll
go/ql/test/library-tests/semmle/go/Function/TypeParamType.expected
go/ql/test/library-tests/semmle/go/dataflow/DefaultTaintSanitizer/Builtin.go
go/ql/test/library-tests/semmle/go/dataflow/DefaultTaintSanitizer/DefaultSanitizer.expected
go/ql/test/library-tests/semmle/go/dataflow/DefaultTaintSanitizer/DefaultSanitizer.ql
go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalFlowStep.expected
go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.expected
go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/main.go
go/ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.expected
go/ql/test/library-tests/semmle/go/frameworks/TaintSteps/TaintStep.ql
go/ql/test/library-tests/semmle/go/frameworks/TaintSteps/main.go

Go 1.21 was released recently. This PR updates our CI to use Go 1.21 and makes the Go extractor aware of Go 1.21. It also adds support for the new built-in functions: `min`, `max`, and `clear`.

Go: Basic Go 1.21 support

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll

https://github.com/github/codeql/pull/11725 reveals the following bad join-orders when calculating flow in
```
Evaluated relational algebra for predicate DataFlowImpl#248dabc3::MakeImpl#DataFlowImplSpecific#21008cd7::RubyDataFlow#::Impl#TaintTracking#47c9f12a::Global#StoredXSSQuery#5ea303cf::StoredXss::Config#::C#::MkStage#Stage1#::Stage#Stage2Param#::fwdFlowIn#11#fffffffffff@a0f95zb8 on iteration 108 running pipeline standard with tuple counts:
1918   ~0%    {9} r1 = SCAN DataFlowImpl#248dabc3::MakeImpl#DataFlowImplSpecific#21008cd7::RubyDataFlow#::Impl#TaintTracking#47c9f12a::Global#StoredXSSQuery#5ea303cf::StoredXss::Config#::C#::MkStage#Stage1#::Stage#Stage2Param#::fwdFlow#9#fffffffff#prev_delta OUTPUT In.0, In.8, In.1, In.2, In.3, In.4, In.5, In.6, In.7
7780921   ~0%    {11} r2 = …
```

Data flow: Earlier call-context based dispatch filtering

---

.pre-commit-config.yaml
misc/codegen/templates/trap_tags_h.mustache
swift/extractor/infra/SwiftDispatcher.h
swift/extractor/infra/SwiftLocationExtractor.cpp
swift/extractor/infra/SwiftLocationExtractor.h
swift/extractor/print_unextracted/main.cpp
swift/extractor/translators/TranslatorBase.h
swift/extractor/trap/TrapLabel.h

This simplifies several instances of metaprogramming by leveraging [constraints and concepts from C++20][1]. This:
* gets rid of `std::enable_if` by usage of `requires`, making it more readable and yield better compiler messages.
* uses `requires` instead of `static_assert` to enforce `TrapLabel` typing
* _greatly_ simplifies all compile-time tests for validity of a given expression, by use of simple `requires` constraints
* uses some standard library concepts where possible
* generalizes and simplifies `SwiftLocationExtractor`
Notice that in order to use the `std::derived_from` concept, `virtual` inheritance had to be added to the label tags, because diamond inheritance is a problem otherwise. That's because `std::derived_from<T, U>` requires that `T*` be convertible to `U*`, which is …

Swift: use C++20 constraints and concepts to simplify code

---

misc/codegen/templates/trap_tags_h.mustache
swift/extractor/infra/SwiftDispatcher.h
swift/extractor/infra/SwiftLocationExtractor.cpp
swift/extractor/infra/SwiftLocationExtractor.h
swift/extractor/print_unextracted/main.cpp
swift/extractor/translators/TranslatorBase.h
swift/extractor/trap/TrapLabel.h

Reverts github/codeql#13991
Unfortunately, it seems the `<concepts>` library is not available on macOS 11. For the moment it's best to revert this.

Revert "Swift: use C++20 constraints and concepts to simplify code"

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll
csharp/ql/test/library-tests/dataflow/library/FlowSummaries.ql
csharp/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.cs
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll
java/ql/lib/semmle/code/java/dataflow/FlowSummary.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowDispatch.qll
java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImplSpecific.qll
java/ql/src/Metrics/Summaries/GeneratedVsManualCoverageQuery.qll
java/ql/src/Metrics/Summaries/TopJdkApis.qll
java/ql/src/Telemetry/ExternalApi.qll
java/ql/test/ext/TopJdkApis/TopJdkApisTest.ql
java/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.expected
java/ql/test/query-tests/Telemetry/SupportedExternalApis/SupportedExternalApis.java
java/ql/test/query-tests/Telemetry/UnsupportedExternalAPIs/Test.java
python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImplSpecific.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImplSpecific.qll

The telemetry queries (`*/telemetry/supported-external-api` and `*/telemetry/unsupported-external-api` for java and C#) used for reporting the usage of third party APIs (or missing modeling of third party APIs) are based on the `isSupported()` predicate below (from `ExternalApi.qll`).
```codeql
/** Holds if this API is a known neutral. */
pragma[nomagic]
predicate isNeutral() { this instanceof FlowSummaryImpl::Public::NeutralCallable }
/**
* Holds if this API is supported by existing CodeQL libraries, that is, it is either a
* recognized source, sink or neutral or it has a flow summary.
*/
predicate isSupported() {
this.hasSummary() or this.isSource() or this.isSink() or this.isNeutral()
}
```
That is, we think of an API as being supported if there exist *any* model for the API. However, …

Java/C#: Update telemetry queries to report callables with sink/source neutrals as being supported.

---

java/ql/lib/change-notes/2023-08-21-java-command-injection-sanitizer.md
java/ql/lib/semmle/code/java/security/CommandLineQuery.qll

Similar to the [sql injection query](https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/security/SqlInjectionQuery.qll#L25), a numeric sanitizer seems to make sense here

Java: add sanitizer to command injection query

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
ruby/ql/test/library-tests/dataflow/params/TypeTracker.expected
ruby/ql/test/library-tests/dataflow/params/TypeTracker.qlref

Whilst reviewing https://github.com/github/codeql/pull/13938, it occurred to me that we don't include the read/store steps used to model flow into (hash) splat parameters in type tracking. This PR does that, but a bit differently, as we use type tracking's ability to define read-store steps, to avoid having `SynthSplatParameterElementNode`s be `LocalSourceNode`s.

Ruby: Include more (hash) splat flow in type tracking

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FileContent.cs
csharp/extractor/Semmle.Extraction.Tests/FileContent.cs

The computation of `NotYetDownloadedPackages` needs to be delayed after we have tried to download packages through sln and csproj files. This PR makes `NotYetDownloadedPackages` lazy.

C#: Fix lazy evaluation of not yet downloaded packages

---

javascript/ql/lib/semmle/javascript/Paths.qll
javascript/ql/src/change-notes/2023-08-23-import-path-string.md
javascript/ql/test/library-tests/Modules/import-indirect-path.js
javascript/ql/test/library-tests/Modules/tests.expected

Use more data flow during path resolution, so we can resolve imports like
```js
var x = __dirname;
var y = '/a';
require(x + y);
```

JS: Follow immediate predecessors in path resolution

---

cpp/ql/src/Security/CWE/CWE-089/SqlTainted.ql
cpp/ql/test/query-tests/Security/CWE/CWE-089/SqlTainted/SqlTainted.expected

This converts away from `DefaultTaintTracking` towards the newer API.
This does end up with some changes I noticed:
- `argv` is repeated multiple times. This is at often 3 times (argv, *argv, **argv)  + sometimes more (sometimes there seems multiple versions of some indirections?).
- The alert location moves from the `argv` use to the `argv` argument. 
I'm not sure about `node.asConvertedExpr()` vs `asExpr` for the sink. The issue with using `asExpr` is that multiple levels of conversions are reachable without going through each over due to the references. So having fewer possible sinks seems better.
I tried setting `ArgvSource` to use `this.asParameter(2)` instead of `this.asParameter(_)` and it seems to fix these issues, but I am not sure of the consequences.

CPP: Convert SQL tainted away from away from DefaultTaintTracking.

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

Needed to get acceptable performance when doing flow through captured variables in Ruby (https://github.com/github/codeql/pull/11725).

Data flow: Use call contexts in stage 3

---

shared/regex/codeql/regex/nfa/NfaUtils.qll

Fixes a performance problem in a Python project, and seems to have no change in results🤞
Evaluations: [Python](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-14027-2-python/reports), [Ruby](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-14027-3-ruby/reports), [Java](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-14027-0-java/reports), [JavaScript](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-14027-1-javascript/reports). 
Only a single lost result in the Ruby evaluation, but I think we can live with that. 
Otherwise seemingly no change, just some DCA noise.

ReDoS: limit concretize to strings of at most length 100

---

java/ql/lib/change-notes/2023-08-07-jaxrs-webmethod-improvements.md
java/ql/lib/semmle/code/java/frameworks/JaxWS.qll
java/ql/test/library-tests/frameworks/JaxWs/JaxWsEndpoint.java
java/ql/test/stubs/jaxws-api-2.0/javax/xml/bind/annotation/adapters/XmlJavaTypeAdapter.java

`JaxWsEndpoint::getARemoteMethod` required its methods to be annotated with `@WebMethod` or `@WebEndpoint` to be considered sources. This is inconsistent with certain implementations of JAX-RS (like Apache CXF), where `@WebService` methods are still externally accessible if their parameter and return types meet certain conditions. This PR expands our support of JAX-RS to include this.
The logic for acceptable types was obtained from the [JAX-RPC Specification 1.1](https://download.oracle.com/otn-pub/jcp/7228-jaxrpc-1.1-mrd-spec-oth-JSpec/jaxrpc-1_1-mrd-spec.pdf).

Java: Improve `JaxWsEndpoint::getARemoteMethod`

---

java/ql/test/library-tests/dataflow/capture/B.java
shared/dataflow/codeql/dataflow/VariableCapture.qll

When a variable refers to a closure, we emulate what would happen if that closure had been inlined at that point.
```
var x
fun one() {
use x;
}
fun two() {
one() // if 'one' was to be inlined here, then 'two' would also capture 'x'
}
```

Variable capture: synchronize with aliases in nested scopes

---

cpp/ql/src/Likely Bugs/Format/NonConstantFormat.ql
cpp/ql/src/change-notes/2023-08-24-remove-non-constant-assign-sources.md

Running the following on ~1000~ 996 MRVA projects gave 1 result:
```ql
from FormattingFunctionCall call, Expr formatString
where
call.getArgument(call.getFormatParameterIndex()) = formatString and
not exists(DataFlow::Node sink |
B::NonConstFlow::flowTo(sink) and
B::isSinkImpl(sink, formatString)
)
and
exists(DataFlow::Node sink |
A::NonConstFlow::flowTo(sink) and
A::isSinkImpl(sink, formatString)
)
select formatString,
"The format string argument to " + call.getTarget().getName() +
" should be constant to prevent security issues and other potential errors."
```
Where both A and B are modules that both contain all the non-constant format code, except that B omits the  lines also omitted in this PR. The one result comes from [here](https://github.com/cyberbotics/webots/blob/8aba6eaae76989fa …

C++: Omit assign case from `cpp/non-constant-format`

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/AssemblyCache.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/AssemblyInfo.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs

Nuget packages often contain multiple DLLs that target different .NET frameworks. With this PR, the standalone extractor will always choose the DLL that targets the most recent .NET Core version.

C#: Favor DLLs with most recent .NET Core target framework when resolving dependencies in standalone

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

Before
```
Evaluated relational algebra for predicate DataFlowImpl#248dabc3::MakeImpl#DataFlowImplSpecific#21008cd7::RubyDataFlow#::Impl#DataFlow#167ac380::DataFlowMake#DataFlowImplSpecific#21008cd7::RubyDataFlow#::Global#XSS#e59174e9::OrmTracking::Config#::C#::MkStage#Stage2#::Stage#Stage3Param#::flowThroughIntoCall#6#ffffff@0ea4e2mt with tuple counts:
1065437   ~0%    {4} r1 = SCAN project#DataFlowImpl#248dabc3::MakeImpl#DataFlowImplSpecific#21008cd7::RubyDataFlow#::Impl#DataFlow#167ac380::DataFlowMake#DataFlowImplSpecific#21008cd7::RubyDataFlow#::Global#XSS#e59174e9::OrmTracking::Config#::C#::MkStage#Stage2#::Stage#Stage3Param#::fwdFlow#9#fffffffff#2 OUTPUT In.0, In.3, In.1, In.2
1158508760   ~0%    {6} r2 = JOIN r1 WITH project#DataFlowImpl#248dabc3::MakeImpl#DataFlowImplSpecific#21008 …
```

Data flow: Fix a bad join order

---

swift/extractor/invocation/SwiftDiagnosticsConsumer.cpp
swift/extractor/invocation/SwiftDiagnosticsConsumer.h
swift/extractor/main.cpp

Fixed version of https://github.com/github/codeql/pull/13869, which was reverted in https://github.com/github/codeql/pull/13917.

Swift: Route compiler diagnostics through our log.

---

cpp/ql/lib/change-notes/2023-08-24-no-taint-argv-indirections.md
cpp/ql/lib/semmle/code/cpp/security/FlowSources.qll
cpp/ql/src/change-notes/2023-08-24-no-taint-argv-indirections.md
cpp/ql/src/experimental/Security/CWE/CWE-078/WordexpTainted.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-078/WordexpTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-022/semmle/tests/TaintedPath.expected
cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-089/SqlTainted/SqlTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowDestination.expected
cpp/ql/test/query-tests/Security/CWE/CWE-129/semmle/ImproperArrayIndexValidation/ImproperArrayIndexValidation.expected
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected
cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextBufferWrite.expected

Rather than considering all indirections of `argv` as tainted,  this only considers the actual arguments to be tainted. This reduces duplicate results where we had a source for each level of indirection.
There are lots of changes to the numbers of results but not changes to which databases have results. I tested some of the largest changes to see that the set of alert locations is identical and it was (but I can't think of an easy way to test on a larger scale).
I had to fix `cpp/wordexp-injection` injection as it reported if the argument was tainted rather than an indirection of it so it stopped reporting any results.

CPP:Only taint argv indirections

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FileContent.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FileInfoExtensions.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/ProgressMonitor.cs
csharp/extractor/Semmle.Extraction.Tests/FileContent.cs

In this PR we restrict the files that is scanned for packages references and ASP.NET framework dependency to files smaller than 1 MB. Furthermore, we fetch the source dir file info fewer times.
On my machine this had a positive performance impact, especially when source directory contains compressed files and large log files.

C#: Improve GetFiles in the Dependency Manager.

---

csharp/autobuilder/Semmle.Autobuild.Shared/BuildActions.cs
csharp/autobuilder/Semmle.Autobuild.Shared/MsBuildRule.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/NugetPackages.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/ProgressMonitor.cs
csharp/extractor/Semmle.Util/FileUtils.cs

In this PR we improve the *dependency manager*, such that `nuget.exe` is downloaded if it is not found.
The change has been manually tested on the GitHub repo `FluentValidation/FluentValidation`. This repo contains a `packages.config` file and the nuget package dependencies listed here are downloaded to the temporary package folder after the download of `nuget.exe`.

C#: Download `nuget.exe` in the dependency manager (if not present).

---

cpp/ql/lib/change-notes/2023-08-25-delete-or-delete-array.md
cpp/ql/lib/change-notes/2023-08-25-getAllocatorCall-deprecated.md
cpp/ql/lib/semmle/code/cpp/PrintAST.qll
cpp/ql/lib/semmle/code/cpp/controlflow/internal/CFG.qll
cpp/ql/lib/semmle/code/cpp/exprs/Expr.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedElement.qll
cpp/ql/src/Security/CWE/CWE-570/IncorrectAllocationErrorHandling.ql
cpp/ql/test/library-tests/allocators/allocators.expected
cpp/ql/test/library-tests/allocators/allocators.ql
cpp/ql/test/library-tests/ir/ir/PrintAST.expected

This adds a parent to `delete` and `delete[]` so that they can be handled together. This also renames `getAllocatorCall` into `getDeallocatorCall` and fixes some incorrect documentation.
I split this out of the IR work.

CPP: Add parent class for delete and delete[]

---

csharp/ql/src/Concurrency/UnsynchronizedStaticAccess.qhelp

There was a rogue `U+200B` character that was rendering as mojibake:
Also update the MSDN link in this documentation to avoid an unnecessary redirection and use the correct anchor.

Delete thin space from documentation

---

swift/ql/src/queries/Security/CWE-328/WeakSensitiveDataHashing.qhelp
swift/ql/src/queries/Security/CWE-328/WeakSensitiveDataHashingBad.swift
swift/ql/src/queries/Security/CWE-328/WeakSensitiveDataHashingGood.swift

Update the weak sensitive data hashing examples and qhelp to:
1. encourage use of message authentication algorithms where appropriate (for passwords, computationally expensive hashes are already recommended) and
2. not provide an example that uses a SHA-512 hash on a 'certificate'
---
@aegilops (who first pointed out the problem)
@d10c (who is following this issue)
I'm open to suggestions and corrections - I'm only moderately informed on this subject - after which I will request a docs review on the changes as well.
In the longer term, we have plans to implement a Swift version of [`csharp/weak-password-hashing`](https://github.com/advanced-security/codeql-queries/blob/main/csharp/CWE-328/WeakPasswordHashing.ql), which will provide a  much stronger push towards safe password hashing and …

Swift: Update the weak sensitive data hashing examples and qhelp

---

csharp/ql/lib/semmle/code/csharp/Unification.qll
csharp/ql/lib/semmle/code/csharp/commons/Assertions.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
csharp/ql/lib/semmle/code/csharp/dispatch/Dispatch.qll
shared/controlflow/codeql/controlflow/Cfg.qll

Commit-by-commit review is encouraged. These performance fixes make no difference on the projects we have in DCA, but they make a big difference on a particular customer database (see tuple counts in commit messages).

C#: Various performance fixes

---

csharp/ql/lib/semmle/code/cil/Stubs.qll

Avoids an expensive anti-join:
```
[2023-08-29 15:25:48] Evaluated non-recursive predicate _FileSystem#df18ed9a::Make#File#1a556f64::Input#::Container::toString#0#dispred#bf_Method#621e9e2e::__#antijoin_rhs@96d08bc8 in 272332ms (size: 1841891).
Evaluated relational algebra for predicate _FileSystem#df18ed9a::Make#File#1a556f64::Input#::Container::toString#0#dispred#bf_Method#621e9e2e::__#antijoin_rhs@96d08bc8 with tuple counts:
4632443     ~2%    {3} r1 = JOIN _cil_instruction_3#antijoin_rhs_cil_method_implementation#shared WITH cil_method_implementation ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Lhs.1
71945701     ~3%    {3} r2 = JOIN r1 WITH cil_method_implementation_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2
71945701  ~1329%    {3} r3 = JOIN r2 WITH …
```

C#: Speedup `bestImplementation`

---

ruby/ql/lib/codeql/ruby/controlflow/ControlFlowGraph.qll
ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImpl.qll

No longer needed, as `for` loops are desugared into `each` calls.

Ruby: Get rid of unused `EmptinessSuccessor`

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll

This _should_ be identical to the branch [here](https://github.com/github/codeql/blob/main/cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll#L32) (which has a `true` in this case).
I haven't been able to construct a meaningful testcase where this makes a difference right now, but once I open the final PR for deduplicating dataflow results this is required.
The semantics of this change is that it'll make more things an SSA use: Previously, no SSA definitions were considered a use of the underlying SSA variable. After this change, non-certain SSA definitions are also considered uses.

C++: Non-certain definitions should always be uses

---

python/ql/lib/change-notes/2023-07-20-shlex-quote-sanitizer.md
python/ql/lib/semmle/python/security/dataflow/UnsafeShellCommandConstructionCustomizations.qll
python/ql/lib/semmle/python/security/dataflow/UnsafeShellCommandConstructionQuery.qll
python/ql/test/query-tests/Security/CWE-078-UnsafeShellCommandConstruction/src/unsafe_shell_test.py

While `shlex.quote` wouldn't be a perfect sanitizer for `py/command-line-injection` ([see](https://github.com/github/codeql/blob/075633a8172d842f9a90a230bf10fd4ba2199233/python/ql/test/library-tests/frameworks/stdlib/SystemCommandExecution.py#L157)), it should be for `py/shell-command-constructed-from-input`, as the query covers the argument being formatted into the command.

Python: Add `shlex.quote` as `py/shell-command-constructed-from-input` sanitizer

---

misc/scripts/accept-expected-changes-from-ci.py

Allow empty lines while looking for diff (between `---expected` and `FAILED`). This can happen when there is `Locations outside the test directory` since an empty line is printed after that warning message (this output can be interleaved with the diff due to parallel execution).
An example can be seen here: https://github.com/github/semmle-code/actions/runs/6037086053/job/16380700287#step:29:25078

Misc: Fixup for `accept-expected-changes-from-ci.py`

---

swift/extractor/translators/ExprTranslator.cpp

Before we extracted all the subexpressions from the `SequenceExpr` while we should've only extracted the expressions at odd indices:
```
...
/// SequenceExpr - A list of binary operations which has not yet been
/// folded into a tree.  The operands all have even indices, while the
/// subexpressions with odd indices are all (potentially overloaded)
/// references to binary operators.
class SequenceExpr final : public Expr,
...
```
The AST for a `SequenceExpr` looks like this:
```
sequence_expr:
unresolved_dot_expr:
...
assign_expr:
member_ref_expr:
...
dot_syntax_call_expr:
...
unresolved_member_chain_expr:
...
```
however, what's is not visible with the "final" AST is that `unresolved_dot_expr` is the unresolved version of `assign_expr.member_ref_expr` and the …

Swift: fix SequenceExpr extraction

---

go/ql/lib/change-notes/2023-08-28--add-error-sanitizer-for-xss.md
go/ql/lib/change-notes/2023-08-28-add-error-sanitizer-for-xss.md
go/ql/lib/semmle/go/security/Xss.qll
go/ql/test/query-tests/Security/CWE-079/reflectedxsstest.go

When using MRVA with the Reflected XSS query, I noticed that http.Error is often the last step of a path to http.ResponseWriter, but Errors are reported as plaintext not html and thus are do not result in valid XSS. In fact, this False positive is very common, being around half of the total results. I have opened this PR to help remove http.Error FP.

Go: Add sanitizer to remove paths passing through http.Error

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/test/query-tests/Security/CWE/CWE-089/SqlTainted/SqlTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-089/SqlTainted/test.c

This makes global variables reaching `UnreacheachedInstruction` escape the function. This is what we currently do for parameters and I think more justified in this case than for parameters as the flow can actually happen before the return.
The DCA results show a new trueish positive (`cpp/path-injection` from argv where it is fully expected). There was an extraction failure due to failing to download. 
This will helps more when we mark more functions as non-returning as it means more functions are unreachable.

CPP: Handle globals flowing into "UnreacheachedInstruction"

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll

Identified via https://github.com/github/codeql/pull/14108.

C#: Fix logic for flow into property writes

---

python/ql/src/Security/CWE-312/CleartextLogging.qhelp
python/ql/src/Security/CWE-312/examples/CleartextLogging.py
python/ql/src/Security/CWE-312/examples/CleartextLoggingGood.py

A friend of mine was trying to fix an instance of clear-text-logging in Python.  
The QHelp talked about encrypting the information, and that caused confusion.  
The QHelp for clear-text-logging is the exact same as for clear-text-storage, but I think that's wrong.  
For storage of sensitive data it makes sense to encrypt.  
But for logging of sensitive data it's better advice to just not log sensitive data at all.  
The new QHelp is copy-pasted from JavaScript, and I asked Copilot Chat to translate the examples from JS to Python.  
The result seemed good to me.

Py: add new qhelp for clear-text-logging

---

cpp/ql/lib/change-notes/2023-09-06-as-defining-argument-off-by-one-fix.md
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll

Previously, the domain of the parameter was `[2 ..]` instead of `[1 ..]`. This was confusing since all the other indirect concepts are defined in the range `[1 ..]`.
Since all of our queries and models use the version that takes 0 arguments this won't affect any results (but I'll run DCA anyway just to be safe 🤞).

C++: Fix off-by-one in `asDefiningArgument`

---

csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/Type.cs
csharp/extractor/Semmle.Extraction/Context.cs
csharp/ql/test/library-tests/csharp7/TupleExpr.expected
csharp/ql/test/library-tests/csharp7/TupleTypes.expected

Without this change, https://github.com/github/codeql/pull/14095 revealed some `VALUE_NOT_IN_TYPE` inconsistencies related to tuple types.

C#: Clear TRAP stack when calling `PopulateGenerics`

---

go/extractor/diagnostics/diagnostics.go
go/extractor/extractor.go

**Summary**
We keep seeing customers using advanced workflows who run into problems with their Go 1.21 projects and CodeQL in GHA environments:
- The current default version of Go on GHA images is still 1.20.
- We use the system Go toolchain under the hood to perform the build.
- Consequently, Go 1.21 projects fail to build if Go 1.21 is not explicitly installed.
This PR introduces a new diagnostic which is emitted if the `unknown directive: toolchain` error is detected to advise users that a new system version of Go is required along with a link to instructions on how to do that in a GHA workflow.

Go: Add diagnostic for 1.21 `toolchain` error

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/annotate_sinks_only/tainted.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/uninitialized.expected
cpp/ql/test/library-tests/dataflow/fields/flow.expected
cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowDestination.expected

https://github.com/github/codeql/pull/14008/commits/99cc4171f80d6a14a5378545cb1e8759ff3b5a55 prevented flow from an output argument from flowing into an argument to the same call. This revealed a problem that only became apparent on the QA run for 2.14.4. When we have a snippet such as:
```cpp
void test(int* p) {
write_to_first_argument_and_read_from_second_argument(
p, // (1)
p // (2)
);
sink(p); // (3)
}
```
we can't just block flow from a post-update node of a call (i.e., `(1)`) to a use in the same 
call (i.e., `(2)`) since the use-use chain is `(1) -> (2) -> (3)`.
So instead we have to _skip_ the step from `(1)` to `(2)` and go directly from `(1)` to `(3)`. This PR does this using a call to `shortestDistances`.
(Leaving this as a draft while DCA is running.)

C++: Fix dataflow out of post update nodes

---

javascript/extractor/lib/typescript/src/main.ts
javascript/ql/src/change-notes/2023-09-08-tolerate-out-of-order-requests.md

The TypeScript extractor expects that all files are requested in a predetermined order. However, this conflicted with the recent change to exclude large files, where this filtering occurs only at a later stage.
This is the second time this out-of-order check has caused extraction failures due to an otherwise benign change in the Java part of the extractor. I'd like to remove the hard failure and instead regard the queue as speculative optimization that misses in rare cases.

JS: tolerate out of order requests in TypeScript extractor

---

csharp/ql/integration-tests/all-platforms/dotnet_run/test.py
csharp/tools/tracing-config.lua

If quoted arguments are used these will not be respected by the LUA tracer on windows.
In this PR we explicitly quote all compiler arguments containing whitespaces (windows only) in the dotnet matcher.
This is an initial fix. The full fix, which also depends on an internal PR will be merged here: https://github.com/github/codeql/pull/14150

C#: Poor mans quoting.

---

csharp/ql/integration-tests/all-platforms/dotnet_run/test.py
csharp/tools/tracing-config.lua

If quoted arguments are used these will not be respected by the LUA tracer on windows.
In this PR we explicitly quote all compiler arguments containing whitespaces (windows only) in the `dotnet` matcher.
Something similar is already being done in the `dotnet exec` matcher: https://github.com/github/codeql/blob/main/csharp/tools/tracing-config.lua#L177

C#: Explicitly quote arguments in the LUA tracer on windows.

---

go/codeql-tools/configure-baseline.cmd
go/codeql-tools/configure-baseline.sh

I noticed in integration tests we were seeing
```
Initializing database at /Users/mbg/Code/GitHub/codeql/semmle-code/target/codeql-go-integration-tests/ql/go/ql/integration-tests/all-platforms/go/diagnostics/newer-go-version-needed/test-db.
cat: /Users/mbg/Code/GitHub/codeql/semmle-code/target/intree/codeql: No such file or directory
cat: integration: No such file or directory
cat: tests: No such file or directory
cat: dist: No such file or directory
cat: go/go/tools/baseline-config-empty.json: No such file or directory
Failed to run the configure-baseline script for Go. Proceeding with no baseline configuration, baseline information for Go may be degraded as a result.
```

Fix space handling in Golang configure-baseline scripts

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll

Identified via https://github.com/github/codeql/pull/14108.

C#: Exclude CIL arguments from `ArgumentNode` when they are compiled from source

---

cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/BadlyBoundedWrite.expected

The expected output was incorrect and the result of an evaluator bug. This change should go together with the internal PR that fixes this bug.

C++ tests: fix output of bug-stricken test

---

ruby/ql/consistency-queries/DataFlowConsistency.ql
ruby/ql/consistency-queries/VariablesConsistency.ql
ruby/ql/lib/change-notes/2023-08-23-variable-capture-flow.md
ruby/ql/lib/codeql/ruby/ast/Call.qll
ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll
ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplSpecific.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
ruby/ql/lib/codeql/ruby/frameworks/Sinatra.qll
ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModelsSpecific.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected
ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
ruby/ql/test/library-tests/dataflow/global/Flow.expected
ruby/ql/test/library-tests/dataflow/global/TypeTrackingInlineTest.expected
ruby/ql/test/library-tests/dataflow/global/captured_variables.rb
ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
ruby/ql/test/library-tests/frameworks/sinatra/Sinatra.expected
ruby/ql/test/query-tests/experimental/TemplateInjection/TemplateInjection.expected
ruby/ql/test/query-tests/security/cwe-022/PathInjection.expected
ruby/ql/test/query-tests/security/cwe-117/LogInjection.expected

This PR adopts the [shared variable capture flow library](https://github.com/github/codeql/pull/13478) in Ruby.
The new results reported by DCA are a result of the fact that we are now also able to track side-effects on captured variables, such as writes to instance fields inside blocks. The lost results (those that I have checked) are FPs resulting from the old jump-step based modeling, where data could flow in through one callable and out via another.
The implementation is similar to Java (see PR above), except I chose to distinguish "lambda `self`" from "normal `self`". This is because `self` can actually be referenced from within lambdas (as a captured variable):
```rb
class C
def foo
self.@x = taint # the `self.` is actually implicit in Ruby
end
def bar
yield
end
def baz
self.bar do …
```

Ruby: Reimplement flow through captured variables using field flow

---

python/ql/lib/semmle/python/frameworks/Django.qll
python/ql/lib/semmle/python/security/dataflow/UrlRedirectCustomizations.qll
python/ql/src/change-notes/2023-09-13-django-url-allowed-host.md
python/ql/test/query-tests/Security/CWE-601-UrlRedirect/UrlRedirect.expected
python/ql/test/query-tests/Security/CWE-601-UrlRedirect/test.py

Inspired by what to me looks like a clear FP ([MRVA link](https://gist.github.com/erik-krogh/362438a56ed66c2f79916bbfd0799104)).  
The sanitizer seems decently used: https://github.com/search?type=code&q=%22url_has_allowed_host_and_scheme%22+path%3A*.py
Do you usually put implementations like this in the framework models, or directly in the `*Query.qll` file? 
I can move it to `Django.qll` if you want to, but to follow the existing format I would have to create a new `utils` module in `Django.qll`. 
[Evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-14112-0-python/reports), and seems to remove an FP.

Py: add sanitizer guard for `url_has_allowed_host_and_scheme`

---

cpp/ql/src/experimental/Security/CWE/CWE-416/UseAfterExpiredLifetime.cpp
cpp/ql/src/experimental/Security/CWE/CWE-416/UseAfterExpiredLifetime.qhelp
cpp/ql/src/experimental/Security/CWE/CWE-416/UseAfterExpiredLifetime.ql
cpp/ql/src/experimental/Security/CWE/CWE-416/UseAfterExpiredLifetime_c_api_call.cpp
cpp/ql/src/experimental/Security/CWE/CWE-416/UseAfterExpiredLifetime_iterator_invalidation.cpp

This PR:
- Copies the body of the Coding Standard query for detecting a use of an object whose lifetime has ended into experimental
- Inlines the definitions of various things from their standard library so that the query compiles
- Adds the required metadata and qhelp file to the query
There's _plenty_ of things to fix in the query. I think we should delay those changes to future PRs. We'll also have a proper documentation review once we move the query out of experimental, but I'd appreciate a light 👀 from the team on this as I wrote this part from scratch.

C++: Copy the Coding Standards' use-after-lifetime-ended query to Experimental

---

ruby/ql/consistency-queries/DataFlowConsistency.ql
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll

Between https://github.com/github/codeql/pull/14108 and https://github.com/github/codeql/pull/11725.

Ruby: Fix semantic merge conflict

---

csharp/ql/integration-tests/all-platforms/dotnet_run/test.py
csharp/tools/tracing-config.lua

Hotfix: https://github.com/github/codeql/pull/14172

C#: Quoting hotfix.

---

cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedElement.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedGlobalVar.qll

I have done this a few times. As this is not public it shouldn't make any differences other than when debugging.

CPP: Add a location to TranslatedElement to help with debugging IR creation

---

docs/codeql/ql-language-reference/annotations.rst

This PR updates `pragma[assume_small_delta]` documentation to state that it is deprecated.

Document assume_small_delta deprecation

---

swift/ql/lib/codeql/swift/security/CleartextLoggingExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextStoragePreferencesExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextTransmissionExtensions.qll
swift/ql/src/change-notes/2023-09-12-cleartext.md
swift/ql/test/query-tests/Security/CWE-311/CleartextTransmission.expected
swift/ql/test/query-tests/Security/CWE-311/SensitiveExprs.expected
swift/ql/test/query-tests/Security/CWE-311/testSend.swift
swift/ql/test/query-tests/Security/CWE-312/CleartextStoragePreferences.expected
swift/ql/test/query-tests/Security/CWE-312/cleartextLoggingTest.swift
swift/ql/test/query-tests/Security/CWE-312/testUserDefaults.swift

Added additional taint steps to the `swift/cleartext-transmission`, `swift/cleartext-logging` and `swift/cleartext-storage-preferences` queries similar to an existing additional taint step in the `swift/cleartext-storage-database` query.  This identifies data within a container that matches the sensitive data heuristic as sensitive as well, for example `value` in:
```
myObject.password.value
```
I've also added some tests and converted a couple of existing sinks to CSV.

Swift: Consistent additional taint steps between the cleartext-* queries

---

javascript/extractor/src/com/semmle/jcorn/Parser.java
javascript/ql/test/library-tests/AST/ExplicitResource/printAst.expected
javascript/ql/test/library-tests/AST/ExplicitResource/tst.html

Same as https://github.com/github/codeql/pull/14211, but targeting `rc/3.11`.  
The `codePointAt` call 2 lines down was crashing with an index-of-out-bounds.
This adds a simple range-check to prevent that.
DCA run in progress: https://github.com/github/codeql-dca-main/issues/16057 
I'll only merge once that looks good.

JS: fix out of bounds string access in isUsingDecl

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/IDotNet.cs
csharp/extractor/Semmle.Extraction.Tests/FileContent.cs
csharp/extractor/Semmle.Extraction.Tests/Runtime.cs

In this PR we do the following performance optimisations to the *dependency manager*.
- If solution file(s) are restored then we don't explictly restore projects that are up to date with respect to `dotnet restore` (after restoring the solution).
- `dotnet restore` on projects are executed in parallel.
A couple of implementation details
- We need to change the `dotnet restore` verbosity level to `normal` when restoring solutions to get all the relevant information related to restored projects.
- The `DotNet.cs` file is starting to contain business logic. In https://github.com/github/codeql/pull/14142 we re-factor `DotNet.cs` to enable unit testing.
The changes have been tested on `OrchardCMS/OrchardCore` as it contains a solution file.
The numbers below show that we get the same accuracy …

C#: Avoid explicitly restoring projects in solution files.

---

javascript/ql/src/Security/CWE-116/IncompleteMultiCharacterSanitization.qhelp
javascript/ql/src/Security/CWE-116/IncompleteSanitization.qhelp
ruby/ql/src/queries/security/cwe-116/IncompleteMultiCharacterSanitization.qhelp
ruby/ql/src/queries/security/cwe-116/IncompleteSanitization.qhelp

The QHelp for `incomplete-multi-character-sanitization` was just a direct clone of the QHelp for `incomplete-sanitization`.   
The QHelp did contain a paragraph about multi-char regexps, but generally the QHelp wasn't particularly helpful for developers that try to fix `incomplete-multi-character-sanitization` issues.  
So I wrote a separate QHelp for `incomplete-multi-character-sanitization` that focuses on relevant fix-strategies for that query, which should be more helpful for anyone trying to fix issues from that query. 
I'm not sure about that last Ruby example, could a Ruby person confirm if that works? Or maybe suggest a better example? 
---- 
GPT-4 helped me write the QHelp. As the initial prompt I gave it the `incomplete-sanitization` QHelp and my own description of some …

JS/RB: write qhelp for `incomplete-multi-character-sanitization`

---

ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll
ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll
ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll
ruby/ql/lib/codeql/ruby/security/UnsafeCodeConstructionQuery.qll
ruby/ql/lib/codeql/ruby/security/UnsafeShellCommandConstructionQuery.qll
ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected
ruby/ql/test/library-tests/dataflow/array-flow/array_flow.rb
ruby/ql/test/library-tests/dataflow/array-flow/type-tracking-array-flow.expected
ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.expected
ruby/ql/test/library-tests/dataflow/string-flow/string_flow.rb
ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
ruby/ql/test/library-tests/dataflow/summaries/summaries.rb
ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected
ruby/ql/test/library-tests/frameworks/action_controller/params-flow.expected
ruby/ql/test/library-tests/frameworks/active_record/ActiveRecord.expected
ruby/ql/test/library-tests/frameworks/active_support/active_support.rb
ruby/ql/test/query-tests/security/cwe-079/ReflectedXSS.expected
ruby/ql/test/query-tests/security/cwe-079/StoredXSS.expected
ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected
ruby/ql/test/query-tests/security/cwe-094/CodeInjection/CodeInjection.expected
ruby/ql/test/query-tests/security/cwe-117/LogInjection.expected
ruby/ql/test/query-tests/security/cwe-1333-regexp-injection/RegExpInjection.expected
ruby/ql/test/query-tests/security/cwe-134/TaintedFormatString.expected

In this PR we allow for data to be stored inside an array (possibly nested) when reaching a sink in taint tracking. In order to avoid spurious flow, I had to limit the flow summary for `[]` (`ElementReferenceReadUnknownSummary`) to no longer account for the (very unlikely?) case that the unknown index expression might be a range.

Ruby: Allow for implicit array reads at all sinks during taint tracking

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/guard-condition-regression-test.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/guard-condition-regression-test.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/guard-condition-regression-test.ql
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.expected

This is a more correct fix for https://github.com/github/codeql/issues/14183.
Thanks to @hvitved for spotting this!

C++: Fix `phi`->`phi` flow

---

ruby/ql/lib/codeql/ruby/frameworks/Sinatra.qll

Before
```
Evaluated relational algebra for predicate Sinatra#e09174a3::Sinatra::ErbLocalsAccessSummary#fff@22c05bb6 with tuple counts:
212957   ~2195%    {1} r1 = JOIN _Constant#54e8b051::ConstantValue::getStringlikeValue#0#dispred#ff_Expr#6fb2af19::Expr::getConstantV__#shared WITH Expr#6fb2af19::Pair::getKey#0#dispred#ff_1#join_rhs ON FIRST 1 OUTPUT Lhs.1
43862468   ~6045%    {2} r2 = JOIN r1 WITH Call#841c84e8::MethodCall::getMethodName#0#dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.0
43862468   ~6581%    {2} r3 = JOIN r2 WITH AST#a6718388::AstNode::getLocation#0#dispred#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.1
43844886  ~40661%    {2} r4 = JOIN r3 WITH locations_default ON FIRST 1 OUTPUT Rhs.1, Lhs.1
15004   ~8295%    {3} r5 = JOIN r4 WITH …
```

Ruby: Fix a bad join

---

cpp/ql/lib/semmle/code/cpp/controlflow/Dereferenced.qll

This just pulls out the base cases of `dereferencedByOperation` as it's sometimes useful to use that base set in a query without using the recursive logic in that predicate.
cc @bdrodes

C++: Add a `directDereferencedByOperation` predicate

---

go/extractor/cli/go-autobuilder/go-autobuilder.go

Cherry-picked from #14194. This updates the version regex to accept the new version format. Unfortunately, the regex failed to match at all before this change.

Go: Update `versionRe` to include patch version

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisStage.qll

DCA had some random failures on all the Windows runners, but this seems to speedup the main recursion. I _think_ the explanation is two fold:
- By lifting `noOverflow` out we give the compiler a smaller predicate whose `prev` and `prev_delta` can be used in the recursion.
- By restricting out `initialBoundedLower` and `initialBoundedUpper` we make sure that the joins with `initialBounded_prev` are restricted as much as possible before we join with them.

C++: Fix order of non-linear join in range analysis

---

java/ql/lib/change-notes/2023-07-20-regex-parse-modes.md
java/ql/lib/change-notes/2023-09-12-regex-mode-flag-groups.md
java/ql/lib/semmle/code/java/regex/regex.qll
java/ql/test/query-tests/security/CWE-730/ExpRedosTest.java
java/ql/test/query-tests/security/CWE-730/ReDoS.ql

Understand / correctly parse multiple parse mode flags specified in a regular expression string, for example `i` and `s` in:
```
(?is)abc.*
```
Previously we were only recognizing the first flag (`i`).
This is a backport of part of the Swift PR https://github.com/github/codeql/pull/13715 .

Java: Understand multiple parse mode flags specified in a regular expression string

---

shared/regex/codeql/regex/OverlyLargeRangeQuery.qll
shared/regex/codeql/regex/nfa/BadTagFilterQuery.qll
shared/regex/codeql/regex/nfa/NfaUtils.qll
shared/regex/codeql/regex/nfa/RegexpMatching.qll
shared/regex/codeql/regex/nfa/SuperlinearBackTracking.qll
shared/util/codeql/util/suppression/AlertSuppression.qll

This allows the implementation to inherit the implementations from the super class, instead of having to insert predicates like:  
```CodeQL
string toString() { result = super.toString() }
```

Shared: use final class aliases to use `extends` instead of `instanceof` in the shared libraries

---

python/ql/lib/semmle/python/frameworks/Stdlib.qll

I needed this for some other work, but this could easily be merged on its' own :blush:

Python: Modernize modeling of `BaseHTTPRequestHandler`

---

java/ql/src/Security/CWE/CWE-347/MissingJWTSignatureCheck.ql

The signing key that is being set, is _not_ what is being parsed.
A _JWT_ is being parsed, that will then be verified using the set key.
(Or in our case not, because we're looking for security problems :P)
CC: @erik-krogh

Java: Fix alert message

---

python/ql/src/meta/debug/DebugStats.ql
python/ql/src/meta/debug/SimpleClassDebug.ql

For manually debugging things, it's nice to be able to share debug queries.
I had the DebugStats.ql lying around from way back, and thought it was kinda cute. I've extended it with a bunch of things, not too sure if they're all important, but I think it's kinda fun to see the distribution of things :blush:
Here is a dump of what it looks like on a local DB I had (with no dependency installation, but stdlib extraction)

Python: Add debug queries

---

cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll

This is equivalent as `inst = ir` is functional the forex does nothing.

CPP: Simplify some code in IRGuards.

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/test/query-tests/Security/CWE/CWE-119/SAMATE/OverrunWriteProductFlow.expected

Quite an awkward change, but at least the diff is small and the change is very local `:half-tada:`

C++: Reduce dataflow duplication for allocations

---

csharp/ql/integration-tests/all-platforms/dotnet_run/test.py
csharp/tools/tracing-config.lua

From the `dotnet --help` we can see that it is possible run to run applications using `dotnet` using the following syntax
```
dotnet [runtime-options] [path-to-application] [arguments]
```
It turns out that `dotnet` can be used to invoke `dotnet` - but only nested once. That is, `dotnet dotnet build` is perfectly valid. However, it appears that the tracer is only able to intercept the outer `dotnet` call. To fix this we explicitly *disregard* `dotnet` as a possible subcommand and just look for the next possible `subcommand` - and then re-write the arguments to the dotnet application call. That is, we re-write
```
dotnet dotnet build -> dotnet dotnet build -p:UseSharedCompilation=false
```
then `dotnet` still invokes `dotnet` with `build -p:UseSharedCompilation=false` which is required for …

Lua: Tracing of `dotnet dotnet`.

---

cpp/ql/test/query-tests/Security/CWE/CWE-193/InvalidPointerDeref.expected
cpp/ql/test/query-tests/Security/CWE/CWE-193/test.cpp

Note that this breaks a couple of tests. This is good, however: prior to this PR these things wouldn't work on a real project anyway, but now we at least know about it in our tests 😄.
The last commit adds a couple of additional tests.

C++: Fix the declaration of `malloc` in test

---

cpp/ql/test/query-tests/Security/CWE/CWE-193/test.cpp

C++: Use `size_t` explicitly in CWE-193 tests

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
swift/ql/lib/codeql/swift/security/CleartextLoggingExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextStorageDatabaseExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextStoragePreferencesExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextTransmissionExtensions.qll

CPP / Swift: Typos

---

go/ql/src/Security/CWE-117/LogInjectionGood.go

Hello friends,
We recently came across a Code-QL alert for LogInjection, and the suggestion was really useful!
However, after we applied the suggested fix our linter came back and said "actually, don't you mean `ReplaceAll`?" And on second thought, I think the linter is correct! A malicious payload could just have two `\n`s and evade this escaping.
I am hereby proposing that the suggestion instead use `ReplaceAll`.

s/Replace/ReplaceAll/ in LogInjectionGood.go

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll

Before
```
Evaluated relational algebra for predicate DataFlowPublic#e1781e31::BarrierGuard#PolynomialReDoSCustomizations#32063fa3::PolynomialReDoS::lengthGuard#::getAMaybeGuardedCapturedDef#0#f@3c903abq with tuple counts:
280924  ~0%    {2} r1 = SCAN Ssa#da392372::Make#SsaImpl#ff97b16a::SsaInput#::Definition::definesAt#3#dispred#ffff OUTPUT In.2, In.0
280924  ~0%    {2} r2 = JOIN r1 WITH BasicBlocks#d5fe3e99::BasicBlock::getScope#0#dispred#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1
103843  ~1%    {2} r3 = JOIN r2 WITH SSA#304893e3::Ssa::CapturedEntryDefinition#f ON FIRST 1 OUTPUT Lhs.0, Lhs.1
103843  ~5%    {3} r4 = JOIN r3 WITH Ssa#da392372::Make#SsaImpl#ff97b16a::SsaInput#::Definition::getSourceVariable#0#dispred#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.0
19665045  ~0%    {3} r5 = JOIN r4 WITH …
```

Ruby: Fix bad join

---

csharp/autobuilder/Semmle.Autobuild.Shared/Autobuilder.cs
csharp/autobuilder/Semmle.Autobuild.Shared/BuildActions.cs
csharp/extractor/Semmle.Extraction.CIL.Driver/Program.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNetCliInvoker.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/IDotNet.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/Extractor.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/Options.cs
csharp/extractor/Semmle.Extraction.CSharp/Extractor/Extractor.cs
csharp/extractor/Semmle.Extraction.Tests/DotNet.cs
csharp/extractor/Semmle.Extraction.Tests/Runtime.cs
csharp/extractor/Semmle.Util/Logger.cs
csharp/extractor/Semmle.Util/ProcessStartInfoExtensions.cs

This PR 
- parallelizes the implementation of `DependencyManager.DownloadMissingPackages`,
- adds the managed thread ID to all the extractor log messages, and
- merges two implementations of the `Process` starting logic.
Commit-by-commit review is suggested.

C#: Parallelize restore logic of missing packages

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/ProgressMonitor.cs

When the installed sdk doesn't match the target framework versions, reference assemblies are downloaded as nuget packages. Similarly platform specific runtime packages such as `Microsoft.NETCore.App.Runtime.linux-x64` are also downloaded and extracted in Standalone mode. This PR removes the runtime packages from the reference list.
I tested this change on the `ThreeMammals/Ocelot` repo with dotnet 8 installed on the machine. Before the change we had conflicts:
```
error CS0433: The type 'List<T>' exists in both 'System.Collections, Version=8.0.0.0, ...' and 'System.Private.CoreLib, Version=7.0.0.0, ...'
```
After the change the call target query shows improved precision:
```diff
Query CallTargets.ql:
-  Result count - both/traced/standalone: 22026/9434/893
-  Result count in the matching …
```

C#: Remove platform-specific runtime nuget packages from the reference list in Standalone

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll

C++: Lift `getParameter` to `ParameterNode`

---

java/ql/lib/ext/java.lang.model.yml
java/ql/lib/semmle/code/java/security/XmlParsers.qll
java/ql/test/query-tests/security/CWE-611/DocumentBuilderTests.java
shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll
shared/dataflow/qlpack.yml
shared/typetracking/codeql/typetracking/TypeTracking.qll
shared/util/codeql/util/Unit.qll

XmlParsers.qll currently use 12 instances of data flow. Inter-procedural flow is generally needed, but it doesn't have to be fancy, as witnessed by the fact that field flow was disabled in all 12 instances. As such, the full data flow library is huge overkill and puts undue stress on compilation (ram usage, DIL size, and RA size).
This PR adds an experimental light-weight data flow api internally based on type-tracking, and switches XmlParsers to use that instead. This cuts the DIL size of XXE.ql in half (from 495535 lines to 246580 lines). I've tested each of the 12 flow configs on the MRVA top 1000 and there are only a small handful of result differences - except for one case where 4 flow tuples are removed, it's solely a case of some slight additional flow. The light-weight api has …

Java/Dataflow: Add new light-weight data flow api and use it in XmlParsers

---

swift/ql/lib/change-notes/2023-09-29-nsstring.md
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/NsString.qll
swift/ql/test/library-tests/dataflow/taint/libraries/TaintInline.expected
swift/ql/test/library-tests/dataflow/taint/libraries/nsstring.swift
swift/ql/test/library-tests/dataflow/taint/libraries/string.swift

Improve the taint models for `NSString`.  I noticed the varargs functions were not modelled correctly, and we do have flow working through varargs now.

Swift: Improve taint models for NSString

---

misc/codegen/templates/trap_tags_h.mustache
swift/extractor/infra/SwiftDispatcher.h
swift/extractor/infra/SwiftLocationExtractor.cpp
swift/extractor/infra/SwiftLocationExtractor.h
swift/extractor/print_unextracted/main.cpp
swift/extractor/translators/TranslatorBase.h
swift/extractor/trap/TrapLabel.h

Reverts github/codeql#14011
Now out internal CI does not require any more to build on MacOS 11, so we can get this back in.

Revert "Revert "Swift: use C++20 constraints and concepts to simplify code""

---

swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPrivate.qll
swift/ql/test/library-tests/dataflow/taint/core/LocalTaint.expected
swift/ql/test/library-tests/dataflow/taint/core/Taint.expected
swift/ql/test/library-tests/dataflow/taint/core/TaintInline.expected
swift/ql/test/library-tests/dataflow/taint/core/stringinterpolation.swift

Fix a bug in taint flow through string interpolation, where taint was flowing from input to other inputs (see the first commit for the demonstrative test).
@MathiasVP assuming the tests even pass, would you mind checking I'm not missing something here.  It looks like it might've been done the way it was done for a reason (at least one that applied at the time).

Swift: Fix bug in taint flow through string interpolation

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll

Reduces the DIL by ~6000 lines, but does not appear to affect query evaluation performance.

Ruby: Collapse DIL stages

---

java/ql/lib/change-notes/2023-09-19-arithexpr-assignop.md
java/ql/lib/semmle/code/java/arithmetic/Overflow.qll

`ArithExpr` was considering unary and binary operators, but not compound operators, which are equally relevant for arithmetic-related questions. This PR adds `AssignOp`s to the definition of `ArithExpr` to address that.

Java: Consider AssignOps in ArithExpr

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowDispatch.qll
cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowDispatch.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplSpecific.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowImplSpecific.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowDispatch.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
shared/dataflow/codeql/dataflow/DataFlow.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll

With default predicates we can get rid of some dummy hook implementations.

Dataflow: Make use of defaults for language-specific hooks.

---

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
java/kotlin-extractor/src/main/kotlin/comments/CommentExtractor.kt
java/kotlin-extractor/src/main/kotlin/comments/CommentExtractorPSI.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_4_32/CommentExtractorLighterAST.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_9_0-Beta/CommentExtractorLighterAST.kt

Most of the old `CommentExtractor` is now `CommentExtractorPSI`, and `CommentExtractorLighterAST` is new.

Kotlin: Extract LighterAST comments as well as PSI comments

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs

This change improves the accuracy on `powershell/powershell`:
```diff
Results for PowerShell/PowerShell
Query CallTargets.ql:
-  Result count - both/traced/standalone: 92650/74812/29209
-  Result count in the matching 838 files - both/traced/standalone: 92650/60281/9401
-   Matching 57.07%
+  Result count - both/traced/standalone: 140974/26488/42628
+  Result count in the matching 838 files - both/traced/standalone: 140974/11957/7620
+   Matching 87.81%
```

C#: Remove legacy runtime packages from extraction references

---

swift/ql/lib/change-notes/2023-09-12-regex-mode-flag-groups.md
swift/ql/lib/change-notes/2023-09-26-regex-mode-flags.md
swift/ql/lib/codeql/swift/regex/Regex.qll
swift/ql/lib/codeql/swift/regex/internal/ParseRegex.qll
swift/ql/test/library-tests/regex/parse.expected
swift/ql/test/library-tests/regex/regex.swift
swift/ql/test/query-tests/Security/CWE-116/BadTagFilter.expected
swift/ql/test/query-tests/Security/CWE-116/test.swift
swift/ql/test/query-tests/Security/CWE-1333/ReDoS.expected
swift/ql/test/query-tests/Security/CWE-1333/ReDoS.swift

Ports https://github.com/github/codeql/pull/13975/ to Swift.  This fixes an issue where mode flag group characters (e.g. the `i` and `s` in `(?is)`) were considered as ordinary matches against the input string in addition to setting mode flags.
The message for the test result on `ReDoS.swift:73` demonstrates that we no longer conflate these.

Swift: Port regex mode flag fix from Python to Swift

---

java/kotlin-extractor/src/main/kotlin/KotlinExtractorComponentRegistrar.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_4_32/Kotlin2ComponentRegistrar.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_9_0-Beta/Kotlin2ComponentRegistrar.kt

We don't fully support it yet, but if we don't claim to support it then Kotlin fails early.

Kotlin: Claim to support Kotlin 2

---

ruby/ql/lib/codeql/ruby/ApiGraphs.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll
ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.expected
ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.expected
ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.ql
ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.rb
ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected
ruby/ql/test/library-tests/dataflow/hash-flow/type-tracking-hash-flow.expected
ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected
ruby/ql/test/library-tests/dataflow/local/Nodes.expected
ruby/ql/test/library-tests/dataflow/local/TaintStep.expected
ruby/ql/test/library-tests/dataflow/params/TypeTracker.expected
ruby/ql/test/library-tests/dataflow/params/params-flow.expected
ruby/ql/test/library-tests/dataflow/params/params_flow.rb
ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected
ruby/ql/test/library-tests/frameworks/action_controller/params-flow.expected

This PR builds on top of https://github.com/github/codeql/pull/14090. [This DCA run](https://github.com/github/codeql-dca-main/issues/16381) shows the combined effect of those two PRs, while [this DCA run](https://github.com/github/codeql-dca-main/issues/16446) is for this PR alone.
We support flow through hash-splats in all possible combinations:
```rb
def m1(key1:, key2:); end
args = { key1: a, key2: b }
m1(**args)
def m2(**kwargs); end
m2(key1: a, key2: b)
def m3(key1:, **kwargs); end
args = { key1: a }
m3(key2: b, **args)
```
The first case (`m1`) is handled by synthesizing an implicit hash-splat parameter `implicit-hash-param` inside `m1`, and then adding read steps out of `implicit-hash-param` into `key1` (resp. `key2`), reading out a `KnownElementContent` corresponding to the …

Ruby: Improve performance of flow through (hash) splats

---

shared/tree-sitter-extractor/src/node_types.rs

I was perusing the shared extractor the other day, when I came across the `NodeInfo` struct. I noticed that the `fields` and `subtypes` fields on this struct had two seemingly identical ways of expressing the same thing: `None` and `Some(empty)` (where `empty` is respectively the empty map and the empty vector). As far as I can tell, there's no semantic difference in either case, so we can just elide the option type entirely and use the empty value directly. This has the nice side-effect of cleaning up some of the other code.
(Of course, I am happy to be proven wrong about the semantics of the values of the above fields, if there actually is a reason for this choice! 🙂)

Shared: Clean up `NodeInfo` in shared extractor

---

cpp/ql/lib/semmle/code/cpp/File.qll
csharp/ql/lib/semmle/code/csharp/File.qll
go/ql/lib/semmle/go/Files.qll
java/ql/lib/semmle/code/FileSystem.qll
javascript/ql/lib/semmle/javascript/Files.qll
python/ql/lib/semmle/python/Files.qll
ql/ql/src/codeql/files/FileSystem.qll
ruby/ql/lib/codeql/files/FileSystem.qll
shared/util/codeql/util/FileSystem.qll

This switches C++, Go, Java, JavaScript, Python, and QL to the shared FileSystem library as a followup to https://github.com/github/codeql/pull/12289.
I've also made a small performance tweak to the regex matching that extracts base name, stem, and extension from absolute file paths by reusing the same regex instead of calculating the same match 3 times.
Fixes https://github.com/github/codeql-c-team/issues/1598 and https://github.com/github/codeql-go-team/issues/325

All languages: Use shared FileSystem library and minor regex performance improvement.

---

csharp/ql/src/utils/modeleditor/ModelEditor.qll
csharp/ql/test/utils/modeleditor/ApplicationModeEndpoints.expected
csharp/ql/test/utils/modeleditor/FrameworkModeEndpoints.expected

The MaD format and the Java model editor queries use parentheses around the method parameter types, but `parameterQualifiedTypeNamesToString` returns the parameter types without parentheses. This adds the parentheses to the result of `getParameterTypes` to ensure consistency between the Java and C# queries.

C#: Fix parentheses in model editor queries

---

java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt

If the parent is an `IrExternalPackageFragment` then `parentAsClass` was just crashing.
Will be tested by the Kotlin 2 testsuite.

Kotlin: Handle IrExternalPackageFragment properly for more external entities

---

java/ql/lib/change-notes/2023-09-28-case-rule-stmt-cfg-fix.md
java/ql/lib/semmle/code/java/ControlFlowGraph.qll
java/ql/lib/semmle/code/java/controlflow/internal/GuardsLogic.qll
java/ql/test/library-tests/guards12/PrintAst.expected
java/ql/test/library-tests/guards12/Test.java
java/ql/test/library-tests/guards12/guard.expected

Case rules never fall through. This was already handled correctly for rule expressions, but rule statements were missing the implicit break completion. Added qltest and fixed the CFG. I also amended the guards logic a bit to handle default cases in switch expression, which the test also highlighted as missing.
Fixes https://github.com/github/codeql/issues/14332

Java: Fix CFG for case rule statements.

---

.github/workflows/csharp-qltest.yml
csharp/extractor/Semmle.Extraction.CSharp.StubGenerator/StubGenerator.cs
csharp/extractor/Semmle.Extraction.Tests/StubGenerator.cs

In this PR we
- Add a workflow for running the extractor unit tests on windows. Please note that this requires that we use *bash* as shell when executing the workflow, otherwise the workflow doesn't stop on failure.
- Re-write and re-enable the stub generator unit tests.

C#: Also run extractor unit tests on a windows runner.

---

java/ql/lib/ext/threatmodels/threat-model-grouping.model.yml
java/ql/lib/semmle/code/java/dataflow/ExternalFlowConfiguration.qll
java/ql/lib/semmle/code/java/dataflow/FlowSources.qll
java/ql/lib/semmle/code/java/frameworks/hudson/Hudson.qll
java/ql/test/library-tests/dataflow/threat-models/Empty.java
java/ql/test/library-tests/dataflow/threat-models/Test.java
java/ql/test/library-tests/dataflow/threat-models/Test.qll
java/ql/test/library-tests/dataflow/threat-models/TestSources.java
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.ext.yml
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.ql
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest2.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest2.ext.yml
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest2.ql
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest3.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest3.ext.yml
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest3.ql
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest4.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest4.ext.yml
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest4.ql
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest5.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest5.ext.yml
java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest5.ql
java/ql/test/library-tests/dataflow/threat-models/threat-models1.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models1.ql
java/ql/test/library-tests/dataflow/threat-models/threat-models2.expected
java/ql/test/library-tests/dataflow/threat-models/threat-models2.ql

In this PR we introduce a class of data flow nodes called `ThreatModelFlowSource`.
The idea is that these are the exact source nodes we are interested in under a given *threat model*.
For more background information see [EDR](https://github.com/github/code-scanning/blob/main/docs/adrs/0043-threat-modeling.md).
With this implementation it will also be easy to for a query to "opt-in" to *threat models* as defined by the `ThreatModelFlowSource` by updating the data flow configuration.
```codeql
override predicate isSource(DataFlow::Node src) { src instanceof ThreatModelFlowSource }
```
With this change, we can convert most of the data flow related queries that are based on `RemoteFlowSource` to `ThreatModelFlowSource` as this (should) yield the same results as long as the default threat …

Java: Introduce a class of dataflow nodes for the threat modeling.

---

swift/ql/lib/codeql/swift/security/CleartextStorageDatabaseExtensions.qll
swift/ql/lib/codeql/swift/security/CleartextStorageDatabaseQuery.qll
swift/ql/lib/codeql/swift/security/CommandInjectionExtensions.qll
swift/ql/lib/codeql/swift/security/CommandInjectionQuery.qll
swift/ql/test/query-tests/Security/CWE-078/CommandInjection.expected
swift/ql/test/query-tests/Security/CWE-311/CleartextStorageDatabase.expected

Replace additional taint steps in `swift/command-line-injection` and `swift/cleartext-storage-database` with implicit reads instead.  Implicit reads are a more principled / accurate way of doing data flow out from array elements at the sink (now that we model array content and it can work).
Note that in the test changes, the `#select` parts are unaffected.

Swift: Replace two additional taint steps with implicit reads

---

swift/ql/lib/change-notes/2023-09-27-debugdesc.md
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/FilePath.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/String.qll
swift/ql/test/library-tests/dataflow/taint/core/LocalTaint.expected
swift/ql/test/library-tests/dataflow/taint/core/Taint.expected
swift/ql/test/library-tests/dataflow/taint/core/conversions.swift
swift/ql/test/library-tests/dataflow/taint/libraries/files.swift
swift/ql/test/library-tests/dataflow/taint/libraries/string.swift
swift/ql/test/library-tests/dataflow/taint/libraries/url.swift

Model `CustomStringConvertible.description` and `CustomDebugStringConvertible.debugDescription`.  Delete ad-hoc models of these methods on specific classes.

Swift: Model .description, .debugDescription more generally

---

swift/ql/src/queries/Summary/FlowSources.ql
swift/ql/src/queries/Summary/QuerySinks.ql
swift/ql/src/queries/Summary/RegexEvals.ql
swift/ql/src/queries/Summary/SummaryStats.ql
swift/ql/src/queries/Summary/TaintReach.ql

Update summary queries.  Three new queries are added:
- `swift/summary/regex-evals`, which lists regular expression evaluations (approximately the sinks for the regex queries).
- `swift/summary/query-sinks`, which lists all other query sinks.  Hopefully this will give us a much better understanding of why certain queries are under-performing.
- `swift/summary/taint-reach`, which computes the taint reach metric now instead of being done as part of `swift/summary/summary-statistics`.  This change is made because taint reach is expensive to compute and could potentially fail on large projects, so it's best for it to be separate.

Swift: Update summary queries

---

go/Makefile
go/ql/src/experimental/CWE-203/timingBad.go
go/ql/src/experimental/CWE-203/timingGood.go
go/ql/src/experimental/CWE-74/DsnBad.go
go/ql/src/experimental/CWE-74/DsnGood.go

I tried to do this once before but my bash-scripting skills weren't up to it. This time I had copilot to do it for me 😄 .

Go: improve output of check formatting in makefile

---

java/ql/lib/change-notes/2023-09-28-moved-localuserinput-to-mad.md
java/ql/lib/change-notes/2023-10-05-moved-localuserinput-to-mad.md
java/ql/lib/ext/hudson.model.yml
java/ql/lib/ext/java.io.model.yml
java/ql/lib/ext/java.lang.model.yml
java/ql/lib/ext/java.sql.model.yml
java/ql/lib/ext/java.util.model.yml
java/ql/lib/semmle/code/java/dataflow/FlowSources.qll
java/ql/lib/semmle/code/java/frameworks/hudson/Hudson.qll
shared/mad/codeql/mad/ModelValidation.qll

This converts the currently existing forms of `LocalUserInput` to rely on MaD models instead of being manually modeled in QL.
> [!NOTE]
> This does not handle other forms of `LocalUserInput` such as `main` methods or args4j arguments.

Java: Convert implementations of `LocalUserInput` to Models-as-Data

---

java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt

* The way we handle not supporting Brotli is changed, so that now we don't have to worry about impossible cases later on.
* We now determine the compression method that we're using later, which means that we already have a logger with which we can log any warnings we need to.

Kotlin: Some compression simplification

---

cpp/BUILD.bazel
cpp/ql/lib/BUILD.bazel
csharp/BUILD.bazel
csharp/ql/lib/BUILD.bazel
java/BUILD.bazel
java/ql/lib/config/BUILD.bazel
javascript/BUILD.bazel
javascript/ql/lib/BUILD.bazel
python/BUILD.bazel
python/ql/lib/BUILD.bazel

This adds skeleton bazel files that export the dbschemes and stats files.
This is needed so our internal unit tests can read those files.

Add skeleton bazel files for accessing the dbschemes.

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll

https://github.com/github/codeql/pull/14376 fixed a bug where we incorrectly shared representation between certain dataflow nodes.
This fix revealed another bug: the "reverse flow" mechanism (which we have for detecting that something like `myMap["abc"] = source();` is a write that modifies `myMap`) didn't account for the case where the `OutNode` that represents the result of `myMap["abc"]` was an _instruction_ instead of an operand.
This bug was hidden until https://github.com/github/codeql/pull/14376 was merged because these operand and instruction nodes accidentally shared representation.
`OutNode`s are operands most of the time, but they're instructions when the result of the `CallInstruction` has multiple uses. One of the cases where this happens after the frontend upgrade is when an …

C++: Also handle reverse flow on instructions in dataflow

---

javascript/ql/lib/semmle/javascript/AMD.qll
javascript/ql/src/change-notes/2023-10-05-amd-range.md
javascript/ql/test/library-tests/AMD/test_range.js
javascript/ql/test/library-tests/AMD/tests.expected
javascript/ql/test/library-tests/AMD/tests.ql

Adds `AmdModuleDefinition::Range` so users can add aliases for the AMD `define` function.

JS: Add AmdModuleDefinition::Range

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ProductFlow.qll
cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/AllocationToInvalidPointer.qll
cpp/ql/test/query-tests/Security/CWE/CWE-193/InvalidPointerDeref.expected
cpp/ql/test/query-tests/Security/CWE/CWE-193/test.cpp

It's a bit annoying that we have to import `DataFlowPrivate` here, but there's no publicly accessible `asIndirectOperand` or `asIndirectInstruction` predicates on `DataFlow::Node`s yet.
This removes the annoying FP we've been seeing on projects using `sqlite`. @alexet you mentioned that this may be blocking too much flow. Was this the implementation strategy you had in mind when you said this?

C++: Disable size-flow through pointer arithmetics in `cpp/invalid-pointer-deref`

---

cpp/ql/lib/semmle/code/cpp/commons/Buffer.qll

Iteration 3 performed really poorly on basically all forks of https://github.com/OISF/suricata:
```ql
Tuple counts for Buffer#61e3d199::getBufferSize#2#fff/3@i3#ffc522h5 after 7m31s:
13721000    ~3205%       {2} r1 = SCAN Buffer#61e3d199::getBufferSize#2#fff#prev_delta OUTPUT In.0, In.1 'why'
1315097     ~403%        {2} r2 = JOIN r1 WITH DataFlowUtil#47741e1f::ExprFlowCached::localExprFlowStep#2#ff ON FIRST 1 OUTPUT Rhs.1 'bufferExpr', Lhs.1 'why'
40865305    ~365%        {3} r3 = JOIN r2 WITH __Buffer#61e3d199::getBufferSize#2#fff#prev_Buffer#61e3d199::getBufferSize#2#fff#prev_delta_DataFlow__#join_rhs ON FIRST 1 OUTPUT Lhs.0 'bufferExpr', Lhs.1 'why', Rhs.1 'result'
7479500     ~662397%     {1} r4 = SCAN Buffer#61e3d199::getBufferSize#2#fff#prev_delta OUTPUT In.0
53000       ~5094% …
```

C++: Project away `why` to prevent tuple duplication in `Buffer.qll`

---

cpp/ql/src/Security/CWE/CWE-079/CgiXss.ql
cpp/ql/test/query-tests/Security/CWE/CWE-079/semmle/CgiXss/CgiXss.expected

I'm hard pressed for projects that have actually have relevant sources. MRVA only shows 5, one of which have relevant flow: `apache/trafficserver`, `apple/cups`, `OpenPrinting/cups`, `git/git`, and `git-for-windows/git`. DCA doesn't show anything special.

C++: Rewrite `cpp/cgi-xss` to not use default taint tracking

---

docs/codeql/codeql-for-visual-studio-code/about-telemetry-in-codeql-for-visual-studio-code.rst

The recommended setting to use is now `telemetry.telemetryLevel`.
See https://github.com/github/vscode-codeql/pull/2824 which implemented this change in the extension (currently not released as of writing).
I considered still mentioning the old setting because the extension currently respects both. But the [microsoft documentation](https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting) we link to only mentions the new setting, so I decided to follow that example.

Update about-telemetry-in-codeql-for-visual-studio-code.rst to mention telemtry.telemetryLevel

---

java/ql/lib/semmle/code/java/Expr.qll

The type arguments which these predicates have as result are for the type of the created instance.
Previously the documentation said "provided to the constructor", which is misleading / incorrect. Type arguments provided to the constructor are specified directly after the `new` keyword:
```
class C {
<T> C() {
}
}
new <String> C();
```
And those are not part of the results of these predicates.
Feedback, especially regarding the wording, is welcome!

Java: Adjust `ClassInstanceExpr` type argument predicates docs

---

java/ql/lib/change-notes/2023-10-07-MemberRefExpr-getReceiverExpr.md
java/ql/lib/semmle/code/java/Expr.qll
java/ql/test/library-tests/MemberRefExpr/MemberRefExpr.expected
java/ql/test/library-tests/MemberRefExpr/MemberRefExpr.ql
java/ql/test/library-tests/MemberRefExpr/Test.java

Relates to #14277
`MemberRefExpr` inherits predicates such as `getQualifier()` from `ClassInstanceExpr`. However, these are often not useful because they apply to the synthetic anonymous class instead of the member reference expression.
Due to that it appears there is currently no easy way to obtain the expression on the left side of the `::` (e.g. for `this::toString` the `this` expression). This pull request adds a predicate for that. The name is based on the existing `getReceiverType` predicate; but suggestions for a better name are welcome.
I am not completely sure though how useful this predicate is; if you think it this is not useful enough, feel free to reject this PR.

Java: Add predicate `MemberRefExpr::getReceiverExpr`

---

swift/ql/lib/codeql/swift/security/HardcodedEncryptionKeyExtensions.qll
swift/ql/src/change-notes/2023-10-06-const-key-sinks.md
swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.expected
swift/ql/test/query-tests/Security/CWE-321/grdb.swift

Add sinks for the GRDB database library to `swift/hardcoded-key`.  That is, model the functions in that library that deal with encryption keys.

Swift: Add sinks for the GRDB database library to swift/hardcoded-key

---

swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPublic.qll

Performance Improvement motivated by a discovery on a nightly run.
Despite the `bindingset[node]` annotation, the evaluator was attempting to bind `node` using the internal logic of the predicate before applying the externally derived binding (which comes from `TaintTrackingImpl.qll`'s `allowImplicitRead`), causing an explosion of computation.  Forcing the issue with `pragma[only_bind_out]` appears to entirely solve the issue.
Locally I'm seeing something like a 30s improvement on multiple queries.  A DCA run should confirm...

Swift: defaultImplicitTaintRead performance improvement

---

python/ql/test/query-tests/Security/CWE-020-SuspiciousRegexpRange/OverlyLargeRangeQuery.expected
python/ql/test/query-tests/Security/CWE-020-SuspiciousRegexpRange/test.py
shared/regex/codeql/regex/OverlyLargeRangeQuery.qll
shared/regex/codeql/regex/nfa/NfaUtils.qll
shared/util/codeql/util/Strings.qll

A friend of mine found it confusing to see an alert message like this:  
So I used the same escaping that I recently made for the ReDoS queries.  
I could have put that escaping in `NfaUtils.qll`, but that seemed wrong, as it has nothing to do with regular expressions or NFAs. 
So I made a new `Strings` library inside the `utils` pack.    
---- 
The root problem seems to be that the string-constants in the Python extractor (and other languages, but I've only tested Python) are unescaped before being put in the database, which makes sense for the vast majority of use-cases.    
And until recently you couldn't really work with unicode chars in CodeQL in a nice way.
For regular expressions it would make sense to work on the "raw" string instead of the unescaped string that Python has.  
But …

JS/PY/RB/Java: escape unicode chars in overly-large-range

---

go/extractor/cli/go-autobuilder/go-autobuilder.go
go/ql/integration-tests/all-platforms/go/diagnostics/newer-go-version-needed/diagnostics.expected
go/ql/integration-tests/all-platforms/go/diagnostics/newer-go-version-needed/test.py
go/ql/integration-tests/all-platforms/go/diagnostics/newer-go-version-needed/work/go.mod

**Sumarry**
This PR cherry-picks the commits from #14194 that are needed to support an internal PR. 
We change the following:
- We invoke `go version` with `GOTOOLCHAIN=local` to force it to return the version of the local toolchain, rather than attempt to download whatever toolchain the project needs and then run its `version` command.
- The `newer-go-version-needed` diagnostic is no longer needed for Go 1.21+
- The test for the `newer-go-version-needed` diagnostic needs to be updated to account for that, since we are running the tests with Go 1.21+ only.
**How to review**
The tests here are expected to fail, but should pass for the internal PR. 
#14194 was previously approved.

Go: Fix version detection and test for `newer-go-version-needed`

---

cpp/ql/src/Security/CWE/CWE-079/CgiXss.ql
cpp/ql/test/query-tests/Security/CWE/CWE-079/semmle/CgiXss/CgiXss.expected

This reverts commit b6132d2a0fcd7496d0e9145a9519e567e2e2f665.
Temporarily revert the `cpp/cgi-xss` rewrite. The rewrite is looking at expressions instead of indirect expressions, which makes more sense since we are interested in the value being returned from `getenv`. I fix this in a follow-up PR, but I don't want to leave this around in the mean time.

Revert "C++: Rewrite `cpp/cgi-xss` to not use default taint tracking"

---

go/ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll

This fixes a performance regression. The exact cause of the regression was hard to track down, but it seems that the optimizer made some bad choices when deciding how to evaluate the code and these changes stop that.

Go: Change MaxValueState API to get architecture bit size

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/AssemblyCache.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs

This PR helps with setting up standalone integration tests that list assemblies. (https://github.com/github/codeql/pull/14368)

C#: Make conflicting assembly selection deterministic in standalone

---

javascript/ql/lib/change-notes/2023-10-07-tagged-template-litterals.md
javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll
javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll
javascript/ql/lib/semmle/javascript/internal/CachedStages.qll
javascript/ql/test/ApiGraphs/tagged-template/VerifyAssertions.ql
javascript/ql/test/ApiGraphs/tagged-template/index.js
javascript/ql/test/ApiGraphs/tagged-template/package.json
javascript/ql/test/library-tests/CallGraphs/FullTest/getACallee.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/getAFunctionValue.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/getAnArgument.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/getArgument.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/getCalleeName.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/getCalleeNode.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/getLastArgument.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/getNumArgument.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/isImprecise.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/isIncomplete.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/isUncertain.qll
javascript/ql/test/library-tests/CallGraphs/FullTest/taggedTemplate.js
javascript/ql/test/library-tests/CallGraphs/FullTest/tests.expected
javascript/ql/test/library-tests/CallGraphs/FullTest/tests.ql
javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected
javascript/ql/test/library-tests/TaintTracking/DataFlowTracking.expected
javascript/ql/test/library-tests/TaintTracking/tst.js

Motivated by two recent external contributions that noticed the lack of call-edges to/from tagged template literals. ([First](https://github.com/github/codeql/pull/14342), [second](https://github.com/github/codeql/pull/14294)).  
The implementation is fairly straight forward.  
The constant template elements of the tagged template literal are not modeled (the `foo` and `bar` in ``func`foo${exp)bar`;``)
There was a performance issue, which was fixed by adding some more `cache`.  
[An evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/tagCall-with-meta/reports) shows neutral performance and some new call-edges and sinks (new sinks from recognizing more DOM nodes).

JS: recognize tagged template literals as `DataFlow::CallNode`

---

config/identical-files.json
ruby/ql/lib/codeql/ruby/security/HttpToFileAccessQuery.qll
ruby/ql/lib/codeql/ruby/security/TaintedFormatStringQuery.qll
ruby/ql/src/queries/security/cwe-134/TaintedFormatString.ql
ruby/ql/src/queries/security/cwe-912/HttpToFileAccess.ql

The `HttpToFileAccess` and `TaintedFormatString` queries had some files synced by `identical-files.json`, which previously made it impossible to migrate them for one language at a time.
This is problematic for Ruby because a rather trivial change becomes blocked by the JS data flow migration. It's also problematic for the JS migration because the already-large change needs to include Ruby changes on the same branch.
This PR removes the synchronization so each language can migrate independently, and then migrates the queries for Ruby.

JS/Ruby: desync two queries and port the Ruby version to ConfigSig-style

---

.github/workflows/compile-queries.yml

The compilation cache ran out of space when we compile all queries.  
With this change the compile-queries workflow should become much faster in the best-case.

use a bigger compilation cache in the compile-queries workflow

---

cpp/ql/src/Security/CWE/CWE-119/OverrunWriteProductFlow.ql

This flow state was necessary to have a `PathNode` for every place where pointer arithmetic was performed (because a state change always breaks up the big-step relation). However, in https://github.com/github/codeql/pull/13717 a change was made so that _every_ additional flow step by default would break the big-step relation.
This means we don't need to have the hacky `FlowState` anymore 🎉

C++: Remove unnecessary `FlowState` from `cpp/overrun-write`

---

swift/extractor/SwiftExtractor.cpp
swift/extractor/translators/DeclTranslator.cpp
swift/ql/test/extractor-tests/generated/decl/ClassDecl/ClassDecl_getMember.expected
swift/ql/test/extractor-tests/generated/decl/EnumDecl/EnumDecl_getMember.expected
swift/ql/test/extractor-tests/updates/PrintAst.expected
swift/ql/test/library-tests/ast/PrintAst.expected
swift/ql/test/library-tests/dataflow/taint/core/TaintInline.expected
swift/ql/test/library-tests/dataflow/taint/libraries/TaintInline.expected
swift/ql/test/library-tests/elements/expr/methodlookup/PrintAst.expected

Technically, this is a no-op for our test suite, though I'm not sure why the order has changed.
This is required for https://github.com/github/codeql/pull/14261 as it fixes a crash when we try to extract certain unavailable declarations.

Swift: skip declarations marked as unavailable

---

swift/ql/lib/codeql/swift/security/StringLengthConflationQuery.qll
swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.expected
swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.swift

Add a few more test cases for `swift\string-length-conflation`.  Fix a minor result duplication issue.
@AlexDenisov the third case (the "GOOD" result) is very similar to the case you were looking at today.  I'm convinced it should not be a result of the query.

Swift: Additional test cases for `swift\string-length-conflation`

---

java/kotlin-extractor/src/main/java/com/semmle/extractor/java/OdasaOutput.java
java/kotlin-extractor/src/main/kotlin/ExternalDeclExtractor.kt
java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt
java/ql/integration-tests/all-platforms/kotlin/trap_compression/test.py

While you could control compression with
```
CODEQL_EXTRACTOR_JAVA_OPTION_TRAP_COMPRESSION
```
before, most TRAP files used gzip regardless for compatibility with the Java extractor. Now Java understands the option too we can use it for shared TRAP files.

Kotlin: Improve support for TRAP compression options

---

docs/codeql/codeql-for-visual-studio-code/using-the-codeql-model-editor.rst

There was an extra `/` in the second last link in the file.

Fix typo in link

---

docs/codeql/ql-language-reference/ql-language-specification.rst
shared/regex/codeql/regex/nfa/NfaUtils.qll
shared/util/codeql/util/Strings.qll

I wasn't sure what to put as the first word in the title of this PR.  
It's shared code in the `shared/` folder, but it's only used by the ReDoS libraries.
I've put the Python team as reviewers, because they motivated the work.
The codePointAt and codePointCount methods and very new, but they've been in the language for a few weeks by now.  
(The PR was merged about a month ago). 
--- 
I've added documentation for the new string methods to our language specification.

ReDoS: use the new codePointAt and codePointCount methods instead of regex hacks

---

ruby/ql/lib/change-notes/2023-09-18-graphql-sources.md
ruby/ql/lib/codeql/ruby/frameworks/GraphQL.qll
ruby/ql/test/library-tests/frameworks/graphql/GraphQL.expected
ruby/ql/test/library-tests/frameworks/graphql/GraphQL.ql
ruby/ql/test/library-tests/frameworks/graphql/app/graphql/types/base_enum.rb
ruby/ql/test/library-tests/frameworks/graphql/app/graphql/types/direction.rb
ruby/ql/test/library-tests/frameworks/graphql/app/graphql/types/media_category.rb
ruby/ql/test/library-tests/frameworks/graphql/app/graphql/types/post.rb
ruby/ql/test/library-tests/frameworks/graphql/app/graphql/types/post_order.rb
ruby/ql/test/library-tests/frameworks/graphql/app/graphql/types/query_type.rb
ruby/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.expected

Previously we considered any parameter in a graphql resolver to be
a remote flow source. Now we limit that to parameters (and reads of hash splat parameters) which yield scalar types (e.g. String), as defined by the GraphQL schema.
This should reduce GraphQL false positives.
In general, the idea is to ignore sources which are constrained by GraphQL types. For example:
```rb
class class MediaCategory < GraphQL::Schema::Enum
value "AUDIO", "An audio file, such as music or spoken word"
value "IMAGE", "A still image, such as a photo or graphic"
value "TEXT", "Written words"
value "VIDEO", "Motion picture, may have audio"
end
class Post < GraphQL::Schema::Object
field :title, String
field :body, String
field :media_category, Types::MediaCategory
end
class QueryType < GraphQL::Schema::Object …
```

Ruby: Restrict GraphQL remote flow sources

---

cpp/ql/lib/semmle/code/cpp/NameQualifiers.qll
cpp/ql/lib/semmle/code/cpp/controlflow/DefinitionsAndUses.qll
cpp/ql/lib/semmle/code/cpp/controlflow/SSA.qll
cpp/ql/lib/semmle/code/cpp/controlflow/SSAUtils.qll
cpp/ql/lib/semmle/code/cpp/controlflow/internal/ConstantExprs.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/RangeSSA.qll
cpp/ql/src/Microsoft/SAL.qll
csharp/ql/lib/semmle/code/csharp/exprs/Access.qll
csharp/ql/lib/semmle/code/csharp/frameworks/System.qll
java/ql/lib/semmle/code/java/GeneratedFiles.qll
java/ql/lib/semmle/code/java/JDKAnnotations.qll
java/ql/lib/semmle/code/java/Serializability.qll
java/ql/lib/semmle/code/java/deadcode/DeadCode.qll
java/ql/lib/semmle/code/java/deadcode/DeadField.qll
java/ql/lib/semmle/code/java/deadcode/EntryPoints.qll
java/ql/lib/semmle/code/java/frameworks/JAXB.qll
java/ql/lib/semmle/code/java/frameworks/Mockito.qll
java/ql/lib/semmle/code/java/frameworks/camel/CamelJavaAnnotations.qll
java/ql/lib/semmle/code/java/frameworks/camel/CamelJavaDSL.qll
java/ql/lib/semmle/code/java/frameworks/javaee/JavaServerFaces.qll
java/ql/lib/semmle/code/java/frameworks/struts/StrutsConventions.qll
java/ql/src/Likely Bugs/Comparison/UselessComparisonTest.qll

Removes all remaining deprecated `library` annotations.

Java/C/C#: Remove library annotations

---

csharp/ql/lib/semmle/code/csharp/security/auth/InsecureDirectObjectReferenceQuery.qll
csharp/ql/lib/semmle/code/csharp/security/auth/MissingFunctionLevelAccessControlQuery.qll
csharp/ql/src/change-notes/2023-10-13-accesscontrol-idor-updates.md
csharp/ql/test/query-tests/Security Features/CWE-285/MissingAccessControl/MVCTests/ProfileController.cs
csharp/ql/test/query-tests/Security Features/CWE-639/MVCTests/MiscTestControllers.cs

Improves detection of authorize attributes to include generic classes, which should fix [this](https://github.com/github/codeql/issues/14478) FP.

C#: Fix FP in Missing Function Level Access Control and Insecure Direct Object Reference

---

cpp/ql/src/Likely Bugs/RedundantNullCheckSimple.ql
cpp/ql/src/change-notes/2023-10-16-redundant-null-check-simple.md

This query was supposed to be promoted in https://github.com/github/codeql/pull/12822, but I forgot to add the `security` tag. So it was actually never promoted 😱!

C++: Mark `cpp/redundant-null-check-simple` as a security query

---

.github/dependabot.yml

We re-add the allow list to (hopefully) suppress the security updates for the test dependencies and group the `golang.org` dependencies together to avoid generating redundant PRs in cases such as https://github.com/github/codeql/pull/14440

Go: Improve Dependabot configuration

---

java/ql/lib/change-notes/2023-10-12-sync-local-and-remote-dataflow-configurations.md
java/ql/lib/semmle/code/java/security/ArithmeticTaintedLocalQuery.qll
java/ql/lib/semmle/code/java/security/ExternallyControlledFormatStringLocalQuery.qll
java/ql/lib/semmle/code/java/security/ImproperValidationOfArrayIndexLocalQuery.qll
java/ql/lib/semmle/code/java/security/NumericCastTaintedQuery.qll
java/ql/lib/semmle/code/java/security/ResponseSplittingLocalQuery.qll
java/ql/lib/semmle/code/java/security/SqlTaintedLocalQuery.qll
java/ql/lib/semmle/code/java/security/XssLocalQuery.qll

Some of the `*Local` versions of queries diverge from their remote counterpart. This PR synchronizes them.

Java: Synchronize `*Local` versions of queries with their remote counterpart

---

cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/AllocationToInvalidPointer.qll
cpp/ql/test/query-tests/Security/CWE/CWE-193/InvalidPointerDeref.expected
cpp/ql/test/query-tests/Security/CWE/CWE-193/test.cpp

This fixes a missing result on an existing project.

C++: Fix size deduction in `cpp/invalid-pointer-deref`

---

.github/dependabot.yml

Typo didn't get caught before merging #14483.

Fix invalid `dependabot.yml`

---

swift/ql/lib/change-notes/2023-10-16-collection-content.md
swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPublic.qll
swift/ql/lib/codeql/swift/security/CleartextLoggingQuery.qll
swift/ql/lib/codeql/swift/security/CleartextStorageDatabaseQuery.qll
swift/ql/lib/codeql/swift/security/CommandInjectionQuery.qll
swift/ql/lib/codeql/swift/security/ConstantPasswordQuery.qll
swift/ql/lib/codeql/swift/security/ConstantSaltQuery.qll
swift/ql/lib/codeql/swift/security/HardcodedEncryptionKeyQuery.qll
swift/ql/lib/codeql/swift/security/StaticInitializationVectorQuery.qll
swift/ql/lib/codeql/swift/security/UnsafeJsEvalQuery.qll
swift/ql/test/library-tests/dataflow/taint/core/Taint.expected
swift/ql/test/library-tests/dataflow/taint/core/conversions.swift
swift/ql/test/library-tests/dataflow/taint/libraries/int.swift
swift/ql/test/query-tests/Security/CWE-1204/StaticInitializationVector.expected
swift/ql/test/query-tests/Security/CWE-1204/test.swift
swift/ql/test/query-tests/Security/CWE-259/ConstantPassword.expected
swift/ql/test/query-tests/Security/CWE-259/test.swift
swift/ql/test/query-tests/Security/CWE-321/cryptoswift.swift
swift/ql/test/query-tests/Security/CWE-760/ConstantSalt.expected
swift/ql/test/query-tests/Security/CWE-760/test.swift

It's been observed that quite a lot of Swift queries have an `allowImplicitRead` rule for reading out of `CollectionContent`; and it's been further pointed out that we could put that rule in `defaultImplicitTaintRead` so that it applies to all queries.  This behaviour is not expected to ever be undesirable in the context of taint flow queries, so having it there simplifies queries and helps avoid mistakes*.  This PR does this change.
`*` - it turns out we do indeed find some new good results in some of the encryption queries as a result of this change - though new barriers were also required to prevent result duplication.
---
Performance is a slight concern, though we've seen no problems in the queries that were already doing this via `allowImplicitRead`.  I want to call out that we're …

Swift: Add CollectionContent to defaultImplicitTaintRead

---

cpp/ql/lib/change-notes/2023-10-12-additional-call-targets.md
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowDispatch.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/test/library-tests/dataflow/fields/IRConfiguration.qll
cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected
cpp/ql/test/library-tests/dataflow/fields/simple.cpp

This is motivated by a use-case from @bdrodes. It's now possible to extend the class `AdditionalCallTarget` to specify additional call targets. For example, given this snippet:
```cpp
void sink(int);
int source();
void f(int);
void g(int x) {
sink(x);
}
void test() {
int x = source();
f(x);
}
```
there's normally no flow from `source` to `sink`, but if we extend `AdditionalCallTarget` like:
```ql
class MyAdditionalCallTarget extends DataFlow::AdditionalCallTarget {
override Function viableTarget(Call call) {
call.toString() = "call to f" and
result.hasName("g")
}
}
```
then we now get flow because the call to `f` is resolved to target `g`.
Before merging this PR I'd like to confirm with @bdrodes that this solves the problem he's having. Once that's done I'll add a test.
Note that since …

C++: Add an abstract class that can be used to extend `viableCallable`

---

swift/ql/lib/change-notes/2023-10-16-string.md
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/String.qll
swift/ql/test/library-tests/dataflow/taint/libraries/string.swift

Swift: Add models for some missing string methods:
- [`StringProtocol.appendingformat(_:_:)`](https://developer.apple.com/documentation/swift/stringprotocol/appendingformat(_:_:))
- [`String.decodecstring(_:as:repairinginvalidcodeunits:)`](https://developer.apple.com/documentation/swift/string/decodecstring(_:as:repairinginvalidcodeunits:)-3mvvy)
- there are actually four variations of the latter, covered by two models

Swift: Model StringProtocol.appendingformat and String.decodecstring

---

java/ql/lib/ext/javax.crypto.model.yml
java/ql/lib/ext/javax.crypto.spec.model.yml
java/ql/lib/semmle/code/java/security/StaticInitializationVectorQuery.qll

Refactors the `java/static-initialization-vector` query to use models-as-data models for it's sink and moves the definitions for `isAdditionalFlowStep` into models.
This makes it easier for other queries to use these definitions (this is beneficial for queries such as Weak Randomness).

Java: Refactor `java/static-initialization-vector` to use Models as Data

---

java/ql/lib/semmle/code/java/security/SpringCsrfProtection.qll
java/ql/src/Security/CWE/CWE-352/SpringCSRFProtection.ql
java/ql/src/change-notes/2023-10-16-spring-disabled-csrf-protection-improved.md
java/ql/test/query-tests/security/CWE-352/CONSISTENCY/typeParametersInScope.expected
java/ql/test/query-tests/security/CWE-352/SpringCsrfProtectionTest.expected
java/ql/test/query-tests/security/CWE-352/SpringCsrfProtectionTest.java
java/ql/test/query-tests/security/CWE-352/SpringCsrfProtectionTest.ql
java/ql/test/query-tests/security/CWE-352/options
java/ql/test/stubs/springframework-5.3.8/org/springframework/security/config/annotation/web/builders/HttpSecurity.java
java/ql/test/stubs/springframework-5.3.8/org/springframework/security/config/annotation/web/configurers/AbstractHttpConfigurer.java
java/ql/test/stubs/springframework-5.3.8/org/springframework/security/config/annotation/web/configurers/CsrfConfigurer.java

Improves the query `java/spring-disabled-csrf-protection` to detect the pattern:
```java
http.csrf(AbstractHttpConfigurer::disable);
```

Java: Improve java/spring-disabled-csrf-protection

---

docs/codeql/codeql-language-guides/advanced-dataflow-scenarios-cpp.rst
docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp-new.rst
docs/codeql/codeql-language-guides/codeql-for-cpp.rst
docs/codeql/reusables/cpp-new-dataflow-api-note.rst

This PR adds a new article (linked from https://codeql.github.com/docs/codeql-language-guides/codeql-for-cpp/) explaining how we would tackle a few situations that involve tainting a pointer or tainting its indirection.
We know from past experience that this has been something Microsoft has needed some explanation of, and this document should hopefully answer some of the common questions we've gotten (with the expectation that other people will have similar questions).
cc @felicitymay

C++: Add more documentation about dataflow through indirections

---

java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_5_0/ReferenceEntity.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_8_0/ReferenceEntity.kt

This showed up as a bug in Kotlin 2 mode:
We were starting with the Class Id "java/util/Map.Entry", which we then converted to the FqName "java.util.Map.Entry", and then back to a Class Id with ClassId.topLevel. This gave us a Class Id that referenceClass wasn't able to resolve.
Now we just stick with the Class Id that we started with, and the class can be resolved by Kotlin 2.

Kotlin: Don't convert back and forth between ClassId and FqName

---

.github/workflows/check-change-note.yml

Addresses feedback in internal issue.
The change note file name checks are now more verbose explaining why they behave as they do.

Improve change note checking

---

javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeHtmlConstructionQuery.qll

fix typo ('Configration' to ‘Configuration’)

fix typo ('Configration' to ‘Configuration’)

---

cpp/ql/lib/change-notes/2023-10-20-implicit-this.md
cpp/ql/lib/semmle/code/cpp/exprs/Access.qll
cpp/ql/lib/semmle/code/cpp/valuenumbering/HashCons.qll
cpp/ql/test/examples/expressions/PrintAST.expected
cpp/ql/test/library-tests/access/FieldAccess/FieldAccess.expected
cpp/ql/test/library-tests/ir/ir/PrintAST.expected

Closes https://github.com/github/codeql-c-team/issues/1239
`ImplicitThisFieldAccess` now works as expected by using the recently-fixed `compgenerated()` predicate.
As a consequence, the `FieldAccess` test now correctly identifies the field accesses as `ImplicitThisFieldAccess` as well as `PointerFieldAccess`.
I needed to fix up GVN because `ImplicitThisFieldAccess` overlaps with other classes.
Change-note required?

C++: Fix ImplicitThisFieldAccess

---

go/documentation/library-coverage/coverage.rst
go/documentation/library-coverage/frameworks.csv

Note that the space at the beginning of the package patterns for the standard library is deliberate, because builtin functions use the empty string as their package and we want to attribute them to the standard library.

Go: Add Go frameworks for automated coverage reports

---

java/ql/automodel/src/AutomodelFrameworkModeExtractPositiveExamples.ql

The framework mode +example extraction query had a subtle bug that limited its output to sink examples.
The first commit is the actual fix, the second commit is just autoformatting.

Java: Automodel Framework Mode Extraction Bug

---

java/ql/src/Metrics/Summaries/LinesOfCode.ql
java/ql/src/Metrics/Summaries/LinesOfCodeJava.ql
java/ql/src/Metrics/Summaries/LinesOfCodeKotlin.ql
java/ql/src/change-notes/2023-10-20-lines-of-code.md

There's now a single lines-of-code query that gives the total number of lines of code over both languages.
Per-language LoC queries are now just summaries.
@henrymercer

Java/Kotlin: Reshuffle our LoC queries

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ModelUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected
cpp/ql/test/library-tests/dataflow/fields/dataflow-ir-consistency.expected
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/map.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/smart_pointer.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/taint.ql

The motivation for this PR was that we failed to track this flow when the source is whatever `indirect_source()` points to:
```cpp
void test_indirect_taint() {
std::map<int, int*> m;
int* p = indirect_source();
m[1] = p;
int* q = m[1];
sink(q); // $ MISSING: ast ir
}
```
The fix was in our interpretation of models (in `ModelUtil.qll`) so that the model for `operator[]` correctly carried indirect flow from `*p` to `m` (this causes pointer/pointee conflation but since these are _taint_ models that's fine).
Finally, fixing the interpretation of models revealed a missing flow step for smart pointers. Specifically, we didn't model that `operator->` and `get` performed a load.

C++: Fix indirect taint

---

swift/ql/lib/change-notes/2023-10-13-rawrepresentable.md
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/RawRepresentable.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/StandardLibrary.qll
swift/ql/lib/codeql/swift/security/XXEExtensions.qll
swift/ql/test/library-tests/dataflow/taint/libraries/optionset.swift
swift/ql/test/query-tests/Security/CWE-611/XXETest.expected

Model [`RawRepresentable`](https://developer.apple.com/documentation/swift/rawrepresentable), and by extension some uses of [`OptionSet`](https://developer.apple.com/documentation/swift/optionset).  Simplify the XXE query logic a little now that it no longer needs to make special cases for `.rawValue` (or `SignedInteger` initializers).
Query sinks for `swift/xxe` are not affected.  DCA run to follow...

Swift: Model RawRepresentable

---

cpp/ql/lib/semmle/code/cpp/models/implementations/Strtok.qll
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp

This fixes a missing case for the `strtok` model. The problem was revealed by the fixes in https://github.com/github/codeql/pull/14571, but the DCA run for the project that had this regression failed the DCA run. So we didn't spot the regression in the PR 😭.

C++: Fix `strtok` model for indirections

---

java/ql/lib/semmle/code/java/dataflow/internal/ModelExclusions.qll

We currently exclude only JDK internals from MaD models. This PR excludes any models with `%internal%` in their  package name since such models have come up during ML and heuristic triage. 
Let me know if there is any reason not to apply this exclusion.

Java: exclude internal packages globally from MaD models

---

cpp/ql/lib/change-notes/2023-10-24-remove-getlocation-from-folder.md
cpp/ql/lib/semmle/code/cpp/File.qll

Follow up to https://github.com/github/codeql/pull/14321
With the above-mentioned PR, `Container` now has conflicting urls provided by `getURL` and `getLocation`, respectively. This PR removes `getLocation`, since `getURL` ought to be sufficient. I was a bit in doubt about whether to switch the `extends` to `Element` or `ElementBase`, but it seemed that the additional predicates inherited from `Element` made little sense for `Container`s, so I chose `ElementBase`.
cc @jketema

C++: Remove getLocation from Container.

---

.github/workflows/csv-coverage-pr-artifacts.yml
misc/scripts/library-coverage/comment-pr.py

The framework coverage difference commenter currently posts a new comment after new commits. When there are a lot of these comments on a PR, it can be hard to find comments from reviewers. This PR changes the workflow so that it updates one comment box instead of creating multiple comments. 
**Note:** this code is based on the QHelp preview comment workflow which updates one comment box.  The first commit https://github.com/github/codeql/pull/14517/commits/9263cfdf5616644578dce04f11633dee0b9af255 is based on [this code in qhelp-pr-preview.yml](https://github.com/github/codeql/blob/1297acf5b129fdffa0d4dbcde74ac082b1df7487/.github/workflows/qhelp-pr-preview.yml#L88-L92).  The second commit https://github.com/github/codeql/pull/14517/commits/6e29b701007ff881e56ad74a63375b76117fed7d is based …

CI: Update framework coverage difference commenter

---

java/ql/lib/semmle/code/java/Expr.qll

It appears the Kotlin extractor does not have access to the actual string representation in the source code, and for most literal types uses simply the represented value also as `getLiteral` result, see https://github.com/github/codeql/blob/codeql-cli/v2.15.1/java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt#L4443
And also #11296
Feedback, especially regarding the wording, is appreciated.

Kotlin: Mention `Literal::getLiteral()` difference from source code

---

docs/codeql/writing-codeql-queries/debugging-data-flow-queries-using-partial-flow.rst
shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

When using partial flow we would calculate both partial forward flow and partial reverse flow even though only one direction was requested. This moves the choice into the parameterised module application so we know up front which one to calculate. So instead of always using `module Partial = FlowExploration<limit/0>` and choosing between `Partial::partialFlow` and `Partial::partialFlowRev`, you now choose between `module Partial = FlowExplorationFwd<limit/0>` and `module Partial = FlowExplorationRev<limit/0>`, and then always use `Partial::partialFlow`.

Dataflow: Restrict partial flow to either forward or reverse flow.

---

javascript/extractor/src/com/semmle/js/extractor/TypeExprKinds.java
javascript/ql/test/library-tests/TypeScript/Types/badTypes.ts
javascript/ql/test/library-tests/TypeScript/Types/printAst.expected
javascript/ql/test/library-tests/TypeScript/Types/tests.expected

Our extractor crashes on the latest version of babel.  
It crashes on a test case that is syntactically valid, but the test will always have type errors.  
But we still shouldn't crash on it.  
I'm running an evaluation, and I won't merge before that comes back clean.

JS: fix `TypeExprKinds` crashing on a `ThisExpression`

---

java/ql/lib/semmle/code/java/dispatch/VirtualDispatch.qll

As the title says this splits the different layers of virtual dispatch into separate stages. Having them in a single stage has been a source of annoyance when editing anything in between as everything kept being recomputed.

Java: Split the different layers of virtual dispatch into separate cached stages.

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

These aliases are now utilised in DIL and RA names, so we can simplify a bit.

Dataflow: simplify using stage aliases.

---

javascript/ql/src/RegExp/IdentityReplacement.ql

A customer pointed out that it didn't make much sense to have this query marked as "high severity", and I agree.  
(CodeQL devs: See backref for more context). 
I'm lowering it to a medium of 5.0 for now.

JS: lower the severity of js/identity-replacement to medium

---

go/ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll
go/ql/src/change-notes/2023-10-27-incorrect-integer-conversion-guards.md
go/ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.go

Two bugs fixed, with corresponding test cases, plus some miscellaneous refactoring to make some of the code a bit nicer to read and to try to avoid doing integer arithmetic with floats (because CodeQL integers are signed 32-bit integers) above the level where that is precise.

Go: Two fixes to upper bound checks in "incorrect integer conversion" query

---

ruby/ql/lib/codeql/ruby/typetracking/ApiGraphShared.qll
ruby/ql/src/queries/modeling/GenerateModel.ql
ruby/ql/src/queries/modeling/internal/Summaries.qll
ruby/ql/src/queries/modeling/internal/Types.qll
ruby/ql/src/queries/modeling/internal/Util.qll
ruby/scripts/generate_model.py

Generates `typeModel` and `summaryModel` data extensions entries. Usage is `generate_model.py -o model.yml <path_to_gem_database>`.
Replaces https://github.com/github/codeql/pull/13750 which contains some more context - access paths here are mostly generated using API graphs rather than the AST. This generally seems to yield more complete results than using the AST.
As this only generates type and summary models (not sources and sinks), it isn't expected to generate particularly useful models on its own, though added flow summaries may find some missing paths.
`pathToNodeRec` in `Util.qll` contains a workaround to avoid generating paths of unbounded length. We can in theory end up generating paths of unbounded length if there is a cycle in access paths - for example a fluent API would …

Ruby: add a query and script for autogenerating typeModel and summaryModel data extensions entries

---

go/ql/lib/change-notes/2023-10-25-reflectedxss-cookie-sanitizer.md
go/ql/lib/semmle/go/security/ReflectedXssCustomizations.qll
go/ql/test/library-tests/semmle/go/frameworks/XNetHtml/ReflectedXss.expected
go/ql/test/library-tests/semmle/go/frameworks/XNetHtml/SqlInjection.expected
go/ql/test/library-tests/semmle/go/frameworks/XNetHtml/test.go
go/ql/test/query-tests/Security/CWE-079/ReflectedXss.expected
go/ql/test/query-tests/Security/CWE-079/reflectedxsstest.go

In Reflected XSS vulnerabilities, control over cookie values requires another vulnerability such as CRLF injection in order to exploit. For this reason, most alerts will be FPs and developers will not understand the issue, therefore it is best to not alert to this issue.

Go: GoAdd Cookie Sanitizer to Reflected XSS

---

codeql-workspace.yml
javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsExtensions.qll
javascript/ql/lib/semmle/javascript/frameworks/data/internal/model.yml
python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModelsExtensions.qll
python/ql/lib/semmle/python/frameworks/data/internal/empty.model.yml
ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModelsExtensions.qll
ruby/ql/lib/codeql/ruby/frameworks/data/internal/model.yml

The neutralModel extensible predicate already exists in Java and C#, so
this change brings the dynamic languages more in line with static
languages. The Model Editor uses this predicate to mark endpoints as
"not interesting" from a data flow perspective.
We don't actually make use of this predicate inside the dynamic libraries (indeed, at the moment I think only Java and C# do so), but the model editor should be able to take advantage of it nonetheless.
The first commit allows codeql to see data extensions stored in the .github
directory inside the codeql repo. This is useful when using the CodeQL
Model Editor whilst working inside the codeql repo.

JS/Ruby/Python: Add neutralModel extensible predicate

---

cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/flowOut.cpp

This demonstrates a false dataflow edge that shouldn't exist.

CPP: Add dataflow FP with output arguments

---

csharp/ql/lib/semmle/code/csharp/AnnotatedType.qll
csharp/ql/lib/semmle/code/csharp/Attribute.qll
csharp/ql/lib/semmle/code/csharp/Callable.qll
csharp/ql/lib/semmle/code/csharp/Event.qll
csharp/ql/lib/semmle/code/csharp/Generics.qll
csharp/ql/lib/semmle/code/csharp/Member.qll
csharp/ql/lib/semmle/code/csharp/Property.qll
csharp/ql/lib/semmle/code/csharp/Stmt.qll
csharp/ql/lib/semmle/code/csharp/Type.qll
csharp/ql/lib/semmle/code/csharp/TypeRef.qll
csharp/ql/lib/semmle/code/csharp/Unification.qll
csharp/ql/lib/semmle/code/csharp/Using.qll
csharp/ql/lib/semmle/code/csharp/Variable.qll
csharp/ql/lib/semmle/code/csharp/exprs/Creation.qll
csharp/ql/lib/semmle/code/csharp/exprs/Expr.qll

[Type references](https://github.com/github/codeql/blob/c1a1ebfb6026f887dd4c531dfad6ade754fc1378/csharp/ql/lib/semmle/code/csharp/TypeRef.qll#L10) are used by the C# extractor to avoid situations where the type of, say, an expression is defined in an assembly, and we for some reason never get around to extracting the type. In this case, instead of the expression not being included at all (because of a `VALUE_NOT_IN_TYPE` TRAP import error), we simply get an expression with an unknown type.
In some situations, the same entity may be extracted multiple times (in multiple compilations), and we can end up in a situation where an associated type is extracted both directly (because the type belongs to the entity we are extracting) and as a reference, and in case the reference is unresolvable, …

C#: Only use `getTypeRef` when there is not already a type available

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/ql/integration-tests/posix-only/standalone_dependencies/Assemblies.expected
csharp/ql/integration-tests/windows-only/standalone_dependencies/Assemblies.expected

This PR handles `netstandard` target frameworks. When multiple frameworks are targeted then the assemblies get deduplicated by name. Netstandard packages contain a `netstandard.dll` assembly, which conflicts with other variants.
The DCA experiments shows significant improvement on `DewGaming/PokemonDatabase`, where it removes 266810 compilation errors.

C#: Handle `netstandard` references in standalone extraction

---

swift/ql/test/query-tests/Security/CWE-094/UnsafeJsEval.expected
swift/ql/test/query-tests/Security/CWE-094/UnsafeJsEval.swift

Clean up the `swift/unsafe-js-eval` test, with the intent of making the results easier to understand.  It's an unusual test because the `testAsync` and `testSync` methods are matrix tests - each pairs a number of sources to a number of sinks via calling a closure called `sink` representing each of the sinks.  I've labelled both source and sink lines as `BAD` to make it clearer which lines should appear in the results.

Swift: Clean up the swift/unsafe-js-eval test

---

go/ql/integration-tests/all-platforms/go/bazel-sample-1/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/bazel-sample-2/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/diagnostics/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/go-get-without-modules-sample/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/go-mod-sample/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/make-sample/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/ninja-sample/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/single-go-mod-and-go-files-not-under-it/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/single-go-mod-in-root/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/single-go-mod-not-in-root/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/single-go-work-not-in-root/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/two-go-mods-nested-none-in-root/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/two-go-mods-nested-one-in-root/force_sequential_test_execution
go/ql/integration-tests/all-platforms/go/two-go-mods-not-nested/force_sequential_test_execution
go/ql/integration-tests/linux-only/go/dep-sample/force_sequential_test_execution
go/ql/integration-tests/linux-only/go/glide-sample/force_sequential_test_execution

`go get` has been observed to sometimes fail when multiple tests try to simultaneously fetch the same package.

Go: mark all integration tests non-parallelisable

---

java/ql/test/kotlin/library-tests/enum/test.expected
java/ql/test/kotlin/library-tests/enum/test.ql

In Kotlin 2 mode, there are more library classes matching `Enum%`, so the output was spuriously different.

Kotlin: Make the enum test more precise

---

cpp/ql/lib/change-notes/2023-10-30-realloc-flow.md
cpp/ql/lib/semmle/code/cpp/models/implementations/Allocation.qll
cpp/ql/lib/semmle/code/cpp/models/implementations/Memset.qll
cpp/ql/src/Security/CWE/CWE-497/ExposedSystemData.ql
cpp/ql/src/Security/CWE/CWE-497/PotentiallyExposedSystemData.ql
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-497/semmle/tests/PotentiallyExposedSystemData.expected
cpp/ql/test/query-tests/Security/CWE/CWE-497/semmle/tests/tests.cpp

This should fix some missing results that @jketema was observing on MRVA 🤞

C++: Add a taint model for `realloc`

---

cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/InvalidPointerToDereference.qll
cpp/ql/test/query-tests/Security/CWE/CWE-193/InvalidPointerDeref.expected
cpp/ql/test/query-tests/Security/CWE/CWE-193/test.cpp

This is quite a nice simplification of `cpp/invalid-pointer-deref`. The only actual change is in https://github.com/github/codeql/commit/c8edf3151b90515d36a82fb1453425990c002ade#diff-fae29bfae3f7ffbf1c40e3b1e68cec1869e8757d7461d85382914f9c74b69699, and the remaining code just:
- Accepts the test changes
- Simplify the surrounding code now that `deltaDerefSourceAndPai` is always 0
- Updates the documentation
This removes a nasty FP (which is awesome) at the cost of removing a synthetic TP we added in https://github.com/github/codeql/pull/13815. I think this is a worthwhile change (and I'll run a difference query on MRVA to see the impact of this).

C++: Remove one use of range analysis in `cpp/invalid-pointer-deref`

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticSSA.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/ModulusAnalysis.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisConstantSpecific.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisImpl.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisRelativeSpecific.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeUtils.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/SignAnalysisCommon.qll
java/ql/lib/semmle/code/java/dataflow/RangeAnalysis.qll
shared/rangeanalysis/codeql/rangeanalysis/RangeAnalysis.qll
shared/rangeanalysis/codeql/rangeanalysis/internal/RangeUtils.qll

This moves the `ssaRead` predicate to a shared utils library, and cleans up some predicates in the signatures.
Commit-by-commit review is encouraged.
There are some very minor changes in the set of computed tuples for Java, as unary plus is now included (which is very uncommon), and `LocalVariableDeclExpr` are now also included in `ssaRead` as I didn't bother extending the language api to support excluding them (having those tuples won't matter, since such expressions are never in a context where we care about `ssaRead`).

Rangeanalysis: Share ssaRead predicate

---

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll
python/ql/test/experimental/dataflow/module-initialization/localFlow.ql

The logic for separating local flow into _import time_ and _runtime_ was duplicated a few times.
Create a module for it instead, and add a good qldoc.
The logic for adding flow out of post-update-nodes
was also duplicated, so I added a module for that also.
The two modules are now only used together (except in one test file).
I did not fuse them, though, as I think they may not be used
together in the case of use-use-flow.

Python: module for import time flow

---

csharp/ql/lib/semmle/code/cil/Declaration.qll
csharp/ql/lib/semmle/code/csharp/Callable.qll
csharp/ql/lib/semmle/code/csharp/Element.qll
csharp/ql/lib/semmle/code/csharp/Generics.qll
csharp/ql/lib/semmle/code/csharp/Member.qll
csharp/ql/lib/semmle/code/csharp/Namespace.qll
csharp/ql/lib/semmle/code/csharp/Type.qll
csharp/ql/lib/semmle/code/csharp/Variable.qll
csharp/ql/lib/semmle/code/csharp/commons/QualifiedName.qll
csharp/ql/lib/semmle/code/dotnet/Declaration.qll
csharp/ql/lib/semmle/code/dotnet/Namespace.qll

This PR moves the logic for computing fully qualified names into `QualifiedName.qll`, and makes it parameterized on how to print unbound generics. This is in preparation for a change to the Models-as-Data format for C#.

C#: Move qualified name computation into `QualifiedName.qll`

---

cpp/ql/lib/semmle/code/cpp/models/Models.qll
cpp/ql/lib/semmle/code/cpp/models/implementations/ODBC.qll
cpp/ql/src/change-notes/2023-10-31-odbc-models.md
cpp/ql/src/change-notes/released/0.8.3.md
cpp/ql/test/query-tests/Security/CWE/CWE-089/SqlTainted/SqlTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-089/SqlTainted/test.c

Adds a model implementation for ODBC database APIs.

C++: Adding a model implementation for ODBC.

---

cpp/ql/test/library-tests/ir/range-analysis/SimpleRangeAnalysis_tests.cpp
shared/rangeanalysis/codeql/rangeanalysis/ModulusAnalysis.qll

This fixes the bounds in the loop-unrolled code from https://github.com/github/codeql/pull/14444

RangeAnalysis: Improve bounds that rely on relative modulus.

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FileContent.cs
csharp/extractor/Semmle.Extraction.Tests/FileContent.cs
csharp/ql/integration-tests/posix-only/standalone_dependencies/Assemblies.expected
csharp/ql/integration-tests/windows-only/standalone_dependencies/Assemblies.expected

In the DependencyManager we do some processing of eg. `PackageReference` and other content.
However, in some cases this might be commented out.
That is, the dependency manager shouldn't detect that we have a package dependency when it comes across something like
```csharp
```
as this is commented out.

C#: Update DependencyManager logic to exclude commented out references.

---

swift/extractor/main.cpp
swift/third_party/BUILD.swift-llvm-support.bazel
swift/third_party/BUILD.swift-toolchain-linux.bazel
swift/third_party/BUILD.swift-toolchain-macos.bazel
swift/third_party/load.bzl
swift/third_party/swift-llvm-support/BUILD.bazel
swift/tools/tracing-config.lua

This fetches the resource directory directly from the released
toolchains, allowing us to stop prebuilding and assembling them.
Moreover insertion of our resource directory is moved to the lua
tracing configuration (solving a `TODO`) and enhanced. Now all options
that start with the original resource directory (either explicit or
implied) are redirected to our resource directory.
This solves a problem where `-I <original resource dir>/some/path` was
passed to the extractor and did not work.
This works around the 5.9 linux compatibility problem by including the
`PackageDescription` swift modules in the in-dist toolchain. Copying the
toolchain and fixing the `-I` flag was not enough as for some reason
compilation of `PackageDescription.swiftinterface`  was causing a crash
in the SIL pass. …

Swift: rework resource dir

---

docs/codeql/reusables/supported-frameworks.rst

After https://github.com/github/codeql/pull/13729 was merged, we can probably claim support for AWS Lambda. Let me know if you think otherwise.

Python: Add AWS Lambda as a supported framework

---

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll
python/ql/lib/semmle/python/dataflow/new/internal/ImportResolution.qll
python/ql/test/experimental/dataflow/coverage/dataflow-consistency.expected
python/ql/test/experimental/dataflow/coverage/loops.py
python/ql/test/experimental/dataflow/module-initialization/localFlow.ql
python/ql/test/experimental/dataflow/strange-essaflow/testFlow.ql
python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep-py3/dataflow-consistency.expected
python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/dataflow-consistency.expected
python/ql/test/experimental/dataflow/validTest.py
python/ql/test/experimental/dataflow/variable-capture/dataflow-consistency.expected
python/ql/test/library-tests/ApiGraphs/py3/dataflow-consistency.expected
python/ql/test/library-tests/frameworks/django-orm/dataflow-consistency.expected

These should be filtered on use-use steps, so I have factored those out.
(If self loops appear on the other steps, we want the inconsistency check to tell us.)
Based on https://github.com/github/codeql/pull/14617 so should be rebased once that is merged.

Python: filter local self loops

---

swift/ql/test/library-tests/dataflow/taint/libraries/string.swift
swift/ql/test/library-tests/dataflow/taint/libraries/url.swift

Fix failing QL for Swift tests on `main`.  My best guess is that this is the result of some recent PRs interacting (positively).  I'll investigate a bit deeper but I want to get CI started on this now...

Swift: Fix failing tests

---

swift/ql/test/library-tests/dataflow/flowsources/webview.swift

Add a test cases for webview sources from a branch that didn't make it (because we found a better way to do what it was trying to do).

Swift: Add a webview test case

---

python/ql/lib/semmle/python/dataflow/new/internal/ImportResolution.qll

This doesn't really seem to impact performance, is just a bit cleaner way to write the QL code.
In the worst case, since we do string concat with empty string, we would need to load string + attempt to store new string in string pool, which is useless since we can surely just reuse the integer ID.
```
Evaluated non-recursive predicate ImportResolution#f829f0f0::ImportResolution::getImmediateModuleReference#1#ff#reorder_1_0#join_rhs#CSE@5fdc6eia in 1ms (size: 2).
Evaluated relational algebra for predicate ImportResolution#f829f0f0::ImportResolution::getImmediateModuleReference#1#ff#reorder_1_0#join_rhs#CSE@5fdc6eia with tuple counts:
1   ~0%    {1} r1 = CONSTANT(unique string)[""]
1   ~0%    {1} r2 = CONSTANT(unique string)[".__init__"]
2   ~0%    {1} r3 = r1 UNION r2
return r3
Evaluated …
```

Python: Minor cleanup for string pool interaction

---

csharp/ql/lib/semmle/code/csharp/Generics.qll

This predicate would never contain any tuples, given that the extractor considers a constructed type `C<T1, ..., Tn>`, where `Ti` is the `i`th type parameter of `C`, identical with the unbound generic type ``C`n``.

C#: Deprecate `UnboundGenericType::getInstanceType/0`

---

csharp/ql/test/TestUtilities/InlineFlowTest.qll
csharp/ql/test/library-tests/dataflow/types/Types.cs
csharp/ql/test/library-tests/dataflow/types/Types.expected
csharp/ql/test/library-tests/dataflow/types/Types.ql

I initially thought we didn't handle unbound generic types correctly in our GVN translation, and hence data flow, but [it turns out](https://github.com/github/codeql/blob/c6bc1a3f3ac043cd6714f51f70f2aafa880a48a0/csharp/ql/lib/semmle/code/csharp/Unification.qll#L29) that we actually do properly treat type parameters as type arguments for unbound generic types. So this PR merely confirms that, by adding a test that would otherwise fail.

C#: Add another data flow test

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/AssemblyCache.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/Assets.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/Dependencies.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyContainer.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/IDotNet.cs
csharp/extractor/Semmle.Extraction.Tests/Assets.cs
csharp/extractor/Semmle.Extraction.Tests/DotNet.cs
csharp/extractor/Semmle.Extraction.Tests/Runtime.cs
csharp/extractor/Semmle.Util/IEnumerableExtensions.cs
csharp/ql/integration-tests/posix-only/standalone_dependencies/Assemblies.expected
csharp/ql/integration-tests/windows-only/standalone_dependencies/Assemblies.expected

In this PR we try to narrow which dependencies to include in standalone compilation.
Prior to this PR we took all dll's in all the packages that were downloaded as a part of the `dotnet restore` process and included them in the standalone compilation.
As a result
- It often led to conflicts as Packages might contain the assemblies for multiple versions of .NET (which then conflict with each other). The deduplication of dll's can only fix this if the dll's have identical names.
- Way to many assemblies not required for compilation got included.
We try to solve this issue by inspecting the content of all `project.assets.json` files after `dotnet restore`s have been executed:
- In the `targets` section we try to find all *package* references and _only_ include the dll's that are required for …

C#: Use `project.assets.json` for package dependencies.

---

docs/codeql/reusables/supported-frameworks.rst

They were almost alphabetical, but not quite.
Python was ordered by category first, and by name within each catogory. I've left it like that, but it would probably be better to be consistent between languages, one way or the other.

Docs: Put lists in supported-frameworks.rst in more alphabetical order

---

swift/extractor/translators/TypeTranslator.cpp

`getCanonicalType` will force computation of the canonical type. Without canonical type computed. `getString` may cause crashes in certain cases.

Swlft: force canonical type computation before using the type

---

java/ql/integration-tests/all-platforms/java/diagnostics/java-version-too-old/test.py

I've been investigating moving the Java integration tests to a
GH-hosted macos runner, instead of a self-hosted one.
This test is not compatible with a GH-hosted runners Java setup.
It is also not compatible to being exposed to JAVA_21_HOME_X64 variable yet.
This PR fixes both issues.

Java: Make integration test more robust wrt recent Java versions.

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/RangeAnalysis.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/SimpleRangeAnalysis.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticExpr.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticExprSpecific.qll
cpp/ql/test/library-tests/ir/range-analysis/SimpleRangeAnalysis_tests.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-193/InvalidPointerDeref.expected
cpp/ql/test/query-tests/Security/CWE/CWE-193/test.cpp

In C/C++ there are many implicit conversions which must be handled as part of range analysis. For example, in the following:
```cpp
void test(short s) {
if(s < 5) { ... }
}
```
there's a short-to-int conversion on `s`. Previously, we made the new range analysis library handle this by wrapping the definition of a C/C++ `SemExpr` inside an `EquivalenceClass` so that the expression `(int)s` and the expression `s` was identical.
However, @aschackmull made me aware that the range analysis library already has support for "this expression reads this variable" to handle stuff like `+n < 5` in Java. So we can get equivalent functionality by simply making these "safe conversions" copy-value expressions, and the range analysis library will ensure that a bound on `(int)s` in the example above is …

C++: Simplify the definition of `SemExpr` for range analysis

---

cpp/ql/test/library-tests/ir/range-analysis/test.cpp

This snippet causes non-terminating modulus analysis when we remove IR phi input operands as SSA variables. I think it has something to do with the non-exact phi operand, but I've yet to verify this. For now it's good to simply have this testcase included

C++: Add range analysis testcase

---

java/ql/lib/semmle/code/java/security/regexp/ExponentialBackTracking.qll
java/ql/src/Security/CWE/CWE-730/ReDoSReferences.inc.qhelp
javascript/ql/lib/semmle/javascript/security/regexp/ExponentialBackTracking.qll
javascript/ql/src/Performance/ReDoSReferences.inc.qhelp
python/ql/lib/semmle/python/security/regexp/ExponentialBackTracking.qll
python/ql/src/Security/CWE-730/ReDoSReferences.inc.qhelp
ruby/ql/lib/codeql/ruby/security/regexp/ExponentialBackTracking.qll
ruby/ql/src/queries/security/cwe-1333/ReDoSReferences.inc.qhelp
shared/regex/codeql/regex/nfa/ExponentialBackTracking.qll

Fix a dead link related to the ReDoS query in all places where it occurs.
- old link: http://www.cs.bham.ac.uk/~hxt/research/reg-exp-sec.pdf (claimed to be "James Kirrage, Asiri Rathnayake, Hayo Thielecke: Static Analysis for Regular Expression Denial-of-Service Attacks. NSS 2013.", now "404: Not Found")
- new link: https://arxiv.org/abs/1301.0849 ("Static Analysis for Regular Expression Denial-of-Service Attacks James Kirrage, Asiri Rathnayake, Hayo Thielecke")
- I noticed this was a dead link while working on the [Swift ReDoS query `.qhelp`](https://github.com/github/codeql/blob/main/swift/ql/src/queries/Security/CWE-1333/ReDoSReferences.inc.qhelp#L10), and already did the substitution there.  This PR extends that substitution to every other occurrence.

Fix a dead ReDoS link in docs

---

javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java

No test case, because this only causes crashes on Windows (where e.g. `*.js` is not a valid file name).  
That also means I haven't tested it.  
But it should fix the reported error... 
Fixes an internally reported crash on Windows. 
See the backref for a stacktrace and some more details.

JS: catch when the main: path is invalid on Windows

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticExprSpecific.qll
cpp/ql/test/query-tests/Security/CWE/CWE-193/InvalidPointerDeref.expected
cpp/ql/test/query-tests/Security/CWE/CWE-193/test.cpp

In https://github.com/github/codeql/pull/10555 I added very specialized code to the range analysis library to catch a very specific pattern motivated by https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-10160. This worked really well to convince ourselves that this query can catch real-world issues. Unfortunately, using a value number as an SSA variable gives some weird results because GVN doesn't behave as SSA would.
This PR basically reverts the above PR. We can then figure out how to properly do this once @aschackmull is done with his ongoing work on sharing the range analysis code between C/C++ and Java.

C++: Don't use GVN as SSAVariable in new range analysis

---

csharp/ql/integration-tests/posix-only/dotnet_test/dotnet_test.csproj
csharp/ql/integration-tests/posix-only/dotnet_test/test.py
csharp/tools/tracing-config.lua

If an absolute path is provided for a `.dll` or `.exe` file on an OS where slashes `/` are used as directory path separators then the tracer fails to identify that `dotnet test` shouldn't inject the `-p:UseSharedCompilation=false` (as the call is directly delegated to `vstest` and doesn't include any compilation).
This is fixed in this PR.

C#: Tracer improvement for `dotnet test`

---

go/Makefile

This changes the default build target we use to build the go extractor to use the per-platform targets (requires internal change to follow up). This also builds the macos target as universal binary.

Restructure go Makefile: Build the per-platform target.

---

swift/ql/lib/change-notes/2023-11-01-field-sinks.md
swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPublic.qll
swift/ql/test/query-tests/Security/CWE-078/CommandInjection.expected
swift/ql/test/query-tests/Security/CWE-078/CommandInjection.swift

Fix a bug in the `defaultImplicitTaintRead` mechanism for reading from field access paths at sinks.  Assuming `source()` is a taint source and `Mid.field` is a sink (say, defined through models-as-data), consider:
```
class Base { }
class Mid : Base {
var field : String
}
class Derived : Mid {
}
...
base.field = source() // case 1
mid.field = source() // case 2
derived.field = source() // case 3
```
- case 1 is impossible, as `Base` does not have a `field`.
- case 2 is the normal case.  Taint flows from `source()` to the access of `mid` with an access path for `.field`.  `defaultImplicitTaintRead` recognizes that the sink is an access to `Mid` and permits any field of `Mid` to be stripped off the access path, and we get a result.
- in case 3, once again taint flows from `source()` to the …

Swift: Fix defaultImplicitTaintRead on fields

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticExprSpecific.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticSSA.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisImpl.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeUtils.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/SignAnalysisCommon.qll
java/ql/lib/semmle/code/java/dataflow/RangeAnalysis.qll
java/ql/lib/semmle/code/java/dataflow/RangeUtils.qll
java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/ModulusAnalysisSpecific.qll
java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/SignAnalysisSpecific.qll
shared/rangeanalysis/codeql/rangeanalysis/ModulusAnalysis.qll
shared/rangeanalysis/codeql/rangeanalysis/RangeAnalysis.qll
shared/rangeanalysis/codeql/rangeanalysis/internal/RangeUtils.qll

This should ideally be completely semantics-preserving as a straight refactor, but there was some weirdness around C++ SSA variables, which makes that claim non-trivial, so let's see what DCA says.
Also, I've duplicated a predicate in `SignAnalysisSpecific.qll` in order to avoid C# changes in this PR - that cleanup will follow in a later PR.

Java/C++/RangeAnalysis: Move SsaReadPosition to shared qlpack.

---

javascript/extractor/lib/typescript/BUILD.bazel

This pull request includes a single change to the `javascript/extractor/lib/typescript/BUILD.bazel` file to reorder the `PATH` environment variable in the `genrule(` function. This ensures that the `node` executable is found in the correct location when running `npm run` commands.

Take our node, not the one that comes first on the PATH.

---

cpp/ql/lib/semmle/code/cpp/models/implementations/Gets.qll
cpp/ql/test/query-tests/Security/CWE/CWE-114/semmle/UncontrolledProcessOperation/UncontrolledProcessOperation.expected
cpp/ql/test/query-tests/Security/CWE/CWE-114/semmle/UncontrolledProcessOperation/test.cpp

Also add the test that exposed this. Note that the test would only have started failing after `cpp/uncontrolled-process-operation` with the rewrite of the query away from default taint tracking, which has not happened yet.

C++: Fix `hasRemoteFlowSource` for `fgets`

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
cpp/ql/test/library-tests/syntax-zoo/dataflow-ir-consistency.expected

The logic for handling indirections of global variables was all wrong 😭. This PR hopefully fixes this logic 🤞.
The first commit adds a bunch of tests. I've then split the fix into a sequence of small commits. Finally, the last commit accepts the test changes.
There are a couple of new inconsistencies regarding missing `toString` on some esoteric syntax. I haven't investigated those yet, but I don't think they should block this PR.
@jketema I'm requesting a review from you because you initially identified these missing steps. Let me know what I can do to help the review process here!

C++: Fix indirect global-variable flow

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll

This PR simply moves a couple of predicates from `DataFlow::Node` subclasses to a shared base class. It should not cause any observable changes (other than changing `toString`s on `Node0Impl`).

C++: Move a couple of predicates to `Node0Impl`

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisConstantSpecific.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisImpl.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisRelativeSpecific.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeUtils.qll
java/ql/lib/semmle/code/java/dataflow/RangeAnalysis.qll
java/ql/lib/semmle/code/java/dataflow/RangeUtils.qll
java/ql/test/library-tests/dataflow/modulus-analysis/ModulusAnalysis.expected
java/ql/test/library-tests/dataflow/range-analysis/RangeAnalysis.expected
shared/rangeanalysis/codeql/rangeanalysis/ModulusAnalysis.qll
shared/rangeanalysis/codeql/rangeanalysis/RangeAnalysis.qll
shared/rangeanalysis/codeql/rangeanalysis/internal/RangeUtils.qll

This moves 3 more predicates to the shared qlpack.
The few additional range analysis tuples for java are harmless bounds for `LocalVariableDeclExpr`s, which don't really need bounds, but it's simpler to just accept them as they are now handled uniformly as `CopyValueExpr`s.

Java/C++/Rangeanalysis: Share more range analysis utility predicates.

---

swift/extractor/infra/SwiftTagTraits.h

Doesn't really change anything except updating the TODOs.

Swift: do not extract non-AST types, NFC

---

cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/UnboundedWrite.expected
cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/tests.cpp

I spent so long wondering why the test I added wasn't detected. In the end, it turned out this was because a function call that dominates the test I added was non-terminating, and thus the CFG containing any of the later tests was pruned away 😂.

C++: Fix nonterminating test

---

cpp/autobuilder/Semmle.Autobuild.Cpp.Tests/BuildScripts.cs
csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs
csharp/autobuilder/Semmle.Autobuild.Shared/BuildActions.cs
csharp/autobuilder/Semmle.Autobuild.Shared/MsBuildRule.cs

The autobuilder was checking if the process was on ARM macos, and executed `dotnet msbuild` instead of `msbuild` if so. However, we execute an x64 dotnet binary on an ARM machine, so the execution platform reported is x64, which in turn leads to running `msbuild`, and not `dotnet msbuild`. Instead of checking the execution platform, we're now checking the host operating system, as that's relevant to whether the mono installation has msbuild or not.

C#: Change IsARM to Apple silicon check

---

csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget/skip-on-platform-osx-arm

The test is failing currently, and that needs further investigation. This is a temporary workaround to allow us to continue to work on some necessary infrastructure investments around these tests.

Disable the nuget standalone dependencies test on ARM-osx.

---

cpp/ql/src/Security/CWE/CWE-120/UnboundedWrite.ql
cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/UnboundedWrite.expected
cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/tests.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/UnboundedWrite.expected

I had missed this issue in https://github.com/github/codeql/pull/14669.
The problem was that every sink was marked as an out barrier. I did this to avoid path duplication when the outgoing argument was marked as a sink to continue to flag up cases such as:
```cpp
char buffer[1024];
gets(buffer);
```
However, marking all sinks are out barriers was slightly too aggressive (as seen in the first commit). This is because the query also flags up writes fields when the _qualifier_ of the field is tainted. That is, this is also flagged up:
```cpp
S* s = tainted_struct();
strcpy(buffer, s->field);
```
so both `struct` _and_ `s->field` are marked as sinks. But since we mark every sink as an out barrier we'd mark `s` as a barrier, and thus we'd never get a to the read step required to catch …

C++: Fix missing results in `cpp/unbounded-write`

---

cpp/ql/lib/change-notes/2023-11-15-return-stack-allocated-memory.md
cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql
cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnStackAllocatedMemory/ReturnStackAllocatedMemory.expected
cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnStackAllocatedMemory/test.cpp

@andersfugmann reminded me that there's an evil family of functions that return stack-allocated memory, and that our `cpp/return-stack-allocated-memory` query isn't aware of these. This PR fixes this problem.

C++: Catch more returns of stack-allocated memory

---

csharp/extractor/Semmle.Extraction.CSharp/Populators/TypeContainerVisitor.cs
csharp/ql/test/library-tests/standalone/assemblyattribute/attr.expected
csharp/ql/test/library-tests/standalone/assemblyattribute/attr.ql
csharp/ql/test/library-tests/standalone/assemblyattribute/options
csharp/ql/test/library-tests/standalone/assemblyattribute/standalone.cs

This PR tries to fix assembly attribute extraction in standalone mode. I can't reliably repro the issue, but occasionally we're seeing the below exception:
```
Exception has occurred: CLR/System.ArgumentOutOfRangeException
Exception thrown: 'System.ArgumentOutOfRangeException' in Microsoft.CodeAnalysis.dll: 'Specified argument was out of the range of valid values.'
at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.get_Item(Int32 index)
at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.Enumerator.get_Current()
at Semmle.Extraction.CSharp.Populators.TypeContainerVisitor.VisitAttributeList(AttributeListSyntax node) in .../ql/csharp/extractor/Semmle.Extraction.CSharp/Populators/TypeContainerVisitor.cs:line 92
```
I don't know if this fix is really fixing the problem, but it avoids using …

C#: Fix assembly attribute extraction in standalone mode

---

ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll
ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected
ruby/ql/test/library-tests/dataflow/array-flow/array-flow.ql
ruby/ql/test/library-tests/dataflow/array-flow/array_flow.rb
ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected
ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.ql
ruby/ql/test/library-tests/dataflow/hash-flow/hash_flow.rb

Removes the requirement that the `Hash`/`Array` reference must be qualified with `::`.

Ruby: Include more nodes in `{Hash,Array}LiteralCfgNode`

---

cpp/ql/src/Security/CWE/CWE-190/IntegerOverflowTainted.ql
cpp/ql/test/query-tests/Security/CWE/CWE-190/SAMATE/IntegerOverflowTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/IntegerOverflowTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-197/SAMATE/IntegerOverflowTainted/IntegerOverflowTainted.expected

This PR is very much like https://github.com/github/codeql/pull/14784. There are so many results for this query that it's very difficult to go through all the changes. I've gone through some of the ones with the highest query result difference, and most of them are lost results arising from the same reason as in https://github.com/github/codeql/pull/14784.

C++: Convert `cpp/integer-overflow-tainted` away from DefaultTaintTracking

---

docs/codeql/codeql-for-visual-studio-code/using-the-codeql-model-editor.rst

Hey 👋 
I noticed this yesterday when I compared my VS Code settings for the CodeQL model editor with the [documentation](https://codeql.github.com/docs/codeql-for-visual-studio-code/using-the-codeql-model-editor/).
The property seems to be named `codeQL.runningQueries.useExtensionPacks` and not `codeQL.runningQueries.useModelPacks`. (I think the name was discussed at one point; in the [code of the VS Code](https://github.com/github/vscode-codeql) extension it doesn't appear currently. )
But more importantly: It works as expected with `codeQL.runningQueries.useExtensionPacks` being set to `all`.

Doc: Fix name of VS Code settings property to use extension packs

---

csharp/ql/integration-tests/all-platforms/dotnet_pack/test.py
csharp/ql/integration-tests/posix-only/dotnet_test_mstest/dotnet_test_mstest.csproj

After the runners have been updated to a newer version of dotnet, some of the integration tests have started to fail. These are fixed in this PR.

C#: Fix integration test failures after dotnet upgrade on runners.

---

java/kotlin-extractor/build.py
java/kotlin-extractor/kotlin_plugin_versions.py

We now have a proper class to represent versions, rather than using tuples. The version is passed deeper down, so we can now have version-dependent compilation flags.

Kotlin: Build: Refactor version handling

---

shared/typetracking/codeql/typetracking/TypeTracking.qll
shared/typetracking/codeql/typetracking/internal/TypeTrackingImpl.qll

Needed for Ruby, where we will allow for (irrelevant) post-update use-use steps where the origin node is not a local source node.

Type tracking: Parameterize consistency checks

---

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt

The AST when the parent class is a file class is different in Kotlin 2 mode.

Kotlin: Fix findTopLevelFunctionOrWarn for Kotlin 2

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/TestBase.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp

In https://github.com/github/codeql/pull/14736 we fixed a bunch of problems related to tracking indirections of global variables. One thing we forgot to handle was the subtle semantic difference between pointer types and array types. This PR fixes this by special-casing `ArrayType` similar to what we've been doing for SSA for a [long time](https://github.com/github/codeql/blob/main/cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll#L875).
The first commit adds a lot of tests. I basically threw in any combination of direct/indirect and static local/global tests I could think of. The second PR fixes the tests that were failing by doing the above handlign of array types.
DCA looks uneventful. The first run showed no changes in performance/results. The second run (which …

C++: Fix global-variable flow for array types

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/test/library-tests/dataflow/local/Nodes.expected

This PR removes some irrelevant data flow nodes and edges, reported by the consistency checks of the shared type tracking library:
- Only add flow-insensitive variable capture steps in type tracking when there is both a read and a write.
- Limit `ReturningNode`s to those that may actually return a value.
- Restrict `Synth(Hash)SplatArgumentNode`s  to those into which we may actually do an implicit store.
- Limit `HashSplatContent`s to symbols, as only symbols can be mapped to parameters.

Ruby: Prune irrelevant data flow nodes and edges

---

cpp/ql/src/Security/CWE/CWE-190/ArithmeticWithExtremeValues.ql

This PR gets rid of the final low-precision CWE-190 query that uses `DefaultTaintTracking`. Like previous PRs, I've simply ported over the barriers from `DefaultTaintTracking`. MRVA shows relatively few alert differences with the most extreme one being 52 lost results on https://github.com/esheldon/fitsio out of 27000 alerts 😂.
And all the lost results on that project seems to be because of pointer/pointee conflation that's now resolved.

C++: Convert `cpp/arithmetic-with-extreme-values` away from `DefaultTaintTracking`

---

csharp/ql/integration-tests/all-platforms/dotnet_pack/test.py
csharp/ql/integration-tests/posix-only/dotnet_test_mstest/dotnet_test_mstest.csproj

Backporting #14825 to rc/3.11 branch so that the C# tests can start passing again.

Backport PR #14825

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/Assets.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyContainer.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FrameworkPackageNames.cs
csharp/extractor/Semmle.Extraction.Tests/Assets.cs

In this PR we introduce assets.json unit tests for six representative target frameworks (that behaves slightly differently when generating assets files and how to list dependencies).
The frameworks are: `net70`, `net4.8`, `netstandard2.1`, `netstandard1.6`, `netcoreapp2.0`, `netcoreapp3.1`
As an outcome of introducing the tests, we also introduce the following improvements/modifications to the assets parser.
- Inspecting the `frameworkReferences` section of the `project.assets.json` files to identify which frameworks are being used (this is relevant for some of the target frameworks from the above list - but not all).
- If a *package* from the `target` section in the `project.assets.json` file contains a `compile` section we only include what is in the compile section (also for …

C#: Framework dependency detection.

---

go/ql/lib/change-notes/2023-11-15-bug-fix-value-flow-in-slice-expression.md
go/ql/lib/semmle/go/dataflow/internal/ContainerFlow.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll
go/ql/test/library-tests/semmle/go/dataflow/ArrayConversion/main.go
go/ql/test/library-tests/semmle/go/dataflow/SliceExpressions/Flows.ql
go/ql/test/library-tests/semmle/go/dataflow/SliceExpressions/main.go
go/ql/test/query-tests/Security/CWE-078/CommandInjection.expected

Previously we were relying on taint flow only.

Go: model value flow with array content through slice expressions

---

CODEOWNERS

The second one is added by https://github.com/github/codeql/pull/14833.

Kotlin: Add more CODEOWNERS entries

---

python/ql/test/experimental/dataflow/use-use-flow/read_explosion.py
python/ql/test/experimental/dataflow/use-use-flow/use-use-counts.expected
python/ql/test/experimental/dataflow/use-use-flow/use-use-counts.ql

Or for a data flow node filling that role, at least.

Python: Test demonstrating the need for phi-read-nodes

---

csharp/ql/lib/semmle/code/csharp/security/dataflow/flowsinks/ExternalLocationSink.qll
csharp/ql/test/library-tests/standalone/externalLocationSink/externalLocationSink.expected
csharp/ql/test/library-tests/standalone/externalLocationSink/externalLocationSink.ql
csharp/ql/test/library-tests/standalone/externalLocationSink/options
csharp/ql/test/library-tests/standalone/externalLocationSink/standalone.cs

In the standalone mode, we're automatically adding implicit usings to the compilation. If we detect any web application in the repo, we're adding the asp.net core specific implicit usings, which include `Microsoft.Extensions.Logging`. This namespace contains `ILogger`, which is quite a common name, and oftentimes conflict with `ILogger` interfaces defined in the repo. As a result, we're facing ambiguities in the standalone extracted compilation, and we end up with an incomplete DB. This PR adjusts the `LogMessageSink` class to work in cases when "logger-like" method calls have no extracted target.

C#: Tolerate missing call targets in LogMessageSink

---

swift/ql/src/change-notes/released/0.3.3.md

Update original change note in line with the change here: https://github.com/github/codeql/pull/14876#discussion_r1402142306

Update change note 0.3.3.md

---

cpp/ql/src/Security/CWE/CWE-134/UncontrolledFormatString.ql
cpp/ql/test/query-tests/Security/CWE/CWE-134/SAMATE/UncontrolledFormatString.expected
cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/argv/argvLocal.c
cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/argv/argvLocal.expected
cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/funcs/funcsLocal.expected
cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/globalVars/UncontrolledFormatString.expected
cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/ifs/ifs.expected

For discussion of MRVA results see internal issue. The alerts lost on vim in DCA seem related to pointer/pointee conflation.
I'll fix up the internal tests once we're ok with this PR.

C++: Rewrite `cpp/tainted-format-string` away from `DefaultTaintTracking`

---

javascript/ql/src/CHANGELOG.md
javascript/ql/src/change-notes/released/0.8.3.md

A late implementation of this comment from docs: https://github.com/github/codeql/pull/14876#discussion_r1402144127

JS: update the JS change notes to mention security severity instead of just severity

---

cpp/ql/src/Security/CWE/CWE-170/ImproperNullTerminationTainted.ql
cpp/ql/test/query-tests/Likely Bugs/Memory Management/ImproperNullTermination/ImproperNullTerminationTainted.expected

This query logic in this query was kinda odd. The query starts by tracking flow from a subset of flow sources (the ones that can leave the variable with a non-zero terminated string) to a specific kind of `VariableAccess` (places where we know a zero-terminated string is expceted). That's all well and good. The problem is that, to weed out false positives, the query adds barrier logic to the query by reinventing a query-specific dataflow library. This dataflow library is implemented as a less-than-ideal transitive closure over the old `exprDefinition` predicate from [DefinitionsAndUses library](https://github.com/github/codeql/blob/main/cpp/ql/lib/semmle/code/cpp/controlflow/DefinitionsAndUses.qll#L279).
This PR rewrites the query to be a standard taint-tracking query. This is not totally …

C++: Rewrite `cpp/user-controlled-null-termination-tainted` away from `DefaultTaintTracking`

---

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.11.0.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.15.0.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.15.3.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.7.5.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.8.0.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.9.3.rst

Fixes several generator bugs:
* The same unordered list with multiple different markers is no longer mangled into a single line (see 2.11.0, 2.8.0)
* A major aggregator bug led to category header confusion and bullets ended up in the wrong category, this is now fixed (see 2.15.0)
* List continuation parser logic led to skipped tokens, now fixed (see 2.15.3)
* Difficult nested backticks are now rendered as literals, and dangling whitespace is handled correctly (see 2.15.3)
* Inline code no longer produces HTML entities (see 2.7.5)

Fix changelog docs based on latest generator version

---

cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/constant/ConstantAnalysis.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/constant/ConstantAnalysis.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedCondition.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedElement.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/constant/ConstantAnalysis.qll
cpp/ql/test/library-tests/controlflow/guards-ir/tests.expected
cpp/ql/test/library-tests/ir/ir/aliased_ir.expected
cpp/ql/test/library-tests/ir/ir/operand_locations.expected
cpp/ql/test/library-tests/ir/ir/raw_ir.expected
cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/ifs/ifs.expected

This PR changes IR generation negations in conditional branches to generate a `LogicalNot` instruction instead of swapping the branches. While swapping the branches is technically correct, it means that we don't always have an instruction (and hence: a dataflow node) that computes result of the conditional expression.
For example, on the following snippet:
```cpp
if(!b) {
foo();
} else {
bar();
}
```
we would generate:
```cpp
Block 0
r4_5(glval<bool>) = VariableAddress[b]     :
m4_6(bool)        = InitializeParameter[b] : &:r4_5
r5_1(glval<bool>) = VariableAddress[b]     :
r5_2(bool)        = Load[b]                : &:r5_1
v5_3(void)        = ConditionalBranch      : r5_2
False -> Block 1
True -> Block 2
Block 1
r6_1(glval<unknown>) = FunctionAddress[foo] :
v6_2(void)           = …
```

C++: Don't short circuit logical negation in conditions

---

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
java/kotlin-extractor/src/main/kotlin/LinesOfCode.kt
java/kotlin-extractor/src/main/kotlin/LinesOfCodePSI.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_5_0/LinesOfCodeLighterAST.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_9_0-Beta/CommentExtractorLighterAST.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_9_0-Beta/LinesOfCodeLighterAST.kt
java/ql/integration-tests/all-platforms/kotlin/extractor_information_kotlin2/ExtractorInformation.expected

Works similar to the way comment extraction works.
Fixes the numlines kotlin2 test.

Kotlin: Add LighterAST support to numlines extraction

---

ruby/ql/test/library-tests/dataflow/global/Flow.expected
ruby/ql/test/library-tests/dataflow/global/blocks.rb

We seem to be missing flow in cases like this
```rb
class A
def m1(&block)
r = block.call()
sink r
end
end
A.new.m1 { source(1) }
```

Ruby: Add test for missing block flow

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TaintTrackingUtil.qll
cpp/ql/src/Security/CWE/CWE-807/TaintedCondition.ql
cpp/ql/test/query-tests/Security/CWE/CWE-807/semmle/TaintedCondition/TaintedCondition.expected

The final step in undoing the workaround in https://github.com/github/codeql/pull/14886/files#diff-40e2016a464c1cf96ccb2a7469f1d6d2da1768ab2f355c8beb3bd0050ecd6a18R31 we add taint-flow through the implicit integer to boolean cast generated in a snippet such as:
```cpp
int x = some_int();
if(!x) { ... }
```
This is necessary because we generate IR that's equivalent to:
```cpp
int x = some_int();
if(!(x != 0)) { ... }
```
and since we already have taint-flow from `x` to `!x`, the additional taint from `x` to `x != 0` ensures that we get flow to the result of the condition.

C++: Add Taint through int -> bool casts

---

cpp/ql/lib/semmle/code/cpp/models/implementations/Getenv.qll
cpp/ql/lib/semmle/code/cpp/models/implementations/Gets.qll
cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected
cpp/ql/test/query-tests/Security/CWE/CWE-807/semmle/TaintedCondition/TaintedCondition.expected

All disappearing DCA results look ok (I spot checked the systemd ones), and follow the pattern:
```cpp
x = getenv(...);
strcpy(y, x);
strcpy(z, y);
```
Before we got flow to the second strcpy, because we were looking at x directly, and not its indirection.

C++: Do not use `isReturnValue` in `getenv`, `gets`, and `fgets` models

---

cpp/ql/src/Security/CWE/CWE-290/AuthenticationBypass.ql

This is no longer needed after https://github.com/github/codeql/pull/14894 and https://github.com/github/codeql/pull/14904

C++: Remove workaround for negated conditions in `cpp/user-controlled-bypass`

---

swift/ql/lib/change-notes/2023-11-22-contentsof.md
swift/ql/lib/codeql/swift/frameworks/Frameworks.qll
swift/ql/lib/codeql/swift/frameworks/Heuristic.qll
swift/ql/test/library-tests/dataflow/flowsources/custom.swift

Adds a simple heuristic matching of "contentsOf" functions as flow sources in Swift code.  In practice many of the sources found by this heuristic are already modelled - `Data(contentsOfFile:)` is especially common.  But we now catch some more obscure stuff as well, e.g. [`NSDictionary(contentsOf:)`](https://developer.apple.com/documentation/foundation/nsdictionary/1416069-init), [`NSImage(contentsOf:)`](https://developer.apple.com/documentation/appkit/nsimage/1519907-init), [`NSArray(contentsOfFile:)`](https://developer.apple.com/documentation/foundation/nsarray/1413844-init) and [`AVAudioPlayer(contentsOf:)`](https://developer.apple.com/documentation/avfaudio/avaudioplayer/1387281-init)...

Swift: "contentsOf" sources

---

cpp/ql/src/Security/CWE/CWE-114/UncontrolledProcessOperation.ql
cpp/ql/src/Security/CWE/CWE-134/UncontrolledFormatString.ql
cpp/ql/src/Security/CWE/CWE-290/AuthenticationBypass.ql

This should not be needed anymore now that #14903 is merged 🤞

C++: Don't exclude `ExprNode`s as sources

---

swift/ql/lib/codeql/swift/StringFormat.qll
swift/ql/lib/codeql/swift/security/UncontrolledFormatStringExtensions.qll
swift/ql/src/change-notes/2023-11-16-format-string.md
swift/ql/test/query-tests/Security/CWE-134/UncontrolledFormatString.expected
swift/ql/test/query-tests/Security/CWE-134/UncontrolledFormatString.swift

More sinks for `swift/uncontrolled-format-string`:
- sinks for [`NSMutableString.appendFormat(_:_:)`](https://developer.apple.com/documentation/foundation/nsmutablestring/1415629-appendformat) and [`StringProtocol.appendingFormat(_:_:)`](https://developer.apple.com/documentation/swift/stringprotocol/appendingformat(_:_:)).
- sink for imported C `printf` functions.
- heuristic sink for things that look like formatting functions.

Swift: More sinks for swift/uncontrolled-format-string

---

swift/ql/lib/codeql/swift/security/SqlInjectionExtensions.qll
swift/ql/src/change-notes/2023-11-14-sql-injection.md
swift/ql/test/query-tests/Security/CWE-089/SqlInjection.expected
swift/ql/test/query-tests/Security/CWE-089/other.swift

Add heuristic sinks for the `swift/sql-injection` query.  I tried some more sophisticated rules, but in this case simpler was better.  Had to fix a performance issue with the `ParamDecl` bit.

Swift: Heuristic sinks for swift/sql-injection

---

javascript/ql/src/DOM/TargetBlank.ql
javascript/ql/src/change-notes/2023-11-28-django-urls.md
javascript/ql/test/query-tests/DOM/TargetBlank/tst.js

Django URLs are currently not detected, but flask and nunjucks URL are.
This fixes https://github.com/github/codeql/issues/12267. See the issue for more information.

JS: Add django template urls as "save urls"

---

docs/codeql/reusables/supported-versions-compilers.rst

Support was added in https://github.com/github/codeql/pull/14636

Docs: List Python 3.12 as supported

---

swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected

This moves the read and write steps on keypath nodes so that the component node is the destination of the read and source of the write, rather than being the source of the read and destination of the write. This means that the type of the dataflow node matches the type that the read/write implies, which will be important when type pruning is added.

Swift: move keypath dataflow writes to fix types

---

javascript/ql/src/Security/CWE-327/BadRandomness.ql

Our style guide states that names should not end in a period. I'm updating this now to allow us to automate a process for GitHub docs, see: https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md#query-name-name

Remove unwanted period from query name

---

python/ql/lib/change-notes/2023-11-27-tarfile-extraction-filters.md
python/ql/lib/semmle/python/security/dataflow/TarSlipCustomizations.qll
python/ql/test/query-tests/Security/CWE-022-TarSlip/TarSlip.expected
python/ql/test/query-tests/Security/CWE-022-TarSlip/tarslip.py

Adds support for extraction filters as defined in https://peps.python.org/pep-0706/ and implemented in Python 3.12.
By my reading, setting the filter to `'data'` or `'tar'` is probably safe, whereas `'fully_trusted'` or the default (which is the same as `None`) is not.
For now, I have just added this modelling to the tarslip query. We could also share it with the modelling of `shutil.unpack_archive` (which has also gained a `filter` argument), but it was unclear to me where we should put this modelling in that case. Perhaps the best solution would be to merge the experimental `py/tarslip-extended` query into the existing query (in which case the current location is perhaps not too bad).

Python: Add support for extraction filters

---

csharp/ql/lib/semmle/code/csharp/Callable.qll
csharp/ql/lib/semmle/code/csharp/ExprOrStmtParent.qll
csharp/ql/lib/semmle/code/csharp/File.qll
csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/FlowSummary.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.cs
csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.expected

Previously, we would assume that calls to library methods would invoke their passed delegates. This is now generalized to include any method without a body (i.e., also abstract methods and interface methods).

C#: Strengthen call-back heuristics by considering body-less methods

---

csharp/ql/src/Security Features/CWE-639/InsecureDirectObjectReference.ql
csharp/ql/src/experimental/Security Features/CWE-759/HashWithoutSalt.ql
java/ql/src/experimental/Security/CWE/CWE-073/FilePathInjection.ql
java/ql/src/experimental/Security/CWE/CWE-552/UnsafeUrlForward.ql
java/ql/src/experimental/Security/CWE/CWE-625/PermissiveDotRegex.ql

Most tags use the "external/cwe/cwe-xxx" format, except for these few queries. Updating them for consistency (even though most of them are experimental).
Noticed in passing while we were adding a process for GitHub docs to automatically pull in query lists with their associated CWEs.

Update inconsistent CWE tags

---

java/ql/lib/change-notes/2023-11-29-new-spring-models.md
java/ql/lib/ext/org.springframework.cloud.config.server.environment.model.yml
java/ql/lib/ext/org.springframework.core.io.model.yml
java/ql/lib/ext/org.springframework.web.util.model.yml
java/ql/test/library-tests/frameworks/spring/webutil/Test.java

This PR adds a `path-injection` sink for `org.springframework.core.io.Resource#createRelative(String)` and a source for `org.springframework.web.util.UrlPathHelper#getPathWithinApplication` in order to cover CVE-2019-3799.
Additional `UrlPathHelper` sources are also added and their existing taint steps are removed. Let me know if anything looks wrong with these changes.

Java: add Spring models

---

go/ql/test/query-tests/InconsistentCode/UnhandledCloseWritableHandle/UnhandledCloseWritableHandle.expected
go/ql/test/query-tests/InconsistentCode/UnhandledCloseWritableHandle/tests.go

I found this test hard to reason about from the `.expected` file so I reorganized it. I also added in calls to a function which was otherwise uncalled, which seems to be intended to check that we don't find a result when the deferred function returns the error.

Go: improve test unhandled close writable handle

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/AssemblyCacheExtensions.cs
csharp/ql/integration-tests/posix-only/standalone_dependencies/Assemblies.expected
csharp/ql/integration-tests/windows-only/standalone_dependencies/Assemblies.expected

This PR is changing the sorting of conflicting assemblies. Assembly version now takes precedence over .net core version.

C#: Prefer assembly version over netcore version in conflict resolution

---

csharp/ql/lib/semmle/code/csharp/security/dataflow/UrlRedirectQuery.qll
csharp/ql/src/change-notes/2023-11-29-url-redirect-false-positive.md
csharp/ql/test/library-tests/dataflow/flowsources/remote/remoteFlowSource.ql
csharp/ql/test/query-tests/Security Features/CWE-601/UrlRedirect/UrlRedirect.cs
csharp/ql/test/query-tests/Security Features/CWE-601/UrlRedirect/UrlRedirect.expected
csharp/ql/test/resources/stubs/System.Web.cs

C#: Fix a URL redirection from remote source false positive

---

config/identical-files.json
ruby/ql/consistency-queries/TypeTrackingConsistency.ql
ruby/ql/lib/change-notes/2023-11-21-new-type-tracking-lib.md
ruby/ql/lib/codeql/ruby/ApiGraphs.qll
ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/lib/codeql/ruby/frameworks/XmlParsing.qll
ruby/ql/lib/codeql/ruby/frameworks/rack/internal/App.qll
ruby/ql/lib/codeql/ruby/frameworks/rack/internal/Response.qll
ruby/ql/lib/codeql/ruby/regexp/internal/RegExpTracking.qll
ruby/ql/lib/codeql/ruby/security/InsecureDownloadCustomizations.qll
ruby/ql/lib/codeql/ruby/security/OpenSSL.qll
ruby/ql/lib/codeql/ruby/security/StackTraceExposureCustomizations.qll
ruby/ql/lib/codeql/ruby/security/UnsafeCodeConstructionCustomizations.qll
ruby/ql/lib/codeql/ruby/security/UnsafeHtmlConstructionCustomizations.qll
ruby/ql/lib/codeql/ruby/security/UnsafeShellCommandConstructionCustomizations.qll
ruby/ql/lib/codeql/ruby/typetracking/ApiGraphShared.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTracker.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll
ruby/ql/lib/codeql/ruby/typetracking/TypeTracking.qll
ruby/ql/lib/codeql/ruby/typetracking/internal/TypeTrackingImpl.qll
ruby/ql/test/TestUtilities/InlineTypeTrackingFlowTest.qll
ruby/ql/test/library-tests/dataflow/array-flow/type-tracking-array-flow.expected
ruby/ql/test/library-tests/dataflow/hash-flow/type-tracking-hash-flow.expected
ruby/ql/test/library-tests/dataflow/params/TypeTracker.expected
ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.ql

This PR switches out the existing type tracking library, `codeql.ruby.typetracking.TypeTracker.qll`, with a new library based on the shared type tracking library, exposed as `codeql.ruby.typetracking.TypeTracking.qll`. The old type tracking library has been deprecated.
The consistency checks of the shared type tracking library revealed a lot of issues, which have been fixed on https://github.com/github/codeql/pull/14787, but also some here:
- Consider any (non-parameter) implicit SSA write definition a local source node, for example local exception variables introduced in `rescue` clauses.
- Consider any target of a store (including with(out)-content checks) to be a local source node. (This is what results in the improved expected test output.)

Ruby: Adopt shared type tracking library

---

go/ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.go
go/ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.ql
go/ql/test/query-tests/Security/CWE-681/Test32BitArchitectureBuildConstraintInFileName_386.go
go/ql/test/query-tests/Security/CWE-681/Test32BitArchitectureBuildConstraints.go
go/ql/test/query-tests/Security/CWE-681/Test64BitArchitectureBuildConstraintInFileName_amd64.go
go/ql/test/query-tests/Security/CWE-681/Test64BitArchitectureBuildConstraints.go
go/ql/test/query-tests/Security/CWE-681/TestNoArchitectureBuildConstraints.go
go/ql/test/query-tests/Security/CWE-681/TestOldBuildConstraints.go

We changed the test query when the query was changed so that the comments in the test file would stay the same.
I've reverted the test query and updated the comments in the test file. This avoids problems in the branch switching to use-use flow.

Go: Improve tests for Incorrect Integer Conversion

---

swift/ql/lib/codeql/swift/frameworks/StandardLibrary/WebView.qll

Simplify `AdoptsWkNavigationDelegate` in `WebView.qll`.  As promised (quite a while ago) in https://github.com/github/codeql/pull/12044/files#r1091832015 .

Swift: Simplify AdoptsWkNavigationDelegate in WebView.qll.

---

cpp/ql/lib/DefaultOptions.qll

Observed this attribute while working on coding standards test regression when replacing Guards by IRGuards.

C++: Also support the `__noreturn__` attribute in `exits`

---

csharp/extractor/Semmle.Extraction.CSharp.StubGenerator/StubVisitor.cs
csharp/ql/test/resources/stubs/_frameworks/Microsoft.NETCore.App/System.Memory.cs
csharp/ql/test/resources/stubs/_frameworks/Microsoft.NETCore.App/System.Runtime.cs

This PR adds some missing attributes to stubs. These attributes are needed for interpolated string handlers being properly considered by Roslyn.

C#: Add interpolated string handler attributes to generated stubs

---

swift/ql/lib/change-notes/2023-12-07-closure-models.md
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Array.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Data.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/PointerTypes.qll
swift/ql/test/library-tests/dataflow/taint/libraries/unsafepointer.swift

Model "Manual Memory Management" closure functions such as (classless) `withUnsafePointer`.  Model `withMemoryRebound` and similar methods on the various pointer classes.
Note that results aren't great on the tests involve `.pointee`.  Some non-trivial work is needed to fix them and I've created an issue to track that.

Swift: Model Manual Memory Management closure functions and withMemoryRebound variants

---

ruby/ql/lib/codeql/ruby/frameworks/core/Gem.qll
ruby/ql/lib/codeql/ruby/security/CodeInjectionCustomizations.qll
ruby/ql/lib/codeql/ruby/security/CommandInjectionCustomizations.qll
ruby/ql/lib/codeql/ruby/security/LogInjectionQuery.qll
ruby/ql/lib/codeql/ruby/security/PathInjectionCustomizations.qll
ruby/ql/lib/codeql/ruby/security/SqlInjectionCustomizations.qll
ruby/ql/lib/codeql/ruby/security/UrlRedirectCustomizations.qll
ruby/ql/src/queries/modeling/GenerateModel.ql
ruby/ql/src/utils/modeleditor/ApplicationModeEndpoints.ql
ruby/ql/src/utils/modeleditor/FrameworkModeEndpoints.ql
ruby/ql/src/utils/modeleditor/ModelEditor.qll
ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeEndpoints.expected
ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeEndpoints.qlref
ruby/ql/test/query-tests/utils/modeleditor/lib/module.rb
ruby/ql/test/query-tests/utils/modeleditor/lib/mylib.rb
ruby/ql/test/query-tests/utils/modeleditor/lib/other.rb
ruby/ql/test/query-tests/utils/modeleditor/mylib.gemspec
ruby/ql/test/query-tests/utils/modeleditor/other_lib/lib/other_gem.rb
ruby/ql/test/query-tests/utils/modeleditor/other_lib/other_lib.gemspec

Prototype support for working with Ruby models in the model editor.

Ruby: Experimental model editor support

---

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointCharacteristics.qll
javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/ExtractMisclassifiedEndpointFeatures.ql
javascript/ql/experimental/adaptivethreatmodeling/test/endpoint_large_scale/FilteredTruePositives.ql
javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll
javascript/ql/lib/semmle/javascript/dataflow/TypeInference.qll
javascript/ql/lib/semmle/javascript/frameworks/AngularJS/DependencyInjections.qll
javascript/ql/lib/semmle/javascript/frameworks/Express.qll
javascript/ql/lib/semmle/javascript/security/dataflow/LoopBoundInjectionQuery.qll
javascript/ql/lib/semmle/javascript/security/dataflow/PrototypePollutionCustomizations.qll
javascript/ql/lib/semmle/javascript/security/dataflow/PrototypePollutionQuery.qll
javascript/ql/src/meta/analysis-quality/UnmodelledSteps.ql
javascript/ql/test/library-tests/DependencyModuleImports/Test.ql
ql/ql/src/codeql_ql/ast/Ast.qll
ql/ql/src/codeql_ql/style/RedundantImportQuery.qll
ql/ql/test/queries/style/RedundantImport/D.qll
ql/ql/test/queries/style/RedundantImport/E.qll
ql/ql/test/queries/style/RedundantImport/RedundantImport.expected
ql/ql/test/queries/style/RedundantImport/RedundantImport.qlref
ql/ql/test/queries/style/RedundantImport/folder/A.qll
ql/ql/test/queries/style/RedundantImport/folder/B.qll
ql/ql/test/queries/style/RedundantImport/folder/C.qll

On https://github.com/github/codeql/pull/14573 I observed that the query does not take `deprecated` imports into account, which is fixed on this PR.
I also removed some restrictions that I could not understand; this results in many new results on `github/codeql`, and those that I have sampled look legit.

QL4QL: Improvements to `RedundantImport` query

---

cpp/ql/src/experimental/Security/CWE/CWE-1240/CustomCryptographicPrimitive.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-1240/CustomCryptographicPrimitive.expected
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-1240/CustomCryptographicPrimitive.qlref
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-1240/library/tests_library.h
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-1240/tests_crypto.cpp
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-1240/tests_not_crypto.cpp

Adds an experimental query for detecting custom implementations of a cryptographic primitive (i.e. covering https://mas.owasp.org/MASTG/General/0x04g-Testing-Cryptography/#custom-implementations-of-cryptography
and parts of https://cwe.mitre.org/data/definitions/1240.html).
Currently `@precision medium`, because it flags established library encryption implementations just as happily as custom implementations and entirely custom algorithms.  Though probably none of these should be in a database unless it's a database for a cryptography library.
Developed during a hackathon.  Needs more work to be production quality - in particular it currently lacks:

C++: Experimental query for implementation of a cryptographic primitive

---

swift/ql/lib/change-notes/2023-11-27-append.md
swift/ql/lib/codeql/swift/frameworks/Heuristic.qll
swift/ql/test/library-tests/dataflow/taint/libraries/array.swift
swift/ql/test/library-tests/dataflow/taint/libraries/custom.swift
swift/ql/test/library-tests/dataflow/taint/libraries/ui.swift

Adds a small number of imprecise taint flow models.  There's a *lot* more we could potentially do here, but lets start small for now:
- taint flow through methods that look like an "append" or "insert"; many of these will be on classes derived from `Collection` (which we can model and I think do model most of), but quite often these patterns are also copied in classes that do not derived from `Collection`.  By using an imprecise model, we can catch the latter as well.
- taint flow through initializers with a "data" argument, which I'm pretty happy will inherit taint from an argument of that nature.
There's a contents / flow paths issue here - we only have flow path support on MAD flow models, not on QL flow models which these imprecise sinks have to be - so we can't have flow from the …

Swift: Imprecise Taint Flows

---

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPublic.qll
python/ql/test/experimental/dataflow/basic/local.expected
python/ql/test/experimental/dataflow/basic/sinks.expected
python/ql/test/experimental/dataflow/basic/sources.expected
python/ql/test/experimental/dataflow/enclosing-callable/EnclosingCallable.expected
python/ql/test/experimental/dataflow/import-star/global.expected
python/ql/test/experimental/import-resolution/ModuleExport.expected
python/ql/test/experimental/import-resolution/package/subpackage/__init__.py
python/ql/test/library-tests/PointsTo/new/ImpliesDataflow.expected

This should have been part of https://github.com/github/codeql/pull/14777.
These nodes are extra copared to which SSA nodes existed before.
We do lose one result that we gained by having these nodes:
```
testFailures
+| package/subpackage/__init__.py:12:90:12:113 | Comment #$ prints=submodule_attr | Missing result:prints=submodule_attr |
```
which is the one we might expect to lose. We do get to keep the other one (about lambdas in flow summaries),

Python: Remove control flow nodes for module entry definitions from the dataflow graph.
