java/ql/lib/change-notes/2023-12-08-deprecate-reexport-of-old-dataflow-libraries.md, java/ql/lib/semmle/code/java/frameworks/JsonIo.qll, java/ql/lib/semmle/code/java/regex/RegexFlowConfigs.qll, java/ql/lib/semmle/code/java/security/AndroidIntentRedirectionQuery.qll, java/ql/lib/semmle/code/java/security/CleartextStorageCookieQuery.qll, java/ql/lib/semmle/code/java/security/CleartextStorageQuery.qll, java/ql/lib/semmle/code/java/security/HardcodedCredentialsSourceCallQuery.qll, java/ql/lib/semmle/code/java/security/XmlParsers.qll, java/ql/src/experimental/Security/CWE/CWE-1004/SensitiveCookieNotHttpOnly.ql
This deprecates the public re-exporting of the copies of the old dataflow library (e.g. `semmle.code.java.dataflow.DataFlow2` or `semmle.code.java.dataflow.TaintTracking3`).
Currently CodeQL issues a warning when using an item from a `deprecated import`, even if the usage is in a deprecated context. So for now, modules which still use the deprecated items (e.g. a deprecated class extending `TaintTracking2::Configuration`) mark the import as deprecated, and then re-import it privately.
=> Java: Deprecate or remove imports of dataflow library copies

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisConstantSpecific.qll, cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisImpl.qll, cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisRelativeSpecific.qll, shared/rangeanalysis/codeql/rangeanalysis/RangeAnalysis.qll
This adds a pre-bound calculation to range analysis, which does an initial simple pass using forward-flowing steps only. Nodes with multiple incoming bound-flow edges such as bitwise-and and ssa references under a guard, might have simple tight bounds coming from one edge, and multiple looser bounds from the other. By inferring the simpler bounds in an initial pass, we're able to prune away the other looser bounds including those that might proliferate through a back-edge. An example is `x &= 7` for which this initial pass will ensure that no upper bound for `x` greater than 7 can pass the assignment.
Commit-by-commit review encouraged, as the first couple of commits are just refactorings.
=> Rangeanalysis: Prune range calculation.

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/PrintDataFlowRelevantIR.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/PrintIRLocalFlow.qll
Previously, when I was debugging IR dataflow issues I'd import `PrintIRLocalFlow.qll` to reduce the amount of IR printed, and then comment out the `getOperandProperty` and `getInstructionProperty` overrides (because they're simply too noisy and not very helpful).
This PR separates the property provider that hides IR from the property provider that prints local flow. That means you can hide the irrelevant IR without needing to comment out anything.
This is strictly for debugging purposes, and thus I don't believe this needs to be run on DCA.
=> C++: Add a `PropertyProvider` for only showing dataflow-relevant IR

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll, cpp/ql/src/Critical/DoubleFree.ql, cpp/ql/src/Critical/FlowAfterFree.qll, cpp/ql/src/Critical/UseAfterFree.ql, cpp/ql/test/query-tests/Critical/MemoryFreed/DoubleFree.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/UseAfterFree.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/test_free.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/UseAfterFree/UseAfterFree.expected
Previously, the only way to track flow out of function calls was to use `node.asDefiningArgument()` to get the dataflow node corresponding to the value that was written inside a function call. For example, consider something like:
```cpp
void f(int* p) { *p = source(); }
void test() {
int* p;
f(p);
sink(*p);
}
```
using `node.asDefiningArgument()` gives you the indirect node corresponding to what `p` points to after the call to `f` returns. Internally, this is basically equivalent to `node.(PostUpdateNode).getPreUpdateNode().getIndirectExpr()` which:
1. Grabs a `PostUpdateNode`
2. Gets the node representing the value "before the function call"
3. Gets the indirect expression associated with the node
However, if instead one wanted to track the _pointer_ to the value that's coming out of …
=> C++: Add `PostUpdateNode`s for addresses of outgoing arguments

go/ql/lib/change-notes/2023-12-08-find-more-callees-for-captured-functions.md, go/ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll, go/ql/test/library-tests/semmle/go/frameworks/Twirp/RequestForgery.expected
This is needed because capturing a variable is a jump step and we want to find a callee source for captured functions.
=> Go: Also follow jump steps when looking for a callee source

csharp/extractor/Semmle.Extraction.CSharp.StubGenerator/StubVisitor.cs, csharp/extractor/Semmle.Extraction.Tests/StubGenerator.cs
This is a pre-requisite for updating the stubs as the `ref readonly` parameter feature from C# 12 is already used in the .NET 8 Core framework.
=> C#: Stub generator support for `ref readonly` parameters.

csharp/ql/src/Telemetry/ExternalApi.qll, csharp/ql/src/Telemetry/ExternalLibraryUsage.ql, csharp/ql/test/query-tests/Telemetry/LibraryUsage/options, csharp/ql/test/query-tests/Telemetry/SupportedExternalSinks/options, csharp/ql/test/query-tests/Telemetry/SupportedExternalSources/options
In this PR we change the telemetry queries slightly (which should have no impact in production) and make it explicit that we are only interested in calls performed in source code. This is important for testing purposes as we would like to use our stubs (which contains base constructor calls) to avoid cluttering the output.
This PR is a preparation for the .NET 8 stub update.
=> C#: Telemetry should only count calls in source.

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DebugPrinting.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/Node0ToString.qll
One of the first things I do when I debug dataflow node-related things is to modify the `toString` of `InstructionNode`s and `OperandNode`s. This PR simplifies that process by creating an abstract class to control whether the debug version (or the efficient) version should be used.
Then, to enable debug printing, one can simply import `DebugPrinting.qll` to modify the output.
By default `toString` already present on `main` will be used. So nothing should change from the user point-of-view. I've checked that the `toString` still compiles to the efficient RA when debugging isn't enabled:
```ql
Evaluated relational algebra for predicate DataFlowPrivate::Node0Impl.toStringImpl/0#dispred#9d03b963@295a56td with tuple counts:
5160283   ~0%    {2} r1 = JOIN …
```
=> C++: Easier debugging of dataflow node `toString` output

java/ql/integration-tests/all-platforms/java/buildless-maven/test.expected, java/ql/integration-tests/all-platforms/java/buildless/test.expected, java/ql/integration-tests/all-platforms/java/maven-sample/test.expected
This updates some of the integration tests to handle the `.properties` extractor being enabled.
=> Java: Add `.properties` file references in integration tests

csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/StandaloneBuildRule.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyOptions.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FilePathFilter.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/IProgressMonitor.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/ProgressMonitor.cs, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Extractor.cs, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Options.cs, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Program.cs, csharp/extractor/Semmle.Extraction.Tests/FilePathFilter.cs, csharp/extractor/Semmle.Extraction.Tests/Options.cs
This PR 
- removes all the unused options from the standalone extractor,
- handles the `LGTM_INDEX_FILTERS` environment variable, which contains the `paths` and `paths-ignore` codescanning settings.
The CI QL Tests are failing due to the removal of the options. The linked internal PR covers those.
=> C#: Remove unneeded options and add support for `paths/paths-ignore` in standalone

ruby/ql/test/TestUtilities/InlineFlowTest.qll, shared/dataflow/codeql/dataflow/test/InlineFlowTest.qll
When not using `DefaultFlowTest`, it is useful to be able to implement a custom `getArtString` predicate.
=> InlineFlowTest: Allow for custom `getArgString`

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/src/utils/modeleditor/ApplicationModeEndpoints.ql, csharp/ql/src/utils/modeleditor/FrameworkModeEndpoints.ql, csharp/ql/src/utils/modeleditor/ModelEditor.qll, csharp/ql/test/utils/modeleditor/FrameworkModeEndpoints.expected, csharp/ql/test/utils/modeleditor/FrameworkModeEndpoints.ext.yml, csharp/ql/test/utils/modeleditor/PublicGenericClass.cs
The names returned in the C# model editor queries did not match the names that were expected in the MaD files. For example, it would return `PublicGenericClass`2`, whereas the MaD format expects `PublicGenericClass<T,T2>`. This fixes it by reusing the same `QualifiedName` module that `ExternalFlow.qll` uses.
=> C#: Fix names of generic types/methods in model editor queries

javascript/extractor/lib/typescript/src/ast_extractor.ts, javascript/extractor/lib/typescript/src/main.ts, javascript/extractor/lib/typescript/src/type_table.ts
And add a new `SEMMLE_TYPESCRIPT_SKIP_EXTRACTING_TYPES` environment variable to skip extraction of all types.  
This is a workaround for an internal report about long extraction times.  
I'm not sure why those fixes weren't needed previously, and I couldn't replicate them when running tests. 
They're clearly basic TypeScript errors, so I'm not sure what's going on.  
I think it's something for @asgerf to look at when he's back?
I tried the new flag locally on `microsoft/vscode`. 
The extraction got faster, and we only lost a single alert on that project.
And extraction is way faster with the flag on a minimal example from the internal report.
Evaluation were very uneventful ([nightly-old.yml](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-15072-896432__nightly-old__code- …
=> JS: Various TypeScript extraction fixes.

swift/ql/test/query-tests/Security/CWE-327/BrokenCryptoAlgorithm.qlref.disabled, swift/ql/test/query-tests/Security/CWE-327/test_commoncrypto.swift
Revert https://github.com/github/codeql/pull/15094/, that is, put back the test that was introduced in https://github.com/github/codeql/pull/13870 .  These tests encountered an extraction issue on Linux CI.  The goal of _this_ PR is to get the test cases back in, as I don't want to lose them, with any problematic parts disabled so that CI passes.  There are issues tracking fixing the extraction problem itself and for repairing the affected tests afterwards (this isn't the only one).
It will take me a few iterations to get this passing CI.  Please don't review / merge until then.
=> Swift: Revert:Revert "Swift: CommonCrypto test cases for the BrokenCryptoAlgorithm query"

javascript/extractor/lib/typescript/src/main.ts
This is how the `Boolean` function behaves on strings: 
```
> Boolean("true")
true
> Boolean("false")
true
> Boolean("any string")
true
```
This means that setting the environment variable to any string will make the option `true`.
=> JS: fix the parsing of boolean environment variables in the TypeScript extractor

javascript/ql/lib/semmle/javascript/PrintAst.qll, javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowNode.qll
Model XML attributes similar to HTML attributes so we can reason about values flowing from/to XML attributes.
This is necessary for supporting Web frameworks relying on XML to define views such as SAP UI5.
=> JavaScript: Add support for XML attributes in the data flow graph

javascript/extractor/lib/typescript/src/ast_extractor.ts, javascript/extractor/lib/typescript/src/main.ts, javascript/extractor/lib/typescript/src/type_table.ts
Cherry-picking the commits from https://github.com/github/codeql/pull/15105 and https://github.com/github/codeql/pull/15105 into `rc/3.12` such that they should be part of the next release.  
The internal PR (`codeql-extractor.yml`) is just for documentation. So that PR doesn't need to be merged to the release branch.  
I'm doing an evaluation (see backref), just to make sure everything looks OK.
=> JS: TypeScript extractor fixes into rc/3.12

cpp/ql/src/Security/CWE/CWE-120/BadlyBoundedWrite.ql, cpp/ql/src/change-notes/2023-12-15-badly-bounded-write.md, cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/BadlyBoundedWrite.expected, cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/tests2.cpp
New attempt at fixing https://github.com/github/codeql/issues/13913.
The original attempt is here: https://github.com/github/codeql/pull/13929, which was backed out here: https://github.com/github/codeql/pull/13996, because of a bug found in monotonic aggregates, which has since been fixed.
Currently running DCA and MRVA on this, will report on the results when they're ready.
=> C++: Only consider the maximum buffer size for badly bounded write

cpp/ql/lib/semmle/code/cpp/Function.qll, cpp/ql/src/jsf/4.10 Classes/AV Rule 79.ql
This was reported by the nightly C++ DCA run. There was a join order issue in both the base case and the recursive case 🙈.
Before:
```
Pipeline base for AVRule79::Resource.calledFromDestructor/1#c82b6f08@31f21b02 was evaluated in 1 iterations totaling 33ms (delta sizes total: 7823).
39806  ~3%    {2} r1 = JOIN AVRule79::Resource#8f0c844b WITH `Declaration::Declaration.getDeclaringType/0#dispred#6d415a62` ON FIRST 1 OUTPUT Rhs.1, Lhs.0
2278593  ~1%    {2} r2 = JOIN r1 WITH `Declaration::Declaration.getDeclaringType/0#dispred#6d415a62_10#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1
7823  ~3%    {2} r3 = JOIN r2 WITH MemberFunction::Destructor#3b34c0ea ON FIRST 1 OUTPUT Lhs.1, Lhs.0
return r3
Pipeline standard for AVRule79::Resource.calledFromDestructor/1#c82b6f08@31f21b02 was evaluated in 5 …
```
=> C++: Fix joins in `cpp/resource-not-released-in-destructor`

swift/ql/test/library-tests/dataflow/flowsources/customurlschemes.swift
I was investigating some missing taint sources and created a few more test cases for `application(...launchOptions...)` as a taint source.  We might as well keep them.
=> Swift: Add more test cases for application(...launchOptions...).

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll, ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected, ruby/ql/test/library-tests/dataflow/local/local_dataflow.rb
Until we have proper data flow for pattern matching (possibly using desugaring and flow summaries), this PR changes simple pattern matches such as
```rb
case value
in Foo => x then ...
in y => then ...
end
```
from being taint steps to value steps.
=> Ruby: Model simple pattern matching as value steps instead of taint steps

java/ql/lib/semmle/code/java/security/AndroidCertificatePinningQuery.qll, java/ql/src/change-notes/2023-12-12-android-certificate-pinning-precision.md, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test1/Test.java, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test2/Test.java, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test3/Test.java, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test4/Test.java, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test5/Test.java
Local URIs should never require pinning.
In this PR we are making the conscious decision of _requiring_ a URL string to flow to the sink in order to consider it a valid "missing certificate pinning" candidate, and then we check any sort of certificate pinning validation on the domain of the URL string.
In the old version, if we couldn't find a flow from a string to the sink and there was no certificate pinning check in place, we'd just alert on the sink, but that was prone to FPs for things like `getResource`, `getResourceAsStream`, `newFileSystem`, and similar calls that _can_ operate on the network but normally access the local filesystem.
=> Java: Fix FPs in Missing certificate pinning

cpp/ql/src/jsf/4.16 Initialization/AV Rule 145.ql
Another join order issue reported by the C++ nightly DCA run.
Before:
```
[2023-12-15 11:55:06] Evaluated non-recursive predicate AVRule145::enumThatHasConstantWithImplicitValue/1#42617793@cb2a023l in 124ms (size: 512).
Evaluated relational algebra for predicate AVRule145::enumThatHasConstantWithImplicitValue/1#42617793@cb2a023l with tuple counts:
{3} r1 = `Enum::Enum.getEnumConstant/1#dispred#8bfe8fc8` AND NOT `_Enum::Enum.getEnumConstant/1#dispred#8bfe8fc8_Enum::EnumConstant.getInitializer/0#dispred#ee634a2f___#antijoin_rhs`(FIRST 3)
12570      ~1%    {2} r2 = SCAN r1 OUTPUT In.0, In.1
12557      ~1%    {2} r3 = STREAM DEDUP r2
8703841      ~3%    {4} r4 = JOIN r3 WITH `Enum::Enum.getEnumConstant/1#dispred#8bfe8fc8` ON FIRST 1 OUTPUT Lhs.0, Lhs.1, Rhs.1, Rhs.2
{4} r5 = REWRITE r4 WITH …
```
=> C++: Fix joins in `AV Rule 145`

csharp/extractor/Semmle.Extraction.CSharp.StubGenerator/StubVisitor.cs, csharp/extractor/Semmle.Extraction.Tests/StubGenerator.cs, csharp/ql/test/resources/stubs/ServiceStack.Common/8.0.0/ServiceStack.Common.cs, csharp/scripts/stubs/helpers.py
In this PR we
- Escape method names in case they overlap with keywords.
- Don't generate stubs for the "hidden" `<Clone>$` method (compiler generated method on record types, which can't be invoked directly).
- Use a regex for finding a package version number in the dependencies list.
There is still more room for improvement to also include the `record` modifier on types, but that is a bit more involved as we will then need to avoid generating some of the compiler generated methods for that particular type. In all the APIs we generate stubs for there are only two record class types exposed, so I don't think it is worth it (yet).
The "dependencies" logic in the python script should basically resemble the logic we have in the assets parser in C#, which means that we should probably re-use …
=> C#: Escape method names in stub generation.

cpp/ql/lib/semmle/code/cpp/models/interfaces/FormattingFunction.qll
This one also kept showing up on the nightly DCA run.
Before:
```ql
Pipeline standard for FormattingFunction::stripTopLevelSpecifiersOnly/1#c8bada68#bf@379a1xvo was evaluated in 4 iterations totaling 150ms (delta sizes total: 2262215).
{1} r1 = `m#FormattingFunction::stripTopLevelSpecifiersOnly/1#c8bada68#bf#prev_delta` AND NOT Type::SpecifiedType#e92ebe9d(FIRST 1)
1931981  ~23%    {2} r2 = SCAN r1 OUTPUT In.0, In.0
330478   ~0%    {2} r3 = JOIN `_Type::SpecifiedType#e92ebe9d_m#FormattingFunction::stripTopLevelSpecifiersOnly/1#c8bada68#bf#prev_d__#shared` WITH `Type::DerivedType.getBaseType/0#dispred#b08b94f7` ON FIRST 1 OUTPUT Rhs.1, Lhs.0
0   ~0%    {2} r4 = JOIN r3 WITH `FormattingFunction::stripTopLevelSpecifiersOnly/1#c8bada68#bf#prev` ON FIRST 1 OUTPUT Lhs.1, Rhs.1
330478   ~2% …
```
=> C++: Fix joins in `cpp/wrong-type-format-argument`

misc/bazel/cmake/setup.cmake
(cherry picked from commit 819fc52854993c9fcbafe80a11a5637208ca9a7e)
=> Bazel/CMake: use bazelisk to use correct bazel version

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll, cpp/ql/lib/semmle/code/cpp/ir/internal/CppType.qll
Also highlighted by the DCA join order report. This on was actually quite bad 😅.
Before:
```
[2023-12-18 10:09:33] Evaluated non-recursive predicate SsaInternalsCommon::isModifiableAtImpl/2#2b25ad2f@b02f6ccj in 71404ms (size: 2842043).
Evaluated relational algebra for predicate SsaInternalsCommon::isModifiableAtImpl/2#2b25ad2f@b02f6ccj with tuple counts:
4208191   ~1%    {2} r1 = JOIN CppType::TCppType#eff8d274 WITH `CppType::CppType.hasType/2#dispred#d3f6ee89` ON FIRST 1 OUTPUT Rhs.1, Lhs.0
4207753   ~0%    {2} r2 = JOIN r1 WITH `Type::Type.getUnderlyingType/0#dispred#bd141f6a` ON FIRST 1 OUTPUT Rhs.1, Lhs.1
2914047693   ~0%    {3} r3 = JOIN r2 WITH `Type::Type.getUnderlyingType/0#dispred#bd141f6a_10#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.0
1280304   ~0%    {3} r4 = JOIN r3 WITH …
```
=> C++: Fix joins in `isModifiableAtImpl`

csharp/ql/src/Telemetry/ExtractorInformation.ql
Sample results:
| Key  | Value | 
| ------------- | ------------- | 
| Number of files | 2,020 |
| Total number of lines | 173,864 |
| Number of lines of code | 126,920 |
| Number of files with extension config | 1 |
| Number of files with extension cs | 1,562 |
| Number of files with extension props | 32 |
| Number of files with extension dll | 394 |
| Number of files with extension csproj | 30 |
| Number of diagnostics with severity 0 | 7,303 |
| Number of diagnostics with severity 2 | 12,611 |
| Number of diagnostics with severity 3 | 762 |
| Total number of lines with extension config | 11 |
| Total number of lines with extension cs | 171,160 |
| Total number of lines with extension props | 1,315 |
| Total number of lines with extension csproj | 1,378 |
| Number of lines of code with …
=> C#: Add telemetry query to report extractor information

python/ql/src/meta/analysis-quality/TTCallGraph.ql, python/ql/src/meta/analysis-quality/TTCallGraphMissing.ql, python/ql/src/meta/analysis-quality/TTCallGraphNew.ql, python/ql/src/meta/analysis-quality/TTCallGraphNewAmbiguous.ql, python/ql/src/meta/analysis-quality/TTCallGraphShared.ql
These queries were great when evaluating coverage of the new call-graph compared with the old.
However, they are not useful to run as part of our DCA experiments.
=> Python: Remove `@tags meta` from internal debug queries

java/ql/lib/change-notes/2023-12-19-add-replace-methods-to-mapmutator.md, java/ql/lib/semmle/code/java/Maps.qll
Adds the `replace` and `replaceAll` methods of the `java.util.Map` interface to the `MapMutator` class in `Maps.qll`.
=> Java: Add the `Map#replace` and `Map#replaceAll` methods to `MapMutator` in `Maps.qll`

csharp/ql/src/utils/modeleditor/FrameworkModeEndpointsQuery.qll, csharp/ql/src/utils/modeleditor/ModelEditor.qll
This adds files that are only used as "test support files" as test files in the model editor queries. The detection of these files is based on the [Java](https://github.com/github/codeql/blob/2305d55967d71ca13b06482f273ba9c6baa7240f/java/ql/lib/semmle/code/java/dataflow/internal/ModelExclusions.qll#L27-L31) and [Ruby](https://github.com/github/codeql/blob/2305d55967d71ca13b06482f273ba9c6baa7240f/ruby/ql/src/utils/modeleditor/ModelEditor.qll#L132-L137) methods.
Examples of test support files in [mongodb/mongo-csharp-driver](https://github.com/mongodb/mongo-csharp-driver):
- [`tests/MongoDB.Bson.TestHelpers/IO/NullBsonStream.cs`](https://github.com/mongodb/mongo-csharp-driver/blob/302640265d6db856fafad2254b19cdaa33d3d743/tests/MongoDB.Bson.TestHelpers/IO/NullBsonStream.cs)
- …
=> C#: Classify test support files in model editor queries

python/ql/lib/change-notes/2023-12-20-add-scope-entry-definition-nodes.md, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPublic.qll, python/ql/lib/semmle/python/dataflow/new/internal/LocalSources.qll, python/ql/lib/semmle/python/dataflow/new/internal/TypeTrackingImpl.qll, python/ql/test/experimental/dataflow/coverage/localFlow.expected, python/ql/test/experimental/dataflow/enclosing-callable/EnclosingCallable.expected, python/ql/test/experimental/dataflow/typetracking/moduleattr.expected, python/ql/test/experimental/dataflow/typetracking/tracked.ql, python/ql/test/library-tests/ApiGraphs/py3/test_crosstalk.expected, python/ql/test/library-tests/ApiGraphs/py3/test_crosstalk.py, python/ql/test/library-tests/ApiGraphs/py3/test_crosstalk.ql
otherwise we confuse captured variables
in the single scope entry cfg node. Now
we have one for each defined variable.
=> Python: Add scope entry definition nodes

docs/codeql/codeql-overview/system-requirements.rst
Does this extra system requirement make sense?
Addresses https://github.com/github/codeql/issues/15139
=> Update system requirements for ruby

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
This is https://github.com/github/codeql/pull/15107, but for SSA variables.
This `toString` isn't actually used anywhere, but it can be helpful when debugging dataflow
=> C++: Show indirections when printing SSA variables

swift/swift-autobuilder/swift-autobuilder.cpp
`pod install` could generate Xcode projects files needed for autobuilding, so it's better to install dependencies first, and then do re-scan to pick up the new files.
=> Swift: separate installation of dependencies and autobuilding

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
I forgot to include the actual variable name in https://github.com/github/codeql/pull/15185 :doh:
=> C++: Show base variable in SSA variable `toString`s

java/ql/lib/semmle/code/java/security/MaybeBrokenCryptoAlgorithmQuery.qll, java/ql/src/Security/CWE/CWE-327/MaybeBrokenCryptoAlgorithm.ql, java/ql/test/query-tests/security/CWE-327/semmle/tests/BrokenCryptoAlgorithm.expected, java/ql/test/query-tests/security/CWE-327/semmle/tests/MaybeBrokenCryptoAlgorithm.expected, java/ql/test/query-tests/security/CWE-327/semmle/tests/WeakHashing.java
Change the logic of checking potential `.properties` values from implicit `forall` to explicit `exists`.
When I implemented this earlier, I made the check against secure algorithms with `not mc.getPropertyValue().regexpMatch(getSecureAlgorithmRegex())`. But since calls to `getProperty` can have two values (one from the file and one the default value), this resulted in the query missing calls with a secure default value.
E.g.
```java
// # production.properties
// hashAlg1=MD5
String algorithm = props.getProperty("hashAlg1", "SHA-256");
// ^ BAD    // ^ OK
```
=> Java: Fix minor error in `java/potentially-weak-cryptographic-algorithm`

ruby/ql/lib/codeql/ruby/ast/Module.qll, ruby/ql/lib/codeql/ruby/ast/internal/Module.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/src/queries/modeling/internal/Types.qll, ruby/ql/src/utils/modeleditor/FrameworkModeEndpoints.ql, ruby/ql/src/utils/modeleditor/ModelEditor.qll, ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeEndpoints.expected, ruby/ql/test/query-tests/utils/modeleditor/GenerateModel.expected, ruby/ql/test/query-tests/utils/modeleditor/GenerateModel.qlref
This PR does a few things:
- Excludes endpoints whose path has `examples` in it. This removes a lot of example code that otherwise gets picked up when modeling libraries.
- Changes the `FrameworkModeEndpoints` query to produce not only methods, but also classes. These are not technically endpoints, but it allows the model editor to learn about them and thus handle the new results from `GenerateModel` (see below). This involves some refactoring of the `Endpoint` class, because we want to include both `DataFlow::MethodNode`s and `DataFlow::ModuleNode`s, which don't have a common ancestor.
- Updates the `GenerateModel` query to produce `typeModel` rows for subclass relationships. For example:
```rb
class A
def foo(x)
end
end
class B < A
end
```
If we mark `A#foo` as a sink, we also want to …
=> Ruby: Model editor improvements

cpp/ql/test/library-tests/special_members/generated_copy/functions.expected, cpp/ql/test/library-tests/special_members/generated_copy/functions.ql
Without this it is very hard to see what specifically is defaulted/deleted.
=> C++: Improve special members test by printing more function details

go/ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll, go/ql/src/change-notes/2023-12-17-incorrect-integer-conversion-fix.md, go/ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.expected, go/ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.go
The new logic for comparing with MaxInt and MaxUint had a logic error which affected strict inequailities. So `x <= MaxUint` would work but `x < MaxUint` wouldn't.
=> Go: fix FP in incorrect integer conversion query relating to strict comparisons with MaxInt and MaxUint

java/ql/automodel/publish.sh, java/ql/automodel/src/README.md
The `automodel` extraction queries (released as a `codeql` query pack), and `automodel` Python CLI (released as part of `turbomodel`) are functionally coupled. They must be released "together". The official releases of the `codeml-automodel` repo (see https://github.com/github/codeml-automodel/releases) specify coupled `sha`s. 
This PR upgrades the `publish.sh` script to default to publishing the version of the `automodel` extraction queries that correspond to the latest release of `codeml-automodel`; specifically, invoking `publish.sh` will:
- Check you don't have any uncommitted local changes
- Check that you have the required security tokens
- Check that you have a local `codeql` distribution (needed to package and publish the query pack)
- Check that the version of the `codeql` code …
=> ensure `publish.sh` uses the latest `automodel` release

csharp/ql/lib/semmle/code/csharp/frameworks/System.qll, csharp/ql/src/change-notes/2024-01-03-logforging-false-positive.md, csharp/ql/test/query-tests/Security Features/CWE-117/LogForging.cs, csharp/ql/test/query-tests/Security Features/CWE-117/LogForging.expected
It turns out that there more overloads of the `String.Replace` method, which we didn't consider replace methods.
=> C#: Fix Log forging false positive.

go/ql/lib/semmle/go/controlflow/ControlFlowGraphImpl.qll
The first level doesn't deal with defer statements properly. The second level uses the first level to deal with them properly.
=> Go: Stratify `CFG::succ` to avoid recursion

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
Non-linear recursion is only needed when type flow is enabled, so this PR makes sure that we don't do unnecessary non-linear recursion in those pruning stages where type flow is disabled.
<details><summary>Example DIL before</summary>
```
noinline
nomagic
incremental
`DataFlowImpl::Impl<HttpClient::HttpClientDisablesCertificateValidationFlow::C>::Stage2::fwdFlowIn/6#e7e669eb`(
/* DataFlowImpl::MakeImpl<DataFlowImplSpecific::RubyDataFlow>::Impl<DataFlow::DataFlowMake<DataFlowImplSpecific::RubyDataFlow>::Global<HttpClient::HttpClientDisablesCertificateValidationConfig>::C>::ParamNodeEx */ `DataFlowImpl#248dabc3::MakeImpl<DataFlowImplSpecific#21008cd7::RubyDataFlow>::Impl<DataFlow#167ac380::DataFlowMake<DataFlowImplSpecific#21008cd7::RubyDataFlow>::Global<HttpClient#d717370f::HttpClientDisabl …
```
=> Data flow: Avoid unnecessary non-linear recursion in `fwdFlowIn`

csharp/ql/lib/change-notes/2023-12-20-arg-param-mapping.md, csharp/ql/lib/semmle/code/csharp/dataflow/Nullness.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/exprs/Call.qll, csharp/ql/test/library-tests/arguments/PrintAst.expected, csharp/ql/test/library-tests/arguments/argumentByName.expected, csharp/ql/test/library-tests/arguments/argumentByParameter.expected, csharp/ql/test/library-tests/arguments/argumentName.expected, csharp/ql/test/library-tests/arguments/argumentType.expected, csharp/ql/test/library-tests/arguments/arguments.cs, csharp/ql/test/library-tests/arguments/parameterGetArguments.expected, csharp/ql/test/query-tests/Nullness/NullMaybe.expected, csharp/ql/test/query-tests/Nullness/Params.cs
This PR changes `Call::getArgumentForParameter` to better cover cases when arguments are passed to `params` parameters. 
Commit-by-commit review is suggested.
=> C#: Improve arg-param mapping logic to better handle arguments passed to `params` parameters

swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Security.qll, swift/ql/lib/codeql/swift/security/SensitiveExprs.qll, swift/ql/lib/codeql/swift/security/WeakPasswordHashingExtensions.qll, swift/ql/lib/codeql/swift/security/WeakPasswordHashingQuery.qll, swift/ql/lib/codeql/swift/security/WeakSensitiveDataHashingExtensions.qll, swift/ql/lib/codeql/swift/security/WeakSensitiveDataHashingQuery.qll, swift/ql/src/change-notes/2023-12-15-weak-password-hashing.md, swift/ql/src/queries/Security/CWE-328/WeakPasswordHashing.qhelp, swift/ql/src/queries/Security/CWE-328/WeakPasswordHashing.ql, swift/ql/src/queries/Security/CWE-328/WeakPasswordHashingBad.swift, swift/ql/src/queries/Security/CWE-328/WeakPasswordHashingGood.swift, swift/ql/src/queries/Security/CWE-328/WeakSensitiveDataHashing.ql, swift/ql/src/queries/Security/CWE-328/WeakSensitiveDataHashingBad.swift, swift/ql/src/queries/Security/CWE-328/WeakSensitiveDataHashingGood.swift, swift/ql/src/queries/Summary/QuerySinks.ql, swift/ql/test/query-tests/Security/CWE-311/SensitiveExprs.expected, swift/ql/test/query-tests/Security/CWE-328/WeakPasswordHashing.expected, swift/ql/test/query-tests/Security/CWE-328/WeakPasswordHashing.qlref, swift/ql/test/query-tests/Security/CWE-328/WeakSensitiveDataHashing.expected, swift/ql/test/query-tests/Security/CWE-328/testArgon2Swift.swift, swift/ql/test/query-tests/Security/CWE-328/testCryptoKit.swift, swift/ql/test/query-tests/Security/CWE-328/testCryptoSwift.swift
New query for Use of an inappropriate cryptographic hashing algorithm on passwords.
This query is designed to be used alongside the existing `swift/weak-sensitive-data-hashing` query, and I've made some adjustments to that query to avoid duplication and to make sure results are reported by the most appropriate query.  Previously:
```
swift/weak-sensitive-data-hashing: password, credential or private info -> MD5 or SHA1 hash
```
Now:
```
swift/weak-sensitive-data-hashing: non-password credential or private info -> MD5 or SHA1 hash
swift/weak-password-hashing: password -> MD5, SHA1, SHA2 (including variants such as SHA-512), SHA3 hash
```
To do this I had to make passwords an explicit kind of sensitive data in Swift (`SensitivePassword`), and I added MAD syntax for it …
=> Swift: Query for Use of an inappropriate cryptographic hashing algorithm on passwords

java/ql/lib/ext/org.pac4j.jwt.config.encryption.model.yml, java/ql/lib/ext/org.pac4j.jwt.config.signature.model.yml, java/ql/lib/semmle/code/java/frameworks/Netty.qll, java/ql/lib/semmle/code/java/frameworks/OpenSaml.qll, java/ql/lib/semmle/code/java/frameworks/Servlets.qll, java/ql/lib/semmle/code/java/security/Cookies.qll, java/ql/lib/semmle/code/java/security/InsecureRandomnessQuery.qll, java/ql/lib/semmle/code/java/security/RandomDataSource.qll, java/ql/test/query-tests/security/CWE-330/InsecureRandomCookies.java, java/ql/test/query-tests/security/CWE-330/WeakRandomCookies.java, java/ql/test/query-tests/security/CWE-330/options, java/ql/test/stubs/netty-4.1.x/io/netty/handler/codec/http/Cookie.java, java/ql/test/stubs/netty-4.1.x/io/netty/handler/codec/http/DefaultCookie.java
Adds more sinks for increased CVE coverage.
No change note since this is part of https://github.com/github/codeql/pull/13608 and ought to be released at the same time, so they can share change note.
=> Java: Add more sinks to the Insecure Randomness query

cpp/downgrades/cf72c8898d19eb1b3374432cf79d8276cb07ad43/upgrade.properties, cpp/ql/lib/upgrades/098850d25c4e9d417eb74c1bef9deb2f9d2dc417/upgrade.properties
This PR adds missing `delete` directives in upgrade and downgrade scripts.
=> C++: Fix upgrade delete directives

ruby/ql/lib/codeql/ruby/frameworks/core/Kernel.qll
Add `public_send` and `__send__` as Code Injection sinks as proposed by @vcsjones
=> Ruby: Update Kernel.qll to include `Object.send` aliases

java/kotlin-extractor/kotlin_plugin_versions.py, java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/kotlin-extractor/src/main/kotlin/utils/TypeSubstitution.kt, java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_5_0/parents.kt, java/kotlin-extractor/src/main/kotlin/utils/versions/v_2_0_255-SNAPSHOT/parents.kt
The current master isn't compatible with the 2.0.0-Beta1
=> Kotlin: Add a 2.0.255 snapshot

misc/bazel/workspace.bzl
This doesn't bump rules_python, as there's some incompatible changes in that which will need further addressing.
=> Bazel: Bump dependant rules versions.

swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected, swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected, swift/ql/test/library-tests/dataflow/dataflow/test.swift, swift/ql/test/library-tests/dataflow/flowsources/swiftui.swift, swift/ql/test/query-tests/Security/CWE-311/testSwiftUI.swift
Add dataflow tests for flow through property wrappers, and for input via SwiftUI `TextField`s and similar (SwiftUI uses property wrappers heavily).  No models at this stage, as I am still figuring out the best way to do this.
=> Swift: Add dataflow tests for property wrappers and SwiftUI

cpp/ql/lib/semmle/code/cpp/rangeanalysis/RangeAnalysisUtils.qll
This PR addresses the two comments on the QLDoc for `cmpWithLinearBound` mentioned in https://github.com/github/codeql/issues/15248.
=> C++: Fix QLDoc on `cmpWithLinearBound`

java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt, java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/utils/ClassNames.kt
=> Kotlin: Remove 1.4 compatibility

javascript/ql/lib/semmle/javascript/frameworks/React.qll, javascript/ql/test/library-tests/TaintTracking/DataFlowTracking.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tooltip.jsx
Fixes https://github.com/github/codeql/issues/15207
Evaluations ([nightly](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/react-step__nightly-old__code-scanning__1/reports), [default](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/react-step__default__code-scanning/reports)) look good. 
No impact on performance.  
New call-edges and new results, all of which LGTM.
=> JS: promote `PropsTaintStep` to a `PreCallGraphStep`

java/ql/automodel/src/AutomodelApplicationModeCharacteristics.qll, java/ql/automodel/src/AutomodelFrameworkModeCharacteristics.qll, java/ql/automodel/src/AutomodelJavaUtil.qll
These have dummy locations, which breaks certain invariants that break downstream processing.
Alternative to https://github.com/github/codeql/pull/15263; I think I prefer this approach since it's more targeted.
=> Automodel: Do not generate features for compiler-generated program elements.

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowDispatch.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowDispatch.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplSpecific.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplSpecific.qll, docs/ql-libraries/dataflow/dataflow.md, go/ql/lib/semmle/go/dataflow/internal/DataFlowDispatch.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowDispatch.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplSpecific.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplSpecific.qll, ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected, ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.ql, shared/dataflow/codeql/dataflow/DataFlow.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll
Removes a redundant column from `mayBenefitFromCallContext`, and additionally makes `mayBenefitFromCallContext` and `viableImplInCallContext` optional in the API.
=> Data flow: Remove column from `mayBenefitFromCallContext`

java/ql/automodel/publish.sh
Adds ability to "dry-run" the `automodel` query pack publication. Useful to test prior to a proper release.
- More command-line control
- Some copying around of files to support dry-run and non-dry-run use-cases
Successfully tested locally (with a dry-run).
=> Support dry-run of publishing script

go/ql/lib/semmle/go/frameworks/stdlib/Log.qll, go/ql/lib/semmle/go/security/CleartextLogging.qll, go/ql/lib/semmle/go/security/SensitiveActions.qll, go/ql/src/change-notes/2024-01-09-cleartext-logging-new-sources-and-sinks.md, go/ql/test/query-tests/Security/CWE-312/CleartextLogging.expected, go/ql/test/query-tests/Security/CWE-312/main.go
Handles `log.Output` as a logging sink, and `secretkey` (case insensitive) as a potentially sensitive variable name. It also adds a barrier-in for sources to `go/clear-text-logging`,  so that overlapping paths are removed.
This adds coverage for CVE-2023-46742.
=> Go: Adds sources and sinks to `go/clear-text-logging`

cpp/ql/src/change-notes/2024-01-09-add-exception-to-av-rule-32.md, cpp/ql/src/jsf/4.06 Pre-Processing Directives/AV Rule 32.ql, cpp/ql/test/query-tests/jsf/4.06 Pre-Processing Directives/AV Rule 32/test.c
This is used as textual includes in several projects for macro metaprogramming, for example in `llvm-project` and in `swift` (and since some time in our internal codebase as well).
=> C++: add `.def` to exceptions to AV rule 32

cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected, cpp/ql/test/library-tests/dataflow/fields/dataflow-consistency.expected, cpp/ql/test/library-tests/dataflow/fields/dataflow-ir-consistency.expected, cpp/ql/test/library-tests/syntax-zoo/dataflow-consistency.expected, cpp/ql/test/library-tests/syntax-zoo/dataflow-ir-consistency.expected, ruby/ql/consistency-queries/DataFlowConsistency.ql, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected, ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb, ruby/ql/test/library-tests/dataflow/global/TypeTrackingInlineTest.expected, ruby/ql/test/library-tests/dataflow/global/blocks.rb, shared/dataflow/codeql/dataflow/internal/DataFlowImplConsistency.qll
Before this PR, we incorrectly assumed that all `yield` calls happen inside the CFG scope that is the method, to which the (implicit) block parameter belongs. However, that need not be the case:
```rb
def invoke_block1 x
yield x
end
def invoke_block2 x
invoke_block1 x do |x|
yield x # refers to the implicit block parameter of `invoke_block2`
end
end
```
=> Ruby: Handle captured `yield` calls

csharp/extractor/Semmle.Extraction.CSharp/Entities/OrdinaryMethod.cs, csharp/ql/lib/change-notes/2024-01-10-lambda-param-defaults.md, csharp/ql/lib/semmle/code/csharp/exprs/Call.qll, csharp/ql/test/library-tests/arguments/PrintAst.expected, csharp/ql/test/library-tests/arguments/argumentType.expected, csharp/ql/test/library-tests/arguments/lambdaArgument.expected, csharp/ql/test/library-tests/arguments/lambdaArgument.ql, csharp/ql/test/library-tests/arguments/lambdas.cs, csharp/ql/test/library-tests/parameters/LambdaParameters.cs, csharp/ql/test/library-tests/parameters/Parameters.expected
It turns out that the extractor "almost" works out of the box for `params` and default parameters for lambda expressions.
The implementation of "ordinary" lambdas are based on `System.Func` whereas the implementation of lambdas with parameter defaults or the use of `params` parameters are based on compiler generated delegates (as these features are already support by delegates).
Below is an example of some C# code that is compiled and de-compiled to illustrate the difference.
```csharp
class LambdaArgumentsTest
{
void M1()
{
var l1 = (int x) => x + 1;
var l2 = (int x, int y = 1) => x + y;
}
}
```
Compiling and de-compiling yields
```csharp
[CompilerGenerated]
internal delegate TResult <>f__AnonymousDelegate0<T1, T2, TResult>(T1 arg1, T2 arg2 = 1);
internal class LambdaArgumentsTest
{ …
```
=> C# 12: Support for lambda `param` parameter and parameter defaults.

javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll
Includes API sink nodes when unfolding types.
=> JS: Include sink nodes as base-case when resolving types

csharp/ql/test/library-tests/typealias/alias.cs, csharp/ql/test/library-tests/typealias/alias.expected, csharp/ql/test/library-tests/typealias/alias.ql
It turns out that type aliasing works out of the box.
The semantic model already contains the substituted types.
Should we consider to extract the alias directives (we have not done so up until now)?
=> C# 12: Type alias [Test only]

csharp/ql/lib/change-notes/2024-01-11-manual-neutral-model-blocks-generated-models.md, csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.cs, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.expected, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.ext.yml, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.ql, csharp/ql/test/library-tests/dataflow/external-models/Steps.cs, csharp/ql/test/library-tests/dataflow/external-models/steps.expected, csharp/ql/test/library-tests/dataflow/external-models/steps.ext.yml, csharp/ql/test/library-tests/dataflow/external-models/steps.ql, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/src/change-notes/2024-01-11-manual-neutral-model-blocks-generated-models.md, java/ql/test/library-tests/dataflow/external-models/C.java, java/ql/test/library-tests/dataflow/external-models/steps.expected, java/ql/test/library-tests/dataflow/external-models/steps.ext.yml
When a manual neutral summary model exists for a callable, we should ignore any generated summary models for it. This PR implements this for C# and Java. This will allow us to add manual neutral models for methods which we have decided we do not want flow for, such as hash functions.
=> C#/Java: Manual neutral summaries should block generated summaries

go/ql/lib/semmle/go/security/InsecureRandomness.qll, go/ql/lib/semmle/go/security/InsecureRandomnessCustomizations.qll, go/ql/src/change-notes/2024-01-10-insecure-randomness-index-flowstep.md, go/ql/test/query-tests/Security/CWE-338/InsecureRandomness/InsecureRandomness.expected, go/ql/test/query-tests/Security/CWE-338/InsecureRandomness/sample.go
This PR adds a flow step so that `go/insecure-randomness` recognizes the pattern of randomly selecting a character/substring from a predefined set with a weak RNG, which is a security risk if the result is used in a sensitive function.
Adds coverage for CVE-2023-46740.
=> Go: Recognize unsafe candidate selection in `go/insecure-randomness`

python/ql/src/Security/CWE-601/UrlRedirect.qhelp, python/ql/src/Security/CWE-601/examples/redirect_good.py, python/ql/src/Security/CWE-601/examples/redirect_good2.py
=> Python: Mention more sanitisation options in py/url-redirection qhelp.

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
I had hoped that this would fix the performance problems in https://github.com/github/codeql/pull/15194, but it doesn't look like it. Nevertheless, I think we should get this fix in since it may still be a (small) performance optimization _and_ it fixes more pointer/pointee conflation of global variables.
I've verified that all the lost results are due to pointer/pointee conflation being removed from global variables 🎉
=> C++: Fix duplicate "final global value" nodes

swift/swift-autobuilder/swift-autobuilder.cpp
This reverts commit dd13ea3d0a41764b065f6e50efff40aa4fc8ffca.
Reverting https://github.com/github/codeql/pull/15116 as it caused regression.
=> Revert "Swift: separate installation of dependencies and autobuilding"

go/extractor/cli/go-autobuilder/go-autobuilder.go
The `go version` command returns a version identifier which is not a valid semantic version. This is noticeable for pre-release builds of Go, such as `go1.22rc1`. Our existing handling of such versions meant that they were treated as invalid by `semver.Compare` and were therefore considered lower than all other versions. This PR implements a workaround for version identifiers that contain `rc` in them so that they are converted into a valid semantic version and therefore compared correctly.
=> Go: Better handle pre-release versions

java/ql/lib/change-notes/2024-01-06-regex-flag-parsing.md, java/ql/lib/semmle/code/java/regex/regex.qll, java/ql/test/library-tests/regex/parser/RegexParseTests.expected, java/ql/test/library-tests/regex/parser/RegexParseTests.ql, java/ql/test/library-tests/regex/parser/Test.java
Fixes:
- Flag `d` not being recognized
- Syntax for disabling flags (`-`) not being recognized
- Non-capturing group with flags erroneously containing `:` as literal
Any feedback is appreciated! Especially if I overlooked or failed to consider something.
I am not sure if this change is also relevant for the regex libraries of the other languages.
=> Java: Improve Regex flag parsing

swift/extractor/main.cpp, swift/logging/SwiftDiagnostics.cpp, swift/logging/SwiftDiagnostics.h, swift/logging/SwiftLogging.cpp, swift/logging/SwiftLogging.h, swift/logging/tests/assertion-diagnostics/AssertFalse.cpp, swift/swift-autobuilder/BuildRunner.cpp, swift/swift-autobuilder/swift-autobuilder.cpp, swift/tools/diagnostics/AutobuilderIncompatibleOs.cpp
In preparation for reusing this code for the C++ extractor telemetry,
* Rename `codeql::SwiftDiagnostic` to `codeql::Diagnostic`
* Provide `codeql::swiftDiagnostic()` to construct a Swift diagnostic.
=> Swift extractor: Generalise SwiftDiagnostics

docs/codeql/codeql-for-visual-studio-code/about-telemetry-in-codeql-for-visual-studio-code.rst
We plan to start collecting telemetry about which settings users are using in the CodeQL extension for VS Code, to help inform which features are useful or not. We currently only check for the `codeQL.canary` setting, but we'd like to extend this to others too, hence the slight change in wording!
For example, an upcoming change (https://github.com/github/vscode-codeql/pull/3238) will add telemetry for the `codeQL.addingDatabases.addDatabaseSourceToWorkspace` setting.
=> Add note about telemetry for CodeQL extension settings

swift/ql/lib/codeql/swift/elements/pattern/Pattern.qll
This gets rid of the expensive magic here:
```ql
OIN `m#Pattern::Pattern.getMatchingExpr/0#a063c6af#bf#prev_delta` WITH `_Element::Generated::Element.getResolveStep/0#dispred#f0bb72ef_0#antijoin_rhs_Element::Generated::El__#join_rhs#2` ON FIRST 1 OUTPUT Rhs.1
399       ~1%    {1} r2 = JOIN `m#Pattern::Pattern.getMatchingExpr/0#a063c6af#bf#prev_delta` WITH `_Element::Generated::Element.getResolveStep/0#dispred#f0bb72ef_0#antijoin_rhs_Element::Generated::El__#join_rhs#1` ON FIRST 1 OUTPUT Rhs.1
54       ~0%    {1} r3 = JOIN `m#Pattern::Pattern.getMatchingExpr/0#a063c6af#bf#prev_delta` WITH `_Element::Generated::Element.getResolveStep/0#dispred#f0bb72ef_0#antijoin_rhs_Element::Generated::El__#join_rhs` ON FIRST 1 OUTPUT Rhs.1
1784       ~0%    {2} r4 = JOIN …
```
=> Swift: Add `nomagic` to `Pattern.getMatchingExpr`

javascript/ql/test/query-tests/Security/CWE-020/SuspiciousRegexpRange/tst.js, shared/regex/codeql/regex/OverlyLargeRangeQuery.qll
Throwing the Python team is as reviewers because we found some FPs during some triage. 
Evaluations (see backrefs) look good.
=> JS/PY/JAVA/RB: mark the range [0-?] as good in the overly-large-range query

csharp/ql/lib/change-notes/2024-01-18-simpletype-sanitizer.md, csharp/ql/lib/semmle/code/csharp/security/Sanitizers.qll, csharp/ql/test/query-tests/Security Features/CWE-117/LogForging.expected, csharp/ql/test/query-tests/Security Features/CWE-117/LogForgingAsp.cs
In this PR we fix a range of false positives for queries that use *simple* type sanitizers.
Before this change, the following action method in an ASP.NET controller would lead to log forging alert
```csharp
public void Action(bool? b)
{
var logger = new ILogger();
if (b is not null)
{
// GOOD: Boolean? is a sanitizer.
logger.Warn($"Warning about the bool: {b}");
}
}
```
With the change in this PR, we now consider nullable *simple* types as sanitizers as well - removing the above alert.
=> C#: Consider nullable simple types as sanitizers.

docs/codeql/reusables/supported-frameworks.rst
JS/TS support is old; noting for symmetry with advertised support in Python. Golang support is new as of https://github.com/github/codeql/pull/15373
Describe it as a "serverless framework" for all, since it's a bit different from your typical web framework.
=> Note AWS Lambda support

python/ql/lib/semmle/python/frameworks/Django.qll, python/ql/lib/semmle/python/frameworks/Stdlib/Urllib.qll, python/ql/lib/semmle/python/frameworks/Yarl.qll, python/ql/lib/semmle/python/security/dataflow/UrlRedirectCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/UrlRedirectQuery.qll, python/ql/src/Security/CWE-601/UrlRedirect.qhelp, python/ql/src/Security/CWE-601/examples/redirect_good2.py, python/ql/src/Security/CWE-601/examples/redirect_good3.py, python/ql/src/change-notes/2023-12-21-url-redirect-more-sanitizers.md, python/ql/test/query-tests/Security/CWE-601-UrlRedirect/UrlRedirect.expected, python/ql/test/query-tests/Security/CWE-601-UrlRedirect/test.py
Fixes https://github.com/github/codeql/issues/15178.
Since some sanitisers don't handle backslashes correctly, I updated the data-flow configuration to incorporate a flow state tracking whether or not backslashes have been eliminated or converted to forward slashes.
=> Python: Add support for more URL redirect sanitisers.

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
Both of these cases are caused by the disjunction meaning that we join order seperately. When we have the disjunction we join order the outer join separately to the inner join. Currently we pick `hasIndexInBlock` first in the outer join. Then inside the block for every order we try we can't place `adjacentDefReadExt` without a CP (as we can never join with any argument), so basically we essentially ignore the `only_bind_into` pragmas and select that CP. Another optimisation comes along and removes the CP so it isn't awful in this case as joining on `bb1, i1` seems to be good enough but we are relying on that other optimisation and making the optimiser very confused.
This makes us actually pick the intended join order (from before the phi case was added). The other option is to remove …
=> CPP: Fix join ordering hints to make them do what they intend.

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/IDotNet.cs, csharp/extractor/Semmle.Extraction.Tests/DotNet.cs, csharp/extractor/Semmle.Extraction.Tests/Runtime.cs, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_error/Assemblies.expected, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_error/Assemblies.ql, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_error/proj/Program.cs, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_error/proj/nuget.config, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_error/proj/proj.csproj, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_error/standalone.sln, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_error/test.py
This PR slightly changes the package restore logic in the dependency manager. When a package couldn't be restored through `sln` or `csproj` files, we fall back to a dedicated `dotnet restore` on the package name. This fallback restore uses the `nuget.config` file in the repo. This PR changes the fallback logic to first try restoring with the `nuget.config`, and if that fails with `NU1301` error, then the restore is tried again without the `nuget.config`.
=> C#: Try fallback `dotnet restore` without nuget.config

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected, cpp/ql/test/library-tests/string_concat/strconcat.expected
In order to ensure that we don't have duplicated query results for `path-problem` queries we need to ensure that for a given expression `e`, there's only one dataflow node `n` such that `n.asExpr() = e`.
In order to ensure that only one such node exists, we use the dataflow node corresponding to the last _unique_ mention of the operand or instruction. To do that, we index the mapping from instructions (or operands) to expressions by an integer `n` that represents that this instruction (or operand) is the `n`'th instruction (or operand) whose unconverted expression result is `e`. When we compute which node `n` should have `n.asExpr() = e` we pick the largest `n` and let that node have a result for `asExpr()`.
To do that, most of the charpreds in the classes that map from dataflow nodes to …
=> C++: Remove more `asExpr` duplication

csharp/ql/lib/semmle/code/csharp/frameworks/Format.qll, csharp/ql/lib/semmle/code/csharp/security/dataflow/UrlRedirectQuery.qll, csharp/ql/src/change-notes/2024-01-22-url-redirect-sanitizer.md, csharp/ql/test/query-tests/Security Features/CWE-601/UrlRedirect/UrlRedirect.cs, csharp/ql/test/query-tests/Security Features/CWE-601/UrlRedirect/UrlRedirect.expected
In this PR we improve the sanitizer for `cs/web/unvalidated-url-redirection` to also take string interpolation expressions and string.Format into account.
That is, the following cases are now identified correctly:
```csharp
// GOOD: The attacker can only control the parameters, not the location
ctx.Response.Redirect($"foo.asp?param={url}");
// BAD: The attacker can control the location
ctx.Response.Redirect($"{url}.asp?param=foo");
// GOOD: The attacker can only control the parameters, not the location
ctx.Response.Redirect(string.Format("foo.asp?param={0}", url));
// BAD: The attacker can control the location
ctx.Response.Redirect(string.Format("{0}.asp?param=foo", url));
```
Prior to this change all of the above would generate alerts. The sanitizers introduced in this PR are simple as …
=> C#: Add more santizers to the `cs/web/unvalidated-url-redirection` query.

csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/CSharpAutobuilder.cs
This PR enables standalone extraction when `CODEQL_EXTRACTOR_CSHARP_BUILD_MODE` is `none`.  This enables triggering standalone extraction via the upcoming `--build-mode` CLI option and its integration into the CodeQL Action.
Tested by creating a database locally with `--build-mode none` and verifying that "Running C# standalone extractor" appears in the build logs.
=> C#: Enable standalone extraction via `--build-mode`

cpp/ql/lib/semmle/code/cpp/PrintAST.qll, cpp/ql/lib/semmle/code/cpp/exprs/Expr.qll, cpp/ql/lib/semmle/code/cpp/stmts/Stmt.qll, cpp/ql/test/library-tests/destructors/PrintAST.expected, cpp/ql/test/library-tests/destructors/PrintAST.ql, cpp/ql/test/library-tests/destructors/destructors.expected, cpp/ql/test/library-tests/destructors/destructors.ql, cpp/ql/test/library-tests/ir/ir/PrintAST.expected
This PR adds a new `getSyntheticDestructor` predicate to `Stmt` and `Expr`, and adds destructors to the IR. Currently only the `Stmt` relation is populated by the extractor.
=> C++: First-class destructors in AST

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
This fixes a bad join on a boolean that we're seeing in https://github.com/github/codeql/pull/15421.
Before:
```ql
Pipeline standard for DataFlowImpl::Impl<ExecTainted::ExecState::C>::Stage2::fwdFlowIn/6#c607111e@49e568w9 was evaluated in 542 iterations totaling 5390ms (delta sizes total: 2160).
15796    ~3%    {8} r1 = SCAN `DataFlowImpl::Impl<ExecTainted::ExecState::C>::Stage2::fwdFlowIntoArg/11#f173ad92#prev_delta` OUTPUT In.10, In.0, In.1, In.2, In.6, In.7, In.8, In.9
61741080    ~1%    {10}    | JOIN WITH `DataFlowImpl::Impl<ExecTainted::ExecState::C>::Stage2::FwdFlowIn<FwdFlowInNoRestriction>::fwdFlowInValidEdgeTypeFlowDisabled/4#6ab9ff68_3012#join_rhs` ON FIRST 1 OUTPUT Lhs.3, Lhs.1, Lhs.2, Lhs.4, Lhs.5, Lhs.6, Lhs.7, Rhs.1, Rhs.2, Rhs.3
41848245    ~1%    {10} r2 = JOIN r1 WITH …
```
=> DataFlow: Fix join order

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/library-tests/dataflow/asExpr/test-indirect.expected, cpp/ql/test/library-tests/dataflow/asExpr/test-indirect.ql, cpp/ql/test/library-tests/dataflow/asExpr/test.cpp, cpp/ql/test/library-tests/dataflow/asExpr/test.expected, cpp/ql/test/library-tests/dataflow/asExpr/test.ql
The first commit adds an inline expectations test for testing the behavior of `asExpr` and `asIndirectExpr`. The next commit fixes some `asIndirectExpr` duplication similar to how it was fixed for `asExpr` in https://github.com/github/codeql/pull/15410.
(DCA looks uneventful)
=> C++: Add `asExpr` and `asIndirectExpr` library tests (and fix more duplication)

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
This works around
https://youtrack.jetbrains.com/issue/KT-63847/K2-IllegalStateException-IrFieldPublicSymbolImpl-for-java.time-Clock.OffsetClock.offset0-is-already-bound
=> Kotlin: Catch/ignore a IllegalArgumentException exception

cpp/ql/src/Critical/ScanfChecks.qll, cpp/ql/src/change-notes/2024-01-29-incorrectly-checked-scanf.md, cpp/ql/test/query-tests/Critical/MissingCheckScanf/IncorrectCheckScanf.expected, cpp/ql/test/query-tests/Critical/MissingCheckScanf/MissingCheckScanf.expected, cpp/ql/test/query-tests/Critical/MissingCheckScanf/test.cpp
Note that, because the `cpp/missing-check-scanf` query only raises an alert if `cpp/incorrectly-checked-scanf` doesn't, by fixing the FP in `cpp/incorrectly-checked-scanf` we're now moving the alert to the `cpp/missing-check-scanf` query.
This is a good trade-off since `cpp/incorrectly-checked-scanf` is a high-precision query, and `cpp/missing-check-scanf` is only at precision `medium`.
I tried to fix the FP in `cpp/incorrectly-checked-scanf` as well, but this is more difficult. So I think we should get this fix in first before trying to fix the `cpp/incorrectly-checked-scanf` case.
=> C++: Fix FP in `cpp/incorrectly-checked-scanf`

cpp/ql/src/Critical/ScanfChecks.qll, cpp/ql/src/change-notes/2024-01-29-incorrectly-checked-scanf-2.md, cpp/ql/test/query-tests/Critical/MissingCheckScanf/IncorrectCheckScanf.expected, cpp/ql/test/query-tests/Critical/MissingCheckScanf/MissingCheckScanf.expected, cpp/ql/test/query-tests/Critical/MissingCheckScanf/test.cpp
Fixes https://github.com/github/codeql/issues/15415 by correctly identifying that `scanf(...) >= 0` also implies that `scanf(...) != EOF` (because the C standard specifies that `EOF` is negative).
As with https://github.com/github/codeql/pull/15456, this moves the FP to the `cpp/missing-check-scanf` query. I suggest we fix that one in a future PR.
=> C++: Fix another FP in `cpp/incorrectly-checked-scanf`

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected, ruby/ql/test/library-tests/dataflow/local/InlineFlowTest.expected, ruby/ql/test/library-tests/dataflow/local/TaintStep.expected, ruby/ql/test/library-tests/dataflow/local/local_dataflow.rb
The only values that can flow from the LHS of an `&&` expression are
`false` and `nil`, neither of which seem relevant for any of our
queries.
=> Ruby: Block flow from LHS of && expressions

ruby/ql/src/utils/modeleditor/ModelEditor.qll
This will report when summary and neutral methods are supported by MaD in the framework mode endpoints query for the model editor. It follows the same pattern as `SinkCallable` and `SourceCallable`, but the implementations for summary and neutral models are simpler because they don't need to extract the method name from the path manually.
=> Ruby: Correctly report supported status of summary and neutral models

python/ql/lib/change-notes/2024-01-22-html-escape.md, python/ql/lib/semmle/python/frameworks/Stdlib.qll, python/ql/test/library-tests/frameworks/stdlib/test_html.py
I've seen a few FPs related to XSS where `html.escape` has been used. When quotes are not escaped, it could end up being used in a dangerous way such as this example:
```py
html = '<foo attr="' + html.escape(user_input, quote=False) + '">...</foo>'
```
I couldn't really decide whether we should allow this as a sanitizer when quotes are not escaped, but ended up allowing it as a sanitizer, since it was easier this way. (Let me know if you think not doing so was not the right choice)
We should check how JS approaches this, I think they have a more sophisticated way of handling it.
=> Python: Add `html.escape` as HTML sanitizer

ruby/ql/lib/codeql/ruby/ast/Call.qll, ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/typetracking/internal/TypeTrackingImpl.qll, ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
On https://github.com/github/codeql/pull/15370, @hmac identified some spurious flow, which is ultimately down to how call-context sensitivity was implemented.
Previously, we would only consider a call context `ctx` to be relevant for a call `call`, when the target of `call` can also be looked up in the argument of `ctx` which matches the parameter that is the receiver of `call`. For example, in
```rb
def call_m x
x.m             # (1)
end
class A
def m
end
end
class B
end
call_m A.new      # (2)
call_m B.new      # (3)
```
the call `x.m` (1) will only consider call context (2) to be relevant and not call context (3). This means that if flow enters via (3), we will incorrectly consider `A#m` to be a viable target of (1).
This PR lifts this restriction, and instead considers any call …
=> Ruby: Rework `mayBenefitFromCallContext`

ruby/ql/src/queries/modeling/internal/Util.qll
When using the [`GenerateModel.ql`](https://github.com/github/codeql/blob/c265c15f3f4fa2058d9172d4f078fe6c7760eaf0/ruby/ql/src/queries/modeling/GenerateModel.ql) query, it was generating type models for private methods. These don't add any value for consumers of the library, so we don't need to model those. Therefore, this will only allow modeling of public methods.
=> Ruby: Only generate models for public methods

cpp/ql/src/Likely Bugs/Memory Management/UninitializedLocal.ql, cpp/ql/src/change-notes/2024-01-29-uninitialized-local-false-positive.md, cpp/ql/test/query-tests/Security/CWE/CWE-457/semmle/tests/test.cpp
False positive fix for cpp/uninitialized-local to address unallocated pointer access to static methods.
=> False positive fix for cpp/uninitialized-local

ruby/ql/src/queries/modeling/internal/Types.qll, ruby/ql/src/queries/modeling/internal/Util.qll, ruby/ql/src/utils/modeleditor/ModelEditor.qll
When we have a test like [`class BlankTest < Minitest::Test`](https://github.com/Shopify/liquid/blob/9b38a1528266aec36918a5188563d9c42b2500ea/test/integration/blank_test.rb#L12), we shouldn't create a model like `"Minitest::Test", "BlankTest", ""` since the `BlankTest` is irrelevant for consumers of the library. This fixes it by only considering these models where both modules are in relevant files (i.e. in non-test files).
=> Ruby: Only model relevant files for type models

ruby/ql/lib/codeql/ruby/security/InsecureRandomnessCustomizations.qll, ruby/ql/lib/codeql/ruby/security/InsecureRandomnessQuery.qll, ruby/ql/src/change-notes/2023-12-18-insecure-randomness-query.md, ruby/ql/src/experimental/insecure-randomness/InsecureRandomness.qhelp, ruby/ql/src/experimental/insecure-randomness/InsecureRandomness.ql, ruby/ql/src/experimental/insecure-randomness/examples/InsecureRandomnessBad.rb, ruby/ql/src/experimental/insecure-randomness/examples/InsecureRandomnessGood.rb, ruby/ql/test/query-tests/experimental/InsecureRandomness/InsecureRandomness.expected, ruby/ql/test/query-tests/experimental/InsecureRandomness/InsecureRandomness.qlref, ruby/ql/test/query-tests/experimental/InsecureRandomness/InsecureRandomness.rb
This pull request adds a query for Insecure Randomness.
Looking forward to your suggestions.
=> Ruby: Add Insecure Randomness Query 

ruby/ql/src/utils/modeleditor/ModelEditor.qll, ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeEndpoints.expected, ruby/ql/test/query-tests/utils/modeleditor/lib/mylib.rb
This changes the model editor endpoint query to model constructors (i.e. `initialize` instance methods) as `Type!#new`, rather than as `Type#initialize`. This matches [the way that `Util::pathToMethod` models these methods](https://github.com/github/codeql/blob/c1aaf5a5744f28e9d5f19d14188c0203694d344c/ruby/ql/src/queries/modeling/internal/Util.qll#L49-L56).
=> Ruby: Model constructors in endpoint query on new instead of initialize

csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Invocation.cs, csharp/ql/test/library-tests/delegates/Delegates4.expected, csharp/ql/test/library-tests/delegates/Delegates4.ql, csharp/ql/test/library-tests/delegates/PrintAst.expected, csharp/ql/test/library-tests/delegates/delegates.cs
This PR fixes an extractor bug where we would incorrectly determine the qualifier of a delegate call when it was a qualified expression. For example, in
```csharp
this.LambdaField(0)
```
where `LambdaField` is a field holding a lambda, we would consider `this` to be the qualifier of the delegate call, instead of `this.LambdaField`.
=> C#: Fix extraction of qualified delegate calls

go/extractor/cli/go-autobuilder/go-autobuilder.go, go/extractor/diagnostics/diagnostics.go
This PR slightly improves the `go/autobuilder/newer-go-version-needed` diagnostic by including version information as well making it clearer what the versions relate to.
=> Go: Include versions in newer Go version needed diagnostic

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNetCliInvoker.cs
Same as https://github.com/github/codeql/pull/15491, but for the dependency fetcher used in buildless mode.
=> C#: Disable msbuild node reuse in dependency fetcher

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/fields/E.cs, csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected
In this PR we introduce inter-procedural dataflow for `ref` structs when used as arguments to calls.
Until now, the C# dataflow library assumed that if `s` is a struct then the following was safe as structs have value type semantics (that is, calling `DoStuff` could not have the side effect of changing `Field` on `s`).
```csharp
s.Field = "safe";
DoStuff(s);
Sink(s.Field);
```
However, for `ref` structs we can have `ref` fields, which means that the observable state of the struct can be altered.
This is solved by adding post update nodes for arguments of type ref struct. However, this might also introduce false positive flow for non-ref fields - therefore we exclude these.
This is an imperfect solution, but these are already corner case scenarios.
This PR is a pre-requisite for adding …
=> C#: Inter-procedural dataflow for `ref` structs when used as arguments.

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/models/interfaces/FunctionInputsAndOutputs.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/TestBase.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/flowOut.cpp, cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/uninitialized.expected, cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowDestination.expected
This PR fixes a TODO that I left in as part of https://github.com/github/codeql/pull/14799.
In the above PR we removed false flow in code like:
```cpp
void modify_copy(int* p) {
int x = *p; // (1)
taint(&x);
}
void test() {
int x;
modify_copy(&x);
sink(x);
}
```
by teaching the C/C++ dataflow library to rule out certain flow steps that shouldn't be used when calculating summaries (i.e., there shouldn't be a summary from the indirection of the input argument to `modify_copy` to the output indirection of `modify_copy`). The terminology I used was that the step from `*p` to `x` at `// (1)` isn't "identity preserving".
This PR extends this set of exclusion rules to also block flow when a modelled function isn't identity preserving. A common example that we've seen in many FPs is …
=> C++: Block summary flow through `strdup` and friends

java/ql/automodel/src/AutomodelApplicationModeCharacteristics.qll, java/ql/automodel/test/AutomodelApplicationModeExtraction/Test.java
We were already filtering lambda expressions; this is a bit more general. I left the lambda-expression filtering in anyway, just in case we get weird type information.
=> Automodel: Do not consider `@FunctionalInterface`-typed expressions as candidates.

cpp/ql/lib/change-notes/2024-01-30-preproc-block.md, cpp/ql/lib/semmle/code/cpp/headers/PreprocBlock.qll, cpp/ql/test/library-tests/headers/preprocBlock/header.h, cpp/ql/test/library-tests/headers/preprocBlock/preprocblock.cpp, cpp/ql/test/library-tests/headers/preprocBlock/preprocblock.expected, cpp/ql/test/library-tests/headers/preprocBlock/preprocblock.ql, cpp/ql/test/library-tests/headers/preprocBlock/preprocinclude.expected, cpp/ql/test/library-tests/headers/preprocBlock/preprocinclude.ql
The `PreprocBlock.qll` library offers a view of `#if`, `#elif`, `#else` and similar directives (and the code they contain) as a tree.  That is, there's a parent-child relationship between blocks (identified by their opening directive), as well as the ability to tell what include statements and macro definitions are contained within each block.
---
The `preprocblock.expected` test is a good place to start if the above isn't crystal clear.
This is actually an old library, but until now it's not been available in the codeql repo.
=> C++: Add PreprocBlock.qll library

ruby/ql/src/utils/modeleditor/FrameworkModeAccessPaths.ql, ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeAccessPaths.expected, ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeAccessPaths.qlref, ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeEndpoints.expected, ruby/ql/test/query-tests/utils/modeleditor/lib/mylib.rb
This adds a simple query for creating a subset of valid access paths that can be used in MaD models. It's not intended to be complete, and will probably be rewritten to be a recursive query rather than this simple query.
Considerations:
- Right now, it's a simple query that hardcodes some strings, but it should be recursive in the future.
- In the future, it might make sense to make this a graph query (i.e. having `nodes` and `edges` query predicates), but we want to get this simple solution in first.
- `Util::pathToNode` does something close to what we want, but it doesn't have the `details` and `defType`, which are really useful to have in the model editor.
- The intention is to iterate on this query, so the most important part for now is that the query is at least correct in reporting …
=> Ruby: Add query for access paths in model editor

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/Instruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/internal/SSAConstruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/Instruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/IRConstruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/Instruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SSAConstruction.qll, csharp/ql/src/experimental/ir/implementation/raw/Instruction.qll, csharp/ql/src/experimental/ir/implementation/raw/internal/IRConstruction.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/Instruction.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/internal/SSAConstruction.qll
The `getIntervalUpdatedByChi` predicate used to be consumed by IR dataflow a long time ago, but this hasn't been the case for more than a year. We might as well just delete this predicate now.
=> C++: Delete unused IR predicate

cpp/ql/lib/change-notes/2024-02-06-flow-out-barrier-function.md, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/Swap.qll, cpp/ql/lib/semmle/code/cpp/models/interfaces/FlowOutBarrier.qll, cpp/ql/test/library-tests/dataflow/taint-tests/map.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/set.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/string.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/stringstream.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/vector.cpp
This PR adds a new abstract class `FlowOutBarrierFunction` for blocking flow out of a function model. One of the obvious examples is `std::swap` where we on `main` has this FP:
```
void test() {
char* s1 = tainted();
char* s2 = nullptr;
std::swap(s1, s2);
sink(s1); // should not be tainted
}
```
This PR adds an interface for specifying that such functions shouldn't have flow out of a given `FunctionInput`. Operationally, this amounts to blocking use-use flow once the data reaches the function's input.
In this PR I've just implemented the class on `std::swap`. Once the change is in we can provide extents for a bunch of other classes that we currently model.
=> C++: Add an interface for models to block flow

cpp/ql/lib/semmle/code/cpp/models/implementations/Swap.qll, cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
In https://github.com/github/codeql/pull/15528 I forgot to model that `std::swap` also clears the 0'th argument. This PR fixes that.
DCA looks uneventful. There are two failing projects because of a known bug in DCA that is being worked on as we speak. This shouldn't block this PR, though.
=> C++: Also clear the `0`'th argument of `swap`

csharp/codeql-extractor.yml, go/codeql-extractor.yml, ql/codeql-extractor.yml, ruby/codeql-extractor.yml, swift/codeql-extractor.yml
This is in preparation for the new starter workflow described in the buildless experience ADR where we will specify the build mode for each language explicitly.  This metadata only affects runs where a `--build-mode` option is specified, which currently does not impact production.
=> Add supported build modes to extractor metadata

ruby/ql/src/utils/modeleditor/FrameworkModeAccessPaths.ql, ruby/ql/src/utils/modeleditor/ModelEditor.qll, ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeAccessPaths.expected, ruby/ql/test/query-tests/utils/modeleditor/FrameworkModeEndpoints.expected, ruby/ql/test/query-tests/utils/modeleditor/GenerateModel.expected, ruby/ql/test/query-tests/utils/modeleditor/lib/mylib.rb
This removes the `ReturnValue` as a valid access path for constructors. In a constructor, I believe the `ReturnValue` is meaningless since it's equal to `Argument[self]`.
The main reason that I ran into this is that `getAReturnNode()` for a constructor returns every statement in the `initialize` method as a return node, so we were getting duplicate `ReturnValue` rows.
If `ReturnValue` is a valid value for constructors, I think the easiest solution would be to return `getSelfParameter()` as the node instead of the return node.
=> Ruby: Remove `ReturnValue` as access path for constructors

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/type-bugs.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/type-bugs.ql
We were calling `getUnspecifiedType` instead of `getUnderlyingType` in a bunch of places when computing the type of a dataflow node, and since `getUnspecifiedType` strips away specifiers such as `const` and `volatile` we could get into a situation where a node's `getType` returned `int` while the same node's `asExpr().getType()` returned `const int`.
The fix is to use `getUnderlyingType` instead of `getUnspecifiedType` since `getUnderlyingType` only resolves `typedefs` without stripping specifiers.
Finally, I also fixed a bug where some nodes were not correctly specified as being dataflow nodes wrapping a glvalue instruction or operand. This also fixed some inconsistency errors.
There still are some type-related bugs, but they seem a bit more difficult to fix. I'll write up an issue for …
=> C++: Don't strip specifiers in `Node.getType`

csharp/ql/consistency-queries/DataFlowConsistency.ql, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/delegates/DelegateFlow.cs, csharp/ql/test/library-tests/dataflow/delegates/DelegateFlow.expected
This PR adds support for tracking lambdas through fields and (field-like) properties, but (currently) limited to assignments in constructors and uses in instance methods:
```csharp
class C
{
private Action a;
public C(Action a)
{
this.a = a; // (1)
}
public void CallAction()
{
this.a(); // (2)
}
public void SetAction(Action a)
{
this.a = a; // (3)
}
}
```
That is, we will track lambdas from `(1)` to `(2)`, but not from `(2)` to `(3)`. This restriction is because the data flow algorithm for tracking lambdas is not field-sensitive, hence we need to model field stores/reads as jump steps, and therefor apply the conservative restriction above.
I spot checked a few of the new results, and they are indeed the result of more lambda calls being resolvable.
=> C#: Additional tracking of lambdas through fields and properties

javascript/ql/src/LanguageFeatures/SpuriousArguments.ql, javascript/ql/test/query-tests/LanguageFeatures/SpuriousArguments/tst.js
Fixes: https://github.com/github/codeql/issues/15286
[Evaluation looks OK](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-15523-94b7bd__nightly-old__CustomSuite/reports).
=> JS: exclude tagged template literals from `js/superfluous-trailing-arguments`

java/ql/lib/semmle/code/java/security/AndroidLocalAuthQuery.qll, java/ql/src/Security/CWE/CWE-287/AndroidInsecureLocalAuthentication.qhelp, java/ql/src/Security/CWE/CWE-287/AndroidInsecureLocalAuthentication.ql, java/ql/src/Security/CWE/CWE-287/AndroidInsecureLocalAuthenticationBad.java, java/ql/src/Security/CWE/CWE-287/AndroidInsecureLocalAuthenticationGood.java, java/ql/src/change-notes/2024-02-02-android-insecure-local-auth.md, java/ql/test/query-tests/security/CWE-287/InsecureLocalAuth.expected, java/ql/test/query-tests/security/CWE-287/InsecureLocalAuth.ql, java/ql/test/query-tests/security/CWE-287/Test.java, java/ql/test/query-tests/security/CWE-287/Test2.java, java/ql/test/query-tests/security/CWE-287/options, java/ql/test/stubs/google-android-9.0.0/android/hardware/biometrics/BiometricPrompt.java, java/ql/test/stubs/google-android-9.0.0/android/hardware/fingerprint/FingerprintManager.java, java/ql/test/stubs/google-android-9.0.0/android/os/Bundle.java, java/ql/test/stubs/google-android-9.0.0/android/os/Parcel.java, java/ql/test/stubs/google-android-9.0.0/android/security/identity/IdentityCredential.java, java/ql/test/stubs/google-android-9.0.0/android/security/identity/PersonalizationData.java, java/ql/test/stubs/google-android-9.0.0/android/security/identity/PresentationSession.java, java/ql/test/stubs/google-android-9.0.0/android/security/identity/ResultData.java, java/ql/test/stubs/google-android-9.0.0/android/util/ArrayMap.java, java/ql/test/stubs/google-android-9.0.0/androidx/biometric/BiometricPrompt.java
This query finds instances of local authentication callbacks that don't use a `CryptoObject`.
=> Java: Add query for insecure local authentication

java/ql/src/Security/CWE/CWE-078/ExecRelative.ql, java/ql/src/change-notes/2024-02-12-relative-exec-severity.md
Significantly reduces the severity of `java/relative-path-command` from 9.8 to 5.4
https://www.first.org/cvss/calculator/4.0#CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N
This is the result of a conversation between myself and @JarLob that can be found in the GitHub Security Ambassadors Slack channel here: https://github-partners.slack.com/archives/C01MF7QQK3P/p1706734093860739
@JarLob's opinion was that the severity should likely be even lower than a 5.4, possibly bringing it down as much as `low` given the attacker would have to have significant system control to exploit this.
=> Reduce severity of `java/relative-path-command`

ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/test/library-tests/frameworks/active_record/ActiveRecord.expected, ruby/ql/test/library-tests/frameworks/active_record/ActiveRecord.rb
Recognise calls to `connection` on ActiveRecord instances.
=> Ruby: Recognise more ActiveRecord connections

python/ql/lib/change-notes/2024-01-29-psycopg-modeling.md, python/ql/lib/semmle/python/Frameworks.qll, python/ql/lib/semmle/python/frameworks/Psycopg.qll, python/ql/test/library-tests/frameworks/psycopg/ConceptsTest.expected, python/ql/test/library-tests/frameworks/psycopg/ConceptsTest.ql, python/ql/test/library-tests/frameworks/psycopg/pep249.py
Not as much used as the predecessor `psycopg2`, but since they're recommending using the newer version (v3) for new projects, that should change over time :blush:
=> Python: Model the `psycopg` package

java/ql/test/library-tests/dataflow/inoutbarriers/A.java, java/ql/test/library-tests/dataflow/inoutbarriers/test.expected, java/ql/test/library-tests/dataflow/inoutbarriers/test.ql, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
Fixes a bug in the handling of stateful out-barriers.
These were initially handled at the very last pruning step, since they aren't relevant for pruning in practice.
However, `subpaths` is computed in a way that isn't affected by the pruning, whereas `edges` is affected. This can result in a tuple `subpaths(arg, par, ret, res)` where `edges*(par, ret)` does not hold.
This means we get a spurious `arg -> res` edge, which can result in a spurious alert. And this alert is missing its data flow path, because no path can be materialised for `par -> ret`.
The solution I've opted for is just to check the out-barrier when we generate the steps that feed into `pathStep`. I've verified (for one query) that when stateful out-barriers aren't in use, the DIL is unaffected.
=> Shared: fix a bug in stateful outbarriers

python/BUILD.bazel, python/downgrades/BUILD.bazel
This allows us to (later) build the whole python language pack with bazel.
=> Python: Update BUILD.bazel files.

cpp/ql/lib/semmle/code/cpp/models/implementations/Memset.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
Turns out we were missing a really important flow summary for `memset` 😱
=> C++: Fix `memset` model

go/extractor/extractor.go, go/extractor/gomodextractor.go, go/ql/lib/semmle/go/Files.qll
We do not currently call `extractFileInfo` for dummy files (used e.g. when emitting diagnostics that do not relate to a particular file/location), which leads to a database inconsistency when it happens because the dummy file that is referenced is does not exist in the database. This PR inserts that missing `extractFileInfo` call and ensures that the dummy file does not end up in `CompilationCompilingFilesTable`. 
Note that this currently results in the dummy file appearing in e.g. `File` queries and we should decide whether this is OK (since it is obviously a dummy file) or modify the database schema or QL library so that the dummy files are hidden.
=> Go: Fix file info extraction for dummy files

java/ql/lib/semmle/code/java/Expr.qll
Resolves #3266 (see discussion there)
This change tries to document the current behavior, reducing some confusion regarding which CodeQL class covers which assignment type.
I assume this requires no change note since these are only documentation changes, is that correct?
However, personally I think maybe `Assignment` should actually cover `UnaryAssignExpr` (at least the name <code>Unary<b>Assign</b>Expr</code> suggests this). For example if you currently want to check for any assignments to array elements you still have to write custom code for this because as mentioned `Assignment` does not cover `UnaryAssignExpr`, and all the `Var...` classes don't work either because the assignment is not directly on a variable, but instead on an `ArrayAccess`.
=> Java: Document which assignment type is covered by which class

shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll
`viableCallableExt` is called in `resolveReturn` and `resolveCall`, so it should to be cached.
=> Data flow: Cache `viableCallableExt`

javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/BasicExprTypeInference.qll, javascript/ql/src/change-notes/2024-02-13-block-logical-and-flow.md, javascript/ql/test/library-tests/DataFlow/tests.expected, javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/library-tests/TaintTracking/DataFlowTracking.expected, javascript/ql/test/library-tests/TaintTracking/logical-and.js, javascript/ql/test/query-tests/Statements/UselessConditional/UselessConditional.expected
This removes the data flow edge from `x` to `x && y`. Since only falsy values can propagate through we usually do not care about this data flow.
=> JS: Fix flow through &&

go/ql/test/query-tests/Security/CWE-798/HardcodedCredentials.expected, go/ql/test/query-tests/Security/CWE-798/jwt.go
We don't want name-based heuristics to pick these variable names, but also using something like 'safeName' may mislead readers into believing the test cases are intended to be GOOD cases (i.e. safe).
=> Go: Use less confusing name for hardcoded credentials tests

docs/codeql/codeql-language-guides/customizing-library-models-for-ruby.rst
Add documentation on customizing Ruby analysis using data extensions. This closely follows the format of the JS documentation.
=> Ruby: add docs for customizing library models with data extensions

ruby/ql/lib/change-notes/2024-02-12-raw-erb-output.md, ruby/ql/lib/codeql/ruby/ast/Erb.qll, ruby/ql/lib/codeql/ruby/ast/internal/Erb.qll, ruby/ql/lib/codeql/ruby/security/XSS.qll, ruby/ql/test/query-tests/security/cwe-079/ReflectedXSS.expected, ruby/ql/test/query-tests/security/cwe-079/app/views/foo/bars/show.html.erb
In Rails at least, `<%== x %>` is equivalent to `<%= raw x %>` or `<%= x.to_s.html_safe %>`.
=> Ruby: Recognise raw Erb output as XSS sink

java/ql/lib/semmle/code/java/security/PathSanitizer.qll, java/ql/src/change-notes/2024-02-15-path-sanitizer-equals.md, java/ql/test/library-tests/pathsanitizer/Test.java, java/ql/test/library-tests/pathsanitizer/TestKt.kt
Handles the pattern `"/safe/path".equals(tainted)` as a path injection sanitizer.
=> Java: Expand ExactPathSanitizer to work on the argument of 'equals' too

.github/workflows/check-change-note.yml, .github/workflows/check-implicit-this.yml, .github/workflows/check-qldoc.yml, .github/workflows/check-query-ids.yml, .github/workflows/close-stale.yml, .github/workflows/compile-queries.yml, .github/workflows/csharp-qltest.yml, .github/workflows/csv-coverage-metrics.yml, .github/workflows/csv-coverage-pr-artifacts.yml, .github/workflows/csv-coverage-pr-comment.yml, .github/workflows/csv-coverage-timeseries.yml, .github/workflows/csv-coverage-update.yml, .github/workflows/csv-coverage.yml, .github/workflows/fast-forward.yml, .github/workflows/go-tests-other-os.yml, .github/workflows/go-tests.yml, .github/workflows/labeler.yml, .github/workflows/mad_regenerate-models.yml, .github/workflows/ql-for-ql-build.yml, .github/workflows/ql-for-ql-dataset_measure.yml, .github/workflows/ql-for-ql-tests.yml, .github/workflows/query-list.yml, .github/workflows/ruby-build.yml, .github/workflows/ruby-dataset-measure.yml, .github/workflows/ruby-qltest.yml, .github/workflows/swift.yml, .github/workflows/sync-files.yml, .github/workflows/tree-sitter-extractor-test.yml, .github/workflows/validate-change-notes.yml
Repositories can be configured with Default access (restricted) https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
Best practice says that workflows should declare the minimal permissions they require. Without declaring permissions, paranoid forks fail miserably.
closes #15462
=> Declare permissions

csharp/ql/lib/semmle/code/csharp/security/dataflow/UrlRedirectQuery.qll, csharp/ql/src/change-notes/2024-02-14-url-sanitizers.md, csharp/ql/test/query-tests/Security Features/CWE-601/UrlRedirect/UrlRedirect.expected, csharp/ql/test/query-tests/Security Features/CWE-601/UrlRedirect/UrlRedirect2.cs
I was looking at the QHelp for `cs/web/unvalidated-url-redirection`, but it was hard to write good fix examples that weren't flagged by the query.  
So I've added a few new sanitizers to the query.  
I've worked very little with queries that use the shared dataflow library, and I think this might be my first "real" C# PR.  
What I'm saying is to look closely, because I might have made some silly mistake.
=> C#: Add a few more sanitizers to `cs/web/unvalidated-url-redirection`

java/ql/automodel/src/AutomodelApplicationModeCharacteristics.qll, java/ql/automodel/src/AutomodelFrameworkModeCharacteristics.qll, java/ql/automodel/test/AutomodelApplicationModeExtraction/Test.java, java/ql/automodel/test/AutomodelFrameworkModeExtraction/com/github/codeql/test/MyWriter.java, java/ql/automodel/test/AutomodelFrameworkModeExtraction/java/io/File.java
The two fixes are conceptually independent, but both came up during a recent triage (https://github.com/github/codeql/pull/15486).
The first one is to do with implicit varargs arrays: the extraction queries for mining endpoint candidates aim to exclude known models, but were previously failing to properly match up implicit varargs arrays in application mode. That's because we were using the data-flow nodes of the individual arguments collected into the varargs array to represent the endpoints, but the MaD models refer to the `ImplicitVarargsArray` node. We now do the latter as well.
The second one is to do with recognising existing models for method parameters and return values: if an existing model is marked as `subtypes=True`, we should consider overriding methods to also be covered by …
=> Automodel: Improve handling of varargs and overriding in extraction queries

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
This is a preparatory change to an upcoming PR I'm doing related to the "automatically block flow out of modelled functions" work. It won't really have any visible impact yet, so it should be a totally safe change.
The core of the change is that we were incorrectly calling `getUnspecifiedType` instead of `getUnderlyingType` when checking whether a parameter could be written to. Calling `getUnspecifiedType` is wrong since, in addition to resolve typedefs, it also strips off `const` specifiers.
Instead, we should be calling `getUnderlyingType` since that _only_ resolves typedefs.
DCA looks uneventful (as expected).
=> C++: Don't strip specifiers away in `TFinalParameterUse`

.github/workflows/csv-coverage-update.yml
This pull request includes a change to the `.github/workflows/csv-coverage-update.yml` file. The permissions for `contents` have been updated from `read` to `write`. This change allows the workflow to modify the repository's contents. The workflow currently fails when it pushes a new commit to a specific branch in the repo.
=> Extend permissions in `csv-coverage-update.yml`

.github/workflows/ql-for-ql-build.yml
We downgraded to `read` in https://github.com/github/codeql/pull/15493 but it looks like we need `write` to upload the SARIF. See [failure](https://github.com/github/codeql/actions/runs/7916238959/job/21635263983).
=> Add `security-events: write` permission in `ql-for-ql-build.yml`

cpp/ql/src/CHANGELOG.md, cpp/ql/src/change-notes/released/0.9.4.md
This patches the changenote in the release branch to be in line with the version on main, so that changelog generation can proceed from the release branch.
=> Fix change note on 2.16.2 release branch

java/ql/test/library-tests/dataflow/flowfeature/A.java, java/ql/test/library-tests/dataflow/flowfeature/flow.expected, java/ql/test/library-tests/dataflow/flowfeature/flow.ql, shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll
The flow features `FeatureHasSourceCallContext` and `FeatureEqualSourceSinkCallContext` didn't work for parameterless static functions. This bug is fairly obscure, since most use-cases of those two features expect the source to be a parameter, and that's why it has gone undetected for quite some time.
=> Dataflow: Fix flow-feature bug for parameterless static functions

swift/BUILD.bazel, swift/ql/test/extractor-tests/run_under/Strings.expected, swift/third_party/BUILD.swift-llvm-support.bazel, swift/third_party/swift-llvm-support/BUILD.bazel, swift/tools/qltest.sh, swift/tools/test/qltest/utils.py
The test sdk that we were prebuilding to run ql tests is actually not needed, as the `resource-dir` we package for cross-version compatibility is enough for running qltests as well.
=> Swift: remove test sdk

swift/third_party/load.bzl
This includes:
* prebuilding Swift on Ubuntu 20.04 like we were previously doing
* removing unneeded ios, tvos, etc targets from the prebuilding, that we don't use any way.
=> Swift: update swift prebuilt package

java/ql/integration-tests/all-platforms/java/buildless-sibling-projects/buildless-fetches.expected, java/ql/integration-tests/all-platforms/java/buildless-sibling-projects/diagnostics.expected
Older / shadowed versions of dependencies are also added to the classpath, hence the change here
=> Java: test changes for making buildless' classpath ordering deterministic

.github/workflows/go-tests-other-os.yml, .github/workflows/go-tests.yml, go/ql/test/library-tests/semmle/go/Function/TypeParamType.expected
This bumps the version of Go used for our query tests to 1.22 and updates the expected test output for one test accordingly.
=> Go: Update workflows and expected test results for Go 1.22

java/ql/lib/semmle/code/java/security/SensitiveLoggingQuery.qll
This is also slightly faster to evaluate (217s instead of 228s on apache/geode on my machine).
=> Java: Sensitive Logging: Simplify definition of source and improve QLDoc

csharp/extractor/Semmle.Extraction.CSharp/Entities/Constructor.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Method.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Statements/SyntheticEmptyBlock.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/Type.cs, csharp/ql/lib/semmle/code/csharp/Callable.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/constructors/PrintAst.expected, csharp/ql/test/library-tests/csharp9/PrintAst.expected, csharp/ql/test/library-tests/dataflow/constructors/ConstructorFlow.expected, csharp/ql/test/library-tests/dataflow/constructors/Constructors.cs, csharp/ql/test/library-tests/dataflow/tuples/DataFlowStep.expected, csharp/ql/test/library-tests/dataflow/tuples/PrintAst.expected, csharp/ql/test/library-tests/expressions/ConstructorInitializers.expected, csharp/ql/test/library-tests/expressions/PrintAst.expected, csharp/ql/test/library-tests/expressions/expressions.cs
It turns out that the extraction of primary constructors didn't extract initialisers correctly. This is fixed in this PR.
That is, for
```csharp
public class C1(object o1) { }
public class C2(object o2) : C1(o2) { }
```
We need to extract
- The *implicit* inititaliser (calling the `object` constructor) for the primary constructor on `C1`.
- The *explicit* initialiser (calling the `C1` constructor) for the primary constructor on `C2`.
This is needed for
- Getting data-flow to work properly for *simple* classes with primary constructors (otherwise we won't get a control flow node corresponding to the basic block containing the class declaration). Adding the implicit initialiser means that we at least have a first statement, which is calling the `object` constructor.
- First step for getting …
=> C# 12: Primary constructor inititalizers.

python/ql/lib/semmle/python/Module.qll, python/ql/lib/semmle/python/Scope.qll
This is used by `Scope::isPublic` which in turn is called by the framework model for `setuptools`.
On my current quesry, this had a dramatic effect on the most expensive predicates:
Before
```
Most expensive predicates for completed query FindUses.ql:
time  | evals |   max @ iter | predicate
------|-------|--------------|----------
1m9s |  2933 | 123ms @ 422  | PointsTo::Expressions::equalityEvaluatesTo/4#ebe72212@cab7d3xr
43.1s |       |              | FlowSummaryImpl::Private::Steps::summaryLocalStep/3#900fb25e#ffb@8aa78a38
41.3s |  2936 |  2.1s @ 409  | PointsTo::InterProceduralPointsTo::scope_entry_value_transfer_from_earlier/4#acb2199d@cab7ddxr
30.2s |  2946 |  67ms @ 847  | PointsTo::PointsToInternal::multi_assignment_points_to/4#28782e93@cab7d0yr
29.7s |  2930 |  1.9s @ 30   | …
```
=> python: remove a use of points-to

csharp/ql/lib/change-notes/2024-02-21-getonly-properties.md, csharp/ql/lib/semmle/code/csharp/Property.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/constructors/ConstructorFlow.expected, csharp/ql/test/library-tests/dataflow/constructors/Constructors.cs
Dataflow for "readonly" properties (properties with only a "getter") didn't work.
That is, `Obj = o` wasn't detected as a store step into the property `Obj`. This is fixed in this PR.
```csharp
public class C
{
public object Obj { get; }
public C(object o)
{
Obj = o;
}
}
```
=> C#: Read-only property flow.

java/ql/lib/semmle/code/java/security/StaticInitializationVectorQuery.qll, shared/typetracking/codeql/typetracking/internal/TypeTrackingImpl.qll
Using a full global data flow instance is overkill and prone to performance issues: In my fieldFlowBranchLimit experiments I noticed this particular configuration suddenly taking an additional 3.6 hours to compute in the dca run.
I expect that the SimpleGlobal flow will be mostly comparable for the level of precision needed here, so I don't expect much in the way of alert changes, but let's see if dca finds something.
=> Java: Switch helper flow from Global to SimpleGlobal in StaticInitializationVectorQuery.

java/ql/test-kotlin2/library-tests/interface-delegate/test.expected
We lose a location here, but this makes the Kotlin 2 results more similar to the Kotlin 1 results.
=> Kotlin 2: Accept location changes in library-tests/interface-delegate

java/ql/test-kotlin2/library-tests/operator-overloads/PrintAst.expected
This also brings the Kotlin 2 output back in line with the Kotlin 1 output.
=> Kotlin 2: Accept changes in library-tests/operator-overloads

javascript/ql/lib/semmle/javascript/endpoints/EndpointNaming.qll, javascript/ql/test/library-tests/EndpointNaming/EndpointNaming.expected, javascript/ql/test/library-tests/EndpointNaming/EndpointNaming.ql, javascript/ql/test/library-tests/EndpointNaming/pack1/main.js, javascript/ql/test/library-tests/EndpointNaming/pack10/foo.js, javascript/ql/test/library-tests/EndpointNaming/pack11/index.ts, javascript/ql/test/library-tests/EndpointNaming/pack11/package.json, javascript/ql/test/library-tests/EndpointNaming/pack12/index.js, javascript/ql/test/library-tests/EndpointNaming/pack12/package.json, javascript/ql/test/library-tests/EndpointNaming/pack2/lib.js, javascript/ql/test/library-tests/EndpointNaming/pack2/main.js, javascript/ql/test/library-tests/EndpointNaming/pack3/lib.js, javascript/ql/test/library-tests/EndpointNaming/pack3/main.js, javascript/ql/test/library-tests/EndpointNaming/pack4/index.js, javascript/ql/test/library-tests/EndpointNaming/pack5/src/index.js, javascript/ql/test/library-tests/EndpointNaming/pack6/index.js, javascript/ql/test/library-tests/EndpointNaming/pack7/index.js, javascript/ql/test/library-tests/EndpointNaming/pack8/foo.js, javascript/ql/test/library-tests/EndpointNaming/pack8/index.js, javascript/ql/test/library-tests/EndpointNaming/pack9/foo.js, javascript/ql/test/library-tests/EndpointNaming/pack9/index.ts
This fixes some bugs in endpoint naming and makes it more robust at handling higher-order functions.
Previously it was a two-phase naming process: first we named every API node sink, and then named functions/classes that flow to those sinks. However, this made it difficult to work with functions generated by a higher-order function call, e.g. `exports.foo = makeFoo(baseFoo)` or functions generated by `new Function()`. Instead, the logic for naming functions/classes is now weaved into the first phase, mainly via the inclusion of instance edges.
Aliasing logic is now based on finding `SourceNodes` that flow to a multiple sinks, and has been separated from name generation. The old aliasing rule was basically "any candidate name that didn't get picked is an alias" but this was not sound; it …
=> JS: Improvements to endpoint naming

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FileContent.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FrameworkPackageNames.cs, csharp/extractor/Semmle.Extraction.Tests/FileContent.cs
Fallback cases coming from `<PackageReference />` and `packages.config` are now differentiated. In the latter case we're restoring the package through projects that target `net481`.
This change helps with restoring `EntityFramework` references. EF has different dependencies based on the target framework. If we're referencing `net481` reference assemblies and the .net core variant of EF, then duplicate type declarations are found due to the `System.Configuration.ConfigurationManager` and `System.Data.SqlClient` transitive dependencies.
=> C#: Improve fallback nuget package restore in buildless

java/ql/src/Security/CWE/CWE-200/AndroidSensitiveTextField.ql
This is an error for the Docs content linter and does not match the [style guide for metadata](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md#query-name-name).
=> Remove period from 'name' for Java query

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/test/library-tests/dataflow/constructors/ConstructorFlow.expected, csharp/ql/test/library-tests/dataflow/constructors/Constructors.cs, csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected, csharp/ql/test/library-tests/dataflow/tuples/Tuples.expected
In this PR we re-factor the logic for data flow for record types from their (primary) constructor into the auto generated property.
=> C#: Use primary constructors for record types for dataflow.

ruby/ql/lib/change-notes/2024-02-20-activerecord-sql-sink-arguments.md, ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/test/query-tests/security/cwe-089/ActiveRecordInjection.rb, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected
Part of https://github.com/github/codeql-team/issues/2616 and https://github.com/github/codeql-team/issues/2559.
This PR considers additional arguments to the methods `group`, `joins`, `pluck`, `order`, `reorder`, `select`, and `reselect` as sql sinks.
=> Ruby: Consider additional arguments to certain `ActiveRecord` methods as sql injection sinks.

ruby/ql/lib/change-notes/2024-02-15-activerecord_connection_sql_sinks.md, ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/test/library-tests/frameworks/active_record/ActiveRecord.expected, ruby/ql/test/library-tests/frameworks/active_record/ActiveRecord.rb
Part of https://github.com/github/codeql-team/issues/2616 and https://github.com/github/codeql-team/issues/2559
=> Ruby: Add additional sql sinks for ActiveRecord connection methods

ruby/ql/lib/codeql/ruby/frameworks/actiondispatch/internal/Request.qll, ruby/ql/src/change-notes/2024-02-13-rails-more-request-sources.md, ruby/ql/test/library-tests/frameworks/action_controller/ActionController.expected, ruby/ql/test/library-tests/frameworks/action_controller/input_access.rb
This PR adds some missing sources on the `request` object of Ruby on Rails (e.g. when used in an `ActionController`). E.g. the possibility of accessing a parameter directly via the request object `request["parameter_name"]` or accessing a header via `request.headers['Accept']`.
There is some overlap with the [request properties](https://github.com/github/codeql/blob/main/ruby/ql/lib/codeql/ruby/frameworks/rack/internal/Request.qll) as modelled for Rack and I am not sure if the original intent was that these sources should be provided by the Rack additions. (Currently they are not however.)
Additionally, I removed the three host related properties `"host_authority", "host", "hostname"` inside of `HeadersCall` as they were listed twice. (once in `HeadersCall` and once in `HostCall`). Maybe …
=> Ruby: add additional sources on the request object of Rails

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplSpecific.qll, shared/dataflow/codeql/dataflow/DataFlow.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
This PR adds a hook to the data flow library to allow for certain callables to excluded from the field-flow-branch-limit restriction.
For Ruby, we want to always include flow into/out of summarized callables, as these are expected to have high precision, which will ultimately reduce false negatives.
=> Ruby: No `fieldFlowBranchLimit` for `SummarizedCallable`s

csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/CSharpAutobuilder.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/Constants.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/DotNetRule.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/StandaloneBuildRule.cs
This PR extends the dotnet SDK downloading in buildless mode. If there's no `dotnet` CLI on the machine, it downloads the latest one as if that version was specified in the `global.json`. This way buildless extraction doesn't depend on `dotnet` being installed beforehand onto the machine.
=> C#: Download latest dotnet SDK when missing

config/identical-files.json, cpp/ql/lib/IDEContextual.qll, csharp/ql/lib/IDEContextual.qll, go/ql/lib/ideContextual.qll, java/ql/lib/IDEContextual.qll, javascript/ql/lib/IDEContextual.qll, python/ql/lib/analysis/IDEContextual.qll, ql/ql/src/codeql/IDEContextual.qll, ruby/ql/lib/codeql/IDEContextual.qll, shared/util/codeql/util/FileSystem.qll
Swift is still on its own implementation, since their `File` class does not implement the newly introduced `FileSig` signature (the predicates `getStem` and `getExtension` are missing).
=> Share `getFileBySourceArchiveName` implementation

ruby/ql/lib/change-notes/2024-02-20-activerecord-sql-sink-arguments.md
Removes an erroneous blank line.
=> Ruby: Fix change note formatting

.github/workflows/compile-queries.yml
The shared qlpacks didn't match the `*/ql` pattern, so add that path explicitly.
=> Workflows: Run format check on shared.

javascript/extractor/BUILD.bazel
The `resources` folder never existed, this was probably introduced as a copy-paste mistake. Remove the rule.
=> JS: Remove empty build target.

.gitattributes, .github/workflows/ruby-build.yml, ruby/BUILD.bazel, ruby/downgrades/BUILD.bazel, ruby/extractor/BUILD.bazel, ruby/extractor/Cargo.Bazel.lock, ruby/extractor/Cargo.lock, ruby/extractor/Cargo.toml, ruby/extractor/Cross.toml, ruby/extractor/cargo-bazel-lock.json, ruby/ql/lib/BUILD.bazel, ruby/tools/BUILD.bazel
This PR introduces a bazel and `rules_rust`-based build system for the ruby extractor and language pack.
This replaces the existing, `cargo` and `cross`-based build system.
For local development, nothing changes, and the existing `cargo`-based build still keeps working as-is.
We no longer need to use `cross` to compile our Linux binaries, as we now can link against our hermetic C++ toolchain, which ships with an old enough glibc, so that we don't run into symbol version issues when deploying the binaries to older systems. However, this means that we no longer can run the centos-test with the `github/codeql`/`cargo`-based buildsystem, as the correct binaries will only be produced by the internal bazel setup.
Besides the one change in dependency (explained in detail in `Cargo.toml` and in …
=> Ruby: Start building the language pack using bazel.

cpp/ql/lib/semmle/code/cpp/controlflow/SubBasicBlocks.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/AddressFlow.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowDispatch.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplConsistency.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplSpecific.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/FlowVar.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/SubBasicBlocks.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/TaintTrackingImplSpecific.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/TaintTrackingUtil.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking1/TaintTrackingParameter.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking2/TaintTrackingParameter.qll
Mark internal files in the old dataflow library as deprecated (the public imports already are).
=> C++: Mark internal files in the old dataflow library as deprecated

csharp/ql/lib/printCfg.ql, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.ql, ruby/ql/lib/ide-contextual-queries/printCfg.ql, ruby/ql/test/library-tests/controlflow/graph/Cfg.ql, shared/controlflow/codeql/controlflow/Cfg.qll, swift/ql/lib/codeql/swift/controlflow/internal/PrintCFG.ql, swift/ql/lib/codeql/swift/elements/File.qll, swift/ql/test/library-tests/controlflow/graph/Cfg.ql
This PR moves the existing `View CFG` implementations for Ruby and Swift into the shared CFG library, and subsequently instantiates the shared implementation in C#.
=> Shared `View CFG` implementation

shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
Identified by the join-order metric. It mostly isn't too bad but @yoff had a case where it exploded:
```
129348098   ~5%    {5} r5 = JOIN `FlowSummaryImpl::Private::summaryNodeInputState/2#f551a1f5` WITH `FlowSummaryImpl::Private::summaryNodeOutputState/2#34a54271` ON FIRST 1 OUTPUT Lhs.0, Lhs.1, Rhs.1, Lhs.2, Rhs.2
72581   ~2%    {6}    | JOIN WITH `FlowSummaryImpl::Private::summary/4#0b3df9ce#reorder_1_3_0_2_2031#join_rhs` ON FIRST 3 OUTPUT Lhs.0, Lhs.1, Lhs.3, Lhs.2, Lhs.4, Rhs.3
```
This change forces `summary` to be part of the first join.
=> Dataflow: Prevent bad join in FlowSummaryImpl::Private::Steps::summaryLocalStep.

swift/ql/lib/change-notes/2024-02-22-extension-patch.md, swift/ql/lib/codeql/swift/elements/decl/ExtensionDecl.qll, swift/ql/lib/codeql/swift/elements/decl/TypeDecl.qll
Workaround for an issue where databases can contain `ExtensionDecl`s that extend multiple `TypeDecl`s (i.e. a database inconsistency), ultimately sometimes forming an infinite loop in `TypeDecl.getFullName`.  This fix makes the QL more robust, allowing evaluation to complete, though the database inconsistencies are still present.
=> Swift: Workaround for TypeDecl.getFullName issue.

java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll
Henning noticed a lot of fastTC duplication (29x at the DIL level across a query suite). Cachaca has been saving us somewhat, but not completely, so this PR should eliminate the duplication.
=> Java: Cache interpretElement.

ruby/ql/lib/change-notes/2024-02-26-arel-sqlliteral.md, ruby/ql/lib/codeql/ruby/frameworks/Arel.qll, ruby/ql/test/library-tests/dataflow/local/TaintStep.expected, ruby/ql/test/query-tests/security/cwe-089/ArelInjection.rb, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected
Part of https://github.com/github/codeql-team/issues/2559 and https://github.com/github/codeql-team/issues/2616
This PR adds modelling for `Arel::Nodes::SqlLiteral.new` as a flow step and as an instance of `SqlConstruction` (and thus a sink for the sql injection query).
This finds 8 additional TP results in the test application for https://github.com/github/codeql-team/issues/2559
=> Ruby: Model Arel::Nodes::SqlLiteral.new

go/ql/lib/change-notes/2024-02-14-range-map-read.md, go/ql/lib/semmle/go/dataflow/internal/ContainerFlow.qll, go/ql/test/library-tests/semmle/go/dataflow/MapReadsAndStores/Flows.ql, go/ql/test/library-tests/semmle/go/dataflow/MapReadsAndStores/test.go
Flow such as the following was broken:
```
var someMap map[string]string
someMap["someKey"] = source()
for _, val := range someMap {
sink(val)
}
```
This is because the store-step relating to the map store used content-kind "map.value", while the read via the range statement used content-kind "array".
Note the case for reading array content now always constrains the read node to have array or slice type, as array content was previously being read from the base over a range statement iterating over a map.
=> Golang: fix flow from a map value via a range statement

cpp/ql/test/library-tests/special_members/generated_copy/functions.expected, cpp/ql/test/library-tests/specifiers2/specifiers2.expected
* The `specifiers2` tests have a different result now due to the implementation of CWG 2387.
* The `special_members/generated_copy` has improved results as the frontend has improved support for deleted copy constructors.
=> C++: Accept test changes after frontend upgrade

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected, ruby/ql/test/library-tests/dataflow/array-flow/array_flow.rb, ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.expected, ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected, ruby/ql/test/library-tests/dataflow/params/params-flow.expected, ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected, ruby/ql/test/library-tests/frameworks/active_support/ActiveSupportDataFlow.expected, ruby/ql/test/library-tests/frameworks/sinatra/Flow.expected, ruby/ql/test/query-tests/experimental/LdapInjection/Ldapinjection.expected, ruby/ql/test/query-tests/security/cwe-079/ReflectedXSS.expected, ruby/ql/test/query-tests/security/cwe-079/StoredXSS.expected, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected, ruby/ql/test/query-tests/security/cwe-094/UnsafeCodeConstruction/UnsafeCodeConstruction.expected, ruby/ql/test/query-tests/security/cwe-312/CleartextLogging.expected, ruby/ql/test/query-tests/security/cwe-506/HardcodedDataInterpretedAsCode.expected
Hides more synthetic nodes (such as synthetic block parameters), unhides all array/hash literal creations.
=> Ruby: Rework hidden synthetic data-flow nodes

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This is the only thing we ever use them for so there's no need to allocate a `VariableNode` for _every_ variable in the database.
DCA shows a nice reduction of the tuple pool size 🎉
=> C++: Restrict `VariableNode`s to only be global-like variables

java/ql/lib/change-notes/2024-02-23-widget-flowsteps.md, java/ql/lib/semmle/code/java/dataflow/FlowSteps.qll, java/ql/test/query-tests/security/CWE-312/android/CleartextStorage/CleartextStorageSharedPrefsTest.java
The library Widget.qll was accidentally removed from the global context when its sources were migrated to models-as-data in #13136. This re-adds it so that its flow steps are enabled again.
=> Java: Re-enable Widget.qll flow steps

ruby/ql/lib/change-notes/2024-02-29-i18n-translate.md, ruby/ql/lib/codeql/ruby/Frameworks.qll, ruby/ql/lib/codeql/ruby/frameworks/Translation.qll, ruby/ql/test/library-tests/dataflow/local/TaintStep.expected, ruby/ql/test/query-tests/security/cwe-079/ReflectedXSS.expected, ruby/ql/test/query-tests/security/cwe-079/app/controllers/foo/bars_controller.rb, ruby/ql/test/query-tests/security/cwe-079/app/views/foo/bars/show.html.erb
Closes https://github.com/github/codeql-team/issues/1964
Part of https://github.com/github/codeql-team/issues/2616
This PR models flow steps for [`I18n.translate`](https://guides.rubyonrails.org/i18n.html), the [view helper `translate`](https://api.rubyonrails.org/classes/ActionView/Helpers/TranslationHelper.html#method-i-translate), and the [controller helper `translate`](https://api.rubyonrails.org/classes/AbstractController/Translation.html#method-i-translate) (as well as each of their aliases as `t`); the latter two of which may also escape html depending on the key used.
=> Ruby: Model Rails translation methods

csharp/codeql-extractor.yml, csharp/ql/integration-tests/all-platforms/cshtml_standalone/test.py, csharp/ql/integration-tests/all-platforms/cshtml_standalone_disabled/test.py, csharp/ql/integration-tests/all-platforms/cshtml_standalone_flowsteps/test.py, csharp/ql/integration-tests/all-platforms/cshtml_standalone_net6/test.py, csharp/ql/integration-tests/all-platforms/standalone/test.py, csharp/ql/integration-tests/all-platforms/standalone_dependencies_net48/test.py, csharp/ql/integration-tests/linux-only/standalone_dependencies_non_utf8_filename/test.py, csharp/ql/integration-tests/posix-only/standalone_dependencies/test.py, csharp/ql/integration-tests/posix-only/standalone_dependencies_multi_target/test.py, csharp/ql/integration-tests/posix-only/standalone_dependencies_no_framework/test.py, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget/test.py, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_error/test.py, csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_no_sources/test.py, csharp/ql/integration-tests/windows-only/standalone_dependencies/test.py
`--build-mode none` replaces the existing `-Obuildless=true`.
=> C#: Add `build_modes: none` to `codeql-extractor.yml`

csharp/ql/integration-tests/all-platforms/dotnet_build/Program.cs, csharp/ql/integration-tests/all-platforms/dotnet_build/test.py, csharp/ql/integration-tests/all-platforms/dotnet_run/test.py, csharp/tools/tracing-config.lua
In this PR we improve the C# tracer such that eg. `run` is not recognised as a dotnet SDK sub-command but rather an argument to the program being executed (if `dotnet` is used to invoke an application).
```bash
dotnet <path-to-application> run my other arguments
```
Before this change, this worked by accident if the path to the application wasn't absolute (starting with `/`).
=> C#: Don't inject compiler flags when dotnet is used to execute an application.

ruby/ql/lib/codeql/ruby/frameworks/core/Kernel.qll, ruby/ql/src/change-notes/2024-03-01-method-code-injection-sinks.md, ruby/ql/test/library-tests/frameworks/core/Kernel.expected, ruby/ql/test/library-tests/frameworks/core/Kernel.ql, ruby/ql/test/library-tests/frameworks/core/Kernel.rb
Adds code injection sinks for calls to [`method`](https://ruby-doc.org/core-3.0.0/Method.html) with untrusted data.
E.g.
```ruby
m = method("exit")
m.call
```
(Note: the `public_method` and `singleton_method` are added for completeness, their usage in real-world projects is likely quite rare)
=> Ruby: sinks for code injection via calls to `method`

go/extractor/autobuilder/build-environment.go
This PR updates the `maxGoVersion` constant to `1.22` so that we allow this as a version to be recommended by resolve build environment functionality in e.g. default setup workflows. 
Enabled by having merged #15361.
=> Go: Allow 1.22 as a supported version

go/extractor/go.mod, go/extractor/go.work.sum
Bumps the Go version in our `go.mod` file (and also updates the `go.work.sum` file which apparently missing some entries when we merged it in https://github.com/github/codeql/pull/15362).
=> Go: Use Go 1.22 for the extractor

java/ql/lib/semmle/code/java/security/SensitiveLoggingQuery.qll, java/ql/src/change-notes/2024-03-04-sensitive-log-remove-null-from-sources.md, java/ql/test/query-tests/security/CWE-532/Test.java
I noticed some FPs in `apache/geode` where the source was a variable called `NULLTOKEN`. It is an easy fix to exclude variable names that match "null" (case-insensitively) from the sources.
=> Java: sensitive logging query exclude null in variable name

python/ql/consistency-queries/PhaseDependentFlowConsistency.ql
This would have found the problem fixed in
https://github.com/github/codeql/pull/15755.
As highlighted in the comment in the code, it's not a perfect solution
since we don't have an automatic way to ensure we don't introduce a new
PhaseDependentFlow use with a new step relation and forget to add it to
this consistency check... but I think this consistency check still adds
value!
=> Python: Add consistency check for `PhaseDependentFlow`

ruby/ql/lib/change-notes/2024-02-26-arel-sqlliteral.md, ruby/ql/lib/change-notes/2024-02-29-i18n-translate.md
Fixed the Markdown formatting for two changenotes so that the pack changelogs will render appropriately!
=> Fix Markdown formatting on Ruby changenotes

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/global/Capture.cs, csharp/ql/test/library-tests/dataflow/global/DataFlow.expected, csharp/ql/test/library-tests/dataflow/global/DataFlowPath.expected, csharp/ql/test/library-tests/dataflow/global/TaintTracking.expected, csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.expected
https://github.com/github/codeql/pull/15665 follow-up.
=> C#: Variable capture follow-up

go/ql/lib/semmle/go/security/SensitiveActions.qll
This avoids high memory usage on projects with lots of very long strings.
=> Go: Only check strings of length <= 100 for dummy password with <= 2 unique characters

go/extractor/cli/go-autobuilder/go-autobuilder.go, go/extractor/project/project.go, go/extractor/project/project_test.go, go/extractor/toolchain/toolchain.go, go/extractor/util/util.go, go/extractor/util/util_test.go, go/ql/integration-tests/all-platforms/go/mixed-layout/diagnostics.expected, go/ql/integration-tests/all-platforms/go/mixed-layout/force_sequential_test_execution, go/ql/integration-tests/all-platforms/go/mixed-layout/src/module/go.mod, go/ql/integration-tests/all-platforms/go/mixed-layout/src/module/go.sum, go/ql/integration-tests/all-platforms/go/mixed-layout/src/module/test.go, go/ql/integration-tests/all-platforms/go/mixed-layout/src/stray-files/test.go, go/ql/integration-tests/all-platforms/go/mixed-layout/src/workspace/go.work, go/ql/integration-tests/all-platforms/go/mixed-layout/src/workspace/subdir/go.mod, go/ql/integration-tests/all-platforms/go/mixed-layout/src/workspace/subdir/go.sum, go/ql/integration-tests/all-platforms/go/mixed-layout/src/workspace/subdir/test.go, go/ql/integration-tests/all-platforms/go/mixed-layout/test.expected, go/ql/integration-tests/all-platforms/go/mixed-layout/test.py, go/ql/integration-tests/all-platforms/go/mixed-layout/test.ql, go/ql/integration-tests/all-platforms/go/single-go-mod-and-go-files-not-under-it/test.expected
This PR improves the automatic `go.mod` initialisation logic in the Go autobuilder in two ways:
1. Go modules are now named after the correct import path, if possible. E.g. instead of `codeql/auto-project`, we may now use `github.com/user/repo`.
2. A bug which could cause `go.mod` files to be initialised in parent directories of existing `go.mod` files has been fixed.
=> Go: Improve names of auto-generated Go modules

ruby/ql/lib/change-notes/2024-03-01-typhoeus-request.md, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Typhoeus.qll, ruby/ql/test/library-tests/frameworks/http_clients/HttpClients.expected, ruby/ql/test/library-tests/frameworks/http_clients/Typhoeus.rb
Closes https://github.com/github/codeql-team/issues/618
Part of https://github.com/github/codeql-team/issues/2616
This PR adds modelling for `Typhoeus::Request.new` as an http client request, and tracks flow to the response body either directly (`req.run.body`) or through callbacks (`req.on_complete do |resp| { ... resp.body ...}`).
=> Ruby: Model `Typhoeus::Request.new`

ruby/ql/lib/codeql/ruby/security/ServerSideRequestForgeryCustomizations.qll
MaD sinks marked as `request-forgery` will now be considered in `rb/request-forgery`.
=> Ruby: Include request forgery sinks from MaD

csharp/ql/test/library-tests/dataflow/collections/CollectionFlow.expected, ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected, ruby/ql/test/library-tests/dataflow/global/Flow.expected, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll, swift/ql/test/query-tests/Security/CWE-311/CleartextStorageDatabase.expected
This PR parameterizes predicates related to context-sensitivity by the relevant call edges, in a new `CallContextSensitivity<CallContextSensitivityInputSig Input>` module. This enables us to compute those predicates based on the relevant call edges from the previous pruning stage, in turn allowing for potentially smaller tuple counts:
<details><summary>Example tuple counts before</summary>
\# | n | stage | nodes | fields | conscand | states | tuples | calledges | tfnodes | tftuples
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 30 | 3 Fwd | 41,891 | 1,202 | 64,539 | 1 | 9,164,518 | 13,020 | 0 | 0
2 | 50 | 5 Fwd | 17,482 | 488 | 2,952 | 1 | 128,109 | 7,004 | 0 | 0
3 | 60 | 6 Fwd | 13,739 | 385 | 1,396 | 1 | 61,374 | -1 | -1 | -1
4 | 65 | 6 Rev | 860 | 35 | 43 | 1 | 1,108 | -1 | …
=> Data flow: prune context-sensitivity relations

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
Two commits fixing two separate problems.
The first commit improves the join of `returnFlowsThrough`, `flowIntoCallApaTaken`, and `fwdFlow`. The join must happen in that order (digging into the git history shows prior join-order tweaks in this predicate documenting this), but it still has an unfortunate blow-up, which we can fortunately cut substantially down by including the `argApa` column in the first join.
Improves from
```
2024-03-04 13:29:20] Evaluated non-recursive predicate DataFlowImpl::Impl<TaintedPath::TaintedPath::C>::Stage5::flowThroughIntoCall/6#b44155c7@6dd478n9 in 126ms (size: 398332).
Evaluated relational algebra for predicate DataFlowImpl::Impl<TaintedPath::TaintedPath::C>::Stage5::flowThroughIntoCall/6#b44155c7@6dd478n9 with tuple counts:
1  ~0%    {2} r1 = SCAN …
```
=> Dataflow: Misc performance fixes

docs/codeql/reusables/supported-versions-compilers.rst
I think that this will be clearer.
This turns into `<td>Kotlin 1.5.0 to 1.9.2<em>x</em></td>`.
=> Kotlin: Docs: Give upper bound as 1.9.2x rather than 1.9.20

shared/dataflow/codeql/dataflow/DataFlow.qll, shared/rangeanalysis/codeql/rangeanalysis/RangeAnalysis.qll
Similar to https://github.com/github/codeql/pull/15684 , I'm experimenting with using Copilot ("GitHub Copilot: Generate Docs" command) to help fill holes in our QLDoc comments.  To be honest I think the output is not quite good enough, even after a bit of manual cleanup - it tends to explain code in detail without ever stating what the purpose of the class / predicate is, and the latter is probably what the reader is after.  Hopefully though, this will be a good starting point for discussion...
=> Shared: Fill some QLDoc holes

java/ql/test/ext/TopJdkApis/TopJdkApisTest.java
As of the JDK22 extractor update, this will no longer be implicitly imported by other classes referenced in this file.
=> Java: Explicitly import Lock class

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs
`dotnet/runtime` contains "empty" global.json files, which resulted in `null` SDK versions, that we tried to download and install.
=> C#: Improve `global.json` file parsing

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
Before this PR, store steps where the target node would clear the stored content via `clearsContent` would get filtered away. However, it is convenient to be able to only filter away _earlier_ store steps, which is what this PR changes. The old semantics can be still be maintained on a per-language basis, as it is simply a matter of removing such store steps up front.
Needed in preparation for https://github.com/github/codeql/pull/15802.
=> Data flow: Allow for direct stores into nodes with `clearsContent`

javascript/ql/lib/semmle/javascript/endpoints/EndpointNaming.qll, javascript/ql/test/library-tests/EndpointNaming/EndpointNaming.expected, javascript/ql/test/library-tests/EndpointNaming/pack1/main.js
A class was erroneously considered to escape into client code if it escaping into a upstream library:
```js
class A {}
module.exports = new A(); // Correct: escapes downstream
class B {}
require('foo')(new B()); // Wrong: escapes upstream, does not need a synthetic name
```
=> JS: Improve detection of classes with escaping instances

csharp/ql/lib/change-notes/2024-03-07-update-system.net.http.httprequestmessage-models.md, csharp/ql/lib/ext/System.Net.Http.model.yml, csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected
There is an autogenerated MaD for System.Net.Http.HttpRequestMessage constructor where `Uri` class is one of the parameters. However, it's missing the overloaded constructor where the parameter is a string URL.
- https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.-ctor?view=net-8.0
Both versions of the constructor can have taint flow, such as for SSRF. This PR adds the missing MaD for the overloaded constructor.
=> csharp update MaD for HttpRequestMessage

javascript/ql/lib/semmle/javascript/dataflow/internal/StepSummary.qll, javascript/ql/test/library-tests/TypeTracking/TypeTracking.expected, javascript/ql/test/library-tests/TypeTracking/summarize.js
For type-tracking, we currently have a simple summarization of functions in two cases:
- Induce a local step when a parameter is returned, and
- Induce a load step when a property of a parameter is returned.
This PR adds two more summaries:
- Induce a store step when a parameter is stored on the returned object.
- Induce a load-store step when a property of a parameter is stored on the returned object.
I ran two evaluations, both of which are fairly quiet. The new call edges seem valid.
- [With store steps only](https://github.com/github/codeql-dca-main/tree/data/asgerf/summarised-tt-s__default__code-scanning/reports)
- [With both steps](https://github.com/github/codeql-dca-main/issues/19500)
=> JS: Summarise store steps for type tracking

javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/CallGraphs.qll, javascript/ql/src/change-notes/2024-03-07-lift-cg-restriction.md, javascript/ql/test/library-tests/CallGraphs/FullTest/tests.expected
Does two things:
- Loosens the restriction for when to track objects with methods. Previously the object had to be an allocation site, now it can be any `SourceNode` other than `this` inside a constructor (functions stored on that are instead seen as instance methods).
- Improves detection of function-style classes, by looking for functions that are invoked with `new`.
The tracking of objects affects the call graph directly, and also contributes to the `impliedReceiverStep`, which causes the host object to flow into `this` in the body of method:
```js
bar().foo = function() { 
this; // <- value of bar() now flows here
}
```
[Evaluation](https://github.com/github/codeql-dca-main/issues/19658) shows neutral performance and about 24k new call edges and a few new alerts. The alerts I've …
=> JS: Call graph improvements

docs/codeql/codeql-language-guides/customizing-library-models-for-csharp.rst, docs/codeql/codeql-language-guides/customizing-library-models-for-java-and-kotlin.rst, docs/codeql/reusables/beta-note-threat-models-java.rst, docs/codeql/reusables/beta-note-threat-models.rst
Adds information about threat modeling to the C# MaD docs.
=> C#: Add references to threat modeling to C# Models-as-Data documentation

csharp/ql/lib/semmle/code/csharp/security/dataflow/CodeInjectionQuery.qll, csharp/ql/lib/semmle/code/csharp/security/dataflow/ResourceInjectionQuery.qll, csharp/ql/lib/semmle/code/csharp/security/dataflow/SqlInjectionQuery.qll, csharp/ql/src/change-notes/2024-03-06-remove-default-local-sources.md, csharp/ql/test/query-tests/Security Features/CWE-094/CodeInjection.ext.yml
The `AddLocalSource` classes were added in https://github.com/github/codeql/pull/15419 to make deprecating `LocalSource` classes easier.
This removes them so that queries rely on `ThreatModelFlowSource`.
=> C#: Remove `AddLocalSource` classes from queries

python/ql/lib/semmle/python/dataflow/new/internal/TaintTrackingPrivate.qll, python/ql/test/query-tests/Functions/ModificationOfParameterWithDefault/ModificationOfParameterWithDefault.expected, python/ql/test/query-tests/Functions/ModificationOfParameterWithDefault/test.py
This should fix the issue reported by @alex-slynko.
I think it's reasonable to just add these calls as copy steps in general. 
---
Does this warrant a change note? I opted not to add one, but I'm happy to add one if needed.
=> Python: Add `.copy()` method call as copy step

csharp/extractor/Semmle.Extraction.CSharp/Entities/Assembly.cs
This PR changes the computed ID of the output assembly in buildless mode. The assembly ID typically looks like: `01szix0x.nzd.dll, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`, but to compute this, Roslyn needs to process assembly attributes, which might fail on a set of source files that were not meant to be compiled together.
=> C#: Change ID of buildless output assembly

python/ql/test/library-tests/essa/ssa-compute/test2.py
Here is an interesting example where we lose use-use flow. I could not minimize the example any further, that is: removing the try-finally blocks made things work again, and converting `while -> if` made things work as well.
```py
def func(x):
try:
with Thing as y:
y.foo(x, some_var.some_attr)
while not x.attribute: # <-- missing flow to x
y.bar() # <-- missing flow to y
print(x)
finally:
pass
```
I noticed that by change `some_var.some_attr` to `0` the problem would also go away, and by changing to `some_var` we would only have missing flow for `y` but have proper flow for `x`...
I did spend some time looking into a fix in the SsaCompute.qll file, but did not reach a conclusion. While it shares some aspects with https://github.com/github/codeql/pull/10970 and …
=> Python: Add example of missing use-use flow

ruby/ql/lib/change-notes/2024-03-08-activerecord-from.md, ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/test/query-tests/security/cwe-089/ActiveRecordInjection.rb, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected
This PR models the second argument, `subquery_name`, of the [`from`](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-from) method, as an sqli sink. 
Part of https://github.com/github/codeql-team/issues/2864
=> Ruby: Model second argument of `ActiveRecord` `from`

cpp/ql/src/Security/CWE/CWE-843/TypeConfusion.qhelp, cpp/ql/src/Security/CWE/CWE-843/TypeConfusion.ql, cpp/ql/src/Security/CWE/CWE-843/TypeConfusionBad.cpp, cpp/ql/src/Security/CWE/CWE-843/TypeConfusionCommon.cpp, cpp/ql/src/Security/CWE/CWE-843/TypeConfusionGood.cpp, cpp/ql/src/change-notes/2024-03-05-type-confusion-query.md, cpp/ql/test/query-tests/Security/CWE/CWE-843/TypeConfusion.expected, cpp/ql/test/query-tests/Security/CWE/CWE-843/TypeConfusion.qlref, cpp/ql/test/query-tests/Security/CWE/CWE-843/test.cpp
This PR adds a new medium precision query `cpp/type-confusion` to detect issues such as:
```cpp
struct Animal {
virtual ~Animal();
};
struct Cat : public Animal {
Cat();
~Cat();
};
struct Dog : public Animal {
Dog();
~Dog();
};
void test6() {
Animal* a = new Cat;
Dog* d = static_cast<Dog*>(a); // BAD
}
```
=> C++: Add a new query for detecting type confusion vulnerabilities

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
This PR makes sure that we deduplicate by name the package reference list, which might contain `("abc", csproj)` and `("abc", packagesconfig)`. We prefer the `csproj` variant.
I found this issue in `mono/mono` which occasionally failed with:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not find a part of the path '/home/runner/work/_temp/codeql_databases/csharp/working/1692ca4ce0441bb2/missingpackages_workingdir'.)
---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/runner/work/_temp/codeql_databases/csharp/working/1692ca4ce0441bb2/missingpackages_workingdir'.
at System.IO.FileSystem.RemoveEmptyDirectory(String fullPath, Boolean topLevel, Boolean throwWhenNotEmpty)
at Semmle.Util.TemporaryDirectory.Dispose() in …
```
=> C#: Deduplicate not yet restored package names

java/ql/lib/change-notes/2024-03-11-add-parcelfiledescriptor-open-model.md, java/ql/lib/ext/android.os.model.yml
Adds a `path-injection` sink to for the [`android.os.ParcelFileDescriptor::open`] methods.
This covers a regression in the `java/path-injection` query.
[`android.os.ParcelFileDescriptor::open`]: https://developer.android.com/reference/android/os/ParcelFileDescriptor#open(java.io.File,%20int)
=> Java: Add path-injection sink for `ParcelFileDescriptor::open`

csharp/ql/lib/change-notes/2024-03-11-registry-sources.md, csharp/ql/lib/ext/Microsoft.Win32.model.yml, csharp/ql/lib/semmle/code/csharp/security/dataflow/flowsources/Local.qll, csharp/ql/test/library-tests/dataflow/flowsources/local/registry/Registry.expected, csharp/ql/test/library-tests/dataflow/flowsources/local/registry/Registry.ext.yml, csharp/ql/test/library-tests/dataflow/flowsources/local/registry/Registry.ql, csharp/ql/test/library-tests/dataflow/flowsources/local/registry/UseRegistry.cs, csharp/ql/test/library-tests/dataflow/flowsources/local/registry/options, shared/mad/codeql/mad/ModelValidation.qll, shared/threat-models/ext/threat-model-grouping.model.yml
Adds the `windows-registry` threat model and source models for the methods in `Microsoft.Win32.Registry` and `RegistryKey` that get information from the registry.
=> C#: Add source models for values from the Windows registry

ruby/ql/lib/codeql/ruby/security/XSS.qll
The data flow loop used in `OrmTracking` is known to be quite slow/infeasible on some DBs, so this PR reduces the access path limit from 5 to 1. This is the same access path limit as used in type tracking, but flow precision is generally much better (call context sensitivity, full support for flow summaries, full support for captured variables, etc.).
=> Ruby: Lower access path limit to 1 for `OrmTracking`

javascript/ql/lib/semmle/javascript/AMD.qll, javascript/ql/test/library-tests/AMD/tests.expected
When an AMD `define()` call declares `exports`, `module`, or `require` as a dependency, it does not import a module with that name, but we accidentally treated them as imports.
Also removes a spurious recursion pattern in AMD.
[Evaluation](https://github.com/github/codeql-dca-main/issues/19501) looks very quiet. Two spurious import edges have been removed. I've seen some more cases in other codebases.
=> JS: Do not treat AMD pseudo-dependencies as imports

javascript/ql/lib/semmle/javascript/Arrays.qll, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.expected, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.js, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXssWithCustomSanitizer.expected
Fixes internal issue (see backref). 
Evaluations look good:  
[Nightly](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-15893-809dcd__nightly-old__code-scanning/reports): Meta queries show a few new tainted-nodes, which all look good. 
[Default](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-15893-129286__default__code-scanning/reports): Also a few new tainted-notes, which look good.
=> JS: allow more flow through .filter()

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This fixes the two surprising missing results from https://github.com/github/codeql/pull/15371 that @geoffw0 was seeing when he switched from interpreting `Argument[-1]` as `this` to `*this`.
I didn't bother adding a testcase since @geoffw0 PR will contain such tests anyway
=> C++: Fix dataflow node <> expression problem on prvalues

go/ql/lib/semmle/go/security/HardcodedCredentials.qll, go/ql/src/Security/CWE-798/HardcodedCredentials.ql, go/ql/src/change-notes/2024-03-14-hardcoded-credentials-more-sources.md, go/ql/test/query-tests/Security/CWE-798/HardcodedCredentials.expected
Using the heuristic for dummy passwords to discard sources in this query makes us miss sources like [this one](https://github.com/1Panel-dev/KubePi/blob/2fb4f6961217204561abb34952e9f05d9ca02476/internal/api/v1/session/session.go#L35), so I think it's a good idea to remove the limitation.
=> Go: Consider more strings as hardcoded credentials

csharp/ql/lib/semmle/code/csharp/security/dataflow/flowsources/Local.qll, csharp/ql/lib/semmle/code/csharp/security/dataflow/flowsources/Stored.qll
Queries such as `cs/sql-injection` cast their source to a `SourceNode` in order to describe them. For example:
```ql
import semmle.code.csharp.security.dataflow.flowsources.FlowSources
string getSourceType(DataFlow::Node source) {
result = source.(SourceNode).getSourceType()
}
```
Models as data source models are not included in `SourceNode` by default, they must be wrapped with a class extending `SourceNode`.
This adds such classes, which wrap the `sourceNode(DataFlow::Node,string)` predicate and assigns a `getSourceType`.
=> C#: Add classes extending `SourceNode` for local and stored source models

cpp/ql/lib/change-notes/2024-03-15-switches-in-guard-conditions.md, cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll, cpp/ql/test/library-tests/controlflow/guards/Guards.expected, cpp/ql/test/library-tests/controlflow/guards/GuardsControl.expected, cpp/ql/test/library-tests/controlflow/guards/GuardsControl.ql, cpp/ql/test/library-tests/controlflow/guards/test.cpp
This PR introduces the minimal changes necessary to support `switch` statements in the guards library. After this PR, it's now possible to ask if a block is controlled by a particular `case` in a switch statement.
It's still possible to do more in this area. For example, `GuardCondition.comparesEq` still doesn't reason about `switch` statements since the interface on that predicate can't really support it (its columns include `(Expr left, Expr right, int k)` which holds if `left == right + k`, but the `case` label in a switch isn't an expression). So such changes are probably best done in a follow-up PR.
DCA looks good. The removed results are clear FPs that now disappear. And the new results is because the medium precision query now shows these …
=> C++: Handle `switch` statements in the guards library

ruby/ql/lib/change-notes/2024-03-14-actiondispatch-uploadedfile.md, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/test/library-tests/dataflow/global/instance_variables.rb, ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected, ruby/ql/test/library-tests/dataflow/local/TaintStep.expected, ruby/ql/test/library-tests/frameworks/action_controller/ActionController.expected, ruby/ql/test/library-tests/frameworks/action_controller/params-flow.expected, ruby/ql/test/library-tests/frameworks/action_controller/params_flow.rb
This PR models attributes and methods from an `UploadedFile` that comes from a field of `params`. 
This allows an additional result for command injection in railsgoat to be found. 
Closes https://github.com/github/codeql-team/issues/2363.
=> Ruby: Model ActiveDispatch::Http::UploadedFile

csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.expected, csharp/ql/test/library-tests/dataflow/global/DataFlowPath.expected, csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.expected, python/ql/test/experimental/dataflow/summaries/summaries.expected, ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected, ruby/ql/test/library-tests/dataflow/global/Flow.expected, ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected, shared/dataflow/change-notes/2024-02-28-hidden-subpaths.md, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
Previously, we would not get `subpaths` computed for hidden wrappers, such as when flow passes through a callback passed into a library method with a flow summary:
```rb
a = [taint]
b = a.each do |x| # missing subpath: `a` (line 2) to `x` (line 2), `x` (line 2) to `x` (line 3), and `x` (line 3) to `b`
x
end
sink x
```
This PR changes that to allow for an arbitrary number of hidden intermediate wrappers, and also takes into account that argument/out/parameter nodes may be hidden (we previously only took into account that return nodes could be hidden).
=> Data flow: Account for hidden `subpath` wrappers

python/ql/src/Security/CWE-798/HardcodedCredentials.ql
- `ModuleValue.attr` and `ClassValue.lookup` are approximated by `Function.getName`
- `ClassValue.getName` is apprximated by `Class.getName`
- `Module::named` is approximated by `Module.getName`
- `Value::named` is approximated by `Builtins::likelyBuiltin`
- `FunctionValue.getNamedArgumentForCall` is approximated by `ArgumentNode.argumentOf`
=> python: Rewrite `HardcodedCredentials` away from `PointsTo`

config/identical-files.json, javascript/ql/lib/semmle/javascript/AST.qll, javascript/ql/lib/semmle/javascript/CFG.qll, javascript/ql/lib/semmle/javascript/Comments.qll, javascript/ql/lib/semmle/javascript/Errors.qll, javascript/ql/lib/semmle/javascript/Files.qll, javascript/ql/lib/semmle/javascript/HTML.qll, javascript/ql/lib/semmle/javascript/JSDoc.qll, javascript/ql/lib/semmle/javascript/JSON.qll, javascript/ql/lib/semmle/javascript/Lines.qll, javascript/ql/lib/semmle/javascript/Locations.qll, javascript/ql/lib/semmle/javascript/Regexp.qll, javascript/ql/lib/semmle/javascript/RestrictedLocations.qll, javascript/ql/lib/semmle/javascript/SSA.qll, javascript/ql/lib/semmle/javascript/Tokens.qll, javascript/ql/lib/semmle/javascript/Variables.qll, javascript/ql/lib/semmle/javascript/XML.qll, javascript/ql/lib/semmle/javascript/YAML.qll, javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll, javascript/ql/lib/semmle/javascript/frameworks/Templating.qll, javascript/ql/lib/semmle/javascript/internal/CachedStages.qll, javascript/ql/lib/semmle/javascript/internal/Locations.qll, javascript/ql/test/testUtilities/internal/InlineExpectationsTestImpl.qll
In preparation for https://github.com/github/codeql/pull/15853.
The increase in extraction errors reported by DCA is because some `@json_parse_error` entities apparently have locations in `hasLocation` and not `json_locations`.
=> JS: Add `DataFlow::Node.getLocation`

javascript/ql/test/ApiGraphs/classes/VerifyAssertions.expected, javascript/ql/test/ApiGraphs/classes/classes.js, javascript/ql/test/library-tests/TypeTracking/TypeTracking.expected, javascript/ql/test/library-tests/TypeTracking/implicit-receiver.js
This PR is a journey for me into better understanding the JS CodeQL analysis, by trying to write tests to show the effect of https://github.com/github/codeql/pull/15823. I've written some tests that initially fail on commit 245cd5c0b5965667858f903e9948ceb1f20ed63b (parent of PR merge commit), and then tested them again on 7c35309732dd2aa4dc0b4e2949922272ad448854 (PR merge commit)
I was able to highlight the effect of the [Detect more FunctionStyleClasses commit](https://github.com/github/codeql/pull/15823/commits/a54a73c9a2d473da215aaa94ad08cd14b816f190), see the change in `javascript/ql/test/ApiGraphs/classes/VerifyAssertions.expected`.
I had expected that the step defined here https://github.com/github/codeql/blob/13e3a5158eaa3f8c685ab342e2fba64cac10b296/javascript/ql/lib/semmle/javascri …
=> JS: show test changes after #15823

ruby/ql/lib/codeql/ruby/ast/internal/Constant.qll
This gives a nice little speedup with no apparent loss of results.
=> Ruby: remove isString from TSymbol

cpp/ql/lib/change-notes/2024-03-19-predicates-for-switches-as-guards.md, cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/EdgeKind.qll, cpp/ql/src/Critical/ScanfChecks.qll, cpp/ql/test/library-tests/controlflow/guards-ir/tests.expected, cpp/ql/test/library-tests/controlflow/guards-ir/tests.ql, cpp/ql/test/library-tests/controlflow/guards/GuardsCompare.expected, cpp/ql/test/library-tests/controlflow/guards/GuardsCompare.ql
This PR is the follow-up to https://github.com/github/codeql/pull/15941 that addresses this comment I made in that PR:
> It's still possible to do more in this area. For example, GuardCondition.comparesEq still doesn't reason about switch statements since the interface on that predicate can't really support it (its columns include `(Expr left, Expr right, int k)` which holds if `left == right + k`, but the case label in a switch isn't an expression). So such changes are probably best done in a follow-up PR.
This PR only does the required API additions to support `GuardCondition.comparesEq` for `switch` statements. We also have a predicate `GuardCondition.comparesLt` which needs a similar treatment. I'm delaying that until a future PR
=> C++: Implement guards logic for switch statements

ruby/ql/lib/change-notes/2024-03-19-activerecord-scopes.md, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll, ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll, ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected, ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.ql, ruby/ql/test/library-tests/dataflow/hash-flow/hash_flow.rb, ruby/ql/test/query-tests/security/cwe-089/ActiveRecordInjection.rb, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected
Track flow into ActiveRecord scopes, e.g.
```rb
class User < ApplicationRecord
scope :with_role, ->(role) { where("role = #{role}") } #(3)
end
class UsersController < ApplicationController
def show
role = params[:role] # (1)
@users = User.with_role(role) # (2)
end
end
```
We will track flow from `role` assigned in (1), through the call to `with_role` (2) which targets the lambda at (3). We do this by adding an additional call step.
Also add a few missing flow summaries for Hash.
=> Ruby: Track flow into ActiveRecord scopes

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplSpecific.qll, python/ql/test/experimental/dataflow/summaries/InlineTaintTest.expected, python/ql/test/experimental/dataflow/summaries/InlineTaintTest.ql, python/ql/test/experimental/dataflow/summaries/TestSummaries.qll, python/ql/test/experimental/dataflow/summaries/conflicting_summaries.py, python/ql/test/experimental/dataflow/summaries/extracted_package/functions.py
We noticed that when
- a function has more than one summary (with different charpred)
- one summary is subsumed by a subpath (or something happens around the function being extracted)
- the function is called multiple times(we needed at least three)
one of the summaries would no longer lead to flow.
Fixed by doing the same as Ruby in https://github.com/github/codeql/pull/15689
=> Python: No `fieldFlowBranchLimit` for `SummarizedCallable`s

cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll, cpp/ql/test/library-tests/controlflow/guards-ir/tests.ql, cpp/ql/test/library-tests/controlflow/guards/GuardsCompare.expected, cpp/ql/test/library-tests/controlflow/guards/GuardsCompare.ql
I got the interface slightly wrong in https://github.com/github/codeql/pull/15958: In https://github.com/github/codeql/blob/219cd4e41514b53447a098c398b00047bf6e53b2/cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll#L143 it doesn't make sense to simply have a boolean to determine whether "the test was true or false" since the "test" may be the scrutinee of a `switch`. So instead, this PR updates the newly added predicates to instead have an `AbstractValue` column. The effect of this is visible in the [second commit](c640bd67e934de2efcbbb3c26abe4bc77afdcd45) where we previously had:
```
| 61 | i == 0 when i is true |
| 61 | i == 1 when i is true |
| 61 | i == 2 when i is true |
```
which made no sense.
Note that this isn't a breaking change since the new predicates has only been there for …
=> C++: Fix interface for `GuardCondition.comparesEq` and `GuardCondition.ensuresEq`

cpp/ql/lib/change-notes/2024-03-19-predicates-for-switches-as-guards-2.md, cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll, cpp/ql/test/library-tests/controlflow/guards-ir/tests.expected, cpp/ql/test/library-tests/controlflow/guards-ir/tests.ql, cpp/ql/test/library-tests/controlflow/guards/GuardsCompare.expected, cpp/ql/test/library-tests/controlflow/guards/GuardsCompare.ql
This is the _final_ PR we need to fully support `switch` statement support in the Guards library 🎉 This PR is the `<` version of https://github.com/github/codeql/pull/15958 that ensures that we can know the lower and upper bounds given by `case` statements such as:
```cpp
switch(i) {
case 0 ... 10:
// i >= 0 and i < 11 in here
break;
}
```
Commit-by-commit review recommended
=> C++: Support `<` reasoning for `switch` statements in Guards library

docs/codeql/reusables/supported-versions-compilers.rst
We shipped Go 1.22 support in CodeQL 2.16.4. This updates the documentation to include Go 1.22 in the range of supported versions.
=> Docs: Add Go 1.22 to supported versions range

go/extractor/extractor.go
This PR enables `CODEQL_EXTRACTOR_GO_FAST_PACKAGE_INFO` by default. This speeds up Go dependency extraction by only invoking `go list` once per logical workspace, rather than once per dependency. 
This has been tested with a QA experiment, which showed no regressions caused by turning this on by default and improvements in extraction times across the board.
=> Go: Make `CODEQL_EXTRACTOR_GO_FAST_PACKAGE_INFO` on by default

cpp/ql/src/Critical/MissingCheckScanf.ql, cpp/ql/src/change-notes/2024-03-20-missing-check-scanf-path-problem.md, cpp/ql/test/query-tests/Critical/MissingCheckScanf/MissingCheckScanf.expected
Turns `cpp/missing-check-scanf` into a `path-problem` query as suggested by @jketema [here](https://github.com/github/codeql/pull/15988#issuecomment-2009747855).
=> Make `cpp/missing-check-scanf` a `path-problem` query

ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/ql.dbscheme, ql/ql/src/ql.dbscheme.stats, ruby/downgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/erb_ast_node_info.ql, ruby/downgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/old.dbscheme, ruby/downgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/ruby.dbscheme, ruby/downgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/ruby_ast_node_info.ql, ruby/downgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/upgrade.properties, ruby/extractor/Cargo.lock, ruby/extractor/Cargo.toml, ruby/extractor/cargo-bazel-lock.json, ruby/ql/lib/codeql/ruby/AST.qll, ruby/ql/lib/codeql/ruby/ast/internal/TreeSitter.qll, ruby/ql/lib/ruby.dbscheme, ruby/ql/lib/ruby.dbscheme.stats, ruby/ql/lib/upgrades/f9f0f4023e433184fda76f595247bf448b782135/erb_ast_node_location.ql, ruby/ql/lib/upgrades/f9f0f4023e433184fda76f595247bf448b782135/erb_ast_node_parent.ql, ruby/ql/lib/upgrades/f9f0f4023e433184fda76f595247bf448b782135/old.dbscheme, ruby/ql/lib/upgrades/f9f0f4023e433184fda76f595247bf448b782135/ruby.dbscheme, ruby/ql/lib/upgrades/f9f0f4023e433184fda76f595247bf448b782135/ruby_ast_node_location.ql, ruby/ql/lib/upgrades/f9f0f4023e433184fda76f595247bf448b782135/ruby_ast_node_parent.ql, ruby/ql/lib/upgrades/f9f0f4023e433184fda76f595247bf448b782135/upgrade.properties, shared/tree-sitter-extractor/src/extractor/mod.rs, shared/tree-sitter-extractor/src/generator/mod.rs, shared/tree-sitter-extractor/src/generator/ql_gen.rs
The DIL generated for `AstNode.getParent` is unnecessarily complex. Instead of using the `ast_node_info` extensional directly, we get a join with
```ql
TreeSitter::Ruby::AstNode#941e5e6b#b(
/* TreeSitter::Ruby::AstNode.extends */ interned unique entity this
)
{
(
exists(
/* @ruby_underscore_method_name */ interned dontcare entity _,
/* @ruby_underscore_method_name */ interned dontcare entity _1
|
ruby_alias_def(this, _, _1)
) and
project#ruby_ast_node_info(this)
)
or
(ruby_alternative_pattern_def(this) and project#ruby_ast_node_info(this))
// or
// ... one case for each member @ruby_ast_node
```
This happens because `ast_node_info` needs to contain a row for each AST node, as it also records AST node locations, and hence the column for the parent is not simply an `AstNode`, but either an …
=> Tree-sitter: Split up `ast_node_info` table into two tables

cpp/ql/src/Critical/ScanfChecks.qll
We now use the new predicates added in https://github.com/github/codeql/pull/15980 (we already updated other parts of the query to use https://github.com/github/codeql/pull/15958).
=> C++: Simplify use of guard conditions in `cpp/incorrectly-checked-scanf`

csharp/extractor/Semmle.Extraction/Context.cs
The TRAP stack is used to prevent duplicate entities in the DB, when the same source file is compiled multiple times. However, this can never happen in buildless mode, so there is no reason to emit `.push` and `.pop` instructions.
Reduces [TRAP size](https://github.com/github/codeql-dca-main/blob/data/hvitved/pr-15994-79dc7f__nightly-buildle__nightly/reports/summaries/space.theme.md#trap-size-per-source) and [TRAP import](https://github.com/github/codeql-dca-main/blob/data/hvitved/pr-15994-79dc7f__nightly-buildle__nightly/reports/summaries/time.theme.md#trap-import-time-per-source) a bit.
=> C#: Avoid using TRAP stack in buildless mode

swift/extractor/BUILD.bazel
Our tracer has problems with relocating this specific extractor binary.
=> Swift: add `-headerpad_max_install_names` to link options

cpp/ql/src/Critical/MissingCheckScanf.ql
These now use the new predicates added in https://github.com/github/codeql/pull/15958 and https://github.com/github/codeql/pull/15980
=> C++: Simplify use of guard conditions in `cpp/missing-check-scanf`

cpp/ql/src/Summary/LinesOfUserCode.ql, csharp/ql/src/Metrics/Summaries/LinesOfCode.ql, go/ql/src/Summary/LinesOfCode.ql, java/ql/src/Metrics/Summaries/LinesOfCode.ql, javascript/ql/src/Summary/LinesOfUserCode.ql, python/ql/src/Summary/LinesOfUserCode.ql, ql/ql/src/queries/summary/LinesOfCode.ql, ql/ql/src/queries/summary/LinesOfUserCode.ql, ruby/ql/src/queries/summary/LinesOfCode.ql, ruby/ql/src/queries/summary/LinesOfUserCode.ql, swift/ql/src/diagnostics/SuccessfullyExtractedLines.ql
The new file coverage metrics are available in all supported GHES versions. This PR tags lines of code queries as `debug`.  This means that lines of code information will only be shown in the logging output of the CLI when running at higher verbosities (including the CodeQL Action debug mode).  Lines of code information will also still be available in the SARIF file.
The one exception is the metric queries for Java/Kotlin that provides separate lines of code information for Java and Kotlin. I've left these as non-debug level since separate file coverage information for languages like Java and Kotlin is only available for GHES 3.12 and later.
=> Show lines of code data in debug mode only

swift/third_party/BUILD.swift-toolchain-linux.bazel
This allows the bazel cache to cache this genrule invocation. It shouldn't depend on system-specific binaries, so I believe this is correct.
This is the only part of our build where we otherwise need to recompute parts after pulling in a full cache.
=> Swift genrule: Replace local with no-sandbox.

csharp/ql/src/Security Features/WeakEncryption.qhelp
I've copied the sentence regarding the use of AES in ECB mode from the corresponding [Java query QHelp](https://codeql.github.com/codeql-query-help/java/java-potentially-weak-cryptographic-algorithm/) (`java/potentially-weak-cryptographic-algorithm`).
=> C#: add hint regarding ECB to weak encryption QHelp

cpp/ql/src/Likely Bugs/Protocols/TlsSettingsMisconfiguration.ql, cpp/ql/src/Likely Bugs/Protocols/UseOfDeprecatedHardcodedProtocol.ql, cpp/ql/src/change-notes/2024-03-22-boost-ssl.md
Also clean up the names of the queries while here.
=> C++: Add precision to `cpp/boost/tls-settings-misconfiguration` and `cpp/boost/use-of-deprecated-hardcoded-security-protocol`

javascript/ql/src/DOM/TargetBlank.qhelp, javascript/ql/src/DOM/TargetBlank.ql, javascript/ql/src/change-notes/2024-03-21-target-blank-precision.md
Fixes https://github.com/github/codeql/issues/15995
=> JS: change the precision of the `js/unsafe-external-link` query to `low`

go/ql/src/Security/CWE-022/TaintedPath.qhelp, go/ql/src/Security/CWE-022/TaintedPathGood.go, go/ql/src/Security/CWE-022/TaintedPathGood2.go
Closely mimics the changes for Java in https://github.com/github/codeql/pull/15409.
=> Go: Update query help for `go/path-injection` to include example fixes.

java/ql/integration-tests/all-platforms/kotlin/default-parameter-mad-flow/test.ext.yml
An upcoming CLI change will start validating test-specific data extensions more thoroughly, and this test was using the wrong pack name in its `addsTo:` property.
=> Use correct model pack name in qltest data extension

java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.ext.yml
We were extending a predicate that does not exist, but we weren't adding any data anyway. I think we might have removed that predicate early in the threat model work.
There's an in-flight CodeQL PR that will start emitting validation errors for data extensions in QL tests, just like we already do for regular data extensions.
=> Remove unused data extension in test

go/ql/lib/change-notes/2024-03-20-dependecy-retrieval-improvement.md
This adds a changenote for the change made in https://github.com/github/codeql/pull/15935.
=> Go: Add changenote for `CODEQL_EXTRACTOR_GO_FAST_PACKAGE_INFO` change

cpp/ql/lib/change-notes/2024-03-26-taint-inheriting-content.md, cpp/ql/lib/semmle/code/cpp/ir/dataflow/FlowSteps.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TaintTrackingUtil.qll, cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/taint.ql
Many other languages have found this class very useful and in the name of aligning languages we should add it to C/C++ as well.
=> C++: Add `TaintInheritingContent`

go/ql/src/Security/CWE-601/OpenUrlRedirect.qhelp, go/ql/src/Security/CWE-601/OpenUrlRedirectGood.go, go/ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirectGood.go
The example showed a different (and better) fix from what the help claimed, but the suggestion also had a subtle bug that I fixed at the same time.
=> Go: Improve QHelp for `go/unvalidated-url-redirection`.

java/ql/src/Likely Bugs/Statements/MissingEnumInSwitch.ql, java/ql/src/change-notes/2024-03-27-MissingEnumInSwitch.md, java/ql/test/query-tests/Likely Bugs/Statements/MissingEnumInSwitch/MissingEnumInSwitch.expected, java/ql/test/query-tests/Likely Bugs/Statements/MissingEnumInSwitch/MissingEnumInSwitch.qlref, java/ql/test/query-tests/Likely Bugs/Statements/MissingEnumInSwitch/Test.java
The tool status page warns:
```
An analysis file contained multiple alerts that included more related
locations than our allowed limit of 100.
These alerts correspond to the rule java/missing-case-in-switch.
Only 100 locations were stored for these alerts.
```
Here's one possible fix: This change the query so that we only get a single alert for a switch, but it gives up to 3 cases that are not matched, along with the count of how many more cases there are. What do you think?
Another possibility, that will fix some cases (silencing them completely) but miss others, is C++'s approach of requiring a certain percentage of cases to be covered: https://github.com/github/codeql/blob/main/cpp/ql/src/Likely%20Bugs/Likely%20Typos/MissingEnumCaseInSwitch.ql#L21
=> Java: Limit the amount of results that MissingEnumInSwitch produces per switch

docs/codeql/codeql-language-guides/codeql-for-ruby.rst, docs/codeql/codeql-language-guides/customizing-library-models-for-ruby.rst
The content has already been reviewed in https://github.com/github/codeql/pull/15488. This just re-adds it.
=> Ruby: Re-add MaD docs

go/extractor/cli/go-autobuilder/go-autobuilder.go, go/extractor/diagnostics/diagnostics.go, go/extractor/project/project.go, go/extractor/toolchain/toolchain.go, go/extractor/toolchain/toolchain_test.go, go/ql/integration-tests/all-platforms/go/diagnostics/invalid-toolchain-version/diagnostics.expected, go/ql/integration-tests/all-platforms/go/diagnostics/invalid-toolchain-version/src/go.mod, go/ql/integration-tests/all-platforms/go/diagnostics/invalid-toolchain-version/src/main.go, go/ql/integration-tests/all-platforms/go/diagnostics/invalid-toolchain-version/test.py, go/ql/integration-tests/all-platforms/go/go-version-bump/diagnostics.expected, go/ql/integration-tests/all-platforms/go/go-version-bump/src/go.mod, go/ql/integration-tests/all-platforms/go/go-version-bump/src/main.go, go/ql/integration-tests/all-platforms/go/go-version-bump/test.py, go/ql/integration-tests/all-platforms/go/two-go-mods-one-failure/diagnostics.expected
Starting in Go 1.21, Go uses a new version format for toolchains which uses [the `1.N.P` syntax](https://tip.golang.org/doc/toolchain#version). This is a problem for our users when their `go.mod` files only contain a `go` directive that uses the old version format, e.g. `go 1.22`. `1.22` is a valid _language_ version, but not a valid _toolchain_ version. If there is no additional `toolchain` directive in the `go.mod` file, then `go` uses the _language_ version as the _toolchain_ version. In the example, `1.22` is _not_ a valid _toolchain_ version and certain `go` commands, particularly those which try to acquire the toolchain corresponding to that version, fail with an unhelpful error.
In this PR, we make two changes to the Go autobuilder:
1. We detect `go.mod` files where the _language_ …
=> Go: Deal with incorrect toolchain versions

docs/codeql/codeql-language-guides/codeql-for-javascript.rst, docs/codeql/codeql-language-guides/customizing-library-models-for-javascript.rst
This is the JS equivalent to https://github.com/github/codeql/pull/16073.
The content in customizing-library-models-for-javascript.rst is stable should be made more visible to users. This PR makes the article visible to search and the docs ToC. 
There are some other content changes that should probably be made, but they can take place in a follow up PR.
=> Make customizing-library-models-for-javascript.rst visible to search and the docs TOC

ruby/ql/lib/codeql/ruby/security/UnsafeHtmlConstructionCustomizations.qll, ruby/ql/lib/codeql/ruby/security/UnsafeHtmlConstructionQuery.qll, ruby/ql/lib/codeql/ruby/security/XSS.qll, ruby/ql/test/query-tests/security/cwe-079/UnsafeHtmlConstruction.expected, ruby/ql/test/query-tests/security/cwe-079/lib/unsafeHtml.rb
And refactor the `unsafe-html-construction` query to re-use the reflected-xss sanitizers.  
[The evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/htmlSafeSan__nightly__code-scanning/reports) shows that we remove an FP we had before.
=> RB: Add barrier guard for `.html_safe?` to the XSS queries

ql/ql/src/codeql-suites/ql-code-scanning.qls
Add diagnostics and summary metric queries to the code scanning suite.  This means we'll see them in QL for QL runs on this repository.
=> QL: Run diagnostics and summary metrics in code scanning

java/ql/test-kotlin2/library-tests/exprs/exprs.expected
In a couple of the commit messages, I've shown the Kotlin IR changes that lead to the QL change.
=> Kotlin 2: Accept more changes

javascript/ql/lib/semmle/javascript/AST.qll, javascript/ql/lib/semmle/javascript/Functions.qll, javascript/ql/lib/semmle/javascript/Stmt.qll, javascript/ql/lib/semmle/javascript/frameworks/Bundling.qll, javascript/ql/src/Expressions/UnknownDirective.ql, javascript/ql/test/library-tests/Directives/KnownDirective.ql, javascript/ql/test/query-tests/Expressions/UnknownDirective/UnknownDirective.expected, javascript/ql/test/query-tests/Expressions/UnknownDirective/UnknownDirective.js
Fixes https://github.com/github/codeql/issues/13296
The subclasses of `KnownDirective` were all declared at the top-level of `Stmt.qll`. This means we couldn't add new subclasses without introducing a top-level name exported by `javascript.qll`. So this PR first moves all those subclasses into a `Directives` module. Thanks to the new shadowing rules we can actually leave deprecated aliases for these in the top-level.
Lastly this adds two more directives to handle `"use client"` and `"use server"`.
=> JS: Move Directive subclasses into module and support "use client/server"

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, go/ql/lib/semmle/go/dataflow/ExternalFlow.qll, swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
Remove claims from the models-as-data `ExternalFlow.qll` documentation that appear to be untrue (or unhelpful and confusing).  Following discussions with @atorralba , I believe it's only possible to select a _parameter_ in the Java language (using the "Annotation" feature).  In other languages you have to select the _function_ and use `.Parameter` syntax in the input / output field to deal with parameters (which is also possible in Java).  Its also possible to select a _field_ directly in all languages I think.
So this PR removes what I believe are untrue claims in Swift (resulting from copy-pasting the doc between languages), but which I'm much less confident about in C# and Go.  Please review with care.
=> Remove [potentially] untrue claims about models-as-data

go/extractor/project/project.go
This removes a problematic change introduced in https://github.com/github/codeql/pull/15979 which invokes `go version` in the `LoadGoModules` function with a suitable `GOTOOLCHAIN` environment variable to try and force Go to install a particular version of Go. This does not seem to work correctly and, additionally, breaks the `resolve build-environment` functionality for Go. Therefore, we are temporarily removing the call until those issues are addressed.
=> Go: Revert `go version` call in `LoadGoModules`

csharp/ql/lib/ext/System.Diagnostics.model.yml, csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected, csharp/ql/test/query-tests/Security Features/CWE-078/CommandInjection.expected
I don't think we'd ever want taint summaries for property setters, as they should be store steps instead (at least once https://github.com/github/codeql/pull/16088 is merged). This PR removes a few such taint summaries.
=> C#: Neutralize some `System.Diagnostics` generated models

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-flow.expected, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-flow.ql, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.expected, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.ql, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier_flow.rb, ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected, ruby/ql/test/library-tests/dataflow/local/TaintStep.expected, shared/ssa/codeql/ssa/Ssa.qll
Barrier guards are implemented using SSA; a node is guarded if it is a read of an SSA definition `def`, where `def` is also read in a controlling condition:
```rb
x = taint
if safe(x) then
sink(x) # guarded
end
```
However, this approach does not work when a condition controls not a read, but instead input into a phi node:
```rb
x = taint # 1
if not safe(x) then
x = safe # 2
end
sink(x)
```
In the above, the input into `phi` from `x = taint` (1) is controlled by the `true` edge out of `safe(x)`, but the read of `x` in `sink(x)` is not.
In order to handle this scenario (under-the-hood) with barrier guards, we add a new type of (hidden) data flow nodes that represent input into `phi` nodes, and then split the data flow step `x -> phi` into two steps `x -> [input 1] phi` and `[input 1] phi …
=> Ruby: Extend barrier guards to handle phi inputs

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
In the name of reducing false negatives, this PR assumes that all properties defined in non-source-code behave like fields when tracking data flow.
=> C#: Include all non-source-code properties in data flow

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
https://github.com/github/codeql/pull/16087 follow-up:
```
Evaluated relational algebra for predicate DataFlowImpl::Impl<PolynomialReDoSQuery::PolynomialReDoSFlow::C>::storeEx/5#34133ef9@0425e0m7 with tuple counts:
2209132     ~1%    {6} r1 = SCAN `DataFlowImpl::Impl<PolynomialReDoSQuery::PolynomialReDoSFlow::C>::storeExUnrestricted/5#3a86a98e` OUTPUT In.1, In.0, In.1, In.2, In.3, In.4
4338565685     ~1%    {6}    | JOIN WITH `DataFlowPublic::ContentSet.getAReadContent/0#dispred#e4acf74e_10#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5
34811200  ~1428%    {5}    | JOIN WITH `project#DataFlowImpl::Impl<PolynomialReDoSQuery::PolynomialReDoSFlow::C>::readSetEx/3#35ac556a` ON FIRST 1 OUTPUT Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5
return r1
```
=> Data flow: Fix bad join

ruby/ql/src/queries/security/cwe-116/IncompleteMultiCharacterSanitization.qhelp
I haven't checked `git blame`, but I just assume that I made the mistake myself.
=> RB: fix language specifier typo in qhelp for rb/multi-char-san

javascript/ql/lib/semmle/javascript/dataflow/internal/CallGraphs.qll, javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/Test.expected, javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/implied-receiver.js
Propagates `this` into functions that are installed on objects in a non-trivial way, e.g:
```js
function fooFactoryFactory() {
return function fooFactory() {
return function foo() {
/** calls:F.member */
this.member();
}
}
}
function F() {
this.foo = fooFactoryFactory()();
}
```
=> JS: more implied receiver steps

docs/codeql/reusables/supported-versions-compilers.rst
The footnote wasn't properly updated in https://github.com/github/codeql/pull/16133. @turbo suggested that we simply remove the version number from the footnote to avoid making this mistake again.
=> Docs: Remove Swift version in footnote

java/ql/lib/qlpack.yml, java/ql/lib/semmle/code/java/dataflow/TypeFlow.qll, shared/typeflow/change-notes/2024-02-26-initial-version.md, shared/typeflow/codeql/typeflow/TypeFlow.qll, shared/typeflow/codeql/typeflow/internal/TypeFlowImpl.qll, shared/typeflow/qlpack.yml
This PR pulls out the shareable parts of Java's type-flow library into a new shared qlpack. In a subsequent PR, I plan to make use of this library for C/C++ dataflow 🤞
=> Java/Shared: Refactor `TypeFlow.qll` into a shared library

python/extractor/buildtools/index.py
The comments says 2.17.0, but I was a little too late to uphold that promise :sweat_smile:
=> Python: Extractor: Remove dependency installation fallback

cpp/ql/lib/semmle/code/cpp/models/Models.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/Fopen.qll
These will prevent the one query result regression I'm seeing when enabling sound IR.
I'm not adding any interesting taint here or anything. The class merely states that `fopen` and friends don't cause arguments to escape. A future PR could probably add taint flow for these functions, but I want to keep this PR minimal as it's blocking sound IR.
DCA shows some new FPs for `cpp/uninitialized-local`, but these will all disappear once sound IR is merged. I'll open that PR as soon as this one is merged.
=> C++: Add alias models for `fopen` and friends

docs/codeql/codeql-language-guides/customizing-library-models-for-javascript.rst, javascript/ql/lib/semmle/javascript/ApiGraphs.qll, javascript/ql/src/change-notes/2024-04-08-instance-to-subclasses.md, javascript/ql/test/library-tests/frameworks/data/test.expected, javascript/ql/test/library-tests/frameworks/data/test.js, javascript/ql/test/library-tests/frameworks/data/test.ql
This makes the `Instance` MaD token obtain instances of the current class as well as instances of subclasses of the current class. For the moment this only works for sources (formerly known as use-nodes). I'll add a corresponding case for sinks (def-nodes) in a separate PR.
For example, `foo;Member[C].Instance.Member[m]` now matches the following:
```js
import { C } from "foo";
new C().m(); // <-- found (same as before)
class D extends C {
d() {
this.m(); // <-- found (new)
}
new D().m(); // <-- found (new)
```
This aligns with how MaD for Ruby works, and resolves some issues that were raised in user feedback (see backlink).
=> JS: Make getInstance() propagate to subclasses

java/ql/src/Likely Bugs/Arithmetic/InformationLoss.ql, java/ql/test/query-tests/security/CWE-190/semmle/tests/InformationLoss.expected, java/ql/test/query-tests/security/CWE-190/semmle/tests/Test.java
I'm not at all sure if this is the right approach.  
I saw an (internal) alert, where I noticed that the alert-location was very different from the location that needed to be modified to fix the alert, so I've tried to add a link that should link to the variable declaration (if relevant).  
[An evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/PR-16128-0-java__2/reports) confirms that there is no change in results or performance.  
The only thing that's changed is the alert-message.  
What do you think?
=> Java: add link to the source variable in the alert-message for `java/implicit-cast-in-compound-assignment`

swift/actions/run-integration-tests/action.yml
This uses [this workaround](https://github.com/redsun82/setup-swift/commit/b2b6f77ab14f6a9b136b520dc53ec8eca27d2b99) for https://github.com/swift-actions/setup-swift/issues/591.
=> CI: apply `setup-swift` workaround

csharp/ql/integration-tests/all-platforms/diag_recursive_generics/Types.ql, csharp/ql/lib/semmle/code/csharp/Element.qll, csharp/ql/lib/semmle/code/csharp/Member.qll, csharp/ql/lib/semmle/code/csharp/Namespace.qll, csharp/ql/lib/semmle/code/csharp/commons/QualifiedName.qll, csharp/ql/lib/semmle/code/csharp/dataflow/SSA.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/lib/semmle/code/csharp/security/dataflow/ExternalAPIsQuery.qll, csharp/ql/test/library-tests/attributes/AttributeElements.ql, csharp/ql/test/library-tests/constructors/Destructors1.ql, csharp/ql/test/library-tests/csharp11/fileScoped.ql, csharp/ql/test/library-tests/csharp11/nativeInt.ql, csharp/ql/test/library-tests/csharp9/covariantReturn.ql, csharp/ql/test/library-tests/csharp9/foreach.ql, csharp/ql/test/library-tests/csharp9/record.ql, csharp/ql/test/library-tests/csharp9/withExpr.ql, csharp/ql/test/library-tests/dispatch/GetADynamicTarget.ql, csharp/ql/test/library-tests/enums/Enums3.ql, csharp/ql/test/library-tests/frameworks/system/Dispose/Dispose.ql, csharp/ql/test/library-tests/frameworks/system/Equals/Equals.ql, csharp/ql/test/library-tests/generics/Generics.ql, csharp/ql/test/library-tests/overrides/Overrides22.ql, csharp/ql/test/library-tests/unification/Unification.ql
In this PR we replace the last uses of `getFullyQualifiedName` and `getFullyQualifiedNameWithTypes` (and deprecate and uncache these) with their `hasFully..` counterparts to avoid unneeded string concatenation (and thus pressure on the string pool).
Further more we delete some of the deprecated caches predicates.
=> C#: Fully qualified name.

docs/codeql/codeql-language-guides/customizing-library-models-for-csharp.rst, docs/codeql/codeql-language-guides/customizing-library-models-for-java-and-kotlin.rst, docs/codeql/reusables/threat-model-description.rst
Moves duplicated content on threat models into a reusable for maintainability.
=> Make duplicated content clear

cpp/ql/lib/qlpack.yml, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TypeFlow.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp, cpp/ql/test/library-tests/dataflow/dataflow-tests/type-bugs.expected
This PR instantiates the newly created `TypeFlow` library that was pulled out of Java [here](https://github.com/github/codeql/pull/15728) for C/C++. The use-case for C/C++ is that we want to determine whether a pointer points to a single object or a buffer (i.e., multiple consecutive objects). This addresses FPs in dataflow/taint-flow queries such as:
```cpp
void write_and_use(int* p) {
*p = 0;
use(p); // <-- should *p be tainted here?
}
```
if `p` is simply the address of a local variable such as `&x` where `x` is an `int`, then `*p = 0` overwrites any possible previous value. However, if `p` is the result of calling `malloc(1024)`, then tainted data may still be obtained from `p` (for example, by reading `*(p + 1)`).
On `main` we rely on GVN to check if `p` was equal to some …
=> C++: Use the shared typeflow library

go/ql/lib/semmle/go/internal/Locations.qll
This fixes a performance problem in code introduced in https://github.com/github/codeql/pull/15853. The below numbers were obtained on `dolthub/go-mysql-server`, but I have seen the evaluator do the same optimizations on other projects.
Before:
```
[2024-04-10 11:18:51] Evaluated non-recursive predicate _Files::File#0e2ffa35_files_locations_default_23451#join_rhs_project#DataFlowUtil::Node.hasLocationI__#antijoin_rhs@212c1fm6 in 23595ms (size: 14907567).
Evaluated relational algebra for predicate _Files::File#0e2ffa35_files_locations_default_23451#join_rhs_project#DataFlowUtil::Node.hasLocationI__#antijoin_rhs@212c1fm6 with tuple counts:
15168020  ~1%    {5} r1 = SCAN `project#DataFlowUtil::Node.hasLocationInfo/5#dispred#c7d73140` OUTPUT In.1, In.2, In.3, In.4, In.0
1109162913  ~0%    {6} …
```
=> Go: Avoid magic in `TSynthLocation` definition

go/ql/lib/change-notes/2023-10-08-addional-gopath-sanitizers.md, go/ql/lib/change-notes/2024-03-11-addional-gopath-sanitizers.md, go/ql/lib/semmle/go/security/TaintedPathCustomizations.qll, go/ql/test/query-tests/Security/CWE-022/TaintedPath.expected, go/ql/test/query-tests/Security/CWE-022/TaintedPath.go
This PR adds some additional sanitizers to the TaintedPath Customization due to a high number of false positives I have found after doing some research.
I have added:
filepath.Base
strings.ReplaceAll
http.ParseMultipartForm
I have also removed path.Clean as it does not sufficiently clean paths for software that can run on Windows.
Please see: https://github.com/labstack/echo/pull/1718 as an example.
=> Go: Add and Modify Sanitizers For TaintedPath

ruby/ql/src/queries/security/cwe-078/UnsafeShellCommandConstruction.qhelp, ruby/ql/src/queries/security/cwe-078/examples/unsafe-shell-command-construction_fixed.rb
The `Kernel::system(...)` call does not accept an array as input, so the QHelp should not mention arrays.
=> RB: don't mention arrays in the qhelp for rb/shell-command-constructed-from-input

MODULE.bazel, swift/third_party/load.bzl
The cleanup has to do with `repository_name` not being required any more, and some other unused code now that `semmle-code` is using bzlmod.
=> Bazel: `swift/third_party/load.bzl` cleanup and `bazel mod tidy` enablement

go/ql/lib/semmle/go/security/TaintedPathCustomizations.qll, go/ql/test/query-tests/Security/CWE-022/TaintedPath.expected, go/ql/test/query-tests/Security/CWE-022/TaintedPath.go
Follow up to https://github.com/github/codeql/pull/11703. Update a QLDoc, add another sanitizer and expand the replace all sanitizer to include other ways of replacing all. I think the original change note covers these changes too.
=> Go: Tweak go tainted path additions

go/integration-tests-lib/go_integration_test.py
We currently have a lot of code duplication in the Python sources for the Go integration tests. This PR adds some of the common Python code to a shared location, mirroring what is already done for Java. This shared code will later be usable by all integration tests to avoid code duplication. 
Note that there is an internal PR to accompany this one. However, this PR does not depend on the internal one (in the sense that it doesn't do anything either way) and can be merged without it.
=> Go: Add integration test library

python/extractor/buildtools/version.py
This PR modifies the check for the "py" launcher on Windows, in the Python extractor. We now look for the launcher only if the python_executable_name extractor option is not specified.
=> Python: Modifies check for py launcher on Windows

ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/lib/codeql/ruby/security/MassAssignmentCustomizations.qll, ruby/ql/lib/codeql/ruby/security/MassAssignmentQuery.qll, ruby/ql/src/change-notes/2024-03-22-mass-assignment.md, ruby/ql/src/queries/security/cwe-915/MassAssignment.qhelp, ruby/ql/src/queries/security/cwe-915/MassAssignment.ql, ruby/ql/src/queries/security/cwe-915/examples/MassAssignmentBad.rb, ruby/ql/src/queries/security/cwe-915/examples/MassAssignmentGood.rb, ruby/ql/test/query-tests/security/cwe-915/MassAssignment.expected, ruby/ql/test/query-tests/security/cwe-915/MassAssignment.qlref, ruby/ql/test/query-tests/security/cwe-915/test.rb
This query looks for instances of request parameters having `permit!` called on them, which allows arbitrary parameters to be specified by the request, and then being used for a mass assignment operation.
=> Ruby: Add query for insecure mass assignment

swift/ql/test/query-tests/Security/CWE-311/CleartextTransmission.expected
No idea why this test started failing on main, but the diff seems harmless.
=> Swift: accept new test results

.github/workflows/swift.yml
Not being triggered by changes in shared was making it possible to not notice changes in `shared` having effect on Swift tests. For example [this PR](https://github.com/github/codeql/pull/15501) introduced a test change that was fixed [here](https://github.com/github/codeql/pull/16197).
=> Swift: add `shared/**` to CI triggers

java/kotlin-extractor/deps.bzl, java/kotlin-extractor/deps/dev/.gitignore, java/kotlin-extractor/deps/dev/kotlinc, java/kotlin-extractor/deps/dev/kotlinc.bat, java/kotlin-extractor/versions.bzl
By adding `java/kotlinc-extractor/deps/dev` to `PATH`, one gets a `kotlinc` wrapper that takes care of downloading and extracting the desired version of `kotlinc` on demand. The desired version can be selected with `kotlinc --select x.y.z`, or left to the current default of `1.9.0`.
Moreover, this requested version is integrated with the Bazel build, so that when using this wrapper, changes in the selected version will be picked up to define the default single version kotlin extractor build, without needing to do anything else (like `bazel fetch --force` or similar).
Selected and installed version data is stored in `.gitignore`d files in the same directory, and can be cleared with `kotlinc --clear`.
=> Kotlin/Bazel: provide wrapper for managing versions of `kotlinc`

go/extractor/toolchain/toolchain.go
A hopefully small change which changes the behaviour of `GetEnvGoVersion` to respect existing values for `GOTOOLCHAIN` if the environment variable is already set. This is primarily useful for testing, where we can use this to force a particular toolchain to be used for the purpose of a test. It may also be useful for users who wish to override whatever the system default is.
=> Go: Respect `GOTOOLCHAIN` in `GetEnvGoVersion` if already set

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/AssemblyLookupLocation.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNetCliInvoker.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/IDotNetCliInvoker.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/NugetExeWrapper.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/NugetPackageRestorer.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/Razor.cs, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Extractor.cs, csharp/extractor/Semmle.Extraction.Tests/DotNet.cs
Replaced some `LogInfo` with `LogDebug` (some of the more chatty `LogInfo`).
@tamasvajk : Should we consider to use `LogDebug` when executing commands (most of the `onOut` callbacks - prints as Info)?
=> C#: Logging

ruby/ql/lib/codeql/ruby/security/CodeInjectionCustomizations.qll
Noticed the mistake when browsing the docs [here](https://codeql.github.com/codeql-standard-libraries/ruby/codeql/ruby/security/CodeInjectionCustomizations.qll/module.CodeInjectionCustomizations$CodeInjection$FlowState.html).
=> Tiny docs fix

cpp/ql/src/Critical/GlobalUseBeforeInit.ql, cpp/ql/test/query-tests/Critical/GlobalUseBeforeInit/GlobalUseBeforeInit.expected
@nickrolfe highlighted this bad join:
```ql
Evaluated relational algebra for predicate #select@4dc5a3gq with tuple counts:
1125  ~0%    {5} r1 = SCAN globalvariables OUTPUT In.0, _, In.2, _, _
1125  ~2%    {2}    | REWRITE WITH Tmp.1 := "The variable '", Tmp.3 := "'", Tmp.4 := " is used in this function but may not be initialized when it is called.", Out.1 := (Tmp.1 ++ In.2 ++ Tmp.3 ++ Tmp.4) KEEPING 2
6  ~0%    {3}    | JOIN WITH `GlobalUseBeforeInit::useFunc/2#81a8e7f2` ON FIRST 1 OUTPUT Lhs.0, Rhs.1, Lhs.1
1  ~0%    {2}    | JOIN WITH `GlobalUseBeforeInit::uninitialisedBefore/2#8cd27ca7#bf` ON FIRST 2 OUTPUT Lhs.1, Lhs.2
return r1
```
This is exactly the same kind of join order issue we've seen in https://github.com/github/codeql/pull/16089.
This query isn't in any security suite so it …
=> C++: Use interpolation to avoid a bad join order

python/ql/test/extractor-tests/flags/Flags.ql
In https://github.com/github/codeql/commit/25cb52aa52b30744575e6e8bfc1ec03a70bd265d I accidentally introduced an extra `not` where none existed before. Whoops! This naturally caused the test to fail. Hopefully this fix should do the trick. (Note again that currently no CI is run on this test -- that'll come later -- but as far as I can see, this is the only failing test after having moved all the tests out.)
=> Python: Fix flags test

cpp/ql/test/experimental/query-tests/Security/CWE/CWE-416/IteratorToExpiredContainer.expected, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-416/test.cpp
This represents the vast majority of FPs that we're seeing on MRVA for this query.
=> C++: Add `cpp/iterator-to-expired-container` FP test

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
This PR is fixing a bug introduced in https://github.com/github/codeql/pull/16195. (The order of the `Dispose` calls matter, also, I accidentally removed the check for `cleanupTempWorkingDirectory`.)
=> C#: Fix cleanup logic in dependency manager

csharp/ql/src/Telemetry/ExtractorInformation.ql
This PR is adjusting the "known type" query in `cs/telemetry/extraction-information` to match the java implementation. We're excluding expression from non-source files, such as arguments of attributes.
=> C#: Adjust known type telemetry query

cpp/ql/src/experimental/Security/CWE/CWE-416/IteratorToExpiredContainer.ql, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-416/IteratorToExpiredContainer.expected, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-416/test.cpp
This fixes the FP I added in https://github.com/github/codeql/pull/16232.
Unfortunately, this also removes a TP in one of the tests. We were never really supposed to catch this one, but we did so by accident. Fixing the FP also removes this accidental catch.
=> C++: Fix `cpp/iterator-to-expired-container` FPs

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
Before
```
(726s) Cancelling evaluation of #12545 evaluator rec DataFlowImpl::Impl<TaintedPath::TaintedPath::Flow::C>::Subpaths::subpaths05/4#6d4ff244/4@2f7ff6v4: No demand for this layer anymore.
(726s) Tuple counts for DataFlowImpl::Impl<TaintedPath::TaintedPath::Flow::C>::Subpaths::subpaths05/4#6d4ff244/4@i1#2f7ff6v4 after 11m42s:
3969000     ~1572%     {4} r1 = SCAN `DataFlowImpl::Impl<TaintedPath::TaintedPath::Flow::C>::Subpaths::subpaths04/4#89effa1e` OUTPUT In.1 'par', In.0 'arg', In.2, In.3 'out'
3963564     ~1607%     {4} r2 = r1 AND NOT `DataFlowImpl::Impl<TaintedPath::TaintedPath::Flow::C>::PathNodeImpl.isHidden/0#dispred#8010d23f`(FIRST 1)
9998        ~0%        {4} r3 = JOIN r1 WITH `#DataFlowImpl::Impl<TaintedPath::TaintedPath::Flow::C>::Subpaths::localStepFromHidden/2#2db712 …
```
=> Data flow: Fix a bad join

javascript/ql/lib/semmle/javascript/ApiGraphs.qll, javascript/ql/lib/semmle/javascript/ES2015Modules.qll, javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll, javascript/ql/lib/semmle/javascript/dataflow/Sources.qll, javascript/ql/test/ApiGraphs/custom-use-steps/VerifyAssertions.ql, javascript/ql/test/ApiGraphs/custom-use-steps/index.js, javascript/ql/test/ApiGraphs/custom-use-steps/package.json, javascript/ql/test/ApiGraphs/reexport/VerifyAssertions.expected, javascript/ql/test/ApiGraphs/reexport/index.js, javascript/ql/test/ApiGraphs/reexport/lib/esmodule-reexport.js, javascript/ql/test/ApiGraphs/reexport/lib/esmodule-reexported1.js, javascript/ql/test/ApiGraphs/reexport/lib/esmodule-reexported2.js, javascript/ql/test/library-tests/Modules/tests.expected
We didn't properly support this in API graphs:
```js
export * as foo from "./bar"
```
When we can resolve `./bar` to a module, we now generate store steps into the `* as foo` specifier, and mark `* as foo` as the export named `foo` in the current module.
This also led to some general improvements to API graphs since it's quite convenient if API graphs generally converts load/store to member steps (something similar is already happening in Ruby).
=> JS: Improve support for `export * as ...` declarations

go/ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll, go/ql/src/change-notes/2024-04-17-incorrect-integer-conversion-barriers.md, go/ql/test/query-tests/Security/CWE-681/IncorrectIntegerConversion.go
I found the type switch FPs while looking at the results for https://github.com/github/codeql/pull/16120, which fixed some broken flow into type switch clauses. While thinking about how best to fix them I also realised that any type assertion should transform the flow state, so I implemented that as well.
A before and after MRVA run suggests that on the top 1000 repos this PR removes 218 FPs, but the more detailed picture is more nuanced. On a very small number of repos it increased the number of alerts. This seems counter-intuitive, as this PR only adds barriers and hence should only remove results. I investigated and found that this was because removing some flow allowed us to find more results within the default limit for `fieldFlowBranchLimit`.
=> Go: Fix FPs in `go/incorrect-integer-conversion` query

csharp/extractor/Semmle.Extraction.CSharp/Extractor/Analyser.cs
Despite what the original comment said, calling `CSharpCompilation.Clone` actually makes the extractor consume _more_ memory instead of less memory, at least when running in buildless mode, where all `.cs` files are included in one single compilation.
Running buildless extraction on `dotnet/roslyn` locally with `/usr/bin/time -l` reported a `maximum resident set size` of `51,035,299,840` before this PR and `15,477,882,880` after.
DCA confirms that this is an improvement, as the database build time for `mono/mono` and `OrchardCMS/OrchardCore` decrease by 70% in buildless mode.
=> C#: Do not call `CSharpCompilation.Clone`

cpp/ql/lib/change-notes/2024-04-18-param-nodes.md, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/library-tests/dataflow/parameters-without-defs/test.cpp, cpp/ql/test/library-tests/dataflow/parameters-without-defs/test.expected, cpp/ql/test/library-tests/dataflow/parameters-without-defs/test.ql
This PR fixes an annoyance with `ParameterNode`s in C/C++ dataflow: Parameters of functions without a definition (i.e., when we only have a set of declarations) don't generate `ParameterNode`s.
This is because we define `ParameterNode`s using the `InitializeParameter` instruction in the IR, and without a function body there's no instructions associated with the function.
This PR fixes this by generating new dataflow nodes (from `Parameter`s) and marking those as `ParameterNode`s.
Ideally, only https://github.com/github/codeql/pull/16246/commits/98a3f2da7dd43ca0b82d638fa6b97f2e0b6927bc and https://github.com/github/codeql/pull/16246/commits/06f52c28547f12c7297e52a83f876dfea13e8eff would've been necessary. However, the current setup for marking parameter nodes wasn't very easy to extend to …
=> C++: Add Parameter nodes for functions without bodies

cpp/ql/lib/semmle/code/cpp/exprs/Expr.qll
This will slightly brake IR generation for databases created with CodeQL 2.17.1. There are two changes:
* Some type are different in the IR. This seems inconsequential.
* The IR becomes inconsistent when a null pointer is being deleted. This should hopefully not occur at all in real world code.
=> C++: Improve handling of re-use expressions

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplSpecific.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/test/library-tests/dataflow/taint-tests/swap2.cpp, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/collections/CollectionFlow.ql, csharp/ql/test/library-tests/dataflow/types/Types.ql, go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplSpecific.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, java/ql/test/library-tests/frameworks/guava/handwritten/flow.ql, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, shared/dataflow/change-notes/2024-04-19-fieldflowbranchlimit.md, shared/dataflow/codeql/dataflow/DataFlow.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/test/InlineFlowTest.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll, swift/ql/test/TestUtilities/InlineFlowTest.qll
This makes two changes to the fieldFlowBranchLimit interpretation:
* The count is adjusted to properly count virtual dispatch instead of nodes. This will block less flow and hence result in more computation and more alerts - hopefully fixing some FNs.
* The blocking condition on return edges is changed to only care about virtual dispatch count and not the number of call sites. This will block more flow and hopefully reduce FPs and performance problems based on uncertain dispatch. This has anecdotally been identified as the core issue in a couple of poorly performing cases.
For the return edge condition, special care is taken to still follow call edges that are determined by the call context.
All qltests are also updated to use the default fieldFlowBranchLimit instead of an inflated value …
=> Dataflow: update fieldFlowBranchLimit semantics

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
This fixes the comments I added [here](https://github.com/github/codeql/pull/15599#discussion_r1572142639).
=> C++: `fieldFlowBranchLimit` follow-up (1)

javascript/ql/lib/semmle/javascript/security/SensitiveActions.qll, javascript/ql/lib/semmle/javascript/security/internal/SensitiveDataHeuristics.qll, python/ql/lib/semmle/python/security/internal/SensitiveDataHeuristics.qll, ruby/ql/lib/codeql/ruby/security/internal/SensitiveDataHeuristics.qll, swift/ql/lib/codeql/swift/security/internal/SensitiveDataHeuristics.qll
It's generally faster to do `name.regexpMatch("a|b|c")` than `name.regexpMatch(["a", "b", "c"])`.
`SensitiveDataHeuristics.qll` is shared with Python/Ruby/Swift, but I haven't modified it in a way that would affect those languages. This approach would likely help those languages as well, but I don't know if any of them have the kinds of tuple counts we see with JS.
**Before:**
```
[2024-04-22 23:40:12] Evaluated non-recursive predicate _SensitiveActions::writesProperty/2#18c4f0d1_SensitiveDataHeuristics::HeuristicNames::maybeSensitive__#shared@b4f553uj in 2938ms (size: 1420).
Evaluated relational algebra for predicate _SensitiveActions::writesProperty/2#18c4f0d1_SensitiveDataHeuristics::HeuristicNames::maybeSensitive__#shared@b4f553uj with tuple counts:
3573353  ~0%    {4} r1 = JOIN …
```
=> JS: do fewer regexp matches in SensitiveActions

.github/workflows/buildifier.yml, .pre-commit-config.yaml, BUILD.bazel, MODULE.bazel, javascript/BUILD.bazel, javascript/extractor/BUILD.bazel, misc/codegen/BUILD.bazel, misc/codegen/generators/BUILD.bazel, python/extractor/tsg-python/tsp/BUILD.bazel, swift/extractor/BUILD.bazel, swift/logging/BUILD.bazel
This introduces tooling and enforcement for formatting bazel files.
The tooling is provided as a bazel run target from [keith/buildifier-prebuilt](https://github.com/keith/buildifier-prebuilt).
This is used in a [`pre-commit`](https://pre-commit.com/) hook for those having that installed. In turn this is used in a CI check. Relying on a `pre-commit` action gives us easy checking that buildifying did not change anything in the files and printing the diff, without having to hand-roll the check ourselves.
=> Bazel: introduce buildifier formatting

javascript/ql/lib/semmle/javascript/frameworks/data/ModelsAsData.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll, javascript/ql/test/library-tests/ModelGeneration/ModelGeneration.expected, javascript/ql/test/library-tests/frameworks/data/test.expected, javascript/ql/test/library-tests/frameworks/data/test.ext.yml, javascript/ql/test/library-tests/frameworks/data/test.js
The first commit fixes an issue where in model generation, where package names containing a dot weren't single-quoted, so they'd be parsed as a `<package>.<type>` pair instead of just a reference to the package.
This ends up looking a bit ugly for generated packages where we use the convention `(package).access_path`. So the following commit adds explicit support for `(package)` as a type name.
=> JS: Fix naming issue in generated models

ruby/ql/lib/codeql/ruby/security/SensitiveActions.qll
Follow-up to https://github.com/github/codeql/pull/16306, making the same changes for Ruby.
**Before:**
```
[2024-04-24 10:42:04] Evaluated non-recursive predicate _Constant::ConstantValue.isStringlikeValue/1#dispred#ff1ad965_SensitiveDataHeuristics::HeuristicName__#shared@fd52ac02 in 10567ms (size: 991).
Evaluated relational algebra for predicate _Constant::ConstantValue.isStringlikeValue/1#dispred#ff1ad965_SensitiveDataHeuristics::HeuristicName__#shared@fd52ac02 with tuple counts:
3539396  ~4%    {4} r1 = JOIN `SensitiveDataHeuristics::HeuristicNames::maybeSensitiveRegexp/1#d87d0a76` WITH `Constant::ConstantValue.isStringlikeValue/1#dispred#ff1ad965` CARTESIAN PRODUCT OUTPUT Lhs.0, Lhs.1, Rhs.0, Rhs.1
993  ~2%    {4}    | JOIN WITH PRIMITIVE regexpMatch#bb ON Lhs.3,Lhs.1
993  ~4%    {3} …
```
=> Ruby: do fewer regexp matches in SensitiveActions

go/extractor/project/project.go, go/extractor/project/project_test.go
In our current implementation of `LoadGoModules`, we use the `ParseLax` function which is described as "ParseLax is like Parse but ignores unknown statements". The intention here was that this would allow us to understand even slightly invalid `go.mod` files, but the reality is that the implementation of `ParseLax` only parses a subset of the full `go.mod` format. 
This PR changes our current use of `ParseLax` to `Parse` so that the module files are parsed in full, including `toolchain` directives. 
I also did some refactoring to allow the addition of some unit tests for the `go/autobuilder/invalid-go-toolchain-version` diagnostic condition that I wrote as part of troubleshooting this to make sure that the condition behaves as expected.
=> Go: Fix `LoadGoModules` missing out on `toolchain` directives

cpp/ql/src/experimental/Security/CWE/CWE-125/DangerousWorksWithMultibyteOrWideCharacters.ql
Fix typo in experimental query `cpp/dangerous-use-convert-function`.
=> C++: Fix typo.

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/Instruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/internal/SSAConstruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/Instruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/IRConstruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/Instruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SSAConstruction.qll
The `getResultIRType` was cached in a non-optimal way. The cached annotation was put on the top-level predicate (since we at some point identified that this predicate should be cached). However, by adding the `cached` keyword there instead of inside a `cached` module with all the other cached IR predicates the evaluator generated a whole evalaution stage just for this single predicate. This can be seen in evaluation logs such as:
```ql
Most expensive predicates for stage 15 of completed query TaintedPath.ql:
time | evals | max @ iter | predicate
-----|-------|------------|----------
7ms |       |            | Declaration::Declaration#46770055@c8d6b3b5
6ms |       |            | ExternalFlow::elementSpec/6#fd7bf2b1@8bed2a7i
6ms |       |            | …
```
=> C++: Remove a stage by properly caching `getResultIRType`

ruby/ql/src/queries/security/cwe-078/examples/file_open.rb, ruby/ql/src/queries/security/cwe-078/examples/kernel_open.rb
Update the examples for `rb/kernel-open` to show that `URI.open` is not good. Provide an alternative of `Net::HTTP.get(URI.parse(...))`, though there are many other good approaches too.
=> Ruby: Add URI.open example to rb/kernel-open qhelp

cpp/ql/src/Security/CWE/CWE-022/TaintedPath.ql, cpp/ql/src/change-notes/2024-04-25-path-injection.md, cpp/ql/test/query-tests/Security/CWE/CWE-022/semmle/tests/TaintedPath.expected, cpp/ql/test/query-tests/Security/CWE/CWE-022/semmle/tests/stdlib.h, cpp/ql/test/query-tests/Security/CWE/CWE-022/semmle/tests/test.c
Reduce duplication from the `cpp/path-injection` query, by making sources and sinks barriers.
=> C++: Reduce duplication from cpp/path-injection

cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedStmt.qll, cpp/ql/test/library-tests/ir/ir/PrintAST.expected, cpp/ql/test/library-tests/ir/ir/aliased_ir.expected, cpp/ql/test/library-tests/ir/ir/ir.cpp, cpp/ql/test/library-tests/ir/ir/raw_ir.expected
This fixes an IR generation problem that @jketema was seeing
Commit-by-commit review recommended
=> C++: Fix IR destructor calls on `JumpStmt`s

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
This should reduce peak memory usage in data flow.
=> Dataflow: Use doublyBoundedFastTC.

cpp/ql/src/Security/CWE/CWE-416/IteratorToExpiredContainer.qhelp, cpp/ql/src/Security/CWE/CWE-416/IteratorToExpiredContainer.ql, cpp/ql/src/Security/CWE/CWE-416/IteratorToExpiredContainerExtendedLifetime-fixed.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/IteratorToExpiredContainer/IteratorToExpiredContainer.expected
This PR does two things that should hopefully make the results from the new `cpp/iterator-to-expired-container` query easier to understand:
- It updates the alert message to more correctly reflect what's going on
- It updates the qhelp file so that it contains an example of a fix.
Note that, because of the first fix, we only get half the number of alerts since we no longer include the call to begin in the alert message. Previously, we'd often get an alert on the same location with two alert messages such as:
- This object is destroyed before `call to begin` is called.
- This object is destroyed before `call to end` is called.
Other than the alert being wrong, it was also quite annoying to have two alerts on the same element explaining the same problem.
=> C++: Improve documentation for `cpp/iterator-to-expired-container`

go/extractor/project/project.go
This revives a commit from https://github.com/github/codeql/pull/14194 that hadn't made its way into the code yet. Note that:
- `tryReadGoDirective` is only used as a fallback these days, if parsing the `go.mod` file fails.
- The `go.mod` parser also parses version suffixes, so this just means we can tolerate them better if we reach this fallback.
=> Go: Allow version suffixes

cpp/ql/src/experimental/Best Practices/GuardedFree.cpp, cpp/ql/src/experimental/Best Practices/GuardedFree.qhelp, cpp/ql/src/experimental/Best Practices/GuardedFree.ql
This PR introduces a new experimental query that finds instances of `free()` guarded by a superfluous NULL check.
=> Cpp: new experimental query cpp/guarded-free

misc/scripts/accept-expected-changes-from-ci.py
CI has changed how jobs are being run, so needed to make things slightly more robust. All changes are backwards compatible, so good to go :+1:
=> .expected script: Handle multiple job failure URLs

cpp/ql/src/Security/CWE/CWE-416/UseOfStringAfterLifetimeEnds.qhelp, cpp/ql/src/Security/CWE/CWE-416/UseOfStringAfterLifetimeEnds.ql, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/UseOfStringAfterLifetimeEnds/UseOfStringAfterLifetimeEnds.expected
Improve `cpp/use-of-string-after-lifetime-ends` `.qhelp`, references and alert message.  The aim is to be more helpful for users who are not very familiar with temporary objects and lifetime issues that can result.
@MathiasVP please check for technical inaccuracies.
Docs team, please make any suggestions you may have for readability etc.
=> C++: Improve UseOfStringAfterLifetimeEnds doc.

cpp/ql/test/query-tests/Critical/MemoryFreed/MemoryFreed.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/UseAfterFree.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/test.cpp
Adds a test case I wrote while reviewing a suspected FP for `UseAfterFree.ql`.  I could not reproduce the issue.
=> C++: Add test case for reassignment to UseAfterFree.ql.

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/IRVariable.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/IRVariable.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/IRVariable.qll
This PR is just a simple refactoring of the `IRVariable` files that replaces explicit enumeration of subclasses in the base class with abstract classes.
In order to ensure no other code accidentally extends the new abstract classes they're kept private and final aliases are provided. This means code will continue to work exactly as before.
=> C++: Clean up `IRVariable`s using final aliases

.github/workflows/buildifier.yml, .pre-commit-config.yaml, BUILD.bazel, misc/bazel/BUILD.bazel
See https://github.com/github/codeql/pull/16428 for details as to why this is necessary.
=> Bazel: move buildifier out of root `BUILD`

cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/IteratorToExpiredContainer/IteratorToExpiredContainer.expected, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/IteratorToExpiredContainer/test.cpp
This is a reduction of the class of FPs we saw once we merged a recent extractor change.
=> C++: Add `cpp/iterator-to-expired-container` FP

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/IteratorToExpiredContainer/IteratorToExpiredContainer.expected, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/IteratorToExpiredContainer/test.cpp
The motivation for this PR is the FP added in https://github.com/github/codeql/pull/16416.
Consider the FP added in that PR:
```cpp
void test5(int i)
{
while(i < 10) {
const auto& vvs = returnValue();
for(const auto& vs : vvs) { }
++i;
}
}
```
When the prvalue `returnValue()` is bound to the const reference `vvs` a temporary is created. That temporary has two important properties: the value of the temporary and the value of the _address_ of the temporary. Both of these have SSA definitions. However, the SSA definition for the value of the address of the temporary was placed at the entry of the function (see [this PR](https://github.com/github/codeql/pull/15047) for when this was added). Which meant that dataflow saw the code as:
```cpp
void test5(int i)
{
&#temp = ... // i.e., the …
```
=> C++: Fix location of SSA def for local variable addresses

javascript/ql/lib/semmle/javascript/frameworks/NodeJSLib.qll, javascript/ql/src/Security/CWE-798/HardcodedCredentials.qhelp, javascript/ql/src/Security/CWE-798/HardcodedCredentials.ql, javascript/ql/test/query-tests/Security/CWE-798/HardcodedCredentials.expected, javascript/ql/test/query-tests/Security/CWE-798/HardcodedCredentials.js
Fixes https://github.com/github/codeql/issues/16360 and https://github.com/github/codeql/issues/16359.  
Replaces https://github.com/github/codeql/pull/16244 
I looked at what credentials-kinds we have, and I found the below (list is possibly non-exhaustive):  
```
"user name"
"password"
"authorization header"
"key"
"token"
"credentials"
"Node.js http(s) client login username"
"Node.js http(s) client login password"
```
I changed the last two to just `user name` and `password`.  
We already filtered away keys that look like dummy passwords for `password`, `credentials`, and `token`, and it seemed reasonable to just add `key` to that list. 
I also added a note in the QHelp with two sample passwords that we recognize as dummy-passwords.
Evaluations …
=> JS: Remove some FPs from the hardcoded-credentials query

shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll, swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
This matches summaryThroughStepTaint.
=> Shared data flow: Make summaryThroughStepValue include param outputs

misc/scripts/accept-expected-changes-from-ci.py
When using a sufficiently new version of Python, it will give a warning
about the escape sequence `\_` in `¯\_(ツ)_/¯` not being a valid escape :D fix is to make the docstring a raw string.
Thanks @owen-mc
=> misc: Fix docstring warning

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
This is just a small cleanup that shouldn't have any external impact. The `BaseSourceVariableInstruction` column is functionally determined by the other columns, so we can simply remove it.
DCA was uneventful
=> C++: Remove an unnecessary column

go/ql/lib/change-notes/2024-05-08-fix-flow-variadic-builtin-variable.md, go/ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll
It was not defined for built-in functions or for functions called via a function variable.
I've pulled this commit out of https://github.com/github/codeql/pull/16413 so that it can be reviewed and performance-tested in isolation. I don't think it needs a test because it is tested by that PR, and by all the tests for data flow through variadic arguments.
=> Go: Fix `getType` on `ImplicitVarArgsSlice`

go/ql/test/query-tests/Security/CWE-078/CommandInjection.expected
I'm pretty sure this is what happened:
* https://github.com/github/codeql/pull/16457 was merged
* https://github.com/github/codeql/pull/16458 was merged without rebasing or merging in `main`
* the combination of the two meant that the test in question can now find paths using the existing taint flow using old-style go function models or value flow using the new-style go MaD models. This leads to extra edges and nodes without any extra results.
This will be fixed when https://github.com/github/codeql/pull/16413 is merged, which removes the old-style models. (Both of the above PRs were bug-fixes that I pulled out of https://github.com/github/codeql/pull/16413.)
=> Go: Fix test expectations

go/ql/src/Security/CWE-020/MissingRegexpAnchor.qhelp, go/ql/src/Security/CWE-020/MissingRegexpAnchorGoodDomain.go
It didn't seem clear what to do when the vulnerable regular expression is only for a hostname.
Some fixes ended up just inserting an end-anchor, and ignoring the beginning.  
So e.g. the "fix" `github.com$` could still be bypassed with e.g. `totallynotafakegithub.com`.
=> Go: Add an example specific to domain names in missing-regexp-anchor

csharp/downgrades/ab09ac8287516082b7a7367f8fda1862b1be47c5/upgrade.properties, csharp/ql/lib/upgrades/0f562410898f4d4afab2da91f5aaece660ebfa88/upgrade.properties
=> C#: Use entities in reorder directives

go/ql/lib/upgrades/b37faf5d62cccefad9fcfd8f5c026620097b2355/upgrade.properties
=> Go: Use entities in reorder directives

javascript/ql/lib/upgrades/9ca3692b65fd8d751431861d1a25c57f3e61d15b/upgrade.properties, javascript/ql/lib/upgrades/c73fbfca57f3d593b9ff50c6aa3a886d6888efec/upgrade.properties
=> JS: Use entities in reorder directives

python/ql/lib/upgrades/4f1806347d7fafe2f78508da01c01e5aff5f7cbb/upgrade.properties
=> Python: Use entities in reorder directives

java/ql/lib/semmle/code/java/dataflow/FlowSources.qll, java/ql/lib/semmle/code/java/frameworks/ApacheHttp.qll, java/ql/lib/semmle/code/java/frameworks/JAXB.qll, java/ql/lib/semmle/code/java/security/Encryption.qll, java/ql/lib/semmle/code/java/security/XSS.qll, java/ql/src/Likely Bugs/Concurrency/WaitOutsideLoop.ql, java/ql/src/Security/CWE/CWE-319/UseSSLSocketFactories.ql, java/ql/src/Security/CWE/CWE-676/PotentiallyDangerousFunction.ql, java/ql/src/experimental/Security/CWE/CWE-078/CommandInjectionRuntimeExec.qll, java/ql/src/experimental/Security/CWE/CWE-939/IncorrectURLVerification.ql
Just cleaning up some tech debt.
=> Java: Clean up some instances of getQualifiedName.

misc/bazel/internal/git_lfs_probe.py
This will fix external Codespaces tests failures related to lfs-probe
=> Make GITHUB_TOKEN in lfs_probe a fallback rather than an override

csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, java/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, java/ql/test/utils/modelgenerator/dataflow/p/AbstractImplOfExternalSPI.java, java/ql/test/utils/modelgenerator/dataflow/p/ImplOfExternalSPI.java, java/ql/test/utils/modelgenerator/dataflow/p/Inheritance.java, java/ql/test/utils/modelgenerator/dataflow/p/MultipleImpls.java
In this PR 
- The logic for *lifting* models is improved (further explanation can be seen below).
- Fix a small issue with sink model exclusions (these were wrongly excluded based on summarized callables and neutrals with summary kind).
- Do some minor re-factoring.
The idea with the lifting logic is to make models as general as possible.
Assume that `B <: A` (`B` is a subtype of `A` or `B` is an implementation of `A`) and assume that we have 
methods `B.M` and `A.M` where `B.M` is an override or implementation of `A.M`. In case the model generator finds a summary model `S` for `B.M` we *lift* the model to `A.M` (that is, we assume that `A.M` exhibits the same flow as `B.M` as this is perceived as a part of the override/implementation contract).
The old logic
- For lifting was dispersed …
=> Java: Improve finding best type for models and lifting.

java/ql/lib/upgrades/8ab354e68e86100ee3abe28bd44f491ecc77c1dd/upgrade.properties, java/ql/lib/upgrades/b4e689c90426b017ad550e30a439cab2763ff424/upgrade.properties
=> Java: Use entities in reorder directives

python/ql/lib/semmle/python/ApiGraphs.qll, python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModelsSpecific.qll, python/ql/test/library-tests/frameworks/data/test.expected, python/ql/test/library-tests/frameworks/data/test.py
This also adds a new member predicate to `API::Node`, but my intention is not to make changes to the interpretation of the API graph yet, although we do want to follow subclasses here also at some point.
=> Python: The MaD token `Instance` now follows subclasses

javascript/ql/src/Security/CWE-338/InsecureRandomness.qhelp, javascript/ql/src/Security/CWE-338/examples/InsecureRandomness_fixed.js
- `RandomSource` is not a thing anymore, and the MDN link made a 301 redirect to `Crypto` instead.  
- Added an example of how to get a floating point value between 0 and 1 with a cryptographically secure method.  
Fixes https://github.com/github/codeql/issues/16499
=> JS: Update the insecure-randomness QHelp

go/ql/lib/change-notes/2024-05-16-incorrect-integer-conversion-defined-types.md, go/ql/lib/semmle/go/security/IncorrectIntegerConversionLib.qll
A bug has been fixed which meant that the query `go/incorrect-integer-conversion` did not consider type assertions and type switches which use a defined type whose underlying type is an integer type. This may lead to fewer false positive alerts.
=> Go: make two barriers recognise named types whose underlying types are integer types

docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp-new.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-csharp.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-java.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-javascript-and-typescript.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-python.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-ruby.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-swift.rst, docs/codeql/codeql-language-guides/customizing-library-models-for-java-and-kotlin.rst, docs/codeql/codeql-language-guides/data-flow-cheat-sheet-for-javascript.rst, docs/codeql/codeql-language-guides/using-flow-labels-for-precise-data-flow-analysis.rst, docs/codeql/codeql-overview/codeql-glossary.rst, docs/codeql/conf.py, docs/codeql/contents.rst, docs/codeql/reusables/codespaces-template-note.rst, docs/codeql/reusables/setup-to-run-tutorials.rst, docs/codeql/writing-codeql-queries/about-codeql-queries.rst, docs/codeql/writing-codeql-queries/about-data-flow-analysis.rst, docs/codeql/writing-codeql-queries/creating-path-queries.rst, docs/codeql/writing-codeql-queries/debugging-data-flow-queries-using-partial-flow.rst, docs/codeql/writing-codeql-queries/introduction-to-ql.rst
This change should stop us building the CodeQL for VS Code docs as part of the docs publication for the CodeQL docs site. It's likely to delete the HTML files from the `codeql-docs` repository, but I've checked with Rachael and this won't have any impact on the redirects that we already have in place.
This change is worth doing so that, as we hand over more responsibility for the CodeQL docs site to the CodeQL team, there are fewer areas for confusion.
I'll test this PR by running a docs build and creating a test PR to update the CodeQL docs site.
- https://github.com/github/codeql-docs/pull/286/files?diff=split&w=1
- Preview: https://github-4d907a7910-15579910.drafts.github.io/docs/codeql-overview/
=> Stop building the CodeQL for VS Code docs now they've been migrated

python/ql/lib/semmle/python/Concepts.qll, python/ql/lib/semmle/python/dataflow/new/internal/TaintTrackingPrivate.qll, python/ql/lib/semmle/python/dataflow/new/internal/TaintTrackingPublic.qll, python/ql/test/experimental/query-tests/Security/CWE-091-XsltInjection/XsltInjection.expected, python/ql/test/library-tests/dataflow/summaries/summaries.expected, python/ql/test/query-tests/Security/CWE-020-ExternalAPIs/UntrustedDataToExternalAPI.expected, python/ql/test/query-tests/Security/CWE-943-NoSqlInjection/NoSqlInjection.expected
Taint steps can have a provenance string that shows up in path explanations. For steps added via the `AdditionalTaintStep` class, this string used to be hardcoded to `"AdditionalTaintStep"`. Now it is possible to overwrite this string.
=> Python: Allow provenance in additional taint steps

cpp/downgrades/19887dbd33327fb07d54251786e0cb2578539775/upgrade.properties, cpp/ql/lib/upgrades/ddd31fd02e51ad270bc9e6712708e5a5b6881518/upgrade.properties
=> C++: Use entities in reorder directives

swift/downgrades/15d0da3a76b9dbffb921ae6d585f8a8de8945a0b/upgrade.properties, swift/downgrades/5559b5a367524777b3f6ef3fc285ae81031ca1da/upgrade.properties, swift/downgrades/ba4171b90d0665b40e9e203bac9e3d4a0b2d03ec/upgrade.properties, swift/downgrades/f5a22f5168adfd7f308b5941c11852c925edd638/upgrade.properties, swift/downgrades/f6a8ee8a21fb596fa84261ddedb68c00d8457ef4/upgrade.properties, swift/ql/lib/upgrades/147e087e57e51b2eb41e75c9c97380d0e6c20ecb/upgrade.properties, swift/ql/lib/upgrades/62fc609c1ab6ae748ff51362ffa5c368ba834ddf/upgrade.properties, swift/ql/lib/upgrades/98a78b66651ad4eb35a8edf1642767c794909ea4/upgrade.properties, swift/ql/lib/upgrades/e646f9e0308ec7135c83c0fdf96896d2737a8013/upgrade.properties, swift/ql/lib/upgrades/f937d9e63094280b7ec0ef26c70310daad5c1f79/upgrade.properties
=> Swift: Use entities in reorder directives

cpp/ql/src/Critical/NotInitialised.ql, cpp/ql/src/change-notes/2024-05-19-avoid-reporting-static-variable.md, cpp/ql/test/query-tests/Critical/NotInitialised/NotInitialised.expected, cpp/ql/test/query-tests/Critical/NotInitialised/NotInitialised.qlref, cpp/ql/test/query-tests/Critical/NotInitialised/test.cpp
Static variables are initialized to zero or null by compiler, no need to get an initializer of them.
See https://stackoverflow.com/questions/13251083/the-initialization-of-static-variables-in-c
See 6.7.8/10 in the [C99 Standard](http://www.open-std.org/JTC1/sc22/wg14/www/docs/n1256.pdf)
=> C++: Static variables are initialized to zero or null by compiler

misc/bazel/internal/git_lfs_probe.py, misc/bazel/lfs.bzl
If the cache is prefilled, LFS rules were still trying to query for LFS urls.
Now the strategy is to first try to fetch the files from the repository cache (which is possible by providing an empty url list and `allow_fail` to `repository_ctx.download`), and only run the LFS protocol if that fails. Technically this is made possible by enhancing `git_lfs_probe.py` with a `--hash-only` flag.
This is also an optimization where no uneeded internet access is done (including the slightly slow SSH call) if the repository cache is warm.
Additionally, `-oStrictHostKeyChecking=accept-new` is now passed to the SSH call for LFS authentication. This makes a difference in the case the build is executed within a container on an already checked-out repository.
=> Bazel: allow LFS rules to use cached downloads without internet

javascript/ql/lib/change-notes/2024-05-09-sensitive-heuristics.md, javascript/ql/lib/semmle/javascript/security/internal/SensitiveDataHeuristics.qll, python/ql/lib/change-notes/2024-05-09-sensitive-heuristics.md, python/ql/lib/semmle/python/security/internal/SensitiveDataHeuristics.qll, python/ql/test/query-tests/Security/CWE-312-CleartextLogging/CleartextLogging.expected, python/ql/test/query-tests/Security/CWE-312-CleartextLogging/test.py, ruby/ql/lib/change-notes/2024-05-09-sensitive-heuristics.md, ruby/ql/lib/codeql/ruby/security/internal/SensitiveDataHeuristics.qll, swift/ql/lib/codeql/swift/security/SensitiveExprs.qll, swift/ql/lib/codeql/swift/security/internal/SensitiveDataHeuristics.qll
Adds a category of private information to the shared sensitive data heuristics file.
This may result in new results for the following queries: 
- `rb/sensitive-get-query`
- `py/clear-text-storage-sensitive-data`
- `py/clear-text-logging-sensitive-data`
- `py/weak-sensitive-data-hashing`
- `js/clear-text-stotage-sensitive-data`
- `js/clear-text-logging`
=> Ruby/Python/JS/Swift: Add category of Private information to shared sensitive data heuristics

ruby/downgrades/307ebf14d59930ba903d71d377f6f4129d0a6d22/upgrade.properties, ruby/downgrades/4ba51641799d2aaa315c7323931e2dd2a94c9f9d/upgrade.properties, ruby/downgrades/fabe9e179ed1e3d0e45ccfab6ce94b4bab02dee5/upgrade.properties, ruby/ql/lib/upgrades/09a494ce67d8141f28d6411f89b9ff7bdad440f3/upgrade.properties, ruby/ql/lib/upgrades/1199e154f5e9b3560297633c6ebb4dfe0b191ae4/upgrade.properties, ruby/ql/lib/upgrades/24d81950f3ab7e67e14553e1a5111a04e8ae8445/upgrade.properties, ruby/ql/lib/upgrades/3595c826de6db850f16b9da265a54dbf24dd3126/upgrade.properties, ruby/ql/lib/upgrades/40be81bc2086eb0368f33c770e0a84817bb340c3/upgrade.properties, ruby/ql/lib/upgrades/b5aef9c93ae64f848017d2dcb760eed916ab0cdd/upgrade.properties, ruby/ql/lib/upgrades/f765176af8e0a5128d2adb1ae9c5a6b1c8e7b20b/upgrade.properties
=> Ruby: Use entities in reorder directives

javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java, javascript/ql/lib/change-notes/2024-05-21-big-ts-files.md
Should fix: https://github.com/github/codeql/issues/13656 
I replicated the issue locally. We didn't exclude large files from the TypeScript extraction, only the plain JavaScript extraction.
=> JS: fix that very large TypeScript files would crash the extractor

csharp/BUILD.bazel, misc/bazel/csharp.bzl, misc/bazel/pkg.bzl
This uses a rule to combine `pkg_rules` targets with no overlap (with latest entries taking priority over earlier ones)
=> Bazel/C#: avoid zipmerge

java/ql/lib/semmle/code/java/security/ZipSlipQuery.qll, java/ql/src/change-notes/2024-05-22-zipslip-number-sanitizer.md
Adds the default type sanitizer to java/zipslip.
=> Java: Improve sanitizer for java/zipslip

python/extractor/tsg-python/Cargo.toml, ql/Cargo.lock, ql/buramu/tree-sitter-blame/Cargo.toml, ql/extractor/Cargo.toml, ql/ql/src/codeql_ql/StructuredLogs.qll, ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/ql.dbscheme, ql/rust-toolchain.toml, ruby/extractor/Cargo.lock, ruby/extractor/Cargo.toml, ruby/extractor/cargo-bazel-lock.json, ruby/extractor/rust-toolchain.toml, ruby/extractor/src/extractor.rs, ruby/ql/test/library-tests/frameworks/action_view/ActionView.expected, shared/tree-sitter-extractor/Cargo.toml, shared/tree-sitter-extractor/rust-toolchain.toml, shared/tree-sitter-extractor/src/extractor/mod.rs, shared/tree-sitter-extractor/src/extractor/simple.rs
This PR bumps our shared Tree-sitter extractor (and hence our Ruby and QL4QL extractors) to use the latest `tree-sitter` version.
=> Tree-sitter: Bump to 0.22.6

ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/test/query-tests/security/cwe-089/ActiveRecordInjection.rb, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected
See https://guides.rubyonrails.org/v2.3/active_record_querying.html#conditions
We previously assumed a string argument - but array arguments are only vulnerable if the first element is tainted.
=> Ruby: ActiveRecord - refine `conditions` argument as an SQLi sink

cpp/ql/src/experimental/Likely Bugs/DerefNullResult.cpp, cpp/ql/src/experimental/Likely Bugs/DerefNullResult.qhelp, cpp/ql/src/experimental/Likely Bugs/DerefNullResult.ql
Inspired by https://github.com/OISF/suricata/pull/11098
=> Adds another rule for null deref

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
`Config::allowImplicitRead(n, _)` is implied from `isImplicitReadNode(n, _)`.
=> Data flow: Remove two redundant conjuncts

csharp/ql/test/experimental/Security Features/CWE-759/HashWithoutSalt.expected, csharp/ql/test/query-tests/Security Features/CWE-209/ExceptionInformationExposure.expected, csharp/ql/test/query-tests/Security Features/CWE-338/InsecureRandomness.expected, ruby/ql/test/query-tests/experimental/CWE-522-DecompressionBombs/DecompressionBombs.expected, ruby/ql/test/query-tests/experimental/LdapInjection/Ldapinjection.expected, ruby/ql/test/query-tests/experimental/cwe-022-ZipSlip/ZipSlip.expected, ruby/ql/test/query-tests/experimental/cwe-176/UnicodeBypassValidation.expected, ruby/ql/test/query-tests/security/cwe-079/ReflectedXSS.expected, ruby/ql/test/query-tests/security/cwe-079/StoredXSS.expected, ruby/ql/test/query-tests/security/cwe-506/HardcodedDataInterpretedAsCode.expected, ruby/ql/test/query-tests/security/cwe-601/UrlRedirect.expected, ruby/ql/test/query-tests/security/cwe-798/HardcodedCredentials.expected, ruby/ql/test/query-tests/security/cwe-915/MassAssignment.expected, shared/dataflow/codeql/dataflow/DataFlow.qll, shared/dataflow/codeql/dataflow/TaintTracking.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, swift/ql/test/query-tests/Security/CWE-022/UnsafeUnpack/UnsafeUnpack.expected, swift/ql/test/query-tests/Security/CWE-094/UnsafeJsEval.expected, swift/ql/test/query-tests/Security/CWE-311/CleartextStorageDatabase.expected, swift/ql/test/query-tests/Security/CWE-311/CleartextTransmission.expected, swift/ql/test/query-tests/Security/CWE-312/CleartextStoragePreferences.expected
Follow-up for https://github.com/github/codeql/pull/15501
This adds provenance for the steps that are defined directly in the configuration.
=> Dataflow: Add provenance for configuration-specific steps.

cpp/ql/src/Security/CWE/CWE-416/UseOfUniquePointerAfterLifetimeEnds.ql, cpp/ql/src/change-notes/2024-05-22-use-of-unique-pointer-after-lifetime-ends-fp.md, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/UseOfUniquePtrAfterLifetimeEnds/UseOfUniquePointerAfterLifetimeEnds.expected, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/UseOfUniquePtrAfterLifetimeEnds/test.cpp
This fixed a FP that @geoffw0 spotted earlier
=> C++: Fix `cpp/use-of-unique-pointer-after-lifetime-ends` FP

cpp/ql/src/Likely Bugs/Memory Management/AllocaInLoop.ql
`this` wasn't bound in the predicate, so it ended up generating a CP.
(Looking at the DIL it does look like the compiler actually saved us and eliminated the CP, but we should probably be on the safe side and remove the CP anyway)
=> C++: Avoid a CP in `cpp/alloca-in-loop`

csharp/ql/src/experimental/Security Features/JsonWebTokenHandler/JsonWebTokenHandlerLib.qll, csharp/ql/src/experimental/Security Features/JsonWebTokenHandler/delegated-security-validations-always-return-true.ql
Generalized `CallableAlwaysReturnsTrue` for lambdas. Also removed `CallableAlwaysReturnsTrueHigherPrecision`, since the supposed extra `callableOnlyThrowsArgumentNullException(this)` condition is already imposed in `CallableAlwaysReturnsTrue`.
=> C#: Simplify logic in `JsonWebTokenHandlerLib.qll`

csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/Semmle.Autobuild.CSharp.csproj, csharp/autobuilder/Semmle.Autobuild.CSharp/StandaloneBuildRule.cs, csharp/autobuilder/Semmle.Autobuild.Shared/Autobuilder.cs, csharp/tools/tracing-config.lua
Invoke the buildless extractor directly in `--build-mode none` instead of through a process creation.
=> C#: Avoid process creation indirection in auto-builder

java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/dataflow/FlowSummary.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowDispatch.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, java/ql/src/utils/modeleditor/ModelEditor.qll, shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
This blocks source dispatch when we have an exact match from a manual model, thus improving analysis when analysing the db containing the source for a given manual model. I.e. this only affects projects for which there exists some number of manual models.
=> Java: Remove source dispatch when there's an exact match from a manual model.

java/ql/lib/semmle/code/java/dataflow/internal/DataFlowDispatch.qll
Before:
```
[2024-05-23 11:42:53] Evaluated non-recursive predicate DataFlowDispatch::viableImplInCallContext/2#80593438@6b3107v1 in 58322ms (size: 8133273).
Evaluated relational algebra for predicate DataFlowDispatch::viableImplInCallContext/2#80593438@6b3107v1 with tuple counts:
584084   ~4%    {3} r1 = JOIN `Expr::MethodCall.getMethod/0#dispred#41989dc9` WITH num#DataFlowPrivate::TCall#52d9e003 ON FIRST 1 OUTPUT Lhs.1, Lhs.0, Rhs.1
584084   ~0%    {2} r2 = JOIN r1 WITH `Member::Method.getSourceDeclaration/0#dispred#93e6cdf8` ON FIRST 1 OUTPUT Lhs.1, Lhs.2
22431   ~5%    {4}    | JOIN WITH `DataFlowDispatch::mayBenefitFromCallContext/3#b7976ae1` ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Lhs.1, Rhs.2
22431   ~3%    {4}    | JOIN WITH num#DataFlowPrivate::TSrcCallable#bc4053c4 ON FIRST 1 OUTPUT …
```
=> Java: Fix join-order in viableImplInCallContext.

docs/codeql/ql-language-reference/annotations.rst
Note that this is not a recent change, and the language specification has correctly stated this for at least 4 years in the [corresponding table](https://github.com/github/codeql/blob/c0d623c056c4491fad7711e949618629a6f23969/docs/codeql/ql-language-reference/ql-language-specification.rst?plain=1#L845-L849).
@kaspersv noted the need to fix this on [this PR](https://github.com/github/semmle-code/pull/50077#pullrequestreview-2074099312).
=> `monotonicAggregates` can apply to modules (see language spec)

java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, java/ql/src/utils/modelgenerator/internal/CaptureSummaryFlowQuery.qll, java/ql/test/utils/modelgenerator/dataflow/p/ImplOfExternalSPI.java, java/ql/test/utils/modelgenerator/dataflow/p/Inheritance.java, java/ql/test/utils/modelgenerator/dataflow/p/PrivateFlowViaPublicInterface.java
As neutrals do not have a concept of applying to all overrides, the models should not be lifted. Instead we should generate summary neutrals for all "relevant" (public) methods that don't have a summary model that applies to them.
=> Java: Do not lift neutrals in Model generation.

java/ql/lib/change-notes/2024-05-15-static-field-side-effect.md, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, java/ql/test/library-tests/dataflow/fields/G.java, java/ql/test/library-tests/dataflow/fields/flow.expected
Fixes https://github.com/github/codeql/issues/15972
=> Java: Add support for flow through side-effects on static fields.

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/TaintTrackingPrivate.qll, csharp/ql/src/Language Abuse/ForeachCapture.ql, csharp/ql/test/library-tests/dataflow/external-models/steps.ql
It turns out that the current logic for *dataflow* applied to summarized callables is inconsistent.
The following can happen:
If a callable in *source* is also considered a summarized callable because there exist a summary of a super implementation that apply to all overrides, then the source callable will not be included in `DataFlowSummarizedCallable`.
However, the callable will get summary nodes for the parameters and return, which will cause the `uniqueEnclosingCallable` test to fail (as there doesn't exist a corresponding `DataFlowSummarizedCallable` for the *parameter* and *return* summary nodes).
Instead of aligning the summary node and dataflow summarised callable implementation, it seems more consistent (and to ensure code cohesion) to move the exclusion logic to the adapter. …
=> C#: Make the flow summary filtering in the adapter.

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowDispatch.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/constant-size/ConstantSizeArrayOffByOne.expected, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/call-sensitivity/CallSensitivityFlow.expected, csharp/ql/test/library-tests/dataflow/global/DataFlowPath.expected, csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.expected, go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, java/ql/test/library-tests/dataflow/call-sensitivity/flow.expected, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, shared/dataflow/codeql/dataflow/DataFlow.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImplConsistency.qll, shared/util/codeql/util/internal/MakeSets.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
This replaces our call context representation with a set-based representation of the allowed call edges, thus unifying equivalent call contexts. This unification means that we avoid redundant computation when a callable is reachable with several different, but equivalent call contexts.
In some cases I've observed 3000 equivalent call contexts, which will now be replaced by a single entity, and in that particular case the total tuple count for the stage was cut in half.
Commit-by-commit review encouraged. The first commit introduces the `MakeSets` primitive, which is then used to collapse local call contexts. Then a sequence of refactoring commits follow. And finally, the "Dataflow: Switch call context to a set representation" commit contains the implementation of and switch to fully …
=> Dataflow: Implement call context grouping to improve performance

config/dbscheme-fragments.json, ql/ql/src/ql.dbscheme, ruby/downgrades/63af05c01bdd6a38f280e41ac0453db52f46989c/old.dbscheme, ruby/downgrades/63af05c01bdd6a38f280e41ac0453db52f46989c/ruby.dbscheme, ruby/downgrades/63af05c01bdd6a38f280e41ac0453db52f46989c/upgrade.properties, ruby/ql/lib/codeql/Locations.qll, ruby/ql/lib/ruby.dbscheme, ruby/ql/lib/upgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/empty_location.ql, ruby/ql/lib/upgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/old.dbscheme, ruby/ql/lib/upgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/ruby.dbscheme, ruby/ql/lib/upgrades/440de75c71e9206ce16eed49a22c76e7889b5fc3/upgrade.properties, shared/tree-sitter-extractor/src/extractor/mod.rs, shared/tree-sitter-extractor/src/generator/prefix.dbscheme
Makes a difference on really large DBs, where scanning the full `locations_default` relation can be expensive:
```
[2024-05-24 08:14:11] Evaluated non-recursive predicate locations_default_234501#join_rhs@25a852j3 in 1551288ms (size: 1803722310).
Evaluated relational algebra for predicate locations_default_234501#join_rhs@25a852j3 with tuple counts:
1803722310  ~0%    {6} r1 = SCAN locations_default OUTPUT In.2, In.3, In.4, In.5, In.0, In.1
return r1
```
=> Tree-sitter: Emit `empty_location` relation to avoid scan

cpp/ql/test/library-tests/padding/options
The padding test is the only test that currently depends on the contents of the `predefined_macros` file that we ship with CodeQL for use with the CodeQL tests. Explicitly specifying `__x86_64` makes the test independent of the contents of the file.
=> C++: Make the padding test independent of the `predefined_macros` file

cpp/ql/src/Security/CWE/CWE-131/NoSpaceForZeroTerminator.qhelp
This PR aims to improve the recommendations with the following changes:
- Replace segmentation fault with crash that is platform agnostic (I think segmentation fault is not really a thing on Windows).
- Replace security vulnerability with malicious code execution. This provides a range of issues, because a crash (previously segmentation fault) could also be considered a security vulnerability. Namely a DOS.
- Removed the additional note on stack allocated arrays which seem confusing because we are always talking about buffers allocated on the heap.
=> Rewrite recommendations for the query `cpp/no-space-for-terminator`

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureSummaryFlowQuery.qll, csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.ql, csharp/ql/test/utils/modelgenerator/dataflow/Summaries.cs
In this PR we align the C# model generator lifting and override logic with Java.
That is,
- Models are now lifted to the top base class within the source code. However, we exclude `Object` and `ValueType` as this causes issues when generating models for .NET runtime (as these class definitions are included in the .NET runtime source code).
- The extensible logic is changed; We now say that models should apply to all overrides with the exception of overrides of methods defined on `Object` and `ValueType` (as class or value type implicitly extend these).
Furthermore, we also make a small fix related to sink model discovery. We only want to exclude generation of these, if there exist a neutral sink model (and not a neutral summary model).
=> C#: Lift models.

java/ql/lib/semmle/code/java/security/SpringCsrfProtection.qll, java/ql/src/change-notes/2024-05-30-disabled-csrf-query.md, java/ql/test/query-tests/security/CWE-352/SpringCsrfProtectionTest.java, java/ql/test/stubs/springframework-5.3.8/org/springframework/security/config/web/server/ServerHttpSecurity.java
Improves the query [`java/spring-disabled-csrf-protection`](https://codeql.github.com/codeql-query-help/java/java-spring-disabled-csrf-protection/) reporting calls to [`ServerHttpSecurity.CsrfSpec::disable`](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/web/server/ServerHttpSecurity.CsrfSpec.html#disable())
=> Disable csrf for ServerHttpSecurity

misc/bazel/pkg.bzl
In order to build the language-independent parts of our dist with `pkg.bzl`, we need two override features:
* A way to set the prefix in the zip files to the empty string, so that our top-level files stay top-level.
* A way to put `codeql.exe` into the arch-specific zip, despite it not being under `CODEQL_PLATFORM`. This PR implements both.
=> `pkg.bzl`: Add features to support the nolang dist.

go/ql/lib/change-notes/2024-05-09-model-append-copy-max-min.md, go/ql/lib/semmle/go/frameworks/Stdlib.qll, go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalTaintStep.expected, go/ql/test/query-tests/Security/CWE-078/CommandInjection.expected, go/ql/test/query-tests/Security/CWE-327/UnsafeTLS.expected
These are needed when they are called with string arguments. This is a partial revert of https://github.com/github/codeql/pull/16413.
=> Go: Add back taint models for `append` and `copy`

java/ql/lib/change-notes/2024-05-23-typeflow-precision.md, java/ql/lib/semmle/code/java/dataflow/TypeFlow.qll, java/ql/test/library-tests/dispatch/ViableCallable.java
This improves TypeFlow to account for more argument-parameter pairs. Previously this was restricted to private callables, as we need to ensure that a proper closed-world assumption applies, since we're doing a universal flow calculation, but this can be extended to all callables that aren't implicitly public.
Improved TypeFlow means improved virtual dispatch, which ought to translate to more precise data flow.
=> Java: Improve dispatch through TypeFlow of effectively private calls.

csharp/ql/integration-tests/legacy, go/ql/integration-tests/legacy, java/ql/integration-tests/legacy, javascript/ql/integration-tests/legacy, ruby/ql/integration-tests/legacy, swift/ql/integration-tests/legacy
This is in preparation for the new integration test framework. Only tests marked thus will be run by the current framework and only tests not marked thus will be run by the new one.
No actual review is necessary from the language teams (well, there's also not much to review here :laughing:).
=> Mark all integration tests as legacy

misc/bazel/cmake/setup.cmake
This space breaks when upgrading bazelisk on Windows. Somehow, a space inside the argument messes up some argument-parsin somewhere. Porbably due to Windows argument parsing being not well-defined in how it splits a string into argv. Removing the space works around the problem.
If the space is included, cmake suddenly can't find the bazelisk binary anymore, despite happily executing `info output_base` earlier.
=> Cmake generator: Remove space in argument.

misc/bazel/internal/install.py, misc/bazel/pkg.bzl
First, the labels used in this file need to be wrapped in `Label`, so that we can use the installer target for `codeql_pack`'s that are defined in the internal repo. Second, when unpacking zips, the path passed to `ripunzip` included a trailing `\n`, which caused `ripunzip` to fail.
=> `pkg.bzl`: Fix install targets.

python/ql/lib/semmle/python/security/dataflow/ServerSideRequestForgeryQuery.qll
Fixes an error in the deprecation notice for a taint tracking configuration.
=> Python: Fixes an error in the deprecation notice for a taint tracking configuration

go/ql/lib/semmle/go/frameworks/stdlib/NetHttp.qll
`getSummaryInputOrOutputNode` was giving the summary component stack for arguments corresponding to variadic parameters. This will be a problem when the models for variadic functions are converted to models-as-data.
Note: this has no tests, but it has been extracted from https://github.com/github/codeql/pull/16592 where it was needed to fix some tests that failed after some models were converted to models-as-data. So I feel this is okay, as it will be tested by that PR.
=> Go: Fix bug in ResponseWriter for variadic MaD

ruby/extractor/src/extractor.rs, shared/tree-sitter-extractor/src/autobuilder.rs, shared/tree-sitter-extractor/src/extractor/mod.rs, shared/tree-sitter-extractor/src/extractor/simple.rs
1. Make sure that the auto-builder passes the verbosity defined in `CODEQL_VERBOSITY` into the `codeql database index-files` invocation.
2. Make sure that the verbosity applies to the shared logic in the `codeql-extractor` crate.
=> Tree-sitter: Verbosity fixes

python/ql/lib/semmle/python/Frameworks.qll, python/ql/lib/semmle/python/frameworks/Opml.qll, python/ql/src/change-notes/2024-05-27-opml-models.md
Adds models for https://pypi.org/project/opml
<details><summary>Source code</summary>
$ pip3 install opml
$ cat /usr/local/python/3.10.13/lib/python3.10/site-packages/opml/*.py
```python
import lxml.etree
class OutlineElement(object):
"""A single outline object."""
def __init__(self, root):
"""Initialize from the root <outline> node."""
self._root = root
def __getattr__(self, attr):
if attr in self._root.attrib:
return self._root.attrib[attr]
raise AttributeError()
@property
def _outlines(self):
"""Return the available sub-outline objects as a seqeunce."""
return [OutlineElement(n) for n in self._root.xpath('./outline')]
def __len__(self):
return len(self._outlines)
def __getitem__(self, index):
return self._outlines[index]
class Opml(object):
"""Python representation of an OPML file.""" …
```
=> Python: Add models for `opml`

python/ql/src/Security/CWE-601/UrlRedirect.qhelp, python/ql/src/Security/CWE-601/examples/redirect_good2.py
Fixes https://github.com/github/codeql/issues/16041
/cc @max-schaefer who originally created https://github.com/github/codeql/pull/15176
=> Python: Update url-redirect qhelp with `https:/example.com` handling

go/ql/lib/semmle/go/dataflow/internal/TaintTrackingUtil.qll, go/ql/lib/semmle/go/security/CleartextLogging.qll, go/ql/lib/semmle/go/security/OpenUrlRedirect.qll, go/ql/src/experimental/frameworks/DecompressionBombsCustomizations.qll, go/ql/test/experimental/CWE-522-DecompressionBombs/DecompressionBombs.expected, go/ql/test/library-tests/semmle/go/frameworks/Echo/OpenRedirect.expected, go/ql/test/query-tests/Security/CWE-312/CleartextLogging.expected, go/ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirect.expected
The duplication of flow steps in additional flow steps added by configs was highlighted by https://github.com/github/codeql/pull/16511 and the new test results were accepted in https://github.com/github/codeql/pull/16562. This PR fixes them, so we aren't specifying additional flow steps in configs which duplicate existing flow steps.
=> Go: remove flow step duplication in configs

cpp/ql/src/Security/CWE/CWE-676/DangerousFunctionOverflow.ql, cpp/ql/src/change-notes/2014-06-05-gets-parameter.md, cpp/ql/test/query-tests/Security/CWE/CWE-676/semmle/PotentiallyDangerousFunction/test.c, cpp/ql/test/query-tests/Security/CWE/CWE-676/semmle/PotentiallyDangerousFunction/test.cpp
This showed up while looking at some alerts.
=> C++: Ignore `gets`'es with incorrect parameter counts

java/ql/integration-tests/all-platforms/java/android-sample-kotlin-build-script-no-wrapper/test.expected, java/ql/integration-tests/all-platforms/java/android-sample-kotlin-build-script/test.expected, java/ql/integration-tests/all-platforms/java/android-sample-no-wrapper/test.expected, java/ql/integration-tests/all-platforms/java/android-sample-old-style-kotlin-build-script-no-wrapper/test.expected, java/ql/integration-tests/all-platforms/java/android-sample-old-style-kotlin-build-script/test.expected, java/ql/integration-tests/all-platforms/java/android-sample-old-style-no-wrapper/test.expected, java/ql/integration-tests/all-platforms/java/android-sample-old-style/test.expected, java/ql/integration-tests/all-platforms/java/android-sample/test.expected, java/ql/integration-tests/all-platforms/java/ant-sample/test.expected, java/ql/integration-tests/all-platforms/java/buildless-gradle-timeout/test.expected, java/ql/integration-tests/all-platforms/java/gradle-sample-kotlin-script/test.expected, java/ql/integration-tests/all-platforms/java/gradle-sample/test.expected, java/ql/integration-tests/all-platforms/java/java-web-jsp/test.expected, java/ql/integration-tests/all-platforms/java/maven-sample-extract-properties/test.expected, java/ql/integration-tests/all-platforms/java/maven-sample-large-xml-files/test.expected, java/ql/integration-tests/all-platforms/java/maven-sample-small-xml-files/test.expected, java/ql/integration-tests/all-platforms/java/maven-sample-xml-mode-all/test.expected, java/ql/integration-tests/all-platforms/java/maven-sample-xml-mode-byname/test.expected, java/ql/integration-tests/all-platforms/java/maven-sample-xml-mode-disabled/test.expected, java/ql/integration-tests/all-platforms/java/maven-sample-xml-mode-smart/test.expected, java/ql/integration-tests/all-platforms/java/partial-gradle-sample-without-gradle/test.expected, java/ql/integration-tests/all-platforms/java/partial-gradle-sample/test.expected, java/ql/integration-tests/all-platforms/kotlin/default-parameter-mad-flow/test.expected
This means the expected output is in the order that the new test driver creates it in, which means future diffs will be smaller.
=> Java integration tests: accept new output

cpp/ql/lib/semmle/code/cpp/dataflow/ExternalFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
Improve the QLDoc for `modelCoverage` in all languages to match the go version.
=> C/C#/Java/Swift: Cover all params in QLDoc of `modelCoverage`

javascript/BUILD.bazel
This was missing in https://github.com/github/codeql/pull/16656, so we couldn't actually delete the resources in the internal repo.
=> JS: Use `resources/tools` from external repo, not internal.

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedExpr.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp, cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected, cpp/ql/test/library-tests/ir/ir/PrintAST.expected, cpp/ql/test/library-tests/ir/ir/aliased_ir.expected, cpp/ql/test/library-tests/ir/ir/ir.cpp, cpp/ql/test/library-tests/ir/ir/raw_consistency.expected, cpp/ql/test/library-tests/ir/ir/raw_ir.expected
This PR does two things with the end goal of getting flow through this example:
```cpp
void test() {
unsigned long x = source();
double d = __builtin_bit_cast(double, x);
sink(d);
}
```
- First, we fix IR generation for builtins. We were not skipping children we could not translate, which caused the IR generation to fail since the first argument of `__builtin_bit_cast` is a `TypeName` which has no IR representation. This meant that `__builtin_bit_cast` had no operands in the IR (see the first commit which adds a test for this).
We could have added IR generation for `TypeName`s, but that would involve introducing another IR instruction which I didn't really feel like doing since we currently have no use-cases for doing anything with `TypeName`s in any queries.
- Second, we add flow through …
=> C++: Fix IR generation for builtins and add flow through `__builtin_bit_cast`

cpp/ql/lib/change-notes/2024-06-14-boost-asio.md, cpp/ql/lib/change-notes/2024-06-14-models-as-data-yml-extensions.md, cpp/ql/lib/ext/Boost.Asio.model.yml, cpp/ql/lib/ext/empty.model.yml, cpp/ql/lib/qlpack.yml, cpp/ql/lib/semmle/code/cpp/dataflow/ExternalFlow.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/ExternalFlowExtensions.qll, cpp/ql/test/library-tests/dataflow/external-models/asio_streams.cpp, cpp/ql/test/library-tests/dataflow/external-models/flow.expected, cpp/ql/test/library-tests/dataflow/external-models/flow.ext.yml, cpp/ql/test/library-tests/dataflow/external-models/flow.ql, cpp/ql/test/library-tests/dataflow/external-models/sinks.expected, cpp/ql/test/library-tests/dataflow/external-models/sinks.ext.yml, cpp/ql/test/library-tests/dataflow/external-models/sinks.ql, cpp/ql/test/library-tests/dataflow/external-models/sources.expected, cpp/ql/test/library-tests/dataflow/external-models/sources.ext.yml, cpp/ql/test/library-tests/dataflow/external-models/sources.ql, cpp/ql/test/library-tests/dataflow/external-models/steps.expected, cpp/ql/test/library-tests/dataflow/external-models/steps.ext.yml, cpp/ql/test/library-tests/dataflow/external-models/steps.ql, cpp/ql/test/library-tests/dataflow/external-models/test.cpp, cpp/ql/test/library-tests/dataflow/external-models/validatemodels.expected, cpp/ql/test/library-tests/dataflow/external-models/validatemodels.ql, cpp/ql/test/library-tests/dataflow/source-sink-tests/asio_streams.cpp, docs/codeql/codeql-language-guides/codeql-for-cpp.rst, docs/codeql/codeql-language-guides/customizing-library-models-for-cpp.rst, shared/mad/codeql/mad/ModelValidation.qll
Add support for extension models in C/C++, that is, defining source, sink and summary models in `.yml` files rather than by writing QL classes to contain them.
In addition to the changes, tests and documentation for this feature, I have added a partial model for the `Boost.Asio` network library (using extension models).  This was necessary in order to create verified examples for the documentation.  In addition, it adds a further layer of testing for the feature and a few new models for CPP.
=> C++: Support for extension models (.yml)

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/src/Likely Bugs/Memory Management/AllocaInLoop.ql, cpp/ql/test/library-tests/dataflow/dataflow-tests/BarrierGuard.cpp, cpp/ql/test/library-tests/dataflow/dataflow-tests/TestBase.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/localFlow-ir.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected, cpp/ql/test/library-tests/dataflow/fields/dataflow-consistency.expected, cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected, cpp/ql/test/library-tests/dataflow/fields/partial-definition-diff.expected, cpp/ql/test/library-tests/dataflow/fields/partial-definition-ir.expected, cpp/ql/test/library-tests/dataflow/fields/partial-definition.expected, cpp/ql/test/library-tests/dataflow/fields/path-flow.expected, cpp/ql/test/library-tests/dataflow/fields/simple.cpp
This is the C/C++ version of https://github.com/github/codeql/pull/15985. The strategy is completely identical to the Ruby version: create a new dataflow node branch for phi inputs, and modify dataflow so that we do `def -> phi input -> phi` instead of `def -> phi`. We then extend the barrier guard implementation so that it can put barriers on these new phi input nodes.
I've also done some cleanup along the way.
=> C++: Extend barrier guards to handle phi inputs

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/test/query-tests/Security Features/CWE-807/ConditionalBypass.expected, csharp/ql/test/query-tests/Security Features/CWE-807/ConditionalBypass.ql, csharp/ql/test/query-tests/Security Features/CWE-807/ConditionalBypass.qlref, go/ql/lib/semmle/go/dataflow/ExternalFlow.qll, go/ql/test/query-tests/Security/CWE-022/TaintedPath.expected, go/ql/test/query-tests/Security/CWE-022/TaintedPath.ql, go/ql/test/query-tests/Security/CWE-022/TaintedPath.qlref, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/test/query-tests/security/CWE-311/CWE-319/HttpsUrls.expected, java/ql/test/query-tests/security/CWE-311/CWE-319/HttpsUrls.ql, java/ql/test/query-tests/security/CWE-311/CWE-319/HttpsUrls.qlref, javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll, python/ql/lib/semmle/python/frameworks/data/internal/ApiGraphModels.qll, ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModels.qll, ruby/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.expected, ruby/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.ql, ruby/ql/test/query-tests/security/cwe-078/CommandInjection/CommandInjection.qlref, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/test/ProvenancePathGraph.qll
This adds the list of referenced models in a qltest and renumbers the MaD ids to get stable test output. Where applicable, I've updated one test per language to demonstrate the conversion.
=> Dataflow: Add support for pretty-printed alert provenance in tests

csharp/Directory.Build.props, csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BUILD.bazel, csharp/autobuilder/Semmle.Autobuild.CSharp/BUILD.bazel, csharp/autobuilder/Semmle.Autobuild.Cpp.Tests/BUILD.bazel, csharp/autobuilder/Semmle.Autobuild.Cpp/BUILD.bazel, csharp/autobuilder/Semmle.Autobuild.Shared/BUILD.bazel, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/BUILD.bazel, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/Properties/AssemblyInfo.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/Semmle.Extraction.CSharp.DependencyFetching.csproj, csharp/extractor/Semmle.Extraction.CSharp.DependencyStubGenerator/BUILD.bazel, csharp/extractor/Semmle.Extraction.CSharp.Driver/BUILD.bazel, csharp/extractor/Semmle.Extraction.CSharp.Standalone/BUILD.bazel, csharp/extractor/Semmle.Extraction.CSharp.StubGenerator/BUILD.bazel, csharp/extractor/Semmle.Extraction.CSharp.StubGenerator/Properties/AssemblyInfo.cs, csharp/extractor/Semmle.Extraction.CSharp.StubGenerator/Semmle.Extraction.CSharp.StubGenerator.csproj, csharp/extractor/Semmle.Extraction.CSharp.Util/BUILD.bazel, csharp/extractor/Semmle.Extraction.Tests/BUILD.bazel, csharp/extractor/Semmle.Extraction/BUILD.bazel, csharp/extractor/Semmle.Util.Tests/BUILD.bazel, csharp/extractor/Semmle.Util/BUILD.bazel, csharp/scripts/BUILD.bazel, csharp/scripts/gen-assembly-info.py, csharp/scripts/gen-git-assembly-info.py, misc/bazel/csharp.bzl
This PR cleans up the build configuration for C# projects:
- Removes the last `AssemblyInfo.cs` files and moves `InternalsVisibleToAttributes` to csproj files.
- Removes the corresponding `"Properties/*.cs"` source declarations from Bazel build scripts.
- Ensures that assembly description attributes are added to the output artefacts when they are built with Bazel.
=> C#: Add assembly attributes to assemblies built with Bazel

java/ql/lib/semmle/code/java/security/BrokenCryptoAlgorithmQuery.qll, java/ql/lib/semmle/code/java/security/Encryption.qll, java/ql/src/change-notes/2024-05-13-rsa-ecb-secure.md
This PR adds the ciphers `RSA/ECB/OAEPWithSHA-1AndMGF1Padding` and `RSA/ECB/OAEPWithSHA-256AndMGF1Padding` to the list of secure algorithms.
CodeQL flags the uses of these ciphers as risky/weak because it sees ECB in the cipher name and matches the regex from the `getInsecureAlgorithmRegex()` function.
The ciphers listed above are part of the Java Cryptographic Architecture and Java Security Standard, and after a quick google search it appears that none of the security providers operate RSA in the block mode. So ECB in the context of RSA is a misnomer.
I did omit the other algorithm `RSA/ECB/PKCS1Padding` as I believe PKCS1 padding is weaker compared to OAEP.
[List of supported ciphers from the Java Security API](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/javax/crypto/Cip …
=> Java: Add RSA/ECB/OEAP ciphers to the list of secure algorithms

cpp/ql/lib/change-notes/2024-10-06-builtin-expect.md, cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll, cpp/ql/test/library-tests/controlflow/guards/Guards.expected, cpp/ql/test/library-tests/controlflow/guards/GuardsCompare.expected, cpp/ql/test/library-tests/controlflow/guards/GuardsControl.expected, cpp/ql/test/library-tests/controlflow/guards/GuardsEnsure.expected, cpp/ql/test/library-tests/controlflow/guards/test.cpp
This PR extends the `IRGuards` library to support reasoning about expressions inside calls to the buildin operation `__builtin_expect`. This builtin is most often used to define macros such as:
```cpp
#define likely(expr) __builtin_expect(!!(expr), 1)
#define unlikely(expr) __builtin_expect(!!(expr), 0)
```
and used like:
```cpp
if(unlikely(p == NULL)) {
...
}
```
previously, the guards library wouldn't know about the semantics of `__builtin_expect`, and we'd only know that `__builtin_expect(!!(p == NULL), 0)` was true inside the true branch. However, after this PR we infer that `p == NULL` inside the true branch (and `p != NULL` inside the false branch).
=> C++: Support `__builtin_expect` in `IRGuards`

go/extractor/project/BUILD.bazel, go/extractor/project/project.go, go/extractor/project/project_test.go
Supercedes #16453 using an implementation based on the new `SemVer` type introduced by #16460 (which should be merged first).
**Context**
In Go 1.21, the Go team started making a distinction between _language_ and _toolchain_ versions. Historically, the Go version is declared with a `go` directive in a `go.mod` file, or a `go.work` file. Since Go 1.21, `go` directives are used to declare the _language_ version. A new `toolchain` directive may be used to explicitly declare the _toolchain_ version. For backwards compatibility, if there is no `toolchain` directive, the _language_ version is used as the _toolchain_ version. In the Go autobuilder, we have numerous places where we try to determine the "version" of Go that is in use, should be installed, etc. Here, we are mainly interested in …
=> Go: Use toolchain directives for version selection if available, and add tests (v2)

go/extractor/util/util.go
This PR improves the logging for stray Go source files to only log one line, rather than one for each stray source file (which can be a lot in repos that don't use Go modules).
=> Go: Only log one line for stray .go files

python/ql/lib/semmle/python/security/dataflow/ServerSideRequestForgeryCustomizations.qll, python/ql/src/change-notes/2024-06-04-ssrf-sanitizers.md, python/ql/test/query-tests/Security/CWE-918-ServerSideRequestForgery/full_partial_test.py
Closes https://github.com/github/codeql-team/issues/3024
Adds checks against the contents of a string (such as .isalnum; and regex matches) as barrier guards for SSRF.
=> Python: Add additional sanitizers to SSRF 

shared/ssa/codeql/ssa/Ssa.qll
C/C++ started using this predicate in https://github.com/github/codeql/pull/16677, and apparently there's a bad join order in the predicate.
Before:
```ql
[2024-06-12 15:21:44] (79s) Tuple counts for SsaInternals::lastRefRedefExt/6#638f2140/6@a7eef2qm after 1m19s:
14364       ~0%        {6} r1 = SCAN `SsaInternals::SsaImpl::lastRefRedefExtSameBlock/5#8f663a50` OUTPUT In.0 'def', In.1 'sv', In.2 'input', In.3 'i', In.2 'input', In.4 'next'
1102500     ~876%      {4} r2 = SCAN `project#SsaInternals::SsaImpl::SsaDefReaches::ssaDefRank/5#4a1106c1#4` OUTPUT In.3, In.0 'next', In.1 'sv', In.2
797000      ~1088%     {3}    | JOIN WITH SsaInternals::SsaImpl::SsaDefReaches::SsaDefExt#21906d4b ON FIRST 1 OUTPUT Lhs.3, Lhs.1 'next', Lhs.2 'sv'
9759567     ~2653%     {4} r3 = JOIN r2 WITH …
```
=> SSA: Fix bad join in `lastRefRedefExt`

java/ql/lib/change-notes/2024-06-17-ffbl-implicit-this.md, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll
This a bug fix, as we previously failed to recognize the second-level scopes of implicit instance accesses, e.g. implicit `this`.
The effect of this change should be that we prune more uncertain flow, and hopefully thereby improve performance and reduce FPs.
For a particular big project that I've tested locally, this reduced the number of stage 3 tuples by 16% from 164M to 137M.
=> Java: Calculate 2nd level scopes for implicit instance accesses.

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/src/utils/modeleditor/FrameworkModeEndpointsQuery.qll, shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
In this PR we add some shared classes for *neutrals*, *sources* and *sinks* and also add some adapters for Java and C# to populate the source and sink callable classes.
This PR is a pre-requisite for some model generator related work.
=> C#/Java: Add some (shared) helper classes for Neutrals, Sources and Sink

java/ql/lib/semmle/code/java/security/TaintedPermissionsCheckQuery.qll, java/ql/src/change-notes/2024-06-17-tainted-permissions-check.md
In this PR we opt-in the `java/tainted-permissions-check` to threat models.
Prior to this change, the query used both `remote` and `local` sources as input. Now the default is to use only `remote` sources (as this the threat models default). However, it is possible to enable `local` (or other) sources by enabling the relevant threat model.
Using MRVA on java top-100 for this query we get
- 1 result for remote flow sources.
- 3 results for remote + local flow sources.
DCA looks good; There are no changes to performance or alerts.
It seems that this query doesn't produce an overwhelming number of results in general.
=> Java: Opt-in `java/tainted-permissions-check` to threat models.

ruby/ql/lib/change-notes/2024-05-15-cleartext-sources.md, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/security/CleartextLoggingQuery.qll, ruby/ql/lib/codeql/ruby/security/CleartextStorageQuery.qll, ruby/ql/lib/codeql/ruby/security/internal/CleartextSources.qll, ruby/ql/test/query-tests/security/cwe-312/CleartextStorage.expected, ruby/ql/test/query-tests/security/cwe-312/app/controllers/users_controller.rb
Depends on https://github.com/github/codeql/pull/16446. 
This PR expands `CleartextSources.qll` to use additional sensitive data heuristics besides passwords. 
Additionally, the cleartext storage and cleartext logging queries allow implicit read steps at sinks. 
This finds new results in Railsgoat (https://github.com/github/codeql-team/issues/2367)
=> Ruby: Use additional sensitive data heuristics for CleartextSources

go/ql/lib/change-notes/2024-06-17-go-global-variable-writes.md, go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll, go/ql/test/experimental/CWE-1004/CookieWithoutHttpOnly.expected, go/ql/test/experimental/CWE-321-V2/HardCodedKeys.expected, go/ql/test/library-tests/semmle/go/dataflow/GlobalVariableSideEffects/globalVariable.go
Note flow via something like `sideEffect(&x)` is still broken. I think this is because we're lacking a store-step for `*x = source()`, which should result in `x` having taint with access path `[PointerContent]`. This might also involve address operations being able to read taint (i.e. to note that if `&x` is tainted with `[PointerContent]` then `x` is tainted without an access path), but I'm not sure -- in any event I don't address the matter here. I'd suggest tackling that issue by cribbing off C/C++, which has surely addressed (no pun intended) this exact issue.
=> Add support for flow through content of global variables

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.17.4.rst
Quick manual patch for the changelog of 2.17.4. 
Changes made on `semmle-code` : https://github.com/github/semmle-code/pull/50347 and 
`codeql-cli-binaries`: https://github.com/github/codeql-cli-binaries/pull/177 to make sure these changes properly show up when generating the change logs for the next release.
=> 2.17.4 Changelog patch

go/ql/lib/change-notes/2024-06-08-refactor-go-queries-to-use-threatmodelflowsource.md, go/ql/lib/semmle/go/security/CommandInjectionCustomizations.qll, go/ql/lib/semmle/go/security/ExternalAPIs.qll, go/ql/lib/semmle/go/security/LogInjectionCustomizations.qll, go/ql/lib/semmle/go/security/MissingJwtSignatureCheckCustomizations.qll, go/ql/lib/semmle/go/security/OpenUrlRedirectCustomizations.qll, go/ql/lib/semmle/go/security/ReflectedXssCustomizations.qll, go/ql/lib/semmle/go/security/RequestForgeryCustomizations.qll, go/ql/lib/semmle/go/security/SqlInjectionCustomizations.qll, go/ql/lib/semmle/go/security/TaintedPathCustomizations.qll, go/ql/lib/semmle/go/security/UncontrolledAllocationSizeCustomizations.qll, go/ql/lib/semmle/go/security/XPathInjectionCustomizations.qll, go/ql/src/Security/CWE-640/EmailInjectionCustomizations.qll, go/ql/src/experimental/CWE-090/LDAPInjection.qll, go/ql/src/experimental/CWE-203/Timing.ql, go/ql/src/experimental/CWE-287/ImproperLdapAuthCustomizations.qll, go/ql/src/experimental/CWE-369/DivideByZero.ql, go/ql/src/experimental/CWE-74/DsnInjection.ql, go/ql/src/experimental/CWE-79/HTMLTemplateEscapingPassthrough.ql, go/ql/src/experimental/CWE-807/SensitiveConditionBypass.qll, go/ql/src/experimental/CWE-840/ConditionalBypass.ql, go/ql/src/experimental/CWE-918/SSRF.qll, go/ql/src/experimental/CWE-942/CorsMisconfiguration.ql, go/ql/src/experimental/frameworks/DecompressionBombs.qll
Follow up of #16697. This refactors queries to use `ThreatModelFlowSource` instead of `RemoteFlowSource` in their definitions of `isSource`.
Since the Go libraries currently do not have any local sources as far as I can tell, this should not be a breaking change.
> [!NOTE]
> Since this PR is based on #16697, the appropriate commit range to review is: https://github.com/github/codeql/pull/16709/files/03aa05c8c19cd9b396a51ee29307aea7c9aaab69..b4d4f8268f123045d5cb46723a883e6e788f082c
=> Go: Refactor queries to use `ThreatModelFlowSource` instead of `RemoteFlowSource`

javascript/ql/lib/change-notes/2024-06-14-type-tracking-array-steps.md, javascript/ql/lib/semmle/javascript/Arrays.qll, javascript/ql/test/library-tests/Arrays/DataFlow.expected, javascript/ql/test/library-tests/Arrays/TaintFlow.expected, javascript/ql/test/library-tests/Arrays/arrays.js, javascript/ql/test/library-tests/Arrays/printAst.expected, javascript/ql/test/library-tests/frameworks/Collections/test.expected, javascript/ql/test/library-tests/frameworks/Collections/tst.js
I also spotted a mistake in Array.splice modeling, so I also fixed it up.
I think the big question is whether we actually _want_ to have these steps part of normal type-tracking; by allowing read of array elements at _any_ position, we might not handle examples like the one below precisely (and think the call `f()` could target any of the 3 functions)
```js
const fns = [f1, f2 ,f3];
const f = fns[0];
f();
```
_note: I didn't actually test this out, just thinking out loud_
=> JS: Allow many Array steps to be used in type-tracking

javascript/extractor/src/com/semmle/jcorn/Identifiers.java
This doesn't make a difference in practice because we only run the method on arrays of even length, but we might as well fix it.
=> JavaScript: Fix CodeQL alert in extractor

ruby/ql/lib/codeql/ruby/frameworks/Sinatra.qll, ruby/ql/test/library-tests/frameworks/sinatra/Flow.expected, ruby/ql/test/library-tests/frameworks/sinatra/Flow.ql, ruby/ql/test/library-tests/frameworks/sinatra/Sinatra.expected
Fixes a type incompatibility identified by @aschackmull  on https://github.com/github/codeql/pull/16785.
=> Ruby: Rework `Sinatra.FilterJumpStep`

go/ql/lib/semmle/go/Packages.qll
In all the databases I've looked in, some of the packages start with "vendor/", followed by what appears to be a sensible package path. The existing code to remove "vendor/" accidentally matches for "/vendor/", so it isn't removing it. This PR fixes that bug.
=> Go: Fix bug removing "vendor/" from package paths

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ExprNodes.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/TestBase.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
When a temporary is materialized we special-case `asExpr` to assign the correct node for which `asExpr()` should have a result. For example, consider this example:
```cpp
struct A {
void f();
};
void test() {
A().f();
}
```
which generates the following (simplified) IR:
```cpp
r6_1(glval<A>)       = VariableAddress[#temp6:5]  :
r6_5(glval<unknown>) = FunctionAddress[f]         :
v6_6(void)           = Call[f]                    : func:r6_5, this:r6_1
r4_1(glval<unknown>) = FunctionAddress[sink]      :
r4_2(glval<int>)     = VariableAddress[#temp4:10] :
r4_3(int)            = Constant[42]               :
m4_4(int)            = Store[#temp4:10]           : &:r4_2, r4_3
m4_5(unknown)        = Chi                        : total:m3_4, partial:m4_4
r4_6(int &)          = CopyValue …
```
=> C++: Fix missing `asExpr` for temporary materializations with conversions

csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/test/utils/modelgenerator/dataflow/CaptureSinkModels.ext.yml, csharp/ql/test/utils/modelgenerator/dataflow/Sinks.cs, csharp/ql/test/utils/modelgenerator/dataflow/Sources.cs, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, java/ql/test/utils/modelgenerator/dataflow/CaptureSourceModels.ext.yml, java/ql/test/utils/modelgenerator/dataflow/p/Sinks.java, java/ql/test/utils/modelgenerator/dataflow/p/Sources.java
In this PR we restrict the source and sink model generation for C# and Java: If a value passes through an irrelevant type we consider the value sanitised (we do the same for summary model generation).
Furthermore, for C# we also severely limit the source model extrapolation and require that sources only propagate upwards in the call stack based on a unique callable path (to avoid unwanted virtual dispatch).
=> C#/Java: Introduce source and sink model generation sanitisers.

go/ql/lib/semmle/go/Scopes.qll, go/ql/lib/semmle/go/frameworks/BeegoOrm.qll, go/ql/lib/semmle/go/frameworks/Logrus.qll, go/ql/lib/semmle/go/frameworks/stdlib/Fmt.qll, go/ql/lib/semmle/go/frameworks/stdlib/HtmlTemplate.qll, go/ql/lib/semmle/go/frameworks/stdlib/Log.qll
The first commits just formats a comment correctly.
The second commit writes out some function names in full rather than trying to uses string matching or string concatenation to save space. You can search the repo for "Fprintf" and find references to it easily.
The third commit fixes `getQualifiedName` for built-in functions so it gives `panic` instead of `.panic`. It's only very recently that `hasQualifiedName`, and hence `getQualifiedName`, have been defined for built-in functions, so this is a small clean up to make sure that the output is correct.
=> Go: a few small clean ups

config/identical-files.json, csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/src/utils/modelconverter/InterpretModel.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsPrinting.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureSummaryFlowQuery.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsPrinting.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, java/ql/src/utils/modelgenerator/internal/CaptureSummaryFlowQuery.qll, java/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, shared/mad/codeql/mad/modelgenerator/ModelPrinting.qll
In this PR we convert the model printing module from a pyrameterized module into a parameterized module.
This avoids syncing at least one part of the model generator implementation.
=> C#/Java: Parameterized module for model printing.

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, shared/dataflow/codeql/dataflow/DataFlow.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
It appears that most of the benefit from type pruning in stage 3 is closely correlated to the `Content` that's tracked in the access path. This means that we can drop flow-sensitive type pruning, which removes the risk for type-based fanout and consequent performance problems, by replacing it with a flow-insensitive type pruning that merely compares the tracked `Content` and the type of the current node with the possible container types given by the set of store steps.
So far this PR only changes stage 3. How this can impact subsequent changes still needs to be investigated. But this change alone appears to benefit performance - in particular on large databases.
=> Dataflow: Replace stage 3 type pruning with flow-insensitive type pruning.

go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
This workaround is no longer needed.
=> Go: Make DataFlowType a singleton (remove workaround)

cpp/ql/src/Security/CWE/CWE-570/IncorrectAllocationErrorHandling.ql, cpp/ql/test/query-tests/Security/CWE/CWE-570/IncorrectAllocationErrorHandling.expected
We can use the newly added unary version of `GuardCondition.comparesEq` to avoid handling the two cases separately.
In order to not produce duplicated results I had to pick some arbitrary ordering to not flag up both `!p` and `p` in the alert message. Picking the "smallest" one produces the given results. We could also have picked the "largest" one which would've kept the alert message as it is on main, but I feel like `guard = max(GuardCondition gc, ...)` looked weird 😂 Additionally, I do think it's more user-friendly to flag up the outermost expression in the condition.
=> C++: Simplify `cpp/incorrect-allocation-error-handling`

shared/dataflow/codeql/dataflow/VariableCapture.qll
Only has an effect for debugging purposes
=> Shared: add location for 'this' CaptureContainer

docs/codeql/codeql-language-guides/codeql-for-python.rst, docs/codeql/codeql-language-guides/customizing-library-models-for-python.rst, python/ql/lib/change-notes/2024-06-24-Data-extensions-supported-by-queries-and-documented.md, python/ql/lib/semmle/python/frameworks/Fabric.qll, python/ql/lib/semmle/python/security/dataflow/CodeInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/CommandInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/LogInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/UnsafeDeserializationCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/UrlRedirectCustomizations.qll, python/ql/test/library-tests/dataflow/model-summaries/InlineTaintTest.ext.yml, python/ql/test/library-tests/dataflow/model-summaries/NormalDataflowTest.ext.yml, python/ql/test/library-tests/dataflow/model-summaries/model_summaries.py, python/ql/test/library-tests/frameworks/fabric/fabric_v1_test.py
Adds documentation for the Python Models as Data format. The structure is heavily based on the JavaScript documentation. Both because that document is quite nice and because it will be easier for users to navigate if the structure is similar.
In addition, this PR
- adds a few tests reflecting the documentation
- make the mentioned sink-kinds have an effect on relevant queries
=> python: Document MaD format

csharp/ql/src/utils/modelgenerator/CaptureNeutralModels.ql, csharp/ql/src/utils/modelgenerator/CaptureSinkModels.ql, csharp/ql/src/utils/modelgenerator/CaptureSourceModels.ql, csharp/ql/src/utils/modelgenerator/CaptureSummaryModels.ql, csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureSummaryFlowQuery.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, csharp/ql/test/utils/modelgenerator/dataflow/CaptureSinkModels.ext.yml, csharp/ql/test/utils/modelgenerator/dataflow/CaptureSourceModels.ext.yml, csharp/ql/test/utils/modelgenerator/dataflow/Sinks.cs, csharp/ql/test/utils/modelgenerator/dataflow/Sources.cs, java/ql/src/utils/modelgenerator/CaptureNeutralModels.ql, java/ql/src/utils/modelgenerator/CaptureSinkModels.ql, java/ql/src/utils/modelgenerator/CaptureSourceModels.ql, java/ql/src/utils/modelgenerator/CaptureSummaryModels.ql, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, java/ql/src/utils/modelgenerator/internal/CaptureSummaryFlowQuery.qll, java/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, java/ql/test/utils/modelgenerator/dataflow/CaptureSinkModels.ext.yml, java/ql/test/utils/modelgenerator/dataflow/CaptureSourceModels.ext.yml, java/ql/test/utils/modelgenerator/dataflow/p/Sinks.java, java/ql/test/utils/modelgenerator/dataflow/p/Sources.java
In this PR we create separate classes of callables to be used by the dataflow configurations for the *source*, *sink* and *summary* callable target classes for model generation. Furthermore, we
- Ensure that *source* and *sink* models are not generated in case there exist a corresponding manual neutral or manual source/sink.
- Enable all source *kinds* for the C# source model generator.
IMO we should also avoid lifting sources or sinks the same way we do for summaries due to the following reason (this will also become easier to implement with the different classes for summary, source and sink callables): Contrary to summaries - sources and sinks have more granular kinds. As an example, we could imagine an interface or abstract class for writing to a *stream*. Depending on the …
=> C#/Java: Respect manual neutrals, sources and sinks in model generation.

docs/codeql/codeql-overview/system-requirements.rst
Note that a `java` binary is at least highly recommended for Java extraction, and in many circumstances a hard requirement. The same goes for `mvn` and `gradle`.
=> Java: document extraction system requirements

java/ql/src/Metrics/Summaries/LinesOfCodeJava.ql, java/ql/src/Metrics/Summaries/LinesOfCodeKotlin.ql
This brings them into line with LinesOfCode.ql
=> Java/Kotlin: Tag the LoC queries 'debug'

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
This adds a module `Debug` available in a data flow module resulting from the application of `Global<..>` to a configuration. The `Debug` module contains references to the individual stages, which in turn contain a `Graph` module with a `query edges` predicate and a `query subpaths` predicate. The associated PathNode type also contains convenience predicate for picking out sources and sinks, and additionally arbitrary-source and arbitrary-sink in case there's an abundance of flow and one just wants to see some representative examples.
=> Dataflow: Add path-problem view of intermediate stages for debug purposes.

csharp/autobuilder/Semmle.Autobuild.CSharp/DotNetRule.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/Program.cs, csharp/autobuilder/Semmle.Autobuild.Cpp/Program.cs, csharp/autobuilder/Semmle.Autobuild.Shared/MsBuildRule.cs, csharp/autobuilder/Semmle.Autobuild.Shared/Project.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/AssemblyInfo.cs, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Extractor.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Destructor.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/OrdinaryMethod.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/Analyser.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/Extractor.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/TracingAnalyser.cs, csharp/extractor/Semmle.Extraction/Context.cs, csharp/extractor/Semmle.Extraction/Extractor/ExtractionContext.cs, csharp/extractor/Semmle.Extraction/TrapWriter.cs, csharp/extractor/Semmle.Util/Logging/ILogger.cs, csharp/extractor/Testrunner/Testrunner.cs
This pull request replaces the old `string.Format` method calls with the newer, more readable and more performant string interpolation syntax. Additionally, the `Logger.Log` method calls are replaced with more specific logging methods like `LogError` or `LogInfo`.
=> C#: Change `string.Format` calls to interpolated strings

docs/codeql/reusables/supported-versions-compilers.rst, javascript/extractor/lib/typescript/package-lock.json, javascript/extractor/lib/typescript/package.json, javascript/ql/lib/change-notes/2024-04-26-typescript-5-5.md, javascript/ql/test/library-tests/TypeScript/Types/printAst.expected, javascript/ql/test/library-tests/TypeScript/Types/tests.expected, javascript/ql/test/library-tests/TypeScript/Types/tst.ts
A very uneventful upgrade. 
TypeScript 5.5 doesn't really add anything significant for us, and it didn't break any of our existing code.  
See the release announcement: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/ 
Evaluations look good. 
There are some new good call-edges, which is nice, but I'm not sure why they appeared.
=> JS: upgrade TypeScript to 5.5

go/documentation/library-coverage/frameworks.csv
Add Go JOSE to library coverage frameworks, so it doesn't just get lumped in the "other" category. The actual output files will be automatically updated after this is merged, so no need to do it in this PR. (It took me three goes to get the format right 😆 .)
Introduced in https://github.com/github/codeql/pull/15585.
=> Go: Add Go JOSE to library coverage frameworks

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll
A case of bad magic. Rather than evaluating separately whether a class has a method of some name, the compiler opted to magick in the fact that this was done as part of the `findFunctionAccordingToMro` predicate. Hilarity ensued.
However, _we_ know that magic really isn't needed in this case (the number of results is bounded by `Class.getAMethod` since methods have only a single name), so by factoring it out into a helper predicate, we can help the join-orderer along.
Before
```
(377s) Starting to evaluate predicate _DataFlowDispatch::findFunctionAccordingToMro/2#a610c0a3#prev_DataFlowDispatch::getNextClassInMro/1#__#shared/3@i6#L3#f893bw2h (iteration 6)
(377s) Tuple counts for _DataFlowDispatch::findFunctionAccordingToMro/2#a610c0a3#prev_DataFlowDispatch::getNextClassInMro/1#__#shared/3@i …
```
=> Python: Fix bad join in `DataFlowDispatch`

python/ql/src/Security/CWE-798/HardcodedCredentials.ql, python/ql/src/change-notes/2024-06-28-cred-hardcoded.md
Adding in support for Hardcoded Credentials sinks as Models as Data Extensions.
This should match the spec defined in the MaD Shared library:
https://github.com/github/codeql/blob/main/shared/mad/codeql/mad/ModelValidation.qll#L51
My goal is to make it easier for us to add Hardcoded Credential sinks as Models as Data for frameworks / libraries such as Database Controllers, etc.
=> Python: Add Hardcoded Credentials MaD support

csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, csharp/ql/test/utils/modelgenerator/dataflow/CaptureSinkModels.ext.yml, csharp/ql/test/utils/modelgenerator/dataflow/CaptureSourceModels.ext.yml, csharp/ql/test/utils/modelgenerator/dataflow/Sinks.cs, csharp/ql/test/utils/modelgenerator/dataflow/Sources.cs, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, java/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, java/ql/test/utils/modelgenerator/dataflow/CaptureSinkModels.ext.yml, java/ql/test/utils/modelgenerator/dataflow/CaptureSourceModels.ext.yml, java/ql/test/utils/modelgenerator/dataflow/p/ImplOfExternalSPI.java, java/ql/test/utils/modelgenerator/dataflow/p/PrivateFlowViaPublicInterface.java, java/ql/test/utils/modelgenerator/dataflow/p/Sinks.java, java/ql/test/utils/modelgenerator/dataflow/p/Sources.java, shared/mad/codeql/mad/modelgenerator/ModelPrinting.qll
In this PR we re-write the model generator to lift sources and sinks due to the following reason:
Contrary to summaries - sources and sinks have more granular kinds. As an example, we could imagine an interface or abstract class for writing to a stream. Depending on the implementation the stream writer could write to maybe the console, a file, a database, a log, etc. which could all be of different kinds (of sinks). That is, if we are lifting sinks we would then get a union of these kinds and the prototype implementation would become a "universal" sink. A similar argument can be applied for sources.
=> C#/Java: Do not lift source and sink models.

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected, ruby/ql/test/library-tests/dataflow/local/TaintStep.expected
The exposed local flow step relation (which is seldomly used) was missing flow steps from reads into [phi-input nodes](https://github.com/github/codeql/pull/15985).
=> Ruby: Add missing local flow steps

cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll
This was causing some confusion [here](https://github.com/github/codeql/discussions/16890).
Support for `switch` statements was added in https://github.com/github/codeql/pull/15941.
=> C++: Update QLDoc on `GuardCondition`

python/ql/lib/semmle/python/frameworks/internal/PoorMansFunctionResolution.qll
On a certain database, the evaluator was spending 17 seconds on a single iteration, which is usually a bad sign.
Looking more closely, we find the following culprit:
```
(621s) Tuple counts for PoorMansFunctionResolution::poorMansFunctionTracker/2#75430e01/3@i1#fb44303q after 17.8s:
79429084 ~0%     {3} r1 = JOIN `TypeTrackingImpl::TypeTracker.start/0#dispred#f8047cd1` WITH `DataFlowPublic::Node.asExpr/0#dispred#2845197a` CARTESIAN PRODUCT OUTPUT Rhs.0, Lhs.0 't', Rhs.1
59018875 ~7%     {3}    | JOIN WITH LocalSources::LocalSourceNode#2491029a ON FIRST 1 OUTPUT Lhs.2, Lhs.1 't', Lhs.0 'result'
7929     ~1%     {3}    | JOIN WITH `PoorMansFunctionResolution::lastDecoratorCall/1#152a5a8f_10#join_rhs` ON FIRST 1 OUTPUT Lhs.1 't', Rhs.1 'func', Lhs.2 'result'
277654   ~5%     {3} r2 = JOIN …
```
=> Python: Fix bad join in function resolution

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll, csharp/ql/lib/semmle/code/cil/Ssa.qll, csharp/ql/lib/semmle/code/cil/internal/SsaImpl.qll, csharp/ql/lib/semmle/code/csharp/controlflow/internal/PreSsa.qll, csharp/ql/lib/semmle/code/csharp/dataflow/SSA.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/BaseSSA.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, python/ql/lib/semmle/python/dataflow/new/internal/VariableCapture.qll, ruby/ql/lib/codeql/ruby/dataflow/SSA.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll, shared/dataflow/codeql/dataflow/VariableCapture.qll, shared/ssa/codeql/ssa/Ssa.qll, swift/ql/lib/codeql/swift/dataflow/Ssa.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
In preparation for https://github.com/github/codeql/pull/16884.
=> SSA: Add `BasicBlock.{getNode/1,length/0}` to the input signature

csharp/extractor/Semmle.Extraction.Tests/FilePathFilter.cs, csharp/extractor/Semmle.Extraction.Tests/FilePattern.cs, csharp/extractor/Semmle.Extraction/FilePattern.cs
This PR adjusts the path include/exclude logic to allow `**/` to match an empty string. This means that `**/src/` will match the content of the `src` folder in the root of the repository, while previously it only matched `src` folders in subdirectories.
=> C#: Fix glob pattern processing: allow `**/` to match empty string

javascript/extractor/src/com/semmle/js/extractor/Main.java
It always returns true nowadays.
=> JS: Remove call to shouldExtract

python/ql/lib/modeling/Util.qll
Currently, the model editor query for Python includes a lot of endpoints that are irrelevant for modeling because they are part of the tests of the package that is being modeled. For example, for `django/django` [this file](https://github.com/django/django/blob/f302343380c77e1eb5dab3b64dd70895a95926ca/tests/auth_tests/client.py) is included, which is irrelevant for modeling. Therefore, this PR introduces [the same mechanism that is used in Ruby](https://github.com/github/codeql/blob/779795b4213d8c8d7d1b24548fe5dbd7111411a4/ruby/ql/src/queries/modeling/internal/Util.qll#L8-L15) for excluding endpoints in files which are probably part of the package's tests.
=> Python: Exclude probable test files in model editor

java/kotlin-extractor/dev/.gitignore, java/kotlin-extractor/dev/wrapper.py
Also removed the version check step, as a version not existing will give a 404 any way later on, and that was adding a delay.
The cache is stored in a `.kotlinc_zips` and will be cleaned up by `--clear`.
Closes https://github.com/github/code-scanning-internal-dx-team/issues/694
=> Kotlin: make wrapper cache downloaded zips

go/ql/lib/change-notes/2024-07-08-fix-clear-sanitizer.md, go/ql/lib/semmle/go/dataflow/internal/TaintTrackingUtil.qll, go/ql/test/library-tests/semmle/go/dataflow/DefaultTaintSanitizer/Builtin.go, go/ql/test/library-tests/semmle/go/dataflow/DefaultTaintSanitizer/DefaultSanitizer.expected
There was a bug which meant that the built-in function `clear` was considered as a sanitizer in some cases when it shouldn't have been. This has now been fixed, which may lead to more alerts.
=> Go: fix `clear` sanitizer

misc/bazel/internal/install.py
Windows might need some retrying around deleting
the target directory.
=> Install script: Windows-compatible cleanup path.

cpp/ql/test/query-tests/Likely Bugs/Memory Management/SuspiciousCallToStrncat/SuspiciousCallToStrncat.expected, cpp/ql/test/query-tests/Likely Bugs/Memory Management/SuspiciousCallToStrncat/test.c
The size arguments here are actually off-by-one, but these calls won't overflow the buffer since the string constants are sufficiently small. So _technically_ these are FPs.
=> C++: Add 'cpp/unsafe-strncat' FPs

cpp/ql/src/Likely Bugs/Memory Management/SuspiciousCallToStrncat.ql, cpp/ql/src/change-notes/2024-07-08-unsafe-strncat-query.md
The query produces excellent results on MRVA 🎉 (see the backlink for analysis of the results).
=> C++: Promote `cpp/unsafe-strncat` to Code Scanning

shared/ssa/codeql/ssa/Ssa.qll
This PR adds a new module, `DataFlowIntegration`, to the shared SSA library, which makes it much easier to integrate SSA into the shared data flow library. The integration layer gives you all the relevant flow steps (such as use-use), but also gives you [phi-reads](https://github.com/github/codeql/pull/11198) and [phi-input barriers](https://github.com/github/codeql/pull/15985) without having to worry about how they are implemented.
The interface is inspired by the [variable capture library](https://github.com/github/codeql/blob/main/shared/dataflow/codeql/dataflow/VariableCapture.qll), meaning that we construct a `Node` type where some branches should map to existing branches in the `DataFlow::Node` type, while the `SsaNode` sub class should be added as a new branch to `DataFlow::Node`. …
=> SSA: Add data flow integration layer

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FileProvider.cs
This is an attempt to make buildless extraction deterministic. 
I've seen alert wobble in the following scenario: there are multiple source files in the repo with global statements, Roslyn chooses (hopefully by the syntax tree order in the compilation) one of the files to contain the generated `<Main>$`, in the other files the global statements are not extracted.
=> C#: Order files in buildless extraction

csharp/ql/lib/semmle/code/csharp/Location.qll, csharp/ql/lib/semmle/code/csharp/security/xml/InsecureXMLQuery.qll
Needed in preparation for https://github.com/github/codeql/pull/16817.
=> C#: Perform fewer `regexpCapture`s when matching version numbers

go/extractor/extractor.go, go/ql/integration-tests/all-platforms/go/extract-vendor/build-environment.expected, go/ql/integration-tests/all-platforms/go/extract-vendor/diagnostics.expected, go/ql/integration-tests/all-platforms/go/extract-vendor/force_sequential_test_execution, go/ql/integration-tests/all-platforms/go/extract-vendor/src/go.mod, go/ql/integration-tests/all-platforms/go/extract-vendor/src/go.sum, go/ql/integration-tests/all-platforms/go/extract-vendor/src/test.go, go/ql/integration-tests/all-platforms/go/extract-vendor/src/vendor/example.com/test/add.go, go/ql/integration-tests/all-platforms/go/extract-vendor/src/vendor/modules.txt, go/ql/integration-tests/all-platforms/go/extract-vendor/test.expected, go/ql/integration-tests/all-platforms/go/extract-vendor/test.py, go/ql/integration-tests/all-platforms/go/extract-vendor/test.ql
This PR introduces a new environment variable `CODEQL_EXTRACTOR_GO_EXTRACT_VENDOR_DIRS` which, if set to `true`, includes `vendor` directories in the extraction. I have also added an integration test to verify that a `vendor` directory is included in the extraction with this environment variable set to true. Specifically, `test.expected` does not contain `src/vendor/example.com/test/add.go` if `CODEQL_EXTRACTOR_GO_EXTRACT_VENDOR_DIRS` is not `true` or with an old version of the extractor.
=> Go: Add environment variable to include `vendor` directories in extraction

.github/workflows/compile-queries.yml
CLI v2.18.0 is released, so we can remove the workaround for `DatabaseQualityDiagnostics.ql` in the `compile-queries.yml` workflow.
=> Remove CI workaround for `DatabaseQualityDiagnostics.ql`

python/ql/src/experimental/Security/CWE-094/Js2Py.qhelp, python/ql/src/experimental/Security/CWE-094/Js2Py.ql, python/ql/src/experimental/Security/CWE-094/Js2pyBad.py, python/ql/src/experimental/Security/CWE-094/Js2pyGood.py, python/ql/test/experimental/query-tests/Security/CWE-094/Js2Py.expected, python/ql/test/experimental/query-tests/Security/CWE-094/Js2Py.qlref, python/ql/test/experimental/query-tests/Security/CWE-094/Js2PyTest.py
Js2Py is a Javascript to Python translation library written in Python. It allows users to invoke JavaScript code directly from Python. The Js2Py interpreter by default exposes the entire standard library to it's users. This can lead to security issues if a malicious input were directly.
This PR includes a CodeQL query along with a qhelp and testcases to detect cases where an untrusted input flows to an Js2Py eval call.
This query successfully detects CVE-2023-0297 in `pyload/pyload`along with it's fix. The databases can be downloaded from the links bellow.
```
https://file.io/qrMEjSJJoTq1
https://filetransfer.io/data-package/a02eab7V#link
```
=> Python : Arbitrary code execution due to Js2Py

shared/ssa/codeql/ssa/Ssa.qll
So as to avoid having to compute the barrier guards logic for all possible guards up front.
=> SSA: Make barrier guards a parameterized module

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FileProvider.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/Extractor.cs
This PR is reverting the changes in https://github.com/github/codeql/pull/16945 and instead orders syntax trees before creating the compilation. I overlooked the fact that we're creating syntax trees on multiple threads, so ordering the files didn't result in a stable order for the syntax trees. This PR fixes that by ordering the syntax trees directly.
This change has an impact on both traced and buildless extraction.
=> C#: Order syntax trees before creating compilation

python/extractor/semmle/logging.py, python/extractor/semmle/util.py, python/extractor/semmle/worker.py
In the hopes this will fix a problem encountered in the wild (that I couldn't reproduce locally).
I couldn't find any tests that I could easily extend to test the new behavior either, so what I did was to locally alter `BuiltinExtractor` to always throw an exception. I observed this causes us to generate `Exception: 'BuiltinModuleExtractable' object has no attribute 'path'` in the logs.
With the commits from this PR, we now properly log the failure reason:
```
[2024-07-09 14:07:25] [build-stdout] [ERROR] [15] Failed to extract module _datetime: <exception-reason>
[2024-07-09 14:07:25] [build-stdout] [TRACEBACK] [15] "semmle/worker.py", line 263, in _extract_loop
[2024-07-09 14:07:25] [build-stdout] [TRACEBACK] [15] "semmle/extractors/super_extractor.py", line 34, in process
[2024-07-09 …
```
=> Python: Handle diagnostics writing for `BuiltinModuleExtractable`

cpp/ql/src/Security/CWE/CWE-416/IteratorToExpiredContainer.ql, cpp/ql/src/change-notes/2024-07-11-iterator-to-expired-container-query.md
The query has a very narrow set of results on MRVA, but they're all mostly TPs (three TPs and one FP). See backlink to MRVA results.
=> C++: Promote `cp/iterator-to-expired-container` to Code Scanning

csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/test/utils/modelgenerator/dataflow/Sources.cs, misc/scripts/models-as-data/generate_flow_model.py
In this PR we further narrow the C# source model generation to exclude all callables that overrides or implements something else. This is because we need to "limit" the number of generated sources models that could be used during dynamic dispatch (to avoid getting to many false positive/speculative results).
=> C#: Narrow source model generation.

java/ql/lib/change-notes/2024-06-12-isandroid-deprecated.md, java/ql/lib/semmle/code/java/frameworks/android/Android.qll, java/ql/lib/semmle/code/java/security/AndroidCertificatePinningQuery.qll, java/ql/lib/semmle/code/java/security/CleartextStorageAndroidFilesystemQuery.qll, java/ql/lib/semmle/code/xml/AndroidManifest.qll, java/ql/src/change-notes/2024-07-07-android-application-heuristic-updated.md, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test1/AndroidManifest.xml, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test2/AndroidManifest.xml, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test3/AndroidManifest.xml, java/ql/test/query-tests/security/CWE-295/AndroidMissingCertificatePinning/Test4/AndroidManifest.xml
This change improves the detection of Android apps in the CodeQL Java standard library. It moves the detection of Android apps to one place and updates the detection to be more accurate. Previously we just required the presence of a `AndroidManifest.xml` file anywhere in the project. This PR improves that in two ways:
- the `AndroidManifest.xml` file must define an activity, service or  content provider (so it corresponds to an android application rather than a library);
- we only consider files in an android application if they are under a folder that contains such an `AndroidManifest.xml`.
[These](https://gist.github.com/owen-mc/99b0dfa1144d25c7bafa5041d9892946) are the results for "[Android missing certificate pinning](https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/ …
=> Java: Improve Android app detection

go/ql/lib/semmle/go/dataflow/ExternalFlow.qll
This avoids putting all the prefixes in the string pool.
See https://github.com/github/codeql/pull/16941#discussion_r1677548036 for more background.
=> Go: Change string prefix check

cpp/ql/src/Security/CWE/CWE-191/UnsignedDifferenceExpressionComparedZero.ql, cpp/ql/src/change-notes/2024-07-16-unsigned-difference-expression-compared-zero-.md, cpp/ql/test/query-tests/Security/CWE/CWE-191/UnsignedDifferenceExpressionComparedZero/UnsignedDifferenceExpressionComparedZero.expected, cpp/ql/test/query-tests/Security/CWE/CWE-191/UnsignedDifferenceExpressionComparedZero/test.cpp
Ideally, this should just be done by using the shared range analysis library. However, in a [follow-up PR](https://github.com/github/codeql/pull/16982) I'm suggesting that we move this query into Code Scanning, and we're not quite ready to pull that library into Code Scanning just yet.
So for now I've added the most common/easy cases here. In fact, only the `BitwiseAndExpr` case had an impact on MRVA, and the rest are just for more thorough coverage.
Commit-by-commit review recommended
=> C++: Fix FPs in `cpp/unsigned-difference-expression-compared-zero`

cpp/ql/lib/change-notes/2024-07-16-alert-provenance.md, cpp/ql/lib/semmle/code/cpp/dataflow/ExternalFlow.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/FlowSummaryImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/test/library-tests/dataflow/external-models/flow.expected, cpp/ql/test/library-tests/dataflow/external-models/flow.ql
Extends the work on https://github.com/github/codeql/pull/15501 to fully include CPP.
@aschackmull please could you check I haven't left anything out.
=> C++: Support MaD alert provenance

misc/bazel/pkg.bzl
see the comment for an explanation.
=> pkg.bzl: Disable remote caching of zipmerge steps.

go/extractor/toolchain/toolchain.go
This should help troubleshoot issues if something goes wrong.
=> Go: Output stdout/stderr for `go version` if something goes wrong

cpp/ql/src/Critical/SizeCheck2.ql, cpp/ql/src/change-notes/2024-07-22-suspicious-allocation-size.md, cpp/ql/test/query-tests/Critical/SizeCheck/SizeCheck2.expected, cpp/ql/test/query-tests/Critical/SizeCheck/test.c, cpp/ql/test/query-tests/Critical/SizeCheck/test2.c
Fix an issue with `cpp/suspicious-allocation-size`, that it was unaware of the pattern of "variable size" `struct`s where the last member is an array of size zero or one, but additional space for it is allocated in practice.
=> C++: Fix issue with cpp/suspicious-allocation-size

cpp/ql/test/query-tests/Critical/MemoryFreed/MemoryFreed.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/UseAfterFree.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/test.cpp
More tests for `cpp/use-after-free`.  This was a second failed attempt to reproduce an issue I've seen once in the wild.  I'm going to cut my losses here.
=> C++: More tests for cpp/use-after-free

cpp/ql/src/Critical/ScanfChecks.qll, cpp/ql/src/change-notes/2024-07-23-incorrectly-checked-scanf.md, cpp/ql/test/query-tests/Critical/MissingCheckScanf/IncorrectCheckScanf.expected, cpp/ql/test/query-tests/Critical/MissingCheckScanf/MissingCheckScanf.expected, cpp/ql/test/query-tests/Critical/MissingCheckScanf/test.cpp
Fix false positives results from the `cpp/incorrectly-checked-scanf` query.  The logic used by the query didn't accept some ways of writing a good `scanf` return value check.
=> C++: Fix false positives in cpp/incorrectly-checked-scanf

docs/codeql/codeql-language-guides/annotations-in-java.rst
#6246 added new predicates and deprecated some of the existing predicates, including `getAValue()` which is currently used in the example.
Please let me know if the new documentation text is too verbose or if I should adjust it in some way.
=> Java: Update `Annotation` predicate examples in language guide

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/internal/SSAConstruction.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SSAConstruction.qll
A rule of thumb for writing high-performance QL is to avoid complex negations as these will be materialized to be the right-hand side of an antijoin. So when writing
```ql
if A then B else C
```
we should be careful about what we put into `A` since it will be desugared to
```ql
A and B
or
not A and C
```
So to avoid unnecessary materialization we pull out all the parts of A we expect to "always hold".
=> C++: Avoid expensive negation

java/ql/lib/ext/org.apache.commons.lang3.model.yml, java/ql/lib/semmle/code/java/regex/RegexFlowConfigs.qll
The sink kind `regex-use` doesn't match [the code which parses regex-use sink kinds](https://github.com/github/codeql/blob/4c8da54b64d67aa958ed8875492f962bb1c5c5af/java/ql/lib/semmle/code/java/regex/RegexFlowConfigs.qll#L20-L49) for regex injection. It turns out this is intentional, but not clearly documented. This PR adds comments explaining that.
=> Java: Add comments about use of sink kind `regex-use`

swift/ql/lib/change-notes/2024-07-24-url-model.md, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPublic.qll, swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Url.qll, swift/ql/test/library-tests/dataflow/taint/libraries/url.swift
Two minor fixes for Swift:
- fixed errors in the model for `URL.withUnsafeFileSystemRepresentation(_:)`.
- filled out the (previously empty) QLDoc comment for `SsaDefinitionNode`.
=> Swift: Minor fixes

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, docs/ql-libraries/dataflow/dataflow.md, go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, shared/dataflow/codeql/dataflow/DataFlow.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
The `ppReprType` predicate was originally used instead of `DataFlowType.toString` in the data flow interface to avoid having to wrap the Java `DataFlowType` in an IPA type. But now that we have QL language features like `extends final`, we can get rid of this and simply use `DataFlowType.toString` in the data flow language-specific api.
=> Dataflow: Replace `ppReprType` with `DataFlowType.toString`.

cpp/ql/test/library-tests/specifiers2/cpp20.cpp, cpp/ql/test/library-tests/specifiers2/inst_func_specifiers.expected, cpp/ql/test/library-tests/specifiers2/inst_func_specifiers.ql, cpp/ql/test/library-tests/specifiers2/specifiers2.expected, cpp/ql/test/library-tests/specifiers2/specifiers2.ql, cpp/ql/test/library-tests/specifiers2/specifiers2d.expected, cpp/ql/test/library-tests/specifiers2/templ_func_specifiers.expected, cpp/ql/test/library-tests/specifiers2/templ_func_specifiers.ql
Note that the `explict(bool)` specifiers currently do not end up in the database.
=> C++: Add additional test cases for `explict` and `explicit(bool)` specifiers

cpp/ql/src/Security/CWE/CWE-014/MemsetMayBeDeleted.qhelp, cpp/ql/src/Security/CWE/CWE-311/CleartextStorage.c, cpp/ql/src/Security/CWE/CWE-311/CleartextStorage.inc.qhelp, cpp/ql/src/Security/CWE/CWE-313/CleartextSqliteDatabase.c, cpp/ql/src/Security/CWE/CWE-313/CleartextSqliteDatabase.qhelp
Improve advice for using encryption in query documentation and examples:
- in `cpp/memset-may-be-deleted`, make a clear recommendation for `memset_s` above the other suggestions (especially writing your own).
- in the `cpp/cleartext-*` queries which share an example, give (partial) code for performing encryption using libsodium instead of invoking a magical "encrypt" function which was not provided and frankly was not plausible.  Also hint at the need for key management.
- in the `cpp/cleartext-storage-database` query, have the encryption key passed in via parameter instead of using a placeholder (insecure) key, and hint at the need for key management.
=> C++: Improve query doc advice for using encryption

cpp/ql/lib/semmle/code/cpp/models/implementations/StdMath.qll, cpp/ql/test/query-tests/Security/CWE/CWE-457/semmle/tests/UninitializedLocal.expected, cpp/ql/test/query-tests/Security/CWE/CWE-457/semmle/tests/test.cpp
I don't think we need a change note for this as this FP only happened after we merged https://github.com/github/codeql/pull/17034 earlier today.
=> C++: Add missing write side effect to `std::remquo`

java/ql/lib/ext/org.apache.commons.lang3.model.yml, java/ql/lib/semmle/code/java/regex/RegexFlowConfigs.qll
Fixes comments about the `regex-use` sink kind.
See https://github.com/github/codeql/pull/17053#issuecomment-2248874305.
=> Java: fix comments about use of sink kind `regex-use`

cpp/ql/test/library-tests/attributes/routine_attributes/arguments.expected, cpp/ql/test/library-tests/attributes/routine_attributes/routine_attributes.expected, cpp/ql/test/library-tests/attributes/type_attributes/arguments.expected, cpp/ql/test/library-tests/attributes/type_attributes/type_attributes.expected, cpp/ql/test/library-tests/attributes/var_attributes/var_attributes.expected
Update test output following extractor changes.
=> C++: Update attributes test output

java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll
Adds support for printing provenance of experimental models in qltest. Otherwise those rows will be missing. See also https://github.com/github/codeql/pull/17087
=> Java: Pretty-print experimental models for qltest.

misc/bazel/internal/install.py
Ripunzip is great, but occasionally bugs out due to a parallelism issue. As we don't want this to fail CI, retry the entire ripunzip/installation step up to 3 times.
We need to clean up the working directory as ripunzip doesn't support overwriting files. I've not been able to test this with the original issue (it doesn't seem to reproduce locally for me), but I injected another error and got 3 retries of installation.
=> Bazel installer: Retry ripunzip step.

java/ql/src/Violations of Best Practice/Dead Code/DeadRefTypes.ql, java/ql/src/change-notes/2024-07-30-unused.md, java/ql/test/query-tests/DeadCode/DeadRefTypes/ClassWithAnnotatedMethod.java, java/ql/test/query-tests/DeadCode/DeadRefTypes/ClassWithAnnotation.java, java/ql/test/query-tests/DeadCode/DeadRefTypes/DeadRefTypes.expected, java/ql/test/query-tests/DeadCode/DeadRefTypes/DeadRefTypes.qlref, java/ql/test/query-tests/DeadCode/DeadRefTypes/MyAnnotation.java, java/ql/test/query-tests/DeadCode/DeadRefTypes/UnusedClass.java
This query didn't have any tests. I've added some basic ones just to make sure the PR does what it says it does.
=> Java: Fix FPs in `java/unused-reference-type` for JUnit 4-style tests

java/ql/test/library-tests/dataflow/call-sensitivity/flow.expected, java/ql/test/library-tests/dataflow/call-sensitivity/flow.ql, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.ql, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest2.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest2.ql, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest3.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest3.ql, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest4.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest4.ql, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest5.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest5.ql, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest6.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest6.ql
Adds support for post-process provenance pretty-printing in `.ql` library-tests.
=> Java: Add support for post-process provenance pretty-printing in `.ql` library-tests

cpp/ql/lib/change-notes/2024-07-31-constexpr-if.md, cpp/ql/lib/semmle/code/cpp/exprs/Expr.qll, cpp/ql/test/library-tests/exprs/unevaluated/test.cpp, cpp/ql/test/library-tests/exprs/unevaluated/unevaluated.expected
The controlling expression of a `constexpr if` is always evaluated at compile-time (see [here](https://en.cppreference.com/w/cpp/language/if#Constexpr_if)).
=> C++: Mark `constexpr if` as unevaluated

cpp/ql/src/Critical/MemoryMayNotBeFreed.ql, cpp/ql/src/change-notes/2024-07-31-memory-may-not-be-freed.md, cpp/ql/test/query-tests/Critical/MemoryFreed/MemoryFreed.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/MemoryMayNotBeFreed.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/MemoryNeverFreed.expected, cpp/ql/test/query-tests/Critical/MemoryFreed/test_free.cpp
Improve `cpp/memory-may-not-be-freed`.  The query has code that recognizes when a function returns an allocation, i.e. it behaves like an allocator.  This code excludes cases where the allocation is copied to a field or global variable in addition to being returned, acknowledging that such cases are probably not allocators / are beyond the scope of analysis by this query.  However if the allocation is made into a field, not copied into a field, this was being overlooked (causing large numbers of false positives for some users).
=> C++: Improve cpp/memory-may-not-be-freed

python/ql/lib/semmle/python/Frameworks.qll, python/ql/lib/semmle/python/frameworks/Streamlit.qll, python/ql/src/change-notes/2024-07-26-streamlit-models.md, python/ql/test/experimental/meta/RemoteFlowSourceTest.qll, python/ql/test/library-tests/frameworks/gradio/source_test.ql, python/ql/test/library-tests/frameworks/streamlit/ConceptsTest.expected, python/ql/test/library-tests/frameworks/streamlit/ConceptsTest.ql, python/ql/test/library-tests/frameworks/streamlit/rfs-test.expected, python/ql/test/library-tests/frameworks/streamlit/rfs-test.ql, python/ql/test/library-tests/frameworks/streamlit/test.py
👋 This PR adds a few sources and a sink for the [Streamlit](https://streamlit.io/) framework. Streamlit is a popular Python library for creating web apps for machine learning and data science. 🚀 
I did a bit of tweaking with tests, let me know if these could be improved.
Side note: Streamlit creates SQL connection to databases using SQL Alchemy Engine. There are a few potential SQLExecution sinks that I haven't included, because to execute the SQL query they require sqlalchemy's `TextClause` object, which is already modeled, so my assumption here is that we don't need to model those.
For example `st.connection().session.execute()` would be a potential sink, but it requires a `TextClause` object, which is already modeled as a SQL injection sink. 
Here is an example of how it could be used: …
=> Python: Add Streamlit models

go/ql/lib/ext/github.com.go-jose.go-jose.jwt.model.yml, go/ql/lib/ext/github.com.go-jose.go-jose.model.yml, go/ql/lib/semmle/go/frameworks/GoJose.qll, go/ql/lib/semmle/go/security/ExternalAPIs.qll, go/ql/src/experimental/frameworks/JWT.qll, go/ql/test/library-tests/semmle/go/frameworks/Beego/ReflectedXss.expected, go/ql/test/library-tests/semmle/go/frameworks/Revel/OpenRedirect.expected, go/ql/test/library-tests/semmle/go/frameworks/Revel/ReflectedXss.expected, go/ql/test/library-tests/semmle/go/frameworks/Revel/TaintedPath.expected, go/ql/test/query-tests/Security/CWE-347/MissingJwtSignatureCheck.expected
It has had quite a few different import paths in the past.
=> Go: Fix missing `go-jose` package path

csharp/ql/test/library-tests/dataflow/async/Async.expected, csharp/ql/test/library-tests/dataflow/collections/CollectionFlow.expected, csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest2.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest3.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest4.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest5.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest6.expected, go/ql/test/query-tests/Security/CWE-601/BadRedirectCheck/BadRedirectCheck.expected, java/ql/test/experimental/query-tests/security/CWE-625/PermissiveDotRegex.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest2.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest3.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest4.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest5.expected, java/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest6.expected, java/ql/test/query-tests/security/CWE-601/semmle/tests/UrlRedirect.expected, python/ql/test/experimental/query-tests/Security/CWE-022-TarSlip/TarSlip.expected, ruby/ql/test/query-tests/security/cwe-506/HardcodedDataInterpretedAsCode.expected, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
I expect this to mostly affect edges that have a corresponding subpaths-tuple, so it won't have much effect on the actual path explanations, but if you somehow provide a modeled library function with through-flow as a call-back argument to another library function, which then results in a combined through-flow, then it could be relevant.
In any case, it's a small correctness bug that's easy to fix. And we should see plenty of test coverage of this in the recorded `edges` relations in qltests.
=> Dataflow: Propagate provenance correctly for flow-through wrappers.

shared/dataflow/codeql/dataflow/test/ProvenancePathGraph.qll
Ideally this shouldn't happen, but it currently does (due to a known bug), so let's just be a bit more robust and have the tests actually work.
=> Dataflow: Allow printing multiple models for one MaDId.

go/documentation/library-coverage/frameworks.csv
While doing this I found some extra package paths that we should use, which I've implemented [here](https://github.com/github/codeql/pull/17113) and [here](https://github.com/github/codeql/pull/17114).
=> Go: add newly modeled packages to frameworks.csv

swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.qhelp, swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.swift, swift/ql/src/queries/Security/CWE-311/CleartextTransmission.qhelp, swift/ql/src/queries/Security/CWE-311/CleartextTransmission.swift, swift/ql/src/queries/Security/CWE-312/CleartextStoragePreferences.qhelp, swift/ql/src/queries/Security/CWE-312/CleartextStoragePreferences.swift, swift/ql/src/queries/Security/CWE-321/HardcodedEncryptionKey.swift, swift/ql/src/queries/Security/CWE-327/ECBEncryption.swift, swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.expected, swift/ql/test/query-tests/Security/CWE-321/cryptoswift.swift, swift/ql/test/query-tests/Security/CWE-327/ECBEncryption.expected, swift/ql/test/query-tests/Security/CWE-327/test.swift
Swift: Improve query documentation and examples that involve encryption:
- replace pseudocode in examples with more realistic code (for the `swift/cleartext-*` queries).
- mention key management in the `.qhelp`s, and provide a reference to help with that.
- use the correct initializer for [CryptoSwift's `CBC` class](https://github.com/krzyzanowskim/CryptoSwift/blob/main/Sources/CryptoSwift/BlockMode/CBC.swift#L31) in examples and tests.
=> Swift: Improve documentation and examples that use encryption

go/ql/lib/ext/github.com.jbowtie.gokogiri.model.yml, go/ql/lib/ext/github.com.jbowtie.gokogiri.xml.model.yml, go/ql/lib/ext/github.com.moovweb.gokogiri.xml.model.yml, go/ql/lib/ext/github.com.moovweb.gokogiri.xpath.model.yml, go/ql/test/query-tests/Security/CWE-643/XPathInjection.expected
It turns out that `jbowtie/gokogiri` is a fork of `moovweb/gokogiri`. They are equally popular, so I have named the models file after the original repo. The things that we model are the same in both packages.
=> Go: Add import path for Gokogiri

swift/ql/src/queries/Security/CWE-089/SqlInjection.qhelp, swift/ql/src/queries/Security/CWE-089/SqlInjectionBad.swift, swift/ql/src/queries/Security/CWE-089/SqlInjectionGood.swift
Improve the `swift/sql-injection` qhelp and examples in various ways, with the aim of making it clearer what these problems look like and how they should be fixed.
=> Swift: Improve doc for swift/sql-injection

MODULE.bazel, go/BUILD.bazel, go/extractor/BUILD.bazel, go/extractor/dbscheme/BUILD.bazel, go/extractor/project/BUILD.bazel, go/extractor/trap/BUILD.bazel, go/extractor/util/BUILD.bazel, go/gen.py
If I recall correctly, we were avoiding using the `gazelle` rule because of some compilation problem on macOS, which seems to be gone with the current versions of `rules_go` and/or `gazelle`.
This will make sure that gazelle uses the bundled go version: prior to this, the build through `make` was misbehaving if `go` was not installed.
=> Go/Bazel: fix gazelle invocation to use bundled bazel go

ruby/ql/lib/codeql/ruby/controlflow/internal/Guards.qll, ruby/ql/lib/codeql/ruby/dataflow/SSA.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll
This PR adopts the newly introduced shared [SSA data-flow integration layer](https://github.com/github/codeql/pull/16884).
=> Ruby: Adopt shared SSA data-flow integration

ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll
Add method `get_response` for ruby `Net::HTTP`
=> Ruby: Add get_response for Net::HTTP

docs/codeql/reusables/supported-platforms.rst, docs/codeql/reusables/supported-versions-compilers.rst
`ubuntu-18.04` Actions runners is deprecated so should be removed from the platforms we support.
Also, changed a footnote to indicate that Swift support requires macOS. Swift analysis on Linux is no longer supported: https://github.com/github/codeql-action/blob/main/CHANGELOG.md#unreleased
=> Docs: remove `ubuntu-18.04`, indicate Swift requires macOS

cpp/ql/test/library-tests/dataflow/external-models/flow.expected
Similar to https://github.com/github/codeql/pull/17139 but for C++.
=> C++: Accept test changes caused by new CLI version.

misc/bazel/internal/git_lfs_probe.py
It is advisable to exclude b63bd2ad14ebd51e1b39d4bed8b5302413c79ed0 from the diff view: that changes only formatting according to my current IDE settings (and the top level `black` configuration).
This was confirmed to help a user with a specific git remote configuration in `ql`.
=> Bazel: make `git_lfs_probe.py` try all available endpoints

go/documentation/library-coverage/frameworks.csv
I got one of the paths wrong in the frameworks.csv file.
=> Go: Fix mistake in frameworks.csv

csharp/ql/src/Telemetry/ExtractorInformation.ql
Timing values in the telemetry data make little sense, because after a traced extraction we end with one value per compilation, so possibly hundreds/thousands of values. 
Also, the values are not stable, so they are causing wobbles in DCA.
=> C#: Remove timing values from extractor telemetry query

python/ql/lib/semmle/python/dataflow/new/internal/TaintTrackingPrivate.qll, python/ql/lib/semmle/python/frameworks/Stdlib.qll, python/ql/lib/semmle/python/frameworks/Stdlib/StdLib.model.yml, python/ql/lib/semmle/python/security/dataflow/UnsafeShellCommandConstructionQuery.qll, python/ql/src/semmle/python/functions/ModificationOfParameterWithDefault.qll, python/ql/test/experimental/query-tests/Security/CWE-022-UnsafeUnpacking/UnsafeUnpack.expected, python/ql/test/experimental/query-tests/Security/CWE-409/DecompressionBombs.expected, python/ql/test/library-tests/frameworks/stdlib/Logging.py, python/ql/test/query-tests/Security/CWE-078-CommandInjection/CommandInjection.expected
These are the models gathered so far during experiments not extracting the standard library by default.
A good part of the models are generated by special automation. Where possible, I have made manual adjustments to make them align with their documentation and not be overly specific.
Commit-by-commit review should be beneficiel.
=> Python: Modelling of the Standard Library

java/ql/test/library-tests/dataflow/flowfeature/A.java, java/ql/test/library-tests/dataflow/flowfeature/flow.expected, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
The first commit adds a test highlighting the problem and the second commit fixes the bug. Note that this bug is quite low impact since FeatureHasSinkCallContext isn't used much - it's primary use-case is for identification of source wrappers, which I believe isn't currently in use.
cc: @michaelnebel
=> Dataflow: Fix bug causing spurious flow for FeatureHasSinkCallContext

cpp/ql/lib/semmle/code/cpp/dataflow/ExternalFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/test/library-tests/dataflow/library/FlowSummaries.ql, csharp/ql/test/utils/modelgenerator/dataflow/CaptureNeutralModels.ext.yml, csharp/ql/test/utils/modelgenerator/dataflow/Sinks.cs, go/ql/lib/semmle/go/dataflow/ExternalFlow.qll, go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowDispatch.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, java/ql/test/utils/modelgenerator/dataflow/CaptureNeutralModels.ext.yml, java/ql/test/utils/modelgenerator/dataflow/p/Sinks.java, shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll, swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
The existing implementation doesn't handle *kind* and *provenance* in conjunction with each other as they get mixed in the `NeutralCallable` class (we basically get the *product* of the kinds and provenances - see the example below).
The *neutral* classes are now created based on parameterised modules instead.
If we quick eval the `myTest` predicate in the following example, we get the tuples `(A,A1)` and `(A,A2)`.
```ql
bindingset[this]
abstract class Base extends string {
abstract string getValue();
}
class A1 extends Base {
A1() { this = "A" }
override string getValue() { result = "A1" }
}
class A2 extends Base {
A2() { this = "A" }
override string getValue() { result = "A2" }
}
predicate myTest(A2 a, string value) { a.getValue() = value }``
=> C#/Java/Go: Neutrals are split into separate classes.

shared/dataflow/codeql/dataflow/DataFlow.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/test/ProvenancePathGraph.qll
I noticed that even though our two different use-cases for `PathGraphSig` relies on parameterisations with different `PathNodeSig`s then that doesn't prevent us from sharing `PathGraphSig`.
There's a little bit of module-juggling to ensure that `PathGraphSig` is exposed both at the top-level and in the result of `DataFlowMake`.
I've copied `TypeWithToString` from `Option.qll`. I think that's fine for now, but of course if we see a proliferation of use-cases for that signature then we can consider putting it in its own shared lib.
=> Dataflow: Reduce duplication, define PathGraphSig only once.

go/ql/test/experimental/CWE-321-V2/go.mod, go/ql/test/experimental/CWE-321-V2/vendor/modules.txt
The commands I ran were:
```
go mod tidy
depstubber -write_module_txt
```
=> Go: Remove unneeded dependency from test go.mod

go/ql/lib/ext/clevergo.tech.clevergo.model.yml, go/ql/lib/ext/github.com.beego.beego.server.web.context.model.yml, go/ql/lib/ext/github.com.beego.beego.server.web.model.yml, go/ql/lib/ext/github.com.gofiber.fiber.model.yml, go/ql/lib/ext/github.com.labstack.echo.model.yml, go/ql/lib/ext/github.com.revel.revel.model.yml, go/ql/lib/ext/github.com.valyala.fasthttp.model.yml, go/ql/lib/ext/gopkg.in.macaron.model.yml, go/ql/lib/ext/net.http.model.yml, go/ql/lib/ext/regexp.model.yml, go/ql/lib/semmle/go/concepts/HTTP.qll, go/ql/lib/semmle/go/frameworks/Beego.qll, go/ql/lib/semmle/go/frameworks/Echo.qll, go/ql/lib/semmle/go/frameworks/Fasthttp.qll, go/ql/lib/semmle/go/frameworks/Macaron.qll, go/ql/lib/semmle/go/frameworks/Revel.qll, go/ql/lib/semmle/go/frameworks/stdlib/NetHttp.qll, go/ql/lib/semmle/go/frameworks/stdlib/Regexp.qll, go/ql/src/experimental/frameworks/CleverGo.qll, go/ql/src/experimental/frameworks/Fiber.qll, go/ql/test/library-tests/semmle/go/concepts/Regexp/RegexpMatchFunction.expected, go/ql/test/library-tests/semmle/go/frameworks/Echo/OpenRedirect.expected, go/ql/test/library-tests/semmle/go/frameworks/Revel/OpenRedirect.expected, go/ql/test/query-tests/Security/CWE-020/IncompleteHostnameRegexp/IncompleteHostnameRegexp.expected, go/ql/test/query-tests/Security/CWE-020/IncompleteHostnameRegexp/IncompleteHostnameRegexp.qlref, go/ql/test/query-tests/Security/CWE-601/BadRedirectCheck/BadRedirectCheck.expected, go/ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirect.expected, shared/mad/codeql/mad/ModelValidation.qll
Convert regex-use, url-redirection sinks to use models-as-data. Follows on from https://github.com/github/codeql/pull/17162.
=> Go: convert regex-use, url-redirection sinks to use models-as-data

csharp/ql/lib/change-notes/2024-05-23-static-field-side-effect.md, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected, csharp/ql/test/library-tests/dataflow/fields/K.cs
Same as https://github.com/github/codeql/pull/16500 for Java.
=> C#: Add support for flow through side-effects on static fields

java/ql/test/library-tests/dataflow/subpaths/A.java, java/ql/test/library-tests/dataflow/subpaths/flow.expected, java/ql/test/library-tests/dataflow/subpaths/flow.ql
@asgerf found a bug causing a missing subpath, so I distilled it into a qltest. I'll look into fixing this in a separate PR.
Note that the flow works just fine - it's just the subpaths tuple that's missing, which causes a slightly less informative path explanation.
=> Dataflow: Add test highlighting missing subpath.

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/test/utils/modelgenerator/dataflow/CaptureSinkModels.ext.yml, csharp/ql/test/utils/modelgenerator/dataflow/Sinks.cs, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/test/utils/modelgenerator/dataflow/CaptureSinkModels.ext.yml, java/ql/test/utils/modelgenerator/dataflow/p/Sinks.java, shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
The abstract class implementation is replaced by a parameterized module implementation for the same reason as on: https://github.com/github/codeql/pull/17007
=> C#/Java: Fix source- and sink callable provenance overlap.

java/ql/lib/change-notes/2024-08-09-buildless-executable-war.md, java/ql/lib/change-notes/2024-08-09-buildless-gradle-classifiers.md, java/ql/lib/change-notes/2024-08-14-buildless-coder-malfunction.md
These were all missing a change note when originally merged.
=> Java: add change notes for three recent buildless fixes

csharp/ql/test/library-tests/dataflow/collections/CollectionFlow.expected, java/ql/test/experimental/query-tests/security/CWE-625/PermissiveDotRegex.expected, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
A small bug which caused us to generate a bit too many edges in the PathGraph. This should have no impact on alerts, but might reduce bqrs size a bit.
=> Dataflow: Fix missing join on summaryLabel.

python/ql/src/Security/CWE-020/CookieInjection.ql
The `@name` attribute for queries should not end with a period, see [Query metadata style guide](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md#query-name-name).
This PR removes the period from the name. As far as I can tell, this is the only place where the update needs to be made.
Ideally this would be picked up by a linter or reviewer before it generates a linter error in the Docs repository, but it doesn't happen very often 🙂 
👋🏻 One process consideration. When a team promotes an experimental query into the default packs, it would make sense to ask for a review by the Docs team since we don't review the user-facing content for experimental queries when they are added to the repository.
=> Update CookieInjection.ql to remove period from @name

swift/ql/lib/codeql/swift/security/CleartextTransmissionExtensions.qll, swift/ql/src/change-notes/2024-08-12-cleartext-transmission.md, swift/ql/test/query-tests/Security/CWE-311/CleartextTransmission.expected, swift/ql/test/query-tests/Security/CWE-311/SensitiveExprs.expected, swift/ql/test/query-tests/Security/CWE-311/testURL.swift
Fix false positives in the `swift/cleartext-transmission` query where a `tel:`, `mailto:` or similar URL is created that contains unencrypted sensitive data (the telephone number or e-mail address) that is, strictly speaking, transmitted.  However in these cases the data is only transmitted by the act of it's use, which is very much intended and unavoidable in creating that connection.  This kind of result is therefore not helpful.
=> Swift: Fix false positives in the swift/cleartext-transmission query

cpp/ql/src/Security/CWE/CWE-190/Bounded.qll, cpp/ql/src/Security/CWE/CWE-190/TaintedAllocationSize.ql, cpp/ql/src/change-notes/2024-08-16-uncontrolled-allocation-size.md, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/test.cpp
Reuse the `bounded` predicate in the `TaintedAllocationSize` query.
=> C++: Reuse bounded predicate in TaintedAllocationSize query

swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.expected, swift/ql/test/query-tests/Security/CWE-321/misc.swift
I had spotted what I thought was a pattern of false positives for `swift/hardcoded-key`, `swift/hardcoded-password` and `swift/constant-salt` (the queries that have constants as sources), where certain kinds of conversions were being mistaken for constants.  On closer investigation (using a proper viewer that allows clicking through to the source), it turns out these cases actually involved constants being passed as parameters, so they're not false positives at all.
This PR adds some test cases that document and confirm correct behaviour.
=> Swift: Additional test cases for swift/hardcoded-key

cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/test.cpp
As pointed out by @intrigus-lgtm the test that I added in #17220 was not a true negative but a false negative. This PR fixes that by adding an actual true negative and marking the false negative as such.
=> C++: Fix tests and add an actual true negative

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/test/library-tests/dataflow/api-graphs/VerifyApiGraphExpectations.expected, ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected, ruby/ql/test/library-tests/dataflow/array-flow/array_flow.rb, ruby/ql/test/library-tests/dataflow/array-flow/type-tracking-array-flow.expected, ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.expected, ruby/ql/test/library-tests/dataflow/params/TypeTracker.expected, ruby/ql/test/library-tests/dataflow/params/params-flow.expected, ruby/ql/test/library-tests/dataflow/params/params_flow.rb, ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected, ruby/ql/test/library-tests/frameworks/action_controller/params-flow.expected
Inspired by [@asgerf's PR](https://github.com/github/codeql/pull/17213), this PR rewrites the logic for how Ruby handles splat arguments and parameters. Instead of using a separate `Content` type to perform the matching, we make use of different argument/parameter positions in order to prevent synthetic splat arguments from being matched with synthetic splat parameters.
Not only does this rewrite simplify the code, we also get [a significant speedup](https://github.com/github/codeql-dca-main/tree/data/hvitved/PR-17222-0-ruby/reports) (12% end-to-end analysis speedup on average). This is because the early data flow pruning stages have precise argument/parameter position matching, wheres precise content matching only happens in later pruning stages.
=> Ruby: Rework (hash) splat argument/parameter matching

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/TaintTrackingPrivate.qll, csharp/ql/lib/semmle/code/csharp/frameworks/EntityFramework.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/test/library-tests/dataflow/external-models/steps.ql, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll
Storing into properties and reading out of properties takes overriding into account. For example, in
```csharp
interface I
{
string Prop { get; set; }
}
class C : I
{
public string Prop { get; set; }
public void M()
{
this.Prop = "taint";
Sink(((I)this).Prop);
}
}
```
` this.Prop = "taint"` stores into the property `C.Prop`, whereas `((I)this).Prop` read from `I.Prop`. Before this PR, `((I)this).Prop` would give rise to two read steps: one for `I.Prop` and one for `C.Prop`. In general, this meant that property reads would fan out to all possible compatible properties, which is better solved using `ContentSet`s.
=> C#: Implement `ContentSet`

csharp/ql/lib/change-notes/2024-08-21-abstract-asp-controller.md, csharp/ql/lib/semmle/code/csharp/frameworks/microsoft/AspNetCore.qll, csharp/ql/test/library-tests/dataflow/flowsources/aspremote/AspRemoteFlowSource.cs, csharp/ql/test/library-tests/dataflow/flowsources/aspremote/aspRemoteFlowSource.expected, csharp/ql/test/library-tests/frameworks/microsoft/AspNetCore.cs, csharp/ql/test/library-tests/frameworks/microsoft/AspNetCore.expected, csharp/ql/test/query-tests/Security Features/CWE-089/SqlInjection.cs, csharp/ql/test/query-tests/Security Features/CWE-089/SqlInjection.expected, csharp/ql/test/query-tests/Security Features/CWE-089/options
In this PR we remove the restriction that a controller should be *instantiable* (this was introduced as a part of https://github.com/github/codeql/pull/9406).
Even though the documentation states that controllers should be *instantiable* then from an analysis perspective it makes sense to include abstract controllers as we are mostly interested in parameters (as remote sources) and methods (action methods) on controllers, which can easily be exposed to a user as the following example shows
```csharp
public abstract class AbstractController : Controller {
public void ActionMethod(string userInput) { sink(userInput); }
}
public class ConcreteController : AbstractController { }
```
=> C#: ASP.NET Controller is allowed to be abstract.

javascript/ql/lib/semmle/javascript/frameworks/helmet/Helmet.Required.Setting.model.yml, javascript/ql/lib/semmle/javascript/frameworks/helmet/Helmet.qll, javascript/ql/src/Security/CWE-693/CUSTOMIZING.md, javascript/ql/src/Security/CWE-693/InsecureHelmet.ql
previously was getting the below warning due to pack structure:
```
WARNING: In extension for codeql/javascript-queries:requiredHelmetSecuritySetting, addsTo.pack 'codeql/javascript-queries' is not one of the transitive dependencies of 'codeql/javascript-all'. This warning will become an error in future versions of CodeQL. (.../codeql/packages/codeql/javascript-all/1.1.1/semmle/javascript/frameworks/helmet/Helmet.Required.Setting.model.yml:1,1-1
```
=> Update JS helmet model structure

go/ql/lib/semmle/go/dataflow/ExternalFlow.qll
Teach the automation that when looking at the package column of a model it should ignore `fixed-version:` at the beginning and strip out any major version suffix (like `/v2` or `.v3`). Also teach it that `/` is the separator for package paths in go, so now it understands that `os/exec` should be counted under the "canonical package" of `os`, which is fine as we want them both lumped into the "Standard library" bucket. I think this means we can stop using so many `*` when listing which canonical packages go in which buckets, e.g. we can put `os` instead of `os*`.
=> Go: Try to fix packages in frameworks coverage

go/BUILD.bazel, go/codeql-tools/baseline-config-empty.json, go/codeql-tools/baseline-config-vendor.json, go/codeql-tools/configure-baseline.cmd, go/codeql-tools/configure-baseline.sh, go/extractor/cli/go-configure-baseline/BUILD.bazel, go/extractor/cli/go-configure-baseline/go-configure-baseline.go, go/extractor/configurebaseline/BUILD.bazel, go/extractor/configurebaseline/configurebaseline.go, go/extractor/extractor.go, go/extractor/util/BUILD.bazel, go/extractor/util/extractvendordirs.go, go/ql/integration-tests/all-platforms/go/configure-baseline/src/a/vendor/avendor.go, go/ql/integration-tests/all-platforms/go/configure-baseline/src/b/vendor/bvendor.go, go/ql/integration-tests/all-platforms/go/configure-baseline/src/c/vendor/cvendor.go, go/ql/integration-tests/all-platforms/go/configure-baseline/src/root.go, go/ql/integration-tests/all-platforms/go/configure-baseline/test.py, go/ql/lib/change-notes/2024-08-20-vendor-dirs-baseline.md
Our existing configure-baseline scripts would give the wrong result if a `vendor` directory wasn't at the root of the repository, or if the `CODEQL_EXTRACTOR_GO_EXTRACT_VENDOR_DIRS` variable was set to `true` indicating the user wants their vendored code scanned.
Here I replace the shell scripts that implemented the very simplest behaviour with a small Go program.
=> Go / configure-baseline: account for multiple vendor directories and the `CODEQL_EXTRACTOR_GO_EXTRACT_VENDOR_DIRS` setting

javascript/ql/lib/semmle/javascript/NodeJS.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-312/BuildArtifactLeak.expected, javascript/ql/test/query-tests/Security/CWE-730/RegExpInjection.expected, javascript/ql/test/query-tests/Security/CWE-798/HardcodedCredentials.expected
As usual, targeting `js/shared-dataflow-merge-main` which contains `js/shared-dataflow-branch` with `main` merged into it.
Some of the relevant changes on `main` that needed fixups:
- [This PR](https://github.com/github/codeql/pull/17212) caused negative recursion on the shared data flow branch, and needed a fixup to be evaluted during the `TEarlyStageNode` stage.
- Some test output has changed as a result of the recent `subpaths` refactoring.
- Some minor changes to test cases result in changed updates
=> JS: Resolve conflicts after merging 'main' into shared data flow branch

.github/workflows/buildifier.yml, .pre-commit-config.yaml, misc/bazel/BUILD.bazel, misc/bazel/buildifier/BUILD.bazel, misc/ripunzip/BUILD.bazel, misc/ripunzip/install.sh
* The relative path to misc doesn't work when running from another repo
* The buildifier dependency is not available from other repos, therefore we can't pull in //misc/bazel without further refactoring.
Therefore, inline the runfiles snippet here.
=> Make ripunzip installer accessible from outside this repo.

cpp/ql/test/library-tests/dataflow/taint-tests/taint.expected, java/ql/test-kotlin1/library-tests/dataflow/summaries/test.expected, java/ql/test-kotlin2/library-tests/dataflow/summaries/test.expected, java/ql/test/experimental/query-tests/security/CWE-200/SensitiveAndroidFileLeak.expected, java/ql/test/library-tests/dataflow/implicit-read/A.java, java/ql/test/library-tests/dataflow/implicit-read/test.ql, java/ql/test/library-tests/frameworks/apache-commons-lang3/flow.expected, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, swift/ql/test/library-tests/dataflow/taint/core/Taint.expected, swift/ql/test/library-tests/dataflow/taint/libraries/set.swift, swift/ql/test/query-tests/Security/CWE-094/UnsafeJsEval.expected, swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.expected, swift/ql/test/query-tests/Security/CWE-757/InsecureTLS.expected
After using an implicit read, flow can now only terminate in a sink or continue along edges contributed by `Config:isAdditionalFlowStep`, but not via other kinds of steps, like simple local flow steps.
This is achieved by treating the implicit read node as a sink if its original node was a sink, and copying any relevant outgoing steps from the original node onto the implicit read node.
=> Shared: restrict flow after using implicit read

cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/taint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/vector.cpp
Some of the sinks in this test were flagged for the wrong reason.
The flow into these sinks isn't working properly, but this was not revealed by the test since an alternate, spurious path exists for each of them. The spurious path goes through the implicit read at one of the prior sinks and takes a use-use step.
In one case the false negative can be revealed by swapping the order of the sinks, but in the other case I had to remove some of the sinks to avoid the interference.
This came up while trying to [fix the issue](https://github.com/github/codeql/pull/17262) with use-use flow after an implicit read, and this test started failing because the fix removes the spurious paths that the test was relying on.
=> C++: Reveal false negative in test case 

csharp/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPartialPath.ql, csharp/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPath.ql, csharp/ql/src/utils/modelgenerator/debug/README.md, csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPartialPath.ql, java/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPath.ql, java/ql/src/utils/modelgenerator/debug/README.md, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll
In this PR we add a couple of debugging queries related to model generation for C# and Java.
- A query for returning flow paths (if we need to figure out why the model generator generates a certain model).
- A query for partial flow (if we need to figure out why the model generator doesn't generate a certain model).
=> C#/Java: Add some model generator summary debugging queries.

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll
Simplifies the representation of the forward flow calculation by merging the three columns representing the summary context into one. This does introduce a bit of non-linear recursion, but this is easily managed and definitely worth it for the readability improvement.
=> Dataflow: Simplify using a SummaryCtx type.

misc/bazel/internal/git_lfs_probe.py
The case of an `HTTPError` was printed to stdout (and therefore gobbed by bazel).
While I'm at it, I also introduced a timeout to `urlopen` and improved the `no endpoints found` error message.
=> Bazel: fix logging bug in `git_lfs_probe.py`

shared/dataflow/codeql/dataflow/internal/ContentDataFlowImpl.qll
```
17950      ~0%     {7} r1 = JOIN `_CaptureModels::PropagateContentFlow::nodeReaches/6#a1f43490#prev_delta_DataFlowImpl::Impl<CaptureMo__#shared` WITH `CaptureModels::PropagateContentFlow::readStep/5#34c0c273#cpe#25` ON FIRST 1 OUTPUT Lhs.4, Lhs.1 'source', Lhs.2 'scReads', Lhs.3 'scStores', Lhs.5 'reads', Lhs.6 'stores', Rhs.1
17950      ~1%     {8}    | JOIN WITH `DataFlowImpl::Impl<CaptureModels::PropagateContentFlow::Flow::C>::S6::PathNode.getNode/0#dispred#c4a4b697` ON FIRST 1 OUTPUT Lhs.6, Lhs.1 'source', Lhs.2 'scReads', Lhs.3 'scStores', Lhs.0, Lhs.4 'reads', Lhs.5 'stores', Rhs.1
1149877000 ~0%     {8}    | JOIN WITH `DataFlowImpl::Impl<CaptureModels::PropagateContentFlow::Flow::C>::S6::PathNode.getState/0#dispred#06e3fe70_10#join_rhs` ON FIRST 1 OUTPUT Lhs.4, Rhs.1 'node', …
```
=> Shared: Fix bad join in content flow.

java/kotlin-extractor/src/main/kotlin/utils/Logger.kt
We never use the greater generality, so this makes it easier to see what's happening.
=> Kotlin: Restrict some TrapWriter types to DiagnosticTrapWriter

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
https://github.com/github/codeql/pull/17262 follow-up.
The C++ query [`InvalidPointerDeref.ql`](https://github.com/github/codeql/blob/main/cpp/ql/src/Security/CWE/CWE-193/InvalidPointerDeref.ql) makes use of an [inlined `isSink` predicate](https://github.com/github/codeql/blob/main/cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/InvalidPointerToDereference.qll#L177), presumably in order to only calculate the predicate based on what is forwards reachable in the initial pruning stage.
It is perhaps questionable to rely on the data flow library being able to support this, but this PR at least restores that functionality.
=> Data flow: Move `toNormalSinkNodeEx` into `PathNodeMid`

cpp/ql/test/query-tests/Critical/MemoryFreed/UseAfterFree.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/ArithmeticTainted.expected, csharp/ql/test/query-tests/Security Features/CWE-338/InsecureRandomness.expected, go/ql/test/experimental/CWE-1004/CookieWithoutHttpOnly.expected, go/ql/test/experimental/CWE-74/DsnInjectionLocal.expected, go/ql/test/library-tests/semmle/go/frameworks/Twirp/RequestForgery.expected, go/ql/test/library-tests/semmle/go/frameworks/XNetHtml/ReflectedXss.expected, go/ql/test/query-tests/Security/CWE-078/StoredCommand.expected, go/ql/test/query-tests/Security/CWE-079/StoredXss.expected, python/ql/test/library-tests/frameworks/django-orm/ReflectedXss.expected, ruby/ql/test/query-tests/security/cwe-094/CodeInjection/CodeInjection.expected, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll, swift/ql/test/query-tests/Security/CWE-078/CommandInjection.expected
This PR moves the `LocalFlowBigStep` module from between stage 2 and stage 3 into the stage module, calculated as an output of the stage. The `LocalFlowBigStep` module is parameterized by an existing step relation, and we invoke the module in `Stage3Param` (as before this PR), and in `Stage6Param`, using the big step relation from `Stage3Param` as input.
The benefit of doing this is that we can sometimes skip intermediate nodes, resulting in smaller `edges` relations (as seen in the changes to the expected test output).
=> Data flow: Compute local big step relation as stage output

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
The FlowState rightfully belongs as a part of the `SummaryCtx`. Previously, when stage 6 had separate code, this was the case, but it was left out in the stage 6 refactor, as it would have involved adding an extra column in a lot of places. But now that the `SummaryCtx` representation has been improved, it's easy to add back in.
=> Dataflow: Include FlowState in SummaryCtx.

cpp/ql/lib/semmle/code/cpp/models/Models.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/Memcpy.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/Memset.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/NoexceptFunction.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/Printf.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/Strcat.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/Strcpy.qll, cpp/ql/lib/semmle/code/cpp/models/interfaces/NonThrowing.qll, cpp/ql/src/Security/CWE/CWE-570/IncorrectAllocationErrorHandling.ql, cpp/ql/src/change-notes/2024-08-26-non-throwing-functions.md, cpp/ql/test/query-tests/Security/CWE/CWE-570/IncorrectAllocationErrorHandling.expected, cpp/ql/test/query-tests/Security/CWE/CWE-570/test.cpp
Add basic modeling of functions that don't throw.
For now I've just let the classes for the two C functions mentioned in the issue, `memset` and `memcpy`, extend the new class.
=> C++: Add basic modeling of functions that don't throw

shared/dataflow/codeql/dataflow/internal/ContentDataFlowImpl.qll
This PR fixes a problem with the flow state in the content flow implementation. The flow state is used to track the number of reads and stores and whether the value is preserved.
The snippet of code seen below was from the original implementation.
Note that `ContentConfig::isAdditionalFlowStep/2` was also used within the `additionalStep` predicate. 
```
predicate isAdditionalFlowStep(Node node1, FlowState state1, Node node2, FlowState state2) {
storeStep(node1, state1, _, node2, state2) or
readStep(node1, state1, _, node2, state2) or
additionalStep(node1, state1, node2, state2)
}
predicate isAdditionalFlowStep = ContentConfig::isAdditionalFlowStep/2;
```
This meant that the steps provided by `ContentConfig::isAdditionalFlowStep/2` could be taken with and without altering the flow state …
=> DataFlow: Bugfix in content flow state for value preservation.

cpp/ql/test/query-tests/Security/CWE/CWE-457/semmle/tests/UninitializedLocal.expected, cpp/ql/test/query-tests/Security/CWE/CWE-457/semmle/tests/test.cpp
Adds a test to confirm and ensure that `cpp/uninitialized-local` doesn't produce false positives for `va_copy` when `va_copy` is extracted as what we would expect.
=> C++: Add test for cpp/uninitialized-local and va_copy

cpp/ql/src/Security/CWE/CWE-190/Bounded.qll, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/ArithmeticUncontrolled/ArithmeticUncontrolled.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/ArithmeticUncontrolled/test.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/test.cpp
The `cpp/uncontrolled-allocation-size` query has some false negatives, such as [this one](https://github.com/paldepind/codeql/blob/d9dbcdba3481016956f20f7f99c7d88a87dfb832/cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/test.cpp#L194).
To improve this, @geoffw0 suggested a change to how [`bounded`](https://github.com/paldepind/codeql/blob/d9dbcdba3481016956f20f7f99c7d88a87dfb832/cpp/ql/src/Security/CWE/CWE-190/Bounded.qll#L26) (which servers as a barrier for this query) works. In an expression like `a % 10` the barrier should be put on the whole expression and not on `a` as is done now. This fixes aforementioned false negative (and potentially others as well).
Note that since `bounded` is also used in two other queries well have to see to what extend this change …
=> C++: Tweak the `bounded` barrier

.github/workflows/ruby-build.yml
A recent update to the `upload-artifact` action stopped uploading "hidden" files (paths that begin with `.`) by default. This was announced widely last week, but I misinterpreted "hidden" as meaning the "hidden" file attribute on Windows, rather than the `.`-prefix convention.
I've fixed the problematic uses in the ruby-build workflow, and I'll work with IDX to see if there are any other workflows that need updating.
=> Include hidden files when uploading Ruby pack

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.cs, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.expected, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.ext.yml
It turns out that we have a bug in the C# Synthetic field implementation. Synthetic fields were only support when declared directly in QL and not in MaD.
To fix this we need to introduce an adapter that adds all mentioned synthetic fields from MaD rows as possible synthetic field names.
=> C#: Support SyntheticField in MaD.

go/ql/lib/change-notes/released/1.1.5.md
We will include this change note when there is documentation about how to use the functionality.
=> Go: Remove change note from 1.15.md

go/ql/lib/change-notes/2024-09-03-local-threat-models-file-environment.md, go/ql/lib/change-notes/released/1.1.5.md
We will include this change note when there is documentation about how to use the functionality.
=> Go: Remove threat models change note from 1.15.md

go/ql/lib/semmle/go/Scopes.qll, go/ql/lib/semmle/go/Types.qll, go/ql/test/library-tests/semmle/go/Function/TypeParamType.expected, go/ql/test/library-tests/semmle/go/Function/TypeParamType.ql
Information about the parent of a `TypeParamType` was already available in the database, but not exposed anywhere in QL. This PR makes the information available with new `getParent` and `getIndex` predicates.
I have also updated the `TypeParamType` test so that it is clearer where the type parameter types come from, which makes it easier for us to spot acceptable changes during version upgrades.
=> Go: Add `getParent` and `getIndex` for `TypeParamType`

MODULE.bazel
We need this for the Go 1.23 work, which we are aiming to get into `rc/3.15`, but we merged it into `main` yesterday in #17359. This PR backports it to `rc/3.15`.
=> Backport "Bazel/Go: Bump rules_go to 0.50.0" to `rc/3.15`

.github/workflows/csharp-qltest.yml
All jobs that are deleted have been moved to the internal repo.
The unit tests are also run internally through bazel, but keeping them here also tests the msbuild build.
=> C#: Delete jobs that moved to the internal repo.

python/ql/src/experimental/Security/CWE-346/CorsBad.py, python/ql/src/experimental/Security/CWE-346/CorsBypass.qhelp, python/ql/src/experimental/Security/CWE-346/CorsBypass.ql, python/ql/src/experimental/Security/CWE-346/CorsGood.py, python/ql/test/experimental/query-tests/Security/CWE-346/Cors.py, python/ql/test/experimental/query-tests/Security/CWE-346/CorsBypass.expected, python/ql/test/experimental/query-tests/Security/CWE-346/CorsBypass.qlref
This PR adds a query to detect a Cross Origin Resource Sharing(CORS) policy bypass due to an incorrect check.
This PR attempts to detect the vulnerability pattern found in CVE-2022-3457
```python
if request.method in ['POST', 'PUT', 'PATCH', 'DELETE']:
origin = request.headers.get('Origin', None)
if origin and not origin.startswith(request.base):
raise cherrypy.HTTPError(403, 'Unexpected Origin header')
```
In this case, a value obtained from a header is compared using `startswith` call. This comparision is easily bypassed resulting in a CORS bypass. Given that similar bugs have been found in other languages as well, I think this PR would be a great addition to the exisitng python query pack.
The databases for CVE-2022-3457 can be downloaded from
``` …
```
=> WIP: Python: CORS Bypass

misc/bazel/rust.bzl, misc/bazel/semmle_code_stub/buildutils-internal/glibc_symbols_check.bzl, misc/bazel/semmle_code_stub/buildutils-internal/lipo.bzl
This is another shot at https://github.com/github/codeql/pull/17382, using a different and more lightweight approach.
This allows building the ruby and python (and in the future also rust) packs from within the codeql repository. This will:
* skip defining the glibc symbols checking, which only makes sense when building the release from the internal repository
* stub out our `universal_binary` rule, which we only need when building the release.
=> Bazel: stub internal repo parts needed for building rust binaries

cpp/ql/test/header-variant-tests/multi-target-includes/includes.expected, cpp/ql/test/library-tests/includes/include_next/includes.expected
The updated test results look more correct, as the documentation of `#include_next` [1] that it should start looking in the next directory in the search path. Before this update, the frontend was actually looking in the current directory first, which is incorrect.
[1] https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html
=> C++: Update expected test results after extractor changes

csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/test/utils/modelgenerator/dataflow/CaptureContentSummaryModels.expected, csharp/ql/test/utils/modelgenerator/dataflow/CaptureContentSummaryModels.ext.yml, csharp/ql/test/utils/modelgenerator/dataflow/CaptureContentSummaryModels.ql, csharp/ql/test/utils/modelgenerator/dataflow/Summaries.cs, java/ql/lib/semmle/code/java/dataflow/internal/ContentDataFlow.qll, java/ql/src/utils/modelgenerator/CaptureContentSummaryModels.ql, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, java/ql/test/utils/modelgenerator/dataflow/CaptureContentSummaryModels.expected, java/ql/test/utils/modelgenerator/dataflow/CaptureContentSummaryModels.ql, java/ql/test/utils/modelgenerator/dataflow/p/Factory.java, java/ql/test/utils/modelgenerator/dataflow/p/FinalClass.java, java/ql/test/utils/modelgenerator/dataflow/p/FluentAPI.java, java/ql/test/utils/modelgenerator/dataflow/p/ImmutablePojo.java, java/ql/test/utils/modelgenerator/dataflow/p/Inheritance.java, java/ql/test/utils/modelgenerator/dataflow/p/InnerClasses.java, java/ql/test/utils/modelgenerator/dataflow/p/InnerHolder.java, java/ql/test/utils/modelgenerator/dataflow/p/Joiner.java, java/ql/test/utils/modelgenerator/dataflow/p/MultipleImpl2.java, java/ql/test/utils/modelgenerator/dataflow/p/MultipleImpls.java, java/ql/test/utils/modelgenerator/dataflow/p/ParamFlow.java, java/ql/test/utils/modelgenerator/dataflow/p/Pojo.java, java/ql/test/utils/modelgenerator/dataflow/p/PrivateFlowViaPublicInterface.java, misc/scripts/models-as-data/generate_flow_model.py, shared/mad/codeql/mad/modelgenerator/ModelPrinting.qll
In this PR we introduce a new model generator query for Java and C#. The work is based on https://github.com/github/codeql/pull/8667.
This should not in any way be considered the final version of these queries.
=> Java/C#: Field based model generator (Experimental).

MODULE.bazel, go/actions/test/action.yml, go/extractor/autobuilder/build-environment.go, go/extractor/extractor.go, go/extractor/go.mod, go/ql/test/extractor-tests/diagnostics/CONSISTENCY/UnexpectedFrontendErrors.expected, go/ql/test/library-tests/semmle/go/Files/CONSISTENCY/UnexpectedFrontendErrors.expected, go/ql/test/library-tests/semmle/go/Function/TypeParamType.expected, go/ql/test/library-tests/semmle/go/Types/Aliases.expected, go/ql/test/library-tests/semmle/go/Types/Aliases.ql, go/ql/test/library-tests/semmle/go/Types/Field_getPackage.expected, go/ql/test/library-tests/semmle/go/Types/Field_hasQualifiedName2.expected, go/ql/test/library-tests/semmle/go/Types/Field_hasQualifiedName3.expected, go/ql/test/library-tests/semmle/go/Types/QualifiedNames.expected, go/ql/test/library-tests/semmle/go/Types/SignatureType_getNumParameter.expected, go/ql/test/library-tests/semmle/go/Types/SignatureType_getNumResult.expected, go/ql/test/library-tests/semmle/go/Types/StructFields.expected, go/ql/test/library-tests/semmle/go/Types/Types.expected, go/ql/test/library-tests/semmle/go/Types/aliases.go, go/ql/test/query-tests/Diagnostics/CONSISTENCY/UnexpectedFrontendErrors.expected, go/ql/test/query-tests/Diagnostics/ExtractionErrors.expected, go/ql/test/query-tests/Summary/CONSISTENCY/UnexpectedFrontendErrors.expected
This PR is an alternative to the line of work in #17058 which tries to keep the changes required to tolerate Go 1.23 more minimal. The main difference is that in #17058 we explicitly extract `Alias` types, store them in the database, and then consequently have to deal with type equality issues that arise from this. In contrast, we do not explicitly extract the `Alias` types in this PR and instead just use the Go compiler to resolve them to their underlying types directly. This has the benefit that much fewer changes are needed to tolerate Go 1.23 extraction and that the behaviour is the same as before Go 1.23. The downside is that no information about aliases is available to query writers.
=> Go: Support 1.23 (Transparent aliases)

python/ql/lib/semmle/python/security/dataflow/CleartextLoggingCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/CleartextStorageCustomizations.qll, python/ql/src/change-notes/2024-08-27-sensitive-certificate.md, python/ql/test/query-tests/Security/CWE-312-CleartextLogging/CleartextLogging.expected, python/ql/test/query-tests/Security/CWE-312-CleartextLogging/test.py, python/ql/test/query-tests/Security/CWE-312-CleartextStorage-py3/CleartextStorage.expected, python/ql/test/query-tests/Security/CWE-312-CleartextStorage-py3/test.py, python/ql/test/query-tests/Security/CWE-312-CleartextStorage/CleartextStorage.expected, python/ql/test/query-tests/Security/CWE-312-CleartextStorage/test.py
A certificate, such as an SSL certificate or x509 certificate, often does not contain sensitive data, so the cleartext storage and cleartext logging queries result in false positive alerts when considering them. This PR excludes certificates as sources for these queries.
=> Python: Exclude certificate classification fo sensitive data queries

shared/tree-sitter-extractor/src/extractor/mod.rs, shared/tree-sitter-extractor/src/trap.rs
This generalizes the location cache to allow multiple sources to be extracted in the same trap file, by adding `file_label` to `Location`, and therefore to location cache keys. This will be used by the Rust extractor.
=> Tree-sitter: allow multiple sources per trap file

.github/workflows/ruby-build.yml
Ports the changes needed to work with the latest version of `upload-artifact` that ignores hidden (`.`-prefixed) files by default.
=> Fix upload in Ruby build

csharp/downgrades/ab09ac8287516082b7a7367f8fda1862b1be47c5/upgrade.properties, csharp/ql/lib/upgrades/ba2201248071b2bf0bb52909b35014091d2e18a6/upgrade.properties, csharp/ql/lib/upgrades/dd813977f70fcbf737b0bbe9dc8297edff713168/upgrade.properties, csharp/ql/lib/upgrades/efcd69e086a26dd33395f2ddb3113b2849399040/upgrade.properties
This PR fixes trivial errors in a few upgrade.properties files.
=> C#: Fix trivial upgrade.properties errors

rust/README.md
Add a `README.md` for Rust, explaining how developers can get started.
I'm happy to take suggestions for the `TODO`s I've left in the doc; alternatively we can merge this as-is and come back to them later.
=> Rust: Add a README.md

docs/prepare-db-upgrade.md
The new names aren't great, so feel free to change them, but I think we do need an explicit example of updating two relations using one ql file.
=> Docs: Give clearer example of multiple query predicates in one ql file

javascript/ql/src/Security/CWE-312/ActionsArtifactLeak.qhelp, javascript/ql/src/Security/CWE-312/ActionsArtifactLeak.ql, javascript/ql/src/Security/CWE-312/examples/actions-artifact-leak-fixed.yml, javascript/ql/src/Security/CWE-312/examples/actions-artifact-leak.yml, javascript/ql/src/change-notes/2024-09-06-new-actions-artifact-leak-query.md, javascript/ql/test/query-tests/Security/CWE-312/.github/workflows/test.yml, javascript/ql/test/query-tests/Security/CWE-312/ActionsArtifactLeak.expected, javascript/ql/test/query-tests/Security/CWE-312/ActionsArtifactLeak.qlref
This query models the issue coined as [ArtiPACKED](https://www.bleepingcomputer.com/news/security/github-actions-artifacts-found-leaking-auth-tokens-in-popular-projects/) where the `actions/checkout` action stores the GITHUB_TOKEN into `.git/config` and then this directory gets included into an artifact.
The latest version of `actions/upload-artifact` has been patched to prevent hidden files to be included into the artifact. This query reports those cases where users are both using an unpatched version of `actions/upload-artifact` and also using `actions/checkout` in a way that persists credentials into `.git` directory.
=> Javascript: Query to detect GITHUB_TOKEN leaked in artifacts

rust/ql/test/.gitignore, rust/ql/test/extractor-tests/generated/File/File.expected, rust/tools/qltest.sh
For the moment this removes the possibility to set custom flags or env variables for the extractor via comments, but that can be added back easily if needed with a different mechanism (like an `env` file).
=> Rust: make ql tests extract files together

rust/ql/src/codeql-suites/rust-code-scanning.qls, rust/ql/src/codeql-suites/rust-security-and-quality.qls, rust/ql/src/codeql-suites/rust-security-experimental.qls, rust/ql/src/codeql-suites/rust-security-extended.qls
Add the core query suite `.qls` files for Rust.
=> Rust: Add query suites

cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedElement.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedStmt.qll, cpp/ql/test/library-tests/ir/ir/aliased_ir.expected, cpp/ql/test/library-tests/ir/ir/aliased_ssa_consistency.expected, cpp/ql/test/library-tests/ir/ir/aliased_ssa_consistency_unsound.expected, cpp/ql/test/library-tests/ir/ir/raw_consistency.expected, cpp/ql/test/library-tests/ir/ir/raw_ir.expected, cpp/ql/test/library-tests/ir/ir/unaliased_ssa_consistency.expected, cpp/ql/test/library-tests/ir/ir/unaliased_ssa_consistency_unsound.expected, cpp/ql/test/library-tests/syntax-zoo/aliased_ssa_consistency.expected, cpp/ql/test/library-tests/syntax-zoo/raw_consistency.expected, cpp/ql/test/library-tests/syntax-zoo/unaliased_ssa_consistency.expected
Note that although this fixes some inconsistencies this does not (yet) accurately reflect the semantics of `__finally` blocks. See the highlighted paragraph [here](https://learn.microsoft.com/en-us/cpp/cpp/try-finally-statement?view=msvc-170#:~:text=When%20the%20termination%20handler%20completes%2C%20execution%20continues%20after%20the%20__finally%20statement.%20However%20the%20guarded%20section%20ends%20(for%20example%2C%20via%20a%20goto%20out%20of%20the%20guarded%20body%20or%20a%20return%20statement)%2C%20the%20termination%20handler%20is%20executed%20before%20the%20flow%20of%20control%20moves%20out%20of%20the%20guarded%20section.).
Both DCA experiments are relevant. DCA shows a 10%~11% slowdown on keepassxc. It' not clear to me where this is coming from. I locally tried rerunning and I …
=> C++: Fix `__finally` related inconsistencies

csharp/.gitignore, csharp/.vscode/launch.json
The PR is adding various VSCode debug launch configurations for C# extraction.
=> C#: Add VSCode `launch.json`

csharp/extractor/Semmle.Extraction.CSharp/Entities/Indexer.cs, csharp/ql/lib/change-notes/2024-09-16-indexer-attributes.md, csharp/ql/test/library-tests/attributes/AttributeArguments.expected, csharp/ql/test/library-tests/attributes/AttributeElements.expected, csharp/ql/test/library-tests/attributes/ExperimentalAttributes.expected, csharp/ql/test/library-tests/attributes/PrintAst.expected, csharp/ql/test/library-tests/attributes/attributes.cs
In this PR we add extractor support for attributes on indexers.
With this change we now extract the attribute usage on the example below
```csharp
[Attribute]
public object this[int i] => return null;
```
=> C#: Extract attributes on indexers.

python/ql/test/2/extractor-tests/hidden/options, python/ql/test/extractor-tests/exo_path/options, python/ql/test/extractor-tests/filter-option/options, python/ql/test/extractor-tests/flags/options, python/ql/test/extractor-tests/identical_contents/options, python/ql/test/extractor-tests/paths/options, python/ql/test/extractor-tests/thrift/options, python/ql/test/library-tests/modules/spurious_init/options, python/ql/test/library-tests/thrift/options
The `**/src_archive/**` exclusion patterns seem to have to do with trying to exclude archived source files from being picked up for the extractor while running the test itself. However it seems that directory is not being used any more by `codeql` (which uses a `src` directory instead).
A `*.testproj` exclusion pattern will work in a more robust way, by excluding any file inside the database being built.
=> Python: replace `src_archive` exclusion patterns with `*.testproj` ones

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.18.4.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
Adding unified changelog for 2.18.4.
=> CodeQL 2.18.4 unified changelog

docs/codeql/codeql-language-guides/codeql-for-cpp.rst, docs/codeql/codeql-language-guides/codeql-for-go.rst, docs/codeql/codeql-language-guides/codeql-for-java.rst, docs/codeql/codeql-language-guides/codeql-for-javascript.rst, docs/codeql/codeql-overview/about-codeql.rst, docs/codeql/writing-codeql-queries/running-codeql-queries.rst
When this article was originally written, it needed to be all things to all people. Now that the CodeQL docs site is firmly focused on security researchers and anyone else who wants to learn how to write CodeQL queries, we can make the content more focused.
These updates aim to answer the following needs of security researchers:
- Determine if the effort of learning CodeQL is balanced by the additional opportunities to find vulnerabilities
- Identify a quick way to learn the language.
- Test my new query so I can report vulnerabilities and get them fixed/get bounty.
In addition, I've added metadata keywords to this article and the new article introduced by:
- https://github.com/github/codeql/pull/17361
This are intended to aid discoverability and we'll check the data analytics a month or …
=> Update "About CodeQL" to cover the information needs of security researchers better

csharp/ql/lib/semmle/code/csharp/dataflow/internal/BaseSSA.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll, csharp/ql/test/library-tests/csharp7/LocalTaintFlow.expected, csharp/ql/test/library-tests/dataflow/barrier-guards/BarrierFlow.cs, csharp/ql/test/library-tests/dataflow/barrier-guards/barrier-flow.expected, csharp/ql/test/library-tests/dataflow/barrier-guards/barrier-flow.ql, csharp/ql/test/library-tests/dataflow/local/DataFlowStep.expected, csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected, csharp/ql/test/library-tests/dataflow/tuples/DataFlowStep.expected, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
This PR adopts the newly introduced shared [SSA data-flow integration layer](https://github.com/github/codeql/pull/16884). A side-effect is that we get [phi-input barrier guards](https://github.com/github/codeql/pull/15985) for free, which had not previously been ported to C#.
=> C#: Adopt shared SSA data-flow integration

csharp/ql/lib/change-notes/2024-09-16-accessor-mad.md, csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, csharp/ql/test/library-tests/dataflow/external-models/Sinks.cs, csharp/ql/test/library-tests/dataflow/external-models/Sources.cs, csharp/ql/test/library-tests/dataflow/external-models/sinks.expected, csharp/ql/test/library-tests/dataflow/external-models/sinks.ext.yml, csharp/ql/test/library-tests/dataflow/external-models/srcs.expected, csharp/ql/test/library-tests/dataflow/external-models/srcs.ext.yml
In this PR we added support for `Attribute.Getter` and `Attribute.Setter` as a part of the models as data description in the `ext` field of a model.
Assume we have the following declarations.
```csharp
namespace N {
public class SourceAttribute : System.Attribute { }
public class MyClass {
[SourceAttribute]
public object TaggedSrcPropertyGetter { get; }
}
}
```
If we add the following source model
```yaml
- ["N", "SourceAttribute", false, "", "", "Attribute.Getter", "ReturnValue", "local", "manual"]
```
Then `TaggedSrcPropertyGetter` is considered a `local` source of taint.
=> C#: Add MaD support for `Attribute.Getter` and `Attribute.Setter`.

java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, java/ql/test/library-tests/dataflow/capture/B.java, java/ql/test/library-tests/dataflow/capture/inlinetest.expected, shared/dataflow/codeql/dataflow/VariableCapture.qll
Variable capture in constructors was only supported when the constructor was called directly - if the capture happened a call away, e.g. in the object initializer, which is a common pattern, then we failed to recognize it.
Fixes https://github.com/github/codeql/issues/17473
=> Java: Fix support for variable capture inside object initializers.

rust/ql/src/queries/summary/SummaryStats.ql, rust/ql/test/query-tests/diagnostics/SummaryStats.expected
Add a bit more data to `rust/summary/summary-statistics` (this query is intended for manual use on a project when you want to get a first impression of a database).
=> Rust: Add more summary stats.

javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/Contents.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowPrivate.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSummaryPrivate.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/TaintTrackingPrivate.qll, javascript/ql/lib/semmle/javascript/internal/flow_summaries/Arrays.qll, javascript/ql/lib/semmle/javascript/internal/flow_summaries/ForOfLoops.qll, javascript/ql/lib/semmle/javascript/internal/flow_summaries/Strings.qll, javascript/ql/lib/semmle/javascript/security/TaintedUrlSuffix.qll, javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssQuery.qll, javascript/ql/test/library-tests/Arrays/DataFlow.expected, javascript/ql/test/library-tests/Arrays/arrays.js, javascript/ql/test/library-tests/FlowSummary/tst.js, javascript/ql/test/library-tests/TaintedUrlSuffix/test.expected, javascript/ql/test/library-tests/TaintedUrlSuffix/test.ql, javascript/ql/test/library-tests/TaintedUrlSuffix/tst.js, javascript/ql/test/library-tests/TripleDot/arrays.js, javascript/ql/test/library-tests/TripleDot/tst.js, javascript/ql/test/query-tests/Security/CWE-078/IndirectCommandInjection/IndirectCommandInjection.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tst.js, javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/ClientSideUrlRedirect.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected
Previously, when reading an array element at a known index, we did not read values stored at an unknown index. We now properly read from unknown array indices.
However, this interacted poorly with how we handled `split('#')` and `split('?')` calls in `TaintedUrlSuffix`. In this case we want to block flow into the first element of the resulting array, while also transitioning from the `tainted-url-suffix` state to the `taint` state. Instead of the various hacks we've employed in the past, this is now modelled with the help of flow summaries.
Flow summaries cannot be query-specific and don't know anything about flow states (because those are query-specific), but I've adopted a solution where a flow summary can contribute so-called _optional_ steps and barriers identified by a name, which …
=> JS: Fix handling of constant array index reads, and fix the fallout

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll, csharp/ql/src/utils/modelgenerator/CaptureContentSummaryModels.ql, csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, csharp/ql/test/utils/modelgenerator/dataflow/Summaries.cs, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, java/ql/src/utils/modelgenerator/internal/CaptureTypeBasedSummaryModels.qll, java/ql/test/utils/modelgenerator/dataflow/p/InnerHolder.java, java/ql/test/utils/modelgenerator/dataflow/p/Joiner.java, java/ql/test/utils/modelgenerator/dataflow/p/MultiPaths.java, java/ql/test/utils/modelgenerator/dataflow/p/MultipleImpls.java, java/ql/test/utils/modelgenerator/dataflow/p/Pojo.java, java/ql/test/utils/modelgenerator/dataflow/p/PrivateFlowViaPublicInterface.java, shared/dataflow/codeql/dataflow/internal/ContentDataFlowImpl.qll, shared/mad/codeql/mad/modelgenerator/ModelPrinting.qll
If we apply the content based model generator to
- The Java SDK we get around 80k models.
- The .NET 8 Runtime we get around 500k models.
Many of these models are undesirable, primarily because of one of the following reasons
1. Due to the lack of type constraints, we get lots of models as "data" could have originated from lots of different implementations (and conversely for stores).
2. A model reads from a synthetic field that no other model writes to (and conversely).
With the changes proposed in this PR, applying the content based model generator to
- The Java SDK we get around 4k models.
- The .NET 8 Runtime we get around 5k models.
The issues are addressed in the following way:
1. We make a rough filtering on the APIs: Content based model generation is only considered for an API if …
=> C#/Java: Content based model generation improvements.

csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest1.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest2.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest3.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest4.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest5.expected, csharp/ql/test/library-tests/dataflow/threat-models/threat-models-flowtest6.expected, csharp/ql/test/query-tests/Security Features/CWE-020/UntrustedDataToExternalAPI.expected, csharp/ql/test/query-tests/Security Features/CWE-079/StoredXSS/StoredXSS.expected, csharp/ql/test/query-tests/Security Features/CWE-079/XSSAsp/XSS.expected, csharp/ql/test/query-tests/Security Features/CWE-089/SqlInjection.expected, csharp/ql/test/query-tests/Security Features/CWE-201/ExposureInTransmittedData/ExposureInTransmittedData.expected, csharp/ql/test/query-tests/Security Features/CWE-321/HardcodedSymmetricEncryptionKey/HardcodedSymmetricEncryptionKey.expected, csharp/ql/test/query-tests/Security Features/CWE-838/InappropriateEncoding.expected, go/ql/test/library-tests/semmle/go/frameworks/Beego/TaintedPath.expected, go/ql/test/library-tests/semmle/go/frameworks/Echo/OpenRedirect.expected, go/ql/test/library-tests/semmle/go/frameworks/Echo/TaintedPath.expected, go/ql/test/library-tests/semmle/go/frameworks/Encoding/jsoniter.expected, go/ql/test/library-tests/semmle/go/frameworks/Gin/TaintedPath.expected, go/ql/test/library-tests/semmle/go/frameworks/Gorestful/gorestful.expected, go/ql/test/query-tests/Security/CWE-020/IncompleteHostnameRegexp/IncompleteHostnameRegexp.expected, go/ql/test/query-tests/Security/CWE-022/TaintedPath.expected, go/ql/test/query-tests/Security/CWE-022/UnsafeUnzipSymlink.expected, go/ql/test/query-tests/Security/CWE-022/ZipSlip.expected, go/ql/test/query-tests/Security/CWE-078/CommandInjection.expected, go/ql/test/query-tests/Security/CWE-078/StoredCommand.expected, go/ql/test/query-tests/Security/CWE-347/MissingJwtSignatureCheck.expected, go/ql/test/query-tests/Security/CWE-601/BadRedirectCheck/BadRedirectCheck.expected, go/ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirect.expected, go/ql/test/query-tests/Security/CWE-643/XPathInjection.expected
https://github.com/github/codeql/pull/17504 didn't update the test expectations for all the affected languages.
=> C#/Go: Fix test expectations including double space

.github/workflows/go-tests.yml
Go CI should have run for https://github.com/github/codeql/pull/17504. Hopefully this change will fix it.
I did consider whether to restrict to the shared libraries that are actually used by Go, but I think we will forget to update it.
=> Go: Run CI when shared libraries change

csharp/ql/lib/change-notes/2024-09-19-reduced-dataflow-nodes.md, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
This addresses a problem observed when libraries define a very large number of types with large class hierarchies, for example as part of generated code. Since user code is very unlikely to refer to all or even most of them, by excluding such code from dataflow node generation and therefore from the C# dataflow hooks' idea of a "relevant" type, we can make many of the type predicates defined in DataFlowPrivate.qll very much cheaper.
See discarded variant https://github.com/github/codeql/pull/17482 for some discussion.
=> C#: Restrict dataflow node creation to source and source-referenced entities

misc/codegen/lib/schemadefs.py, misc/codegen/loaders/schemaloader.py, misc/codegen/test/test_schemaloader.py
Reverts github/codeql#17514, as it's superseded by a better approach implemented in https://github.com/github/codeql/pull/17523
=> Revert "Codegen: allow to include `.py` files in `schema.py`"

csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.ql, ruby/ql/test/library-tests/controlflow/graph/Cfg.expected, ruby/ql/test/library-tests/controlflow/graph/Cfg.ql, rust/ql/test/library-tests/controlflow/Cfg.expected, rust/ql/test/library-tests/controlflow/Cfg.ql, shared/controlflow/codeql/controlflow/Cfg.qll, swift/ql/test/library-tests/controlflow/graph/Cfg.expected, swift/ql/test/library-tests/controlflow/graph/Cfg.ql
The original motivation for using `@kind graph` was to be able to visualize CFGs in VS Code. However, now that we have `View CFG`, this is no longer needed. Moreover, `@kind graph` often has spurious reorderings of the output, and there are some known limitations (such as missing multi-edges, IIRC), so it is not well suited for qltest.
=> Shared: Do not use `@kind graph` for CFG test output

misc/codegen/lib/schema.py, misc/codegen/lib/schemadefs.py, misc/codegen/loaders/schemaloader.py, misc/codegen/test/test_schemaloader.py, rust/schema/__init__.py, rust/schema/prelude.py
This allows to fully reannotate classes with the `@annotate` decoration. Properties can be modified by adding property modifiers to the special `_` placeholder. Property modifiers can also be undone with `~`. See unit tests for example (`defs` namespacing is only used in tests).
=> Codegen: allow full annotation of classes

misc/codegen/generators/qlgen.py, misc/codegen/generators/rusttestgen.py, misc/codegen/lib/schema.py, misc/codegen/lib/schemadefs.py, misc/codegen/loaders/schemaloader.py, misc/codegen/test/test_cppgen.py, misc/codegen/test/test_dbschemegen.py, misc/codegen/test/test_qlgen.py, misc/codegen/test/test_schemaloader.py
This is mostly an internal cleanup where some `schema.Class` special properties are moved to pragmas, allowing the latter to have parameters. In the long run this allows easier integration of new domain-specific things without having to pollute `schema.Class` and `schemaloader`.
For the moment I've kept some class annotations not as pragmas (`hideable`, `group`, `test_with`) , because they are automatically inherited from super classes, which the current pragma mechanism does not give. I might do another pass to get those in the pragmas as well.
Finally, there's also a finer distinction between class-only pragmas and general pragmas, so that for example `ql_test.collapse_hiearchy` can't be applied any more on a property, as that does not make any sense.
=> Codegen: parametrized pragmas

misc/codegen/generators/qlgen.py, misc/codegen/generators/rusttestgen.py, misc/codegen/lib/ql.py, misc/codegen/lib/schema.py, misc/codegen/lib/schemadefs.py, misc/codegen/loaders/schemaloader.py, misc/codegen/test/test_cppgen.py, misc/codegen/test/test_dbschemegen.py, misc/codegen/test/test_qlgen.py, misc/codegen/test/test_schemaloader.py
Follow up to https://github.com/github/codeql/pull/17532, introducting inherited pragmas and porting to them everything that remains.
=> Codegen: introduce inherited pragmas and move remaining decorations

misc/codegen/generators/rustgen.py, misc/codegen/lib/rust.py, misc/codegen/lib/schemadefs.py, misc/codegen/templates/rust_classes.mustache
By using the `rust.detach` pragma on a property, we make that property not appear in the generated struct as a field, and provide instead a `generated::Class::emit_property` function that can be used to emit the corresponding TRAP entry independently.
=> Rust/Codegen: allow to "detach" property emission

misc/codegen/generators/rusttestgen.py, misc/codegen/lib/schema.py
Now code blocks in `desc` modifiers of properties are also brought in the generated test code.
=> Rust: take test code also from property descriptions

python/ql/lib/change-notes/2024-09-20-const-compare-gaurd.md, python/ql/lib/semmle/python/dataflow/new/BarrierGuards.qll, python/ql/lib/semmle/python/security/dataflow/CodeInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/CommandInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/LdapInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/LogInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/PathInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/PolynomialReDoSCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/ReflectedXSSCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/ServerSideRequestForgeryCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/SqlInjectionCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/UnsafeDeserializationCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/UrlRedirectCustomizations.qll, python/ql/src/experimental/Security/CWE-074/TemplateInjectionCustomizations.qll, python/ql/src/experimental/Security/CWE-091/XsltInjectionCustomizations.qll, python/ql/src/experimental/semmle/python/security/dataflow/EmailXss.qll, python/ql/src/experimental/semmle/python/security/injection/CsvInjection.qll, python/ql/test/library-tests/dataflow/tainttracking/commonSanitizer/InlineTaintTest.ql, python/ql/test/library-tests/dataflow/tainttracking/commonSanitizer/test_const_compare.py
Renames `StringConstCompareBarrier` to `ConstCompareBarrier` and expands it to cover comparisons to additional constats such as `None`. 
This reduces FP flow in cases such as `if x is None: return x`.
=> Python: Expand `StringConstCompareBarrier` sanitizer gaurds to cover additional constants

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ProductFlow.qll, go/ql/test/experimental/CWE-090/LDAPInjection.expected, go/ql/test/experimental/CWE-1004/CookieWithoutHttpOnly.expected, go/ql/test/library-tests/semmle/go/frameworks/XNetHtml/ReflectedXss.expected, go/ql/test/query-tests/Security/CWE-078/CommandInjection.expected, java/ql/test/experimental/query-tests/security/CWE-078/CommandInjectionRuntimeExecLocal.expected, java/ql/test/library-tests/frameworks/apache-commons-lang3/flow.expected, java/ql/test/query-tests/security/CWE-078/ExecTainted.expected, ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.expected, ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected, ruby/ql/test/library-tests/frameworks/action_controller/params-flow.expected, ruby/ql/test/query-tests/experimental/LdapInjection/Ldapinjection.expected, ruby/ql/test/query-tests/security/cwe-079/ReflectedXSS.expected, ruby/ql/test/query-tests/security/cwe-079/StoredXSS.expected, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected, ruby/ql/test/query-tests/security/cwe-094/CodeInjection/CodeInjection.expected, ruby/ql/test/query-tests/security/cwe-117/LogInjection.expected, ruby/ql/test/query-tests/security/cwe-1333-regexp-injection/RegExpInjection.expected, ruby/ql/test/query-tests/security/cwe-134/TaintedFormatString.expected, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll, shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll, swift/ql/test/library-tests/dataflow/taint/core/Taint.expected, swift/ql/test/query-tests/Security/CWE-078/CommandInjection.expected, swift/ql/test/query-tests/Security/CWE-311/CleartextStorageDatabase.expected, swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.expected, swift/ql/test/query-tests/Security/CWE-757/InsecureTLS.expected
This PR moves the `TNodeEx` `newtype` from `DataFlowImpl.qll` into `DataFlowImplCommon.qll` (and makes it `cached`). The purpose of doing this is to avoid an additional `newtype` creation for all instantiations of the data flow library, and as witnessed by the DCA runs it has a very positive impact on memory/cache usage (and in general also a modest impact on timing).
Before moving the `newtype`, the first commit removes the Boolean `hasRead` column from `TNodeImplicitRead`, in order to the size of the `newtype` when later caching it. This commit then also adjusts the generated `edges` relation by never revealing the implicit reads that happen at sinks.
Commit-by-commit review is suggested.
=> Data flow: Cache `TNodeEx`

python/ql/lib/semmle/python/Concepts.qll, python/ql/lib/semmle/python/frameworks/FastApi.qll, python/ql/lib/semmle/python/frameworks/Starlette.qll, python/ql/src/change-notes/2024-08-26-Cors-misconfiguration-middleware.md, python/ql/src/experimental/Security/CWE-942/CorsMisconfigurationMiddleware.qhelp, python/ql/src/experimental/Security/CWE-942/CorsMisconfigurationMiddleware.ql, python/ql/src/experimental/Security/CWE-942/CorsMisconfigurationMiddlewareBad.py, python/ql/src/experimental/Security/CWE-942/CorsMisconfigurationMiddlewareGood.py, python/ql/test/experimental/meta/ConceptsTest.qll, python/ql/test/library-tests/frameworks/fastapi/middleware.py, python/ql/test/library-tests/frameworks/starlette/Middleware.py, python/ql/test/query-tests/Security/CWE-942-CorsMisconfigurationMiddleware/CorsMisconfigurationMiddleware.expected, python/ql/test/query-tests/Security/CWE-942-CorsMisconfigurationMiddleware/CorsMisconfigurationMiddleware.qlref, python/ql/test/query-tests/Security/CWE-942-CorsMisconfigurationMiddleware/fastapi.py, python/ql/test/query-tests/Security/CWE-942-CorsMisconfigurationMiddleware/starlette.py
Model FastAPI & Starlette CORS Middlewares for misconfiguration
=> Python: Add Support for CORS Middlewares

go/ql/lib/semmle/go/Types.qll, go/ql/test/library-tests/semmle/go/PrintAst/PrintAst.expected, go/ql/test/library-tests/semmle/go/PrintAst/PrintAstExcludeComments.expected
This avoids our having types that are distinct both in the database and are distinguishable in QL, but which pretty-print identically.
=> Go: Expose whether functions are variadic in their pp() output

go/ql/src/Security/CWE-681/IncorrectIntegerConversionQuery.ql, go/ql/src/change-notes/2024-09-24-incorrect-integer-conversion-query-precision.md
`very-high` implies near 0 false positives and we have run into a number and an entire class
=> Downgrade IncorrectIntegerConversionQuery precision to high

cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/InvalidPointerToDereference.qll, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
The data flow library doesn't handle inlined sink definitions that well anymore, so fix the offending C++ query.
=> Cpp: Replace sink inlining with a forward scan from source.

cpp/ql/lib/semmle/code/cpp/Type.qll
Wrapping breaks the highlighting in VSCode, making the QLDoc difficult to read.
=> C++: Do not wrap quoted text to the next line

javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.ql
Change the query id for XssWithAdditionalSources.ql to `js/xss-additional-sources-dom-test` to avoid conflict with Xss.ql
=> Resolve id conflict with XssWithAdditionalSources.ql

csharp/ql/lib/semmle/code/csharp/security/dataflow/flowsinks/Html.qll, csharp/ql/src/change-notes/2024-09-25-attribute-collection-sink.md, csharp/ql/test/query-tests/Security Features/CWE-079/XSSAsp/AspInline.expected, csharp/ql/test/query-tests/Security Features/CWE-079/XSSAsp/XSS.cs, csharp/ql/test/query-tests/Security Features/CWE-079/XSSAsp/XSS.expected
In this PR we remove the indexer and `Add` method of `System.Web.UI.AttributeCollection` as possible HTML sinks as the information is HTML encoded when the control is rendered.
This can be confirmed by running (needs to be a .NET Framework app).
```csharp
using System;
using System.Web.UI;
using System.Web.UI.WebControls;
class Program
{
static void Main(string[] args)
{
Button b = new Button();
b.Attributes.Add("my_key", "<some value & my stuff");
b.Attributes["my_index_key"] = "my_<index&_value";
b.RenderControl(new HtmlTextWriter(Console.Out));
}
}
```
=> C#: `AttributeCollection` is no longer considered a HTML sink.

java/kotlin-extractor2/src/main/kotlin/KotlinExtractor.kt, java/kotlin-extractor2/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor2/src/main/kotlin/KotlinUsesExtractor.kt, java/kotlin-extractor2/src/main/kotlin/TrapFileWriter.kt, java/kotlin-extractor2/src/main/kotlin/TrapWriter.kt, java/kotlin-extractor2/src/main/kotlin/utils/Logger.kt, java/kotlin-extractor2/src/main/kotlin/utils/TypeResults.kt
This PR formats all `.kt` files in IDEA. (It helps in keeping the upcoming diffs small)
=> KE2: Format code in IDEA

java/ql/lib/ext/java.lang.model.yml
This is just to block speculative flow through these.
=> Java: Add a couple of neutrals

java/ql/lib/semmle/code/java/security/Sanitizers.qll
Looking through the data from my initial MRVA top 100 speculative taint run, these additional types came up as potentially relevant to sanitize. The temporals I've also seen pop up before. This should help guard against FP flow going too much off the rails.
I'll run dca before phrasing the change note.
=> Java: Add more type-based sanitizers.

rust/ql/lib/codeql/rust/controlflow/internal/ControlFlowGraphImpl.qll, rust/ql/test/library-tests/controlflow/CONSISTENCY/CfgConsistency.expected, rust/ql/test/library-tests/controlflow/Cfg.expected, rust/ql/test/library-tests/controlflow/test.rs
Adds a bunch of test cases for functions with incorrect CFGs.
=> Rust: Add more CFG tests

java/ql/lib/ext/java.lang.model.yml, java/ql/lib/ext/java.util.model.yml, java/ql/test/library-tests/dataflow/collections/containerflow.expected
The comment about `WithoutElement` in relation to the `remove` methods was wrong, so fix that. Also, a couple of very small actual tweaks in relation to that: `Set.clear` should apply to overrides, and add neutrals for `Collection.remove` and `Comparable.compareTo`.
=> Java: Minor model tweak and comment fix.

cpp/ql/test/library-tests/macros/inmacroexpansion/inmacroexpansion.expected, cpp/ql/test/library-tests/macros/inmacroexpansion/test.cpp
Observe that these changes demonstrate that checking for expansions currently doesn't completely work as one might expect. I currently don't plan to fix this, was just noticing that we were missing some test coverage here.
=> C++: Add more macro expansion tests

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll, java/ql/lib/ext/java.lang.model.yml, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, java/ql/src/utils/modeleditor/ModelEditor.qll, java/ql/test/ext/TopJdkApis/TopJdkApisTest.expected
Neutrals generally have little impact on the analysis, but having a neutral like `Map.containsKey` also cover `HashMap.containsKey` makes a lot of sense. This might remove a tiny bit of source dispatch for low-confidence dispatch to source implementations of such methods, as that's AFAIR the only touchpoint between neutrals and analysis semantics.
=> Java/C#: Add overrides to the interpretation of neutral MaD models.

go/codeql-extractor.yml, go/extractor/configurebaseline/configurebaseline.go, go/extractor/extractor.go, go/extractor/util/extractvendordirs.go, go/ql/integration-tests/extract-vendor/test.py
This was already supported but didn't have a documented extractor option. We also now log when this mode is active.
=> Go: add extractor option for vendor-directory extraction

javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll, javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll, javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/ExceptionXssQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/StoredXssQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeHtmlConstructionQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/XssThroughDomQuery.qll, javascript/ql/test/library-tests/TaintBarriers/tests.ql, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/ConsistencyDomBasedXss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected
Fixes a bug that caused cached barriers nodes to be re-evaluated. Specifically, this predicate in `TaintTrackingPrivate` was re-evaluated due to the cached `AdditionalSanitizerGuardNode` inheriting from the query-specific `SanitizerGuard`:
```codeql
private class SanitizerGuardAdapter extends DataFlow::Node instanceof TaintTracking::AdditionalSanitizerGuardNode {
...
}
cached
predicate defaultTaintSanitizer(DataFlow::Node node) {
node instanceof DataFlow::VarAccessBarrier or
node = MakeBarrierGuard<SanitizerGuardAdapter>::getABarrierNode() // transitively depends on SanitizerGuardNode
}
```
The `AdditionalSanitizerGuardNode` class no longer inherits from `SanitizerGuardNode` which means its `sanitizes/blocks` predicates have their own rootdef now.
This revealed a bug in the some of the …
=> JS: Fix bug causing re-evaluation of cached barriers

java/kotlin-extractor2/src/main/kotlin/KotlinExtractor.kt
We now only call analyze once, on the source module, and concurrency is possible.
Review will be easier with `?w=1`.
=> KE2: Refactor the top level a bit

python/ql/lib/semmle/python/frameworks/Stdlib.model.yml, python/ql/test/experimental/query-tests/Security/CWE-409/DecompressionBombs.expected, python/ql/test/library-tests/frameworks/urllib/InlineTaintTest.expected, python/ql/test/library-tests/frameworks/urllib/InlineTaintTest.ql, python/ql/test/library-tests/frameworks/urllib/taint_test.py
Adds a model for `urllib.parse.parse_qs` and a test for urllib.
The change note about several new models for std lib should cover this model also.
=> Python: model `urllib.parse.parse_qs`

go/ql/integration-tests/test-extraction/src/go.mod, go/ql/integration-tests/test-extraction/src/pkg1/def.go, go/ql/integration-tests/test-extraction/src/pkg1/def_blackbox_test.go, go/ql/integration-tests/test-extraction/src/pkg1/def_test.go, go/ql/integration-tests/test-extraction/src/pkg2/use.go, go/ql/integration-tests/test-extraction/test.expected, go/ql/integration-tests/test-extraction/test.py
This adds a case exercising the need for packages to be visited in topological order (cross-package type variable references), and a `_test` package that wouldn't exist in `go list` output without the `-test` flag. Unfortunately I couldn't reproduce the circumstance where that causes a crash, but by instrumenting the code that invokes `go list` I can see that with the `-test` flag we get everything we need out of one `go list` run, whereas without it we fall back to the slow path that issues individual `go list` queries on a per package basis.
=> Go: augment test-extraction tests

java/ql/src/Metrics/Summaries/GeneratedVsManualCoverageQuery.qll, shared/mad/codeql/mad/modelgenerator/internal/ModelGeneratorImpl.qll
Also, another minor fix to one of the Java tests that reports *generated* models - it should take all generated models into account (and not only `df` generated models).
=> C#/Java: Only use heuristic if no content based model exist (in mixed mode). 

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll, python/ql/lib/semmle/python/frameworks/Stdlib.qll, python/ql/test/library-tests/dataflow/coverage/test_builtins.py
=> Python: All dict constructor args are relevant

rust/ql/lib/codeql/rust/elements/AssignmentOperation.qll, rust/ql/lib/codeql/rust/elements/internal/VariableImpl.qll, rust/ql/lib/rust.qll, rust/ql/test/library-tests/variables/Cfg.expected, rust/ql/test/library-tests/variables/variables.expected, rust/ql/test/library-tests/variables/variables.ql, rust/ql/test/library-tests/variables/variables.rs
Taking the address of a variable `x` via `&(mut) x` neither reads nor writes the variable, so the access to `x` should neither be a `VariableReadAccess` nor a `VariableWriteAccess`. This also includes implicit references in compound assignments `x += y` which [really means](https://doc.rust-lang.org/std/ops/trait.AddAssign.html) `(&mut x).add_assign(y)`.
Note that once we implement SSA support, then (some) variable references will be modeled as uncertain variable writes.
=> Rust: `&(mut) x` is neither a read nor a write

shared/ssa/codeql/ssa/Ssa.qll
Adds `BarrierGuardWithState<>` for when you need a barrier guard where the flow state is part of the signature.
In most cases one could get by with just implementing separate barrier guards for each flow state, but in JS we need this in order to share barrier guards between the shared library and old data flow library.
=> SSA: Add BarrierGuardWithState

javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/query-tests/Security/CWE-020/UntrustedDataToExternalAPI/UntrustedDataToExternalAPI.expected, javascript/ql/test/query-tests/Security/CWE-078/CommandInjection/CommandInjection.expected, javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/StoredXss/StoredXss.expected, javascript/ql/test/query-tests/Security/CWE-089/untyped/SqlInjection.expected, javascript/ql/test/query-tests/Security/CWE-201/PostMessageStar.expected, javascript/ql/test/query-tests/Security/CWE-312/BuildArtifactLeak.expected, javascript/ql/test/query-tests/Security/CWE-312/CleartextLogging.expected, javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/ServerSideUrlRedirect.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/Consistency.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingMergeCall/PrototypePollutingMergeCall.expected
- Filenames are now relative to the test case, not the qlpack
- Data flow paths going through an implicit read have changed slightly
=> JS DataFlow: Update tests after merging in 'main'

docs/codeql/codeql-language-guides/extensible-predicates.rst, docs/codeql/ql-language-reference/modules.rst, docs/codeql/ql-language-reference/ql-language-specification.rst, docs/codeql/ql-language-reference/types.rst
This PR introduces public-facing documentation around the experimental `QlBuiltins::BigInt` type.
- **Fix trailing whitespace in docs**: applies the .rst formatter to fix whitespace. For this reason, reviewing commit-by-commit is recommended.
- **Initial BigInt documentation**: Basic docs.
=> BigInt Documentation

rust/ql/consistency-queries/CfgConsistency.ql, rust/ql/lib/codeql/rust/controlflow/internal/Completion.qll, rust/ql/lib/codeql/rust/controlflow/internal/ControlFlowGraphImpl.qll, rust/ql/lib/codeql/rust/controlflow/internal/Splitting.qll, rust/ql/test/library-tests/controlflow/Cfg.expected
This PR implements `ConditionalCompletionSplitting`, similar to how its done for other languages (C#, Ruby, and Swift). The idea is to record information about the Boolean value of sub expressions in order to (a) have all expressions be post-order in the CFG, and (b) provide more accurate information for a future guards library.
Before this PR, logical negation expressions were in fact post-order, but the dominance information was lost. For example, this program
```rust
fn test_if_not_operator(a: bool) -> bool {
if !a {
true
} else {
false
}
}
```
has the following CFGs before and after
<details><summary>Before</summary>
```mermaid
flowchart TD
1["enter test_if_not_operator"]
10["BlockExpr"]
11["false"]
2["exit test_if_not_operator"]
3["exit test_if_not_operator (normal)"]
4["BlockExpr"] …
```
=> Rust: Implement `ConditionalCompletionSplitting`
