cpp/ql/test/experimental/query-tests/Security/CWE/CWE-125/semmle/tests/test.cpp
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-125/semmle/tests/test1.cpp
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-125/semmle/tests/test2.cpp
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-125/semmle/tests/test3.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/flowOut.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/self-Iterator.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/true_upon_entry.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-131/NoSpaceForZeroTerminator/test.c
cpp/ql/test/query-tests/Security/CWE/CWE-131/NoSpaceForZeroTerminator/test.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-131/NoSpaceForZeroTerminator/test2.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/ArithmeticTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/IntegerOverflowTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/main.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/test.c
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/test3.c
cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/test4.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-497/semmle/tests/tests2.cpp

In QLtest we do not have linkage awareness, so having multiple functions with the same name in the same test causes ODR violations.

C++: Fix ODR violations in tests

---

rust/ql/test/query-tests/unusedentities/UnusedVariable.expected
rust/ql/test/query-tests/unusedentities/main.rs

More test cases for unused variables.  Confirms that the issue producing spurious results for `None` matches is due to use of unqualified enum values that are being misrecognized as variables.

Rust: More test cases for unused variables

---

rust/ql/lib/codeql/rust/printast/PrintAst.qll
rust/ql/lib/codeql/rust/printast/PrintAstNode.qll
rust/ql/src/queries/ide-contextual-queries/printAst.ql

- Turn `PrintAst` into a parameterized module, parameterizing over relevant nodes. This means that we no longer need to cache `getOrder(PrintAstNode node)`, which could be really expensive to compute in full on some DBs.
- `getPrimaryQlClasses` already concats all `getAPrimaryQlClass`es, so the extra `concat` in `prettyPrint` is not needed.

Rust: `PrintAst` improvements

---

cpp/ql/lib/change-notes/2024-10-07-range-analysis-of-getc.md
cpp/ql/lib/semmle/code/cpp/rangeanalysis/SimpleRangeAnalysis.qll
cpp/ql/src/Security/CWE/CWE-129/ImproperArrayIndexValidation.ql
cpp/ql/src/change-notes/2024-10-07-unclear-array-index-validation.md
cpp/ql/test/query-tests/Security/CWE/CWE-129/semmle/ImproperArrayIndexValidation/ImproperArrayIndexValidation.expected
cpp/ql/test/query-tests/Security/CWE/CWE-129/semmle/ImproperArrayIndexValidation/test1.c

This PR modernizes the old _low precision_ `cpp/unclear-array-index-validation` by getting rid of the old DefaultTaintTracking inherited barriers and replacing them with a more precise `BarrierGuard` instantiation, and uses of `SimpleRangeAnalysis`.
I've started two DCA runs:
- A `nightly` one to test the impact of the changes to `SimpleRangeAnalysis`
- A run with just `cpp/unclear-array-index-validation` to test the changes to that query.
Since this query isn't included in any security suite I'm not sure how much you care about the result changes on `cpp/unclear-array-index-validation`?
I did a diff MRVA run to test the results, and they look reasonable.
The new results are TPs. They essentially look like:
```cpp
c = fgetc(fin);
while(c != EOF) { …
```

C++: Modernize `cpp/unclear-array-index-validation`

---

rust/ql/lib/codeql/rust/elements/internal/VariableImpl.qll
rust/ql/test/library-tests/controlflow/Cfg.expected
rust/ql/test/library-tests/variables/Cfg.expected
rust/ql/test/library-tests/variables/variables.expected
rust/ql/test/library-tests/variables/variables.ql
rust/ql/test/library-tests/variables/variables.rs
shared/util/codeql/util/DenseRank.qll

Add AST logic for identifying captured variables.
I identified and fixed two bugs as well:
- Actually use the inner scope in `variableAccessCandInScope`, as the comment says.
- Account for `rank` being potentially non-dense, by applying a newly introduced `DenseRank` library.

Rust: Account for captured variables

---

rust/ql/lib/codeql/rust/elements/internal/VariableImpl.qll
rust/ql/test/library-tests/variables/variables.expected
rust/ql/test/query-tests/unusedentities/UnusedVariable.expected
rust/ql/test/query-tests/unusedentities/main.rs

Temporary workaround for misrecognising enum constants as variable names.  This is not always accurate (see the comment) but should lean towards too few things being recognised as variables rather than too many, which is better for the quality of results.
@hvitved

Rust: Restrict variables to lowercase (for now).

---

csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImpl.qll
csharp/ql/lib/semmle/code/csharp/controlflow/internal/Splitting.qll
ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImpl.qll
ruby/ql/lib/codeql/ruby/controlflow/internal/Splitting.qll
rust/ql/lib/codeql/rust/controlflow/internal/ControlFlowGraphImpl.qll
rust/ql/lib/codeql/rust/controlflow/internal/Splitting.qll
shared/controlflow/codeql/controlflow/Cfg.qll
shared/util/codeql/util/Void.qll
swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImplSpecific.qll
swift/ql/lib/codeql/swift/controlflow/internal/Splitting.qll

Ideally, I would have liked for `SplitImplementations::ConditionalCompletionSplitting` to be parameterized over `ConditionalCompletionSplittingInput` instead of having the outer `MakeWithSplitting` be parameterized over it, but then it would not be possible to extend the abstract `SplitImpl` class.

Shared `ConditionalCompletionSplitting` implementation

---

cpp/ql/lib/change-notes/2024-10-09-fopen-taint.md
cpp/ql/lib/semmle/code/cpp/models/implementations/Fopen.qll
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp

Ideally this should've been done through MaD, but considering that we had the `Fopen` class already I couldn't really be bothered to convert it to MaD 😂
I'll run DCA once that's unbroken.

C++: Add taint through `fopen`

---

rust/ql/lib/codeql/rust/controlflow/internal/SuccessorType.qll

After the simplification of break/continue labels in #17644 these types are no longer used.

Rust: Remove unused types

---

cpp/ql/lib/semmle/code/cpp/PrintAST.qll
cpp/ql/test/examples/expressions/PrintAST.expected
cpp/ql/test/library-tests/ir/ir/PrintAST.expected

C++: Print handler parameters in PrintAST

---

python/ql/lib/change-notes/2024-10-09-finditer-match.md
python/ql/lib/semmle/python/frameworks/Stdlib.qll
python/ql/test/library-tests/frameworks/stdlib/test_re.py

Do we want a change note for this?

Python: model that `re.finditer` returns an iterable of `re.Match` objects

---

rust/ql/lib/codeql/rust/controlflow/internal/Completion.qll
rust/ql/lib/codeql/rust/controlflow/internal/ControlFlowGraphImpl.qll
rust/ql/test/library-tests/controlflow/Cfg.expected
rust/ql/test/library-tests/controlflow/test.rs

The primary goal of this PR is to handle the `?` operator (`TryExpr`) in the CFG, as that is currently the cause of dead-ends.
The PR does a few other things as well:
* Fixes a bug where abnormal control flow in the scrutinee of a match expression would incorrectly continue to match arms.
* Simplifies the implementation of `return` to use a standard tree.
With this PR, the code
```rust
fn test_question_mark_operator_1(s: &str) -> Option<i32> {
str.parse::<u32>()? + 4
}
```
results in the CFG below. The CFG is roughly as if the `a?` operator is sugar for `(if a.is_ok() { a.unwrap() } else { return None })` which I think is a fine way to handle it. But, do note that `match` edges are not created in the CFG, so a successful `?` will not look the same in the CFG as a succesfull match on …

Rust: Handle question mark operator in CFG

---

rust/ql/lib/codeql/rust/controlflow/internal/Completion.qll

Rename predicate as dicussed in https://github.com/github/codeql/pull/17686#pullrequestreview-2362633929.

Rust: Rename isIrrefutablePattern to isExhaustiveMatch

---

rust/ql/test/query-tests/unusedentities/main.rs

Changes to unused variable.
- update test annotations following the changes to `.expected` results in https://github.com/github/codeql/pull/17659 .
- ~disable the workaround for `rust/unused-variable` being too noisy.~ --- still too noisy
- DCA run for testing.

Rust: Unused variable follow-up work

---

rust/ql/consistency-queries/SsaConsistency.ql
rust/ql/lib/codeql/rust/dataflow/Ssa.qll
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
rust/ql/lib/codeql/rust/elements/internal/VariableImpl.qll
rust/ql/test/library-tests/variables/Cfg.expected
rust/ql/test/library-tests/variables/Ssa.expected
rust/ql/test/library-tests/variables/Ssa.ql
rust/ql/test/library-tests/variables/variables.expected
rust/ql/test/library-tests/variables/variables.rs

This PR adds an initial static single assignment (SSA) library to Rust.
In this first version, we restrict the analysis to variables that are either immutable, or mutable with the following constraints:
- the variable is not captured, and
- the variable is not borrowed, either explicitly `& mut x` or [implicitly as a method call receiver](https://doc.rust-lang.org/reference/expressions/method-call-expr.html) `x.foo()`.
We may be able to relax these constraints, but that will be done follow-up.

Rust: Initial SSA implementation

---

rust/ql/lib/codeql/rust/controlflow/internal/Completion.qll

Rust: add MacroPat to isExhaustiveMatch

---

go/ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll

Specifically the disjunct for this.getPos() != -1. Running on uber/aresdb, before we had this:
```
2403   ~1%    {3} r6 = JOIN `DataFlowUtil::SummarizedParameterNode.getPos/0#dispred#70a2aab4` WITH `DataFlowPrivate::FlowSummaryNode.getSummarizedCallable/0#dispred#e79ea9be` ON FIRST 1 OUTPUT Lhs.1, Lhs.0, Rhs.1
9149774   ~5%    {4}    | JOIN WITH `Types::SignatureType.getParameterType/1#dispred#2c11bb7b_102#join_rhs` ON FIRST 1 OUTPUT Lhs.2, Rhs.1, Lhs.1, Rhs.2
923   ~9%    {2}    | JOIN WITH `Scopes::Callable.getType/0#dispred#55a0e6a2` ON FIRST 2 OUTPUT Lhs.2, Lhs.3
```
We add a binding pragma to make it not bind on this.getPos() until necessary. After we have this:
```
2403   ~0%    {3} r6 = JOIN `DataFlowUtil::SummarizedParameterNode.getPos/0#dispred#70a2aab4` WITH …
```

Go: Fix bad join order in `SummarizedParameterNode.gettype`

---

java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt
java/kotlin-extractor/src/main/kotlin/utils/Logger.kt
java/ql/integration-tests/kotlin/all-platforms/logs/logs.expected

This makes it easy to see if setting the verbosity to 4 has actually succeeded.
I plan to force-green the "Kotlin internal queries" failure, as that is broken in main, and the motivation behind this PR is to help fix it.

Kotlin: Log our verbosity level

---

rust/codegen/BUILD.bazel
rust/codegen/codegen.sh

This passes command line arguments to codegen, allowing in particular `--force` to be passed.
Also, a convenience `//rust/codegen:py` is added to only run the python based code generation, which will be faster and enough when `ast-generator` is unchanged.

Rust: fix codegen to allow `--force` again

---

python/ql/lib/change-notes/2024-10-15-models-for-copy-replace.md
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPublic.qll
python/ql/lib/semmle/python/frameworks/Stdlib.model.yml
python/ql/lib/semmle/python/frameworks/Stdlib.qll
python/ql/test/library-tests/dataflow/tainttracking/defaultAdditionalTaintStep/test_collections.py

- Adds support for `copy.replace` ([added](https://docs.python.org/3.13/library/copy.html#copy.replace) in Python 3.13)
- Adds support for Models-as-Data representation for various content types.
Can (and should) be reviewed commit-by-commit.

Python: Model `copy.replace`

---

cpp/ql/lib/semmle/code/cpp/Element.qll
cpp/ql/test/library-tests/scopes/parents/parents.cpp
cpp/ql/test/library-tests/scopes/parents/parents.expected

This is mostly used to detect the shadowing of variable declarations.
DCA shows no changes. This does break some coding standards tests. I'll update the test results there after this is merged, and open an issue that informs the coding standards people of this. I briefly looked at fixing the query, but (a) it's not clearly documented what the query should do, and (b) this requires digging through about 400 lines of query code, which I find very hard to follow.

C++: Add missing parent scope cases

---

java/kotlin-extractor2/src/main/kotlin/KotlinExtractor.kt
java/kotlin-extractor2/src/main/kotlin/utils/Logger.kt

This happens at `info` level, which is logged by default.
This ports https://github.com/github/codeql/pull/17741 to KE2.

KE2: Log our verbosity level

---

cpp/ql/lib/change-notes/2024-10-16-function-pointer-resolution.md
cpp/ql/lib/change-notes/2024-10-16-new-api-for-call-target-resolution.md
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp

This uses the existing "lambda resolution" mechanism in the dataflow library to resolve calls through function pointers.
We already track function addresses flowing into MaD models that specify a function pointer as an input (which was added in https://github.com/github/codeql/pull/15371/commits/e9cd2dc9e18b6373dd9d3e812f545b6d4650822b). However, we never went the extra mile and added it when you call the function pointer _in the source code_.
This PR adds the one line which enables this. This should hopefully mean that we resolve a lot more function pointers.
Ideally, I would have liked to also remove the old [function pointer resolution and virtual dispatch code](https://github.com/github/codeql/blob/7d62cdad71eeeaa9c79880f005d4ea00718de32e/cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal …

C++: Improve function pointer resolution

---

docs/codeql/reusables/supported-versions-compilers.rst

Adds Python 3.13 to the list.
We might want to consider shortening the list to something like "3.5 - 3.13" at some point.
Also, once we're finally rid of standard library extraction, we should update footnote 8 accordingly.

Python: Update supported-versions-compilers.rst

---

go/ql/lib/semmle/go/Decls.qll
go/ql/lib/semmle/go/Scopes.qll
go/ql/lib/semmle/go/Types.qll
go/ql/lib/semmle/go/controlflow/IR.qll
go/ql/src/InconsistentCode/LengthComparisonOffByOne.ql

I got fed up of the extra boilerplate code needed to do this in various different situations. Performance-wise I'm not sure if it's better to mark this `pragma[inline]` or if it would be better to leave it as it is. (Or even `pragma[noinline]`!) I will make sure to fix any performance problems before merging.
I'm open to suggestions for a better predicate name.

Go: Add helper predicate `lookThroughPointerType`

---

go/ql/lib/change-notes/2024-10-17-ast-viewer-type-param-decl.md
go/ql/lib/semmle/go/AST.qll
go/ql/test/library-tests/semmle/go/PrintAst/PrintAst.expected
go/ql/test/library-tests/semmle/go/PrintAst/PrintAstExcludeComments.expected
go/ql/test/library-tests/semmle/go/PrintAst/PrintAstNestedFunction.expected
go/ql/test/library-tests/semmle/go/PrintAst/PrintAstRestrictFile.expected
go/ql/test/library-tests/semmle/go/PrintAst/PrintAstRestrictFunction.expected
go/ql/test/library-tests/semmle/go/PrintAst/go.mod
go/ql/test/library-tests/semmle/go/PrintAst/other.go

type param declarations were just floating, not part of the tree rooted in at the file node. This is easily fixed.
Should this have a change note? src or lib?
Note that we currently don't extract any kind of type parameter declaration for methods on generic types. We probably ought to, for consistency. But for now it is correct that the tests don't show anything in that case.

Go: Fix type param declarations in AST viewer

---

python/ql/lib/semmle/python/frameworks/Stdlib.model.yml
python/ql/test/experimental/query-tests/Security/CWE-022-UnsafeUnpacking/UnsafeUnpack.expected
python/ql/test/experimental/query-tests/Security/CWE-409/DecompressionBombs.expected

as a reaction to the latest QA run

Python: extra modelling of stdlib

---

java/ql/src/Security/CWE/CWE-352/SpringCSRFProtection.qhelp

Updates the Spring Security Reference link to the current documentation.

Java: update qhelp link for `java/spring-disabled-csrf-protection`

---

rust/ql/lib/codeql/rust/elements/internal/MatchExprImpl.qll

Before
```
Evaluated relational algebra for predicate MatchExprImpl::Impl::MatchExpr.getLastArm/0#dispred#24e5f4cf@9cf607tl with tuple counts:
660677  ~0%    {4} r1 = SCAN `MatchExprImpl::Impl::MatchExpr.getArm/1#dispred#817de8a3` OUTPUT _, In.0, In.2, In.1
660677  ~0%    {3}    | REWRITE WITH Tmp.0 := 1, Out.0 := (Tmp.0 + In.3) KEEPING 3
5342095756  ~0%    {3}    | JOIN WITH `MatchArmList::Generated::MatchArmList.getNumberOfArms/0#dispred#9ad72f08_10#join_rhs` ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Lhs.2
96597  ~3%    {2}    | JOIN WITH `MatchExpr::Generated::MatchExpr.getMatchArmList/0#dispred#11f1a73e` ON FIRST 2 OUTPUT Lhs.0, Lhs.2
return r1
```
After
```
Evaluated relational algebra for predicate MatchExprImpl::Impl::MatchExpr.getLastArm/0#dispred#24e5f4cf@9d7a92pu with tuple counts:
660677 …
```

Rust: Fix bad join

---

rust/ql/lib/codeql/rust/controlflow/internal/ControlFlowGraphImpl.qll
rust/ql/lib/codeql/rust/controlflow/internal/Scope.qll

Similar to how we have the `PatternTrees` module for patterns.

Rust: Move all expression CFG trees inside an `ExprTrees` module

---

go/ql/src/Security/CWE-681/IncorrectIntegerConversionQuery.qhelp

Go: Update `go/incorrect-integer-conversion` qhelp to explain possible source of FPs

---

go/Makefile

On Windows, make's path resolution algorithm is incorrect. It picks up a bazel.exe in PATH that's _after_ a bazel binary. In particular, on actions, the non-exe binary is a bazelisk instance, whereas bazel.exe is a bazel (at the current time 7.3.2) installation.
This means we pick up the wrong bazel version, and if the differences between the bazel we want and that we actually get are too big, the build fails.
Thanks to @smowton and @redsun82 for debugging help!

Go: Fix makefile to use bash to look up bazel path.

---

cpp/ql/test/library-tests/basic_blocks/bb_cfg.ql
cpp/ql/test/library-tests/basic_blocks/cfg.ql
cpp/ql/test/library-tests/c++_exceptions/graphable.ql
cpp/ql/test/library-tests/constexpr_if/cfg.ql
cpp/ql/test/library-tests/destructors/cfg.ql
cpp/ql/test/library-tests/lambdas/cfg/cfg.ql
cpp/ql/test/library-tests/pointsto/basic/sets.ql
cpp/ql/test/library-tests/sub_basic_blocks/cut.ql
cpp/ql/test/library-tests/sub_basic_blocks/no_cut.ql
cpp/ql/test/library-tests/virtual_functions/cfg/cfg.ql
cpp/ql/test/library-tests/vla/cfg.ql
cpp/ql/test/successor-tests/break_labels/cfg.ql
cpp/ql/test/successor-tests/conditional_destructors/cfg.ql
cpp/ql/test/successor-tests/exceptionhandler/ellipsisexceptionhandler/graphable.ql
cpp/ql/test/successor-tests/exceptionhandler/exceptionhandler/graphable.ql
cpp/ql/test/successor-tests/pruning/graphable.ql
cpp/ql/test/successor-tests/returnstmt/graphable.ql
cpp/ql/test/successor-tests/stackvariables/stackvariables/graphable.ql
cpp/ql/test/successor-tests/switchstmt/switchbody/graphable.ql

A number of CPP library tests contain `// query-type: graph` annotations that make the test driver compare the output from the test query in a special mode. (This feature is not used by other languages).
It's somewhat awkward in the implementation of `codeql test run` that this annotation is not an ordinary item of query metadata -- essentially it means that _every_ test query has to be opened and read an extra time to look for this annotation. I'd like to move towards using ordinary query metadata for this, since the QL compiler already parses it anyway.
(It seems unlikely that there exist any test _outside_ this repository that uses `// query-type: graph`).
For the time being, give the annotation in both old and new syntaxes, until a CLI that recognizes both has been released.

Supplement 'query-type: graph' with actual query metadata

---

python/extractor/tests/parser/class.py
python/extractor/tsg-python/python.tsg

This caused a dataset check error on the `python/cpython` database, as we had a `DictUnpacking` node whose parent was not a `dict_item_list`, but rather an `expr_list`.
Investigating a bit further revealed that this was because in a construction like
```python
class C[T](base, foo=bar, **kwargs): ...
```
we were mistakenly adding `**kwargs` to the same list as `base` (which is just a list of expressions), rather than the same list as `foo=bar` (which is a list of dictionary items)
The ultimate cause of this was the use of `! name` in `python.tsg` to distinguish between bases and keyword arguments (only the latter of which have the `name` field). Because `dictionary_splat` doesn't have a `name` field either, these were mistakenly put in the wrong list, leading to the error.
Also, because …

Python: Fix bug in handling of `**kwargs` in class bases 

---

cpp/ql/test/library-tests/dataflow/fields/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/fields/partial-definition-diff.expected
cpp/ql/test/library-tests/dataflow/fields/partial-definition-ir.expected
cpp/ql/test/library-tests/dataflow/fields/partial-definition.expected
cpp/ql/test/library-tests/dataflow/fields/simple.cpp

A simple testcase that demonstrate some missing flow that I may be working on addressing soon-ish.

C++: Add test with missing flow

---

javascript/extractor/lib/typescript/src/type_table.ts

Fixes the hang reported in https://github.com/github/codeql/issues/17827 (if you disable type extraction)

JS: have getId always return null if skipExtractingTypes is set

---

rust/ql/lib/codeql/rust/controlflow/internal/ControlFlowGraphImpl.qll
rust/ql/lib/codeql/rust/controlflow/internal/Splitting.qll
rust/ql/lib/codeql/rust/controlflow/internal/SuccessorType.qll
rust/ql/lib/codeql/rust/internal/CachedStages.qll

This PR ports the `CachedStages.qll` idea from JS/Python to Rust, and applies it to cached predicates belonging to the CFG construction. It has the effect that we collapse three QL compilation stages into one (though, the DIL reduction is rather limited). I foresee that we will also want to use `CachedStages.qll` when implementing data flow.

Rust: Collapse cached CFG logic into one stage

---

cpp/ql/test/query-tests/Likely Bugs/Format/WrongTypeFormatArguments/Builtin/WrongTypeFormatArguments.expected
cpp/ql/test/query-tests/Likely Bugs/Format/WrongTypeFormatArguments/Builtin/WrongTypeFormatArguments.qlref
cpp/ql/test/query-tests/Likely Bugs/Format/WrongTypeFormatArguments/Builtin/tests.c

C++: Add wrong format type builtin function test

---

.github/workflows/build-ripunzip.yml
.github/workflows/swift.yml
docs/codeql/reusables/supported-platforms.rst

Remove macos-12 and its variants, deprecated

---

rust/ql/lib/codeql/rust/elements/internal/FormatArgumentImpl.qll
rust/ql/lib/codeql/rust/elements/internal/FormatConstructor.qll
rust/ql/lib/codeql/rust/elements/internal/FormatImpl.qll
rust/ql/lib/codeql/rust/elements/internal/LocatableImpl.qll
rust/ql/lib/codeql/rust/elements/internal/LocationImpl.qll
rust/ql/lib/codeql/rust/elements/internal/VariableImpl.qll
rust/ql/lib/codeql/rust/internal/CachedStages.qll

Follows up on https://github.com/github/codeql/pull/17791. Recovers most of the performance we lost.

Rust: Cache `Locatable.getLocation` and `Location`

---

rust/ql/test/query-tests/unusedentities/UnusedValue.expected
rust/ql/test/query-tests/unusedentities/unreachable.rs

Clean up the `unusedentities/unreachable.rs` test.  There were a handful of accidental unused value results in the test introduced in https://github.com/github/codeql/pull/17803 that weren't annotated.  First I added annotations.  Then I decided the test code should be fixed, as these results aren't interesting (they're similar to cases in the other test file) and they distract from what `unreachable.rs` is about.

Rust: Clean up unreachable test

---

actions/extractor/tools/autobuild.sh

This reverts commit 3228447544a52e56da4ae7890fd17d0bc844cbeb.
Turns out that bash will report "parameter not set" if the variable is unset, as opposed to just empty. We needed the default value as empty for the test to work.

Revert "Fix bash nit"

---

javascript/resources/tools/autobuild.cmd

I'm not sure it ever worked.  
Apparently the old syntax expands the value at parse-time (where `half_ram` doesn't exist yet).  
[The fix was found and written by ChatGPT](https://chatgpt.com/share/671fe8d0-2c70-8012-864b-db39a2b73d4f) (after I had added some debug printing, which was written by Copilot). 
It seems to work fine now. (The `Memory for TypeScript process` debug print inside the parser started printed the right value).

fix the RAM setting on Windows

---

javascript/extractor/src/com/semmle/js/extractor/HTMLExtractor.java
javascript/extractor/src/com/semmle/js/extractor/Main.java
javascript/ql/test/library-tests/frameworks/Vue/special-syntax.vue
javascript/ql/test/library-tests/frameworks/Vue/tests.expected
javascript/ql/test/library-tests/frameworks/Vue/tests.ql

Vue supports attributes of form `:foo` or `@foo`, or `:foo.bar` etc. Previously they were seen as syntax errors, which means we didn't extract the surrounding HTML element (which is something we do to guard against noise from incorrectly parsed HTML soup). We now allow these additional characters so elements get extracted properly.
The `:` and `@` attributes are [shorthands](https://v2.vuejs.org/v2/guide/syntax.html#Shorthands) for `v-bind:...` and `v-on:...` attributes, but since we don't model those attributes currently, there are no changes to the Vue model.

JS: Fix parsing of special Vue attributes

---

actions/BUILD.bazel
actions/extractor/BUILD.bazel
actions/ql/test/query-tests/Placeholder/Placeholder.expected

This PR adds the new Actions extractor to the CLI build. Most of the Bazel code has been lifted from the Rust extractor, which was just added a couple weeks ago. Like Rust, the Actions extractor will wind up in the `experimental` directory of the CLI build for now.
I'll open the internal CLI PR one these changes are merged and the submodule is bumped.

Add the Actions extractor to the build

---

rust/ql/lib/codeql/rust/dataflow/DataFlow.qll
rust/ql/lib/codeql/rust/dataflow/TaintTracking.qll
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/TaintTrackingImpl.qll
rust/ql/test/library-tests/dataflow/barrier/barrier.ql
rust/ql/test/library-tests/dataflow/barrier/main.rs
rust/ql/test/library-tests/dataflow/local/DataFlowStep.ql
rust/ql/test/library-tests/dataflow/local/main.rs

This PR adds the basic setup for data flow and taint tracking with the goal that
* The QL compiles and is suitable for building on top of.
* The external API for the data flow library and taint tracking is in place, such that queries can be written against them.

Rust: Add basic skeleton setup for data flow

---

java/kotlin-extractor2/ke2.sh

Example usage:
```
CODEQL_JAVA_HOME=/openjdk23/home/ CODEQL_KOTLIN_EXTRACTOR_JVM_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8888" codeql database create -l java -c "kotlinc test.kt" db
```

KE2: Enable attaching debugger to extractor

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/lib/codeql/ruby/frameworks/ActiveSupport.qll
ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.expected
ruby/ql/test/library-tests/dataflow/flow-summaries/semantics.rb
ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected
ruby/ql/test/library-tests/dataflow/hash-flow/hash_flow.rb
ruby/ql/test/library-tests/frameworks/active_support/ActiveSupportDataFlow.expected
ruby/ql/test/library-tests/frameworks/active_support/hash_extensions.rb

Before this PR, we distinguished between symbols and strings in hash keys. So, for example, we would (correctly) not report flow in cases like
```rb
hash[:key] = "taint"
sink(hash["key"])
```
However, doing so meant that the flow summaries for methods such as [`with_indifferent_access`](https://api.rubyonrails.org/v4.2.0/classes/ActiveSupport/HashWithIndifferentAccess.html) would throw away any known information about the keys, leading to false positive flow.
While we could attempt to improve the summaries for methods like `with_indifferent_access`, this PR instead simply considers symbol/string hash keys equal when they denote the same value. The only potential downside is false positive flow, like in the example above, but this seems very unlikely in practice. Indeed, DCA confirms that …

Ruby: Do not distinguish between symbols and strings in hash keys

---

python/extractor/semmle/python/imports.py
python/extractor/semmle/python/modules.py
python/extractor/semmle/python/parser/tsg_parser.py
python/extractor/semmle/util.py

Does a bunch of things, unfortunately all in the same place, so my apologies in advance for a slightly complicated commit.
As for the changes themselves, this PR
- Adds timers for the old and new parsers. This means we get the overall time spent on these parts of the extractor if the extractor is run with `DEBUG` output shown.
- Adds logging information (at the `DEBUG` level) to show which invocations of the parsers happen when, and whether they succeed or not.
- Adds support for using an environment variable named `CODEQL_PYTHON_DISABLE_OLD_PARSER` to disable using the old parser entirely. This makes it easier to test the new parser in isolation.
- Fixes a bug where we did not check whether a parse with the new parser had already succeeded, and so would do a superfluous second parse.
- …

Python: Improve parser logging/timing/customisability

---

python/ql/src/meta/analysis-quality/CallGraphQuality.qll
python/ql/test/experimental/library-tests/CallGraph/InlineCallGraphTest.ql
python/ql/test/library-tests/dataflow/calls/DataFlowCallTest.ql

This should be a simple semantics-preserving refactor to eliminate references to `TNormalCall`.

Python: Refactor references to NormalCall.

---

misc/scripts/accept-expected-changes-from-ci.py

When I ran the script on a PR that included [this job](https://github.com/github/semmle-code/actions/runs/11660045127), it only looked at the first sub job (https://github.com/github/semmle-code/actions/runs/11660045127/job/32461625428) and not the remaining two slices.
This change makes it run against all sub jobs; not sure if it is the right way to fix it, though.

Handle matrix jobs in accept changes script

---

rust/ql/consistency-queries/DataFlowConsistency.ql
rust/ql/src/queries/diagnostics/DataFlowConsistencyCounts.ql
rust/ql/src/queries/summary/Stats.qll
rust/ql/src/queries/summary/SummaryStats.ql
rust/ql/test/query-tests/diagnostics/DataFlowConsistencyCounts.expected
rust/ql/test/query-tests/diagnostics/DataFlowConsistencyCounts.qlref
rust/ql/test/query-tests/diagnostics/SummaryStats.expected
shared/dataflow/codeql/dataflow/internal/DataFlowImplConsistency.qll

**Rust:** expose counts of data flow inconsistencies in `rust/summary/summary-statistics` and new diagnostic query `rust/diagnostics/data-flow-consistency-counts`.  This (the former, at the moment) will allow us to display data flow inconsistencies in DCA runs.
**Shared:** there's a change to the shared library `DataFlowImplConsistency.qll` in the addition of a predicate `getInconsistencyCounts`.  It's not super clean as it duplicates some information from the existing query predicates - but on the other hand it _prevents_ that duplication from having to go any further (e.g. into language specific diagnostic queries).  There might be a nicer way to do this, perhaps involving an abstract `class DataFlowInconsistency` that collects all results in one place ... but that would inevitably end …

Rust: Expose counts of data flow inconsistencies

---

.vscode/settings.json

When `editor.suggest.matchOnWordStartOnly` is turned on (the default), VSCode autocomplete does not return all options for a search term that is preceded by "A", such as "param" in the below images.
Disabling this setting allows VSCode to return all possible matches for a search term.
Related issue: https://github.com/github/vscode-codeql/issues/2573

VSCode setting: turn off `editor.suggest.matchOnWordStartOnly`

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll
csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll
csharp/ql/test/utils/modelgenerator/dataflow/Summaries.cs
java/ql/src/utils/modelgenerator/internal/CaptureModels.qll
shared/mad/codeql/mad/modelgenerator/internal/ModelGeneratorImpl.qll

In this PR we added support for read/store steps for delegate calls (where the delegate being called is parameter of a callable) for C#.
The read and store steps for delegate calls and delegate returns are basically "dead ends" and are only relevant for content dataflow related to model generation.

C#: Models for higher order methods.

---

java/ql/lib/semmle/code/java/dataflow/TypeFlow.qll

Noticed that this was missing during my recent TypeFlow refactor. It probably won't affect much.

Kotlin: Support NotNullExpr in TypeFlow.

---

rust/ql/test/extractor-tests/canonical_path/CONSISTENCY/DataFlowConsistency.expected
rust/ql/test/extractor-tests/generated/MacroItems/CONSISTENCY/DataFlowConsistency.expected

The modified result is just a change due to a semantic conflict after introducing some `toString` implementations.
The new inconsistency should be looked at more in detail.

Rust: accept some inconsitencies for now

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected

Tiny PR that
* Marks SSA data flow nodes with `[SSA]` when they are stringified.
* Hide's SSA nodes in paths.

Rust: Mark SSA data flow nodes in output and hide them in paths

---

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
java/ql/test-kotlin1/library-tests/classes/genericExprTypes.expected
java/ql/test-kotlin2/library-tests/classes/genericExprTypes.expected

This matches the Java extractor's treatment of these literals, and so enables dataflow type-tracking to avoid special-casing Kotlin. Natively, Kotlin would regard this as kotlin.Nothing?, the type that can only contain null (kotlin.Nothing without a ? can take nothing at all), which gets Java-ified as java.lang.Void, and this will continue to be used when a null type has to be "boxed", as in representing substituted generic constraints with no possible type.

Kotlin extractor: use special <nulltype> for null literals

---

Cargo.lock
ql/Cargo.lock
ruby/extractor/Cargo.toml
shared/tree-sitter-extractor/Cargo.toml

There was a recent round of tree-sitter-* package releases, so the latest code is now a) released and b) available on crates.io.
Therefore, move away from the (super slow on CI) git dependencies to released crates instead. This also includes a run of `cargo update`, so there's a bunch of more changes to the lockfile.
Ruby team: What sort of testing do you need to run on this to validate these changes? Can you assist me with those if possible?

Rust: Update cargo dependencies.

---

go/extractor/extractor.go
go/ql/lib/change-notes/2024-11-07-fix-missing-qualified-names-for-methods.md
go/ql/test/library-tests/semmle/go/Types/Field_getPackage.expected
go/ql/test/library-tests/semmle/go/Types/Field_hasQualifiedName2.expected
go/ql/test/library-tests/semmle/go/Types/Field_hasQualifiedName3.expected
go/ql/test/library-tests/semmle/go/Types/MethodCount.expected
go/ql/test/library-tests/semmle/go/Types/MethodTypes.expected
go/ql/test/library-tests/semmle/go/Types/Method_hasQualifiedName2.expected
go/ql/test/library-tests/semmle/go/Types/Method_hasQualifiedName3.expected
go/ql/test/library-tests/semmle/go/Types/Methods.expected
go/ql/test/library-tests/semmle/go/Types/QualifiedNames.expected
go/ql/test/library-tests/semmle/go/Types/SignatureType_getNumParameter.expected
go/ql/test/library-tests/semmle/go/Types/SignatureType_getNumResult.expected
go/ql/test/library-tests/semmle/go/Types/StructFields.expected
go/ql/test/library-tests/semmle/go/Types/Types.expected
go/ql/test/library-tests/semmle/go/Types/pkg1/promotedStructs.go
go/ql/test/library-tests/semmle/go/Types/promoted.go
go/ql/test/library-tests/semmle/go/aliases/InterfaceImpls/test.expected
go/ql/test/library-tests/semmle/go/aliases/InterfaceImpls/test.ql
go/ql/test/library-tests/semmle/go/dataflow/ExternalFlowInheritance/test.go

The fix is to always extract `*t` when we are extracting a named type `t` which can have methods defined on it (i.e. its underlying type is not a pointer or an interface).

Go: fix missing qualified names for some promoted methods

---

javascript/ql/lib/change-notes/2024-11-11-reserve-support.md
javascript/ql/lib/semmle/javascript/Arrays.qll
javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll
javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected
javascript/ql/test/library-tests/TaintTracking/tst.js

While addressing another [issue](https://github.com/github/codeql-javascript-team/issues/435) I found that we we're missing support for `Array.prototype.reverse`.  
I've added support for the method, and moved an existing related support for `.sort()` to a more relevant [location](https://github.com/github/codeql/blob/f1c6dc1d9bff7b5d4a98e6342d0cea10e183cb58/javascript/ql/lib/semmle/javascript/Arrays.qll#L451).

JS: Added support for reverse function

---

cpp/ql/test/experimental/query-tests/Best Practices/GuardedFree/GuardedFree.expected
cpp/ql/test/experimental/query-tests/Best Practices/GuardedFree/GuardedFree.qlref
cpp/ql/test/experimental/query-tests/Best Practices/GuardedFree/test.cpp

I investigated a bit if the query can be promoted (instead of moving it to a separate repo). The tests highlight some issues.

C++: Add tests for experimental `cpp/guarded-free` query

---

rust/ql/test/library-tests/dataflow/barrier/inline-flow.expected
rust/ql/test/library-tests/dataflow/barrier/inline-flow.ql
rust/ql/test/library-tests/dataflow/barrier/main.rs
rust/ql/test/utils/InlineFlowTest.qll

Setup inline flow test library for Rust. It doesn't output anything, but it should once other things begin to work 😉

Rust: Setup inline flow test library

---

java/ql/lib/ext/java.io.model.yml

Java: Add model for CharArrayWriter.toString().

---

.github/workflows/csv-coverage-metrics.yml
.github/workflows/csv-coverage-pr-artifacts.yml
.github/workflows/csv-coverage-timeseries.yml
.github/workflows/csv-coverage.yml
.github/workflows/mad_modelDiff.yml
.github/workflows/mad_regenerate-models.yml
.github/workflows/post-pr-comment.yml
.github/workflows/qhelp-pr-preview.yml
.github/workflows/ql-for-ql-build.yml
.github/workflows/ql-for-ql-dataset_measure.yml
.github/workflows/query-list.yml
.github/workflows/ruby-build.yml
.github/workflows/ruby-dataset-measure.yml
.github/workflows/swift.yml

https://github.com/actions/upload-artifact and https://github.com/actions/download-artifact are deprecating `v3` soon, and this PR bumps naively to `v4`.
~From skimming, `.github/workflows/qhelp-pr-preview.yml`~ From running, several workflows seem to be hit by the unique name restriction mentioned in https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md. This needs investigation.

chore(actions): bump to artifacts@v4

---

cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedElement.qll
cpp/ql/test/library-tests/ir/multiple-entry-points/raw_ir.expected

Reverts github/codeql#17694
I'm reverting this due to https://github.com/github/codeql-c-team/issues/2482. The problem is that it seems that TRAP caching does pull in a few duplicate functions, which is arguably a bug but will take a bit more time to investigate. In the meantime, since github/codeql#17694 can cause results wobble, I think it would be safest to revert.
@jketema kindly do double-check that this PR is indeed the root cause of these new alert deltas.

Revert "C++: Do not generate IR for functions with multiple entry points"

---

java/kotlin-extractor2/src/main/kotlin/KotlinUsesExtractor.kt
java/kotlin-extractor2/src/main/kotlin/TrapWriter.kt
java/kotlin-extractor2/src/main/kotlin/entities/Expression.kt
java/kotlin-extractor2/src/main/kotlin/entities/Function.kt
java/kotlin-extractor2/src/main/kotlin/entities/MethodCall.kt
java/kotlin-extractor2/src/main/kotlin/entities/Types.kt
java/kotlin-extractor2/src/main/kotlin/utils/JvmNames.kt

Basic implementation of property and variable accesses, and flexible types since they were needed in passing.
Choices for comment:
* Keep KE1's choice to extract property accesses as desugared getter or setter calls.
* Possible alternative: extract a reference expression, perhaps with the hint that the compiler knows this is targeting a property, and turn that into a getter/setter call QL-side
* For the time being, extract flexible types as their lower bound (this means `String!` is extracted as `String`; the upper bound would mean we get `String?` instead; I don't know from memory if we get flexible types that are more complex than just flexible nullability
* Possible alternatives: extract the other bound, or extract a flexible type explicitly (and do something with this QL-side so that …

KE2: implement basic usage of properties, variables and flexible types

---

javascript/ql/lib/change-notes/2024-11-12-immutable-array-operations.md
javascript/ql/lib/semmle/javascript/Arrays.qll
javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected
javascript/ql/test/library-tests/TaintTracking/tst.js
javascript/ql/test/query-tests/NodeJS/DubiousImport/externs.js

Added missing QL support for JavaScript `Array.prototype.toReversed` and `Array.prototype.toReversed` addressing [issue](https://github.com/github/codeql-javascript-team/issues/435).

JS: Added support for toSorted and toReversed

---

csharp/extractor/Semmle.Extraction.CSharp/Extractor/Extractor.cs

This PR changes how empty binlog files are treated. Previously, the extractor returned a failed extraction error code in such a case:
```
[ERROR] Spawned process exited abnormally (code 2; tried to run: [.../extractor-csharp/csharp/tools/autobuild.sh])
A fatal error occurred: Exit status 2 from command: [...extractor-csharp/csharp/tools/autobuild.sh]
```
Now the behavior matches what we experience in traced mode, when no source code is found:
```
Finalizing database at .../DB1.
CodeQL did not detect any code written in languages supported by this CodeQL distribution (C#, XML, Java Properties Files or Java/Kotlin). Confirm that there is some source code for one of these languages in the project. For more information, review our troubleshooting guide at …
```

C#: Consider the extraction of empty binlog files acceptable

---

java/ql/lib/change-notes/2024-11-14-unreachable-basic-block-in-constant-switch-statement.md
java/ql/lib/semmle/code/java/controlflow/UnreachableBlocks.qll
java/ql/test/library-tests/unreachableblocks/UnreachableBlocks.expected

This bug was fixed in passing in https://github.com/github/codeql/pull/711, but unfortunately that PR wasn't merged for performance reasons. It hasn't been noticed in the meantime, presumably because constant switch statements are pretty rare.

Java: fix unreachable basic blocks in const switch stmt

---

rust/ql/lib/codeql/rust/controlflow/internal/Splitting.qll
rust/ql/test/library-tests/controlflow/Cfg.expected
rust/ql/test/library-tests/controlflow/test.rs

Example:
```rust
fn test_and_if_let(a: bool, b: Option<bool>, c: bool) -> bool {
if a && let Some(d) = b {
d
} else {
false
}
}
```
<details><summary>CFG before:</summary>
```mermaid
flowchart TD
1["enter test_and_if_let"]
10["BlockExpr"]
11["IfExpr"]
12["a"]
13["... && ..."]
14["[boolean(false)] ... && ..."]
15["LetExpr"]
16["TupleStructPat"]
17["d"]
18["b"]
19["BlockExpr"]
2["exit test_and_if_let"]
20["d"]
21["BlockExpr"]
22["false"]
3["exit test_and_if_let (normal)"]
4["a"]
5["Param"]
6["b"]
7["Param"]
8["c"]
9["Param"]
1 --> 4
3 --> 2
4 -- match --> 5
5 --> 6
6 -- match --> 7
7 --> 8
8 -- match --> 9
9 --> 12
10 --> 3
11 --> 10
12 -- false --> 14
12 -- true --> 15
13 -- false --> 22
13 -- true --> 20
14 -- false --> 22
15 --> 18
16 -- match --> 17
16 -- no-match --> 13
17 -- match --> …
```

Rust: Improve CFG for `let` expressions

---

.github/workflows/cpp-swift-analysis.yml
actions/BUILD.bazel
misc/bazel/pkg.bzl
rust/BUILD.bazel
rust/README.md
swift/README.md
swift/actions/build-and-test/action.yml

This makes the first `codeql_pack` in a package add an `install` target aliasing the `<name>-installer` one. This makes it so that one can for example do `bazel run //rust:install` instead of the stuttering `bazel run //rust:rust-installer`. If a bazel package defines multiple `codeql_pack` targets, the first one only will get the `install` alias.

Bazel: add an `install` shortcut and an `experimental` attribute to `codeql_pack`

---

python/extractor/semmle/python/passes/pruner.py
python/ql/test/query-tests/Statements/unreachable/UnreachableCode.expected

Python: Fix pruning of literals in `match` pattern

---

cpp/ql/src/Critical/UseAfterFree.qhelp

C++: fix typo in qhelp

---

go/ql/lib/ext/os.model.yml
go/ql/lib/semmle/go/dataflow/ExternalFlow.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
go/ql/lib/semmle/go/frameworks/stdlib/Os.qll
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/completetest.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/sinks.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/sinks.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/srcs.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/srcs.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/test.go
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/vendor/github.com/nonexistent/test/stub.go
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/completetest.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/sinks.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/sinks.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/srcs.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/srcs.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/test.go
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/vendor/github.com/nonexistent/test/stub.go

[When we modeled `os.Stdin` as a source](https://github.com/github/codeql/pull/17335), we noticed that it was not possible to write a models-as-data model for it. This PR fixes that, both for sources and sinks, and it converts the model for `os.Stdin` to models-as-data. As with models-as-data for fields, the input/output column must be empty. Unlike fields, the type column must also be empty.
I don't think this needs a change note as models-as-data hasn't been publicly announced for Go.

Go: Allow package-level variables in models-as-data models

---

rust/ql/lib/codeql/rust/elements/internal/VariableImpl.qll
shared/util/codeql/util/DenseRank.qll

As suggested by @aschackmull [here](https://github.com/github/codeql/pull/17696#pullrequestreview-2372015468).

Util: Refactor `DenseRank` implementation

---

javascript/ql/lib/change-notes/2024-11-18-ES2022-find-functions.md
javascript/ql/lib/semmle/javascript/Arrays.qll
javascript/ql/src/Statements/UseOfReturnlessFunction.ql
javascript/ql/test/library-tests/Arrays/DataFlow.expected
javascript/ql/test/library-tests/Arrays/DataFlow.ql
javascript/ql/test/library-tests/Arrays/TaintFlow.expected
javascript/ql/test/library-tests/Arrays/TaintFlow.ql
javascript/ql/test/library-tests/Arrays/arrays.js
javascript/ql/test/library-tests/Arrays/printAst.expected
javascript/ql/test/query-tests/Statements/UseOfReturnlessFunction/UseOfReturnlessFunction.expected
javascript/ql/test/query-tests/Statements/UseOfReturnlessFunction/tst.js

Added support for ES2023 feature, `Arrray.protype.findLastIndex`, `Arrray.protype. findLast`.
DCA run shows that the run time stays approximately the same. Meta queries revealed new taint for `Arrray.protype.find` calls with lambda, which was expected.

JS: Added support for Array.prototype.[findLastIndex, findLast] ES2022 feature

---

rust/ql/lib/codeql/rust/controlflow/internal/ControlFlowGraphImpl.qll
rust/ql/test/library-tests/controlflow/Cfg.expected
rust/ql/test/library-tests/controlflow/test.rs
rust/ql/test/library-tests/variables/Cfg.expected

Currently `self` parameters are not included in the CFG. This PR adds them.
This example:
```rust
fn add(&mut self, a: i64, b: i64) {
self.n += a + b;
}
```
results in this CFG (previously the 2nd and 3rd node where not there):
```mermaid
flowchart TD
1["enter add"]
10["BlockExpr"]
11["self"]
12["FieldExpr"]
13["... += ..."]
14["ExprStmt"]
15["a"]
16["... + ..."]
17["b"]
2["exit add"]
3["exit add (normal)"]
4["SelfParam"]
5["self"]
6["a"]
7["Param"]
8["b"]
9["Param"]
1 --> 5
3 --> 2
4 --> 6
5 --> 4
6 -- match --> 7
7 --> 8
8 -- match --> 9
9 --> 14
10 --> 3
11 --> 12
12 --> 15
13 --> 10
14 --> 11
15 --> 17
16 --> 13
17 --> 16
```

Rust: Include `self` parameters in the CFG

---

java/ql/test/library-tests/dataflow/getter/getter.expected
shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll

When investigating a Ruby performance issue, I found that we produced some false positive return-through-parameter flow, which is because we are not tracking call contexts in the `parameterValueFlow` logic. This PR adds tracking of call contexts.

Data flow: Track call contexts in `parameterValueFlow`

---

javascript/ql/lib/change-notes/2024-11-20-ES2023-string-protytpe-toWellFormed.md
javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll
javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected
javascript/ql/test/library-tests/TaintTracking/string-immutable-operations.js

Added `String.prototype.toWellFormed` to [`StringManipulationTaintStep`](https://github.com/github/codeql/blob/afc2d3e6d25f24d6111072b555357151b3684222/javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll#L601).
The DCA run times look fine, and no new meta alerts have appeared, which is expected due to the `String.prototype.toWellFormed` novelty.

JS: Added taint-step String.prototype.toWellFormed ES2023 feature

---

.github/workflows/compile-queries.yml

Setting the RAM explicitly means we can use all 16 cores (otherwise, only 8 cores will be used).

CI: Set `--ram` in `compile-queries.yml`

---

python/ql/test/library-tests/dataflow/global-or-captured-vars/test.expected
python/ql/test/library-tests/dataflow/global-or-captured-vars/test.py
python/ql/test/library-tests/dataflow/global-or-captured-vars/test.ql

Adds test cases for cases involving flow through global variables and captured variables. 
This checks whether modelling stdlib `queue.Queue` as a container would allow for the use case of dataflow between access of a shared `Queue` across separate threads, which is necessary for covering [CVE-2024-32651](https://github.com/github/codeql-python-CVE-coverage/issues/3176). As-is it appears that such modelling would not be sufficient to detect flow in this case.

Python: Add some test cases for flow involving global and captured variables

---

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
java/kotlin-extractor2/src/main/kotlin/entities/Types.kt
java/ql/lib/config/semmlecode.dbscheme
java/ql/lib/semmle/code/Location.qll
java/ql/lib/semmle/code/java/KotlinType.qll

This adds the beginning of KtType extraction.
The main change is in the dbscheme relations, which now look like:
```
/**
* `id` is the Kotlin type for the non-nullable class type `classid`.
*/
kt_class_types(
unique int id: @kt_class_type,
int classid: @reftype ref
)
/**
* `id` is the Kotlin type that is the same as `kttypeid`, but is nullable.
*/
kt_nullable_types(
unique int id: @kt_nullable_type,
int kttypeid: @kt_type ref
)
/**
* `id` is the Kotlin type that is the alias called `name` of `kttypeid`.
* That is, it has been defined by `typealias name = kttypeid`.
*/
kt_type_alias(
unique int id: @kt_type_alias,
string name: string ref,
int kttypeid: @kt_type ref
)
```
and `useType` now produces these.
This broke the KE1 build, which for now I've just fixed with `TODO()` calls; I think …

KE2: Start working on KtTypes

---

java/kotlin-extractor2/src/main/kotlin/KotlinExtractor.kt

With this, if I make the testsuite driver use 1.7, then the test code
```
sealed interface ReadResult
data class Number(val number: Int) : ReadResult
data class Text(val text: String) : ReadResult
data object EndOfFile : ReadResult
```
makes the extractor print
```
=== Diagnostics
--- Diagnostic:
WRONG_MODIFIER_TARGET
ERROR
Modifier 'data' is not applicable to 'standalone object'. Location(startLine=5, startColumn=1, endLine=5, endColumn=4)
--- End diagnostics
```

KE2: Use the right language version

---

java/kotlin-extractor2/BUILD.bazel

Once we get closer to completion, it will be useful to have this on.

KE2: Add warnings-as-error to build system, but commented out for now

---

java/kotlin-extractor2/src/main/kotlin/entities/Expression.kt

Avoids shadowing `trapWriterWriteExpr`, and removes the need to check for an impossible case.
Recommend reviewing with `?w=1`.

KE2: Small refactoring

---

java/ql/lib/semmle/code/java/security/Encryption.qll
java/ql/lib/semmle/code/java/security/MaybeBrokenCryptoAlgorithmQuery.qll
java/ql/src/change-notes/2024-10-29-weak-crypto-hash.md
java/ql/test/query-tests/security/CWE-327/semmle/tests/BrokenCryptoAlgorithm.expected

Removes weak hash algorithms such as MD5 and SHA1 from `java/weak-cryptographic-algorithm` and adds these cases to `java/potentially-weak-cryptographic-algorithm` instead.
The removal of weak hash algorithms from `java/weak-cryptographic-algorithm` aligns with other languages, e.g. https://github.com/github/codeql/pull/11129.
Let me know if there is any concern with changing the behavior of `rankedInsecureAlgorithm` instead of doing the exclusion for `java/weak-cryptographic-algorithm` directly in [BrokenAlgoLiteral](https://github.com/github/codeql/blob/b00bbc9ca2fba1de83c36eb909448fdf5e85c83b/java/ql/lib/semmle/code/java/security/BrokenCryptoAlgorithmQuery.qll#L15)? I chose to do the exclusion in `rankedInsecureAlgorithm` since doing so automatically adds the weak hash cases to …

Java: Improve weak crypto query

---

java/ql/lib/semmle/code/java/security/Encryption.qll
java/ql/src/change-notes/2024-11-22-sha3.md
java/ql/test/query-tests/security/CWE-327/semmle/tests/MaybeBrokenCryptoAlgorithm.expected
java/ql/test/query-tests/security/CWE-327/semmle/tests/WeakHashing.java

Fixes: https://github.com/github/codeql/issues/18082

Java: add SHA3 family to list of secure crypto algorithms

---

rust/ast-generator/src/main.rs

Changes the parameters of `class_name` and `property_name` from `&String` to the [more idiomatic](https://doc.rust-lang.org/std/string/struct.String.html#deref) `&str`.

Rust: Change `&String` to `&str`

---

.vscode/tasks.json
misc/scripts/create-change-note.py

Adds a VSCode Task (accessible from the "Run Task" menu) for creating change notes, prompting the user for the language, name, and category of the change.
The language options presented are based on the existing occurrences of `change-notes` folders in the repo. There are more such files (in particular every shared library has a `change-notes` directory), but it seemed to me that the language change notes are the ones that are most common, and so in an effort to not clutter the list too much, I only included the languages.
The selection of categories is based on existing usage -- more specifically the result of grepping for occurrences of `'^category: '` in the repo. It's possible there are more change categories that could be added.
Hopefully this should make it more convenient to create …

Add script and VSCode task for creating change notes

---

rust/ql/lib/codeql/rust/controlflow/CfgNodes.qll
rust/ql/lib/codeql/rust/controlflow/internal/CfgNodes.qll
rust/ql/lib/codeql/rust/dataflow/DataFlow.qll
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/test/library-tests/dataflow/barrier/inline-flow.expected
rust/ql/test/library-tests/dataflow/global/inline-flow.expected
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/local/DataFlowStep.ql
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/dataflow/local/main.rs

This PR adds support for tracking data flow through construction and deconstruction of enum variants. For example, we can now identify flow in cases such as
```rust
enum MyEnum {
A(i64),
B(i64),
}
let s1 = MyEnum::A(source());
match s1 {
MyEnum::A(n) => sink(n), // flow
MyEnum::B(n) => sink(n), // no flow
}
```
Commit-by-commit review is suggested.

Rust: Data flow through variants

---

java/ql/test/library-tests/dataflow/range-analysis-inline/B.java
java/ql/test/library-tests/dataflow/range-analysis-inline/range.ql

This adds inline expectation test for the java range analysis.
Feel free to suggest better tests or better syntax.

java: inline range test

---

java/ql/lib/semmle/code/java/security/Encryption.qll
java/ql/src/change-notes/2024-11-24-sha2.md
java/ql/test/query-tests/security/CWE-327/semmle/tests/WeakHashing.java

Adds `SHA-384` as a secure algorithm so that the `java/potentially-weak-cryptographic-algorithm` query no longer flags it. 
Adding `SHA-384` aligns Java with [other languages](https://github.com/github/codeql/blob/f0045692a76454e00a39f318510f8e188b563cc0/python/ql/lib/semmle/python/concepts/internal/CryptoAlgorithmNames.qll#L24C27-L24C35).

Java: add SHA-384 to list of secure crypto algorithms

---

java/ql/lib/semmle/code/java/Expr.qll

It makes a lot of noise in the CFG QLL, that we aren't fixing yet

KE2: Don't actually deprecate WhenBranch.getCondition() yet

---

cpp/ql/lib/semmle/code/cpp/dataflow/ExternalFlow.qll
cpp/ql/test/library-tests/dataflow/taint-tests/format.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/stl.h
cpp/ql/test/library-tests/dataflow/taint-tests/test_mad-signatures.expected

This PR fixes quite an embarrassing bug: We forgot to check the function name when matching MaD models with `Function`s when dealing with non-member functions 😱
That's ... quite bad. Luckily, there are several reasons for why this went unnoticed for 4 months:
- The only non-member models we have is `boost::asio::buffer` and `std::format`
- We were still correctly validating the signature, which meant that very few spurious functions were being matched.
Commit-by-commit review recommended. The last commit is just a cleanup of the conjuncts.

C++: Actually check function names in MaD

---

javascript/ql/lib/semmle/javascript/dataflow/internal/TaintTrackingPrivate.qll
javascript/ql/lib/semmle/javascript/security/dataflow/IndirectCommandInjectionQuery.qll
javascript/ql/test/experimental/Security/CWE-918/SSRF.expected
javascript/ql/test/library-tests/Arrays/DataFlow.expected
javascript/ql/test/library-tests/Arrays/TaintFlow.expected
javascript/ql/test/library-tests/Arrays/printAst.expected
javascript/ql/test/library-tests/FlowSummary/DataFlowConsistency.expected
javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected
javascript/ql/test/query-tests/Security/CWE-078/IndirectCommandInjection/IndirectCommandInjection.expected
javascript/ql/test/query-tests/Security/CWE-089/local-threat-source/SqlInjection.expected
javascript/ql/test/query-tests/Security/CWE-117/LogInjection.expected

`speculativeTaintStep` is a mandatory part of the data flow interface now, resulting in compilation errors when merging in `main`.
It's not a priority to get this working, so just providing a bare-bones implementation that's slightly better than `none()`.

JS: Merge 'main' and implement 'speculativeTaintStep'

---

python/extractor/semmle/util.py
python/ql/lib/change-notes/2024-11-26-fix-match-cfg-pruning.md

... And also bump the extractor version.

Python: Add change note for CFG pruning fix

---

swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Array.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Collection.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/Dictionary.qll
swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/DataFlowInline.expected
swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/test.swift
swift/ql/test/library-tests/dataflow/dataflow/test2.swift
swift/ql/test/query-tests/Security/CWE-020/MissingRegexAnchor.expected
swift/ql/test/query-tests/Security/CWE-020/UnanchoredUrlRegex.swift

Fix `makeIterator()` models.  We previously depended on the `Sequence.makeIterator()` model, but it appears basic `for in` loops go to `Collection.makeIterator()` now, so we need a model of that.

Swift: Fix makeIterator() models

---

csharp/ql/lib/change-notes/2024-11-26-model-microsoft.jsinterop.ijsruntime.md
csharp/ql/lib/ext/Microsoft.JSInterop.model.yml

Adds `js-injection` sink models for the extensions methods for the `Microsoft.JSInterop.IJSRuntime` interface, which can run arbitrary JS.
~- [ ] All new queries have appropriate `.qhelp`. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-help-style-guide.md) in this repository.~
~- [ ] New and changed queries have correct query metadata. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md) in this repository.~
~- [ ] Autofixes generated based on these changes are valid, only needed if this PR makes significant changes to `.ql`, `.qll`, or `.qhelp` files. See [the documentation](https://github.com/github/codeql-team/blob/main/docs/best-practices/validating-autofix-for-query-changes.md) (internal access …

C#: Add `js-interop` sinks for `Microsoft.JSInterop.IJSRuntime`

---

java/kotlin-extractor2/src/main/kotlin/entities/Expression.kt

We have a query that was complaining that the 2 `extractBinaryExpression` methods had other methods inbetween them. We could just move the definitions together, but actually I think that the 2 methods that I've renamed to `extract...With` are qualitatively different: They don't simply extract what they're given, but they're also being told how to extract it, so I think the `With` suffix makes it clearer what's going on.

KE2: Small method renaming

---

.github/workflows/compile-queries.yml

Avoid running `compile-queries.yml` workflow on changes unrelated to queries (in particular on Kotlin extractor changes).

Include paths on pull_request event trigger for compile-queries.yml workflow

---

csharp/ql/lib/change-notes/2024-11-27-navigationmanager.uri-and-uri-parsing-utilities.md
csharp/ql/lib/ext/Microsoft.AspNetCore.Components.model.yml
csharp/ql/lib/ext/Microsoft.AspNetCore.WebUtilities.model.yml
csharp/ql/lib/ext/System.Web.model.yml
csharp/ql/lib/ext/generated/System.Web.model.yml
csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected

A common way to access the URL of the current page in Asp.NET Core / Blazor applications is through the `NavigationManager.Uri` property. This PR models `NavigationManager::get_Uri` as a remote flow source, as well as several summaries which deal with parsing query strings.
This PR is related to the Blazor modeling work.
~- [ ] All new queries have appropriate `.qhelp`. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-help-style-guide.md) in this repository.~
~- [ ] New and changed queries have correct query metadata. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md) in this repository.~
~- [ ] Autofixes generated based on these changes are valid, only needed if this PR makes significant changes to `.ql`, …

C#: `NavigationManager::Uri` and URI query-string parsing utilities

---

swift/ql/lib/codeql/swift/frameworks/StandardLibrary/RawRepresentable.qll
swift/ql/lib/codeql/swift/frameworks/StandardLibrary/String.qll
swift/ql/test/library-tests/dataflow/taint/libraries/TaintInline.expected

Small fix for the `OptionSet` and `BinaryInteger` models for Swift 6.  I'm particularly displeased with this one as there doesn't seem to be much reason why `BinaryInteger` would apparently not derive from `CustomStringConvertible` any more (hence needing its own model of `.description`), though it does remind me of some of the changes in https://github.com/github/codeql/pull/17989 to integral type models.  Similarly for `OptionSet`, either it's been divorced from `RawRepresentable` or for some reason we're not extracting the association correctly any more.
In any case, all of the test regressions I'm aware of are now fixed.

Swift: Fix for OptionSet and BinaryInteger models

---

rust/ql/lib/codeql/rust/Concepts.qll
rust/ql/lib/codeql/rust/Frameworks.qll
rust/ql/lib/codeql/rust/frameworks/Sqlx.qll
rust/ql/test/query-tests/security/CWE-089/SqlSinks.expected
rust/ql/test/query-tests/security/CWE-089/SqlSinks.ql
rust/ql/test/query-tests/security/CWE-089/sqlx.rs

Following on from https://github.com/github/codeql/pull/18069 , this pull requests adds some sink models for the `rust/sql-injection` query.
I've also added a test for the sinks, since at present we don't have enough flow to get the associated query results for them.

Rust: Sink models for rust/sql-injection

---

csharp/.vscode/launch.json

Add an extra debugging launch configuration for hooking directly into the tracing extractor.

C#: Add launch task for debugging the tracing extractor.

---

rust/extractor/src/rust_analyzer.rs

This is a follow up to https://github.com/github/codeql/pull/18167, addressing a review comment from @paldepind.

Rust: elaborate on `path_to_file_id` comment

---

.devcontainer/devcontainer.json
CODEOWNERS

Upgrades Codespaces default configuration to use Ubuntu 24

Update codespaces default config to ubuntu 24

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ProductFlow.qll
shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll
shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
shared/mad/codeql/mad/modelgenerator/internal/ModelGeneratorImpl.qll

Follows up on https://github.com/github/codeql/pull/17300.

Data flow: Move more logic into `DataFlowImplCommon`

---

java/kotlin-extractor2/src/main/kotlin/KotlinFileExtractor.kt
java/kotlin-extractor2/src/main/kotlin/comments/CommentExtractor.kt
java/kotlin-extractor2/src/main/kotlin/entities/Expression.kt
java/kotlin-extractor2/src/main/kotlin/entities/Function.kt
java/kotlin-extractor2/src/main/kotlin/utils/IrVisitorLookup.kt

As far as I can see, the analysis API isn't giving us fake overrides.

KE2: Remove the fakeOverride code

---

ql/ql/src/queries/style/ValidatePredicateGetReturns.ql
ql/ql/test/queries/style/ValidatePredicateGetReturns/ValidatePredicateGetReturns.expected
ql/ql/test/queries/style/ValidatePredicateGetReturns/ValidatePredicateGetReturns.qlref
ql/ql/test/queries/style/ValidatePredicateGetReturns/test.qll

This PR adds a new query to ensure that predicates starting with 'get' actually return a value. It includes the query definition, expected test results, and test cases to validate the functionality.

Add query to ensure predicates starting with 'get' return a value

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/dataflow/local/main.rs

Adds some amount of data flow through tuples and structs.
One notable omission is that field access to `struct`s is not handled. This is because the field in a `FieldExpression` is a `NameRef` which is not a subclass of `Resolvable`. Hence we can not lookup which `struct` the field is actually for. I think we'll want to have the extractor resolve these `NameRef`s as well, so we can do the same thing that we do for struct-like variants.

Rust: Data flow through tuple and struct fields

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowUtil.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
rust/ql/lib/codeql/rust/dataflow/DataFlow.qll
rust/ql/lib/codeql/rust/dataflow/FlowSummary.qll
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/FlowSummaryImpl.qll
rust/ql/lib/codeql/rust/elements/internal/CallExprBaseImpl.qll
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/dataflow/local/main.rs
rust/ql/test/library-tests/dataflow/models/main.rs
rust/ql/test/library-tests/dataflow/models/models.expected
rust/ql/test/library-tests/dataflow/models/models.ql
shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll

Introduces the class `SummarizedCallable` for defining flow summaries in QL. Models-as-data will be added follow-up.

Rust: Adopt shared flow summaries library

---

rust/ql/lib/codeql/rust/dataflow/FlowSummary.qll
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/dataflow/local/main.rs
rust/ql/test/library-tests/dataflow/models/main.rs

Follow-up to https://github.com/github/codeql/pull/18083 and https://github.com/github/codeql/pull/18078.

Rust: Use canonical paths for variants in data flow

---

docs/codeql/codeql-language-guides/analyzing-data-flow-in-javascript-and-typescript.rst
docs/codeql/codeql-language-guides/codeql-library-for-javascript.rst
docs/codeql/codeql-language-guides/data-flow-cheat-sheet-for-javascript.rst
docs/codeql/codeql-language-guides/using-flow-labels-for-precise-data-flow-analysis.rst
javascript/ql/test/tutorials/Analyzing data flow in JavaScript/Global data flow/query1.ql
javascript/ql/test/tutorials/Analyzing data flow in JavaScript/Global data flow/query2.ql
javascript/ql/test/tutorials/Analyzing data flow in JavaScript/Global data flow/query3.ql
javascript/ql/test/tutorials/Analyzing data flow in JavaScript/Global data flow/query4.ql
javascript/ql/test/tutorials/Analyzing data flow in JavaScript/Global data flow/query5.ql
javascript/ql/test/tutorials/Introducing the JavaScript libraries/query17.qll

The PR updates three documents/tutorials to use `ConfigSig` and flow state:
- The general language introduction
- Ported one `DataFlow::Configuration` to `ConfigSig`
- The data flow tutorial
- Ported a bunch of `DataFlow::Configuration`/`TaintTracking::Configuration` classes to `ConfigSig`
- Also some prose that needed updating.
- Removed mentioned of `isBarrierEdge` which does not exist anymore.
- The flow label tutorial
- Ported `DataFlow::Configuration` to `ConfigSig`
- Replaced flow label API with flow state API. We don't have to create a subclass for each flow label anymore, which greatly simplified the examples (but makes the diff bigger, sorry).
- Replaced "flow label" terminology with "flow state" in the prose.
- Completely rewrote the "API" section near the end
- The article's …

JS: Update data flow documentation and tutorials for JavaScript

---

java/kotlin-extractor2/src/main/kotlin/entities/Expression.kt

`useType` already handles null types, and extracts an error type for them.
The error also includes info about where that came from via the `with` stack, although we might want to make that finer grained in future.

KE2: Remove some unnecessary !!s

---

csharp/extractor/Semmle.Extraction.CSharp/CodeAnalysisExtensions/SymbolExtensions.cs
csharp/extractor/Semmle.Extraction.CSharp/Entities/Method.cs
csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/Type.cs
csharp/extractor/Semmle.Extraction.CSharp/Extractor/Analyser.cs
csharp/extractor/Semmle.Extraction.CSharp/Extractor/Extractor.cs
csharp/ql/lib/change-notes/2024-12-03-public-protected-reference.md
csharp/ql/test/library-tests/conversion/operator/Operator.expected
csharp/ql/test/library-tests/conversion/reftype/RefType.expected
csharp/ql/test/library-tests/csharp9/FunctionPointer.expected
csharp/ql/test/library-tests/tuples/tuples.expected

In this PR we change how much information we extract from reference assemblies.
Prior to this PR all symbols (also private an internal) were extracted from the reference assemblies even though not all of them are accessible outside the assemblies (e.g. it is not possible to call a private method outside the assembly).
With this PR, we only extract *public* and *protected* members ("effectively" public members and types) from the reference assemblies.
There is one identified drawback with this approach, which was identified by DCA:
- If a project exposes its internals to another project and if the project that exposes its internals is referenced as a dll (and not by source), then we get missing call targets (and thereby unknown expression types). This happens in a few cases in our DCA …

C#: Only extract public and protected members from metadata.

---

shared/util/codeql/util/AlertFiltering.qll

This documentation-only PR clarifies that a query should either ignore `restrictAlertsTo` completely or apply `restrictAlertsTo` filtering to all alerts.  This update eliminates the ambiguity on whether a query may choose to apply `restrictAlertsTo` filtering to only some alerts but not others (it may not).

AlertFiltering: prohibit partial filtering

---

csharp/ql/lib/change-notes/2024-12-03-dynamic-field-flow.md
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll
csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected
csharp/ql/test/library-tests/dataflow/fields/L.cs

This PR adds a new kind of `Content` to track flow through dynamic members. For example:
```csharp
dynamic d = ...;
d.Foo = Source();
Sink(d.Foo);
```
since `d` is a `dynamic` the property access `Foo` is not a `FieldOrPropertyAccess` and thus needs special handling.

C#: Add field-flow for dynamic fields

---

rust/ql/src/queries/security/CWE-696/BadCtorInitialization.ql
rust/ql/test/query-tests/security/CWE-696/BadCTorInitialization.expected
rust/ql/test/query-tests/security/CWE-696/test.rs

Improve the `rust/ctor-initialization` query, adding so-called "transitive" results through calls where the target is in the database.

Rust: Improve rust/ctor-initialization

---

go/ql/test/library-tests/semmle/go/dataflow/ExternalFlowInheritance/test_fields.go
go/ql/test/library-tests/semmle/go/dataflow/ExternalFlowInheritance/vendor/github.com/nonexistent/test/stub.go

Trivial change to some tests to fix some spurious results.

Go: Fix some spurious results in ExternalFlowInheritance tests

---

java/kotlin-extractor2/src/main/kotlin/KotlinUsesExtractor.kt
java/kotlin-extractor2/src/main/kotlin/entities/Function.kt

Restore the basics of function label construction from parameter, return and extension receiver types.
Restoration of generics, variances, type substition etc still to do.

KE2: restore basic function label construction

---

csharp/ql/lib/change-notes/2024-12-04-dataflow-type-pruning-tweak.md
csharp/ql/test/library-tests/dataflow/collections/CollectionFlow.expected
csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected
csharp/ql/test/library-tests/dataflow/global/DataFlowPath.expected
csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.expected
java/ql/lib/change-notes/2024-12-04-dataflow-type-pruning-tweak.md
java/ql/test/library-tests/dataflow/capture/inlinetest.expected
java/ql/test/library-tests/frameworks/android/intent/test.expected
java/ql/test/library-tests/frameworks/android/notification/test.expected
shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll

This PR changes how type pruning is done in the data flow library. The primary change is that access paths no longer carry information about tracked types. On its own, this is a precision reduction, so it's combined with a separate precision improvement in that we now track the type of the originally tainted object - this corresponds to the innermost type in an access path, if available, prior to this PR. These two changes mostly balance each other in terms of overall precision, but of course they also affect performance. For Java on MRVA top 1000, this effect was slightly negative with two projects having big degradations in terms of number of computed tuples in certain queries. However, without types in access paths, this now allows other changes, so this PR contains a third tweak that …

Dataflow: Remove tracked types from Access Paths, track tainted object type, and tweak type pruning.

---

cpp/ql/src/Best Practices/GuardedFree.ql

QA exposed a join order problem that happens on #18207 when running `cpp/guarded-free`.
Before:
```ql
[2024-12-04 20:18:49] Tuple counts for _IRGuards::GuardConditionFromIR#2c83f350_10#join_rhs_IRGuards::GuardConditionImpl.valueControls/2#di__#count_range/2@e5cbfe69 after 4m47s:
2822000     ~828%        {2} r1 = SCAN `Operand::Operand.getAnyDef/0#dispred#8dbe2fb8` OUTPUT In.1, In.0
933500      ~15963%      {1}    | JOIN WITH `project#Instruction::Instruction.getUnconvertedResultExpression/0#dispred#d46d1df3` ON FIRST 1 OUTPUT Lhs.1
23966000    ~119664%     {2}    | JOIN WITH `IRGuards::IRGuardCondition.comparesEq/4#dispred#be87109f#ffbff#cpe#1245_103#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Rhs.2
23915563    ~115617%     {2}    | JOIN WITH IRGuards::GuardConditionFromIR#2c83f350_10#join_rhs ON …
```

C++: Fix a join-order problem that happens on #18207

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/NugetPackageRestorer.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/Options.cs
csharp/extractor/Semmle.Extraction.CSharp.Standalone/Program.cs
csharp/extractor/Semmle.Extraction.CSharp/Extractor/ExtractionContext.cs
csharp/extractor/Semmle.Util/Logging/PidStreamWriter.cs
csharp/extractor/Testrunner/Testrunner.cs

As of C# 13 there is a dedicated *lock* object type for threat synchronization: https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13#new-lock-object
This *should* perform slightly better than just locking on another object type.
In this PR we use the new `Lock` type for sync locks where applicable.

C#: Use dedicated lock type where applicable.

---

python/ql/lib/change-notes/2024-11-26-parameter-annotation-api-graph-support.md
python/ql/lib/semmle/python/ApiGraphs.qll
python/ql/lib/semmle/python/dataflow/new/internal/LocalSources.qll
python/ql/test/library-tests/ApiGraphs/py3/test_annotations.py

Adds API graph support for observing that in
```python
def foo(x : Bar): ...
```
The variable `x` is likely to be an instance of the type `Bar` inside this function.
In particular, we add `getInstanceFromAnnotation` as a predicate on API graph nodes that tracks this step (corresponding to a new edge type labeled with "annotation" in the API graph), and extend the existing `getAnInstance` predicate to also include instances arising from type annotations.
A more complete solution would also add support for annotated assignments (`x : Foo = ...` or just `x : Foo`) as well as track types through type aliases (`type Foo = Bar`). This turns out to be non-trivial, however, as these type constructs don't have any CFG nodes (and so no data-flow nodes by default either). In order to not have …

Python: Add API graph support for parameter annotations

---

csharp/.vscode/launch.json
csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/Pattern.cs
csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/RecursivePattern.cs

In this PR we narrow types used for pattern matching for patterns in the extractor (when it comes to variable designation syntax). Otherwise we get a compiler warning when we update Roslyn.

C#: Narrow pattern types

---

cpp/ql/src/Likely Bugs/Format/WrongNumberOfFormatArguments.ql
cpp/ql/src/change-notes/2024-12-05-wrong-number-format-arguments.md
cpp/ql/test/query-tests/Likely Bugs/Format/WrongNumberOfFormatArguments/WrongNumberOfFormatArguments.expected
cpp/ql/test/query-tests/Likely Bugs/Format/WrongNumberOfFormatArguments/syntax_errors.c

Commit-by-commit review encouraged. It's a fairly small fix that removes a grand total of one FP on [DCA](https://github.com/github/codeql-dca-main/blob/data/calumgrant/pr-18194-99efff__nightly-buildle__nightly/reports/alert-comparison.md).

C++: Fix a FP in cpp/wrong-number-format-arguments caused by an extraction error

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependabotProxy.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNetCliInvoker.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/EnvironmentVariableNames.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/NugetPackageRestorer.cs

This PR is part of work to enable private package registries to be used in Default Setup. 
The existing Default Setup workflow will initialise the Dependabot package proxy, if a private package registry configuration is set. The host, port, and certificate used by the proxy are then passed to CodeQL in the `analyze` step. 
The changes in this PR modify the C# extractor to recognise when the corresponding environment variables are set. If so, we use the data from those environment variables to:
1. Construct the proxy address from the host and port and pass it to `dotnet` via the `HTTP_PROXY` and `HTTPS_PROXY` environment variables.
2. Store the certificate on disk, and pass the path to `dotnet` via `SSL_CERT_FILE`.
3. We also configure a suitable proxy for the feed reachability checks.
In …

C#: Set proxy environment variables, if Dependabot proxy is detected

---

rust/ql/integration-tests/hello-project/summary.expected
rust/ql/integration-tests/hello-workspace/summary.cargo.expected
rust/ql/integration-tests/hello-workspace/summary.rust-project.expected
rust/ql/src/queries/summary/SummaryStats.ql
rust/ql/test/query-tests/diagnostics/SummaryStats.expected

Add % of files extracted without errors to summary stats.  Requested by @redsun82 .
- I don't think the `exists(f.getRelativePath())` part makes any difference right now, but let me know if you have a preference about it.
- the 57% number for the test is rather low, reflecting some odd stuff we're doing there.  On `openvmm` I get 91%.
- the number is rounded to an `int`, because I'm not confident I can output a float or string and pick it up in DCA.  Again, if this is a problem please say and I'll look into what I can do.

Rust: Add % of files extracted without errors to summary stats.

---

cpp/ql/src/Likely Bugs/Format/WrongTypeFormatArguments.ql
cpp/ql/src/change-notes/2024-12-05-wrong-type-format-args.md
cpp/ql/test/query-tests/Likely Bugs/Format/WrongTypeFormatArguments/Buildless/WrongTypeFormatArguments.expected
cpp/ql/test/query-tests/Likely Bugs/Format/WrongTypeFormatArguments/Buildless/tests.c

C++: Fix more FPs with extraction errors on cpp/wrong-type-format-arguments

---

cpp/ql/src/Security/CWE/CWE-120/BadlyBoundedWrite.ql
cpp/ql/src/change-notes/2024-12-05-badly-bounded-write.md
cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/BadlyBoundedWrite.expected
cpp/ql/test/query-tests/Security/CWE/CWE-120/semmle/tests/errors.c

C++: Fix FPs in cpp/badly-bounded-write caused by extraction errors

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll

Observed during QA of https://github.com/github/codeql/pull/18207.
Before (on #18207):
```ql
[2024-12-06 12:46:11] Evaluated non-recursive predicate DataFlowUtil::BarrierGuard<UnboundedWrite::lessThanOrEqual>::getABarrierNode/0#fcc0c149@eee4e50o in 695949ms (size: 10004).
Evaluated relational algebra for predicate DataFlowUtil::BarrierGuard<UnboundedWrite::lessThanOrEqual>::getABarrierNode/0#fcc0c149@eee4e50o with tuple counts:
322600    ~0%    {2} r1 = JOIN `Instruction::Instruction.getConvertedResultExpression/0#dispred#f9cfafab` WITH `ValueNumberingInternal::tvalueNumber/1#f03b58f9` ON FIRST 1 OUTPUT Rhs.1, Lhs.1
483600582    ~0%    {2}    | JOIN WITH `ValueNumberingInternal::tvalueNumber/1#f03b58f9_10#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1
467900586    ~0%    {2}    | JOIN WITH …
```

C++: Fix two bad joins in barrier guards

---

csharp/autobuilder/Semmle.Autobuild.CSharp/BUILD.bazel
csharp/autobuilder/Semmle.Autobuild.CSharp/paket.references
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/BUILD.bazel
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/paket.references

Besides cleaning up the dependencies for `Newtonsoft.Json` we also remove `nowarn` from `Build.bazel` in the Dependency fetching project, as it appears to override what is in the project file. Note that in the project file the *default* `NoWarn` is included, which also includes the *global* *default* `NoWarn` for warning 1701 and 1702 (We got a 1702 compiler warning for the dependency fetching project).
This was the last remaining compiler warning.

C#: Clean up dependencies Newtonsoft.Json.

---

java/kotlin-extractor2/src/main/kotlin/KotlinFileExtractor.kt
java/kotlin-extractor2/src/main/kotlin/entities/Expression.kt
java/kotlin-extractor2/src/main/kotlin/entities/FunctionalInterface.kt
java/kotlin-extractor2/src/main/kotlin/entities/MethodCall.kt

It used to sometimes return null, which could mean either it extracted a statement or it failed to extract an expression. Also, what it returned didn't take into account any ExprStmt or StmtExpr wrappers.
Now, it will always return an ID of the type that it StmtExprParent corresponds to.
The essence of the changes is in `KotlinFileExtractor.kt`; the rest is just switching to the new interface.

KE2: extractExpression always returns an ID

---

csharp/BUILD.bazel
csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BUILD.bazel
csharp/autobuilder/Semmle.Autobuild.Cpp.Tests/BUILD.bazel
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/BUILD.bazel
csharp/extractor/Semmle.Extraction.CSharp.StubGenerator/BUILD.bazel
csharp/extractor/Semmle.Extraction.Tests/BUILD.bazel
csharp/extractor/Semmle.Util.Tests/BUILD.bazel

With this, we can finally re-enable the C# unit tests on Windows (no more bazel errors about path length limitations).
The target name appears 3/4 times in the relevant path, so shortening it from the original names to "t" fixes our long-path problem.

C#: Shorten test target names to make Windows happy.

---

csharp/BUILD.bazel
csharp/extractor/Semmle.Util.Tests/LongPaths.cs

I think there are three issues causing the tests to fail when running them via bazel (one can also be provoked locally).
- When tests interact with the file system (eg. creating files) they should do so in a special folder: https://bazel.build/reference/test-encyclopedia#test-interaction-filesystem
- The tests are running in parallel on bazel (this is stated as a comment in our test runner). Since the tests were all interacting with the same file names (copying, creating and deleting) this could cause concurrency issues.
- When executing `File.Delete(path)` a directory not found exception can be thrown (this can happen for the "long" path in case the directory has not been created). This can also happen locally, if tests are not executed in the "right order" (som tests explicitly creates …

C#: Enable Semmle.Util.Tests.

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TypeFlow.qll
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/constant-size/ConstantSizeArrayOffByOne.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test-source-sink.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
cpp/ql/test/library-tests/dataflow/dataflow-tests/uninitialized.expected

This PR fixes a bug where we were incorrectly concluding that a write such as:
```cpp
int xs[10];
*xs = 42;
```
would overwrite the entire object.
Commit-by-commit review recommended (even though the fix is extremely straightforward).

C++: Consider writes to arrays as uncertain

---

rust/ql/lib/codeql/rust/dataflow/FlowSummary.qll
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/FlowSummaryImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/ModelsAsData.qll
rust/ql/lib/codeql/rust/dataflow/internal/empty.model.yml
rust/ql/lib/codeql/rust/frameworks/stdlib/lang-core.model.yml
rust/ql/lib/qlpack.yml
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/dataflow/models/main.rs
rust/ql/test/library-tests/dataflow/models/models.expected
rust/ql/test/library-tests/dataflow/models/models.ext.yml
rust/ql/test/library-tests/dataflow/models/models.ql
rust/ql/test/query-tests/security/CWE-089/SqlInjection.qlref
rust/ql/test/utils/InlineFlowTest.qll
rust/ql/test/utils/PrettyPrintModels.ql
rust/ql/test/utils/ProvenancePathGraph.qll

Adds support for writing model-as-data flow summaries for Rust. This includes flow through variants, records, arrays, and tuples. The format is as follows
```
string crate, string path, string input, string output, string kind, string provenance
```
For example, the flow summary for `unwrap` is
```
"lang:core", "<crate::option::Option>::unwrap", "Argument[self].Variant[crate::option::Option::Some(0)]", "ReturnValue", "value", "manual"
```
Although this PR also adds the extensible predicates for sources and sinks, they are not yet working.

Rust: Models-as-data for flow summaries

---

java/ql/lib/change-notes/2024-12-06-file-getname.md
java/ql/lib/semmle/code/java/security/PathSanitizer.qll
java/ql/test/query-tests/security/CWE-022/semmle/tests/TaintedPath.java

Adds `java.io.File.getName` as a path injection sanitizer.

Java: add File.getName as a path injection sanitizer

---

java/ql/lib/change-notes/2024-11-28-model-resttemplate-getforobject-third-parameter.md
java/ql/lib/ext/org.springframework.web.client.model.yml
java/ql/lib/semmle/code/java/frameworks/spring/SpringWebClient.qll
java/ql/lib/semmle/code/java/security/RequestForgery.qll
java/ql/test/query-tests/security/CWE-918/SpringSSRF.java

I ran MRVA for the ssrf query restricted to only this new sink (before I had added the commit to reduce FPs) and got no alerts. So I don't think this is a commonly used sink.
Note to reviewers: currently I have had to make `HostSanitizingPrefix` public to make this work, and I have introduced a bidirectional import between Spring and RequestForgery. I am very open to suggestions for how to do this better.

Java: add SSRF sink model for the third parameter of `RestTemplate.getForObject`

---

java/ql/lib/semmle/code/java/ControlFlowGraph.qll

This PR is built on top of https://github.com/github/codeql/pull/17970. That should be merged first. Only review after the commit "Undo accidental bugfix".
This PR is purely a refactoring to make the code easier to read and to make it easier to add new kinds of control flow nodes. As a guide I used [the equivalent class in the go library](https://github.com/github/codeql/blob/main/go/ql/lib/semmle/go/controlflow/ControlFlowGraph.qll#L39).

Java: Make separate classes for different control flow node kinds

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll
csharp/ql/lib/semmle/code/csharp/dispatch/Dispatch.qll

When debugging a data flow performance issue, I noticed that we may have incorrect flow out of calls using reflection. 
The data flow library uses the `Dispatch.qll` library to resolve calls, and this library distinguishes between the static target and dynamic targets of calls; for reflection-based calls, any method with matching name and arity is considered a static target, and this is then refined based on type information when calculating dynamic call targets. This means that "static target" of reflection calls is overly broad, and should not be used in data flow.

C#: Remove false-positive reflection calls in dataflow

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

I noticed in a run that `flowThroughOutOfCall` may have a large fan-out when joining `call` with `ccc` through `matchesCall`:
```
[2024-12-10 20:37:27] Evaluated non-recursive predicate DataFlowImpl::MakeImpl<Location::Location,DataFlowImplSpecific::CsharpDataFlow>::Impl<ExternalLocationSink::LocalFileOutputStreamFlow::C>::Stage2::flowThroughOutOfCall/7#306bfe26@3d1aaa28 in 3916ms (size: 109177854).
Evaluated relational algebra for predicate DataFlowImpl::MakeImpl<Location::Location,DataFlowImplSpecific::CsharpDataFlow>::Impl<ExternalLocationSink::LocalFileOutputStreamFlow::C>::Stage2::flowThroughOutOfCall/7#306bfe26@3d1aaa28 with tuple counts:
153181   ~8%    {2} r1 = JOIN `DataFlowImplCommon::DataFlowCallEx.projectToCall/0#dispred#c63e421f` WITH …
```

Data flow: Remove unused column from `flowThroughOutOfCall`

---

javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll
javascript/ql/lib/semmle/javascript/security/TaintedUrlSuffix.qll
javascript/ql/lib/semmle/javascript/security/TaintedUrlSuffixCustomizations.qll
javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectCustomizations.qll
javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectQuery.qll
javascript/ql/test/library-tests/FlowLabels/DefaultFlowLabels.expected
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/ClientSideUrlRedirect.expected
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/Consistency.ql
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/react.js
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/regexp-exec.js
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/tst.js
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/tst10.js
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/tst12.js
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/tst13.js
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/tst15.js
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/tst7.js
javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/typed.ts
javascript/ql/test/testUtilities/ConsistencyChecking.qll

`ClientSideUrlRedirect` used a flow label called `DocumentUrl` to distinguish between fully tainted values and values like `location.href` that only have tainted characters after the first `#` or `?`.
This is also what `TaintedUrlSuffix` is for, so this PR replaces `DocumentUrl` with `TaintedUrlSuffix`.
Also adds (legacy) consistency checking to its test suite and fixes various issues with the tests (this was easier than migrating the whole test suite at this point).
Also improves on `TaintedUrlSuffix` to avoid regressions in alert quality.
Apart from being a general improvement to the query, this is also a preparation for moving away from the `FlowLabel` class, as this is simpler to do when it's using a standard flow label rather than its own query-specific flow label. …

JS: Use TaintedUrlSuffix in ClientSideUrlRedirect

---

go/ql/lib/change-notes/2024-12-13-os-args-model.md
go/ql/lib/ext/os.model.yml
go/ql/lib/semmle/go/frameworks/stdlib/Os.qll
go/ql/test/experimental/CWE-74/DsnInjectionLocal.expected
go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/commandargs/test.expected
go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/commandargs/test.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/commandargs/test.ql
go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/commandargs/test_os.go

`os.Args` cannot be modeled in Models as Data, so it needs a custom QL model.

Go: Model `os.Args` as a `commandargs` source

---

misc/scripts/prepare-db-upgrade.sh

My upstream remote is called `upstream`, not `origin`, as recommended in the internal readme. This bites me every time I have to make a db upgrade script, which is infrequently enough that I always forget in between. @esbena kindly came up with this solution.

Misc: Look up remote name instead of using `origin` in `misc/prepare-db-upgrade.sh`

---

misc/bazel/utils.bzl
swift/BUILD.bazel

This still defines a pack with linux included for development. `//swift:install` will still also include linux.

Swift: remove linux from standard pack

---

misc/bazel/pkg.bzl

This hack is meant to be an optimization when using install for tests, where the install step is skipped if nothing changed. If the installation directory is somehow messed up, `bazel run` can be used to force install.
This is added as a `<name>-installer-as-test` target, which we can now use in our internal pytest integration to skip the installation step if nothing changed on the CLI + language packs side.

Bazel: add a test wrapper around installation scripts

---

csharp/ql/lib/ext/Microsoft.AspNetCore.Components.CompilerServices.model.yml
csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected

Blazor has a static class named `RuntimeHelpers` [(source)](https://github.com/dotnet/aspnetcore/blob/c70204ae3c91d2b48fa6d9b92b62265f368421b4/src/Components/Components/src/CompilerServices/RuntimeHelpers.cs) which provides some methods which help the compiler with callbacks and type checking.
I will model the other `RuntimeHelpers` methods in a subsequent PR, but I need to investigate them further as I model dataflow through Blazor components. `TypeCheck<T>` is an identity function to help with type checking.
Since the [`TypeCheck<T>`](https://github.com/dotnet/aspnetcore/blob/c70204ae3c91d2b48fa6d9b92b62265f368421b4/src/Components/Components/src/CompilerServices/RuntimeHelpers.cs#L20) method is [not to be used directly in application …

C#: Add summary for `Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelper::TypeCheck<T>`

---

csharp/ql/lib/change-notes/2024-12-12-add-markupstring-as-html-injection-sink.md
csharp/ql/lib/ext/Microsoft.AspNetCore.Components.model.yml

Adds `html-injection` sinks for the [`MarkupString`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.markupstring?view=aspnetcore-9.0) class from Blazor's `Microsoft.AspNetCore.Components` library.
`MarkupString` does not escape HTML tags in the string, so it is a potential XSS sink.
~- [ ] All new queries have appropriate `.qhelp`. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-help-style-guide.md) in this repository.~
~- [ ] QL tests are added if necessary. See [Testing custom queries](https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/testing-custom-queries) in the GitHub documentation.~
~- [ ] New and changed queries have correct query metadata. See [the …

C#: Add `html-injection` sinks for Blazor `MarkupString`

---

cpp/ql/lib/CHANGELOG.md
cpp/ql/lib/change-notes/released/3.0.0.md

I don't think it's worth propagating this to all the places where the change note has been copied, but at least this is correct now going forward.

C++: Add word missing from change note

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/test/library-tests/dataflow/barrier/inline-flow.expected
rust/ql/test/library-tests/dataflow/closures/inline-flow.expected
rust/ql/test/library-tests/dataflow/global/inline-flow.expected
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/dataflow/models/models.expected
rust/ql/test/library-tests/dataflow/taint/inline-taint-flow.expected

Always including the left-hand side of an assignment in data flow path graphs make it easier to follow flow. The same goes for scrutinee and patterns in `match` expressions.

Rust: Never skip assignment LHS in data flow

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/gvn/ValueNumbering.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/gvn/ValueNumbering.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/gvn/ValueNumbering.qll

The join order fix in https://github.com/github/codeql/pull/18233 turned out to be slightly incomplete. This can actually be seen in the 'after' tuple counts, but I decided to ignore it since I couldn't find a repository where it was too bad 🙈
Well, jokes on me, because there was actually a repository where this happened (thanks for flagging this up to me, @jketema):
```ql
[2024-12-17 14:53:19] Evaluated non-recursive predicate DataFlowUtil::BarrierGuard<UnboundedWrite::lessThanOrEqual>::getABarrierNode/0#fcc0c149@37a2adb9 in 266575ms (evaluation was halted due to CancellationException).
Evaluated relational algebra for predicate DataFlowUtil::BarrierGuard<UnboundedWrite::lessThanOrEqual>::getABarrierNode/0#fcc0c149@37a2adb9 with tuple counts:
2067749       ~0%    {2} r1 = JOIN …
```

C++: Fix two more dataflow-related joins

---

cpp/ql/lib/change-notes/2024-12-17-template-parameter-base.md
cpp/ql/lib/change-notes/2024-12-17-template-parameter.md
cpp/ql/lib/semmle/code/cpp/Class.qll
cpp/ql/lib/semmle/code/cpp/Declaration.qll
cpp/ql/lib/semmle/code/cpp/Print.qll
cpp/ql/lib/semmle/code/cpp/Type.qll
cpp/ql/lib/semmle/code/cpp/commons/Dependency.qll
cpp/ql/lib/semmle/code/cpp/dataflow/ExternalFlow.qll
cpp/ql/lib/semmle/code/cpp/internal/QualifiedName.qll
cpp/ql/src/Best Practices/Unused Entities/UnusedLocals.ql
cpp/ql/src/Likely Bugs/Arithmetic/PointlessSelfComparison.qll
cpp/ql/src/Likely Bugs/ReturnConstTypeCommon.qll
cpp/ql/src/jsf/4.13 Functions/AV Rule 114.ql
cpp/ql/test/examples/expressions/PrintAST.expected
cpp/ql/test/library-tests/declaration/declaration.cpp
cpp/ql/test/library-tests/ir/ir/PrintAST.expected
cpp/ql/test/library-tests/proxy_class/locations.expected
cpp/ql/test/library-tests/proxy_class/locations.ql

This will enable us to support non-type template parameters, which we currently do not support, and error template parameters, which might become relevant in the `build-mode: none` context.
DCA was ran on the internal PR.

C++: Introduce a new base class for template parameters

---

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/SignAnalysisCommon.qll

It's well-known that recursion through `forall`/`forex` may perform poorly. Apparently we do recursion through `forex` in the sign analysis library (which is part of the new range analysis library for C++). This results in some unfortunate tuple counts because the "range" part of the `forall`/`forex` gets joined with itself:
```ql
Tuple counts for _RangeAnalysisImpl::SignAnalysis::zeroBound/3#c119dcdb_RangeAnalysisImpl::SignAnalysis::zeroBound/3#__#antijoin_rhs/3@i4#L3#76559w2g after 1m28s:
256000    ~900%         {4} r1 = JOIN `RangeAnalysisImpl::SignAnalysis::zeroBoundOk/3#a6688e7a#prev_delta` WITH num#Sign::TZero#65a6fcab CARTESIAN PRODUCT OUTPUT Lhs.0, Lhs.1 'arg1', Lhs.2 'arg2', Rhs.0
251000    ~1835%        {3}    | JOIN WITH `RangeAnalysisImpl::SignAnalysis::zeroBound/3#c119dcdb` …
```

C++: Fix `forex` recursion in sign analysis

---

java/ql/test/library-tests/dataflow/deduplicate-path-graph/A.java
java/ql/test/library-tests/dataflow/deduplicate-path-graph/test.expected
java/ql/test/library-tests/dataflow/deduplicate-path-graph/test.ql
ruby/ql/src/queries/security/cwe-094/CodeInjection.ql
ruby/ql/test/query-tests/security/cwe-094/CodeInjection/CodeInjection.expected
shared/dataflow/change-notes/2023-10-02-deduplicate-path-graph.md
shared/dataflow/codeql/dataflow/DataFlow.qll

Adds a shared parameterised module, `DataFlow::DeduplicatePathGraph`, for post-processing a `PathGraph` so that it doesn't result in duplicate alerts or alerts with multiple identical paths.
This issue usually arises from using `FlowState`, which is embedded in the `PathNode` but not rendered as part of its string value. This can thus result in paths that have different intermediate flow states but appear to be identical to the end-user.
The issue with multiple alerts, i.e. seemingly-identical rows in the `#select` clause, is particularly bad for tools that attempt to diff results (such as DCA) but does not perform its own deduplication in advance.
The module works by projecting `PathNode` down to their `(node, toString)` values, which is closer to what the end-user actually sees in the …

Shared: Add DataFlow::DeduplicatePathGraph

---

csharp/ql/lib/ext/Microsoft.AspNetCore.Components.model.yml
csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected

The `NavigationManager` was accidentally spelled `NagivationManager`.

Fix typo in `NavigationManager` name in models

---

cpp/ql/test/library-tests/builtins/type_traits/clang.cpp
cpp/ql/test/library-tests/clang_builtin_macros/extended.cpp
cpp/ql/test/library-tests/complex_numbers/conjugation.c
cpp/ql/test/library-tests/complex_numbers/test.c
cpp/ql/test/library-tests/constants/addresses/addresses.cpp
cpp/ql/test/library-tests/constexpr_if/test.cpp
cpp/ql/test/library-tests/conversions/complex.c
cpp/ql/test/library-tests/fold/fold.cpp
cpp/ql/test/library-tests/ir/ir/complex.c
cpp/ql/test/library-tests/ir/ir/coroutines.cpp
cpp/ql/test/library-tests/ir/types/complex.c
cpp/ql/test/library-tests/specifiers2/cpp20.cpp
cpp/ql/test/library-tests/structs/compatible_c/b1.c
cpp/ql/test/library-tests/structs/compatible_c/b2.c
cpp/ql/test/library-tests/structs/compatible_c/c1_gnu.c
cpp/ql/test/library-tests/structs/compatible_c/c2_gnu.c
cpp/ql/test/library-tests/syntax-zoo/builtin.c
cpp/ql/test/library-tests/syntax-zoo/cpp11.cpp
cpp/ql/test/library-tests/syntax-zoo/cpp17.cpp
cpp/ql/test/library-tests/types/datasizeof/datasizeof.cpp
cpp/ql/test/library-tests/vector_types/vector_types.cpp

C++: Simplify some semmle-extractor-options in tests

---

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.19.4.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.20.0.rst
docs/codeql/codeql-overview/codeql-changelog/index.rst

Add detailed changelog entries for CodeQL versions 2.19.4 and 2.20.0, highlighting new features, bug fixes, and improvements.

Update CodeQL changelog for versions 2.19.4 and 2.20.0

---

cpp/ql/test/library-tests/unspecified_type/types/unspecified_type.expected

C++: Update test after extractor changes

---

actions/ql/src/Security/CWE-829/UnversionedImmutableAction.md

Clarify immutable actions help text to indicate that sha pinning also guarantees immutability.

Clarify immutable actions help text

---

actions/ql/src/Security/CWE-829/UnversionedImmutableAction.ql
actions/ql/src/codeql-suites/actions-all.qls
actions/ql/src/codeql-suites/actions-bughalla.qls
actions/ql/src/codeql-suites/actions-code-scanning.qls
actions/ql/src/codeql-suites/actions-security-and-quality.qls
actions/ql/src/codeql-suites/actions-security-extended.qls

This PR updates the suite files for the Actions queries:
= Added `actions-security-extended.qls`, which is needed for Default Setup.
- Made `actions-security-extended.qls` just import `actions-code-scanning.qls`, since the set of queries is the same for now.
- Made `actions-security-and-quality.qls` just import `actions-security-extended.qls`, since the set of queries is the same for now.
- Replaced "Actions" with "GitHub Actions" in the suite descriptions, to match how we display the language name in the Code Scanning UI.
I also marked the `UnversionedImmutableAction.ql` query with the `internal` tag, and added an exclusion for `internal` queries in the suite file. This query refers to a feature that is not yet generally available, so it's causing customer confusion.

Update suites for Actions queries

---

csharp/ql/lib/change-notes/2024-12-18-blazor-attribute-sources.md
csharp/ql/lib/ext/Microsoft.AspNetCore.Components.model.yml
csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected

The attributes
~- [`[Parameter]`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.parameterattribute?view=aspnetcore-8.0)~
- [`[SupplyParameterFromFormAttribute]`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.SupplyParameterFromFormAttribute?view=aspnetcore-8.0)
- [`[SupplyParameterFromQueryAttribute]`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.SupplyParameterFromQueryAttribute?view=aspnetcore-8.0)
Tell Blazor to initialize the variables with parameters defined by the route/form values/query parameters/etc. Values derived from the URI or form should be classified as `remote` flow sources.
~- [ ] All new queries have appropriate `.qhelp`. See [the …

C#: Add common sources for Blazor components

---

rust/autobuild/src/main.rs
rust/extractor/src/config.rs
rust/ql/integration-tests/file-exclusions/codeql-config.yml
rust/ql/integration-tests/file-exclusions/source_archive.default.expected
rust/ql/integration-tests/options/cfg/functions.expected
rust/ql/integration-tests/options/cfg/functions.override.expected
rust/ql/integration-tests/options/cfg/src/lib.rs
rust/ql/integration-tests/options/cfg/test_cfg_overrides_option.py

Users will still be able to opt out:
* for unit tests, by providing the `cargo_cfg_overrides=-test` extractor option
* for integration tests, by excluding the test files from the analysis using `paths-ignore` in the codescanning configuration file
We may want to revisit whether we want a single option for both. Also further work will be needed to restrict our security queries to non-test code on the QL side.

Rust: reinstate extraction of test code

---

csharp/ql/test/library-tests/strings/Strings.cs
csharp/ql/test/library-tests/strings/stringLiterals.expected
csharp/ql/test/library-tests/strings/stringLiterals.ql

This is a test only PR (no extractor or library development required).
In this PR we add a test using the new escape sequence `\e` for the ESCAPE character. `\e` is syntactic sugar for `\u001b`. The new feature is described [here](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13#new-escape-sequence).

C# 13: [TEST ONLY] Add test using the new escape char for ESCAPE.

---

cpp/ql/lib/change-notes/2024-12-20-sizeof-pack.md

Mostly the change notes of:
* https://github.com/github/codeql/pull/18320
* https://github.com/github/codeql/pull/18360

C++: Slightly tweak change note to make it more consistent with others

---

.github/codeql/codeql-config.yml

This will also exclude code examples in `rust/ql/src/queries`.

Rust: extend `paths-ignore` to all `rust/ql`

---

go/ql/test/query-tests/Security/CWE-079/StoredXss.qlref

Updates the `StoredXss.qlref` test to use test post-processing. 
Merging this separately will make the `database` source model PRs easier.

Go: Add post-processing to StoredXss.qlref test

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

Remove a few predicates that I noticed didn't have any uses.

Dataflow: Remove some dead code.

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll

Example tuple counts (~10 % reduction in stage 1):
\# | n | stage | nodes | fields | conscand | states | tuples | calledges | tfnodes | tftuples
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 10 | 1 Fwd | 3,530,293 | 37,778 | -1 | 1 | 5,111,856 | -1 | -1 | -1
2 | 15 | 1 Rev | 2,195,396 | 29,094 | -1 | 1 | 3,366,038 | 2,078,437 | -1 | -1
3 | 20 | 2 Fwd | 668,068 | 5,322 | 6,521 | 1 | 1,291,454 | 516,310 | 0 | 0
4 | 25 | 2 Rev | 351,997 | 3,170 | 3,673 | 1 | 526,910 | 125,603 | 0 | 0
5 | 30 | 3 Fwd | 19,865 | 75 | 89 | 1 | 27,492 | 6,212 | 1,108 | 2,127
\# | n | stage | nodes | fields | conscand | states | tuples | calledges | tfnodes | tftuples
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 10 | 1 Fwd | 3,460,957 | 37,591 | -1 | 1 | 4,764,986 | -1 | -1 | -1
2 | 15 | 1 …

Data flow: Prune parameter-self flow in stage 1

---

go/ql/lib/ext/database.sql.driver.model.yml
go/ql/lib/ext/database.sql.model.yml
go/ql/lib/semmle/go/frameworks/stdlib/DatabaseSql.qll
go/ql/test/query-tests/Security/CWE-078/StoredCommand.expected
go/ql/test/query-tests/Security/CWE-079/StoredXss.expected

There have been some issues with variable arguments in source models in MaD. This reverts some models back to being modeled in QL.

Go: Revert MaD models for `database/sql` to use QL instead

---

config/identical-files.json
rust/ql/integration-tests/hello-project/summary.expected
rust/ql/integration-tests/hello-workspace/summary.cargo.expected
rust/ql/integration-tests/hello-workspace/summary.rust-project.expected
rust/ql/lib/codeql/rust/security/SensitiveData.qll
rust/ql/lib/codeql/rust/security/internal/SensitiveDataHeuristics.qll
rust/ql/src/queries/summary/SensitiveData.ql
rust/ql/src/queries/summary/SummaryStats.ql
rust/ql/test/library-tests/sensitivedata/SensitiveData.ql
rust/ql/test/library-tests/sensitivedata/test.rs
rust/ql/test/query-tests/diagnostics/SummaryStats.expected

Add a library for recognising sensitive data in Rust.  The core logic in `SensitiveDataHeuristics.qll` is shared between languages, the integration in `SensitiveData.qll` is Rust specific (so are the tests and summary queries).
The implementation here is a bit minimal, there's a lot I want to improve both in the integration and in the shared library.  However I'm keen to get something in place and working so that I can start building queries on top of this alongside making improvements to it.

Rust: Sensitive data library

---

javascript/ql/lib/semmle/javascript/dataflow/AdditionalTaintSteps.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowPrivate.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/VariableCapture.qll
javascript/ql/lib/semmle/javascript/internal/flow_summaries/Arrays.qll
javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssQuery.qll
javascript/ql/lib/semmle/javascript/security/dataflow/PrototypePollutingAssignmentQuery.qll
javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeCodeConstruction.qll
javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeHtmlConstructionQuery.qll
javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeJQueryPluginQuery.qll
javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeShellCommandConstructionQuery.qll
javascript/ql/lib/semmle/javascript/security/dataflow/XssThroughDomQuery.qll
javascript/ql/lib/semmle/javascript/security/regexp/PolynomialReDoSQuery.qll
javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/lib/lib.js

All TODO comments have corresponding issues internally.
There are a few TODOs that I left in when in cases where they add clarification and represent a relatively local task close to where the comment appears. For larger tasks, issues are more appropriate.

JS: Clean up some TODO comments

---

docs/codeql/ql-language-reference/modules.rst

AFAIUI this will be merged as part of the next release, when the .bitLength() primitive will be available, so should probably be merged alongside/before that.

Language reference: mention BigInt.bitLength()

---

javascript/extractor/src/com/semmle/ts/extractor/TypeScriptASTConverter.java
javascript/ql/src/change-notes/2025-01-09-import-spec-strings.md
javascript/ql/test/library-tests/Modules/arbitrarySpecifier.ts
javascript/ql/test/library-tests/Modules/tests.expected

Fixes https://github.com/github/codeql/issues/18336

JS: Fix crash in case of string literal in export specifier

---

cpp/ql/lib/change-notes/2025-01-07-config.md
cpp/ql/lib/semmle/code/cpp/ConfigurationTestFile.qll
cpp/ql/src/Best Practices/SloppyGlobal.ql
cpp/ql/src/Critical/OverflowStatic.ql
cpp/ql/src/Likely Bugs/Arithmetic/FloatComparison.ql
cpp/ql/src/Likely Bugs/Likely Typos/ExprHasNoEffect.ql
cpp/ql/src/Likely Bugs/Underspecified Functions/TooFewArguments.ql
cpp/ql/src/Security/CWE/CWE-120/BadlyBoundedWrite.ql
cpp/ql/src/Security/CWE/CWE-732/DoNotCreateWorldWritable.ql
cpp/ql/src/change-notes/2025-01-07-cmake.md
cpp/ql/test/query-tests/Likely Bugs/Likely Typos/ExprHasNoEffect/CMakeFiles/CMakeScratch/TryCompile-abcdef/CheckFunctionExists.c
cpp/ql/test/query-tests/Likely Bugs/Likely Typos/ExprHasNoEffect/CMakeFiles/CMakeScratch/TryCompile-abcdef/ExprHasNoEffect.expected
cpp/ql/test/query-tests/Likely Bugs/Likely Typos/ExprHasNoEffect/CMakeFiles/CMakeScratch/TryCompile-abcdef/ExprHasNoEffect.qlref

This silences alert wobble, as the suffix of CMake `TryCompile-` directories is random and changes each time a project is built.
There's probably other queries where this makes sense, but for now I've limited myself to queries for which I concretely observed `TryCompile-` files showing up.
DCA nightly shows that the neovim alerts on `TryCompile-` files disappears, and similarly for DCA autobuild posix and .NET diagnostics.

C++: Silence alerts coming from CMake test compilation files

---

cpp/ql/lib/ext/oleauto.model.yml
cpp/ql/src/change-notes/2025-01-09-SysAllocString.md
cpp/ql/test/library-tests/dataflow/external-models/flow.expected
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/test_mad-signatures.expected

The lack of these models were causing some false negatives at Microsoft.

C++: Add MaD models for `SysAllocString` and friends

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/FlowSummaryImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
go/ql/lib/semmle/go/dataflow/ExternalFlow.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
rust/ql/lib/codeql/rust/dataflow/FlowSink.qll
rust/ql/lib/codeql/rust/dataflow/FlowSource.qll
rust/ql/lib/codeql/rust/dataflow/FlowSummary.qll
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/FlowSummaryImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/ModelsAsData.qll
rust/ql/lib/utils/test/InlineFlowTest.qll
rust/ql/test/library-tests/dataflow/models/main.rs
rust/ql/test/library-tests/dataflow/models/models.expected
rust/ql/test/library-tests/dataflow/models/models.ext.yml
rust/ql/test/library-tests/dataflow/models/models.ql
shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll
shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll

This PR adds support for defining flow sources/sinks for Rust with non-trivial access paths. For example, one may define
```yml
extensions:
- addsTo:
pack: codeql/rust-all
extensible: sourceModel
data:
- ["repo::test", "crate::my_option_source", "ReturnValue.Variant[crate::option::Option::Some(0)]", "test-source", "manual"]
```
which models calls to `crate::my_option_source` as flow sources of kind `test-source`, but where the origin of tainted data is not directly the result of the call, but rather stored inside `Option::Some` in the result of the call.
Similarly, one may define a sink restricted to data stored inside `Option::Some`:
```yml
extensions:
- addsTo:
pack: codeql/rust-all
extensible: sinkModel
data:
- ["repo::test", "crate::my_option_sink", …
```

Rust: Add support for MaD sources and sinks with access paths

---

python/ql/lib/change-notes/2024-12-11-lxml-flowsteps.md
python/ql/lib/semmle/python/frameworks/Lxml.qll
python/ql/test/library-tests/frameworks/lxml/InlineTaintTest.expected
python/ql/test/library-tests/frameworks/lxml/InlineTaintTest.ql
python/ql/test/library-tests/frameworks/lxml/taint_test.py
shared/threat-models/ext/supported-threat-models.model.yml

Models additional flow steps for `Element` and `ElementTree` objects from the `lxml.etree` module, to track taint through parsed XML elements.

Python: Model additional flow steps for the lxml framework

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependabotProxy.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNetCliInvoker.cs

This fixes an extractor crash if any of the three environment variables are already set (existing values will be overridden). This problem was reported to us by a customer who already has `HTTP_PROXY` and `HTTPS_PROXY` set on their runner. Overriding the existing values should be the desired behaviour here, because the Dependabot proxy settings are only available if there is a private registry configuration and the Dependabot proxy was started.
I have also removed some incorrect log output in the first commit.

C#: Fix crash if proxy environment variables are already set

---

csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/TypeParameterConstraints.cs
csharp/ql/lib/change-notes/2025-01-03-allow-ref-struct.md
csharp/ql/lib/semmle/code/csharp/Conversion.qll
csharp/ql/lib/semmle/code/csharp/Generics.qll
csharp/ql/lib/semmle/code/csharp/Type.qll
csharp/ql/lib/semmle/code/csharp/Unification.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/test/library-tests/conversion/boxing/Boxing.cs
csharp/ql/test/library-tests/conversion/boxing/Boxing.expected
csharp/ql/test/library-tests/csharp11/PrintAst.expected
csharp/ql/test/library-tests/csharp7.2/PrintAst.expected
csharp/ql/test/library-tests/csharp7.2/RefStructs.ql
csharp/ql/test/library-tests/dispatch/CallContext.expected
csharp/ql/test/library-tests/dispatch/CallGraph.expected
csharp/ql/test/library-tests/dispatch/GetADynamicTarget.expected
csharp/ql/test/library-tests/dispatch/ViableCallable.cs
csharp/ql/test/library-tests/typeparameterconstraints/TypeParameterConstraints.cs
csharp/ql/test/library-tests/typeparameterconstraints/typeParameterConstraints.expected
csharp/ql/test/library-tests/typeparameterconstraints/typeParameterConstraints.ql
csharp/ql/test/library-tests/unification/Unification.cs
csharp/ql/test/library-tests/unification/Unification.expected

In this PR we introduce support for the `allows ref struct` type parameter constraint. The language feature is described [here](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13#allows-ref-struct).
A couple of notes on the implementation.
- A `ref struct` type can not be implicitly converted to a `dynamic` type, `object` or `ValueType`.
- The `allows ref struct` is a *negative* constraint meaning that it extends the number of types that can be used as type replacement for a type parameter.
The *unification* and *dispatch* *call* logic has been adapted to take the `allows ref struct` constraint into account (relevant for dynamic dispatch) for deciding relevant dispatch targets. To make things easier a new class `RefStruct` has been introduced in the type hierarcy. One …

C# 13: Allows ref struct.

---

java/ql/lib/semmle/code/java/security/Encryption.qll
java/ql/src/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql
java/ql/src/change-notes/2024-11-29-java-weak-crypto-algorithm-explanation.md
java/ql/test/library-tests/Encryption/Test.java
java/ql/test/library-tests/Encryption/cryptoalgospec.expected
java/ql/test/library-tests/Encryption/insecure.expected
java/ql/test/library-tests/Encryption/insecure.ql
java/ql/test/library-tests/Encryption/secure.expected
java/ql/test/query-tests/security/CWE-327/semmle/tests/BrokenCryptoAlgorithm.expected

Java: Make `java/weak-cryptographic-algorithm` give  a reason why the algo is insecure

---

rust/extractor/src/config.rs
rust/extractor/src/main.rs

This shows a marginal performance gain (~2% average).

Rust: run sysroot discovery once

---

cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll
cpp/ql/src/Security/CWE/CWE-120/UnboundedWrite.ql

This fixes a performance problem in https://github.com/github/codeql/pull/18017 on some projects compiled as C code (where we infer many new guards on https://github.com/github/codeql/pull/18017 which causes the barrier to explode in size).
This PR adds a very cheap pruning phase to the `cpp/unbounded-write` query. The "cheapness" comes from the fact that we only evaluate the first stage of dataflow. This provides enough pruning to make the performance impact of https://github.com/github/codeql/pull/18017 negligible (compare [this run](https://github.com/github/codeql-dca-main/tree/data/MathiasVP/generate-int-to__nightly__nightly__3/reports) with [this run](https://github.com/github/codeql-dca-main/tree/data/MathiasVP/generate-int-to__nightly__nightly__2/reports)).

C++: Speed up the `cpp/unbounded-write` query for an upcoming change

---

cpp/ql/lib/change-notes/2025-01-13-indirect-instruction-barrier-guard.md
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/test/library-tests/dataflow/ir-barrier-guards/test.cpp
cpp/ql/test/library-tests/dataflow/ir-barrier-guards/test.ql

On `main` we have `BarrierGuards` for:
- `Operand`/`Instruction` nodes for reasoning about barriers at the instruction level (using `DataFlow::InstructionBarrierGuard<myPredicate/3>::getABarrierNode()`)
- `Expr` nodes for reasoning about barriers at the expression level (using DataFlow::BarrierGuard<myPredicate/3>::getABarrierNode()`)
- Indirect `Expr` nodes for reasoning about barriers on the pointed-to value of an expression (using `DataFlow::BarrierGuard<myPredicate/3>::getAnIndirectBarrierNode()`)
Spot an obvious missing one? We never added a `BarrierGuard` for reasoning about indirect instruction/operand nodes.
Barriers on indirections are nice when working with functions that validate the data pointed to by an argument to a function call. For example:
```cpp
bool isValidData(char* …
```

C++: Add a `BarrierGuard` module for indirect instruction/operand nodes.

---

java/ql/src/Likely Bugs/Serialization/MissingVoidConstructorsOnSerializable.qhelp

Note I haven't included a reference because I can't find a sufficiently-authoritative source -- only a blog quoting Effective Java seems close to appropriate, and I suspect that's pirated.

Java: document serialization proxy pattern

---

javascript/ql/lib/change-notes/2025-01-10-sensitive-data.md
javascript/ql/lib/semmle/javascript/security/internal/SensitiveDataHeuristics.qll
python/ql/lib/change-notes/2025-01-10-sensitive-data.md
python/ql/lib/semmle/python/security/internal/SensitiveDataHeuristics.qll
ruby/ql/lib/change-notes/2025-01-10-sensitive-data.md
ruby/ql/lib/codeql/ruby/security/internal/SensitiveDataHeuristics.qll
rust/ql/lib/codeql/rust/security/internal/SensitiveDataHeuristics.qll
rust/ql/test/library-tests/sensitivedata/test.rs
swift/ql/lib/change-notes/2025-01-10-sensitive-data.md
swift/ql/lib/codeql/swift/security/SensitiveExprs.qll
swift/ql/lib/codeql/swift/security/internal/SensitiveDataHeuristics.qll

Improve the share sensitive data library handling of `snake_case` variable names.  This is especially relevant for Rust, where snake case is encouraged and widely used, but the main change is in the shared `SensitiveDataHeuristics.qll` file and will affect (hopefully benefit) other languages as well.  It's a simple change, but we need a fairly high level of confidence / agreement before merging this.
Testing:

Improve shared sensitive data library handling of snake_case variable names

---

cpp/ql/src/Critical/ScanfChecks.qll

This is a no-op for now since the `Instruction` for which `Instruction.getUnconvertedResultExpression()` is a `Call` is obviously the `CallInstruction`, but once we add the instructions which compute the implicit `!= 0` the `CompareNE` instruction will also have the `Call` as the result of `Instruction.getUnconvertedResultExpression()`.
So to fix this we can restrict the type of `i` to be a `CallInstruction`

C++: Harden `checkedForEof`

---

csharp/ql/test/library-tests/async/Async.expected
csharp/ql/test/library-tests/async/Await.expected
csharp/ql/test/library-tests/async/async.cs
csharp/ql/test/library-tests/iterators/iterators.cs
csharp/ql/test/library-tests/iterators/iterators.expected
csharp/ql/test/library-tests/iterators/iterators.ql

For C# 13 we are now allowed to use ref locals, ref structs and unsafe context in iterators and async methods as described [here](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13#ref-and-unsafe-in-iterators-and-async-methods).
In this PR we just add some code examples to check that this compiles and doesn't fail during extraction.

C# 13: [TEST ONLY] Test example with ref local, unsafe context and ref struct in async- and iterator methods.

---

csharp/ql/test/library-tests/implements/Implements.cs
csharp/ql/test/library-tests/implements/Implements.expected
csharp/ql/test/library-tests/implements/Implements.ql

`ref struct` types are now allowed to implement interfaces as described [here](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-13#ref-struct-interfaces).
In this PR we add some tests for this. Some testing of data flow and viable callable was already made in https://github.com/github/codeql/pull/18385

C# 13: [TEST ONLY] ref structs are allowed to implement interfaces.

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

This was identified by the join-order metric. It's not recursive, so it didn't hurt us too much, but it's an easy fix.
Before:
```
[2025-01-16 10:32:29] Evaluated non-recursive predicate DataFlowImpl::MakeImpl<Location::Location,DataFlowImplSpecific::JavaDataFlow>::Impl<SensitiveLoggingQuery::SensitiveLoggerFlow::C>::S6Graph::fwdFlowInStep/10#316df909@3f9c0ft4 in 13ms (size: 38324).
Evaluated relational algebra for predicate DataFlowImpl::MakeImpl<Location::Location,DataFlowImplSpecific::JavaDataFlow>::Impl<SensitiveLoggingQuery::SensitiveLoggerFlow::C>::S6Graph::fwdFlowInStep/10#316df909@3f9c0ft4 with tuple counts:
15972   ~0%    {7} r1 = JOIN `num#DataFlowImpl::MakeImpl<Location::Location,DataFlowImplSpecific::JavaDataFlow>::Impl<SensitiveLoggingQuery::SensitiveLoggerFlow::C>::Stage6::TS …
```

Dataflow: Minor join-order fix

---

javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSummaryPrivate.qll

Fixes a semantic merge conflict between https://github.com/github/codeql/pull/18467 and https://github.com/github/codeql/pull/18298

JS: Fix semantic merge conflict: Implement new signature members in StepInputSig

---

cpp/ql/lib/DefaultOptions.qll
cpp/ql/lib/change-notes/2025-01-16-noreturn.md
cpp/ql/test/query-tests/jsf/4.13 Functions/AV Rule 114/AV Rule 114.expected
cpp/ql/test/query-tests/jsf/4.13 Functions/AV Rule 114/test.c
cpp/ql/test/query-tests/jsf/4.13 Functions/AV Rule 114/test.cpp

C++: Support more "noreturn" attributes in DefaultOptions

---

cpp/ql/src/Architecture/Refactoring Opportunities/ClassesWithManyFields.ql

We have not supported Objective-C for a long time.

C++: Remove some Objective-C specific query code

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

The first commit tweaks a join-order slightly: We can add the final column of `readStepFwd` to the join as a noop, but then `ap2 = apCons(c, ap1)` becomes implied and can be dropped, which simplifies things. This was mainly motivated by the second commit to get a cleaner RA diff.
The second commit fixes an actual join-order issue in `S6Graph::localStep/10`.
Before:
```
[2025-01-16 10:31:51] Evaluated non-recursive predicate DataFlowImpl::MakeImpl<Location::Location,DataFlowImplSpecific::JavaDataFlow>::Impl<SensitiveLoggingQuery::SensitiveLoggerFlow::C>::S6Graph::localStep/10#eaf7e0b3@d7e3e562 in 46ms (size: 49487).
Evaluated relational algebra for predicate DataFlowImpl::MakeImpl<Location::Location,DataFlowImplSpecific::JavaDataFlow>::Impl<SensitiveLoggingQuery::SensitiveLoggerFlow::C>::S6 …
```

Dataflow: Another minor join-order fix

---

javascript/extractor/src/com/semmle/js/extractor/HTMLExtractor.java
javascript/extractor/src/com/semmle/js/extractor/Main.java
javascript/ql/lib/semmle/javascript/DOM.qll
javascript/ql/lib/semmle/javascript/frameworks/Angular2.qll
javascript/ql/lib/semmle/javascript/security/dataflow/XssThroughDomCustomizations.qll
javascript/ql/src/change-notes/2025-01-09-angular2-xss-through-dom.md
javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/XssThroughDom.expected
javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/angular.ts

Adds support for a few sources of form inputs and DOM objects coming from Angular:
- Recognise `$event` inside an Angular event handler as a source of DOM events
- Recognise `NgForm.value` as a source of form input
- Recognise `[(ngModel)]` two-way data binding as a source of form input

JS: Add Angular2 DOM sources

---

rust/ql/integration-tests/hello-project/summary.expected
rust/ql/integration-tests/hello-workspace/summary.cargo.expected
rust/ql/integration-tests/hello-workspace/summary.rust-project.expected
rust/ql/src/queries/summary/CryptographicOperations.ql
rust/ql/src/queries/summary/QuerySinkCounts.ql
rust/ql/src/queries/summary/QuerySinks.ql
rust/ql/src/queries/summary/Stats.qll
rust/ql/src/queries/summary/SummaryStats.ql
rust/ql/src/queries/summary/TaintReach.qll
rust/ql/test/query-tests/diagnostics/SummaryStats.expected

Add more metrics for tracking taint flow in Rust.  Prior to this PR we have:
- taint sources, tracked by `rust/summary/taint-sources` and `rust/summary/summary-statistics`.
- sensitive data (which are also commonly used as taint sources), tracked by `rust/summary/sensitive-data` and `rust/summary/summary-statistics`.
Which doesn't give us a very complete picture.  This PR adds:
- query sinks, tracked by `rust/summary/query-sinks`, `rust/summary/query-sink-counts` and `rust/summary/summary-statistics`.
- cryptographic operations (which are also commonly used as taint sinks), tracked by `rust/summary/cryptographic-operations` and `rust/summary/summary-statistics`.
- taint edges (raw count), tracked by `rust/summary/summary-statistics`.
- taint reach, tracked by …

Rust: More metrics for tracking taint.

---

cpp/ql/test/library-tests/preprocessor/preprocessor/pp.cpp
cpp/ql/test/library-tests/preprocessor/preprocessor/pp.h
cpp/ql/test/library-tests/preprocessor/preprocessor/preproc.expected

Note that the new test case shows that line splicing is not correctly handled in the case of `#if`.

C++: Uncomment preprocessor test cases and add addition `#if` test case

---

cpp/ql/test/library-tests/preprocessor/preprocessor/pp.cpp
cpp/ql/test/library-tests/preprocessor/preprocessor/pp.h
cpp/ql/test/library-tests/preprocessor/preprocessor/preproc.expected

C++: Uncomment more preprocessor tests

---

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll

Alternative to https://github.com/github/codeql/pull/18355.
For a summary edge `arg->par->ret->out` found in reverse flow with access paths `ap` at `arg`/`par` and `innerReturnAp` at `ret`/`out` it seems superfluous to include `innerReturnAp` in the call-edge `arg`-`par` join. The added constraint is that a path exists between `par` and `ret` with those access paths, but when we join `flowThroughIntoCall` in reverse flow, then that exactly what we just established, so I don't think it adds much (if anything). Dropping the column avoids the need to materialize a combination of 3 access paths (`ap`, `innerReturnAp`, and `returnAp`) that can vary independently in degenerate cases.

Dataflow: Simplify the call-edge join in reverse through-flow.

---

go/ql/lib/change-notes/2024-12-16-any-content-readers.md
go/ql/lib/ext/text.template.model.yml
go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowUtil.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
go/ql/lib/semmle/go/dataflow/internal/TaintTrackingUtil.qll
go/ql/lib/semmle/go/frameworks/stdlib/NetHttp.qll
go/ql/lib/semmle/go/frameworks/stdlib/TextTemplate.qll
go/ql/test/library-tests/semmle/go/frameworks/serialization/test.ql
go/ql/test/library-tests/semmle/go/frameworks/serialization/texttemplate.go

Add a mechanism for specifying dataflow nodes that ought read taint through any access path, and use it to make `template/text` functions read taint out of fields.
Note this PR currently has https://github.com/github/codeql/pull/18355 applied because it appears to significantly improve performance for some outlier repositories. This shouldn't be merged until that PR has been dealt with.

Go: `template/text.Template` execution methods: support reading arbitrary content

---

MODULE.bazel
docs/codeql/reusables/supported-versions-compilers.rst
java/kotlin-extractor/deps/kotlin-compiler-2.1.20-Beta1.jar
java/kotlin-extractor/deps/kotlin-compiler-embeddable-2.1.20-Beta1.jar
java/kotlin-extractor/deps/kotlin-stdlib-2.1.20-Beta1.jar
java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
java/kotlin-extractor/src/main/kotlin/utils/ClassNames.kt
java/kotlin-extractor/src/main/kotlin/utils/TypeSubstitution.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_5_0/IrBuiltIns.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_5_0/VirtualFileBasedSourceElement.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_5_0/typeUtils.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_6_0/IrBuiltIns.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_2_0_0-RC1/JavaBinarySourceElement.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_2_0_0-RC1/VirtualFileBasedSourceElement.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_2_1_20-Beta1/VirtualFileBasedSourceElement.kt
java/kotlin-extractor/src/main/kotlin/utils/versions/v_2_1_20-Beta1/typeUtils.kt
java/kotlin-extractor/versions.bzl
java/ql/integration-tests/kotlin/all-platforms/diagnostics/kotlin-version-too-new/diagnostics.expected

I had to make the `org.jetbrains.kotlin.ir.types.*` imports more explicit to avoid importing deprecated methods that clashed with their replacements.

Kotlin: Add support for 2.1.20-Beta1

---

python/ql/lib/change-notes/2025-01-15-builtin-model.md
python/ql/lib/semmle/python/frameworks/Stdlib.qll
python/ql/test/library-tests/dataflow/coverage/test_builtins.py
python/ql/test/library-tests/dataflow/variable-capture/test_library_calls.py

These builtins were missing models; this PR adds support for them.

Python: Add models for builtins `map`, `filter`, `zip`, and `enumerate`.

---

java/ql/lib/config/semmlecode.dbscheme.stats

https://github.com/github/codeql/pull/18529 passed all its CI checks, but caused an internal stats-checking unit test to fail. This should fix it.

Java: fix stats for databaseMetadata relation

---

java/ql/lib/change-notes/2025-01-07-jax-rs-annotation-inheritance.md
java/ql/lib/semmle/code/java/frameworks/JaxWS.qll
java/ql/test/library-tests/frameworks/JaxWs/JakartaRs1.java
java/ql/test/library-tests/frameworks/JaxWs/JakartaRs3.java
java/ql/test/library-tests/frameworks/JaxWs/JakartaRs4.java
java/ql/test/library-tests/frameworks/JaxWs/JakartaRsInterface.java
java/ql/test/library-tests/frameworks/JaxWs/JaxRs1.java
java/ql/test/library-tests/frameworks/JaxWs/JaxRs3.java
java/ql/test/library-tests/frameworks/JaxWs/JaxRs4.java
java/ql/test/library-tests/frameworks/JaxWs/JaxRsInterface.java

Currrently, our JAX-RS models correctly follow the spec, which says that annotations on classes and interfaces aren't inherited. However, some implementations (like Apache CXF), do allow inheritance of annotations on classes and interfaces. This PR updates our modeling to allow inheritance of those annotations (but only when the class does not have any JAX-RS annotations). 
This PR also adds lots of tests.

Java: Update JAX-RS annotation inheritance

---

docs/codeql/reusables/supported-versions-compilers.rst

https://github.com/github/codeql/pull/17953 should have included this, but we forgot it.

JS: update missing TS support doc

---

javascript/extractor/src/com/semmle/js/extractor/Main.java
javascript/ql/src/change-notes/2025-01-21-vue-ts-notsconfig.md
javascript/ql/test/library-tests/TypeScript/RegressionTests/EmbeddedTypeScriptNoTSConfig/DB-CHECK.expected
javascript/ql/test/library-tests/TypeScript/RegressionTests/EmbeddedTypeScriptNoTSConfig/embedded-typescript.vue
javascript/ql/test/library-tests/TypeScript/RegressionTests/EmbeddedTypeScriptNoTSConfig/test.expected
javascript/ql/test/library-tests/TypeScript/RegressionTests/EmbeddedTypeScriptNoTSConfig/test.js
javascript/ql/test/library-tests/TypeScript/RegressionTests/EmbeddedTypeScriptNoTSConfig/test.ql

When TypeScript code is embedded in a HTML-like file such as a Vue file, we write the embedded code to a separate `.ts` file, to be extracted later by the TypeScript extractor. (To avoid starting up the TypeScript extractor in a multi-threaded context). These generated files are called "snippets". The mapping between such snippet files and their original source location is stored in `ExtractorState#getSnippets()`.
We have two different code paths for scheduling TypeScript files for extraction: one for files that are part of a tsconfig file, and one for "loose" files that aren't associated with any tsconfig. The second code path however was missing a case for extracting snippets. This led to unextracted code and DB consistency errors. This PR adds the missing snippet-extracting code.

JS: Avoid inconsistent DB when embedded TS has no associated tsconfig.json

---

cpp/ql/lib/semmle/code/cpp/headers/PreprocBlock.qll
cpp/ql/test/library-tests/headers/preprocBlock/preprocblock.expected
cpp/ql/test/library-tests/headers/preprocBlock/preprocblock23.cpp
cpp/ql/test/library-tests/headers/preprocBlock/preprocinclude.expected

C++: Update `PreprocBlock.qll` QLDoc and add C++23 test

---

java/ql/lib/semmle/code/java/frameworks/JaxWS.qll
java/ql/lib/semmle/code/java/frameworks/spring/SpringHttp.qll
java/ql/lib/semmle/code/java/security/XSS.qll

@jbj highlighted a case where the regex matching in `isXssVulnerableContentType` was a noticeable bottleneck - it's slow and it's evaluated multiple times.
Timing it locally, I measured one of the cases to 2.5s.
Merging the 4 regexes to 1 brought that down to about 670ms.
And testing the resulting regex on a single-column projection brought that further down to about 90ms.
This makes sense, since checking a single regex is much faster than checking 4. And projecting `CompileTimeConstantExpr.getStringValue()` to the string column easily reduces the number of regex operations by an order of magnitude when many string literals have the same value.

Java: Improve performance of XSS regex.

---

actions/extractor/tools/autobuild-impl.ps1
actions/extractor/tools/autobuild.sh

This PR changes the includes paths to only look at `.github/workflows/*.yml` and `.github/workflows/*.yaml` because workflows cannot be nested under subdirectories in `.github/workflows`.
After further discussion, we've decided to add
```
include:.github/reusable_workflows/**/*.yml
include:.github/reusable_workflows/**/*.yaml
```
to support reusable workflows.

Change includes paths in autobuild.sh

---

javascript/ql/src/Security/CWE-020/IncorrectSuffixCheck.ql
javascript/ql/src/change-notes/2025-01-22-indexof-suffix-check.md
javascript/ql/test/query-tests/Security/CWE-020/IncorrectSuffixCheck/IncorrectSuffixCheck.expected
javascript/ql/test/query-tests/Security/CWE-020/IncorrectSuffixCheck/tst.js

Fixes internal issue (see backref).   
Evaluations were uneventful. I did a rerun of the `nightly-old` due to the first one hinting slightly towards a performance regression, but that disappeared on a rerun.

JS: Fix FPs with js/incorrect-suffix-check

---

cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll

Before on `silentearth/curl2`:
```
Evaluated recursive predicate IRGuards::Cached::unary_compares_eq/5#7aa979d8@e3b01fca in 26109ms on iteration 2 (delta size: 4020).
Evaluated relational algebra for predicate IRGuards::Cached::unary_compares_eq/5#7aa979d8@e3b01fca on iteration 2 running pipeline standard with tuple counts:
0   ~0%    {5} r1 = JOIN `IRGuards::Cached::unary_compares_eq/5#7aa979d8#prev_delta` WITH `IRGuards::Cached::BuiltinExpectCallValueNumber.getCondition/0#dispred#9b2b5da2_10#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.3, Lhs.4
1835651   ~2%    {5} r2 = SCAN `IRGuards::Cached::unary_compares_eq/5#7aa979d8#prev_delta` OUTPUT In.4, In.0, In.1, In.2, In.3
1832833   ~0%    {5}    | JOIN WITH `IRGuards::AbstractValue.getDualValue/0#dispred#bfb2631d` ON FIRST 1 OUTPUT …
```

C++: Fix join-order problem found on `IncorrectCheckScanf.ql`

---

rust/ql/lib/utils/test/TranslateModels.qll
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/local/DataFlowStep.ql
rust/ql/test/library-tests/dataflow/taint/TaintFlowStep.expected
rust/ql/test/library-tests/dataflow/taint/TaintFlowStep.ql
shared/dataflow/codeql/dataflow/test/ProvenancePathGraph.qll

I also updated `rust/ql/test/library-tests/dataflow/local/DataFlowStep.ql` to test the local flow step relation used by global data flow instead of the exposed local step relation.

Rust: Translate more MaD IDs in tests

---

cpp/ql/lib/semmle/code/cpp/models/implementations/Pure.qll
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/test_mad-signatures.expected

This PR cleans up the taint-flow model for the `PureStrFunction` class. Previously, this was conflating pointers and their indirections which caused false flow in some cases. See the first commit for an example of this.
Additionally, I added a _dataflow_ model for the cases where the pointer is actually preserved.
DCA shows 3 lost results, and they appear to be FPs that are now correctly removed.

C++: Remove pointer/pointee conflation from models of "pure" functions

---

cpp/ql/src/Security/CWE/CWE-190/TaintedAllocationSize.ql

Alternative to https://github.com/github/codeql/pull/18564. Hopefully this should be a much better join-order: This reorders the two `readsVariable` conjuncts pushing one into the offending predicate and pulling the other out. The result is `variableEqualityCheckedInBlock(Variable checkedVar, IRBlock bb)` which appears to have a good column correlation (i.e. small size), and it's simple enough to handle the inlined `ensuresEq`. This makes sense since its semantic interpretation also seems like a reasonable thing to materialise. The subsequent join is fast when it happens on both columns, which we ensure by adding the basic block as an additional column to `readsVariable` (it's functional so should be a safe addition).

C++: Fix join order problem in TaintedAllocationSize.

---

ruby/ql/lib/codeql/ruby/security/ConditionalBypassQuery.qll
ruby/ql/lib/codeql/ruby/security/InsecureDownloadQuery.qll
ruby/ql/lib/codeql/ruby/security/UnsafeCodeConstructionQuery.qll
ruby/ql/lib/codeql/ruby/security/UnsafeHtmlConstructionQuery.qll
ruby/ql/lib/codeql/ruby/security/UnsafeShellCommandConstructionQuery.qll
ruby/ql/lib/codeql/ruby/security/WeakSensitiveDataHashingQuery.qll
ruby/ql/lib/codeql/ruby/security/regexp/MissingFullAnchorQuery.qll
ruby/ql/lib/codeql/ruby/security/regexp/PolynomialReDoSQuery.qll
ruby/ql/src/experimental/decompression-api/DecompressionApi.ql
ruby/ql/src/queries/security/cwe-732/WeakFilePermissions.ql

There was a bug in the patch query which meant some queries were inadvertently marked as "obviously" safe for diff-informed queries, even though they select a related location.
This PR starts by re-running the new fixed version of the patch query, which also does a better job of mentioning which related location is selected.
The inserted TODOs are then resolved using the new `getASelectedSinkLocation` API.

Ruby: fix and improve diff-informed queries

---

rust/ql/test/library-tests/controlflow/BasicBlocks.expected
rust/ql/test/library-tests/controlflow/Cfg.expected
rust/ql/test/library-tests/controlflow/test.rs

Just two additional control flow tests for two patterns that weren't covered before.

Rust: Add two additional control flow tests

---

csharp/autobuilder/Semmle.Autobuild.CSharp/DotNetRule.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs
csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs
csharp/extractor/Semmle.Extraction.Tests/DotNet.cs
csharp/ql/integration-tests/linux/standalone_dotnet3/Files.expected
csharp/ql/integration-tests/linux/standalone_dotnet3/Files.ql
csharp/ql/integration-tests/linux/standalone_dotnet3/Program.cs
csharp/ql/integration-tests/linux/standalone_dotnet3/global.json
csharp/ql/integration-tests/linux/standalone_dotnet3/standalone_dotnet3.csproj
csharp/ql/integration-tests/linux/standalone_dotnet3/test.py

When downloading (older) versions of the .NET CLI, we can sometimes run into issues where the downloaded files are not executable. For example, attempting to run .NET 3 on Ubuntu 24.04 results in this error
```
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
```
The fix suggested by this PR is to extend downloading to also include a verification step, where we check that running `dotnet --info` exits cleanly.

C#: Verify that downloaded .NET CLIs are executable

---

go/extractor/extractor.go

This is a small part of https://github.com/github/codeql/pull/18306 that can be merged in advance and means that the extractor won't fail on code using type paramters on type aliases, which is a new language feature in go 1.24. It is not tested in this PR as that would involve the test using 1.24, but it is tested in the original PR.

Go: 1.24 support - Tolerate type parameters on alias types

---

javascript/ql/src/Security/CWE-312/examples/CleartextLogging.js
javascript/ql/src/Security/CWE-312/examples/CleartextLoggingGood.js
javascript/ql/test/query-tests/Security/CWE-312/CleartextLogging.expected
javascript/ql/test/query-tests/Security/CWE-312/passwords.js

```Bash
> console.info(`[INFO] Environment: ${process.env}`);
[INFO] Environment: [object Object]
```

JS: fix example in clear-text-logging qhelp to actually be bad

---

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected
ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
ruby/ql/test/library-tests/dataflow/global/Flow.expected
ruby/ql/test/library-tests/dataflow/global/TypeTrackingInlineTest.expected
ruby/ql/test/library-tests/dataflow/global/callbacks.rb

Now that we [track types in data flow](https://github.com/github/codeql/pull/18315), implementing `localMustFlowStep` means that we will also get type-based call-target pruning, as implemented in the [shared library](https://github.com/github/codeql/blob/204afab42729d6c09b38b4b08518823c33b5ca38/shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll#L1916).

Ruby: Implement `localMustFlowStep `

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll

In https://github.com/github/codeql/pull/18592 (after lots of back-and-forth) we identified a problem in the C++ MaD setup where we were conflating the summarized callables and the source callable whenever a summarized callable existed in the database.
Initially, I thought that the fix required us to remove parameter nodes for MaD summarized functions (something I now know we shouldn't do!), and thus I did ad80b36074bb41ece2b7fba1435449fc7ed97c41. However, in a later commit we re-introduced the parameter nodes. However, I forgot to revert ad80b36074bb41ece2b7fba1435449fc7ed97c41. So this PR reverts that commit.

C++: #18592 follow-up

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll

This gives us the missing result that we lost after the all the bugfixes in https://github.com/github/codeql/pull/18592
The alert changes are completely identical to the original PR. All these results are _good changes_. I'll paste that description here for reference:
We gain 1 new result on `cpp/path-injection`. I've confirmed that this is because we now stay below the default field flow branch limit (i.e., `2`) for flow out of [this call to push_back](https://github.com/openjdk/jdk/blob/8dc43aa0fe8cdba2a2953258de02c6afa072987a/src/jdk.jpackage/share/native/applauncher/AppLauncher.h#L49). Before, we had out flow from both the MaD summary and the source code which resulted in going over the limit. But now we only have the MaD summary-proided out flow which keeps us below the threshold. …

C++: Don't infer lambda calls when there is a static dispatch

---

go/ql/lib/semmle/go/frameworks/GinCors.qll
go/ql/lib/semmle/go/frameworks/RsCors.qll
go/ql/test/experimental/CWE-942/CorsGin.go
go/ql/test/experimental/CWE-942/CorsMisconfiguration.expected
go/ql/test/experimental/CWE-942/CorsMisconfiguration.go
go/ql/test/experimental/CWE-942/CorsMisconfiguration.qlref
go/ql/test/experimental/CWE-942/RsCors.go

Follow up to https://github.com/github/codeql/pull/14873 with a few trivial improvements.

Go: miscellaneous improvements rs cors models

---

go/ql/lib/change-notes/2025-01-22-fix-parameter-in-models.md
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/completetest.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/sinks.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/srcs.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/srcs.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalTaintFlow/test.go
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/completetest.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/sinks.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/srcs.expected
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/srcs.ext.yml
go/ql/test/library-tests/semmle/go/dataflow/ExternalValueFlow/test.go

It was silently failing because `InterpretNode.asCallable()` was only working correctly for summarized callables. This is fine for other input and output kinds, but "Parameter" is used for parameters of functions with bodies.

Go: Fix "Parameter" in models-as-data

---

docs/codeql/ql-language-reference/expressions.rst
docs/codeql/ql-language-reference/name-resolution.rst
docs/codeql/ql-language-reference/ql-language-specification.rst

It turns out the previous BigInt-related updates to the QL language reference were not complete. This time I searched for `float` in the language reference and considered whether each occurrence should be generalised to cover `BigInt`.
Two open questions are left for possible future work:
1. The `avg` aggregate may have no good implementation for `BigInt`. If we remove support for it, we'll have to update the language reference.
2. The word "integer" is used all over the language reference to mean `int` or its subtypes. I'll argue that `BigInt` is also a kind of integer, but I don't feel strongly enough about it to comb through all occurrences myself and update them. Maybe ideally the word "integer" should be dropped and replaced with either `int` or "integral type".

QL reference: more BigInt updates

---

shared/util/codeql/util/AlertFiltering.qll
shared/util/ext/default-alert-filter.yml

This commit introduces a new extensible predicate `restrictAlertsToExactLocation`, which is similar to the existing `restrictAlertsTo` predicate but matches alert locations exactly.
`restrictAlertsToExactLocation` is intended for situations such as testing, where we know the exact alert location and want to distinguish between alert locations that are potentially on the same line.

AlertFiltering: add restrictAlertsToExactLocation

---

javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/PreCallGraphStep.qll
javascript/ql/lib/semmle/javascript/frameworks/Nest.qll
javascript/ql/src/change-notes/2025-01-30-nest-di.md
javascript/ql/test/library-tests/frameworks/Nest/global/app.module.ts
javascript/ql/test/library-tests/frameworks/Nest/global/foo.impl.ts
javascript/ql/test/library-tests/frameworks/Nest/global/foo.interface.ts
javascript/ql/test/library-tests/frameworks/Nest/global/validation.ts
javascript/ql/test/library-tests/frameworks/Nest/test.expected
javascript/ql/test/library-tests/frameworks/Nest/test.ql

Adds support for dependency injection in NestJS.
There are other dependency injection libraries out there and we'll likely want to factor out some of this to a general DI support library. But for now just focusing on NestJS support.

JS: Add support for dependency injection in Nest

---

javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java
javascript/extractor/src/com/semmle/js/extractor/Main.java
javascript/ql/src/change-notes/2025-01-30-typescript-tsconfig-names.md
javascript/ql/test/library-tests/TypeScript/TSConfigReferences/src/main.ts
javascript/ql/test/library-tests/TypeScript/TSConfigReferences/test.expected
javascript/ql/test/library-tests/TypeScript/TSConfigReferences/test.ql
javascript/ql/test/library-tests/TypeScript/TSConfigReferences/tsconfig.foo.json
javascript/ql/test/library-tests/TypeScript/TSConfigReferences/tsconfig.json

Improves our handling of the situation where the `tsconfig.json` file includes nothing, but references another file that does, but is not called `tsconfig.json`.
We could do this by following `"references"` and `"extends"` and extract more files based on that, but for now I've done the simple thing by just treating more files as tsconfig-like files.

JS: Treat more file patterns as tsconfig-like files

---

.bazelrc

This should speed up the Rust extractor by quite a lot.

Rust: build optimized code

---

java/ql/lib/semmle/code/java/security/CommandLineQuery.qll
java/ql/lib/semmle/code/java/security/WebviewDebuggingEnabledQuery.qll

Similar to the reasoning behind https://github.com/github/codeql/pull/17648, diff-informed queries have to be exact. Over-approximations may cause alert wobble over the lifetime of a PR.

Java: make diff-informed queries exact

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/FlowSummaryImpl.qll

This PR updates our data flow library to use the [newly introduced](https://github.com/github/codeql/pull/18579) `PathResolution` library for identifying record and variant constructions. We still need a workaround for built-in types like `Option`, until we extract the relevant source code.

Rust: Use `PathResolution` module in data flow

---

javascript/ql/test/query-tests/Security/CWE-611/libxml.noent.js
rust/ql/test/query-tests/security/CWE-312/test_logging.rs
shared/util/codeql/util/test/InlineExpectationsTest.qll

This changes the test post-processing query so that an explicit `Source` tag should be omitted for alerts where the source and alert location are on the same line.
Previously, the `Source` tag should be omitted when the locations were exactly the same; now they only have to be on the same line.
Currently both start and end lines have to match in order to be considered on the same line.
For context, I am trying to port the JS tests to post-processed inline expectations, and I'm seeing a lot of `$ Alert Source` expectations that seem unnecessary.

Test: Don't expect 'Source' tag when source and alert are on the same same

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/FlowSummaryImpl.qll
rust/ql/src/utils/modelgenerator/internal/CaptureModels.qll
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/models/main.rs
rust/ql/test/library-tests/dataflow/models/models.expected
rust/ql/test/library-tests/dataflow/models/models.ext.yml
rust/ql/test/utils-tests/modelgenerator/summaries.rs

Implementation is similar to the one in C#. This is primarily 1/ adding and using two new content types and 2/ properly implementing more of the model generation signature.

Rust: Higher order function model generation

---

csharp/ql/test/library-tests/dataflow/delegates/DelegateFlow.ql
csharp/ql/test/library-tests/dataflow/functionpointers/FunctionPointerFlow.ql
shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
shared/dataflow/codeql/dataflow/internal/DataFlowImplCommon.qll
shared/dataflow/codeql/dataflow/internal/DataFlowImplStage1.qll

Adds the following internal aliases in the data flow library to make the code less verbose
```ql
class Call = DataFlowCall;
class Callable = DataFlowCallable;
class Type = DataFlowType;
class Expr = DataFlowExpr;
```

Data flow: Add aliases for removing `DataFlow` prefixes

---

swift/extractor/translators/ExprTranslator.cpp

Closes https://github.com/github/codeql/issues/18678
Unfortunately, I wasn't really able to reproduce the issue in my code, but in any case that roundabout way of getting the type for the root type repr of a key path expression was done in the past only because `getRootType` was not present in the Swift compiler API at the time.

Swift: fix `KeyPathExpr` assertion

---

python/extractor/semmle/python/parser/tsg_parser.py

This makes it _much_ easier to find the offending bit of syntax.

Python: Print file path when logging context errors

---

python/extractor/semmle/python/passes/flow.py
python/ql/lib/change-notes/2025-02-06-robustly-handle-loop-constructs.md
python/ql/test/extractor-tests/syntax_error/without_loop.py

Observed on some test files in Nuitka/Nuitka, having `break` and `continue` outside of loops in Python is (to Python) a syntax error, but our parser happily accepted this broken syntax.
This then caused issues further downstream in the control-flow construction, as it broke some invariants.
To fix this we now skip the code that would previously fail when the invariants are broken.

Python: Handle loop constructs outside of loops

---

rust/ql/lib/codeql/rust/Frameworks.qll
rust/ql/lib/codeql/rust/frameworks/stdlib/Clone.qll
rust/ql/test/library-tests/dataflow/modeled/inline-flow.expected
rust/ql/test/library-tests/dataflow/modeled/inline-flow.ql
rust/ql/test/library-tests/dataflow/modeled/main.rs

The `clone` method is very common in Rust and implementations should always make an exact clone of the input. So allowing value flow through any `clone` method seems useful.
I wasn't sure how to implement this. In C/C++ I think we have a way of adding flow that is based on data flow nodes, but here I extended `SummarizedCallable::Range` which is based on strings and thus feels a bit odd. Maybe we will want another way to add additional flow steps later, but for now this seems to work just fine.

Rust: Model `clone`

---

rust/ql/lib/codeql/rust/controlflow/CfgNodes.qll
rust/ql/lib/codeql/rust/elements/internal/PathImpl.qll
rust/ql/lib/codeql/rust/elements/internal/RecordExprFieldImpl.qll
rust/ql/lib/codeql/rust/elements/internal/RecordExprImpl.qll
rust/ql/lib/codeql/rust/elements/internal/RecordPatFieldImpl.qll
rust/ql/lib/codeql/rust/elements/internal/VariableImpl.qll
rust/ql/test/extractor-tests/generated/RecordPatField/RecordPatField.expected
rust/ql/test/extractor-tests/generated/RecordPatField/RecordPatField_getNameRef.expected
rust/ql/test/extractor-tests/generated/RecordPatField/RecordPatField_getPat.expected
rust/ql/test/library-tests/dataflow/local/CONSISTENCY/DataFlowConsistency.expected
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/dataflow/local/main.rs

Like https://github.com/github/codeql/pull/18656, but for constructions instead of destructions.

Rust: Shorthand record construction in data flow

---

rust/ql/test/library-tests/dataflow/modeled/inline-flow.expected
rust/ql/test/utils-tests/modelgenerator/option.rs

This PR just adds some additional tests for the model generation based on the `Option` implementation in the Rust core library. Given that we'll eventually want to run the model generation and just trust its output I think it's worthwhile to have a decent amount of test coverage. This `Option` implementation contains some realistic Rust code while still being reasonably simple.

Rust: Add additional tests for model generation

---

csharp/ql/src/Telemetry/DatabaseQuality.qll
java/ql/src/Telemetry/DatabaseQuality.qll
rust/ql/src/queries/telemetry/DatabaseQuality.qll
rust/ql/src/queries/telemetry/DatabaseQualityDiagnostics.ql
rust/ql/src/queries/telemetry/ExtractorInformation.ql
shared/util/codeql/util/ReportStats.qll

For now, this will yield DCA numbers on missing call targets, but should also eventually yield telemetry data.

Rust: Implement database quality telemetry query

---

rust/ql/lib/codeql/rust/Concepts.qll
rust/ql/lib/codeql/rust/frameworks/tokio-postgres.model.yml
rust/ql/test/library-tests/frameworks/postgres/Postgres.ql
rust/ql/test/library-tests/frameworks/postgres/main.rs

Two changes in this PR:
- Added a new Concept for Database reads
- Added `tokio-postgres` support
- Added database-read sources and SQL Injection sinks

Rust: Add Database Sources + tokio-postgres support

---

rust/ql/lib/codeql/rust/AstConsistency.qll
rust/ql/lib/codeql/rust/elements/internal/PathResolution.qll
rust/ql/test/library-tests/path-resolution/CONSISTENCY/AstConsistency.expected
rust/ql/test/library-tests/path-resolution/main.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected

This PR models [namespaces](https://doc.rust-lang.org/reference/names/namespaces.html) when resolving paths. Values and types live in different namespaces, so their names are allowed to overlap without shadowing. The context in which a path occurs uniquely determines which namespace to lookup into, except for uses like `use foo::bar` where `bar` may refer to either a value or a type (or both).

Rust: Model namespaces in path resolution

---

shared/tree-sitter-extractor/src/extractor/mod.rs

Printing a line for every extracted file is too verbose and for large projects makes it impossible to view the log in the Actions UI.

TreeSitter extractors: log fewer lines

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/FlowSummaryImpl.qll
rust/ql/test/library-tests/dataflow/models/main.rs
rust/ql/test/library-tests/dataflow/models/models.expected
rust/ql/test/library-tests/dataflow/models/models.ext.yml
rust/ql/test/library-tests/dataflow/models/options.yml

This PR takes a small step towards handling async Rust:
* Adds a content type for things stored in the `Future` trait.
* `.await` reads from the future content.
Notably this doesn't handle non-modeled calls to `async` functions.

Rust: Basic support for future content and `.await`

---

java/ql/lib/semmle/code/java/security/NumericCastTaintedQuery.qll

It was discovered by the upcoming support for exact locations matching in diff-informed testing that this data-flow configuration did not correspond exactly to the query.

Java: precise diff-informed NumericCastTainted

---

python/ql/test/library-tests/dataflow/coverage/functional.py
python/ql/test/library-tests/dataflow/validTest.py

This can also serve for a place to add tests for
constructs like threading.Thread, mulitprocess.Process, concurrent.futures.ThreadPoolExecutor, and concurrent.futures.ProcessPoolExecutor.

Python: Add tests for functional-like programming

---

rust/ql/lib/codeql/rust/elements/internal/IdentPatImpl.qll
rust/ql/test/extractor-tests/generated/IdentPat/IdentPat.expected
rust/ql/test/extractor-tests/generated/IdentPat/IdentPat_getName.expected
rust/ql/test/extractor-tests/generated/IdentPat/IdentPat_getPat.expected
rust/ql/test/library-tests/controlflow/BasicBlocks.expected
rust/ql/test/library-tests/controlflow/Cfg.expected
rust/ql/test/library-tests/controlflow/test.rs
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/variables/Cfg.expected
rust/ql/test/library-tests/variables/Ssa.expected
rust/ql/test/query-tests/unusedentities/UnusedValue.expected

In particular, this makes it possible to distinguish an identity pattern from the name inside it in the string representation.

Rust: Tweak `toString` on identity pattern

---

javascript/ql/test/query-tests/AngularJS/DuplicateDependency/DuplicateDependency.expected
javascript/ql/test/query-tests/AngularJS/DuplicateDependency/DuplicateDependency.qlref
javascript/ql/test/query-tests/AngularJS/DuplicateDependency/duplicates.js
shared/util/codeql/util/test/InlineExpectationsTest.qll

Makes the inline test post-processor support queries that select a location that does not correspond to an instance of `Location`. This can happen when it selects an entity that uses `hasLocationInfo` to craft a custom location range.
To ensure the behavior is exercised, this PR also ports one of the JS queries for which this was blocking migration to post-processed inline expectations.

Test: Support arbitrary locations in inline test post-processor

---

rust/extractor/src/translate/base.rs

We found out we can stumble upon a `line_index.line_col` panic, specifically when reporting a macro parse error.
This replaces `line_col` with safer `try_line_col`, and deals more gracefully with the error.

Rust: avoid panic from `line_index` crate

---

shared/tree-sitter-extractor/src/file_paths.rs

On https://github.com/github/codeql/pull/18767 I learned that root paths on Windows, like `c:\`, are currently normalized to `C:`, while the shared YAML extractor normalizes it as `C:/`. This PR aligns the behavior of the Rust-based extractors with the YAML extractor.

Rust extractors: Normalize drive letter paths with a trailing `/`

---

go/Makefile

This helped me debug when some dbscheme upgrade scripts weren't working.

Go: Print diff when dbscheme upgrade fails

---

go/documentation/library-coverage/frameworks.csv

Updating docs, adding `weak` to the standard library row and adding new rows for various newly-modeled libraries which were in the "Others" row. A bot should post a comment here showing what they will look like when compiled. After this is merged, a bot will make a PR updating the docs using this info.

Go: Add more modeled frameworks to docs

---

javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll
javascript/ql/lib/semmle/javascript/internal/flow_summaries/AllFlowSummaries.qll
javascript/ql/lib/semmle/javascript/internal/flow_summaries/UrlSearchParams.qll
javascript/ql/src/change-notes/2025-02-13-url-search-params.md
javascript/ql/test/library-tests/TripleDot/urlsearchparams.js
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected

Fixes https://github.com/github/codeql/issues/18757.
With the data flow migration, the old model of `URLSearchParams` stopped working because its pseudo-properties were not included in `PropertyName`.
I've confirmed that simply including them in `PropertyName` would fix the observed issue, but I went ahead and ported the model to flow summaries. I decided to model the object as a `Map` since it shares most of the same interface and the addition of `getAll` is unlikely to cause problems for regular `Map` objects.

JS: Migrate model of URLSearchParams

---

javascript/ql/lib/semmle/javascript/security/regexp/PolynomialReDoSQuery.qll
javascript/ql/src/experimental/Security/CWE-918/SSRF.qll

Removes some superfluous related locations to more accurately restrict the queries to the diff range.
Note that this only fixes the test failures that are fixable without refactoring the query or using `AlertFiltering` directly

JS: Provide more precise related locations

---

javascript/extractor/src/com/semmle/jcorn/Parser.java
javascript/extractor/src/com/semmle/js/extractor/ExtractorConfig.java
javascript/ql/lib/change-notes/2025-02-16-v-flag.md
javascript/ql/lib/semmle/javascript/Expr.qll
javascript/ql/lib/semmle/javascript/Regexp.qll
javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialBackTracking.expected
javascript/ql/test/query-tests/Security/CWE-400/ReDoS/ReDoS.expected
javascript/ql/test/query-tests/Security/CWE-400/ReDoS/tst.js

The first commits are picked from this WIP PR: https://github.com/github/codeql/pull/18055 
This is an alternative to: https://github.com/github/codeql/pull/18727

JS: Add support for the regex V flag

---

misc/scripts/models-as-data/generate_flow_model.py

When generating MaD for Rust filenames end up containing `/`s and `:`s that are problematic (or impossible) to include in paths.
With this PR the names of the created files are sanitized. For instance `foo://bar/baz` gets turned into `foo-bar-baz`.
Also makes some tiny tweaks to the documentation.

Sanitize path when generating MaD files

---

java/ql/lib/change-notes/2025-01-16-file-constructor-sanitizer.md
java/ql/lib/ext/java.io.model.yml
java/ql/lib/semmle/code/java/dataflow/FlowSteps.qll
java/ql/lib/semmle/code/java/security/PathSanitizer.qll
java/ql/test/experimental/query-tests/security/CWE-200/InsecureWebResourceResponse.expected
java/ql/test/library-tests/frameworks/jdk/java.io/test.expected
java/ql/test/library-tests/paths/test.expected
java/ql/test/library-tests/pathsanitizer/Test.java
java/ql/test/query-tests/security/CWE-022/semmle/tests/ZipSlip.expected

Adds a path injection sanitizer for the `child` argument of a `java.io.File` constructor when that argument is normalized or  checked for the absence of "..".
Note that sanitizing the second argument of the `File` constructor also sanitizes other uses of that variable after the constructor call (see the `MISSING` cases in the tests). Let me know if there is some way to adjust the QL to avoid also sanitizing these other uses. I can sanitize the `File` constructor call instead of the second argument, but then the first argument needs to be checked for taint.

Java: `File` constructor path sanitizer

---

javascript/ql/lib/change-notes/2025-02-12-express-download.md
javascript/ql/lib/semmle/javascript/frameworks/Express.qll
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/tainted-sendFile.js

Add result.download to Express as Path Traversal Sink

JS: Add result.download to Express as Path Traversal Sink

---

javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowPrivate.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/TaintTrackingPrivate.qll
javascript/ql/lib/semmle/javascript/frameworks/LodashUnderscore.qll
javascript/ql/lib/semmle/javascript/internal/flow_summaries/AmbiguousCoreMethods.qll
javascript/ql/src/change-notes/2025-02-18-no-implicit-array-taint.md
javascript/ql/test/library-tests/FlowSummary/DataFlowConsistency.expected
javascript/ql/test/library-tests/TripleDot/arrays.js
javascript/ql/test/library-tests/TripleDot/buffer.js
javascript/ql/test/query-tests/Security/CWE-078/IndirectCommandInjection/IndirectCommandInjection.expected
javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction/UnsafeShellCommandConstruction.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.expected
javascript/ql/test/query-tests/Security/CWE-079/StoredXss/StoredXss.expected
javascript/ql/test/query-tests/Security/CWE-089/untyped/SqlInjection.expected
javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/ImproperCodeSanitization.expected
javascript/ql/test/query-tests/Security/CWE-730/RegExpInjection.expected

When a flow summary uses `ArrayElement` in its output column, we'd previously generate a taint step in addition to a store step into the array. This PR removes that rule, so that _reading_ from `ArrayElement` generates a taint step, but storing into `ArrayElement` does not.
The rule was there in order to be consistent with how things worked with the old data flow library, where arrays were generally considered tainted if they contained a tainted element, but we don't really do that anymore. This PR makes a couple of semi-related changes in order to recover from observed FPs/FNs resulting from the first commit.
The DCA run looks good:
- 4 fixed FPs
- 1 lost result from `ExceptionXss` which is due to that query having an AP limit of 1, which is no longer enough to find the flow. The result …

JS: Do not taint whole array when storing into ArrayElement

---

javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java

Fixes https://github.com/github/codeql/issues/18801
This fixes the bug that was supposed to be fixed in https://github.com/github/codeql/pull/18550, but that PR only fixed it in the legacy entry-point used by qltest. Meaning it worked in tests but not in production 🤦. This PR uses the same fix in AutoBuild entry point. We should unify the two entry points ASAP but for now this PR just fixes the bug.

JS: Extract TS snippets with no tsconfig.json file

---

java/ql/src/Security/CWE/CWE-352/SpringCSRFProtection.qhelp

Updates the overview section of the `java/spring-disabled-csrf-protection` QHelp to align with other CSRF queries. Context:  https://github.com/github/codeql/pull/18288#issuecomment-2634786516
Also updates the name of the OWASP website. Context: https://github.com/github/codeql/pull/18288#discussion_r1943166158
**Autofix validation:** I quickly checked the effect on autofix for a couple alerts. Autofix still successfully removes the `.disable()` call, but it now also discusses handling CSRF tokens in the fix descriptions and includes code related to CSRF tokens in one of the fix suggestions. Let me know if this sounds like a reason to avoid this wording update? 
(Note that I purposefully did not include any explicit mention of tokens in this update, but the related …

Java: update `java/spring-disabled-csrf-protection` QHelp

---

rust/ql/lib/codeql/rust/elements/internal/PathResolution.qll
rust/ql/test/library-tests/dataflow/global/inline-flow.expected
rust/ql/test/library-tests/dataflow/global/main.rs
rust/ql/test/library-tests/path-resolution/main.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected

Functions inherited through trait bounds or `impl` blocks are now modeled in the path resolution logic.

Rust: Path resolution for inherited associated items

---

javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowPrivate.qll
javascript/ql/src/change-notes/2025-02-17-downward-calls.md
javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/Test.expected
javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/Test.ql
javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/accessors.js
javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/subclasses.js
javascript/ql/test/library-tests/CallGraphs/FullTest/tests.expected
javascript/ql/test/library-tests/TripleDot/subclass.js

Resolves calls targeting `this` downwards in the class hierarchy, for example:
```js
class Base {
foo() {
this.bar(); // calls Sub.bar
}
}
class Sub extends Base {
bar() { ... }
}
```
We already resolve calls upwards in the class hierarchy. One of the risks from resolving both upwards and downwards is that flow can start in one subclass, go upwards to a base class, and then move into a different subclass. This PR mitigates using some features of the shared data flow library involving `DataFlowType` and `viableImplInCallContext`.
Both DCA and QA run were very quiet (see backlinks). The DCA run showed 531 new call edges across 95 projects, resulting in 6 new sinks and 694 nodes now being tainted.

JS: Resolve calls downward in class hierarchy

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/src/utils/modelgenerator/internal/CaptureModels.qll
rust/ql/test/utils-tests/modelgenerator/CaptureSinkModels.expected
rust/ql/test/utils-tests/modelgenerator/CaptureSinkModels.ext.yml
rust/ql/test/utils-tests/modelgenerator/CaptureSinkModels.ql
rust/ql/test/utils-tests/modelgenerator/CaptureSourceModels.expected
rust/ql/test/utils-tests/modelgenerator/CaptureSourceModels.ext.yml
rust/ql/test/utils-tests/modelgenerator/CaptureSourceModels.ql
rust/ql/test/utils-tests/modelgenerator/sinks.rs
rust/ql/test/utils-tests/modelgenerator/sources.rs

With this we should be able to generate sources and sinks from already modeled sources and sinks.

Rust: Generate sources and sinks

---

actions/extractor/BUILD.bazel
javascript/extractor/README.md
javascript/resources/BUILD.bazel
python/BUILD.bazel
ruby/BUILD.bazel
swift/BUILD.bazel

Previously some extractors did and some didn't provide an explicit license alongside the codeql-extractor.yml, though those that did all used the MIT license.

Regularise extractor pack licenses to all cite the MIT license that covers the whole CodeQL repository

---

docs/codeql/reusables/supported-frameworks.rst

The alignment of the tables in the "[Supported languages and frameworks](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/)" article (except the first table) has recently changed to the center which doesn't look right. This most likely happened due to a change in the Sphinx version used to generate the site. 
I've used the `align` property to make sure the tables align to the left. That seems to be the most straightforward way but let me know if there are any problems with that. 
Note: There is also a weird thing going on with the footnotes being indented...not sure how to fix that

Fix table alignment in supported languages article

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/SsaImpl.qll
java/ql/test/library-tests/dataflow/ssa/A.java
java/ql/test/library-tests/dataflow/ssa/test.ql
java/ql/test/library-tests/pattern-switch/dfg/GuardTest.java
ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
ruby/ql/test/library-tests/variables/ssa.expected
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
shared/ssa/codeql/ssa/Ssa.qll

I want to reinterpret phi-reads as reads rather than definitions and hide them from the exposed interface of the SSA library. For normal SSA usage they should be irrelevant: they're only useful for getting an optimised use-use step relation, in particular for use in data-flow.
This PR leaves most of the existing implementation intact, but adds alternative predicates and switches the internal implementation of several others in preparation for this change.
The PR is structured as a long sequence of individually simple commits, so commit-by-commit review is very much encouraged.
There's more work to come, but each of the commits should make sense on their own, and I'd gathered so many that I wanted to merge them to main before adding too many more.

Ssa: Refactor shared SSA in preparation for eliminating phi-read definitions 

---

go/ql/lib/semmle/go/StringOps.qll

Old join order (on `uber/aresdb`):
```
[2025-02-20 12:19:36] Evaluated non-recursive predicate StringOps::StringOps::HasPrefix::comparesFirstCharacter/3#24aa5857@5bcd38hd in 3ms (size: 1).
Evaluated relational algebra for predicate StringOps::StringOps::HasPrefix::comparesFirstCharacter/3#24aa5857@5bcd38hd with tuple counts:
6528  ~0%    {3} r1 = JOIN project#DataFlowUtil::EqualityTestNode#9fb3a74a#2 WITH `DataFlowUtil::BinaryOperationNode.hasOperands/2#dispred#c32311b8` ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Rhs.2
6562  ~4%    {3}    | JOIN WITH `GlobalValueNumbering::globalValueNumber/1#39395ec1` ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2
1766593  ~1%    {3}    | JOIN WITH `GlobalValueNumbering::globalValueNumber/1#39395ec1_10#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2
89  ~0%    {5}    | JOIN …
```

Go: Fix bad join order in `comparesFirstCharacter`

---

cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql
cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected
cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/test.cpp

Expand qldoc and tests for the `cpp/command-line-injection` (`ExecTainted.ql`) query.  I was hoping to fix a performance issue as well (rarely occurring, since https://github.com/github/codeql/pull/18633/) - I didn't manage to figure it out, but the extra doc comments I wrote along the way are worth keeping.

C++: Expand qldoc and tests for cpp/command-line-injection

---

rust/ast-generator/BUILD.bazel
rust/lint.py

* `bazel run //rust/ast-generator:inject-sources` could fail on macOS if a non-coreutils `cp` was used
* that is now also run by `lint.py` to ensure the sources cargo needs are present

Rust: strengthen linting script

---

cpp/ql/lib/semmle/code/cpp/dataflow/ExternalFlow.qll

It is impossible to avoid a CP in this predicate on it's own.
Picking `getClassAndName` first is always a CP as it doesn't use `nameWithoutArgs`. This disjunct cannot be picked as `not method instanceof ConversionOperator` requires `method` to be bound first. 
In practice the argument `result` also happens to be bound at the call site, so `getClassAndName` is not a CP at the call site. However the call site has no idea that we need `method` to be bound and we join order assuming that it isn't so it. We also assume it isn't bound internally. This means that the join order is quite sensitive.
An alternative would be to add `result` to the binding set to get a similar effect to what we do now (I wasn't sure whether to make this do what seems to be intended or whether to preserve the existing …

CPP: Prevent forced bad join order which is saved by context.

---

go/ql/lib/semmle/go/dataflow/internal/DataFlowUtil.qll

Old code:
```ql
guardingFunction(g, f, inp, outp, p) and
c = f.getACall() and
nd = inp.getNode(c) and
localFlow(pragma[only_bind_out](outp.getNode(c)), resNode)
```
Old join order (note that `FunctionOutput.getExitNode` comes from ``outp.getNode`, which is just a wrapper for it):
```
Pipeline standard for DataFlowUtil::BarrierGuard<WrappedErrorAlwaysNil::nilTestGuard>::guardingCall/8#aa0defc4#fffffffb@dfedaw8n was evaluated in 2 iterations totaling 7ms (delta sizes total: 4).
6   ~0%    {5} r1 = SCAN `DataFlowUtil::BarrierGuard<WrappedErrorAlwaysNil::nilTestGuard>::guardingFunction/5#1f27d9d8#fffbf#prev_delta` OUTPUT In.3, In.0, In.1, In.2, In.4
722106   ~6%    {7}    | JOIN WITH `FunctionInputsAndOutputs::FunctionOutput.getExitNode/1#dispred#4c5ce77c` ON FIRST 1 OUTPUT Lhs.2, Rhs.1, …
```

Go: Improve bad join order in guardingCall

---

java/ql/lib/semmle/code/java/frameworks/Servlets.qll
java/ql/lib/semmle/code/java/security/XSS.qll
java/ql/src/change-notes/2025-01-28-fix-xss-content-type-safe.md
java/ql/test/query-tests/security/CWE-079/semmle/tests/JaxXSS.java
java/ql/test/query-tests/security/CWE-079/semmle/tests/JsfXSS.java
java/ql/test/query-tests/security/CWE-079/semmle/tests/SetJavascriptEnabled.java
java/ql/test/query-tests/security/CWE-079/semmle/tests/SpringXSS.java
java/ql/test/query-tests/security/CWE-079/semmle/tests/XSS.java

This already existed for Jax and Spring, but not the standard library.
- ~All new queries have appropriate `.qhelp`. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-help-style-guide.md) in this repository.~
- ~New and changed queries have correct query metadata. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md) in this repository.~
- ~Adding a new query? Consider also [adding the query to autofix](https://github.com/github/codeml-autofix/blob/main/docs/updating-query-support.md#adding-a-new-query-to-the-query-suite).~

Java: Add XSS Sanitizer for `HttpServletResponse.setContentType` with safe values

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/test/library-tests/dataflow/local/DataFlowStep.expected
csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowNodes.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowNode.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowPrivate.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/TaintTrackingPrivate.qll
javascript/ql/test/library-tests/TripleDot/useuse.js
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll
ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.expected
ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.ql
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
shared/ssa/codeql/ssa/Ssa.qll

Commit-by-commit review encouraged. I've attempted to make every commit self-contained.
This PR includes a sequence of small changes, including:
* A bugfix for guards for SSA input nodes. The version on main accidentally had a cast from DefinitionExt to Definition that ruled out some guarded nodes.
* Replacement of the use-use calculation to use the revised implementation.
* Switch the JavaScript ad-hoc barrier-guard for falsy checks to use the out-of-the-box implementation. (This adds a few additional guarded nodes in the case I tested - no tuples were lost).
* Deprecate the public SsaDefinitionExtNode and SsaInputNode and replace them with a more general notion of synthesized reads.

Ssa: Refactor the data flow integration module

---

cpp/ql/lib/semmle/code/cpp/Location.qll

Reported here: https://github.com/github/codeql/issues/17743. Note that we do not use the modified `isBefore` predicate anywhere in our own code.
Without this change on the query provided by the user:
```
[2025-02-25 12:42:01] Evaluated non-recursive predicate quickquery::UnrealFunctionAnnotation.annotates/1#dispred#9cd6c269@c668c8tv in 23846ms (size: 20381473).
Evaluated relational algebra for predicate quickquery::UnrealFunctionAnnotation.annotates/1#dispred#9cd6c269@c668c8tv with tuple counts:
1   ~0%    {0} r1 = CONSTANT()[]
27323   ~0%    {2}    | JOIN WITH `Location::Location.getEndLine/0#dispred#83af84ae#bf` CARTESIAN PRODUCT OUTPUT Rhs.0, Rhs.1
6162566035   ~0%    {4}    | JOIN WITH `Location::Location.getStartLine/0#d54f9e6c` CARTESIAN PRODUCT OUTPUT Lhs.0, Lhs.1, Rhs.0, Rhs.1 …
```

C++: Fix join-order problem with `isBefore`

---

csharp/ql/test/utils/inline-tests/InlineTests.cs
csharp/ql/test/utils/inline-tests/PathProblemQuery.expected
csharp/ql/test/utils/inline-tests/PathProblemQueryRelatedLocs.expected
csharp/ql/test/utils/inline-tests/PathProblemQueryRelatedLocs.qlref
csharp/ql/test/utils/inline-tests/ProblemQuery.expected
csharp/ql/test/utils/inline-tests/ProblemQueryRelatedLocs.expected
csharp/ql/test/utils/inline-tests/ProblemQueryRelatedLocs.qlref
csharp/ql/test/utils/inline-tests/queries/PathProblemQueryRelatedLocs.expected
csharp/ql/test/utils/inline-tests/queries/PathProblemQueryRelatedLocs.ql
csharp/ql/test/utils/inline-tests/queries/ProblemQueryRelatedLocs.ql
csharp/ql/test/utils/inline-tests/queries/ProblemQueryWithRelatedLocs.ql
javascript/ql/test/query-tests/Security/CWE-352/MissingCsrfMiddleware.qlref
javascript/ql/test/query-tests/Security/CWE-352/MissingCsrfMiddlewareBad.js
javascript/ql/test/query-tests/Security/CWE-352/csurf_api_example.js
javascript/ql/test/query-tests/Security/CWE-352/csurf_example.js
javascript/ql/test/query-tests/Security/CWE-352/fastify.js
javascript/ql/test/query-tests/Security/CWE-352/fastify2.js
javascript/ql/test/query-tests/Security/CWE-352/lusca_example.js
javascript/ql/test/query-tests/Security/CWE-352/tst.js
javascript/ql/test/query-tests/Security/CWE-352/unused_cookies.js
rust/ql/test/query-tests/security/CWE-328/test.rs
shared/util/codeql/util/test/InlineExpectationsTest.qll

This adds support for marking related locations with `// $ RelatedLocation` inline comments. They are only expected if at least one such comment exists in the test; and if so then all related locations must be annotated.
Some queries use a primary alert location such that a large number of alerts get consolidated into a single alert. For such queries simply putting `$ Alert` on the consolidated alert line isn't a good choice. For path problems this is rarely a problem as we have `Source` and `Sink` tags, but for non-path problems it can be an issue.
This PR migrates the JS `MissingCsrfMiddleware` test to inline expectations so the behaviour is exercised. This query flags the cookie-parsing middleware function, as opposed to the vulnerable route handler function, because there can be a …

Test: Add support for RelatedLocation tag and use in a JS query

---

docs/codeql/reusables/supported-versions-compilers.rst

I assume that docs which use this fragment will be regenerated without me having to do anything.

Go: Document support for Go 1.24

---

actions/ql/extensions/immutable-actions-list/ext/immutable_actions.yml
actions/ql/extensions/immutable-actions-list/qlpack.yml
actions/ql/lib/ext/config/immutable_actions.yml
actions/ql/lib/ext/config/trusted_actions_owner.yml
actions/ql/src/change-notes/2025-02-27-immutable-actions-list.md
actions/ql/test/qlpack.yml
codeql-workspace.yml

This PR removes the current list of immutable actions from the standard library pack, and moves it into a new model pack, `github/immutable-actions-list`.
We have an existing Actions query, `actions/unversioned-immutable-action`, which alerts about references to an action without a semantic version if there's an immutable version of that action available. However, since the immutable actions feature isn't available to customers yet, we're currently reporting alerts that our customers have no way of fixing. We don't want to remove the query from the default suite, though, because then we couldn't run it internally on repos that use Default Setup, which is nearly all of them.
Instead, I've created a new model pack containing the list. We'll deploy this model pack internally for now. Once …

Move list of immutable actions into internal model pack for now.

---

actions/extractor/BUILD.bazel

The Bash script in the `actions` extractor has its executable bit set in the repo, but was losing that bit somewhere along the way from the repo checkout to the CLI zip file. The fix is to specify the scripts in the `exes` parameter of `codeql_pkg_files` rather than in the `srcs` parameter.
We didn't notice this because everywhere we test the Actions extractor, it's being picked up from the repo, not the CLI distribution. It also didn't affect anyone using the CodeQL Action, because the Action had an embedded copy of the `actions` extractor, and that copy _does_ have the executable bit set correctly 🤦‍♂️.

Set the executable bit on the scripts in the Actions extractor

---

csharp/ql/src/Bad Practices/PathCombine.qhelp
csharp/ql/src/Bad Practices/PathCombine.ql
csharp/ql/src/change-notes/2025-02-26-path-combine.md
csharp/ql/test/query-tests/Bad Practices/Path Combine/PathCombine.cs
csharp/ql/test/query-tests/Bad Practices/Path Combine/PathCombine.expected
csharp/ql/test/query-tests/Bad Practices/Path Combine/PathCombine.qlref
csharp/ql/test/query-tests/Bad Practices/Path Combine/options

The docs for [Path.Combine](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=net-9.0) warns:
> [!IMPORTANT]  
> This method assumes that the first argument is an absolute path and that the following argument or arguments are relative paths. If this is not the case, and particularly if any subsequent arguments are strings input by the user, call the [Join](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.join?view=net-9.0) or [TryJoin](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.tryjoin?view=net-9.0) method instead.
This commit adds a corresponding CodeQL query to recommend against Path.Combine.

Add CodeQL recommendation against Path.Combine

---

java/ql/src/Likely Bugs/Concurrency/UnreleasedLock.ql
java/ql/src/change-notes/2025-03-02-unreleased-lock-fp.md
java/ql/test/query-tests/UnreleasedLock/UnreleasedLock.expected
java/ql/test/query-tests/UnreleasedLock/UnreleasedLock.java

This PR adjusts the `java/unreleased-lock` query so that it no longer reports alerts in cases where a boolean variable is used to track lock state.

Java: handle lock state check stored in variable for `java/unreleased-lock`

---

cpp/ql/src/Metrics/Internal/IncludeResolutionStatus.ql

This PR adds a query to get metrics to evaluate the include resolution status in C++ BMN.
It will be added to DCA as an uninterpreted query.

C++ query to extract the number of errors due to include file resolution failure

---

rust/ql/src/utils/modelgenerator/internal/CaptureModels.qll

Currently the model generator create wonky `.model.yml` files with models containing no canonical names.
This PR restricts the generator to only consider library functions that has canonical paths.

Rust: Exclude functions without canonical path from model generation

---

cpp/ql/test/library-tests/templates/nontype_instantiations/general/test.expected
cpp/ql/test/library-tests/templates/nontype_instantiations/general/test.ql

These values are currently the same as the result that `getTemplateArgument` yields. However, this will change with the upcoming frontend update.

C++: Update template test to also output the value of template arguments

---

csharp/ql/consistency-queries/SsaConsistency.ql
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
csharp/ql/test/library-tests/dataflow/ssa/SSAPhiRead.expected
csharp/ql/test/library-tests/dataflow/ssa/SSAPhiRead.ql
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowNodes.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowUtil.qll
java/ql/lib/semmle/code/java/dataflow/internal/SsaImpl.qll
ruby/ql/consistency-queries/SsaConsistency.ql
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
ruby/ql/test/library-tests/variables/ssa.expected
ruby/ql/test/library-tests/variables/ssa.ql
rust/ql/consistency-queries/SsaConsistency.ql
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
rust/ql/test/library-tests/variables/Ssa.expected
rust/ql/test/library-tests/variables/Ssa.ql
shared/ssa/codeql/ssa/Ssa.qll

More SSA refactoring commits. This is mostly about adjusting qltests to avoid DefinitionExt references, and fixing up the consistency queries.

Ssa: Update qltests including consistency checks

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll

This changes one ad-hoc fieldFlowBranchLimit tweak to another. I tried to do some comparisons on the computed counts, and there are plenty of discrepancies, but that's possibly completely fine - let's see what dca says.
The primary motivation for this change is to get rid of the dependence on SSA Phi Read nodes, which I plan to hide within the SSA library.

C++: Change countNumberOfBranchesUsingParameter to match qldoc closer.

---

python/ql/src/codeql-suites/python-ccr.qls

Adds `py/not-named-self` and `py/not-named-cls` to the CCR suite.

Python: Include `py/not-named-self` and `py/not-named-cls` in the CCR suite

---

csharp/ql/src/Useless code/FutileConditional.ql
csharp/ql/src/change-notes/2025-03-05-useless-if-statement.md
csharp/ql/test/query-tests/Useless Code/FutileConditional/FutileConditional.cs
csharp/ql/test/query-tests/Useless Code/FutileConditional/FutileConditional.expected
csharp/ql/test/query-tests/Useless Code/FutileConditional/FutileConditional.qlref
csharp/ql/test/query-tests/Useless Code/FutileConditional/options

It is not an un-common pattern to write something like
```csharp
if (b) {
// Insert some relevant debugging statements here
// My commented out code.
}
```
Due to the above our query might seem a bit to noisy. In this PR we remove the alerts, if the empty if-block contains a comment.
We still catch the following examples (where the first one is the most important as it is most likely unintentional).
```csharp
if (b);
if (b)
{
}
```

C#: Fewer alerts in `cs/useless-if-statement`.

---

rust/ql/lib/codeql/rust/elements/internal/FormatTemplateVariableAccessConstructor.qll

```
Evaluated relational algebra for predicate _Synth::Synth::TFormatArgument#5cbf2ffd_63#join_rhs__Format::Format.getArgumentRef/0#dispred#38d664c__#antijoin_rhs@889ee4br with tuple counts:
11356  ~0%    {5} r1 = JOIN `_Format::Format.getArgumentRef/0#dispred#38d664cb_Format::Format.getParent/0#dispred#f6ec3e8b_10#joi__#shared` WITH Synth::Synth::TFormatArgument#5cbf2ffd_63#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.3, Lhs.0
19631351  ~0%    {6}    | JOIN WITH name_texts_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.0
45933  ~0%    {6}    | JOIN WITH format_args_arg_names_10#join_rhs ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5
747  ~0%    {5}    | JOIN WITH format_args_expr_args_02#join_rhs ON FIRST 2 OUTPUT Lhs.0, Lhs.2, Lhs.3, Lhs.4, Lhs.5 …
```

Rust: Fix bad joins

---

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.19.4.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.20.4.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.20.5.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.20.6.rst
docs/codeql/codeql-overview/codeql-changelog/index.rst

merging in the changedocs for 2.20.6

Changedocs for 2.20.6

---

.vscode/tasks.json
misc/scripts/create-change-note.py

Changes the script for creating change notes to read the EDITOR environment variable, and use the editor specified therein. This makes the script more convenient when used from a terminal.
The VSCode task is updated to the set EDITOR to `code -r` which preserves the current behavior.

Change note creation script uses EDITOR environment variable

---

java/ql/consistency-queries/SsaConsistency.ql
java/ql/lib/semmle/code/java/dataflow/internal/BaseSSA.qll
java/ql/lib/semmle/code/java/dataflow/internal/SsaImpl.qll
ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.expected
rust/ql/test/query-tests/security/CWE-089/CONSISTENCY/SsaConsistency.expected
shared/ssa/codeql/ssa/Ssa.qll

This extends the SSA consistency checks with a number of new checks and enables them for Java. The additional consistency checks reveal that we're constructing too many phi read nodes, so the superfluous nodes are removed.

Ssa: Extend consistency checks and reduce phi read nodes

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/localFlow-ir.expected

Intuitively, C++ has (at least) the following dataflow nodes:
- A dataflow node for each instruction
- A dataflow node for each operand
- A dataflow node for each possible indirection of an instruction
- A dataflow node for each possible indirection of an operand
Because many of these nodes semantically represent the same concept we merge some of these into a single dataflow node tuple. This has two benefits:
- We allocate less dataflow nodes which saves on memory, and
- It's easier to pick the right dataflow node for sources, sinks, and (especially) barriers.
For example, for IR such as:
```cpp
r1(glval<int>) = VariableAddress[a]     : 
r2(int)        = Load[a]                : &:r1, m1
```
there will be a single dataflow node representing both the _instruction_ `r1` and the _operand_ …

C++: Share indirect dataflow nodes across `CopyValue` instructions

---

docs/codeql/reusables/supported-versions-compilers.rst
javascript/extractor/lib/typescript/package-lock.json
javascript/extractor/lib/typescript/package.json
javascript/ql/lib/change-notes/2025-02-17-typescript-5-8.md

All the changes are additional type-checking, or optional features that are only relevant under specific flags.  
No new syntax or other changes that seem to be relevant for our work.  
See the announcement blogpost: https://devblogs.microsoft.com/typescript/announcing-typescript-5-8/
I'm running some DCA evaluations to confirm that everything is fine.

JS: upgrade TypeScript to 5.8

---

javascript/ql/lib/semmle/javascript/MembershipCandidates.qll
javascript/ql/src/change-notes/2025-02-28-membership-regexp-test.md
javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected
javascript/ql/test/library-tests/TaintTracking/DataFlowTracking.expected
javascript/ql/test/library-tests/TaintTracking/regexp-sanitiser.js

The class `EnumerationRegExp` is intended to capture the idea of a regexp that acts as a hardcoded list of values to check, e.g. `/^(foo|bar|baz)$/` but with some leeway for choice, like `/^(found/recogni[sz]ed)$/`.
However, the implementation used an `exists` that was probably meant to be `forall` or `forex`, which means it was way too loose in what it accepted. This gave rise to some invalid barrier guards, which is not caught by any existing test nor by DCA, but I have a simple tests now. This PR makes it more restrictive.
Regexp-based barrier guards are primarily the responsibility of `SanitizerRegExpTest`, but `EnumerationRegExp` gives rise to `MembershipCandidate` which gives rise to barrier guards, so we have two ways for regexp checks to become barrier guards. The ones from …

JS: Sharpen up EnumerationRegExp

---

rust/tools/qltest.cmd
rust/tools/qltest.sh

* verbosity is raised to DEBUG to have more information in the logs
* color codes are now skipped in the `qltest.log` file
* they are still printed out on the console when running with `--show-extractor-output`.

Rust: tweak qltest logs

---

javascript/ql/src/meta/alerts/TaintedNodes.ql

This explodes on some databases due to not restricting the set of sinks.

JS: Remove TaintedNodes.ql from default meta query suite

---

javascript/ql/lib/semmle/javascript/Routing.qll

DCA and CI look fine, so I think this is fine.  
It fixes a catastrophic performance issue (see backref).  
`getPathFromFork` had a lot of results, which caused a blowup in `isGuardedByNodeInternal`.

JS: ensure the result from getPathFromFork is unique (to avoid a blowup)

---

javascript/ql/lib/semmle/javascript/TypeScript.qll
javascript/ql/test/library-tests/frameworks/HTTP/RemoteRequestInput.expected
javascript/ql/test/library-tests/frameworks/HTTP/express-typed.ts

Something changed in the TypeScript compiler at some point which means we handle code like this differently:
```ts
import { Request } from "express";
type Alias = Request & { foo: string };
```
Previously the type `Alias` would be extracted as its own type, and we could recognise that it contained `Request` as an "underlying type", so things like `hasUnderlyingType("express", "Request")` would hold for things annotated with `Alias`.
Unfortunately the type `Alias` is now extracted as `any`. Note that `Request` is an unresolved type because no `.d.ts` file is found for `express` as we don't install dependencies. My theory is that the change comes down to how the compiler handles unresolved types internally.
The good thing is that we're expecting to move away from type extraction anyway, and …

JS: Unfold local type aliases in getAnUnderlyingType

---

javascript/ql/lib/change-notes/2025-03-10-js-refactor-markdown-table.md
javascript/ql/lib/ext/markdown-table.model.yml
javascript/ql/lib/semmle/javascript/frameworks/Markdown.qll
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.expected
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.js
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXssWithCustomSanitizer.expected

Ported the `markdown-table` model to a flow summary to ensure `ArrayElement` is unfolded correctly.

JS: Refactor `markdown-table` library modeling

---

go/ql/src/InconsistentCode/UnhandledCloseWritableHandle.ql
go/ql/test/query-tests/InconsistentCode/UnhandledCloseWritableHandle/UnhandledCloseWritableHandle.expected
go/ql/test/query-tests/InconsistentCode/UnhandledCloseWritableHandle/UnhandledCloseWritableHandle.qlref
go/ql/test/query-tests/InconsistentCode/UnhandledCloseWritableHandle/tests.go

Converts the tests to use be inline expectation tests and adds a test (marked `SPURIOUS`) for an FP when there is a deferred call to `os.File.Close` and then later a call to `os.File.Sync`.
What we should probably do in this case is to make sure that every control flow path from the deferred call to `os.File.Close` to the end of the function either includes a call to `os.File.Sync` or involves returning a non-nil error. (I thought about how to do this and I think you would define some predicates like this:
```
private BasicBlock allowedSuccessor(BasicBlock b) {
result = b.getASuccessor()
// and result doesn't contain a handled sync call
// and result doesn't end by returning an non-nil error
}
private BasicBlock maximalAllowedSuccessor(BasicBlock b) {
result = …
```

Go: Add test for FP in `go/unhandled-writable-file-close`

---

actions/ql/src/qlpack.yml

The query pack has suites that rely on the `codeql/suite-helpers` pack, but doesn't include it as a dependency. This will cause error when resolving suites referring the Actions query pack.

Add missing dependency

---

javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowPrivate.qll
javascript/ql/src/change-notes/2025-03-11-vue-fix.md
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/v-html.vue

Attribute nodes were missing their enclosing callable, which means the shared data flow library was unable to track flow there. As far as I can tell this only affects Vue.
I'm honestly not sure why `DataFlow::XmlAttributeNode` exists since we don't seem to use it for anything 😕.

JS: Fix attributes nodes missing an enclosing callable

---

csharp/ql/src/Bad Practices/Control-Flow/ConstantCondition.ql
csharp/ql/src/change-notes/2025-03-11-constant-condition.md
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantCondition.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantCondition.expected
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantCondition.qlref
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantConditionBad.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantConditionalExpressionCondition.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantForCondition.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantIfCondition.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantIsNullOrEmpty.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantNullCoalescingLeftHandOperand.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantWhileCondition.cs

In this PR we start to take conditions into account for matching in switch statements and expressions. That is, we allow match all (discard) patterns, if there is a condition. Furthermore, we also apply the logic to switch/case statements.
Example
```csharp
public string M(int i)
{
return i switch
{
_ when i % 2 == 0 => "even", // We used to flag this in cs/constant-condition
_ => "odd"
};
}
```
This reduces the number of false positives.

C#: Increase precision of `cs/constant-condition`.

---

python/ql/src/Security/CWE-918/ServerSideRequestForgery-end.inc.qhelp

A PR referencing this issue: https://github.com/github/codeql/issues/18815

Python: Add more documentation in regards to SSRF

---

javascript/ql/lib/change-notes/2025-03-11-tanstack-angular.md
javascript/ql/lib/ext/tanstack.model.yml
javascript/ql/lib/semmle/javascript/frameworks/Angular2.qll
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXssWithResponseThreat/Xss.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXssWithResponseThreat/test.ts

Added library modeling for `@tanstack/angular-query-experimental.`
Updated the Angular client request to use API Graph instead of Dataflow.

JS: Update Angular Client Request's with API graph and `Tanstack` Angular modeling

---

csharp/ql/src/codeql-suites/csharp-ccr.qls

In this PR we add the `cs/constant-condition` to the CCR suite.
A couple of improvements related to the accuracy was made prior to this change
- https://github.com/github/codeql/pull/18976
- https://github.com/github/codeql/pull/18932
The available autofix triage data for C# only had 3 results where 2 were FPs (which were fixed by the above improvements) and for the last data point autofix gave an almost correct suggestion (at least a good staring point).
I have tried to run autofix locally on our query test data files, which provided pretty good fix suggestions. Most of these cases are constructed examples, where the correct suggestion is to delete the code as nothing is done (which autofix correctly detects). Furthermore, it is also able to correctly detect the logic error in the `Max` …

C#: Add cs/constant-condition to the CCR suite.

---

python/ql/lib/change-notes/2025-02-26-add-get-min-max-parameters-to-function-class.md
python/ql/lib/semmle/python/Function.qll
python/ql/lib/semmle/python/objects/ObjectAPI.qll

These seem generally useful outside of points-to, and so it might be better to add them to the `Function` class instead.
I took the liberty of renaming these to say `Arguments` rather than `Parameters`, as this is more in line with the nomenclature that we're using elsewhere. (The internal points-to methods retain the old names.)
I'm somewhat ambivalent about the behaviour of `getMaxParameters` on functions with `*varargs`. The hard-coded `INT_MAX` return value is somewhat awkward, but the alternative (to only have the predicate defined when a specific maximum exists) seems like it would potentially cause a lot of headaches.

Python: Move min/maxParameter methods to `Function` class

---

python/ql/lib/semmle/python/Exprs.qll
python/ql/src/Variables/UnusedModuleVariable.ql
python/ql/src/change-notes/2025-03-04-fix-forward-annotation-fp-in-unused-global-var-query.md
python/ql/test/query-tests/Variables/unused/UnusedModuleVariable.expected
python/ql/test/query-tests/Variables/unused/variables_test.py

Fixes the false positive reported in https://github.com/github/codeql/issues/18910
Adds a new `Annotation` class (subclass of `Expr`) which encompasses all possible kinds of annotations in Python.
Using this, we look for string literals which are part of an annotation, and which have the same content as the name of a (potentially) unused global variable, and in that case we do not produce an alert.
In future, we may want to support inspecting such string literals more deeply (e.g. to support stuff like "list[unused_var]"), but I think for now this level of support is sufficient.

Python: Add support for forward references in unused var query

---

javascript/ql/lib/change-notes/2025-03-13-unescape.md
javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected
javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tst.js

Added a taint step for `unescape`.
Closes #19003

JS: Add support for `unescape`

---

rust/tools/qltest.sh

Turns out some version of macOS do not support the way `mktemp` was being used. In any case it wasn't really necessary, see https://github.com/github/codeql/pull/18918#discussion_r1979444850 (which I forgot to follow up on at the time after approval).

Rust: fix `qltest.sh` for some versions of macOS

---

.github/codeql/codeql-config.yml

Actions language analysis is hitting some errors while analysing some JS files: https://github.com/github/codeql/actions/runs/13839086154/job/38721621923 
This PR adds those paths to the exceptions in codeql config, to avoid that

Add paths to codeql-config.yml to avoid codeql analysis errors

---

cpp/ql/src/JPL_C/LOC-3/Rule 17/BasicIntTypes.ql
cpp/ql/src/change-notes/2025-03-11-basic-int-types.md
cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 17/BasicIntTypes.expected

The purpose of this check is to ensure that all integral types used by the code point to some fixed size type (e.g. an unsigned 8-bit integer). However, the previous implementation only allowed JPL style typedefs (i.e. U8) and ignored C standard integer types (i.e. uint8_t). This causes the query to false-positive when a typedef resolves to a C standard int type instead of the JPL type even though the spirit of the check has been met.
'bool' has also be allowed as part of the exclusions list as it represents distinct values 'true' and 'false' in C++ code.
Since this significantly reduces the false-positives on my project, I've labeled it "majorAnalysis" per: https://github.com/github/codeql/blob/main/docs/change-notes.md#query-pack-change-categories

Fixing BasicIntTypes to allow C Standard Integers and 'bool'

---

csharp/ql/src/Useless code/IntGetHashCode.ql
csharp/ql/src/change-notes/2025-03-13-useless-gethashcode-call.md
csharp/ql/test/query-tests/Useless Code/IntGetHashCode/IntGetHashCode.cs
csharp/ql/test/query-tests/Useless Code/IntGetHashCode/IntGetHashCode.expected
csharp/ql/test/query-tests/Useless Code/IntGetHashCode/IntGetHashCode.qlref

As [this](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types) table indicates, only `byte`, `sbyte`, `short`, `ushort` and `int` can use the identity function for `GetHashCode` (and they indeed do so) as the return type of `GetHashCode` is `int`.
In this PR we update the `cs/useless-gethashcode-call` to exclude calls to `GetHashCode` on `uint`, `long` and `ulong` and convert the tests to inline tests.

C#: Increase precision of `cs/useless-gethashcode-call`.

---

javascript/ql/lib/semmle/javascript/Promises.qll
javascript/ql/test/ApiGraphs/async-await/VerifyAssertions.expected
javascript/ql/test/ApiGraphs/async-await/wrap-async-in-thunk.js

API graphs were missing a `getPromised()` step from the return value of an `async` function to the returned expression (i.e. from the promise object to the value it is being resolved with).
It is currently relying on `PromiseFlow::storeStep` to access promise-related steps, which means steps contributed by other means are not seen by API graphs. In general we want API graphs to use all type-tracking steps, including those induced by summaries, like in Ruby, but now I'm just fixing the bug by moving the relevant code into `PromiseFlow::storeStep`.

JS: Fix bug in API graphs getPromised() missing async function returns

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/AllocationToInvalidPointer.qll
cpp/ql/lib/semmle/code/cpp/security/InvalidPointerDereference/InvalidPointerToDereference.qll
cpp/ql/src/Likely Bugs/Memory Management/AllocaInLoop.ql
cpp/ql/src/Security/CWE/CWE-119/OverrunWriteProductFlow.ql
cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/constant-size/ConstantSizeArrayOffByOne.expected
cpp/ql/test/library-tests/dataflow/dataflow-tests/localFlow-ir.expected
cpp/ql/test/query-tests/Security/CWE/CWE-022/SAMATE/TaintedPath/TaintedPath.expected
cpp/ql/test/query-tests/Security/CWE/CWE-134/SAMATE/UncontrolledFormatString.expected
cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/consts/NonConstantFormat.expected
cpp/ql/test/query-tests/Security/CWE/CWE-193/InvalidPointerDeref.expected
cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected
shared/ssa/codeql/ssa/Ssa.qll

Commit-by-commit review encouraged.
There are a bunch of minor commits, and then there's "C++: Use SSA data flow integration module", which is the main change that switches C++ from direct phi-read references to use the data flow integration module to construct use-use flow.
I've done a lot of local black-box testing of these changes and they generally looking very reasonable. There are minor changes on the order of 0.1% of the ssa-based data flow edges, but at this point I think further evaluation is best done via dca.

C++: Refactor SSA usage in data flow.

---

actions/ql/src/Security/CWE-077/EnvPathInjectionCritical.ql
actions/ql/src/Security/CWE-077/EnvPathInjectionMedium.ql
actions/ql/src/Security/CWE-077/EnvVarInjectionCritical.ql
actions/ql/src/Security/CWE-077/EnvVarInjectionMedium.ql
actions/ql/src/change-notes/2025-03-13-environment-query-names.md

This will reflect in the UI titles of existing and new alerts once shipped but should not churn any existing alerts.

Actions: Fix typos in query names for env var injection

---

.github/codeql/codeql-config.yml

These are test cases for the GitHub Actions analysis. Exclude them when running code scanning against this repo, to avoid noisy alerts.
Test workflow files in this directory are safe from execution, because Actions only executes workflows that live directly in the `.github/workflows` top-level directory.
`action.yml` files in this directory can in theory be executed as a step in a workflow; for now exclude them.

Code scanning config: Exclude actions test directory

---

misc/suite-helpers/security-experimental-selectors.yml

Correct `model-generator` -> `modelgenerator` in the `security-experimental-selectors.yml` suite helper.
- no queries have `@tags model-generator`.
- something like 49 queries have `@tags modelgenerator`.
- all other [suite helpers](https://github.com/github/codeql/tree/main/misc/suite-helpers) use `modelgenerator`.
I'm guessing somehow `security-experimental-selectors.yml` was left out of a change at some point.

Correct modelgenerator exclusion in suite helper

---

java/ql/lib/change-notes/2025-03-10-matches-replace-path-sanitizer.md
java/ql/lib/semmle/code/java/JDK.qll
java/ql/lib/semmle/code/java/security/PathSanitizer.qll
java/ql/test/library-tests/pathsanitizer/Test.java
java/ql/test/query-tests/security/CWE-022/semmle/tests/TaintedPath.java

Adds a path injection sanitizer for calls to `replace`, `replaceAll`, and `matches` that make sure `/`, `\`, `..` are not in the path.
- This PR does not attempt to handle all possible regexes, but instead heuristically covers some common cases. Let me know if you want any adjustments to the heuristics applied.
- Note that some of the QL is structured to optimize performance, such as the use of the predicates `isReplaceTarget`, `isReplaceAllTarget`, and `isMatchesTarget`.

Java: path sanitizer for `replace`, `replaceAll`, and `matches`

---

rust/extractor/src/translate/base.rs
rust/ql/test/extractor-tests/canonical_path/canonical_paths.expected

After the rename done in https://github.com/github/codeql/pull/19059, canonical path extraction was lost on `StructExpr` and `StructPath` as the identifiers used for the type in the `emit_detached!` macro were not updated. This fixes that.

Rust: fix canonical paths broken on `StructExpr` and `StructPath`

---

javascript/extractor/src/com/semmle/js/parser/JSDocParser.java

This code was a bit of a performance cringe. It copied every character into a temporary array, copied that into a String, and slow-appended that onto another String.
Note that the call to Characters.toChars is redundant here as advance() doesn't return a code point; it returns -1 or a UTF-16 char. The -1 case is checked for before reaching the call, so we can just cast it to a char and use it directly.
We use a StringBuilder to accumulate the string. Normally it's faster to track the start/end indices and do a substring(), but that won't work in the JSDoc extractor because of the star-skipping logic in advance().

JS: Use StringBuilder when building up type name in JSDoc

---

java/ql/integration-tests/java/buildless-inherit-trust-store/server.py

This doesn't really matter since it's a dummy test server, but it's simpler to fix than to dismiss.

Avoid CodeQL alert against integration test

---

java/ql/src/Security/CWE/CWE-327/MaybeBrokenCryptoAlgorithm.ql
java/ql/test/query-tests/security/CWE-327/semmle/tests/MaybeBrokenCryptoAlgorithm.expected

From https://en.wikipedia.org/wiki/Comma_splice:
> It is usually considered an error in English writing style.

Java: fix comma splice in alert message

---

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/NugetPackageRestorer.cs
csharp/ql/src/change-notes/2025-03-21-dependency-fetching.md

When dotnet core projects are restored, the dependency manager precisely tracks the referenced package folders. The fallback restore logic ignored the precise usage list and instead considered all subfolders in the restore location to be referenced, even though not all subfolders were added to the dependency list. This meant that packages downloaded in partially successful restores were available on disk, but not added to the dependency list by the normal restore process, and skipped by the fallback restore process. This commit fixes this problem by ensuring that the fallback restore logic doesn't consider all subfolders in the restore location to be referenced, but only those that were added to the dependency list by the normal restore process.

C#: Fix buildless fallback restore logic

---

rust/ql/lib/codeql/rust/elements/internal/FieldExprImpl.qll
rust/ql/lib/codeql/rust/elements/internal/StructImpl.qll
rust/ql/lib/codeql/rust/elements/internal/VariantImpl.qll
rust/ql/lib/codeql/rust/internal/Type.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected
rust/ql/test/library-tests/type-inference/type-inference.ql
shared/typeinference/codeql/typeinference/internal/TypeInference.qll

This PR attempts to address most of @aschackmull's comments over in https://github.com/github/codeql/pull/18632, plus a few additional tweaks to the type inference implementation.

Rust: Adjustments to type inference

---

rust/ql/integration-tests/hello-workspace/exe/src/main.rs
rust/ql/integration-tests/hello-workspace/lib/src/a_module/mod.rs
rust/ql/integration-tests/hello-workspace/path-resolution.ql
rust/ql/integration-tests/hello-workspace/rust-project.json
rust/ql/integration-tests/hello-workspace/summary.cargo.expected
rust/ql/integration-tests/hello-workspace/summary.rust-project.expected
rust/ql/lib/codeql/rust/elements/internal/CrateImpl.qll
rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/lib/codeql/rust/internal/PathResolutionConsistency.qll
rust/ql/lib/utils/test/PathResolutionInlineExpectationsTest.qll
rust/ql/src/queries/telemetry/RustAnalyzerComparison.qll
rust/ql/test/extractor-tests/canonical_path/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/extractor-tests/canonical_path_disabled/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/library-tests/path-resolution/main.rs
rust/ql/test/library-tests/path-resolution/my2/mod.rs
rust/ql/test/library-tests/path-resolution/my2/my3/mod.rs
rust/ql/test/library-tests/path-resolution/my2/nested2.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected
rust/ql/test/library-tests/path-resolution/path-resolution.ql

This PR implements various improvements to our path resolution logic, most notably the ability to resolve paths across crates. Commit-by-commit review is strongly encouraged.
[DCA shows](https://github.com/github/codeql-dca-main/issues/27603) that, while we maintain performance, we gain an additional 132% true positive call edges (up 448,902 from 193,392) and an additional 94% true positive resolved paths (up 345,075 from 177,539), all numbers computed across the entire DCA suite.

Rust: Path resolution improvements

---

javascript/ql/lib/change-notes/2025-03-24-got-package.md
javascript/ql/lib/semmle/javascript/frameworks/ClientRequests.qll
javascript/ql/test/library-tests/frameworks/ClientRequests/ClientRequests.expected
javascript/ql/test/library-tests/frameworks/ClientRequests/tst.js

This PR models got's `Options` type, `paginate()`, and `extend()` functions, modeling their behavior.

JS: `got` package modeling

---

go/ql/lib/change-notes/2025-03-18-loggercall-type-format-specifier.md
go/ql/lib/semmle/go/Concepts.qll
go/ql/lib/semmle/go/security/CleartextLoggingCustomizations.qll
go/ql/lib/semmle/go/security/LogInjectionCustomizations.qll
go/ql/src/Security/CWE-352/ConstantOauth2State.ql
go/ql/src/change-notes/2025-03-20-logging-false-positive-type-format-specifier.md
go/ql/test/library-tests/semmle/go/concepts/LoggerCall/LoggerCall.ql
go/ql/test/library-tests/semmle/go/concepts/LoggerCall/glog.go
go/ql/test/library-tests/semmle/go/concepts/LoggerCall/logrus.go
go/ql/test/library-tests/semmle/go/concepts/LoggerCall/main.go
go/ql/test/library-tests/semmle/go/concepts/LoggerCall/stdlib.go
go/ql/test/query-tests/Security/CWE-117/LogInjection.go
go/ql/test/query-tests/Security/CWE-312/CleartextLogging.expected
go/ql/test/query-tests/Security/CWE-312/CleartextLogging.qlref
go/ql/test/query-tests/Security/CWE-312/klog.go
go/ql/test/query-tests/Security/CWE-312/main.go
go/ql/test/query-tests/Security/CWE-312/overrides.go
go/ql/test/query-tests/Security/CWE-312/passwords.go
go/ql/test/query-tests/Security/CWE-312/protobuf.go

`LoggerCall::getAMessageComponent` no longer returns arguments to logger calls which correspond to the verb `%T` in a format specifier. This will remove false positives in "Log entries created from user input" (`go/log-injection`) and "Clear-text logging of sensitive information" (`go/clear-text-logging`), and it may lead to more results in "Use of constant `state` value in OAuth 2.0 URL" (`go/constant-oauth2-state`).
I've made a library change note but may change it to a query change note, pending discussion with colleagues.
Prompted by https://github.com/github/codeql/issues/18926.

Go: Fix false positives when logging using `%T`

---

.github/workflows/go-tests-rtjo.yml
.github/workflows/ruby-qltest-rtjo.yml
go/Makefile
go/actions/test/action.yml

Add new QL language test CI jobs next to the existing ones in this repo, using run-time join ordering (`--dynamic-join-order-mode=all`), to be triggered by adding the "Run: RTJO Language Tests" label.

CI: Add RTJO tests for Go and Ruby

---

.github/workflows/build-ripunzip.yml

Moving the workflow to run on `ubuntu-22`, since `ubuntu-20` is going to be removed from actions-runners offering: https://github.com/actions/runner-images/issues/11101

Replace occurences of ubuntu-20 by ubuntu-22 in .github/workflows

---

javascript/ql/lib/change-notes/2025-03-26-async-fileRead.md
javascript/ql/lib/semmle/javascript/frameworks/NodeJSLib.qll
javascript/ql/test/query-tests/Security/CWE-200/FileAccessToHttp.expected
javascript/ql/test/query-tests/Security/CWE-200/FileAccessToHttp.js

This pull request aims to resolve reported issue related to `require("fs").promises.readFile()` showing no data node found.

JS: Add support for `async` `readFile`

---

javascript/ql/lib/change-notes/2025-03-26-Hapi.md
javascript/ql/lib/semmle/javascript/frameworks/Hapi.qll
javascript/ql/test/library-tests/frameworks/hapi/src/hapihapi.js
javascript/ql/test/library-tests/frameworks/hapi/tests.expected
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/hapi.js

The latest version of `Hapi` introduces a new import name, `@hapi/hapi`, and a new server function.
Without this update, `CodeQL` would miss alerts related to the TaintedPath CWE-022 when using the newer version of the `Hapi` server.

JS: Support for newer version of `Hapi` - `@hapi/hapi`

---

csharp/ql/consistency-queries/DataFlowConsistency.ql
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/test/library-tests/dataflow/global/DataFlowPath.expected
csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.expected

Same as https://github.com/github/codeql/pull/19121, but for C#. Reverts the non-uniqueness introduced in https://github.com/github/codeql/pull/10594.

C#: Make `getPreUpdateNode` Unique Again

---

rust/ql/lib/codeql/rust/frameworks/log.model.yml
rust/ql/test/query-tests/security/CWE-020/RegexInjection.expected
rust/ql/test/query-tests/security/CWE-312/CleartextLogging.expected

This pull request adds argument 1 of `log::__private_api::log` as a log injection sink.
Line 42: `debug!("message = {}", password);`
expands to:
```rust
// Recursive expansion of debug! macro
// ====================================
{
{
let lvl = (log::Level::Debug);
if lvl <= log::STATIC_MAX_LEVEL && lvl <= log::max_level() {
log::__private_api::log(
({ log::__private_api::GlobalLogger }),
log::__private_api::format_args!("message = {}", password),
lvl,
&(
(log::__private_api::module_path!()),
log::__private_api::module_path!(),
log::__private_api::loc(),
),
(),
);
}
}
}
```
Most likely this [commit](https://github.com/rust-lang/log/commit/d5061b629afecc32724060a874990b8d33408c30) is responsible for the sudden test failure. That commit is part of the [log …

Rust: fix CleartextLogging query

---

docs/codeql/codeql-language-guides/customizing-library-models-for-javascript.rst
javascript/ql/lib/ext/guarded-route-handler-stress-test.model.yml
javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll
javascript/ql/test/library-tests/frameworks/data/guardedRouteHandler.js
javascript/ql/test/library-tests/frameworks/data/test.expected
javascript/ql/test/library-tests/frameworks/data/test.ext.yml

Adds a new MaD token called `GuardedRouteHandler` which goes from a middleware function installed in an HTTP router framework to all route handlers guarded by it.
For example
```js
const express = require('express')
const app = express()
app.use(require('@example/middleware').injectData())
app.get('/foo', (req, res) => {
req.data; // found by '@example/middleware'; Member[injectData].ReturnValue.GuardedRouteHandler.Parameter[0].Member[data]
});
```
The immediate motivation for this is to support [this use-case](https://github.com/github/codeql/pull/19118/files/7cc0634f573ed4015a1a9ae194283694babd341b..4cdc40d1150912deea084ee9124662bd1e913c7e#r2016496174)
For testing purposes, I temporarily included [this test commit](https://github.com/github/codeql/pull/19132/commits/2460874f4702e86fff1a5 …

JS: Add GuardedRouteHandler access path component

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll

Previously, we didn't extract `crate::...` paths for non-source code, but starting with https://github.com/github/codeql/pull/19113 we do.

Rust: Also resolve `crate` paths in non-source files

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/test/library-tests/dataflow/dataflow-tests/localFlow-ir.expected
csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
csharp/ql/test/library-tests/csharp7/LocalTaintFlow.expected
csharp/ql/test/library-tests/dataflow/local/DataFlowStep.expected
csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected
java/ql/lib/semmle/code/java/dataflow/internal/SsaImpl.qll
java/ql/test/library-tests/dataflow/capture/test.expected
java/ql/test/library-tests/dataflow/null/testnullflow.expected
java/ql/test/library-tests/dataflow/partial/test.expected
java/ql/test/library-tests/dataflow/partial/testRev.expected
java/ql/test/library-tests/dataflow/switchexpr/switchexprflow.expected
java/ql/test/library-tests/dataflow/taint-ioutils/dataFlow.expected
java/ql/test/library-tests/dataflow/this-flow/this-flow.expected
javascript/ql/lib/semmle/javascript/dataflow/internal/sharedlib/Ssa.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.expected
ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected
ruby/ql/test/library-tests/dataflow/local/TaintStep.expected
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
shared/ssa/codeql/ssa/Ssa.qll

This PR contains 3 tweaks to the shared SSA use-use step relation in the data flow integration module. Each of them trims the step relation in order to generate fewer nodes and fewer edges.
* `WriteDefinition`s are skipped for Java. There should be no need to include an extra node in the step from the RHS of an assignment to the first use of the variable, but some languages may depend on the flow out of definitions for now, so so far this is opt-in only.
* Synthetic reads on the input edges to phi nodes are necessary for proper BarrierGuards. But it's only a fraction of them that are actually potentially needed by any guard, so we can restrict their creation quite a bit. Furthermore, I've added a hook to allow certain SSA usages to skip these nodes entirely if BarrierGuards are not going …

Ssa: Trim the use-use relation to skip irrelevant nodes

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowNodes.qll
java/ql/lib/semmle/code/java/dataflow/internal/SsaImpl.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/sharedlib/Ssa.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
shared/ssa/codeql/ssa/Ssa.qll

This replaces the two predicates, `ssaDefAssigns` and `ssaDefInitializesParam`, with a per-default synthesized input-value node that can then be mapped to the RHS of an assignment or the parameter as appropriate.
The changes are split into individual commits that can be reviewed one-by-one, but the combined changes are simple enough that it's possibly just as easy to just look at all the changes together.

Ssa: Refactor data flow integration to make the input signature simpler

---

java/ql/lib/semmle/code/java/Expr.qll
java/ql/lib/semmle/code/java/controlflow/BasicBlocks.qll
java/ql/lib/semmle/code/java/dataflow/internal/BaseSSA.qll
java/ql/lib/semmle/code/java/environment/SystemProperty.qll

This PR makes 3 changes to caching in the Java QL libs (separated cleanly in individual commits):
* Merge the cached stages related to BasicBlocks, and cache the char-pred.
* Merge the cached stages related to BaseSSA, and cache the SourceVariable newtype.
* Values of CompileTimeConstants of type int, bool, and string involve mutually recursive calculation. The int values were cached but the other two weren't, so I fixed that. Since they're mutually recursive they all end up in the same stage.
All 3 of these changes were motivated by statically inspecting DIL overlap between stages. These cases stood out as potentially being able to cause recomputation.
The changes caused a bit of performance fallout, which was fixed in an additional commit.

Java: Adjust caching of BasicBlocks, BaseSSA, and CompileTimeConstants

---

misc/scripts/accept-expected-changes-from-ci.py

Apparently this is necessary for Swift.

Misc: Add another path prefix to accept-expected-changes-from-ci.py

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll

Commit-by-commit review encouraged as I was able to make a few initial simplifications that should make the actual switch simpler to review.

C++: Refactor Iterator SSA flow to use the data flow integration module.

---

cpp/ql/lib/change-notes/2025-03-31-calling-convention.md
cpp/ql/lib/semmle/code/cpp/Specifier.qll
cpp/ql/test/library-tests/calling-convention/calling-convention.expected
cpp/ql/test/library-tests/calling-convention/calling-convention.ql
cpp/ql/test/library-tests/calling-convention/test.cpp

- Introduced the class `CallingConventionSpecifier` to represent calling conventions in C++ functions.
- Added tests for calling conventions in C++ functions.
- Added a change note for calling convention support.

C++: Add class representing calling conventions

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/test/library-tests/path-resolution/main.rs
rust/ql/test/library-tests/path-resolution/my.rs
rust/ql/test/library-tests/path-resolution/my/my4/my5/mod.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected

Implements a couple of improvements to path resolution:
- Correct handling of `mod foo;` imports inside nested modules.
- Restrict sibling `mod foo;` imports to crate entry files and `mod.rs` files.

Rust: More path resolution improvements

---

python/ql/src/Functions/ReturnConsistentTupleSizes.ql
python/ql/src/change-notes/2025-03-27-modernize-mixed-tuple-returns-query.md
python/ql/test/query-tests/Functions/return_values/ReturnConsistentTupleSizes.expected
python/ql/test/query-tests/Functions/return_values/functions_test.py

Removes the dependence on points-to in favour of an approach based on (local) data-flow.
I first tried a version that used type tracking, as this more accurately mimics the behaviour of the old query. However, I soon discovered that there were _many_ false positives in this setup. The main bad pattern I saw was a helper function somewhere deep inside the code that both receives and returns an argument that can be tuples with different sizes and origins. In this case, global flow produces something akin to a cartesian product of "n-tuples that flow into the function" and "m-tuples that flow into the function" where m < n.
To combat this, I decided to instead focus on only flow _within_ a given function (and so local data-flow was sufficient).
Additionally, another class of false positives …

Python: Modernize `py/mixed-tuple-returns`

---

javascript/ql/lib/semmle/javascript/ApiGraphs.qll
javascript/ql/lib/semmle/javascript/dataflow/Sources.qll
javascript/ql/test/ApiGraphs/spread/VerifyAssertions.expected
javascript/ql/test/ApiGraphs/spread/tst.js
javascript/ql/test/query-tests/Security/CWE-918/RequestForgery.expected
javascript/ql/test/query-tests/Security/CWE-918/apollo.serverSide.ts

Makes sure API graphs can look through spread/rest parameters. An important situation where this occurs is in default constructors, where spread/rest are inserted automatically.
For example, the class below
```js
import { ApolloServer } from "@apollo/server"
class CustomApollo extends ApolloServer {}
```
is desugared into this:
```js
class CustomApollo extends ApolloServer {
constructor(...args) { super(...args) }
}
```
We have a model that looks for arguments passed to the `ApolloServer` constructor,
```yml
["@apollo/server", "Member[ApolloServer,ApolloServerBase].Argument[0].AnyMember.AnyMember.AnyMember.Parameter[1]", "remote"]
```
This ought to pick up on calls to `new CustomApollo` because the arguments are forwarded to `ApolloServer`:
```js
new CustomApollo({ ... })
```
But …

JS: Handle spread/rest in API graphs

---

java/ql/test/library-tests/dataflow/capture/test.expected
rust/ql/test/library-tests/dataflow/local/CONSISTENCY/DataFlowConsistency.expected
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
shared/dataflow/codeql/dataflow/VariableCapture.qll
shared/ssa/codeql/ssa/Ssa.qll
swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected

The first commit contains the primary change: The VariableCapture library is updated to use the DataFlowIntegration module instead of direct references to phi-read nodes. The nested SSA instantiation causes a little bit of caching, so I make sure to collapse those stages with parts of VariableCapture that would otherwise be duplicated across several stages. This ensures that we maintain the same number of cached stages (as the nested SSA already introduces a stage), and I think it also ought to be a mostly strict reduction of cross-stage DIL duplication.
The subsequent 2 commits are simple SSA cleanups.

Ssa: Replace phi-read references in VariableCapture with default use-use flow

---

csharp/ql/lib/semmle/code/csharp/controlflow/internal/PreSsa.qll

This adds a few tuples to the updated predicates. Spot-checking the additions for `adjacentReadPairSameVar` all look correct. The differences for `getAFirstRead` all had to do with `ref` variables, and I couldn't quite make sense of them, but there weren't that many, and I _think_ the new version ought to be more correct.

C#: Update PreSSA to reference the new use-use predicates.

---

shared/yaml/codeql/yaml/Yaml.qll

Seen on `github/codeql`, some queries had very poor performance:
```
[2/24 eval 36m4s] Evaluation done; writing results to codeql/actions-queries/Security/CWE-312/ExcessiveSecretsExposure.bqrs
```
Investigating further lead to the following worrying sequence of joins (after I ran out of patience and cancelled the query):
```
[2025-04-01 12:31:03] Tuple counts for Yaml::YamlInclude.getTargetPath/0#dispred#32565107#fb#reorder_1_0/2@i6#9f4b2jw1 after 8m40s:
...
559418    ~33%        {1} r5 = SCAN `Yaml::YamlNode.getLocation/0#dispred#24555c57#prev_delta` OUTPUT In.1
...
909345525 ~821%       {3} r7 = JOIN r5 WITH `Yaml::YamlNode.getLocation/0#dispred#24555c57#prev` CARTESIAN PRODUCT OUTPUT Rhs.1, Lhs.0 'result', Rhs.0
909342139 ~779%       {3}    | JOIN WITH …
```

Actions: Fix bad performance in `getTargetPath`

---

rust/ql/lib/codeql/rust/dataflow/Ssa.qll
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
rust/ql/test/library-tests/variables/Ssa.expected
rust/ql/test/query-tests/security/CWE-089/CONSISTENCY/SsaConsistency.expected
shared/ssa/codeql/ssa/Ssa.qll

The consistency check `phiWithoutTwoPriorRefs` revealed that we were creating too many pseudo reads of captured variables at calls. Instead of checking that a call can be reached from _some_ write, in order to be considered relevant, we instead need to check that it is _dominated_ by _some_ write.

Rust: Fix `capturedCallRead`

---

CODEOWNERS

This pull request adds @github/ps-codeql as a code owner of `**/experimental/quantum/` to support the development of post-quantum cryptography-related libraries and queries.
We’ll be committing stable but experimental work to these directories as it becomes ready for public use, with a near-term goal of moving it out of experimental.
To get started, we’d also need write access to `github/codeql`.
cc @adityasharad @lcartey

Add @ps-codeql to CODEOWNERS for experimental cryptography

---

rust/ql/lib/codeql/rust/internal/Type.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/lib/codeql/rust/internal/TypeMention.qll
rust/ql/test/library-tests/type-inference/type-inference.expected

This PR changes how the `Self` parameter is handled in trait methods. Suppose some trait `Trait<A>`. Today a method on this trait is handled like this (where the `|` is some fictional syntax):
```rust
fn before<Self>(self: Self | Trait<A>) -> A;
```
The `self` parameter has the type of an implicit `Self` parameter and the trait type. On a call the passed `self` is then matched as a "subtype" of `Trait<A>` to infer `A`.
With this PR the situration is now like this:
```rust
fn after<A, Self : Trait<A>>(self: Self) -> A;
```
The `self` parameter only has the `Self` type and the `Self` type parameter now has the trait as a trait bound. This works since we can now handle trait bounds on type parameters, and `A` is inferred through that.
The biggest benefit of this is that we no longer infer …

Rust: Make trait a base type mention of the self type parameter

---

swift/ql/lib/codeql/swift/dataflow/Ssa.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected
swift/ql/test/library-tests/dataflow/dataflow/test.swift

Something about the use-use steps in data flow looks buggy, but I'm not going to fix that here. This is just aiming for a one-for-one semantically equivalent switch to the new use-use predicates.

Swift: Update SSA to reference the new use-use predicates.

---

javascript/ql/lib/change-notes/2025-04-02-rimraf.md
javascript/ql/lib/ext/rimraf.model.yml
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/rimraf.js

Added MaD for `rimraf` functions which were not covered.

JS: Modeling of `rimraf` functions

---

csharp/ql/integration-tests/all-platforms/blazor_net_8/XSS.expected
csharp/ql/lib/change-notes/2025-03-08-blazor-parameter-passing-string-literal.md
csharp/ql/lib/semmle/code/csharp/frameworks/microsoft/aspnetcore/Components.qll
csharp/ql/test/library-tests/frameworks/microsoft/aspnetcore/blazor/NameList2.cs
csharp/ql/test/library-tests/frameworks/microsoft/aspnetcore/blazor/Xss.expected
csharp/ql/test/library-tests/frameworks/microsoft/aspnetcore/blazor/remoteFlowSource.expected

Continuation of https://github.com/github/codeql/pull/18957.
Older versions of Blazor used a string literal instead of a `nameof` expression in order to specify the property being set. Therefore, it is necessary to modify the corresponding jump node in order to model the steps correctly.

C#: Blazor: Support string literals as property names in jump nodes

---

misc/scripts/stageoverlap.py

I'm adding this script, since it's been quite useful for me. The code is somewhat ad-hoc, but it does the job well enough. Possible future extensions: it would be nice to filter trivial predicates for which we don't care whether they're repeated across stages. That could be done by actually parsing some DIL or staying with the ad-hoc nature, we could also add an optional argument with an allow-list of predicate prefixes. Regardless, as-is it's quite useful to get an overview of the different stages in DIL and their overlap. The script also works on concatenated DIL from several queries (which is what you get when you dump DIL from compiling an entire suite).

Misc: Add stage overlap script

---

rust/ql/lib/codeql/rust/elements/internal/FunctionImpl.qll
rust/ql/lib/codeql/rust/elements/internal/MethodCallExprImpl.qll
rust/ql/lib/codeql/rust/internal/Type.qll
rust/ql/lib/utils/test/InlineMadTest.qll
rust/ql/test/extractor-tests/canonical_path/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/extractor-tests/canonical_path/canonical_paths.expected
rust/ql/test/extractor-tests/canonical_path_disabled/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/extractor-tests/canonical_path_disabled/canonical_paths.expected
rust/ql/test/extractor-tests/generated/MacroItems/CONSISTENCY/AstConsistency.expected
rust/ql/test/library-tests/controlflow/Cfg.expected
rust/ql/test/library-tests/dataflow/global/inline-flow.expected
rust/ql/test/library-tests/dataflow/global/viableCallable.expected
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/library-tests/dataflow/local/inline-flow.expected
rust/ql/test/library-tests/dataflow/modeled/inline-flow.expected
rust/ql/test/library-tests/dataflow/pointers/inline-flow.expected
rust/ql/test/library-tests/dataflow/strings/inline-taint-flow.expected
rust/ql/test/library-tests/type-inference/loop/main.rs
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected
rust/ql/test/library-tests/type-inference/type-inference.ql
rust/ql/test/library-tests/variables/Cfg.expected
rust/ql/test/query-tests/security/CWE-022/TaintedPath.expected
rust/ql/test/query-tests/security/CWE-089/SqlInjection.expected
rust/ql/test/query-tests/security/CWE-311/CleartextTransmission.expected
rust/ql/test/query-tests/security/CWE-312/CleartextLogging.expected

Adds inline expectations tests for type inference.
The annotations for resolved method calls and field expressions are pretty straightforward and the annotations now subsume what we had in the expected file before.
I've also added annotations for inferred types. We obviously don't want to annotate every single expression, so these annotations are optional and can be used in important places only. These annotations depend on stringifying AST nodes which can be a bit annoying, but I don't think it's too bad is we only use them sparingly and can write the tests with that in mind.
Let's merge at least #19146 before this.

Rust: Add inline expectations test for type inference

---

shared/ssa/change-notes/2025-04-03-definitionext-deprecation.md
shared/ssa/codeql/ssa/Ssa.qll

This PR deprecates all public predicates and classes in the SSA library that somehow reference phi-read nodes or `DefinitionExt`. The `DefinitionExt` and `PhiReadNode` classes are still used internally in the SSA library, but they're now completely hidden.

Ssa: Deprecate the public DefinitionExt and PhiReadNode

---

config/sync-files.py
csharp/ql/test/query-tests/API Abuse/NoDisposeCallOnLocalIDisposable/NoDisposeCallOnLocalIDisposable.cs
csharp/ql/test/query-tests/API Abuse/NoDisposeCallOnLocalIDisposable/NoDisposeCallOnLocalIDisposable.expected
csharp/ql/test/query-tests/API Abuse/NoDisposeCallOnLocalIDisposable/NoDisposeCallOnLocalIDisposableBad.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantCondition.expected
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantConditionBad.cs
csharp/ql/test/query-tests/Bad Practices/Control-Flow/ConstantCondition/ConstantIfCondition.cs

To better allow inline expectations testing, we consider test files to be identical (or equivalent), if they are "the same" modulo comments.

C#: Accept file sync mismatch for C# testfiles.

---

ruby/ql/consistency-queries/DataFlowConsistency.ql
ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
ruby/ql/test/library-tests/dataflow/global/Flow.expected
ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected
ruby/ql/test/library-tests/dataflow/local/TaintStep.expected

Inspired by [this PR for Rust](https://github.com/github/codeql/pull/19106), we revert the change introduced in https://github.com/github/codeql/pull/10444, where `getPreUpdateNode` was made non-unique, and instead use reverse post-update steps to ensure that side-effects propagate correctly in the case of compound arguments.

Ruby: Make `getPreUpdateNode` Unique Again

---

csharp/ql/src/codeql-suites/csharp-code-quality.qls
csharp/ql/test/query-tests/Dead Code/DeadStoreOfLocal/DeadStoreOfLocal.cs
csharp/ql/test/query-tests/Dead Code/DeadStoreOfLocal/DeadStoreOfLocal.qlref
csharp/ql/test/query-tests/Dead Code/DeadStoreOfLocal/DeadStoreOfLocalBad.cs

In this PR we
- Add the `cs/useless-assignment-to-local` query to the code quality query suite.
- Re-factor the tests to use inline expectations and add a test, which uses string interpolation.

C#: Add `cs/useless-assignment-to-local` to the code quality suite.

---

rust/ql/integration-tests/hello-project/summary.expected
rust/ql/integration-tests/hello-workspace/summary.cargo.expected
rust/ql/integration-tests/hello-workspace/summary.rust-project.expected
rust/ql/lib/codeql/rust/dataflow/internal/Content.qll
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/FlowSummaryImpl.qll
rust/ql/lib/codeql/rust/elements/internal/EnumImpl.qll
rust/ql/lib/codeql/rust/elements/internal/PathImpl.qll
rust/ql/lib/codeql/rust/frameworks/stdlib/Stdlib.qll
rust/ql/lib/codeql/rust/internal/CachedStages.qll
rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/lib/codeql/rust/internal/PathResolutionConsistency.qll
rust/ql/lib/codeql/rust/internal/Type.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/extractor-tests/canonical_path/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/extractor-tests/canonical_path_disabled/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/library-tests/path-resolution/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/library-tests/path-resolution/main.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected
rust/ql/test/library-tests/path-resolution/path-resolution.ql
rust/ql/test/query-tests/diagnostics/SummaryStats.expected

This PR started out with me wanting to get rid of the `VariantInLib` workaround, which was needed prior to [extracting the crate graph](https://github.com/github/codeql/pull/18228).
Removing `VariantLib` means we will be using our QL logic for resolving `option::Option` and `result::Result` paths, instead of relying on `getExtendedCanonicalPath` provided by the extractor. However, in order to resolve those paths, we need to take [the standard library prelude](https://doc.rust-lang.org/reference/names/preludes.html#standard-library-prelude) into account, which is exactly what this PR does.
Since we don't know which edition of Rust is being used, we simply include all the editions; 2015, 2018, 2021, and 2024.
Removing `VariantLib` also revealed that we need to handle `$crate` paths inside …

Rust: Take prelude into account when resolving paths

---

rust/ql/lib/codeql/rust/security/CleartextLoggingExtensions.qll
rust/ql/lib/codeql/rust/security/CleartextTransmissionExtensions.qll
rust/ql/lib/codeql/rust/security/SqlInjectionExtensions.qll
rust/ql/lib/codeql/rust/security/TaintedPathExtensions.qll
rust/ql/lib/codeql/rust/security/WeakSensitiveDataHashingExtensions.qll
rust/ql/lib/codeql/rust/security/regex/RegexInjectionExtensions.qll
rust/ql/src/queries/security/CWE-020/RegexInjection.ql
rust/ql/src/queries/security/CWE-022/TaintedPath.ql
rust/ql/src/queries/security/CWE-089/SqlInjection.ql
rust/ql/src/queries/security/CWE-311/CleartextTransmission.ql
rust/ql/src/queries/security/CWE-312/CleartextLogging.ql
rust/ql/src/queries/security/CWE-328/WeakSensitiveDataHashing.ql
rust/ql/src/queries/summary/Stats.qll
rust/ql/test/query-tests/security/CWE-020/RegexInjectionSink.ql

Fixes a number of inconsistencies in the Rust queries:
- all sinks now extend `QuerySink::Range`.
- these are essentially semantic merge conflicts, as we merged the `QuerySink` class at about the same time as several new queries that were written without it.
- all query extensions files are included in `Stats.qll`.
- thus, all queries will be included in sink stats e.g. on the DCA job.
- all query extension files use a `module` now (for tidiness).
- all queries have extendable sources, where appropriate.
- more consistent class names in a few cases (slightly improves maintainability).
- more consistent import order (slightly improves maintainability).

Rust: Define queries more consistently and include all sinks in stats

---

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.20.7.rst
docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.21.0.rst
docs/codeql/codeql-overview/codeql-changelog/index.rst

This pull request includes updates to the CodeQL CLI changelog documentation for versions 2.20.7 and 2.21.0. The changes detail new features, bug fixes, and enhancements across multiple languages and components. Additionally, the changelog index has been updated to include these new versions.

Add changelog entries for CodeQL CLI versions 2.20.7 and 2.21.0

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll

Only matters to `rust-lang/rust`, where the prelude exists in both source code and in the crate graph, so we need to handle both.

Rust: Minor path resolution fix for `($)crate` paths

---

ruby/ql/src/change-notes/2025-04-04-refine-deadstore.md
ruby/ql/src/queries/variables/DeadStoreOfLocal.qhelp
ruby/ql/src/queries/variables/DeadStoreOfLocal.ql
ruby/ql/src/queries/variables/examples/DeadStoreOfLocal.rb
ruby/ql/src/queries/variables/examples/DeadStoreOfLocalGood.rb
ruby/ql/test/query-tests/variables/DeadStoreOfLocal/DeadStoreOfLocal.expected
ruby/ql/test/query-tests/variables/DeadStoreOfLocal/DeadStoreOfLocal.qlref
ruby/ql/test/query-tests/variables/DeadStoreOfLocal/DeadStoreOfLocal.rb
ruby/ql/test/query-tests/variables/DeadStoreOfLocal/TestTemplate.rb

In preparation for shipping `rb/useless-assignment-to-local` as a quality query, this PR removes three classes of FPs:
- a call to `result` on an ERB template will grab all the local variables referenced in the template (example [here](https://github.com/rails/rails/blob/951ea8f75d9bf6d2999df2f0497347976dce9476/actionpack/lib/action_dispatch/journey/gtg/transition_table.rb#L159C11-L159C21)). As an approximation, we do not report useless assignments in the vicinity of such calls.
- a reference to `binding` (as seen in the above example, but templates can also work without such a reference) will capture all the local variables in the scope. This means such assignments are useful even if not explicitly read. Our SSA analysis currently do not see these implicit reads. As an approximation, we …

ruby: remove some FPs from `rb/useless-assignment-to-local`

---

java/ql/src/Telemetry/SupportedExternalApis.ql
java/ql/src/Telemetry/SupportedExternalSinks.ql
java/ql/src/Telemetry/UnsupportedExternalAPIs.ql

In the future, this tag should signal to the action that the queries should be excluded from incremental scans because they are too slow and/or produce too many results.
The three queries tagged here rely on global data-flow analysis to find all XSS sinks. All other metric and diagnostic queries are fast enough for incrementality.
This is a copy of https://github.com/github/codeql/pull/18788, except with a different tag name.

Java: add exclude-from-incremental tag to telemetry queries

---

rust/ql/consistency-queries/SsaConsistency.ql
rust/ql/integration-tests/hello-project/summary.expected
rust/ql/integration-tests/hello-workspace/summary.cargo.expected
rust/ql/integration-tests/hello-workspace/summary.rust-project.expected
rust/ql/src/queries/diagnostics/SsaConsistencyCounts.ql
rust/ql/src/queries/summary/Stats.qll
rust/ql/test/query-tests/diagnostics/SsaConsistencyCounts.expected
rust/ql/test/query-tests/diagnostics/SsaConsistencyCounts.qlref
rust/ql/test/query-tests/diagnostics/SummaryStatsReduced.expected
shared/ssa/codeql/ssa/Ssa.qll

Provide SSA inconsistency counts:
- precise data through existing query `rust/diagnostics/ssa-consistency` (which has been given metadata).
- totals per inconsistency type through new query `rust/diagnostics/ssa-consistency-counts`.
- overall totals through `rust/summary/summary-statistics` (via changes in `Stats.qll`).  This data will be used by the DCA report.
This required adding a predicate `getInconsistencyCounts` to the shared `SSA.qll`, similar to the one we already have for data flow.  This shouldn't be controversial as no existing shared behaviour is changed, but I'm open to suggestions / comments representing all interests of course.

Rust: SSA inconsistency counts

---

csharp/ql/integration-tests/all-platforms/diag_missing_project_files/test.py
csharp/ql/integration-tests/posix/standalone_dependencies_no_framework/test.py
csharp/ql/integration-tests/posix/standalone_dependencies_nuget with_space/test.py
csharp/ql/integration-tests/posix/standalone_dependencies_nuget/test.py
csharp/ql/integration-tests/posix/standalone_dependencies_nuget_no_sources/test.py

`csharp` tests that use `nuget` don't seem to be working, possibly due to issues with provisioning of `Mono` and `nuget` on those runners: https://github.com/actions/runner-images/blob/macos-15/20250120.591/images/macos/macos-15-Readme.md 
Disabling the tests on that platform for now.

Disable csharp tests that use nuget on macos-15

---

go/extractor/toolchain/toolchain.go

Seems like `err` was used incorrectly instead of `decErr` here. The Go compiler alerted me to this, since `err` is `nil` at this point.

Go: Fix `err` instead of `decErr` in `GetPkgsInfo`

---

java/ql/src/codeql-suites/java-security-and-quality.qls

This PR is explicitly mentioning all the quality query IDs in the Java security and quality suite.
It should be merged after https://github.com/github/codeql/pull/19229.

Java: Add explicit filtering for quality queries that should be included in security-and-quality

---

java/ql/integration-tests/java/buildless-inherit-trust-store/test.py
java/ql/integration-tests/java/buildless-snapshot-repository/test.py

`macos-15` has issues with test maven servers, that causes timeouts. Running those servers with `sudo` fixes the problem.
Same fix that https://github.com/github/codeql/pull/19204

Run test servers with `sudo` when running on `macos-15`

---

docs/codeql/codeql-language-guides/codeql-for-actions.rst
docs/codeql/codeql-language-guides/codeql-library-for-actions.rst
docs/codeql/codeql-language-guides/customizing-library-models-for-actions.rst
docs/codeql/codeql-language-guides/customizing-library-models-for-ruby.rst
docs/codeql/codeql-language-guides/index.rst
docs/codeql/reusables/supported-frameworks.rst

Discovered in internal review of docs preview.
Use double backticks to render inline code blocks. Use __ after inline hyperlinks.
Use an extra blank line to format the Actions library predicates table correctly. Fix some rogue references to Ruby and case inconsistency.
Place GitHub Actions link lower in sidebar (order by human-readable language name).

Docs: Fix formatting of GitHub Actions content

---

javascript/ql/lib/change-notes/2025-04-07-open-package.md
javascript/ql/lib/ext/open.model.yml
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/open.js

Added model as data for `open` package.

JS: Model as Data `open` package

---

javascript/ql/lib/change-notes/2025-04-02-mkdirp.md
javascript/ql/lib/ext/mkdirp.model.yml
javascript/ql/lib/semmle/javascript/frameworks/Files.qll
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/mkdirp.js

Added MaD for `mkdirp` functions which were not covered and converted old modeling of `mkdirp` to MaD.

JS: Modeling of `mkdirp` functions

---

java/ql/integration-tests/java/gradle-sample-without-wrapper-or-gradle-buildless/diagnostics.expected

The wording of the diagnostic message is updated for buildless scenarios where 'Built' isn't appropriate.

Java: Update test expectation

---

java/ql/lib/change-notes/2025-04-09-enum-type-exclusion.md
java/ql/lib/semmle/code/java/security/Sanitizers.qll

For the same reasons as integers and other simple values, enums are probably not useful injection vectors for most purposes.

Java: Add EnumType to SimpleTypeSanitizer

---

actions/extractor/tools/autobuild.cmd

Pass the quoted script path to PowerShell using `-File`. This ensures the path is treated as a string rather than a command, and correctly handles file paths that contain spaces, unblocking integration tests.
Add logging to autobuild.cmd for easier debugging.

Actions: Fix invocation of autobuild PowerShell script

---

ruby/ql/src/queries/variables/DeadStoreOfLocal.ql

```
[2025-04-09 09:22:56] (380s) Cancelling evaluation of #11561 evaluator _ApiGraphs::API::Impl::MkMethodAccessNode#4daa063f_ApiGraphs::API::Impl::TApiNode#368fc76d_ApiGraphs__#antijoin_rhs/1@d02e8ckf: Demand has vanished for #11561 evaluator _ApiGraphs::API::Impl::MkMethodAccessNode#4daa063f_ApiGraphs::API::Impl::TApiNode#368fc76d_ApiGraphs__#antijoin_rhs/1@d02e8ckf
[2025-04-09 09:22:56] (380s) Tuple counts for _ApiGraphs::API::Impl::MkMethodAccessNode#4daa063f_ApiGraphs::API::Impl::TApiNode#368fc76d_ApiGraphs__#antijoin_rhs/1@d02e8ckf after 5m17s:
12500       ~2341%      {2} r1 = JOIN `__Variable::LocalVariable.getDefiningAccess/0#dispred#316bde3e_10#join_rhs__Variable::LocalVariableW__#shared` WITH `Statement::Stmt.getCfgScope/0#dispred#58b7c05d` ON FIRST 1 OUTPUT Rhs.1, Lhs.0 'arg0' …
```

Ruby: Fix bad join in `DeadStoreOfLocal.ql`

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll

The extractor produces fully crate-qualified paths for entities extracted from the crate graph, which our path resolution logic handles. However, for entities where the crate-qualifier refers to the defining crate itself, the extractor should have used the special `crate` qualifier instead of the name of the crate.
For example, the `impl<T> Option<T>` block is extracted as `impl<T> core::option::Option<T>` instead of `impl<T> crate::option::Option<T>`.
This PR adjusts our path resolution logic to also handle crate self-references like above, but restricted to entities from the crate graph.
DCA shows that, while we maintain performance, we reduce the number of unresolved call targets by 16 % (down 1,699,468 from 2,012,848), all numbers computed across the entire DCA suite.
cc @aibaars

Rust: Allow for crate self-references in crate graph paths

---

javascript/ql/lib/javascript.qll
javascript/ql/lib/semmle/javascript/frameworks/HTTP.qll
javascript/ql/lib/semmle/javascript/frameworks/WebResponse.qll
javascript/ql/lib/semmle/javascript/security/dataflow/ReflectedXssCustomizations.qll
javascript/ql/src/change-notes/2025-04-09-web-response.md
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.expected
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXssWithCustomSanitizer.expected
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/response-object.js

Recognizes the `x` in `new Response(x)` as a `ResponseSendArgument`; the main effect is that it becomes a sink for reflected XSS.
Our HTTP model assumes each `ResponseSendArgument` has an associated `RouteHandler` and we use that to identify related header definitions. This meant it was not possible to associate a `ResponseSendArgument` with its header definitions if they did not have the same route handler.
But for calls like `new Response(body, { headers })` the headers are fairly obvious whereas the route handler is unnecessarily hard to find. So this PR also extends the HTTP model a bit to better account for sinks where we can use the direct and obvious association between 'body' and 'headers' in the call.

JS: Add sinks for calls to 'new Response()'

---

javascript/ql/lib/change-notes/2025-04-09-make-dir.md
javascript/ql/lib/ext/make-dir.model.yml
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected
javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/make-dir.js

The following pull-request adds model as data for `make-dir` package.

JS: Add support for `make-dir` package

---

docs/codeql/query-help/index.rst

This list would currently be incorrectly published as shown in the screenshot below. This PR corrects the order to alphabetic. So "GitHub Actions" should appear after C/C++ and C#.

CodeQL docs: Fix ordering in side navigation bar for Query help

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/elements/internal/AstNodeImpl.qll
rust/ql/lib/codeql/rust/elements/internal/VariableImpl.qll
rust/ql/lib/codeql/rust/internal/CachedStages.qll
rust/ql/lib/codeql/rust/internal/PathResolution.qll

Using @aschackmull 's [stage overlay script](https://github.com/github/codeql/pull/19156), I identified some unintended cases of predicates being recomputed, which this PR addresses, by making sure that more predicates are cached (in the same stage).
[DCA shows](https://github.com/github/codeql-dca-main/tree/data/hvitved/PR-19246-0-rust/reports#analysis-time-per-source) a whopping 10% analysis time speedup, and we also [reduce the DIL size](https://github.com/github/codeql-dca-main/blob/data/hvitved/PR-19246-0-rust/reports/summaries/output.theme.md#dil-sizes) as expected.

Rust: Cache tweaks

---

javascript/ql/lib/change-notes/2025-04-07-websocket.md
javascript/ql/lib/semmle/javascript/frameworks/WebSocket.qll
javascript/ql/src/Security/trest/test.ql
javascript/ql/test/library-tests/frameworks/WebSocket/browser-custom.js
javascript/ql/test/library-tests/frameworks/WebSocket/browser.js
javascript/ql/test/library-tests/frameworks/WebSocket/client-custom.js
javascript/ql/test/library-tests/frameworks/WebSocket/client.js
javascript/ql/test/library-tests/frameworks/WebSocket/server-custom.js
javascript/ql/test/library-tests/frameworks/WebSocket/server.js
javascript/ql/test/library-tests/frameworks/WebSocket/sockjs.js
javascript/ql/test/library-tests/frameworks/WebSocket/test.expected
javascript/ql/test/library-tests/frameworks/WebSocket/test.qlref

Refactored `WebSocket` to use `API` graphs, thus it would work with custom wrappers.
Added inline test expectations for `library-tests/frameworks/WebSocket`.

JS: Refactor `WebSocket` to use `API` graphs

---

javascript/ql/lib/change-notes/2025-04-07-typed-arrays.md
javascript/ql/lib/semmle/javascript/internal/flow_summaries/AllFlowSummaries.qll
javascript/ql/lib/semmle/javascript/internal/flow_summaries/Decoders.qll
javascript/ql/lib/semmle/javascript/internal/flow_summaries/Strings.qll
javascript/ql/lib/semmle/javascript/internal/flow_summaries/TypedArrays.qll
javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected
javascript/ql/test/library-tests/TaintTracking/typed-arrays.js
javascript/ql/test/query-tests/Security/CWE-522-DecompressionBombs/DecompressionBombs.expected

This pull request introduces taint modeling for the most commonly used `TypedArray`, specifically the [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array), which is primarily utilized in byte-to-string operations. It excludes other `TypedArray` types, such as [Int32Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array), as they are generally not associated with taint propagation.
Additionally, this update adds support for `ArrayBuffer` and `SharedArrayBuffer`, which are frequently used in low-level operations and are often passed to `TypedArray` constructors.
Finally, the pull request includes taint propagation for `TextDecoder`, as it plays a key role in converting `ArrayBuffer` or …

JS: Taint propagation from low-level `ArrayBuffer` to `Strings`

---

cpp/ql/lib/semmle/code/cpp/dataflow/ExternalFlow.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TaintTrackingUtil.qll

This PR does the necessary changes to existing C++ code required for model generation. It should be a no-opt in terms of results and performance.
DCA was uneventful (as expected).

C++: Prepare for model generation adoption

---

csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll
java/ql/src/utils/modelgenerator/internal/CaptureModels.qll
rust/ql/src/utils/modelgenerator/internal/CaptureModels.qll
shared/mad/codeql/mad/modelgenerator/internal/ModelGeneratorImpl.qll

This PR slightly generalizes the model generation input signature to allow for a smooth C++ adoption:
- 732fcbf1c908abbe7f6976e7aff17712eca8ab89 moves the `asParameter` out of the `NodeExtended` signature. This is necessary because the return type of C++'s `Node.asParameter` is different from the actual parameter nodes we use inside dataflow.
- Likewise, c484945f395d31e7c6c131ef373baf467ca8b555 moves the `getEnclosingCallable` out of the `NodeExtended` for similar reasons. I also moved `getAsExprEnclosingCallable` for symmetry.
- ea3bb8cf0c2a362c02b1ea586733706e52a1596c adds a hook to customize the `ReturnValue` string for `ValueReturnKind`s. This necessary because C++ has `ReturnValue`, `ReturnValue[*]`, `ReturnValue[**]`, etc, for returning `p`, `*p`, `**p` from a function. …

Shared: Prepare model generation for C++ adoption

---

csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs
csharp/autobuilder/Semmle.Autobuild.Shared/Project.cs
csharp/ql/lib/change-notes/2025-04-11-auto-builder-sdk.md

In this PR we extend the auto builder heuristic detection logic for when to use `dotnet` to build a project.
There are tree ways to reference an `Sdk`, which is described [here](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022#reference-a-project-sdk).
DCA doesn't show any changes to performance, build capabilities or alerts for the projects in our autobuild suite.

C#: Improve auto-builder to better detect SDK references.

---

csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs
csharp/autobuilder/Semmle.Autobuild.Cpp.Tests/BuildScripts.cs
csharp/autobuilder/Semmle.Autobuild.Shared/MsBuildRule.cs
csharp/extractor/Semmle.Util/BuildActions.cs
csharp/ql/integration-tests/all-platforms/diag_missing_project_files/test.py

This pull request includes several changes to improve the handling of the autobuild process, particularly for different operating systems and scenarios where `mono` is or isn't available. The main changes involve updating the process execution logic and adding new test cases for better coverage.

C#: Fix autobuild on macos without mono

---

actions/ql/src/Security/CWE-312/UnmaskedSecretExposure.md

Corrects "know" to "known" in the description of the UnmaskedSecretExposure document.

actions: Fix spelling error in UnmaskedSecretExposure.md

---

actions/ql/src/Security/CWE-077/EnvVarInjectionMedium.md
actions/ql/src/Security/CWE-275/MissingActionsPermissions.ql
actions/ql/src/Security/CWE-312/ExcessiveSecretsExposure.ql
actions/ql/src/Security/CWE-312/UnmaskedSecretExposure.md
actions/ql/src/change-notes/2025-04-14-excessive-secrets-exposure-security-severity.md
docs/codeql/reusables/supported-versions-compilers.rst

Remove the public preview notice for the next publish.
Various corrections to query help.
Add missing `security-severity` for the excessive secrets exposure query.

Actions: Remove preview notice, minor help and metadata fixes

---

csharp/autobuilder/Semmle.Autobuild.Shared/Project.cs

This pull request includes changes to improve the readability and correctness of the XML documentation in the `Semmle.Autobuild.Shared/Project.cs` file. The most important change is the replacement of angle brackets with their HTML-encoded equivalents to ensure proper rendering in documentation.
The change was made with CoPilot in Agent mode and the PR description above was generated using CoPilot.

C#: Adjust comments and remove compilation warnings.

---

rust/extractor/src/crate_graph.rs
rust/ql/lib/codeql/rust/elements/internal/LifetimeImpl.qll
rust/ql/test/extractor-tests/crate_graph/module.rs
rust/ql/test/extractor-tests/crate_graph/modules.expected
rust/ql/test/extractor-tests/crate_graph/modules.ql
rust/ql/test/extractor-tests/generated/BreakExpr/BreakExpr.expected
rust/ql/test/extractor-tests/generated/BreakExpr/BreakExpr_getExpr.expected
rust/ql/test/extractor-tests/generated/BreakExpr/BreakExpr_getLifetime.expected
rust/ql/test/extractor-tests/generated/ContinueExpr/ContinueExpr_getLifetime.expected
rust/ql/test/extractor-tests/generated/Label/Label_getLifetime.expected
rust/ql/test/extractor-tests/generated/SelfParam/SelfParam_getLifetime.expected
rust/ql/test/extractor-tests/utf8/ast.expected
rust/ql/test/library-tests/controlflow/BasicBlocks.expected
rust/ql/test/library-tests/controlflow/Cfg.expected
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected

This PR aims to support the extraction of generic parameters, arguments, and the resolution of bound type variables in Rust.

Rust: extract generic parameters, arguments and resolve bound type variables

---

javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll
javascript/ql/test/library-tests/DataFlow/tests.expected
javascript/ql/test/library-tests/GetALocalSource/rest-pattern.js
javascript/ql/test/library-tests/GetALocalSource/test.expected
javascript/ql/test/library-tests/GetALocalSource/test.ql
javascript/ql/test/library-tests/GetALocalSource/test.qlref

We were missing a value step from one of the internal nodes in a `...rest` pattern that would allow flow to react the corresponding SSA node. This manifested in `getALocalSource` not working. As far as I can tell, data flow still worked, though.

JS: Fix missing flow into rest pattern lvalue

---

ruby/ql/test/library-tests/modules/ancestors.expected
ruby/ql/test/library-tests/modules/ancestors.ql
ruby/ql/test/library-tests/modules/superclasses.expected
ruby/ql/test/library-tests/modules/superclasses.ql

Graphs use the internal id if `semmle.order` is not good enough. However the internal id of a `newtype` depends on evaluation order (and in this case whether `TResolved` or `TUnresolved` is evaluated first). It seems the current evaluator is very consistent but RTJO changes it. In theory though the current evaluator could get the wrong result as multiple threads can change scheduling order.
I am looking into making the graph code use the label as an intermediate order. However we end up still needing us to make this test deterministic as the change would break this test.
This just adds the `toString` as an order when the location is not defined, I have put these first in the order as that matches the existing results better (if `semmle.order` is not defined then it is treated 0).
I have …

Ruby: Make module graph queries avoid relying on evalaution order.

---

swift/ql/integration-tests/autobuilder/xcode-fails-spm-works/Files.ql
swift/ql/integration-tests/osx/canonical-case/Files.ql
swift/ql/integration-tests/osx/hello-ios/Files.ql
swift/ql/integration-tests/osx/hello-xcode/Files.ql
swift/ql/integration-tests/posix/cross-references/Classes.ql
swift/ql/integration-tests/posix/cross-references/Deinitializers.ql
swift/ql/integration-tests/posix/cross-references/Enums.ql
swift/ql/integration-tests/posix/cross-references/Functions.ql
swift/ql/integration-tests/posix/cross-references/Initializers.ql
swift/ql/integration-tests/posix/cross-references/Protocols.ql
swift/ql/integration-tests/posix/cross-references/Structs.ql
swift/ql/integration-tests/posix/cross-references/VarDecls.ql
swift/ql/integration-tests/posix/frontend-invocations/Files.ql
swift/ql/integration-tests/posix/hello-world/test.ql
swift/ql/integration-tests/posix/symlinks/Files.ql

With Swift 6.1 the extractor will start to extract files outside of the test directory. These files and their elements we do not want to see in our tests.
Targeting `main` with this PR to ensure we do not break something by accident in the upgrade.
Integration test counterpart to https://github.com/github/codeql/pull/19344

Swift: Make file checking in integration tests more strict

---

swift/ql/test/library-tests/elements/location/location.ql

With Swift 6.1 the extractor will start to extract files outside of the test directory. These files and their elements we do not want to see in our tests.
Test forgotten in https://github.com/github/codeql/pull/19344

Swift: Make file checking in tests more strict

---

shared/util/codeql/util/FileSystem.qll

Before
```
Evaluated relational algebra for predicate FileSystem::Folder::Append<PathResolution::shouldAppend>::appendStep/3#bed54f6d@d2a7eeoa on iteration 2 running pipeline standard with tuple counts:
120   ~2%    {4} r1 = SCAN `FileSystem::Folder::Append<PathResolution::shouldAppend>::appendStep/3#bed54f6d#prev_delta` OUTPUT In.1, In.0, In.2, In.3
0   ~0%    {6} r2 = JOIN r1 WITH `_FileSystem::Folder::Append<PathResolution::shouldAppend>::getComponent/2#a6e36a04#join_rhs#1` ON FIRST 1 OUTPUT Lhs.0, Rhs.1, Lhs.1, Lhs.2, Lhs.3, _
{6}    | REWRITE WITH Tmp.5 := 1, Out.5 := (InOut.1 - Tmp.5), TEST Out.5 = InOut.3
0   ~0%    {4}    | SCAN OUTPUT In.2, In.0, In.1, In.4
91   ~3%    {6} r3 = JOIN r1 WITH `_FileSystem::Folder::Append<PathResolution::shouldAppend>::getComponent/2#a6e36a04#join_rh …
```

Shared: Fix join in `FileSystem.qll`

---

csharp/ql/lib/semmle/code/csharp/security/auth/MissingFunctionLevelAccessControlQuery.qll
csharp/ql/src/change-notes/2025-04-15-missing-function-level-access-control.md
csharp/ql/test/query-tests/Security Features/CWE-285/MissingAccessControl/MVCTests/MissingAccessControl.expected
csharp/ql/test/query-tests/Security Features/CWE-285/MissingAccessControl/MVCTests/MissingAccessControl.qlref
csharp/ql/test/query-tests/Security Features/CWE-285/MissingAccessControl/MVCTests/ProfileController.cs

The change note was made mostly using CoPilot chat.
With the right context (the query, query module and another change note) it produced reasonable output.
DCA is uneventful.

C#: Relax condition for authorize attributes on `cs/web/missing-function-level-access-control`.

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/lib/utils/test/PathResolutionInlineExpectationsTest.qll
rust/ql/test/library-tests/path-resolution/main.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/variables/variables.ql

I used Copilot Agent to generate the test case, which mostly worked fine, except it inserted a stray whitespace in one of the comment markers, which took my quite a while to identify. To prevent this from happening again, I've inserted appropriate trimming of the markers.

Rust: Take `where` clauses into account in path resolution

---

rust/ql/test/library-tests/dataflow/local/DataFlowStep.ql

Should've ben done in https://github.com/github/codeql/pull/19305/files .

Rust: Remove unnecessary predicate.

---

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ExternalFlow.qll

Fix join order in `ExternalFlow::interpretElement/6`, which was causing a huge slowdown in RTJO mode.

C#: Join order fix

---

shared/dataflow/codeql/dataflow/DataFlow.qll

The context for this is that we might want to raise it to 3 for C++ in combination with some other changes.

Dataflow: Make default field flow branch limit configurable per language

---

docs/codeql/reusables/supported-platforms.rst

I've effectively sync'ed this with the list of runners that are publicly available. I did not yet add Windows 2025, as it is my understanding is that we haven't really done any testing on that yet.

Update list of supported platforms

---

cpp/ql/src/Likely Bugs/Arithmetic/IntMultToLong.ql
cpp/ql/src/Likely Bugs/Format/WrongTypeFormatArguments.ql
cpp/ql/src/Likely Bugs/Underspecified Functions/ImplicitFunctionDeclaration.ql
cpp/ql/src/Security/CWE/CWE-190/ComparisonWithWiderType.ql
cpp/ql/src/Security/CWE/CWE-468/SuspiciousAddWithSizeof.ql

This PR introduces checks for the absence of build-mode-none in
* cpp/wrong-type-format-argument
* cpp/comparison-with-wider-type
* cpp/integer-multiplication-cast-to-long
* cpp/implicit-function-declaration
* cpp/suspicious-add-sizeof

C++: Add exception for build-mode-none in various queries

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll

Rust: Path resolution performance tweaks

---

python/ql/lib/semmle/python/security/dataflow/PolynomialReDoSQuery.qll

This commit disabled diff-informed for PolynomialReDoS.ql because it could miss some alerts within diff ranges.

Python: disable diff-informed PolynomialReDoS.ql

---

csharp/ql/lib/semmle/code/csharp/Stmt.qll
csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImpl.qll
csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected
csharp/ql/test/library-tests/controlflow/graph/Condition.expected
csharp/ql/test/library-tests/controlflow/graph/Dominance.expected
csharp/ql/test/library-tests/controlflow/graph/EnclosingCallable.expected
csharp/ql/test/library-tests/controlflow/graph/EntryElement.expected
csharp/ql/test/library-tests/controlflow/graph/ExitElement.expected
csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected
csharp/ql/test/library-tests/controlflow/graph/Nodes.expected
csharp/ql/test/library-tests/controlflow/graph/Switch.cs

Thanks to @aschackmull for making me aware, and providing the example.
Before
```mermaid
flowchart TD
1["enter M16"]
10["2"]
11["call to method WriteLine"]
12["...;"]
13[""1 or 2""]
14["break;"]
15["case ...:"]
16["3"]
17["call to method WriteLine"]
18["...;"]
19[""3""]
2["exit M16"]
20["break;"]
21["default:"]
22["call to method WriteLine"]
23["...;"]
24[""def""]
25["break;"]
3["exit M16 (normal)"]
4["{...}"]
5["switch (...) {...}"]
6["access to parameter i"]
7["case ...:"]
8["1"]
9["case ...:"]
1 --> 4
3 --> 2
4 --> 5
5 --> 6
6 --> 7
7 --> 8
8 -- match, no-match --> 9
9 --> 10
10 -- match --> 12
10 -- no-match --> 14
10 -- no-match --> 15
11 --> 14
12 --> 13
13 --> 11
14 -- break --> 3
15 --> 16
16 -- match --> 18
16 -- no-match --> 21
17 --> 20
18 --> 19
19 --> 17
20 -- break --> 3
21 …
```

C#: Fix CFG for fall-through switch statements

---

cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/UseAfterFree/UseAfterFree.expected
cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/UseAfterFree/test.cpp

These derive from https://github.com/github/codeql/issues/19387. Note that these FPs are a known issue.

C++: Add use-after-free FP tests

---

shared/mad/codeql/mad/modelgenerator/internal/ModelGeneratorImpl.qll

A not-super-widely-known feature from state-based dataflow configurations is that you can omit the state (see [here](https://github.com/github/codeql/pull/13851)) in the `isSink` when you don't want to restrict the state in `isSink`.
It looks like this is exactly what's being done in `PropagateFlowConfig::isSink` so we might as well omit the sink and avoid the small cartesian product.

Shared: Use `isSink/1` in `PropagateFlowConfig`

---

csharp/ql/integration-tests/posix/query-suite/csharp-code-quality.qls.expected
csharp/ql/src/Likely Bugs/EqualityCheckOnFloats.ql
csharp/ql/src/change-notes/2025-04-28-equality-on-floats-precision.md
csharp/ql/src/codeql-suites/csharp-code-quality.qls

The precision of the query has been increased to high. Even though comparing floats in many cases yield correct results, it should generally be avoided. If exact comparison is needed, `decimal` should be used instead.

C#: Add `cs/equality-on-floats` to the Code Quality suite.

---

csharp/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPartialPath.ql
csharp/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPath.ql
java/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPartialPath.ql
java/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPath.ql
rust/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPartialPath.ql
rust/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPath.ql

The DCA suites are relying on the `modelgenerator` tag, so we should tag the local debug queries differently.
The failing Java integration test is unrelated.

C#/Java/Rust: Change the tag for the model generator debugging queries.

---

rust/extractor/src/crate_graph.rs
rust/ql/lib/codeql/rust/frameworks/stdlib/Clone.qll
rust/ql/test/library-tests/dataflow/modeled/inline-flow.expected
rust/ql/test/library-tests/type-inference/type-inference.ql
rust/ql/test/query-tests/security/CWE-089/CONSISTENCY/PathResolutionConsistency.expected

Written with the help from Copilot chat.
[DCA](https://github.com/github/codeql-dca-main/issues/28513) looks great; the `Missing call targets` metric goes down for all projects, without significant analysis slowdown.

Rust: Extract `SelfParam`s from crate graph

---

python/ql/src/Resources/FileNotAlwaysClosedQuery.qll

Thanks to @nickrolfe and @alexet for help on slack.

Python: Improve performance of FileNotClosed query by using an explicit fastTC

---

javascript/ql/lib/semmle/javascript/ApiGraphs.qll
javascript/ql/lib/semmle/javascript/internal/flow_summaries/Promises.qll
javascript/ql/src/change-notes/2025-04-30-promise-all.md

Adds explicit type-tracking steps through common uses of `Promise.all`:
In the following example, we'd generate a read step from `promise1 -> val1` reading the promise-content, and likewise for `promise2 -> val2`:
```js
const [ val1, val2 ] = await Promise.all([ promise1, promise2 ]);
```
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/promise-all__default__code-scanning__1/reports) looks good, showing 15 new call edges, 18 new sinks, and 11 new threat model sources.

JS: Better type-tracking through Promise.all()

---

rust/ql/lib/codeql/rust/internal/CachedStages.qll
rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/lib/codeql/rust/internal/Type.qll

This PR works around two issues in the crate graph extractor:
1. We currently don't know when a trait function has a default implementation, so we assume that it always does.
2. The crate graph extractor sometimes generates paths that are not valid, in terms of visibility. For example, instead of generating the path `core::iter::Iterator` (because that's how it is [publicly visible](https://doc.rust-lang.org/src/core/iter/mod.rs.html#450)), it generates `core::iter::traits::iterator::Iterator`, which mentions the private `traits` module.
~[DCA](https://github.com/github/codeql-dca-main/issues/28487) looks great; the `Missing call targets` metric goes down for all projects, without significant analysis slowdown.~
[DCA](https://github.com/github/codeql-dca-main/issues/28625) is somewhat …

Rust: Crate graph extraction workarounds

---

ruby/ql/lib/codeql/ruby/security/regexp/MissingFullAnchorQuery.qll
ruby/ql/lib/codeql/ruby/security/regexp/PolynomialReDoSQuery.qll

These queries were failing in `codeql test run --check-diff-informed` because they can select locations inside the regex. Until that can be fixed, diff-informed mode is disabled for these queries.
I didn't add a code comment with details about the problem because I didn't investigate it in full detail, but I presume it's overall the same story as in #19379.
Cc @d10c @cklin @asgerf

Ruby: disable diff-informed mode on regex queries

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected
rust/ql/test/query-tests/security/CWE-089/SqlInjection.expected
rust/ql/test/utils-tests/modelgenerator/CaptureSummaryModels.expected

Removes the current heuristic for implicit borrows and derefs and determines these based on type inference instead.
* Some false flow is removed in a few tests.
* Improvements to the output of the model generation visible in the test output changes.
* Nothing reported by the DCA.

Rust: Use type inference to insert implicit borrows and derefs

---

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.21.0.rst

These break when the RST is processed.
Escape the backslashes and consistently add inline code blocks.

Docs: Fix escaping in 2.21.0 changelog

---

rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/frameworks/postgres/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected

[DCA](https://github.com/github/codeql-dca-main/issues/28642) looks great; we gain more call edges without affecting performance.

Rust: Type inference for `?` expressions

---

javascript/ql/lib/change-notes/2025-04-30-fastify-all.md
javascript/ql/lib/semmle/javascript/frameworks/Fastify.qll
javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/CodeInjection.expected
javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/HeuristicSourceCodeInjection.expected
javascript/ql/test/query-tests/Security/CWE-094/CodeInjection/fastify.js

Implements modeling of `Fastify`'s `all` method which handles requests across all HTTP methods with a single route definition.

JS: Modeling of `fastify` 

---

misc/scripts/calculate_mrva_totals.py

Use this script if you want to quickly calculate the totals of some query across all the queries in a MRVA run.
For an example of such a query, see e.g. [`python/ql/src/Metrics/Internal/TypeAnnotations.ql`](https://github.com/github/codeql/blob/4141b4fb8a245ffac7323036fb16ec6c9e9e315e/python/ql/src/Metrics/Internal/TypeAnnotations.ql)
The script expects the query to produce an output table of the form
```
| header0  | header1  | header2  | header3  | ...
|----------|----------|----------|----------|----
| message1 | value11  | value12  | value13  | ...
| message2 | value21  | value22  | value23  | ...
...
```
where all of the `values` are numbers. For each `(message, header)` pair, it then calculates the total of all the values in that cell, across all of the repos in the MRVA run.
To use …

Misc: Add script for calculating totals for a MRVA run

---

python/ql/lib/change-notes/2025-04-30-model-send-header.md
python/ql/lib/semmle/python/frameworks/Stdlib.qll
python/ql/test/library-tests/frameworks/stdlib/http_server.py

Requested [here](https://github.com/github/field-security-codeql/issues/194)

python: model `send_header` from `http.server`

---

rust/ql/lib/codeql/rust/frameworks/stdlib/Clone.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/dataflow/modeled/inline-flow.expected
rust/ql/test/library-tests/dataflow/modeled/main.rs
rust/ql/test/utils-tests/modelgenerator/CaptureSummaryModels.expected
rust/ql/test/utils-tests/modelgenerator/option.rs

The [clone method](https://doc.rust-lang.org/std/clone/trait.Clone.html) takes a `&self` parameter, meaning that in terms of data flow it dereferences the receiver argument. Now that we have [a principled way of inserting implicit borrows](https://github.com/github/codeql/pull/19419), it makes sense to strengthen the modeling of the `Clone` trait.
Related, I also updated some expected flow summaries related to `clone`.

Rust: Strengthen modeling of the `Clone` trait

---

docs/codeql/reusables/supported-frameworks.rst
python/ql/lib/change-notes/2025-05-01-hdbcli.md
python/ql/lib/semmle/python/Frameworks.qll
python/ql/lib/semmle/python/frameworks/Hdbcli.qll
python/ql/test/library-tests/frameworks/hdbcli/ConceptsTest.ql
python/ql/test/library-tests/frameworks/hdbcli/pep249.py

Added support for the `hdbcli` PyPI package (SAP HANA DB connector) as a PEP 249 compliant database module.

Python: modeling of `hdbcli`

---

javascript/ql/lib/change-notes/2025-04-30-shelljs.md
javascript/ql/lib/ext/shelljs.model.yml
javascript/ql/lib/semmle/javascript/frameworks/ShellJS.qll
javascript/ql/lib/semmle/javascript/security/dataflow/CleartextLoggingCustomizations.qll
javascript/ql/lib/semmle/javascript/security/dataflow/IndirectCommandInjectionCustomizations.qll
javascript/ql/src/Security/CWE-295/DisablingCertificateValidation.ql
javascript/ql/test/library-tests/frameworks/Shelljs/ShellJS.expected
javascript/ql/test/library-tests/frameworks/Shelljs/tst.js
javascript/ql/test/query-tests/Security/CWE-078/IndirectCommandInjection/IndirectCommandInjection.expected
javascript/ql/test/query-tests/Security/CWE-078/IndirectCommandInjection/actions.js

Added support for additional functions in the `shelljs` and `async-shelljs` libraries:
- `which`: Command location functionality
- `cmd`: Command execution wrapper
- `asyncExec`: Asynchronous command execution
- `env`: Environment variable handling

JS: Modeling of `ShellJS` functions

---

go/extractor/extractor.go
go/extractor/trap/labels.go

It was reported that `codeql/go/ql/test/library-tests/semmle/go/aliases/InterfaceImpls` fails `DB-CHECK` if you add `--check-databases` to the test target of `codeql/go/Makefile`. This turns out to be because that test has a method defined on a receiver which is an alias `Impl6Alias` of the type `Impl6`. This is equivalent to defining the method on `Impl6` directly. There is some code in the extractor which makes sure that objects which are receiver variables get a special label which is the same when seen from different files. That code was not unaliasing the type of the receiver. This PR fixes that, which fixes the db inconsistency.
I do not think this needs any tests. I also don't think it needs a change note.
I also included a minor drive-by refactor. We were defining our own wrapper …

Go: fix database inconsistency when receiver has alias type

---

ruby/ql/integration-tests/query-suite/ruby-code-quality.qls.expected
ruby/ql/src/change-notes/2025-05-12-rb-useless-assignment-to-local-precision-high.md
ruby/ql/src/queries/variables/DeadStoreOfLocal.ql

from `medium` to `high`. It was initially set to `medium` due to the number of alerts observed on the Java top 100 via MRVA. However, after triaging a large number of these, it does indeed seem that they are almost all true positives.

ruby: adjust precision of `rb/useless-assignment-to-local`

---

rust/ql/lib/codeql/rust/elements/AssignmentOperation.qll
rust/ql/lib/codeql/rust/elements/LogicalOperation.qll
rust/ql/lib/codeql/rust/elements/Operation.qll
rust/ql/lib/codeql/rust/elements/internal/BinaryExprImpl.qll
rust/ql/lib/codeql/rust/elements/internal/OperationImpl.qll
rust/ql/lib/codeql/rust/elements/internal/PrefixExprImpl.qll
rust/ql/lib/rust.qll
rust/ql/test/library-tests/operations/Operations.ql
rust/ql/test/library-tests/operations/test.rs

Unify various classes representing operations under a single `Operation` class, providing a single consistent interface (with `getOperatorName()` and `getAnOperand()`) for reasoning about them.
The idea is to get things in order before I follow up with another PR that will add new subclasses, allowing us to find things like the dereference expression (`*`) and comparison operations more easily.

Rust: Add Operation class

---

rust/ql/lib/codeql/rust/elements/LiteralExprExt.qll
rust/ql/lib/codeql/rust/elements/internal/LiteralExprImpl.qll
rust/ql/lib/rust.qll
rust/ql/test/extractor-tests/literal/literal.expected
rust/ql/test/extractor-tests/literal/literal.ql
rust/ql/test/extractor-tests/literal/literal.rs

In preparation for https://github.com/github/codeql/pull/19474.
Eventually we will also want to have predicates for retrieving the literal values, e.g. `int IntegerLiteralExpr.getValue()`, but that is left as future work.

Rust: Add `LiteralExpr` sub classes

---

cpp/ql/lib/change-notes/2025-05-13-range-analysis-infinite-loop.md
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/IRFunction.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/internal/AliasedSSA.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/internal/SSAConstruction.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/IRFunction.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/IRConstruction.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/IRFunction.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SSAConstruction.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SimpleSSA.qll
cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticExprSpecific.qll

As part of the IR SSA/alias analysis we compute the which memory allocations overlap. In https://github.com/github/codeql/pull/17062 we mitigated a problem where, in very large function bodies, the set of overlapping memory allocations was basically a cartesian product.
As a result of this, we don't always have proper SSA information on these large function bodies. It's well-known that even one missing SSA edge can cause the shared range analysis to loop infinitely.
This PR excludes the functions with incomplete SSA information from the new range analysis. Ideally, I would like us to move away from using the IR SSA/alias analysis in the new range analysis library, but that seemed like too big of a task to start right now.
On a customer codebase there were 3 functions in the entire …

C++: Fix infinite range analysis loop on invalid SSA

---

cpp/ql/src/utils/modelgenerator/CaptureContentSummaryModels.ql
cpp/ql/test/library-tests/dataflow/modelgenerator/dataflow/CaptureContentSummaryModels.ql
cpp/ql/test/library-tests/dataflow/modelgenerator/dataflow/CaptureHeuristicSummaryModels.ql
cpp/ql/test/library-tests/dataflow/modelgenerator/dataflow/summaries.cpp
csharp/ql/src/utils/modelgenerator/CaptureContentSummaryModels.ql
csharp/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPartialPath.ql
csharp/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPath.ql
csharp/ql/test/utils/modelgenerator/dataflow/CaptureContentSummaryModels.ql
csharp/ql/test/utils/modelgenerator/dataflow/CaptureHeuristicSummaryModels.ql
csharp/ql/test/utils/modelgenerator/dataflow/Summaries.cs
java/ql/src/utils/modelgenerator/CaptureContentSummaryModels.ql
java/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPartialPath.ql
java/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPath.ql
java/ql/test/utils/modelgenerator/dataflow/CaptureContentSummaryModels.ql
java/ql/test/utils/modelgenerator/dataflow/CaptureHeuristicSummaryModels.ql
java/ql/test/utils/modelgenerator/dataflow/p/FinalClass.java
java/ql/test/utils/modelgenerator/dataflow/p/ImmutablePojo.java
java/ql/test/utils/modelgenerator/dataflow/p/Inheritance.java
java/ql/test/utils/modelgenerator/dataflow/p/InnerClasses.java
java/ql/test/utils/modelgenerator/dataflow/p/MultiPaths.java
java/ql/test/utils/modelgenerator/dataflow/p/MultipleImpl2.java
java/ql/test/utils/modelgenerator/dataflow/p/MultipleImpls.java
java/ql/test/utils/modelgenerator/dataflow/p/ParamFlow.java
rust/ql/src/utils/modelgenerator/CaptureContentSummaryModels.ql
rust/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPartialPath.ql
rust/ql/src/utils/modelgenerator/debug/CaptureSummaryModelsPath.ql
rust/ql/test/utils-tests/modelgenerator/CaptureSummaryModels.ql
shared/mad/codeql/mad/modelgenerator/internal/ModelGeneratorImpl.qll
shared/mad/codeql/mad/modelgenerator/internal/ModelPrinting.qll

Ideally, we want generated flow summaries to be content-sensitive. That is, a summary for a function such as:
```cpp
int read_f(S* s) { return s->f; }
```
should specify that we read the content `f` from `Argument[*0]`.
However, if a function is super complex it may read/write many access paths, and this could cause an explosion in the number of summaries we generate.
To mitigate this, the flow summary generation library [puts various restrictions](https://github.com/github/codeql/blob/f5a295c24e4cbfb9b7e3dfe085de82a1f832b387/shared/mad/codeql/mad/modelgenerator/internal/ModelGeneratorImpl.qll#L798-L809) on which callables receive content-sensitive summaries.
When a content-sensitive summary isn't generated, we currently [fall back](https://github.com/github/codeql/blob/f5a295c24e4cbfb9b7e …

Shared: Generate more value-preserving flow summaries

---

csharp/ql/lib/semmle/code/csharp/frameworks/Format.qll
csharp/ql/src/API Abuse/FormatInvalid.ql
csharp/ql/src/Security Features/CWE-134/UncontrolledFormatString.ql
csharp/ql/src/change-notes/2025-04-10-uncontrolled-format-string.md
csharp/ql/test/query-tests/Security Features/CWE-134/ConsoleUncontrolledFormatString.cs
csharp/ql/test/query-tests/Security Features/CWE-134/UncontrolledFormatString.cs
csharp/ql/test/query-tests/Security Features/CWE-134/UncontrolledFormatString.expected
csharp/ql/test/query-tests/Security Features/CWE-134/UncontrolledFormatString.qlref
csharp/ql/test/query-tests/Security Features/CWE-134/UncontrolledFormatStringBad.cs

This is a follow up of https://github.com/github/codeql/pull/19148
In this PR we
- Re-factor tests to use the inline expectations framework.
- Remove the `hasInsertions` check. This can be removed as methods like `Console.WriteLine(string)` are no longer considered potential format calls (this was fixed in https://github.com/github/codeql/pull/19148).
- Add support for `CompositeFormat.Parse` as this can cause runtime crashes when provided with an invalid format string.
DCA doesn't report any changes to performance or alerts.

C#: Improve precision of `cs/uncontrolled-format-string`.

---

swift/ql/lib/change-notes/2025-05-14-type_value_expr_cfg.md
swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll
swift/ql/test/library-tests/ast/Errors.expected
swift/ql/test/library-tests/ast/Missing.expected
swift/ql/test/library-tests/ast/PrintAst.expected
swift/ql/test/library-tests/ast/cfg.swift
swift/ql/test/library-tests/controlflow/graph/Cfg.expected
swift/ql/test/library-tests/controlflow/graph/cfg.swift
swift/tools/qltest.sh

We do see errors  about missing types from type reprs, which is not ideal. However I propose to postpone looking at that when type value expressions get out from being experimental.
Also, changed `qltest.sh` to be more liberal about the location of special option comments in the test source code.

Swift: add new `TypeValueExpr` to CFG

---

go/ql/lib/semmle/go/controlflow/IR.qll
go/ql/test/library-tests/semmle/go/IR/test.expected
go/ql/test/library-tests/semmle/go/IR/test.go
go/ql/test/library-tests/semmle/go/IR/test.ql

I saw a minor edge case bug (`CallExpr.getTarget()` is not defined when we are calling a variable - we can instead use `CallExpr.getCalleeType()` when we just want the type of the target), but it turned out to be in redundant code, so I expanded our tests to confirm this and deleted the redundant code.

Go: Remove redundant code in `IR::ExtractTupleElementInstruction.getResultType()` and expand tests

---

ruby/ql/lib/change-notes/2025-05-02-ruby-printast-order-fix.md
ruby/ql/lib/codeql/ruby/printAst.qll
ruby/ql/test/library-tests/ast/Ast.expected

Real parents can have synthesized children, so always assigning index 0 leads to nondeterminism in graph output.

Ruby printAst: fix order for synth children of real parents

---

csharp/ql/lib/semmle/code/csharp/frameworks/system/collections/Generic.qll
csharp/ql/src/Likely Bugs/HashedButNoHash.ql
csharp/ql/src/change-notes/2025-05-15-gethashcode-is-not-defined.md
csharp/ql/test/query-tests/Likely Bugs/HashedButNoHash/HashedButNoHash.cs
csharp/ql/test/query-tests/Likely Bugs/HashedButNoHash/HashedButNoHash.expected
csharp/ql/test/query-tests/Likely Bugs/HashedButNoHash/HashedButNoHash.qlref

Even though there is a general compiler warning [CS0659](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0659) for all types overriding `Equals` but not `GetHashCode` - this query only targets expressions of types, where it is more likely to have an impact that `GetHashCode()` is not overridden.

C#: Improve the query `cs/gethashcode-is-not-defined`.

---

cpp/ql/src/utils/modelgenerator/internal/CaptureModels.qll

@jketema noticed that there are a few summaries (for OpenSSL specifically) in https://github.com/github/codeql/pull/19492 that are from test functions. This PR excludes model generation for functions inside folders that match `%test%`.
Care is needed to not exclude our own tests, though, as the summary tests are located in `cpp/ql/test/library-tests/dataflow/modelgenerator/dataflow`. So we explicitly allow that directory.
I tried to regenerate the OpenSSL models with these changes on top of https://github.com/github/codeql/pull/19492 and compare the changes: https://www.diffchecker.com/z6iyKLAU/ (this isn't super readable, but I've manually checked most of the excludes functions and they do indeed belong to tests)

C++: Exclude tests in model generation

---

cpp/ql/lib/experimental/quantum/OpenSSL/Operations/EVPCipherOperation.qll
java/ql/lib/experimental/quantum/JCA.qll

Adds modeling for EVP cipher update calls, flowing their inputs through to EVP cipher final calls. 
Fixes a bug in JCA where intermediate cipher calls (updates) were being modeled as cipher operation instances.

Quantum: Expand OpenSSL cipher modeling and fix JCA false reporting of intermediate calls

---

cpp/ql/lib/utils/test/dataflow/FlowTestCommon.qll

`hasLocationInfo` on dataflow nodes has been deprecated for over a year.
Deprecated in https://github.com/github/codeql/pull/15853

C++: Do not use deprecated `hasLocationInfo` in `FlowTestCommon`

---

cpp/ql/lib/change-notes/2025-05-16-array-aggregate-literals.md
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ExprNodes.qll
cpp/ql/test/library-tests/dataflow/asExpr/test.cpp
cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/consts/NonConstantFormat.expected
cpp/ql/test/query-tests/Security/CWE/CWE-319/UseOfHttp/UseOfHttp.expected

This PR fixes the same problem as https://github.com/github/codeql/pull/19501, but for `ArrayAggregateLiterals`. Unlike in the `ArrayAggregateLiterals` case we don't have a post-update node to use to represent the "fully initialized literal" since array writes aren't handled using post-update nodes. So we can't do quite the same in this case.
In https://github.com/github/codeql/pull/19501 I said that we should fix the `ArrayAggregateLiterals` by making use of post-update nodes for array writes. However, that's a _really_ hard task that I don't actually feel like tackling right now 😅
However, we can do something that's almost as good: We can use the last `Store` instruction as the dataflow node for which `node.asExpr() instanceof ArrayAggregateLiteral` should hold. This is because, at this …

C++: Make `node.asExpr() instanceof ArrayAggregateLiteral` satisfiable

---

cpp/ql/lib/change-notes/2025-05-18-2025-May-outdated-deprecations.md
cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
cpp/ql/lib/semmle/code/cpp/security/Security.qll
cpp/ql/lib/semmle/code/cpp/security/SecurityOptions.qll
swift/ql/lib/change-notes/2025-05-18-2025-May-outdated-deprecations.md
swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll
swift/ql/lib/codeql/swift/dataflow/FlowSummary.qll
swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPublic.qll
swift/ql/lib/codeql/swift/security/WeakSensitiveDataHashingQuery.qll

Cherry-picked from https://github.com/github/codeql/pull/19504. Mostly because the related internal C++ tests did get removed, so I don't want the keep the C++ deprecations around for too long without test coverage.

C++/Swift: delete outdated deprecations

---

cpp/ql/lib/experimental/quantum/OpenSSL/OpenSSL.qll
cpp/ql/lib/experimental/quantum/OpenSSL/Operations/EVPCipherOperation.qll
cpp/ql/lib/experimental/quantum/OpenSSL/Operations/EVPHashOperation.qll

Adds digest modeling for 'update' and 'final' calls in openssl.

Crypto: Model OpenSSL intermediate digest operations

---

rust/ql/lib/codeql/files/FileSystem.qll
rust/ql/lib/codeql/rust/elements/internal/AstNodeImpl.qll
rust/ql/lib/codeql/rust/elements/internal/LocatableImpl.qll
rust/ql/lib/codeql/rust/elements/internal/LocationImpl.qll
rust/ql/lib/codeql/rust/elements/internal/MacroCallImpl.qll
rust/ql/lib/codeql/rust/frameworks/stdlib/Stdlib.qll
rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/lib/utils/test/PathResolutionInlineExpectationsTest.qll
rust/ql/test/TestUtils.qll
rust/ql/test/library-tests/path-resolution/my.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected
rust/ql/test/library-tests/path-resolution/path-resolution.ql
rust/ql/test/library-tests/type-inference/type-inference.expected
rust/ql/test/library-tests/type-inference/type-inference.ql

https://github.com/github/codeql/pull/19506 follow-up.

Rust: Follow-up work to make path resolution and type inference tests pass again

---

cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/AlgToAVCFlow.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/BlockAlgorithmInstance.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/CipherAlgorithmInstance.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/EllipticCurveAlgorithmInstance.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/HashAlgorithmInstance.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/KnownAlgorithmConstants.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/OpenSSLAlgorithmInstanceBase.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/OpenSSLAlgorithmInstances.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmInstances/PaddingAlgorithmInstance.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/CipherAlgorithmValueConsumer.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/DirectAlgorithmValueConsumer.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/EllipticCurveAlgorithmValueConsumer.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/HashAlgorithmValueConsumer.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/OpenSSLAlgorithmValueConsumerBase.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/OpenSSLAlgorithmValueConsumers.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/PaddingAlgorithmValueConsumer.qll
cpp/ql/lib/experimental/quantum/OpenSSL/Operations/EVPCipherInitializer.qll
cpp/ql/lib/experimental/quantum/OpenSSL/Operations/EVPCipherOperation.qll
cpp/ql/lib/experimental/quantum/OpenSSL/Operations/EVPHashOperation.qll
cpp/ql/lib/experimental/quantum/OpenSSL/Operations/OpenSSLOperationBase.qll
java/ql/lib/experimental/quantum/JCA.qll
shared/quantum/codeql/quantum/experimental/Model.qll

Adds algorithm instance and consumers for openssl elliptic curves.

Crypto: Add OpenSSL elliptic curve algorithm instances and consumers

---

.github/workflows/go-tests-other-os.yml

Seems like `windows-latest-xl` is not available any more, leading to jobs waiting endlessly (see for example https://github.com/github/codeql/actions/runs/15109425790). This should unblock CI, but longer term we should consider doing what other languages do (i.e. run tests from the internal repo).

Go: move to standard windows runner

---

rust/extractor/src/qltest.rs

The target file created by `cargo check` was causing problems in language tests.
We might want to also ignore `target` by default in the production indexing, but I'll leave that for further discussion.

Rust: ignore `target` in `qltest`

---

rust/ql/lib/codeql/rust/internal/Type.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected

This PR adds type inference for _all_ non-overloadable operators in Rust. It turns out that there are only three such operators. `&&` and `||` (which are not overloadable for short-circuiting reasons) and `=`.
The assignment operator evaluates to unit, and as we didn't have a unit type I added one.

Rust: Type inference for non-overloadable operators

---

cpp/ql/lib/experimental/quantum/Language.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/OpenSSLAlgorithmValueConsumers.qll
cpp/ql/lib/experimental/quantum/OpenSSL/AlgorithmValueConsumers/PKeyAlgorithmValueConsumer.qll

Value consumer modeling for PKEY alg consumers in openssl.

Quantum: Add OpenSSL PKEY algorithm value consumers.

---

rust/ql/lib/codeql/rust/internal/TypeInference.qll
shared/typeinference/codeql/typeinference/internal/TypeInference.qll

This PR speeds up type inference by
1. avoiding the `strictcount` aggregate,
2. avoiding a run-time negation that can be done at compile-time, and
3. avoiding checking for type path lengths when deconstructing existing type paths that have already been checked.
[DCA](https://github.com/github/codeql-dca-main/issues/28908) shows an impressive 65 % analysis time speedup on `rust-lang/rust`.

Rust: Improve performance of type inference

---

javascript/ql/lib/semmle/javascript/NPM.qll
javascript/ql/src/NodeJS/UnresolvableImport.ql
javascript/ql/test/library-tests/NPM/tests.expected

Fixes a bad join order in `PackageJson.getPackageName()` for the case where a package is nested within another package.
Also `NpmPackage.getAFile()` had a discrepancy between its documentation, which states that files are only associated with their nearest enclosing package, but it actually associated files with all their enclosing packages. It now does what it says in the QLDoc. One of the queries that depended on the old behaviour has been updated accordingly.

JS: More efficient nested package naming

---

rust/ql/lib/codeql/rust/internal/Type.qll
rust/ql/lib/codeql/rust/internal/TypeMention.qll

I just realized that the type for `impl` blocks is in fact unused after the recent changes to method resolution.

Rust: Remove unused impl type

---

java/ql/src/Performance/StringReplaceAllWithNonRegex.md
java/ql/test/query-tests/StringReplaceAllWithNonRegex/Test.java

As suggested in [this comment](https://github.com/github/codeql/pull/19115/files#r2041673782).

Java: Add test showing correct usage

---

java/ql/lib/change-notes/2025-05-22-spring-request-mapping-value.md
java/ql/lib/semmle/code/java/frameworks/spring/SpringController.qll
java/ql/test/library-tests/frameworks/spring/controller/RequestController.ql
java/ql/test/library-tests/frameworks/spring/controller/Test.java

This supersedes https://github.com/github/codeql/pull/19512.

Java: Fix SpringRequestMappingMethod URL Extraction #2

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
java/ql/lib/semmle/code/java/controlflow/Guards.qll
java/ql/lib/semmle/code/java/dataflow/internal/SsaImpl.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/sharedlib/Ssa.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
shared/dataflow/codeql/dataflow/VariableCapture.qll
shared/ssa/change-notes/2025-05-23-guards-interface.md
shared/ssa/codeql/ssa/Ssa.qll

For languages without a guards implication logic, `hasBranchEdge` and `controlsBranchEdge` is the same thing, but libraries like SSA should distinguish between them. This _might_ theoretically improve barrier guards a bit for Java, but more importantly this prepares us a bit for the introduction of a shared Guards library.

SSA: Distinguish between has and controls branch edge.

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/FlowSummaryImpl.qll
cpp/ql/test/library-tests/dataflow/models-as-data/tests.cpp
shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll

In https://github.com/github/codeql/pull/19563 @jketema is adding flow sources for (among other things) [GetCommandLineA](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinea) which should have the following MaD specification:
```yml
["", "", False, "GetCommandLineA", "", "", "ReturnValue[*]", "local", "manual"]
```
(because it's not the pointer returned by `GetCommandLineA` that's user controlled - it's the data that's pointed to!)
However, we noticed that this is not parsed correctly by the current implementation of `SourceSinkInterpretation::interpretOutput` since it only has a case for `getStandardReturnValueKind` (and `ReturnValue` is the standard return value kind, not `ReturnValue[*]`).
This PR fixes that missing case, and I've checked that …

Shared/C++: Handle non-standard return values in MaD flow sources/sinks

---

rust/ql/lib/codeql/rust/elements/internal/CallExprImpl.qll
rust/ql/lib/codeql/rust/elements/internal/MethodCallExprImpl.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/dataflow/global/inline-flow.expected
rust/ql/test/library-tests/dataflow/global/main.rs
rust/ql/test/library-tests/dataflow/global/viableCallable.expected
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected
rust/ql/test/library-tests/type-inference/type-inference.ql

This PR adds resolution for function calls to trait methods `ATrait::some_method(obj, ...)`.
Key changes:
- Introduce an abstract `MethodCall` abstract class that is extended by the different types of expressions that can lead to method calls. Later this class can also be extended by overloaded operators that perform method calls.
- Added a `methodCandidateTrait` predicate, which is similar to the existing `methodCandidate` predicate but which also takes a trait that the method should come from. `potentialInstantiationOf` now accounts both for method calls that target a specific trait.

Rust: Resolve function calls to traits methods

---

javascript/ql/src/codeql-suites/javascript-security-and-quality.qls

This PR explicitly hardcodes all the quality query IDs within the `JavaScript` security and quality suite. Similar to #19245

JS: Explicitly Filter Quality Queries for Inclusion in `Security-and-Quality`

---

go/extractor/util/registryproxy.go

This should resolve https://github.com/github/codeql-action/issues/2909 after we didn't catch this in https://github.com/github/codeql/pull/19248. If the environment variables are set, but contain the empty string, then we treat those empty strings as meaningful values, even though they are not.

Go: Explicitly check whether proxy env vars are empty

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll

Needed in order to resolve paths inside the Core library itself, such as resolving `Option` at https://github.com/rust-lang/rust/blob/95a2212587f1b8500af1ac630322b0cb2e030c61/library/core/src/iter/traits/iterator.rs#L373.

Rust: Also include prelude path resolution in Core

---

go/Makefile
go/extractor/extractor.go
go/ql/test/query-tests/definitions/definitions.expected
go/ql/test/query-tests/definitions/greet.go

This PR adds the following flags when we run tests: `--fail-on-trap-errors`, `--check-undefined-labels`, `--check-unused-labels`, `--check-repeated-labels`, `--check-redefined-labels`, `--check-use-before-definition`. There are also two extractor fixes to make tests pass with these flags:
1. Avoid making unused labels in certain situations.
2. Fix a db inconsistency on Windows by making the Go extractor use "C:/" for the drive root instead of "C:", so it matches up with the XML extractor (which we use for HTML files).

Go: Check more things while running tests

---

rust/extractor/src/translate/base.rs

Now https://github.com/github/codeql/pull/19572 is merged it should be possible to remove the workaround and re-enable attribute macro expansion on library files. Reverts https://github.com/github/codeql/commit/df99e06c816183b01c9cdb56521e20bdaf4cb7b6

Rust: re-enable attribute macro expansion in library mode

---

rust/ql/lib/codeql/rust/elements/internal/BinaryExprImpl.qll
rust/ql/lib/codeql/rust/elements/internal/OperationImpl.qll
rust/ql/lib/codeql/rust/elements/internal/PrefixExprImpl.qll
rust/ql/lib/codeql/rust/elements/internal/RefExprImpl.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected

Implements type inference for overloaded operators in Rust.
Note, that this does _not_ implement the data flow side of things.
Shoutout to Copilot :copilot: for helping out with generating the tests 💪

Rust: Type inference for operator overloading

---

python/ql/lib/semmle/python/frameworks/Pandas.qll
python/ql/src/change-notes/2025-05-26-pandas-sqli-sinks.md
python/ql/test/library-tests/frameworks/pandas/dataframe_query.py

Pandas has a `read_sql` sink, which allows for executing raw SQL queries with untrusted input. `read_sql` is a convenience method, that dispatches the query either to `read_sql_table` or `read_sql_query`. Please note that `read_sql_table` is not vulnerable to SQLi, but `read_sql_query` is.
Note that instead of adding new tests, I edited the previous tests, because they contained the vulnerable `read_sql` and `read_sql_query` method, which made them show up as failed.

Python: Add Pandas SQLi sinks

---

javascript/ql/lib/change-notes/2025-05-30-url-package-taint-step.md
javascript/ql/lib/semmle/javascript/security/dataflow/RequestForgeryCustomizations.qll
javascript/ql/test/query-tests/Security/CWE-918/RequestForgery.expected
javascript/ql/test/query-tests/Security/CWE-918/serverSide.js

This PR enhances the request forgery (SSRF) detection by adding support for tracking taint flow through the `URL` constructor.

JS: Add URL constructor taint tracking for request forgery

---

.github/workflows/build-ripunzip.yml
.github/workflows/csharp-qltest.yml

The rip-unzip build workflow is using slightly older runners to ensure being runnable on supported platforms, though admittedly I don't know whether that can be an issue on windows.

CI: remove deprecated `windows-2019` usage

---

shared/quantum/codeql/quantum/experimental/Model.qll

This is a small update to Model.qll which adds signature artifact nodes and signature artifact consumers to signature verify operation nodes.

Quantum: Added signature input nodes to signature verify operation nodes

---

actions/ql/lib/codeql/actions/Ast.qll

`class Env` was previously abstract with no concrete descendants, so user queries like `any(Env e | ...)` would never produce results.
In the JS library the corresponding class derived from `YamlNode` and has concrete descendants representing workflow-, job- and step-level `env` nodes. However these are dubiously useful since you can always just use `any(Step s).getEnv()` to achieve the same result. Since `EnvImpl` already fully characterises an `env` node, I simply make the class concrete.

Actions: Make `Env` non-abstract

---

.github/workflows/validate-change-notes.yml

@cklin not release-blocking but a coverage improvement we might as well include sooner.

CI: Expand list of packs/languages for change note validation

---

csharp/ql/integration-tests/posix/query-suite/csharp-code-quality.qls.expected
csharp/ql/src/Performance/StringConcatenationInLoop.ql

This PR is adding the `cs/string-concatenation-in-loop` query to the code-quality suite. I've ran the query on MRVA and then manually checked autofix suggestions. The results and the fixes are sensible.

Add `cs/string-concatenation-in-loop` to the quality suite

---

csharp/ql/integration-tests/posix/query-suite/csharp-code-quality.qls.expected
csharp/ql/lib/semmle/code/csharp/dataflow/Nullness.qll
csharp/ql/lib/semmle/code/csharp/frameworks/system/Diagnostics.qll
csharp/ql/src/CSI/NullAlways.ql
csharp/ql/src/CSI/NullMaybe.ql
csharp/ql/src/change-notes/2025-06-03-dereferece-extension-method.md
csharp/ql/test/query-tests/Nullness/A.cs
csharp/ql/test/query-tests/Nullness/Assert.cs
csharp/ql/test/query-tests/Nullness/B.cs
csharp/ql/test/query-tests/Nullness/C.cs
csharp/ql/test/query-tests/Nullness/D.cs
csharp/ql/test/query-tests/Nullness/E.cs
csharp/ql/test/query-tests/Nullness/F.cs
csharp/ql/test/query-tests/Nullness/Forwarding.cs
csharp/ql/test/query-tests/Nullness/GuardedString.cs
csharp/ql/test/query-tests/Nullness/Implications.expected
csharp/ql/test/query-tests/Nullness/NullAlways.expected
csharp/ql/test/query-tests/Nullness/NullAlways.qlref
csharp/ql/test/query-tests/Nullness/NullAlwaysBad.cs
csharp/ql/test/query-tests/Nullness/NullMaybe.expected
csharp/ql/test/query-tests/Nullness/NullMaybe.qlref
csharp/ql/test/query-tests/Nullness/NullMaybeBad.cs
csharp/ql/test/query-tests/Nullness/Params.cs
csharp/ql/test/query-tests/Nullness/StringConcatenation.cs
csharp/ql/test/query-tests/Nullness/options
csharp/ql/test/resources/stubs/Library.cs

In this PR we do the following for `cs/dereferenced-value-is-always-null` and `cs/dereferenced-value-may-be-null`.
- Change the class of de-referenced expressions: When calling a library extension method where the `this` parameter is a nullable type, we now assume that the null may happen in the extension method itself (this is at least common for the usage of testing frameworks, which reports a high amount of false positives related to the use of such extension methods).
- Remove the explicit type requirements on Debug.Assert methods (they are trivially true). They cause issues when extraction have broken types - and the change doesn't affect the methods that match the predicate when types are healthy.
- Add the queries of the Code Quality suite.
- Convert the tests to use inline …

C#: Improve `cs/dereference-*` queries and add to the Code Quality suite.

---

rust/ql/lib/codeql/rust/security/regex/RegexInjectionExtensions.qll

Update `RegexInjectionExtensions.qll` to use `getCanonicalPath` rather than `getResolvedPath` + `getResolvedCrateOrigin`.
@hvitved please confirm that this is the right direction we want to move in.

Rust: Update RegexInjectionExtensions to use getCanonicalPath.

---

javascript/ql/integration-tests/query-suite/javascript-code-quality.qls.expected
javascript/ql/src/LanguageFeatures/TemplateSyntaxInStringLiteral.ql
javascript/ql/src/change-notes/2025-06-12-string-interpolation.md
javascript/ql/src/change-notes/2025-06-12-template-syntax-metadata.md
javascript/ql/test/query-tests/LanguageFeatures/TemplateSyntaxInStringLiteral/TemplateSyntaxInStringLiteral.expected
javascript/ql/test/query-tests/LanguageFeatures/TemplateSyntaxInStringLiteral/TemplateSyntaxInStringLiteral.js

This pull request adds the query `js/template-syntax-in-string-literal` to the Code Quality suite. The problem that the query aims to highlight is straightforward for `autofix` to fix.
While running MRVA, a few patterns of false positives were observed. Note that all of these cases are rare:
-   Packages like [yup](https://www.npmjs.com/package/yup) may produce false positives. Yup uses special variables such as `${min}`, `${max}`, `${path}`, `${less}`, etc., which are correctly interpolated, even when included inside single (`''`) or double (`""`) quotes and passed to the respective yup methods. These false positives are uncommon, as they only occur when there is a variable with the exact same name in the current scope.
- ~~In certain [test framework …

JS: Promote `js/template-syntax-in-string-literal` to the Code Quality suite.

---

.github/workflows/python-tooling.yml
.pre-commit-config.yaml
misc/scripts/models-as-data/bulk_generate_mad.py

Turns out this is important for the black formatting tool to work correctly. The formatting won't generally change between python versions (it only depends on `black`'s version), but the formatted code needs to be parseable by the system python version. One script uses
```python
def foo[T](x: T) -> T:
```
syntax, which is only supported in Python 3.12 and later.
Running `pre-commit` will now require a python 3.12 installation (which is already what we mandate for internal developer environment setup). The error in case of absence of such a version is pretty clear though.

CI: fix python version

---

ql/ql/src/codeql_ql/ast/Ast.qll
ql/ql/src/queries/overlay/InlineOverlayCaller.ql

This PR adds a QL-for-QL query to warn about possible non-inlining across the overlay frontier for possibly local non-private inline predicates. It will be used in tandem with [a script](https://github.com/github/codeql/pull/19631) to automatically add overlay annotations to files without existing overlay annotations. Once locality annotations have been added to a file, this query takes over responsibility for warning about possible non-inlining.
Due to a limitation of the tree-sitter-ql grammar with respect to annotations on file-level module declarations (i.e., `module;`), the heuristic for determining whether an inline predicate might be local is very crude: if the file contains any `overlay[local]` or `overlay[local?]` annotations. 
For …

Overlay: Add QL for QL query to warn about possible non-inlining across overlay frontier

---

csharp/ql/integration-tests/posix/query-suite/csharp-code-quality.qls.expected
csharp/ql/src/Likely Bugs/HashedButNoHash.ql

In this PR we add the query `cs/gethashcode-is-not-defined` to the Code Quality suite.
It is worth mentioning that
- There is compiler warning [CS0659](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0659?f1url=%3FappId%3Droslyn%26k%3Dk(CS0659)) which reports all types where the `Equals` method is overridden, but where the `GetHashCode` is not. Our query is a bit more conservative in its approach by only reporting such types, if they are used in a hashing context.
- Only very few cases found via MRVA, but it looks like they would have been good to fix.
- There wasn't any triage data for this query. Created some examples and ran autofix locally - it provided good fix suggestions (in all cases it correctly applied `HashCode.Combine` to create a decent hash function).

C#: Add `cs/gethashcode-is-not-defined` to the Code Quality suite.

---

csharp/ql/lib/semmle/code/csharp/Generics.qll
csharp/ql/lib/semmle/code/csharp/commons/QualifiedName.qll

Avoids a combinatorial explosion when type arguments are not unique.

C#: Handle non-unique type arguments when computing generics strings

---

javascript/ql/lib/change-notes/2025-06-16-serialize-js.md
javascript/ql/lib/semmle/javascript/JsonParsers.qll
javascript/ql/lib/semmle/javascript/JsonStringifiers.qll
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.expected
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXssWithCustomSanitizer.expected
javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/tst2.js

Enhances the XSS analysis to track taint through `serialize-javascript` calls when tainted data is passed via object properties.

JS: Improve XSS detection for `serialize-javascript` with tainted objects

---

cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/TranslatedCall.qll
cpp/ql/test/library-tests/controlflow/guards-ir/tests.expected
cpp/ql/test/library-tests/controlflow/guards/GuardsControl.expected
cpp/ql/test/library-tests/controlflow/guards/GuardsEnsure.expected
cpp/ql/test/library-tests/ir/ir/aliased_ir.expected
cpp/ql/test/library-tests/ir/ir/raw_ir.expected

Same as https://github.com/github/codeql/pull/19746, but for C++ exceptions (whereas https://github.com/github/codeql/pull/19746 was for SEH exceptions).

C++: Add exception edges out of calls inside `try` statements

---

actions/ql/lib/codeql/actions/security/OutputClobberingQuery.qll
actions/ql/lib/codeql/actions/security/RequestForgeryQuery.qll
actions/ql/lib/codeql/actions/security/SecretExfiltrationQuery.qll
actions/ql/src/Models/CompositeActionsSinks.ql
actions/ql/src/Models/CompositeActionsSources.ql
actions/ql/src/Models/CompositeActionsSummaries.ql
actions/ql/src/Models/ReusableWorkflowsSinks.ql
actions/ql/src/Models/ReusableWorkflowsSources.ql
actions/ql/src/Models/ReusableWorkflowsSummaries.ql

An auto-generated patch that enables diff-informed data flow in the obvious cases.
Builds on https://github.com/github/codeql/pull/18346 and https://github.com/github/codeql-patch/pull/88

Actions: mass enable diff-informed data flow

---

cpp/ql/lib/experimental/semmle/code/cpp/security/PrivateCleartextWrite.qll
cpp/ql/src/Likely Bugs/Conversion/CastArrayPointerArithmetic.ql
cpp/ql/src/Likely Bugs/Memory Management/NtohlArrayNoBound.qll
cpp/ql/src/Security/CWE/CWE-114/UncontrolledProcessOperation.ql
cpp/ql/src/Security/CWE/CWE-129/ImproperArrayIndexValidation.ql
cpp/ql/src/Security/CWE/CWE-134/UncontrolledFormatString.ql
cpp/ql/src/Security/CWE/CWE-190/IntegerOverflowTainted.ql
cpp/ql/src/Security/CWE/CWE-497/ExposedSystemData.ql
cpp/ql/src/Security/CWE/CWE-497/PotentiallyExposedSystemData.ql
cpp/ql/src/Security/CWE/CWE-611/XXE.ql
cpp/ql/src/experimental/Security/CWE/CWE-078/WordexpTainted.ql
cpp/ql/src/experimental/Security/CWE/CWE-190/AllocMultiplicationOverflow.ql

An auto-generated patch that enables diff-informed data flow in the obvious cases.
Builds on https://github.com/github/codeql/pull/18342 and https://github.com/github/codeql-patch/pull/88

C++: mass enable diff-informed data flow

---

swift/ql/lib/codeql/swift/security/CleartextLoggingQuery.qll
swift/ql/lib/codeql/swift/security/CleartextTransmissionQuery.qll
swift/ql/lib/codeql/swift/security/CommandInjectionQuery.qll
swift/ql/lib/codeql/swift/security/ConstantPasswordQuery.qll
swift/ql/lib/codeql/swift/security/ConstantSaltQuery.qll
swift/ql/lib/codeql/swift/security/ECBEncryptionQuery.qll
swift/ql/lib/codeql/swift/security/HardcodedEncryptionKeyQuery.qll
swift/ql/lib/codeql/swift/security/InsecureTLSQuery.qll
swift/ql/lib/codeql/swift/security/InsufficientHashIterationsQuery.qll
swift/ql/lib/codeql/swift/security/PathInjectionQuery.qll
swift/ql/lib/codeql/swift/security/PredicateInjectionQuery.qll
swift/ql/lib/codeql/swift/security/SqlInjectionQuery.qll
swift/ql/lib/codeql/swift/security/StaticInitializationVectorQuery.qll
swift/ql/lib/codeql/swift/security/StringLengthConflationQuery.qll
swift/ql/lib/codeql/swift/security/UncontrolledFormatStringQuery.qll
swift/ql/lib/codeql/swift/security/UnsafeJsEvalQuery.qll
swift/ql/lib/codeql/swift/security/UnsafeUnpackQuery.qll
swift/ql/lib/codeql/swift/security/WeakPasswordHashingQuery.qll
swift/ql/lib/codeql/swift/security/WeakSensitiveDataHashingQuery.qll
swift/ql/lib/codeql/swift/security/XXEQuery.qll
swift/ql/lib/codeql/swift/security/regex/RegexInjectionQuery.qll

An auto-generated patch that enables diff-informed data flow in the obvious cases.
Builds on https://github.com/github/codeql/pull/18343 and https://github.com/github/codeql-patch/pull/88

Swift: mass enable diff-informed data flow

---

csharp/ql/src/Security Features/CWE-327/DontInstallRootCert.ql

Stacks on top of earlier PR: https://github.com/github/codeql/pull/19659
Uses patch from: https://github.com/github/codeql-patch/pull/88/commits/ec5681e740c18c792443099fb3e413446616a0ee 
Adds `getASelected{Source,Sink}Location() { none() }` override to queries that select a dataflow source or sink as a location, but not both.

C#: mass-enable diff-informed queries phase 2 - `getASelected{Source,Sink}Location() { none() }`

---

swift/ql/lib/codeql/swift/security/ConstantPasswordQuery.qll
swift/ql/lib/codeql/swift/security/InsufficientHashIterationsQuery.qll
swift/ql/lib/codeql/swift/security/StaticInitializationVectorQuery.qll
swift/ql/lib/codeql/swift/security/StringLengthConflationQuery.qll
swift/ql/lib/codeql/swift/security/UnsafeJsEvalQuery.qll
swift/ql/lib/codeql/swift/security/UnsafeUnpackQuery.qll

Stacks on top of earlier PR: https://github.com/github/codeql/pull/19659
Uses patch from: https://github.com/github/codeql-patch/pull/88/commits/ec5681e740c18c792443099fb3e413446616a0ee 
Adds `getASelected{Source,Sink}Location() { none() }` override to queries that select a dataflow source or sink as a location, but not both.

Swift: mass-enable diff-informed queries phase 2 - `getASelected{Source,Sink}Location() { none() }`

---

java/ql/lib/semmle/code/java/security/ArbitraryApkInstallationQuery.qll
java/ql/lib/semmle/code/java/security/HardcodedCredentialsApiCallQuery.qll
java/ql/lib/semmle/code/java/security/HardcodedCredentialsSourceCallQuery.qll
java/ql/lib/semmle/code/java/security/HttpsUrlsQuery.qll
java/ql/lib/semmle/code/java/security/InsecureBasicAuthQuery.qll
java/ql/lib/semmle/code/java/security/SensitiveUiQuery.qll
java/ql/lib/semmle/code/java/security/UnsafeAndroidAccessQuery.qll

An auto-generated patch that enables diff-informed data flow in the obvious cases.
- Adds `observeDiffInformedIncrementalMode() { any() }` override to queries that don't select a location other than a dataflow source or sink.
- Adds `getASelected{Source,Sink}Location() { none() }` override to queries that select a dataflow source or sink as a location, but not both.
Java has previously had a round of diff-informed query enablements, but it seems some queries were missed in the first round.

Java: mass enable diff-informed data flow + `none()` overrides

---

rust/extractor/src/config.rs
rust/extractor/src/qltest.rs
rust/extractor/src/qltest_cargo.mustache
rust/ql/test/.gitignore
rust/ql/test/query-tests/security/CWE-022/options.yml
rust/ql/test/query-tests/security/CWE-022/rust-toolchain.toml
rust/ql/test/query-tests/security/CWE-770/options.yml
rust/ql/test/query-tests/security/CWE-770/rust-toolchain.toml
rust/ql/test/query-tests/security/CWE-825/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/query-tests/security/CWE-825/options.yml
rust/ql/test/query-tests/security/CWE-825/rust-toolchain.toml

Rather than fixing the version separately for each test, we can just request to use a nightly in the `options.yml` file, with the specific version hard-coded in `qltest.rs`. We can update it if we need to.
It's better to have a single nightly version for all tests that require it, in order to avoid downloading more versions than necessary.
Also removed some uneeded cargo check requests, as that flag is true by default on all tests.

Rust: fix nightly toolchain version for tests using it

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/test/library-tests/path-resolution/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/library-tests/path-resolution/main.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected

For example, `use std::{self as ztd}` introduces `ztd` as an alias for `std`.

Rust: Path resolution for `crate::{self as foo}`

---

javascript/ql/lib/semmle/javascript/frameworks/Fastify.qll

Fastify moved from fastify.io to fastify.dev at the end of 2023.
fastify.io currently redirects to fastify.dev, but this may change in the future. :)

JS: Update Fastify tld

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/tools/builtins/await.rs
shared/typeinference/codeql/typeinference/internal/TypeInference.qll

This PR refactors the shared type inference library, it untangles the logic for figuring out whether a type tree implements a trait, such that we can expose that logic from the shared library. This is done by a new module called `SatisfiesConstraintInput`. This module can be used to figure out if and how the type of an AST nodes (or more generally any `HasTypeTree`) implements a given trait.
----------------------------
I believe we can use this module for quite a few things in Rust:
* In `for` loops like `for i of e { ... }` where the type of `i` depends on how `e` implements the `IntoIterator` trait.
* Method resolution for trait implementations on type parameters. For an implementation like
```rust
impl<T: Trait1> Trait2 for T { fn a_method(...) ... }
```
and a method call like
```rust …
```

Rust: Add `SatisfiesConstraintInput` module in shared type inference

---

ruby/extractor/src/extractor.rs
ruby/ql/lib/codeql/ruby/ast/internal/TreeSitter.qll
shared/tree-sitter-extractor/src/generator/mod.rs
shared/tree-sitter-extractor/src/generator/ql.rs
shared/tree-sitter-extractor/src/generator/ql_gen.rs

Stacked on top of https://github.com/github/codeql/pull/19684

Ruby: generate overlay discard predicates

---

java/ql/lib/semmle/code/java/controlflow/Guards.qll
shared/controlflow/codeql/controlflow/Guards.qll

A minor refactor in the interface to the Guards library. This is necessary to facilitate instantiation in C# where a single expression might correspond to multiple equality checks. E.g. `x.compareTo(y) == 0` is a single expression that both acts as an equality check between the comparison and 0, and `x` and `y`.

Guards: Refactor EqualityTest interface.

---

java/ql/lib/semmle/code/java/ControlFlowGraph.qll
java/ql/test/query-tests/Nullness/C.java
java/ql/test/query-tests/Nullness/NullMaybe.expected
java/ql/test/query-tests/RangeAnalysis/A.java
java/ql/test/query-tests/RangeAnalysis/ArrayIndexOutOfBounds.expected

Follow-up for https://github.com/github/codeql/pull/19573 to fix the small issue with asserts.

Java: Fix assert CFG by properly tagging the false successor.

---

java/ql/integration-tests/java/query-suite/java-code-quality-extended.qls.expected
java/ql/integration-tests/java/query-suite/java-code-quality.qls.expected
java/ql/src/Likely Bugs/Concurrency/ScheduledThreadPoolExecutorZeroThread.md
java/ql/src/Likely Bugs/Concurrency/ScheduledThreadPoolExecutorZeroThread.ql
java/ql/test/query-tests/ScheduledThreadPoolExecutorZeroThread/ScheduledThreadPoolExecutorZeroThread.expected
java/ql/test/query-tests/ScheduledThreadPoolExecutorZeroThread/ScheduledThreadPoolExecutorZeroThread.qlref
java/ql/test/query-tests/ScheduledThreadPoolExecutorZeroThread/Test.java

This pull request introduces a new query to identify potential issues with setting the `corePoolSize` of `ScheduledThreadPoolExecutor` to zero, which may lead to unintended behavior and programmer error. The changes include adding the query logic, documentation, test cases, and integration into the query suite.
MRVA top 100 only reports 4 alerts. I checked autofix on 3 of these. Two autofix suggestions completely removed the `executor.setCorePoolSize(0)` calls, the third one changed the 0 value to `Schedulers.DEFAULT_POOL_SIZE`, which is the value used in `setMaximumPoolSize`.

Java: Add `java/javautilconcurrentscheduledthreadpoolexecutor` query for zero thread pool size

---

python/ql/src/Resources/FileNotAlwaysClosedQuery.qll
python/ql/test/query-tests/Resources/FileNotAlwaysClosed/resources_test.py

cc @nickrolfe , @aschackmull , @alexet

Python: Improve performance of FileNotClosed query by using basic block reachability

---

java/ql/lib/semmle/code/java/security/CleartextStorageCookieQuery.qll
java/ql/lib/semmle/code/java/security/CleartextStorageQuery.qll

I picked this commit out of #17846 because it doesn't rely on any of the controversial API changes that are holding back that PR. It appears there are no tests for `CleartextStorageCookie.ql`.
> This query shares implementation with several other queries about cleartext storage, but it's the only one of them that's in the code-scanning suite. The sharing mechanism remains the same as before, but now each query has to override `getASelectedLocation` to become diff-informed.
>
> Two other data-flow configurations are used in this query, but they can't easily be made diff-informed.

Java: Diff-informed CleartextStorageCookie.ql

---

rust/ql/lib/codeql/rust/dataflow/internal/Node.qll
rust/ql/lib/codeql/rust/internal/CachedStages.qll

This PR introduces extra caching, to avoid recomputing things in data flow query stages. I also identified an unfortunate recomputation as a result of `NodePublic` being `abstract`; the compiler does not know that `NodePublic` is in fact the same as the entire underlying `newtype`, so that resulted in a needless charpred with expensive recomputations.
Reduces lines of DIL from 39K to 28.5K for the query stage of `CleartextLogging.ql`. [DCA confirms](https://github.com/github/codeql-dca-main/blob/data/hvitved/PR-19886-0-rust/reports/summaries/output.theme.md#dil-sizes) the DIL reduction for data flow queries.

Rust: Cache `DataFlow::Node.{toString,getLocation}`

---

javascript/ql/lib/semmle/javascript/frameworks/Nest.qll
javascript/ql/test/library-tests/frameworks/Nest/global/app.module.ts
javascript/ql/test/library-tests/frameworks/Nest/global/foo.impl.ts
javascript/ql/test/library-tests/frameworks/Nest/global/foo.interface.ts
javascript/ql/test/library-tests/frameworks/Nest/global/imports.ts
javascript/ql/test/library-tests/frameworks/Nest/global/validation.ts
javascript/ql/test/library-tests/frameworks/Nest/local/middleware.ts
javascript/ql/test/library-tests/frameworks/Nest/test.expected

Adds NestJS middlewares as remote flow sources and improves dependency injection in several ways (each commit message explains what it adds support for).

Improve NestJS sources and dependency injection

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ProductFlow.qll

Looks like I forgot to sync the product-flow field flow branch limits in https://github.com/github/codeql/pull/19269. Syncing this here.

C++: Sync the product-flow field flow branch limits with the default one

---

rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
rust/ql/test/library-tests/variables/Ssa.expected
rust/ql/test/query-tests/security/CWE-825/CONSISTENCY/SsaConsistency.expected
rust/ql/test/query-tests/security/CWE-825/CONSISTENCY/VariableCaptureConsistency.expected

https://github.com/github/codeql/pull/19702 follow-up.

Rust: Fix variable capture inconsistencies

---

cpp/ql/lib/change-notes/2025-06-24-float16 copy.md

Change not summarizing all the Arm64 work that has been done in earlier PRs, and where change notes were omitted.

C++: Add Arm64 change note

---

cpp/ql/lib/semmle/code/cpp/exprs/Call.qll
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/ir/ir/PrintAST.expected
cpp/ql/test/library-tests/ptr_to_member/segfault/exprs.expected

This PR overrides `toString` for `ConstructorInit`, which previously had `no string representation`. It also overrides `toString` for `ConstructorBaseInit` while preserving the existing behavior.
Coding Standards PR: https://github.com/github/codeql-coding-standards/pull/916

C++: fix `(no string representation)` for `ConstructorInit`

---

ruby/ql/lib/codeql/ruby/ast/internal/Literal.qll

Fixes the `PoolGrowthError "String too long (2160871 characters)"` error we have seen at a customer.

Ruby: Do not compute `StringlikeLiteralImpl.getStringValue` for large strings

---

cpp/ql/lib/ext/Windows.model.yml
cpp/ql/src/change-notes/2025-07-12-create-thread.md
cpp/ql/test/library-tests/dataflow/external-models/flow.expected
cpp/ql/test/library-tests/dataflow/external-models/validatemodels.expected
cpp/ql/test/library-tests/dataflow/external-models/windows.cpp

Adds flow summaries for `CreateThread`, `CreateRemoteThread`, and `CreateRemoteThreadEx`. They're all pretty much identically: We add a summary from the `lpParameter` to the function passed in via the `lpStartAddress` parameter.

C++: Add flow summaries for `CreateThread` and friends

---

rust/ast-generator/src/field_info.rs
rust/ast-generator/src/main.rs

This makes it so that all customization of the `ast-generator` is written down in functions at the very start of `main.rs`. This should make it somewhat easier to maintain and tweak it in the future.

Rust: refactor `ast-generator` to have all customization at the start

---

cpp/bulk_generation_targets.yml

Now that we have `glibc` in the `mad-generation` suite we can start to generate flow summaries for the project.

C++: Add `glibc` to `bulk_generation_targets.yml`

---

cpp/bulk_generation_targets.yml

Now that we have `glibc` in the `mad-generation` DCA suite we can start to generate flow summaries for the project.

C++: Add glibc to the list of bulk generation targets

---

rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
rust/ql/test/library-tests/variables/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/library-tests/variables/CONSISTENCY/SsaConsistency.expected
rust/ql/test/library-tests/variables/Cfg.expected
rust/ql/test/library-tests/variables/Ssa.expected
rust/ql/test/library-tests/variables/main.rs
rust/ql/test/library-tests/variables/variables.expected

This PR inserts missing SSA definitions; [DCA](https://github.com/github/codeql-dca-main/issues/30034) confirms that ~ 2/3 of all SSA inconsistencies are fixed.

Rust: Fix SSA inconsistencies

---

ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll
ruby/ql/lib/codeql/ruby/ast/internal/TreeSitter.qll
shared/tree-sitter-extractor/src/generator/mod.rs
shared/tree-sitter-extractor/src/generator/ql_gen.rs

Since the tree-sitter-based extractors use `*` IDs for locations, they are not shared between a base database and an overlay, so we need to add `discard_entity` predicates to discard locations from the base in files that got re-extracted in the overlay.

Ruby/QL: add discard predicates for locations

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/test/extractor-tests/canonical_path/canonical_paths.expected
rust/ql/test/extractor-tests/canonical_path/regular.rs

This should cover cases where items are defined in `extern {}` blocks. 
* https://github.com/rust-lang/libc/blob/8e6f36c6ba5c91c150f2d79a06ffdc3d0b83a0f6/src/lib.rs#L75-L83
* https://github.com/rust-lang/libc/blob/8e6f36c6ba5c91c150f2d79a06ffdc3d0b83a0f6/src/unix/mod.rs#L583-L586

Rust: path resolution: handle items in `extern` blocks

---

rust/ql/lib/change-notes/2025-07-07-type-inference-for-loops.md
rust/ql/lib/codeql/rust/elements/RangeExprExt.qll
rust/ql/lib/codeql/rust/frameworks/stdlib/Stdlib.qll
rust/ql/lib/codeql/rust/internal/Type.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/lib/rust.qll
rust/ql/test/library-tests/dataflow/sources/TaintSources.expected
rust/ql/test/library-tests/dataflow/sources/test.rs
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected

This PR generalizes the existing logic for inferring types of `for` loops to be based on the `IntoIterator` trait, cf. [how `for` loops are desugared](https://doc.rust-lang.org/reference/expressions/loop-expr.html#r-expr.loop.for.desugar). Additionally, this PR also adds type inference for range expressions like `1..10`.
[DCA](https://github.com/github/codeql-dca-main/issues/30038) looks good; more resolved calls, no significant slowdown.

Rust: Improve type inference for `for` loops and range expressions

---

rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected
rust/ql/test/query-tests/security/CWE-825/AccessAfterLifetime.expected
rust/ql/test/query-tests/security/CWE-825/lifetime.rs

Adjusts the types from `str` type `&str`.

Rust: Adjust the inferred type of string literals

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/test/extractor-tests/canonical_path/canonical_paths.expected
rust/ql/test/extractor-tests/canonical_path/regular.rs

@hvitved This is probably the wrong way to fix this.

Rust: fix missing canonical paths for trait impls on builtin numeric types

---

ql/ql/src/codeql_ql/ast/Ast.qll
ql/ql/src/codeql_ql/style/DeadCodeQuery.qll
ql/ql/test/queries/style/DeadCode/Foo.qll

Private discard entity predicates are currently marked as dead code by the QL4QL dead code query. This PR updates the query such that discard predicates are always considered alive.

QL4QL: Discard predicates are always alive

---

cpp/ql/lib/ext/pthread.model.yml
cpp/ql/lib/ext/std.thread.model.yml
cpp/ql/src/change-notes/2025-07-10-pthread-and-std-thread.md
cpp/ql/test/library-tests/dataflow/external-models/flow.expected
cpp/ql/test/library-tests/dataflow/external-models/sinks.expected
cpp/ql/test/library-tests/dataflow/external-models/sources.expected
cpp/ql/test/library-tests/dataflow/external-models/test.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/stl.h
cpp/ql/test/library-tests/dataflow/taint-tests/thread.cpp

This is https://github.com/github/codeql/pull/19955, but for `pthread`s and `std::thread`s.

C++: Add more thread creation models

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/Instruction.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/Instruction.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/Instruction.qll
cpp/ql/src/change-notes/2025-07-11-function-objects.md
cpp/ql/test/library-tests/dataflow/external-models/flow.expected
cpp/ql/test/library-tests/dataflow/external-models/flow.ext.yml
cpp/ql/test/library-tests/dataflow/external-models/sinks.expected
cpp/ql/test/library-tests/dataflow/external-models/sources.expected
cpp/ql/test/library-tests/dataflow/external-models/test.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/thread.cpp

While adding tests for `std::thread` in https://github.com/github/codeql/pull/20016 I noticed that we failed to get dataflow in this example:
```cpp
int x = source();
std::thread([](int y){
sink(y);
}, x);
```
this turned out to be because we never properly added support for passing C++ function objects when we added support for function pointer resolution in https://github.com/github/codeql/pull/17788. This PR fixes that problem.
Commit-by-commit review recommended

C++: Better dataflow for function objects

---

python/ql/lib/change-notes/2025-06-04-call-graph-type-annotations.md
python/ql/lib/semmle/python/Exprs.qll
python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll
python/ql/test/experimental/library-tests/CallGraph-type-annotations/InlineCallGraphTest.expected
python/ql/test/experimental/library-tests/CallGraph-type-annotations/InlineCallGraphTest.qlref
python/ql/test/experimental/library-tests/CallGraph-type-annotations/type_annotations.py

Adds support for tracking instances via type annotations. Also adds a convenience method to the newly added `Annotation` class, `getAnnotatedExpression`, that returns the expression that is annotated with the given type. For return annotations this is any value returned from the annotated function in question.

Python: Support type annotations in call graph

---

java/ql/lib/change-notes/2025-07-11-unsafe-deserialization-extra-sink.md
java/ql/lib/semmle/code/java/JDK.qll
java/ql/lib/semmle/code/java/security/UnsafeDeserializationQuery.qll
java/ql/test/query-tests/security/CWE-502/A.java
java/ql/test/query-tests/security/CWE-502/UnsafeDeserialization.expected
java/ql/test/query-tests/security/CWE-502/UnsafeDeserialization.ext.yml
java/ql/test/query-tests/security/CWE-502/com/example/MyObjectInput.java

The qualifiers of a calls to `readObject` on any classes that implement `java.io.ObjectInput` are now recognised as sinks for `java/unsafe-deserialization`. Previously this was only the case for classes which extend `java.io.ObjectInputStream`.

Java: add extra sink for `java/unsafe-deserialization`

---

cpp/ql/lib/semmle/code/cpp/Concept.qll

Noted by @MathiasVP on Slack.
* `RequirementExpr` was missing a charpred, or wasn't abstract. I added a charpred.
* `NestedRequirementExpr` accidentally didn't extend `RequirementExpr`
* `ConceptIdExpr` accidentally did extend `RequirementExpr` (while it can occur in other contexts)

C++: Fix C++20 concept related class extensions

---

ruby/ql/lib/qlpack.yml

Stacked on top of https://github.com/github/codeql/pull/19989

Ruby: enable overlay compilation

---

java/ql/integration-tests/kotlin/linux/custom_plugin/plugin/BUILD.bazel
java/ql/integration-tests/kotlin/linux/custom_plugin/test.py

Put less emphasis on plugin build isolation, to get a better DevEx out of it. The crux of the test is the database extraction part, not the plugin build.
The plugin build is now done from the internal repo, and reusing whatever cached things are there.

Kotlin: tweak plugin test

---

javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java
javascript/extractor/test/com/semmle/js/extractor/test/AutoBuildTests.java
javascript/ql/lib/change-notes/2025-07-11-ignore-outdirs-that-would-exclude-everything.md

In https://github.com/github/codeql/pull/19680 we added support for automatically ignoring files in the `outDir` directory as specified in the TSconfig compiler options (as these files were likely duplicates of `.ts` file we were already scanning).
However, in some cases people put `outDir: "."` or even `outDir: ".."` in their configuration, which had the side effect of excluding _all_ files, leading to a failed extraction.
With the changes in this PR, we now ignore any `outDir`s that are not  properly contained within the source root of the code being scanned. This should prevent the files from being extracted, while still allowing us to not double-scan files in, say, a `.github` directory, as seen in some Actions workflows.

JavaScript: Ignore `outDir`s that would exclude everything

---

java/ql/lib/semmle/code/Location.qll
java/ql/lib/semmle/code/java/Overlay.qll

This should improve accuracy of overlay analysis, since we'll now correctly discard entities from files that were deleted.

Java: use `overlayChangedFiles` in discard prediactes

---

java/ql/lib/semmle/code/java/Overlay.qll

This PR adds discard predicates for Java to discard XML locatables and Java properties. XML and Java property extraction is not incremental and the overlay therefore contains a full XML and Java property extraction during overlay analysis. If the overlay contains any XML locatables, all XML locatables are discarded from base, and likewise for Java properties. 
Overlay compilation is currently disabled for Java and the discard predicates currently have no effect on compilation or evaluation.

Overlay: Add XML and Java property discarding

---

cpp/ql/src/Security/CWE/CWE-114/UncontrolledProcessOperation.ql

Having both `asExpr()` and `asIndirectExpr()` doesn't appear to change any results. This was a leftover from back when we ported the default-taint-tracking queries over, and we still had a few remaining bugs in `asExpr` and `asIndirectExpr`, and probably some remaining pointer sources that needed to be converted to pointee sources.
I've manually verified that all the removed results from DCA are due to deduplication.

C++: Reduce duplication in `cpp/uncontrolled-process-operation`

---

go/ql/lib/semmle/go/dataflow/internal/DataFlowImplConsistency.qll

As pointed out in https://github.com/github/codeql/issues/19890, this file didn't compile.

Go: Fix compilation of DataFlowImplConsistency.qll

---

java/ql/lib/qlpack.yml

This PR enables overlay compilation for Java. With overlay compilation enabled, the compiler will model the overlay frontier throughout optimisation passes and generate QLX that supports both non-overlay aware evaluation and overlay aware evaluation. The current non-overlay aware evaluation will remain the default. Enabling overlay compilation will not affect semantics under non-overlay aware evaluation, but may affect performance as some previously valid optimisations are no longer valid under overlay compilation. 
Previous DCA experiments identified two real regressions stemming from TC bounds and magic bounds that were hampered by the overlay frontier. The TC bound regressions both involved use of `DataFlow::localExprFlow` and affected 2 queries. The TC bound regressions were fixed …

Overlay: Enable overlay compilation for Java

---

java/ql/lib/change-notes/2025-07-16-models-as-data-unsafe-deserialization-sinks.md
java/ql/lib/change-notes/2025-07-16-unsafe-deserialization-sinks-deprecation.md
java/ql/lib/ext/com.alibaba.com.caucho.hessian.io.model.yml
java/ql/lib/ext/com.caucho.burlap.io.model.yml
java/ql/lib/ext/com.caucho.hessian.io.model.yml
java/ql/lib/ext/com.cedarsoftware.util.io.model.yml
java/ql/lib/ext/com.esotericsoftware.yamlbeans.model.yml
java/ql/lib/ext/java.beans.model.yml
java/ql/lib/ext/org.apache.commons.lang.model.yml
java/ql/lib/ext/org.apache.commons.lang3.model.yml
java/ql/lib/ext/org.exolab.castor.xml.model.yml
java/ql/lib/ext/org.ho.yaml.model.yml
java/ql/lib/ext/org.jabsorb.model.yml
java/ql/lib/semmle/code/java/frameworks/Castor.qll
java/ql/lib/semmle/code/java/frameworks/HessianBurlap.qll
java/ql/lib/semmle/code/java/frameworks/JYaml.qll
java/ql/lib/semmle/code/java/frameworks/Jabsorb.qll
java/ql/lib/semmle/code/java/frameworks/YamlBeans.qll
java/ql/lib/semmle/code/java/frameworks/apache/Lang.qll
java/ql/lib/semmle/code/java/security/UnsafeDeserializationQuery.qll
java/ql/test/query-tests/security/CWE-502/UnsafeDeserialization.expected
java/ql/test/query-tests/security/CWE-611/XXE.expected
shared/mad/codeql/mad/ModelValidation.qll

This PR allows sinks for `java/unsafe-deserialization` to be specified using models-as-data, and also converts some of the sinks to use that format and deprecates any classes that no longer have any uses. Many of the sinks have to stay defined in QL because they have extra logic around whether they are safe or not.
I ran MRVA on this query using 1000 repos and found no differences in the results before and after. There are also no test result differences except adding more models and changes to the numbering of the existing models. These two things give me confidence that the conversions have not changed behaviour.

Java: allow the definition of `java/unsafe-deserialization` sinks using data extensions

---

docs/query-metadata-style-guide.md
java/ql/src/Language Abuse/TypeVariableHidesType.ql
javascript/ql/src/Quality/UnhandledErrorInStreamPipeline.ql
ql/ql/src/codeql/files/FileSystem.qll
ql/ql/src/codeql_ql/ast/Ast.qll
ql/ql/src/queries/style/MissingQualityMetadata.ql
ql/ql/src/queries/style/MissingSecurityMetadata.ql
ql/ql/test/queries/style/MissingQualityMetadata/MissingQualityMetadata.expected
ql/ql/test/queries/style/MissingQualityMetadata/MissingQualityMetadata.qlref
ql/ql/test/queries/style/MissingQualityMetadata/testcases/BadQualityMaintainabilityWrongToplevel.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/BadQualityMultipleTopLevel.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/BadQualityNoToplevel.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/BadQualityReliabilityWrongToplevel.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/GoodNotQuality.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/GoodQualityMaintainability.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/GoodQualityMaintainabilityWithCrossSub.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/GoodQualityMaintainabilityWithSub.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/GoodQualityReliability.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/GoodQualityReliabilityWithCrossSub.ql
ql/ql/test/queries/style/MissingQualityMetadata/testcases/GoodQualityReliabilityWithSub.ql
ql/ql/test/queries/style/MissingSecurityMetadata/MissingSecurityMetadata.expected

In this PR we introduce a Ql4Ql check for correct use of quality query tags as documented [here](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md#quality-query-sub-category-tags).
According to the documentation
- A quality query (a query tagged with `quality`) should have at least a top level categorisation.
- A query *may* have sub-level categories as well. If a quality query is tagged with top-level A and with sub-categories B1,..,Bn then at least one of the sub-categories Bi should be a sub-category of A.
Furthermore, we also fix the existing violations.

Ql4ql: Quality query tagging.

---

java/ql/lib/semmle/code/java/security/CsrfUnprotectedRequestTypeQuery.qll
java/ql/src/Security/CWE/CWE-352/CsrfUnprotectedRequestType.ql

This should be completely behaviour-preserving, but saves hundreds of MBs of output for some repos. Dca has had trouble processing the output of this query even for cases with zero alerts for several repos.
See also comments here: https://github.com/github/codeql/pull/19872#issuecomment-3083292194

Java: Prune PathGraph for CsrfUnprotectedRequestType.ql

---

java/ql/lib/semmle/code/java/ControlFlowGraph.qll

The somewhat recent change to the CFG for Java assert statements introduced an accidental cartesian product. The product is between completions and assert statements, both of which are somewhat limited in number, which is why we haven't discovered this before now. It was identified by the join-order metric, since the CP was confusing the optimiser to select a particularly bad join order.
Before:
```
444   ~4%    {2} r34 = JOIN Completion::Completion#3da5aa6a WITH num#Completion::NormalCompletion#17a01869 CARTESIAN PRODUCT OUTPUT Rhs.0, Lhs.0
257653644   ~0%    {3}    | JOIN WITH `ControlFlowGraph::ControlFlowGraphImpl::last/3#f72f2d15_201#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Rhs.2
17760   ~0%    {3}    | JOIN WITH `Statement::AssertStmt.getMessage/0#dispred#911385b1_10#join_rhs` ON …
```

Java: Fix accidental CP in CFG for asserts.

---

java/ql/src/Likely Bugs/Collections/ArrayIndexOutOfBounds.ql
java/ql/src/Likely Bugs/Statements/PartiallyMaskedCatch.ql

Follow-up to https://github.com/github/codeql/pull/20088 with a few more cases.
Commit 1: The double SSA-to-use occurrences were being joined, which meant a large fanout. On the other hand, we couldn't really go from `b` to `len` either, since that's an even larger fanout. The solution was to factor out the two functional joins from `len` to `arr` and to `b`, since that allows a two-column join.
Before:
```
[2025-07-18 15:24:29] Evaluated non-recursive predicate _#Bound::Bound.getExpr/0#dispred#43d310d3Merge_#Expr::FieldAccess.getField/0#dispred#29ef4aa0Merge_#__#shared@3fd433m3 in 62ms (size: 186).
Evaluated relational algebra for predicate _#Bound::Bound.getExpr/0#dispred#43d310d3Merge_#Expr::FieldAccess.getField/0#dispred#29ef4aa0Merge_#__#shared@3fd433m3 with tuple counts:
92543 …
```

Java: Improve more join-orders

---

java/ql/src/Security/CWE/CWE-502/UnsafeDeserialization.qhelp

It was brought to our attention in https://github.com/github/codeql/issues/19664 that SnakeYaml is not vulnerable to `java/unsafe-deserialization` as of version 2.0 (released in 2023). This is because all constructors now extend `SafeConstructor`. We already had an exclusion for constructors which extend `SafeConstructor`, so the query does not need to be updated. This PR updates the qhelp file.

Java: Update qhelp: SnakeYaml is safe from version 2.0

---

shared/typeinference/codeql/typeinference/internal/TypeInference.qll

This PR makes a few refactors to the type inference library.
I think these changes make sense on their own, but on `databend` they also reduce the total number of tuples (observed using "Compare Performance" in VSCode) and the following bad join reported by VScode (also observed on `databend`) disappears:
<details>
<summary>Bad join</summary>
```
Pipeline standard for TypeInference::CallExprBaseMatching::typeConstraintBaseTypeMatch/5#ebeb4216@f3cabgyd was evaluated in 530 iterations totaling 145ms (delta sizes total: 36047).
5442   ~0%    {5} r1 = JOIN `TypeInference::CallExprBaseMatchingInput::Access.getTarget/0#dispred#29d66fd1#prev_delta` WITH TypeInference::CallExprBaseMatching::AccessConstraint::MkRelevantAccess#8a6252ad#prev ON FIRST 1 OUTPUT Rhs.2, Lhs.0, Lhs.1, Rhs.3, Rhs.4
5442 …
```

Rust: Type inference refactor and improve join orders

---

python/ql/src/Exceptions/CatchingBaseException.qhelp
python/ql/src/Exceptions/EmptyExcept.qhelp
python/ql/src/Expressions/CallToSuperWrongClass.qhelp
python/ql/src/Expressions/DuplicateKeyInDictionaryLiteral.py
python/ql/src/Expressions/DuplicateKeyInDictionaryLiteral.qhelp
python/ql/src/Expressions/ExplicitCallToDel.qhelp
python/ql/src/Expressions/IncorrectComparisonUsingIs.qhelp
python/ql/src/Expressions/IncorrectComparisonUsingIs.ql
python/ql/src/Expressions/UnsupportedFormatCharacter.qhelp
python/ql/src/Functions/ConsistentReturns.qhelp
python/ql/src/Functions/ConsistentReturns.ql
python/ql/src/Functions/InitIsGenerator.qhelp
python/ql/src/Functions/ModificationOfParameterWithDefault.qhelp
python/ql/test/query-tests/Functions/return_values/ConsistentReturns.expected

Updates documentation of several quality queries, to use python 3 rather than python 2 documentation as references, and a few minor grammatical fixes.

Python: Minor documantation updates to several quality queries

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/SsaImpl.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/BarrierGuards.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/TaintTrackingPrivate.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/sharedlib/Ssa.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
shared/dataflow/codeql/dataflow/VariableCapture.qll
shared/ssa/codeql/ssa/Ssa.qll

This just tweaks the internal api in SSA to support BarrierGuard wrappers from https://github.com/github/codeql/pull/20121. Semantics and external interfaces remain unchanged.

SSA: Update data flow integration and BarrierGuard interface to use GuardValue.

---

rust/ql/integration-tests/query-suite/rust-code-scanning.qls.expected
rust/ql/integration-tests/query-suite/rust-security-and-quality.qls.expected
rust/ql/integration-tests/query-suite/rust-security-extended.qls.expected
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/src/queries/summary/NodesWithTypeAtLengthLimit.ql

A node can have a type at a type path that reaches the length limit of 10 if: 1/ the type is 10 levels deep (not likely) or 2/ type inference got in some infinite cycle and reached the type path length limit.
We'v previously had a performance issue due to the latter and now it seems that something similar is happening in https://github.com/github/codeql/pull/20140: We have some existing types that reach the limit and something in #20140 causes that latent issue to explode even further.
This PR adds a metric for DCA that tracks how many nodes have a type that reach the type path length limit. These infinite cycles may not show up as performance issues initially, but they could later, so having DCA report them will let us catch things earlier and will help us work towards getting the metric …

Rust: Add metric for DCA and debug predicates for type that reach the length limit

---

rust/ql/lib/codeql/rust/internal/TypeInference.qll

```
Evaluated relational algebra for predicate TypeInference::closureParameterPath/2#9d0bf423#bbf@ba08cc1s with tuple counts:
565067    ~172652%    {2} r1 = JOIN `Callable::Callable.getParam/1#dispred#ce0254b3_01#count_range` WITH `Callable::Generated::Callable.getNumberOfParams/0#dispred#abb45996` ON FIRST 1 OUTPUT Rhs.1, Lhs.1
24684     ~11784%    {3}    | JOIN WITH Type::TTupleTypeParameter#5ca17706 ON FIRST 2 OUTPUT Rhs.2, Lhs.1, Lhs.0
2970      ~1391%    {3}    | JOIN WITH `TypeInference::TypePath::singleton/1#ee45de3b` ON FIRST 1 OUTPUT Lhs.1, Lhs.2, Rhs.1
664       ~242%    {4}    | JOIN WITH `Stdlib::FnOnceTrait.getTypeParam/0#dispred#93f20bbc` CARTESIAN PRODUCT OUTPUT Rhs.1, Lhs.0, Lhs.1, Lhs.2
303        ~49%    {4}    | JOIN WITH Type::TDynTraitTypeParameter#e16268df ON FIRST 1 …
```

Rust: Fix two bad joins introduced by magic

---

rust/ql/lib/codeql/rust/internal/Type.qll
rust/ql/lib/codeql/rust/internal/TypeMention.qll

Addresses https://github.com/github/codeql/pull/20094#discussion_r2254286785.
DCA looks fine.

Rust: Remove restriction in `PathTypeMention`

---

java/ql/lib/change-notes/2025-07-28-guardwrappers.md
java/ql/lib/semmle/code/java/controlflow/Guards.qll
java/ql/test/library-tests/guards/Guards.java
java/ql/test/library-tests/guards/GuardsInline.expected
java/ql/test/query-tests/Nullness/C.java
java/ql/test/query-tests/Nullness/NullMaybe.expected
shared/controlflow/codeql/controlflow/Guards.qll

This improves the shared library implementation of guard wrappers in several ways. Commit-by-commit review is strongly encouraged.
* Improves the Guards instantiation interface by removing the nesting of parameteristion of the `CustomGuard`/`WrapperGuard` module.
* Generalises wrappers to support all sorts of return values - not just booleans.
* Generalises wrappers to also support exceptional/normal return.
* Adds a (currently unused) module intended to be connected to `BarrierGuard` to support wrapped sanitizers.

Guards: Improve support for wrapped guards

---

java/ql/integration-tests/java/android-sample-kotlin-build-script-no-wrapper/test.py
java/ql/integration-tests/java/android-sample-no-wrapper/test.py
java/ql/integration-tests/java/android-sample-old-style-kotlin-build-script-no-wrapper/test.py
java/ql/integration-tests/java/android-sample-old-style-no-wrapper/test.py

Gradle 9 which has recently been rolled out to action images requires Java 17.
Closes https://github.com/github/semmle-code/issues/53694

Java: use java 17 in `no-wrapper` tests

---

javascript/ql/lib/semmle/javascript/Concepts.qll
shared/concepts/codeql/concepts/ConceptsShared.qll

https://github.com/github/codeql/pull/19984 follow-up.

Shared: Use `final` aliases in `ConcentsShared.qll`

---

cpp/ql/lib/change-notes/2025-08-02-gvn.md
cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/gvn/internal/ValueNumberingInternal.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/gvn/internal/ValueNumberingInternal.qll
cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/gvn/internal/ValueNumberingInternal.qll
cpp/ql/test/library-tests/valuenumbering/GlobalValueNumbering/ir_gvn.expected
cpp/ql/test/library-tests/valuenumbering/GlobalValueNumbering/test.cpp
cpp/ql/test/query-tests/Likely Bugs/Memory Management/StrncpyFlippedArgs/StrncpyFlippedArgs.expected

Consider the following snippet:
```cpp
struct S {
void foo() const;
void bar();
};
void test() {
S s;
s.foo();
s.bar();
}
```
Because `foo` is a `const` member function there will be a `GlvalueConversion` which converts the qualifier from a `glval<S>` to a `glval<const S>` before it's passed to `foo`. This conversion will generate a `Convert` instruction.
However, since `bar` isn't a `const` member function there won't be a `Convert` instruction, and so global value numbering (GVN) concludes that the two qualifiers won't necessarily evaluate to the same value at runtime (although, they obviously will).
This PR modifies GVN so that conversions that only modify specifiers receive the same global value number.
There was 1 query test change (see …

C++: Value numbering for casts that only modify specifiers

---

actions/ql/src/Security/CWE-829/UntrustedCheckoutCritical.md
actions/ql/src/Security/CWE-829/UntrustedCheckoutHigh.md
actions/ql/src/Security/CWE-829/UntrustedCheckoutMedium.md

Add some small samples to show how the untrusted code could potentially be executed in an action workflow. (The change is the same for all 3 doc files)

Actions: clarify doc for untrusted checkout

---

ruby/ql/lib/change-notes/2025-07-21-nethttprequest-improvements.md
ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll
ruby/ql/test/library-tests/frameworks/http_clients/HttpClients.expected
ruby/ql/test/library-tests/frameworks/http_clients/NetHttp.rb

This PR makes 3 improvements to the `NetHttpRequest` class:
- Adds `connectionNode` like other Ruby HTTP clients (see #19294)
- Makes `requestNode` and `connectionNode` public so subclasses can use them (see #19294)
- Adds detection of `Net::HTTP.start` - this is a [common way](https://docs.ruby-lang.org/en/master/Net/HTTP.html#class-Net::HTTPSession-label-Strategies) to make HTTP requests in Ruby

Fix #19294, Ruby NetHttpRequest improvements

---

MODULE.bazel
go/actions/test/action.yml
go/extractor/autobuilder/build-environment.go
go/extractor/go.mod

The failure of Go Resolve Build Environment Tests looks expected. The test does pass on the internal PR (after workflow updates).
See the internal PR for a DCA experiment.

Go: Update Go version to 1.25.0

---

java/ql/lib/semmle/code/java/ControlFlowGraph.qll
java/ql/lib/semmle/code/java/Member.qll
java/ql/lib/semmle/code/java/controlflow/Guards.qll
java/ql/lib/semmle/code/java/dataflow/internal/SsaImpl.qll
java/ql/lib/semmle/code/java/security/ArithmeticCommon.qll
java/ql/lib/semmle/code/java/security/PathSanitizer.qll
shared/controlflow/codeql/controlflow/Guards.qll

This enables the Guards library wrapper guard integration with BarrierGuard such that data flow sanitizers make use of the full power of the Guards library including wrapped validation checks.
Some individual barriers had ad-hoc support for this, which can now be deleted as it becomes superfluous.

Java: Enable BarrierGuard wrappers

---

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaImpl.qll
cpp/ql/lib/semmle/code/cpp/models/interfaces/FormattingFunction.qll
cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
cpp/ql/test/library-tests/dataflow/taint-tests/taint.ql

This fixes a FN that @jketema noticed on the Coding Standards queries.
The new results in `cpp/non-constant-format` and `cpp/tainted-format-string` highlight some really weird code:
```cpp
#define die(fmt,args...) do { fprintf(stderr, fmt, ## args ); fflush(stderr); exit(-1); } while(0)
...
if(/*NEEDTMP &&*/ !(tmp = (unsigned char*)malloc(ns))) die(stderr, "malloc error\n");
```
We get new results on `stderr`. It took me a second to spot the issue, but it looks like `die` expands to:
```cpp
do { fprintf(stderr, stderr, "malloc error\n"); fflush(stderr); exit(-1); } 
```
Which seems very bad! So this looks like TPs 🎉

C++: Mark the write to `fprintf`'s 0'th argument as partial

---

java/ql/integration-tests/java/query-suite/java-code-quality-extended.qls.expected
java/ql/src/Violations of Best Practice/Undesirable Calls/CallsToRunFinalizersOnExit.ql
java/ql/src/Violations of Best Practice/Undesirable Calls/GarbageCollection.ql
java/ql/src/change-notes/2025-07-19-adjust-tags.md

Adds `previous-id` and adjusts tags for `java/garbage-collection` and `java/run-finalizers-on-exit`. Follow-up to https://github.com/github/codeql/pull/19075.
This will add `java/run-finalizers-on-exit` to the code-quality-extended suite. `java/garbage-collection` will not be added to any suite due to its `low` precision.

Java: Add `previous-id` and adjust tags for `java/garbage-collection` and `java/run-finalizers-on-exit`

---

shared/typeinference/codeql/typeinference/internal/TypeInference.qll

Rename variables to be consistent with the naming used in `conditionSatisfiesConstraint`.

Type inference: Rename some variables

---

rust/ql/integration-tests/qltest/test_qltest.py

The integration test expectes to find a certain phrase from the extractor repeated in the _stderr_ of `codeql test run`. However, that subcommand is about to start reproducing the extractor output as-is, which means the phrase will instead appear in _stdout_.
Change the integration test to capture all of the output, so it will keep passing across the change.

rust integration test: use all output from codeql test run

---

.bazelrc
MODULE.bazel

This was meant to avoid using `gold`, but `lld` might not be installed. Having `gold` installed results in the following warning:
```
warning: the gold linker is deprecated and has known bugs with Rust
|
= help: consider using LLD or ld from GNU binutils instead
```
* if a user sees this warning, they can provide the `lld` or whatever linker they prefer themselves, or make sure to uninstall `gold`
* in any case, this is not what we use for releasing (where we are sure we don't use `gold`).

Bazel: do not force `lld` and fix `platforms` warning

---

rust/ql/lib/change-notes/2025-08-25-in-macro-expansion.md
rust/ql/lib/codeql/rust/elements/internal/MacroCallImpl.qll

When investigating [this false positive report](https://github.com/github/codeql/issues/20256), I realized that the underlying cause was that attribute macros were not taken into account when filtering away results inside expansions.
[DCA](https://github.com/github/codeql-dca-main/issues/30919) confirms that the FPs have been eliminated.

Rust: Include `getAttributeMacroExpansion` in `isInMacroExpansion`

---

rust/ql/lib/codeql/rust/internal/TypeInference.qll

I think the `0` and `i` where intended to be the other way around.

Rust: Fix minor typo in bound in comment

---

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.22.4.rst
docs/codeql/codeql-overview/codeql-changelog/index.rst

Include a new entry in the changelog for CodeQL CLI version 2.22.4, summarizing the updates and improvements made in this release.

Add changelog entry for CodeQL CLI version 2.22.4

---

java/ql/integration-tests/java/query-suite/java-code-quality-extended.qls.expected
java/ql/integration-tests/java/query-suite/not_included_in_qls.expected
java/ql/src/Violations of Best Practice/Undesirable Calls/CallsToSystemExit.java
java/ql/src/Violations of Best Practice/Undesirable Calls/CallsToSystemExit.qhelp
java/ql/src/Violations of Best Practice/Undesirable Calls/CallsToSystemExit.ql
java/ql/test/query-tests/CallsToSystemExit/CallsToSystemExit.expected
java/ql/test/query-tests/CallsToSystemExit/CallsToSystemExit.qlref
java/ql/test/query-tests/CallsToSystemExit/ExampleRuntimeExit.java
java/ql/test/query-tests/CallsToSystemExit/ExampleRuntimeHalt.java
java/ql/test/query-tests/CallsToSystemExit/ExampleSystemExit.java
java/ql/test/query-tests/CallsToSystemExit/LocalClassInTestMethod.java

This PR integrates improvements from the `java/jvm-exit-prevents-cleanup-and-reuse` query in `codeql-quality-queries` into the main CodeQL repository. The enhanced query now provides better detection of problematic JVM termination calls with reduced false positives and has been promoted quality query suite.
It was decided to keep this query at low/medium precision, as there are quite a few false positives. This is largely due to the way command-line interfaces (CLI) and build tools handle application termination: they often use exit calls in ways that differ from standard software practices. As a result, the query may incorrectly flag these legitimate uses as potential issues, which impacts its overall accuracy.
Autofix appears feasible, though acceptance may vary depending on the …

Java: Enhance `java/jvm-exit` query and add to quality

---

rust/ql/lib/codeql/rust/elements/RangeExprExt.qll
rust/ql/lib/codeql/rust/frameworks/stdlib/Stdlib.qll
rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/type-inference/CONSISTENCY/TypeInferenceConsistency.expected
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/pattern_matching.rs
rust/ql/test/library-tests/type-inference/type-inference.expected

* Fixes a type inference inconsistency where multiple certain types could be inferred for the same node due to match ergonomics/binding modes in pattern matching.
* Makes inference of logical operators certain.
* Makes inference of range expression certain and adds support for the `..` range.

Rust: Minor tweaks to certain type inference

---

javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll

Background: To ensure MaD library models have a near-zero cost for codebases that don't use the modelled library, we prune models based on what packages are imported in the current codebase. This means we don't parse the access paths or synthesise data flow nodes for irrelevant models.
This means that in order to generate `DataFlow::Node`, we first have to compute imported paths. There is thus a dependency on the `Import` class. However, the `Import` class also depends on local data flow. We therefore have `TEarlyStageNode`, which is used by `Import` but does not contain flow summary-generated nodes.
For overlay mode, the `TEarlyStageNode` has no effect on locality as the entire newtype needs to be made local. The dependency above puts us in an "all or nothing" situation where _a lot_ …

JS: Change pruning to not rely on Import

---

python/ql/test/query-tests/analysis/jump_to_defn/Definitions.expected
python/ql/test/query-tests/analysis/jump_to_defn/test.py

Document missing jump-to-def targets.

Python: Add jump-to-def tests for unpacking assignments

---

javascript/ql/lib/change-notes/2025-07-15-xml-bomb-sinks.md
javascript/ql/lib/semmle/javascript/frameworks/XmlParsers.qll
javascript/ql/test/query-tests/Security/CWE-776/XmlBomb.expected
javascript/ql/test/query-tests/Security/CWE-776/libxml.js
javascript/ql/test/query-tests/Security/CWE-776/libxml.noent.js
javascript/ql/test/query-tests/Security/CWE-776/libxml.sax.js
javascript/ql/test/query-tests/Security/CWE-776/libxml.saxpush.js
python/ql/lib/change-notes/2025-07-15-xml-bomb-sinks-python.md
python/ql/lib/semmle/python/frameworks/Lxml.qll
python/ql/test/library-tests/frameworks/lxml/parsing.py
python/ql/test/query-tests/Security/CWE-776-XmlBomb/XmlBomb.expected

Removed `libxmljs` and `lxml` from XML bomb sink list, as their underlying C library have been [patched](https://github.com/GNOME/libxml2/blob/0c948334a8f5c66d50e9f8992e62998017dc4fc6/NEWS#L905-L908) and are no longer vulnerable.

JS: Exclude patched libraries from `xml-bomb` sink

---

java/ql/integration-tests/java/query-suite/java-code-quality-extended.qls.expected
java/ql/integration-tests/java/query-suite/java-code-quality.qls.expected
java/ql/src/Violations of Best Practice/Implementation Hiding/VisibleForTestingAbuse.md
java/ql/src/Violations of Best Practice/Implementation Hiding/VisibleForTestingAbuse.ql
java/ql/test/query-tests/VisibleForTestingAbuse/VisibleForTestingAbuse.expected
java/ql/test/query-tests/VisibleForTestingAbuse/VisibleForTestingAbuse.qlref
java/ql/test/query-tests/VisibleForTestingAbuse/packageone/AnnotatedClass.java
java/ql/test/query-tests/VisibleForTestingAbuse/packageone/SourcePackage.java
java/ql/test/query-tests/VisibleForTestingAbuse/packageone/SourcePackage1.java
java/ql/test/query-tests/VisibleForTestingAbuse/packageone/VisibleForTesting.java
java/ql/test/query-tests/VisibleForTestingAbuse/packagetwo/Annotated.java
java/ql/test/query-tests/VisibleForTestingAbuse/packagetwo/Source.java
java/ql/test/query-tests/VisibleForTestingAbuse/packagetwo/Test.java
java/ql/test/query-tests/VisibleForTestingAbuse/packagetwo/UseWithinAnnotation.java

Added new query `java/visible-for-testing-abuse`.
Initial MRVA 1000 run produced 5,108 results, after reducing false positives ended up with 2,611.
Autofix tends to remove `@VisibleForTesting`, but it may requires deeper refactoring in which case it may not be accepted as a good fix.

Java: Added new query `java/visible-for-testing-abuse`

---

python/ql/lib/change-notes/2025-08-25-psycopg2-connection-pool-modelling.md
python/ql/lib/semmle/python/frameworks/Psycopg2.qll
python/ql/test/library-tests/frameworks/psycopg2/ConceptsTest.ql
python/ql/test/library-tests/frameworks/psycopg2/connectionpool.py

Our current modelling only treated `psycopg2` insofar as it implemented PEP 249 (which does not define any notion of connection pool), which meant we were missing database connections that arose from such pools.
With these changes, we add support for the three classes relating to database pools that are defined in `psycopg2`. (Note that `getAnInstance` automatically looks at subclasses, which means this should also handle cases where the user has defined a new subclass that inherits from one of these three classes.)

Python: Add support for Psycopg2 database connection pools

---

csharp/ql/lib/change-notes/2025-08-29-base-qualifier-dispatch.md
csharp/ql/lib/semmle/code/csharp/dispatch/Dispatch.qll
csharp/ql/test/library-tests/dataflow/call-sensitivity/CallSensitivityFlow.cs
csharp/ql/test/library-tests/dataflow/call-sensitivity/CallSensitivityFlow.expected

Fixes the issue discussed [here](https://github.com/github/codeql/discussions/20260). [DCA](https://github.com/github/codeql-dca-main/issues/31006) is uneventful.

C#: Fix context-sensitive dispatch when using `base` qualifier

---

actions/extractor/codeql-extractor.yml
csharp/codeql-extractor.yml
go/codeql-extractor.yml
javascript/resources/codeql-extractor.yml
python/codeql-extractor.yml
ruby/codeql-extractor.yml
rust/codeql-extractor.yml
swift/codeql-extractor.yml

The current CodeQL Action relies on a hard-coded list of supported languages.  This PR specifies default queries for each CodeQL language, allowing us to remove that list and instead detect languages dynamically:
We now select languages whose extractors are present in the CodeQL search path and provide default queries.
Reasoning:
- We choose to start providing default queries information since we only want to select extractors which have first-class support e.g. JavaScript, but not .properties.  What differentiates these extractors is whether they have queries associated with them.
- Makes it easier for third-parties to develop and test extractors: they don't need to fork the Action, and don't get stuck on the current hard-coded `codeql/<lang>-queries` default queries in the CLI.
- Makes …

Specify default queries in `codeql-extractor.yml`

---

rust/ql/lib/codeql/rust/dataflow/internal/TaintTrackingImpl.qll
rust/ql/src/queries/security/CWE-798/HardcodedCryptographicValue.ql
rust/ql/test/library-tests/dataflow/strings/inline-taint-flow.expected
rust/ql/test/query-tests/security/CWE-022/TaintedPath.expected
rust/ql/test/query-tests/security/CWE-825/AccessAfterLifetime.expected
rust/ql/test/query-tests/security/CWE-825/main.rs

This PR lifts data flow read-steps of `ReferenceContent` to taint steps, in the same way that we already do for `ElementContent`. The motivation is the same: If a reference is a taint source, then it should be safe to assume that the data pointed to is tainted as well (as opposed to just the reference itself).
[DCA](https://github.com/github/codeql-dca-main/issues/31105) looks fine.

Rust: Deref as taint step

---

go/ql/lib/semmle/go/StringOps.qll
go/ql/lib/semmle/go/dataflow/internal/DataFlowUtil.qll
go/ql/src/experimental/IntegerOverflow/RangeAnalysis.qll

Fix some Ql4Ql violations based on the following checks
- `ql/field-only-used-in-charpred`
- `ql/could-be-cast`
- `ql/counting-to-zero`
- `ql/dataflow-module-naming-convention`
- `ql/if-with-none`
- `ql/missing-parameter-qldoc`
- `ql/misspelling`

Go: Fix some Ql4Ql violations.

---

java/ql/lib/experimental/quantum/JCA.qll
java/ql/lib/experimental/quantum/Language.qll
java/ql/lib/printAst.ql
java/ql/lib/semmle/code/java/Concurrency.qll
java/ql/lib/semmle/code/java/Conversions.qll
java/ql/lib/semmle/code/java/Statement.qll
java/ql/lib/semmle/code/java/dataflow/internal/ContainerFlow.qll
java/ql/lib/semmle/code/java/dataflow/internal/DataFlowUtil.qll
java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/SignAnalysisSpecific.qll
java/ql/lib/semmle/code/java/frameworks/Mockito.qll
java/ql/lib/semmle/code/java/frameworks/javaee/ejb/EJB.qll
java/ql/lib/semmle/code/java/security/CleartextStorageAndroidFilesystemQuery.qll
java/ql/lib/semmle/code/java/security/FileWritable.qll
java/ql/lib/semmle/code/java/security/TempDirUtils.qll
java/ql/lib/semmle/code/java/security/UnsafeDeserializationQuery.qll
java/ql/src/Likely Bugs/Comparison/HashedButNoHash.ql
java/ql/src/Likely Bugs/Concurrency/NotifyWithoutSynch.ql
java/ql/src/Likely Bugs/Termination/SpinOnField.ql
java/ql/src/Violations of Best Practice/Magic Constants/MagicConstants.qll
java/ql/src/Violations of Best Practice/Naming Conventions/ConfusingOverloading.ql
java/ql/src/experimental/quantum/Analysis/ArtifactReuse.qll
java/ql/src/experimental/quantum/Examples/BrokenCrypto.ql
java/ql/src/utils/flowtestcasegenerator/FlowTestCase.qll

Fix some Ql4Ql violations based on the following checks
- `ql/field-only-used-in-charpred`
- `ql/could-be-cast`
- `ql/counting-to-zero`
- `ql/dataflow-module-naming-convention`
- `ql/if-with-none`
- `ql/missing-parameter-qldoc`
- `ql/misspelling`

Java: Fix some Ql4Ql violations.

---

ruby/ql/lib/codeql/ruby/ApiGraphs.qll
ruby/ql/lib/codeql/ruby/frameworks/core/Kernel.qll
ruby/ql/lib/codeql/ruby/frameworks/http_clients/Excon.qll
ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll
ruby/ql/lib/codeql/ruby/regexp/internal/ParseRegExp.qll
ruby/ql/lib/codeql/ruby/security/ImproperMemoizationQuery.qll

Fix some Ql4Ql violations based on the following checks
- `ql/field-only-used-in-charpred`
- `ql/could-be-cast`
- `ql/counting-to-zero`
- `ql/dataflow-module-naming-convention`
- `ql/if-with-none`
- `ql/missing-parameter-qldoc`
- `ql/misspelling`

Ruby: Fix some Ql4Ql violations.

---

actions/ql/lib/codeql/Locations.qll
actions/ql/lib/codeql/actions/Ast.qll
actions/ql/lib/codeql/actions/ast/internal/Ast.qll
actions/ql/lib/codeql/actions/controlflow/BasicBlocks.qll
actions/ql/lib/codeql/actions/dataflow/ExternalFlow.qll
actions/ql/lib/codeql/actions/dataflow/FlowSources.qll
actions/ql/lib/codeql/actions/security/ArgumentInjectionQuery.qll
actions/ql/lib/codeql/actions/security/ArtifactPoisoningQuery.qll
actions/ql/lib/codeql/actions/security/ControlChecks.qll
actions/ql/lib/codeql/actions/security/EnvVarInjectionQuery.qll
actions/ql/lib/codeql/actions/security/OutputClobberingQuery.qll
actions/ql/lib/codeql/actions/security/UseOfUnversionedImmutableAction.qll
actions/ql/src/experimental/Security/CWE-829/ArtifactPoisoningPathTraversal.ql

Fix some Ql4Ql violations based on the following checks
- `ql/field-only-used-in-charpred`
- `ql/could-be-cast`
- `ql/counting-to-zero`
- `ql/dataflow-module-naming-convention`
- `ql/if-with-none`
- `ql/missing-parameter-qldoc`
- `ql/misspelling`

Actions: Fix some Ql4Ql violations.

---

go/ql/lib/change-notes/2025-07-15-path-injection-sanitizers.md
go/ql/lib/ext/os.model.yml
go/ql/lib/semmle/go/security/TaintedPathCustomizations.qll
go/ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/Os.go
go/ql/test/query-tests/Security/CWE-022/TaintedPath.expected
go/ql/test/query-tests/Security/CWE-022/TaintedPath.go

Account for os.PathSeparator in Go sanitizer and remove CreateTemp from valid sinks

Update Go Path Injection Sanitizer and Sink

---

go/extractor/cli/go-autobuilder/go-autobuilder.go
go/extractor/cli/go-extractor/BUILD.bazel
go/extractor/cli/go-extractor/go-extractor.go
go/extractor/util/BUILD.bazel
go/extractor/util/logging.go
go/extractor/util/logging_test.go

I noticed that the Go autobuilder/extractor don't respect `CODEQL_VERBOSITY` and therefore the call to e.g. `slog.Debug` in `registryproxy.go` never has any effect. This PR sets the log level for `slog` based on the value of `CODEQL_VERBOSITY`.

Go: Set log level based on `CODEQL_VERBOSITY`

---

java/ql/integration-tests/java/buildless-erroneous/ExtractorInformation.expected

These unneeded annotation processors are no longer run.

Java: Update tests results with disabled annotation processing when lombok is not used.

---

java/ql/src/Violations of Best Practice/Naming Conventions/ConfusingOverloading.ql

Performance of `ConfusingOverloading.ql` was broken by https://github.com/github/codeql/pull/20116. This PR fixes things. There were two issues: the dreaded join-on-index and a case of bad magic.

Java: Fix broken performance.

---

java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
java/ql/lib/semmle/code/java/frameworks/android/ExternalStorage.qll
java/ql/src/Likely Bugs/Collections/ContainsTypeMismatch.ql
java/ql/src/Likely Bugs/Collections/RemoveTypeMismatch.ql
java/ql/src/Likely Bugs/Frameworks/Swing/BadlyOverriddenAdapter.ql
java/ql/src/Likely Bugs/Likely Typos/SelfAssignment.ql

https://github.com/github/codeql/pull/20380 didn't quite cut it - there were many more cases of broken performance. This covers most things, I think.

Java: Fix more broken performance.

---

rust/ql/lib/codeql/rust/internal/TypeInference.qll
rust/ql/test/library-tests/type-inference/main.rs
rust/ql/test/library-tests/type-inference/type-inference.expected

We currently infer certain type information for `self` in `fn f(self: Self)` but not for `self` in `fn f(self)` even though the latter is just syntactic sugar for the former. This PR removes that distinction. Just in our tests, that removes 4 spurious types.
The PR uses the word "shorthand" which comes from the Rust reference which uses the terms ["shorthand self"](https://doc.rust-lang.org/reference/items/functions.html#grammar-ShorthandSelf) and ["shorthand syntax"](https://doc.rust-lang.org/stable/reference/items/associated-items.html#r-associated.fn.method.self-pat-shorthands).
The logic for inferring the type of a shorthand self parameters is now included inside `inferAnnotatedType` which I think makes sense as there's explicit annotations right beneath the sugar.
The [first DCA …

Rust: Infer certain type for shorthand `self`

---

cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll
cpp/ql/src/Security/CWE/CWE-295/SSLResultNotChecked.ql

The `cpp/certificate-not-checked` query had two unnecessary complications:
1. It was reinventing the `ensuresEqEdge` predicate (which existed on the `IRGuardCondition`, but not in `GuardCondition`)
2. It had explicit handling of `!` and implicit int-to-bool conversions.
This PR fixes both of these problems. (1) is fixed by lifting those `ensures*Edge` from `IRGuardCondition`s to `GuardCondition`s and use those new predicates in the query. (2) can just be removed because of the earlier work we've done on unary guards.
DCA was uneventful

C++: Simplify `cpp/certificate-not-checked`

---

javascript/ql/lib/semmle/javascript/frameworks/xUnit.qll
javascript/ql/test/library-tests/frameworks/xUnit/tests.expected

The XUnit family of library models contained an override of `getFirstToken` and `getLastToken`. Overriding the common definitions was not actually necessary, and induced some dependencies that are problematic for overlay locality.
This PR removes the problematic dependency by introducing separate root-defs for the custom interpretation of these predicates.

JS: Avoid overriding Expr predicates in xUnit.qll

---

cpp/ql/src/Critical/ScanfChecks.qll

Another preparation for adopting the shared guards library.

C++: Cleanup `ScanfChecks.qll`

---

javascript/ql/src/Security/CWE-116/IncompleteMultiCharacterSanitization.qhelp

This change corrects the spelling of "occurrences" in the Incomplete Multi-Character Sanitization documentation. This fix aims to improve clarity and ensure that the documentation accurately reflects the intended terminology.

javascript: Fix spelling error in documentation

---

shared/controlflow/codeql/controlflow/Guards.qll

This fixes a performance problem when switching C/C++ to the shared guards library.
The Rust CI failure is (obviously) unrelated.

Shared: Remove antijoin from `Guards.qll`

---

cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/fields/dataflow-consistency.expected
cpp/ql/test/library-tests/dataflow/models-as-data/consistency.expected
cpp/ql/test/library-tests/syntax-zoo/dataflow-consistency.expected
javascript/ql/test/library-tests/FlowSummary/DataFlowConsistency.expected
shared/dataflow/codeql/dataflow/internal/DataFlowImplConsistency.qll

Stops reporting local flow edges between post-update nodes as a consistency errors. Such flow tends to occur when parameters are used as callback arguments in a flow summary.
E.g fixes the consistency errors observed after adding the new flow summaries in https://github.com/github/codeql/pull/20375.

DataFlow: Permit local flow between post-update nodes

---

javascript/ql/lib/change-notes/2025-09-15-promisifications.md
javascript/ql/lib/ext/call-me-maybe.model.yml
javascript/ql/lib/semmle/javascript/ApiGraphs.qll
javascript/ql/lib/semmle/javascript/Promises.qll
javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll
javascript/ql/lib/semmle/javascript/dataflow/PromisifyFlow.qll
javascript/ql/test/query-tests/Security/CWE-078/CommandInjection/CommandInjection.expected
javascript/ql/test/query-tests/Security/CWE-078/CommandInjection/promisification.js

Added modeling for the following promisification related packages:
- [@gar/promisify](https://www.npmjs.com/package/@gar/promisify)
- [es6-promisify](https://www.npmjs.com/package/es6-promisify)
- [util.promisify](https://www.npmjs.com/package/util.promisify)
- [thenify-all](https://www.npmjs.com/package/thenify-all)
- [call-me-maybe](https://www.npmjs.com/package/call-me-maybe)
- [@google-cloud/promisify](https://www.npmjs.com/package/@google-cloud/promisify)
- [util-promisify](https://www.npmjs.com/package/util-promisify)

JS: Promisification library modeling and enhance flow

---

csharp/ql/lib/semmle/code/csharp/controlflow/Guards.qll
csharp/ql/src/change-notes/2025-09-17-nullguard-pattern.md
csharp/ql/test/query-tests/Nullness/E.cs
csharp/ql/test/query-tests/Nullness/Implications.expected
csharp/ql/test/query-tests/Nullness/NullCheck.expected
csharp/ql/test/query-tests/Nullness/NullMaybe.expected

Patterns like `x is (string or null)` and `x is not string` were being identified as null guards in the wrong branch.

C#: Bugfix for nullguards for complex patterns.

---

javascript/ql/integration-tests/query-suite/javascript-code-quality-extended.qls.expected
javascript/ql/integration-tests/query-suite/not_included_in_qls.expected
javascript/ql/src/Comments/CommentedOutCode.ql
javascript/ql/src/Comments/TodoComments.ql
javascript/ql/src/DOM/Alert.ql
javascript/ql/src/Declarations/RedeclaredVariable.ql
javascript/ql/src/Declarations/UnusedParameter.ql
javascript/ql/src/LanguageFeatures/ArgumentsCallerCallee.ql
javascript/ql/src/LanguageFeatures/DebuggerStatement.ql
javascript/ql/src/LanguageFeatures/Eval.ql
javascript/ql/src/Performance/ReassignParameterAndUseArguments.ql
javascript/ql/src/RegExp/BackspaceEscape.ql
javascript/ql/src/Statements/ImplicitReturn.ql
javascript/ql/src/Statements/InconsistentReturn.ql

In this PR we add most `medium` precision queries to the `codeql-quality-extended` suite, with the exception of
- `js/summary/taint-sources` and `js/summary/taint-sinks` which highlights potential sources and sinks (look like debugging queries).
- It appears that none of the `medium` precision queries results in an overwhelming number of alerts.
- Adding the `medium` precision queries (on top of `high` and `very-high`) only increases analysis time around 5%.

JS: Add most `medium` precision queries to the `code-quality-extended` suite. 

---

rust/ql/test/library-tests/dataflow/sources/InlineFlow.expected
rust/ql/test/library-tests/dataflow/sources/InlineFlow.ql

Makes it much easier to debug the test case.

Rust: Convert data flow test to `@kind path-problem`

---

java/ql/lib/semmle/code/java/regex/RegexFlowConfigs.qll

With this the regex parsing becomes local.
The assumption is that strings in the base don't become regexs or stop being regexs. From what I have seen that doesn't seem likely.

Jave: Use force local to make parsing local after global regex finding.

---

rust/ql/lib/codeql/rust/internal/PathResolution.qll
rust/ql/lib/utils/test/PathResolutionInlineExpectationsTest.qll
rust/ql/test/library-tests/path-resolution/main.rs
rust/ql/test/library-tests/path-resolution/path-resolution.expected
rust/ql/test/library-tests/path-resolution/proc_macro.rs
rust/ql/test/query-tests/security/CWE-696/BadCTorInitialization.expected

Note, since `getImmediateParent` finds the enclosing `ItemNode` wherever it may be, simply removing items that have an expanded macro attribute is enough to enable path resolution to find things in inside the expansion.
Going per-commit shows a bug that my first approach introduced, and then a test and fix for that.

Rust: Account for attribute expansions in path resolution

---

cpp/ql/lib/semmle/code/cpp/dataflow/internal/FlowSummaryImpl.qll
csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll
go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll
java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSummaryPrivate.qll
python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll
ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
rust/ql/lib/change-notes/2025-09-19-parameter-mad.md
rust/ql/lib/codeql/rust/dataflow/internal/DataFlowImpl.qll
rust/ql/lib/codeql/rust/dataflow/internal/FlowSummaryImpl.qll
rust/ql/lib/utils/test/InlineFlowTest.qll
rust/ql/test/library-tests/dataflow/models/CONSISTENCY/PathResolutionConsistency.expected
rust/ql/test/library-tests/dataflow/models/main.rs
rust/ql/test/library-tests/dataflow/models/models.expected
rust/ql/test/library-tests/dataflow/models/models.ext.yml
rust/ql/test/library-tests/dataflow/sources/InlineFlow.expected
rust/ql/test/library-tests/dataflow/sources/web_frameworks.rs
rust/ql/test/query-tests/security/CWE-918/Cargo.lock
rust/ql/test/query-tests/security/CWE-918/RequestForgery.expected
rust/ql/test/query-tests/security/CWE-918/options.yml
rust/ql/test/query-tests/security/CWE-918/request_forgery_tests.rs
shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll

This PR adds support for MaD sources with an `Argument[_].Parameter[_]` access path. This corresponds to sources that pass tainted data to a callback/function.
The implementation is my interpretation of a comment on Slack by @hvitved. My understanding is that this is not necessarily the long-term ideal way to implement this, but it is a quick way to give us something that works and that lets us write the models that we want to write for Rust.
[The DCA report](https://github.com/github/codeql-dca-main/issues/31579) looks good. Taint reach triples on `rust-vulnerable-apps` which makes sense as it uses Warp for which we now have working models.

Rust, shared: Support `Parameter` in source MaD models

---

go/extractor/util/registryproxy.go
go/extractor/util/registryproxy_test.go

This PR modifies the Go autobuilder/extractor to support `git_source` private registry configurations, in addition to the `goproxy_server` configurations that were already supported.
In https://github.com/github/codeql-action/pull/3079, we modified the CodeQL Action so that `git_source` configurations are now propagated to the Go autobuilder/extractor.
With the changes in this PR, if a `git_source` configuration is provided, we set `GOPRIVATE` to include a pattern for the hostname provided in the configuration. The `GOPRIVATE` variable instructs `go` which packages should not be fetched via a `GOPROXY` (whether it's the default one or a custom one). For example, if the `git_source` configuration is for `https://github.com/foo`, then we'd set `GOPRIVATE=github.com/foo*`.
This is a …

Go: Support `git_source`

---

.gitignore

Add `.orig` files to the `.gitignore`.  I believe these files are sometimes left over by `git mergetool` and we don't want them adding to the repo.

Add .orig files to the .gitignore.

---

javascript/ql/src/CHANGELOG.md
javascript/ql/src/change-notes/released/2.1.0.md

This pull request updates the documentation to acknowledge the original contributor of the "Permissive CORS configuration" query after its promotion from experimental to the default security suite.

Attribute `js/cors-permissive-configuration` to original author

---

docs/codeql/reusables/supported-frameworks.rst

Update [Supported languages and frameworks](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/) with some libraries we've recently added models for.

Rust: Update Supported languages and frameworks

---

java/ql/integration-tests/java/evaluation-to-constant-errortype/ConstantExpAppearsNonConstant.expected
java/ql/integration-tests/java/evaluation-to-constant-errortype/ConstantExpAppearsNonConstant.qlref
java/ql/integration-tests/java/evaluation-to-constant-errortype/Test.java
java/ql/integration-tests/java/evaluation-to-constant-errortype/test.py
java/ql/src/Likely Bugs/Arithmetic/ConstantExpAppearsNonConstant.ql

This PR fixes the FPs described in the issue linked below.
Closes: http://github.com/github/codeql-java-team/issues/425
DCA Nightly Buildless: https://github.com/github/codeql-dca-main/issues/31838
DCA Nightly: https://github.com/github/codeql-dca-main/issues/31839

Java: Fix false positives in evaluation-to-constant query for ErrorType

---

java/ql/src/Likely Bugs/Concurrency/StartInConstructor.ql
java/ql/test/query-tests/StartInConstructor/Test.java

Quick drive-by FP fix found while triaging autofixes.

Java: note that classes with entirely private constructors can't be subclassed

---

go/ql/lib/change-notes/2025-09-30-fewer-safe-urls.md
go/ql/lib/semmle/go/security/OpenUrlRedirectCustomizations.qll
go/ql/lib/semmle/go/security/RequestForgeryCustomizations.qll
go/ql/lib/semmle/go/security/SafeUrlFlow.qll
go/ql/lib/semmle/go/security/SafeUrlFlowCustomizations.qll
go/ql/test/library-tests/semmle/go/security/SafeUrlFlow/SafeUrlFlow.expected
go/ql/test/library-tests/semmle/go/security/SafeUrlFlow/SafeUrlFlow.go
go/ql/test/library-tests/semmle/go/security/SafeUrlFlow/SafeUrlFlow.ql
go/ql/test/library-tests/semmle/go/security/SafeUrlFlow/SafeUrlFlow.qlref

This didn't have any tests, so I generated some using copilot. While fixing up the tests I noticed a latent bug - a sanitizer had been incorrectly specified. This means that some URLs were considered safe when they shouldn't have been, so we may find more results now that it is fixed.

Go: Add tests for SafeUrlFlow, and fix a latent bug

---

cpp/ql/lib/semmle/code/cpp/Element.qll

Before (when running `cpp/inconsistent-null-check` on zeek/spicy):
```
Evaluated non-recursive predicate Element::Element.getFile/0#dispred#536cb5f3#bb@f6f5329i in 182326ms (size: 50437). Evaluated relational algebra for predicate Element::Element.getFile/0#dispred#536cb5f3#bb@f6f5329i with tuple counts:
2029351   ~0%    {2} r1 = SCAN `Expr::Expr.getLocation/0#dispred#0a3d90c6` OUTPUT In.1, In.0
2029351   ~0%    {2}    | JOIN WITH `Location::Location.getStartLine/0#d54f9e6c` ON FIRST 1 OUTPUT Rhs.1, Lhs.1
1168789   ~0%    {2}    | JOIN WITH `InconsistentCheckReturnNull::assertInvocation/2#b2a4c9e3_10#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1
5533128288   ~0%    {3}    | JOIN WITH `Location::Location.getContainer/0#9edabfb6_10#join_rhs` ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Lhs.0
50413   ~0% …
```

C++: Fix bad magic on `Element.getFile`

---

java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/ExtractionErrors.qlref
java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/app/.mvn/wrapper/maven-wrapper.properties
java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/app/mvnw
java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/app/mvnw.cmd
java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/app/pom.xml
java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/app/src/main/java/testmaven/Test.java
java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/methods.expected
java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/methods.ql
java/ql/integration-tests/java/maven_3_fetch_maven_4_wrapper/test.py

Java: Integration tests for Maven 4

---

java/ql/integration-tests/java/buildless-dependency-different-repository/test.py

The `buildless-dependency-different-repository` test was timing out when trying to fetch Maven dependencies from local HTTP servers. Turns out Python's `http.server` on newer macOS versions binds only to IPv6 by default, but Maven tries to connect via IPv4. 
Added `-b localhost` to the server commands to make them listen on both IPv4 and IPv6, just like we already do in the `buildless-snapshot-repository` test.

Java: Fix buildless test HTTP server binding on macOS26
