github/codeql

cpp/ql/test/.project, cpp/ql/test/.qlpath
These are adapted from `javascript/ql/test`.
=> C++: Create Eclipse project for cpp/ql/test/

change-notes/1.18/analysis-javascript.md, javascript/ql/src/semmle/javascript/security/SensitiveActions.qll, javascript/ql/src/semmle/javascript/security/dataflow/MissingRateLimiting.qll, javascript/ql/test/query-tests/Security/CWE-770/MissingRateLimiting.expected, javascript/ql/test/query-tests/Security/CWE-770/tst.js
Some minor improvements for ` js/missing-rate-limiting`, inspired by concrete FPs and TPs.
=> JavaScript: Improve js/missing-rate-limiting

change-notes/1.18/analysis-javascript.md, javascript/ql/src/javascript.qll, javascript/ql/src/semmle/javascript/frameworks/ComposedFunctions.qll, javascript/ql/test/library-tests/frameworks/ComposedFunctions/compose.expected, javascript/ql/test/library-tests/frameworks/ComposedFunctions/compose.ql, javascript/ql/test/library-tests/frameworks/ComposedFunctions/tst.js
Copy of #115 which was meant for 1.18 but was left behind when the rc was branched.
=> JS: model composed functions (RC)

change-notes/1.19/analysis-javascript.md, cpp/ql/src/Likely Bugs/Arithmetic/IntMultToLong.ql, cpp/ql/src/semmle/code/cpp/Declaration.qll, cpp/ql/src/semmle/code/cpp/Function.qll, cpp/ql/src/semmle/code/cpp/Namespace.qll, cpp/ql/src/semmle/code/cpp/Type.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/raw/internal/IRBlockConstruction.qll, cpp/ql/test/library-tests/namespaces/namespaces/decls.expected, cpp/ql/test/library-tests/namespaces/namespaces/decls.ql, cpp/ql/test/library-tests/namespaces/namespaces/namespaces.cpp, cpp/ql/test/query-tests/Likely Bugs/Arithmetic/IntMultToLong/IntMultToLong.expected, javascript/ql/src/semmle/javascript/security/dataflow/RegExpInjection.qll, javascript/ql/test/query-tests/Security/CWE-730/RegExpInjection.expected, javascript/ql/test/query-tests/Security/CWE-730/RegExpInjection.js
This merges master into next but first reverts #155 because #155 reverts a commit from master that's supposed to remain on next.
=> Merge master to next

java/ql/src/semmle/code/java/frameworks/Mockito.qll
This removes some false positives in `CloseSql`.
=> Java: Add Mockito.verify to MockitoMockMethod.

change-notes/1.19/analysis-javascript.md, javascript/ql/src/Security/CWE-352/MissingCsrfMiddleware.ql, javascript/ql/test/query-tests/Security/CWE-352/MissingCsrfMiddleware.expected, javascript/ql/test/query-tests/Security/CWE-352/lusca_example.js
While going over a huge amount of CSRF results on lgtm.com I noticed some false positives from projects using `lusca`.
=> JS: recognize CSRF middleware from lusca

cpp/ql/src/definitions.qll
This should be merged together with the corresponding internal PR. The tests on this PR can be ignored.
=> Merge rc/1.18 into master.

cpp/ql/src/META-INF/MANIFEST.MF, csharp/ql/src/META-INF/MANIFEST.MF, java/ql/src/META-INF/MANIFEST.MF, javascript/ql/src/META-INF/MANIFEST.MF
=> Version: Bump to 1.18.0 release.

javascript/externs/web/w3c_dom1.js
cf. https://developer.mozilla.org/en-US/docs/Web/API/DOMException/DOMException
Fixes #256.
=> JavaScript: Update model of `DOMException`.

csharp/config/tracer/linux/csharp-compiler-settings, csharp/config/tracer/linux/extract-csharp.sh, csharp/extractor/Semmle.Extraction.CSharp/Analyser.cs, csharp/extractor/Semmle.Extraction.CSharp/CompilerVersion.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor.cs, csharp/extractor/Semmle.Extraction/Context.cs, csharp/extractor/Semmle.Extraction/TrapWriter.cs
=> C#: Pass `--compiler` flag to extractor on Linux

change-notes/1.19/analysis-java.md, java/ql/src/Security/CWE/CWE-089/SqlInjectionLib.qll, java/ql/src/semmle/code/java/frameworks/Hibernate.qll, java/ql/src/semmle/code/java/frameworks/MyBatis.qll, java/ql/src/semmle/code/java/frameworks/SpringJdbc.qll
This adds support for the Spring JDBC, MyBatis, and Hibernate frameworks in the SQL injection queries.
=> Java: Add additional SQL injection sinks.

change-notes/1.19/analysis-java.md, java/ql/src/semmle/code/java/dataflow/FlowSources.qll, java/ql/src/semmle/code/java/frameworks/SpringWeb.qll
Parameters annotated with certain Spring Web annotations are added as remote user inputs.
=> Java: Add remote user input sources for Spring servlets.

csharp/ql/src/semmle/code/csharp/commons/Assertions.qll
=> C#: Improve performance in `ForwarderAssertMethod`

cpp/ql/src/semmle/code/cpp/commons/Buffer.qll
Backport of https://github.com/Semmle/ql/pull/368 currently being discussed with a customer.
=> C++: Backport "Improve memberMayBeVarSize" to rc/1.18

csharp/extractor/Semmle.Extraction.CSharp/Analyser.cs
Fixes a bug introduced in #391.
=> C#: Fix an ArgumentNullException.

cpp/ql/src/Critical/InconsistentNullnessTesting.cpp, cpp/ql/src/Critical/OverflowCalculated.cpp
Correct a couple of pieces of example code I happened upon.
=> CPP: Minor corrections to examples

java/ql/src/Violations of Best Practice/Dead Code/DeadStoreOfLocalUnread.qhelp, java/ql/src/Violations of Best Practice/Dead Code/DeadStoreOfLocalUnread.ql, java/ql/src/Violations of Best Practice/Dead Code/LocalInitialisedButNotUsed.qhelp, java/ql/src/Violations of Best Practice/Dead Code/LocalInitialisedButNotUsed.ql, java/ql/src/Violations of Best Practice/Dead Code/UnusedLocal.qhelp, java/ql/src/Violations of Best Practice/Dead Code/UnusedLocal.ql, java/ql/src/Violations of Best Practice/legacy/InexactVarArg.java, java/ql/src/Violations of Best Practice/legacy/InexactVarArg.qhelp
This PR ensures that all queries with a CWE tag have a reference section, ensuing that the automatic CWE references can be added. It also updates some wording for greater consistency.
=> Java: Update qhelp for queries with CWE tags (SD-2779)

javascript/externs/README.md, javascript/externs/lib/bdd.js, javascript/externs/web/w3c_rtc.js
Inspired by findings at a customer's.
A (limited) dist-compare showed no impact on performance or results.
=> JavaScript: Add a few more externs.

javascript/config/suites/javascript/maintainability-more
c.f. https://git.semmle.com/Semmle/code/pull/29055 @xiemaisi
=> JS: rename query file in suite

cpp/ql/src/jsf/4.21 Operators/AV Rule 165.ql, cpp/ql/test/query-tests/jsf/4.21 Operators/AV Rule 165/AV Rule 165.expected, cpp/ql/test/query-tests/jsf/4.21 Operators/AV Rule 165/AV Rule 165.qlref, cpp/ql/test/query-tests/jsf/4.21 Operators/AV Rule 165/test.c
While tagging the JSF queries I had to run some of them, and a few easy fixes came up I couldn't resist.  There's a lot more I could have done but these queries are not a priority for development at the moment.
=> CPP: Fix AV Rule 165

cpp/ql/src/JPL_C/LOC-3/Rule 13/LimitedScopeFunction.ql, cpp/ql/src/Power of 10/Rule 6/VariableScopeTooLarge.ql, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFunction/LimitedScopeFunction.expected, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFunction/LimitedScopeFunction.qlref, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFunction/test.c, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFunction/test.h
Another query that came to my attention whilst adding tags.  Quickly added a test and removed some FPs.
=> CPP: Fix Limitedscopefunction.ql

csharp/ql/src/semmle/code/csharp/dataflow/SSA.qll
Simplify liveness analysis by avoiding the two extra copies of `liveAtRank()` (and other auxiliary predicates) for fields/captured variables analysis.
In addition to simplifying the logic, this also has a positive performance impact, for example:
Before:
```
SsaDef.ql-13:SSA::Ssa::FieldOrPropsImpl::liveAtRank#ffff ........................... 5m16s (executed 13561 times)
SsaDef.ql-13:SSA::Ssa::FieldOrPropsImpl::updateCandidate#ffff ...................... 1m20s
SsaDef.ql-13:SSA::Ssa::FieldOrPropsImpl::liveAfterUpdateCandidate#ff ............... 35.5s
SsaDef.ql-13:SSA::Ssa::FieldOrPropsImpl::refRankExt#ffff#join_rhs .................. 32.1s
SsaDef.ql-13:SSA::Ssa::FieldOrPropsImpl::refRankExt#ffff ........................... 28.7s
SsaDef.ql-13:SSA::Ssa::FieldOrPropsImpl::refExt#fff …
```
=> C#: Refactor SSA liveness logic

cpp/ql/test/library-tests/opts/main.cpp, cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnCstrOfLocalStdString/ReturnCstrOfLocalStdString.expected, cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnCstrOfLocalStdString/test.cpp
Make test cases use standard declarations.
=> CPP: Clean up some test code.

csharp/ql/src/semmle/code/csharp/controlflow/ControlFlowGraph.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/BasicBlockDominance.expected, csharp/ql/test/library-tests/controlflow/graph/BooleanNode.expected, csharp/ql/test/library-tests/controlflow/graph/ConditionBlock.expected, csharp/ql/test/library-tests/controlflow/graph/ConditionalFlow.expected, csharp/ql/test/library-tests/controlflow/graph/Conditions.cs, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/ElementGraph.expected, csharp/ql/test/library-tests/controlflow/graph/EntryElement.expected, csharp/ql/test/library-tests/controlflow/graph/EntryPoint.expected, csharp/ql/test/library-tests/controlflow/graph/ExitElement.expected, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected
~This PR is based on https://github.com/Semmle/ql/pull/489, so only the last three commits need reviewing.~
@calumgrant
=> C#: Fix two bugs in Boolean CFG splitting

change-notes/1.19/analysis-cpp.md, cpp/ql/src/JPL_C/LOC-3/Rule 13/LimitedScopeFile.ql, cpp/ql/src/Power of 10/Rule 6/GlobalCouldBeStatic.ql, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFile/LimitedScopeFile.expected, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFile/LimitedScopeFile.qlref, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFile/file1.c, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFile/file1.h, cpp/ql/test/query-tests/JPL_C/LOC-3/Rule 13/LimitedScopeFile/file2.c
Another query that came to my attention whilst adding tags.  Quickly added a test and removed some FPs.
=> CPP: Fix Limitedscopefile.ql

cpp/ql/src/Best Practices/Magic Constants/MagicNumbersUseConstant.ql, cpp/ql/src/Best Practices/Magic Constants/MagicStringsUseConstant.ql, cpp/ql/src/Best Practices/NVI.ql, cpp/ql/src/Best Practices/NVIHub.ql, cpp/ql/src/Best Practices/Unused Entities/UnusedIncludes.ql, cpp/ql/src/Likely Bugs/Memory Management/Padding/More64BitWaste.ql, cpp/ql/src/Likely Bugs/Memory Management/Padding/NonPortablePrintf.ql, cpp/ql/src/Likely Bugs/Memory Management/Padding/Suboptimal64BitType.ql
Add `@tags` to some queries in 'Best Practices' and 'Likely Bugs' that were lacking them.
In some cases I've also added `@precision` and tweaked `@problem.severity`.
=> CPP: Query tags 1

cpp/ql/src/Architecture/General Top-Level Information/GeneralStatistics.qhelp
@geoffw0 - this is the file that I seem to have overlooked in the earlier PR.
=> C++: Update qhelp for consistency

cpp/ql/src/semmle/code/cpp/AutogeneratedFile.qll
Fixes https://jira.semmle.com/browse/CPP-296.
=> CPP: Fix false positive from AutoGeneratedFile.qll.

cpp/ql/test/library-tests/defuse/addressOf.cpp, cpp/ql/test/library-tests/defuse/definitionUsePair.expected, cpp/ql/test/library-tests/defuse/isAddressOfAccess.expected, cpp/ql/test/library-tests/defuse/useOfVar.expected, cpp/ql/test/library-tests/defuse/useOfVarActual.expected, cpp/ql/test/library-tests/defuse/useUsePair.expected
It looks like this is what it was originally intended to do.
=> C++: Tweak the defuse test

python/ql/src/semmle/python/dependencies/Dependencies.qll
Fixes a cartesian product accidentally introduced a few months back.
=> Python: Fix performance regression in dependency analysis

change-notes/1.19/analysis-javascript.md
Change note for modifications to UselessConditional in https://github.com/Semmle/ql/pull/395 and https://github.com/Semmle/ql/pull/404. One of them adds more results, the other removes some.
=> JS: add change note for UselessConditional.ql

python/ql/src/.vs/VSWorkspaceSettings.json
Moved from internal repository.
=> Python: Add QL for VS workspace settings file.

python/ql/src/semmle/dataflow/SSA.qll, python/ql/src/semmle/dataflow/SsaCompute.qll, python/ql/src/semmle/python/pointsto/Base.qll, python/ql/src/semmle/python/security/TaintTracking.qll
…by refactoring ADT to match class hierarchy making it more transparent to the optimizer.
=> Python : Speed up ESSA computation

python/ql/src/semmle/python/pointsto/PointsTo.qll
… by factoring out handling of tuples in class tests.
This is a cut down version of https://github.com/Semmle/ql/pull/578 without the slight change in semantics that PR had.
=> Python points-to: Improve performance of subclass test predicates on large DBs

javascript/ql/test/query-tests/Security/CWE-754/UnvalidatedDynamicMethodCall.expected
Caused by interaction between https://github.com/Semmle/ql/pull/558 and https://github.com/Semmle/ql/pull/555.
=> JavaScript: Fix expected test output.

java/ql/src/semmle/code/java/Annotation.qll
As per corresponding internal PR.
=> Java: account for change to field annotation extraction

javascript/ql/src/Declarations/MixedStaticInstanceThisAccess.ql
This query had regressed rather badly since 1.18 on VSCode (4s -> 34s). Refactoring the `isLocalMethodAccess` predicate to expose the method kind as a parameter helps the optimiser pick a better join order, which gets us back down to 6s, which is reasonable, considering that the query has become more complex since 1.18.
=> JavaScript: Fix performance regression in `MixedStaticInstanceThisAccess`.

docs/query-help-style-guide.md
@felicity-semmle I think this is ready for a quick editorial review now, Thanks.
=> Query help style guide: editorial review

javascript/ql/src/AngularJS/DuplicateDependency.ql, javascript/ql/src/AngularJS/RepeatedInjection.ql, javascript/ql/src/AngularJS/UnusedAngularDependency.ql, javascript/ql/test/query-tests/AngularJS/DuplicateDependency/DuplicateDependency.expected, javascript/ql/test/query-tests/AngularJS/DuplicateDependency/duplicates.js, javascript/ql/test/query-tests/AngularJS/RepeatedInjection/RepeatedInjection.expected, javascript/ql/test/query-tests/AngularJS/RepeatedInjection/repeated-injection.js, javascript/ql/test/query-tests/AngularJS/UnusedAngularDependency/UnusedAngularDependency.expected, javascript/ql/test/query-tests/AngularJS/UnusedAngularDependency/unused-angular-dependency.js
Makes use of `RestrictedLocations::FirstLineOf` for three AngularJS function alerts.
=> JS: improve Angularjs alert locations

change-notes/1.20/analysis-csharp.md, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/ArrayCreation.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Factory.cs, csharp/ql/test/library-tests/csharp7.3/ArrayCreations.expected, csharp/ql/test/library-tests/csharp7.3/ArrayCreations.ql, csharp/ql/test/library-tests/csharp7.3/ArrayElements.expected, csharp/ql/test/library-tests/csharp7.3/ArrayElements.ql, csharp/ql/test/library-tests/csharp7.3/csharp73.cs, javascript/ql/src/Statements/UselessConditional.ql, javascript/ql/src/semmle/javascript/dataflow/Configuration.qll, javascript/ql/src/semmle/javascript/dataflow/Nodes.qll, javascript/ql/test/library-tests/Receiver/GetReceiver.expected, javascript/ql/test/library-tests/Receiver/GetReceiver.ql, javascript/ql/test/library-tests/Receiver/tst.js, javascript/ql/test/query-tests/Statements/UselessConditional/UselessConditional.expected, javascript/ql/test/query-tests/Statements/UselessConditional/UselessConditional.js
=> Merge master into next.

java/ql/src/semmle/code/java/dataflow/TaintTracking.qll
=> Remove a duplicated predicate.

change-notes/1.20/analysis-javascript.md, javascript/ql/src/semmle/javascript/Concepts.qll, javascript/ql/src/semmle/javascript/frameworks/Express.qll, javascript/ql/src/semmle/javascript/security/dataflow/TaintedPath.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-022/tainted-sendFile.js
Should fix some false positives seen at a customer.
=> JS: Recognize 'root' option in Express res.sendFile

csharp/ql/src/semmle/code/csharp/dispatch/Dispatch.qll
In an earlier version of the evaluator, `fastTC` would mistakenly perform a number of explicit recursion steps, and consequently `boundedFastTC` could be used as a workaround. As this is no longer the case, there is no reason to use `boundedFastTC`.
=> C#: Replace a use of `boundedFastTC` with `fastTC`

cpp/ql/src/semmle/code/cpp/controlflow/ControlFlowGraph.qll
This speeds up the `reachable` predicate by about 30% on the dbs I've tested: comdb2 and Wireshark. That's significant because `reachable` is one of our slowest predicates.
I've added a comment to try and explain why it improves performance to factor out the base case. You can see the DIL before and after this PR at https://git.semmle.com/gist/jonas/acfc2788805f21d4b397e355098af111. With this change, two things happen: the `@cfgnode#f(n)` check covers only the base case, and the join order is swapped in the recursive case. The join order only changes in `[delta_order]`, which is only used in the first two iterations or so. Notice that `reachableBaseCase` gets inlined into `reachable`, but that happens _after_ the type check is inserted.
=> C++: Factor out `reachable` base case

java/ql/src/Metrics/queries.xml
This should no longer be needed.
=> Java: Remove `Metrics/queries.xml`

change-notes/1.20/analysis-python.md, python/ql/src/Security/CWE-327/InsecureDefaultProtocol.qhelp, python/ql/src/Security/CWE-327/InsecureDefaultProtocol.ql, python/ql/src/Security/CWE-327/InsecureProtocol.qhelp, python/ql/src/Security/CWE-327/InsecureProtocol.ql, python/ql/src/Security/CWE-327/examples/insecure_default_protocol.py, python/ql/src/Security/CWE-327/examples/insecure_protocol.py, python/ql/test/query-tests/Security/CWE-327/InsecureDefaultProtocol.expected, python/ql/test/query-tests/Security/CWE-327/InsecureDefaultProtocol.qlref, python/ql/test/query-tests/Security/CWE-327/InsecureProtocol.expected, python/ql/test/query-tests/Security/CWE-327/InsecureProtocol.py, python/ql/test/query-tests/Security/CWE-327/InsecureProtocol.qlref, python/ql/test/query-tests/Security/CWE-327/options, python/ql/test/query-tests/Security/lib/pyOpenSSL/SSL.py
~Still requires docs and change note. These will be added soon.~
=> Python: Check for insecure versions of SSL and TLS.

python/ql/src/semmle/python/pointsto/PointsTo.qll, python/ql/src/semmle/python/types/ClassObject.qll, python/ql/src/semmle/python/types/ModuleObject.qll, python/ql/src/semmle/python/types/Object.qll
=> Python: Remove some negation from points-to, in preparation for ADT Objects.

cpp/ql/src/Security/CWE/CWE-190/ArithmeticTainted.ql, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/ArithmeticTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/IntegerOverflowTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/test5.cpp
Rework `ArithmeticTainted.ql` so that it will catch issues like line 17 of https://github.com/gsingh93/lgtm-test/blob/master/test.cpp.
=> CPP: Improve ArithmeticTainted.ql

cpp/ql/src/semmle/code/cpp/ir/implementation/raw/internal/TranslatedStmt.qll
Thanks, @aeyerstaylor, for noticing that we missed `TranslatedStmt.qll` when converting the IR construction to use field overrides.
=> C++: Use more field overriding in IR construction

csharp/ql/src/semmle/code/csharp/controlflow/internal/SuccessorType.qll
As suggested here: https://github.com/Semmle/ql/pull/886#discussion_r254634936.
=> C#: Add QL doc to `SuccessorType.qll`

python/ql/src/semmle/python/dataflow/SsaDefinitions.qll, python/ql/src/semmle/python/pointsto/PointsTo.qll, python/ql/src/semmle/python/types/ModuleObject.qll
Better models the changing state of a module as it imported.
Attributes of module are tracked that are not global variables are treated as named attributes of the "$" pseudo variable. ESSA form ensures that all state changes are handled correctly.
=> Python improve import analysis

csharp/ql/src/semmle/code/csharp/controlflow/Guards.qll
Fixes a bad join-order in `Guards::Internal::conditionalAssign#ffff#antijoin_rhs#1`:
```
[2019-01-25 14:12:03] (377s) Starting to evaluate predicate Guards::Internal::conditionalAssign#ffff#antijoin_rhs#1
[2019-01-25 14:20:41] (895s) Tuple counts:
9302551    ~1%     {7} r1 = JOIN ControlFlowGraph::ControlFlow::Internal::PreSsa::Definition::getAPhiInput_dispred#ff WITH Guards::Internal::conditionalAssign#ffff#shared#1 ON ControlFlowGraph::ControlFlow::Internal::PreSsa::Definition::getAPhiInput_dispred#ff.<0>=Guards::Internal::conditionalAssign#ffff#shared#1.<0> OUTPUT FIELDS {ControlFlowGraph::ControlFlow::Internal::PreSsa::Definition::getAPhiInput_dispred#ff.<1>,Guards::Internal::conditionalAssign#ffff#shared#1.<1>,Guards::Internal::conditionalAssign#ffff#shared#1.<2>,Guards::Internal::con …
```
=> C#: Improve join order in `conditionalAssign()`

csharp/autobuilder/Semmle.Autobuild/BuildScript.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/Method.cs, csharp/extractor/Semmle.Extraction.CSharp.Standalone/CsProjFile.cs, csharp/extractor/Semmle.Util/CanonicalPathCache.cs
https://lgtm.com/projects/g/Semmle/ql/alerts?mode=tree&ruleFocus=1506101336230
=> C#: Add some alert suppression comments

README.md
Link to 'Learning QL' material updated in anticipation of further consolidation of QL docs.
=> Update link in readme file

csharp/ql/src/API Abuse/DisposeNotCalledOnException.ql, csharp/ql/src/semmle/code/csharp/controlflow/ControlFlowElement.qll
I have kicked off a dist comparison and will post the results when they are ready.
=> C#: Improve performance of `cs/dispose-not-called-on-throw`

csharp/ql/src/semmle/code/csharp/dataflow/DataFlow.qll
Profiling report [here](https://git.semmle.com/gist/tom/877838a94b64939551df614cd042150c) (internal link).
=> C#: Improve join orders in `DataFlow` module

change-notes/1.20/analysis-python.md, change-notes/1.20/support/python-frameworks.csv, python/ql/src/semmle/python/web/Http.qll, python/ql/src/semmle/python/web/HttpRequest.qll, python/ql/src/semmle/python/web/HttpResponse.qll, python/ql/src/semmle/python/web/bottle/Response.qll, python/ql/src/semmle/python/web/cherrypy/General.qll, python/ql/src/semmle/python/web/cherrypy/Request.qll, python/ql/src/semmle/python/web/cherrypy/Response.qll, python/ql/test/library-tests/web/cherrypy/Sinks.expected, python/ql/test/library-tests/web/cherrypy/Sinks.ql, python/ql/test/library-tests/web/cherrypy/Sources.expected, python/ql/test/library-tests/web/cherrypy/Sources.ql, python/ql/test/library-tests/web/cherrypy/options, python/ql/test/library-tests/web/cherrypy/red.py, python/ql/test/library-tests/web/cherrypy/test.py, python/ql/test/query-tests/Security/lib/cherrypy/__init__.py, python/ql/test/query-tests/Security/lib/cherrypy/_helper.py
Not as full featured as our django or flask support, but covers requests and responses.
=> Python: CherryPy support

csharp/ql/src/Concurrency/UnsafeLazyInitialization.ql, csharp/ql/src/Language Abuse/MissedTernaryOpportunity.ql, csharp/ql/src/Language Abuse/UselessIsBeforeAs.ql, csharp/ql/src/Language Abuse/UselessNullCoalescingExpression.ql, csharp/ql/src/Likely Bugs/NestedLoopsSameVariable.ql, csharp/ql/src/Likely Bugs/SelfAssignment.ql, csharp/ql/src/Performance/UseTryGetValue.ql, csharp/ql/src/semmle/code/csharp/commons/Constants.qll, csharp/ql/src/semmle/code/csharp/commons/StructuralComparison.qll, csharp/ql/src/semmle/code/csharp/controlflow/Guards.qll
Profiling report [here](https://git.semmle.com/gist/tom/bfed5eb1eb7c8a9bbb065354fdf1d733) (internal link).
=> C#: Speedup structural comparison library

cpp/ql/src/Likely Bugs/Conversion/LossyFunctionResultCast.qhelp, cpp/ql/src/Likely Bugs/Likely Typos/FutileParams.qhelp, javascript/ql/src/Security/CWE-116/DoubleEscaping.qhelp
Pointed out by @felicity-semmle.
=> Fix qhelp backticks

cpp/ql/src/Architecture/Refactoring Opportunities/ClassesWithManyFields.qhelp, cpp/ql/src/Architecture/Refactoring Opportunities/ClassesWithManyFields.ql, cpp/ql/test/query-tests/Architecture/Refactoring Opportunities/ClassesWithManyFields/cwmf.expected
(ClassesWithManyFields.{ql,qhelp})
=> [CPP-80] Provide kinder, gentler wording for messages

javascript/ql/test/query-tests/Declarations/DeadStoreOfLocal/DeadStoreOfLocal.expected, javascript/ql/test/query-tests/Declarations/DeadStoreOfLocal/tst.js
See https://jira.semmle.com/browse/ODASA-7844
=> JS: document limitation of js/useless-assignment-to-local

README.md
=> Make licensing text in README.md more generic

change-notes/1.20/analysis-python.md
Needs links to full documentation added.
=> Python: Add change note for new taint-tracking configuration API.

cpp/ql/src/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql, cpp/ql/src/semmle/code/cpp/security/Encryption.qll
=> C++: Fix performance of BrokenCryptoAlgorithm.ql

change-notes/1.21/analysis-cpp.md, cpp/ql/src/jsf/4.10 Classes/AV Rule 79.ql, cpp/ql/test/query-tests/jsf/4.10 Classes/AV Rule 79/AV Rule 79.expected, cpp/ql/test/query-tests/jsf/4.10 Classes/AV Rule 79/Variants.cpp
See https://discuss.lgtm.com/t/false-positive-resource-not-released-in-destructor/1938
=> CPP: Fix Resource not released in destructor FP

change-notes/1.21/analysis-javascript.md, javascript/ql/src/semmle/javascript/security/dataflow/UrlConcatenation.qll, javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/ClientSideUrlRedirect.expected, javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/tst10.js, javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/ServerSideUrlRedirect.expected, javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/express.js
Fixes some FPs I've seen. [Evaluation](https://git.semmle.com/asger/dist-compare-reports/tree/domitian.ti.semmle.com_1553764222664) looks fine.
=> JS: More sanitizing prefix edges for URL redirection queries

python/ql/src/Security/CWE-094/CodeInjection.ql
=> Fix CWE tag for Code injection query.

change-notes/1.21/analysis-cpp.md, cpp/ql/src/Security/CWE/CWE-676/PotentiallyDangerousFunction.qhelp, cpp/ql/src/Security/CWE/CWE-676/PotentiallyDangerousFunction.ql, cpp/ql/test/query-tests/Security/CWE/CWE-676/semmle/PotentiallyDangerousFunction/PotentiallyDangerousFunction.expected, cpp/ql/test/query-tests/Security/CWE/CWE-676/semmle/PotentiallyDangerousFunction/test.c
(following on from https://github.com/Semmle/ql/pull/842#discussion_r252579880)
=> CPP: Add variants to PotentiallyDangerousFunction.ql

change-notes/1.21/analysis-javascript.md, javascript/ql/src/semmle/javascript/frameworks/Express.qll, javascript/ql/test/library-tests/frameworks/Express/src/routesetups.js, javascript/ql/test/library-tests/frameworks/Express/tests.expected
This is a bit of cleanup for Express. More route handlers are now detected, primarily due to additional use of dataflow for router objects.
Evaluation is ongoing.
=> JS: Express cleanup and more route handlers

javascript/ql/src/Customizations.qll, javascript/ql/src/javascript.qll
Somewhat analogous to the `Options.qll` module in C++; see module comments for further explanation.
Would have been useful at &lt;customer name redacted&gt; and will probably come in handy in future.
=> JavaScript: Add an (empty) `Customizations.qll` module.

cpp/ql/test/query-tests/Likely Bugs/OO/IncorrectConstructorDelegation/IncorrectConstructorDelegation.expected, cpp/ql/test/query-tests/Likely Bugs/OO/IncorrectConstructorDelegation/IncorrectConstructorDelegation.qlref, cpp/ql/test/query-tests/Likely Bugs/OO/IncorrectConstructorDelegation/test.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/OverflowBuffer.expected, cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/tests.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-772/semmle/tests-memory/test.cpp, cpp/ql/test/query-tests/jsf/4.24 Control Flow Structures/AV Rule 186/AV Rule 186.expected, cpp/ql/test/query-tests/jsf/4.24 Control Flow Structures/AV Rule 186/AV Rule 186.qlref, cpp/ql/test/query-tests/jsf/4.24 Control Flow Structures/AV Rule 186/test.c
A small collection of new tests and test cases I've accumulated in recent months, generally while investigating one thing or another that turned out not to require a code change PR.  Nevertheless, with these tests already written I think we might as well add them to our suite.
=> CPP: New test cases

javascript/ql/src/Security/CWE-116/IncompleteSanitization.ql, javascript/ql/test/query-tests/Security/CWE-116/IncompleteSanitization/IncompleteSanitization.expected, javascript/ql/test/query-tests/Security/CWE-116/IncompleteSanitization/tst.js, python/ql/src/semmle/python/dataflow/DataFlow.qll, python/ql/src/semmle/python/security/TaintTracking.qll, python/ql/test/library-tests/taint/dataflow/Config.qll, python/ql/test/library-tests/taint/dataflow/Dataflow.expected, python/ql/test/library-tests/taint/dataflow/Dataflow.ql, python/ql/test/library-tests/taint/dataflow/TestNode.expected, python/ql/test/library-tests/taint/dataflow/TestNode.ql, python/ql/test/library-tests/taint/dataflow/test.py
Fixes conflict in `/javascript/ql/test/query-tests/Security/CWE-116/IncompleteSanitization/IncompleteSanitization.expected`.
=> Mergeback: rc/1.20 into Semmle/master

javascript/extractor/lib/typescript/src/ast_extractor.ts, javascript/extractor/lib/typescript/src/main.ts
Cherry-pick of #1247 to the RC branch.
=> TS: Dont extract redirect SourceFiles

cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll
The "does not" seems implausible considering the name and body of the predicate.
=> CPP: Fix two doc comments.

cpp/ql/src/Likely Bugs/RedundantNullCheckSimple.cpp, cpp/ql/src/Likely Bugs/RedundantNullCheckSimple.qhelp
Add basic qhelp for RedundantNullCheckSimple.ql (which isn't yet on LGTM or any dashboard, but still, it should have qhelp).
=> CPP: Add qhelp for RedundantNullCheckSimple.ql.

cpp/ql/src/Critical/LargeParameter.ql, cpp/ql/test/query-tests/Critical/LargeParameter/LargeParameter.expected, cpp/ql/test/query-tests/Critical/LargeParameter/test.cpp
See:
- https://discuss.lgtm.com/t/bad-advice-large-object-passed-by-value/2026
- https://github.com/Semmle/ql/issues/1269
I've added tests intended to cover these concerns, and a proposed fix.  I encourage discussion of the fix as (1) I'm not confident these exclusions are exactly the right call and (2) the implementation is untidy.  Suggestions are welcome.
=> CPP: Tests and changes for LargeParameter.ql

javascript/ql/src/semmle/javascript/frameworks/Express.qll
This works fine on master but together with some other changes this caused magic to introduce a cartesian product
=> JS: Fix lurking cartesian product in Express

csharp/ql/src/semmle/code/csharp/Variable.qll
Performance report [here](https://git.semmle.com/gist/tom/f6a1be944b928e333e73de16e5c215a9) (internal link).
=> C#: Refactor predicates in `Variable` class to be defined by dispatch

java/ql/src/semmle/code/java/controlflow/internal/GuardsLogic.qll
I don't know exactly when this slipped, but sometime recent the join-order of `conditionalAssign` changed leading to very poor performance.
I also fixed up the qldoc a bit to clarify the logic.
=> Java: Fix join-order for GuardsLogic::conditionalAssign.

java/ql/src/semmle/code/java/dataflow/FlowSources.qll
Followup to https://github.com/Semmle/ql/pull/1305.
=> Java: Deprecate RemoteUserInput

javascript/ql/src/DOM/TargetBlank.ql
As suggested by Drew from MITRE.
=> JavaScript: Add CWE-1022 to TargetBlank.

change-notes/1.21/analysis-javascript.md
Ping @felicity-semmle @mc-semmle
=> JS: Add change note for TypeScript full extraction

csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll, csharp/ql/test/library-tests/csharp7/LocalTaintFlow.expected, csharp/ql/test/library-tests/dataflow/global/DataFlowEdges.expected, csharp/ql/test/library-tests/dataflow/global/GetAnOutNode.expected, csharp/ql/test/library-tests/dataflow/global/TaintTrackingEdges.expected, csharp/ql/test/library-tests/dataflow/global/This.cs, csharp/ql/test/library-tests/dataflow/local/DataFlowStep.expected, csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected
In preparation for flow through fields. Performance report ([full report](https://git.semmle.com/gist/tom/ea38e07f3c9d0246778d34b8d5aab9b1)):
```
Project              23faa942ced@bc00877ff  23faa942ced@e1d4166e3                                             roslyn               2777                   2713                   0.976954
corefx               2175                   2150                   0.988506                                   EntityFrameworkCore  2287                   2271                   0.993004
pythonnet            110                    110                    1                                          OneOf                890                    891                    1.00112
monodevelop          3307                   3316                   1.00272 …
```
=> C#: Data flow through `this` parameter

README.md, docs/query-help-style-guide.md, docs/query-metadata-style-guide.md
@felicity-semmle: see https://jira.semmle.com/browse/SD-3458
I've also updated a couple of links.
=> docs: add link to style guides in readme

javascript/config/suites/javascript/security-extra
=> JS: Add queries to the manual suite for LGTM constistency

cpp/config/suites/security/cwe-676
See https://git.semmle.com/Semmle/code/pull/31977#discussion_r139239.
=> CPP: Add DangerousFunctionOverflow.ql to the security suite.

change-notes/1.21/analysis-javascript.md, change-notes/1.21/extractor-javascript.md
This PR is to merge my change note tidy up branch into the `rc/1.21` branch. Unfortunately I mistargeted #1417 against `master`.
@xiemaisi - as suggested
=> QL 1.21: javascript change notes - rc/1.21 branch

python/ql/src/semmle/python/Exprs.qll, python/ql/src/semmle/python/Flow.qll, python/ql/src/semmle/python/objects/ObjectInternal.qll, python/ql/src/semmle/python/objects/Sequences.qll, python/ql/src/semmle/python/objects/TObject.qll, python/ql/src/semmle/python/pointsto/PointsTo.qll, python/ql/test/library-tests/PointsTo/new/Call.expected, python/ql/test/library-tests/PointsTo/new/NameSpace.expected, python/ql/test/library-tests/PointsTo/new/PointsToNone.expected, python/ql/test/library-tests/PointsTo/new/PointsToWithContext.expected, python/ql/test/library-tests/PointsTo/new/PointsToWithType.expected, python/ql/test/library-tests/PointsTo/new/Values.expected, python/ql/test/library-tests/PointsTo/new/code/l_calls.py
https://github.com/Semmle/ql/pull/1391 should have gone in the 1.21 branch.
=> Backport of #1391

change-notes/1.21/analysis-cpp.md, change-notes/1.21/analysis-csharp.md, change-notes/1.21/analysis-java.md, change-notes/1.21/analysis-python.md, change-notes/support/language-support.rst, change-notes/support/versions-compilers.csv
The only conflict was in: `change-notes/1.21/analysis-python.md`. @markshannon - can you check you're happy with the resolution.
=> Merge 'rc/1.21' back into 'master'

python/ql/test/3/library-tests/six/test.expected
https://github.com/Semmle/ql/pull/1433 did not include the update to the test results. This PR fixes that.
=> Python: fixup test results for https://github.com/Semmle/ql/pull/1433

python/ql/src/semmle/python/Module.qll, python/ql/src/semmle/python/types/ModuleObject.qll, python/ql/test/library-tests/ControlFlow/PointsToSupport/UseFromDefinition.ql
A few minor changes fixing issues picked up by running the [Sanity check query](https://github.com/Semmle/ql/blob/master/python/ql/src/analysis/Sanity.ql)
=> Python sanity improvements

python/ql/src/semmle/python/Flow.qll
This PR should have no effect without loop unrolling, but should maintain correctness with loop unrolling.
=> Python : Prepare for loop unrolling in extractor

javascript/extractor/lib/typescript/src/main.ts
`ts.sys.readFile` sniffs the content encoding from the file, and also strips the BOM. I've removed an old workaround that was in place to ensure the BOM was stripped, which isn't needed.
This fixes a failure involving a UTF-16 encoded `tsconfig.json` file (ODASA-7989).
=> TS: Rely on ts.sys.readFile for reading files

java/ql/src/semmle/code/java/security/Encryption.qll
@tibbes This should remove the FP you reported.
=> Java: Add SHA512 to the crypto whitelist.

cpp/ql/src/Likely Bugs/Memory Management/Padding/NonPortablePrintf.ql, cpp/ql/test/library-tests/functions/getathrowntype/getAThrownType.expected, cpp/ql/test/library-tests/functions/getathrowntype/getAThrownType.ql, cpp/ql/test/library-tests/functions/getathrowntype/test.cpp, cpp/ql/test/query-tests/Likely Bugs/Memory Management/Padding/More64BitWaste/More64BitWaste.expected, cpp/ql/test/query-tests/Likely Bugs/Memory Management/Padding/More64BitWaste/More64BitWaste.qlref, cpp/ql/test/query-tests/Likely Bugs/Memory Management/Padding/More64BitWaste/test.cpp, cpp/ql/test/query-tests/Likely Bugs/Memory Management/Padding/NonPortablePrintf/NonPortablePrintf.expected, cpp/ql/test/query-tests/Likely Bugs/Memory Management/Padding/NonPortablePrintf/NonPortablePrintf.qlref, cpp/ql/test/query-tests/Likely Bugs/Memory Management/Padding/NonPortablePrintf/test.cpp, cpp/ql/test/query-tests/Likely Bugs/ReturnConstType/test.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/extreme/ArithmeticWithExtremeValues.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/extreme/test.c
This pull request is a collection of new tests and test cases I've accumulated over the last few months, that ought to be added to master.  There's also a *tiny* change to a query violation message.
=> CPP: Add some tests

cpp/ql/src/Likely Bugs/Likely Typos/inconsistentLoopDirection.ql
This query seems to have been de-optimized by recent optimizer or stats changes. On libretro/libretro-uae, the query took 1 second on a warm cache with dist 89ad5f1 but took 9979 seconds with dist a3b9b6eb9.
The slowness was due to a Cartesian product in `illDefined{Decr,Incr}ForStmt` between all the definitions and all the uses of `Variable v`. This would be no problem with the right join order, but that has apparently been lost.
This PR factors out a pair of `pragma[noinline]` helper predicates to make sure the definitions (`v.getAnAssignedValue()`) and the uses (`v.getAnAccess()`) are queried and filtered in separate predicates.
The performance problem can be seen in the tuple counts of this pipeline I interrupted during evaluation of …
=> C++: Fix inconsistent-loop-direction performance

change-notes/1.22/analysis-cpp.md, cpp/ql/src/semmle/code/cpp/models/Models.qll, cpp/ql/src/semmle/code/cpp/models/implementations/Swap.qll, cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/taint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/test_diff.expected, cpp/ql/test/library-tests/dataflow/taint-tests/test_ir.expected
Model data flow through std::swap.
I'm not completely sure what the difference between `isInParameter` and `isInParameterPointer` is, but there's no `isOutParameter` so I guess references are considered pointers?
=> CPP: Model std::swap

python/ql/src/semmle/python/pointsto/PointsTo.qll
Uses an extensional (not IPA type) for origins and prevents some harmful magic.
=> Python: Performance improvements to points-to. 

cpp/ql/src/semmle/code/cpp/ir/implementation/aliased_ssa/internal/AliasedSSA.qll
#1587 had a join ordering issue that I didn't notice until it was merged.
=> C++: further optimization of overlap computation

python/ql/src/analysis/Sanity.ql, python/ql/src/semmle/python/Scope.qll
Fixes 2 false positives for AST and CFG sanity
Also improves reporting for ClassValue sanity.
=> Python: Fix a couple of  false positives in sanity query

python/ql/src/semmle/python/Module.qll
Avoids giving modules two names when there are two potential import roots for the module's file.
=> Python refine module naming.

javascript/ql/src/semmle/javascript/GlobalAccessPaths.qll
https://github.com/Semmle/ql/pull/1621 vs https://github.com/Semmle/ql/pull/1613
=> JavaScript: Fix semantic merge conflict.

docs/ql-documentation/learn-ql/javascript/dataflow-cheat-sheet.rst, docs/ql-documentation/learn-ql/javascript/ql-for-javascript.rst
Previously reviewed here: https://git.semmle.com/Semmle/code/pull/33332
=> JS: Add data flow cheat sheet

docs/ql-documentation/ql-handbook/annotations.rst, docs/ql-documentation/ql-handbook/expressions.rst, docs/ql-documentation/ql-handbook/formulas.rst, docs/ql-documentation/ql-handbook/modules.rst, docs/ql-documentation/ql-handbook/name-resolution.rst, docs/ql-documentation/ql-handbook/queries.rst, docs/ql-documentation/ql-handbook/recursion.rst, docs/ql-documentation/ql-handbook/types.rst, docs/ql-documentation/vale-styles/Semmle/ignore.txt
This pull request makes some minor updates to the QL handbook for things flagged as errors by Vale.
Mostly the changes just improve the consistency of formatting. There was one typo and a poorly defined date. Please let me know if you'd like me to generate a preview.
@jf205 - I think that these changes probably require only a documentation review, but please say if you think otherwise.
=> Ql handbook: Corrections for issues found using Vale

cpp/ql/test/library-tests/constants/constants/strings.expected
https://git.semmle.com/Semmle/code/pull/33380
=> C++: Accept changes to getValueText

javascript/ql/src/semmle/javascript/dataflow/Sources.qll, javascript/ql/src/semmle/javascript/dataflow/TypeTracking.qll
Plus a few minor comment tweaks
=> JS: Remove experimental warning from type tracking

python/ql/src/Security/CWE-022/PathInjection.ql, python/ql/src/Security/CWE-078/CommandInjection.ql, python/ql/src/Security/CWE-209/StackTraceExposure.ql, python/ql/src/Security/CWE-327/BrokenCryptoAlgorithm.ql, python/ql/src/Security/CWE-601/UrlRedirect.ql, python/ql/src/Security/CWE-798/HardcodedCredentials.ql, python/ql/src/semmle/python/security/injection/Path.qll, python/ql/src/semmle/python/web/Http.qll, python/ql/src/semmle/python/web/django/Redirect.qll, python/ql/src/semmle/python/web/flask/Redirect.qll, python/ql/src/semmle/python/web/pyramid/Redirect.qll, python/ql/src/semmle/python/web/tornado/Redirect.qll
Should be no change in semantics or results, so need change note needed.
=> Python: Update all remaining taint-tracking queries to use configurations

docs/ql-documentation/training/index.rst
=> Docs: Update ql training homepage

javascript/ql/src/semmle/javascript/frameworks/AngularJS/AngularJSCore.qll
Fixes <https://jira.semmle.com/browse/ODASA-8040>
[Performance is unchanged](https://git.semmle.com/esben/dist-compare-reports/tree/js/fix-missing-this-in-method_1565075693333).
=> JS: fix missing this in method

cpp/ql/src/semmle/code/cpp/Declaration.qll
Mostly just adding backticks in QLDoc comments.  I'm trying out the edit-in-github workflow @jbj showed me, which seems like it will be a quicker way to do minor changes like these.
=> CPP: QLDoc tidy up Declaration.qll

docs/ql-documentation/learn-ql/java/dataflow.rst
This PR relates to [SD-3739], which was raised by Sam P. I can't find him on github, so @felicity-semmle would you mind checking this please? I'll make the same change on help.semmle.com directly.
=> docs: fix typo in Java data flow exercise

CONTRIBUTING.md, docs/ql-style-guide.md, docs/query-metadata-style-guide.md
This PR adds some basic information about contributing queries to the public repo (related Jira issue: https://jira.semmle.com/browse/SD-3476).
It's pretty high-level and mainly links to our existing documentation. A bit further down the line we can add more information about testing new queries.
=> docs: add more information about contributing queries to the public repo

cpp/ql/src/semmle/code/cpp/Struct.qll, cpp/ql/src/semmle/code/cpp/Union.qll, cpp/ql/test/library-tests/structs/structs/structs.c, cpp/ql/test/library-tests/structs/structs/structs.cpp, cpp/ql/test/library-tests/structs/structs/structs.expected, cpp/ql/test/library-tests/structs/structs/structs.ql, cpp/ql/test/library-tests/unions/Unions1.expected, cpp/ql/test/library-tests/unions/Unions1.ql, cpp/ql/test/library-tests/unions/Unions4.expected, cpp/ql/test/library-tests/unions/Unions4.ql, cpp/ql/test/library-tests/unions/unions.cpp
For https://jira.semmle.com/browse/CPP-407.
I also extended and cleaned up their tests.
=> CPP: Add syntax examples to QLDoc in Struct.qll, Union.qll.

javascript/ql/src/Security/CWE-020/MissingRegExpAnchor.qhelp, javascript/ql/src/Security/CWE-022/TaintedPath.qhelp
In these two cases, the qhelp and the examples were slightly inconsistent.
=> JavaScript: Fix two minor qhelp inconsistencies.

cpp/ql/src/semmle/code/cpp/Enum.qll, cpp/ql/test/library-tests/enums/enums/Enums1.expected, cpp/ql/test/library-tests/enums/enums/Enums3.expected, cpp/ql/test/library-tests/enums/enums/Enums3.ql, cpp/ql/test/library-tests/enums/enums/enums.cpp, cpp/ql/test/library-tests/lambdas/captures/elements.ql
For https://jira.semmle.com/browse/CPP-407.
I also extended a test.
=> CPP: Add syntax examples to QLDoc in Enum.qll.

cpp/ql/src/semmle/code/cpp/Initializer.qll, cpp/ql/src/semmle/code/cpp/Parameter.qll
For https://jira.semmle.com/browse/CPP-407.
=> CPP: Add syntax examples to QLDoc in Initializer.qll, Parameter.qll

javascript/documentation/library-customization.rst
Mostly a starting point for discussion with no claims to completeness; includes bits that we may eventually want to move elsewhere.
=> JavaScript: Start documenting extension points provided by the standard library.

cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/lambdas.cpp, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test_diff.expected, cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
I've checked with a temporary workaround for the locations problem that my annotations in the test cpp files are on the correct lines.
=> C++: Support flow through LambdaExpression

java/ql/src/Performance/ConcatenationInLoops.ql, java/ql/src/semmle/code/java/Expr.qll, java/ql/src/semmle/code/java/Member.qll, java/ql/src/semmle/code/java/controlflow/internal/Preconditions.qll, java/ql/src/semmle/code/java/dataflow/TaintTracking.qll, java/ql/src/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll, java/ql/src/semmle/code/java/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, java/ql/src/semmle/code/java/dispatch/ObjFlow.qll, java/ql/test/library-tests/frameworks/android/manifest/manifest.ql, java/ql/test/library-tests/frameworks/guice/flow.ql
The "everything is autoformatted" invariant had slipped for a few files.
=> Java: Autoformat.

misc/emacs/ql-mode-base.el
=> Remove reference to internal emacs tooling from public repository

docs/language/global-sphinx-files/global-conf.py
=> QL docs: Update global variables

change-notes/1.23/analysis-javascript.md, javascript/ql/src/Security/CWE-020/IncorrectSuffixCheck.ql, javascript/ql/test/query-tests/Security/CWE-020/IncorrectSuffixCheck.expected, javascript/ql/test/query-tests/Security/CWE-020/tst.js
Fixes ODASA-8077. Not sure if an evaluation is warranted for such a small change.
=> JS: Fix FP in incorrect suffix check

docs/language/ql-handbook/predicates.rst, docs/language/ql-handbook/queries.rst, docs/language/ql-handbook/types.rst
Some small changes suggested by @AlexTereshenkov 🙂 
Could you check if the updated examples/explanations are helpful?
=> QL handbook: Add examples and fix typos

.github/ISSUE_TEMPLATE/lgtm-com---false-positive.md
Add a new issue template for false positive in LGTM.com
=> Add a new issue template for false positive in LGTM.com

docs/language/learn-ql/javascript/dataflow-cheat-sheet.rst, docs/language/learn-ql/javascript/introduce-libraries-js.rst
These are some cherry-picked link updates that have already been reviewed om master https://github.com/Semmle/ql/pull/1903
@shati-patel, please could you merge?
=> docs: update some links in a couple of javascript topics

python/ql/src/semmle/python/objects/ObjectAPI.qll, python/ql/test/3/query-tests/Statements/iter/NonIteratorInForLoop.expected, python/ql/test/3/query-tests/Statements/iter/async_iterator.py
=> Python: Add `__aiter__` as a recognised iterator method.

cpp/ql/src/semmle/code/cpp/valuenumbering/HashCons.qll
The key insight here is that `HC_FieldCons` and `HC_Array` are
functionally determined by the things that arise in another
recursive call. Lifting them to their own predicate, therefore,
reduces nonlinearity and constrains the join order in a way that
cannot be asymptotically bad -- and, indeed, makes quite a big
difference in practice.
=> C++: HashCons: Further performance improvements

change-notes/1.23/analysis-javascript.md, javascript/ql/src/semmle/javascript/security/dataflow/Xss.qll, javascript/ql/test/query-tests/Security/CWE-079/sanitiser.js
We now use local data flow to detect more regexp-based sanitizers.
=> JavaScript: Improve XSS sanitizer detection.

cpp/ql/src/semmle/code/cpp/exprs/Literal.qll, cpp/ql/test/library-tests/sideEffects/exprs/exprs.c, cpp/ql/test/library-tests/sideEffects/exprs/exprs.expected
https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/575/ (no changes)
=> C++: Implement AggregateLiteral.mayBeImpure()

docs/language/learn-ql/python/pointsto-type-infer.rst, docs/language/learn-ql/python/statements-expressions.rst
The PR cherry-picks recent updates to the QL for Python documentation onto the rc/1.22 branch.
=> Learn QL: QL for Python doc fixes for 1.22

change-notes/1.23/analysis-csharp.md, csharp/ql/src/semmle/code/csharp/Stmt.qll, csharp/ql/src/semmle/code/csharp/controlflow/ControlFlowGraph.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/Condition.expected, csharp/ql/test/library-tests/controlflow/graph/Consistency.expected, csharp/ql/test/library-tests/controlflow/graph/Consistency.ql, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/EnclosingCallable.expected, csharp/ql/test/library-tests/controlflow/graph/EntryElement.expected, csharp/ql/test/library-tests/controlflow/graph/ExitElement.expected, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, csharp/ql/test/library-tests/controlflow/graph/Nodes.expected, csharp/ql/test/library-tests/controlflow/graph/Switch.cs
Addresses https://github.com/Semmle/ql/issues/1974
Can be reviewed on a per commit basis.
=> C#: Fix CFG for switch statements where the default case is not the last

cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/taint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/test_diff.expected, cpp/ql/test/library-tests/dataflow/taint-tests/test_ir.expected
This is just the new test cases from https://github.com/Semmle/ql/pull/1602, as requested by @jbj.
=> CPP: Add taint tests.

csharp/ql/src/semmle/code/csharp/controlflow/internal/Splitting.qll
I will post a `dist-compare` report when it is ready. Update: [here](https://git.semmle.com/gist/tom/11fe86cae0374ea1a2aa56353a3cba61) is the report (internal link).
=> C#: Improve a few join-orders in `Splitting.qll`

docs/language/ql-spec/qldoc.rst
Method -> member predicate
@alexet - Could you check if this is consistent with the current terminology?
=> Terminology update

cpp/ql/src/jsf/4.10 Classes/AV Rule 81.ql, cpp/ql/src/jsf/4.21 Operators/AV Rule 159.ql, cpp/ql/src/jsf/4.28 Portable Code/AV Rule 213.ql, cpp/ql/src/semmle/code/cpp/controlflow/Guards.qll, cpp/ql/src/semmle/code/cpp/controlflow/SSA.qll, cpp/ql/src/semmle/code/cpp/padding/Padding.qll, cpp/ql/src/semmle/code/cpp/rangeanalysis/RangeSSA.qll
Lots of tiny QLDoc corrections / cleanup, many of which were accumulated while reviewing large quantities of code last week.
=> CPP: Tiny qldoc fixes.

docs/ql-style-guide.md, docs/query-metadata-style-guide.md
Spotted this in our meeting just now.
=> Docs: Small fixes

change-notes/1.23/analysis-java.md, java/ql/src/Likely Bugs/Comparison/UselessComparisonTest.ql, java/ql/test/query-tests/UselessComparisonTest/A.java
This is a slight generalization of the existing overflow check patterns in the query.  This fixes #2059
=> Java: Add another overflow check pattern to UselessComparisonTest.

cpp/ql/src/codeql-suites/cpp-lgtm-full.qls, cpp/ql/src/codeql-suites/cpp-lgtm.qls, cpp/ql/src/qlpack.json, csharp/ql/src/codeql-suites/csharp-lgtm-full.qls, csharp/ql/src/codeql-suites/csharp-lgtm.qls, csharp/ql/src/qlpack.json, java/ql/src/codeql-suites/java-lgtm-full.qls, java/ql/src/codeql-suites/java-lgtm.qls, java/ql/src/qlpack.json, javascript/ql/src/codeql-suites/javascript-lgtm-full.qls, javascript/ql/src/codeql-suites/javascript-lgtm.qls, javascript/ql/src/qlpack.json, misc/suite-helpers/lgtm-displayed-only.yml, misc/suite-helpers/lgtm-selectors.yml, misc/suite-helpers/qlpack.json, python/ql/src/codeql-suites/python-lgtm-full.qls, python/ql/src/codeql-suites/python-lgtm.qls, python/ql/src/qlpack.json
https://github.com/github/pe-security-codeql/issues/7
=> Add some new-style suite definitions

javascript/ql/src/semmle/javascript/security/dataflow/CommandInjection.qll
The same class is already defined [here](https://github.com/Semmle/ql/blob/master/javascript/ql/src/semmle/javascript/security/dataflow/IndirectCommandArgument.qll#L30) and imported into the same scope, so this definition is redundant.
=> JavaScript: Remove a duplicate `Configuration` class.

.codeqlmanifest.json, cpp/ql/src/qlpack.json, cpp/ql/src/qlpack.yml, csharp/ql/src/qlpack.json, csharp/ql/src/qlpack.yml, java/ql/src/qlpack.json, java/ql/src/qlpack.yml, javascript/ql/src/qlpack.json, javascript/ql/src/qlpack.yml, misc/legacy-support/cpp/qlpack.json, misc/legacy-support/cpp/qlpack.yml, misc/legacy-support/csharp/qlpack.json, misc/legacy-support/csharp/qlpack.yml, misc/legacy-support/java/qlpack.json, misc/legacy-support/java/qlpack.yml, misc/legacy-support/javascript/qlpack.json, misc/legacy-support/javascript/qlpack.yml, misc/legacy-support/python/qlpack.json, misc/legacy-support/python/qlpack.yml, misc/suite-helpers/qlpack.json, misc/suite-helpers/qlpack.yml, python/ql/src/qlpack.json, python/ql/src/qlpack.yml
This PR belongs to https://git.semmle.com/Semmle/code/pull/34867
There should be nothing outside internal alpha that depends on the previous `qlpack.json` files being there.
=> qlpack files are now YAML rather than JSON

docs/language/learn-ql/go/ql-for-go.rst, docs/language/learn-ql/index.rst
@shati-patel: this adds a few links for Go content to the 'Learning QL' project.
=> docs: add ql for go topic

change-notes/1.23/analysis-python.md, python/ql/src/Functions/IterReturnsNonIterator.py, python/ql/src/Functions/IterReturnsNonIterator.qhelp, python/ql/src/Functions/IterReturnsNonIterator.ql, python/ql/test/query-tests/Functions/general/IncorrectRaiseInSpecialMethod.expected, python/ql/test/query-tests/Functions/general/IterReturnsNonIterator.expected, python/ql/test/query-tests/Functions/general/IterReturnsNonSelf.expected, python/ql/test/query-tests/Functions/general/OverlyComplexDelMethod.expected, python/ql/test/query-tests/Functions/general/SignatureSpecialMethods.expected, python/ql/test/query-tests/Functions/general/protocols.py
@s0 I adapted your error message from https://github.com/Semmle/ql/issues/1427. I made it shorter to fit the style of the other queries. I ended up rewriting the documentation and example to get the point across more clearly.
=> Python: improve py/iter-returns-non-iterator

misc/suite-helpers/lgtm-displayed-only.yml, misc/suite-helpers/lgtm-selectors.yml
Capture `path-problem` as well as `problem` queries.
=> Update new-style suite definitions

change-notes/1.23/analysis-javascript.md, javascript/ql/src/semmle/javascript/Concepts.qll, javascript/ql/src/semmle/javascript/frameworks/Express.qll, javascript/ql/src/semmle/javascript/security/dataflow/TaintedPath.qll, javascript/ql/src/semmle/javascript/security/dataflow/TaintedPathCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/Consistency.expected, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/normalizedPaths.js, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/tainted-sendFile.js
Fixes https://github.com/Semmle/ql/issues/2197
[Evaluation](https://git.semmle.com/asger/dist-compare-reports/tree/express-sendfile_1571981710999) was uneventful, but I've confirmed that the reported FP goes away.
=> JS: Fix FPs from Express sendFile sink

java/ql/src/Security/CWE/CWE-113/NettyResponseSplitting.java, java/ql/src/Security/CWE/CWE-113/NettyResponseSplitting.qhelp, java/ql/src/Security/CWE/CWE-113/NettyResponseSplitting.ql, java/ql/src/Security/CWE/CWE-113/ResponseSplitting.qhelp
=> Add CWE-113 check for io.netty.handler.codec.http.DefaultHttpHeaders

python/ql/src/semmle/python/dataflow/Configuration.qll
I didn't want to clutter up my other pull requests -- they are already suffering from trying to do too many things at once :confused:
=> Python: Fix qldoc for TaintTracking Configuration

.codeqlmanifest.json, cpp/upgrades/qlpack.yml, csharp/upgrades/qlpack.yml, javascript/upgrades/qlpack.yml, python/upgrades/qlpack.yml
This is a lower-impact alternative to https://github.com/Semmle/ql/pull/2198.
It slightly clutters the output from `resolve qlpacks`, but otherwise is less likely to break things.
=> Make each upgrade directory a QL pack

csharp/autobuilder/Semmle.Autobuild.Tests/BuildScripts.cs
Follow-up on https://github.com/Semmle/ql/pull/2208.
=> C#: Update autobuilder tests

change-notes/1.23/analysis-javascript.md, javascript/ql/src/Expressions/UnknownDirective.ql, javascript/ql/test/query-tests/Expressions/UnknownDirective/dual-use.js
=> JavaScript: Recognize ":" pseudo-directive.

docs/language/global-sphinx-files/_templates/layout.html
@shati-patel and @felicitymay: this _should_ be the last change required to the existing CodeQL docs.
=> docs: update banner links

docs/language/global-sphinx-files/_templates/layout.html
Small change. Is "using CodeQL" okay? ("Writing CodeQL" sounds strange to me.) 
@jf205 or @felicitymay for review please 🙏
=> Docs: Update sidebar

cpp/ql/src/Microsoft/SAL.qll, cpp/ql/src/Security/CWE/CWE-457/InitializationFunctions.qll, cpp/ql/src/semmle/code/cpp/NestedFields.qll, cpp/ql/src/semmle/code/cpp/dispatch/VirtualDispatch.qll, cpp/ql/src/semmle/code/cpp/security/boostorg/asio/protocols.qll
Ad-hoc cleanup for the recently contributed queries and libraries.  No behaviour changes.
=> CPP: Clean up new queries and libraries

.codeqlmanifest.json
This allows IntelliSense/GoToDef to work in the test sources.
=> Add QL test directories to `.codeqlmanifest.json`

cpp/ql/test/library-tests/types/error/exprs.expected, cpp/ql/test/library-tests/types/error/exprs.ql, cpp/ql/test/library-tests/types/error/test.cpp
See discussion in https://github.com/Semmle/ql/pull/2309#discussion_r345784811.
=> CPP: Add a quick test of ErroneousType.

docs/language/learn-ql/writing-queries/writing-queries.rst
=> Docs: Typo fix

docs/language/learn-ql/intro-to-data-flow.rst, docs/language/learn-ql/writing-queries/introduction-to-queries.rst, docs/language/learn-ql/writing-queries/path-queries.rst, docs/language/learn-ql/writing-queries/writing-queries.rst
These topics are linked to from the new CodeQL help, so I reviewed them more carefully and updated some text/links.
(We can decide later if it's worth republishing. Either way, I thought I'd raise this now.)
=> Docs: Tidy up links in relevant topics

CODEOWNERS
(and reorder cpp, so it all follows the same pattern)
=> CODEOWNERS: Add python team

cpp/ql/test/library-tests/functions/routinetype/routinetype.cpp, cpp/ql/test/library-tests/functions/routinetype/types.expected, cpp/ql/test/library-tests/functions/routinetype/types.ql
Inspired by https://github.com/Semmle/ql/pull/2309#discussion_r346208839.
=> CPP: Add a quick test of RoutineType.

csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/local/DataFlowStep.expected, csharp/ql/test/library-tests/dataflow/local/LocalDataFlow.cs, csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected
Fixes https://github.com/Semmle/ql/issues/2256.
=> C#: Add missing assignment data flow steps

docs/language/README.rst
Cherry-picked from https://github.com/Semmle/ql/pull/2349.
=> Docs: Update readme in docs folder (cherry-pick from master) 

docs/language/learn-ql/writing-queries/introduction-to-queries.rst, docs/language/learn-ql/writing-queries/path-queries.rst, docs/language/learn-ql/writing-queries/writing-queries.rst
Follow-up to https://github.com/Semmle/ql/pull/2350.
=> Docs: Update links from blog to security lab

cpp/ql/src/Likely Bugs/Protocols/TlsSettingsMisconfiguration.qhelp, cpp/ql/src/Likely Bugs/Protocols/TlsSettingsMisconfiguration.ql
Address points raised by @hubwriter in https://github.com/Semmle/ql/pull/2113/files#diff-5bc34902af26176dba7dcfb06071fad3.
=> CPP: Improve TlsSettingsMisconfiguration qhelp 

cpp/ql/src/Likely Bugs/Arithmetic/SignedOverflowCheck.qhelp
Partly based on feedback from @aschackmull, these changes will hopefully make the qhelp less confusing.
=> C++: Signed Overflow Check qhelp improvements

cpp/ql/src/Likely Bugs/Likely Typos/CompareWhereAssignMeant.ql, cpp/ql/src/Likely Bugs/Likely Typos/ExprHasNoEffect.ql, cpp/ql/test/query-tests/Likely Bugs/Likely Typos/CompareWhereAssignMeant/CompareWhereAssignMeant.expected, cpp/ql/test/query-tests/Likely Bugs/Likely Typos/CompareWhereAssignMeant/test.cpp
Fixes #2382.
I've checked that the modified query has no results on the project where the FP was found: https://lgtm.com/query/6046279876493370503/
=> C++: Fix FP for expression SFINAE with decltype

cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SimpleSSA.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SimpleSSAImports.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/SimpleSSAPublicImports.qll, cpp/ql/src/semmle/uml/MagicDraw.qll, csharp/ql/src/semmle/code/csharp/ir/implementation/unaliased_ssa/internal/SimpleSSA.qll, csharp/ql/src/semmle/code/csharp/ir/implementation/unaliased_ssa/internal/SimpleSSAImports.qll, csharp/ql/src/semmle/code/csharp/ir/implementation/unaliased_ssa/internal/SimpleSSAPublicImports.qll
The qldoc build found a few compilation warnings/errors in files that aren't used in any other test. See individual commit messages for details.
=> C++/C#: Fix QL compilation warnings/errors

javascript/ql/src/semmle/javascript/dataflow/DataFlow.qll, javascript/ql/test/library-tests/PropWrite/tests.expected, javascript/ql/test/library-tests/PropWrite/tst.js
@max-schaefer do you remember the reason for this being treated as an unknown property?
I'll run an evaluation over the weekend.
=> JS: Add prop names for array element pattern PropReads

change-notes/1.23/analysis-python.md
=> Python: Update change note for 1.23.

java/ql/test/query-tests/EmptyInterface/EmptyInterface.expected, java/ql/test/query-tests/EmptyInterface/EmptyInterface.qlref, java/ql/test/query-tests/EmptyInterface/IAmAlsoOK.java, java/ql/test/query-tests/EmptyInterface/IAmBad.java, java/ql/test/query-tests/EmptyInterface/IAmBadAsWell.java, java/ql/test/query-tests/EmptyInterface/IAmBadToo.java, java/ql/test/query-tests/EmptyInterface/IAmNonEmpty.java, java/ql/test/query-tests/EmptyInterface/IAmNonEmptyAsWell.java, java/ql/test/query-tests/EmptyInterface/IAmNonEmptyToo.java, java/ql/test/query-tests/EmptyInterface/IAmOK.java, java/ql/test/query-tests/EmptyInterface/IAmUseful.java
This is a test of an internal query for the Semmle repository. It cannot run against the public QL repository alone, and therefore should not be tested here.
https://git.semmle.com/Semmle/code/pull/35690 adds the test back to the internal repo.
=> remove java test EmptyInterface

change-notes/1.23/analysis-csharp.md
This is a replacement for the PR #2430. It seems likely that our bot doesn't like the branch name to include a `#` symbol. No changes apart from the branch name.
@calumgrant
=> 1.23/sd 4095 finalize change notes csharp

docs/language/global-sphinx-files/global-conf.py, docs/language/learn-ql/cobol/introduce-libraries-cobol.rst, docs/language/learn-ql/cobol/ql-for-cobol.rst, docs/language/ql-training/conf.py, docs/language/support/cobol-note.rst, docs/language/support/conf.py, docs/language/support/framework-support.rst, docs/language/support/language-support.rst
Reverts Semmle/ql#2487, which was merged into the wrong branch. I'll open a new PR which targets rc/1.23.
=> Revert "Learning CodeQL docs: add COBOL notes and remove links"

docs/language/global-sphinx-files/global-conf.py, docs/language/learn-ql/cobol/introduce-libraries-cobol.rst, docs/language/learn-ql/cobol/ql-for-cobol.rst, docs/language/ql-training/conf.py, docs/language/support/cobol-note.rst, docs/language/support/conf.py, docs/language/support/framework-support.rst, docs/language/support/language-support.rst
@felicitymay this PR includes the same changes as #2487, but is targeted against the correct branch (rc/1.23).
=> Learning CodeQL docs: add COBOL notes and remove links (rc/1.23)

cpp/ql/src/semmle/code/cpp/security/SensitiveExprs.qll
The biggest speedups were the first and third commit.
IMO the result is also cleaner QL than we started with.
=> CPP: Speed up SensitiveExprs.qll

change-notes/1.23/analysis-csharp.md, csharp/ql/src/semmle/code/csharp/ir/implementation/unaliased_ssa/internal/reachability/ReachableBlockInternal.qll, csharp/ql/src/semmle/code/csharp/ir/internal/TIRVariable.qll, docs/language/learn-ql/cobol/introduce-libraries-cobol.rst, docs/language/learn-ql/cobol/ql-for-cobol.rst, docs/language/support/cobol-note.rst, docs/language/support/conf.py, docs/language/support/language-support.rst
The only conflicts were in Sphinx project files, related to documentation--everything else merged cleanly.
=> Merge rc/1.23 into master

change-notes/1.24/analysis-csharp.md, csharp/ql/src/Security Features/CWE-016/ASPNetPagesValidateRequest.qhelp, csharp/ql/src/Security Features/CWE-016/ASPNetPagesValidateRequest.ql, csharp/ql/src/Security Features/CWE-016/ASPNetPagesValidateRequestBad.config, csharp/ql/src/Security Features/CWE-016/ASPNetPagesValidateRequestGood.config, csharp/ql/src/Security Features/CWE-016/Web.config.ASPNetPagesValidateRequest.bad, csharp/ql/src/Security Features/CWE-016/Web.config.ASPNetPagesValidateRequest.good, csharp/ql/test/query-tests/Security Features/CWE-016/ASPNetPagesValidateRequest/ASPNetPagesValidateRequest.expected, csharp/ql/test/query-tests/Security Features/CWE-016/ASPNetPagesValidateRequest/ASPNetPagesValidateRequest.qlref, csharp/ql/test/query-tests/Security Features/CWE-016/ASPNetPagesValidateRequest/ASPNetPagesValidateRequestBad.config, csharp/ql/test/query-tests/Security Features/CWE-016/ASPNetPagesValidateRequest/ASPNetPagesValidateRequestGood.config
Note: qltests failure will be resolved by https://github.com/Semmle/ql/pull/2356
=> Asp net pages validate request

.github/labeler.yml
TL;DR: YAML escaping is complicated. I think this should fix the problems.
=> Actions: Fix broken escaping in PR labeller action.

change-notes/1.24/analysis-csharp.md, csharp/ql/src/semmle/code/csharp/commons/Assertions.qll, csharp/ql/src/semmle/code/csharp/frameworks/system/Diagnostics.qll, csharp/ql/src/semmle/code/csharp/frameworks/system/diagnostics/Contracts.qll, csharp/ql/test/library-tests/commons/Assertions/Assertions.cs, csharp/ql/test/library-tests/commons/Assertions/Assertions.expected, csharp/ql/test/library-tests/commons/Assertions/Assertions.ql, csharp/ql/test/library-tests/commons/Assertions/FailingAssertion.expected
Fixes https://github.com/github/codeql-csharp-team/issues/2.
=> C#: Recognize Code Contract assertions

CONTRIBUTING.md
Follow-up to https://github.com/Semmle/ql/pull/2536 @jf205
=> Docs: Update mention of "QL for Eclipse"

docs/language/learn-ql/beginner/find-thief-1.rst, docs/language/learn-ql/beginner/find-thief-2.rst, docs/language/learn-ql/beginner/fire-1.rst, docs/language/learn-ql/beginner/fire-2.rst, docs/language/learn-ql/beginner/heir.rst, docs/language/learn-ql/beginner/ql-tutorials.rst
I've made some updates to bring the detective tutorial more in line with our [style guide](https://github.com/Semmle/ql/blob/master/docs/ql-style-guide.md), including some renaming/autoformatting.
(I thought it would be easier to make these changes now rather than transferring my [Jira](https://jira.semmle.com/browse/SD-3981) issue to GitHub.)
@jf205, would you mind reviewing?
=> QL tutorials: Update formatting and style

docs/language/ql-handbook/predicates.rst
Added an example [suggested by Alexey](https://jira.semmle.com/browse/SD-3529) to the [QL handbook](https://help.semmle.com/QL/ql-handbook/predicates.html#binding-behavior).
@max-schaefer - could you have a look if this is a rational example? (I chose you since you're definitely in the office today 😉 )
=> QL HB: Add bindingset example

change-notes/1.24/analysis-csharp.md, csharp/ql/src/Dead Code/DeadStoreOfLocal.ql, csharp/ql/test/query-tests/Dead Code/DeadStoreOfLocal/DeadStoreOfLocal.cs, csharp/ql/test/query-tests/Dead Code/DeadStoreOfLocal/DeadStoreOfLocal.expected
Fixes https://github.com/github/codeql-csharp-team/issues/11
=> C#: Remove FP in useless assignment to _

docs/language/learn-ql/python/introduce-libraries-python.rst
While reviewing #2609 I spotted another broken link. @RasmusWL, please can you check that the new URL is correct?
=> docs: fix link in Python topic

change-notes/1.24/analysis-java.md
=> Java: add change note for `java/maven/non-https-url`

cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This matches the corresponding predicate in AST data flow.
=> C++: Add DataFlow::Node.asDefiningArgument in IR

java/ql/test/query-tests/Nullness/C.java, java/ql/test/query-tests/Nullness/NullMaybe.expected
Document the two FPs reported in https://github.com/Semmle/ql/issues/2630 as unit tests.
=> Java: Document two FPs with unit tests.

change-notes/1.24/analysis-java.md
Add change note for the query added in https://github.com/Semmle/ql/pull/2586
=> Java: Add change note for java/spring-disabled-csrf-protection.

change-notes/1.24/analysis-javascript.md, javascript/ql/src/Security/CWE-352/MissingCsrfMiddleware.ql, javascript/ql/test/query-tests/Security/CWE-352/MissingCsrfMiddleware.expected, javascript/ql/test/query-tests/Security/CWE-352/MissingCsrfMiddlewareBad.js, javascript/ql/test/query-tests/Security/CWE-352/MissingCsrfMiddlewareGood.js, javascript/ql/test/query-tests/Security/CWE-352/csurf_api_example.js, javascript/ql/test/query-tests/Security/CWE-352/csurf_example.js, javascript/ql/test/query-tests/Security/CWE-352/lusca_example.js, javascript/ql/test/query-tests/Security/CWE-352/unused_cookies.js
Addresses the FP reported in https://github.com/Semmle/ql/issues/2539.
Evaluation underway
=> JS: Sharpen missing CSRF middleware query

change-notes/1.24/analysis-cpp.md, change-notes/1.24/analysis-csharp.md, change-notes/1.24/analysis-java.md
Add change notes for the improvements in https://github.com/Semmle/ql/pull/2498.
=> Java/C++/C#: Add change note for taint-getters.

change-notes/1.24/analysis-csharp.md, csharp/ql/src/Likely Bugs/DangerousNonShortCircuitLogic.ql, csharp/ql/test/query-tests/Likely Bugs/DangerousNonShortCircuitLogic/DangerousNonShortCircuitLogic.cs, csharp/ql/test/query-tests/Likely Bugs/DangerousNonShortCircuitLogic/DangerousNonShortCircuitLogic.expected
Fixes https://github.com/github/codeql-csharp-team/issues/17
=> C#: Remove false positive in cs/non-short-circuit

cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/src/semmle/code/java/Expr.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl5.qll
Looking into some recent performance regressions I've found a couple of easy fixes.  This improves performance substantially on certain projects.
=> Java: Improve performance.

docs/language/ql-handbook/modules.rst
Fixes https://github.com/github/codeql-coreql-team/issues/178.
=> QL language handbook: add link to information about module resolution in QL spec

javascript/ql/test/library-tests/frameworks/LazyCache/LazyCache.expected, javascript/ql/test/library-tests/frameworks/LazyCache/LazyCache.ql, javascript/ql/test/library-tests/frameworks/LazyCache/tst.js
Adds a test case that should have been included in https://github.com/Semmle/ql/pull/2768
=> JS: Add test case for lazy-cache

csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll
Adding this class to the public data-flow API, as discussed with @lcartey.
=> C#: Add new class `AssignableDefinitionNode` to the data-flow library

python/ql/src/Imports/ModuleImportsItself.ql, python/ql/test/query-tests/Imports/PyCheckerTests/ImportandImportFrom.expected, python/ql/test/query-tests/Imports/PyCheckerTests/ModuleImportsItself.expected, python/ql/test/query-tests/Imports/PyCheckerTests/imports_test.py, python/ql/test/query-tests/Imports/PyCheckerTests/options, python/ql/test/query-tests/Imports/PyCheckerTests/pkg_notok/__init__.py, python/ql/test/query-tests/Imports/PyCheckerTests/pkg_notok/bar.py, python/ql/test/query-tests/Imports/PyCheckerTests/pkg_ok/__init__.py, python/ql/test/query-tests/Imports/PyCheckerTests/pkg_ok/foo1.py, python/ql/test/query-tests/Imports/PyCheckerTests/pkg_ok/foo2.py, python/ql/test/query-tests/Imports/PyCheckerTests/pkg_ok/foo3.py, python/ql/test/query-tests/Imports/PyCheckerTests/pkg_ok/foo4.py, python/ql/test/query-tests/Imports/PyCheckerTests/pkg_ok/foo5.py
Fixes https://github.com/Semmle/ql/issues/2771
=> Python: Fix FP for py/import own module

change-notes/1.24/analysis-javascript.md, javascript/config/suites/javascript/security, javascript/ql/src/Security/CWE-079/UnsafeJQueryPlugin.qhelp, javascript/ql/src/Security/CWE-079/UnsafeJQueryPlugin.ql, javascript/ql/src/Security/CWE-079/examples/UnsafeJQueryPlugin.js, javascript/ql/src/Security/CWE-079/examples/UnsafeJQueryPlugin_safe.js, javascript/ql/src/semmle/javascript/security/dataflow/UnsafeJQueryPlugin.qll, javascript/ql/src/semmle/javascript/security/dataflow/UnsafeJQueryPluginCustomizations.qll, javascript/ql/src/semmle/javascript/security/dataflow/Xss.qll, javascript/ql/test/query-tests/Security/CWE-079/UnsafeJQueryPlugin.expected, javascript/ql/test/query-tests/Security/CWE-079/UnsafeJQueryPlugin.qlref, javascript/ql/test/query-tests/Security/CWE-079/unsafe-jquery-plugin.js
This is the production quality version of <https://securitylab.github.com/ctf/jquery>.
The query has the same main ideas as the one in the competition, but it has been amended with lots of type tracking and advanced sanitization.
Evaluation is ongoing.
=> JS: add query js/unsafe-jquery-plugin

cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl5.qll
Alternative to https://github.com/Semmle/ql/pull/2859 that attempts to avoid potential blowups.
=> Java/C++/C#: Improve join-order in pathStep predicate

python/ql/src/Expressions/UnnecessaryLambda.ql
This PR is part of the Expressions modernization effort.
=> Python: ObjectAPI to ValueAPI: UnnecessaryLambda

cpp/ql/src/Likely Bugs/Arithmetic/UnsignedGEZero.qll
This query used two fastTC operations that were already somewhat inefficient on their own but could send the evaluator into an OOM loop when run in parallel without enough RAM.
The fix is to recurse manually, starting just from the expressions that are potential candidates for alerts.
=> C++: Fix performance of UnsignedGEZero.ql

cpp/ql/src/semmle/code/cpp/ir/dataflow/DefaultTaintTracking.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/aliased_ssa/IRVariable.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/raw/IRVariable.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/IRVariable.qll, cpp/ql/test/library-tests/declarationEntry/declarationEntry/declarationEntry.expected, cpp/ql/test/library-tests/declarationEntry/declarationEntry/fde.expected, cpp/ql/test/library-tests/declarationEntry/declarationEntry/fde.ql, cpp/ql/test/library-tests/declarationEntry/declarationEntry/macro.c, csharp/ql/src/semmle/code/csharp/ir/implementation/raw/IRVariable.qll, csharp/ql/src/semmle/code/csharp/ir/implementation/unaliased_ssa/IRVariable.qll
- Fix some typos.
- Address https://jira.semmle.com/browse/ODASA-640 (the issue is now tested and no longer occurs).
=> C++: Test and typos.

change-notes/1.24/analysis-java.md, java/ql/src/Customizations.qll, java/ql/src/java.qll
This allows users to add customizations to the standard library that apply to all queries.
Analogous to the [`Customizations.qll`](https://github.com/Semmle/ql/blob/master/javascript/ql/src/Customizations.qll) file for JavaScript.
=> Java: add `Customizations.qll`

cpp/ql/test/library-tests/lambdas/captures/elements.expected, cpp/ql/test/library-tests/templates/instantiations_functions/elements.expected
https://git.semmle.com/Semmle/code/pull/36343
=> C++: Update tests following extractor no longer extracting some unused types

java/ql/test/query-tests/Nullness/C.java, java/ql/test/query-tests/Nullness/NullMaybe.expected
Document the FP reported here: https://github.com/Semmle/ql/issues/2939
=> Java: Document a FP for nullness in a test.

python/ql/src/Expressions/IsComparisons.qll
This PR is part of the Expressions modernization effort.
=> Python: ObjectAPI to ValueAPI: IsComparisons

python/ql/src/Exceptions/IllegalRaise.ql, python/ql/src/Exceptions/Raising.qll, python/ql/src/semmle/python/objects/ObjectAPI.qll
=> Python: ObjectAPI to ValueAPI: Raising

javascript/ql/src/Declarations/UnreachableMethodOverloads.ql, javascript/ql/src/semmle/javascript/StringOps.qll, javascript/ql/src/semmle/javascript/frameworks/NodeJSLib.qll, javascript/ql/src/semmle/javascript/frameworks/ShellJS.qll, javascript/ql/src/semmle/javascript/security/UselessUseOfCat.qll, javascript/ql/test/query-tests/Security/CWE-078/UselessUseOfCat.ql
Hopefully the last time we need to do this.
The PR check has been enabled but some PRs slipped past presumably because they were already green or due to a delay in bumping the submodule.
=> JS: Autoformat again

javascript/ql/src/semmle/javascript/dataflow/Configuration.qll, javascript/ql/src/semmle/javascript/frameworks/NodeJSLib.qll
Not sure why the PR check isn't catching these, but I'm hoping it's just a symptom of PRs being opened before the check was enabled.
=> JS: Autoformat

change-notes/1.24/analysis-javascript.md, javascript/ql/src/semmle/javascript/security/SensitiveActions.qll, javascript/ql/test/library-tests/SensitiveActions/tst.js
Fixes [this FP](https://lgtm.com/projects/g/microsoft/vscode/alerts/?mode=tree&ruleFocus=1505904558124)
=> JS: Declassify sensitive exprs with special characters

cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl5.qll
At least for Java this was getting bad magic.
=> Java/C++/C#: Fix performance issue in partial paths exploration.

python/ql/src/Exceptions/CatchingBaseException.ql
=> Python: ObjectAPI to ValueAPI: CatchingBaseException

python/ql/src/Exceptions/EmptyExcept.ql, python/ql/src/semmle/python/objects/ObjectAPI.qll
=> Python: ObjectAPI to ValueAPI: EmptyExcept

python/ql/src/Exceptions/RaisingTuple.ql
=> Python: ObjectAPI to ValueAPI: RaisingTuple

python/ql/src/Expressions/CallArgs.qll, python/ql/src/semmle/python/objects/ObjectAPI.qll
This PR is part of the Expressions modernization effort.
=> Python: ObjectAPI to ValueAPI: CallArgs

docs/language/learn-ql/index.rst, docs/language/learn-ql/ql-training.rst, docs/language/ql-training/cpp/bad-overflow-guard.rst, docs/language/ql-training/java/query-injection-java.rst, docs/language/ql-training/slide-snippets/intro-ql-general.rst
There were no conflicts in this merge.
=> Merge rc/1.23 back into master

python/ql/src/semmle/python/regex.qll
and use the canonical way of specifying a ModuleValue
=> Python: Add a bit of regex docs

change-notes/1.24/analysis-javascript.md, javascript/ql/src/Expressions/RedundantExpression.ql, javascript/ql/test/query-tests/Expressions/RedundantExpression/tst.js
A very simple fix for [these FPs](https://lgtm.com/projects/g/pytorch/pytorch.github.io/alerts?id=js%2Fredundant-operation&mode=list). 
No evaluation planned, let me know if you want one.
=> JS: js/redundant-operation FP with ++expressions

python/ql/src/semmle/python/security/strings/Basic.qll, python/ql/src/semmle/python/security/strings/Common.qll, python/ql/src/semmle/python/security/strings/External.qll
Need to investigate the 2 TODOs. Will probably do that Monday.
=> Python: Modernise StringKind files

java/ql/src/semmle/code/java/dataflow/internal/ContainerFlow.qll
A fairly straightforward addition of the methods on `Queue` (https://docs.oracle.com/javase/7/docs/api/java/util/Queue.html)
=> Java: Add taint steps for java.util.Queue methods.

javascript/ql/src/semmle/javascript/dataflow/Configuration.qll
I had a partial review for https://github.com/Semmle/ql/pull/3000 around, but didn't get to press submit before the merge.
=> JS: loosen qldoc for `barrierGuardIsRelevant`

CONTRIBUTING.md, docs/experimental.md, docs/supported-queries.md
This is a continuation of https://git.semmle.com/Semmle/ql/pull/7.
=> Docs: refactor guidelines for new queries

python/ql/src/Exceptions/IllegalExceptionHandlerType.ql, python/ql/src/semmle/python/objects/ObjectAPI.qll, python/ql/src/semmle/python/types/Exceptions.qll, python/ql/test/2/library-tests/ControlFlow/Exceptions/Handles.ql, python/ql/test/3/library-tests/ControlFlow/Exceptions/Handles.ql, python/ql/test/library-tests/exceptions/Handles.ql
=> Python: ObjectAPI to ValueAPI: IllegalExceptionHandlerType

python/ql/src/Exceptions/UnguardedNextInGenerator.ql, python/ql/src/semmle/python/objects/ObjectAPI.qll, python/ql/test/query-tests/Exceptions/generators/test.py
=> Python: ObjectAPI to ValueAPI: UnguardedNextInGenerator

javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll, javascript/ql/test/query-tests/Security/CWE-089/untyped/DatabaseAccesses.expected, javascript/ql/test/query-tests/Security/CWE-089/untyped/SqlInjection.expected, javascript/ql/test/query-tests/Security/CWE-089/untyped/mongoose.js
Another batch of Mongoose model improvments. The [evaluation](https://git.semmle.com/esben/dist-compare-reports/tree/js/even-more-mongoose-improvements_1584196308188) (which is currently being rerun due to a last-minute refactoring) does not show a result difference though, as the benchmarks that inspired these changes are not accessible on GitHub (any more). See the tests for the expected effects.
This is the last planned NoSQL improvement from me.
=> JS: Mongoose improvements: Mongoose and createConnection

java/ql/src/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
Requested on https://github.com/Semmle/ql/issues/3079.  Seems like reasonable taint steps.
=> Java: Add apache Base64 taint steps.

java/ql/src/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
This seems like a straightforward addition.  See https://github.com/Semmle/ql/issues/3079.
=> Java: Add URLDecoder.decode as taint step.

java/ql/src/semmle/code/java/Member.qll
Fixes https://github.com/Semmle/ql/issues/3103.
=> Java: Fixup FinalizeMethod definition.

javascript/ql/src/experimental/SockJS/SockJS.qll, javascript/ql/src/experimental/SockJS/examples/server.js
At the moment CodeQL can not work with none of Websocket libraries. This code adds remote flow source for quie popular framework SockJS.
=> Experimental SockJS support

python/ql/test/library-tests/PointsTo/regressions/wrong/classmethod/Test.expected, python/ql/test/library-tests/PointsTo/regressions/wrong/classmethod/Test.ql, python/ql/test/library-tests/PointsTo/regressions/wrong/classmethod/test.py, python/ql/test/query-tests/Expressions/callable/NonCallableCalled.expected, python/ql/test/query-tests/Expressions/callable/test.py
Specifically a problem when using a second decorator
=> Python: Add points-to regression when using @classmethod decorators

cpp/ql/src/semmle/code/cpp/ir/implementation/aliased_ssa/Instruction.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/raw/Instruction.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/Instruction.qll, csharp/ql/src/semmle/code/csharp/ir/implementation/raw/Instruction.qll, csharp/ql/src/semmle/code/csharp/ir/implementation/unaliased_ssa/Instruction.qll
I missed this suggestion before I merged the original PR. Fixing it now before I forget.
=> C++: Late fix for PR feedback

javascript/ql/src/semmle/javascript/dataflow/Configuration.qll
I think [this small evaluation](https://git.semmle.com/erik/dist-compare-reports/tree/profiling-erik-krogh.northeurope.cloudapp.azure.com_1584703475883) speaks for itself.
Currently waiting for a large evaluation.
=> JS: add more isRelevant() calls

docs/language/ql-spec/language.rst
@shati-patel I missed this during review.
=> Change 'Set Literals' to 'Set literals'

cpp/ql/src/semmle/code/cpp/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/tainttracking3/TaintTrackingImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/tainttracking4/TaintTrackingImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/tainttracking5/TaintTrackingImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/tainttracking2/TaintTrackingImpl.qll
Modelled after the correponding comment for `DataFlowImpl.qll`.
=> Data flow: Add module doc comment for `TaintTrackingImpl.qll`

javascript/ql/src/semmle/javascript/dataflow/TaintTracking.qll
One of the failures in the recent dist upgrade was from a bad join in the charpred for `DictionaryTaintStep`. This changes it to:
- Use `getALocalSource` instead of type inference.
- Step into the object literal instead of to a _use_ of the object literal. Stepping directly to a use can create N^2 edges.
=> JS: Fix perf issue in DictionaryTaintStep

csharp/ql/test/query-tests/Nullness/E.cs, csharp/ql/test/query-tests/Nullness/EqualityCheck.expected, csharp/ql/test/query-tests/Nullness/Implications.expected, csharp/ql/test/query-tests/Nullness/NullCheck.expected, csharp/ql/test/query-tests/Nullness/NullMaybe.expected
Reported [here](https://github.com/Semmle/ql/issues/3134).
=> C#: Add false-positive test for NullMaybe.ql

cpp/ql/src/semmle/code/cpp/ir/dataflow/DefaultTaintTracking.qll
These docs are mostly copied and adapted from `DefaultTaintTrackingImpl.qll`.
=> C++: QLDoc in DefaultTaintTracking

python/ql/src/Functions/OverlyComplexDelMethod.ql, python/ql/test/query-tests/Functions/general/OverlyComplexDelMethod.expected
This PR is part of the ValueAPI modernization effort.
=> Python: ObjectAPI to ValueAPI: OverlyComplexDelMethod

docs/language/learn-ql/writing-queries/query-help.rst
a.k.a. "fun with rst tables" 😭 
Fixes https://github.com/github/semmle-docs/issues/62. 
See the preview [here](https://jenkins.internal.semmle.com/job/Docs/job/Generate-Sphinx/1630/artifact/target/sphinx/learn-ql/writing-queries/query-help.html).
=> Docs: Change "Qhelp" to "Query help"

README.md
Per https://github.com/Semmle/ql/pull/3205, code is now licensed under the MIT License.
=> Update README to reflect new license

python/ql/src/Classes/UselessClass.ql
This PR is part of the ValueAPI modernization effort.
=> Python: ObjectAPI to ValueAPI: UselessClass

cpp/ql/src/semmle/code/cpp/ir/implementation/aliased_ssa/internal/PrintSSA.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/PrintSSA.qll, cpp/ql/src/semmle/code/cpp/ir/internal/IRUtilities.qll, cpp/ql/test/library-tests/valuenumbering/GlobalValueNumbering/ir_gvn.expected, csharp/ql/src/semmle/code/csharp/ir/implementation/unaliased_ssa/internal/PrintSSA.qll
Two minor fixes that I made as part of debugging a larger change. I wanted to separate these out from that change, though. Individual changes are detailed in the corresponding commit messages.
=> C++: A couple of fixes for IR dumps

change-notes/1.24/analysis-python.md
=> Python: Finalise change notes for 1.24.

docs/language/global-sphinx-files/qllexer.py
Fixes https://github.com/github/semmle-docs/issues/73.
~(Just waiting for the internal preview to check that it works.)~
=> Highlight "unique" as a keyword in CodeQL docs

csharp/autobuilder/Semmle.Autobuild.Tests/BuildScripts.cs
https://github.com/Semmle/ql/pull/3199 follow-up.
=> C#: Update expected test output

docs/language/learn-ql/python/ql-for-python.rst
=> Docs: Update link text

java/ql/src/semmle/code/java/dataflow/FlowSources.qll, java/ql/test/library-tests/dataflow/taintsources/SpringMultiPart.java, java/ql/test/library-tests/dataflow/taintsources/options, java/ql/test/library-tests/dataflow/taintsources/remote.expected, java/ql/test/stubs/springframework-5.2.3/LICENSE.txt, java/ql/test/stubs/springframework-5.2.3/org/springframework/core/io/InputStreamSource.java, java/ql/test/stubs/springframework-5.2.3/org/springframework/core/io/Resource.java, java/ql/test/stubs/springframework-5.2.3/org/springframework/lang/Nullable.java, java/ql/test/stubs/springframework-5.2.3/org/springframework/util/MultiValueMap.java, java/ql/test/stubs/springframework-5.2.3/org/springframework/web/multipart/MultipartFile.java, java/ql/test/stubs/springframework-5.2.3/org/springframework/web/multipart/MultipartRequest.java
This PR adds all get methods of `org.springframework.web.multipart.MultipartFile` as a RemoteFlowSource.
=> Java: add `org.springframework.web.multipart.MultipartFile::getX` as RemoteFlowSource

csharp/autobuilder/Semmle.Autobuild/Autobuilder.cs
For some reason, the previous code generated some compiler warnings. The only change is to move the the local function to class level, and the warnings went away.
I suspect a compiler bug.
=> C#: Remove nullability warnings

docs/language/learn-ql/python/statements-expressions.rst
Fixes https://github.com/github/codeql/issues/3360
=> Docs: Fix result of cmp.getComparator(0) in Python tutorial

docs/supported-queries.md
Add some details about query tagging (see https://wiki.semmle.com/display/IN/Query+tags and https://wiki.semmle.com/display/IN/Modelling+CWEs+at+Semmle).
=> Add details about query tagging to supported-queries.md

javascript/ql/src/experimental/adaptivethreatmodeling/docs/about-adaptive-threat-modeling.md
Small technical fix to `.md` for ATM.
=> correct "known endpoints" to "candidate endpoints"

cpp/ql/src/semmle/code/cpp/exprs/Access.qll
Pointed out in https://github.com/github/codeql/issues/3356.
=> C++: Fix error in QLDoc.

python/ql/src/Functions/ModificationOfParameterWithDefault.ql, python/ql/test/query-tests/Functions/general/functions_test.py
Fixes https://github.com/github/codeql/issues/3397
=> Python: More safe methods for py/modification-of-default-value 

cpp/ql/test/library-tests/dataflow/fields/flow.expected, cpp/ql/test/library-tests/dataflow/fields/simple.cpp
Based on the Java example in https://github.com/github/codeql/pull/3421.
=> C++: Add testcase for #3110

javascript/ql/src/Security/CWE-079/examples/XssThroughDom.js, javascript/ql/src/Security/CWE-079/examples/XssThroughDomFixed.js, javascript/ql/src/Security/CWE-089/examples/SqlInjection.js, javascript/ql/src/Security/CWE-134/examples/TaintedFormatStringBad.js, javascript/ql/src/Security/CWE-134/examples/TaintedFormatStringGood.js, javascript/ql/src/Security/CWE-327/examples/BrokenCryptoAlgorithm.js, javascript/ql/src/Security/CWE-352/examples/MissingCsrfMiddlewareBad.js, javascript/ql/src/Security/CWE-352/examples/MissingCsrfMiddlewareGood.js, javascript/ql/src/Security/CWE-502/examples/UnsafeDeserializationBad.js, javascript/ql/src/Security/CWE-502/examples/UnsafeDeserializationGood.js, javascript/ql/src/Security/CWE-601/examples/ServerSideUrlRedirect.js, javascript/ql/src/Security/CWE-601/examples/ServerSideUrlRedirectGood.js, javascript/ql/src/Security/CWE-611/examples/Xxe.js, javascript/ql/src/Security/CWE-611/examples/XxeGood.js, javascript/ql/src/Security/CWE-776/examples/XmlBomb.js, javascript/ql/src/Security/CWE-776/examples/XmlBombGood.js, javascript/ql/src/Security/CWE-798/examples/HardcodedCredentials.js, javascript/ql/src/Security/CWE-843/examples/TypeConfusionThroughParameterTampering.js, javascript/ql/src/Security/CWE-843/examples/TypeConfusionThroughParameterTampering_fixed.js, javascript/ql/src/Security/CWE-916/examples/InsufficientPasswordHash.js, javascript/ql/src/Security/CWE-916/examples/InsufficientPasswordHash_fixed.js, javascript/ql/src/Security/CWE-918/examples/RequestForgeryBad.js, javascript/ql/src/Security/CWE-918/examples/RequestForgeryGood.js
This is most of the fixes for <https://github.com/github/codeql-javascript-team/issues/114>.
Let's discuss the next step in there.
=> JS: fix some FNs in the qhelp examples

docs/language/support/language-support.rst
This PR updates the information for people with questions about language and compiler support.
This change doesn't need to be included in any built artifacts.
=> CodeQL 1.24: Update information on support

docs/language/support/language-support.rst
=> Merge rc/1.24 back to master

javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/library-tests/TaintTracking/DataFlowTracking.expected, javascript/ql/test/library-tests/TaintTracking/capture-flow.js
Adds a test for missed flow as described in https://github.com/github/codeql-javascript-team/issues/156
=> JS: Add test case for missed captured flow

java/ql/src/semmle/code/java/Member.qll
=> Java: Fix for private interface methods.

cpp/ql/src/semmle/code/cpp/commons/unix/Constants.qll
More work towards https://github.com/github/codeql-c-analysis-team/issues/40.
I've borrowed some of the information from https://www.gnu.org/software/libc/manual/html_node/Permission-Bits.html and https://www.gnu.org/software/libc/manual/html_node/Access-Modes.html.
=> C++: QLDoc for Constants

java/ql/test/library-tests/typeflow/A.java, java/ql/test/library-tests/typeflow/typeflow.expected
This adds a test case for https://github.com/github/codeql/pull/3607
=> Java: Add test case for TypeFlow improvement

change-notes/1.25/analysis-python.md, python/ql/src/semmle/python/security/strings/Basic.qll, python/ql/src/semmle/python/security/strings/External.qll, python/ql/src/semmle/python/web/bottle/Request.qll, python/ql/src/semmle/python/web/turbogears/Request.qll, python/ql/src/semmle/python/web/turbogears/Response.qll
See details in commit messages.
=> Python: Fix some problems in TaintKind useage

java/ql/src/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
My attempt to implement https://github.com/github/codeql/issues/3139
=> add support for java.io.StringWriter

javascript/ql/src/Security/CWE-295/DisablingCertificateValidation.qhelp, javascript/ql/src/Security/CWE-295/DisablingCertificateValidation.ql, javascript/ql/test/query-tests/Security/CWE-295/DisablingCertificateValidation.expected, javascript/ql/test/query-tests/Security/CWE-295/DisablingCertificateValidation.qlref, javascript/ql/test/query-tests/Security/CWE-295/tst.js
CVE-2018-1000096: TP/TN
Similar to `js/disabling-electron-websecurity`
=> JS: add query js/disabling-certificate-validation

javascript/ql/src/Security/CWE-327/BadRandomness.qhelp, javascript/ql/src/Security/CWE-327/BadRandomness.ql, javascript/ql/src/semmle/javascript/security/dataflow/InsecureRandomness.qll, javascript/ql/src/semmle/javascript/security/dataflow/InsecureRandomnessCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-327/BadRandomness.expected, javascript/ql/test/query-tests/Security/CWE-327/BadRandomness.qlref, javascript/ql/test/query-tests/Security/CWE-327/bad-random.js
Gets a TP/TN on CVE-2018-1000620
TODO:
=> JS: Introduce query to detect biased random number generators

docs/language/learn-ql/go/ast-class-reference.rst, docs/language/learn-ql/go/ql-for-go.rst
Mergeback PR to include recent documentation edits!
=> Merge rc/1.24 into master

change-notes/1.25/analysis-javascript.md
Adds missing change note for https://github.com/github/codeql/pull/3643
=> JS: add changenote for yargs

python/ql/src/semmle/python/objects/ObjectAPI.qll
Matching the one for `Function.getQualifiedName`
=> Python: Add QLDoc for FunctionValue.getQualifiedName

java/ql/src/Likely Bugs/Comparison/NoAssignInBooleanExprs.ql
`ConditionalStmt` is the superclass of:
- `IfStmt`
- `ForStmt`
- `WhileStmt`
- `DoStmt`
=> Simplify NoAssignInBooleanExprs.ql

docs/language/ql-training/query-examples/cpp/data-flow-cpp-2.ql, docs/language/ql-training/query-examples/java/empty-if-java-class.ql
=> Fix training example syntax

cpp/ql/src/semmle/code/cpp/models/implementations/Gets.qll, cpp/ql/src/semmle/code/cpp/security/CommandExecution.qll
I was hoping one of these would fix an issue I was looking at.  They didn't.  But the improvements are worth keeping anyway.
=> C++: Extend the GetsFunction and SystemFunction models.

cpp/ql/src/semmle/code/cpp/ObjectiveC.qll, cpp/ql/src/semmle/code/cpp/security/BufferWrite.qll, cpp/ql/src/semmle/code/cpp/security/FileWrite.qll, cpp/ql/src/semmle/code/cpp/security/OutputWrite.qll
Complete and improve QLDoc in ObjectiveC.qll, BufferWrite.qll, FileWrite.qll, OutputWrite.qll.
=> C++: QLDoc ObjectiveC.qll, BufferWrite.qll, FileWrite.qll, OutputWrite.qll

csharp/ql/src/Concurrency/Concurrency.qll, csharp/ql/src/Documentation/Documentation.qll, csharp/ql/src/cil.qll, csharp/ql/src/dotnet.qll, csharp/ql/src/semmle/code/cil/Instructions.qll
Improve the qldoc coverage of our public API.
=> C#: Improve qldoc coverage

javascript/ql/src/semmle/javascript/DOM.qll, javascript/ql/test/library-tests/DOM/Customizations.expected, javascript/ql/test/library-tests/DOM/nameditems.js, javascript/ql/test/query-tests/Security/CWE-079/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/tst.js
Fix for [ODASA-7528](https://jira.semmle.com/browse/ODASA-7528)
=> JS: Recognize calls to .item and .namedItem

cpp/ql/src/semmle/code/cpp/Parameter.qll, cpp/ql/src/semmle/code/cpp/Specifier.qll, cpp/ql/src/semmle/code/cpp/Struct.qll, cpp/ql/src/semmle/code/cpp/TypedefType.qll, cpp/ql/src/semmle/code/cpp/Union.qll, cpp/ql/src/semmle/code/cpp/UserType.qll, cpp/ql/src/semmle/code/cpp/Variable.qll, cpp/ql/src/semmle/code/cpp/commons/File.qll, cpp/ql/src/semmle/code/cpp/security/SecurityOptions.qll
Add more QLDoc in more places.
=> C++: Even more QLDoc

cpp/ql/src/semmle/code/cpp/TestFile.qll, cpp/ql/src/semmle/code/cpp/commons/StringAnalysis.qll, cpp/ql/src/semmle/code/cpp/exprs/Access.qll, cpp/ql/src/semmle/code/cpp/exprs/ArithmeticOperation.qll, cpp/ql/src/semmle/code/cpp/exprs/BitwiseOperation.qll, cpp/ql/src/semmle/code/cpp/exprs/BuiltInOperations.qll, cpp/ql/src/semmle/code/cpp/exprs/Call.qll, cpp/ql/src/semmle/code/cpp/exprs/Cast.qll, cpp/ql/src/semmle/code/cpp/exprs/ComparisonOperation.qll, cpp/ql/src/semmle/code/cpp/exprs/Expr.qll, cpp/ql/src/semmle/code/cpp/exprs/Lambda.qll, cpp/ql/src/semmle/code/cpp/exprs/LogicalOperation.qll, cpp/ql/src/semmle/code/cpp/exprs/ObjectiveC.qll, cpp/ql/src/semmle/code/cpp/security/PrintfLike.qll
Yet more QLDoc in yet more places.
I think this is the last chunk of QLDoc improvements I can fit in for this quarter, but I don't see any reason we can't continue to work on this next quarter.
=> C++: Yet more QLDoc

javascript/ql/src/semmle/javascript/frameworks/Files.qll, javascript/ql/test/library-tests/frameworks/Concepts/tst-file-names.js
cf https://www.npmjs.com/package/walk-sync
=> JavaScript: Fix module name for `walk-sync` package.

cpp/ql/src/semmle/code/cpp/commons/Synchronization.qll, cpp/ql/src/semmle/code/cpp/exprs/Literal.qll, cpp/ql/src/semmle/code/cpp/security/FunctionWithWrappers.qll, cpp/ql/src/semmle/code/cpp/security/Overflow.qll, cpp/ql/src/semmle/code/cpp/security/SensitiveExprs.qll
I noticed yesterday we're still short of our QLDoc target for the quarter, so I fitted a bit more work in.
@jbj
=> C++: Bit more QLDoc

docs/language/support/reusables/frameworks.rst
https://github.com/github/codeql/pull/3836 retargeted to rc/1.24.
@jf205 can I get another approval?
=> JS: Add Vue to list of supported frameworks

docs/language/support/reusables/frameworks.rst
Only trivial docs changes and no conflicts.
=> 1.24 -> master mergeback

cpp/ql/src/semmle/code/cpp/security/Encryption.qll, cpp/ql/test/library-tests/security/encryption/test.cpp, cpp/ql/test/library-tests/security/encryption/test.expected, cpp/ql/test/library-tests/security/encryption/test.ql
Address follow-up request at: https://github.com/github/codeql/pull/3837#discussion_r447630902
=> C++: Make getSecureAlgorithmRegex() work as expected.

cpp/ql/src/semmle/code/cpp/ir/implementation/aliased_ssa/IRBlock.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/aliased_ssa/IRVariable.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/aliased_ssa/Instruction.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/raw/IRBlock.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/raw/IRVariable.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/raw/Instruction.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/IRBlock.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/IRVariable.qll, cpp/ql/src/semmle/code/cpp/ir/implementation/unaliased_ssa/Instruction.qll, csharp/ql/src/experimental/ir/implementation/raw/IRBlock.qll, csharp/ql/src/experimental/ir/implementation/raw/IRVariable.qll, csharp/ql/src/experimental/ir/implementation/raw/Instruction.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/IRBlock.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/IRVariable.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/Instruction.qll
This PR just fixes a few bits of PR feedback from my previous QLDoc PR.
=> C++: QLDoc cleanup

csharp/ql/src/semmle/code/csharp/controlflow/ControlFlowGraph.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/Condition.expected, csharp/ql/test/library-tests/controlflow/graph/ConditionalAccess.cs, csharp/ql/test/library-tests/controlflow/graph/Consistency.expected, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/EnclosingCallable.expected, csharp/ql/test/library-tests/controlflow/graph/EntryElement.expected, csharp/ql/test/library-tests/controlflow/graph/ExitElement.expected, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, csharp/ql/test/library-tests/controlflow/graph/Nodes.expected
Fixes https://github.com/github/codeql/issues/3868.
=> C#: Fix CFG for conditional method calls with `out` parameters

.github/codeql/codeql-config.yml
... Possibly some of the other language teams want to get on this? :slightly_smiling_face: 
If so, give me a shout!
=> Code Scanning: Don't scan the Python directory.

misc/suite-helpers/code-scanning-selectors.yml, misc/suite-helpers/lgtm-selectors.yml, misc/suite-helpers/security-and-quality-selectors.yml, misc/suite-helpers/security-extended-selectors.yml
=> CodeQL: exclude `experimental`  queries from LGTM suites

java/ql/src/semmle/code/java/Expr.qll
Fixes https://github.com/github/codeql/issues/3631
=> Java: Add Expr.getAnEnclosingStmt.

cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/IRDataflowTestCommon.qll
Fixes https://github.com/github/codeql-c-analysis-team/issues/111
=> C++: make IR BarrierGuard::checks match AST

csharp/autobuilder/Semmle.Autobuild.Shared/Autobuilder.cs, csharp/autobuilder/Semmle.Autobuild.Shared/BuildCommandAutoRule.cs, csharp/autobuilder/Semmle.Autobuild.Shared/BuildCommandRule.cs
As suggested by @calumgrant on https://github.com/github/codeql/pull/3846.
=> C#: Introduce delegate type in autobuilder

change-notes/1.25/analysis-csharp.md
Change note for https://github.com/github/codeql/pull/3366.
=> C#: Add change note

change-notes/1.25/analysis-javascript.md, javascript/ql/src/semmle/javascript/frameworks/SystemCommandExecutors.qll, javascript/ql/test/query-tests/Security/CWE-078/CommandInjection.expected, javascript/ql/test/query-tests/Security/CWE-078/UselessUseOfCat.expected, javascript/ql/test/query-tests/Security/CWE-078/other.js
Automatically inferred via flow summaries :tada:
See individual commits for details.
=> JavaScript: Add more command-injection sinks.

java/ql/src/experimental/Security/CWE/CWE-297/InsecureJavaMail.qhelp
- Creates a list item for every link
- Prefixes the links with the context
=> [Java] Improve InsecureJavaMail.qhelp references

csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
This change removes the restriction that only access paths of length 1 can have the head adjusted, based on type information from the call to the relevant library-code callable.
Since we don't have unbound IPA types (yet), I had to introduce a `newtype TAdjustedAccessPath` to represent adjusted access paths. The [C# differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/313/) shows no changes in performance nor results.
=> C#: More type-based adjustment of library-flow access paths

java/ql/src/Security/CWE/CWE-209/StackTraceExposure.ql
=> Java: stack trace exposure: address false positives

java/ql/src/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql
Let's try this at precision high as discussed.
=> Java: Update precision of java/weak-cryptographic-algorithm.

java/ql/src/experimental/CWE-532/SensitiveInfoLog.ql
Add a new logger type Log4J 2, and add a new search string "secret" which could contain sensitive information in debug logs
=> Add Log4J 2 and a new search string secret

python/ql/src/experimental/dataflow/internal/TaintTrackingPrivate.qll
=> Python: Reformualte explanation of experience from JS

java/ql/src/Security/CWE/CWE-079/XSS.ql, java/ql/src/semmle/code/java/security/XSS.qll
This PR abstracts the sanitizer and additional taint step of the XSS analysis to enable customization.
The existing implementation is moved into a default implementation of these abstractions.
=> Java: Customizable XSS analysis

cpp/ql/src/semmle/code/cpp/rangeanalysis/SimpleRangeAnalysis.qll
This PR adds support for experimental `SimpleRangeAnalysisExpr`s which are also `AssignOperation`s. The key problem here was that `AssignOperation`s are also `RangeSsaDefinition`s, but the library did not propagate bounds to their uses. The following changes are made to support this use case:
- In `getDef(Upper|Lower)BoundsImpl` use a generic form that supports all `AssignOperation`s, not just those hard-coded into the library. This works by delegating to the expression itself. Note: we need to use the bounds of the expression before conversion here, because the conversion do not apply to later uses of the lvalue variable.
- `defDependsOnDef` is updated to make it generic to all analyzable `AssignOperation`s.
=> C++: Support `AssignOperation`s with `SimpleRangeAnalysisExpr`s

cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/defaulttainttracking.cpp, cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/tainted.expected, cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/test_diff.expected
Part of https://github.com/github/codeql-c-analysis-team/issues/103.
=> C++: Add field to object taint tests

cpp/ql/src/jsf/4.10 Classes/AV Rule 82.ql
Fixes https://github.com/github/codeql/issues/4215
=> C++: Add cases for conditional and comma operator in AV Rule 82

csharp/ql/src/semmle/code/csharp/commons/Collections.qll, csharp/ql/test/query-tests/ReadOnlyContainer/ReadOnlyContainer.cs, csharp/ql/test/query-tests/ReadOnlyContainer/ReadOnlyContainer.expected
Fixes https://github.com/github/codeql/issues/4199
=> C#: Improve empty collection check to not report on collections with property writes

cpp/ql/src/semmle/code/cpp/dataflow/internal/AddressFlow.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp, cpp/ql/test/library-tests/dataflow/dataflow-tests/localFlow.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test_diff.expected, cpp/ql/test/library-tests/dataflow/fields/arrays.cpp, cpp/ql/test/library-tests/dataflow/fields/by_reference.cpp, cpp/ql/test/library-tests/dataflow/fields/dataflow-consistency.expected, cpp/ql/test/library-tests/dataflow/fields/dataflow-ir-consistency.expected, cpp/ql/test/library-tests/dataflow/fields/flow-diff.expected, cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected, cpp/ql/test/library-tests/dataflow/fields/partial-definition-diff.expected, cpp/ql/test/library-tests/dataflow/fields/partial-definition-ir.expected, cpp/ql/test/library-tests/dataflow/fields/partial-definition.expected, cpp/ql/test/library-tests/dataflow/fields/path-flow.expected, cpp/ql/test/library-tests/dataflow/fields/realistic.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/arrayassignment.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/taint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/test_diff.expected, cpp/ql/test/library-tests/dataflow/taint-tests/vector.cpp
This is my attempt to address the lack of data flow reported by @rvermeulen in https://github.slack.com/archives/CP75PA8Q1/p1599747786196400. I wrote a few tests specifically for this problem, but it turns out it was already well covered by existing tests.
This PR will conflict with https://github.com/github/codeql/pull/4230.
=> C++: Add AST flow through arrays

python/ql/src/experimental/dataflow/internal/DataFlowPrivate.qll, python/ql/src/experimental/dataflow/internal/DataFlowPublic.qll, python/ql/src/semmle/python/essa/SsaCompute.qll, python/ql/test/experimental/dataflow/tainttracking/customSanitizer/TestTaint.expected, python/ql/test/experimental/dataflow/tainttracking/customSanitizer/TestTaint.ql, python/ql/test/experimental/dataflow/tainttracking/customSanitizer/test.py, python/ql/test/experimental/meta/debug/dataflow.qll
This PR implements barrier guards based on `ConditonBlock` from the `GuardedControlFlow` library.
The test case for `isSanitizerGuard` is implemented as an example (and passes); please review if this is an acceptable API (here `BarrierGuard` is a control flow node rather than an expression).
=> Python: Implement `BarrierGuard`

cpp/ql/src/semmle/code/cpp/controlflow/internal/ConstantExprs.qll
It is possible for the upcoming frontend release to make
```
(bool)e
```
where e has a constant value 0, but the (implicit) cast has no constant value. This was causing us to not understand `__assume(0)` correctly.
Now compileTimeConstantInt will handle casts itself if necessary.
https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1435/ is happy.
=> C++: Improve `compileTimeConstantInt`

change-notes/1.25/analysis-java.md, change-notes/1.25/analysis-python.md, csharp/extractor/Semmle.Extraction.CIL/Context.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/Assembly.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/File.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/Folder.cs, csharp/extractor/Semmle.Extraction.CIL/Factories.cs, csharp/extractor/Semmle.Extraction.CSharp/Analyser.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Compilation.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor.cs, csharp/extractor/Semmle.Extraction.Tests/FilePattern.cs, csharp/extractor/Semmle.Extraction.Tests/Layout.cs, csharp/extractor/Semmle.Extraction.Tests/PathTransformer.cs, csharp/extractor/Semmle.Extraction.Tests/TrapWriter.cs, csharp/extractor/Semmle.Extraction/Entities/File.cs, csharp/extractor/Semmle.Extraction/Entities/Folder.cs, csharp/extractor/Semmle.Extraction/Extractor.cs, csharp/extractor/Semmle.Extraction/FilePattern.cs, csharp/extractor/Semmle.Extraction/Layout.cs, csharp/extractor/Semmle.Extraction/PathTransformer.cs, csharp/extractor/Semmle.Extraction/TrapWriter.cs, csharp/extractor/Semmle.Util/CanonicalPathCache.cs
I had to resolve a few merge conflicts; not sure if it can be seen in the web UI, but `gitk` at least shows how the conflicts were resolved.
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/454/
=> Merge rc/1.25 into main

java/change-notes/2020-09-22-hibernate-sql-sinks.md
Add missing change note.
@aschackmull
=> Java: change note for Hiberate ORM improvements

javascript/ql/src/semmle/javascript/frameworks/Express.qll, javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/ServerSideUrlRedirect.expected, javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/express.js
Gains [a TP in juice-shop](https://github.com/bkimminich/juice-shop/blob/master/routes/redirect.js#L16).
=> JS: change `SimpleParameter` to `Parameter` in the express model to support destructuring parameters

javascript/ql/src/semmle/javascript/AMD.qll, javascript/ql/src/semmle/javascript/frameworks/AngularJS/AngularJSCore.qll, javascript/ql/src/semmle/javascript/frameworks/AngularJS/DependencyInjections.qll, javascript/ql/src/semmle/javascript/frameworks/AngularJS/ServiceDefinitions.qll, javascript/ql/src/semmle/javascript/frameworks/Connect.qll, javascript/ql/src/semmle/javascript/frameworks/Firebase.qll, javascript/ql/src/semmle/javascript/frameworks/Hapi.qll, javascript/ql/src/semmle/javascript/frameworks/Koa.qll, javascript/ql/src/semmle/javascript/frameworks/NodeJSLib.qll, javascript/ql/src/semmle/javascript/frameworks/Restify.qll, javascript/ql/src/semmle/javascript/heuristics/AdditionalRouteHandlers.qll, javascript/ql/test/library-tests/AMD/AmdModule.expected, javascript/ql/test/library-tests/AMD/AmdModuleDefinition.expected, javascript/ql/test/library-tests/AMD/AmdModuleDefinition.ql, javascript/ql/test/library-tests/AMD/AmdModuleDependencies.expected, javascript/ql/test/library-tests/AMD/AmdModuleExportedSymbol.expected, javascript/ql/test/library-tests/AMD/AmdModuleExpr.expected, javascript/ql/test/library-tests/AMD/AmdModuleImportedModule.expected, javascript/ql/test/library-tests/AMD/AmdModule_exports.expected, javascript/ql/test/library-tests/AMD/tst5.js, javascript/ql/test/library-tests/frameworks/AngularJS/dependencies/DependencyKinds.expected, javascript/ql/test/library-tests/frameworks/AngularJS/dependencies/dependency-kinds.js, javascript/ql/test/library-tests/frameworks/Express/RouteHandler.qll, javascript/ql/test/library-tests/frameworks/connect/src/test.js, javascript/ql/test/library-tests/frameworks/connect/tests.expected
I went through the uses of `SimpleParameter` and changed the ones where I thought we could potentially gain results by using `Parameter` instead.
=> JS: Use Parameter instead of SimpleParameter in more models

java/ql/src/semmle/code/Location.qll
=> Java: Include column numbers in Location.toString

javascript/ql/src/Declarations/DeadStoreOfProperty.ql
Removes a stray TODO I forgot in https://github.com/github/codeql/pull/3930.
=> JS: remove stray todo

docs/query-classification-and-display.md
=> Docs: Query classification and display

cpp/ql/src/Best Practices/Exceptions/LeakyCatch.qhelp, cpp/ql/src/Best Practices/Unused Entities/UnusedStaticVariables.qhelp, cpp/ql/src/Best Practices/UseOfGoto.qhelp, cpp/ql/src/Critical/MissingNullTest.qhelp, cpp/ql/src/Likely Bugs/Arithmetic/BadCheckOdd.qhelp, cpp/ql/src/Likely Bugs/Arithmetic/BitwiseSignCheck.qhelp, cpp/ql/src/Likely Bugs/Arithmetic/ComparisonPrecedence.qhelp, cpp/ql/src/Likely Bugs/Arithmetic/FloatComparison.qhelp, cpp/ql/src/Likely Bugs/Arithmetic/IntMultToLong.qhelp, cpp/ql/src/Likely Bugs/Conversion/LossyPointerCast.qhelp, cpp/ql/src/Likely Bugs/Format/WrongTypeFormatArguments.qhelp, cpp/ql/src/Likely Bugs/Leap Year/Adding365DaysPerYear.qhelp, cpp/ql/src/Likely Bugs/Leap Year/UncheckedLeapYearAfterYearModification.qhelp, cpp/ql/src/Likely Bugs/Leap Year/UncheckedReturnValueForTimeFunctions.qhelp, cpp/ql/src/Likely Bugs/Leap Year/UnsafeArrayForDaysOfYear.qhelp, cpp/ql/src/Likely Bugs/Likely Typos/MissingEnumCaseInSwitch.qhelp, cpp/ql/src/Likely Bugs/Memory Management/SuspiciousCallToMemset.qhelp, cpp/ql/src/Likely Bugs/NestedLoopSameVar.qhelp, cpp/ql/src/Likely Bugs/OO/NonVirtualDestructor.qhelp, cpp/ql/src/Metrics/Files/FMacroRatio.qhelp, cpp/ql/src/Metrics/Files/FTimeInFrontend.qhelp, cpp/ql/src/Security/CWE/CWE-089/SqlTainted.qhelp, cpp/ql/src/jsf/4.10 Classes/AV Rule 89.qhelp, cpp/ql/src/jsf/4.13 Functions/AV Rule 114.qhelp, cpp/ql/src/jsf/4.16 Initialization/AV Rule 145.qhelp, cpp/ql/src/jsf/4.24 Control Flow Structures/AV Rule 189.qhelp
Fixes https://github.com/github/codeql-c-analysis-team/issues/152. I only had to find a new reference for the date-related queries.
=> C++: Fix broken qhelp links

python/ql/src/semmle/python/dataflow/new/RemoteFlowSources.qll, python/ql/src/semmle/python/dataflow/new/TypeTracker.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowPublic.qll, python/ql/src/semmle/python/frameworks/MySQLdb.qll, python/ql/src/semmle/python/frameworks/Werkzeug.qll
Fixes the non-`old` part of https://github.com/github/codeql-python-team/issues/191.
=> Python: Fix ql doc

python/ql/src/semmle/python/dataflow/new/internal/TaintTrackingPrivate.qll, python/ql/src/semmle/python/frameworks/Django.qll, python/ql/src/semmle/python/frameworks/Fabric.qll, python/ql/src/semmle/python/frameworks/Flask.qll, python/ql/src/semmle/python/frameworks/Werkzeug.qll
Now that auto-formatting rules have been updated
=> Python: Update set literal formatting

cpp/ql/src/semmle/code/cpp/Class.qll, cpp/ql/src/semmle/code/cpp/MemberFunction.qll, cpp/ql/src/semmle/code/cpp/Print.qll, cpp/ql/src/semmle/code/cpp/Type.qll, cpp/ql/src/semmle/code/cpp/exprs/ComparisonOperation.qll, cpp/ql/src/semmle/code/cpp/exprs/Expr.qll, cpp/ql/src/semmle/code/cpp/exprs/Literal.qll, cpp/ql/src/semmle/code/cpp/exprs/LogicalOperation.qll, cpp/ql/src/semmle/code/cpp/internal/QualifiedName.qll
Addresses most of https://github.com/github/codeql-c-analysis-team/issues/60
=> C++: Remove uses of abstract from the standard library.

csharp/ql/src/semmle/code/csharp/controlflow/BasicBlocks.qll, csharp/ql/src/semmle/code/csharp/controlflow/internal/PreBasicBlocks.qll, csharp/ql/src/semmle/code/csharp/security/dataflow/TaintedPath.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/Condition.expected, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/EnclosingCallable.expected, csharp/ql/test/library-tests/controlflow/guards/BooleanGuardedExpr.expected, csharp/ql/test/library-tests/controlflow/guards/GuardedControlFlowNode.expected, csharp/ql/test/library-tests/controlflow/guards/GuardedExpr.expected, csharp/ql/test/library-tests/controlflow/guards/MatchingGuardedExpr.expected, csharp/ql/test/query-tests/Nullness/NullMaybe.expected
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/656/
=> C#: Always create basic blocks for nodes with a conditional predecessor

javascript/change-notes/2020-11-30-nosql.md, javascript/ql/src/Security/CWE-089/SqlInjection.qhelp, javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll, javascript/ql/test/query-tests/Security/CWE-089/untyped/DatabaseAccesses.expected, javascript/ql/test/query-tests/Security/CWE-089/untyped/SqlInjection.expected, javascript/ql/test/query-tests/Security/CWE-089/untyped/mongoose.js
=> JavaScript: Add models for more Mongoose methods.

cpp/ql/src/semmle/code/cpp/dataflow/internal/FlowVar.qll
Applies fix from https://github.com/github/codeql/pull/4677/files
@adityasharad
=> Fix FlowVar overflow bug

csharp/ql/src/Useless code/DefaultToString.qll
Follow-up on https://github.com/github/codeql/pull/4704.
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/673/
=> C#: Improve join-order in `DefaultToString.qll`

java/change-notes/2020-12-09-xxe-fp-fix.md, java/ql/src/semmle/code/java/security/XmlParsers.qll, java/ql/test/query-tests/security/CWE-611/SAXParserTests.java, java/ql/test/query-tests/security/CWE-611/XXE.expected
resolves https://github.com/github/codeql/issues/4792
=> Java: Fix false positive in the XXE query

docs/codeql/_static/custom.css_t
See https://github.com/github/codeql/pull/4838.
=> [CodeQL docs] Fix two CSS bugs (rc/1.26)

docs/codeql/codeql-language-guides/analyzing-data-flow-in-csharp.rst
fix for the issue #4848 and #4849
=> Fix for csharp docs

csharp/ql/src/semmle/code/csharp/controlflow/internal/Completion.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/Condition.expected, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/EnclosingCallable.expected, csharp/ql/test/library-tests/controlflow/graph/ExitElement.expected, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, csharp/ql/test/library-tests/controlflow/graph/Nodes.expected, csharp/ql/test/library-tests/exceptions/Exceptions1.expected
~~[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/745/)~~
[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/754/)
=> C#: Remove throw completion from StringLiteral

csharp/ql/src/semmle/code/csharp/controlflow/internal/ControlFlowGraphImpl.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/EnclosingCallable.expected, csharp/ql/test/library-tests/controlflow/graph/EntryElement.expected, csharp/ql/test/library-tests/controlflow/graph/ExitElement.expected, csharp/ql/test/library-tests/controlflow/graph/Finally.cs, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, csharp/ql/test/library-tests/controlflow/graph/Nodes.expected
Fixes https://github.com/github/codeql/issues/4893
~~[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/744/)~~
[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/753/)
=> C#: Fix expanded assignment lookup in finally blocks for CFG

python/ql/src/semmle/python/frameworks/Flask.qll, python/ql/test/experimental/library-tests/frameworks/flask/old_test.py, python/ql/test/experimental/library-tests/frameworks/flask/routing_test.py
Draft since it depends on the changes from https://github.com/github/codeql/pull/4864
=> Python: Add modeling of Flask class based (HTTP) request handlers

docs/codeql/support/reusables/versions-compilers.rst, java/change-notes/2021-01-14-java-15-support.md
=> Java: update documentation on supported language versions

docs/codeql/README.rst
@shati-patel, I spotted this in passing and thought it could do with being updated.
=> Update reference to new CodeQL site

python/change-notes/2021-01-12-flask-class-based-view-handlers.md
For https://github.com/github/codeql/pull/4944
=> Python: Add change-note for Flask class based view handlers

csharp/ql/src/semmle/code/csharp/controlflow/internal/NonReturning.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/Condition.expected, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/EnclosingCallable.expected, csharp/ql/test/library-tests/controlflow/graph/EntryElement.expected, csharp/ql/test/library-tests/controlflow/graph/ExitElement.expected, csharp/ql/test/library-tests/controlflow/graph/ExitMethods.cs, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, csharp/ql/test/library-tests/controlflow/graph/Nodes.expected
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/803/
=> C#: Teach CFG about `ExceptionDispatchInfo::Throw`

javascript/upgrades/c8859f3725d4b070a877f8792214582d517c8a9b/toplevel_parent_xml_node.ql
Fixes a performance issue in the upgrade script from https://github.com/github/codeql/pull/4958, which previously took forever to upgrade a `rhino` database.
=> JS: Fix performance issue in upgrade script

cpp/ql/src/semmle/code/cpp/Comments.qll, cpp/ql/src/semmle/code/cpp/commons/Synchronization.qll
Follow-up to https://github.com/github/codeql/pull/5026 (as suggested by @geoffw0).
=> C++: Remove more linear scans

csharp/ql/src/semmle/code/csharp/dataflow/SSA.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/SsaImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/SsaImplCommon.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/SsaImplSpecific.qll, csharp/ql/test/library-tests/dataflow/local/DataFlowStep.expected, csharp/ql/test/library-tests/dataflow/local/LocalDataFlow.cs, csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/802/
=> C#: Adjust flow into phi nodes

cpp/ql/src/semmle/code/cpp/models/Models.qll, cpp/ql/src/semmle/code/cpp/models/implementations/Strset.qll, cpp/ql/src/semmle/code/cpp/models/implementations/Strtok.qll, cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/taint.cpp
Part of https://github.com/github/codeql-c-analysis-team/issues/220.
=> C++: Strset and strtok model implementations

cpp/ql/src/semmle/code/cpp/models/implementations/Pure.qll
Part of https://github.com/github/codeql-c-analysis-team/issues/220
=> C++: Model more pure functions

python/ql/src/semmle/python/frameworks/Django.qll, python/ql/test/experimental/library-tests/frameworks/django-v2-v3/routing_test.py
and a slightly concerning bugfix in `django_attr` :grimacing:
=> Python: Add full-path modeling of Django more view classes

csharp/ql/src/semmle/code/csharp/dataflow/SSA.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/SsaImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/SsaImplCommon.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/SsaImplSpecific.qll
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/823/
=> C#: Move uncertain-read logic into shared SSA implementation

cpp/ql/src/semmle/code/cpp/Element.qll, cpp/ql/src/semmle/code/cpp/Namespace.qll, cpp/ql/src/semmle/code/cpp/Preprocessor.qll, cpp/ql/src/semmle/code/cpp/Specifier.qll
I just found a whole branch of QLDoc improvements on my machine that never got PR'd.  This is from the 2019 push to add source code examples to the QLDoc for each QL class (which we never finished, though I believe we did get through 90% of the ones designated important).
=> C++: QLDoc Improvements

csharp/extractor/Semmle.Extraction.CIL/Entities/ConstructedType.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/Instruction.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/NamedTypeIdWriter.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/NoMetadataHandleType.FullyQualifiedNameParser.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/NoMetadataHandleType.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/SignatureDecoder.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/TypeDefinitionType.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/TypeReferenceType.cs, csharp/extractor/Semmle.Extraction.CIL/PDB/MetadataPdbReader.cs, csharp/extractor/Semmle.Extraction.CIL/PDB/Method.cs, csharp/extractor/Semmle.Extraction.CIL/PDB/NativePdbReader.cs, csharp/extractor/Semmle.Extraction.CIL/PDB/PdbReader.cs, csharp/extractor/Semmle.Extraction.CSharp.Driver/Driver.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/CommentLine.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/LocalFunction.cs, csharp/extractor/Semmle.Extraction.CSharp/Populators/DirectiveVisitor.cs, csharp/extractor/Semmle.Extraction/CommentProcessing.cs, csharp/extractor/Semmle.Extraction/Context.cs, csharp/extractor/Semmle.Extraction/Entities/Assembly.cs, csharp/extractor/Semmle.Extraction/Entities/ExtractionError.cs, csharp/extractor/Semmle.Extraction/Entities/SourceLocation.cs, csharp/extractor/Semmle.Extraction/Extractor.cs, csharp/extractor/Semmle.Extraction/Message.cs, csharp/extractor/Semmle.Util/Win32.cs
This PR fixes a couple of nullability build warnings. (There are still two left.) Additionally some minor code quality fixes have been applied.
=> C#: Fix nullable warnings and some code quality issues

javascript/ql/test/query-tests/Performance/ReDoS/tst.js
Adds the regular expressions from this FP report: #5145
=> JS: add two non ReDoS regular expressions to the ReDoS test suite

java/ql/test/experimental/query-tests/security/CWE-548/A.java, java/ql/test/experimental/query-tests/security/CWE-555/A.java
Presumably this is needed to have the test actually run.
=> Java: Add empty file to test.

javascript/change-notes/2021-02-16-vue-router.md, javascript/ql/src/semmle/javascript/dataflow/DataFlow.qll, javascript/ql/src/semmle/javascript/dataflow/Nodes.qll, javascript/ql/src/semmle/javascript/frameworks/Vue.qll, javascript/ql/test/library-tests/frameworks/Vue/compont-with-route.vue, javascript/ql/test/library-tests/frameworks/Vue/router.js, javascript/ql/test/library-tests/frameworks/Vue/tests.expected, javascript/ql/test/library-tests/frameworks/Vue/tests.ql
Evaluations: (internal links)
- [Security queries on 20 vue-router apps](https://github.com/dsp-testing/asgerf-bcqs/tree/auto/data/workflow/diagnostics-vue-router5/reports) looks fine
- Discovers [173 new taint sources](https://github.com/dsp-testing/asgerf-bcqs/blob/auto/data/workflow/diagnostics-vue-router5/reports/alert-comparison.md)
- Also reports a client-side log injection 🤦.  We'll need https://github.com/github/codeql/pull/5033 to fix it.
=> JS: Add flow sources from vue-router

javascript/ql/src/semmle/javascript/Expr.qll, javascript/ql/src/semmle/javascript/Stmt.qll, javascript/ql/src/semmle/javascript/security/dataflow/PrototypePollutionCustomizations.qll
=> JS: Fix 'is, is' and 'is is'.

java/ql/src/semmle/code/java/frameworks/Servlets.qll
cf https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html#addCookie(javax.servlet.http.Cookie)
=> Java: Correct signature and package in comment

python/change-notes/2021-02-24-port-flask-debug.md, python/ql/src/Security/CWE-215/FlaskDebug.ql, python/ql/test/query-tests/Security/CWE-215/FlaskDebug.expected, python/ql/test/query-tests/Security/CWE-215/settings.py, python/ql/test/query-tests/Security/CWE-215/test.py
I feel quite confident about this query change, so from my point of view, I'm happy to verify results after next dist-upgrade :blush:
=> Python: port py/flask-debug query

cpp/ql/src/Security/CWE/CWE-014/MemsetMayBeDeleted.ql
There seems to have been two performance problems with this query on one project. The first was this conjunct:
```codeql
// `v` is not only just used in the call to `memset`.
exists(Access acc |
acc = v.getAnAccess() and not call.getArgument(0).getAChild*() = acc and not acc.isUnevaluated()
) and
```
where we got a giant tuple explosion due to the transitive closure inside the negation that's being evaluated before we ever limit `call` to be a call to `Memset`:
```
Tuple counts for let0#antijoin_rhs#3/3@69573f:
129545890 ~5%     {3} r1 = JOIN let0#shared#2 WITH Variable::Variable::getAnAccess_dispred#ff ON FIRST 1 OUTPUT Rhs.1 'arg2', Lhs.0 'arg0', Lhs.1 'arg1'
2897      ~1%     {3} r2 = JOIN r1 WITH Expr::Expr::isUnevaluated_dispred#b ON FIRST 1 OUTPUT Lhs.0 'arg2', Lhs.1 'arg0', Lhs.2 …
```
=> C++: Fix performance in cpp/memset-may-be-deleted.

.github/workflows/docs-review.yml
@felicitymay this should fix the outgoing notifications.
=> Actions: Fix comment that tags the Docs team

java/ql/src/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/src/semmle/code/java/dataflow/FlowSources.qll, java/ql/test/library-tests/dataflow/taintsources/remote.expected
This PR converts some of the remote flow sources to CSV based ones.
~~[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/1195/)~~ [Differences job](https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/1211/)
=> Java: Convert remote flow sources to use new CSV format

python/change-notes/2021-02-23-port-bind-to-all-interfaces.md, python/ql/src/Security/CVE-2018-1281/BindToAllInterfaces.ql, python/ql/src/experimental/Security-old-dataflow/CVE-2018-1281/BindToAllInterfaces.ql, python/ql/test/query-tests/Security/CVE-2018-1281/BindToAllInterfaces.expected, python/ql/test/query-tests/Security/CVE-2018-1281/BindToAllInterfaces_test.py
Draft PR while validating whether the ported query can find all the interesting results.
=> Python: Port py/bind-socket-all-network-interfaces query

javascript/ql/src/semmle/javascript/heuristics/AdditionalSources.qll, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/xmlRequest.js
Makes `XssWithAdditionalSources.ql` get a TP for CVE-2020-26249
=> JS: don't filter away templated URLs in RemoteServerResponse

csharp/ql/src/semmle/code/csharp/dataflow/internal/Steps.qll, csharp/ql/test/query-tests/Dead Code/DeadStoreOfLocal/DeadStoreOfLocal.cs, csharp/ql/test/query-tests/Dead Code/DeadStoreOfLocal/DeadStoreOfLocal.expected
Fixes https://github.com/github/codeql/issues/4652.
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/942/
=> C#: Take phi nodes into account in `Steps::getARead()`

.github/workflows/check-change-note.yml
=> Add name to check-change-note.yml workflow

docs/codeql/writing-codeql-queries/creating-path-queries.rst
Just two small things I noticed while reading over the docs
=> Docs: Small improvements to path queries docs

cpp/autobuilder/Semmle.Autobuild.Cpp/Semmle.Autobuild.Cpp.csproj, csharp/autobuilder/Semmle.Autobuild.CSharp/DotNetRule.cs, csharp/autobuilder/Semmle.Autobuild.CSharp/Semmle.Autobuild.CSharp.csproj, csharp/autobuilder/Semmle.Autobuild.Shared/Semmle.Autobuild.Shared.csproj, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Semmle.Extraction.CSharp.Standalone.csproj
~~[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/949/)~~ [Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/951/)
=> C#: Upgrade nuget packages

csharp/ql/src/semmle/code/csharp/Callable.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/async/Async.cs, csharp/ql/test/library-tests/dataflow/async/Async.expected, csharp/ql/test/library-tests/dataflow/async/Async.ql, csharp/ql/test/library-tests/dataflow/global/GetAnOutNode.expected
Fixes https://github.com/github/codeql/issues/5410.
~~[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/944/)~~ [Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/948/)
=> C#: add store step for return statements inside async methods

java/ql/src/meta/frameworks/Coverage.ql, java/ql/src/semmle/code/java/dataflow/ExternalFlow.qll
A couple of questions: Is the path where I put the query reasonable? And is its `@kind` and `@id` appropriate?
=> Java: Add query for CSV framework coverage.

javascript/ql/src/semmle/javascript/dataflow/TaintTracking.qll, javascript/ql/src/semmle/javascript/frameworks/AngularJS/ServiceDefinitions.qll
While evaluating my some of my recent PRs I looked into the benchmarks that performed badly.  
So I looked into it, and found a few issues... and those issues had nothing to do with the code in the PRs :shrug: 
[Evaluation shows a decent improvement](https://github.com/dsp-testing/erik-krogh-dca/tree/run/joins-default-security/reports).
=> JS: Two join-order improvements

docs/codeql/codeql-language-guides/using-api-graphs-in-python.rst
Addresses https://github.com/github/codeql-python-team/issues/341
=> Python, doc: Note ephemeral nature of import nodes

csharp/config/suites/lgtm/csharp-metrics-lgtm, csharp/ql/src/codeql-suites/exclude-dependency-queries.yml
Follow-up on https://github.com/github/codeql/pull/5524.
=> C#: Remove deleted queries from suites

docs/codeql/codeql-cli/creating-codeql-databases.rst, docs/codeql/codeql-cli/testing-query-help-files.rst
This PR fixes two broken links.
=> Fix broken links

cpp/ql/test/query-tests/jsf/4.10 Classes/AV Rule 79/AV Rule 79.expected, cpp/ql/test/query-tests/jsf/4.10 Classes/AV Rule 79/Variants.cpp
For https://github.com/github/codeql-c-analysis-team/issues/258.
=> C++: Test strdup with AV rule 79

docs/codeql/codeql-for-visual-studio-code/analyzing-your-projects.rst
Update the docs to indicate that you can specify a project slug downloading a database from LGTM
=> download LGTM database from a project slug

javascript/ql/examples/queries/dataflow/BackendIdor/BackendIdor.ql, javascript/ql/examples/queries/dataflow/DecodingAfterSanitization/DecodingAfterSanitization.ql, javascript/ql/examples/queries/dataflow/DecodingAfterSanitization/DecodingAfterSanitizationGeneralized.ql, javascript/ql/examples/queries/dataflow/EvalTaint/EvalTaintPath.ql, javascript/ql/examples/queries/dataflow/InformationDisclosure/InformationDisclosure.ql, javascript/ql/examples/queries/dataflow/StoredXss/StoredXss.ql, javascript/ql/examples/queries/dataflow/StoredXss/StoredXssTypeTracking.ql, javascript/ql/examples/queries/dataflow/TemplateInjection/TemplateInjection.ql
Hopefully last round of buggy metadata updates.
=> JS: Update more query metadata

python/ql/src/semmle/python/frameworks/Django.qll
I was super confused when reading those myself, so wrote up a more descriptive version :smile:
=> Python: Better text for getSourceType in Django

csharp/ql/src/semmle/code/cil/internal/SsaImplCommon.qll, csharp/ql/src/semmle/code/csharp/controlflow/internal/pressa/SsaImplCommon.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/SsaImplCommon.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/basessa/SsaImplCommon.qll
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/970
=> C#: Performance tweaks in `SsaImplCommon.qll`

csharp/ql/src/codeql-suites/csharp-code-scanning.qls, csharp/ql/src/codeql-suites/csharp-security-and-quality.qls, csharp/ql/src/codeql-suites/csharp-security-extended.qls
Follow-up on https://github.com/github/codeql/pull/5542.
=> C#: Remove mentions of `exclude-dependency-queries.yml`

docs/codeql/codeql-for-visual-studio-code/customizing-settings.rst
Adds a section to "[Customizing settings](https://codeql.github.com/docs/codeql-for-visual-studio-code/customizing-settings/)" about telemetry + a link to more detail in "[About telemetry](https://codeql.github.com/docs/codeql-for-visual-studio-code/about-telemetry-in-codeql-for-visual-studio-code/)."
=> Docs: Mention telemetry in "customizing settings"

csharp/change-notes/2021-04-09-dapper-support.md, csharp/ql/src/semmle/code/csharp/frameworks/Dapper.qll, csharp/ql/src/semmle/code/csharp/frameworks/Sql.qll, csharp/ql/test/query-tests/Security Features/CWE-089/SqlInjection.cs, csharp/ql/test/query-tests/Security Features/CWE-089/SqlInjection.expected, csharp/ql/test/query-tests/Security Features/CWE-089/SqlInjectionDapper.cs, csharp/ql/test/resources/stubs/Dapper.cs
[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/985/)
=> C#: Dapper support

csharp/ql/src/semmle/code/csharp/dispatch/Dispatch.qll
[Removing the trap stack](https://github.com/github/codeql/pull/5577) amplified bad performance of `Dispatch::SimpleTypeDataFlow::getASourceType()`.  The underlying problem is an ad-hoc data-flow loop where flow is tracked through fields and properties from _all assignments_ to _all reads_, which may result in a tuple explosion. The solution is to break up the data-flow loop, to avoid the combinatorial explosion.
<details>
<summary>Before</summary>
```
[2021-04-08 11:50:23] (552s) Clause timing report:
[2021-04-08 11:50:23] (552s) 
[2021-04-08 11:50:23] 
viableCallable.ql-25:Dispatch::Internal::SimpleTypeDataFlow::Sink::getASource_dispred#ff .......................................................................................................... 20.9s …
```
=> C#: Improve performance of `Dispatch::SimpleTypeDataFlow::getASourceType()`

cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, docs/ql-libraries/dataflow/dataflow.md, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImpl4.qll
Needed for https://github.com/github/codeql/pull/5629.
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/993/
https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1898/
https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/1300/ (exluding `google/guava` which failed to build)
https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/501/
=> Data flow: Prevent bad join-order in `pathStep`

python/change-notes/2021-03-22-django-queryset-chains.md, python/ql/src/semmle/python/frameworks/Django.qll, python/ql/test/library-tests/frameworks/django/SqlExecution.py
co-authored by @yoff (in pair programming)
=> Python: Model QuerySet chains in Django

python/ql/src/semmle/python/frameworks/Dill.qll
If only all rewrites were this smooth...
---
No change note required. Behaviour should be the same.
=> Python: Use API graphs in Dill model

csharp/ql/src/semmle/code/csharp/dataflow/internal/SsaImpl.qll
<details>
<summary>Before (`dotnet/efcore`)</summary>
```
[2021-04-13 16:00:45] (531s) Clause timing report:
[2021-04-13 16:00:45] (531s) 
[2021-04-13 16:00:45] 
SsaDef.ql-26:SsaImpl::CallGraph::SimpleDelegateAnalysis::delegateCallSource#ff#reorder_1_0 . 1m43s (67 evaluations with max 16.8s in SsaImpl::CallGraph::SimpleDelegateAnalysis::delegateCallSource#ff#reorder_1_0/2@i18#d4acbx)
SsaDef.ql-26:SsaImpl::CallGraph::SimpleDelegateAnalysis::delegateFlowStep#ff#reorder_1_0 ... 1.9s (27 evaluations with max 1.6s in SsaImpl::CallGraph::SimpleDelegateAnalysis::delegateFlowStep#ff#reorder_1_0/2@i1#d4acb0)
SsaDef.ql-26:cil_instruction_1023#join_rhs ................................................. 1.1s
SsaDef.ql-26:cil_instruction_103#join_rhs .................................................. …
```
=> C#: Improve performance of `SsaImpl::CallGraph::SimpleDelegateAnalysis`

csharp/ql/src/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowUtil.qll, java/ql/src/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
Followup for a couple of comments on https://github.com/github/codeql/pull/5456.
=> Java/C#: Move a couple of flow summary tweaks to the shared implementation.

csharp/change-notes/2021-04-22-console-read-local-source.md, csharp/ql/src/semmle/code/csharp/security/dataflow/flowsources/Local.qll, csharp/ql/test/query-tests/Security Features/CWE-134/ConsoleUncontrolledFormatString.cs, csharp/ql/test/query-tests/Security Features/CWE-134/UncontrolledFormatString.expected
[Diff job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/997/)
=> C#: Add Console.Read* to local flow sources

docs/codeql/ql-language-reference/ql-language-specification.rst
This adjusts the spec to cover the changes we are planning to make. 
This is mostly a lifting of restrictions on super.
=> Docs: Update the language specification for changes to super.

cpp/ql/src/experimental/Security/CWE/CWE-570/WrongInDetectingAndHandlingMemoryAllocationErrors.cpp, cpp/ql/src/experimental/Security/CWE/CWE-570/WrongInDetectingAndHandlingMemoryAllocationErrors.qhelp, cpp/ql/src/experimental/Security/CWE/CWE-570/WrongInDetectingAndHandlingMemoryAllocationErrors.ql, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-570/semmle/tests/WrongInDetectingAndHandlingMemoryAllocationErrors.expected, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-570/semmle/tests/test.cpp
This PR handles the qhelp and testing parts of https://github.com/github/codeql-c-analysis-team/issues/228. I'll improve the QL code in a separate PR.
=> C++: Improve qhelp and tests for cpp/detect-and-handle-memory-allocation-errors

docs/codeql/support/reusables/frameworks.rst
According to @asgerf, React Native is already supported 🎉
=> Add React Native to JavaScript frameworks docs

java/ql/src/experimental/Security/CWE/CWE-601/SpringUrlRedirect.java, java/ql/src/experimental/Security/CWE/CWE-601/SpringUrlRedirect.qhelp, java/ql/src/experimental/Security/CWE/CWE-601/SpringUrlRedirect.ql, java/ql/src/experimental/Security/CWE/CWE-601/SpringUrlRedirect.qll, java/ql/test/experimental/query-tests/security/CWE-601/SpringUrlRedirect.expected, java/ql/test/experimental/query-tests/security/CWE-601/SpringUrlRedirect.java, java/ql/test/experimental/query-tests/security/CWE-601/SpringUrlRedirect.qlref, java/ql/test/experimental/query-tests/security/CWE-601/options, java/ql/test/stubs/springframework-5.2.3/org/springframework/web/servlet/ModelAndView.java, java/ql/test/stubs/springframework-5.2.3/org/springframework/web/servlet/View.java, java/ql/test/stubs/springframework-5.2.3/org/springframework/web/servlet/view/AbstractUrlBasedView.java, java/ql/test/stubs/springframework-5.2.3/org/springframework/web/servlet/view/RedirectView.java
The Sping framework implements the redirection function, and the commonly used methods are:
- String mapping RequestMapping to achieve redirection
- ModelAndView object
- RedirectView object
When the program merges the user input directly into the URL redirect request without verification, can carry out phishing attacks on users.
=> [Java] CWE-601 Spring url redirection detect

javascript/ql/src/semmle/javascript/security/dataflow/CodeInjectionCustomizations.qll
Recognizes the sink for CVE-2020-28470
[A run across a bunch of LGTM projects](https://lgtm.com/query/4346257153245005433/) reveals more sinks than I had expected. 
Evaluation will come later.
=> JS: add writes to textContent on a <script /> as a sink for code-injection

cpp/ql/src/semmle/code/cpp/stmts/Stmt.qll
(Fixes https://github.com/github/codeql-c-team/issues/373.)
This PR improved the performance of `SwitchCase.getAStmt` by removing the large antijoin in the predicate.
Given this query:
```codeql
import cpp
from SwitchCase case, Stmt stmt
where stmt = case.getAStmt()
select case, stmt
```
We get the following tuple counts on `alibaba/AliSQL` when running this query on main (I stopped it during evaluation):
```
Tuple counts for Stmt::SwitchCase::getAStmt#ff#antijoin_rhs#1/5@3afd70:
214389     ~1%          {5} r1 = JOIN Stmt::SwitchCase::getAStmt#ff#shared WITH Block::BlockStmt::getStmt_dispred#fff ON FIRST 1 OUTPUT Lhs.0 'arg1', Lhs.1 'arg0', Lhs.2 'arg2', Rhs.1 'arg3', Rhs.2 'arg4'
1431556191 ~5%          {7} r2 = JOIN r1 WITH Block::BlockStmt::getStmt_dispred#fff ON FIRST 1 OUTPUT Lhs.1 …
```
=> C++: Remove large antijoin in `SwitchCase.getAStmt`

.github/workflows/check-change-note.yml
This change is intended to fix the error in https://github.com/github/codeql/pull/5664/checks?check_run_id=2716444058
=> Fix change note workflow to handle paginated results

javascript/change-notes/2021-06-02-debug.md, javascript/ql/src/semmle/javascript/frameworks/Logging.qll, javascript/ql/test/query-tests/Security/CWE-312/CleartextLogging.expected, javascript/ql/test/query-tests/Security/CWE-312/passwords.js
[Evaluation looks fine](https://github.com/dsp-testing/erik-krogh-dca/tree/run/lib-debug-default-CustomSuite/reports).
=> JS: add support for the debug library

javascript/change-notes/2021-06-04-whatwg-fetch.md, javascript/ql/src/semmle/javascript/frameworks/ClientRequests.qll, javascript/ql/test/library-tests/frameworks/ClientRequests/ClientRequests.expected, javascript/ql/test/library-tests/frameworks/ClientRequests/tst.js
[Evaluation looks fine](https://github.com/dsp-testing/erik-krogh-dca/tree/run/whatwg-fetch-nightly-security-extended/reports).
=> JS: add model for whatwg-fetch

cpp/ql/test/library-tests/variables/getanassignedvalue/test.cpp
Follow up for https://github.com/github/codeql/pull/6027
=> C++: Remove outdated comment

javascript/change-notes/2021-06-07-serverless.md, javascript/ql/src/semmle/javascript/frameworks/ServerLess.qll, javascript/ql/test/library-tests/frameworks/ServerLess/test.expected, javascript/ql/test/library-tests/frameworks/ServerLess/tst6/handler.js, javascript/ql/test/library-tests/frameworks/ServerLess/tst6/serverless.yml, javascript/ql/test/library-tests/frameworks/ServerLess/tst7/handler.js, javascript/ql/test/library-tests/frameworks/ServerLess/tst7/serverless.yml
[Evaluation looks fine](https://github.com/dsp-testing/erik-krogh-dca/tree/run/serverlessLib-nightly-security-extended/reports).
=> JS: Add remote flow source for the `serverless` library

javascript/ql/src/semmle/javascript/security/dataflow/Xss.qll
See https://github.com/github/codeql/pull/6024#pullrequestreview-678294776
=> JS: fix typo in `SerializeJavascriptSanitizer` qldoc

javascript/change-notes/2021-06-14-script-with-tsx-lang.md, javascript/extractor/src/com/semmle/js/extractor/HTMLExtractor.java, javascript/extractor/src/com/semmle/js/extractor/Main.java, javascript/ql/test/library-tests/TypeScript/EmbeddedInScript/Test.expected, javascript/ql/test/library-tests/TypeScript/EmbeddedInScript/other.ts, javascript/ql/test/library-tests/TypeScript/EmbeddedInScript/test_tsx.vue
Fixes https://github.com/github/codeql/issues/6066
=> JS: Support script tags with lang='tsx'

python/ql/src/semmle/python/dataflow/new/internal/TypeTracker.qll
This removes 2 stages for Ruby, resulting in slightly improved performance.
=> Python: Move cached predicates in type tracker library to same stage

java/ql/test/query-tests/security/CWE-311/CWE-319/HttpsUrls.expected, java/ql/test/query-tests/security/CWE-311/CWE-319/HttpsUrls.qlref, java/ql/test/query-tests/security/CWE-311/CWE-319/HttpsUrlsTest.java, java/ql/test/query-tests/security/CWE-311/CWE-319/UseSSL.expected, java/ql/test/query-tests/security/CWE-311/CWE-319/UseSSLTest.java
See corresponding internal PR.
=> Java: Move/tweak some tests

javascript/ql/src/Performance/PolynomialReDoS.ql, javascript/ql/src/Performance/ReDoS.ql
[CWE-1333](https://cwe.mitre.org/data/definitions/1333.html) sounds like a perfect fit. 
Inspired by Nicks comment here: https://github.com/github/codeql/pull/6038#issuecomment-864909171
=> JS: add CWE-1333 to the JS ReDoS queries

javascript/change-notes/2021-06-22-chokidar.md, javascript/ql/src/semmle/javascript/frameworks/Files.qll, javascript/ql/test/library-tests/frameworks/Concepts/tests.expected, javascript/ql/test/library-tests/frameworks/Concepts/tst-file-names.js
[Evaluation looks fine](https://github.com/dsp-testing/erik-krogh-dca/tree/run/chokidar-nightly-security-extended/reports).
=> JS: add support for the `chokidar` library

java/change-notes/2021-06-23-generic-type-names.md, java/ql/src/semmle/code/java/Generics.qll, java/ql/src/semmle/code/java/dataflow/internal/ContainerFlow.qll, java/ql/src/semmle/code/java/frameworks/play/Play.qll, java/ql/test/library-tests/dataflow/collections/B.java, java/ql/test/library-tests/dependency-counts/PrintAst.expected, java/ql/test/library-tests/dependency/PrintAst.expected, java/ql/test/library-tests/frameworks/play/PlayBodyParserAnnotation.expected, java/ql/test/library-tests/generics/PrintAst.expected, java/ql/test/library-tests/typeaccesses/PrintAst.expected
Requires https://github.com/github/semmle-code/pull/39553
=> Adapt to static methods and nested types returning unbound declaring types

misc/scripts/library-coverage/comment-pr.py
This commit handles the case when the current run finds no coverage change and the previous run is identified,
but it doesn't have the required artifacts.
This case impacts PRs that were opened before the new workflow implementation was merged and since the merge new commits have been pushed to them. Subsequent commits to the PRs would not trigger this issue.
This bug was reported in https://github.com/github/codeql/pull/6149#issuecomment-867408080.
=> Fix framework coverage commenting action

java/ql/src/semmle/code/java/security/RequestForgery.qll
This fixes a case of very bad magic causing a quadratic slowdown in `RequestForgery.ql`.
=> Java: Fix bad magic.

javascript/change-notes/2021-07-12-case.md, javascript/ql/src/semmle/javascript/frameworks/StringFormatters.qll, javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/library-tests/TaintTracking/case.js
[Evaluation was uneventful](https://github.com/dsp-testing/erik-krogh-dca/tree/run/case-eval/reports).
=> JS: Add support for many case changing libraries

javascript/change-notes/2021-07-12-more-precise-capture-steps.md, javascript/ql/src/semmle/javascript/dataflow/Configuration.qll, javascript/ql/src/semmle/javascript/dataflow/internal/FlowSteps.qll, javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/library-tests/TaintTracking/DataFlowTracking.expected, javascript/ql/test/library-tests/TaintTracking/capture-flow.js
The handling of data flow through captured variables was incorrect, leading to both missed flow and spurious flow (see backlinked issue).
[Evaluation](https://github.com/dsp-testing/asgerf-dca/issues/165) (internal link) fixes a few FPs and gains a TP (data flow). Performance seems acceptable considering this is a bug fix.
=> JS: more precise capture steps

cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowDispatch.qll
I've been wanting to try this out for some time, and now https://github.com/github/codeql-c-team/issues/552 gave me a perfect excuse to try it out!
I imagine this will cause some performance regression, so I'm opening this PR to try it out on Jenkins.
CPP-Differences: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/2119/
=> C++: Resolve function pointer calls using call contexts

csharp/ql/src/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll, java/ql/src/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1196/
https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/1506/
=> Data flow: Use cached predicates from DataFlowImplCommon in `FlowSummaryImpl.qll`

javascript/change-notes/2021-07-12-read-pkg.md, javascript/ql/src/semmle/javascript/security/dataflow/TaintedPathCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/other-fs-libraries.js
[Evaluation was uneventful](https://github.com/dsp-testing/erik-krogh-dca/tree/run/read-pkg__nightly__CustomSuite/reports).
=> JS: add the `cwd` option from `read-pkg` as sink for `path-injection`

docs/codeql/support/reusables/frameworks.rst, python/ql/src/semmle/python/frameworks/MySQLdb.qll
Just for completeness in terms of what we claim support for.
=> Python: Mention modeling of `mysqlclient` PyPI package

cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll, cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, cpp/ql/src/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowImplCommon.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/src/semmle/code/java/dataflow/internal/DataFlowImplCommon.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, python/ql/src/semmle/python/dataflow/new/internal/DataFlowImplCommon.qll
The first commit just moves some code around. The second commit contains the actual change.
=> Dataflow: Refactor call context check

python/ql/src/semmle/python/dataflow/new/SensitiveDataSources.qll, python/ql/src/semmle/python/frameworks/Stdlib.qll
See commit messages for more information. 
Needs performance evaluation (obviously).
Does not need a change note.
=> Python: Fix a few performance issues.

javascript/change-notes/2021-07-15-ansi-to-html.md, javascript/ql/src/semmle/javascript/frameworks/Logging.qll, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tst.js
[Evaluation was uneventful](https://github.com/dsp-testing/erik-krogh-dca/tree/run/ansi-to-html__nightly__CustomSuite/reports).
=> JS: add a taint step through the `ansi-to-html` library

javascript/change-notes/2021-07-15-sort-keys.md, javascript/ql/src/semmle/javascript/Extend.qll, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.expected, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXssWithCustomSanitizer.expected, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/tst2.js
[Evaluation looks fine](https://github.com/dsp-testing/erik-krogh-dca/tree/run/sort-keys__nightly__CustomSuite__1/reports).
=> JS: add sort-keys as a clone call

javascript/change-notes/2021-07-14-react-tooltip.md, javascript/ql/src/semmle/javascript/security/dataflow/Xss.qll, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tooltip.jsx
[Evaluation was uneventful](https://github.com/dsp-testing/erik-krogh-dca/tree/run/react-tooltip__nightly__CustomSuite/reports).
=> JS: add xss sink for `react-tooltip`

javascript/change-notes/2021-07-14-mkdirp.md, javascript/ql/src/semmle/javascript/frameworks/Files.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/other-fs-libraries.js
[Evaluation was uneventful](https://github.com/dsp-testing/erik-krogh-dca/tree/run/mkdirp__default__CustomSuite/reports).
=> JS: add mkdirp as a sink for tainted-path

javascript/change-notes/2021-07-14-querystring.md, javascript/ql/src/semmle/javascript/frameworks/UriLibraries.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.js
[Evaluation was uneventful](https://github.com/dsp-testing/erik-krogh-dca/tree/run/qs__nightly__security-extended/reports).
=> JS: Add taint steps through some URI libraries

misc/suite-helpers/security-and-quality-selectors.yml, misc/suite-helpers/security-extended-selectors.yml
=> Code Scanning selectors: Include diagnostic and summary metric queries

java/ql/src/experimental/Security/CWE/CWE-601/SpringUrlRedirect.java, java/ql/src/experimental/Security/CWE/CWE-601/SpringUrlRedirect.qhelp, java/ql/src/experimental/Security/CWE/CWE-601/SpringUrlRedirect.ql, java/ql/src/experimental/Security/CWE/CWE-601/SpringUrlRedirect.qll, java/ql/test/experimental/query-tests/security/CWE-601/SpringUrlRedirect.expected, java/ql/test/experimental/query-tests/security/CWE-601/SpringUrlRedirect.java
Add Open URL Redirect attack sinks by the `ResponseEntity` class in the Spring Framework.
=> [Java] CWE-601: Add Spring URL Redirect ResponseEntity sink

docs/codeql/support/reusables/frameworks.rst
Updating manually maintained list with coverage in `JacksonSerializability.qll`
=> Java: update `frameworks.rst` with Jackson

cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/localFlow.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp, cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected
Fixes https://github.com/github/codeql-c-team/issues/535. [CPP-Differences](https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/2181/) looks fine.
=> C++: Fix missing local flow in AST dataflow

csharp/ql/src/semmle/code/csharp/dataflow/ExternalFlow.qll, csharp/ql/test/library-tests/dataflow/external-models/Steps.cs, csharp/ql/test/library-tests/dataflow/external-models/steps.expected, csharp/ql/test/library-tests/dataflow/external-models/steps.ql
C# version of https://github.com/github/codeql/pull/6215.
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1229/
=> C#: Fix CSV overrides logic

javascript/ql/src/semmle/javascript/DOM.qll, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/XssThroughDom.expected, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/xss-through-dom.js
Recognizes some more sinks for CVE-2019-20921
[Performance evaluation looks good](https://github.com/dsp-testing/erik-krogh-dca/tree/run/pr-6487-cc2a267__nightly__CustomSuite/reports).  
One new result, which looks like a TP.
=> JS: recognize array elements from JQuery objects as DOM values

cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/test_buffer_overrun.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-119/semmle/tests/tests.cpp
Adds more test cases for buffer overruns.
=> More buffer overrun tests

javascript/ql/src/semmle/javascript/NodeModuleResolutionImpl.qll, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialBackTracking.expected, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialReDoS.expected, javascript/ql/test/query-tests/Performance/ReDoS/lib/otherLib/js/src/index.js, javascript/ql/test/query-tests/Performance/ReDoS/lib/otherLib/package.json
Recognizes the source for CVE-2021-23414
[Evaluation looks clean](https://github.com/dsp-testing/erik-krogh-dca/tree/run/pr-6534-5d232bb__default__CustomSuite/reports).
=> JS: recognize more src folders when "main" in package.json points to a compiled output
