csharp/ql/src/Security Features/CWE-327/InsecureSQLConnection.ql, csharp/ql/test/query-tests/Security Features/CWE-327/InsecureSQLConnection/InsecureSQLConnection.cs, csharp/ql/test/query-tests/Security Features/CWE-327/InsecureSQLConnection/InsecureSQLConnection.expected, csharp/ql/test/query-tests/Security Features/CWE-327/InsecureSQLConnection/InsecureSQLConnection.qlref
This change makes the query a bit less noisy (but still quite noisy).
=> C#: Use data flow instead of taint tracking in `InsecureSQLConnection.ql`

javascript/ql/src/experimental/Security/CWE-079/ClipboardXss.qhelp, javascript/ql/src/experimental/Security/CWE-079/ClipboardXss.ql, javascript/ql/src/experimental/Security/CWE-079/examples/clipboard-xss-sample.js
This query looks for potential DomBasedXSS vulnerabilities whose source is the clipboard API. This source is not currently covered by the official XSS queries.
=> Experimental query: ClipboardBasedXss

java/ql/lib/semmle/code/java/frameworks/guava/Base.qll, java/ql/lib/semmle/code/java/frameworks/guava/IO.qll, java/ql/test/library-tests/frameworks/guava/TestBase.java, java/ql/test/library-tests/frameworks/guava/TestIO.java
Also add tests for the affected functions
=> Fix minor mistakes in old Guava models

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll
Minor follow-up for https://github.com/github/codeql/pull/5032
=> Dataflow: Only calculate fastTC for the relevant part of edges.

docs/codeql/codeql-cli/about-ql-packs.rst
This is a first pass to fix obvious holes and outdated information, but
we should rethink these docs completely.
=> Update the docs about qlpacks

python/ql/lib/semmle/python/frameworks/SqlAlchemy.qll, python/ql/test/library-tests/frameworks/sqlalchemy/new_tests.py
=> Python: Minor sqlalchemy comment fixes

docs/codeql/ql-language-reference/ql-language-specification.rst
Thanks to https://github.com/github/codeql/issues/6750
=> Fix typo in language spec

java/ql/lib/semmle/code/java/Expr.qll
Fixes https://github.com/github/codeql/issues/6619
=> Java: Add StringLiteral.isTextBlock().

docs/codeql/support/ql-training.rst
These changes appear to work for the staging and live sites.
=> Update links to match those on the staging site

javascript/ql/lib/semmle/javascript/security/CryptoAlgorithms.qll, python/ql/lib/semmle/python/concepts/CryptoAlgorithms.qll, python/ql/test/library-tests/frameworks/crypto/test_sha3.py, python/ql/test/library-tests/frameworks/cryptodome/test_sha3.py
Official names are SHA3-224, SHA3-256, SHA3-384, SHA3-512 as per https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf
=> Python/JS: Recognize SHA-3 hash functions

cpp/ql/src/Security/CWE/CWE-570/IncorrectAllocationErrorHandling.ql
Fixes https://github.com/github/codeql/issues/6805.
=> C++: Add more CWEs to 'cpp/incorrect-allocation-error-handling'.

javascript/ql/src/Declarations/MixedStaticInstanceThisAccess.ql, javascript/ql/test/query-tests/Declarations/MixedStaticInstanceThisAccess/MixedStaticInstanceThisAccess.expected, javascript/ql/test/query-tests/Declarations/MixedStaticInstanceThisAccess/abstract.ts
Fixes https://github.com/github/codeql/issues/6853
=> JS: Fix FP in mixed-this static access

ruby/ql/src/queries/security/cwe-732/WeakFilePermissions.ql
This is a minor PR. Sorry for such a minute change,.
=> Fixed a typo. ( Minor PR)

java/change-notes/2021-10-29-optional-lambda-flow.md, java/ql/lib/semmle/code/java/frameworks/Optional.qll, java/ql/test/library-tests/optional/FunctionalTest.java
Adds support for the various lambda-accepting methods on `java.util.Optional`
=> Java: Model java.util.Optional lambda methods

javascript/ql/src/Security/CWE-614/ClearTextCookie.ql
[CWE-319: Cleartext Transmission of Sensitive Information](https://cwe.mitre.org/data/definitions/319.html).
=> JS: add cwe-319 to js/clear-text-cookie

csharp/ql/lib/semmle/code/cil/internal/SsaImplCommon.qll, csharp/ql/lib/semmle/code/csharp/controlflow/internal/pressa/SsaImplCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImplCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/basessa/SsaImplCommon.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImplCommon.qll
See @aschackmull 's coment on https://github.com/github/codeql/pull/6961.
=> Shared SSA: Improved dominance frontier calculation

docs/codeql/support/reusables/frameworks.rst
This PR adds the newly supported JavaScript and Java libraries/frameworks to the documentation.
=> Add updated framework support for JS/Java

python/ql/lib/semmle/python/dataflow/new/internal/TaintTrackingPrivate.qll, python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/test_async.py, python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/test_for.py, python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/test_syntax.py, python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/test_with.py, python/ql/test/experimental/meta/InlineTaintTest.qll, python/ql/test/experimental/meta/debug/InlineTaintTestPaths.expected, python/ql/test/experimental/meta/debug/InlineTaintTestPaths.ql
Fixes a small issue discovered while modeling `asyncpg`..
=> Python: Taint through `async with`

cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected, cpp/ql/test/library-tests/dataflow/taint-tests/map.cpp
The first commit fixes a bug found by @geoffw0 [here](https://github.com/github/codeql/pull/6825#discussion_r741732743), and the second commit fixes a similar bug in another test function.
=> C++: Fix a testcase

python/ql/lib/semmle/python/essa/Definitions.qll, python/ql/lib/semmle/python/pointsto/PointsTo.qll, python/ql/src/Statements/RedundantAssignment.ql
See the commit messages for more information. 
Does not need a change note.
Evaluation in progress.
=> Python: Fix a bunch of performance issues

javascript/ql/lib/semmle/javascript/frameworks/ClientRequests.qll, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/xmlRequest.js
One step closer towards flagging CVE-2021-21278
[Smoke test](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-7139-1a31ef2__smoke-test__smoke-test/reports) looks OK.
=> JS: improve the got model

docs/codeql/codeql-cli/getting-started-with-the-codeql-cli.rst
Tiny docs change for the Apple Silicon public beta.
=> Add requirements for Apple Silicon

csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImplShared.qll, csharp/ql/test/library-tests/controlflow/splits/CONSISTENCY/CfgConsistency.expected, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplShared.qll
The C# inconsistencies should be fixed later.
=> Shared CFG: Add "dead end" consistency query

csharp/ql/consistency-queries/SsaConsistency.ql, csharp/ql/lib/semmle/code/csharp/ExprOrStmtParent.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/Condition.expected, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/EnclosingCallable.expected, csharp/ql/test/library-tests/controlflow/graph/EntryElement.expected, csharp/ql/test/library-tests/controlflow/graph/ExitElement.expected, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, csharp/ql/test/library-tests/controlflow/graph/Nodes.expected, csharp/ql/test/library-tests/controlflow/graph/cflow.cs
Enables the shared SSA consistency queries and fixes two inconsistencies.
=> C#: Enable SSA consistency queries

java/ql/lib/semmle/code/java/security/XmlParsers.qll, java/ql/test/query-tests/security/CWE-611/DocumentBuilderTests.java, java/ql/test/query-tests/security/CWE-611/XXE.expected
Per seclab's request discussing https://github.com/github/codeql/issues/7199
=> Note that FEATURE_SECURE_PROCESSING isn't a sufficient defence against XXE

.codeqlmanifest.json
Handles the post release process.
=> Add a version policy

python/change-notes/2021-11-24-FastAPI-Custom-APIRouter-Subclass.md, python/change-notes/2021-11-24-FastAPI-FileResponse-FileSystemAccess copy.md, python/ql/lib/semmle/python/frameworks/FastApi.qll, python/ql/test/library-tests/frameworks/fastapi/response_test.py, python/ql/test/library-tests/frameworks/fastapi/router.py
With these changes, we are now able to flag CVE-2021-43775
=> Python: FastAPI improvements

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
=> Fix QL Doc typo.

csharp/ql/lib/semmle/code/csharp/dataflow/LibraryTypeDataFlow.qll, csharp/ql/lib/semmle/code/csharp/frameworks/System.qll, csharp/ql/test/library-tests/dataflow/library/FlowSummaries.expected, csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected
In this PR we cover the conversion of flow summaries for
- System.Boolean.
- System.Uri.
=> C#: Convert some of the existing flow summaries to CSV

javascript/ql/src/Security/CWE-327/BrokenCryptoAlgorithm.ql
CWE-328: Use of Weak Hash, see https://cwe.mitre.org/data/definitions/328.html
=> JS: Tag queries with CWE-328

ruby/ql/lib/codeql/ruby/ast/Method.qll
Extracted from https://github.com/github/codeql/pull/7198.
=> Ruby: Tweak `Method::isPrivate` join-orders

ruby/ql/test/TestUtilities/InlineFlowTest.qll
Ported from Java and C#.
Extracted from https://github.com/github/codeql/pull/7198.
=> Ruby: Add `InlineFlowTest.qll`

python/ql/test/2/query-tests/Imports/syntax_error/SyntaxError.expected, python/ql/test/3/library-tests/with/test.expected, python/ql/test/3/library-tests/with/test.py, python/ql/test/3/library-tests/with/test.ql, python/ql/test/3/query-tests/Imports/syntax_error/SyntaxError.expected, python/ql/test/query-tests/Diagnostics/ExtractionWarnings.expected
External part of an internal PR. Language tests will fail on this one.
=> Python: Fix syntax error locations

javascript/ql/lib/semmle/javascript/security/performance/PolynomialReDoS.qll, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialBackTracking.expected, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialReDoS.expected, javascript/ql/test/query-tests/Performance/ReDoS/lib/lib.js
[Evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-7284-30466df__nightly__CustomSuite__2/reports).
=> JS: remove paths without unmatched returns from polynomial-redos

ruby/change-notes/2021-12-07-customizations.md, ruby/ql/lib/Customizations.qll, ruby/ql/lib/ruby.qll
Allows for global customizations to things like remote flow sources - we have this mechanism in other languages already (JS, Python, C#, Java).
=> Ruby: add `Customizations.qll` file

csharp/ql/lib/semmle/code/csharp/controlflow/ControlFlowGraph.qll, csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImplShared.qll, csharp/ql/lib/semmle/code/csharp/controlflow/internal/Splitting.qll, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, ruby/ql/lib/codeql/ruby/controlflow/BasicBlocks.qll, ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll, ruby/ql/lib/codeql/ruby/controlflow/ControlFlowGraph.qll, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplShared.qll
Enables the fix of an inconsistency for C# identified via https://github.com/github/codeql/pull/7231.
=> Shared CFG: Include CFG scope in `TElementNode`

cpp/ql/lib/qlpack.yml, csharp/ql/lib/qlpack.yml, java/ql/lib/qlpack.yml, javascript/ql/lib/qlpack.yml, python/ql/lib/qlpack.yml
Ensure the version range is flexible enough to handle future version changes.
=> Fix semver for upgrades references

javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml, javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml
0.0.1 was released, so we should bump to 0.0.2.
=> Bump ATM pack version to 0.0.2

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointFeatures.qll
Pushing the restriction to 256 tokens into the `bodyTokens` predicate means we avoid this predicate blowing up due to very large functions.
This results in a runtime improvement from 1800s+ to 294s as measured on a problematic repo on my machine (I didn't wait for the query to finish running).
=> ATM: Optimize body tokens by pushing in size restriction

cpp/ql/lib/semmle/code/cpp/dataflow/internal/TaintTrackingUtil.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TaintTrackingUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking3/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/TaintTrackingPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking3/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking4/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking5/TaintTrackingImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll, java/ql/lib/semmle/code/java/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/TaintTrackingPrivate.qll, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking1/TaintTrackingImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking2/TaintTrackingImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking3/TaintTrackingImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking4/TaintTrackingImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
=> Dataflow: Add default taint sanitizer guard

cpp/ql/lib/change-notes/2022-01-11-remove-upgrades-packs.md, csharp/ql/lib/change-notes/2022-01-11-remove-upgrades-packs.md, java/ql/lib/change-notes/2022-01-11-remove-upgrades-packs.md, javascript/ql/lib/change-notes/2022-01-11-remove-upgrades-packs.md, python/ql/lib/change-notes/2022-01-11-remove-upgrades-packs.md
Note that codeql/ruby-all has not changed.
=> Changenotes: Add changenotes for upgrades refactoring

javascript/ql/src/Security/CWE-843/examples/TypeConfusionThroughParameterTampering.js, javascript/ql/src/Security/CWE-843/examples/TypeConfusionThroughParameterTampering_fixed.js
Closes https://github.com/github/codeql/issues/7488
Fixes the issues with the example pointed out in the linked issues.
=> Fix example in JavaScript query

cpp/ql/lib/semmle/code/cpp/commons/NullTermination.qll, cpp/ql/src/Security/CWE/CWE-131/NoSpaceForZeroTerminator.ql
Quick fix for some code duplication that was noted in prior work on the null termination queries.
=> C++: Fix some code duplication.

cpp/ql/src/experimental/Security/CWE/CWE-266/IncorrectPrivilegeAssignment.ql
Implements suggestions from https://github.com/github/codeql/pull/6949#issuecomment-976482965
=> C++: Reduce FPs in IncorrectPrivilegeAssignment.ql

java/ql/src/utils/model-generator/CaptureSinkModels.ql, java/ql/src/utils/model-generator/ModelGeneratorUtils.qll, java/ql/test/utils/model-generator/p/Sinks.java
* Exclude `main` methods
* Exclude any `logging` sinks as are not actionable for the users of specific libraries
=> Java: Exclude irrelevant rows from models

javascript/ql/lib/semmle/javascript/DOM.qll, javascript/ql/lib/semmle/javascript/Extend.qll, javascript/ql/lib/semmle/javascript/Promises.qll, javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll, javascript/ql/lib/semmle/javascript/frameworks/Cheerio.qll, javascript/ql/lib/semmle/javascript/frameworks/ConnectExpressShared.qll, javascript/ql/lib/semmle/javascript/frameworks/Files.qll, javascript/ql/lib/semmle/javascript/frameworks/NoSQL.qll, javascript/ql/lib/semmle/javascript/frameworks/NodeJSLib.qll, javascript/ql/lib/semmle/javascript/frameworks/PkgCloud.qll, javascript/ql/lib/semmle/javascript/frameworks/Restify.qll, javascript/ql/lib/semmle/javascript/frameworks/SocketIO.qll, javascript/ql/lib/semmle/javascript/frameworks/jQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/IndirectCommandArgument.qll, javascript/ql/lib/semmle/javascript/security/dataflow/PrototypePollutionCustomizations.qll, javascript/ql/test/tutorials/Validating RAML-based APIs/HTTP.qll, javascript/ql/test/tutorials/Validating RAML-based APIs/query2.expected, javascript/ql/test/tutorials/Validating RAML-based APIs/query2.ql, javascript/ql/test/tutorials/Validating RAML-based APIs/query3.expected, javascript/ql/test/tutorials/Validating RAML-based APIs/query3.ql, javascript/ql/test/tutorials/Validating RAML-based APIs/query4.expected, javascript/ql/test/tutorials/Validating RAML-based APIs/query4.ql
Fixes a lot of code-scanning warnings [like this one](https://github.com/github/codeql/security/code-scanning/6156?query=ref%3Arefs%2Fheads%2Fmain).
=> JS: use more set literals

javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectQuery.qll
Fixes [this code-scanning alert](https://github.com/github/codeql/security/code-scanning/2736?query=ref%3Arefs%2Fheads%2Fmain).
=> JS: move electron sink to the customizations file

java/ql/lib/semmle/code/java/frameworks/android/Slice.qll, java/ql/lib/semmle/code/java/security/ImplicitPendingIntents.qll, java/ql/src/Security/CWE/CWE-927/ImplicitPendingIntents.qhelp, java/ql/src/Security/CWE/CWE-927/ImplicitPendingIntents.ql, java/ql/src/change-notes/2021-12-21-android-implicit-pendingintents.md
This PR introduces fixes and improvements on top of github/codeql#6779.
=> Java: Improvements to the Android query Use of implicit PendingIntents

docs/codeql/codeql-cli/getting-started-with-the-codeql-cli.rst
The output has changed and there are no more upgrades
packs. There are also other changes included here.
Related to https://github.com/github/semmle-code/pull/40918
=> Update docs on the output of `resolve qlpacks`

ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll
```
[2022-01-25 12:35:14] (234s) Tuple counts for ActionController::ActionControllerHelperMethod#class#ff/2@ef816fil after 1.5s:
7685     ~0%     {3} r1 = JOIN ActionController::ActionControllerContextCall#ff#shared WITH Method::Method::getName_dispred#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.1 'controllerClass', Lhs.0 'this'
13198    ~0%     {3} r2 = JOIN r1 WITH Constant::ConstantValue::getStringOrSymbol_dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.1 'controllerClass', Lhs.2 'this', Rhs.1
15835365 ~4%     {5} r3 = JOIN r2 WITH AST::AstNode::getEnclosingModule_dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, "helper_method", Lhs.0 'controllerClass', Lhs.1 'this', Lhs.2
12943    ~1%     {4} r4 = JOIN r3 WITH Call::MethodCall::getMethodName_dispred#ff ON FIRST 2 OUTPUT Lhs.4, Lhs.2 …
```
=> Ruby: Fix bad join in `ActionControllerHelperMethod`

csharp/ql/lib/semmlecode.csharp.dbscheme.stats
I forgot to remove a few entries on https://github.com/github/codeql/pull/7746.
=> C#: Remove stats for removed relations

csharp/ql/lib/semmle/code/csharp/File.qll
https://github.com/github/codeql/pull/7515/ follow-up.
=> C#: Restrict stub logic to QL test DBs

csharp/ql/src/Metrics/internal/ExtractorDiagnostics.ql
=> C#: Add internal extractor diagnostics query

csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImplShared.qll, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplShared.qll, ruby/ql/test/library-tests/controlflow/graph/Cfg.expected, ruby/ql/test/library-tests/regexp/parse.expected, ruby/ql/test/library-tests/regexp/parse.ql
- Ruby: add more properties for ordering nodes in graph tests
- C#: sync changes from Ruby to improve ordering of graph test output
=> Ruby/C#: more stable graph test ordering

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll, cpp/ql/lib/tutorial.qll, cpp/ql/test/TestUtilities/InlineExpectationsTest.qll, csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImplShared.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplCommon.qll, csharp/ql/lib/tutorial.qll, csharp/ql/test/TestUtilities/InlineExpectationsTest.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplCommon.qll, java/ql/lib/tutorial.qll, java/ql/test/TestUtilities/InlineExpectationsTest.qll, javascript/ql/lib/semmle/javascript/security/performance/ReDoSUtil.qll, javascript/ql/lib/tutorial.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplCommon.qll, python/ql/lib/semmle/python/dataflow/new/internal/TypeTracker.qll, python/ql/lib/semmle/python/security/performance/ReDoSUtil.qll, python/ql/lib/tutorial.qll, python/ql/test/TestUtilities/InlineExpectationsTest.qll, ruby/ql/lib/codeql/ruby/ast/internal/Variable.qll, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplShared.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplCommon.qll, ruby/ql/lib/codeql/ruby/frameworks/StandardLibrary.qll, ruby/ql/lib/codeql/ruby/security/ServerSideRequestForgeryCustomizations.qll, ruby/ql/lib/codeql/ruby/security/performance/ReDoSUtil.qll, ruby/ql/lib/codeql/ruby/typetracking/TypeTracker.qll, ruby/ql/lib/tutorial.qll, ruby/ql/test/TestUtilities/InlineExpectationsTest.qll
Fixes all alerts reported in:
`gh api -H 'Accept: application/sarif+json' https://api.github.com/repos/github/codeql/code-scanning/analyses/20490376`
https://github.com/github/codeql/pull/7814/checks?check_run_id=5036474517
=> Ruby: fix all QL-QL alerts

python/ql/lib/semmle/python/ApiGraphs.qll
Converts the labels in API graphs to an IPA type.  
A similar refactoring helped performance in JS, but I doubt it'll do much here (because you're not using API-graphs that much yet).   
However, the refactoring should help keep performance good in the future. 
This should be a simple easy to review PR before I open [the big one](https://github.com/github/codeql/pull/7806) for review. 
See the backref for a performance evaluation (not done yet, but I won't merge unless it turns out OK).
=> Python: refactor API-graph labels to an IPA type

javascript/ql/lib/semmle/javascript/NodeJS.qll, javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction.expected, javascript/ql/test/query-tests/Security/CWE-078/lib/isImported.js, javascript/ql/test/query-tests/Security/CWE-078/lib/lib.js
Gets a TP for CVE-2021-45459 
[An evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-7870-0584a6a__nightly__security-extend__2/reports).  (Ignore the backrefs).
=> JS: recognize a nodejs re-exports in a loop

csharp/ql/test/library-tests/csharp10/Tuples.cs, csharp/ql/test/library-tests/csharp10/tuples.expected, csharp/ql/test/library-tests/csharp10/tuples.ql, csharp/ql/test/library-tests/dataflow/patterns/Patterns.cs, csharp/ql/test/library-tests/dataflow/tuples/DataFlowStep.expected, csharp/ql/test/library-tests/dataflow/tuples/PrintAst.expected, csharp/ql/test/library-tests/dataflow/tuples/Tuples.cs, csharp/ql/test/library-tests/dataflow/tuples/Tuples.expected, csharp/ql/test/library-tests/dataflow/tuples/Tuples.ql
In this PR, we
* Refactor existing tuple data flow test cases to use the default taint configuration.
* Introduce data flow tests for mixed assignment and declaration tuples.
* Introduce tests for the mixed assignment and declaration tuples in general.
=> C# 10: Tuple deconstruction.

javascript/ql/lib/javascript.qll, javascript/ql/lib/semmle/javascript/frameworks/Snapdragon.qll, javascript/ql/src/change-notes/2022-02-10-snapdragon.md, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialBackTracking.expected, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialReDoS.expected, javascript/ql/test/query-tests/Performance/ReDoS/lib/lib.js, javascript/ql/test/query-tests/Performance/ReDoS/lib/snapdragon.js
Gets a TP/TN for CVE-2018-1109
[Evaluation looks clean](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-7921-d55920a__nightly__security-extend__1/reports).
=> JS: add model for the snapdragon library

cpp/ql/lib/semmle/code/cpp/dataflow/internal/FlowVar.qll, docs/codeql/ql-language-reference/formulas.rst
$ git grep -i descendant | wc -l
170
=> Spelling: Use "descendant" rather than "descendent" for consistency

javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/CountAlertsAndEndpoints.ql
Closes https://github.com/github/ml-ql-adaptive-threat-modeling/issues/1214
This ensures that when we identity databases to use in the evaluation sets, the number of recoverable results in the end-to-end evaluation matches those seen when running the `CountAlertsAndEndpoints.ql` query.
@annarailton ran some tests with the updated query, which can be seen [here](https://github.com/github/ml-ql-adaptive-threat-modeling/issues/1214#issuecomment-1046856937).
=> Update counting query to match end-to-end results

javascript/ql/experimental/adaptivethreatmodeling/src/NosqlInjectionATM.md, javascript/ql/experimental/adaptivethreatmodeling/src/SqlInjectionATM.md
The docs from the ATM NoSqlInjection query were about SQL injections. This PR fixes that, and also polishes the ATM SQL Injection query docs.
=> update ATM NosqlInjection and SqlInjection query docs

javascript/ql/src/Security/CWE-918/ClientSideRequestForgery.qhelp
Addresses @hubwriter's change request: https://github.com/github/codeql/pull/8054#discussion_r812688416
=> JS: Minor fixup in the client-side request forgery qhelp

ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/ide-contextual-queries/printAst.ql, ql/ql/src/queries/style/RegexpInsteadOfPattern.ql
I downloaded [the latest .sarif files from the workflow](https://github.com/github/codeql/actions/workflows/ql-for-ql-build.yml?query=branch%3Amain), and fixed everything.
=> QL: fix ql-for-ql errors inside ql-for-ql

docs/codeql/support/reusables/versions-compilers.rst
See https://github.com/github/docs-content/issues/6395
=> Update supported Java and Python versions

python/ql/lib/change-notes/2022-02-08-fix-attribute-taint.md, python/ql/lib/semmle/python/dataflow/new/internal/TaintTrackingPrivate.qll, python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/test_attr.py, python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/test_with.py
Fixes https://github.com/github/codeql/issues/7786
Draft PR so we can gauge what the impact of this change is before merging it (and look for failing QL tests :sweat_smile:)
=> Python: Fix attribute taint

docs/codeql/writing-codeql-queries/debugging-data-flow-queries-using-partial-flow.rst
The things that I mentioned in https://github.com/github/codeql/pull/6502#issuecomment-901087620 that never got into the document :flushed:
=> Docs: Mention `hasPartialFlowRev` and performance problem

ruby/ql/lib/codeql/ruby/frameworks/Core.qll, ruby/ql/lib/codeql/ruby/frameworks/core/String.qll, ruby/ql/test/library-tests/dataflow/string-flow/string-flow.expected, ruby/ql/test/library-tests/dataflow/string-flow/string-flow.ql, ruby/ql/test/library-tests/dataflow/string-flow/string_flow.rb, ruby/ql/test/query-tests/security/cwe-312/CleartextLogging.expected
This seemed fairly straightforward, so I thought I'd give it a go.
This PR is branched from #7886, which I think is why not all the CI tests are running on it. Once that PR is merged, we should hopefully get a full CI run.
=> Ruby: Add String flow summaries

CONTRIBUTING.md
=> Fix dead link in `CONTRIBUTING.md`

cpp/ql/src/codeql-suites/cpp-code-scanning.qls, cpp/ql/src/codeql-suites/cpp-lgtm-full.qls, cpp/ql/src/codeql-suites/cpp-security-and-quality.qls, cpp/ql/src/codeql-suites/cpp-security-extended.qls
Fixes https://github.com/github/codeql/issues/8412
See https://github.com/github/codeql/issues/8412#issuecomment-1078281668 for more detail.
A fix for the CLI is forthcoming.
=> Suites: Remove self-referential `from` directives

ql/ql/src/codeql_ql/ast/Ast.qll
The last PR was a little quick, sorry.
=> QL: fix Import::getImportString

cpp/ql/lib/semmle/code/cpp/controlflow/StackVariableReachability.qll, cpp/ql/lib/semmle/code/cpp/security/Overflow.qll
Same as https://github.com/github/codeql/pull/8612. It was causing weird CI failures (maybe due to the PR being retargeted), so I'll see if a fresh PR fixes it 🤞.
=> C++: Fix bad magic and bad join

python/ql/lib/semmle/python/Concepts.qll
This solved performance problems experienced in https://github.com/github/codeql/pull/8634, and this commit+PR is to ensure we get this change in as fast as possible.
=> Python: Rewrite concepts to use `extends ... instanceof ...`

python/ql/lib/semmle/python/frameworks/Aiohttp.qll, python/ql/lib/semmle/python/frameworks/Django.qll, python/ql/lib/semmle/python/frameworks/Flask.qll, python/ql/lib/semmle/python/frameworks/RestFramework.qll, python/ql/lib/semmle/python/frameworks/Stdlib.qll, python/ql/lib/semmle/python/frameworks/Tornado.qll, python/ql/lib/semmle/python/frameworks/Twisted.qll
Based on offline conversation we had today. /cc @erik-krogh
=> Python: Refactor how we find a `Class` from `API::Node`

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForOnActivityResult.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl2.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplForLibraries.qll
Minor cleanup following https://github.com/github/codeql/pull/8474.
=> Dataflow: Cleanup unused column

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForOnActivityResult.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl2.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplForLibraries.qll
=> Add `nomagic` to `revPartialPathStep`

swift/codegen/schema.yml, swift/ql/lib/swift.dbscheme
=> Swift: rename certain dbscheme columns

docs/supported-queries.md
update broken link target from semmle to github
=> Docs - Supported Queries - Fixing broken link

.github/workflows/ql-for-ql-build.yml
=> QL: add swift to QL-for-QL

.github/labeler.yml
Thanks to @nickrolfe for suggesting this.
=> Include Swift in `labeler.yml`

java/ql/lib/semmle/code/java/Javadoc.qll, java/ql/lib/semmle/code/java/controlflow/BasicBlocks.qll, java/ql/lib/semmle/code/java/controlflow/Dominance.qll, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/deadcode/DeadEnumConstant.qll, java/ql/lib/semmle/code/java/frameworks/ApacheLdap.qll, java/ql/lib/semmle/code/java/frameworks/Jndi.qll, java/ql/lib/semmle/code/java/frameworks/SpringLdap.qll, java/ql/lib/semmle/code/java/frameworks/UnboundId.qll, java/ql/lib/semmle/code/java/frameworks/struts/StrutsXML.qll, java/ql/src/Advisory/Declarations/NonPrivateField.ql, java/ql/src/Likely Bugs/Serialization/NonSerializableField.ql, java/ql/src/Likely Bugs/Serialization/NonSerializableInnerClass.ql
Identified by QL-for-QL in https://github.com/github/codeql/pull/8796
=> Java: Remove some useless imports.

python/ql/test/query-tests/Security/CWE-730-PolynomialReDoS/PolynomialBackTracking.expected, python/ql/test/query-tests/Security/CWE-730-PolynomialReDoS/PolynomialBackTracking.ql
It seems to have been misplaced in the `src` folder.
=> PY: move the polynomialbacktracking-test to the test folder

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointTypes.qll, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/ExtractEndpointLabelEncoding.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/ExtractEndpointMapping.ql, javascript/ql/experimental/adaptivethreatmodeling/test/query_mappings/ExtractEndpointLabelEncoding.expected, javascript/ql/experimental/adaptivethreatmodeling/test/query_mappings/ExtractEndpointLabelEncoding.qlref
- Change `NotASinkType` to `NegativeType`
- Change `encoding` -> `label` and `description` -> `labelName`
- Add test for query mappings
- Update `endpointTypeEncoded` -> `label`
Fixes https://github.com/github/ml-ql-adaptive-threat-modeling/issues/1819
Fixes https://github.com/github/ml-ql-adaptive-threat-modeling/issues/1820
Fixes https://github.com/github/ml-ql-adaptive-threat-modeling/issues/1821
Fixes https://github.com/github/ml-ql-adaptive-threat-modeling/issues/1816
PR in `backend`: https://github.com/github/ml-ql-adaptive-threat-modeling-backend/pull/1270
Requires rebasing on ~https://github.com/github/codeql/pull/8557~ https://github.com/github/codeql/pull/8597 for the tests to all pass.
=> Experimental (ATM): update query label mappings

python/ql/lib/semmle/python/essa/Essa.qll, python/ql/lib/semmle/python/essa/SsaCompute.qll, python/ql/src/Numerics/Pythagorean.ql, python/ql/test/query-tests/Numerics/Pythagorean.expected
These were all observed on various forks of the `jython/jython` project.
--- 
No change note required, as this is just a performance fix.
=> Python: Fix a bunch of bad joins

java/ql/lib/semmle/code/java/frameworks/Hibernate.qll, java/ql/lib/semmle/code/java/frameworks/HikariCP.qll, java/ql/lib/semmle/code/java/frameworks/Jdbc.qll, java/ql/lib/semmle/code/java/frameworks/Jdbi.qll, java/ql/lib/semmle/code/java/frameworks/JsonJava.qll, java/ql/lib/semmle/code/java/frameworks/Logging.qll, java/ql/lib/semmle/code/java/frameworks/MyBatis.qll, java/ql/lib/semmle/code/java/frameworks/Optional.qll, java/ql/lib/semmle/code/java/frameworks/Regex.qll, java/ql/lib/semmle/code/java/frameworks/SpringJdbc.qll, java/ql/lib/semmle/code/java/frameworks/Stream.qll, java/ql/lib/semmle/code/java/frameworks/android/Android.qll, java/ql/lib/semmle/code/java/frameworks/android/ContentProviders.qll, java/ql/lib/semmle/code/java/frameworks/android/Intent.qll, java/ql/lib/semmle/code/java/frameworks/android/SQLite.qll, java/ql/lib/semmle/code/java/frameworks/android/Widget.qll, java/ql/lib/semmle/code/java/frameworks/jOOQ.qll, java/ql/lib/semmle/code/java/security/ImplicitPendingIntents.qll, java/ql/lib/semmle/code/xml/AndroidManifest.qll, java/ql/src/experimental/Security/CWE/CWE-073/JFinalController.qll, java/ql/src/experimental/Security/CWE/CWE-200/InsecureWebResourceResponse.ql, java/ql/src/experimental/Security/CWE/CWE-552/UnsafeUrlForward.ql, java/ql/src/experimental/Security/CWE/CWE-552/UnsafeUrlForward.qll, java/ql/src/experimental/semmle/code/java/PathSanitizer.qll
Continuation of https://github.com/github/codeql/pull/8796 and https://github.com/github/codeql/pull/8875.
=> Java: Make all imports of ExternalFlow private

csharp/ql/test/query-tests/Language Abuse/UselessCastToSelf/UselessCastToSelf.cs, csharp/ql/test/query-tests/Language Abuse/UselessCastToSelf/UselessCastToSelf.expected
Documents the FP reported [here](https://github.com/github/codeql/issues/8627).
=> C#: Add FP test for `cs/useless-cast-to-self`

java/ql/lib/semmle/code/java/security/CleartextStorageAndroidFilesystemQuery.qll, java/ql/lib/semmle/code/java/security/Files.qll, java/ql/lib/semmle/code/java/security/InformationLeak.qll, java/ql/lib/semmle/code/java/security/LogInjection.qll, java/ql/lib/semmle/code/java/security/QueryInjection.qll, java/ql/lib/semmle/code/java/security/SensitiveLoggingQuery.qll, java/ql/lib/semmle/code/java/security/UrlRedirect.qll, java/ql/lib/semmle/code/java/security/XPath.qll, java/ql/lib/semmle/code/java/security/XSS.qll, java/ql/lib/semmle/code/java/security/XsltInjection.qll, java/ql/src/experimental/Security/CWE/CWE-200/AndroidFileIntentSink.qll, java/ql/src/experimental/Security/CWE/CWE-400/ThreadResourceAbuse.qll
=> Java: Make more ExternalFlow imports private

javascript/ql/lib/change-notes/2022-04-30-xss-selection-source.md, javascript/ql/lib/semmle/javascript/security/dataflow/XssThroughDomCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/XssThroughDom.expected, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/xss-through-dom.js
A Selection object represents the range of text selected by the user or the caret's current position.  The Selection API can be used by applications and UI components such as rich-text editors to operate over a user's text selection. The current DOM text sources do not include this API.
=> JS: Selection API DOM text source

ql/ql/src/codeql_ql/ast/Ast.qll
Resolves the QL-for-QL errors seen here: https://github.com/github/codeql/pull/9109
=> QL: add implicit -all to a query pack to match the CodeQL pack resolution

java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt
Ideally this would be in a more JSON-friendly format, and also in the database, but this at least makes the information available.
=> Kotlin: Log peak memory usge before and after extractor

java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt
Makes it easier to filter out the peak memory info
=> Kotlin: Tweak logging

java/ql/src/experimental/Security/CWE/CWE-611/XXELib.qll, java/ql/test/experimental/query-tests/security/CWE-611/XXE.expected, java/ql/test/experimental/query-tests/security/CWE-611/XXE.java
=> Java: Remove org.dom4j.DocumentHelper:parseText as XXE sink

.github/workflows/go-tests.yml
=> Go: trigger CI jobs on Go related changes only

swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowElements.qll, swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll
Resolves the comments raised by @rdmarsh2 in https://github.com/github/codeql/pull/9291.
=> Swift: Fixups for #9291

docs/codeql/codeql-for-visual-studio-code/setting-up-codeql-in-visual-studio-code.rst
@intrigus-lgtm - thanks for https://github.com/github/codeql/pull/9243#discussion_r879744794 ✨ 
It looks as if you spotted this typo just as the pull request was being merged so I've opened a new PR to fix it.
=> Fix typo in recent docs update

swift/README.md
Further minor updates to the swift readme.
=> Swift: Update readme

.github/workflows/labeler.yml
Like in the example on https://github.com/actions/labeler#create-workflow
=> Misc: Set permissions for labeler Action

java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
The Parcelize plugin generates IR that we would otherwise not see. Specifically, there are method invocations on raw types, such as `java.util.ArrayList.add(Object)`. This PR changes these raw type accesses to their generic counterparts, parameterized with `Object`. So the above becomes `java.util.ArrayList<Object>.add(Object)`.
=> Kotlin: Fix fake raw type symbols used by the Parcelize plugin

java/kotlin-extractor/build.py
This can make life easier when debugging.
=> Kotlin: Do each build in its own directory

swift/ql/lib/codeql/swift/elements/Element.qll, swift/ql/test/extractor-tests/expressions/all.expected, swift/ql/test/extractor-tests/patterns/all.expected, swift/ql/test/extractor-tests/types/Types.expected, swift/ql/test/library-tests/controlflow/graph/Cfg.expected, swift/ql/test/library-tests/parent/parent.expected
Another attempt to remove flakiness
=> Swift: remove toString from UnknownElement

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
Previously we handled the case of *methods* with potentially-wildcarded types that Java nontheless constrains to be invariant, but missed out the constructor case.
=> Kotlin: Fix wildcard introduction vs. constructor parameters

java/ql/lib/semmle/code/java/dataflow/internal/DataFlowUtil.qll, java/ql/src/Security/CWE/CWE-022/TaintedPath.ql
This adds a parameterised-module alternative to the existing BarrierGuard class.
=> Java: Add support for BarrierGuards as parameterised modules.

cpp/ql/test/library-tests/variables/global/d.cpp, cpp/ql/test/library-tests/variables/global/d.h, cpp/ql/test/library-tests/variables/global/e.cpp, cpp/ql/test/library-tests/variables/global/vardecl.expected, cpp/ql/test/library-tests/variables/global/variables.expected
Small addition to the tests added here: https://github.com/github/codeql/pull/9631
=> C++: Add variable in namespace test

.github/workflows/swift-codegen.yml, .pre-commit-config.yaml, swift/codegen/.pep8, swift/codegen/generators/dbschemegen.py, swift/codegen/test/test_cppgen.py, swift/codegen/test/test_qlgen.py, swift/codegen/test/test_schema.py, swift/codegen/test/test_trapgen.py, swift/integration-tests/cross-references/test.py
Additionally set up a pre-commit hook and a CI check for that.
=> Swift: autopep8 codegen

swift/codegen/generators/qlgen.py, swift/codegen/test/test_qlgen.py
If one modifies a QL stub but forgets to remove the `// generated`
header comment, codegen will now abort with an error rather than
silently reverting the change.
This is based on the rough heuristic of just counting the lines. If any
change is done to the stub class, the number of lines is bound to be
5 or more.
=> Swift: prevent accidental revert of modified stub

javascript/ql/src/Declarations/UnusedVariable.ql
Fixes https://github.com/github/codeql/issues/9674
=> JS: Fix unused variable FP in template placeholders

ruby/Cargo.lock, ruby/extractor/Cargo.toml, ruby/generator/Cargo.toml
Updates the grammar to include https://github.com/tree-sitter/tree-sitter-ruby/pull/220
=> Ruby: update tree-sitter-ruby

java/ql/lib/change-notes/2022-05-18-android-external-storage.md, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/dataflow/FlowSources.qll, java/ql/lib/semmle/code/java/frameworks/android/ExternalStorage.qll, java/ql/lib/semmle/code/java/security/FileReadWrite.qll, java/ql/test/library-tests/frameworks/android/external-storage/Test.java, java/ql/test/library-tests/frameworks/android/external-storage/options, java/ql/test/library-tests/frameworks/android/external-storage/test.ql, java/ql/test/stubs/google-android-9.0.0/android/os/Environment.java
Adds as sources the contents of files that come from an external storage directory.
=> Java: Add sources for Android external storage

docs/codeql/reusables/beta-note-package-management.rst
Mentioned in https://github.com/github/codeql/pull/9570
=> Recommend installing the latest version of the CLI to use packaging

javascript/externs/nodejs/fs.js, javascript/ql/lib/change-notes/2022-06-30-chownr.md, javascript/ql/lib/semmle/javascript/frameworks/Files.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/tainted-access-paths.js
Recognizes the sink for CVE-2018-7408 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/PR-9754-0-javascript__1/reports).
=> JS: add model for chownr

javascript/ql/lib/semmle/javascript/Actions.qll
Resolves https://github.com/github/codeql-core/issues/2528 and extends for future work.
=> Added Workflow.getName and Step.GetId

ruby/extractor/src/extractor.rs, ruby/extractor/src/main.rs, ruby/extractor/src/trap.rs
This cherry-picks the uncontroversial and non-functional changes from #7219.
=> Ruby: some extractor refactoring

swift/extractor/visitors/DeclVisitor.cpp
We have found out there can be separate declarations (`VarDecl` or
`AccessorDecl`) which are effectively the same (with equal mangled name)
but come from different clang modules. This is the case for example
for glibc constants like `L_SET` that appear in both `SwiftGlibc` and
`CDispatch`.
In this patch, we simply avoid full deduplication in that case by
appending the module name to the trap key for non-swift modules.
A more solid solution should be found in the future.
=> Swift: append clang module names in trap keys

swift/ql/lib/codeql/swift/dataflow/TaintTracking.qll
I forgot to add this file in https://github.com/github/codeql/pull/9275.
=> Swift: Add 'TaintTracking.qll'

.github/workflows/csv-coverage-pr-artifacts.yml, .github/workflows/csv-coverage-timeseries.yml, .github/workflows/csv-coverage-update.yml, .github/workflows/csv-coverage.yml, .github/workflows/go-tests.yml
Addresses https://github.com/github/codeql/pull/9938#pullrequestreview-1057484492
=> CI: remove unneeded PATH definitions

.github/workflows/check-qldoc.yml, .github/workflows/csv-coverage-metrics.yml, .github/workflows/csv-coverage-pr-artifacts.yml, .github/workflows/go-tests.yml, .github/workflows/js-ml-tests.yml, .github/workflows/mad_regenerate-models.yml, .github/workflows/query-list.yml, .github/workflows/ruby-build.yml, .github/workflows/ruby-qltest.yml, .github/workflows/swift-codegen.yml, .github/workflows/swift-integration-tests.yml, .github/workflows/swift-qltest.yml, .github/workflows/validate-change-notes.yml
I had forgotten to include the file name (`action.yml`) in the paths.
=> CI: fix path triggers

swift/ql/lib/codeql/swift/dataflow/Ssa.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
As pointed out by @hvitved [here](https://github.com/github/codeql/pull/9342#discussion_r936292113).
cc @rdmarsh2.
=> Swift: Cache `lastRefRedef`

javascript/ql/lib/semmle/javascript/Arrays.qll, javascript/ql/test/library-tests/Arrays/TaintFlow.expected, javascript/ql/test/library-tests/Arrays/TaintFlow.ql, javascript/ql/test/library-tests/Arrays/arrays.js, javascript/ql/test/library-tests/Arrays/printAst.expected
=> Tests for rebased 7010

ruby/ql/consistency-queries/DataFlowConsistency.ql, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/test/library-tests/dataflow/params/params-flow.expected, ruby/ql/test/library-tests/dataflow/params/params_flow.rb, ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected, ruby/ql/test/library-tests/dataflow/summaries/summaries.rb
The added tests document where flow was missing.
=> Ruby: Support more flow through keyword arguments

java/ql/lib/change-notes/2022-08-05-asynctask-improvements.md, java/ql/lib/semmle/code/java/frameworks/android/AsyncTask.qll, java/ql/test/experimental/query-tests/security/CWE-200/SensitiveAndroidFileLeak.expected, java/ql/test/library-tests/frameworks/android/asynctask/Test.java, java/ql/test/library-tests/frameworks/android/asynctask/test.ql
Uses jump steps to model the life-cycle described here: https://developer.android.com/reference/android/os/AsyncTask\#the-4-steps
=> Java: Improve AsyncTask data flow support

cpp/ql/lib/semmle/code/cpp/Specifier.qll
See here: https://github.com/github/codeql/pull/9971#discussion_r943280458
=> C++: Improve QLDoc based on earlier review

java/ql/lib/semmle/code/java/JDK.qll
This looked like a minor perf improvement, which I randomly came across. Let's see what dca thinks.
=> Java: Minor perf improvement.

swift/ql/lib/codeql/swift/dataflow/Ssa.qll
This fixes some FNs we were seeing on https://github.com/github/codeql/pull/10045.
cc {@AlexDenisov, @redsun82}.
=> Swift: Fix SSA for calls to getter functions

javascript/ql/src/Expressions/TypoDatabase.qll, ql/ql/src/codeql_ql/style/TypoDatabase.qll
See https://github.com/github/codeql/pull/10080
=> add desugered to the typo database

ql/ql/src/queries/style/RedundantOverride.ql, ql/ql/test/queries/style/RedundantOverride/RedundantOverride.expected, ql/ql/test/queries/style/RedundantOverride/RedundantOverride.qll, ql/ql/test/queries/style/RedundantOverride/RedundantOverride.qlref
Inspired by https://github.com/github/codeql/pull/10094 (which it finds, in addition to a few others).
=> QL: Add redundant overrides query

ql/ql/src/codeql_ql/style/RedundantOverrideQuery.qll, ql/ql/src/queries/style/RedundantOverride.ql, ql/ql/test/queries/style/RedundantOverride/RedundantOverride.expected, ql/ql/test/queries/style/RedundantOverride/RedundantOverride.qll
=> QL: Refine 'redundant override' query

cpp/ql/lib/semmle/code/cpp/File.qll, csharp/ql/lib/semmle/code/cil/Types.qll, csharp/ql/lib/semmle/code/csharp/Callable.qll, csharp/ql/lib/semmle/code/csharp/Namespace.qll, csharp/ql/lib/semmle/code/csharp/Property.qll, csharp/ql/src/experimental/ir/implementation/raw/internal/TranslatedExpr.qll, csharp/ql/src/experimental/ir/implementation/raw/internal/desugar/internal/TranslatedCompilerGeneratedDeclaration.qll, javascript/ql/lib/semmle/javascript/Files.qll, javascript/ql/lib/semmle/javascript/frameworks/xUnit.qll, javascript/ql/test/library-tests/frameworks/Testing/customised/Tests.ql, python/ql/lib/semmle/python/Comprehensions.qll, python/ql/lib/semmle/python/Flow.qll, python/ql/lib/semmle/python/Keywords.qll, python/ql/lib/semmle/python/dataflow/new/internal/Attributes.qll, ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/test/callgraph/Foo.qll, ql/ql/test/callgraph/callgraph.expected, ruby/ql/lib/codeql/ruby/ast/Module.qll, ruby/ql/lib/codeql/ruby/ast/Variable.qll, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImpl.qll
Created using an automatic patch based on https://github.com/github/codeql/pull/10102.
=> Remove redundant overrides

javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/evaluation/NosqlInjection.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/evaluation/SqlInjection.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/evaluation/TaintedPath.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/evaluation/Xss.ql
Deprecations gets deleted eventually (by me).  
So they should be fixed.
=> ATM: fix deprecation warnings in ATM tests

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
The non-null-expressions were in `getFunctionalInterfaceType` and `getFunctionalInterfaceTypeWithTypeArgs`. Everything else is just indenting code inside `if null` conditionals, and reordering blocks of code so that those conditionals make sense.
=> Kotlin: Fix some more not-null-exprs in the extractor

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
Along the way, a bit of refactoring to make the code simpler and more robust.
Probably easiest to review commit-by-commit.
=> Kotlin: Remove some more non-null-expressions

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
These only needed pretty straightforward, local changes.
=> Kotlin: Remove more not-null expressions

java/ql/lib/change-notes/2022-08-25-taint-model-spring-crudrepository.md, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/frameworks/spring/Spring.qll, java/ql/lib/semmle/code/java/frameworks/spring/SpringData.qll, java/ql/test/library-tests/frameworks/spring/data/Test.java, java/ql/test/library-tests/frameworks/spring/data/options, java/ql/test/library-tests/frameworks/spring/data/test.ql
@atorralba  @aschackmull as discussed.
This yields an [SQL injection in WebGoat](https://github.com/zbazztian/webgoat-scan/security/code-scanning/292).
=> Java: Add data flow model for Spring's CrudRepository.save() method

java/ql/lib/semmle/code/java/security/OverlyLargeRangeQuery.qll, javascript/ql/lib/semmle/javascript/security/OverlyLargeRangeQuery.qll, python/ql/lib/semmle/python/security/OverlyLargeRangeQuery.qll, ruby/ql/lib/codeql/ruby/security/OverlyLargeRangeQuery.qll
Same as this PR: https://github.com/github/codeql/pull/10213. 
But against the `rc/3.7` branch.
=> put a limit on the length of the equivalent range

java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
=> Kotlin: Small simplification

javascript/ql/lib/semmle/javascript/ApiGraphs.qll, javascript/ql/lib/semmle/javascript/Classes.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll, javascript/ql/test/library-tests/frameworks/data/test.expected, javascript/ql/test/library-tests/frameworks/data/test.js, javascript/ql/test/library-tests/frameworks/data/test.ql
Some changes to the JS-specific MaD library in support of generated typings.
[Evaluation](https://github.com/github/codeql-dca-main/issues/6509) looks quiet
=> JS: Some JS-specific MaD changes

javascript/ql/lib/semmle/javascript/ApiGraphs.qll
Fixes a timeout in the upgrade caused by the N^2 behaviour when a class with N members has an instance that escapes at N different def-nodes.
Previously, each def-node would have edges to each of the class's members, so that patterns like this would work:
```ts
class C {
foo(x) {} // 'x' found by API::moduleImport("testlib").getParameter(0).getMember("foo").getParameter(0)
bar() {}
baz() {}
}
const c = new C();
c.field = x;
require('testlib')(c);
```
Now, instead of adding edges from the `c` def-node, we mark the `MkClassInstance` API node as another def-node for that argument. That is, when you do `API::moduleImport("testlib").getParameter(0)`, you now get two def-nodes: `MkDef(c)` for the argument and `MkClassInstance(C)` for the class instance. The `MkDef` node will have the edges …
=> JS: Make API graph more sparse for escaping class instance members

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
=> Kotlin: Refactor extractStaticTypeAccessQualifier

python/ql/test/experimental/dataflow/typetracking_imports/README.md, python/ql/test/experimental/dataflow/typetracking_imports/highlight_problem.expected, python/ql/test/experimental/dataflow/typetracking_imports/highlight_problem.ql, python/ql/test/experimental/dataflow/typetracking_imports/options, python/ql/test/experimental/dataflow/typetracking_imports/pkg/alias_only_direct.py, python/ql/test/experimental/dataflow/typetracking_imports/pkg/alias_problem.py, python/ql/test/experimental/dataflow/typetracking_imports/pkg/alias_problem_fixed.py, python/ql/test/experimental/dataflow/typetracking_imports/pkg/alias_star.py, python/ql/test/experimental/dataflow/typetracking_imports/pkg/foo_def.py, python/ql/test/experimental/dataflow/typetracking_imports/pkg/other.py, python/ql/test/experimental/dataflow/typetracking_imports/pkg/problem_absolute_import.py, python/ql/test/experimental/dataflow/typetracking_imports/pkg/use.py, python/ql/test/experimental/dataflow/typetracking_imports/pkg/works_absolute_import.py, python/ql/test/experimental/dataflow/typetracking_imports/tracked.qlref
Apparently ordering is currently important when using `import *` :grimacing: We should fix that, but here is a test-case to reproduce :blush:
=> Python: Add testcase for import problem

ruby/ql/lib/codeql/ruby/frameworks/ActiveResource.qll
This was a conflict between the merge of https://github.com/github/codeql/pull/9974 and https://github.com/github/codeql/pull/10114
=> Ruby: Fix ActiveResource HTTP client request modeling

ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected, ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.ql, ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
In preparation for a PR that adds more tests.
=> Ruby: Convert data-flow test to use inline test expectations

javascript/ql/lib/semmle/javascript/security/dataflow/InsecureRandomnessCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-338/InsecureRandomness.expected, javascript/ql/test/query-tests/Security/CWE-338/tst.js
Gets a TP/TN for CVE-2021-23451
[Evaluation was every uneventful.](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/selRandom__nightly-old__CustomSuite/reports)
=> JS: add taint-step in js/insecure-randomness for selecting a random element

javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeHtmlConstructionQuery.qll, ql/ql/src/queries/bugs/MissingSanitizerGuardCase.ql
See https://github.com/github/codeql/pull/10381#discussion_r968650892.  
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/PR-10390-0-javascript/reports).
=> QL: add unmentioned guard class query

java/ql/src/Security/CWE/CWE-079/XSS.java, java/ql/src/Security/CWE/CWE-079/XSS.qhelp
According to @atorralba suggestion in issue #10395 , this PR updates the vulnerable XSS source code that works with the current query.
=> Updated vulnerable XSS.java version

docs/codeql/codeql-cli/about-codeql-workspaces.rst, docs/codeql/codeql-cli/publishing-and-using-codeql-packs.rst
Small docs update to include information abotu `registries` in `codeql-workspace.yml`.
=> Add information about the `registries` block in `codeql-workspace.yml`

java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt
We have a way to carry on here, so we may as well do so
=> Kotlin: Remove a throw statement

java/kotlin-extractor/build.py, java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/kotlin-extractor/src/main/kotlin/utils/TypeSubstitution.kt
We might need to refine this if different versions give different warnings, but for now I've tried the simple approach.
=> Kotlin: Compile with -Werror, and fix warnings

csharp/ql/integration-tests/all-platforms/dotnet_run/Program.cs, csharp/ql/integration-tests/all-platforms/dotnet_run/dotnet_run.csproj, csharp/ql/integration-tests/all-platforms/dotnet_run/test.py, csharp/tools/tracing-config.lua
https://github.com/github/codeql/pull/10464 follow-up.
=> C#: Prepend `-p:UseSharedCompilation=false` instead of append for `dotnet run`

go/ql/src/Diagnostics/SuccessfullyExtractedFiles.ql
Update the query identifier for `Diagnostics/SuccessfullyExtractedFiles.ql` to be consistent with other languages.  This allows us to consume the results of the successfully extracted files queries in a language-agnostic fashion.
=> Go: Use a consistent query identifier for successfully extracted files

javascript/ql/lib/semmle/javascript/Actions.qll
Added https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
=> Added job.getRunsOn

docs/codeql/codeql-overview/index.rst, docs/codeql/codeql-overview/system-requirements.rst, docs/codeql/index.html, docs/codeql/support/reusables/platforms.rst
Add a table of platform requirements (OS, OS version, CPU architecture).
Add a list of additional language-specific software requirements.
Preview:
=> Docs: Add CodeQL system requirements page

python/ql/lib/semmle/python/dataflow/new/internal/TypeTracker.qll, ruby/ql/lib/codeql/ruby/typetracking/TypeTracker.qll
https://github.com/github/codeql/pull/10375 follow-up.
Prevents reevaluation of flow summaries for Ruby, since those are now taken into account in `basicLoadStep` and `basicStoreStep`.
=> Ruby/Python: Cache more type tracking predicates

ruby/ql/src/queries/security/cwe-078/KernelOpen.ql, ruby/ql/test/query-tests/security/cwe-078/KernelOpen.expected
Just something I encountered while looking into the query.
=> RB: add a link to the source in the alert-message for `rb/kernel-open`

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
While evalauting https://github.com/github/codeql/blob/main/cpp/ql/test/query-tests/Likely%20Bugs/Format/NonConstantFormat/performance.c 😱.
Before (I canceled the evaluation midway):
```
Tuple counts for DataFlowUtil#47741e1f::simpleLocalFlowStep#2#ff/2@b18535ui after 41.2s:
...
7000      ~0%     {2} r52 = SCAN SsaInternals#7b362d2f::TDefOrUse#ff OUTPUT In.1, In.0
6000      ~3%     {2} r53 = JOIN r52 WITH SsaInternals#7b362d2f::useToNode#2#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1 'nodeTo'
5000      ~0%     {4} r54 = JOIN r53 WITH SsaInternals#7b362d2f::DefOrUseImpl::hasIndexInBlock#3#dispred#ffff ON FIRST 1 OUTPUT Rhs.3, Lhs.1 'nodeTo', Rhs.1, Rhs.2
637301500 ~1%     {7} r55 = JOIN r54 WITH Ssa#da392372::Make#SsaInternals#7b362d2f::SsaInput#::definesAt#3#dispred#ffff_1023#join_rhs ON FIRST 1 …
```
=> C++: Fix join in `SsaInternals`

cpp/ql/lib/semmle/code/cpp/security/FlowSources.qll, cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql, cpp/ql/test/query-tests/Security/CWE/CWE-078/SAMATE/ExecTainted/ExecTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-129/SAMATE/ImproperArrayIndexValidation/ImproperArrayIndexValidation.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextBufferWrite.expected
NOTE: This PR also contains the commits from https://github.com/github/codeql/pull/10839. Only the very last commit is new.
----------------------------
This is one of the queries that gets significantly prettier after the dataflow change 🎉.
=> C++: Prepare `cpp/command-line-injection` for IR-based use-use dataflow

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
Before
```
Evaluated relational algebra for predicate XSS#e59174e9::Shared::Sanitizer#class#f@6c9d334e with tuple counts:
0   ~0%    {1} r1 = JOIN ActionView#3462bac2::RailsHtmlEscaping#f WITH project#DataFlowPublic#e1781e31::CallNode::getArgument#1#dispred#fff#3 ON FIRST 1 OUTPUT Lhs.0
554860   ~0%    {2} r2 = JOIN SsaImpl#ff97b16a::Cached::getARead#1#ff_10#join_rhs WITH DataFlowPrivate#462ff392::Cached::TExprNode#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1
1   ~0%    {1} r3 = JOIN r2 WITH DataFlowPublic#e1781e31::BarrierGuard#BarrierGuards#2462899b::stringConstArrayInclusionCall#::getAMaybeGuardedCapturedDef#0#f ON FIRST 1 OUTPUT Lhs.1
1   ~0%    {1} r4 = r1 UNION r3
7   ~0%    {1} r5 = JOIN r2 WITH DataFlowPublic#e1781e31::BarrierGuard#BarrierGuards#2462899b::stringConstCompare#::getAMaybeGuarded …
```
=> Ruby: Fix bad join-order in `BarrierGuard::getABarrierNode`

java/kotlin-extractor/src/main/java/com/semmle/util/expansion/ExpansionEnvironment.java, java/kotlin-extractor/src/main/java/com/semmle/util/files/FileUtil.java, java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
=> Spelling kotlin

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/PrintIRLocalFlow.qll
This targets the use-use dataflow feature branch
=> C++: Spelling fixes and documentation clarification

.github/labeler.yml
Would just be nice for filtering PRs
=> Misc: Add automatic `DataFlow Library` label

swift/ql/src/queries/Security/CWE-089/SqlInjection.ql, swift/ql/src/queries/Security/CWE-311/CleartextStorageDatabase.ql, swift/ql/src/queries/Security/CWE-311/CleartextTransmission.ql, swift/ql/src/queries/Security/CWE-312/CleartextStoragePreferences.ql, swift/ql/src/queries/Security/CWE-321/HardcodedEncryptionKey.ql, swift/ql/src/queries/Security/CWE-757/InsecureTLS.ql, swift/ql/src/queries/Security/ECB-Encryption/ECBEncryption.ql
Simplify some more Swift query QL, particularly unnecessary variables.
=> Swift: Simplify some more QL

.github/workflows/atm-check-queries-run.yml, config/atm/ml-powered-queries-repo/add-note.js, config/atm/ml-powered-queries-repo/app.js, config/atm/ml-powered-queries-repo/index.js, config/atm/ml-powered-queries-repo/logger.js, config/atm/ml-powered-queries-repo/models/note.js, config/atm/ml-powered-queries-repo/models/user.js, config/atm/ml-powered-queries-repo/notes-api.js, config/atm/ml-powered-queries-repo/read-notes.js, config/atm/ml-powered-queries-repo/users-api.js
As discussed this clones a hard-coded open-source repo and builds a JavaScript database from the latest commit.
POC run [here](https://github.com/github/codeql/actions/runs/3369358110)
=> ATM: add PR check running boosted queries

.github/labeler.yml
Label PRs touching files matching `javascript/ql/experimental/adaptivethreatmodeling/**/*` with "ATM".
=> Add ATM to labeler

.github/workflows/compile-queries.yml
@aibaars It's me again, sorry.  
I had a typo in the previous PR.
=> fix typo in compile-queries workflow

.github/workflows/atm-check-queries-run.yml, .github/workflows/atm-check-query-suite.yml, CODEOWNERS
This PR makes some improvements to the ATM check queries workflow that ensures that we can run the ATM query pack on `main` using the latest release of the CodeQL CLI.
=> ATM: Miscellaneous improvements for the check queries workflow

cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.ql
This targets `main`, as this is independent of the use-use dataflow work.
=> C++: Small fixes for the dataflow tests

docs/codeql/codeql-language-guides/codeql-for-ruby.rst
@felicitymay could you have a quick look at this? Thanks!
=> Ruby: docs add missing entry

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql, cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected
This fixes some issues uncovered in https://github.com/github/codeql/pull/11254.
=> C++: Reduce path duplication

.github/workflows/swift.yml, CODEOWNERS
Also fixed the mention of the workflow file in `CODEOWNERS`.
=> Swift: fix path of generated C++ files artifact

csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/Semmle.Autobuild.CSharp.Tests.csproj, csharp/autobuilder/Semmle.Autobuild.CSharp/Semmle.Autobuild.CSharp.csproj, csharp/autobuilder/Semmle.Autobuild.Shared/Semmle.Autobuild.Shared.csproj, csharp/extractor/Semmle.Extraction.CIL/Semmle.Extraction.CIL.csproj, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Semmle.Extraction.CSharp.Standalone.csproj, csharp/extractor/Semmle.Extraction.CSharp/Entities/UserOperator.cs, csharp/extractor/Semmle.Extraction.CSharp/Semmle.Extraction.CSharp.csproj, csharp/extractor/Semmle.Extraction.Tests/Semmle.Extraction.Tests.csproj, csharp/extractor/Semmle.Extraction/Semmle.Extraction.csproj, csharp/extractor/Semmle.Util.Tests/Semmle.Util.Tests.csproj, csharp/ql/integration-tests/posix-only/dotnet_test/dotnet_test.csproj, csharp/ql/test/library-tests/csharp9/PrintAst.expected
Update all nuget packages to the latest version.
=> C#: Update all nuget packages

cpp/autobuilder/Semmle.Autobuild.Cpp.Tests/Semmle.Autobuild.Cpp.Tests.csproj, cpp/autobuilder/Semmle.Autobuild.Cpp/Semmle.Autobuild.Cpp.csproj, csharp/autobuilder/Semmle.Autobuild.CSharp/Semmle.Autobuild.CSharp.csproj, csharp/autobuilder/Semmle.Autobuild.Shared/Semmle.Autobuild.Shared.csproj, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Semmle.Extraction.CSharp.Standalone.csproj, csharp/extractor/Semmle.Extraction.CSharp/Semmle.Extraction.CSharp.csproj
https://github.com/github/codeql/pull/11266 follow-up.
=> C++: Update auto-builder nuget packages

cpp/ql/src/Likely Bugs/Conversion/CastArrayPointerArithmetic.ql
This predicate was generating very large `nodes` and `edges` relations on openjdk:
```ql
[2022-11-18 13:51:16] Evaluated non-recursive predicate nodes#query#fffffffff@e1f77atd in 575ms (size: 700124).
Evaluated relational algebra for predicate nodes#query#fffffffff@e1f77atd with tuple counts:
700124   ~1%    {4} r1 = JOIN DataFlowImpl#9021cc4c::PathNode::toString#0#dispred#ff WITH DataFlowImpl#9021cc4c::PathNode::toString#0#dispred#ff ON FIRST 1 OUTPUT "semmle.label", Lhs.0, Lhs.1, Rhs.1
700124   ~1%    {3} r2 = SCAN DataFlowImpl#9021cc4c::PathNode::toString#0#dispred#ff OUTPUT "semmle.label", In.0, In.1
0   ~0%    {3} r3 = r2 AND NOT project#DataFlowImpl#9021cc4c::PathNode::toString#0#dispred#ff(Lhs.1)
0   ~0%    {4} r4 = SCAN r3 OUTPUT "semmle.label", In.1, In.2, "(no string …
```
=> C++: Reduce size of `edges` and `nodes` in `cpp/upcast-array-pointer-arithmetic`

javascript/extractor/README.md
=> JS: update `javascript/extractor/README.md` to mention CodeQL instead of LGTM

ruby/downgrades/1199e154f5e9b3560297633c6ebb4dfe0b191ae4/upgrade.properties
Thanks @AlexDenisov for spotting this.
=> Ruby: fix upgrade script

shared/util/change-notes/2022-11-30-initial-version.md, shared/util/codeql/util/Boolean.qll, shared/util/codeql/util/Option.qll, shared/util/codeql/util/Unit.qll, shared/util/qlpack.yml
Adds `Unit`, `Boolean`, and `Option` to a shared `Util` qlpack.
=> Shared: Add Util qlpack.

swift/ql/test/library-tests/dataflow/taint/TaintInline.expected, swift/ql/test/library-tests/dataflow/taint/data.swift
More test cases are now working after #11185 🎉
=> Swift: Fix expectations in data.swift

cpp/ql/lib/semmle/code/cpp/models/implementations/Iterator.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/StdContainer.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/StdString.qll, cpp/ql/lib/semmle/code/cpp/models/interfaces/Iterator.qll
These are the additions necessary for my upcoming changes to iterator dataflow on the use-use dataflow feature branch.
Other than providing a few new classes and predicates, this shouldn't change any behavior.
=> C++: Change iterator models

java/ql/lib/semmle/code/java/dataflow/TypeFlow.qll
The new `QlBuiltins::EquivalenceRelation` should be available in a released codeql version, so this should be safe to merge now.
=> Java: Replace ad-hoc SCC reduction with union-find.

java/ql/lib/change-notes/2022-12-05-insecure-cookie-global-flow.md, java/ql/src/Security/CWE/CWE-614/InsecureCookie.ql, java/ql/test/query-tests/security/CWE-311/CWE-614/semmle/tests/Test.java
- Add support for interprocedural setting of cookie security
- Add test case
=> Java: Support interprocedural setting of cookie security

java/kotlin-extractor/src/main/kotlin/utils/Logger.kt
The message saying that the limit was exceeded is now given at the same severity as the original message.
=> Kotlin: Improve diagnostic limit message

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll
Also, removed unnecessary recursion in `SummarizedCallable::propagatesFlowExt`.
=> Ruby: Ensure `Node::{toString,getLocation}` are computed in data flow stage

java/ql/lib/semmle/code/java/frameworks/android/WebView.qll, java/ql/src/Security/CWE/CWE-200/AndroidWebViewSettingsFileAccess.qhelp, java/ql/src/Security/CWE/CWE-200/AndroidWebViewSettingsFileAccess.ql, java/ql/src/Security/CWE/CWE-200/AssetLoaderExample.java, java/ql/src/Security/CWE/CWE-200/WebViewFileAccessSafe.java, java/ql/src/Security/CWE/CWE-200/WebViewFileAccessUnsafe.java, java/ql/src/change-notes/2022-11-12-android-webview-file-access.md, java/ql/test/query-tests/security/CWE-200/semmle/tests/WebViewFileAccess.expected, java/ql/test/query-tests/security/CWE-200/semmle/tests/WebViewFileAccess.java, java/ql/test/query-tests/security/CWE-200/semmle/tests/WebViewFileAccess.qlref, java/ql/test/query-tests/security/CWE-200/semmle/tests/options
Added a query for detecting settings of Android WebViews which enable access to the file system.
=> Java: Query to detect Android Webview file access

python/ql/lib/change-notes/2022-12-03-new-stdlib-cmdi-sinks.md, python/ql/lib/semmle/python/frameworks/Stdlib.qll
Adding two missing Command Injection sinks identified by @Frycos in https://frycos.github.io/vulns4free/2022/12/02/rce-in-20-minutes.html
=> Added two new CMDi sinks for python's stdlib

javascript/ql/lib/semmle/javascript/frameworks/NoSQL.qll, javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/CodeInjectionCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/CommandInjectionCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/ReflectedXssCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/RequestForgeryCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/ServerSideUrlRedirectCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/TaintedPathCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeDeserializationCustomizations.qll, javascript/ql/test/library-tests/DataExtensions/Test.expected, javascript/ql/test/library-tests/DataExtensions/Test.ql, javascript/ql/test/library-tests/DataExtensions/connection.example.ts, javascript/ql/test/library-tests/DataExtensions/connection.model.yml, javascript/ql/test/library-tests/DataExtensions/execa.example.js, javascript/ql/test/library-tests/DataExtensions/execa.model.yml, javascript/ql/test/library-tests/DataExtensions/message.example.js, javascript/ql/test/library-tests/DataExtensions/message.model.yml, javascript/ql/test/qlpack.yml
Contains only the code parts of https://github.com/github/codeql/pull/11615, which can be merged beforehand.
=> JS: Add data extension sinks

cpp/ql/src/Security/CWE/CWE-022/TaintedPath.ql, cpp/ql/test/query-tests/Security/CWE/CWE-022/SAMATE/TaintedPath/TaintedPath.expected, cpp/ql/test/query-tests/Security/CWE/CWE-022/semmle/tests/TaintedPath.expected, cpp/ql/test/query-tests/Security/CWE/CWE-022/semmle/tests/test.c
~Note this currently includes 3be0b3e6c7a97415ee11028367966c6074e3f77b from https://github.com/github/codeql/pull/11677~
=> C++: Make `cpp/path-injection` work with use-use dataflow

csharp/extractor/Semmle.Extraction.CSharp/Entities/CommentBlock.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Compilations/Compilation.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/ArrayCreation.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Initializer.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/BinaryPattern.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/Pattern.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/PositionalPattern.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/PropertyPattern.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/RecursivePattern.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/RelationalPattern.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/UnaryPattern.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/PreprocessorDirectives/PragmaWarningDirective.cs
In this PR we just do some minor re-factors and the content should be semantics preserving.
=> C#: Re-factor and use `ForEach`.

ql/ql/src/codeql_ql/ast/internal/Type.qll, ql/ql/test/modules/ClassSig.qll, ql/ql/test/modules/test.expected, ql/ql/test/modules/test.ql
Fixes the following false positives:
* https://github.com/github/codeql/security/code-scanning/78600
* https://github.com/github/codeql/security/code-scanning/78601
=> QL: fix visibility of module parameters

ql/ql/src/queries/performance/MissingNomagic.ql
Seems we had a merge that caused a catastrophic join-order to appear unexpectedly.  
The QL-for-QL runs times out on `main`: https://github.com/github/codeql/actions/runs/3765954311/jobs/6401945839
=> QL: fix catastrophic join-order in `ql/cand-missing-nomagic`

docs/codeql/codeql-cli/about-codeql-packs.rst, docs/codeql/codeql-cli/creating-and-working-with-codeql-packs.rst, docs/codeql/codeql-cli/publishing-and-using-codeql-packs.rst
This pull request adds docs for CodeQL pack compatibility as part of CodeQL CLI 2.12.0 release. 
cc @hmakholm @felicitymay
=> Docs: CodeQL pack compatibility

python/ql/test/experimental/dataflow/TestUtil/DataflowQueryTest.qll, python/ql/test/query-tests/Security/CWE-022-PathInjection/DataflowQueryTest.expected, python/ql/test/query-tests/Security/CWE-022-PathInjection/DataflowQueryTest.ql, python/ql/test/query-tests/Security/CWE-022-PathInjection/flask_path_injection.py, python/ql/test/query-tests/Security/CWE-022-PathInjection/path_injection.py, python/ql/test/query-tests/Security/CWE-022-PathInjection/test.py, python/ql/test/query-tests/Security/CWE-022-PathInjection/test_chaining.py, python/ql/test/query-tests/Security/CWE-078-CommandInjection/DataflowQueryTest.expected, python/ql/test/query-tests/Security/CWE-078-CommandInjection/DataflowQueryTest.ql, python/ql/test/query-tests/Security/CWE-078-CommandInjection/command_injection.py
Similar to the consistency queries used in javascript, but based on the inline expectations test framework.
Annotations include relative line numbers, which may or may not be appropriate.
=> Python: Inline query tests

misc/scripts/generate-code-scanning-query-list.py
Also adds swift now that I was poking at this file anyway
=> Misc: Add `security-experimental` to `generate-code-scanning-query-list.py`

java/kotlin-extractor/src/main/java/com/semmle/extractor/java/OdasaOutput.java
Review will be easier with `?w=1`
=> Kotlin: Remove legacy trap-locking support

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplForRegExp.qll
The synced files check is failing on `main`.  
This should fix it.
=> PY: Sync a dataflow config

docs/codeql/ql-language-reference/ql-language-specification.rst
This PR updates the language spec in line with the [previous update](https://github.com/github/codeql/pull/12062) to the handbook.
=> shadowing in the QL language specification

docs/codeql/reusables/supported-platforms.rst
Rebase of https://github.com/github/codeql/commit/e8bf8fe7a4d82571118530d75966d4975845f37a
=> Add MacOS Ventura to supported platforms

java/ql/src/utils/stub-generator/Stubs.qll
Fixes cases in which the generated stubs don't compile due to name conflicts, by referring to all types that could possibly conflict by their fully qualified names.
=> Java: Stub generator: Use fully qualified names to avoid conflicts

javascript/ql/lib/semmle/javascript/internal/ConceptsShared.qll, javascript/ql/lib/semmle/javascript/security/internal/CryptoAlgorithmNames.qll, python/ql/lib/semmle/python/concepts/internal/CryptoAlgorithmNames.qll, python/ql/lib/semmle/python/internal/ConceptsShared.qll, ruby/ql/lib/codeql/ruby/internal/ConceptsShared.qll, ruby/ql/lib/codeql/ruby/security/internal/CryptoAlgorithmNames.qll, ruby/ql/test/library-tests/security/CryptoAlgorithms.expected
I have tried to add a few links to support the claim that these algorithms are strong/safe. It wasn't always super easy, so in some cases I have ended up just linking to the documentation of the `cryptography` Python package.
=> Python/Ruby/JS Crypto: Add a few algorithms + block modes

go/ql/lib/change-notes/2023-02-01--add-support-for-twirp-framework.md
Unsure how this ever passed CI.
=> Update Twirp change note to new style

python/ql/src/Security/CWE-022/examples/tainted_path.py, python/ql/src/Security/CWE-022/examples/tarslip_bad.py, python/ql/src/Security/CWE-022/examples/tarslip_good.py
Fixes problem highlighted in https://github.com/github/codeql/issues/12156
=> Python: Update a few examples so queries work on them

.github/workflows/ql-for-ql-build.yml, ql/Cargo.lock, ql/Cargo.toml, ql/autobuilder/src/main.rs, ql/buramu/Cargo.toml, ql/buramu/README.md, ql/buramu/src/main.rs, ql/buramu/tree-sitter-blame/Cargo.toml, ql/buramu/tree-sitter-blame/binding.gyp, ql/buramu/tree-sitter-blame/bindings/node/binding.cc, ql/buramu/tree-sitter-blame/bindings/node/index.js, ql/buramu/tree-sitter-blame/bindings/rust/build.rs, ql/buramu/tree-sitter-blame/bindings/rust/lib.rs, ql/buramu/tree-sitter-blame/dep.out, ql/buramu/tree-sitter-blame/grammar.js, ql/buramu/tree-sitter-blame/package.json, ql/buramu/tree-sitter-blame/src/grammar.json, ql/buramu/tree-sitter-blame/src/node-types.json, ql/buramu/tree-sitter-blame/src/parser.c, ql/buramu/tree-sitter-blame/src/tree_sitter/parser.h, ql/buramu/tree-sitter-blame/test.blame, ql/extractor/Cargo.toml, ql/extractor/src/main.rs, ql/generator/Cargo.toml, ql/generator/src/main.rs, ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/ql.dbscheme, ql/ql/src/queries/reports/OutdatedDeprecations.ql, ql/rust-toolchain.toml
Not actually hooked up to the workflow yet, as it remains to be seen how slow it is on the Actions runners.
=> QL: Add blame extractor

swift/ql/lib/codeql/swift/dataflow/ExternalFlow.qll, swift/ql/lib/codeql/swift/frameworks/StandardLibrary/FileManager.qll, swift/ql/test/library-tests/dataflow/flowsources/FlowSources.expected, swift/ql/test/library-tests/dataflow/flowsources/filemanager.swift
Taint source models for the `FileManager` class.
=> Swift: Taint sources for FileManager

python/ql/src/experimental/Security/CWE-022bis/UnsafeUnpack.ql
This recently merged external contribution was to be accepted with precision medium. I forgot to ensure this during review.
=> python: Lower precision as discussed

ql/Cargo.lock, ql/extractor/Cargo.toml, ql/extractor/src/main.rs, ql/generator/Cargo.toml, ql/ql/src/codeql_ql/StructuredLogs.qll, ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/ql.dbscheme
I had forgotten about this extra filtering that takes place in the extractor.
=> QL: Fix JSON extraction

ql/ql/src/codeql_ql/StructuredLogs.qll
Pushes it into an internal module and removes the abstract class.
cc: @MathiasVP
=> QL: Clean up structured logs module

ql/Cargo.lock, ql/autobuilder/src/main.rs, ql/extractor/Cargo.toml, ql/generator/Cargo.toml
Updates the grammar to allow trailing commas in objects and arrays.
Also bumps the file size limit to 10MB.
=> QL: Make the JSON parser a bit more robust

ql/ql/src/codeql_ql/StructuredLogs.qll
This PR does two things:
1. It replaces calls to `toInt` with `toFloat` where there's a chance of overflows.
2. It abstracts away the `-1` padding in the `counts` and `duplicationPercentages` arrays.
Once this PR is merged it's trivial to add the join order metric for non-recursive predicates to a ql-for-ql query 🎉.
=> QL: Handle large numbers and -1 padding

ql/ql/src/experimental/RA.qll, ql/ql/test/experimental/raparser.expected, ql/ql/test/experimental/raparser.ql
Here's a somewhat simple RA parser. I wanted to do a more comprehensive parser for every type of RA expression, but in the end this gives a basic framework and probably is sufficient for what we need.
=> RA parser first draft

ql/ql/src/queries/performance/LargeJoinOrder.ql
This PR removes the "bucket" terminology that I stole from DCA. In this case, a "bucket" is really a pipeline ordering, so there's no reason to use that terminology here.
=> QL: Join-order query fixes

ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/queries/bugs/SumWithoutDomain.ql, ql/ql/test/queries/bugs/SumWithoutDomain/SumWithoutDomain.expected, ql/ql/test/queries/bugs/SumWithoutDomain/SumWithoutDomain.qlref, ql/ql/test/queries/bugs/SumWithoutDomain/Test.qll
This produces 14 results on this repo, and they are mostly good results.
=> Query and tests for sum without domain

ruby/ql/lib/change-notes/2023-02-13-actioncontroller-filters.md, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/frameworks/Rails.qll, ruby/ql/lib/codeql/ruby/frameworks/actioncontroller/Filters.qll, ruby/ql/test/library-tests/frameworks/action_controller/ActionController.expected, ruby/ql/test/library-tests/frameworks/action_controller/Filters.expected, ruby/ql/test/library-tests/frameworks/action_controller/Filters.ql, ruby/ql/test/library-tests/frameworks/action_controller/filter_flow.rb, ruby/ql/test/library-tests/frameworks/action_controller/params-flow.expected, ruby/ql/test/query-tests/security/cwe-094/CodeInjection/CodeInjection.expected, ruby/ql/test/query-tests/security/cwe-094/CodeInjection/CodeInjection.rb
This is the second half of https://github.com/github/codeql/pull/11666. We add
jump steps between filters in order to model the flow of execution.
=> Ruby: flow steps for ActionController filters

cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql
The old sanitizers were less effective because fewer things are `InstructionNode`s now.
The first commit is a small cleanup that renames `fst` and `snd` to be more meaningful. The second commit contains the actual performance fix.
=> C++: Speedup `cpp/command-line-injection`

javascript/ql/lib/semmle/javascript/frameworks/jQuery.qll, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/XssThroughDom.expected, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/xss-through-dom.js
Receognizes the sink in CVE-2023-0949 
See backref for evaluation (in progress).
=> JS: add the html argument to the jQuery functions as an XSS sink

swift/extractor/mangler/SwiftMangler.cpp, swift/extractor/mangler/SwiftMangler.h, swift/extractor/translators/TypeTranslator.cpp, swift/extractor/translators/TypeTranslator.h
Just moves one thing around in preparation for more work.
=> Swift: introduce type mangling

swift/extractor/mangler/SwiftMangler.cpp, swift/extractor/mangler/SwiftMangler.h
Should go after https://github.com/github/codeql/pull/12388
=> Swift: mangle builtin types

cpp/ql/src/Security/CWE/CWE-732/DoNotCreateWorldWritable.c
Closes https://github.com/github/codeql/issues/12414
=> C++: fix example code for `FilePermissions.qll`

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll, cpp/ql/test/query-tests/Security/CWE/CWE-134/semmle/globalVars/UncontrolledFormatStringThroughGlobalVar.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextBufferWrite.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextFileWrite.expected, cpp/ql/test/query-tests/Security/CWE/CWE-319/UseOfHttp/UseOfHttp.expected, cpp/ql/test/query-tests/Security/CWE/CWE-497/semmle/tests/ExposedSystemData.expected
=> C++: Use `getAUse` in `getIRRepresentationOfIndirectOperand`

java/ql/test/library-tests/dataflow/callback-dispatch/A.java
Add a qltest for https://github.com/github/codeql/pull/12474
=> Java: Add a qltest demonstrating side-effect on a callback instance.

java/ql/lib/semmle/code/java/security/AndroidSensitiveCommunicationQuery.qll, java/ql/lib/semmle/code/java/security/FragmentInjectionQuery.qll, java/ql/lib/semmle/code/java/security/IntentUriPermissionManipulationQuery.qll, java/ql/lib/semmle/code/java/security/LogInjectionQuery.qll, java/ql/lib/semmle/code/java/security/RsaWithoutOaepQuery.qll, java/ql/lib/semmle/code/java/security/UnsafeContentUriResolutionQuery.qll, java/ql/src/Security/CWE/CWE-117/LogInjection.ql, java/ql/src/Security/CWE/CWE-266/IntentUriPermissionManipulation.ql, java/ql/src/Security/CWE/CWE-441/UnsafeContentUriResolution.ql, java/ql/src/Security/CWE/CWE-470/FragmentInjection.ql, java/ql/src/Security/CWE/CWE-780/RsaWithoutOaep.ql, java/ql/src/Security/CWE/CWE-927/SensitiveCommunication.ql, java/ql/test/query-tests/security/CWE-117/LogInjectionTest.ql, java/ql/test/query-tests/security/CWE-266/IntentUriPermissionManipulationTest.ql, java/ql/test/query-tests/security/CWE-441/UnsafeContentUriResolutionTest.ql, java/ql/test/query-tests/security/CWE-470/FragmentInjectionTest.ql, java/ql/test/query-tests/security/CWE-780/RsaWithoutOaepTest.ql, java/ql/test/query-tests/security/CWE-927/SensitiveCommunication.ql
This refactors 6 more queries.
=> Java: Refactor more dataflow queries to the new API (take 3)

javascript/ql/lib/semmle/javascript/security/dataflow/BrokenCryptoAlgorithmCustomizations.qll, javascript/ql/src/change-notes/2023-03-16-block-modes.md, javascript/ql/test/query-tests/Security/CWE-327/BrokenCryptoAlgorithm.expected, javascript/ql/test/query-tests/Security/CWE-327/tst.js
Fixes https://github.com/github/codeql/issues/12545
=> JS: Include weak block modes as sink in weak crypto algorithm

python/ql/src/Variables/UninitializedLocal.ql, python/ql/src/change-notes/2023-03-20-uninitialized-local.md, python/ql/test/query-tests/Variables/undefined/UninitializedLocal.expected, python/ql/test/query-tests/Variables/undefined/captured.py
Fixes https://github.com/github/codeql-python-team/issues/675
=> Python: Patch uninitialized local query

java/ql/lib/semmle/code/java/security/XxeLocalQuery.qll, java/ql/lib/semmle/code/java/security/XxeRemoteQuery.qll, java/ql/src/Security/CWE/CWE-022/TaintedPathLocal.ql, java/ql/src/Security/CWE/CWE-022/ZipSlip.ql, java/ql/src/Security/CWE/CWE-090/LdapInjection.ql, java/ql/src/Security/CWE/CWE-090/LdapInjectionLib.qll, java/ql/src/Security/CWE/CWE-094/InsecureBeanValidation.ql, java/ql/src/Security/CWE/CWE-134/ExternallyControlledFormatString.ql, java/ql/src/Security/CWE/CWE-134/ExternallyControlledFormatStringLocal.ql, java/ql/src/Security/CWE/CWE-190/ArithmeticTaintedLocal.ql, java/ql/src/Security/CWE/CWE-190/ArithmeticUncontrolled.ql, java/ql/src/Security/CWE/CWE-190/ArithmeticWithExtremeValues.ql, java/ql/src/Security/CWE/CWE-200/AndroidWebViewSettingsAllowsContentAccess.ql, java/ql/src/Security/CWE/CWE-297/UnsafeHostnameVerification.ql, java/ql/src/Security/CWE/CWE-601/UrlRedirect.ql, java/ql/src/Security/CWE/CWE-601/UrlRedirectLocal.ql, java/ql/src/Security/CWE/CWE-611/XXE.ql, java/ql/src/Security/CWE/CWE-611/XXELocal.ql, java/ql/src/Security/CWE/CWE-643/XPathInjection.ql, java/ql/src/Security/CWE/CWE-807/TaintedPermissionsCheck.ql
=> Java: Refactor more queries to the new DataFlow module API

java/ql/src/Security/CWE/CWE-078/ExecTaintedLocal.ql, java/ql/src/Security/CWE/CWE-079/XSSLocal.ql, java/ql/src/Security/CWE/CWE-089/SqlConcatenated.ql, java/ql/src/Security/CWE/CWE-089/SqlTaintedLocal.ql, java/ql/src/Security/CWE/CWE-129/ImproperValidationOfArrayConstruction.ql, java/ql/src/Security/CWE/CWE-129/ImproperValidationOfArrayConstructionCodeSpecified.ql, java/ql/src/Security/CWE/CWE-129/ImproperValidationOfArrayConstructionLocal.ql, java/ql/src/Security/CWE/CWE-129/ImproperValidationOfArrayIndex.ql, java/ql/src/Security/CWE/CWE-129/ImproperValidationOfArrayIndexCodeSpecified.ql, java/ql/src/Security/CWE/CWE-129/ImproperValidationOfArrayIndexLocal.ql, java/ql/src/Security/CWE/CWE-190/ArithmeticWithExtremeValues.ql, java/ql/src/Security/CWE/CWE-209/StackTraceExposure.ql, java/ql/src/Security/CWE/CWE-614/InsecureCookie.ql
=> Java: Refactor more queries to the new DataFlow module API (part 2)

java/ql/src/Security/CWE/CWE-190/ArithmeticTainted.ql, java/ql/src/Security/CWE/CWE-200/TempDirLocalInformationDisclosure.ql, swift/ql/src/diagnostics/SuccessfullyExtractedFiles.ql, swift/ql/test/query-tests/Diagnostics/SuccessfullyExtractedFiles.expected, swift/ql/test/query-tests/Diagnostics/SuccessfullyExtractedFiles.qlref, swift/ql/test/query-tests/Diagnostics/error.swift
Backport of https://github.com/github/codeql/pull/12567
=> Swift: add a query showing successfully extracted files

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlow.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking1/TaintTracking.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlow.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking1/TaintTracking.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking1/TaintTracking.qll, go/ql/lib/semmle/go/dataflow/internal/DataFlow.qll, go/ql/lib/semmle/go/dataflow/internal/tainttracking1/TaintTracking.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll, java/ql/lib/semmle/code/java/dataflow/internal/tainttracking1/TaintTracking.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlow.qll, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking1/TaintTracking.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlow.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/tainttracking1/TaintTracking.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlow.qll, swift/ql/lib/codeql/swift/dataflow/internal/tainttracking1/TaintTracking.qll
Fix for review comment on https://github.com/github/codeql/pull/12645
=> Dataflow: Minor qldoc fix

ruby/ql/src/change-notes/2023-03-24-sensitive-get-query-problem.md, ruby/ql/src/queries/security/cwe-598/SensitiveGetQuery.ql, ruby/ql/test/query-tests/security/cwe-598/SensitiveGetQuery.expected
Conflict resolved in `.expected` output.
=> Merge `rc/3.9` back into `main`

java/ql/src/Security/CWE/CWE-522/InsecureLdapAuth.ql
Small fix of a tag that I missed during review.
=> Java: Fix InsecureLdapAuth tags

java/ql/lib/change-notes/2023-03-29-rangeanalysis-add.md, java/ql/lib/semmle/code/java/dataflow/RangeAnalysis.qll, java/ql/test/library-tests/dataflow/range-analysis/RangeAnalysis.expected
Mirrors https://github.com/github/codeql/pull/12673.
=> Java: Support double-recursive range analysis bounds for addition.

cpp/ql/lib/experimental/semmle/code/cpp/semantic/analysis/RangeAnalysisStage.qll, cpp/ql/test/library-tests/ir/range-analysis/SimpleRangeAnalysis_tests.cpp
Does what it says on the tin. Other than the annoying number of cases in `boundedMulOperandCand` this is mostly straightforward.
=> C++: IR-based range analysis of multiplication

.github/workflows/ruby-qltest.yml
Similar to [C#](https://github.com/github/codeql/blob/0acca2ba76a2973d08545f4ba84524045afba4d5/.github/workflows/csharp-qltest.yml#L7).
=> Run Ruby QL tests on changes to `shared`

docs/codeql/reusables/supported-versions-compilers.rst
=> Ruby: update supported version to 3.2

csharp/ql/test/library-tests/dataflow/operators/Operator.cs, csharp/ql/test/library-tests/dataflow/operators/operatorFlow.expected
=> C#: Data flow tests for virtual and abstract operators.

cpp/ql/src/Security/CWE/CWE-190/ArithmeticTainted.ql, cpp/ql/src/change-notes/2023-04-06-arith-tainted-assign-operations.md, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/ArithmeticTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/IntegerOverflowTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/test2.cpp
Fixes https://github.com/github/codeql/issues/12770
=> C++: Fix FN in `cpp/tainted-arithmetic`

java/ql/lib/change-notes/2023-03-31-new-models-tr2284.md, java/ql/lib/ext/java.io.model.yml, java/ql/lib/ext/java.lang.module.model.yml, java/ql/lib/ext/java.nio.file.spi.model.yml, java/ql/lib/ext/org.apache.commons.io.model.yml
This PR updates the MaD declarations after a recent triage session.
TR 2284
=> Java: Update MaD Declarations after Triage

javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tst.js
Followup to https://github.com/github/codeql/pull/12787 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-12802-b19576__nightly-old__code-scanning/reports).
=> JS: add browser history as XSS sink

cpp/ql/examples/queries.xml, cpp/ql/src/queries.xml, cpp/ql/test/queries.xml, csharp/ql/examples/queries.xml, csharp/ql/src/queries.xml, csharp/ql/test/queries.xml, go/ql/examples/queries.xml, go/ql/src/queries.xml, go/ql/test/queries.xml, java/ql/examples/queries.xml, java/ql/src/queries.xml, java/ql/test/queries.xml, javascript/ql/examples/queries.xml, javascript/ql/experimental/adaptivethreatmodeling/src/queries.xml, javascript/ql/src/queries.xml, javascript/ql/test/queries.xml, python/ql/examples/queries.xml, python/ql/src/queries.xml, python/ql/test/queries.xml, ruby/ql/examples/queries.xml, ruby/ql/src/queries.xml, swift/ql/src/queries.xml
These files should no longer be needed, so removing.
=> Remove all `queries.xml` files

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlow.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlow.qll, go/ql/lib/semmle/go/dataflow/internal/DataFlow.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlow.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlow.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlow.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlow.qll
In this PR we introduce a `MergPathGraph3` parameterised module as this is a nice to have in at least one place in the C# code.
=> Dataflow: Introduce param module for merging three path graphs.

javascript/ql/lib/semmle/javascript/ApiGraphs.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeDeserializationCustomizations.qll, javascript/ql/src/change-notes/2023-04-26-unsafe-yaml-deserialization.md, javascript/ql/test/query-tests/Security/CWE-502/Consistency.ql, javascript/ql/test/query-tests/Security/CWE-502/UnsafeDeserialization.expected, javascript/ql/test/query-tests/Security/CWE-502/tst.js
[Evaluation](https://github.com/github/codeql-dca-main/issues/12614) was quiet
=> JS: Update model of js-yaml

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplCommon.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, go/ql/lib/semmle/go/dataflow/internal/DataFlowImplCommon.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplCommon.qll, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/src/utils/modelgenerator/internal/CaptureModelsSpecific.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplCommon.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplCommon.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplCommon.qll
A small change in preparation for turning the data flow library into a qlpack.
=> Dataflow: Replace "extends Node" with "instanceof Node".

javascript/ql/lib/semmle/javascript/ES2015Modules.qll, javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll
Make all implicit this call receivers explicit to align with internal style guidelines.
=> JS: Make implicit this receivers explicit

csharp/ql/lib/semmle/code/csharp/dataflow/Bound.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/rangeanalysis/Sign.qll, java/ql/lib/semmle/code/java/dataflow/Bound.qll, java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/Sign.qll
Make implicit this call receivers explicit to align with internal style guidelines.
=> Java, C#: Make implicit this receivers explicit

cpp/ql/src/experimental/Likely Bugs/OverrunWriteProductFlow.ql
Small addition to https://github.com/github/codeql/pull/13041
=> C++: Add QLDoc to `getOverflow`

java/ql/src/Telemetry/ExternalApi.qll
Previously `jarContainer()` would always report "rt.jar" on top of any other result.
Thanks goes to @starcke for reporting this.
=> Java: Fix ExternalApi.jarContainer().

java/kotlin-extractor/src/main/java/com/semmle/extractor/java/OdasaOutput.java
This is no longer supported, and has never been used with Kotlin.
=> Kotlin: Remove ODASA_JAVA_LAYOUT support

go/ql/lib/semmle/go/security/SensitiveActions.qll, go/ql/src/experimental/CWE-203/Timing.qhelp, go/ql/src/experimental/CWE-203/Timing.ql, go/ql/src/experimental/CWE-203/timingBad.go, go/ql/src/experimental/CWE-203/timingGood.go, go/ql/test/experimental/CWE-203/Timing.expected, go/ql/test/experimental/CWE-203/Timing.qlref, go/ql/test/experimental/CWE-203/timing.go
detects [CVE-2022-24912](https://nvd.nist.gov/vuln/detail/CVE-2022-24912).
=> Go : Add query to detect potential timing attacks

csharp/ql/consistency-queries/DataFlowConsistency.ql, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/experimental/ir/offbyone/CONSISTENCY/DataFlowConsistency.expected, csharp/ql/test/library-tests/controlflow/graph/CONSISTENCY/DataFlowConsistency.expected, csharp/ql/test/library-tests/controlflow/guards/CONSISTENCY/DataFlowConsistency.expected, csharp/ql/test/library-tests/controlflow/splits/CONSISTENCY/DataFlowConsistency.expected, csharp/ql/test/library-tests/dataflow/defuse/CONSISTENCY/DataFlowConsistency.expected, csharp/ql/test/library-tests/dataflow/global/CONSISTENCY/DataFlowConsistency.expected, csharp/ql/test/library-tests/dataflow/ssa/CONSISTENCY/DataFlowConsistency.expected, csharp/ql/test/query-tests/Nullness/CONSISTENCY/DataFlowConsistency.expected, csharp/ql/test/query-tests/Security Features/CWE-022/ZipSlip/CONSISTENCY/DataFlowConsistency.expected
https://github.com/github/codeql/pull/12959 follow-up.
=> C#: Remove local identity flow steps

swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPublic.qll
Mirror changes made in the Swift tutorial docs [here](https://github.com/github/codeql/pull/12940#discussion_r1190171944) and [here](https://github.com/github/codeql/pull/12940#discussion_r1189983715) into our actual libraries.
=> Swift: Mirror changes made in the tutorial docs.

cpp/ql/lib/semmle/code/cpp/Type.qll
Fixes https://github.com/github/codeql/issues/13214.
=> C++: Update documentation for `TypeMention`

swift/extractor/translators/DeclTranslator.cpp, swift/integration-tests/BUILD.bazel, swift/integration-tests/diagnostics_test_utils.py, swift/logging/Formatters.h, swift/logging/SwiftAssert.h, swift/logging/SwiftDiagnostics.h, swift/logging/tests/assertion-diagnostics/AssertFalse.cpp, swift/logging/tests/assertion-diagnostics/BUILD.bazel, swift/logging/tests/assertion-diagnostics/diagnostics.expected, swift/logging/tests/assertion-diagnostics/test.py
Closes https://github.com/github/codeql-team/issues/1992.
=> Swift: Emit diagnostics on assertion/expectation violations.

shared/util/codeql/util/test/InlineExpectationsTest.qll
Without these some Python tests are broken. I verified locally that this fixes them.
Unfortunately, this requires renaming the related classes in the parameterised modules, otherwise once a test is rewritten `import MakeTest<Test>` will cause naming conflicts.
=> Add forgotten classes related to the legacy `InlineExpectationsTest`class

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll
In preparation for https://github.com/github/codeql/pull/12964.
=> Ruby: Include both `self` parameters and SSA definitions in call graph construction

ruby/ql/lib/change-notes/2023-05-06-pg.md, ruby/ql/lib/codeql/ruby/Frameworks.qll, ruby/ql/lib/codeql/ruby/frameworks/Pg.qll, ruby/ql/test/library-tests/dataflow/local/TaintStep.expected, ruby/ql/test/query-tests/security/cwe-089/PgInjection.rb, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected
This pull request adds Pg library Sinks for SQL injection.
Looking forward to your suggestions.
=> Ruby: Add SQL Injection Sinks

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll, go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImpl.qll, go/ql/lib/semmle/go/dataflow/internal/FlowSummaryImplSpecific.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll, swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImpl.qll, swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImplSpecific.qll
This PR is a pre-requisite for https://github.com/github/codeql/pull/13147 to avoid non monotonic recursion (basically we need to eliminate the negation in getComponent).
=> C#: Re-factor getComponent.

shared/typetracking/codeql/typetracking/TypeTracking.qll
https://github.com/github/codeql/pull/12979 follow-up.
=> Type tracking: Use `noopt`+`inline_late` in `TypeBackTracker::[small]step`

python/ql/test/2/query-tests/Imports/syntax_error/SyntaxError.expected, python/ql/test/3/query-tests/Imports/syntax_error/SyntaxError.expected
See the backlinked internal PR.
=> Python: Update expected output for syntax error queries

java/ql/lib/semmle/code/java/security/LogInjection.qll
=> Java: Add more negation context to reduce string ops and improve perf.

ruby/ql/lib/codeql/ruby/security/XSS.qll
=> Ruby: restrict ORM tracking to calls

javascript/ql/lib/semmle/javascript/frameworks/Vuex.qll
=> JS: Restrict length of state path in vuex model

java/kotlin-extractor/src/main/java/com/semmle/util/files/FileUtil.java
We were getting warnings about it being deprecated, and it was all dead code anyway.
=> Kotlin: Remove use of AccessControlException

docs/codeql/ql-language-reference/ql-language-specification.rst
See https://github.com/github/codeql/pull/13443#pullrequestreview-1487845209
=> mention how instantiation-nested predicates are treated in stratification and evaluation

docs/codeql/ql-language-reference/ql-language-specification.rst
Cleanup of a few small inaccuracies in the QL language spec "Call with results" section.
=> Polish QL language spec "Call with results" section

swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll, swift/ql/src/change-notes/2023-06-22-hide-summarized-nodes.md, swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected, swift/ql/test/query-tests/Security/CWE-079/UnsafeWebViewFetch.expected, swift/ql/test/query-tests/Security/CWE-089/SqlInjection.expected, swift/ql/test/query-tests/Security/CWE-094/UnsafeJsEval.expected, swift/ql/test/query-tests/Security/CWE-1204/StaticInitializationVector.expected, swift/ql/test/query-tests/Security/CWE-134/UncontrolledFormatString.expected, swift/ql/test/query-tests/Security/CWE-311/CleartextTransmission.expected, swift/ql/test/query-tests/Security/CWE-321/HardcodedEncryptionKey.expected, swift/ql/test/query-tests/Security/CWE-760/ConstantSalt.expected
As suggested by Tom here: https://github.com/github/codeql/pull/13452#discussion_r1238173308
=> Swift: Hide summarized nodes from path graphs

java/ql/lib/change-notes/2023-06-22-url-tostring-model.md, java/ql/lib/ext/java.net.model.yml
This adds coverage for CVE-2023-35149.
=> Java: Add URL.toString summary

misc/legacy-support/cpp/qlpack.yml, misc/legacy-support/csharp/qlpack.yml, misc/legacy-support/java/qlpack.yml, misc/legacy-support/javascript/qlpack.yml, misc/legacy-support/python/qlpack.yml, misc/suite-helpers/qlpack.yml
This PR enables implicit this warnings for remaining Misc QL packs.
=> Misc: Enable implicit this warnings for remaining packs

docs/codeql/ql-language-reference/types.rst
- This is part of https://github.com/github/codeql-core/issues/3675.
- See als https://github.com/github/codeql/pull/13633
=> document final extensions in the language reference

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
This reverts commit a50d804ad710e0e314afc823ae2c10f334be8655 (#13600).
On second thoughts, let's look into this some more before committing to this.
=> Revert "Kotlin: Remove a use of ObsoleteDescriptorBasedAPI"

cpp/ql/lib/change-notes/2023-07-07-irguards-compares-pointers.md, cpp/ql/lib/semmle/code/cpp/controlflow/IRGuards.qll, cpp/ql/test/library-tests/controlflow/guards-ir/test.c, cpp/ql/test/library-tests/controlflow/guards-ir/tests.expected
It seems this was something supported by the AST Guards library.
=> C++: Support pointer addition and subtraction in the IRGuards library

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ContentDataFlow.qll, csharp/ql/src/utils/modelgenerator/internal/CaptureModels.qll, java/ql/lib/semmle/code/java/security/ArbitraryApkInstallationQuery.qll, java/ql/lib/semmle/code/java/security/ImplicitPendingIntentsQuery.qll, java/ql/src/Security/CWE/CWE-200/AndroidWebViewSettingsAllowsContentAccess.ql, java/ql/src/utils/modelgenerator/internal/CaptureModels.qll, ruby/ql/lib/codeql/ruby/security/InsecureDownloadQuery.qll
Similar to https://github.com/github/codeql/pull/13732
=> C#/Java/Ruby: Remove superfluous module members.

java/ql/src/Telemetry/AutomodelApplicationModeExtractCandidates.ql
Uses the same trick as for the negative examples, this time with a limit of 9 candidates for each endpoint signature.
On `OpenIdentityPlatform/OpenAM`, this resulted in a reduction in results from ~93k to ~14k. (Further reducing the number of candidates per endpoint to 7 would only reduce the number of results by roughly 700).
As this duplicates some of the logic used in another query, it may be worthwhile to consider extracting this into a shared parameterized module.
cc: @charisk, @jhelie
=> Java: Limit the number of samples extracted in application mode

docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp-new.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-csharp.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-java.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-python.rst, docs/codeql/codeql-language-guides/analyzing-data-flow-in-ruby.rst, docs/codeql/codeql-language-guides/codeql-library-for-go.rst, docs/codeql/codeql-language-guides/using-api-graphs-in-ruby.rst, docs/codeql/ql-training/cpp/global-data-flow-cpp.rst, docs/codeql/ql-training/java/apache-struts-java.rst, docs/codeql/ql-training/java/global-data-flow-java.rst, docs/codeql/ql-training/query-examples/cpp/global-data-flow-cpp-1.ql, docs/codeql/ql-training/query-examples/java/global-data-flow-java-1.ql, docs/codeql/ql-training/slide-snippets/global-data-flow.rst, docs/codeql/ql-training/slide-snippets/path-queries.rst, docs/codeql/writing-codeql-queries/creating-path-queries.rst, docs/codeql/writing-codeql-queries/debugging-data-flow-queries-using-partial-flow.rst, docs/ql-design-patterns.md
This updates the pieces of documentation that I could find to the new data flow API.
I identified the places that needed updates, by grepping for the following list of words:
```
::Configuration
isSanitizer
AdditionalTaintStep
hasFlow
isBarrierGuard
DataFlow::PathNode
DataFlow::PathGraph
```
=> Docs: Update data flow documentation to the new API.

swift/extractor/invocation/SwiftDiagnosticsConsumer.cpp, swift/extractor/invocation/SwiftDiagnosticsConsumer.h, swift/extractor/main.cpp
Based on https://github.com/github/codeql/pull/12760 (which was reverted in https://github.com/github/codeql/pull/12908).
=> Swift: Route compiler diagnostics through our log.

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll
I've been meaning to do this cleanup in a while, and with a small upcoming change to SSA that I'm doing to support an update to our frontend I figured I might as well get this merged first.
These changes shouldn't have any external effects 🤞.
=> C++: Small cleanup of `SsaInternals`

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
This happens because `useDeclarationParent` can return `null`.
Previously, this was hidden by the `return "@\"...{$parentId}..."` in `getFunctionLabel`.
Now we call `useDeclarationParent` ourselves earlier, so we only have to return a nullable value if we aren't passed in a parent ID.
=> Kotlin: useFunction might return null

python/ql/lib/change-notes/2023-08-08-relax-module-resolution.md, python/ql/lib/semmle/python/Module.qll, python/ql/test/experimental/library-tests/CallGraph-implicit-init/example.py
Do not require modules to reside in a package
This inspired by https://github.slack.com/archives/CPGHLR8DD/p1690210556038379
=> Python: Relax module resolution

python/ql/test/experimental/dataflow/TestUtil/DataflowQueryTest.qll, python/ql/test/experimental/query-tests/Security/CWE-022-UnsafeUnpacking/DataflowQueryTest.ql, python/ql/test/query-tests/Security/CWE-022-PathInjection/DataflowQueryTest.ql, python/ql/test/query-tests/Security/CWE-078-CommandInjection/DataflowQueryTest.ql, python/ql/test/query-tests/Security/CWE-078-UnsafeShellCommandConstruction/DataflowQueryTest.ql
Here in a separate PR to make it easier to get merged, since both me and @yoff needs this (@yoff wrote it originally)
=> Python: Adopt tests to new `DataflowQueryTest`

cpp/ql/src/Likely Bugs/Likely Typos/CompareWhereAssignMeant.ql, cpp/ql/src/change-notes/2023-08-25-compare-where-assign-meant.md, cpp/ql/test/query-tests/Likely Bugs/Likely Typos/CompareWhereAssignMeant/CompareWhereAssignMeant.expected, cpp/ql/test/query-tests/Likely Bugs/Likely Typos/CompareWhereAssignMeant/test.cpp
Fixes https://github.com/github/codeql/issues/14054
=> C++: Fix FP in `cpp/compare-where-assign-meant`

python/ql/lib/semmle/python/frameworks/Flask.qll, python/ql/src/change-notes/2023-08-29-fixed-jsonify-xss-fp.md, python/ql/test/library-tests/frameworks/flask/response_test.py, python/ql/test/query-tests/Security/CWE-079-ReflectedXss/ReflectedXss.expected, python/ql/test/query-tests/Security/CWE-079-ReflectedXss/reflected_xss.py
A more general implementation of what https://github.com/github/codeql/pull/14080 wanted to achieve.
=> Python: Remove XSS FP from use of `flask.jsonify`

cpp/autobuilder/Semmle.Autobuild.Cpp.Tests/Semmle.Autobuild.Cpp.Tests.csproj, cpp/autobuilder/Semmle.Autobuild.Cpp/Semmle.Autobuild.Cpp.csproj, csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/Semmle.Autobuild.CSharp.Tests.csproj, csharp/autobuilder/Semmle.Autobuild.CSharp/Semmle.Autobuild.CSharp.csproj, csharp/autobuilder/Semmle.Autobuild.Shared/Semmle.Autobuild.Shared.csproj, csharp/extractor/Semmle.Extraction.CIL/Semmle.Extraction.CIL.csproj, csharp/extractor/Semmle.Extraction.CSharp.Standalone/Semmle.Extraction.CSharp.Standalone.csproj, csharp/extractor/Semmle.Extraction.CSharp/Semmle.Extraction.CSharp.csproj, csharp/extractor/Semmle.Extraction.Tests/Semmle.Extraction.Tests.csproj, csharp/extractor/Semmle.Extraction/Semmle.Extraction.csproj, csharp/extractor/Semmle.Util.Tests/Semmle.Util.Tests.csproj, csharp/extractor/Semmle.Util/Semmle.Util.csproj, csharp/ql/integration-tests/posix-only/dotnet_test/dotnet_test.csproj, csharp/ql/integration-tests/posix-only/dotnet_test_mstest/dotnet_test_mstest.csproj
=> Revert "C#: Bump all dependencies"

python/ql/lib/semmle/python/security/dataflow/SqlInjectionCustomizations.qll
Are there any frameworks we do _not_ want here?
=> Python: import all frameworks in SQL-injection query

docs/codeql/ql-language-reference/annotations.rst, docs/codeql/ql-language-reference/expressions.rst, docs/prepare-db-upgrade.md, docs/qldoc-style-guide.md
=> Docs: fix minor typos

csharp/ql/src/Telemetry/ExternalApi.qll
Minor improvements related to the discussion on: https://github.com/github/codeql/pull/14200
=> C#: Minor improvements to the ExternalApi implementation.

java/ql/automodel/src/qlpack.yml
The pack was just updated to a newer version.
=> Release automodel queries version 0.0.3

python/ql/lib/change-notes/2023-09-29-django-restframework-improvements.md, python/ql/lib/semmle/python/frameworks/RestFramework.qll, python/ql/test/library-tests/frameworks/rest_framework/ConceptsTest.expected, python/ql/test/library-tests/frameworks/rest_framework/ConceptsTest.ql, python/ql/test/library-tests/frameworks/rest_framework/options, python/ql/test/library-tests/frameworks/rest_framework/taint_test.py, python/ql/test/library-tests/frameworks/rest_framework/testapp/urls.py, python/ql/test/library-tests/frameworks/rest_framework/testapp/views.py
Add some of the missing APIs for Django RestFramework
https://github.com/encode/django-rest-framework/blob/605cc4f7367f58002056453d9befd3c1918f6a38/rest_framework/viewsets.py#L238
=> Python - Add support for RestFramework ModelViewSet functions

cpp/ql/src/Critical/DoubleFree.ql, cpp/ql/src/Critical/UseAfterFree.ql, cpp/ql/src/change-notes/2023-10-03-double-free.md, cpp/ql/src/change-notes/2023-10-03-use-after-free.md
=> C++: Promote `cpp/double-free` and `cpp/use-after-free` to Code Scanning

.github/dependabot.yml
Adds a Dependabot configuration for Go extractor dependencies.
=> Add dependabot configuration for Go dependencies

javascript/ql/src/Security/CWE-400/RemotePropertyInjection.expected
Found here: https://github.com/github/codeql/pull/13554#pullrequestreview-1668731857
=> JS: delete an .expected file outside the test directories

swift/ql/test/library-tests/dataflow/taint/core/LocalTaint.expected, swift/ql/test/library-tests/dataflow/taint/core/simple.swift
Add test cases for data flow through global, class member, and static class member initialization.  At present we don't model these flows.
=> Swift: Add data flow tests for member initialization.

swift/README.md
Turned the warning at the top into a warning box.
Made the section headers consistent.
I was going to add a new section, but I realized it belongs somewhere else.  :)
=> Swift: Update README.md

python/ql/lib/change-notes/2023-09-29-allow-namespace-packages.md, python/ql/lib/semmle/python/Module.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPublic.qll, python/ql/test/2/library-tests/six/pointsto.expected, python/ql/test/3/library-tests/modules/entry_point/modules.expected, python/ql/test/3/library-tests/six/pointsto.expected, python/ql/test/experimental/library-tests/CallGraph-implicit-init/example.py, python/ql/test/experimental/library-tests/CallGraph-implicit-init/foo/bar/a.py, python/ql/test/experimental/library-tests/CallGraph-implicit-init/foo/foo.py, python/ql/test/experimental/library-tests/CallGraph-implicit-init/foo_explicit/bar/a.py, python/ql/test/experimental/library-tests/CallGraph-implicit-init/foo_explicit/foo_explicit.py, python/ql/test/experimental/library-tests/CallGraph-implicit-init/not_root/baz/bar/a.py, python/ql/test/experimental/library-tests/CallGraph-implicit-init/not_root/baz/foo.py, python/ql/test/experimental/library-tests/CallGraph-implicit-init/options, python/ql/test/library-tests/PointsTo/regressions/wrong/module-imports/conflict-stdlib/LocalModuleWithRef.expected, python/ql/test/library-tests/PointsTo/regressions/wrong/module-imports/conflict-stdlib/LocalModules.expected, python/ql/test/library-tests/PointsTo/regressions/wrong/module-imports/conflict-stdlib/ModuleWithLocalRef.expected
This recovers alerts in https://github.com/github/field-security-codeql/issues/92 and in https://github.com/github/field-security-codeql/issues/100.
Please review if the test changes are acceptable.
=> Python: Allow namespace packages

java/ql/test/library-tests/dataflow/capture/test.ql, java/ql/test/library-tests/dataflow/partial/test.expected, java/ql/test/library-tests/dataflow/partial/test.ql, java/ql/test/library-tests/dataflow/partial/testRev.expected, java/ql/test/library-tests/dataflow/partial/testRev.ql, java/ql/test/library-tests/dataflow/state/test.ql
Tests updates following https://github.com/github/codeql/pull/14599
=> Java: Update tests to new partial flow api

shared/dataflow/change-notes/2023-10-27-partialflow-api.md
Change note for https://github.com/github/codeql/pull/14599
=> Dataflow: Add change note for partial flow api change.

shared/dataflow/codeql/dataflow/DataFlow.qll
This improves the documentation on the expectations from the data flow library to the given type system.
=> Dataflow: Improve qldoc on the type system.

java/kotlin-extractor/src/main/kotlin/ExternalDeclExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt, java/ql/integration-tests/all-platforms/kotlin/logs/index_logs.py
Knowing when we are writing what can be useful in diagnosing bugs and performance.
=> Kotlin: Log when we start and finish writing to TRAP files

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-193/array-access/ArrayAccessProductFlow.expected, cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected, cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-119/SAMATE/OverrunWriteProductFlow.expected, cpp/ql/test/query-tests/Security/CWE/CWE-611/XXE.expected
DCA looks good 🎉
@jketema do you mind 👀'ing this as the team's other expert on "dataflow node IPA sharing"? 😂
=> C++: Share IPA numbering for indirect nodes

cpp/ql/test/library-tests/ir/range-analysis/SimpleRangeAnalysis_tests.cpp
This add these cases extracted from real programs.
=> CPP: Add some range analysis cases

javascript/ql/lib/semmle/javascript/frameworks/Express.qll, javascript/ql/test/library-tests/frameworks/Express/src/express.js, javascript/ql/test/library-tests/frameworks/Express/tests.expected
Fixes https://github.com/github/codeql/issues/9760
=> Javascript: add `req.path` as remote flow source

cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticCFG.qll, cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticExprSpecific.qll, cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticGuard.qll, cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/SemanticSSA.qll, cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/RangeAnalysisImpl.qll, cpp/ql/lib/semmle/code/cpp/rangeanalysis/new/internal/semantic/analysis/SignAnalysisCommon.qll, java/ql/lib/semmle/code/java/dataflow/RangeAnalysis.qll, java/ql/lib/semmle/code/java/dataflow/RangeUtils.qll, shared/rangeanalysis/codeql/rangeanalysis/ModulusAnalysis.qll, shared/rangeanalysis/codeql/rangeanalysis/RangeAnalysis.qll, shared/rangeanalysis/codeql/rangeanalysis/internal/RangeUtils.qll
I don't expect this refactor to have any semantic impact.
=> Java/C++/RangeAnalysis: Move a couple of utility predicates to shared qlpack

swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll, swift/ql/test/extractor-tests/generated/expr/SingleValueStmtExpr/CONSISTENCY/CfgConsistency.expected, swift/ql/test/library-tests/dataflow/flowsources/CONSISTENCY/CfgConsistency.expected
Heavily inspired by the similar code around 😅
=> Swlft: fix CFG for SingleValueStmtExpr

swift/downgrades/04ef9ecaa9e06a587f252f147462861e3d32846a/downgrade.ql, swift/downgrades/04ef9ecaa9e06a587f252f147462861e3d32846a/upgrade.properties
Followup for https://github.com/github/codeql/pull/14745
=> Swift: update wordings in a downgrade script

ruby/ql/lib/codeql/ruby/dataflow/SSA.qll, ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected, ruby/ql/test/library-tests/dataflow/local/TaintStep.expected, ruby/ql/test/library-tests/variables/ssa.expected
=> Ruby: Include name of variable in `UninitializedDefinition.toString`

misc/bazel/cmake/cmake.bzl
Sorry, forgot this in https://github.com/github/codeql/pull/14805
=> Bazel/CMake: small compatibility fix

csharp/ql/integration-tests/all-platforms/dotnet_pack/test.py, csharp/ql/integration-tests/posix-only/dotnet_test_mstest/dotnet_test_mstest.csproj
Cherry-pick fixes onto the release branch.
=> C# fix integration tests

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternalsCommon.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/ssa0/SsaInternals.qll, csharp/ql/lib/semmle/code/cil/internal/SsaImpl.qll, csharp/ql/lib/semmle/code/csharp/controlflow/internal/PreSsa.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/BaseSSA.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll, shared/dataflow/codeql/dataflow/VariableCapture.qll, shared/ssa/codeql/ssa/Ssa.qll, shared/ssa/qlpack.yml, swift/ql/lib/codeql/swift/dataflow/Ssa.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll
I also had to update the variable capture library, since it invokes the SSA library.
=> SSA: Add locations to ease debugging

cpp/ql/src/Security/CWE/CWE-807/TaintedCondition.ql, cpp/ql/test/query-tests/Security/CWE/CWE-807/semmle/TaintedCondition/TaintedCondition.expected
MRVA top 1000 does not show any results before or after. Still waiting for DCA.
=> C++: Rewrite `cpp/tainted-permissions-check` to not use `DefaultTaintTracking`

python/ql/test/experimental/dataflow/coverage/argumentPassing.py
like for Ruby in https://github.com/github/codeql/pull/14859/files#diff-9ff917104f9f14a90a85284a7fc80fad7a68c0bfed84eee467dbeaf7dc0cc011
=> Python: Highlight missing post-update flow for `*args` and `**kwargs`

shared/yeast/src/lib.rs, shared/yeast/tests/test.rs
This uses my query code instead of the placeholders.
=> YEAST: Hookup query code

swift/integration-tests/.gitignore, swift/integration-tests/osx-only/autobuilder/xcode-fails-spm-works/Files.expected, swift/integration-tests/osx-only/autobuilder/xcode-fails-spm-works/Files.ql, swift/integration-tests/osx-only/autobuilder/xcode-fails-spm-works/Package.swift, swift/integration-tests/osx-only/autobuilder/xcode-fails-spm-works/Sources/hello-world/hello_world.swift, swift/integration-tests/osx-only/autobuilder/xcode-fails-spm-works/codeql-swift-autobuild-test.xcodeproj/project.pbxproj, swift/integration-tests/osx-only/autobuilder/xcode-fails-spm-works/codeql-swift-autobuild-test/AppDelegate.swift, swift/integration-tests/osx-only/autobuilder/xcode-fails-spm-works/test.py, swift/swift-autobuilder/swift-autobuilder.cpp
The bulid success rate went up to ~57% (from ~47% previously).
=> Swift: fix autobuilder bug when Xcode failure breaks the whole autobuild process

docs/codeql/reusables/supported-versions-compilers.rst
@geoffw0 @AlexDenisov This is the relpacement for https://github.com/github/codeql/pull/15019
=> docs: update supported Swift version

docs/codeql/conf.py
Redo of #15097.
@oscarsj Sorry for the trouble..I force pushed an unmodified upstream main branch due to a misnomer to my patch branch again, so there is no diff, and the PR gets closed automatically. Even if i updated my patch branch, the PR will not update. I have to open a new PR.
I've tested locally it works.
=> Fix sphinx.add_lexer.

cpp/ql/lib/change-notes/2023-12-22-unique-function.md, cpp/ql/lib/semmle/code/cpp/Element.qll, cpp/ql/lib/semmle/code/cpp/Function.qll, cpp/ql/lib/semmle/code/cpp/controlflow/internal/ConstantExprs.qll, cpp/ql/lib/semmle/code/cpp/internal/ResolveFunction.qll, cpp/ql/lib/semmle/code/cpp/internal/ResolveGlobalVariable.qll
For DCA analysis see the internal issue that links to this PR.
=> C++: Ensure that only one `Function` exists for every function

java/ql/lib/semmle/code/java/security/MaybeBrokenCryptoAlgorithmQuery.qll, java/ql/src/Security/CWE/CWE-327/MaybeBrokenCryptoAlgorithm.ql, java/ql/test/query-tests/security/CWE-327/semmle/tests/BrokenCryptoAlgorithm.expected, java/ql/test/query-tests/security/CWE-327/semmle/tests/MaybeBrokenCryptoAlgorithm.expected, java/ql/test/query-tests/security/CWE-327/semmle/tests/WeakHashing.java
=> Java: Generalize MaybeBrokenCryptoAlgorithmQuery.qll 

go/ql/lib/change-notes/2024-01-02-go-successfully-extracted.md, go/ql/src/Diagnostics/SuccessfullyExtractedFiles.ql, go/ql/test/query-tests/Diagnostics/SuccessfullyExtractedFiles.expected
Go version of https://github.com/github/codeql/pull/14988.
=> Go: report any extracted file as successfully extracted

docs/codeql/reusables/supported-versions-compilers.rst
Supported as of CodeQL release 2.15.4
=> Note Java 21 support

docs/codeql/ql-language-reference/aliases.rst, docs/codeql/ql-language-reference/modules.rst, docs/codeql/ql-language-reference/ql-language-specification.rst
This documents https://github.com/github/semmle-code/pull/48313.
=> document weak aliases in the language reference

javascript/extractor/lib/typescript/src/type_table.ts
by not having to compute the "type-string" for a type every time.  
I have a case (internal, see backref) where the extraction speed of a large `const` type is speedup massively by this change.  
Evaluations ([default](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/fastTS__default__code-scanning/reports), [nightly](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/fastTS__nightly-old__code-scanning/reports)) were very uneventful.
=> JS: faster TypeScript extraction

javascript/ql/test/query-tests/Security/CWE-020/SuspiciousRegexpRange/tst.js, shared/regex/codeql/regex/OverlyLargeRangeQuery.qll
found during some Python triage, so I'm putting them as reviewer.  
I'm not planning an evaluation, unless someone wants it.
=> remove an FP in overly-large-range for [@-Z]

.clang-format, .github/workflows/swift.yml, .pre-commit-config.yaml, swift/extractor/infra/SwiftDispatcher.h, swift/extractor/infra/SwiftLocationExtractor.h, swift/extractor/translators/PatternTranslator.cpp, swift/extractor/trap/TrapLabel.h, swift/integration-tests/.clang-format, swift/logging/SwiftLogging.h
Also, added a format check in `swift.yml`.
=> Swift: update formatting to `clang-format` 17.0.6

.vscode/settings.json, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.10.5.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.11.5.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.11.6.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.12.4.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.12.7.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.13.3.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.13.5.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.14.3.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.14.5.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.14.6.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.15.4.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.15.5.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.16.0.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.16.1.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.4.3.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.4.6.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.5.1.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.5.2.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.5.3.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.5.4.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.5.9.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.6.3.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.7.6.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.8.5.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.9.4.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
- Add the changelog for the current version
=> Generate changelog for 2.16.1 

java/ql/lib/ext/java.net.model.yml
=> Java: Add models for overloads of DatagramPacket constructor

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/comments/CommentExtractor.kt, java/kotlin-extractor/src/main/kotlin/utils/versions/v_1_9_0-Beta/CommentExtractorLighterAST.kt, java/ql/test-kotlin2/library-tests/comments/comments.expected, java/ql/test-kotlin2/library-tests/comments/comments.kt
Comments aren't 100% yet, but they're relatively unimportant, so I've just accepted the rest of the differences for now.
=> Kotlin 2: Comment improvements

ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected, ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
This was meant to be part of https://github.com/github/codeql/pull/15468, but I forgot to push it before the PR was merged.
=> Ruby: Add another dataflow test

csharp/ql/lib/semmle/code/csharp/dataflow/internal/ContentDataFlow.qll
`PathNode.getASuccessor` is pruned now, so there's no need to refer directly to `edges`.
=> C#: Simplify, getASuccessor is pruned now.

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll
=> C#: Actually cache module `Cached`

shared/tree-sitter-extractor/src/extractor/mod.rs, shared/tree-sitter-extractor/src/trap.rs
Since locations for any given source file are never referenced in any TRAP files besides the one for that particular source file, it's not necessary to use global IDs. Using fresh IDs will reduce the size of the ID pool (both on disk and in memory) and speed up multi-threaded TRAP import (avoiding the locks needed for global IDs).
The one exception is the empty location, which still uses a global ID.
We can still make multiple references to a location *within* a TRAP file, and they must use the same label, which is why we need a hashmap from locations to labels, whose lifetime is that of a single TRAP file. Arguably, it could just live inside the `trap::Writer` object, but keeping it separate avoids having that module know about locations, which are (theoretically) dbscheme-specific.
=> Tree-sitter extractors: use fresh IDs for locations

.github/workflows/qhelp-pr-preview.yml
=> Use `!cancelled` in qhelp-pr-preview workflow

java/ql/test-kotlin2/library-tests/interface-delegate/test.expected, java/ql/test-kotlin2/library-tests/java-kotlin-collection-type-generic-methods/test.expected
I'm not sure exactly what's going on with the Collection interfaces in general, but I've made a ticket to remind us to revisit it later.
=> Kotlin 2: Accept more test changes

java/ql/test-kotlin2/library-tests/stmts/PrintAst.expected, java/ql/test-kotlin2/library-tests/stmts/exprs.expected, java/ql/test-kotlin2/library-tests/stmts/stmts.expected
Mostly location changes. Also a generated variable name changed (`tmp3_loop_parameter` -> `<destruct>`).
=> Kotlin 2: Accept changes in library-tests/stmts

java/ql/test-kotlin2/library-tests/multiple_files/method_accesses.expected
I think that this is a regression, but one that we're not likely to fix soon, so let's just accept the output for now. I've opened a ticket to remind us to return to this.
=> Kotlin: Accept changes in library-tests/multiple_files

ruby/ql/lib/CHANGELOG.md, ruby/ql/lib/change-notes/released/0.8.7.md
=> Ruby: Fix formatting in changelog

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.16.3.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
=> Codeql 2.16.3 changelogs

java/ql/test-kotlin1/library-tests/compilation-units/cus.expected, java/ql/test-kotlin1/library-tests/enum/test.expected, java/ql/test-kotlin1/library-tests/java-kotlin-collection-type-generic-methods/test.expected, java/ql/test-kotlin1/library-tests/reflection/reflection.expected
This updates the tests to reflect the jdk changes as that jdk is not the same.
=> Kotlin: Compile tests using the same jdk as the java tests.

go/extractor/cli/go-autobuilder/go-autobuilder.go, go/extractor/project/project.go, go/extractor/util/util.go
This is a follow-up to #15361 to address review comments from there which do not affect the behaviour of the autobuilder.
=> Go: Various minor improvements in autobuilder implementation 

python/ql/src/Security/CWE-943/NoSqlInjection.ql, python/ql/src/change-notes/2024-03-04-nosql-injection.md
Due to this, it was not part of any query suite :O
@yoff do you agree it should be `high`, or should it be `medium`? I don't have the details from when you did the promotion of this query, so just took a guess.
=> Python: Add precision to NoSQL query

python/ql/test/experimental/dataflow/model-summaries/InlineTaintTest.ext.yml, python/ql/test/experimental/dataflow/model-summaries/NormalDataflowTest.ext.yml, python/ql/test/experimental/dataflow/model-summaries/model_summaries.py
Just making sure that this works (and will keep working). Btw, the test in this form did not pass prior to https://github.com/github/codeql/pull/15755.
=> Python: Add test for `ReturnValue.TupleElement[n]`

python/ql/lib/semmle/python/dataflow/new/FlowSummary.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll, python/ql/lib/semmle/python/dataflow/new/internal/FlowSummaryImpl.qll, python/ql/lib/semmle/python/frameworks/data/ModelsAsData.qll
as it should be covered by `SummarizedCallableFromModel`
Also move things around, to look more like the Ruby code.
Thanks to @aschackmull for finding this.
=> python: Remove `TaintStepFromSummary`

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll
This addresses https://github.com/github/codeql/pull/15918#discussion_r1524521346
cc @geoffw0
=> C++: Follow-up to #15918

python/ql/lib/semmle/python/dataflow/new/internal/DataFlowDispatch.qll, python/ql/lib/semmle/python/frameworks/SqlAlchemy.qll
I don't expect major performance gains from this, just thought it would be interesting to improve a few of the things with high join-order badness :blush:
=> Python: Two small join-order fixes

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.16.5.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
This pull request updates the CodeQL CLI to version 2.16.5.
=> Update CodeQL CLI to version 2.16.5

cpp/ql/lib/semmle/code/cpp/Variable.qll, cpp/ql/test/library-tests/ir/ir/PrintAST.expected
This adds some uniformity, as we already had `FunctionTemplateInstantiation` and `ClassTemplateInstantiation` classes.
=> C++: Add `VariableTemplateInstantiation` class

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.16.6.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
Add CodeQL CLI 2.16.6 updates to the changelog.
=> Add codeql-cli-2.16.6 updates to CodeQL changelog

config/identical-files.json, cpp/ql/lib/qlpack.yml, cpp/ql/lib/semmle/code/cpp/XML.qll, csharp/ql/lib/qlpack.yml, csharp/ql/lib/semmle/code/csharp/XML.qll, java/ql/lib/qlpack.yml, java/ql/lib/semmle/code/java/frameworks/spring/SpringBean.qll, java/ql/lib/semmle/code/java/frameworks/spring/SpringProperty.qll, java/ql/lib/semmle/code/xml/Ant.qll, java/ql/lib/semmle/code/xml/XML.qll, javascript/ql/lib/qlpack.yml, javascript/ql/lib/semmle/javascript/XML.qll, javascript/ql/lib/semmle/javascript/frameworks/ServerLess.qll, python/ql/lib/qlpack.yml, python/ql/lib/semmle/python/frameworks/ServerLess.qll, python/ql/lib/semmle/python/xml/XML.qll, shared/xml/codeql/xml/Xml.qll, shared/xml/qlpack.yml
Commit-by-commit review is suggested, and the second commit is best reviewed with whitespaces ignored.
=> Properly shared `XML.qll` implementation

docs/codeql/reusables/supported-versions-compilers.rst
=> Docs: Mark Swift version 5.10 as supported

java/ql/automodel/src/AutomodelApplicationModeCharacteristics.qll, java/ql/automodel/test/AutomodelApplicationModeExtraction/Test.java, java/ql/automodel/test/AutomodelFrameworkModeExtraction/com/github/codeql/test/MyWriter.java
We already did this in framework mode.
=> Automodel: Filter unexploitable types in application mode.

python/ql/lib/semmle/python/frameworks/data/ModelsAsData.qll
Thanks for pointing out this problem @rvermeulen :+1:
=> Python: Fix `RemoteFlowSourceFromCsv`

shared/dataflow/change-notes/2024-04-09-alert-provenance.md
See https://github.com/github/codeql/pull/15501#discussion_r1562552436
=> Dataflow: Amend change note for alert provenance.

java/ql/lib/semmle/code/java/os/OSCheck.qll
The TC was being fully materialised but all we need is unary reachability.
=> Java: Fix join-order.

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.17.1.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
Changelog entry for the 2.17.1 release
=> Update codeql-changelog index.rst to include codeql-cli-2.17.1

java/ql/src/Security/CWE/CWE-190/ComparisonWithWiderType.ql, java/ql/test/query-tests/security/CWE-190/semmle/tests/ComparisonWithWiderType.expected, java/ql/test/query-tests/security/CWE-190/semmle/tests/ComparisonWithWiderType.java, java/ql/test/query-tests/security/CWE-190/semmle/tests/ComparisonWithWiderType.qlref
It didn't seem to have any (but perhaps I looked in the wrong place?).
=> Java: Add tests for `comparison-with-wider-type`.

javascript/ql/lib/semmle/javascript/frameworks/ShellJS.qll, javascript/ql/test/library-tests/frameworks/Shelljs/ShellJS.expected, javascript/ql/test/library-tests/frameworks/Shelljs/tst.js
The Shelljs package has a piping feature and I've updated the current shelljs module to support piping too.
=> JS: Shelljs improvement

cpp/ql/src/Likely Bugs/Format/NonConstantFormat.qhelp
Update an instance of the very old product name 'Semmle' in a doc page.
I'm open to suggestions for better phrasing.
=> C++: Update an instance of the name 'Semmle' in a doc page.

java/ql/src/Security/CWE/CWE-611/XXE.qhelp
Use more directive wording in the recommendation of the XXE query.
@max-schaefer I think you wanted to be pinged about this.
=> Java: Reword recommendation section of XXE query

csharp/ql/integration-tests/posix-only/standalone_dependencies_nuget_config_fallback/diagnostics.expected
Conflicting PRs: https://github.com/github/codeql/pull/16549 and https://github.com/github/codeql/pull/16541.
=> C#: Fix integration test expected file

go/extractor/trap/labels.go
No functional change. I just find this easier to read.
=> Go: Refactor findMethodWithGivenReceiver

ruby/extractor/Cargo.lock, ruby/extractor/Cargo.toml, ruby/extractor/cargo-bazel-lock.json
To include [this](https://github.com/tree-sitter/tree-sitter-ruby/pull/259) (minor) fix.
=> Ruby: Bump tree-sitter grammar

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.17.4.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
These changes are already in main, but this mergeback is needed to publish just these docs (without the other drafts in main).
=> Add changelog for 2.17.4 to release brach

shared/ssa/codeql/ssa/Ssa.qll
So that we have https://github.com/github/codeql/pull/16740 on `main` as well
=> Mergeback from `rc/3.14`

docs/codeql/codeql-overview/system-requirements.rst
=> Add powershell to list of requirements on windows

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.17.4.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.17.5.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
CodeQL 2.17.5 unified changelog.
=> add 2.17.5 unified changelog

cpp/ql/test/header-variant-tests/iquote/iquote.c, cpp/ql/test/library-tests/CPP-207/options, cpp/ql/test/library-tests/attributes/availability/options, cpp/ql/test/library-tests/clang_builtin_macros/addressof.c, cpp/ql/test/library-tests/clang_builtin_macros/extended.cpp, cpp/ql/test/library-tests/clang_builtin_macros/options, cpp/ql/test/library-tests/clang_builtin_macros/test.cpp, cpp/ql/test/library-tests/clang_ms/options, cpp/ql/test/library-tests/dataflow/dataflow-tests/clang.cpp, cpp/ql/test/library-tests/declspec/guard/test.cpp, cpp/ql/test/library-tests/specifiers2/cpp20.cpp, cpp/ql/test/library-tests/structs/compatible_c/c1_gnu.c, cpp/ql/test/library-tests/structs/compatible_c/c2_gnu.c, cpp/ql/test/library-tests/templates/CPP-223/test.cpp, cpp/ql/test/library-tests/vector_types/options, cpp/ql/test/library-tests/vector_types/vector_types.cpp
See related internal PR for details.
=> C++: Remove unneeded options from tests

docs/codeql/ql-language-reference/modules.rst
This PR adds documentation for the builtin `InternSets` module.
=> Document builtin InternSets module

python/ql/lib/semmle/python/dataflow/new/internal/ImportResolution.qll
The "most expensive predicates" report had the following line on a certain database:
```
1m15s |    11 |   37s @ 4    | ImportResolution::ImportResolution::getImmediateModuleReference/1#3553e6c0#reorder_1_0@12bb4xdo
```
Investigating further revealed the following bad joins
```
(388s) Tuple counts for ImportResolution::ImportResolution::getImmediateModuleReference/1#3553e6c0#reorder_1_0/2@i4#b2325xoe after 36.5s:
0         ~0%        {2} r1 = JOIN `ImportResolution::ImportResolution::sys_modules_module_with_name/1#134529bf#prev_delta` WITH `ImportResolution::ImportResolution::getReferenceToModuleName/1#bc5da225` ON FIRST 1 OUTPUT Rhs.1 'result', Lhs.1 'm'
74884348  ~0%        {3} r2 = JOIN `ImportResolution::ImportResolution::getModuleReference/1#28368ea4#prev_delta` WITH …
```
=> Python: Fix bad join in `getImmediateModuleReference`

cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/IteratorToExpiredContainer/IteratorToExpiredContainer.expected, cpp/ql/test/query-tests/Security/CWE/CWE-416/semmle/tests/IteratorToExpiredContainer/test.cpp
This represents the very last FP we've seeing on MRVA for this query.
=> C++: Add `cpp/iterator-to-expired-container` FP

javascript/ql/integration-tests/all-platforms/diagnostics/internal-error/diagnostics.expected, javascript/ql/integration-tests/all-platforms/diagnostics/internal-error/test.py, javascript/ql/integration-tests/all-platforms/diagnostics/syntax-error/test.py, javascript/ql/integration-tests/all-platforms/no-types/test.py, javascript/ql/integration-tests/all-platforms/qlpack.yml, javascript/ql/integration-tests/legacy
=> Integration tests: port to pytest.

python/ql/test/library-tests/dataflow/tainttracking/isinstance/InlineTaintTest.expected, python/ql/test/library-tests/dataflow/tainttracking/isinstance/InlineTaintTest.ql, python/ql/test/library-tests/dataflow/tainttracking/isinstance/test.py
Thanks @smowton for pointing this out :+1:
=> Python: Add test for impossible isinstance flow

swift/ql/lib/codeql/swift/security/ECBEncryptionQuery.qll, swift/ql/test/library-tests/dataflow/taint/core/LocalTaint.expected, swift/ql/test/library-tests/dataflow/taint/core/Taint.expected, swift/ql/test/library-tests/dataflow/taint/core/simple.swift
A few small changes I've been meaning to PR.
=> Swift: Odds and ends

ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected
https://github.com/github/codeql/pull/17156 follow-up.
=> Ruby: Update expected test output

javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowPrivate.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/VariableCapture.qll, javascript/ql/test/query-tests/Security/CWE-079/ExceptionXss/ExceptionXss.expected, javascript/ql/test/query-tests/Security/CWE-312/BuildArtifactLeak.expected
Some updates to the shared data flow branch after merging with main
=> JS: Merge 'main' into shared dataflow branch

cpp/ql/test/library-tests/dataflow/external-models/flow.expected
Cherry-pick of https://github.com/github/codeql/pull/17161 from `main`.
=> C++: Accept test changes caused by new CLI version.

java/ql/lib/semmle/code/java/security/internal/BoundingChecks.qll
Before
```
[2024-08-06 10:37:59] Evaluated non-recursive predicate BoundingChecks::arrayReference/1#754911ba@0628dahn in 20981ms (size: 2009682526).
Evaluated relational algebra for predicate BoundingChecks::arrayReference/1#754911ba@0628dahn with tuple counts:
94480   ~0%    {2} r1 = SCAN `Expr::ArrayAccess.getArray/0#dispred#b90c658a` OUTPUT In.1, In.0
32   ~0%    {2} r2 = JOIN r1 WITH `Expr::MethodCall.getMethod/0#dispred#41989dc9` ON FIRST 1 OUTPUT Rhs.1, Lhs.1
1013   ~1%    {2}    | JOIN WITH `Expr::MethodCall.getMethod/0#dispred#41989dc9_10#join_rhs` ON FIRST 1 OUTPUT Lhs.1, Rhs.1
92091   ~4%    {2} r3 = JOIN r1 WITH variableBinding ON FIRST 1 OUTPUT Rhs.1, Lhs.1
2009681513   ~0%    {2}    | JOIN WITH variableBinding_10#join_rhs ON FIRST 1 OUTPUT Lhs.1, Rhs.1
2009682526   ~0%    {2} …
```
=> Java: Fix bad join

shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
For now, this is just debugging convenience, but ideally this will be a step towards replacing the pathStep relation and current creation of PathNodes in order to reduce code duplication.
=> Dataflow: Add provenance to StagePathGraph.

java/ql/test/library-tests/dataflow/collections/containerflow.expected, java/ql/test/library-tests/dataflow/subpaths/flow.expected, java/ql/test/library-tests/frameworks/apache-collections/test.expected, java/ql/test/library-tests/frameworks/gson/test.expected, java/ql/test/library-tests/frameworks/guava/generated/collect/test.expected, java/ql/test/library-tests/frameworks/netty/generated/test.expected, java/ql/test/library-tests/frameworks/spring/util/test.expected, shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll
Fixes the bug referenced in https://github.com/github/codeql/pull/17221 and https://github.com/github/codeql/pull/17215
=> Dataflow: Fix missing subpaths due to type strengthening.

java/ql/src/experimental/Security/CWE/CWE-078/CommandInjectionRuntimeExec.ql
Align severity with other command injection vulnerabilities:
- https://github.com/github/codeql/blob/4a448f445e79b9baa07a302d8062fe9f0fcb00b9/cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql#L8
- https://github.com/github/codeql/blob/4a448f445e79b9baa07a302d8062fe9f0fcb00b9/go/ql/src/Security/CWE-078/CommandInjection.ql#L7
- https://github.com/github/codeql/blob/4a448f445e79b9baa07a302d8062fe9f0fcb00b9/swift/ql/src/queries/Security/CWE-078/CommandInjection.ql#L7
- https://github.com/github/codeql/blob/4a448f445e79b9baa07a302d8062fe9f0fcb00b9/javascript/ql/src/Security/CWE-078/CommandInjection.ql#L7
=> Align Java CommandInjectionRuntimeExec.ql Severity

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected, csharp/ql/test/library-tests/dataflow/fields/K.cs
This reverts commit 1bcac50db124f7fbd2e0cf033b284b4d8224f0a3.
=> Revert "C#: Add support for flow through side-effects on static fields"

rust/ql/consistency-queries/Placeholder.ql, rust/ql/consistency-queries/qlpack.yml
Add a consistency queries pack to Rust with a single placeholder query.
=> Rust: Add consistency-queries pack

java/ql/lib/ext/org.springframework.core.io.model.yml, java/ql/lib/ext/org.springframework.web.multipart.model.yml, java/ql/src/change-notes/2024-09-18-getInputStream-summary.md, java/ql/test/library-tests/frameworks/spring/webmultipart/test.expected
Model summary for `getInputStream` methods
=> Model summary for `org.springframework.core.io.getInputStream` methods

docs/codeql/_templates/layout.html
=> Revert changes that made the links in the drop-down on CodeQL docs site relative

docs/codeql/index.html
Somehow this copy/paste error was missed by me and the reviewers 😞
=> Fix link to change logs on landing page

cpp/ql/lib/semmle/code/cpp/security/flowafterfree/FlowAfterFree.qll
=> C++: Remove `inline` pragma from sink

java/kotlin-extractor2/src/main/kotlin/KotlinFileExtractor.kt
https://github.com/github/codeql/pull/17599
=> KE2: Add bugfix from KE1's #17599

go/extractor/extractor.go, go/ql/lib/semmle/go/Types.qll
=> Go: Add comments noting methods from embedded interfaces are already included

csharp/ql/lib/semmle/code/csharp/security/dataflow/LogForgingQuery.qll
=> Update Comment - Clarify threat model flow sources comment in LogForgingQuery.qll

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.19.1.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
=> Adding unified changelog for 2.19.1

python/ql/src/change-notes/released/1.3.0.md, python/ql/src/experimental/Security/CWE-942/CorsMisconfigurationMiddleware.ql
Makes it more clear that the query is experimental.
=> Python: Update CORS query tags and change note

docs/codeql/index.html
Kudos to @aikenka for spotting this.
Closes https://github.com/github/codeql/issues/17723
=> Docs: fix CWE coverage link in main index

python/extractor/cli-integration-test/python-2-deprecation/query.only-python2.expected, python/extractor/cli-integration-test/python-2-deprecation/query.python2-using-python3.expected
=> python: update extractor expectations

docs/codeql/index.html
@redsun82 The URL should be https://codeql.github.com/codeql-query-help/codeql-cwe-coverage/
=> Fix CWE coverage link in main index

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
We need to catch a different exception now.
=> Kotlin: Fix for 2.1.0-Beta2

python/ql/test/library-tests/dataflow/tainttracking/defaultAdditionalTaintStep/test_collections.py
=> Python: Add `copy.replace` test to list of runnable tests

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.19.1.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.19.2.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
=> CodeQL 2.19.2 changedocs

javascript/ql/src/Security/CWE-312/ActionsArtifactLeak.ql
Similar to javascript/ql/src/Security/CWE-094/ExpressionInjection.ql
=> fix: add "actions" tag to ActionsArtifactLeak

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.19.3.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
Publishing the unified changelog fo 2.19.3
=> Changedocs for 2.19.3

docs/codeql/reusables/supported-platforms.rst
Table looks a bit odd at the moment:
=> Remove duplicated "Supported CPU architectures" from "Supported platforms" table

csharp/.vscode/launch.json, csharp/autobuilder/Semmle.Autobuild.CSharp/AutoBuildRule.cs, csharp/autobuilder/Semmle.Autobuild.Shared/Autobuilder.cs, csharp/autobuilder/Semmle.Autobuild.Shared/MarkdownUtil.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/Assets.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNetVersion.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/FileContent.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/IDotNetCliInvoker.cs, csharp/extractor/Semmle.Extraction.CSharp/CodeAnalysisExtensions/SymbolExtensions.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Base/CachedEntity.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Base/IEntity.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression`1.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/NamedType.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/Nullability.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/UserOperator.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/Context.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/TrapWriter.cs, csharp/extractor/Semmle.Extraction.CSharp/Trap/EscapingTextWriter.cs, csharp/extractor/Semmle.Extraction.CSharp/Trap/TrapExtensions.cs, csharp/extractor/Semmle.Util/CanonicalPathCache.cs, csharp/extractor/Semmle.Util/CommandBuilder.cs, csharp/ql/integration-tests/all-platforms/dotnet_build/test.py
Various minor improvements
- Address review comment from a previous PR.
- Fix some compiler warnings (related to incorrect XML comments).
- Update `launch.json`.
=> C#: Update to .NET 9

csharp/ql/test/resources/stubs/System.Web.cs
---
category: fix
---
* Add definitions for Deserialize() and Deserialize<T> to the System.Web.Serialization stubs.
=> Add Deserialize() and Deserialize<T> to System.Web.Serialization stubs

cpp/ql/lib/semmle/code/cpp/models/Models.qll, cpp/ql/lib/semmle/code/cpp/models/implementations/Win32CommandExecution.qll
Just a list of command execution functions from the Win32 that I was researching for something else. May as well include them as `CommandExecutionFunction`s while here.
=> C++: Add more `CommandExecutionFunction`s

go/actions/test/action.yml
=> Update action.yml to use artifacts@v4

rust/ql/test/library-tests/dataflow/sources/test.rs
Fixes a semantic merge conflict.
=> Rust: update inline expectations

csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependabotProxy.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DependencyManager.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNet.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/DotNetCliInvoker.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/EnvironmentVariableNames.cs, csharp/extractor/Semmle.Extraction.CSharp.DependencyFetching/NugetPackageRestorer.cs
This PR ports #18029 to the `codeql-cli-2.20.0` branch.
=> Port "C#: Set proxy environment variables, if Dependabot proxy is detected" to 2.20.0 release branch

cpp/ql/src/change-notes/2024-12-05-wrong-number-format-arguments.md
=> C++: Fix word duplication in change note

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.19.4.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
=> Update codeql unified changelog

.vscode/tasks.json
=> Add `actions` as a supported language for change notes

cpp/ql/src/CHANGELOG.md, cpp/ql/src/change-notes/released/1.3.0.md
=> C++: Remove duplicate word from change note

go/ql/lib/change-notes/2025-01-05-gorm-database-sources.md, go/ql/lib/ext/gorm.io.gorm.model.yml, go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/database/go.mod, go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/database/test_gorm.go, go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/database/user.go, go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/database/vendor/gorm.io/gorm/stub.go, go/ql/test/library-tests/semmle/go/dataflow/flowsources/local/database/vendor/modules.txt
Adds `database` local source models for database-reading methods in the `gorm.io/gorm` ORM package.
~- [ ] All new queries have appropriate `.qhelp`. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-help-style-guide.md) in this repository.~
~- [ ] New and changed queries have correct query metadata. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md) in this repository.~
~- [ ] Autofixes generated based on these changes are valid, only needed if this PR makes significant changes to `.ql`, `.qll`, or `.qhelp` files. See [the documentation](https://github.com/github/codeql-team/blob/main/docs/best-practices/validating-autofix-for-query-changes.md) (internal access required).~
~- [ ] Adding a new query? Consider …
=> Go: Model sources from the `gorm.io/gorm` package

cpp/ql/test/library-tests/dataflow/models-as-data/taint.expected
This seemed to have slipped through earlier.
=> C++: Update expected test results

rust/ql/lib/codeql/rust/controlflow/CfgNodes.qll, rust/ql/test/library-tests/dataflow/local/DataFlowStep.expected, rust/ql/test/library-tests/dataflow/local/inline-flow.expected, rust/ql/test/library-tests/dataflow/local/main.rs
See https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#destructuring-structs.
=> Rust: Shorthand record pattern destructuring in data flow

rust/ql/test/utils-tests/modelgenerator/summaries.rs
Test with missing annotations where added in #18628 but fixed in #18656.
=> Rust: Accept test changes

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.19.2.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.20.1.rst, docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.20.4.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
This pull request includes various updates to the CodeQL CLI and relevant CodeQL query and library packs. The most important changes include new features and bug fixes, improvements to analysis, and breaking changes across multiple languages and libraries.
=> Update changelog to include new CodeQL CLI version

ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll, rust/ql/lib/codeql/rust/dataflow/internal/SsaImpl.qll
Minor followup for https://github.com/github/codeql/pull/18729
=> Rust/Ruby: Minor SSA cleanup.

docs/codeql/codeql-overview/codeql-changelog/codeql-cli-2.20.5.rst, docs/codeql/codeql-overview/codeql-changelog/index.rst
This pull request includes updates to the CodeQL CLI documentation, specifically for version 2.20.5. The changes include new features, breaking changes, bug fixes, and minor analysis improvements across various languages and tools.
=> Add changelog for CodeQL CLI version 2.20.5

rust/ql/test/query-tests/security/CWE-312/CleartextLogging.expected
Leaving really fixing things up to a follow-up PR.
=> Rust: accept test changes for now

java/ql/integration-tests/java/query-suite/not_included_in_qls.expected, java/ql/integration-tests/java/query-suite/test.py
This PR is adding a java integration test to list all queries that are not included in well-known query suites.
=> Java: Add test to check queries not included in well-known query suites

cpp/ql/test/library-tests/structs/compatible_c/c1_gnu.c, cpp/ql/test/library-tests/structs/compatible_c/c2_gnu.c, cpp/ql/test/library-tests/vector_types/options
See individual commits for details.
=> C++: Minor cleanup of qltest options

rust/ql/test/query-tests/security/CWE-117/LogInjection.expected
Fixes semantic merge conflict between https://github.com/github/codeql/pull/20055 and https://github.com/github/codeql/pull/20221.
=> Rust: Update expected test output
