github/codeql

cpp/ql/src/experimental/Security/CWE/CWE-243/IncorrectChangingWorkingDirectory.cpp, cpp/ql/src/experimental/Security/CWE/CWE-243/IncorrectChangingWorkingDirectory.qhelp, cpp/ql/src/experimental/Security/CWE/CWE-243/IncorrectChangingWorkingDirectory.ql, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-243/semmle/tests/IncorrectChangingWorkingDirectory.expected, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-243/semmle/tests/IncorrectChangingWorkingDirectory.qlref, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-243/semmle/tests/test.cpp
The request looks for situations of incorrect work with the setting of the working directory. first of all, this is the lack of checking the return value by the set function, secondly, it is the lack of setting after using the chroot call.
CVE-2008-5110
links to real work results, I will add later. I am currently working on them with developers.
=> CPP: Add query for CWE-243 Creation of chroot Jail Without Changing Working Directory

javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll, javascript/ql/lib/semmle/javascript/security/dataflow/PrototypePollutingAssignmentQuery.qll, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/tst.js
The first commit contains a general oversight in handling of labeled barriers from the data flow library, resulting in a labelled barrier from `PrototypePollutingAssignment` not working correctly. Specifically, the barrier preventing flow into `this`.
The rest are changes specific to `PrototypePollutingAssignment` to make it block spurious flow in a few more cases.
=> JS: Precision fixes, mainly for PrototypePollutingAssignment

.github/actions/fetch-codeql/action.yml, .github/workflows/post-pr-comment.yml, .github/workflows/qhelp-pr-preview.yml
This pull request makes the `qhelp-pr-preview` workflow suitable to be run on pull requests from forks. Actions jobs on pull requests from forks are run with limited privileges and as a result the workflow was not allowed to post a comment containing the QHelp previews. To make this work I split the workflow in two, the first generates the query help in markdown format and uploads the result as an artefact. The second workflow uses a `workflow_run` trigger and takes care of downloading the generated markdown and posting it to the pull request. The first workflow is completely user controlled and runs with read-only permissions. The second workflow has elevated permissions `pull-request: write` to post the comment. However, this workflow is not user controlled and its inputs (a …
=> Rewrite qhelp-pr-preview.yml

cpp/ql/lib/semmle/code/cpp/ir/dataflow/DefaultTaintTracking.qll, cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/annotate_path_to_sink/dispatch.cpp, cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/annotate_path_to_sink/tainted.ql, cpp/ql/test/library-tests/dataflow/DefaultTaintTracking/annotate_path_to_sink/test_diff.cpp
While working on https://github.com/github/codeql/pull/6825 I discovered some problems with the tests in the `annotate_path_to_sink` directory.
The tests in this folder are designed to give us a way to test the path explanations generated for dataflow queries by giving us the ability to annotate path components from ast or ir dataflow queries.
To construct the tainted elements in the path path, the test defines `tainted` roughly like this:
```ql
irTaint(source, tainted) and
(
isSink(tainted)
or
exists(Element sink |
isSink(sink) and
DefaultTaintTracking::tainted(tainted, sink)
)
)
```
this _almost_ works: a tainted value is either a sink, or it's something that ends up in a sink. However, since the first argument of `DefaultTaintTracking::tainted` is restricted to being user input sources …
=> C++: Better `InlineExpectation` tests for path-explanations

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointFeatures.qll
Compute `calleeAPIName` by re-using the logic of `accessPaths`. The vast majority of callee API names can be retrieved in this alternative way. This reduces computation time significantly.
Links to backend PR: https://github.com/github/ml-ql-adaptive-threat-modeling-backend/pull/1051
=> more efficient implementation of calleeApiName

docs/codeql/codeql-cli/codeql-cli-reference.rst, docs/codeql/codeql-cli/creating-codeql-databases.rst, docs/codeql/codeql-cli/extractor-options.rst, docs/codeql/codeql-cli/using-the-codeql-cli.rst
This PR creates a new article that describes extractor options and how to invoke them. It also adds a link to this new article in the [Creating CodeQL databases](https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/) article.
To the docs team member who reviews this, the current examples are a bit vague because whats shipping in this CodeQL CLI release is the ability for CodeQL CLI to accept extractor options from CLI users and pass the options to the extractors. No extractor has declared any options yet, so this may be as specific as we can be for now. As time goes on, each extractor will gradually introduce its own set of extractor options. When this happens, we can revisit these examples and add additional information like which options might be helpful for specific …
=> New docs for extractor options

cpp/ql/lib/semmle/code/cpp/commons/NullTermination.qll
Follow-up to https://github.com/github/codeql/pull/6915.
The goal here was to eliminate the mutual recursion between `mayAddNullTerminator` and `mayAddNullTerminatorHelper`, which was still causing unnecessarily slow performance on a few projects.  I'm not sure if I've found the best solution to this - in particular `mayAddNullTerminatorHelper` looks quite large to me, though I haven't seen it blow up in practice.  Happy to take further suggestions.
The change has a *small* positive effect on performance locally.  I ran [DCA](https://github.com/github/codeql-dca-main/issues/969) on this (actually a variant with the two queries enabled) and only saw a 29s overall improvement there, which is likely not statistically significant.
@MathiasVP
=> C++: Further performance improvement for the null termination queries

java/ql/lib/semmle/code/java/dataflow/internal/DataFlowDispatch.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowNodes.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImplSpecific.qll, java/ql/lib/semmle/code/java/dispatch/DispatchFlow.qll, java/ql/lib/semmle/code/java/dispatch/ObjFlow.qll, java/ql/src/Telemetry/ExternalAPI.qll, java/ql/test/query-tests/security/CWE-297/UnsafeHostnameVerification.expected, java/ql/test/query-tests/security/CWE-798/semmle/tests/HardcodedCredentialsApiCall.expected, java/ql/test/query-tests/security/CWE-798/semmle/tests/HardcodedCredentialsSourceCall.expected
This improves performance when there are fields that have both a high number of reads and a high number of assignments.
=> Java: Add FieldValueNode to break up cartesian step relation.

csharp/ql/lib/semmle/code/csharp/PrintAst.ql, csharp/ql/src/Security Features/CWE-020/ExternalAPIsUsedWithUntrustedData.ql, csharp/ql/src/Security Features/CWE-020/UntrustedDataToExternalAPI.ql, csharp/ql/src/experimental/ir/IRConsistency.ql, csharp/ql/src/experimental/ir/PrintIR.ql, csharp/ql/src/experimental/ir/implementation/raw/IRConsistency.ql, csharp/ql/src/experimental/ir/implementation/raw/PrintIR.ql, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/internal/SSAConsistency.ql, csharp/ql/src/printAst.ql
Similar to https://github.com/github/codeql/pull/7026.
=> C#: Use `cs/` prefix in all query IDs

csharp/tools/osx64/compiler-tracing.spec
As outlined in github/semmle-code#40797, we do not need these stanzas anymore.
=> C#: Remove macos compatibility stanzas from tracing config.

java/ql/src/Likely Bugs/Concurrency/SynchSetUnsynchGet.ql
Recent optimiser changes appear to have introduced bad magic here, which have been observed to cost more than an hour to evaluate on at least one project. This fix makes the query evaluate in a few seconds.
=> Java: Fix bad magic in SynchSetUnsynchGet.

javascript/ql/src/Security/CWE-346/CorsMisconfigurationForCredentials.ql
[CWE-942: Permissive Cross-domain Policy with Untrusted Domains](https://cwe.mitre.org/data/definitions/942.html).  
The CWE was already used in [this similar experimental go query](https://github.com/github/codeql-go/blob/main/ql/src/experimental/CWE-942/CorsMisconfiguration.ql).
=> JS: add cwe-942 to `js/cors-misconfiguration-for-credentials`

javascript/ql/src/Security/CWE-295/DisablingCertificateValidation.ql
[CWE-297: Improper Validation of Certificate with Host Mismatch](https://cwe.mitre.org/data/definitions/297.html). 
The CWE was already used in [this similar Java query](https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-297/UnsafeHostnameVerification.ql).
=> JS: add cwe-297 to `js/disabling-certificate-validation`

javascript/extractor/src/com/semmle/js/extractor/FileExtractor.java
Reverts github/codeql#6924
Reverting due to a bug that caused TypeScript extraction to fail for the file after one that was skipped. The TypeScript process expects files to be requested in a specific order (so it can prepare the next file in parallel).
=> Revert "JS: Skip files with unsupported file encoding"

ruby/change-notes/2021-11-08-hardcoded-credentials-downgrade.md, ruby/ql/src/queries/security/cwe-798/HardcodedCredentials.ql
We've had some feedback around noisy results from this query.
It seems to make sense to downgrade this query so that it's not run as part of the default code scanning suite, as it overlaps with secret scanning functionality. The query will remain in the `security-extended` suite.
@turbo
=> Ruby: Downgrade `rb/hardcoded-credentials` precision from high to medium

ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll, ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected, ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.ql, ruby/ql/test/library-tests/dataflow/type-tracker/type_tracker.rb
Consider this snippet:
```rb
class Container
def field=(val)
puts self.field
@field = val
end
def field
@field
end
end
def m()
var = Container.new
var.field = "hello"
puts var.field
end
```
With the existing formulation of `basicStoreStep`, we would track flow from `"hello"` into `self.field` in the setter, because the target of the store was the pre-update node and not the post-update node. However, we actually didn't have any flow, since `basicStoreStep` was erroneously restricted to target only local source nodes. The second commit introduces the false flow (and the correct missing flow) by removing the local-source-node restriction, and the last commit removes the false flow by targeting post-update nodes.
@tausbn : AFAICT, the Python implementation also doesn't use post-update nodes, …
=> Ruby: Fix `basicStoreStep`

java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/frameworks/apache/IO.qll
This makes it easier to regenerate this in the future and see a proper diff.
=> Java: Extract Commons IO into seperate file

docs/codeql/support/reusables/frameworks.rst, python/change-notes/2021-11-09-model-aiopg.md, python/ql/lib/semmle/python/Frameworks.qll, python/ql/lib/semmle/python/frameworks/Aiopg.qll, python/ql/test/library-tests/frameworks/aiopg/ConceptsTest.ql, python/ql/test/library-tests/frameworks/aiopg/test.py
Adresses part of https://github.com/github/codeql-python-team/issues/388.
A question is if [`call_proc`](https://aiopg.readthedocs.io/en/stable/core.html#aiopg.Cursor.callproc) should be considered a sink similar to `execute`.
=> Python: model aiopg

cpp/ql/src/experimental/Security/CWE/CWE-377/InsecureTemporaryFile.cpp, cpp/ql/src/experimental/Security/CWE/CWE-377/InsecureTemporaryFile.qhelp, cpp/ql/src/experimental/Security/CWE/CWE-377/InsecureTemporaryFile.ql, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-377/semmle/tests/InsecureTemporaryFile.expected, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-377/semmle/tests/InsecureTemporaryFile.qlref, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-377/semmle/tests/test.cpp
Our request is looking for situations of unsafe work with files. use validation functions in the first place without guaranteeing that the file will not be created later. in the second case, he looks for places to work with the file, when his name is predictable and there are no restrictions on access rights.
CVE-2012-0786
CVE-2018-6198
CVE-2007-5936
links to real work results, I will add later. I am currently working on them with developers.
=> CPP: Add query for CWE-377 Insecure Temporary File

javascript/ql/src/Security/CWE-312/CleartextLogging.ql
[CWE-532: Insertion of Sensitive Information into Log File](https://cwe.mitre.org/data/definitions/532.html).
=> JS: add CWE-532 to the js/clear-text-logging query

javascript/change-notes/2021-11-02-session-fixation.md, javascript/ql/src/Security/CWE-384/SessionFixation.qhelp, javascript/ql/src/Security/CWE-384/SessionFixation.ql, javascript/ql/src/Security/CWE-384/examples/SessionFixation.js, javascript/ql/src/Security/CWE-384/examples/SessionFixationFixed.js, javascript/ql/test/query-tests/Security/CWE-384/SessionFixation.expected, javascript/ql/test/query-tests/Security/CWE-384/SessionFixation.qlref, javascript/ql/test/query-tests/Security/CWE-384/tst.js
Inspired by [this csharp query](https://github.com/github/codeql/blob/e2cb53c65f804bd90bdce9313165d328cec46e70/csharp/ql/src/Security%20Features/CWE-384/AbandonSession.ql).  (Which has no results on all of lgtm.com). 
[An evaluation looks ok-ish](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/cwe384__default__CustomSuite/reports).  
The new results appear to be TPs, but I'm not sure if they are worth fixing.  
So I set the severity to `warning` and the precision to `medium`, so that the alerts are not shown by default.
=> JS: add js/session-fixation query

javascript/change-notes/2021-11-02-insufficient-key-size.md, javascript/ql/lib/semmle/javascript/frameworks/CryptoLibraries.qll, javascript/ql/lib/semmle/javascript/security/CryptoAlgorithms.qll, javascript/ql/src/Security/CWE-326/InsufficientKeySize.qhelp, javascript/ql/src/Security/CWE-326/InsufficientKeySize.ql, javascript/ql/test/query-tests/Security/CWE-326/InsufficientKeySize.expected, javascript/ql/test/query-tests/Security/CWE-326/InsufficientKeySize.qlref, javascript/ql/test/query-tests/Security/CWE-326/tst.js, python/ql/lib/semmle/python/concepts/CryptoAlgorithms.qll
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/cwe326-eval/reports) looks fine.  
It finds a few results among the test-cases of NodeJS.   
Heavily inspired by: [csharp query](https://github.com/github/codeql/blob/main/csharp/ql/src/Security%20Features/InsufficientKeySize.ql), [go query](https://github.com/github/codeql-go/blob/main/ql/src/Security/CWE-326/InsufficientKeySize.ql), [python query](https://github.com/github/codeql/blob/main/python/ql/src/Security/CWE-326/WeakCryptoKey.ql). 
There aren't that many projects that generate their own keys, but I managed to [find a few](https://lgtm.com/query/8376072927259659767/).   
None of them look that serious, so I've set the severity to `warning`.
=> JS: Add insufficient key size query

javascript/ql/lib/semmle/javascript/dataflow/internal/CallGraphs.qll
Improves the call graph by tracking object literals with methods on them with a limited form of type tracking. Compared to full type-tracking it is limited in two ways:
- Object literals are not tracked into calls. This is due to risk of false flow when passed in as a "named callback".
- Object literals are not tracked with a type-tracker instance, and so cannot be tracked through properties in as many cases.
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/type-track-obje__default__dist-compare__1/reports) on the default 100 projects shows neutral performance, over 3000 new call edges, and a couple new results.
=> JS: Limited tracking of object literals with methods

javascript/ql/lib/semmle/javascript/GlobalAccessPaths.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeJQueryPluginQuery.qll, javascript/ql/test/query-tests/Security/CWE-079/UnsafeJQueryPlugin/UnsafeJQueryPlugin.expected, javascript/ql/test/query-tests/Security/CWE-079/UnsafeJQueryPlugin/unsafe-jquery-plugin.js
Gets a TP for CVE-2021-41184
An alternative solution I tried was to add extend calls to `GlobalAccessPaths.qll::fromReference`.   
However, that caused FNs in other tests (from the analysis mistakenly concluding that a dominating write existed).
=> JS: have the aliasPropertyPresenceStep step over extend calls

ruby/ql/lib/codeql/ruby/ApiGraphs.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
First perform a forwards sweep (`pruneUseNodeFwd`) followed by a backwards sweep (`pruneUseNodeRev`), before computing `trackUseNode`.
=> Ruby: Prune nodes before computing `trackUseNode`

javascript/change-notes/2021-11-04-sensitive-get-query.md, javascript/ql/src/Security/CWE-598/SensitiveGetQuery.qhelp, javascript/ql/src/Security/CWE-598/SensitiveGetQuery.ql, javascript/ql/src/Security/CWE-598/examples/SensitiveGet.js, javascript/ql/test/query-tests/Security/CWE-598/SensitiveGetQuery.expected, javascript/ql/test/query-tests/Security/CWE-598/SensitiveGetQuery.qlref, javascript/ql/test/query-tests/Security/CWE-598/tst.js
Inspired by an existing [experimental Java query](https://github.com/github/codeql/blob/main/java/ql/src/experimental/Security/CWE/CWE-598/SensitiveGetQuery.ql).   
(That experimental query uses taint-tracking, my query here doesn't). 
The query is extremely simple, but it seems to be quite effective.  
See e.g. [this TP in juice-shop](https://lgtm.com/query/7815244056745865917/). 
[An LGTM run on ~230 projects](https://lgtm.com/query/8286835668029409247/) finds 3 projects with TPs and an FP (`PasswordResetId`). 
[An evaluation looks OK](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/cwe598__default__CustomSuite/reports).
=> JS: add js/sensitive-get-query query

ruby/ql/src/queries/analysis/Definitions.ql
Avoids computing this large set:
```
[2021-11-12 14:31:11] (542s) Tuple counts for Definitions::definitionOf#ff#min_term/5@cc3ffc after 2m10s:
337397265 ~3%     {5} r1 = JOIN Definitions::definitionOf#ff#shared WITH Module::Cached::resolveConstant#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'arg0', Lhs.2 'arg3', Lhs.1 'arg4', Lhs.2 'arg3', Lhs.1 'arg4'
return r1
```
=> Ruby: Fix performance problem in `Definitions.ql`

cpp/change-notes/2021-11-09-use-of-http.md, cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.cpp, cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.qhelp, cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.ql, cpp/ql/test/query-tests/Security/CWE/CWE-319/UseOfHttp/UseOfHttp.expected, cpp/ql/test/query-tests/Security/CWE/CWE-319/UseOfHttp/UseOfHttp.qlref, cpp/ql/test/query-tests/Security/CWE/CWE-319/UseOfHttp/test.cpp
This is a new query for spotting uses of `http` (rather than `https`), which along with another query will provide us a basis to claim partial coverage of [OWASP A08:2021](https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/).  The code and `qhelp` is derived from `java/non-https-url` but simplified in several places.
In addition to the tests you can view some results on LGTM at: https://lgtm.com/query/1597019895252712493/
Performance seems fine locally and I have no reason to be concerned about it.
I'm keen to discuss the right precision and severity (and other tags) for this query in addition to any suggestions you have for the query itself.
=> C++: New query 'Failure to use HTTPS URLs'

javascript/ql/lib/semmle/javascript/ApiGraphs.qll, javascript/ql/lib/semmle/javascript/Promises.qll, javascript/ql/test/ApiGraphs/async-await/tst.ts
The original motivation for this PR was to teach the API-graphs library to properly handle promises being returned from an `async` function. These don't get double-wrapped into another layer of promises, but are copied into the result object. Our library already provides a way of modelling that via a `loadStoreStep`, but such steps were not previously taken into account by the API-graphs library.
With this PR, they are respected when computing use nodes, not just for the promise-related pseudo-properties but for all properties (though I'm not sure to what extent that matters in practice). I haven't looked into the corresponding change for def nodes yet.
@erik-krogh has kindly done a performance evaluation, which looks reasonable (after the second commit anyway).
=> JavaScript: Improve support for copied properties in API graphs

python/ql/src/Security/CWE-295/RequestWithoutValidation.ql, python/ql/test/query-tests/Security/CWE-295-RequestWithoutValidation/RequestWithoutValidation.expected, python/ql/test/query-tests/Security/CWE-295-RequestWithoutValidation/make_request.py, python/ql/test/query-tests/Security/CWE-295-RequestWithoutValidation/options
For my reviewer: I'm don't feel like this should require adding a change note, but happy to do so if you think that's better :blush: (so didn't add the `no-change-note-required` label to the PR yet)
=> Python: Port `py/request-without-cert-validation` to use API graphs

python/ql/lib/semmle/python/frameworks/Stdlib.qll, python/ql/test/library-tests/frameworks/stdlib/Decoding.py, python/ql/test/library-tests/frameworks/stdlib/Encoding.py
New in Python 3.10
See
- https://devdocs.io/python~3.10/library/base64#base64.b32hexencode
- https://devdocs.io/python~3.10/library/base64#base64.b32hexdecode
I just forgot in https://github.com/github/codeql/pull/7133 :facepalm:
=> Python: Model `b32hexencode`/`b32hexdecode`

java/ql/lib/semmle/code/java/dataflow/FlowSteps.qll, java/ql/lib/semmle/code/java/frameworks/android/AsyncTask.qll, java/ql/test/experimental/query-tests/security/CWE-200/SensitiveAndroidFileLeak.expected, java/ql/test/library-tests/frameworks/android/asynctask/Test.java, java/ql/test/library-tests/frameworks/android/asynctask/options, java/ql/test/library-tests/frameworks/android/asynctask/test.ql
This PR adds a new `AdditionalValueStep` for Android's `AsyncTask`. When `execute` or `executeOnExecutor` are called for a certain `AsyncTask`, their `params` argument flows (preserving value) to the `doInBackground` method of that `AsyncTask` implementation.
=> Java: Add AsyncTask additional value step

ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImpl.qll, ruby/ql/test/library-tests/controlflow/graph/Cfg.expected, ruby/ql/test/library-tests/controlflow/graph/cfg.rb
Found by https://github.com/github/codeql/pull/7130.
=> Ruby: Add missing CFG entry for `ForwardParameter`

csharp/ql/src/Bad Practices/Implementation Hiding/ExposeRepresentation.ql
This change avoids the computation of an expensive transitive closure:
```
ExposeRepresentation.ql-32:DataFlowPublic::localExprFlow#ff .......................................................................................... 3m50s
ExposeRepresentation.ql-32:DataFlowPublic::localExprFlow#ff_10#join_rhs .............................................................................. 2m7s
```
Similar to https://github.com/github/codeql/pull/6885.
=> C#: Replace `localFlow` with `localFlowStep` in recursive predicate

ruby/ql/lib/codeql/ruby/ast/internal/Module.qll
```
[2021-11-12 14:06:22] (173s) Starting to evaluate predicate Module::Cached::resolveConstant#ff#antijoin_rhs/3@bde997
[2021-11-12 14:07:35] (246s) Tuple counts for Module::Cached::resolveConstant#ff#antijoin_rhs/3@bde997 after 1m13s:
926812246 ~0%     {4} r1 = JOIN Module::Cached::resolveConstant#ff#shared WITH Module::constantDefinition0#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1 'arg1', Lhs.0 'arg0', Lhs.2 'arg2'
0         ~0%     {3} r2 = JOIN r1 WITH Module::ClassDeclaration::getSuperclassExpr_dispred#ff ON FIRST 2 OUTPUT Lhs.2 'arg0', Lhs.1 'arg1', Lhs.3 'arg2'
0         ~0%     {3} r3 = JOIN r1 WITH Constant::ConstantAccess::getScopeExpr_dispred#ff ON FIRST 2 OUTPUT Lhs.2 'arg0', Lhs.1 'arg1', Lhs.3 'arg2'
0         ~0%     {3} r4 = r2 UNION r3
return r4
```
=> Ruby: Fix bad join-order in `resolveConstant`

javascript/ql/lib/semmle/javascript/PackageExports.qll, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialBackTracking.expected, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialReDoS.expected, javascript/ql/test/query-tests/Performance/ReDoS/lib/indirect.js, javascript/ql/test/query-tests/Performance/ReDoS/lib/lib.js
Gets a TP/TN for CVE-2021-3820. 
[Here is a real example of that pattern](https://github.com/pksunkara/inflect/blob/c025e153df847bbb2873ae75b1a7bd77b0526745/lib/inflect.js).  
[Evaluation looks OK](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/functionExport__default__CustomSuite/reports).  
No change in results.
=> JS: recognize library inputs when the library exports "through" a function

cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.ql
Minor improvements to the query recently added in https://github.com/github/codeql/pull/7094:
- add a CWE tag that should effectively associate the query with OWASP A8.
- add a few more sinks (functions that take a URL as a parameter).
=> C++: Minor improvements to 'Failure to use HTTPS URLs' query

ruby/generator/src/main.rs, ruby/generator/src/ql.rs, ruby/generator/src/ql_gen.rs, ruby/ql/lib/codeql/ruby/ast/internal/TreeSitter.qll
This avoids name clashes in case the tree-sitter grammar contains rules with the same name as the classes exported by the Locations module (e.g. `File`, `Location`, etc.).
=> Ruby: QL generator: use qualified imports

java/change-notes/2021-11-15-overrides.md, java/ql/lib/semmle/code/java/Member.qll, java/ql/lib/semmle/code/java/deadcode/EntryPoints.qll, java/ql/lib/semmle/code/java/deadcode/StrutsEntryPoints.qll, java/ql/lib/semmle/code/java/frameworks/Thrift.qll, java/ql/lib/semmle/code/java/frameworks/javaee/ejb/EJB.qll, java/ql/src/Likely Bugs/Concurrency/NonSynchronizedOverride.ql, java/ql/src/Likely Bugs/Inheritance/NoNonFinalInConstructor.ql, java/ql/test/library-tests/overrides/ConstructedOverrides2.expected
The `Method.overrides(Method)` relation was accidentally transitive. This has been a minor bit of technical debt for a long time, but isn't expected to have much impact as uses are mostly of the transitive form `a.overrides*(b)` and the qldoc has been claiming that only direct overrides were being included.
=> Java: Fix overrides to not be transitive.

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/frameworks/ActiveStorage.qll, ruby/ql/lib/codeql/ruby/frameworks/Files.qll, ruby/ql/lib/codeql/ruby/frameworks/StandardLibrary.qll
This lets us tidy up a few places where we have a `DataFlow::CallNode` with an underlying `MethodCall`, but have to do a clumsy `node.asExpr().getExpr().(MethodCall)` cast in order to get the name of the called method.
=> Ruby: add `getMethodName` predicate to `DataFlow::CallNode` class

cpp/ql/lib/semmle/code/cpp/models/implementations/Iterator.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/localFlow.expected, cpp/ql/test/library-tests/dataflow/fields/path-flow.expected, cpp/ql/test/library-tests/dataflow/taint-tests/localTaint.expected, cpp/ql/test/library-tests/types/__wchar_t/wchar_t.expected, cpp/ql/test/library-tests/types/wchar_t_typedef/wchar_t.expected, cpp/ql/test/library-tests/variables/variables/types.expected, cpp/ql/test/query-tests/Likely Bugs/Conversion/CastArrayPointerArithmetic/CastArrayPointerArithmetic.expected
In order to figure out which parameters can carry flow out of a function, we have a predicate `parameterIsNonConstReference`. That predicate handles pointers and iterators in one case (since pointers are also iterators [thanks to the T* specialization of iterator_traits](https://en.cppreference.com/w/cpp/iterator/iterator_traits)).
However, if that specialization isn't in the database for some reason, we won't always recognize that a parameter is of a type that can carry flow out of a function.
This PR adds a subclass of our modeling of `iterator` so that pointers are always a possible iterator.
=> C++: Always recognize pointers as iterators

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/lib/semmle/code/csharp/frameworks/EntityFramework.qll, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.cs, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.expected, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.ql, csharp/ql/test/library-tests/dataflow/local/TaintTrackingStep.expected, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, java/ql/test/library-tests/dataflow/callback-dispatch/A.java, java/ql/test/library-tests/frameworks/stream/Test.java, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
This PR restricts how we generate [derived flow summaries](https://github.com/github/codeql/pull/6767), to avoid [spurious flow](https://github.com/github/codeql/pull/6841).
For derived fluent flow, this is now restricted to summaries where a parameter is returned (possibly in a (nested) field).
For derived flow through callback parameters, this is now restricted to summaries that are not themselves derived.
=> Data flow: Restrict derived flow summaries

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointScoring.qll
Using `rank[1]` is inefficient compared to using `min()`, and it does exactly the same. 
Found while doing a "dist-upgrade" with ql-for-ql.
=> ATM: use min() instead of rank[1]

csharp/ql/lib/semmle/code/csharp/controlflow/ControlFlowGraph.qll, csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImpl.qll, csharp/ql/test/library-tests/controlflow/graph/BasicBlock.expected, csharp/ql/test/library-tests/controlflow/graph/Dominance.expected, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected
With this PR we maintain the invariant that each CFG scope has both an entry node and an exit node (for static initializers we previously didn't have an exit node).
Identified by https://github.com/github/codeql/pull/7130.
=> C#: Extend `(Annotated)ExitNode` to also cover static fields

cpp/ql/src/Security/CWE/CWE-313/CleartextSqliteDatabase.ql, java/ql/src/experimental/Security/CWE/CWE-598/SensitiveGetQuery.ql, javascript/ql/lib/semmle/javascript/frameworks/AngularJS/AngularJSExpressions.qll, javascript/ql/lib/semmle/javascript/frameworks/ClientRequests.qll, javascript/ql/lib/semmle/javascript/frameworks/NodeJSLib.qll, javascript/ql/lib/semmle/javascript/security/dataflow/XssThroughDomCustomizations.qll, javascript/ql/src/Expressions/UnknownDirective.ql, javascript/ql/test/library-tests/RangeAnalysis/DeadBranch.ql, javascript/ql/test/library-tests/StringConcatenation/ClassContainsTwo.ql, javascript/ql/test/library-tests/StringConcatenation/ContainsTwo.ql, ruby/ql/src/queries/security/cwe-798/HardcodedCredentials.ql
The `matches` predicate has better performance, so it should be used when possible. 
The patch was written automatically by a tool. 
Evalutions (see backrefs) look OK.
=> use matches instead of regexpMatch/prefix/suffix

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaImplCommon.qll, csharp/ql/lib/semmle/code/cil/internal/SsaImplCommon.qll, csharp/ql/lib/semmle/code/csharp/controlflow/internal/pressa/SsaImplCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImplCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/SsaImplSpecific.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/basessa/SsaImplCommon.qll, ruby/ql/consistency-queries/SsaConsistency.ql, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImplCommon.qll
This makes the consistency queries available for other languages too (cc @MathiasVP).
=> Ruby: Move SSA consistency queries into shared SSA library

java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, java/ql/test/library-tests/dataflow/callback-dispatch/A.java
Store steps in summaries aren't likely to be intended to clear the targeted content (also, this currently doesn't even work consistently). This caused false negative flow for any field-of-argument-to-callback summary as these summaries simply didn't work.
This fix could alternatively have been achieved by changing the synthesised read-/store-steps such that more store steps would be inferred as side-effects through reverse reads, but that seemed unnecessarily complicated.
=> Java: Don't clear content in store steps in summaries.

ruby/ql/lib/codeql/ruby/frameworks/ActiveStorage.qll, ruby/ql/lib/codeql/ruby/frameworks/Files.qll, ruby/ql/lib/codeql/ruby/frameworks/StandardLibrary.qll, ruby/ql/lib/codeql/ruby/security/UrlRedirectCustomizations.qll, ruby/ql/src/ide-contextual-queries/printAst.ql, ruby/ql/src/queries/security/cwe-078/KernelOpen.ql
QLDoc for classes should generally start with A/An/The.  
I found a few violations of that during a dist-upgrade of `codeql-ql`.  
Ruby was the worst offender, so I tried to fix them for you.
=> Ruby: use A/An/The to start qlDoc for classes

csharp/ql/lib/semmle/code/dotnet/Element.qll
The optimizer decides to push in this magic context into `Element::getLocation`:
```
m#Element::Element::getLocation_dispred#bf(/* Element::Element */ cached unique entity this)
:-
exists(/* Assignment::AssignExpr */ cached dontcare entity _,
cached dontcare string _1 |
rec #select#cpe#134#fff(_, this, _1)
);
...
```
which makes `StructuralComparisonConfig::candidate` recursive, and perform extremely bad:
```
SelfAssignment.ql-14:StructuralComparison::StructuralComparisonConfiguration::candidate_dispred#fff ...................................................................................................................................................... 35m14s (4 evaluations with max 35m14s in StructuralComparison::StructuralComparisonConfiguration::candidate_dispred#fff/3@i6#ad086iwe) …
```
=> C#: Fix bad magic `Element::fromSource` in context of `SelfAssignment.ql`

docs/codeql/support/reusables/versions-compilers.rst
Also fixes a typo `.xhm` -> `.xhtm`
=> JS: Mention .hbs, .ejs, and .njk file extensions

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/BaseScoring.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointScoring.qll
This PR renames the `adaptiveThreatModelingModels` external predicate to `availableMlModels` per the internal ADR backlinked below.
=> JS: [Internal only] Rename the available ML models external predicate

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
Same as e.g. https://github.com/github/codeql/pull/6777/commits/ec5d8ab2dbb3c2b38252cddb88808936225eae75.
=> Ruby: Restrict use-use flow

ruby/ql/lib/codeql/ruby/controlflow/internal/Splitting.qll
Thanks to @erik-krogh for spotting this.
=> Ruby: Remove CP in `EnsureSplitImpl::exit/3`

ruby/change-notes/2021-11-04-csrf-protection-disabled.md, ruby/ql/lib/codeql/ruby/Concepts.qll, ruby/ql/lib/codeql/ruby/Frameworks.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/lib/codeql/ruby/frameworks/Rails.qll, ruby/ql/src/queries/security/cwe-352/CSRFProtectionDisabled.qhelp, ruby/ql/src/queries/security/cwe-352/CSRFProtectionDisabled.ql, ruby/ql/src/queries/security/cwe-352/examples/UsersController.rb, ruby/ql/test/query-tests/security/cwe-352/CSRFProtectionDisabled.expected, ruby/ql/test/query-tests/security/cwe-352/CSRFProtectionDisabled.qlref, ruby/ql/test/query-tests/security/cwe-352/railsapp/app/controllers/application_controller.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/app/controllers/users_controller.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/config/application.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/config/environment.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/config/environments/development.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/config/environments/production.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/config/environments/test.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/test/controllers/users_controller_test.rb
Finds cases in Rails apps where either `config.action_controller.allow_forgery_protection` is set to `false`, or where token verification is disabled in a controller through `skip_forgery_protection` or `skip_before_action :verify_authenticity_token`.
The bulk of this PR is modelling some core Rails classes and methods. This is separated out from the rest of the `ActiveRecord`, `ActionController`, etc. modelling as it's not generally specific to any one of them.
I suspect that the `@security-severity` on this may be a bit high - since CSRF protection is enabled by default in Rails, the cases where it's explicitly turned off tend to be deliberate, and there are often custom protections in place that this query can't detect. 
Despite this, I think the query is worth including. Because CSRF …
=> Ruby: Add `rb/csrf-protection-disabled` query

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/test/library-tests/dataflow/fields/ir-path-flow.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/ArithmeticUncontrolled/ArithmeticUncontrolled.expected, cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/TaintedAllocationSize/TaintedAllocationSize.expected
When looking at the paths after we merged https://github.com/github/codeql/pull/7188, I noticed that they're awfully long:
It turns out many of those nodes are just conversions during `storeStep`s and `readStep`s. This PR hides those dataflow nodes so the path is much shorter and more readable:
=> C++: Hide some IR dataflow nodes

python/ql/src/Security/CWE-022/PathInjection.ql, python/ql/src/Security/CWE-078/CommandInjection.ql, python/ql/src/Security/CWE-089/SqlInjection.ql, python/ql/src/Security/CWE-094/CodeInjection.ql, ruby/ql/src/queries/security/cwe-089/SqlInjection.ql, ruby/ql/src/queries/security/cwe-094/CodeInjection.ql
These are no longer correct, since the A1 category changed from 2017 to
2021, see https://owasp.org/Top10/#whats-changed-in-the-top-10-for-2021
Since only a very few queries had these tags, I think we're much better
off having them removed.
=> Python/Ruby: Remove owasp tags

.github/workflows/ruby-dataset-measure.yml, .github/workflows/ruby-qltest.yml, ruby/Makefile, ruby/doc/HOWTO.md
The CI jobs should use a freshly built extractor and not rely on the Ruby extractor bundled with the CodeQL CLI.
@dbartol
=> Ruby: fix CI jobs after removal of `.codeql-manifest.json`

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl2.qll
This is a sequence of smaller performance tweaks (commit-by-commit review is encouraged). All of them relate to reducing work by avoiding splits of the tuple stream in the main recursive pipelines. Either by making sure negations are simple anti-joins (thereby also avoiding materialisation) or by avoiding tuple duplication arising from disjunctive filters.
=> Data flow: Performance tuning

javascript/ql/experimental/adaptivethreatmodeling/src/.gitignore, javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml
This will allow us to resolve the ATM machine learning models that will be distributed within this pack.
=> JS: [Internal only] Add ML models specification to ATM query pack definition

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplConsistency.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowPrivate.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplConsistency.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplConsistency.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplConsistency.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplConsistency.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll, ruby/ql/consistency-queries/DataFlowConsistency.ql, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplConsistency.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
This will allow for more fine-grained per-language configuration of the consistency queries. Currently, only two consistency queries can be controlled, but we can easily add support for others.
Ruby appears to be the only language that uses a "real" consistency query, so there I could move the configuration into the query itself. For the other languages I simply added it to `DataFlowPrivate.qll`; but consider moving it when/if switching over to `--consistency-queries` based approach.
=> Data flow: Introduce `ConsistencyConfiguration` class

csharp/ql/test/library-tests/dataflow/library/FlowSummaries.expected, csharp/ql/test/library-tests/frameworks/EntityFramework/FlowSummaries.expected, csharp/ql/test/shared/FlowSummaries.qll
In this PR we narrow the flow summaries produced by the test(s) to include summaries for declarations that are effectively public.
=> C#: Only include effectively public declarations in flow summaries

python/change-notes/2021-11-12-fix-pyhton-query-ids.md, python/ql/src/Security/CWE-020-ExternalAPIs/ExternalAPIsUsedWithUntrustedData.ql, python/ql/src/Security/CWE-020-ExternalAPIs/UntrustedDataToExternalAPI.ql, python/ql/src/analysis/LocalDefinitions.ql, python/ql/src/analysis/LocalReferences.ql
The two queries in CWE-020 are used for manual evaluation (is my
understanding), and the two IDE queries should work based on their tags,
and not on the query-id.
We should get a sign-off on both of them just to be sure though.
- @aeisenberg are you in a position to review IDE part? (or find someone that can)
- @lcartey can you confirm that changing the `id` for the External APIs queries is not going to be a problem?
Thanks :blush:
=> Python: Fix some query-ids

java/change-notes/2021-19-29-improved-ratpack-support.md, java/ql/lib/semmle/code/java/frameworks/ratpack/Ratpack.qll, java/ql/lib/semmle/code/java/frameworks/ratpack/RatpackExec.qll, java/ql/test/library-tests/frameworks/ratpack/resources/PairTest.java, java/ql/test/library-tests/frameworks/ratpack/resources/Resource.java, java/ql/test/stubs/ratpack-1.9.x/ratpack/exec/Operation.java, java/ql/test/stubs/ratpack-1.9.x/ratpack/exec/Promise.java, java/ql/test/stubs/ratpack-1.9.x/ratpack/exec/Result.java, java/ql/test/stubs/ratpack-1.9.x/ratpack/func/Block.java, java/ql/test/stubs/ratpack-1.9.x/ratpack/func/Pair.java
Adds models for `ratpack.func.Pair`, and `ratpack.exec.Result`.
Improve models for `ratpack.exec.Promise`.
=> Java: Ratpack HTTP Framework Additional Modeling

cpp/change-notes/2021-11-25-certificate-result-conflation.md, cpp/ql/src/Security/CWE/CWE-295/SSLResultConflation.qhelp, cpp/ql/src/Security/CWE/CWE-295/SSLResultConflation.ql, cpp/ql/src/Security/CWE/CWE-295/SSLResultConflationBad.cpp, cpp/ql/src/Security/CWE/CWE-295/SSLResultConflationGood.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-295/SSLResultConflation.expected, cpp/ql/test/query-tests/Security/CWE/CWE-295/SSLResultConflation.qlref, cpp/ql/test/query-tests/Security/CWE/CWE-295/test.cpp
This is the first of two new queries for [CWE-295: Improper Certificate Validation](https://cwe.mitre.org/data/definitions/295.html).
Results:
- [on all LGTM C/C++ projects](https://lgtm.com/query/1243915003686309152/); very thin (only 1 result).
- this is disappointing, but the query does cover 2 of the 5 examples given in the CWE definition.
Precision:
- provisionally set to `@medium`, it's difficult to judge without seeing more real world results.
Performance:
- tested locally on `kamailio_kamailio` and `chakra-core` (performance is great with a warmed up cache)
- no timeouts on the above LGTM run.
=> C++: New query for SSL result conflation

csharp/ql/src/Stubs/helpers.py, csharp/ql/src/Stubs/make_stubs_nuget.py, csharp/ql/test/resources/stubs/_frameworks/Microsoft.NETCore.App/System.Runtime.cs
- Hardcode that we target the .NET 5.0 framework independently of what is the default on the machine, where the script is executed.
- Create a global.json file which hardcoded the use SDK to 5.0.402.
- Other minor changes.
=> C#: Update the make_stubs_nuget script

csharp/ql/lib/semmle/code/csharp/frameworks/JsonNET.qll
See
- https://www.newtonsoft.com/json/help/html/Overload_Newtonsoft_Json_JsonSerializer_Serialize.htm
- https://www.newtonsoft.com/json/help/html/Overload_Newtonsoft_Json_JsonSerializer_Deserialize.htm
Found via https://github.com/github/codeql/pull/7231.
=> C#: Fix `Newtonsoft.Json.JsonSerializer.{Deserialize,Serialize}` summaries

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected, csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.ql, csharp/ql/test/shared/FlowSummaries.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
In this PR we introduce a new test case for flow summaries.
The idea is, that we filter out all summaries for interface implementations and overrides.
This will become relevant, when we want to use the flow summaries produced by the test to replace the existing models.
=> C#: Filtered flow summaries

python/ql/test/experimental/dataflow/tainttracking/commonSanitizer/test_string_const_compare.py, python/ql/test/query-tests/Security/CWE-022-PathInjection/PathInjection.expected, python/ql/test/query-tests/Security/CWE-022-PathInjection/path_injection.py
Fixing this problem is not 100% trivial. We want to track iterables that only contain string constants throughout the program (easy with type-tracking), but we probably don't want to include those that could have been modified... I don't want to go down the rabbit whole of doing that implementation right now, so this PR only adds tests cases.
=> Python: Add `x in <var>` test for StringConstCompare 

cpp/ql/src/Likely Bugs/Protocols/TlsSettingsMisconfiguration.ql, cpp/ql/src/Likely Bugs/Protocols/UseOfDeprecatedHardcodedProtocol.ql, cpp/ql/src/Security/CWE/CWE-311/CleartextFileWrite.ql
Add [CWE-326: Inadequate Encryption Strength](https://cwe.mitre.org/data/definitions/326.html) tag to `cpp/boost/tls-settings-misconfiguration`.  This query previously had the `security` tag but no specific CWE, and this is the closest one I can find.  The query is about using `boost::asio` for TLS or SSLv23 without disabling deprecated protocols such as TLS 1.1.
Add [CWE-327: Use of a Broken or Risky Cryptographic Algorithm](https://cwe.mitre.org/data/definitions/327.html) tag to `cpp/boost/use-of-deprecated-hardcoded-security-protocol`.  This query previously had the `security` tag but no specific CWE, and this is the closest one I can find.  The query is about explicitly specifying a deprecated protocol such as SSLv2 with the `boost::asio` library.
Add [CWE-260: Password in …
=> C++: Add CWE tags to some queries.

csharp/ql/test/library-tests/dataflow/library/FlowSummaries.expected, csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected, csharp/ql/test/shared/FlowSummaries.qll
Avoid printing whitespace between types to make the printed string in the flow summaries test parseable as a flow summary.
=> C#: Modify printing of flow summaries in test.

csharp/ql/lib/semmle/code/csharp/dataflow/ExternalFlow.qll, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.cs, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.expected, csharp/ql/test/library-tests/dataflow/external-models/ExternalFlow.ql
In this PR we make it possible to define flow for the backing methods for property methods for getting and setting values.
These were discarded prior to this to change as they were not "Members".
=> C#: Make it possible to define flow for property backing methods.

ruby/ql/test/library-tests/controlflow/graph/Cfg.expected, ruby/ql/test/library-tests/controlflow/graph/Nodes.expected, ruby/ql/test/library-tests/controlflow/graph/ifs.rb
Turns out we didn't have this already.
=> Ruby: Add CFG test for `||`

ruby/Cargo.lock, ruby/extractor/Cargo.toml, ruby/generator/Cargo.toml, ruby/ql/lib/codeql/ruby/ast/Pattern.qll, ruby/ql/lib/codeql/ruby/ast/internal/AST.qll, ruby/ql/lib/codeql/ruby/ast/internal/Pattern.qll, ruby/ql/lib/codeql/ruby/ast/internal/TreeSitter.qll, ruby/ql/lib/ruby.dbscheme, ruby/ql/lib/upgrades/acae5775e0732c3d5c28428ea7428a7cba5311a5/old.dbscheme, ruby/ql/lib/upgrades/acae5775e0732c3d5c28428ea7428a7cba5311a5/ruby.dbscheme, ruby/ql/lib/upgrades/acae5775e0732c3d5c28428ea7428a7cba5311a5/upgrade.properties, ruby/ql/test/library-tests/ast/Ast.expected, ruby/ql/test/library-tests/ast/ValueText.expected, ruby/ql/test/library-tests/ast/control/CaseExpr.expected, ruby/ql/test/library-tests/ast/control/ControlExpr.expected, ruby/ql/test/library-tests/ast/control/cases.rb
This pull request updates the grammar and adds a class for `ParenthesizedPattern`s.
=> Ruby: parenthesized patterns

ruby/ql/lib/codeql/ruby/frameworks/Files.qll, ruby/ql/test/library-tests/frameworks/files/Files.expected, ruby/ql/test/library-tests/frameworks/files/Files.ql
The main aim here is to consider expressions like `IO.new(IO.sysopen("foo.txt", "r"), "r").read` as potential reads from a file. We previously would not have considered this as a file read because `IO.new(IO.sysopen("foo.txt", "r"), "r")` was assumed to be some non-file input source. In other words, this changes from under-approximating possible file reads for these cases to over-approximating them.
There is some minor restructuring here to support this. In particular, `IOReader` only deals with the `IO` module directly, and `FileReader` is the new name for `IOFileReader` (extended, as mentioned above).
Separately, calls to `{IO,File}::try_convert` are no longer considered as a potential `IO`/`File` read nodes. Rather, they potentially return an `IO`/`File` instance.
=> Ruby: Extend `FileSystemReadAccess` to include more potential sources of input from the filesystem

cpp/ql/src/experimental/Security/CWE/CWE-703/FindIncorrectlyUsedExceptions.ql, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-703/semmle/tests/FindIncorrectlyUsedExceptions.expected
good day @geoffw0
I want to make changes to this request.
to qualify for the reward program, thank you.
=> fix request for cpp exceptions

java/ql/src/Security/CWE/CWE-327/BrokenCryptoAlgorithm.ql, java/ql/src/Security/CWE/CWE-327/MaybeBrokenCryptoAlgorithm.ql
CWE-328: Use of Weak Hash, see https://cwe.mitre.org/data/definitions/328.html
Since weak hash functions (md5/sha1) are considered for the
`java/weak-cryptographic-algorithm` query. See
https://github.com/github/codeql/blob/caeeebf572f84f428476ec36745c832f21c8e5c0/java/ql/lib/semmle/code/java/security/Encryption.qll#L148
To keep things consistent between `java/weak-cryptographic-algorithm`
and `java/potentially-weak-cryptographic-algorithm`, I also added the
tag to the latter.
=> Java: Tag queries with CWE-328

ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImpl.qll, ruby/ql/test/library-tests/controlflow/graph/Cfg.expected
Empty StmtSequences appear, for example, in the `else` branch of `if`
statements like the following:
foo
if cond
bar
else
end
baz
Before this change, the CFG for this code would look like this:
foo
│
│
▼
cond
│
true │
▼
bar
│
│
▼
if
│
│
▼
baz
i.e. there is linear flow through the condition, the `then` branch, and
out of the if. This doesn't account for the possibility that the
condition is false and `bar` is not executed. After this change, the CFG
looks like this:
foo
│
│
▼
cond
│    │
true │    │ false
▼    │
bar   │
│    │
│    │
▼    ▼
if
│
│
▼
baz
i.e. we correctly account for the `false` condition.
=> Ruby: Include empty StmtSequences in CFG

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
Use `abstract` predicates internally, and make `ParameterNode::getParameter` `final`.
=> Ruby: Restructure `ParameterNode(Impl)`

ruby/ql/lib/codeql/ruby/security/XSS.qll
These classes were introducing dependency cycles during type compilation. This only even compiled due to a bug in the compiler: https://github.com/github/semmle-code/pull/41019
The problem (by example) is this: `ReflectedXSS::Sink` is an abstract class with only one extension (`ReflectedXSS::AnySink`). Therefore, computing this type requires calculating the type `ReflectedXSS::AnySink` first. At the same time, `ReflectedXSS::AnySink` is `instanceof Shared::Sink`, so that type needs to be calculated first. But then `Shared::Sink` is also abstract and requires `ReflectedXSS::Sink`, introducing a cycle.
These classes aren'y currently used, so I just removed them. Feel free to suggest a better approach.
This seems to be the only case of that pattern occurring in existing QL code, so it is …
=> fix dependency cycle by removing superfluous classes

csharp/ql/lib/semmle/code/csharp/dataflow/LibraryTypeDataFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll, csharp/ql/test/library-tests/dataflow/global/DataFlowPath.expected, csharp/ql/test/library-tests/dataflow/global/TaintTrackingPath.expected, csharp/ql/test/library-tests/dataflow/library/FlowSummaries.expected, csharp/ql/test/library-tests/dataflow/library/FlowSummariesFiltered.expected
Introduce the notion of synthetic fields for C# flow summaries (based on the idea from already implemented in Java).
The need has arisen for this in C# to avoid referring to private fields in flow summaries as these might not be included during compilation (and thus included in the database), if reference assemblies are used during compilation (these are basically stubs).
On this PR we
- Introduce Synthetic fields for C#.
- Use synthetic fields for System.Threading.Tasks and friends.
- Add support for CSV flow summaries to use synthetic fields.
=> C#: Introduce synthetic fields and use them in Task<>.

python/ql/lib/semmle/python/essa/SsaCompute.qll
On `pritomrajkhowa/LoopBound`:
```
Definitions.ql-3:SsaCompute::SsaComputeImpl::AdjacentUsesImpl::adjacentUseUse#ff ................. 4m35s
```
specifically
```
(376s) Tuple counts for SsaCompute::SsaComputeImpl::AdjacentUsesImpl::adjacentUseUse#ff/2@be04e9kp after 4m58s:
388843     ~0%     {4} r1 = JOIN Essa::TPhiFunction#fff_2#join_rhs WITH SsaCompute::SsaComputeImpl::AdjacentUsesImpl::definesAt#ffff ON FIRST 1 OUTPUT Rhs.1, Lhs.0, Rhs.2, Rhs.3
3629812090 ~1%     {7} r2 = JOIN r1 WITH SsaCompute::SsaComputeImpl::variableUse#ffff ON FIRST 1 OUTPUT Lhs.0, Rhs.2, Rhs.3, Lhs.2, Lhs.3, Lhs.1, Rhs.1 'use1'
0          ~0%     {2} r3 = JOIN r2 WITH SsaCompute::SsaComputeImpl::AdjacentUsesImpl::adjacentVarRefs#fffff ON FIRST 5 OUTPUT Lhs.5, Lhs.6 'use1'
0          ~0%     {2} r4 = JOIN r3 WITH …
```
=> Python: Fix bad join in SSA

csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImplShared.qll, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplShared.qll
Finds nodes with multiple normal successors, where one is the special simple successor. For example, this would flag a node that has both a "simple" and a "true" successor.
=> Shared CFG: Add another consistency test

csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/NamedType.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/Type.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/UnknownType.cs, csharp/ql/lib/semmle/code/csharp/TypeRef.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/assemblies/assemblies.ql, csharp/ql/test/library-tests/expressions/PrintAst.expected, csharp/ql/test/library-tests/nestedtypes/PrintAst.expected, csharp/ql/test/library-tests/standalone/controlflow/cfg.expected, csharp/ql/test/library-tests/standalone/controlflow/cfg.ql, csharp/ql/test/library-tests/standalone/errorrecovery/ErrorTypes.expected
It turns out that this entity was never populated. It is required to avoid e.g. data-flow nodes without types.
Identified via https://github.com/github/codeql/pull/7231.
=> C#: Populate `UnknownType`

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointFeatures.qll, javascript/ql/lib/semmle/javascript/dependencies/FrameworkLibraries.qll
This PR attempts to improve the evaluation performance of the ATM queries and libraries, focused on slow bottlenecks that take 10s or more on a moderately large database.
Semantics should be largely unchanged, with the exception of a few places where I've used the strict version of aggregates, which will now have no results (rather than the unit of the aggregation operation) if there are no tuples satisfying the aggregation expressions.
Commit-wise review highly recommended. See commit descriptions and inline comments for further explanation of each change. Careful testing with the actual models against some candidate databases highly recommended, to make sure I haven't changed how features are represented.
=> JS/ATM: Various compilation fixes and performance improvements

python/ql/lib/semmle/python/pointsto/PointsTo.qll
From `pritomrajkhowa/LoopBound`:
```
Definitions.ql-7:PointsTo::PointsToInternal::scope_entry_points_to#ffff#antijoin_rhs#2 ........... 55.1s
```
specifically
```
(443s) Tuple counts for PointsTo::PointsToInternal::scope_entry_points_to#ffff#antijoin_rhs#2/3@74a7cart after 55.1s:
184070    ~0%        {3} r1 = JOIN PointsTo::PointsToInternal::scope_entry_points_to#ffff#shared#1 WITH Variables::GlobalVariable#class#f ON FIRST 1 OUTPUT Lhs.0 'arg2', Lhs.1 'arg0', Lhs.2 'arg1'
184070    ~0%        {3} r2 = STREAM DEDUP r1
919966523 ~2%        {4} r3 = JOIN r2 WITH Essa::EssaDefinition::getSourceVariable_dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1 'arg0', Lhs.2 'arg1', Lhs.0 'arg2'
4281779   ~2293%     {3} r4 = JOIN r3 WITH Essa::EssaVariable::getScope_dispred#ff ON FIRST 2 OUTPUT …
```
=> Python: Fix bad `scope_entry_points_to` join

python/ql/lib/semmle/python/pointsto/PointsTo.qll
From `pritomrajkhowa/LoopBound`:
```
Definitions.ql-7:PointsTo::InterProceduralPointsTo::callsite_points_to#ffff#join_rhs#3 ........... 5m53s
```
specifically
```
(767s) Tuple counts for PointsTo::InterProceduralPointsTo::callsite_points_to#ffff#join_rhs#3/3@f8f86764 after 5m53s:
832806293 ~0%     {4} r1 = JOIN PointsTo::InterProceduralPointsTo::callsite_points_to#ffff#shared#1 WITH PointsTo::InterProceduralPointsTo::var_at_exit#fff ON FIRST 1 OUTPUT Lhs.0, Lhs.1 'arg1', Rhs.1 'arg2', Rhs.2 'arg0'
832806293 ~0%     {3} r2 = JOIN r1 WITH Essa::TEssaNodeRefinement#ffff_03#join_rhs ON FIRST 2 OUTPUT Lhs.3 'arg0', Lhs.1 'arg1', Lhs.2 'arg2'
return r2
```
This one is a bit tricky to unpack. Where is this `shared#1` defined?
```
EVALUATE NONRECURSIVE RELATION:
SYNTHETIC …
```
=> Python: Fix bad `callsite_points_to` join

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/NosqlInjectionATM.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/SqlInjectionATM.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/StandardEndpointFilters.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/TaintedPathATM.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/XssATM.qll
Previously heuristic sinks were always included, to avoid us filtering them out due to not being an argument to an external library call. In this PR, we move the "argument to an external library call" filtering to the query-specific endpoint filters. This lets us filter out heuristic sinks if they match one of the other endpoint filters, reducing FPs.
=> JS: Improve handling of heuristic sinks in endpoint filters

ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/test/library-tests/frameworks/ActionController.expected, ruby/ql/test/library-tests/frameworks/ActionView.expected, ruby/ql/test/library-tests/frameworks/app/controllers/foo/bars_controller.rb
Private instance methods on ActionController classes aren't valid
request handlers. Routing to them will raise an exception.
=> Ruby: Don't count private methods as Rails actions

ruby/ql/lib/codeql/ruby/ApiGraphs.qll
This was using ES6 style class instantiation syntax.
=> Ruby: use Ruby object instantiation syntax in a comment

ruby/Cargo.lock, ruby/extractor/Cargo.toml, ruby/generator/Cargo.toml
Last time we let Dependabot bump `tracing-subscriber`, it caused build failures on Arm-based Macs, and we had to revert the change. Those issues now seem to be fixed.
I also ran `cargo-update` to pick up minor updates to other crates.
=> Ruby: update crate versions

javascript/ql/lib/semmle/javascript/dataflow/internal/InterProceduralTypeInference.qll, javascript/ql/test/library-tests/TypeInference/CallWithAnalyzedReturnFlow/CalleeNodeValue.expected, javascript/ql/test/library-tests/TypeInference/LocalFunction/LocalFunction.expected, javascript/ql/test/library-tests/TypeInference/LocalFunction/LocalFunction.js, javascript/ql/test/library-tests/TypeInference/LocalFunction/LocalFunction_arguments.js, javascript/ql/test/query-tests/Expressions/SuspiciousInvocation/SuspiciousInvocation.expected
To improve inter-procedural type inference for FunctionExpr.
codeql conduct an [Inter-procedural type inference](https://github.com/github/codeql/blob/753d886b0dd8217cfa3fafcc36afd9de9a2aed26/javascript/ql/lib/semmle/javascript/dataflow/internal/InterProceduralTypeInference.qll#L194) for `LocalFunction` .  But `LocalFunction` represents `FunctionDeclStmt` which is only called once locally, so we can easily handle the case below. 
```javascript
function f(source){return source;}
function c(source){return source;}
var sink = c(f)(easySource);
```
But codeql can not handle the case below. Function c is declare by a `FunctionExpr`. 
```javascript
function f(source){return source;}
var c = function c(source){return source;}
var sink = c(f)(easySource);
```
This usage is common so I improve it …
=> JS: Improve inter-procedural type inference for FunctionExpr

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/CoreKnowledge.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/FilteringReasons.qll, javascript/ql/lib/semmle/javascript/frameworks/ExpressModules.qll, javascript/ql/lib/semmle/javascript/frameworks/NoSQL.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/express.js, javascript/ql/test/query-tests/Security/CWE-089/untyped/DatabaseAccesses.expected
Based on sheet `atm-results (2021-12-08)`: 
- 66 triaged results
- 45 addressed FP results: should disappear
- Primary approach: extend the endpoint filters directly
- Secondary approach: model more database accesses
The secondary approach requires some manual result inspection, especially for the missing rate-limiting query.
Core library changes:
- More database accesses recognized (redis, ioredis, marsdb)
- The `express-fileupload` `mv` function has a path-injection sink
=> ATM Endpoint filtering improvements

java/ql/src/experimental/Security/CWE/CWE-020/Log4jJndiInjection.java, java/ql/src/experimental/Security/CWE/CWE-020/Log4jJndiInjection.qhelp, java/ql/src/experimental/Security/CWE/CWE-020/Log4jJndiInjection.ql
This is an experimental query for detecting CVE-2021-44228.
=> Java: Experimental query for Log4j JNDI Injection

java/ql/src/experimental/Security/CWE/CWE-020/Log4jJndiInjection.ql
Just a tiny tweak to how this query will appear in code scanning (follow-up to https://github.com/github/codeql/pull/7354)
=> Clarify Log4jJndiInjection.ql query name and help

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/frameworks/Rails.qll, ruby/ql/lib/codeql/ruby/frameworks/StandardLibrary.qll
I've run into a few more cases where these predicates would be convenient, so it seems to make sense to put them in `DataFlow::CallNode` itself.
=> Ruby: Add `getBlock` and `getNumberOfArguments` predicates to `DataFlow::CallNode`

cpp/ql/src/Likely Bugs/Arithmetic/ComparisonWithCancelingSubExpr.ql, cpp/ql/src/Likely Bugs/Arithmetic/PointlessSelfComparison.qll, cpp/ql/test/query-tests/Likely Bugs/Arithmetic/BadAdditionOverflowCheck/PointlessSelfComparison.expected, cpp/ql/test/query-tests/Likely Bugs/Arithmetic/BadAdditionOverflowCheck/templates.cpp
Fixes https://github.com/github/codeql/issues/7385.
Initially, I wanted to add this case to `Expr.isUnevaluated` since that would make this fix apply more broadly. But I guess, `Expr.isUnevaluated` shouldn't hold for things that are evaluated _at compile-time only_. So for now I've just special-cased this in the query containing the actual FP report.
=> C++: Fix FP in `cpp/comparison-of-identical-expressions`

java/change-notes/2021-06-17-tainted-field-read-step-on-entrypoint-types.md, java/ql/lib/change-notes/2021-12-15-tainted-field-read-step-on-entrypoint-types.md, java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll, java/ql/test/library-tests/dataflow/entrypoint-types/EntryPointTypesTest.java, java/ql/test/library-tests/dataflow/entrypoint-types/EntryPointTypesTest.ql
This PR adds an additional taint step between remote source `Parameter` types (e.g. parameters of a `JAX-RS` resource method) and field reads on said types (either directly or through getters).
Credits to @pwntester for the solution proposal.
=> Java: Preserve taint on field-read-steps on entrypoint types

javascript/ql/lib/javascript.qll, javascript/ql/lib/semmle/javascript/frameworks/TrustedTypes.qll, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/trusted-types.js
Treats a value being boxed in a trusted type as a sink. Concretely, we use the return value from the policy callback as a sink:
```js
trustedTypes.createPolicy('foo', { createHTML: x => /* sink */ })
```
Adding this since it was requested in https://github.com/github/codeql/issues/7336 - previously I have been hesitant to do this due lack of real-world examples of trusted types.
The only uses of trusted types I could find had flow around the policy invocation to the true sink,
```js
const policy = trustedTypes?.createPolicy('something', { createHTML: x => x });
...
function foo(data) {
if (policy != null) { data = policy.createHTML(data); } // new sink here
...
elm.innerHTML = data; // but also flow to the usual sink
}
```
For cases like this, we just get an alert for both sinks. But in …
=> JS: Use return value of trusted type policy callback as a sink

javascript/ql/lib/semmle/javascript/dataflow/internal/CallGraphs.qll, javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/library-tests/TaintTracking/DataFlowTracking.expected, javascript/ql/test/library-tests/TaintTracking/factory-function.js
Fixes https://github.com/github/codeql/issues/7106 by tracking functions with methods.
Evaluations:
- [Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/track-functions__default__dist-compare__3/reports) on default slugs looks ok (unfortunately the meta-queries don't currently works on default slugs)
- [Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/track-functions__smoke-test__smoke-test/reports) on smoke test shows 1 new call edge
=> JS: track functions with methods

javascript/ql/examples/snippets/todocomment.ql
This is just an example query, but it would be nice for people trying to run it if it had the `kind` metadata so its results can be interpreted.
=> Add `kind` metadata to example query.

ruby/ql/lib/codeql/ruby/ast/Erb.qll, ruby/ql/lib/codeql/ruby/ast/Pattern.qll, ruby/ql/lib/codeql/ruby/ast/internal/AST.qll, ruby/ql/lib/codeql/ruby/security/XSS.qll
PR #7394 makes all expressions "post-order" nodes in the control flow graph except for [`SimpleParameter`](https://github.com/github/codeql/pull/7394/files#diff-32ce71534428bfb48247fdc1f6ca40704b369d31bb38b73e2972cadd97367b1aR1) . I think parameters should not be instance of `Expr` , therefore, this pull requests removes the `Expr` class from the super class list of `SimpleParameter`.
=> Ruby: SimpleParameter should not be an Expr

cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.ql
The char pred of `HttpStringLiteral` did great on almost every project on LGTM. It turns out the join-order wasn't the best possible one, however. This led to a single outlier on LGTM (specifically, this project: https://github.com/e-ago/bitcracker).
This PR fixes the join order.
On `main` (on https://github.com/e-ago/bitcracker):
```ql
Tuple counts for UseOfHttp::HttpStringLiteral#class#f#antijoin_rhs/2@d95908b5 after 45m50s:
65980      ~0%     {3} r1 = JOIN quick_eval#f#shared WITH Expr::Expr::getValue_dispred#ff ON FIRST 2 OUTPUT Lhs.0 'arg0', Lhs.0 'arg0', Lhs.1 'arg1'
131968     ~1%     {3} r2 = JOIN quick_eval#f#shared#1 WITH #Expr::Expr::getParent_dispredPlus#bf ON FIRST 1 OUTPUT Rhs.1, Lhs.0 'arg0', Lhs.1 'arg1'
197948     ~0%     {3} r3 = r1 UNION r2
4295033318 ~0%     {3} r4 = …
```
=> C++: Fix join-order in `HttpStringLiteral` charpred

javascript/change-notes/2021-12-07-handlebars-more-raw-interpolation.md, javascript/extractor/src/com/semmle/js/extractor/Main.java, javascript/extractor/src/com/semmle/js/extractor/TemplateEngines.java, javascript/ql/lib/semmle/javascript/frameworks/Templating.qll, javascript/ql/test/library-tests/frameworks/Templating/CodeInjection.expected, javascript/ql/test/library-tests/frameworks/Templating/Xss.expected, javascript/ql/test/library-tests/frameworks/Templating/test.expected, javascript/ql/test/library-tests/frameworks/Templating/views/hbs_sinks.hbs
Recognizes the raw interpolation tag `{{& foo }}`, and whitespace-trimming tags like `{{~ foo }}`.
=> JS: extend syntax of handlebars tags

cpp/ql/lib/semmle/code/cpp/controlflow/SSAUtils.qll
On main (on `php`):
```ql
Tuple counts for SSAUtils::SSAHelper::phi_node#fff/3@i2#c6b1fxk6 after 7.7s:
256024    ~0%      {3} r1 = SCAN SSAUtils::SSAHelper::ssa_defn_rec_dispred#fff#prev_delta OUTPUT In.1 'v', In.0 'this', In.2
104208654 ~0%      {4} r2 = JOIN r1 WITH SSAUtils::live_at_start_of_bb#ff ON FIRST 1 OUTPUT Lhs.1 'this', Lhs.0 'v', Lhs.2, Rhs.1 'b'
90588757  ~0%      {4} r3 = r2 AND NOT SSAUtils::SSAHelper::phi_node#fff#prev(Lhs.0 'this', Lhs.1 'v', Lhs.3 'b')
90588757  ~2%      {4} r4 = SCAN r3 OUTPUT In.2, In.3 'b', In.0 'this', In.1 'v'
82651     ~79%     {3} r5 = JOIN r4 WITH SSAUtils::dominanceFrontier#ff ON FIRST 2 OUTPUT Lhs.2 'this', Lhs.3 'v', Lhs.1 'b'
return r5
...
>>> Created relation SSAUtils::SSAHelper::phi_node_dispred#fff/3@80af8ckn with 155170 rows.
```
On this …
=> C++: Fix join-order in `phi_node` predicate.

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointFeatures.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointScoring.qll
This is part of a set of performance optimizations for ML-powered queries.
In this PR, we take advantage of the interchangeability of the following operations: endpoint filtering, featurization and scoring, and flow computation.  Currently, ATM performs those operations in the order they were given.  However locally we find speedups by performing the flow computation before featurization and scoring.  This PR makes those optimizations in a way that still allows a large number of endpoints to be featurized in internal queries and tests that consume the public ATM CodeQL library.
In the second commit, we push the context about the set of endpoints we wish to featurize into more predicates.  This means we rely less on the optimizer to use magic to push this context into the predicates.
=> JS: Only featurize endpoints that are part of a flow path

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplConsistency.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplConsistency.qll, csharp/ql/consistency-queries/DataFlowConsistency.ql, csharp/ql/lib/semmle/code/cil/Method.qll, csharp/ql/lib/semmle/code/csharp/Unification.qll, csharp/ql/lib/semmle/code/csharp/dataflow/LibraryTypeDataFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplConsistency.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/dotnet/Variable.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplConsistency.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplConsistency.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplConsistency.qll
This PR enables data-flow consistency queries for C#, and also fixes a whole bunch of inconsistencies (others were fixed in preliminary PRs).
=> C#: Enable data-flow consistency queries

cpp/change-notes/2021-10-07-cleartext-transmission.md, cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test3.cpp
Improvements to `cpp/cleartext-transmission`, aiming to reduce FPs on the SAMATE Juliet test suite and on real world LGTM projects.  I have more improvements to come (mostly developed a while ago), but I've limited this PR to a couple of changes to keep things manageable.
The implementation of `checkSocket()` does not cover everything, but it is very much tuned to catch typically definitions of standard input etc.  We can generalize it a bit more at some point if we need to.
SAMATE Juliet tests:
- before:
- https://jenkins.internal.semmle.com/job/Security/job/SAMATE/job/SAMATE-cpp-detailed/189/
- CWE-319 `cpp/cleartext-transmission`: TP 192 (100%); FP 192 (100%)
- after:
- https://jenkins.internal.semmle.com/job/Security/job/SAMATE/job/SAMATE-cpp-detailed/191/
- CWE-319 …
=> C++: Improvements to cpp/cleartext-transmission

ruby/ql/lib/codeql/ruby/controlflow/internal/Completion.qll
This should not matter much in practice (performance-wise), but the generated DIL is a lot simpler.
Before
```
noinline
incremental
Completion::nestedEnsureCompletion#ff(/* Completion::Completion */ Completion::TCompletion outer,
int nestLevel)
:-
(
(
Completion::TReturnCompletion#f(outer),
rec Completion::Completion#class#f(outer)
);
(
Completion::TBreakCompletion#f(outer),
rec Completion::Completion#class#f(outer)
);
(
Completion::TNextCompletion#f(outer),
rec Completion::Completion#class#f(outer)
);
(
Completion::TRedoCompletion#f(outer),
rec Completion::Completion#class#f(outer)
);
(
Completion::TRetryCompletion#f(outer),
rec Completion::Completion#class#f(outer)
);
(
Completion::TRaiseCompletion#f(outer),
rec Completion::Completion#class#f(outer)
);
( …
```
=> Ruby: Reduce non-linear recursion in CFG completion library

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/internal/AliasAnalysis.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/internal/AliasAnalysis.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/internal/AliasAnalysis.qll
This join was previously fixed in https://github.com/github/codeql/pull/3813, but it seems like it's broken again. This is another attempt that will hopefully be more robust.
`main` (on ChakraCore):
```ql
Tuple counts for AliasAnalysis::isArgumentForParameter#fff/3@5f8d3acp after 1.7s:
1040290  ~0%      {3} r1 = JOIN Operand::NonPhiOperand#fff_10#join_rhs WITH Instruction::CallInstruction::getStaticCallTarget_dispred#ff ON FIRST 1 OUTPUT Lhs.1 'operand', Lhs.0 'ci', Rhs.1
942858   ~0%      {3} r2 = r1 AND NOT IRCppLanguage::isFunctionVirtual#f(Lhs.2)
937251   ~0%      {3} r3 = r2 AND NOT Alias::AliasFunction#class#f(Lhs.2)
937251   ~0%      {3} r4 = r3 AND NOT IRCppLanguage::isFunctionVirtual#f(Lhs.2)
937251   ~0%      {3} r5 = r4 AND NOT Alias::AliasFunction#class#f(Lhs.2)
391018   ~2% …
```
=> C++: Fix join order in `isArgumentForParameter`

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll, ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll, ruby/ql/test/library-tests/dataflow/local/Nodes.expected, ruby/ql/test/library-tests/dataflow/local/Nodes.ql, ruby/ql/test/library-tests/dataflow/params/params-flow.expected, ruby/ql/test/library-tests/dataflow/params/params-flow.ql, ruby/ql/test/library-tests/dataflow/params/params_flow.rb, ruby/ql/test/query-tests/security/cwe-798/HardcodedCredentials.expected
Adds support for flow into keyword parameters from keyword arguments. Also gets rid of the `-1` and `-2` positions for modelling `self` and block parameters, respectively.
=> Ruby: Data flow for keyword arguments/parameters

csharp/ql/lib/semmle/code/csharp/dispatch/Dispatch.qll
Before
```
[2021-12-22 09:46:31] (395s) Tuple counts for Dispatch::Internal::hasCallable#fff/3@258418l2 after 5m27s:
49000       ~0%      {2} r1 = JOIN Declaration::Declaration::getUnboundDeclaration_dispred#ff_10#join_rhs WITH project#Dispatch::Internal::DispatchMethodOrAccessorCall::getAStaticTargetExt#ff ON FIRST 1 OUTPUT Lhs.1 'c', Rhs.0
31302       ~3%      {3} r2 = JOIN r1 WITH Type::ValueOrRefType::getAMember_dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.0 'c', Lhs.1 'source', Rhs.1
299700      ~0%      {3} r3 = JOIN r1 WITH Type::ValueOrRefType::hasOverriddenMember_dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.0 'c', Lhs.1 'source', Rhs.1
16650       ~1%      {3} r4 = JOIN r1 WITH Property::Accessor::getDeclaration_dispred#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.1 'source', Lhs.0 'c'
15984 …
```
=> C#: Fix bad join-order in dispatch library

ql/Cargo.lock, ql/extractor/Cargo.toml, ql/generator/Cargo.toml
See
https://github.com/tausbn/tree-sitter-ql/commit/725395405e65814f10095a451404b0ced5dc6289
for the grammar changes and corresponding test.
=> QL: Support trailing comma in set literals

javascript/ql/src/Security/CWE-116/BadTagFilter.ql, python/ql/src/Security/CWE-116/BadTagFilter.ql, ruby/ql/src/queries/security/cwe-116/BadTagFilter.ql
> The software specifies a regular expression in a way that causes data to be improperly matched or compared.
https://cwe.mitre.org/data/definitions/185.html
> A regular expression is overly restrictive, which prevents dangerous values from being detected.
>
> (...) [this CWE] is about a regular expression that does not match all values that are intended. (...)
https://cwe.mitre.org/data/definitions/186.html
---
From my understanding, CWE-625: Permissive Regular Expression, is not applicable. (since this is about accepting a regex match where there should not be a match).
=> JS/Py/Ruby: Add more CWEs to bad-tag-filter queries

ruby/ql/lib/codeql/ruby/ApiGraphs.qll, ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll, ruby/ql/lib/codeql/ruby/frameworks/StandardLibrary.qll, ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected, ruby/ql/test/library-tests/dataflow/array-flow/array-flow.ql, ruby/ql/test/library-tests/dataflow/array-flow/array_flow.rb, ruby/ql/test/library-tests/dataflow/local/Nodes.ql, ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected, ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql, ruby/ql/test/query-tests/security/cwe-022/PathInjection.expected, ruby/ql/test/query-tests/security/cwe-078/CommandInjection.expected, ruby/ql/test/query-tests/security/cwe-078/KernelOpen.expected, ruby/ql/test/query-tests/security/cwe-079/ReflectedXSS.expected, ruby/ql/test/query-tests/security/cwe-089/SqlInjection.expected, ruby/ql/test/query-tests/security/cwe-094/CodeInjection.expected, ruby/ql/test/query-tests/security/cwe-1333-polynomial-redos/PolynomialReDoS.expected, ruby/ql/test/query-tests/security/cwe-1333-regexp-injection/RegExpInjection.expected, ruby/ql/test/query-tests/security/cwe-502/oj-global-options/UnsafeDeserialization.expected, ruby/ql/test/query-tests/security/cwe-502/unsafe-deserialization/UnsafeDeserialization.expected, ruby/ql/test/query-tests/security/cwe-601/UrlRedirect.expected, ruby/ql/test/query-tests/security/cwe-611/Xxe.expected, ruby/ql/test/query-tests/security/cwe-807-user-controlled-bypass/ConditionalBypass.expected, ruby/ql/test/query-tests/security/cwe-918/ServerSideRequestForgery.expected
This PR adds support for (precise) data-flow through arrays (and `Enumerable`s). For the sake of data-flow, arrays and `Enumerable`s are treated the same, and we track array content using either `TKnownArrayElementContent(i)` when the exact array index is known or `TUnknownArrayElementContent()` when the index is unknown.
For example, if we have
```rb
a = [no_taint, taint, no_taint]
```
then `taint` will flow into `TKnownArrayElementContent(1)` on `a`.
Similarly, if we have
```rb
a[i] = taint
```
where `i` is not a known integer constant, then we have flow from `taint` to `TUnknownArrayElementContent` on `a`.
The first commit adds the machinery for defining flow summaries, that is, introduces `T{Known,Unknown}ArrayElementContent` and all the necessary plumbing. Like C# and Java, we also …
=> Ruby: Flow through arrays/enumerables

java/ql/lib/semmle/code/java/frameworks/Strings.qll
... and its overrides. Currently, we do not propagate taint through `AbstractStringBuilder.reverse()` calls, which leads us to miss out on results e.g. within [this webgoat example](https://github.com/zbazztian/webgoat-delombok/blob/main/webgoat-lessons/http-basics/src/main/java/org/owasp/webgoat/http_basics/HttpBasicsLesson.java#L43).
Is there a motivation for this or was this just an oversight?
=> Propagate taint through AbstractStringBuilder.reverse()

cpp/ql/src/Likely Bugs/AmbiguouslySignedBitField.ql, cpp/ql/src/change-notes/2021-12-30-ambiguously-signed-bit-field.md
The gboolean type of GLib (a widely used C library) is a typedef to int.
It is meant to represent a simple true/false value.
Resolves #7491
=> C++: relax ambiguously-signed-bit-field by allowing GLib's gboolean

python/ql/lib/semmle/python/Comparisons.qll, python/ql/lib/semmle/python/Operations.qll, python/ql/lib/semmle/python/essa/Essa.qll, python/ql/lib/semmle/python/essa/SsaDefinitions.qll, python/ql/src/Security/CWE-327/TlsLibraryModel.qll
I was inspired by a duplicated space in some QLDoc in the [MaD implementation](https://github.com/github/codeql/pull/7171/). 
So I tried to see if that would be viable as a QL-for-QL query.  
But it only found a few results in Python, so I think I'll just skip the QL-for-QL query. 
(PR was   written automatically by a tool).
=> Python: remove duplicated spaces in qldoc

python/ql/src/experimental/Security/CWE-090/LDAPInjection.ql, python/ql/src/experimental/Security/CWE-287/ImproperLdapAuth.ql, python/ql/src/experimental/Security/CWE-522/LDAPInsecureAuth.ql, python/ql/src/experimental/Security/CWE-943/NoSQLInjection.ql
When https://github.com/github/code-scanning/issues/4291 ships, we will be using the `experimental` tag on CodeQL queries as a signifier for Adaptive Threat Modeling boosted queries, and showing extra UI around them like this:
We therefore don't want to use this tag for queries that aren't to do with ATM, hence this PR.
@henrymercer @AlonaHlobina
=> Remove experimental tag from non-ATM queries

python/ql/test/query-tests/Statements/unreachable/global.py
Adds a test demostrating the false positive observed by andersfugmann.
Note that this does not change the `.expected` file, and so the tests
will fail. This is expected.
=> Python: Extend unreachable statement test

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll
This is hopefully a behavior-preserving optimization 🤞.
Thanks to @hvitved for suggesting this.
=> C++: Remove `rank` aggregate in `SsaInternals`

cpp/ql/src/Security/CWE/CWE-367/TOCTOUFilesystemRace.ql
This PR removes a bunch of bad self joins from the `cpp/toctou-race-condition` that I observed on `php`. For instance this one:
```ql
(94s) Tuple counts for #select#cpe#135#fff#shared/2@50efafh0 after 4.5s:
20213850 ~0%     {2} r1 = JOIN SSA::SsaDefinition::getAUse_dispred#fff WITH SSA::SsaDefinition::getAUse_dispred#fff ON FIRST 2 OUTPUT Rhs.2 'arg1', Lhs.2 'arg1'
return r1
```
The changes textual changes look quite scary, but it's really just simple refactorings following this "algorithm":
1. Pull stuff into individual predicates
2. Manually add some context into those predicates
I recommend enabling "Hide whitespace" when reviewing the PR. That makes the changes really easy to review.
=> C++: Remove bad self joins in `cpp/toctou-race-condition`.

javascript/ql/lib/javascript.qll, javascript/ql/lib/semmle/javascript/frameworks/Credentials.qll, javascript/ql/lib/semmle/javascript/frameworks/SQL.qll, javascript/ql/lib/semmle/javascript/frameworks/data/ModelsAsData.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/Impl.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/Shared.qll, javascript/ql/test/library-tests/frameworks/data/test.expected, javascript/ql/test/library-tests/frameworks/data/test.js, javascript/ql/test/library-tests/frameworks/data/test.ql
Initial implementation of models-as-data. Please use the backlinked issue for high-level discussion of the format itself.
The implementation is split in three files:
- `Shared.qll` is intended to be shared between languages (some day; currently only works for JS)
- `Impl.qll` is intended to contain the langauge-specific details.
- `ModelsAsData.qll` is the public interface from the rest of the library
Some predicates from `Shared.qll` must be usable from `Impl.qll`, but should not be public in the library, so `ModelsAsData.qll` acts as a gatekeeper toward the public API.
The API exposes two modules:
- `ModelInput` is used for contributing models
- For example, subclass `ModelInput::SinkModelCsv` to add new sinks
- `ModelOutput` is used for accessing interpreted models in terms of API …
=> JS: Initial models-as-data implementation

ruby/generator/Cargo.toml
Reverts github/codeql#7498
This should fix a build failure observed on ARM Macs.
=> Ruby: Revert "Update clap requirement from 2.33 to 3.0 in /ruby/generator"

java/ql/lib/semmle/code/java/Type.qll, java/ql/test/library-tests/localclasses/Test.java, java/ql/test/library-tests/localclasses/test.expected, java/ql/test/library-tests/localclasses/test.ql
Previously `LocalClass` itself would match `.isLocal()` whereas `LocalClass<Param>` would not. Rather than require each individual user to check for `.getSourceDeclaration().isLocal()`, let's note that the specializations themselves are local.
=> Note that parameterizations of local classes are themselves local

csharp/ql/test/library-tests/csharp10/ConstInterpolatedString.cs, csharp/ql/test/library-tests/csharp10/constInterpolatedString.expected, csharp/ql/test/library-tests/csharp10/constInterpolatedString.ql
No changes are needed in the extractor to support const interpolated strings, which has been introduced in C# 10.
A small testcase has been added.
=> C#: Constant string interpolation (test only).

csharp/ql/test/library-tests/csharp10/RecordTypeSealedToString.cs, csharp/ql/test/library-tests/csharp10/recordTypeSealedToString.expected, csharp/ql/test/library-tests/csharp10/recordTypeSealedToString.ql
In C# 10 it is allowed to declare a ToString override as sealed on record types.
This is does not require any changes to the extractor.
=> C#: Record types are allowed to seal ToString (test only).

cpp/ql/lib/semmle/code/cpp/dataflow/internal/FlowVar.qll
`BasicBlock.getEnd()` has a much smaller fan-out than `basicBlock.getANode()`. This rewrite is behavior-preserving because the control-flow node that represents the `Function` is always the end node on the last basic block of a function.
Before:
```ql
Tuple counts for FlowVar::FlowVar::reachesRefParameter_dispred#ff/2@956ac39i after 229ms:
24806   ~1%     {2} r1 = JOIN FlowVar::FlowVar_internal::parameterIsNonConstReference#f WITH Parameter::Parameter::getFunction_dispred#ff ON FIRST 1 OUTPUT Lhs.0 'p', Rhs.1
56985   ~3%     {3} r2 = JOIN r1 WITH num#FlowVar::FlowVar_internal::TBlockVar#fff_12#join_rhs ON FIRST 1 OUTPUT Rhs.1 'this', Lhs.0 'p', Lhs.1
2384489 ~4%     {4} r3 = JOIN r2 WITH FlowVar::FlowVar_internal::getAReachedBlockVarSBB#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.2, Lhs.1 'p', Lhs.0 …
```
=> C++: Smaller join in `reachesRefParameter`

javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml, javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml
In the future we'll do this automatically after a release using `codeql pack release`.
=> JS: Bump ATM pack versions to 0.0.4

javascript/ql/lib/semmle/javascript/Concepts.qll, javascript/ql/lib/semmle/javascript/frameworks/Knex.qll, javascript/ql/lib/semmle/javascript/frameworks/NoSQL.qll, javascript/ql/lib/semmle/javascript/frameworks/SQL.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/Shared.qll, javascript/ql/lib/semmle/javascript/heuristics/AdditionalSources.qll, javascript/ql/test/library-tests/Security/heuristics/HeuristicSink.ql, javascript/ql/test/library-tests/Security/heuristics/HeuristicSource.expected, javascript/ql/test/library-tests/Security/heuristics/HeuristicSource.ql, javascript/ql/test/library-tests/Security/heuristics/sources.js
This adds DB reads as taint sources in `AdditionalSources.qll`.
~~**This is not yet complete**, as it's not handling streaming database queries where the result is consumed by a pipe call (eg, knex, spanner, have such features).~~
=> JS: DB reads as taint sources

java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/frameworks/apache/Lang.qll, java/ql/lib/semmle/code/java/frameworks/spring/Spring.qll, java/ql/lib/semmle/code/java/frameworks/spring/SpringContext.qll, java/ql/test/library-tests/frameworks/apache-commons-lang3/StringEscapeUtilsTest.java, java/ql/test/library-tests/frameworks/spring/context/Test.java, java/ql/test/library-tests/frameworks/spring/context/flow.ql, java/ql/test/library-tests/frameworks/spring/context/options, java/ql/test/stubs/apache-commons-lang3-3.7/org/apache/commons/lang3/StringEscapeUtils.java, java/ql/test/stubs/apache-commons-lang3-3.7/org/apache/commons/lang3/text/translate/CharSequenceTranslator.java, java/ql/test/stubs/springframework-5.3.8/org/springframework/context/HierarchicalMessageSource.java, java/ql/test/stubs/springframework-5.3.8/org/springframework/context/MessageSource.java, java/ql/test/stubs/springframework-5.3.8/org/springframework/context/MessageSourceResolvable.java, java/ql/test/stubs/springframework-5.3.8/org/springframework/context/support/AbstractMessageSource.java, java/ql/test/stubs/springframework-5.3.8/org/springframework/context/support/MessageSourceSupport.java, java/ql/test/stubs/springframework-5.3.8/org/springframework/context/support/StaticMessageSource.java
Additional details can be found [here](https://github.com/github/advanced-security-field/issues/1455).
I created a [proof-of-concept XSS query](https://github.com/zbazztian/webgoat-xss-proof-of-concept/blob/main/.github/custom-xss/custom-xss.ql) showcasing [the results](https://github.com/zbazztian/webgoat-xss-proof-of-concept/security/code-scanning) on WebGoat. The default query did not detect any XSS results in said repository. The results of the modified version look promising and many of them are exploitable (I tested with the WebGoat Docker image).
=> Java: Add Spring and Apache Common Langs taint flow steps

java/ql/lib/semmle/code/java/dataflow/SSA.qll, java/ql/src/Likely Bugs/Collections/ContainsTypeMismatch.ql, java/ql/src/Likely Bugs/Collections/RemoveTypeMismatch.ql
`t.getASupertype*().getSourceDeclaration()` and `.getASourceSupertype*().getSourceDeclaration()` are completely equivalent, but the latter is generally much faster to compute.
=> Java: A few perf fixes for getASupertype*().

javascript/ql/experimental/adaptivethreatmodeling/src/NosqlInjectionATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/SqlInjectionATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/TaintedPathATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/XssATM.ql
- Change the `(boosted)` suffix in the query name to `(experimental)` (we can rename this later without causing alerts to be closed/opened)
- Remove the `experimental/atm` tag — this was requested to improve how the alerts look in the UI
- Update the query IDs to `js/ml-powered/*`
=> JS: Update names, IDs, and tags for ML-powered queries

ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/test/callgraph/callgraph.expected, ql/ql/test/callgraph/packs/other/OtherThing.qll, ql/ql/test/callgraph/packs/other/qlpack.yml
I added QL-for-QL to an internal project of mine, and QL-for-QL didn't recognize the dependency in a `qlpack.yml` file of the following form: 
```
name: my-ql-thing
version: 0.0.0
libraryPathDependencies: codeql-ql  # <- this one wasn't recognized. 
```
=> QL: recognize dependecies of the form: libraryPathDependencies: library-name

csharp/ql/consistency-queries/PrimaryQlClass.ql, csharp/ql/lib/semmle/code/csharp/Generics.qll, csharp/ql/lib/semmle/code/csharp/Modifier.qll, csharp/ql/lib/semmle/code/csharp/Type.qll, csharp/ql/lib/semmle/code/csharp/Variable.qll, csharp/ql/lib/semmle/code/csharp/exprs/Expr.qll, csharp/ql/lib/semmle/code/csharp/frameworks/System.qll, csharp/ql/lib/semmle/code/dotnet/Element.qll, csharp/ql/lib/semmle/code/dotnet/Namespace.qll, csharp/ql/lib/semmle/code/dotnet/Type.qll
- Introduce a consistency query for getAPrimaryQlClass on each element
- Add overrides for getAPrimaryQlClass for all elements in source files, where "???" was printed as primary ql class.
=> C#: PrimaryQlClass

java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/security/CleartextStorageAndroidFilesystemQuery.qll, java/ql/lib/semmle/code/java/security/Files.qll, java/ql/src/Security/CWE/CWE-312/CleartextStorageAndroidFilesystem.java, java/ql/src/Security/CWE/CWE-312/CleartextStorageAndroidFilesystem.qhelp, java/ql/src/Security/CWE/CWE-312/CleartextStorageAndroidFilesystem.ql, java/ql/src/change-notes/2021-09-01-cleartext-storage-filesystem-query.md, java/ql/test/query-tests/Telemetry/UnsupportedExternalAPIs/UnsupportedExternalAPIs.expected, java/ql/test/query-tests/security/CWE-312/AndroidManifest.xml, java/ql/test/query-tests/security/CWE-312/CleartextStorageAndroidFilesystemTest.java, java/ql/test/query-tests/security/CWE-312/CleartextStorageAndroidFilesystemTest.ql, java/ql/test/stubs/google-android-9.0.0/androidx/security/crypto/EncryptedFile.java
Created a query that detects sensitive information being stored in the Android filesystem without encryption, which may expose it to attackers or malicious applications.
The query looks for sensitive data flowing into file inputs that isn't sanitized by encryption or hashing methods. Said methods are currently detected with a simple heuristic - there's field for improvement there.
This PR also adds a little modeling (sinks) for creating and writing to files using the JDK. The `create-file` sinks were moved from `ExternalFlow.qll` to their own library (`Files.qll`).
TO DO
=> Java: Create new query Cleartext storage of sensitive information in Android filesystem

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImplSpecific.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
This is needed for codeql-go, which wants to specify that "ReturnValue[n]" needs a reference
=> Dataflow: Add language-specific NeedsReference predicates

ql/ql/src/codeql_ql/ast/internal/Predicate.qll, ql/ql/test/callgraph/Bar.qll, ql/ql/test/callgraph/callgraph.expected
See the below example.  
I've added support for the `this might be a compile error?` line. 
If it turns out that it's actually supposed to be a compile-error, then we'll revert this PR. 
```CodeQL
class Expr extends int {
Expr() { this = 1 or this = 2 }
}
class Function extends int {
Function() { this = 1 }
int getParameter(int i) { result = i * this }
}
class Foo extends Expr instanceof Function {
Foo() {
exists(super.getParameter(0))
or
exists(this.getParameter(0)) // <- this might be a compile error? But currently the compiler doesn't think so. 
}
predicate bar() {
exists(super.getParameter(0))
or
exists(this.getParameter(0)) // <- this is a compile error, everyone agrees on that. 
}
}
```
=> QL: support this.method() calls in the charpred that references non-extending supertypes

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointFeatures.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointScoring.qll
Absent features are now represented implicitly by the absence of a row in the `tokenFeatures` relation, rather than explicitly by an empty string. This leads to improved runtime performance. To enable this implicit representation, we pass the set of supported token features to the `scoreEndpoints` HOP.
This change requires CodeQL CLI v2.7.4 — we will likely want to hold off on merging this until that version of the CLI is released.
Internal PR backlinked.
=> JS: Update featurization for absent features optimization

docs/codeql/support/conf.py, docs/codeql/support/framework-support.rst, docs/codeql/support/language-support.rst
This PR moves a change that was made in `main` for the LGTM Enterprise 1.28 release into the `rc/3.3` branch and updates the version numbers for the upcoming release of LGTM Enterprise 1.29.
In addition, it adds a note linking out to the main CodeQL CLI docs for anyone who wants information on the latest release and ended up on these pages by mistake (closes https://github.com/github/docs-content/issues/4158).
=> Update version numbers in CodeQL support notes for LGTM 1.29

javascript/ql/experimental/adaptivethreatmodeling/src/NosqlInjectionATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/SqlInjectionATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/TaintedPathATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/XssATM.ql
We follow a template of `(Experimental) <alert message for original query> Identified using machine learning.`, but also modify the original message to indicate uncertainty, for example "This is a path that depends on a user-provided value." -> "This may be a path that depends on a user-provided value."
=> JS: Update alert messages for ML-powered queries

python/ql/lib/semmle/python/frameworks/SqlAlchemy.qll, python/ql/test/library-tests/frameworks/sqlalchemy/new_tests.py
I don't think this is big enough for a change-note, but let me know if you disagree.
The .py file can be run, and still doesn't raise any exceptions on those `assert`s, just FYI.
=> Python: Support SQLAlchemy `scoped_session`

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/SsaInternals.qll, cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected, cpp/ql/test/library-tests/dataflow/dataflow-tests/test.cpp
This PR is basically a glorified cherry-pick of https://github.com/github/codeql/commit/092beb8b73cc23c20f568246fb8e6568d51ed608. The code was written as a response to one of the reviews on https://github.com/github/codeql/pull/6825, but the commit had to be reverted because it caused a loss of dataflow on some projects.
I've now looked at those results, and it turns out they were all FPs caused by weird interaction with phi nodes. e8afec413aabf7407e5502bf1245d50aacb22af9 demonstrates the kind of false-positive that underlies all of the lost results, and 25253c7b8df9a5bf800841881575fc9803f8d7c0 fixes the false-positive by doing exactly what 092beb8b73cc23c20f568246fb8e6568d51ed608 did.
Performance on DCA looks fine.
=> C++: Store destinations should not be uses for dataflow SSA

javascript/ql/experimental/adaptivethreatmodeling/src/NosqlInjectionATM.md, javascript/ql/experimental/adaptivethreatmodeling/src/SqlInjectionATM.md, javascript/ql/experimental/adaptivethreatmodeling/src/TaintedPathATM.md, javascript/ql/experimental/adaptivethreatmodeling/src/XssATM.md, javascript/ql/experimental/adaptivethreatmodeling/src/codeql-suites/javascript-atm-code-scanning.qls
Query help is identical to the original query, except for a new paragraph prepended to the overview explaining that the queries are experimental.
We add Markdown query help since only Markdown query help is embedded in SARIF via `--sarif-add-query-help`.
=> JS: Add query help for ML-powered queries

ruby/ql/lib/codeql/ruby/Frameworks.qll, ruby/ql/lib/codeql/ruby/frameworks/GraphQL.qll, ruby/ql/test/library-tests/frameworks/GraphQL.expected, ruby/ql/test/library-tests/frameworks/GraphQL.ql, ruby/ql/test/library-tests/frameworks/StandardLibrary.expected, ruby/ql/test/library-tests/frameworks/app/graphql/mutations/base_mutation.rb, ruby/ql/test/library-tests/frameworks/app/graphql/mutations/dummy.rb, ruby/ql/test/library-tests/frameworks/app/graphql/resolvers/base.rb, ruby/ql/test/library-tests/frameworks/app/graphql/resolvers/dummy_resolver.rb, ruby/ql/test/library-tests/frameworks/app/graphql/types/base_argument.rb, ruby/ql/test/library-tests/frameworks/app/graphql/types/base_field.rb, ruby/ql/test/library-tests/frameworks/app/graphql/types/base_input_object.rb, ruby/ql/test/library-tests/frameworks/app/graphql/types/base_interface.rb, ruby/ql/test/library-tests/frameworks/app/graphql/types/base_object.rb, ruby/ql/test/library-tests/frameworks/app/graphql/types/mutation_type.rb, ruby/ql/test/library-tests/frameworks/app/graphql/types/query_type.rb, ruby/ql/test/query-tests/security/cwe-078/CommandInjection.expected, ruby/ql/test/query-tests/security/cwe-078/CommandInjection.rb
Adds support for [GraphQL Ruby](https://graphql-ruby.org/).
This is the most widely-used GraphQL library in the ruby ecosystem. It integrates with Rails but all of the handling happens in the GraphQL classes (and subclasses), completely disconnected from the Rails Controllers, etc.
What I have done here is added the CodeQL classes necessary to expose the methods that handle user input as `HTTP::Server::RequestHandler::Range` subclasses. That way, all the existing path queries that deal with user input (RemoteFlowSource) will work in GraphQL handlers as well.
This was my first time writing CodeQL - I'm sure I did some wonky things. Help on improving this code is welcome.
=> Ruby: Add support for GraphQL

csharp/ql/lib/change-notes/2022-01-18-local-shadows-member.md, csharp/ql/src/Bad Practices/Declarations/LocalScopeVariableShadowsMember.ql, csharp/ql/test/query-tests/Bad Practices/Declarations/LocalScopeVariableShadowsMember/LocalScopeVariableShadowsMember.cs
When defining a record type, the compiler generates a Deconstruct method on the class or struct representing the record type.
This method has out parameters with the same name as property accessors.
In this PR we add this exception to the rule that identifies bad practices related to shadowing.
=> C#: Fix false positive alert for shadowing on record types.

javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml, javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml
We've released 0.0.4, so bump the version numbers to 0.0.5.
=> JS: Bump ML-powered query packs to v0.0.5

java/ql/src/Likely Bugs/Arithmetic/RandomUsedOnce.ql, java/ql/src/change-notes/2022-01-19-random-used-once.md
Raised in https://github.com/github/codeql/issues/7601, this is one of the only .ql files that has a security-severity score but not the tag "security", including many other queries that live outside the `Security/` subdirectory.
Besides this the only other files with this security-severity-but-no-security-tag combination are:
```
java/ql/src/Frameworks/JavaEE/EJB/EjbContainerInterference.ql
java/ql/src/Frameworks/JavaEE/EJB/EjbFileIO.ql
java/ql/src/Frameworks/JavaEE/EJB/EjbNative.ql
java/ql/src/Frameworks/JavaEE/EJB/EjbReflection.ql
java/ql/src/Frameworks/JavaEE/EJB/EjbSecurityConfiguration.ql
java/ql/src/Frameworks/JavaEE/EJB/EjbSerialization.ql
java/ql/src/Frameworks/JavaEE/EJB/EjbSetSocketOrUrlFactory.ql
```
Given their location I'm assuming these queries are disabled by default and …
=> Remove security-severity tag to java/random-used-once

csharp/extractor/Semmle.Extraction.CIL.Driver/ExtractorOptions.cs, csharp/extractor/Semmle.Extraction.CIL.Driver/Program.cs, csharp/extractor/Semmle.Extraction.CIL/Analyser.cs, csharp/extractor/Semmle.Extraction.CIL/Entities/PdbSourceFile.cs, csharp/extractor/Semmle.Extraction.CIL/Tuples.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Assembly.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Attribute.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/CachedSymbol.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Invocation.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/File.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/PreprocessorDirectives/PreprocessorDirective.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/NamedType.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/Analyser.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/StandaloneAnalyser.cs, csharp/extractor/Semmle.Extraction.CSharp/Extractor/TracingAnalyser.cs, csharp/extractor/Semmle.Extraction.CSharp/Populators/TypeContainerVisitor.cs, csharp/extractor/Semmle.Extraction.CSharp/Tuples.cs, csharp/extractor/Semmle.Extraction/Context.cs, csharp/extractor/Semmle.Extraction/Extractor/Extractor.cs, csharp/extractor/Semmle.Extraction/Extractor/ExtractorMode.cs, csharp/extractor/Semmle.Extraction/Extractor/StandaloneExtractor.cs, csharp/extractor/Semmle.Extraction/Extractor/TracingExtractor.cs, csharp/extractor/Semmle.Extraction/Options.cs, csharp/ql/lib/semmle/code/csharp/File.qll
Passing `--qltest` to the extractor when run though `codeql test run` is not done yet, that will be done on an internal follow-up PR.
=> C#: Introduce extractor mode to identify DBs created with `codeql test run`

javascript/ql/experimental/adaptivethreatmodeling/lib/qlpack.yml, javascript/ql/experimental/adaptivethreatmodeling/src/qlpack.yml
We've released 0.0.5, so bump the version numbers to 0.0.6.
=> JS: Bump ML-powered query packs to v0.0.6

csharp/extractor/Semmle.Extraction.CSharp/Entities/TypeMention.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/TupleType.cs, csharp/extractor/Semmle.Extraction.CSharp/SymbolExtensions.cs, csharp/extractor/Semmle.Extraction/TrapExtensions.cs
We occasionally see errors like this:
```
Unhandled exception generating id: Object reference not set to an instance of an object. in Label.ToString()    at Semmle.Extraction.CSharp.SymbolExtensions.<>c__DisplayClass11_0.<BuildNamedTypeId>b__0(IFieldSymbol f) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/SymbolExtensions.cs:line 293
at Semmle.Extraction.TrapExtensions.BuildList[T1,T2](T1 trapFile, String separator, IEnumerable`1 items, Action`1 action) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/TrapExtensions.cs:line 232
at Semmle.Extraction.CSharp.SymbolExtensions.BuildNamedTypeId(INamedTypeSymbol named, Context cx, EscapingTextWriter trapFile, ISymbol symbolBeingDefined, Boolean …
```
=> C#: Workaround Roslyn bug in `INamedTypeSymbol.TupleElements`

javascript/ql/src/Security/CWE-915/PrototypePollutingAssignment.ql, javascript/ql/src/Security/CWE-915/PrototypePollutingFunction.ql, javascript/ql/src/Security/CWE-915/PrototypePollutingMergeCall.ql
All the [CWE-471 CVEs in the advisory db](https://github.com/advisories?query=cwe%3A471) are prototype-pollution CVEs.  
So I've added CWE-471 to the prototype-pollution queries.
=> JS: add CWE-471 to the prototype-pollution queries

docs/codeql/support/ql-training.rst
I'm preparing the updates to help.semmle.com for the LGTM Enterprise 1.29 release and found that there was a regression in this article: https://github.com/github/lgtm-docs-staging/pull/47/files?file-filters%5B%5D=.html&file-filters%5B%5D=.txt&show-viewed-files=true#diff-c777c4258e0bca61fac75e4998e6fb6f82cfd6e1ca910303ea2517ce8402e866.
This is because I made the original fix on `main` not realizing that `rc/3.3` had already been created 😞 
This PR just makes the changes from https://github.com/github/codeql/pull/6762 in the `rc/3.3` branch.
@jf205 - do you have time to approve this?
=> Port changes from main to rc/3.3 to avoid regression

cpp/ql/lib/semmle/code/cpp/models/implementations/Gets.qll, cpp/ql/lib/semmle/code/cpp/models/interfaces/FlowSource.qll, cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql, cpp/ql/src/change-notes/2022-01-19-cleartext-transmission.md, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test3.cpp
This PR is a collection of simple improvements to `cpp/cleartext-transmission`, each ruling out a small source of false positive results.  There may be more work to be done before upping the query to `@precision high`, but we're getting closer.
=> C++: Improve cpp/cleartext-transmission

java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll, java/ql/lib/semmle/code/java/frameworks/android/Android.qll, java/ql/lib/semmle/code/java/frameworks/android/Intent.qll, java/ql/lib/semmle/code/java/security/IntentUriPermissionManipulation.qll, java/ql/lib/semmle/code/java/security/IntentUriPermissionManipulationQuery.qll, java/ql/lib/semmle/code/xml/AndroidManifest.qll, java/ql/src/Security/CWE/CWE-266/IntentUriPermissionManipulation.java, java/ql/src/Security/CWE/CWE-266/IntentUriPermissionManipulation.qhelp, java/ql/src/Security/CWE/CWE-266/IntentUriPermissionManipulation.ql, java/ql/src/change-notes/2021-10-27-android-intent-uri-permission-manipulation-query.md, java/ql/test/library-tests/frameworks/android/content-provider/Safe.java, java/ql/test/query-tests/security/CWE-266/AndroidManifest.xml, java/ql/test/query-tests/security/CWE-266/IntentUriPermissionManipulationTest.ql, java/ql/test/query-tests/security/CWE-266/MainActivity.java, java/ql/test/query-tests/security/CWE-266/options
This PR adds a query to detect Intent URI Permission Manipulation in Android applications. The query detects when an exported Activity is obtaining a user-provided Intent and redirecting it back to the calling application. Also, it requires that a non-exported Content Provider with the attribute `android:grantUriPermissions="true"` exists in the project.
When an externally provided Intent is returned to an Activity with `setResult`, a malicious application could exploit this by manipulating the Intent to grant itself permissions to access arbitrary Content Providers that are accessible by the vulnerable application.
The query finds 3 TP when run on a set of 1k Android open source projects.
By adding the source defined in #6963, this goes up to 4 TP results (the extra result occurs in an …
=> Java: CWE-266 - Query to detect Intent URI Permission Manipulation in Android applications

ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/src/change-notes/2022-01-19-csrf-protection-weakened.md, ruby/ql/src/queries/security/cwe-352/CSRFProtectionDisabled.qhelp, ruby/ql/src/queries/security/cwe-352/CSRFProtectionDisabled.ql, ruby/ql/test/query-tests/security/cwe-352/CSRFProtectionDisabled.expected, ruby/ql/test/query-tests/security/cwe-352/railsapp/app/controllers/application_controller.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/app/controllers/articles_controller.rb, ruby/ql/test/query-tests/security/cwe-352/railsapp/app/controllers/users_controller.rb
Calling `protect_from_forgery` without specifying a protection strategy defaults to nulling the `session`. However, if parts of the session are memoized (e.g. in previous `before_action`s), then this may not be sufficient to avoid CSRF attacks, as this memoization can take place before the session is nulled.
See https://www.veracode.com/blog/managing-appsec/when-rails-protectfromforgery-fails for details
=> Ruby: flag up `protect_from_forgery` calls without an exception strategy

java/ql/lib/semmle/code/java/dataflow/internal/DataFlowNodes.qll
Convenience wrapper when you need to reference the data flow node for a `this` access.
=> Java: Add data flow node encapsulating instance accesses.

javascript/ql/lib/semmle/javascript/Externs.qll, javascript/ql/lib/semmle/javascript/Promises.qll, javascript/ql/lib/semmle/javascript/StringOps.qll, javascript/ql/lib/semmle/javascript/TypeScript.qll, javascript/ql/lib/semmle/javascript/dataflow/TypeTracking.qll, javascript/ql/lib/semmle/javascript/frameworks/Babel.qll, javascript/ql/lib/semmle/javascript/frameworks/Cheerio.qll, javascript/ql/lib/semmle/javascript/frameworks/ExpressModules.qll, javascript/ql/lib/semmle/javascript/frameworks/Firebase.qll, javascript/ql/lib/semmle/javascript/frameworks/Next.qll, javascript/ql/lib/semmle/javascript/frameworks/Redux.qll, javascript/ql/lib/semmle/javascript/security/dataflow/StoredXssQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeJQueryPluginCustomizations.qll, javascript/ql/src/Declarations/IneffectiveParameterType.ql, javascript/ql/src/Expressions/ImplicitOperandConversion.ql, javascript/ql/src/Security/CWE-915/PrototypePollutingFunction.ql, javascript/ql/src/experimental/Security/CWE-094/UntrustedCheckout.ql, javascript/ql/src/experimental/Security/CWE-918/SSRF.qll
I rewrote a bunch of QLDoc for classes to make sure they start with `A`/`An`/`The` so that they match better with [the style guide](https://github.com/github/codeql/blob/main/docs/qldoc-style-guide.md#qldoc-for-classes).  
Fixes a lot of code-scanning warnings like [this one](https://github.com/github/codeql/security/code-scanning/3280?query=ref%3Arefs%2Fheads%2Fmain).
=> JS: fix most issues found by ql/class-doc-style

python/ql/lib/semmle/python/security/dataflow/CleartextLoggingCustomizations.qll, python/ql/lib/semmle/python/security/dataflow/CleartextStorageCustomizations.qll, python/ql/src/change-notes/2021-01-19-remove-cleartext-fps.md, python/ql/test/experimental/dataflow/sensitive-data/test.py, python/ql/test/query-tests/Security/CWE-312-CleartextLogging/CleartextLogging.expected, python/ql/test/query-tests/Security/CWE-312-CleartextLogging/test.py, python/ql/test/query-tests/Security/CWE-312-CleartextStorage/CleartextStorage.expected, python/ql/test/query-tests/Security/CWE-312-CleartextStorage/test.py
Draft while double checking that we wouldn't loose any important current results from this.
=> Python: Remove usernames as sensitive source for cleartext queries

java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll
This PR fixes a non-monotonic recursion introduced in github/codeql#6098 that reproduces under specific conditions.
When using local taint tracking to define a `RemoteFlowSource`, a recursion is created because `entrypointFieldStep` adds new `RemoteFlowSource`s, and is a local taint step at the same time.
This is fixed by converting `entrypointFieldStep` into a `defaultAdditionalTaintStep` instead of a `localAdditionalTaintStep`, i.e. it will only affect global taint tracking from now on.
Credits to @aschackmull for the final solution.
=> Java: Fix recursion in `entrypointFieldStep`

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/test/library-tests/csharp10/RecordTypes.cs, csharp/ql/test/library-tests/csharp10/StructTypes.cs, csharp/ql/test/library-tests/csharp10/WithExpression.cs, csharp/ql/test/library-tests/csharp10/recordTypes.expected, csharp/ql/test/library-tests/csharp10/structTypes.expected, csharp/ql/test/library-tests/csharp10/structTypes.ql, csharp/ql/test/library-tests/csharp10/withExpression.expected, csharp/ql/test/library-tests/csharp10/withExpression.ql, csharp/ql/test/library-tests/dataflow/fields/F.cs, csharp/ql/test/library-tests/dataflow/fields/FieldFlow.expected, csharp/ql/test/library-tests/dataflow/fields/J.cs
In this PR we make
- Support for user declared default constructors for structs (test-only).
- Support for with expressions for structs, anonymous types and record structs (test only).
- Flow tests for the type of with expressions.
- Support for flow via anonymous type object initializer.
=> C#: Struct (and to a minor extent anonymous types) improvements 

javascript/ql/experimental/adaptivethreatmodeling/src/XssATM.ql
We didn’t catch this because our unit tests test only library code due to the previous difficulty of running queries with an ML model (the ML models in packs work should fix that), and because the end-to-end evaluation runs separate queries that have different result patterns.
Going forward we should create unit tests for the queries themselves, which will require using the ML model in tests. We should also be able to catch this type of error using DCA.
=> JS: Fix copy/paste error in XSS ML-powered queries results patterns

ruby/ql/lib/codeql/ruby/dataflow/BarrierGuards.qll, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.expected, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.rb
This change recognises guards like `FOO.include?`, where `FOO` is an array
constant. For example:
```ruby
FOO = ["a", "b"]
if FOO.include?(x)
else
end
```
=> Ruby: Update `StringConstArrayInclusionCall` barrier guard

ruby/ql/lib/codeql/ruby/frameworks/StandardLibrary.qll, ruby/ql/test/library-tests/frameworks/StandardLibrary.expected, ruby/ql/test/library-tests/frameworks/StandardLibrary.ql, ruby/ql/test/library-tests/frameworks/const_get.rb, ruby/ql/test/query-tests/security/cwe-094/CodeInjection.expected, ruby/ql/test/query-tests/security/cwe-094/CodeInjection.rb
`Module#const_get` takes a single string argument and interprets it as the
name of a constant. It then looks up the constant and returns its value.
```rb
Object.const_get("Math::PI")
```
By itself, this method is not as dangerous as e.g. `eval`, but if the
value returned is a class that is then instantiated, this can allow an
attacker to instantiate arbitrary Ruby classes.
As a result, I think it's safe to say that any remote input flowing into
this call is a potential vulnerability. A real-world example of this is
https://github.com/advisories/GHSA-52p9-v744-mwjj.
=> Ruby: Add Module#const_get as a code execution

docs/codeql/support/conf.py, docs/codeql/support/framework-support.rst, docs/codeql/support/language-support.rst
@felicitymay this brings your help changes for the LGTM 1.29 docs into the LGTM 1.30 docs.
Conflicts in `*-support.rst` resolved in favour of `rc/3.3`, which has a new paragraph.
Enterprise version numbers updated to LGTM Enterprise 1.30 and CodeQL 2.7.6.
=> Merge rc/3.3 into rc/3.4

java/ql/lib/semmle/code/java/controlflow/internal/GuardsLogic.qll, java/ql/test/query-tests/Nullness/B.java, java/ql/test/query-tests/Nullness/NullMaybe.expected
Support for `&=` and `|=` in the Guards library.
=> Java: Add support for bitwise compound assignments in Guards.

cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql, cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnStackAllocatedMemory/ReturnStackAllocatedMemory.expected, cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnStackAllocatedMemory/test.cpp
Quick follow-up to https://github.com/github/codeql/pull/7682 that removes results when the enclosing function's name suggests that its job is to return the value of the stack pointer.
See internal issue for differences.
=> C++: Remove FPs from `cpp/return-stack-allocated-memory`

javascript/ql/src/Security/CWE-116/BadTagFilter.ql, javascript/ql/src/Security/CWE-116/IncompleteMultiCharacterSanitization.ql, javascript/ql/src/Security/CWE-116/IncompleteSanitization.ql
I added [CWE-80: Improper Neutralization of Script-Related HTML Tags in a Web Page](https://cwe.mitre.org/data/definitions/80.html) to some queries that deal with sanitization of script tags.  
CWE-80 is a child of CWE-79, so I've not added CWE-80 to any query that was already tagged with the more general CWE-79. 
(I also sorted the CWE list on those queries).
=> JS: add CWE-80 to queries that detect bad HTML sanitizers

csharp/ql/lib/semmle/code/csharp/dataflow/FlowSummary.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/lib/semmle/code/csharp/frameworks/EntityFramework.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
This avoids non-linear recursion through a self-join of `interpretSpec`:
```
[2022-01-21 09:04:55] (24s) Tuple counts for dom#FlowSummaryImpl::Private::TConsSummaryComponentStack#ff/2@i28#07224gwr after 14.1s:
0         ~0%         {2} r1 = SCAN FlowSummaryImpl::Private::derivedFluentFlowPush#ffffff#reorder_3_4_5_0_1_2#prev_delta OUTPUT In.1 'tail', In.0 'head'
110216000 ~6471%      {2} r2 = JOIN FlowSummaryImpl::Private::External::interpretSpec#ffff#reorder_3_2_0_1#prev_delta WITH FlowSummaryImpl::Private::External::interpretSpec#ffff#reorder_3_2_0_1#prev ON FIRST 1 OUTPUT Lhs.0 'tail', Rhs.1 'head'
110215000 ~6471%      {2} r3 = JOIN FlowSummaryImpl::Private::External::interpretSpec#ffff#reorder_3_2_0_1#prev WITH FlowSummaryImpl::Private::External::interpretSpec#ffff#reorder_3_2_0_1#prev …
```
=> Data flow: Restructure `RequiredSummaryComponentStack`

javascript/ql/src/Security/CWE-200/PrivateFileExposure.ql
[CWE-219: Storage of File with Sensitive Data Under Web Root](https://cwe.mitre.org/data/definitions/219.html).  
The CWE is that a sensitive file as been placed under a web-root. 
And the query is that a web-root has been placed somewhere that contains sensitive files.  
I think that's close enough.
=> JS: add CWE-219 to js/exposure-of-private-files

cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql, cpp/ql/src/change-notes/2022-01-24-return-stack-allocated-memory.md
The query was rewritten to be more robust in https://github.com/github/codeql/pull/7682 and https://github.com/github/codeql/pull/7701 removed all of the FPs that I've seen on LGTM, so I think this query is ready to go into the Code Scanning suite.
This will make the results of `cpp/return-stack-allocated-memory` show up by default.
Before we merge this I'll run a DCA to make sure we don't get any unintended IR re-evaluations.
=> C++: Add `security` tag to `cpp/return-stack-allocated-memory`

javascript/ql/lib/semmle/javascript/security/PasswordInConfigurationFileQuery.qll, javascript/ql/src/Security/CWE-313/PasswordInConfigurationFile.ql, javascript/ql/src/Security/CWE-862/EmptyPasswordInConfigurationFile.qhelp, javascript/ql/src/Security/CWE-862/EmptyPasswordInConfigurationFile.ql, javascript/ql/src/change-notes/2022-01-18-empty-password-in-configuration-file.md, javascript/ql/test/query-tests/Security/CWE-862/EmptyPasswordInConfigurationFile.expected, javascript/ql/test/query-tests/Security/CWE-862/EmptyPasswordInConfigurationFile.qlref, javascript/ql/test/query-tests/Security/CWE-862/tst.js, javascript/ql/test/query-tests/Security/CWE-862/tst.json, javascript/ql/test/query-tests/Security/CWE-862/tst.yml
[Evaluation looks clean](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/CWE-862__default__CustomSuite/reports). 
[Inspired by this C# query](https://github.com/github/codeql/blob/main/csharp/ql/src/Configuration/EmptyPasswordInConfigurationFile.ql).  
The implementation mostly reuses the logic from our existing `PasswordInConfigurationFile.ql` query.
=> JS: add a js/empty-password-in-configuration-file query

javascript/ql/lib/semmle/javascript/frameworks/NodeJSLib.qll
I'm sending this PR because the lack of complete support for `fs-extra` (ca 60.000.000 downloads weekly) has led to at least one false negative (see here: https://lgtm.com/projects/g/strongloop/strong-arc/snapshot/ac18d2c147b10c94552f215b1016216bb580d3ff/files/client/test/test-server.js?sort=name&dir=ASC&mode=heatmap#L89, it's a FN since fs.remove is not currently recognized as a sink. This PR fixes the problem.)
=> JS: add a predicate to recognize path arguments in calls to the fs-extra lib

cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql
I forgot to do this in https://github.com/github/codeql/pull/7718 when we added the query to Code Scanning.
=> C++: Add security-severity to `cpp/return-stack-allocated-memory`

javascript/ql/lib/semmle/javascript/frameworks/CookieLibraries.qll, javascript/ql/src/Security/CWE-1004/ClientExposedCookie.qhelp, javascript/ql/src/Security/CWE-1275/SameSiteNoneCookie.qhelp, javascript/ql/src/Security/CWE-1275/SameSiteNoneCookie.ql, javascript/ql/src/Security/CWE-1275/examples/SameSiteCookieBad.js, javascript/ql/src/Security/CWE-1275/examples/SameSiteCookieGood.js, javascript/ql/src/change-notes/2022-01-24-samesite-cookie.md, javascript/ql/test/query-tests/Security/CWE-1275/SameSiteNoneCookie.expected, javascript/ql/test/query-tests/Security/CWE-1275/SameSiteNoneCookie.qlref, javascript/ql/test/query-tests/Security/CWE-1275/tst-sameSite.js
[MDN Web Docs: SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite). 
I've set the `@precision` to `medium`, because `SameSite=None` is only an issue if there isn't any other CSRF protection.  
And the query makes no attempt to detect the existence of CSRF protection. 
The default value for `SameSite` is `Lax`. 
The `Lax` setting is not great, but also not terrible, so I don't want to flag that. 
(Also: The `SameSite` attribute is somewhat recent. E.g. there is no IE version that supports it). 
[Evaluation shows no new results, and a constant slow-down caused by having to compile the new query](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/CWE-1275__default__CustomSuite/reports).  
/cc @esbena: This is at least the second time I've seen …
=> JS: add a js/samesite-none-cookie cookie

cpp/ql/src/Security/CWE/CWE-311/CleartextFileWrite.ql, cpp/ql/src/change-notes/2022-01-24-cleartext-storage-file.md, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextFileWrite.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test2.cpp
Resolves some of the inconsistency between `cpp/cleartext-transmission`, `cpp/cleartext-storage-file` and `cpp/cleartext-storage-buffer` by upgrading the second one to non-local taint flow (with paths).
LGTM run: https://lgtm.com/query/834234913031404157/
LGTM diff query: https://lgtm.com/query/495444284760597175/
As you can see above, this makes the query a little noisier, but the quality of results seems to be similar to before.
=> C++: Upgrade cpp/cleartext-storage-file

javascript/ql/experimental/adaptivethreatmodeling/src/NosqlInjectionATM.md, javascript/ql/experimental/adaptivethreatmodeling/src/SqlInjectionATM.md, javascript/ql/experimental/adaptivethreatmodeling/src/TaintedPathATM.md, javascript/ql/experimental/adaptivethreatmodeling/src/XssATM.md
The Code Scanning UI shows just the first paragraph of the query help as a summary, until a user chooses to expand the help. We decided it was more useful to display the standard query help in this summary compared to the experimental query notice, since there is already a notice about experimental queries on the alert show page.
=> JS: Move experimental notice to the bottom of the ML-powered query help

ruby/Cargo.lock, ruby/extractor/Cargo.toml, ruby/extractor/src/main.rs, ruby/generator/Cargo.toml, ruby/generator/src/main.rs
This supersedes #7499 and #7556 by bumping the `clap` dependency in both `generator` and `extractor`. It also fixes a warning arising from the version bump (`clap::App::args_from_usage` is deprecated).
The original PRs didn't update `Cargo.lock`, which looked a bit suspicious.
=> Ruby extractor: bump clap

ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll
This avoids potential combinatorial explosion in `SummaryComponentStack`s. Until now it has not been a problem, since array indices are limited to `0..5`, but with this change we should be able to track arbitrary known indices.
One example is the `dig` method, where `dig(x, y, z)` (with unknowns `x`, `y`, and `z`) yields 6^3 `SummaryComponentStack`s. With this change it yields just a single `SummaryComponentStack`, regardless of whether we increase the precision of which indices to track.
=> Ruby: Introduce `TAnyArrayElementContent`

javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/TaintedPath.expected, javascript/ql/test/query-tests/Security/CWE-022/TaintedPath/tainted-access-paths.js
```
import fs from 'node:fs/promises';
```
Is equivalent to
```
import fs from 'fs/promises';
```
if there is no `node_modules/fs` folder (which would be extremely bad practice).
https://nodejs.org/api/esm.html#node-imports
https://2ality.com/2021/12/node-protocol-imports.html
=> js: add support for the 'node:' prefix for importing internal modules

cpp/ql/examples/qlpack.yml, cpp/ql/src/qlpack.yml, csharp/ql/examples/qlpack.yml, csharp/ql/src/qlpack.yml, java/ql/examples/qlpack.yml, java/ql/src/qlpack.yml, javascript/ql/examples/qlpack.yml, javascript/ql/src/qlpack.yml, python/ql/examples/qlpack.yml, python/ql/src/qlpack.yml, ruby/ql/examples/qlpack.yml, ruby/ql/src/qlpack.yml
Will make it easier to avoid publishing them.
=> Add new groups for examples packs

javascript/ql/src/Security/CWE-020/IncompleteUrlSchemeCheck.ql, javascript/ql/src/Security/CWE-116/BadTagFilter.ql
[CWE-184: Incomplete List of Disallowed Inputs](https://cwe.mitre.org/data/definitions/184.html).  
As I interpret it: CWE-184 is when you have a working sanitizer, except there's a case it doesn't cover.
That matches incomplete-scheme-check and bad-tag-filter. 
We have plenty of other queries that detect various broken sanitizers, but they don't seem to follow the pattern of "incomplete list".
=> JS: add CWE-184 to incomplete-scheme-check and bad-tag-filter

javascript/ql/lib/change-notes/2022-01-08-insecure-dependency-resolution.md, javascript/ql/src/Security/CWE-300/InsecureDependencyResolution.qhelp, javascript/ql/src/Security/CWE-300/InsecureDependencyResolution.ql, javascript/ql/src/Security/CWE-300/examples/bad-package.json, javascript/ql/src/Security/CWE-300/examples/good-package.json, javascript/ql/test/query-tests/Security/CWE-300/InsecureDependencyResolution.expected, javascript/ql/test/query-tests/Security/CWE-300/InsecureDependencyResolution.qlref, javascript/ql/test/query-tests/Security/CWE-300/foo.js, javascript/ql/test/query-tests/Security/CWE-300/package.json
Inspired by [this java query](https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-829/InsecureDependencyResolution.ql). 
[An evaluation looks fine](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/CWE-300-nightly-custom/reports). 
This query has extremely few results, but you [can find a few using code search](https://cs.github.com/?scopeName=All+repos&scope=&q=%2F%5E++++%22%5B%5Euwphtb%5D%5Cw%2B%22%3A+%22%28http%7Cftp%29%3A%5C%2F%5C%2Fgithub.com%5C%2F%2F+path%3A%2Fpackage.json).   
[Here is a LGTM run with some of those projects](https://lgtm.com/query/6137303895174543215/).
=> JS: add js/http-dependency query

csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/TypeParameter.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Types/TypeParameterConstraints.cs
Extracted from https://github.com/github/codeql/pull/7456, in preparation for shared extraction.
=> C#: Make `TypeParameterConstraints` a `CachedEntity`

cpp/ql/src/Security/CWE/CWE-311/CleartextFileWrite.ql, cpp/ql/src/change-notes/2022-01-28-cleartext-storage-file.md
Fix the FPs for `cpp/cleartext-storage-file` that we discovered on `kamailio/kamailio`, where the 'file' was in fact `stderr`.
The code I've used is simple compared to the exclusions in `cpp/cleartext-transmission`, but I found this simple solution worked well in practice.
Diff query: https://lgtm.com/query/1738869787752851711/
=> C++: Fix FPs for cpp/cleartext-storage-file

csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/PropertyPattern.cs, csharp/ql/lib/change-notes/2022-01-25-extended-property-patterns.md, csharp/ql/test/library-tests/csharp10/PropertyPatterns.cs, csharp/ql/test/library-tests/csharp10/propertyPatterns.expected, csharp/ql/test/library-tests/csharp10/propertyPatterns.ql, csharp/ql/test/library-tests/csharp10/recordTypes.expected
In this PR we make support for [Extended property patterns](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/extended-property-patterns).
The idea is that the new form is *de-sugared* into a pattern expression in the old form. The only difference will be some slightly different locations.
=> C#: Desugar property patterns that uses member access syntax.

.github/workflows/ruby-qltest.yml
Change the Ruby CI workflow to run the following jobs in parallel:
- Formatting
- Query compilation check
- Database upgrade check
- Tests (1/2)
- Test (2/2)
The overall effect is that Ruby CI takes ~10 minutes to complete, down from 15-20 minutes.
Other improvements that I haven't figured out yet:
- Cache and restore the CodeQL cache between runs
- Fix Cargo caching, which currently seems to be broken
- Cache the fetching of the CLI
=> Ruby: Split up CI jobs

python/ql/lib/semmle/python/objects/TObject.qll
TL;DR: Something introduced the following bad join order:
```
(227s) Tuple counts for dom#TObject::TPythonTuple#ff/2@i2#8f58670w after 3m46s:
25000      ~0%     {2} r1 = SCAN PointsToContext::PointsToContext::appliesToScope_dispred#ff#prev_delta OUTPUT In.1, In.0 'context'
24000      ~1%     {2} r2 = JOIN r1 WITH @py_scope#f ON FIRST 1 OUTPUT Lhs.1 'context', Lhs.0
1076876712 ~6%     {3} r3 = JOIN r2 WITH Flow::TupleNode#class#f CARTESIAN PRODUCT OUTPUT Rhs.0, Lhs.0 'context', Lhs.1
870129666  ~0%     {3} r4 = JOIN r3 WITH Flow::ControlFlowNode::isLoad_dispred#f ON FIRST 1 OUTPUT Lhs.1 'context', Lhs.2, Lhs.0 'origin'
870129000  ~0%     {3} r5 = r4 AND NOT dom#TObject::TPythonTuple#ff#prev(Lhs.2 'origin', Lhs.0 'context')
870129000  ~1%     {3} r6 = SCAN r5 OUTPUT In.2 'origin', In.1, …
```
=> Python: Fix bad join order in `TPythonTuple`

csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImplShared.qll, csharp/ql/test/library-tests/controlflow/graph/NodeGraph.expected, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplShared.qll, ruby/ql/test/library-tests/controlflow/graph/Cfg.expected
Followup to https://github.com/github/codeql/pull/7775, since I realised ordering of edges in graph tests also needs to be specified. I think I've observed the ordering flipping randomly in the past, although it seemed to happen less often than for nodes.
I feel like it should be possible to simplify the `edges` predicate a little, and avoid some of the repetition it has in each of the main disjuncts, but I couldn't see an obvious way.
=> Ruby/C#: add semmle.order attribute to edges in CFG tests

cpp/ql/src/experimental/Best Practices/UselessTest.cpp, cpp/ql/src/experimental/Best Practices/UselessTest.qhelp, cpp/ql/src/experimental/Best Practices/UselessTest.ql
This query finds any useless test of kind a==8 && a!=7.
This query found an useless test on the Suricata project that can you see in this Pull Request : 
https://github.com/OISF/suricata/pull/6897
=> C/C++ : Useless test

javascript/ql/src/Security/CWE-367/FileSystemRace.qhelp, javascript/ql/src/Security/CWE-367/FileSystemRace.ql, javascript/ql/src/Security/CWE-367/examples/file-race-bad.js, javascript/ql/src/Security/CWE-367/examples/file-race-good.js, javascript/ql/src/change-notes/2022-01-27-file-system-race.md, javascript/ql/test/query-tests/Security/CWE-367/FileSystemRace.expected, javascript/ql/test/query-tests/Security/CWE-367/FileSystemRace.qlref, javascript/ql/test/query-tests/Security/CWE-367/tst.js
Inspired by [this C++ query](https://github.com/github/codeql/blob/main/cpp/ql/src/Security/CWE/CWE-367/TOCTOUFilesystemRace.ql).  
The precision is set to `medium`, because protecting against these kinds of races is uncommon in JS, which is because the attack is irrelevant in most JavaScript applications. 
[Here is a test run](https://lgtm.com/query/112645255730185844/). It's noisy. 
The documentation of the `fs` module has some description of the bad pattern: https://nodejs.org/api/fs.html  
(Search for: "recommended"). 
[An evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/CWE-367__default__CustomSuite__1/reports) is about as noisy as expected.  
Performance is not great, not terrible. It might be a fluke, but I think it's OK for a non-default query.
=> JS: add a js/file-system-race query

.github/workflows/ql-for-ql-dataset_measure.yml, .github/workflows/ql-for-ql-tests.yml, .github/workflows/ruby-build.yml, ruby/actions/create-extractor-pack/action.yml
The ql-for-ql workflow copied the original Ruby ones and likely caused clashes with the cache-key names.
=> Ruby: use ruby specific cache key

ruby/ql/lib/codeql/ruby/frameworks/Files.qll, ruby/ql/test/library-tests/frameworks/files/Files.expected, ruby/ql/test/library-tests/frameworks/files/Files.ql, ruby/ql/test/library-tests/frameworks/files/Files.rb
Add calls to `File.open` as `FileSystemAccess`es.
=> Ruby: Add File.open as a FileSystemAccess

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
Before:
```
[2022-01-28 09:45:34] (449s) Tuple counts for FlowSummaryImpl::Public::SummaryComponentStack::bottom_dispred#ff/2@i23#25a5eew4 after 432ms:
0       ~0%     {2} r1 = SCAN FlowSummaryImpl::Public::SummaryComponentStack::length#ff#prev_delta OUTPUT In.0 'this', (In.1 - 1)
0       ~0%     {2} r2 = JOIN r1 WITH FlowSummaryImpl::Public::SummaryComponentStack::drop#fff#prev ON FIRST 2 OUTPUT Rhs.2, Lhs.0 'this'
0       ~0%     {2} r3 = JOIN r2 WITH FlowSummaryImpl::Public::SummaryComponentStack::head_dispred#ff#prev ON FIRST 1 OUTPUT Lhs.1 'this', Rhs.1 'result'
4171589 ~5%     {2} r4 = SCAN FlowSummaryImpl::Public::SummaryComponentStack::length#ff#prev OUTPUT In.0 'this', (In.1 - 1)
4171589 ~0%     {2} r5 = JOIN r4 WITH FlowSummaryImpl::Public::SummaryComponentStack::drop#fff#prev …
```
=> Data flow: Reduce non-linear recursion in `SummaryComponentStack::bottom`

python/ql/lib/semmle/python/AstExtended.qll, python/ql/lib/semmle/python/AstGenerated.qll
Should put these functions in a private module instead, as indicated by the documentation for `library`?
=> python: remove library annotation to clean up QL warnings.

cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql, cpp/ql/src/change-notes/2022-01-22-cleartext-transmission.md, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test3.cpp
This is an enhancement to `cpp/cleartext-transmission` that allows it to spot passwords that are struct or class fields (much more reliably).  I've weeded out a lot of false positive results in previous PRs, but I wanted to address one of the causes of _missing_ results so that we don't just end up having very few results overall.
Note that the `SensitiveNode` isn't a perfect implementation; it tries to avoid matching all accesses to a `SensitiveVariable` to reduce duplicate results where a variable is accessed multiple times, but this is not done in an especially principled or reliable manner.  Happy to take suggestions on how to pick the right `Node` better.
New results: https://lgtm.com/query/6627472974229539370/
All results: https://lgtm.com/query/7344851133823789124/
=> C++: Recognize password struct fields.

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/TaintTrackingUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/TaintTrackingUtil.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/TaintTrackingPublic.qll, docs/ql-libraries/dataflow/dataflow.md, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowUtil.qll, java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowUtil.qll, python/ql/lib/semmle/python/dataflow/new/internal/TaintTrackingPublic.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPublic.qll
Computing a full transitive closure is often bad; by inlining all calls we are providing more context to the QL optimizer.
=> Data flow: Inline `local(Expr|Instruction)?(Flow|Taint)`

.github/workflows/ql-for-ql-build.yml
Code-scanning doesn't provide a nice way of splitting the results based on which run produced them.  
So now we keep a .sarif file for each language implementation as an artifact.  
If you open the .sarif file in VSCode (and install the recommended extension), then you can nicely view and directly fix the results.
=> QL: upload sarif as part of the QL-for-QL workflow

cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql
We were, once again, hit by the IR re-evaluation problem because we didn't import `semmle.code.cpp.valuenumbering.GlobalValueNumbering` before we imported the IR.
=> C++: Fix re-evaluation in `cpp/return-stack-allocated-memory`

javascript/ql/test/query-tests/Security/CWE-506/HardcodedDataInterpretedAsCode.expected, javascript/ql/test/query-tests/Security/CWE-506/event-stream-orig.js
Some anti-virus products (rightfully) flag this event-stream-orig.js as a malicious file.
This change does two things:
- neutralises the file such that the code can not be run accidentally
- documents the purpose of the file
before the change, flagged by 16 AVs: https://www.virustotal.com/gui/file/e403d3aa39766ab0a7e910c1b60569d0a3e50e3ab0a724704e218b23f66883f3
after the change, flagged by 1 AV: https://www.virustotal.com/gui/file/fc1096acdd0d5e08358bb23c31bcf42a146e6626e425ce8eefedc5bc9ab438e3
=> Document and format event-stream-orig.js 

python/ql/lib/semmle/python/PrintAst.qll, python/ql/src/change-notes/2021-01-19-remove-regexp-from-printast.md
Since this caused bad performance (as we had to evaluate points-to).
Fixes https://github.com/github/codeql/issues/6964
This approach was motivated by the comment on the issue from @tausbn:
> We discussed this internally in the CodeQL Python team, and have
> agreed that the best approach for now is to disable the printing of
> regex ASTs.
I tried to keep our RegExpTerm logic, but doing the fix below did not
work, and still evaluated RegExpTerm :| I guess we will just have to
revert this PR if we want it back
```diff
TRegExpTermNode(RegExpTerm term) {
+    none() and
exists(StrConst str | term.getRootTerm() = getParsedRegExp(str) and shouldPrint(str, _))
}
```
=> Python: Remove `RegExpTerm` from PrintAST

.github/workflows/mad_regenerate-models.yml, java/ql/src/utils/model-generator/RegenerateModels.py
Takes the model generator and any framework model we have on main and regenerates the model using the latest and greatest model generator. This enables us to update and evolve the models without manual intervention.
=> Java: Regenerate framework models automatically

python/ql/lib/semmle/python/regex.qll
Observed on `mozilla/bugbug` on the 2.8.0 CLI branch, we had the following line in the timing report:
```
FullServerSideRequestForgery.ql-17:regex::RegexString::charSet_dispred#fff#antijoin_rhs ............... 1m13s
```
Inspecting the logs, we see the following join:
```
(644s) Tuple counts for regex::RegexString::charSet_dispred#fff#antijoin_rhs/5@f295d1bk after 1m13s:
1         ~0%         {1} r1 = CONSTANT(unique string)["]"]
2389      ~4%         {3} r2 = JOIN r1 WITH regex::RegexString::nonEscapedCharAt_dispred#fff_201#join_rhs ON FIRST 1 OUTPUT Rhs.1 'arg0', Rhs.2 'arg1', (Rhs.2 'arg1' + 1)
668873    ~0%         {6} r3 = JOIN r2 WITH regex::RegexString::char_set_start_dispred#fff ON FIRST 1 OUTPUT Lhs.0 'arg0', "]", Lhs.1 'arg1', Lhs.2 'arg2', Rhs.1 'arg3', Rhs.2 'arg4'
537501371 …
```
=> Python: Fix performance issue in `charSet`

CODEOWNERS
This PR introduces a new reviewers team @github/codeql-ml-powered-queries-reviewers for reviewing ML-powered queries and the associated CodeQL libraries.
=> JS: Add codeowners for ML-powered queries

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/FunctionBodyFeatures.qll
Fix for the catastrophic error identified in https://github.com/github/ml-ql-adaptive-threat-modeling/issues/1618
The catastrophic error is `CatastrophicError "String too long (5395415 characters)"`, which occurs when we tokenize the string associated with the `ASTNode`. I've added a restriction to throw away strings that are longer than 1,000,000 characters before we attempt to tokenize them.
=> Restrict AST nodes according to string length

javascript/ql/lib/change-notes/2022-02-04-jszip, javascript/ql/lib/semmle/javascript/security/dataflow/ZipSlipCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-022/ZipSlip/ZipSlip.expected, javascript/ql/test/query-tests/Security/CWE-022/ZipSlip/ZipSlipBad.js
Gets a TP for CVE-2021-23484 
Evaluation underway, but I doubt it will show anything.
=> JS: add file sources from `jszip` to `js/zip-slip`

cpp/ql/lib/change-notes/2022-02-02-detect-creat-in-openat.md, cpp/ql/lib/change-notes/2022-02-02-detect-missing-mode-argument-for-open.md, cpp/ql/lib/semmle/code/cpp/commons/unix/Constants.qll, cpp/ql/src/Security/CWE/CWE-732/DoNotCreateWorldWritable.ql, cpp/ql/src/Security/CWE/CWE-732/FilePermissions.qll, cpp/ql/src/Security/CWE/CWE-732/OpenCallMissingModeArgument.c, cpp/ql/src/Security/CWE/CWE-732/OpenCallMissingModeArgument.qhelp, cpp/ql/src/Security/CWE/CWE-732/OpenCallMissingModeArgument.ql, cpp/ql/test/query-tests/Security/CWE/CWE-732/OpenCallMissingModeArgument.c, cpp/ql/test/query-tests/Security/CWE/CWE-732/OpenCallMissingModeArgument.expected, cpp/ql/test/query-tests/Security/CWE/CWE-732/OpenCallMissingModeArgument.qlref
When calling `open`/`openat` with the `O_CREAT` flag, the mode argument must be supplied. The query introduced in this PR checks for this.
The meta-data on the query is wrong. Some guidelines on getting this correct are appreciated.
=> C++: Add query for missing mode argument in `open`/`openat` calls

ql/extractor/src/extractor.rs, ql/generator/src/main.rs, ql/generator/src/ql.rs, ql/generator/src/ql_gen.rs, ql/node-types/src/lib.rs, ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/ql.dbscheme, ql/ql/src/ql.dbscheme.stats
In particular, the changes from #7875 that modify the dbscheme to put location columns in a single table, making `getLocation()` faster.
As discussed on Slack, I won't write/generate the upgrade/downgrade scripts, since the primary use case of QL for QL is CI checks that build fresh databases.
=> QL for QL: sync changes from Ruby

java/ql/src/Telemetry/ExternalLibraryUsage.ql, java/ql/src/Telemetry/SupportedExternalSinks.ql, java/ql/src/Telemetry/SupportedExternalSources.ql, java/ql/src/Telemetry/SupportedExternalTaint.ql, java/ql/src/Telemetry/UnsupportedExternalAPIs.ql
This PR incorporates the telemetry queries for Java into the summary metrics framework.  Specifically we use the support for summary metrics with messages that was introduced in CodeQL CLI v2.8.0.
This has a few effects:
1. We'll start running these queries on Code Scanning.
2. We will start displaying a summary output of these queries in the metrics summary table produced on Code Scanning and in the CLI (see example below).
3. We can ingest the results of these queries as part of generic internal pipelines that operate on summary metrics.
<details>
<summary>Example metrics summary table additions</summary>
```
Analysis produced the following metric data:
|                          Metric                          |      Value     | …
```
=> Java: Start running telemetry queries on Code Scanning

ql/generator/src/main.rs, ql/ql/src/ql.dbscheme, ruby/downgrades/9fdd1d40fd3c3f8f9db8fabf5a353580d14c663a/old.dbscheme, ruby/downgrades/9fdd1d40fd3c3f8f9db8fabf5a353580d14c663a/ruby.dbscheme, ruby/downgrades/9fdd1d40fd3c3f8f9db8fabf5a353580d14c663a/upgrade.properties, ruby/generator/src/main.rs, ruby/ql/lib/ruby.dbscheme, ruby/ql/lib/upgrades/fabe9e179ed1e3d0e45ccfab6ce94b4bab02dee5/old.dbscheme, ruby/ql/lib/upgrades/fabe9e179ed1e3d0e45ccfab6ce94b4bab02dee5/ruby.dbscheme, ruby/ql/lib/upgrades/fabe9e179ed1e3d0e45ccfab6ce94b4bab02dee5/upgrade.properties
@alexet pointed out that the `node` column in the `*_ast_node_info` tables should be a keyset, since each node has exactly one row in that table.
This may allow the optimiser/evaluator to make better decisions.
=> Ruby/QL: add `unique` annotation on `node` column

javascript/ql/lib/semmle/javascript/security/dataflow/TaintedPathCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-022/ZipSlip/ZipSlip.expected, javascript/ql/test/query-tests/Security/CWE-022/ZipSlip/ZipSlipBad.js
Gets a TN for CVE-2021-23484 
[An evaluation seems clean](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-7876-ca5f91e__nightly__CustomSuite/reports).
=> JS: recognize more startswith sanitizers for path-injection queries

ruby/ql/lib/codeql/ruby/Frameworks.qll, ruby/ql/lib/codeql/ruby/frameworks/ActiveSupport.qll, ruby/ql/test/library-tests/frameworks/ActiveSupport.expected, ruby/ql/test/library-tests/frameworks/ActiveSupport.ql, ruby/ql/test/library-tests/frameworks/active_support.rb
[`constantize`](https://api.rubyonrails.org/classes/String.html#method-i-constantize) is an ActiveSupport extension on `String` that attempts to look up a constant with the same name as the receiver. It has similar issues to [`Module#const_get`](https://docs.ruby-lang.org/en/3.1/Module.html#method-i-const_get).
=> Ruby: Model calls to `constantize` as code executions

cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql
There was a moderate performance explosion on some projects (such as `nlohmann__json`), caused by the `Encrypted` class.  Tested locally, DCA run to follow.
=> CPP: Fix performance for cpp/cleartext-transmission

.codeqlmanifest.json, csharp/ql/consistency-queries/qlpack.yml, python/ql/consistency-queries/qlpack.yml, ql/ql/consistency-queries/qlpack.yml, ruby/ql/consistency-queries/qlpack.yml
Wanted to add this for Python, so that was the day I learned about `.codeqlmanifest.json` :open_mouth: 
I looked at the `qlpack.yml` for the other languages, and since they were all slightly different, I decided to streamline them. I also made them all use the preferred `dependencies` instead of `libraryPathDependencies`.
=> Misc: Streamline `consistency-queries/qlpack.yml`

cpp/ql/test/query-tests/Best Practices/Hiding/DeclarationHidesVariable/DeclarationHidesVariable.expected, cpp/ql/test/query-tests/Best Practices/Hiding/DeclarationHidesVariable/hiding.cpp
Structured bindings are now handled better, so the false negative related to structured bindings is now a true positive.
=> C++: Update C++ variable hiding test

ruby/ql/lib/codeql/ruby/ApiGraphs.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/test/library-tests/dataflow/api-graphs/ApiGraphs.expected, ruby/ql/test/library-tests/dataflow/api-graphs/callbacks.rb, ruby/ql/test/library-tests/dataflow/api-graphs/test1.rb, ruby/ql/test/library-tests/dataflow/api-graphs/use.ql
Following up on a discussion with @hvitved and @aibaars, this makes some API graph changes in preparation for MaD.
Happy to wait until after https://github.com/github/codeql/pull/7663 and fix the merge conflicts here (though there are surprisingly few conflicts)
- The `getReturn("foo")` edge is now split into `getMethod("foo").getReturn()` through an intermediate node representing the method access itself. This node is always unique to the call site, so it can also also be used as a representative for the call itself (this differs from JS, where we need `API::CallNode` to work with calls in the API graph).
- Adds edges going from the method access to its parameters. These have labels:
- `getParameter(n)` for the `n`th positional parameter
- `getKeywordParameter(name)` for the keyword …
=> Ruby: add def-nodes and separate method/return steps to API graphs

javascript/ql/lib/semmle/javascript/frameworks/SQL.qll, javascript/ql/test/library-tests/frameworks/SQL/SqlString.expected, javascript/ql/test/query-tests/Security/CWE-089/untyped/DatabaseAccesses.expected, javascript/ql/test/query-tests/Security/CWE-089/untyped/SqlInjection.expected, javascript/ql/test/query-tests/Security/CWE-089/untyped/mysql.js
Fixes https://github.com/github/codeql/issues/7586
Recognizes the MySQL sink `connection.query({ sql: <sink> })`, instead of just `connection.query(<sink>)`.
Thanks to @Naman-ntc for finding this missing part of the model ✨
=> JS: Recognize "sql" option as a query string in MySQL

docs/codeql/codeql-cli/extractor-options.rst
Tries to fix and improve some formatting issues with the ["Extractor options" article](https://codeql.github.com/docs/codeql-cli/extractor-options/):
- Adds syntax highlighting for code blocks (I hope I got that right)
- Fixes incorrect indentation of JSON in code blocks
- Replaces usage of left and right quotation marks (`“` and `”`) with regular quotation marks in code blocks
=> Fix and improve Extractor options documentation formatting

csharp/extractor/Semmle.Extraction/Options.cs
| source                                        | `a` targets | `b` targets | a\_m  | b\_m  | diff   | relative | weight |
| --------------------------------------------- | ----------- | ----------- | ----- | ----- | ------ | -------- | ------ |
| mcintyre321\_\_OneOf                          | 1           | 1           | 185.1 | 143.6 | -41.47 | -0.224   | ✔      |
| DeafLight\_\_SilentLux.AutoFixture.Moq.Xunit2 | 1           | 1           | 83.75 | 67.86 | -15.89 | -0.19    | ✔      |
| microsoft\_\_fhir-codegen                     | 1           | 1           | 341.9 | 283.4 | -58.49 | -0.171   | ✔      |
| JetBrains\_\_resharper-rider-plugin           | 1           | 1           | 726.9 | 615.7 | -111.2 | -0.153   | ✔      |
| OrchardCMS\_\_OrchardCore                     | 1 …
=> C#: Use Brotli instead of Gzip

javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll, javascript/ql/lib/semmle/javascript/security/TaintedObject.qll, javascript/ql/lib/semmle/javascript/security/dataflow/PrototypePollutingAssignmentQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeJQueryPluginCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeJQueryPluginQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeShellCommandConstructionCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeShellCommandConstructionQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnvalidatedDynamicMethodCallCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnvalidatedDynamicMethodCallQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/XssThroughDomQuery.qll, javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction.expected, javascript/ql/test/query-tests/Security/CWE-078/lib/lib.js
Gets a TN for CVE-2021-45459 
[Evaluation looks clean](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/nanSan__nightly__security-extend/reports) (ignore the backrefs).  
In `UnsafeShellCommandConstructionQuery.qll` and `UnvalidatedDynamicMethodCallQuery.qll` I also added a missing sanitizierGuard to the `isSanitizerGuard` predicate.
=> JS: Add a `isNaN` sanitizer, and use it in queries that already had a typeof check

csharp/ql/lib/semmle/code/csharp/controlflow/Guards.qll, csharp/ql/lib/semmle/code/csharp/dataflow/Nullness.qll, csharp/ql/test/query-tests/Nullness/E.cs, csharp/ql/test/query-tests/Nullness/EqualityCheck.expected, csharp/ql/test/query-tests/Nullness/Implications.expected, csharp/ql/test/query-tests/Nullness/NullCheck.expected, csharp/ql/test/query-tests/Nullness/NullMaybe.expected
Apply a conservative approach by filtering out results for accesses to captured nullable values, when there is an (implicit) call to the capturing callable which is `null`-guarded. For example:
```
bool M(int? i, IEnumerable<int> @is)
{
if (i.HasValue)
return @is.Any(j => j == i.Value); // GOOD
return false;
}
```
Addresses https://github.com/Semmle/ql/issues/2485. I will run a dist-comparison and report the results.
=> C#: Remove FPs from `cs/dereferenced-value-may-be-null`

javascript/ql/lib/semmle/javascript/frameworks/Cheerio.qll, javascript/ql/lib/semmle/javascript/frameworks/ClientRequests.qll, javascript/ql/lib/semmle/javascript/frameworks/Electron.qll, javascript/ql/lib/semmle/javascript/frameworks/Files.qll, javascript/ql/lib/semmle/javascript/frameworks/SocketIO.qll, javascript/ql/lib/semmle/javascript/frameworks/TorrentLibraries.qll, javascript/ql/test/library-tests/frameworks/Cheerio/Cheerio.expected
I was looking at some of our TypeTrackers and I realized that we had some that could be expressed using API-graphs.
=> JS: convert more type-trackers to API-graphs

docs/codeql/writing-codeql-queries/metadata-for-codeql-queries.rst
Filter queries are a historic feature that is no longer supported.
=> Docs: remove mention of 'filter queries'

ruby/ql/lib/codeql/ruby/ApiGraphs.qll, ruby/ql/test/library-tests/dataflow/api-graphs/use.ql
[Evaluation looks clean](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-7930-9739929__Differences__code-scanning/reports).
=> RB: convert the ruby ApiGraphs to use IPA labels

ql/ql/src/queries/style/DBTypeInNonLib.ql
Removes FPs like [this one](https://github.com/github/codeql/security/code-scanning/7316?query=ref%3Arefs%2Fheads%2Fmain).
=> QL: allow raw db types in upgrade/downgrade scripts

java/ql/src/experimental/Security/CWE/CWE-297/CheckedHostnameVerification.java, java/ql/src/experimental/Security/CWE/CWE-297/IgnoredHostnameVerification.java, java/ql/src/experimental/Security/CWE/CWE-297/IgnoredHostnameVerification.qhelp, java/ql/src/experimental/Security/CWE/CWE-297/IgnoredHostnameVerification.ql, java/ql/test/experimental/query-tests/security/CWE-297/IgnoredHostnameVerification.expected, java/ql/test/experimental/query-tests/security/CWE-297/IgnoredHostnameVerification.java, java/ql/test/experimental/query-tests/security/CWE-297/IgnoredHostnameVerification.qlref
The method `HostnameVerifier.verify()` checks that the hostname from the server's certificate matches the server hostname after an HTTPS connection is established. The method returns true if the hostname is acceptable and false otherwise. The contract of the method does not require it to throw an exception if the verification failed. Therefore, a caller has to check the result and drop the connection if the hostname verification failed.
I'd like to add an experimental query that checks whether the result of hostname verification is checked or not. Currently, the query requires en exception to be thrown based on the result of `HostnameVerifier.verify()`. This makes the query pretty strict. It may result in false positives when an application checks the result of hostname verification but …
=> Java: An experimental query for ignored hostname verification

java/ql/src/Security/CWE/CWE-113/NettyRequestSplitting.java, java/ql/src/Security/CWE/CWE-113/NettyResponseSplitting.ql, java/ql/src/Security/CWE/CWE-113/ResponseSplitting.qhelp, java/ql/src/change-notes/2021-01-02-netty-response-splitting-improve.md
Add more classes to Netty request/response splitting. Change identification to `java/netty-http-request-or-response-splitting`.
Identify request splitting differently from response splitting in query results.
Support addional classes:
* `io.netty.handler.codec.http.CombinedHttpHeaders`
* `io.netty.handler.codec.http.DefaultHttpRequest`
* `io.netty.handler.codec.http.DefaultFullHttpRequest`
=> Java: Add HTTP Request Splitting to Netty Query

ruby/ql/lib/change-notes/2022-02-20-file-system-write-access.md, ruby/ql/lib/codeql/ruby/Concepts.qll, ruby/ql/lib/codeql/ruby/frameworks/Files.qll, ruby/ql/test/library-tests/frameworks/files/Files.expected, ruby/ql/test/library-tests/frameworks/files/Files.ql, ruby/ql/test/library-tests/frameworks/files/Files.rb
e.g. `File.write`, `IO.print`, etc.
This necessitated some restructuring in `Files.qll` to clear things up a bit. `IO`/`File` read/write calls in general are mostly modelled in the abstract `IOOrFileMethodCall` and its implementations `IOOrFileReadMethodCall` and `IOOrFileWriteMethodCall`. The `IO::FileReader` and similar classes are then restrictions of those classes.
=> Ruby: Implement `FileSystemWriteAccess` concept

javascript/ql/experimental/adaptivethreatmodeling/src/NosqlInjectionATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/SqlInjectionATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/TaintedPathATM.ql, javascript/ql/experimental/adaptivethreatmodeling/src/XssATM.ql
This PR adds the following CWE tags to the ML-powered queries:
- Cross-site scripting: CWE-79
- Path injection: CWE-22, CWE-23, CWE-36, CWE-73, CWE-99
- NoSQL injection: CWE-943
- SQL injection: CWE-89
=> JS: Add CWE tags for ML-powered queries

docs/codeql/codeql-cli/getting-started-with-the-codeql-cli.rst
The CLI doesn't run on non-glibc systems.
=> Docs: Add note about muslc incompatibility

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/IRBlock.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/IRBlock.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/IRBlock.qll, csharp/ql/src/experimental/ir/implementation/raw/IRBlock.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/IRBlock.qll
=> C++/C#: Fix spelling of 'postDominanceFrontier'

cpp/ql/test/query-tests/Security/CWE/CWE-428/UnsafeCreateProcessCall.cpp
`CreatePorcess` -> `CreateProcess`
=> C++: Fix Spelling Typos.

javascript/ql/lib/semmle/javascript/frameworks/Hapi.qll, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.expected, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXss.js, javascript/ql/test/query-tests/Security/CWE-079/ReflectedXss/ReflectedXssWithCustomSanitizer.expected
According to [a hapi documentation example](https://hapi.dev/tutorials/routing?lang=en_US#path), route handler responses should return escaped HTML, so I have added those returns as sinks for the `js/reflected-xss` query.
=> JS: model hapi handler returns as reflected-xss sinks

cpp/ql/src/Best Practices/Hiding/DeclarationHidesVariable.ql
The check for `(unnamed local variable)` is no longer needed, because these variables are now identified as being compiler generated.
=> C++: Simplify `cpp/declaration-hides-variable`

java/ql/src/experimental/Security/CWE/CWE-552/UnsafeUrlForward.ql, java/ql/src/experimental/Security/CWE/CWE-552/UnsafeUrlForward.qll
Following up on the discussion at [PR# 7712](https://github.com/github/codeql/pull/7712#event-6081871869), this PR is to update the query committed by [PR# 7286 - Java: CWE-552 Query to detect unsafe request dispatcher usage](https://github.com/github/codeql/pull/7286) to switch to the shared library <code>experimental.semmle.code.java.PathSanitizer</code>. 
With this change, code reusability is improved and it facilitates the future integration once the shared library is promoted from the experimental directory to the main directory.
Please consider to merge the PR. Thanks.
=> CWE-552: Switch to the shared PathSanitizer library

javascript/ql/lib/semmle/javascript/frameworks/data/ModelsAsData.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll
Some preparation to make the MaD prototype in JavaScript usable from Ruby. Only JS code is actually affected by this PR.
- Renames `{Shared,Impl}.qll` to `ApiGraphModels` and `ApiGraphModelsSpecfic`. The `Specific` suffix matches the convention for files providing language-specific details in the shared data flow library.
- Makes the `API::InvokeNode` type be provided by the language, as not all languages use the term `InvokeNode`.
- Makes the base case of access path resolution be language-specific. That is, the `moduleImport` part is now JS-specific. In Ruby, the base case looks quite different as members of an imported package are just flooded into the local scope where it is imported (or something to that effect), and you can't really see locally which access paths refer to something …
=> JS: preparation for sharing MaD library based on API graphs

javascript/ql/lib/semmle/javascript/PackageExports.qll, javascript/ql/test/query-tests/Security/CWE-078/UnsafeShellCommandConstruction.expected, javascript/ql/test/query-tests/Security/CWE-078/lib/subLib/amd.js, javascript/ql/test/query-tests/Security/CWE-078/lib/subLib/amdSub.js, javascript/ql/test/query-tests/Security/CWE-078/lib/subLib/index.js
Recognizes the source for CVE-2020-7792 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-8185-2032126__nightly__CustomSuite/reports).
=> JS: recognize modules imported by AMD imports as library inputs

csharp/ql/lib/change-notes/released/0.0.9.md
This formatting change was already applied in the concatenated change log for release 2.8.1 in https://github.com/github/codeql/pull/7975/commits/c5d917eb72d9eb93af12577496e87a26d5c06852.
=> Fix 0.0.9 change note to match concatenated change log

javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/CountAlertsAndEndpoints.ql
Add the new `Xss` queries to the `CountAlertsAndEndpoints.ql` query.
=> Add new xss queries to result counting query

cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.ql, cpp/ql/src/change-notes/2022-02-24-non-https-url.md, cpp/ql/test/query-tests/Security/CWE/CWE-319/UseOfHttp/UseOfHttp.expected, cpp/ql/test/query-tests/Security/CWE/CWE-319/UseOfHttp/test.cpp
Fix a minor source of (arguable) false positives in `cpp/non-https-url`, then promote it to `@precision high`.  LGTM results for this query have previously shown a low number of false positives.
Here's the query running on some relevant projects: [before](https://lgtm.com/query/7625654925223762953/) and [after](https://lgtm.com/query/7741957734714363773/) the change.
=> C++: Promote cpp/non-https-url

docs/codeql/support/conf.py
As discussed internally, the version number currently reported on help.semmle.com is wrong. This PR corrects the number.
=> Fix error in CodeQL CLI version reported for LGTM 1.29

java/ql/test/library-tests/method-signatures/Test.java, java/ql/test/library-tests/method-signatures/signatures.expected, java/ql/test/library-tests/method-signatures/signatures.ql, java/ql/test/query-tests/InefficientOutputStream/InefficientOutputStreamAnnotations.java
This is based on the scenario raised in https://github.com/github/codeql/issues/7610, and tests that annotations do not interfere with comparing method signatures to determine inheritance. This is expected to fail until an extractor fix is landed.
=> Add test checking that inheritence is noticed even with annotations present

ruby/ql/src/queries/meta/CallGraph.ql, ruby/ql/src/queries/meta/TaintSinks.ql, ruby/ql/src/queries/meta/TaintSources.ql, ruby/ql/src/queries/meta/internal/TaintMetrics.qll
Adds three meta-queries for measuring the number of taint sources, sinks, and call edges.
The idea is to include these in a DCA evaluation (as meta-queries) so it's possible to see the impact of your changes at a more fine-grained level. Often, a change generates no new alerts, but produces sources or sinks that give an indication of its impact. The idea was initially discussed in [this issue](https://github.com/github/codeql-javascript-team/issues/191). As for JS, I didn't include logging-related sinks as they tend to dominate too much compared to their security-relevance.
As an example, [this diff](https://github.com/github/codeql-dca-main/blob/data/asgerf/meta-queries__Differences__smoke-test/reports/alert-meta-comparison.md) is comparing `main` to some earlier version from about a …
=> Ruby: add meta-queries for measuring sources, sinks, and call edges

csharp/ql/lib/semmle/code/csharp/dataflow/internal/AccessPathSyntax.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImplSpecific.qll, java/ql/lib/semmle/code/java/dataflow/internal/AccessPathSyntax.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImplSpecific.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/AccessPathSyntax.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll, ruby/ql/lib/codeql/ruby/dataflow/FlowSummary.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/AccessPathSyntax.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll
Previously it was up to each language to parse the numeric arguments in an access path token, such as `Argument[1..3]`. This has lead to some duplication and inconsistency, with plenty of `regexpCapture` calls doing similar things.
This PR places some common parsing primitives into the `AccessPathSyntax.qll` file and uses those where possible.
Note that for the _identifying_ access path (in dynamic languages), the syntax `Argument[N-1]` means the last argument of a call, and `Argument[N-2]` the second-last, etc. For the time being at least, this syntax is specific to the identifying access path and therefore to dynamic languages, but I still think the shared `AccessPathSyntax.qll` file is the best place for this code to live. The predicate for parsing it, `parseIntWithExplicitArity`, can …
=> Shared: use shared access path syntax to parse arguments in CSV rows

docs/codeql/ql-language-reference/ql-language-specification.rst
The main part of this PR is adding documentation for expression pragmas. The semantics are simple but I gave a vague explanation of what the actual cases do.
I also drive-by fixed a couple of minor issues in the grammar:
- Cases missing from the local fragment for primary (but not from the dull description). Also the order differed for the cases that did exist.
- `in` not allowing set literals.
=> QLSpeciifcation: Add documentation for expression pragmas 

csharp/ql/src/Language Abuse/UselessUpcast.ql, csharp/ql/src/change-notes/2022-02-28-useless-upcast.md, csharp/ql/test/query-tests/Language Abuse/UselessUpcast/UselessUpcast.cs, csharp/ql/test/query-tests/Language Abuse/UselessUpcast/UselessUpcast.expected
This PR removes all casts to `dynamic` from the useless upcast check. The issue was reported in https://github.com/github/codeql/issues/8069.
=> C# Exclude dynamic casts from useless casts check

python/ql/lib/change-notes/2022-02-25-regex-group-characters.md, python/ql/lib/semmle/python/RegexTreeView.qll, python/ql/lib/semmle/python/regex.qll, python/ql/test/library-tests/regex/FirstLast.expected, python/ql/test/library-tests/regex/Regex.ql, python/ql/test/query-tests/Security/CWE-730-ReDoS/ReDoS.expected, ruby/ql/lib/change-notes/2022-02-25-regex-group-characters.md, ruby/ql/lib/codeql/ruby/security/performance/ParseRegExp.qll, ruby/ql/lib/codeql/ruby/security/performance/RegExpTreeView.qll, ruby/ql/test/library-tests/ast/Ast.expected, ruby/ql/test/library-tests/regexp/parse.expected, ruby/ql/test/query-tests/security/cwe-1333-exponential-redos/ReDoS.expected
The Javascript library groups sequences of normal characters, it would be good to make the behaviour of the regex libraries behave as similarly to each other as possible.
=> Ruby/Python: regex parser: group sequences of 'normal' characters

.pre-commit-config.yaml, CONTRIBUTING.md, docs/pre-commit-hook-setup.md, misc/scripts/check-qhelp.py
This enables use of the `pre-commit` framework to run quick pre-commit
checks. In particular this allows to automatically fix:
* trailing white spaces
* absence or multiple newlines at the end of files
* QL code formatting
* file sync
More could be added in the future: anything that can be checked fast
can be added in the configuration (for example well-formedness of
`qldoc` files).
This is a purely opt-in feature. Instructions for enabling it and
possibly configuring its behaviour are in `pre-commit-hook-setup.md`.
=> add pre-commit configuration

python/ql/lib/semmle/python/pointsto/MRO.qll, python/ql/lib/semmle/python/pointsto/PointsTo.qll
Evaluation of `FromImportOfMutableAttribute.ql` on https://github.com/FiacreT/M-moire:
Before
```
Stopped during this pipeline:
[2022-01-11 20:06:33] (91497s) Tuple counts for MRO::reverse_step#fff#reorder_1_2_0/3@i132#49c0994w after 55m58s:
20646       ~0%     {3} r1 = JOIN MRO::needs_reversing#f#prev_delta WITH MRO::Empty#f CARTESIAN PRODUCT OUTPUT Rhs.0, Lhs.0 'remainder', Lhs.0 'remainder'
40425683500 ~2%     {4} r2 = JOIN MRO::Cons#fff#prev_delta WITH MRO::Cons#fff#prev ON FIRST 1 OUTPUT Lhs.2, Rhs.1, Lhs.1 'remainder', Rhs.2 'reversed'
0           ~0%     {3} r3 = JOIN r2 WITH MRO::reverse_step#fff#reorder_1_2_0#prev ON FIRST 2 OUTPUT Lhs.3 'reversed', Rhs.2 'lst', Lhs.2 'remainder'
20646       ~0%     {3} r4 = r1 UNION r3
40333997500 ~1%     {4} r5 = JOIN MRO::Cons#fff#prev_delta …
```
=> Python: Points-to performance improvements

ruby/ql/lib/codeql/ruby/ApiGraphs.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Excon.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Faraday.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/HttpClient.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Httparty.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/OpenURI.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/RestClient.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Typhoeus.qll, ruby/ql/src/queries/security/cwe-078/KernelOpen.ql
This reduces the number of things pulled into scope when importing `ApiGraphs`. 
@hmac
=> Ruby: ApiGraphs: use private imports

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/gvn/internal/ValueNumberingInternal.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/gvn/internal/ValueNumberingInternal.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/gvn/internal/ValueNumberingInternal.qll, csharp/ql/src/experimental/ir/implementation/raw/gvn/internal/ValueNumberingInternal.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/gvn/internal/ValueNumberingInternal.qll
As we've seen in the past, the performance of GVN degrades exponentially when it's run on invalid IR.
In this case, a project had some `InheritanceConversionInstruction`s with 10 base classes and 10 derived classes, which meant that some instructions had 100 value numbers. To make things worse, this could lead to an instruction getting `100^2` value numbers if one invalid `InheritanceConversionInstruction` depended on another invalid `InheritanceConversionInstruction`.
The fix is to exclude `InheritanceConversionInstruction`s with multiple base or derived classes from the GVN loop. This is also how we handle other cases of invalid IR.
While we're at it, I also decided to replace the uses of `strictcount(...) = 1` with `unique( | | ...)`. This code predates the introduction of `unique`, …
=> C++: Fix `GVN` performance on more invalid IR

csharp/codeql-extractor.yml, csharp/extractor/Semmle.Extraction.CSharp/Extractor/Options.cs, csharp/extractor/Semmle.Extraction.Tests/Options.cs, csharp/extractor/Semmle.Extraction/Options.cs, csharp/extractor/Semmle.Util/CommandLineOptions.cs, csharp/ql/src/change-notes/2022-02-23-extractor-option-compression.md
Example on, how to use the new option
```bash
codeql database create --language=csharp --keep-trap --extractor-option=trap.compression=gzip mytest.db
codeql database create --language=csharp --keep-trap --extractor-option=trap.compression=none -c="dotnet build /t:rebuild mytest_out/mytest.csproj /p:UseSharedCompilation=false" mytest.db
```
=> C# Extractor Option for specifying compression.

csharp/autobuilder/Semmle.Autobuild.CSharp.Tests/BuildScripts.cs, csharp/autobuilder/Semmle.Autobuild.Shared/AutobuildOptions.cs, csharp/codeql-extractor.yml, csharp/ql/src/change-notes/2022-02-24-buildless-extractor-option.md
In this PR we introduce a new C# extractor option, which indicates, whether a tracing or buildless (standalone) extraction should be performed, when using the autobuilder.
Closes https://github.com/github/codeql-csharp-team/issues/205
```bash
codeql database create --language=csharp -Obuildless=true db
codeql database create --language=csharp --extractor-option=buildless=true db
```
=> C#: Buildless extractor option.

.github/workflows/ruby-qltest.yml, ruby/ql/lib/change-notes/2022-02-28-regex-string-literals.md, ruby/ql/lib/codeql/ruby/security/performance/ParseRegExp.qll, ruby/ql/lib/codeql/ruby/security/performance/RegExpTreeView.qll, ruby/ql/test/query-tests/security/cwe-1333-exponential-redos/ReDoS.expected, ruby/ql/test/query-tests/security/cwe-1333-exponential-redos/tst.rb
This pull request changes the `Regex` class to be `abstract` and extend `StringlikeLiteral`. This allows adding custom subclasses to parse more string literals as regular expressions if needed. The default subclasses are `RegExpLiteral` and string literals that somehow flow into functions like `Regex.new`, `Regex.compile`, `String.match` and `String.match?`.
=> Ruby: parse more string literals as regular expressions

python/ql/lib/semmle/python/Patterns.qll
This is a simplified version of https://github.com/github/codeql/pull/8028 consisting of just the `nomagic` fix.
=> Python: Prevent magic/inlining in `getCase`

cpp/ql/src/Likely Bugs/Memory Management/UsingExpiredStackAddress.ql, cpp/ql/test/query-tests/Likely Bugs/Memory Management/UsingExpiredStackAddress/UsingExpiredStackAddress.expected, cpp/ql/test/query-tests/Likely Bugs/Memory Management/UsingExpiredStackAddress/test.cpp
This PR changes `cpp/using-expired-stack-address` so that the must-flow in the query follows flow into predicates. This should allow us to catch more true positive results (in particular, it fixes a missing result in our tests). I suggest reviewing the PR on a commit-by-commit basis.
- 9df923a7c82c81d4a9a6d87889936325f693ddf8 fixes the missing must-flow
- bf10456bf53170514767516bd8c86c669e9f4486 adds a path explanation to the query. This was a huge help when debugging the query results on LGTM, and I expect users will have the same opinion.
<s>I've marked this as a draft while I run DCA.</s> DCA looks good.
=> C++: More TPs from `cpp/using-expired-stack-address`

cpp/ql/src/Security/CWE/CWE-326/InsufficientKeySize.c, cpp/ql/src/Security/CWE/CWE-326/InsufficientKeySize.qhelp, cpp/ql/src/Security/CWE/CWE-326/InsufficientKeySize.ql, cpp/ql/src/change-notes/2022-02-16-insufficient-key-size.md, cpp/ql/test/query-tests/Security/CWE/CWE-326/InsufficientKeySize.expected, cpp/ql/test/query-tests/Security/CWE/CWE-326/InsufficientKeySize.qlref, cpp/ql/test/query-tests/Security/CWE/CWE-326/test.cpp
Add a new query for insufficient key strength with prime-based RSA, DSA, and Diffie-Hellman key exchange. This query currently covers the OpenSSL/LibreSSL/BoringSSL APIs.
=> C++: new query for insufficient key strength

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/NosqlInjectionATM.qll, javascript/ql/lib/semmle/javascript/frameworks/Testing.qll
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/atmPerf__nightly__atm/reports).   
There is no baseline in the evaluation as the baseline was a timeout.    
The `nodejs/node` benchmark now finished in ~10 minutes instead of timing out. 
[Evaluation with a baseline](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-8297-dfc74d7__nightly__atm/reports).  
--- 
The change in `getTestFile` prevents an InverseAppend on all file names by limiting the set of feasible files early.  
This saves ~40s pr. query on `nodejs/node`.  
--- 
There were many problems with the `getASubexpressionWithinQuery` predicate.  
- It was a recursive predicate, but each step of the recursion computed the transitive closure of the recursion.  
So it searched the entire tree …
=> JS: Fix ATM timeout on NodeJS

java/ql/lib/change-notes/2022-03-03-char-literal-in-compile-time-constant.md, java/ql/lib/semmle/code/java/Expr.qll, java/ql/test/library-tests/constants/CompileTimeConstantExpr.expected, java/ql/test/library-tests/constants/PrintAst.expected, java/ql/test/library-tests/constants/constants/Constants.java, java/ql/test/library-tests/constants/constants/Values.java, java/ql/test/library-tests/constants/getBooleanValue.ql, java/ql/test/library-tests/constants/getIntValue.ql, java/ql/test/library-tests/constants/getStringValue.expected, java/ql/test/library-tests/constants/getStringValue.ql
Simplifies end-user logic when looking for charater literals.
=> [Java] Add CharacterLiteral to CompileTimeConstantExpr.getStringValue

javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/ExtractEndpointMapping.ql
This query produces a mapping between the ATM security query and the type of sink used in that query. This query will be used in the endpoint pipeline to produce a CSV file ready for the modelling code to consume.
It is necessary for when we add the "cheap" `Xss` queries that utilise the same `Xss` sinks.
=> JS: Add query that maps queries to sink type

ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll, ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected, ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.ql
Depends on https://github.com/github/codeql/pull/8317
=> Ruby: TypeTracker: add smallstep for functions that return their arguments

ruby/ql/consistency-queries/RegExpConsistency.ql, ruby/ql/lib/codeql/ruby/security/performance/ParseRegExp.qll, ruby/ql/lib/codeql/ruby/security/performance/RegExpTreeView.qll, ruby/ql/test/library-tests/regexp/parse.expected, ruby/ql/test/library-tests/regexp/regexp.rb
The `|` in `/[|]/` was previously parsed as _both_ a `RegExpConstant` and a `RegExpAlt`; now it is only the former.
=> Ruby: Fix regex parsing of `/[|]/`

ruby/ql/lib/codeql/ruby/security/performance/ParseRegExp.qll, ruby/ql/test/library-tests/regexp/regexp.expected, ruby/ql/test/library-tests/regexp/regexp.ql
cc @yoff and @joefarebrother for Python and Java.
=> Ruby: Fix off-by-one error in `getGroupName`

ql/ql/src/queries/bugs/OrderByConst.ql, ql/ql/test/queries/bugs/OrderByConst/Foo.qll, ql/ql/test/queries/bugs/OrderByConst/OrderByConst.expected, ql/ql/test/queries/bugs/OrderByConst/OrderByConst.qlref
This was a mistake I made myself recently.  
I never committed the mistake, but that could have happened.  
No results in `github/codeql` :tada:
=> QL: add query detecting ordering by a constant

cpp/ql/lib/semmle/code/cpp/ir/dataflow/MustFlow.qll, cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql, cpp/ql/src/Likely Bugs/OO/UnsafeUseOfThis.ql, cpp/ql/test/query-tests/Critical/UnsafeUseOfThis/UnsafeUseOfThis.expected, cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnStackAllocatedMemory/ReturnStackAllocatedMemory.expected, cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnStackAllocatedMemory/test.cpp
This PR factors out the common functionality from `cpp/unsafe-use-of-this` and `cpp/return-stack-allocated-memory`. This shouldn't change any behavior[^1], but it should mean that we re-evaluate a _tiny_ little bit less stuff in the Code Scanning suite.
[^1]: Apart from the path explanation for `cpp/unsafe-use-of-this` which is now a lot better as it doesn't just use the `toString` given by the IR.
=> C++: Factor must-flow predicates out of two queries

ruby/ql/lib/codeql/ruby/ast/Expr.qll, ruby/ql/lib/codeql/ruby/ast/Variable.qll, ruby/ql/lib/codeql/ruby/ast/internal/Module.qll, ruby/ql/lib/codeql/ruby/ast/internal/Variable.qll, ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll, ruby/ql/lib/codeql/ruby/dataflow/SSA.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImplSpecific.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPublic.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll, ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/lib/codeql/ruby/frameworks/GraphQL.qll, ruby/ql/lib/codeql/ruby/frameworks/core/Kernel.qll, ruby/ql/lib/codeql/ruby/typetracking/TypeTrackerSpecific.qll, ruby/ql/test/library-tests/ast/Ast.expected, ruby/ql/test/library-tests/ast/AstDesugar.expected, ruby/ql/test/library-tests/dataflow/local/DataflowStep.expected, ruby/ql/test/library-tests/dataflow/string-flow/string-flow.expected, ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected, ruby/ql/test/library-tests/frameworks/ActiveRecord.expected, ruby/ql/test/library-tests/variables/ssa.expected
Since @hmac's https://github.com/github/codeql-ruby/pull/335, `self` is handled in the SSA library as any other variable (except we were missing support for captured variables, which required using `SsaImplSpecific::variableWrite` instead of `VariableWriteAccess` in `hasVariableWriteWithCapturedRead`). Consequently, we no longer need explicit flow from `self` parameters to all accesses, as this is now covered by normal parameter-to-first-use flow, followed by adjacent-use-use flow. 
The last two commits are unrelated performance tweaks (though the performance problem fixed by the latter commit was amplified by letting the SSA library handle flow through captured `self` variables).
=> Ruby: Cleanup flow through `self`

javascript/ql/lib/semmle/javascript/dataflow/Sources.qll, javascript/ql/test/query-tests/Security/CWE-078/CommandInjection.expected, javascript/ql/test/query-tests/Security/CWE-078/child_process-test.js
Gets a TP for CVE-2021-46704 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-8380-cebd241__nightly__security-extend/reports).  
--- 
Consider the below. 
```CodeQL
result = DataFlow::moduleImport("foo").getAnInstantiation().getAMethodCall*().getAMethodCall("bar");
```
This will not flag the below: 
```JavaScript
const Foo = require("foo");
const inst = new Foo();
const result = inst.bar();
```
Because `DataFlow::moduleImport("foo").getAnInstantiation().getAMethodCall*()` is restricted to the type `DataFlow::CallNode`, even if we take 0 steps through the transitive closure.
=> JS: support that the base is not a method-call in getAChainedMethodCall

cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll, csharp/ql/lib/semmle/code/csharp/exprs/Creation.qll, python/ql/lib/semmle/python/Flow.qll, python/ql/lib/semmle/python/dataflow/old/Implementation.qll, python/ql/lib/semmle/python/dataflow/old/Legacy.qll, python/ql/lib/semmle/python/dependencies/Dependencies.qll, python/ql/lib/semmle/python/objects/ObjectAPI.qll, python/ql/lib/semmle/python/pointsto/Base.qll, python/ql/lib/semmle/python/pointsto/PointsTo.qll, python/ql/lib/semmle/python/security/strings/Common.qll, python/ql/lib/semmle/python/types/ClassObject.qll, python/ql/src/Lexical/CommentedOutCode.qll, python/ql/src/Resources/FileOpen.qll, ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/codeql_ql/ast/internal/AstNodes.qll, ql/ql/src/queries/style/NonDocBlock.ql
Inspired by [this block comment](https://github.com/github/codeql/blob/86121164c5b0695a8c12fa43677f55db62b34dc7/python/ql/lib/semmle/python/types/Extensions.qll#L51) that should have been a QLDoc.  
That comment not being a QLDoc caused my "remove all deprecated things and their QLDoc"-patch to not delete that comment.  
There appears to be some results, mostly in Python. (The results I haven't fixed look benign).
=> QL: add query detecting block comments in a position where a QLDoc should be

java/ql/lib/change-notes/2022-03-11-revert-8325.md, java/ql/lib/semmle/code/java/Expr.qll, java/ql/test/library-tests/constants/CompileTimeConstantExpr.expected, java/ql/test/library-tests/constants/PrintAst.expected, java/ql/test/library-tests/constants/constants/Constants.java, java/ql/test/library-tests/constants/constants/Values.java, java/ql/test/library-tests/constants/getStringValue.expected, java/ql/test/library-tests/constants/getStringValue.ql
As pointed out in #8325's thread, this breaks the corner case of char-literal addition and the convention that getStringValue only applies to String-typed constants.
=> Java: Revert #8325, Add CharacterLiteral to CompileTimeConstantExpr.getStringValue

ql/ql/src/codeql_ql/ast/internal/Module.qll, ql/ql/src/queries/bugs/PathProblemQuery.ql
and it's absence in `problem` queries.  
No results in `github/codeql` after I got the the query right.
=> QL: make a query checking for `edges` relation in a path-problem query

javascript/ql/lib/semmle/javascript/security/performance/ReDoSUtil.qll, python/ql/lib/semmle/python/security/performance/ReDoSUtil.qll, ruby/ql/lib/codeql/ruby/ast/internal/Scope.qll, ruby/ql/lib/codeql/ruby/ast/internal/Variable.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionDispatch.qll, ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/lib/codeql/ruby/frameworks/core/Kernel.qll, ruby/ql/lib/codeql/ruby/security/performance/ReDoSUtil.qll, ruby/ql/lib/codeql/ruby/security/performance/RegExpTreeView.qll
The first commit replaces these fields with `exists` or `don't-care`s in the charpred. The second commit simplifies a few of these charpreds into ones that should be equivalent in practice, with `KernelMethodCall` needing the most scrutiny.
=> Ruby: resolve `ql/field-only-used-in-charpred` alerts

cpp/ql/lib/change-notes/2022-03-14-taint-interface-cleanup.md, cpp/ql/lib/semmle/code/cpp/dataflow/TaintTracking.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/TaintTracking.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/tainttracking3/TaintTrackingImpl.qll, csharp/ql/lib/change-notes/2022-03-14-taint-interface-cleanup.md, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking3/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking4/TaintTrackingImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/tainttracking5/TaintTrackingImpl.qll, java/ql/lib/change-notes/2022-03-14-taint-interface-cleanup.md, java/ql/lib/semmle/code/java/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/tainttracking2/TaintTrackingImpl.qll, java/ql/lib/semmle/code/java/security/ImplicitPendingIntentsQuery.qll, java/ql/src/utils/model-generator/CaptureSummaryModels.ql, python/ql/lib/change-notes/2022-03-14-taint-interface-cleanup.md, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking1/TaintTrackingImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking2/TaintTrackingImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking3/TaintTrackingImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/tainttracking4/TaintTrackingImpl.qll, python/ql/lib/semmle/python/security/dataflow/PathInjection.qll, python/ql/src/experimental/semmle/python/security/injection/NoSQLInjection.qll, ruby/ql/lib/change-notes/2022-03-14-taint-interface-cleanup.md, ruby/ql/lib/codeql/ruby/dataflow/internal/tainttracking1/TaintTrackingImpl.qll
The flow state extension had to not been propagated to taint analysis, which lead to (a) a weird documentation mix and (b) having to use `isBarrier` and `isAdditionalFlowStep` in places where the user would expect `isSanitizer` and `isAdditionalTaintStep`. This PR fixes this.
I had to fix two Python libraries, a Java library and a Java query, which makes me somewhat worried this change comes a bit too late. Some advice on that would be useful. One solution would be to not mark `isBarrier` and `isAdditionalFlowStep` as final.
=> Extend taint tracking interface with flow states

csharp/ql/lib/semmle/code/csharp/dataflow/ModulusAnalysis.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/rangeanalysis/ModulusAnalysisSpecific.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/rangeanalysis/SsaReadPositionCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/rangeanalysis/SsaReadPositionSpecific.qll, java/ql/lib/semmle/code/java/dataflow/ModulusAnalysis.qll, java/ql/lib/semmle/code/java/dataflow/RangeAnalysis.qll, java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/ModulusAnalysisSpecific.qll, java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/SsaReadPositionCommon.qll, java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/SsaReadPositionSpecific.qll
This borrows a technique (and the implementing code) off Modulus analysis.
=> C#/Java: Range analysis: use ranked phi nodes

cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql
Fixes a bad join in 'cpp/return-stack-allocated-memory' where we'd get a join on the enclosing callable of two nodes.
Before:
```ql
Tuple counts for #select#cpe#12356#fffff/5@087a720v after 32.7s:
106500    ~0%     {2} r1 = SCAN MustFlow::MkLocalPathNode#fff OUTPUT In.0 'select', In.2 'sink'
106000    ~1%     {3} r2 = JOIN r1 WITH DataFlowUtil::Node::getEnclosingCallable_dispred#fb ON FIRST 1 OUTPUT Rhs.1, Lhs.0 'select', Lhs.1 'sink'
951733500 ~0%     {3} r3 = JOIN r2 WITH Instruction::Instruction::getEnclosingFunction_dispred#3#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1 'select', Lhs.2 'sink'
58201000  ~0%     {3} r4 = JOIN r3 WITH project#Instruction::VariableAddressInstruction#class#3#ff ON FIRST 1 OUTPUT Lhs.0, Lhs.1 'select', Lhs.2 'sink'
58200500  ~0%     {4} r5 = JOIN r4 WITH …
```
=> C++: Fix join in `cpp/return-stack-allocated-memory`

csharp/ql/lib/semmle/code/csharp/commons/StructuralComparison.qll
In cases where the target of a call/access has multiple values (which is a DB inconsistency), the GVN construction underlying the structural comparision library may run into a combinatorial explosion. This change excludes such expressions from the GVN construction.
=> C#: Avoid combinatorial explosion in structural comparison library

.github/workflows/check-qldoc.yml
This pull request adds a CI check based on the new `codeql generate library-doc-coverage` command. It is very similar to the   internal test we have, except that it is *much* faster (30s vs 10m),  and adds check annotations to the files. In addition the test output is available to external contributors.
Below some links for an example run:
* [Summary](https://github.com/github/codeql/actions/runs/1951059124)
* [Annotation](https://github.com/github/codeql/pull/8367/files#annotation_2932028736)
* [Log](https://github.com/github/codeql/runs/5463433141?check_suite_focus=true)
@adityasharad @alexet
=> CI: add QLdoc test

java/ql/test/library-tests/frameworks/JaxWs/JaxRs.ql, java/ql/test/library-tests/structure/TypeGetCompilationUnit.ql, javascript/ql/lib/change-notes/2022-02-07-deprecated-modules.md, javascript/ql/lib/semmle/javascript/frameworks/Logging.qll, javascript/ql/lib/semmle/javascript/frameworks/UriLibraries.qll, javascript/ql/test/library-tests/frameworks/UriLibraries/tests.ql, python/ql/lib/change-notes/2022-02-07-deprecated-modules.md, python/ql/lib/semmle/python/Metrics.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPrivate.qll, python/ql/lib/semmle/python/frameworks/Django.qll, python/ql/lib/semmle/python/frameworks/Fabric.qll, python/ql/lib/semmle/python/frameworks/Invoke.qll, python/ql/lib/semmle/python/frameworks/Mysql.qll, python/ql/lib/semmle/python/frameworks/RestFramework.qll, python/ql/lib/semmle/python/frameworks/Stdlib.qll, python/ql/lib/semmle/python/frameworks/Tornado.qll, python/ql/lib/semmle/python/strings.qll, python/ql/src/experimental/semmle/python/frameworks/Django.qll, python/ql/src/experimental/semmle/python/frameworks/Werkzeug.qll, ql/ql/src/codeql_ql/style/AcronymsShouldBeCamelCaseQuery.qll, ql/ql/src/queries/style/NameCasing.ql, ql/ql/src/queries/style/NoUppercaseVariables.ql
~~TODO: Wait for https://github.com/github/codeql/pull/8323.~~ 
Adds a QL-for-QL queries that puts every name definitions in two categories:  
- Things that should start with an upper-case letter. 
- Things that should start with a lower-case letter. 
Every violation of the above is fixed as part of this PR, luckily almost no code violated the above.  
A few modules in the public API started with a lower-case letter, I've left a deprecated alias for those.  
/cc @jbj
=> Rename all upper-case variables, and all lower-case modules

javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/ATMConfig.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/EndpointScoring.qll, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/extraction/ExtractEndpointData.qll
This was previously used in the ATM external API query, but is now dead code.
=> JS: Remove `isEffectiveSinkWithOverridingScore` from ML-powered libraries

cpp/ql/src/Security/CWE/CWE-319/UseOfHttp.ql, cpp/ql/src/Security/CWE/CWE-326/InsufficientKeySize.ql
As identified by the new ql-for-ql query we added [here](https://github.com/github/codeql/pull/8437).
=> C++: Add missing `security-severity` tags

javascript/ql/src/Security/CWE-295/DisablingCertificateValidation.ql, javascript/ql/test/query-tests/Security/CWE-295/DisablingCertificateValidation.expected, javascript/ql/test/query-tests/Security/CWE-295/tst.js
Gets a TP/TN for CVE-2020-24025 
[Evaluation looks OK](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-8438-195ce9c__nightly__CustomSuite/reports).  
There are some new TPs in some test files.
=> JS: add some API-nodes to js/disabling-certificate-validation

javascript/ql/lib/semmle/javascript/DynamicPropertyAccess.qll, javascript/ql/lib/semmle/javascript/GlobalAccessPaths.qll, javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll, javascript/ql/lib/semmle/javascript/internal/CachedStages.qll
Just something I stumbled upon.   
I think the two predicates should do the same thing, so I made one forward to the other. 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/domWrite__nightly__security-extend__6/reports). (Ignore the backref).
=> JS: merge hasDominatingWrite and hasDominatingAssignment

cpp/ql/lib/change-notes/2022-03-10-template-implicit-copy.md, cpp/ql/lib/semmle/code/cpp/Class.qll, cpp/ql/test/library-tests/special_members/generated_copy/assign.expected, cpp/ql/test/library-tests/special_members/generated_copy/copy.cpp, cpp/ql/test/library-tests/special_members/generated_copy/ctor.expected, cpp/ql/test/library-tests/special_members/generated_copy/functions.expected
Fixes some cases in instantiations of templates with manually written copy constructors or copy assignment operators where hasImplicitCopyConstructor would incorrectly hold.
=> C++: fix hasImplicitCopyConstructor for templates

csharp/ql/lib/semmle/code/csharp/frameworks/system/Linq.qll, csharp/ql/lib/semmle/code/csharp/frameworks/system/data/Common.qll, csharp/ql/lib/semmle/code/csharp/frameworks/system/data/Entity.qll, csharp/ql/lib/semmle/code/csharp/frameworks/system/linq/Expressions.qll, csharp/ql/lib/semmle/code/csharp/frameworks/system/xml/XPath.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/ATMConfig.qll, javascript/ql/experimental/adaptivethreatmodeling/lib/experimental/adaptivethreatmodeling/AdaptiveThreatModeling.qll, javascript/ql/lib/semmle/javascript/frameworks/XmlParsers.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll, ql/ql/src/codeql_ql/style/AcronymsShouldBeCamelCaseQuery.qll, ql/ql/src/queries/style/NameCasing.ql, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplSpecific.qll
This was mostly due to me missing a case in the `getName()` predicate. 
Ignore the new `Acronyms should be PascalCase/camelCase` warnings, I'll fix them [over here](https://github.com/github/codeql/pull/8444).
=> disallow lowercase import-as aliases

javascript/ql/src/Security/CWE-094/UnsafeCodeConstruction.ql, javascript/ql/src/Security/CWE-347/MissingJWTKeyVerification.ql, ql/ql/src/queries/style/MissingSecurityMetadata.ql
And stop the QL-for-QL query from flagging queries in a `test` folder.
=> JS: add missing @security-severity to JS queries

javascript/ql/lib/semmle/javascript/security/TaintedUrlSuffix.qll, javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/DOM.qll, javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/Xss.qll, javascript/ql/src/Security/CWE-079/Xss.ql, javascript/ql/test/library-tests/frameworks/Templating/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tst.js, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tst3.js, javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/ClientSideUrlRedirect.expected, javascript/ql/test/query-tests/Security/CWE-601/ClientSideUrlRedirect/tst13.js
This PR replaces https://github.com/github/codeql/pull/6632 
See [this comment by Asger](https://github.com/github/codeql/pull/6632#discussion_r705269103) for what this PR tries to fix.  
This is a deep fix where flow-labels are used to hopefully correctly model how url sinks can cause XSS.  
There are now 3 flow labels in the XSS query:   
- TaintedUrlSuffix: a URL where the attacker only controls a suffix.
- Taint: a tainted value where the attacker controls part of the value.
- PrefixLabel: a tainted value where the attacker controls the prefix 
--- 
All tests pass on every commit (the expected files are updated on each commit).  
This should help in doing a commit-by-commit review. 
--- 
[An evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/PR-8304-0-javascript …
=> JS: Refactor the XSS / Client-side-url queries 

config/identical-files.json, ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplForLibraries.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/tainttrackingforlibraries/TaintTrackingImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/tainttrackingforlibraries/TaintTrackingParameter.qll, ruby/ql/lib/codeql/ruby/security/performance/ParseRegExp.qll
Follow-up to https://github.com/github/codeql/pull/8293.
=> Ruby: Use taint tracking instead of type tracking to define `regExpSource`

cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/test.cpp
One additional test involving branching and one additional test involving `strncat` in a called subroutine.
=> C++: Add additional command line injection tests

javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll, javascript/ql/src/change-notes/2022-03-18-store-load-flow-context-sensitivity-bug.md, javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/library-tests/TaintTracking/summarize-store-load-in-call.js
Background:
`reachableFromStoreBase` forward-tracks the base object of a store whose RHS is potentially reachable. If the RHS of that store is only reachable with call steps, we do not permit the base object to be tracked out of a return edge, as it would lead to wasted work (i.e. we want to prune infeasible flows early).
However, it turns out we tried to used the same `call` bit for two different purposes:
1. Were call steps used to reach the store RHS? (needed for pruning)
2. Did we use a call step while tracking the base object? (needed for context sensitivity)
This PR adds a new `boolean` parameter to track (1), while the boolean in the `PathSummary` corresponds to (2).
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/store-load-flow__default__code-scanning/repor …
=> JS: fix context sensitivity bug in store-load matching

config/identical-files.json, javascript/ql/lib/semmle/javascript/security/dataflow/TaintedFormatStringCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/TaintedFormatStringQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/TaintedFormatStringSpecific.qll, ruby/ql/lib/codeql/ruby/security/TaintedFormatStringCustomizations.qll, ruby/ql/lib/codeql/ruby/security/TaintedFormatStringQuery.qll, ruby/ql/lib/codeql/ruby/security/TaintedFormatStringSpecific.qll, ruby/ql/src/change-notes/2022-03-10-rb-tainted-format-string.md, ruby/ql/src/queries/security/cwe-134/TaintedFormatString.qhelp, ruby/ql/src/queries/security/cwe-134/TaintedFormatString.ql, ruby/ql/src/queries/security/cwe-134/examples/tainted_format_string_bad.rb, ruby/ql/src/queries/security/cwe-134/examples/tainted_format_string_good.rb, ruby/ql/src/queries/security/cwe-134/examples/tainted_format_string_interpolation.rb, ruby/ql/test/query-tests/security/cwe-134/TaintedFormatString.expected, ruby/ql/test/query-tests/security/cwe-134/TaintedFormatString.qlref, ruby/ql/test/query-tests/security/cwe-134/tainted_format_string.rb
This shares as much as possible with the JS version.
=> Ruby: Add rb/tainted-format-string query

config/identical-files.json, javascript/ql/lib/semmle/javascript/security/dataflow/HttpToFileAccessCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/HttpToFileAccessQuery.qll, javascript/ql/lib/semmle/javascript/security/dataflow/HttpToFileAccessSpecific.qll, ruby/ql/lib/codeql/ruby/Concepts.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/lib/codeql/ruby/security/HttpToFileAccessCustomizations.qll, ruby/ql/lib/codeql/ruby/security/HttpToFileAccessQuery.qll, ruby/ql/lib/codeql/ruby/security/HttpToFileAccessSpecific.qll, ruby/ql/src/change-notes/2022-02-23-rb-http-to-file-access.md, ruby/ql/src/queries/security/cwe-912/HttpToFileAccess.qhelp, ruby/ql/src/queries/security/cwe-912/HttpToFileAccess.ql, ruby/ql/src/queries/security/cwe-912/examples/http_to_file_access.rb, ruby/ql/test/query-tests/security/cwe-912/HttpToFileAccess.expected, ruby/ql/test/query-tests/security/cwe-912/HttpToFileAccess.qlref, ruby/ql/test/query-tests/security/cwe-912/http_to_file_access.rb
This is a direct port of the JS version. I've ported the concept `RequestInputAccess` from JS, which we didn't already have an equivalent for. I've also directly shared `HttpToFileAccessQuery` and `HttpToFileAccessCustomizations` between Ruby and JS. Language-specific imports and some classes that extend differently-named concepts have been moved to `HttpToFileAccessSpecific`.
=> Ruby: Add rb/http-to-file-access query

.github/workflows/csv-coverage-pr-artifacts.yml, misc/scripts/library-coverage/compare.py
I'm experimenting with adding JS to the MaD coverage reports: https://github.com/github/codeql/pull/8290. I found that the current scripts are not handling gracefully if no coverage is generated for a language in either the `merge` or `base` comparison cases.
This PR is fixing the following issues:
- Generated files are not copied, but moved, so that they are not left in place for the second (`base`) coverage generation.
- Missing report files are reported, but then are considered as empty files for diff generation.
- Uses python scripts from the `base` SHA.
=> Fix MaD workflows to be more resilient to missing files

.github/workflows/csv-coverage-pr-artifacts.yml, misc/scripts/library-coverage/compare.py
Reverts github/codeql#8294
Reverting the PR, because it didn't handle correctly when no changes were detected in the coverage files.
=> Revert "Fix MaD workflows to be more resilient to missing files"

cpp/ql/lib/semmle/code/cpp/Type.qll
Motivated by some observations of `cpp/system-data-exposure` (by DCA), but the effects of this change will not be limited to this project, and may or may not be positive overall.  So I'll do a DCA run on this PR, then we can discuss...
=> C++: Make getUnderlyingType nomagic

cpp/ql/src/Diagnostics/Internal/ExtractionErrors.ql, cpp/ql/src/Diagnostics/Internal/ExtractionErrors.qll, misc/suite-helpers/code-scanning-selectors.yml
The goal of this PR is to get internal Hubbers working on the C extractor access to extraction error information through DCA as we have for other languages.
This is a simple task, but it's made complicated by the fact that we don't want these extraction errors to show up for customers through the Code Scanning interface. So this PR does two things:
- It adds a `cpp/diagnostics/extraction-errors` query that behaves like the other `lang/extraction-errors` queries.
- It modifies the Code Scanning suite to exclude diagnostics queries in the `Diagnostics/Internal` directory.
This means that the new query won't appear in the Code Scanning UI (so no behavior is changed). I've created a PR in the DCA repo which then adds this diagnostics query when running DCA.
The diagnostics query itself (and …
=> C++: Add internal `ExtractionError` query

cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql, cpp/ql/src/change-notes/2022-03-21-command-line-injection-with-flow-states.md, cpp/ql/test/query-tests/Security/CWE/CWE-078/SAMATE/ExecTainted/ExecTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/ExecTainted.expected, cpp/ql/test/query-tests/Security/CWE/CWE-078/semmle/ExecTainted/test.cpp
Rework `cpp/command-line-injection` to use flow states. Only thing I'm not sure about is whether the location of a dataflow node uniquely determines the node, which I depend upon:
```codeql
class ExecState extends DataFlow::FlowState {
DataFlow::Node fst;
DataFlow::Node snd;
ExecState() {
this = "ExecState (" + fst.getLocation() + ", " + snd.getLocation() + ")" and
interestingConcatenation(fst, snd)
}
...
```
=> C++: Use flow states in `cpp/command-line-injection`

cpp/ql/lib/semmle/code/cpp/Location.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/internal/IRConstruction.qll, cpp/ql/test/library-tests/ir/ir/PrintAST.expected, cpp/ql/test/library-tests/ir/ir/ir.cpp, cpp/ql/test/library-tests/ir/ir/operand_locations.expected, cpp/ql/test/library-tests/ir/ir/raw_ir.expected
I was hacking on a solution to https://github.com/github/codeql/issues/8497 and was surprised to learn that `Location.isBefore` is really `Location.lineIsBefore`.
As an added bonus to this PR, this will improve our IR generation for code that uses `goto`s:
Currently, our _only_ use of `Location.isBefore` predicate is to determine whether a `goto` statement creates a back edge in the control-flow graph. So on `main`, the following program:
```cpp
int test() {
int x = 42;
goto next; next:
return x;
}
```
gets translated as:
```cpp
int test()
Block 0
v1_1(void)       = EnterFunction      :
m1_2(unknown)    = AliasedDefinition  :
m1_3(unknown)    = InitializeNonLocal :
m1_4(unknown)    = Chi                : total:m1_2, partial:m1_3
r2_1(glval<int>) = VariableAddress[x] :
r2_2(int)        = …
```
=> C++: Consider columns in `Location.isBefore`

python/ql/test/3/library-tests/with/test.expected
Depends on an internal PR. The two lines in question were caused by
the insertion of an extra node due to the failure to parse a trailing
comma corrcetly.
=> Python: Fix syntax error in `with` test output

csharp/ql/lib/semmle/code/csharp/commons/Collections.qll, csharp/ql/src/utils/model-generator/ModelGeneratorUtilsSpecific.qll, csharp/ql/test/utils/model-generator/CaptureSummaryModels.expected, csharp/ql/test/utils/model-generator/NoSummaries.cs, csharp/ql/test/utils/model-generator/Summaries.cs, csharp/ql/test/utils/model-generator/options
In this PR we
* Improve the model generation for callables that uses collection like types for parameters (or just types that has collection like types as base class)
* Improve the model generation for callables that uses IEnumerable types as parameter types
* Introduce more test cases.
=> C#: Model generator improvements and more tests

cpp/ql/lib/semmle/code/cpp/models/interfaces/FormattingFunction.qll
Fix a potential issue with `FormattingFunction::getWideCharType` that was identified in the 'Join-order badness' section of a nightly DCA run.  The goals here is to fix the potential issue - I have not found or looked for projects where this problem blows up enough to cause a significant overall slowdown in practice.
The issue appears to come from `getAFormatterWideTypeOrDefault`, specifically `not exists(getAFormatterWideType())` within that which creates a surprising amount of computation.
Before (`wireshark`, `NoSpaceForZeroTerminator.ql`):
```
[2022-03-17 14:58:13] (772s) Tuple counts for FormattingFunction::FormattingFunction::getWideCharType_dispred#bb/2@346c7dg5 after 74ms:
81      ~0%     {1} r1 = FormattingFunction::FormattingFunction::getDefaultCharType_dispred#bf#shared AND NOT …
```
=> C++: Fix expensive getWideCharType().

javascript/ql/lib/change-notes/2022-03-23-api-graph-receiver-label.md, javascript/ql/lib/semmle/javascript/ApiGraphs.qll, javascript/ql/lib/semmle/javascript/security/dataflow/ExternalAPIUsedWithUntrustedDataCustomizations.qll, javascript/ql/test/ApiGraphs/bound-args/index.js, javascript/ql/test/ApiGraphs/partial-invoke/index.js, javascript/ql/test/library-tests/frameworks/Knex/test.expected
This changes the API graph label representing the receiver of call from `parameter -1` to `receiver`.
The member predicates of `API::Node` are affected as follows:
- `getParameter(i)` no longer has a result for `i = -1`, previously it returned the receiver.
- `getAParameter()` no longer includes the receiver.
- `getLastParameter()` no longer returns the receiver when the call has zero arguments. (🤦)
In theory this is not a behaviour-preserving change, but in practice it doesn't change much:
- There are 90 uses of `getParameter(i)` outside `ApiGraphs.qll`, all of them unaffected due to how they restrict `i`.
- There are 11 uses of `getAParameter`, some of which are affected, but as far as I can tell, none of them actually intended to get the receiver.
- There are 3 uses of …
=> JS: Add dedicated API graph label for the receiver, instead of parameter -1

ruby/ql/lib/codeql/ruby/ast/internal/Variable.qll, ruby/ql/test/library-tests/ast/Ast.expected, ruby/ql/test/library-tests/ast/ValueText.expected, ruby/ql/test/library-tests/ast/calls/calls.expected, ruby/ql/test/library-tests/ast/calls/calls.rb
In the following example, we currently identify the read of `x` as a method call:
```ruby
x = 1
f = ->(y) { x }
```
This change fixes that, so we instead identify it as a captured variable read.
[Evaluation](https://github.com/github/codeql-dca-main/blob/data/hmac/pr-8517-99b5c58__nightly__lgtm-full/reports/summaries/any.md#analysis-time-per-source) shows no significant performance impact, and otherwise no changes that I can see.
=> Ruby: fix bug with captured variable reads in lambdas

ruby/ql/test/library-tests/ast/Ast.expected, ruby/ql/test/library-tests/ast/calls/calls.rb
This isn't the identity function, so it's confusing for it to be named
so.
=> Ruby: Fix bad name of lambda in test

ruby/ql/lib/change-notes/2022-03-09-http-client-getaurlpart.md, ruby/ql/lib/codeql/ruby/Concepts.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Excon.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Faraday.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/HttpClient.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Httparty.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/OpenURI.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/RestClient.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Typhoeus.qll, ruby/ql/lib/codeql/ruby/security/ServerSideRequestForgeryCustomizations.qll, ruby/ql/test/library-tests/frameworks/http_clients/HttpClients.ql
When I added the Python query in https://github.com/github/codeql/pull/7420, I did some minor changes. This is only part of those changes, I will do another PR for the changes I made to `disablesCertificateValidation` once I have had time to change our query. (this PR had been laying around for some time, so will do it now so I wont forget about it).
I'm of the understanding that we can just make any breaking changes to the API as we want, since Ruby is still in beta, so that's why I haven't done any kind of deprecation :wink: 
Notice that the change-note [would bump the major version of the library pack](https://github.com/github/codeql/blob/main/docs/change-notes.md#library-pack-change-categories). If you don't want this, let me know, and I can change things :blush:
=> Ruby: Minor change of SSRF concept

javascript/ql/src/Security/CWE-020/IncompleteUrlSchemeCheck.ql, javascript/ql/test/query-tests/Security/CWE-020/IncompleteUrlSchemeCheck.expected, javascript/ql/test/query-tests/Security/CWE-020/IncompleteUrlSchemeCheck.js
Gets a TP/TN for CVE-2021-43861 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-8481-235aa9c__default__CustomSuite/reports).
=> JS: recognize string replacement chains as scheme checks in js/incomplete-url-scheme-check

.github/workflows/ql-for-ql-build.yml, .github/workflows/ql-for-ql-dataset_measure.yml, .github/workflows/ql-for-ql-tests.yml
Updating `codeql-action` to [this branch](https://github.com/github/codeql-action/tree/erik-krogh/newQl).  
~~TODO: Wait for [this `codeql-action` PR](https://github.com/github/codeql-action/pull/998) to merge, then cleanup the commit history (both of this PR and the `codeql-action` branch).~~
=> QL: update codeql-action version in QL-for-QL

ql/ql/src/codeql_ql/ast/Ast.qll
The toplevel QLDoc was disconnected from the Ast, so it showed up in the wrong location when using the "View AST" feature in VSCode. 
And a `getImportString` utility predicate might be useful to have.
=> QL: two small improvements

javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll, javascript/ql/test/library-tests/frameworks/data/test.expected, javascript/ql/test/library-tests/frameworks/data/test.js, javascript/ql/test/library-tests/frameworks/data/test.ql, ruby/ql/lib/codeql/ruby/ApiGraphs.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowDispatch.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll, ruby/ql/lib/codeql/ruby/frameworks/ActiveStorage.qll, ruby/ql/lib/codeql/ruby/frameworks/Core.qll, ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll, ruby/ql/lib/codeql/ruby/frameworks/core/String.qll, ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModelsSpecific.qll, ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected, ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql, ruby/ql/test/library-tests/dataflow/summaries/summaries.rb
Previously we had separate tokens for non-positional arguments, like `Receiver` and `BlockArgument`.
Now these are represented as operands to `Argument`/`Parameter` tokens, as discussed with @hvitved:
Ruby:
- `Argument[self]` for the receiver (previously `Receiver`)
- `Argument[block]` for the block argument (previously `BlockArgument`)
- `Argument[foo:]` for a keyword argument named `foo` (previously not implemented)
JS:
- `Argument[this]` for the receiver (previously `Argument[-1]`)
All of the above also apply to the `Parameter` token.
The names `self` and `this` were chosen to coincide with the keyword/convention from the language.
=> JS/Ruby: Represent non-positional arguments with Argument/Parameter tokens

javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModels.qll, javascript/ql/test/library-tests/frameworks/data/warnings.expected, ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModels.qll
I'm not sure how I missed this, but the current regexp generates warnings about `Argument[0..]`.
This should not affect any queries so we can skip evaluation. I've verified that the DIL for the `js/xss` query unchanged.
=> JS/Ruby: Fix regexp in MaD checking

javascript/ql/lib/semmle/javascript/frameworks/SQL.qll
Rewrites some dynamically generated CSV rows to use type-definition rows instead.
=> JS: write all CSV rows as literals

ruby/ql/lib/codeql/ruby/ast/Constant.qll, ruby/ql/lib/codeql/ruby/ast/Expr.qll, ruby/ql/lib/codeql/ruby/ast/Literal.qll, ruby/ql/lib/codeql/ruby/ast/internal/Constant.qll, ruby/ql/lib/codeql/ruby/ast/internal/Literal.qll, ruby/ql/lib/codeql/ruby/controlflow/CfgNodes.qll, ruby/ql/lib/codeql/ruby/security/performance/RegExpTreeView.qll, ruby/ql/test/library-tests/ast/ValueText.expected
Backporting https://github.com/github/codeql/pull/8538 and https://github.com/github/codeql/pull/8484/.
=> Ruby: Cherry pick performance fixes onto `rc/3.5`

javascript/ql/lib/semmle/javascript/security/performance/ReDoSUtil.qll, javascript/ql/lib/semmle/javascript/security/performance/ReDoSUtilSpecific.qll, python/ql/lib/semmle/python/security/performance/ReDoSUtil.qll, python/ql/lib/semmle/python/security/performance/ReDoSUtilSpecific.qll, python/ql/src/Security/CWE-020/HostnameRegexpSpecific.qll, ruby/ql/lib/codeql/ruby/security/performance/ReDoSUtil.qll, ruby/ql/lib/codeql/ruby/security/performance/ReDoSUtilSpecific.qll
In https://github.com/github/codeql/pull/8489#pullrequestreview-917455000 @nickrolfe  pointed out that 
> having two different RegExpTreeView.qll files seems undesirable. Can they be merged?
There are two files named `RegExpTreeView.qll` in the Python and Ruby libraries. One of them contains language specific implementations of classes/predicates needed the the shared `ReDoSUtil.qll` module. As a result they cannot be merged, however, renaming that module to `ReDoSUtilSpecific.qll` avoids the name clash and also makes it clear that the module is just "implementation details".
=> JS/Ruby/Python: rename RegExpTreeView.qll to ReDoSUtilSpecific.qll

java/ql/src/experimental/Security/CWE/CWE-200/AndroidWebResourceResponse.qll, java/ql/src/experimental/Security/CWE/CWE-200/InsecureWebResourceResponse.java, java/ql/src/experimental/Security/CWE/CWE-200/InsecureWebResourceResponse.qhelp, java/ql/src/experimental/Security/CWE/CWE-200/InsecureWebResourceResponse.ql, java/ql/src/experimental/semmle/code/java/PathSanitizer.qll, java/ql/test/experimental/query-tests/security/CWE-200/AndroidManifest.xml, java/ql/test/experimental/query-tests/security/CWE-200/InsecureWebResourceResponse.expected, java/ql/test/experimental/query-tests/security/CWE-200/InsecureWebResourceResponse.java, java/ql/test/experimental/query-tests/security/CWE-200/InsecureWebResourceResponse.qlref, java/ql/test/experimental/query-tests/security/CWE-200/InsecureWebViewActivity.java, java/ql/test/stubs/google-android-9.0.0/android/webkit/MimeTypeMap.java, java/ql/test/stubs/google-android-9.0.0/androidx/webkit/WebViewAssetLoader.java
Android provides a <code>WebResourceResponse</code> API, which is a <code>WebView</code> class that allows an Android application to behave as a web server by handling requests of popular protocols such as <code>http(s)</code>, <code>file</code>, as well as <code>javascript</code>; and returning a response (including status code, content type, content encoding, headers and the response body). Improper implementation with insufficient input validation can lead to leaking of sensitive configuration file or user data because requests could refer to paths intended to be application-private.
It's a common vulnerability with Android applications that an implementation doesn't handle path validation correctly therefore sensitive app data can be leaked. The query detects insecure implementation …
=> Java: CWE-200 Query to detect insecure WebResourceResponse implementation

.github/workflows/check-qldoc.yml
This PR fixes `Check QLdoc coverage` failures when we add a new language.
=> QLdoc check: handle new languages gracefully

cpp/ql/lib/change-notes/2022-03-28-private-data.md, cpp/ql/lib/experimental/semmle/code/cpp/security/PrivateCleartextWrite.qll, cpp/ql/lib/experimental/semmle/code/cpp/security/PrivateData.qll, cpp/ql/lib/semmle/code/cpp/security/PrivateData.qll, cpp/ql/lib/semmle/code/cpp/security/SensitiveExprs.qll, cpp/ql/src/Security/CWE/CWE-311/CleartextTransmission.ql, cpp/ql/src/change-notes/2022-03-28-cleartext-transmission.md, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test3.cpp
Port `PrivateData.qll` from C#.
- the C# version was chosen as a base, rather than the version in experimental as had been originally planned.  They appear to be extremely similar, but the C# version is more complete.
- the experimental version has been deprecated.
- additional enhancements / tuning has been done to maximize results with minimal FPs.
Use `PrivateData.qll` in `cpp/cleartext-transmission`.
- on LGTM we find a small number of new results, generally I think they're good, a few are weak or FP results.
- `cpp/cleartext-storage-buffer`, `cpp/cleartext-storage-file` and `cpp/cleartext-storage-database` might also benefit, but I need to further investigate whether results are good for these queries.
=> C++: Port PrivateData.qll from C# and use it in cpp/cleartext-transmission

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/src/Telemetry/ExternalAPI.qll, csharp/ql/src/Telemetry/ExternalApi.qll, csharp/ql/src/Telemetry/ExternalLibraryUsage.ql, csharp/ql/src/Telemetry/SupportedExternalSinks.ql, csharp/ql/src/Telemetry/SupportedExternalSources.ql, csharp/ql/src/Telemetry/SupportedExternalTaint.ql, csharp/ql/src/Telemetry/UnsupportedExternalAPIs.ql, csharp/ql/test/query-tests/Telemetry/LibraryUsage/ExternalLibraryUsage.cs, csharp/ql/test/query-tests/Telemetry/LibraryUsage/ExternalLibraryUsage.expected, csharp/ql/test/query-tests/Telemetry/LibraryUsage/ExternalLibraryUsage.qlref, csharp/ql/test/query-tests/Telemetry/LibraryUsage/SupportedExternalTaint.expected, csharp/ql/test/query-tests/Telemetry/LibraryUsage/SupportedExternalTaint.qlref, csharp/ql/test/query-tests/Telemetry/LibraryUsage/UnsupportedExternalAPIs.expected, csharp/ql/test/query-tests/Telemetry/LibraryUsage/UnsupportedExternalAPIs.qlref, csharp/ql/test/query-tests/Telemetry/SupportedExternalSinks/SupportedExternalSinks.cs, csharp/ql/test/query-tests/Telemetry/SupportedExternalSinks/SupportedExternalSinks.expected, csharp/ql/test/query-tests/Telemetry/SupportedExternalSinks/SupportedExternalSinks.qlref, csharp/ql/test/query-tests/Telemetry/SupportedExternalSinks/options, csharp/ql/test/query-tests/Telemetry/SupportedExternalSources/SupportedExternalSources.cs, csharp/ql/test/query-tests/Telemetry/SupportedExternalSources/SupportedExternalSources.expected, csharp/ql/test/query-tests/Telemetry/SupportedExternalSources/SupportedExternalSources.qlref, java/ql/src/Telemetry/ExternalAPI.qll, java/ql/src/Telemetry/ExternalApi.qll, java/ql/src/Telemetry/ExternalLibraryUsage.ql, java/ql/src/Telemetry/SupportedExternalSinks.ql, java/ql/src/Telemetry/SupportedExternalSources.ql, java/ql/src/Telemetry/SupportedExternalTaint.ql, java/ql/src/Telemetry/UnsupportedExternalAPIs.ql
In this PR we introduce C# Telemetry queries for
* All usages of libraries (summarised).
* Usages of unsupported APIs (ie. missing flow summaries).
* Usages of supported APIs (ie. flow summaries)
* Usages of known Sources.
* Usages of known Sinks.
The structure implementation is inspired by the corresponding java implementation, but there is only limited re-use of the java implementation itself.
Furthermore, the there are some language specific differences between C# and Java.
Some explicit sharing between C# and Java has been made.
The following concepts has been translated from Java to C# (which is reflected in the C# implementation).
* Java Package -> C# Namespace.
* Java Jar container -> C# Assembly
Other relevant information:
* The *Telemetry* queries have *kind* `metric` and is …
=> C#: ExternalAPI implementation for Telemetry.

java/ql/lib/semmle/code/java/frameworks/Networking.qll, java/ql/lib/semmle/code/java/security/Encryption.qll, java/ql/lib/semmle/code/java/security/XmlParsers.qll, java/ql/src/experimental/Security/CWE/CWE-611/XXELib.qll
https://github.com/github/codeql/pull/8323 accidentally renamed a bunch of class names in qldoc referring to Java classes.
=> Java: Fix acronym casing in qldoc referring to Java class names.

csharp/ql/lib/semmle/code/csharp/Callable.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/src/utils/model-generator/internal/CaptureModelsSpecific.qll, csharp/ql/test/utils/model-generator/CaptureSummaryModels.expected, csharp/ql/test/utils/model-generator/Summaries.cs
In this PR, we make
* Support for flow models for operators. This requires that we use the operator function name as the qualified name.
* Exclude conversion operators from model generation (there is always flow through conversion operators in library code - see TaintTrackingPrivate.ql).
* Exclude methods, where a namespace is not identified.
=> C#: Operator flow

python/ql/lib/change-notes/2022-03-30-flask-recognize-body-param.md, python/ql/lib/semmle/python/frameworks/Flask.qll, python/ql/test/library-tests/frameworks/flask/response_test.py
As witnessed [here](https://github.com/Netflix/security_monkey/blob/develop/security_monkey/auth/modules.py#L266).
Note that Flask's [Response](https://github.com/pallets/flask/blob/main/src/flask/wrappers.py#L136) class inherits from `werkzeug`'s [Response](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/wrappers/response.py#L172) class.
=> Python: Flask: Identify body contents passed via named response parameter in invocations of Response constructor

cpp/ql/lib/change-notes/2022-03-31-sensitive-exprs.md, cpp/ql/lib/semmle/code/cpp/security/SensitiveExprs.qll, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextFileWrite.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test2.cpp, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test3.cpp
While working on https://github.com/github/codeql/pull/8580, I noticed some extra expressions that `SensitiveExprs.qll` ought to catch.  This PR adds these, and updates the library from using `match` to `regexpMatch` for similar reasons as in that PR.
=> C++: Some enhancements to SensitiveExprs.qll

javascript/ql/lib/semmle/javascript/ApiGraphs.qll, javascript/ql/lib/semmle/javascript/Classes.qll, javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll, javascript/ql/test/library-tests/frameworks/data/paramDecorator.ts, javascript/ql/test/library-tests/frameworks/data/test.expected, javascript/ql/test/library-tests/frameworks/data/test.js, javascript/ql/test/library-tests/frameworks/data/test.ql
Adds the following `API::Node` members:
- `getADecoratedClass`
- `getADecoratedMember`
- `getADecoratedParameter`
And corresponding MaD tokens:
- `DecoratedClass`
- `DecoratedMember`
- `DecoratedParameter`
For example:
```js
import { D } from "foo";
@D
class C // Matched by: foo;;Member[D].DecoratedClass
```
`DecoratedClass` could alternatively be expressed in terms of `Argument[0]` and `ReturnValue`. The others are not so simple, however, as they involve passing a base object and member name as an argument to the decorator, which typically then performs a reflective lookup. We don't have API edges for reflective lookups as they're tricky to model as unary operators.
So for the time being, no argument/return edges are generated for any of the decorator patterns although it's possible we …
=> JS: Add decorator edges in API graphs and corresponding MaD tokens

cpp/ql/lib/semmle/code/cpp/security/PrivateData.qll, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/CleartextTransmission.expected, cpp/ql/test/query-tests/Security/CWE/CWE-311/semmle/tests/test3.cpp
Add more patterns for detecting private data to `PrivateData.qll`, as there were some obvious gaps.  All improvements have been briefly tried out with ad-hoc LGTM queries, to avoid expressions that would produce many false positives (which is easy to do).
There is still _much_ more we could do here, especially in the fields of medical, family and financial information - but with the present design abbreviations (`mob`, `DOB`, `IBAN` and so forth) tend to produce too many false positives, so things might have to become a little more sophisticated in order to support that.
---
Doesn't really need a change note as the library was only added last week in https://github.com/github/codeql/pull/8580 (and that did have a change note).
=> C++: More enhancements to PrivateData.qll

cpp/ql/src/Best Practices/Unused Entities/UnusedLocals.ql, cpp/ql/test/query-tests/Best Practices/Unused Entities/UnusedLocals/code2.cpp
This is similar to the test case with the `if` initializer, and we should not forget about it once we support `if` initialization.
=> C++: Add `cpp/unused-local-variable` test case with `switch` initializer

csharp/ql/test/query-tests/Language Abuse/UselessCastToSelf/UselessCastToSelf.cs, csharp/ql/test/query-tests/Language Abuse/UselessCastToSelf/UselessCastToSelf.expected, csharp/ql/test/query-tests/Language Abuse/UselessCastToSelf/options
We had a false positive report [here](https://github.com/github/codeql/issues/8627). However, the casts in the report are in fact redundant, at least when using [C# 10](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions#natural-type-of-a-lambda-expression) (which is what our extractor is based on). So this PR adds some tests to document the redundant casts, and in fact it revealed a false negative as well (which we should fix later).
=> C#: Add more tests for `cs/useless-cast-to-self`

java/ql/lib/semmle/code/java/Statement.qll, java/ql/src/change-notes/2022-04-01-switch-rule-expressions.md, java/ql/test/library-tests/dataflow/switchexpr/TestSwitchExprStmtConsistency.java, java/ql/test/library-tests/dataflow/switchexpr/switchcasearrows.expected, java/ql/test/library-tests/dataflow/switchexpr/switchcasearrows.ql
Unpack `ExprStmt`s in `getRuleExpression` such that arrow switch rules look the same whether they're used in the context of a switch expression or of a switch statement. Also improve docs.
=> Java: make SwitchCase.getRuleExpression/Statement more consistent

java/ql/lib/semmle/code/java/Reflection.qll
[`Class.getMethod`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#getMethod(java.lang.String,java.lang.Class...)) only has `public` methods as result; the check for this was previously missing.
(For `getField` that check already exists, see a few lines below.)
=> Java: Fix reflection predicate for `getMethod` having non-public method result

java/ql/lib/semmle/code/java/security/CommandLineQuery.qll, java/ql/lib/semmle/code/java/security/SqlInjectionQuery.qll, java/ql/src/Security/CWE/CWE-089/SqlTainted.ql, java/ql/src/Security/CWE/CWE-089/SqlTaintedLocal.ql, java/ql/src/Security/CWE/CWE-089/SqlUnescaped.ql
Make security-related taint tracking configuration public so they can be imported for sink identification
- Update Sql Injection queries
- Update CommandLineQuery
=> Make security-related TaintTracking Configuration public

java/ql/lib/change-notes/2022-04-06-getUrl-deprecation.md, java/ql/lib/semmle/code/xml/MavenPom.qll, java/ql/src/Security/CWE/CWE-1104/MavenPomDependsOnBintray.ql, java/ql/src/Security/CWE/CWE-829/InsecureDependencyResolution.ql
I would like to eventually make all our code follow our own style guide.  
That involves changing the location providing predicate `getURL` to `getUrl`.   
(See [providing locations in CodeQL](https://codeql.github.com/docs/writing-codeql-queries/providing-locations-in-codeql-queries/#providing-urls)).  
However, that change would cause issues in `MavenPom.qll` where a `getUrl()` predicate is already used for something else.   
With my change the frontend would read the existing `getUrl` as a predicate that provides a location, and that would cause the `MavenPomDependsOnBintray.ql` query to break. 
I would therefore like to rename it.
=> Java: rename existing getUrl predicate to getRepositoryUrl

CODEOWNERS
Since @xcorail didn't have write access to this repo, that caused troubles with the CODEOWNERS file.
=> Remove @xcorail from CODEOWNERS

cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql
After discussion in https://github.com/github/codeql/pull/8435
I performed a DCA experiment and did a comparative run on all LGTM C/C++ projects, neither showed any regressions.
Still to do: DCA experiment with the `nightly` query set.
=> C++: Use `isSanitizerOut(DataFlow::Node node)` in `cpp/command-line-injection`

ruby/ql/lib/codeql/ruby/security/InsecureDependencyQuery.qll, ruby/ql/src/change-notes/2022-03-30-insecure-dependency.md, ruby/ql/src/queries/security/cwe-300/InsecureDependencyResolution.qhelp, ruby/ql/src/queries/security/cwe-300/InsecureDependencyResolution.ql, ruby/ql/src/queries/security/cwe-300/examples/bad_gemfile.rb, ruby/ql/src/queries/security/cwe-300/examples/good_gemfile.rb, ruby/ql/test/query-tests/security/cwe-300/Gemfile, ruby/ql/test/query-tests/security/cwe-300/InsecureDependency.expected, ruby/ql/test/query-tests/security/cwe-300/InsecureDependency.ql, ruby/ql/test/query-tests/security/cwe-300/InsecureDependencyResolution.ql, ruby/ql/test/query-tests/security/cwe-300/foo.rb
This is a port of the JS query of the same name. It looks for places in a `Gemfile` where a `http` or `ftp` URL is specified. The tests are written using inline expectations.
=> Ruby: Add rb/insecure-dependency query

csharp/downgrades/qlpack.yml
This PR removes the `version` field from the C# downgrades pack.  C# is the only downgrades pack that has a `version` field, and this change brings it in line with all the other downgrades packs.
Downgrades are bundled with the extractor and are not published independently.  So it does not need a version number.  Generally it is good practice to omit the version number for a downgrades pack because that reduces the likelihood that it might be accidentally published.
=> C#: remove version from downgrades pack

cpp/ql/lib/semmle/code/cpp/AutogeneratedFile.qll
The issue was that `AutoGeneratedFile.qll` produces a concatenation of all comments (believed to be) at the beginning of a file.  This is usually only one or a few comments, but can [very rarely](https://lgtm.com/projects/g/dcreager/libcork/snapshot/8d8ae8145a675ea75f43c1a0ca20745116738ec1/files/_lgtm_build_dir/tests/u128-tests-add.c.in?sort=name&dir=ASC&mode=heatmap#L0) include a huge amount of data leading to a "String too long" error during evaluation.  The fix is to limit it to a maximum of 1000 lines (which may seem excessive, but think I remember seeing files containing license + header + autogenerated comment at around line 100).
In principle this change can affect results, in practice it should do so only extremely rarely (where the 1000 line cutoff matters).  Here's a …
=> C++: Fix issue with extremely long comments in AutogeneratedFile.qll

javascript/ql/lib/semmle/javascript/security/dataflow/XssThroughDomCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/XssThroughDomQuery.qll, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/XssThroughDom.expected, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/xss-through-dom.js
Recognizes the source for CVE-2021-32622  
Also adds a taint-step for `URL.createObjectURL`, also inspired by the same CVE.  
I've just added the step to the `js/xss-throgh-dom`.   
The step is only relevant for XSS, and I think it's mostly relevant for `js/xss-throgh-dom`, so I'm just putting it there for now.    
[Evaluation looks fine](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-8678-0435cee__nightly-old__CustomSuite/reports). One new result that looks like a TP.
=> JS: Add files as a source for `js/xss-through-dom`

docs/codeql/ql-language-reference/formulas.rst
The only documentation of `none()` was blatantly wrong, and `any()` wasn't even mentioned in the language reference on formulas.
=> Doc: Add any() and none() to the language reference.

config/identical-files.json, ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/codeql_ql/ast/internal/AstNodeNumbering.qll, ql/ql/src/codeql_ql/ast/internal/AstNodes.qll, ql/ql/src/codeql_ql/dataflow/DataFlow.qll, ql/ql/src/codeql_ql/dataflow/internal/DataFlowNumbering.qll, ql/ql/src/codeql_ql/dataflow/internal/GlobalFlow.qll, ql/ql/src/codeql_ql/dataflow/internal/LocalFlow.qll, ql/ql/src/codeql_ql/dataflow/internal/NodesInternal.qll, ql/ql/src/codeql_ql/dataflow/internal/VarScoping.qll, ql/ql/src/queries/reports/FrameworkCoverage.ql, ql/ql/test/TestUtilities/InlineExpectationsTest.qll, ql/ql/test/TestUtilities/InlineExpectationsTestPrivate.qll, ql/ql/test/dataflow/getAStringValue/Foo.qll, ql/ql/test/dataflow/getAStringValue/getAStringValue.ql, ql/ql/test/printAst/printAst.expected
This adds facilities for reasoning about data flow between expression in CodeQL.
As a rule of thumb, "A flows to B" means the two expressions could be unified given a sufficient number of predicate inlinings, followed by DNF conversion. For example, `A` flows to `B` and `C` here, but `B` does not flow to `C`:
```
x = A and (x = B or x = C)
--> (to DNF)
(x = A and x = B) or (x = A and x = C)
```
Since (a copy of) `A,B` end up in the same clause where they bound by equality, `A` flows to `B` and vice versa. Same for `A,C` but not for `B,C`.
"Flows to" is a symmetric relation, but "flows to with call steps" is not, which often comes up in the implementation. This is why I prefer this terminology over something like "unifiable with".
This PR adds type-tracking, but not …
=> QL: Add facilities for data flow

swift/BUILD.bazel, swift/extractor/BUILD.swift-prebuilt.bazel
This PR adds a test SDK used for basic testing of the Swift extractor.
=> Swift: package test SDK

README.md
This PR updates the `README` text to clarify that all code in this repository is licensed under the MIT license without any restrictions. The previous explanation could (unintentionally) be interpreted in multiple ways, leading to [confusion](https://github.com/github/codeql/issues/8716).
@niroshan: would love :eyes: from you on this as you were the last person to edit this file. Also cc @felicitymay for info and any documentation suggestions.
=> Update README to clarify license explanation

CODEOWNERS
To make sure the right people are pinged when a change like #5893 are made. The PM team will pull in our friends in documentation (cc @felicitymay) if/when needed.
I used @github/code-scanning-product (rather than @github/codeql-product) so the ping would include @jf205 and myself. We only see a couple of changes per year to those files, so hopefully this shouldn't cause too much noise for the other PMs in @github/code-scanning-product.
=> Update CODEOWNERS for documentation and license changes

javascript/ql/lib/semmle/javascript/ApiGraphs.qll, python/ql/lib/semmle/python/ApiGraphs.qll
See https://github.com/github/codeql/pull/8785 
Evaluations are underway, should be uneventful.
=> JS/PY: mention newtype constructors in API graph label classes

csharp/ql/src/utils/model-generator/CaptureSinkModels.ql, csharp/ql/src/utils/model-generator/CaptureSourceModels.ql, csharp/ql/src/utils/model-generator/CaptureSummaryModels.ql, misc/suite-helpers/code-scanning-selectors.yml, misc/suite-helpers/security-and-quality-selectors.yml, misc/suite-helpers/security-extended-selectors.yml
I verified locally that e.g.
```
codeql resolve queries csharp/ql/src/codeql-suites/csharp-code-scanning.qls | grep Model
```
would return the three queries before, but not after.
=> C#: Exclude model generation queries from all suites

config/identical-files.json, java/ql/lib/semmle/code/java/dataflow/TaintTracking3.qll, java/ql/lib/semmle/code/java/dataflow/internal/tainttracking3/TaintTrackingImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/tainttracking3/TaintTrackingParameter.qll, java/ql/lib/semmle/code/java/frameworks/SnakeYaml.qll, java/ql/lib/semmle/code/java/security/AndroidIntentRedirectionQuery.qll, java/ql/lib/semmle/code/java/security/CleartextStorageClassQuery.qll, java/ql/lib/semmle/code/java/security/CleartextStorageQuery.qll
While trying to enumerate sinks as perceived by various queries, https://github.com/github/codeql/discussions/8742 noticed that some of our qll files that define sinks can't be imported concurrently. This turned out to be because some QLLs defy the usual pattern that lower-numbered dataflow configs are defined in terms of higher ones, not the reverse. By flipping the dataflow instance numbers here, it becomes possible to import all of the `java/ql/lib/semmle/code/java/security` directory concurrently.
=> Java: Avoid higher-numbered dataflow configs that depend on lower-numbered ones

ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll, ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected
`SplatExpr`s are modelled using flow summaries, so there is no need to include them explicitly in `defaultAdditionalTaintStep`.
=> Ruby: Exclude `SplatExpr` from taint tracking

java/ql/lib/semmle/code/java/dataflow/internal/tainttracking3/TaintTrackingImpl.qll
https://github.com/github/codeql/pull/8748 added a copy of `TaintTrackingImpl.qll`.  
But the shared implementation changed in the meantime.   
So now we got the sync files check failing on main.
=> Java: get tainttracking3/TaintTrackingImpl.qll in sync

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPublic.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/SsaImpl.qll, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.expected, ruby/ql/test/library-tests/dataflow/barrier-guards/barrier-guards.rb
Related to https://github.com/github/codeql/pull/2513.
=> Ruby: Handle captured variables in `BarrierGuard::getAGuardedNode()`

misc/suite-helpers/lgtm-selectors.yml, misc/suite-helpers/security-and-quality-selectors.yml, misc/suite-helpers/security-extended-selectors.yml
Thanks to @esbena for pointing this out.
@esbena I did a sweep over all the selectors and added the exclusion rule in all of them (instead of just `security-extended-selectors.yml`). I hope that's not controversial 🤞.
=> Exclude internal diagnostics from all selectors

ruby/ql/lib/codeql/ruby/security/CodeInjectionQuery.qll, ruby/ql/lib/codeql/ruby/security/ServerSideRequestForgeryQuery.qll, ruby/ql/lib/codeql/ruby/security/UrlRedirectQuery.qll, ruby/ql/lib/codeql/ruby/security/performance/RegExpInjectionQuery.qll, ruby/ql/src/queries/security/cwe-918/ServerSideRequestForgery.ql
Most of the time you import the `PathGraph` module from the `.ql` file of a path-query.  
But sometimes you also imported it from the `Query.qll` file (I removed those).  
(I found this from looking at redundant imports, and some of your `PathGraph` imports showed up as redundant).
=> Ruby: dont import the PathGraph module from Query.qll files

javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll, javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/CallGraphs.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSteps.qll, javascript/ql/src/change-notes/2022-04-21-static-accessors.md, javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/Test.expected, javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/Test.ql, javascript/ql/test/library-tests/CallGraphs/AnnotatedTest/accessors.js, javascript/ql/test/library-tests/ClassNode/tests.expected, javascript/ql/test/library-tests/ClassNode/tests.ql, javascript/ql/test/library-tests/ClassNode/tst.js
Fixes two problems with our call graph for accessors, and adds support for calls to static accessors declared on a class.
This PR deals with two bugs:
- `ClassNode.getStaticMethod` previously included static accessors. This lead to some FP call edges as a result from confusing accessors and methods.
- A `PropWrite` node exists for accessors, representing the installation of an accessor. We accidentally saw these as potential calls to the setter. 
It is addressed as follows:
- Introduced `ClassNode.getStaticMember`, analogous to `ClassNode.getInstanceMember`, and made `getStaticMethod` only include methods.
- Added accessor-calls to static accessors to the call graph, and made sure static method calls aren't seen as calls to an accessor.
- Added `PropWrite.isAccessorInstallation` to …
=> JS: Support static accessor calls and fix some FP accessor-calls

cpp/ql/lib/semmle/code/cpp/ir/internal/CppType.qll
See #8805 for the underlying issue. The symptom was bad IR generation on a large number of functions because we never generated an `IRVariable` for a parameter with the affected type.
=> C++: Work around missing size for typedef

cpp/ql/test/query-tests/jsf/4.13 Functions/AV Rule 114/test.c
This is a reduced version of the only regression I'm currently seeing in DCA after upgrading EDG. Add a test case now, so this devolves to a test case failure during the upgrade.
=> C++: Add non-returning function test case using `__builtin_expect`

cpp/ql/lib/change-notes/2022-04-22-no-size-array.md, cpp/ql/lib/semmle/code/cpp/commons/Buffer.qll
Currently the extractor incorrectly emits <strike>-1</strike> 0 for the array `data` below:
```
struct myStruct { // c
...
char data[]; // v
};
```
This will change with the next version of EDG, and  no size will be emitted anymore. This PR makes sure `Buffer.qll` handles arrays without sizes.
This is a separate PR to ensure these these changes do not get lost in a much larger PR and to be able to check that this doesn't cause any regressions already before the EDG upgrade.
=> C++: Cover variable sized member arrays without a size in `Buffer.qll`

docs/codeql/ql-language-reference/expressions.rst
Currently the documentation sounds like the `<expression>` must always be "of numeric type or of type `string`", however that is incorrect, as also described correctly by the [full language specification](https://codeql.github.com/docs/ql-language-reference/ql-language-specification/#aggregations):
> The type of the expression in a `max`, `min` or `rank` aggregation **without an ordering directive expression** must be an orderable type
(emphasis mine)
For example the following is valid:
```codeql
import java
select min(File f | f.getExtension() = "java" | f order by f.getTotalNumberOfLines())
```
```codeql
import java
select rank[5](File f | f.getExtension() = "java" | f order by f.getTotalNumberOfLines())
```
=> Clarify `min`, `max` and `rank` documentation

java/ql/lib/change-notes/2022-03-28-JumpStmt-as-superclass.md, java/ql/lib/semmle/code/java/Expr.qll, java/ql/lib/semmle/code/java/Statement.qll, java/ql/src/Likely Bugs/Statements/ContinueInFalseLoop.ql, java/ql/src/Likely Bugs/Termination/ConstantLoopCondition.ql, java/ql/src/Security/CWE/CWE-129/ArraySizing.qll, java/ql/src/Security/CWE/CWE-835/InfiniteLoop.ql, java/ql/test/library-tests/stmts/JumpTargets.expected, java/ql/test/library-tests/stmts/SwitchCases.expected, java/ql/test/library-tests/stmts/options, java/ql/test/library-tests/stmts/stmts/A.java
=> Java: Make `JumpStmt` a proper superclass

cpp/ql/lib/change-notes/2022-04-25-windows-pool-allocation-functions.md, cpp/ql/lib/semmle/code/cpp/models/implementations/Allocation.qll
Add the following Windows pool allocation functions in `Allocation.qll`:
- [ExAllocatePool2](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool2)
- [ExAllocatePool3](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool3)
- [ExAllocatePoolZero](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepoolzero)
This improves the detection of bugs on Windows kernel drivers.
=> C++: add new Windows pool allocation functions in `Allocation.qll`

java/ql/lib/change-notes/2022-04-22-sharedprefs-fluent-steps.md, java/ql/lib/semmle/code/java/dataflow/ExternalFlow.qll, java/ql/lib/semmle/code/java/frameworks/android/SharedPreferences.qll, java/ql/test/query-tests/security/CWE-312/CleartextStorageSharedPrefsTest.java
Adds fluent steps for the `SharedPreferences$Editor` class.
=> Java: Add value-preserving flow steps for Android's SharedPreferences

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForOnActivityResult.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl2.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplForLibraries.qll
```
Tuple counts for DataFlowImpl::Stage2::fwdFlow#9021cc4c#ffffff#join_rhs/3@f92f70ji after 1m27s:
1500      ~0%     {2} r1 = JOIN project#DataFlowImpl::Stage2::fwdFlow#9021cc4c#ffffff#nullary WITH DataFlowImpl::Stage1::revFlowState#9021cc4c#ff CARTESIAN PRODUCT OUTPUT Rhs.1 'arg2', Rhs.0
226339000 ~0%     {3} r2 = JOIN r1 WITH DataFlowImpl::Stage1::revFlow#9021cc4c#2#fff_20#join_rhs ON FIRST 1 OUTPUT Lhs.1 'arg1', Lhs.0 'arg2', Rhs.1 'arg0'
226315000 ~0%     {3} r3 = r2 AND NOT DataFlowImpl::stateBarrier#9021cc4c#fff(Lhs.2 'arg0', Lhs.0 'arg1', Lhs.1 'arg2')
226315000 ~8%     {3} r4 = SCAN r3 OUTPUT In.2 'arg0', In.0 'arg1', In.1 'arg2'
return r4
```
from
```
project#DataFlowImpl::Stage2::fwdFlow#9021cc4c#ffffff#nullary(),
DataFlowImpl::Stage1::revFlowState#9021cc4c#ff(state, config), …
```
=> Dataflow: Fix join-on-config producing a CP.

javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/lib.js
Gets a TN for CVE-2020-28503 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/parenSan__nightly__security-extend__1/reports). (Ignore the backref).
=> JS: step through parentheses in barrier functions

ruby/ql/test/library-tests/modules/ancestors.expected, ruby/ql/test/library-tests/modules/ancestors.ql, ruby/ql/test/library-tests/modules/superclasses.expected, ruby/ql/test/library-tests/modules/superclasses.ql
These tests using graph queries didn't specify any ordering, so they were subject to the whims of the evaluator's internal implementation details, and started failing with a recent CodeQL CLI update.
Now they pass with both the old and new CLIs.
cc @erik-krogh
=> Ruby: fix graph query tests by defining total ordering

ruby/ql/test/library-tests/modules/superclasses.ql
I introduced a (fairly harmless) typo in #8879 – the key name is `semmle.label`, not `semmle.value`. In fixing it, I've changed the corresponding value to the empty string, so that the test output doesn't change.
=> Ruby: fix typo in edge key for graph query

.github/workflows/codeql-analysis.yml, ruby/extractor/src/main.rs
All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Replace all git.io links with their actual URLs.
=> Replace `git.io` link with the actual URL

ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll, ruby/ql/test/library-tests/dataflow/array-flow/array-flow.expected
The outputs into `self` are not needed, since that will be handled by ordinary use-use flow at the call sites.
=> Ruby: Simplify flow summary for `fetch`

python/ql/lib/semmle/python/frameworks/Asyncpg.qll, python/ql/lib/semmle/python/frameworks/Cryptography.qll, python/ql/lib/semmle/python/frameworks/Django.qll, python/ql/lib/semmle/python/frameworks/Flask.qll, python/ql/lib/semmle/python/frameworks/FlaskSqlAlchemy.qll, python/ql/lib/semmle/python/frameworks/internal/SubclassFinder.qll, python/ql/lib/semmle/python/regex.qll, python/ql/src/Security/CWE-215/FlaskDebug.ql, python/ql/src/experimental/semmle/python/frameworks/Flask.qll, python/ql/src/experimental/semmle/python/frameworks/NoSQL.qll, python/ql/src/experimental/semmle/python/frameworks/Xml.qll, python/ql/test/experimental/dataflow/typetracking/moduleattr.ql, python/ql/test/experimental/dataflow/typetracking/tracked.ql
I took another look at your code after our recent API-graph talks.  
I've refactored a bunch, but you still have a whole lot of type-trackers left.  
I don't think the remaining uses of type-trackers can be refactored to API-graphs.  
A lot of the remaining type-trackers start tracking from an abstract-class that are not guaranteed to be an API-node.  
And a bunch of them rely of edges not currently included in API-graphs (subscript, ...). 
You had a lot of type-trackers that started with `node::getAUse()`, and then tracked from there.   
It's redundant to use `getAUse()` and then afterwards type-track the results, so I converted those to `getAnImmediateUse()`. 
I also looked through all uses of `getAUse()` and refactored anything that looked suspicious.  
--- 
I'm a bit puzzled by that …
=> PY: more API-graphs refactorings

cpp/ql/src/Security/CWE/CWE-611/XXE.ql, cpp/ql/test/query-tests/Security/CWE/CWE-611/XXE.expected, cpp/ql/test/query-tests/Security/CWE/CWE-611/tests.cpp
Add support for `createLSParser` to the CWE-611 XXE query.
This particular extension is straightforward and we already have test cases.
=> C++: Add support for createLSParser to the CWE-611 XXE query.

ruby/ql/lib/codeql/ruby/regexp/RegExpTreeView.qll, ruby/ql/src/change-notes/2022-04-14-rb-missing-regexp-anchor.md, ruby/ql/src/queries/security/cwe-020/MissingRegExpAnchor.qhelp, ruby/ql/src/queries/security/cwe-020/MissingRegExpAnchor.ql, ruby/ql/src/queries/security/cwe-020/examples/missing_regexp_anchor_bad.rb, ruby/ql/src/queries/security/cwe-020/examples/missing_regexp_anchor_good.rb, ruby/ql/test/library-tests/regexp/parse.expected, ruby/ql/test/library-tests/regexp/regexp.expected, ruby/ql/test/query-tests/security/cwe-020/MissingRegExpAnchor/MissingRegExpAnchor.expected, ruby/ql/test/query-tests/security/cwe-020/MissingRegExpAnchor/MissingRegExpAnchor.qlref, ruby/ql/test/query-tests/security/cwe-020/MissingRegExpAnchor/missing_regexp_anchor.rb
This is a port of the JS query of the same name. A few adjustments are needed to adapt to our dataflow and regex libraries, so it's not so easy to share the implementation. I've also added a Ruby-specific check for regexes that use `^` and `$`, which match the start/end of a line rather than the whole string. These regexes should probably use `\A` and `\z` instead.
=> Ruby: Add MissingRegExpAnchor query

ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll, ruby/ql/lib/codeql/ruby/security/InsecureDownloadCustomizations.qll, ruby/ql/lib/codeql/ruby/security/InsecureDownloadQuery.qll, ruby/ql/src/change-notes/2022-04-14-rb-insecure-download.md, ruby/ql/src/queries/security/cwe-829/InsecureDownload.qhelp, ruby/ql/src/queries/security/cwe-829/InsecureDownload.ql, ruby/ql/src/queries/security/cwe-829/examples/insecure_download.rb, ruby/ql/src/queries/security/cwe-829/examples/secure_download.rb, ruby/ql/test/library-tests/frameworks/http_clients/HttpClients.expected, ruby/ql/test/query-tests/security/cwe-829/InsecureDownload.expected, ruby/ql/test/query-tests/security/cwe-829/InsecureDownload.ql, ruby/ql/test/query-tests/security/cwe-829/insecure_download.rb
This query finds cases where a potentially unsafe file is downloaded
over an unsecured connection.
=> Ruby: Add InsecureDownload query

javascript/ql/lib/semmle/javascript/Functions.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSteps.qll, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingFunction/PrototypePollutingFunction.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingFunction/tests.js
This adds a flow step that has been missed for flow that goes from an argument to a `...rest` parameter, eg:
```javascript
f('x', 1, 2);
//        |
// ...    |
//        +-----------------+
function f(x, ...rest) { // |  
console.log(rest[1]);  // |
//            ^^^^^^^       |
//                 |        |
//                 +--------+
}
```
This helps find one of the example I posted in #8846.
I'll trigger an experiment to see what other results this will get. Could easily turn up things.
=> JS: Add flow step to `...rest` parameters

python/ql/lib/semmle/python/essa/Essa.qll
Observed on `FreeCAD/FreeCAD`:
```
Tuple counts for Essa::MethodCallsiteRefinement#24e22a14#f/1@274967ic after 34.5s:
638284     ~0%     {2} r1 = SCAN Essa::TEssaNodeRefinement#24e22a14#ffff OUTPUT In.0, In.3 'this'
636521     ~0%     {2} r2 = r1 AND NOT Essa::SingleSuccessorGuard#class#24e22a14#f(Lhs.1 'this')
1579493668 ~0%     {2} r3 = JOIN r2 WITH SsaDefinitions::SsaSource::method_call_refinement#9197156e#fff ON FIRST 1 OUTPUT Lhs.1 'this', Rhs.2
266673     ~3%     {1} r4 = JOIN r3 WITH Essa::EssaNodeRefinement::getDefiningNode#dispred#f0820431#ff ON FIRST 2 OUTPUT Lhs.0 'this'
return r4
```
After a bit of unbinding, we have:
```
Tuple counts for Essa::MethodCallsiteRefinement#24e22a14#f/1@d73d8e27 after 66ms:
215168 ~1%     {2} r1 = SCAN …
```
=> Python: Fix bad join in `MethodCallsiteRefinement`

ql/ql/src/codeql_ql/style/AcronymsShouldBeCamelCaseQuery.qll, ql/ql/src/queries/style/AcronymsShouldBeCamelCase.ql, ql/ql/test/queries/style/AcronymsShouldBeCamelCase/AcronymsShouldBeCamelCase.expected, ql/ql/test/queries/style/AcronymsShouldBeCamelCase/AcronymsShouldBeCamelCase.qlref, ql/ql/test/queries/style/AcronymsShouldBeCamelCase/Test.qll
* Improve displayed message. In the PR interface it was not always clear which name was referred to, especially in the case of classes, which can be many lines long
* Filter out `NewType` like `NewTypeBranch`. This showed up, e.g., here https://github.com/github/codeql/security/code-scanning/29265
=> QL: Improve camel case query

.github/workflows/csv-coverage-metrics.yml, csharp/ql/src/Metrics/Summaries/FrameworkCoverage.ql
In this PR we
- Port the Java FrameworkCoverage query to C#.
- Include the generation in the "publish" workflow (like for java).
=> C#: Port the java FrameworkCoverage query.

javascript/ql/src/Security/CWE-915/PrototypePollutingFunction.ql, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingFunction/PrototypePollutingFunction.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingFunction/tests.js
Fixes another FN from #8846 (CVE-2021-23574).
The bottom line is, that using iteration like this used to work:
```javascript
function forEachPropNoTempVar(obj, callback) {
const keys = Object.keys(obj)
const len = keys.length
for (let i = 0; i < len; i++) {
const key = keys[i];
callback(key, obj[key])
}
}
```
But iteration like that did not (now fixed):
```javascript
function forEachPropNoTempVar(obj, callback) {
const keys = Object.keys(obj)
const len = keys.length
for (let i = 0; i < len; i++) {
// no local variable used
callback(keys[i], obj[keys[i]])
}
}
```
=> JS: fix a FN for prototype polluting function query

javascript/ql/lib/semmle/javascript/security/dataflow/DomBasedXssCustomizations.qll
=> JS: Nit: Fix typo in QLDoc

python/ql/lib/semmle/python/Exprs.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowPublic.qll, python/ql/lib/semmle/python/pointsto/PointsTo.qll
Makes this
```
(21s) Tuple counts for DataFlowPublic::import_star_read#ff/2@fcd5e6nr after 8.5s:
9743      ~6%     {3} r1 = SCAN num#DataFlowPublic::TModuleVariableNode#fff OUTPUT In.1, In.0, In.2 'result'
9743      ~1%     {3} r2 = JOIN r1 WITH Variables::Variable::getId_dispred#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2 'result'
390808917 ~3%     {3} r3 = JOIN r2 WITH Flow::NameNode::getId_dispred#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2 'result'
307       ~0%     {2} r4 = JOIN r3 WITH ImportStar::ImportStar::importStarResolvesTo#ff ON FIRST 2 OUTPUT Lhs.0, Lhs.2 'result'
307       ~0%     {2} r5 = JOIN r4 WITH num#DataFlowPublic::TCfgNode#ff ON FIRST 1 OUTPUT Rhs.1 'n', Lhs.1 'result'
return r5
```
become this
```
(17s) Tuple counts for …
```
=> Python: Fix bad join in `import_star_read`

.github/workflows/csv-coverage-metrics.yml
This brings all uses of the CodeQL Action in this repo apart from QL-for-QL onto the Node 16 Actions runtime.
We didn't receive a Dependabot update here because we use different versions of the CodeQL Action in this repo, and Dependabot updates for Actions are only supported when the same version of the Action is used throughout the repo.
=> Use codeql-action/upload-sarif@main in CSV coverage metrics workflow

python/ql/lib/semmle/python/dataflow/new/internal/Attributes.qll, python/ql/test/experimental/dataflow/typetracking/attribute_tests.py
I'm still not convinced that this is the best solution, but it fixes the
issue in the short term. When we eventually clean up the whole
`EssaNode` business, we can consider whether there's a better way to do
this.
--- 
I don't think this requires a change note, but will happily add one if needed.
=> Python: Add support for global attribute writes

javascript/ql/lib/semmle/javascript/frameworks/data/internal/ApiGraphModelsSpecific.qll, ruby/ql/lib/codeql/ruby/frameworks/data/internal/ApiGraphModelsSpecific.qll
There were some predicates/types used by `ApiGraphModels.qll` that were unmentioned in the top comment of `ApiGraphModelsSpecific.qll`.  
So I added all the required types/predicates to the list, and made sure the comment is identical in the two files.
=> JS/RB: have `ApiGraphModelsSpecific.qll` mention all the required predicates

docs/codeql/codeql-cli/analyzing-databases-with-the-codeql-cli.rst
Fixes the link to 'Analyzing a CodeQL database' in [Analyzing databases with the CodeQL CLI](https://codeql.github.com/docs/codeql-cli/analyzing-databases-with-the-codeql-cli/#running-query-suites). It should point to https://docs.github.com/en/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/configuring-codeql-cli-in-your-ci-system#analyzing-a-codeql-database.
=> Fix broken link in analyzing-databases-with-the-codeql-cli.rst

cpp/ql/lib/semmle/code/cpp/security/Overflow.qll, cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql, cpp/ql/src/Likely Bugs/OO/UnsafeUseOfThis.ql
These workarounds are no longer needed from CodeQL CLI 2.9.0.
So far I've checked that there's no re-evaluation by looking through the output of
```sh
codeql query compile --dump-dil cpp/ql/src/codeql-suites/cpp-security-and-quality.qls > dil.log 2>&1
```
Comparing this output before and after removing the imports, I can see that some auto-generated names change (suffixes like `#2` come and go), but that's not a problem on its own. The important thing is that there's no change in how many distinct copies of each predicate we evaluate. For this, I compared the output of the following command before and after, finding that there were no changes.
```sh
grep '^query ' dil.log |grep -v '^query #select' |sed 's/ =.*//' |sort -u |sed 's/#.*//' |uniq -c |sort -n
```
I'll start a DCA run to …
=> C++: Remove import order workarounds

cpp/ql/lib/semmle/code/cpp/Function.qll, cpp/ql/src/Likely Bugs/Memory Management/SuspiciousCallToMemset.ql, csharp/ql/lib/semmle/code/csharp/exprs/Call.qll, csharp/ql/src/API Abuse/IncorrectCompareToSignature.ql, csharp/ql/src/Documentation/XmldocExtraParam.ql, csharp/ql/src/Documentation/XmldocExtraTypeParam.ql, csharp/ql/src/Documentation/XmldocMissingException.ql, csharp/ql/src/Documentation/XmldocMissingParam.ql, csharp/ql/src/Documentation/XmldocMissingReturn.ql, csharp/ql/src/Documentation/XmldocMissingSummary.ql, csharp/ql/src/Documentation/XmldocMissingTypeParam.ql, java/ql/lib/semmle/code/java/frameworks/JaxWS.qll, java/ql/lib/semmle/code/java/frameworks/spring/SpringEntry.qll, java/ql/src/experimental/Security/CWE/CWE-939/IncorrectURLVerification.ql, javascript/ql/lib/semmle/javascript/DefUse.qll, javascript/ql/lib/semmle/javascript/Externs.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeShellCommandConstructionCustomizations.qll
This PR fixes QL comments used to generate QL documentation.  They are mostly about back-quoting angle brackets so that they are property escaped in the HTML output.
=> Fix syntax errors in QL comments

python/ql/lib/change-notes/2022-05-02-flask-request-files-modeling.md, python/ql/lib/semmle/python/frameworks/Flask.qll, python/ql/test/library-tests/frameworks/flask/taint_test.py
Spotted when looking over [this part](https://github.com/github/codeql/pull/8693/files/4e5afab08232e8d724f054e8360d19d817893f30..50bfc8eaa09592b22826d50ee6f7a0e896c4f9de#diff-8b08a136e9cfca3a648e75cd69ebe5ebd15b9911381e3b0ac8fb5a73354b8255L424) of @erik-krogh s API graph refactoring PR.
=> Python: Flask: Improve `request.files` modeing

cpp/ql/src/Security/CWE/CWE-611/XXE.ql, cpp/ql/test/query-tests/Security/CWE/CWE-611/XXE.expected, cpp/ql/test/query-tests/Security/CWE/CWE-611/tests.h, cpp/ql/test/query-tests/Security/CWE/CWE-611/tests4.cpp
Add test cases + support for the `libxml2` library in the CWE-611 XXE query.
It turns out less data flow is required for checking this library than for Xerces, so much of the existing query logic isn't really used here.  However, I feel the results are best presented in a single place, not in two separate queries.
Change note covered by https://github.com/github/codeql/pull/8948.
=> C++: Support libxml2 in the XXE query

ruby/ql/lib/codeql/ruby/frameworks/core/Array.qll
The flow summaries that are implemented with an abstract base class restricting the method name, and child classes using that method name, had unfortunate join orders:
```
r1 = JOIN Call::MethodCall::getMethodName#dispred#f0820431#ff WITH Call::MethodCall::getMethodName#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.0, (Lhs.1 ++ "_arg"), Rhs.1
```
They weren't causing catastrophic slowdowns, but fixing them should give a small speedup.
=> Ruby: fix some flow summary join orders

javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll, javascript/ql/lib/semmle/javascript/internal/CachedStages.qll
[Evaluation shows a decent speedup](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/cacheReg__nightly__security-extend/reports#analysis-time-per-source-compact-always-interesting), mostly for big benchmarks.  
[And the db-size is almost completely unaffected](https://github.com/github/codeql-dca-main/blob/data/erik-krogh/cacheReg__nightly__security-extend/reports/db-sizes/entire-db.afterNormalCleanup.txt).
=> JS: cache RegExpCreationNode::getAReference

javascript/ql/src/Declarations/UnreachableMethodOverloads.ql
Saves ~10s on VSCode. 
[Evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-8549-47a9376__nightly-old__CustomSuite__1/reports). Running just that query is now ~8% faster.
=> JS: fix bad join in js/unreachable-method-overloads

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForOnActivityResult.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl2.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplForLibraries.qll
Before
```
[2022-05-02 15:47:16] (1280s) Tuple counts for DataFlowImpl::Subpaths::subpaths#656de156#ffff/4@c5f3dclb after 3m22s:
8389013    ~4%     {5} r1 = JOIN DataFlowImpl::Subpaths::subpaths#656de156#ffff#shared WITH DataFlowImpl::PathNode::getASuccessor#dispred#f0820431#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'arg', Lhs.1, Lhs.2, Lhs.3, Lhs.4 'out'
6689751    ~0%     {4} r2 = JOIN r1 WITH DataFlowImpl::Subpaths::subpaths03#656de156#ffffff_034512#join_rhs ON FIRST 4 OUTPUT Rhs.4, Lhs.4 'out', Lhs.0 'arg', Rhs.5 'ret'
1513839768 ~1%     {5} r3 = JOIN r2 WITH DataFlowImpl::PathNodeImpl::getNodeEx#dispred#f0820431#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.1 'out', Lhs.2 'arg', Lhs.3 'ret', Rhs.1 'par', Lhs.3 'ret'
1513839768 ~1%     {5} r4 = r3 AND NOT …
```
=> Data flow: Speedup `subpaths` predicate

docs/codeql/ql-language-reference/ql-language-specification.rst, docs/codeql/ql-language-reference/variables.rst
To prepare for a future QL language change where variable names must start with a lower-case letter, this commit updates the QL language reference (including the language specification) to change the variable name grammar from `simpleId` to `lowerId`.
To find the locations I should change, I grepped for `variable` and `simpleId`. I also looked manually through [the reference section on variables](https://codeql.github.com/docs/ql-language-reference/variables/).
=> QL language reference: variables must be lowerId

.github/labeler.yml
This pull request changes the configuration of the Pull request labeler  workflow to no longer add the `JS` label on files related to `adaptivethreatmodeling` . The labeler workflow uses a `pull_request_target` trigger which means it will use the workflow definition from the default branch. This means the changes in this PR have no effect until they are merged into the `main` branch.
To test this pull request I pushed the same changes directly to `main` on my [forked repo](https://github.com/aibaars/codeql/commit/c7b2da5e3916473a7b35aceb9602bdb3000819fe) and made a couple of draft pull requests to check that the labeler works as expected:
* https://github.com/aibaars/codeql/pull/14
* https://github.com/aibaars/codeql/pull/15
* https://github.com/aibaars/codeql/pull/16 
* …
=> JS: exclude ATM folder from labeler

swift/codegen/BUILD.bazel, swift/codegen/lib/cpp.py, swift/codegen/lib/dbscheme.py, swift/codegen/requirements.txt, swift/codegen/templates/cpp_traps.mustache, swift/codegen/test/BUILD.bazel, swift/codegen/test/test_cpp.py, swift/codegen/test/test_dbscheme.py, swift/codegen/test/test_trapgen.py, swift/codegen/test/utils.py, swift/codegen/trapgen.py
Closes: https://github.com/github/codeql-c-team/issues/981
=> Swift: add `trapgen` unit tests

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForOnActivityResult.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl2.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplForLibraries.qll
https://github.com/github/codeql/pull/9017 follow-up.
Before
```
Tuple counts for DataFlowImplForContentDataFlow::Subpaths::subpaths#d678ef22#ffff@426ff9sr:
8372517   ~0%    {3} r1 = JOIN DataFlowImplForContentDataFlow::PathNode::getASuccessor#dispred#f0820431#ff_10#join_rhs WITH DataFlowImplForContentDataFlow::PathNodeImpl::getNodeEx#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Lhs.0
6673799   ~0%    {6} r2 = JOIN r1 WITH DataFlowImplForContentDataFlow::Subpaths::subpaths03#d678ef22#ffffff ON FIRST 2 OUTPUT Rhs.3, Rhs.4, Rhs.5, Lhs.2, Lhs.0, Rhs.2
1686847799   ~6%    {5} r3 = JOIN r2 WITH DataFlowImplForContentDataFlow::PathNodeMid#class#d678ef22#fffffff_1250#join_rhs ON FIRST 3 OUTPUT Lhs.4, Rhs.3, Lhs.3, Lhs.5, Rhs.3
1686847799   ~2%    {4} r4 = JOIN r2 WITH …
```
=> Data flow: Speedup `subpaths` predicate (take 2)

.github/workflows/query-list.yml
We recently got a [Dependabot update](https://github.com/github/codeql/pull/9077) for this Action, but it probably makes more sense to remove it and standardise on `.github/actions/fetch-codeql`.
=> Actions: Fetch CodeQL CLI using `gh` rather than third-party Action

swift/codegen/cppgen.py, swift/codegen/dbschemegen.py, swift/codegen/lib/cpp.py, swift/codegen/lib/ql.py, swift/codegen/lib/schema.py, swift/codegen/qlgen.py, swift/codegen/schema.yml, swift/codegen/templates/cpp_classes.mustache, swift/codegen/templates/ql_class.mustache, swift/codegen/test/test_cpp.py, swift/codegen/test/test_cppgen.py, swift/codegen/test/test_dbschemegen.py, swift/codegen/test/test_ql.py, swift/codegen/test/test_qlgen.py, swift/codegen/test/test_schema.py, swift/ql/lib/codeql/swift/generated/type/AnyFunctionType.qll, swift/ql/lib/swift.dbscheme
Properties marked with `predicate` in the schema are now accepted.
* in the dbscheme, they will translate to a table with a single `id`
column (and the table name will not be pluralized)
* in C++ classes, they will translate to `bool` fields
* in QL classes, they will translate to predicates
Closes https://github.com/github/codeql-c-team/issues/1016
=> Swift codegen: add predicate properties

csharp/tools/tracing-config.lua
Right now, this is an unmodified port, without the additional functionality for `dotnet build` that we envision.
This means that we can switch back and forth between Lua and legacy tracing (ideally) without user-impacting differences.
=> C#: Port the existing compiler-tracing.spec files to Lua.

javascript/ql/lib/change-notes/2022-05-09-cash.md, javascript/ql/lib/semmle/javascript/frameworks/jQuery.qll, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/XssThroughDom.expected, javascript/ql/test/query-tests/Security/CWE-079/XssThroughDom/xss-through-dom.js
[cash](https://github.com/fabiospampinato/cash) is yet another smaller version of jQuery.  
CVE-2022-25349: TP/TN
CVE-2019-11003: TP/TN
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-9085-e80ee46__nightly-old__code-scanning/reports).
=> JS: add model for the cash library

cpp/ql/src/Security/CWE/CWE-611/XXE.ql, cpp/ql/test/query-tests/Security/CWE/CWE-611/XXE.expected, cpp/ql/test/query-tests/Security/CWE/CWE-611/tests.h, cpp/ql/test/query-tests/Security/CWE/CWE-611/tests3.cpp
Support for `SAX2XMLReader` in the CWE-611 XXE query.
Change note covered by the one in recent PR https://github.com/github/codeql/pull/8948.
=> C++: Add support for SAX2XMLReader in the CWE-611 XXE query.

csharp/tools/tracing-config.lua
Switch to using the regular API function for building an invocation instead of hand-rolling the code.
=> C#: Lua tracing config: Use API function.

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected
The old code was equivalent with the code below, which seems wrong
```
not n instanceof ExprNode
or
n instanceof ExprNode and
localFlowStepTypeTracker+(..., n)
```
From running on real DB I found that this meant that the following node
types were also included as local source nodes:
- `TReturningNode`
- `TSynthReturnNode`
- `TSummaryNode`
- `TSsaDefinitionNode`
It turned out that `TSynthReturnNode` was required for sure (but I don't fully undestand why), while the others don't immediately seems to be. 
@hvitved I've requested a review from you, since you seem to have been touching this code last. If you think it looks good, once we have filled out proper documentation for the TODO I left in the code, we can take it out of draft :+1:
=> Ruby: Fix `isLocalSourceNode` implementation

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/lib/semmle/code/csharp/frameworks/system/Collections.qll, csharp/ql/test/library-tests/dataflow/external-models/steps.expected, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowPrivate.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowUtil.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
This PR introduces
```ql
SummaryComponent withoutContent(ContentSet c);
SummaryComponent withContent(ContentSet c);
```
to `FlowSummaryImpl.qll` for C#, Java, and Ruby.
The new `SummaryComponent`s are only meant to be used in input specifications, and they gives rise to new synthesized nodes `n` at which `clearsContent(n, c)` resp. `expectsContent(n, c)` holds. This means that we can interpret `SummarizedCallable::clearsContent(ParameterPosition ppos, ContentSet cs)` as a summary with input stack
```
SummaryComponentStack::push(SummaryComponent::withoutContent(cs), SummaryComponentStack::argument(ppos))
```
and output stack
```
SummaryComponentStack::argument(ppos)
```
Ultimately, we should get rid of `SummarizedCallable::clearsContent(ParameterPosition ppos, ContentSet cs)` and use …
=> Data flow: Introduce 'with/without content' summary components

csharp/ql/src/Telemetry/ExternalLibraryUsage.ql, csharp/ql/src/Telemetry/SupportedExternalSinks.ql, csharp/ql/src/Telemetry/SupportedExternalSources.ql, csharp/ql/src/Telemetry/SupportedExternalTaint.ql, csharp/ql/src/Telemetry/UnsupportedExternalAPIs.ql
This will exclude the results of these queries from the summary tables produced by `codeql database analyze` in a future version of the CodeQL CLI.
=> C#: Tag telemetry queries with `telemetry`

java/ql/src/experimental/Security/CWE/CWE-321/HardcodedJwtKey.java, java/ql/src/experimental/Security/CWE/CWE-321/HardcodedJwtKey.qhelp, java/ql/src/experimental/Security/CWE/CWE-321/HardcodedJwtKey.ql, java/ql/src/experimental/Security/CWE/CWE-321/HardcodedJwtKey.qll, java/ql/test/experimental/query-tests/security/CWE-321/HardcodedJwtKey.expected, java/ql/test/experimental/query-tests/security/CWE-321/HardcodedJwtKey.java, java/ql/test/experimental/query-tests/security/CWE-321/HardcodedJwtKey.qlref, java/ql/test/experimental/query-tests/security/CWE-321/options, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/JWT.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/JWTCreator.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/algorithms/Algorithm.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/exceptions/JWTCreationException.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/exceptions/JWTDecodeException.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/exceptions/JWTVerificationException.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/exceptions/SignatureGenerationException.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/exceptions/SignatureVerificationException.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/interfaces/DecodedJWT.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/interfaces/ECDSAKeyProvider.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/interfaces/JWTVerifier.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/interfaces/KeyProvider.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/interfaces/RSAKeyProvider.java, java/ql/test/stubs/auth0-jwt-2.3/com/auth0/jwt/interfaces/Verification.java
JWT (JSON Web Token) is an open standard (RFC 7519) that defines a way to provide information within a JSON object between two parties. JWT is widely used for sharing security information between two parties in web applications. Each JWT contains encoded JSON objects, including a set of claims. JWTs are signed using a cryptographic algorithm to ensure that the claims cannot be altered after the token is issued.
The most basic mistake is using hardcoded secrets for JWT generation/verification. This allows an attacker to forge the token if the source code (and JWT secret in it) is publicly exposed or leaked, which leads to authentication bypass or privilege escalation.
[Auth0 implementation of JWT](https://auth0.com/docs/secure/tokens/json-web-tokens) is the de facto library used in Java …
=> Java: CWE-321 Query to detect hardcoded JWT secret keys

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForOnActivityResult.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl2.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplForLibraries.qll
Two fixes:
The first commit fixes a bad join-order in `nodeMayUseSummary`:
Before:
```
Evaluated non-recursive predicate DataFlowImpl::nodeMayUseSummary#17aa0c36#fffb@cb08d6d9 in 25262ms (evaluation was halted due to CancellationException).
Tuple counts for DataFlowImpl::nodeMayUseSummary#17aa0c36#fffb@cb08d6d9:
318500    ~0%    {4} r1 = SCAN project#DataFlowImpl::Stage4::revFlow#17aa0c36#2#ffffff#2 OUTPUT In.3, In.0, In.1, In.2
318000    ~0%    {5} r2 = JOIN r1 WITH m#DataFlowImpl::countNodesUsingAccessPath#17aa0c36#fbf ON FIRST 1 OUTPUT Lhs.1, Rhs.0, Lhs.1, Lhs.2, Lhs.3
317500    ~4%    {5} r3 = JOIN r2 WITH DataFlowImpl::NodeEx::getEnclosingCallable0#f0820431#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.3, Lhs.4
250080500    ~2%    {5} r4 = JOIN r3 WITH …
```
=> Dataflow: Performance fixes

cpp/ql/lib/change-notes/2022-05-11-deprecated-analysed-string.md, cpp/ql/lib/semmle/code/cpp/commons/Printf.qll, cpp/ql/lib/semmle/code/cpp/commons/StringAnalysis.qll, cpp/ql/lib/semmle/code/cpp/security/BufferWrite.qll, cpp/ql/test/library-tests/string_analysis/StringAnalysis.ql, java/ql/lib/semmle/code/java/dataflow/StringPrefixes.qll, javascript/ql/lib/semmle/javascript/frameworks/NoSQL.qll, python/ql/lib/semmle/python/objects/ObjectInternal.qll, python/ql/lib/semmle/python/objects/Sequences.qll, ql/ql/src/codeql_ql/style/docs/NonUSSpellingQuery.qll
The query was missing multi-line comments containing 'analyse', because `.` does not match newline characters in `regexpMatch`.
=> Fix non-US spellings and the corresponding query

python/ql/lib/change-notes/2022-05-12-moduleimport-disallow-dots.md, python/ql/lib/semmle/python/ApiGraphs.qll, python/ql/src/experimental/Security/CWE-285/PamAuthorization.ql, python/ql/src/experimental/semmle/python/frameworks/NoSQL.qll, python/ql/test/experimental/dataflow/typetracking/tracked.ql, python/ql/test/library-tests/ApiGraphs/py3/ModuleImportWithDots.expected, python/ql/test/library-tests/ApiGraphs/py3/ModuleImportWithDots.ql, python/ql/test/library-tests/ApiGraphs/py3/test.py, python/ql/test/library-tests/ApiGraphs/py3/verifyApiGraphs.ql
Inspired by discussion about this for MaD in https://github.com/github/codeql/pull/8883#discussion_r865858084
(and I actually thought this was already the case :grimacing:)
=> Python: Fully disallow `API::moduleImport` of module with dots

.devcontainer/devcontainer.json
These _should_ get installed automatically if missing, but in my
experience this can be a bit flaky. Installing them here should make
this a bit more robust.
=> Devcontainer: Install test dependencies

javascript/ql/lib/semmle/javascript/NodeModuleResolutionImpl.qll, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/sublib/package.json, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/sublib/sub.js, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/sublib/sub/empty.js
Recognizes the source for CVE-2022-21803 
See the test case to see what I mean.  
There is both a folder and a file that basename `sub`. 
And in that case we should resolve the main module to the file.   
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-9115-3d40207__nightly-old__code-scanning/reports).
=> JS: resolve main module when there is a folder with the same name as the main file

docs/codeql/support/reusables/versions-compilers.rst
As of https://github.com/github/codeql-go/pull/686 landing we support extracting generics, dataflow analysis in programs that use generics, etc. Note this hasn't  gone out in a release yet but I would expect it to be in 2.9.2.
=> Claim Go 1.18 support

java/kotlin-extractor/build.py, java/kotlin-extractor/kotlin_plugin_versions.py
Older python versions don't support it
=> Kotlin: Don't use capture_output or text

java/ql/lib/change-notes/2022-04-29-intent-redirection-sanitizer-fix.md, java/ql/lib/semmle/code/java/security/AndroidIntentRedirection.qll, java/ql/test/query-tests/security/CWE-940/AndroidIntentRedirectionTest.java
When validating intents to protect against intent redirection, both the package name and the class name must be checked. Otherwise, if only the package name is checked, the intent can be redirected to any of the app's activities (including non-exported ones), whereas if only the class name is checked, the intent can be redirect to an activity with the same name in another app. Both things are dangerous and should be flagged by the intent redirection query.
This PR adds more restrictions to the appropriate intent redirection sanitizer to take the above into account.
=> Java: Fix Intent Redirection sanitizer

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImpl4.qll, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplLocal.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl2.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl3.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl2.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl3.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl4.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl3.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl4.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl5.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl6.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForOnActivityResult.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplForSerializability.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl2.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl3.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl4.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImpl2.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplForLibraries.qll
Semantically this is a noop, but making `AccessPath` more obviously equal to `TAccessPath` means that the optimiser is able to eliminate a bunch of type checks that otherwise interferes badly with the join order in the standard order in `pathStep` (they cause the usual prev-before-delta mess).
=> Dataflow: Improve standard order through easier type check elimination.

cpp/ql/src/Security/CWE/CWE-611/XXE.ql, cpp/ql/src/change-notes/2022-05-12-external-entity-expansion.md
Fixes some typos and increases the XXE query precision to `@high`.
The latter is justified by results on 207 LGTM projects: https://lgtm.com/query/5698038244523748150/
- the first two projects with results use `libxml2` and fail to follow the advice in https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html
- the third and fourth use the Xerces `SAX2XMLReader` (`XMLReaderFactory::createXMLReader`) interface and fails to set `fgXercesDisableDefaultEntityResolution`.
- the fifth has examples of both Xerces `SAX2XMLReader` and `createLSParser`.  In all cases results are failing to set `fgXercesDisableDefaultEntityResolution`, though note that for `createLSParser` the need to do this is inferred rather than directly stated by the OWASP doc.
There's also …
=> C++: Fixes some typos and increases the XXE query precision.

javascript/ql/lib/semmle/javascript/security/dataflow/InsecureTemporaryFileCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/InsecureTemporaryFileQuery.qll, javascript/ql/src/Security/CWE-377/InsecureTemporaryFile.qhelp, javascript/ql/src/Security/CWE-377/InsecureTemporaryFile.ql, javascript/ql/src/Security/CWE-377/examples/insecure-temporary-file.js, javascript/ql/src/Security/CWE-377/examples/secure-temporary-file.js, javascript/ql/src/change-notes/2022-01-18-insecure-temporary-file.md, javascript/ql/test/query-tests/Security/CWE-377/InsecureTemporaryFile.expected, javascript/ql/test/query-tests/Security/CWE-377/InsecureTemporaryFile.qlref, javascript/ql/test/query-tests/Security/CWE-377/insecure-temporary-file.js
To safely create a temporary file in the OS temp dir in a multi-user environment you must: 
- Ensure that the file is created with `0o600` permissions or similar. 
- Ensure that you're not reusing an existing file (Use [the `O_EXCL` and `O_CREAT` flags](https://nodejs.org/api/fs.html#fs_fs_constants))   
(An exploit requires extremely precise timing by inserting a file between an `fs.exists(..)` and a `fs.open(..)` call.) 
This query checks for the first of these requirements.   
The only way to ensure the second requirement is to use `fs.open(.., O_EXCL | O_CREAT)`, which is what e.g. [`tmp`](https://www.npmjs.com/package/tmp) does.  
Checking for the second requirement gets complicated. One of the complications is that NodeJS programs very rarely use file handles, and instead just calls …
=> JS: add query for detecting insecure temporary files

java/ql/lib/change-notes/2022-05-16-floating-point-literal-rename.md, java/ql/lib/semmle/code/java/Expr.qll, java/ql/lib/semmle/code/java/dataflow/internal/rangeanalysis/SignAnalysisSpecific.qll, java/ql/src/Likely Bugs/Comparison/NoComparisonOnFloats.ql, java/ql/src/Violations of Best Practice/Magic Constants/MagicConstants.qll, java/ql/test/kotlin/library-tests/literals/literals.expected, java/ql/test/library-tests/fields/PrintAst.expected, java/ql/test/library-tests/literals/floatLiterals/floatLiterals.ql, java/ql/test/library-tests/literals/literals-numeric/negativeNumericLiterals.ql
=> Java: Rename `FloatingPointLiteral` to `FloatLiteral`

ruby/Cargo.lock, ruby/extractor/Cargo.toml, ruby/generator/Cargo.toml
This PR should fix parse errors in statements like
```
exit! if condition
```
See also: https://github.com/tree-sitter/tree-sitter-ruby/pull/216
=> Ruby: update tree-sitter-ruby

java/ql/lib/semmle/code/java/Javadoc.qll, java/ql/test/TestUtilities/InlineExpectationsTestPrivate.qll
Gives `InlineExpectationsTest` the ability to recognize Kotlin comments, allowing its use in `.kt` tests.
=> Kotlin: Add support for InlineExpectationsTest

python/ql/src/Security/CWE-022/TarSlip.ql, python/ql/src/analysis/Consistency.ql, ql/ql/src/queries/performance/ClassPredicateDoesntMentionThis.ql, ql/ql/src/queries/style/CountingToZero.ql
You should use `not exists(..)` instead of `count(...) = 0`. 
With `count(..) = 0` the evaluator will first check how many elements exists in a set, and afterwards check if that count equals 0.   
Using `not exists(..)` instead allows the optimizer to skip the counting.   
(I checked the RA, the optimizer does not optimize `count(..)  = 0` to `not exists(..)`). 
I originally made because I had the idea to replace `count(x)= 1` with `exists(unique(| | x))`, but I didn't like the results I got from that, so I've disabled that part of the query for now.  
(The `count(x) = 1` query got 200+ results). 
---- 
[Evaluation was ueventful](https://github.com/github/codeql-dca-main/tree/data/PR-9082-2-python__1/reports).
=> QL: add query warning about `count(...) = 0`. 

ql/ql/src/queries/style/GetAPrimaryQlClassConsistency.ql
This should hopefully mean fewer false positives for `ql/primary-ql-class-consistency` in Swift.
=> QL: Allow class + `Base` in `ql/primary-ql-class-consistency`

java/ql/lib/semmle/code/java/security/IntentUriPermissionManipulation.qll, java/ql/src/experimental/semmle/code/java/PathSanitizer.qll, javascript/ql/lib/semmle/javascript/frameworks/ClientRequests.qll, javascript/ql/lib/semmle/javascript/frameworks/CryptoLibraries.qll, python/ql/src/experimental/semmle/python/frameworks/Flask.qll, python/ql/test/experimental/query-tests/Security/CWE-113/HeaderInjection.expected, ql/ql/src/queries/performance/UnusedField.ql
Inspired by a recent code-review. 
Detects when a field is not bound by the charpred.  
Also handles the cases where the field is defined in an abstract super-class. 
I fixed all five errors detected by the query. They were pretty benign except for the Python warning in `Flask.qll`.  
(I think the error in `Flask.qll` was from not copy-pasting a line from the above class, so I did that).
=> QL: add unused-field query

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll
Avoids recomputation of some flow-summary related predicates.
=> Ruby: Force cached taint tracking predicates to be evaluated in data flow stage

java/ql/lib/semmle/code/java/JDK.qll, java/ql/lib/semmle/code/java/Type.qll
For consistency moves `NumericType` from `JDK.qll` to `Type.qll`, where all other related type classes are.
I have not added a change note because I assume this change is not externally visible. Though please let me know if a change note is needed.
This change conflicts with #9182; feel free to merge that one first and I will resolve the conflict here afterwards.
=> Java: Move `NumericType` to `Type.qll`

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/ql/consistency-queries/typeParametersInScope.ql, java/ql/test/kotlin/library-tests/dataflow/func/util.kt, java/ql/test/kotlin/library-tests/exprs/PrintAst.expected, java/ql/test/kotlin/library-tests/exprs/exprs.expected, java/ql/test/kotlin/library-tests/function-n/test.expected, java/ql/test/kotlin/library-tests/function-n/test.kt, java/ql/test/kotlin/library-tests/function-n/test.ql, java/ql/test/library-tests/frameworks/guava/generated/collect/CONSISTENCY/typeParametersInScope.expected
* Substitute type parameters when creating a SAM class instance that satisfies a generic instance
* In the process, fix source-locations of SAM class instances to indicate the instantiation site, not the interface being satisfied
* Fix generic arg extraction when Function23+ get rewritten to FunctionN in the JVM lowering
* Fix the type-parameter-out-of-scope test to detect these situations in future
~This is temporarily based on https://github.com/github/codeql/pull/9122 -- the real diff is https://github.com/smowton/codeql/compare/smowton/admin/update-kotlin...smowton:smowton/fix/type-variable-in-scope-consistency~
=> Kotlin: fix cases where type variables were used out of scope

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
This PR fixes the extraction of the `java` property call in `C::class.java` generated by the Parcelize plugin. Generally, these calls are properly associated to `kotlin.jvm.JvmClassMappingKt::java`, and therefore need no special handling. However, with the Parcelize plugin this is not the case.
I'm planning on merging this fix without integration test. It feels way more effort to add the test than the benefit.
=> Kotlin: Fix extraction of reflective call generated by Parcelize

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/TaintTrackingPrivate.qll, csharp/ql/test/library-tests/dataflow/external-models/steps.ql, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowUtil.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/TaintTrackingUtil.qll, java/ql/test/library-tests/dataflow/external-models/steps.ql, java/ql/test/library-tests/dataflow/local-additional-taint/localAdditionalTaintStep.ql, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/TaintTrackingPrivate.qll
The local flow relation was accidentally made mutually recursive with `AdditionalValueStep`. It makes sense to allow the use for local flow to define `AdditionalValueStep::step`, so removing the latter from the former allows this without recursion.
A non-monotonic dummy reference is added to prevent re-introduction of recursion here, and this highlighted the need for a minor refactor in `FlowSummaryImpl` (since `ReturnNodeExt` depends on local flow).
The local flow relation is also fixed to force the use of the fastTC hop, as this otherwise was observed to result in a very slow materialisation.
=> Java: Performance fixes for local flow relation

java/ql/test/kotlin/library-tests/field-initializer-flow/test.expected, java/ql/test/kotlin/library-tests/field-initializer-flow/test.ql
Fixes a field initialization flow test that was deceitfully showing flow from a field access to  another field access, rather than from the field initialization as was intended.
This now correctly highlights the lack of flow, which will be fixed in a different PR once we decide on the appropriate solution.
=> Kotlin: Fix test to correctly highlight lack of flow from field init

java/kotlin-extractor/src/main/kotlin/ExternalDeclExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
Make extraction messages `warning` if code is still extracted regardless of the reported issue. Make extraction messages `error` if some code is not extracted.
=> Kotlin: Adjust diagnostic message severity

.github/workflows/ql-for-ql-dataset_measure.yml
I just pointed the workflow to the `merge_stats.py` file in the `ruby/` folder. 
This PR is a followup based on [this comment](https://github.com/github/codeql/pull/8871#issuecomment-1110126719).
=> QL: point the dataset measure workflow to a merge_stats.py file that exists

cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplCommon.qll, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplCommon.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplCommon.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplCommon.qll, ruby/ql/test/library-tests/dataflow/call-sensitivity/call-sensitivity.expected, ruby/ql/test/library-tests/dataflow/call-sensitivity/call_sensitivity.rb
Since we are computing flow backwards, and we are recording the *first* call seen during reverse flow, it is valid to keep the call context even when we go through a jump step.
=> Data flow: Do not discard call context when computing reverse lambda flow through jumps

swift/extractor/SwiftDispatcher.h
There was a call with side effects in an `assert`, that was therefore
not being called with `NDEBUG` turned on, changing extractor results.
=> Swift: fix extractor built with `NDEBUG`

.codeqlmanifest.json, swift/.codeqlmanifest.json, swift/README.md
The extractor pack entry in there has been moved to the root manifest.
=> Swift: remove `.codeqlmanifest`

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll
Gets rid of
```
Tuple counts for DataFlowPrivate::Cached::isLocalSourceNode#462ff392#f#antijoin_rhs@dd2f927s:
20905019     ~3%    {2} r1 = JOIN DataFlowPrivate::Cached::TExprNode#462ff392#ff_1#higher_order_body WITH boundedFastTC(DataFlowPrivate::Cached::localFlowStepTypeTracker#462ff392#ff_10#higher_order_body,DataFlowPrivate::Cached::TExprNode#462ff392#ff_1#higher_order_body) ON FIRST 1 OUTPUT Rhs.1, Lhs.0
10420128  ~1496%    {1} r2 = JOIN r1 WITH DataFlowPrivate::Cached::TExprNode#462ff392#ff_1#higher_order_body ON FIRST 1 OUTPUT Lhs.1
480918     ~8%    {1} r3 = JOIN r1 WITH DataFlowPrivate::Cached::entrySsaDefinition#462ff392#f ON FIRST 1 OUTPUT Lhs.1
10901046  ~1218%    {1} r4 = r2 UNION r3
return r4
```
Pulled out of https://github.com/github/codeql/pull/9175.
=> Ruby: Eliminate bad `isLocalSourceNode` antijoin

javascript/ql/lib/semmle/javascript/ApiGraphs.qll, javascript/ql/test/ApiGraphs/accessors/VerifyAssertions.ql, javascript/ql/test/ApiGraphs/accessors/index.js
Generates API graph edges in two cases:
- When an object escapes, generates `getMember` edges to the return-value of getters.
- When an instance of a class escapes, generates `getMember` edges to the instance members of the class (including getters, as above).
- Previously, such edges were generated only when the class itself escapes, not when an _instance_ of the class escapes.
Makes the example in https://github.com/github/codeql/pull/8606 actually work in JS.
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/api-graph-acces__default__code-scanning__9/reports) looks reasonable.
=> JS: API graph support for accessors (and classes members)

javascript/ql/src/Security/CWE-384/SessionFixation.ql, javascript/ql/test/query-tests/Security/CWE-384/SessionFixation.expected, javascript/ql/test/query-tests/Security/CWE-384/tst.js
Passport added protection against session-fixation, so we should no longer detect it using our query.  
See this announcement: https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d, and this helpful comment from the maintainer: https://github.com/github/codeql/pull/7029#issuecomment-1132940870
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-9261-1a8cf23__nightly-old__CustomSuite/reports).  
We loose some results, but that was the point.
=> JS: remove support for passport in the session-fixation query

.github/workflows/query-list.yml, README.md, docs/codeql/codeql-cli/about-ql-packs.rst, docs/codeql/codeql-cli/getting-started-with-the-codeql-cli.rst, docs/codeql/codeql-for-visual-studio-code/exploring-the-structure-of-your-source-code.rst, docs/codeql/codeql-for-visual-studio-code/setting-up-codeql-in-visual-studio-code.rst, docs/codeql/codeql-language-guides/modeling-data-flow-in-go-libraries.rst, docs/codeql/query-help/go.rst, docs/codeql/reusables/go-further-reading.rst, docs/codeql/writing-codeql-queries/about-codeql-queries.rst, docs/codeql/writing-codeql-queries/creating-path-queries.rst, go/CONTRIBUTING.md, go/README.md, go/docs/language/learn-ql/go/library-modeling-go.rst
This PR is based on https://github.com/github/codeql/pull/8631, which should be merged first.
---
`github/codeql-go` is being merged into `github/codeql` (this is done by the base PR).
Update references to `codeql-go` within the CodeQL CLI docs.
Add Go to the list of mentioned languages where applicable.
Leave an explanatory note in the setup instructions about the previous requirement to check out `github/codeql-go`, and mention this is no longer necessary.
The remaining references are to historical commits, which will continue to exist.
=> Docs: Update references to github/codeql-go

config/identical-files.json, cpp/ql/lib/semmle/code/cpp/dataflow/internal/DataFlowImplCommon.qll, cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/ContentDataFlow.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplCommon.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowImplForContentDataFlow.qll, csharp/ql/test/library-tests/dataflow/content/ContentFlow.cs, csharp/ql/test/library-tests/dataflow/content/ContentFlow.expected, csharp/ql/test/library-tests/dataflow/content/ContentFlow.ql, java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImplCommon.qll, python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImplCommon.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowImplCommon.qll
This PR introduces a new (internal) data-flow library that, unlike the normal data-flow library, allows for flow from parts of a source to parts of a sink. Example:
```csharp
class C
{
C FieldA;
C FieldB;
void M1()
{
var source = new C();
Sink(source); // direct flow from source to sink
}
void M2()
{
var source = new C();
Sink(source.FieldA); // flow from `FieldA` on source to sink
}
void M3()
{
var source = new C();
var c = new C() { FieldB = source }
Sink(c);  // flow from source to `FieldB` on sink
}
void M4()
{
var source = new C();
var c = new C() { FieldB = source.FieldA }
Sink(c); // flow from `FieldA` on source to `FieldB` on sink
}
}
```
The normal data-flow library will only identify flow in the `M1` case, where as this new library will be able to identify flow in the cases …
=> Data flow: Introduce `ContentDataFlow.qll`

ruby/ql/lib/codeql/ruby/controlflow/ControlFlowGraph.qll, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImpl.qll, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplSpecific.qll
For consistency with our other uses of the range pattern.
=> Ruby: rename CfgScope::Range_ to CfgScopeImpl

config/identical-files.json, swift/ql/lib/codeql/swift/dataflow/DataFlow.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImpl.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplCommon.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplConsistency.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowImplSpecific.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPublic.qll, swift/ql/lib/codeql/swift/dataflow/internal/SsaImplCommon.qll, swift/ql/lib/codeql/swift/dataflow/internal/SsaImplSpecific.qll, swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPrivate.qll, swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPublic.qll, swift/ql/lib/codeql/swift/dataflow/internal/tainttracking1/TaintTrackingImpl.qll, swift/ql/lib/codeql/swift/dataflow/internal/tainttracking1/TaintTrackingParameter.qll
The first two commits are 100% bitwise copies from the internal repo. We can't yet add any tests since we don't extract Swift comments yet, and therefore cannot yet use the inline expectations test framework.
=> Swift: Add shared dataflow library

javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountAlertsAndSinks.qll, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountCodeInjection.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountNosqlInjection.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountSqlInjection.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountTaintedPath.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountXss.ql, javascript/ql/experimental/adaptivethreatmodeling/modelbuilding/counting/CountXssThroughDom.ql
The ATM project uses an AML pipeline to select which CodeQL databases to use as the evaluation databases for each security query being boosted. 
Previously, evaluation sets for _all_ security queries would be produced at once, using the `CountAlertsAndEndpoints.ql` query. However, this query does not scale with adding more security queries, and it is not efficient to create evaluation sets for all queries during every pipeline run (when adding a new query, you simply want to create an evaluation set for that one query, and not the others).
Therefore, after a discussion, it was deemed better to specify one security query that you would like to create an evaluation set for. For this, we would need a way to count alerts and endpoints for a single query. The most simple solution is to add …
=> JS: Add individual per-security-query counting queries

csharp/ql/lib/semmle/code/csharp/dataflow/internal/FlowSummaryImpl.qll, java/ql/lib/semmle/code/java/dataflow/internal/FlowSummaryImpl.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImpl.qll
Before
```
Tuple counts for FlowSummaryImpl::Private::Steps::prohibitsUseUseFlow#1de78b88#ff@fdf8bdrq:
6099   ~0%    {2} r1 = SCAN FlowSummaryImpl::Private::isParameterPostUpdate#1de78b88#fff OUTPUT In.2, In.0
787252695   ~2%    {3} r2 = JOIN r1 WITH project#DataFlowImplCommon::ParamNode::isParameterOf#dispred#f0820431#fff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, true, Lhs.1
5360462712   ~0%    {4} r3 = JOIN r2 WITH FlowSummaryImpl::Private::Steps::summaryLocalStep#1de78b88#ffb_021#join_rhs ON FIRST 2 OUTPUT Rhs.2, Lhs.2, true, Lhs.0
7132   ~2%    {2} r4 = JOIN r3 WITH FlowSummaryImpl::Private::Steps::summaryLocalStep#1de78b88#ffb ON FIRST 3 OUTPUT Lhs.0, Lhs.3
5869  ~25%    {1} r5 = JOIN r4 WITH DataFlowImplCommon::Cached::clearsContentCached#4f8df883#ff ON FIRST 1 OUTPUT Lhs.1
1263   ~9% …
```
=> Data flow: Fix bad join in `prohibitsUseUseFlow`

ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll, ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll, ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected, ruby/ql/test/library-tests/dataflow/hash-flow/hash_flow.rb
Support for
```rb
hash1 = { :foo => taint }
hash = { :bar => no_taint, **hash1 }
sink(hash[:foo]} # bad
sink(hash[:bar]} # good
```
=> Ruby: Data flow for hash-splat expressions in hash literals

.github/workflows/js-ml-tests.yml
This is so we can trigger scheduled runs of these tests
=> ATM: add `workflow_dispatch` to ATM JS tests

java/kotlin-extractor/src/main/java/com/semmle/extractor/java/OdasaOutput.java
Previously Kotlin's use of IntelliJ's VirtualFile interface meant we got the containing JAR file's mtime, not that of the individual file entry.
=> Kotlin: use the same mtimes as Java

ruby/ql/lib/codeql/ruby/ast/Call.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/lib/codeql/ruby/dataflow/internal/FlowSummaryImplSpecific.qll, ruby/ql/test/library-tests/dataflow/global/Flow.expected, ruby/ql/test/library-tests/dataflow/global/instance_variables.rb, ruby/ql/test/library-tests/dataflow/summaries/Summaries.expected, ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql, ruby/ql/test/library-tests/dataflow/summaries/summaries.rb
This pull request adds support for data flow through getter/setter methods. It assumes that setter methods like `field=` write to an instance variable named `@field`. This is to handle cases where the body of the setter method is not visible to the analysis. While this is an approximation, I'd expect very few cases of false flow. If my assumption turns out to be wrong we should make the analysis more precise.
=> Ruby: flow through getters/setters

cpp/ql/src/experimental/Security/CWE/CWE-020/NoCheckBeforeUnsafePutUser.ql, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-020/NoCheckBeforeUnsafePutUser/NoCheckBeforeUnsafePutUser.expected, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-020/NoCheckBeforeUnsafePutUser/test.cpp
Improve `cpp/linux-kernel-no-check-before-unsafe-put-user` in `experimental`.  Inspired by https://github.com/github/codeql/pull/8739 (which was closed) and the tests I developed for that in https://github.com/github/codeql/pull/8800 .    Further improvements (in particular to the way dataflow is used) are definitely possible, but the goal of this PR is just to get specific knowledge out of my head and into the query.
In the first commit I define the sources properly, rather than coming from any parameter.  In the second commit I adjust the query and test to be closer to reality.
=> C++: Improve cpp/linux-kernel-no-check-before-unsafe-put-user

ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/test/library-tests/frameworks/ActiveRecord.expected, ruby/ql/test/library-tests/frameworks/ActiveRecord.ql
The first commit here fixes some cases where we misidentified `self` in a `SingletonMethod` belonging to an active record model class as referring to an instance of that class, rather than referring to the class itself. This bug had also masked cases where we were missing instances of `ActiveRecordModelClass`es, for example, in:
```
class User < ApplicationRecord
def self.get_some_user
find(:first)
end
end
```
We have a call to `find` with an implicit `self` receiver that refers to the `User` class - this was not something that was accounted for in `ActiveRecordModelFinderCall` before, but now is.
The second commit makes `ActiveRecordInstance` publicly available, as it's been requested as a potentially useful class for use in queries.
=> Ruby: Make `ActiveRecordInstance` public and fix some misidentifications

swift/codegen/schema.yml, swift/extractor/visitors/TypeVisitor.h, swift/ql/lib/codeql/swift/generated/type/AnyFunctionType.qll, swift/ql/lib/swift.dbscheme, swift/ql/test/extractor-tests/types/ThrowingAndAsync.expected, swift/ql/test/extractor-tests/types/ThrowingAndAsync.ql, swift/ql/test/extractor-tests/types/Types.expected, swift/ql/test/extractor-tests/types/types.swift
This fills in the `any_function_type_is_throwing` table which is needed to improve CFG precision (I'll open another PR with those changes after this is merged).
I also added an `any_function_type_is_async` table since that was basically a copy-paste of the code required for the `throwing` version. I'm sure we'll need this at some point.
=> Swift: Extract `isThrowing` and `isAsync`

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
Specifically `const`, `lateinit` and `@JvmField` properties get a static field which belongs to the containing class not the companion object, such that Java can address them via the containing class name rather than have to navigate a companion object pointer.
=> Associate certain companion object fields with the parent class

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/ql/test/kotlin/library-tests/clashing-extension-fields/test.expected, java/ql/test/kotlin/library-tests/clashing-extension-fields/test.kt, java/ql/test/kotlin/library-tests/clashing-extension-fields/test.ql, java/ql/test/kotlin/library-tests/exprs/PrintAst.expected, java/ql/test/kotlin/library-tests/exprs/delegatedProperties.expected, java/ql/test/kotlin/library-tests/exprs/exprs.expected
Otherwise we name the `$delegate` fields of `val A.x : String by lazy { "A" }` and `val B.x : String ...` alike, both in name and trap label.
=> Kotlin: Disambiguate the names and trap labels of backing fields of extension properties

javascript/ql/src/Performance/PolynomialReDoS.qhelp
The example got rendered wrong on LGTM for some reason: https://lgtm.com/rules/1511427506129/  
With this change the code is syntactically correct JS, which should hopefully get it to render correctly.
=> JS: use syntactically correct JS in poly-redos example

docs/codeql/support/reusables/versions-compilers.rst, javascript/ql/lib/change-notes/2022-05-24-ecmascript-2022.md, javascript/ql/lib/semmle/javascript/Arrays.qll, javascript/ql/lib/semmle/javascript/MembershipCandidates.qll, javascript/ql/lib/semmle/javascript/StandardLibrary.qll, javascript/ql/lib/semmle/javascript/dataflow/TaintTracking.qll, javascript/ql/src/Declarations/UnusedProperty.ql, javascript/ql/src/Security/CWE-915/PrototypePollutingFunction.ql, javascript/ql/test/library-tests/Arrays/DataFlow.expected, javascript/ql/test/library-tests/Arrays/arrays.js, javascript/ql/test/library-tests/Arrays/printAst.expected, javascript/ql/test/library-tests/TaintBarriers/tests.expected, javascript/ql/test/library-tests/TaintBarriers/tst.js, javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/library-tests/TaintTracking/arrays.js, javascript/ql/test/query-tests/Declarations/UnusedProperty/tst.js, javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/ServerSideUrlRedirect.expected, javascript/ql/test/query-tests/Security/CWE-601/ServerSideUrlRedirect/express.js, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingFunction/PrototypePollutingFunction.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingFunction/tests.js
I took a look at all the finished 2022 proposals from this list: https://github.com/tc39/proposals/blob/main/finished-proposals.md  
We already had support for most of the features, so there wasn't that much more to add.  
I also looked at [RegExp Match Indices](https://github.com/tc39/proposal-regexp-match-indices), but I concluded that we have nothing to support there, because all the values in the new `indices` array are numbers representing various indexes, and those numbers are not tainted.  
[Evaluation was unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-9289-82c6c22__nightly-old__code-scanning/reports).
=> JS: Support the remaining of the finished ES2022 proposals

java/ql/src/utils/model-generator/CaptureSinkModels.ql, java/ql/src/utils/model-generator/CaptureSourceModels.ql, java/ql/src/utils/model-generator/CaptureSummaryModels.ql
The meta data for the capture models queries needs to be updated , such that they are
- Excluded from the many of standard selectors (model-generator tag).
- Kind is set to diagnostic which allows us to create a query suite that can be used with DCA.
=> Java: Update capture models meta data.

swift/codegen/schema.yml, swift/extractor/visitors/ExprVisitor.h, swift/ql/lib/codeql/swift/generated/expr/KeyPathApplicationExpr.qll, swift/ql/lib/swift.dbscheme, swift/ql/test/extractor-tests/expressions/all.expected, swift/ql/test/extractor-tests/expressions/expressions.swift, swift/ql/test/extractor-tests/expressions/semantics.expected
Pretty simple stuff. Note the ninja fix in 52f0b0d8d80e7e9b36faf2b0410c2397a83484b5. It fitted the overall goal of this PR (extractor changes required for CFG construction for KeyPath operations).
=> Swift: Extract KeyPath applications

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/ql/test/kotlin/library-tests/java-kotlin-collection-type-generic-methods/Test.java, java/ql/test/kotlin/library-tests/java-kotlin-collection-type-generic-methods/test.expected, java/ql/test/kotlin/library-tests/java-kotlin-collection-type-generic-methods/test.kt, java/ql/test/kotlin/library-tests/java-kotlin-collection-type-generic-methods/test.ql
Collection, List and Map all define various methods which are either made more generic in Kotlin (e.g. `remove(Object) -> remove(E)`, `containsAll(Collection<?>) -> containsAll(Collection<E>)`), or are made invariant (e.g. `addAll(Collection<? extends E>) -> addAll(Collection<E>)`). This substitutes the types back to their Java signatures,
thereby avoiding differing trap labels and duplicated methods for these types and their descendents.
=> Kotlin: extract methods defined on collections types with their Java signatures

javascript/ql/lib/semmle/javascript/NodeJS.qll, javascript/ql/lib/semmle/javascript/internal/CachedStages.qll
The `getABulkExportedNode`, `.getADecoratedClass()`, `.getADecoratedMember()`, and `.getADecoratedParameter()` all had their own stage.  
I know it doesn't matter much anymore, but I've thrown them into an existing stage where they fit naturally.
=> JS: collapse a few small stages

java/ql/lib/semmle/code/java/dataflow/NullGuards.qll
This was highlighted by the join-order badness metric.
Before:
```
Evaluated recursive predicate NullGuards::customNullGuard#df9d737e#ffbf@516f08wh in 1861ms on iteration 6 (delta size: 231).
Tuple counts for NullGuards::customNullGuard#df9d737e#ffbf@516f08wh on iteration 6 running pipeline order_500000:
363765  ~1388%    {4} r1 = SCAN NullGuards::validReturnInCustomNullGuard#df9d737e#bffb#reorder_1_2_3_0#prev_delta OUTPUT In.3, In.0, In.1, In.2
363765  ~1388%    {4} r2 = r1 AND NOT isVarargsParam(Lhs.1)
363765  ~1440%    {4} r3 = SCAN r2 OUTPUT In.1, In.0, In.2, In.3
363765  ~1462%    {6} r4 = JOIN r3 WITH params ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.0, Lhs.2, Lhs.3, Rhs.2
363765  ~1394%    {5} r5 = JOIN r4 WITH @reftype#f ON FIRST 1 OUTPUT Lhs.2, Lhs.1, Lhs.3, Lhs.4, Lhs.5
363765  ~1446% …
```
=> Java: Improve customNullGuard performance.

swift/README.md
Add installing Bazel as a step to the Swift readme.  The step following this won't work without it.
=> Swift: Added Bazel install step.

javascript/ql/lib/Expressions/ExprHasNoEffect.qll, javascript/ql/lib/semmle/javascript/AMD.qll, javascript/ql/lib/semmle/javascript/frameworks/XmlParsers.qll, javascript/ql/test/library-tests/AMD/tests.expected, javascript/ql/test/library-tests/AMD/umd2.js, javascript/ql/test/query-tests/Expressions/ExprHasNoEffect/ExprHasNoEffect.expected, javascript/ql/test/query-tests/Expressions/ExprHasNoEffect/tst.js
Specifically, we now detect this pattern:
```js
(function (global, factory) {
checkForNodeJS() ? module.exports = factory(...) :
checkForAmd() ? define(..., factory) :
global.mymodule = factory(...)
}(this, function (...) { ... });
```
We previously missed it because we expected the `define` to appear as an expression statement, but here it is nested a bit more deeply.
I fixed this by using the `inVoidContext` predicate we use in a few other queries, which however needed a bit of extra work. I'm curious to see whether that has any knock-on effects on performance or results, if it does I'm happy to switch to a more targeted fix.
=> JavaScript: Improve detection of UMD modules.

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/ql/test/kotlin/library-tests/android_function_return_types/returnTypes.expected, java/ql/test/kotlin/library-tests/android_function_return_types/returnTypes.ql, java/ql/test/kotlin/library-tests/android_function_return_types/test.kt
This PR changes the return type of `java.util.concurrent.ConcurrentHashMap.keySet()` from `Set` to `KeySetView`. The return type is `Set` in the android SDK for backwards compatibility, and the new variant is generated on the fly. The change to `KeySetView` is needed to not have DB inconsistencies.
=> Kotlin: Change return type of Android specific `ConcurrentHashMap.keySet`

swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll, swift/ql/test/library-tests/controlflow/graph/Cfg.expected
We could be a lot smarter about how we generate the CFG (and in the future: dataflow) for `yield` statements, but coroutines aren't actually supported at the user level yet (see https://forums.swift.org/t/modify-accessors/31872). It's still generated by the compiler, which is why I decided we shouldn't ignore it in the CFG.
=> Swift: CFG for `yield`

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/ql/test/kotlin/library-tests/exprs/PrintAst.expected, java/ql/test/kotlin/library-tests/exprs/exprs.expected, java/ql/test/kotlin/library-tests/function-n/test.expected, java/ql/test/kotlin/library-tests/java-kotlin-collection-type-generic-methods/test.expected, java/ql/test/kotlin/library-tests/multiple_extensions/calls.expected, java/ql/test/kotlin/library-tests/reflection/PrintAst.expected
For Kotlin code, introduce wildcards where the compiler would introduce them when lowering to bytecode (when a type parameter has declaration-site variance, by default only in parameter context, special-casing types that can't be extended / with no supertypes, and obeying the `@JvmWildcard` and `@JvmSuppressWildcards` annotations.
For Java code, use the original Java type to suppress wildcard introduction if the Java type didn't use a wildcard even though it would have been appropriate (for example, Java can ask for exactly `Comparable<String>` even though it would lose nothing to permit `Comparable<? super String>`)
=> Kotlin: Introduce / restore implied wildcard types

.github/workflows/query-list.yml
Since go doesn't need to be cloned with the same tag, that makes this change much easier to implement in practice :muscle:
=> Misc: query-list should run on `codeql-cli/*` tags

go/ql/src/qlpack.yml
Now that Go is in the same repo as the `codeql/suite-helpers` pack, we always pick up the repo version of that dependency. Thus, we should use an unrestricted version range, like we do for other intra-repo dependencies.
Targeting `rc/3.6` since this is affecting @rvermeulen and his attempts at package customization.
=> Fix `codeql/suite-helpers` dependency for Go

swift/rules.bzl, swift/tools/prebuilt/BUILD.bazel
This is a temporary workaround. At a later stage we will add
* a Swift/LLVM prebuilt package for arm64
* universal binary for the extractor
=> Swift: build x86_64 on arm64 macOS

swift/codegen/README.md, swift/codegen/codegen.py, swift/codegen/generators/cppgen.py, swift/codegen/generators/dbschemegen.py, swift/codegen/generators/trapgen.py, swift/codegen/lib/cpp.py, swift/codegen/lib/ql.py, swift/codegen/templates/cpp_classes.mustache, swift/codegen/templates/trap_tags.mustache, swift/codegen/templates/trap_traps.mustache, swift/codegen/test/test_cppgen.py, swift/codegen/test/test_trapgen.py, swift/extractor/trap/BUILD.bazel
This adds:
* a base `README.md` file to `codegen`
* module docstrings for the modules in `generators`
* help strings on all command line flags
Moreover some unneeded command line flags (`--namespace`,
`--include-dir` and `--trap-affix`) have been dropped.
=> Swift: document and partially simplify codegen

java/kotlin-extractor/src/main/kotlin/ExternalDeclExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/kotlin-extractor/src/main/kotlin/TrapWriter.kt, java/kotlin-extractor/src/main/kotlin/utils/TypeSubstitution.kt
Makes it easier when reading the code.
The substituteTypeArguments functions aren't actually overloads, but I think the same applies.
=> Kotlin: Put overloads together

ruby/ql/lib/codeql/ruby/security/OpenSSL.qll
I'm doing some on-the-side experiments into performance of the Ruby analysis.   
One of those experiments caused something to change (inlining?), which caused a bad Cartesian product to materialize.   
Here are the tuple counts:   
```
Tuple counts for OpenSSL::CipherOperation#class#74b60a3e#fff@e3d3fb6n:
96368664  ~10%    {2} r1 = JOIN DataFlowPrivate::Cached::TNode#462ff392#f WITH project#OpenSSL::CipherInstantiation#class#74b60a3e#fff#3 CARTESIAN PRODUCT OUTPUT Rhs.0, Lhs.0
96368664   ~3%    {3} r2 = JOIN r1 WITH project#OpenSSL::CipherNode#class#74b60a3e#fff ON FIRST 1 OUTPUT Lhs.0, Lhs.0, Lhs.1
8030722   ~0%    {2} r3 = SCAN DataFlowPrivate::Cached::TNode#462ff392#f OUTPUT 0, In.0
747315   ~0%    {2} r4 = JOIN r3 WITH DataFlowPublic::CallNode::getArgument#dispred#f0820431#fbf_120#join …
```
=> RB: fix bad CP in the charPred for CipherOperation

cpp/ql/lib/semmle/code/cpp/commons/Printf.qll
Improve performance of `cpp/cleartext-storage-buffer`, which regressed a month or so ago.  The difference isn't huge, though the fix is in library code so it could affect other queries as well.
Locally on `wireshark` (with cache warmed up by `cpp/system-data-exposure`) this change improves performance from 55s -> 45s.  It appears to have eliminated entirely the following pre-computation:
```
[2022-06-01 10:56:39] Evaluated non-recursive predicate Printf::callsVariadicFormatter#b0c2256f#bfff#join_rhs#1@3c8b9cg6 in 1308ms (size: 993161).
Tuple counts for Printf::callsVariadicFormatter#b0c2256f#bfff#join_rhs#1@3c8b9cg6:
650340  ~1%    {4} r1 = SCAN Function::Function::getParameter#dispred#f0820431#bff OUTPUT In.2, -1, In.0, In.1
1428098  ~6%    {4} r2 = JOIN r1 WITH …
```
=> C++: Improve performance of Printf::callsVariadicFormatter.

swift/ql/lib/codeql/swift/controlflow/BasicBlocks.qll, swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowElements.qll, swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll, swift/ql/lib/codeql/swift/controlflow/internal/Scope.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll, swift/ql/test/library-tests/controlflow/graph/Cfg.expected, swift/ql/test/library-tests/controlflow/graph/cfg.swift
This PR reverts https://github.com/github/codeql/pull/9419 (which is a revert of https://github.com/github/codeql/pull/9373).
The original PR surfaced some issues in the CFG for certain pattern matching operations, and due to missing locations (which was fixed in https://github.com/github/codeql/pull/9430) these CFG issues led to some strange and flaky test output. The actual CFG fixes landed in https://github.com/github/codeql/pull/9511 and this PR now only shows the intended effects in the graph output diff.
=> Swift: Reintroduce control-flow for key paths

cpp/ql/test/library-tests/controlflow/dereferenced/dereferenced.cpp, cpp/ql/test/library-tests/controlflow/dereferenced/dereferenced.expected, cpp/ql/test/library-tests/controlflow/dereferenced/dereferenced.ql
Add test for `Dereferenced.qll`.  I was investigating an issue this morning that turned out to be nothing (I think I was reading a result incorrectly).  But it seems good to have a permanent test for this.
=> C++: Add test for Dereferenced.qll.

ql/Cargo.lock, ql/extractor/Cargo.toml, ql/generator/Cargo.toml, ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/ql.dbscheme
See https://github.com/tausbn/tree-sitter-ql/compare/725395405e65814f10095a451404b0ced5dc6289...tausbn:various-fixes for the actual changes to the grammar (and tests thereof).
---
A brief summary of the various nodes is perhaps in order.
- `ModuleApplication` represents the "instantiation" of a parameterised module (e.g. `Foo<...>`. Such applications may have children, each of which will be a...
- ... `SignatureExpr`, which corresponds to a predicate `bar::foo/1` or a class `Cls`. Both the `::` prefix and the arity are optional (and if the latter is absent, it's a class).
- `ModuleParam`, which represents a parameter of a parameterised module declaration. Each of these consists of two parts, a `SignatureExpr` and an identifier (representing the "type" and "variable" respectively).
=> QL: Add parser support for parameterised modules

swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowElements.qll, swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll, swift/ql/lib/codeql/swift/controlflow/internal/Scope.qll, swift/ql/test/library-tests/controlflow/graph/Cfg.expected
This implements the necessary changes to address https://github.com/github/codeql/pull/9555/files/0b85bc66d178813f6b8413bdcb617da8c1836f20#r897092930.
=> Swift: Mark closures as callables in the CFG library

cpp/ql/test/library-tests/dataflow/dataflow-tests/dataflow-ir-consistency.expected, cpp/ql/test/library-tests/ir/ir/operand_locations.expected, cpp/ql/test/library-tests/lambdas/captures/elements.expected
This reverts commit 8e7066600a20f87baae93c6b8a7cd1600b7ec89b.
The frontend issue that made this change necessary was fixed.
=> Revert "C++: Fix test failures where location of reference dereference in lambda changed"

python/ql/src/Security/CWE-732/WeakFilePermissions.ql, python/ql/test/query-tests/Security/CWE-732-WeakFilePermissions/WeakFilePermissions.expected, python/ql/test/query-tests/Security/CWE-732-WeakFilePermissions/options
Using API graphs instead of points-to.
Unfortunately, some results will be lost because of this, due to the fact that points-to tracks bitwise operations on small numbers (i.e. flags), whereas API graphs does no such thing. This means using something like `stat.S_IWUSR | stat.S_IWGRP` will not work.
A custom type tracker (like the one used for `re` flags) could be used to recapture this behaviour, but I think that's best left as future work, as it's not clear to me that this query is actually worth the effort it would take to implement this.
---
As this is just modernising a somewhat minor query, I don't think it needs a change note (but I'll happily add one if necessary).
=> Python: Modernise weak file permissions query

ql/Cargo.lock, ql/extractor/Cargo.toml, ql/generator/Cargo.toml, ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/ql.dbscheme
At this point, `getName` is not really a good name for this member predicate, but I'll leave that bit of cleanup for later.
=> QL: Allow module applications to the right of `::`

swift/ql/lib/codeql/swift/dataflow/internal/TaintTrackingPublic.qll
[This call](https://github.com/github/codeql/blob/7c5a83833b974ee40be5d76faed3cdd1b5066708/swift/ql/lib/codeql/swift/dataflow/internal/tainttracking1/TaintTrackingImpl.qll#L166) had no targets, because there was no implementation of `defaultImplicitTaintRead` in the Swift implementation.    
So I added an empty implementation.  
I found it because it was the only consistency error reported by QL-for-QL (after #9575).
=> Swift: add empty implementation of `defaultImplicitTaintRead`

java/kotlin-extractor/kotlin_plugin_versions.py
For example, 1.7.0-RC would previously be truncated to 1.7.0 resulting in failure to build the single-version distro as all candidate alternate-version kotlin files would be ignored.
=> Fix Kotlin single-version build when the best candidate has trailing version info

ql/Cargo.lock, ql/extractor/Cargo.toml, ql/generator/Cargo.toml, ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/codeql_ql/ast/internal/AstNodes.qll, ql/ql/src/codeql_ql/ast/internal/Module.qll, ql/ql/src/codeql_ql/ast/internal/Predicate.qll, ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/codeql_ql/ast/internal/Type.qll, ql/ql/src/codeql_ql/style/DeadCodeQuery.qll, ql/ql/src/ide-contextual-queries/Definitions.qll, ql/ql/src/ql.dbscheme, ql/ql/src/queries/diagnostics/EmptyConsistencies.ql, ql/ql/test/callgraph/ParamModules.qll, ql/ql/test/callgraph/callgraph.expected
Supports all the features currently used in `main` (empty consistency predicates and no parse errors :tada:). 
~~But doesn't support the features that will (hopefully) be used soon.   
I'm going to work on that next.~~  
All current features should be supported!   
Commit-by-commit review partially recommended.   
The commit history is the raw history of how I implemented this (e.g. the initial parser changes were wrong).
=> QL: support for parameterized modules

python/ql/src/analysis/AlertSuppression.ql, python/ql/test/query-tests/analysis/suppression/AlertSuppression.expected
Fixes issue mentioned [here](https://github.com/github/codeql/pull/6528#issuecomment-906494399).
In the code
```
from schemacode import macros  # noqa   (used in "eval" call later on)
```
the `noqa` annotation is ignored because of the comment.
=> Python: Broaden noqa regex to allow comments

swift/ql/lib/codeql/swift/elements/expr/OtherConstructorDeclRefExpr.qll, swift/ql/test/extractor-tests/expressions/all.expected, swift/ql/test/library-tests/controlflow/graph/Cfg.expected, swift/ql/test/library-tests/parent/parent.expected
I had incorrectly concluded that `OtherConstructorDeclRefExpr` was also modeling the _call_ to the constructor, but it's really just the _reference_ to the constructor declarations.
=> Swift: Fix 'toString' on 'OtherConstructorDeclRefExpr'

swift/ql/lib/codeql/swift/elements/Locatable.qll
Fixes a bad join I was getting due to some horrible magic:
```
Tuple counts for Locatable::Locatable::getLocation#dispred#f0820431#fb@5a4d3akt:
16500   ~0%    {2} r1 = JOIN @locatable#f WITH Locatable::LocatableBase::getLocation#f0820431#ff ON FIRST 1 OUTPUT Rhs.1, Lhs.0
16000   ~0%    {2} r2 = JOIN r1 WITH m#ControlFlowGraph::ControlFlowNode::getLocation#dispred#f0820431#fb ON FIRST 1 OUTPUT Lhs.1, Lhs.0
34500   ~0%    {1} r3 = @locatable#f AND NOT Locatable::LocatableBase::getLocation#f0820431#ff_0#antijoin_rhs(Lhs.0)
251908500   ~0%    {7} r4 = JOIN r3 WITH m#ControlFlowGraph::ControlFlowNode::getLocation#dispred#f0820431#fb CARTESIAN PRODUCT OUTPUT Rhs.0, "", 0, 0, 0, 0, Lhs.0
34000   ~0%    {2} r5 = JOIN r4 WITH Location::Location::hasLocationInfo#dispred#f0820431#ffffff ON FIRST 6 …
```
=> Swift: Add `nomagic` to `getLocation`

csharp/extractor/Semmle.Extraction.CSharp/Entities/ImplicitMainMethod.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Method.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/OrdinaryMethod.cs, csharp/extractor/Semmle.Extraction.CSharp/Entities/Statements/GlobalStatementsBlock.cs, csharp/extractor/Semmle.Extraction.CSharp/Populators/CompilationUnitVisitor.cs, csharp/ql/test/library-tests/csharp9-standalone/ExtractorError.expected, csharp/ql/test/library-tests/csharp9-standalone/ExtractorError.ql
This PR fixes global statement extraction. Previously the implicit main method was extracted first, and then its body and statements were extracted independently. However, the statement extraction requires to be run in a method extraction context because it expects the tag stack to contain the current method. This PR fixes this by extracting the global statements as if they appeared inside the implicit main method.
The first commit in this PR shows that there was an extraction error before the fix in the second commit is applied. 
This issue was reported recently in https://github.com/github/codeql/issues/9536.
=> C#: Fix global statement extraction

.gitignore, javascript/extractor/lib/typescript/src/type_table.ts, javascript/extractor/src/com/semmle/js/extractor/ASTExtractor.java, javascript/extractor/src/com/semmle/js/extractor/Main.java, javascript/extractor/src/com/semmle/ts/ast/ExternalModuleDeclaration.java, javascript/extractor/src/com/semmle/ts/extractor/TypeScriptASTConverter.java, javascript/ql/lib/semmle/javascript/NPM.qll, javascript/ql/lib/semmle/javascript/NodeModuleResolutionImpl.qll, javascript/ql/lib/semmlecode.javascript.dbscheme, javascript/ql/lib/upgrades/c1ee5346e068f6e0b687e75b4ba3f04a7382f4c4/old.dbscheme, javascript/ql/lib/upgrades/c1ee5346e068f6e0b687e75b4ba3f04a7382f4c4/semmlecode.javascript.dbscheme, javascript/ql/lib/upgrades/c1ee5346e068f6e0b687e75b4ba3f04a7382f4c4/upgrade.properties
Some more improvements needed for model generation, mainly by improving analysis of `.d.ts` files.
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/madman-prep2__default__code-scanning__3/reports) looks OK
=> JS: Some more improvements to d.ts file analysis

.pre-commit-config.yaml, swift/codegen/codegen.py
This is a small quality of life improvement, mainly for the `pre-commit` usage.
=> Swift: add --quiet to codegen

javascript/ql/lib/semmle/javascript/heuristics/AdditionalTaintSteps.qll, javascript/ql/src/meta/analysis-quality/UnmodelledSteps.ql
For a call to a library function we add a taint-step from the arguments to the return value.   
Might be helpful for quickly debugging some missing taint flows.   
Also adds a meta query for counting potential unmodelled steps
(See thread on #codeql-dynamic from Jun 8th). 
I've tried to enable these steps on a few queries on `microsoft/vscode`.   
The analysis still terminated, so it seems to scale.
=> JS: add heuristic taint-step for potentially unmodelled libraries

javascript/ql/lib/semmle/javascript/Promises.qll, javascript/ql/lib/semmle/javascript/dataflow/TypeTracking.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/StepSummary.qll, javascript/ql/test/library-tests/TypeTracking/TypeTracking.ql, javascript/ql/test/library-tests/TypeTracking/raw-await.js
Doing `await x` on non-promise value just returns `x` itself, but our type-tracking steps didn't take this into account, leading to missed flow.
This PR adds support for this by adding `PropertySet` and `withoutPropStep(Node pred, Node succ, PropertySet props)`. This steps allows flow from `pred -> succ` but without the properties in `props` (see qldoc in PR).
This new step is deliberately similar to the `WithoutElement` step that @hvitved added in https://github.com/github/codeql/pull/8938. (The `WithElement` step is called a `loadStoreStep` in JS)
[Evaluation](https://github.com/github/codeql-dca-main/tree/data/asgerf/without-prop-st__default__code-scanning/reports) was quiet
=> JS: Add withoutPropStep and model raw 'await' step with it

cpp/ql/test/library-tests/variables/global/b.c, cpp/ql/test/library-tests/variables/global/c.c, cpp/ql/test/library-tests/variables/global/c.h, cpp/ql/test/library-tests/variables/global/vardecl.expected, cpp/ql/test/library-tests/variables/global/variables.expected
These expose an issue in the extractor (note the duplication of variables between `c.h` and `c.c` in `variables.expected`). I'd like to have these in whether or not I manage to fix the extractor issue.
=> C++: Add global variable tests

go/codeql-tools/tracing-config.lua
Previously, the pattern didn't match what it was intended to match.
=> Go: Properly escape dash in tracing-config.lua

.devcontainer/swift/Dockerfile, .devcontainer/swift/devcontainer.json, .devcontainer/swift/root.sh, .devcontainer/swift/update-codeql.sh, .devcontainer/swift/user.sh, .devcontainer/swift/user_bashrc.sh
This adds a specific devcontainer setup to spin up a codespace ready for use for swift development.
The configuration is selectable from the `Configure and create codespace` subcommand (selectable by clicking the down arrow next to the default `Create codespace on main` button), and on codespace creation it will:
* install required dependencies to build the swift extractor
* install bazelisk and make it callable via `bazel`
* install the latest version of codeql (can be updated with `update-codeql` at a later stage)
* create a swift extractor pack with the current version of the checked-out code
* create a codeql config file setting up `--search-path` so that the extractor pack is picked up
* set up `pre-commit`
One still needs to update the codeql CLI via the vscode command. After that, …
=> Swift: add devcontainer setup

java/ql/lib/change-notes/2022-05-25-string-valueof-editable-step.md, java/ql/lib/semmle/code/java/frameworks/android/Widget.qll, java/ql/test/library-tests/frameworks/android/widget/TestWidget.java, java/ql/test/library-tests/frameworks/android/widget/TestWidgetKt.kt, java/ql/test/library-tests/frameworks/android/widget/options, java/ql/test/library-tests/frameworks/android/widget/test.expected, java/ql/test/library-tests/frameworks/android/widget/test.ql
Kotlin inlines `expr.toString()` as `String.valueOf(expr)` when `expr` is nullable.
This PR extends #8872 by adding a taint step to handle the above when `expr` is an `Editable`.
=> Kotlin: Add taint step for String.valueOf(Editable)

java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/ql/test/kotlin/library-tests/arrays-with-variances/User.java, java/ql/test/kotlin/library-tests/arrays-with-variances/takesArrayList.kt, java/ql/test/kotlin/library-tests/arrays-with-variances/test.expected, java/ql/test/kotlin/library-tests/arrays-with-variances/test.ql
Kotlin permits introducing a `? extends ...` wildcard against an Array even though the class is final, so long as its argument itself can be extended (i.e. isn't final or is another array type satisfying this condition).
Contravariant arrays get lowered to Object[], and are subject to automatic `extends` wildcard introduction, unless their element type was already Any.
=> Kotlin: Implement array type variance lowering

cpp/ql/lib/change-notes/2022-06-22-class-declaration-entry-fix.md, cpp/ql/lib/semmle/code/cpp/UserType.qll, cpp/ql/test/library-tests/declarationEntry/declarationEntry/declarationEntry.cpp, cpp/ql/test/library-tests/declarationEntry/declarationEntry/declarationEntry.expected, cpp/ql/test/library-tests/declarationEntry/declarationEntry/fde.expected, cpp/ql/test/library-tests/declarationEntry/declarationEntry/forwardDeclaration.cpp, cpp/ql/test/library-tests/declarationEntry/declarationEntry/roundTrip.expected, cpp/ql/test/library-tests/declarationEntry/declarationEntry/roundTrip.ql
This was already possible when the forward class declaration and the class definition occurred in the same scope. However, there is a common C++ usage pattern in which this is not the case (when only a pointer to the class is needed). In this latter scenario we could not round trip between the (forward) `DeclarationEntry` and the `Declaration`.
Effectively this changes the code to:
```
if exists(TypeDeclarationEntry e | e.getType() = this)
then result.getType() = this
else ...
```
We use `type_decls` instead to stay close to the original code.
=> C++: Ensure we can round trip between (forward) class declarations

swift/ql/lib/codeql/swift/controlflow/BasicBlocks.qll, swift/ql/lib/codeql/swift/controlflow/CfgNodes.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPublic.qll
This should fix a problem @geoffw0 has been having with `MemberRefExpr`s not having an `ExprNode`. The problem is that the CFG library maps these to `PropertyGetterElement`s to model them as calls to the (sometimes compiler-generated) functions. The same applies to `PropertySetterElement`.
There might be an issue where we now have several `ExprNodes` mapping to the same `Expr`, but I think we can fix that later by restricting which nodes will have an `AstNode` in the CFG library (in particular, the nodes for which there exists a `PropertyGetterElement` or `PropertySetterElement` shouldn't have an `AstNode`).
What do you think about this solution, @rdmarsh2?
=> Swift: Make sure property setters and getters also have `ExprNodes`

javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeHtmlConstructionCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/UnsafeHtmlConstruction.expected, javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/jquery-plugin.js
Gets a TP for CVE-2022-30241 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/jqueryParam__default__CustomSuite/reports).
=> JS: add all jquery plugin parameters as source to js/html-constructed-from-input

cpp/ql/lib/semmle/code/cpp/internal/QualifiedName.qll, cpp/ql/lib/semmle/code/cpp/internal/ResolveClass.qll
* Remove a comment that no longer applies, as we switched to mangled names in `ResolveClass.qll`
* Remove redundant parentheses
=> C++: Two small QL fixes

cpp/ql/src/experimental/Security/CWE/CWE-670/DangerousUseSSL_shutdown.cpp, cpp/ql/src/experimental/Security/CWE/CWE-670/DangerousUseSSL_shutdown.qhelp, cpp/ql/src/experimental/Security/CWE/CWE-670/DangerousUseSSL_shutdown.ql, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-670/semmle/tests/DangerousUseSSL_shutdown.expected, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-670/semmle/tests/DangerousUseSSL_shutdown.qlref, cpp/ql/test/experimental/query-tests/Security/CWE/CWE-670/semmle/tests/test.cpp
this query looks for improperly closed connections.
CVE-2008-1531
when the situations of calling the second function to close are not processed.
=> CPP: Add query for CWE-670: Always-Incorrect Control Flow Implementation when use SSL_shutdown 

javascript/downgrades/c0664d5721c90dd32a5b167efea24f9cc6f57cfb/ast_node_symbol.ql, javascript/downgrades/c0664d5721c90dd32a5b167efea24f9cc6f57cfb/upgrade.properties
Avoids introducing a DB inconsistency when downgrading
=> JS: Downgrade ast_node_symbol relation

swift/ql/lib/codeql/swift/dataflow/internal/SsaImplSpecific.qll
This check is unnecessary since it's enforced by the compiler, and is causing a bad join order.
=> Swift: remove check for inout params in SSA gen

swift/codegen/generators/qlgen.py, swift/codegen/test/test_qlgen.py
It turns out the threshold of 5 lines for stub modification detection
was too strict: in case of a long class name the QL formatter will put
the closing brace of the empty class definition on a new line, leading
to codegen fail with an error thinking the stub was modified.
On the other side of things, also adding a base to a stub class was not
being detected as a modification.
Now the modification test is slightly smarter. If the stub still marked
as generated and
* has more than 6 lines, or
* the contents does not match a regexp aproximation of a plain stub
then codegen will abort. The test will still avoid reading the whole
contents of all the stubs.
=> Swift: fix stub revert prevention

swift/codegen/templates/ql_class.mustache, swift/ql/lib/codeql/swift/generated/Element.qll
One should only override `getResolveStep` (or `convertsFrom` for `Expr`
classes), as otherwise the resolution/conversion becomes inconsitent.
=> Swift: make `Element::resolve` final

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/ql/consistency-queries/calls.ql, java/ql/test/kotlin/library-tests/lazy-val-multiple-constructors/test.expected, java/ql/test/kotlin/library-tests/lazy-val-multiple-constructors/test.kt, java/ql/test/kotlin/library-tests/lazy-val-multiple-constructors/test.ql
This avoids DB inconsistencies because complex initialisers are extracted to more than one function.
=> Kotlin: reintroduce obinit when we have multiple secondary constructors and no primary

ruby/ql/lib/codeql/ruby/ApiGraphs.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll, ruby/ql/lib/codeql/ruby/frameworks/GraphQL.qll, ruby/ql/lib/codeql/ruby/frameworks/Rails.qll, ruby/ql/lib/codeql/ruby/frameworks/XmlParsing.qll, ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll, ruby/ql/lib/codeql/ruby/frameworks/data/ModelsAsData.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Excon.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Faraday.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/HttpClient.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Httparty.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/NetHttp.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/OpenURI.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/RestClient.qll, ruby/ql/lib/codeql/ruby/frameworks/http_clients/Typhoeus.qll, ruby/ql/test/library-tests/dataflow/api-graphs/use.ql, ruby/ql/test/library-tests/dataflow/summaries/Summaries.ql
The Ruby version of https://github.com/github/codeql/pull/8606
=> Ruby: API graph renaming an documentation

ruby/ql/lib/codeql/ruby/frameworks/Railties.qll
Fixes a semantic merge conflict between https://github.com/github/codeql/pull/9574 and https://github.com/github/codeql/pull/9364 causing a deprecation warning during compilation.
=> Ruby: fix deprecation warning

swift/ql/lib/codeql/swift/elements/type/Type.qll, swift/ql/src/queries/Security/CWE-135/StringLengthConflation.qhelp, swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql, swift/ql/src/queries/Security/CWE-135/StringLengthConflationBad.swift, swift/ql/src/queries/Security/CWE-135/StringLengthConflationGood.swift, swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.expected
String length conflation query, i.e. query for [CVE-2022-23625](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23625) ([patch](https://github.com/wireapp/wire-ios-transport/commit/02e90aa45edaf7eb2d8b97fa2377cd8104274170)) / [CWE-135](https://cwe.mitre.org/data/definitions/135.html).
~This is a draft PR because there are a bunch of things I need to clean up that I'm looking for advice on - see the `TODO` comments in the code.  Many of these will involve small additions in the libraries and I'm seeking discussion of the design of these improvements.~
~The query is also missing qldoc, qhelp, Swift example code, query metadata, a proper violation message, change note ... and results in the `NSString` -> `Swift.String` direction.  I don't anticipate any problems in these areas.~ …
=> Swift: String length conflation query

javascript/extractor/src/com/semmle/js/extractor/FileExtractor.java, javascript/extractor/src/com/semmle/js/extractor/Main.java
The dist upgrade showed some MPEG Transport Stream (video) files with the extension `.mts` that were accidentally parsed as TypeScript. This is a problem we used to have with `.ts` files but the solution was not applied to `.mts` files when we started extracting those. We now apply this to all TypeScript files (including `.tsx` and `.cts`).
=> JS: always sniff file header of TypeScript files

swift/ql/lib/codeql/swift/elements/Locatable.qll
In one version of a test I tried to use this and couldn't, because it didn't exist.  Its a nice shortcut to have.
=> Swift: Add a Locatable.getFile() shortcut similar to the one in CPP.

swift/integration-tests/partial-modules/A/Package.swift, swift/integration-tests/partial-modules/A/Sources/A/A.swift, swift/integration-tests/partial-modules/A/Sources/A/Asup.swift, swift/integration-tests/partial-modules/B/Package.swift, swift/integration-tests/partial-modules/B/Sources/B/B.swift, swift/integration-tests/partial-modules/B/Sources/B/Bsup.swift, swift/integration-tests/partial-modules/Package.swift, swift/integration-tests/partial-modules/Sources/partial-modules/partial_modules.swift, swift/integration-tests/partial-modules/Unknown.ql, swift/integration-tests/partial-modules/test.py
Extractor fails to load separate modules that were built by another
version of an actual compiler.
The test currently fails, but I'd like to get it in separately from [the fix](https://github.com/github/codeql/pull/9702) in order to reduce the other PR diff.
=> Swift: add a test case showing module loading problem

swift/extractor/SwiftExtractor.cpp, swift/extractor/SwiftExtractorConfiguration.h, swift/extractor/main.cpp
Currently, we have a number of assertions in the codebase and certain assumptions about the AST. These don't always hold, sometimes leading to a crash in the extractor.
The crashes leave incomplete TRAP files that cannot be imported into the database.
With this change, we still get those incomplete TRAP files, but we also get a database in the end (even though it is also incomplete as we cannot import everything).
=> Swift: store TRAP files in a temporary folder until the extraction is complete

swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql
Before:
```ql
Tuple counts for StringLengthConflation::StringLengthConflationConfiguration::isSink#dispred#f0820431#cpe#23#ff/2@a077435u after 44.9s:
8437     ~4%      {4} r1 = SCAN ApplyExpr::ApplyExprBase::getArgument#dispred#f0820431#fff OUTPUT In.0, "String", In.1, In.2
3936     ~2%      {4} r2 = JOIN r1 WITH call_exprs ON FIRST 1 OUTPUT Lhs.2, "String", Lhs.0, Lhs.3
95328723 ~3%      {5} r3 = JOIN r2 WITH Callable::CallableBase::getParam#dispred#f0820431#fff_102#join_rhs ON FIRST 1 OUTPUT Lhs.2, Rhs.1, "String", Lhs.3, Rhs.2
886      ~2%      {4} r4 = JOIN r3 WITH ApplyExpr::ApplyExpr::getStaticTarget#dispred#f0820431#ff ON FIRST 2 OUTPUT Lhs.4, "String", Lhs.0, Lhs.3
886      ~0%      {6} r5 = JOIN r4 WITH var_decls ON FIRST 1 OUTPUT "String", Lhs.2, Lhs.3, Lhs.0, Rhs.1, Rhs.2
4 …
```
=> Swift: Don't join on index in `swift/string-length-conflation`

python/ql/lib/semmle/python/pointsto/MRO.qll
Fixes a bad join in `list_of_linearization_of_bases_plus_bases`.
Previvously, we joined together `ConsList` and `getBase` before filtering
these out using the recursive call. Now we do the recursion first.
=> Python: Fix bad join in MRO

python/ql/lib/semmle/python/RegexTreeView.qll
Although this wasn't (as far as I know) causing any performance issues,
it was making the join-order badness report quite noisy, and so I
figured it was worth fixing.
Before:
```
Tuple counts for RegexTreeView::RegExpBackRef::getGroup#dispred#f0820431#ff/2@d3441d0b after 84ms:
1501195 ~3%     {2} r1 = JOIN RegexTreeView::RegExpTerm::getLiteral#dispred#f0820431#ff_10#join_rhs WITH RegexTreeView::RegExpTerm::getLiteral#dispred#f0820431#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'result', Lhs.1 'result'
149     ~0%     {5} r2 = JOIN r1 WITH RegexTreeView::RegExpBackRef#class#31aac2a7#ffff ON FIRST 1 OUTPUT Rhs.1, Rhs.2, Rhs.3, Lhs.1 'result', Lhs.0 'this'
149     ~1%     {3} r3 = JOIN r2 WITH regex::RegexString::numbered_backreference#dispred#f0820431#ffff ON FIRST 3 OUTPUT Lhs.3 'result', …
```
=> Python: Fix bad join in `RegExpBackRef::getGroup`

python/ql/lib/semmle/python/pointsto/MRO.qll
This bad join was identified by the join-order-badness report, which
showed that:
```py/use-of-input:MRO::flatten_list#f4eaf05f#fff#9c5fe54whnlqffdgu65vhb8uhpg# (order_500000)```
calculated a whopping 212,820,108 tuples in order to produce an output of
size 55516, roughly 3833 times more effort than needed.
Here's a snippet of the slowest iteration of that predicate:
```
Tuple counts for MRO::flatten_list#f4eaf05f#fff/3@i1839#0265eb3w after 14ms:
0     ~0%     {3} r1 = JOIN MRO::need_flattening#f4eaf05f#f#prev_delta WITH MRO::ConsList#f4eaf05f#fff#reorder_2_0_1#prev ON FIRST 1 OUTPUT Rhs.1, Lhs.0 'list', Rhs.2
0     ~0%     {3} r2 = JOIN r1 WITH MRO::ClassList::length#f0820431#ff#prev ON FIRST 1 OUTPUT Lhs.2, Lhs.1 'list', Rhs.1 'n'
0     ~0%     {3} r3 = JOIN r2 WITH …
```
=> Python: Fix bad join in MRO `flatten_list`

swift/ql/lib/codeql/swift/elements/expr/ArithmeticOperation.qll, swift/ql/lib/codeql/swift/elements/expr/LogicalOperation.qll, swift/ql/lib/swift.qll, swift/ql/test/library-tests/controlflow/graph/Cfg.expected, swift/ql/test/library-tests/elements/expr/arithmeticoperation/arithmeticoperation.expected, swift/ql/test/library-tests/elements/expr/arithmeticoperation/arithmeticoperation.ql, swift/ql/test/library-tests/elements/expr/arithmeticoperation/arithmeticoperation.swift, swift/ql/test/library-tests/elements/expr/logicaloperation/logicaloperation.expected, swift/ql/test/library-tests/elements/expr/logicaloperation/logicaloperation.ql, swift/ql/test/library-tests/elements/expr/logicaloperation/logicaloperation.swift
Add an `ArithmeticOperation.qll` library, and make various related changes:
- add tests for `ArithmeticOperation.qll` and `LogicalOperation.qll`.
- fix `LogicalOperation.qll` to account for function call `getName` now including the argument pattern.
- we'd have caught this sooner if there had been a test.
- also simplified the QL in that library slightly.
- change `ApplyExpr` to produce a slightly better `toString` in some cases.  I'd really like someone to review this change as I'm not sure how general what I've written is.
I'd also like to know if we're happy with the naming of `BinaryExpr`, `BinaryArithmeticOperation`, `AddExpr` etc, before this stuff becomes more established and difficult to change.
=> Swift: Add ArithmeticOperation.qll library

javascript/ql/lib/semmle/javascript/security/dataflow/ClientSideUrlRedirectCustomizations.qll, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/Xss.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/XssWithAdditionalSources.expected, javascript/ql/test/query-tests/Security/CWE-079/DomBasedXss/tst.js
Browsers like Chrome already implement the [Navigation API](https://wicg.github.io/navigation-api/), and some developers are already using it.  
(When [I try to search for it](https://cs.github.com/?scopeName=All+repos&scope=&q=navigation.navigate%28) all that turns up is React code, which is not the same API). 
[Evaluation was unevenful](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/navigation__nightly-old__CustomSuite/reports).
=> JS: add navigation.navigate as an XSS / URL sink

swift/ql/test/extractor-tests/generated/type/InOutType/in_out.swift
Swift compiler refuses to compile this file, the test failure exposed via https://github.com/github/codeql/pull/9702
```bash
> swift in_out.swift
in_out.swift:12:3: error: variable 's' passed by reference before being initialized
s.bar()
^
in_out.swift:11:5: note: variable defined here
var s: S
^
```
=> Swift: fix test case

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/ql/integration-tests/posix-only/kotlin/nested_generic_types/JavaUser.java, java/ql/integration-tests/posix-only/kotlin/nested_generic_types/KotlinUser.kt, java/ql/integration-tests/posix-only/kotlin/nested_generic_types/libsrc/extlib/OuterGeneric.java, java/ql/integration-tests/posix-only/kotlin/nested_generic_types/libsrc/extlib/OuterNotGeneric.java, java/ql/integration-tests/posix-only/kotlin/nested_generic_types/libsrc/extlib/TypeParamVisibility.java, java/ql/integration-tests/posix-only/kotlin/nested_generic_types/test.expected
Previously the Java extractor did this but the Kotlin extractor nested them within an unbound outer type.
=> Kotlin: note that raw inner classes nest within a raw outer

swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql, swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.expected, swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.swift
Improvements to the string length conflation query:
- allow taint-like flow though `+` and `-`
- when we have taint flow for Swift we may want to consider using it, but I'm not sure.  For `+` and `-` there's a very strong case that that the code still working with a conflated string length value and is unlikely to have fixed that value somehow.
- this change greatly increases the proportion of test cases we catch.
- add QLDoc to the `StringLengthConflationConfiguration` class.
=> Swift: Improvements to the string length conflation query

java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt
We want the .javaResult.id of a TypeResults.
=> Kotlin: Fix a label

java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/ql/consistency-queries/visibility.ql, java/ql/integration-tests/posix-only/kotlin/module_mangled_names/User.java, java/ql/integration-tests/posix-only/kotlin/module_mangled_names/test.expected, java/ql/integration-tests/posix-only/kotlin/module_mangled_names/test.py, java/ql/integration-tests/posix-only/kotlin/module_mangled_names/test.ql, java/ql/integration-tests/posix-only/kotlin/module_mangled_names/test1.kt, java/ql/integration-tests/posix-only/kotlin/module_mangled_names/test2.kt, java/ql/integration-tests/posix-only/kotlin/module_mangled_names/test3.kt, java/ql/test/kotlin/library-tests/internal-public-alias/User.java, java/ql/test/kotlin/library-tests/internal-public-alias/test.expected, java/ql/test/kotlin/library-tests/internal-public-alias/test.kt, java/ql/test/kotlin/library-tests/internal-public-alias/test.ql, java/ql/test/kotlin/library-tests/java-kotlin-collection-type-generic-methods/test.expected, java/ql/test/kotlin/library-tests/methods/methods.expected, java/ql/test/kotlin/library-tests/modifiers/modifiers.expected, java/ql/test/kotlin/library-tests/properties/properties.expected
These are suffixed with `$main` by default, or `$modulename` if one is provided to the compiler.
=> Kotlin: Mangle names of internal functions to match JVM symbols

swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql, swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.expected, swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.swift
More improvements to `swift/string-length-conflation`:
- conflation in the `String` -> `NSString` direction is now detected 🎉 
- slightly more data flow is permitted (in particular through operators `*`, `/`)
- additional test cases
Notably for the `String` and `String.Index` member functions, I can't find a way of checking the associated class is correct (i.e. that we're looking at a call to `String.index` not `foo.index`).  While this would be nice to have, in practice since we match on the argument and parameter names as well, so I think false positives are unlikely.
=> Swift: More improvements to swift/string-length-conflation

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/ql/integration-tests/posix-only/kotlin/private_property_accessors/hasprops.kt, java/ql/integration-tests/posix-only/kotlin/private_property_accessors/test.expected, java/ql/integration-tests/posix-only/kotlin/private_property_accessors/test.py, java/ql/integration-tests/posix-only/kotlin/private_property_accessors/test.ql, java/ql/integration-tests/posix-only/kotlin/private_property_accessors/usesprops.kt
Previously these would get extracted unlike other private methods even if the class was a standard library or other external class. This could cause inconsistencies because if we also compiled the class from source we could end up deciding different names for the property's setter: setXyz$private when seen from source, and setXyz without a
suffix when seen as an external .class file. Avoiding extracting these functions from the external perspective both restores consistency with other kinds of method and avoids these consistency problems.
=> Kotlin: don't extract private setters of external classes

cpp/ql/src/Likely Bugs/UseInOwnInitializer.ql
This predicate has been popping in and out of the join-order badness report on Abseil for a while. 
Before:
```
Tuple counts for UseInOwnInitializer::VariableAccessInInitializer#class#218a1892#bbf/3@c6f2f002 after 4.9s:
1373964  ~3%     {2} r1 = JOIN Access::VariableAccess#8878f617#f WITH Access::Access::getTarget#dispred#f0820431#ff ON FIRST 1 OUTPUT Rhs.1 'var', Lhs.0 'this'
0        ~0%     {3} r2 = JOIN r1 WITH initialisers_120#join_rhs ON FIRST 2 OUTPUT Lhs.1 'this', Lhs.0 'var', Rhs.2 'init'
87097753 ~1%     {4} r3 = JOIN r1 WITH initialisers_102#join_rhs ON FIRST 1 OUTPUT Rhs.2, Lhs.1 'this', Lhs.0 'var', Rhs.1 'init'
6        ~0%     {3} r4 = JOIN r3 WITH #Expr::Expr::getAChild#dispred#f0820431Plus#bf ON FIRST 2 OUTPUT Lhs.1 'this', Lhs.2 'var', Lhs.3 'init'
6        ~0%     {3} …
```
=> C++: Add `nomagic` to `VariableAccessInInitializer`

cpp/ql/test/library-tests/controlflow/nullness/nullness.expected, cpp/ql/test/library-tests/controlflow/nullness/nullness.ql, cpp/ql/test/library-tests/controlflow/nullness/test.cpp
For the benefit of https://github.com/github/codeql/pull/9785. It seems we didn't have any tests covering this.
=> C++: Add tests for `AnalysedExpr::isNullCheck` and `AnalysedExpr::isValidCheck`

ruby/ql/lib/change-notes/2022-07-11-command-execution.md, ruby/ql/lib/codeql/ruby/frameworks/PosixSpawn.qll, ruby/ql/lib/codeql/ruby/frameworks/Railties.qll, ruby/ql/test/library-tests/frameworks/PosixSpawn.ql, ruby/ql/test/library-tests/frameworks/railties/Railties.expected, ruby/ql/test/library-tests/frameworks/railties/Railties.ql
For any database where there is at least one call to `execute_command`, `rake`, `rails_command`, or `git` from `Rails::Generations::Actions`, we accidentally defined every dataflow node in the database as a system command execution sink.
Originally introduced in https://github.com/github/codeql/pull/9574, but presumably not spotted by the DCA run because none of our DCA projects call one of those methods.
=> Ruby: fix defining every dataflow node as a command execution sink

docs/codeql/codeql-cli/creating-and-working-with-codeql-packs.rst, docs/codeql/codeql-cli/publishing-and-using-codeql-packs.rst, docs/codeql/reusables/beta-note-package-management.rst
This PR updates the following docs:
- https://codeql.github.com/docs/codeql-cli/publishing-and-using-codeql-packs/
- https://codeql.github.com/docs/codeql-cli/creating-and-working-with-codeql-packs/
to add information on managing packs on GHES 3.6+ with CodeQL CLI 2.9.4+.
We add a section on authentication too which applies to both Dotcom and GHES users.
@aeisenberg @dbartol @jf205 I'd love to get your initial thoughts on this.
=> Docs: Document packaging support for CodeQL CLI 2.9.4+ on GHES 3.6+

swift/codegen/generators/cppgen.py, swift/codegen/schema.yml, swift/codegen/test/test_cppgen.py
Some fields of base classes pose some problems with diamond hierarchies,
and we don't use them any way as we are emitting them using directly
trap entries instead of structured C++ classes.
This introduces a `cpp_skip` pragma to skip generation of those fields
in structured generated C++ classes, and applies it to `is_unknown` and
`location`.
=> Swift: allow skipping fields in cppgen

javascript/ql/lib/semmle/javascript/dataflow/TypeTracking.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeHtmlConstructionCustomizations.qll, javascript/ql/src/Security/CWE-094/ImproperCodeSanitization.ql, javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/UnsafeHtmlConstruction.expected, javascript/ql/test/query-tests/Security/CWE-079/UnsafeHtmlConstruction/main.js
The `smallStep` predicate should be used as: `t2 = t.smallstep(result, myType(t2))`.  
Most of the uses of `smallStep` did this correctly.   
However, the documentation of `smallStep` and two uses had flipped `t` and `t2`.  
So I fixed that.  
Found while triaging CVE-2022-31127, but I don't think this fix will help us flag that CVE (the source is not library input).  
[Evaluation shows neutral performance](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-9798-c27ddf6__nightly-old__CustomSuite/reports) and some new TPs.
=> JS: use small steps in TypeBackTracker correctly

javascript/ql/src/Declarations/UnusedVariable.ql
Fixes https://github.com/github/codeql/issues/9777 
The attributes in `.vue` files are not currently extracted, so there is no pretty way for us to detect whether a variable is used or not.    
So I've excluded `.vue` files from the query.  
[An evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-9794-9ed7aa9__nightly-old__CustomSuite/reports) shows no performance penalty.  
But unfortunately it also removes a bunch of TPs.
=> JS: exclude variables in .vue files form js/unused-local-variable

python/ql/lib/semmle/python/frameworks/internal/SubclassFinder.qll
This predicate needs a `bindingset` annotation to work, however it seems cleaner to just be an alias.
=> Python: Fix binding incorrect predicate.

swift/ql/src/queries/Security/CWE-135/StringLengthConflation.ql, swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.expected, swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation2.swift
More improvements for the string length conflation query:
- added a test for a potential issue with implementations of `NSString` that has been discussed before, where member functions are defined in a parent class rather than directly in `NSString` itself.  At the moment I believe we can't *fix* this issue because we don't have information about base classes, but at least now it is documented with a test.
- clean up the QL for `isSink` (less code duplication).
=> Swift: More improvements for the string length conflation query

docs/codeql/codeql-overview/supported-languages-and-frameworks.rst, docs/codeql/support/reusables/frameworks.rst
Include links to the CLI changelog, CLI releases, bundle releases, pack changelogs, and pack source.
Clarify that this support information applies to the current version of the CLI, bundle, query packs, and library packs.
Reviewer notes:
- I'm slightly unsure how often to mention the CodeQL bundle. We should mention it somewhere, but it feels like too much to mention it everywhere we mention the query or library packs. I've compromised by mentioning it only where we mention the CLI.
=> Docs: Update supported languages page with links to CLI and pack information

csharp/tools/tracing-config.lua
For proper C# tracing, `dotnet build` needs the parameter
`/p:UseSharedCompilation=false`. However, we can't pass that to the other
subcommands of `dotnet`, therefore we need to figure out which subcommand
of `dotnet` is being invoked.
=> C#: Implement correct behavior for `dotnet build` tracing

cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql
Before on Abseil Linux:
```
Evaluated relational algebra for predicate ExecTainted::ExecState#class#91000ffb#fff@41084cm7 with tuple counts:
40879811  ~0%    {2} r1 = SCAN DataFlowUtil::Node::getLocation#dispred#f0820431#ff OUTPUT In.1, In.0
40879811  ~0%    {2} r2 = JOIN r1 WITH Location::Location::toString#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1
7527  ~3%    {3} r3 = JOIN r2 WITH ExecTainted::interestingConcatenation#91000ffb#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.0
7527  ~0%    {4} r4 = JOIN r3 WITH DataFlowUtil::Node::toString#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.2, Lhs.1, Lhs.0, Rhs.1
7527  ~0%    {5} r5 = JOIN r4 WITH DataFlowUtil::Node::toString#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.2, Lhs.1, Lhs.0, Lhs.3, Rhs.1
7527  ~0%    {6} r6 = JOIN r5 WITH …
```
=> C++: Fix join-order problem in `cpp/command-line-injection`

ql/extractor/src/extractor.rs, ql/extractor/src/main.rs, ql/extractor/src/trap.rs
Synchronise the minor refactoring changes from https://github.com/github/codeql/pull/9878. Shouldn't result in any observable differences.
=> QL: sync Ruby extractor changes

ruby/Cargo.lock, ruby/extractor/Cargo.toml, ruby/extractor/src/main.rs, ruby/ql/test/library-tests/ast/Ast.expected, ruby/ql/test/library-tests/ast/TreeSitter.expected, ruby/ql/test/library-tests/ast/ValueText.expected, ruby/ql/test/library-tests/ast/misc/iso-8859-15.rb
This PR adds support for magic character `coding: [CHARSET]` comments in Ruby source files. If such a comment is detected and `CHARSET` is not `UTF-8` then the source file's contents needs to be converted from `CHARSET` into UTF-8. In addition we should store the converted contents in the source archive, because files in the source archives have to be in UTF-8 format.
See also: https://en.wikibooks.org/wiki/Ruby_Programming/Encoding#Using_Encodings
=> Ruby: handle magic coding: comments

cpp/ql/lib/change-notes/2022-06-24-unique-variable.md, cpp/ql/lib/semmle/code/cpp/Element.qll, cpp/ql/lib/semmle/code/cpp/Variable.qll, cpp/ql/lib/semmle/code/cpp/internal/ResolveGlobalVariable.qll, cpp/ql/test/library-tests/variables/global/variables.expected
Depending on the extraction order, before this change there might be multiple `GlobalVariable`s per declared global variable. See the tests in `cpp/ql/test/library-tests/variables/global`. This change ensures that only one of those `GlobalVariable`s is visible to the user if we can locate a unique definition. If not, the old situation persists.
Note that an exception needs to be made for templated variables. Here, the definition refers to the non-instantiated template, while a declaration that is not a definition refers to an instantiation. In case the instantiation refers to a template parameter, the mangled names of the template and the instantiation will be identical. This happens for example in the following case:
```
template <typename T>
T x = T(42);           // Uninstantiated …
```
=> C++: Ensure only one `Variable` exists for every global variable

cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql
Before on Abseil:
```
Evaluated relational algebra for predicate #select#cpe#12356#fffff@3ffb21o1 with tuple counts:
1235939  ~0%    {2} r1 = SCAN functions OUTPUT In.0, In.0
1235939  ~0%    {2} r2 = JOIN r1 WITH functions ON FIRST 1 OUTPUT Lhs.1, Lhs.0
33500841  ~0%    {2} r3 = JOIN r2 WITH DataFlowUtil::Node::getEnclosingCallable#dispred#f0820431#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1
280683  ~3%    {3} r4 = JOIN r3 WITH MustFlow::MkLocalPathNode#0227f5a1#fff ON FIRST 1 OUTPUT Rhs.2, Lhs.1, Lhs.0
40970  ~2%    {4} r5 = JOIN r4 WITH MustFlow::MustFlowConfiguration::hasFlowPath#dispred#f0820431#fff#cpe#23_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.0
40970  ~0%    {5} r6 = JOIN r5 WITH MustFlow::MkLocalPathNode#0227f5a1#fff_20#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, …
```
=> C++: Fix join-order problem in `cpp/return-stack-allocated-memory`

ql/extractor/src/trap.rs, ruby/extractor/src/trap.rs
Previously, the `BufWriter` came *after* the `GzEncoder` in the chain of writers (i.e. the `GzEncoder` wrapped the `BufWriter`), which meant that we were gzip-encoding every tiny string as soon it was formatted, and the `BufWriter` was just adding buffering between the `GzEncoder`'s output and the file.
Now we invert the relationship, so as we format strings they get buffered by `BufWriter`, and only when its buffer gets full does it pass the data on to `GzEncoder`. It's much more efficient for the `GzEncoder` to perform its compression less often on larger amounts of data in each go.
I think this problem has existed since the very early days of the Ruby extractor, but it didn't cause a noticeable slowdown until the recent refactoring in #9878.
That's because, before the refactoring, we …
=> Ruby/QL: speed up trap writing by putting BufWriter in front of GzEncoder

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/ql/test/kotlin/library-tests/for-array-iterators/test.expected, java/ql/test/kotlin/library-tests/for-array-iterators/test.kt, java/ql/test/kotlin/library-tests/for-array-iterators/test.ql
`Array<*>` can't be queried for an argument type, and `IntArray` doesn't have an argument at all; both were previously causing the extractor to fail to extract the whole file due to throwing an exception.
=> Kotlin: fix for-loop iterators over primitive or wildcard types

java/kotlin-extractor/src/main/kotlin/utils/JvmNames.kt, java/ql/test/kotlin/library-tests/reflection/PrintAst.expected, java/ql/test/kotlin/library-tests/string-charat/Test.java, java/ql/test/kotlin/library-tests/string-charat/test.expected, java/ql/test/kotlin/library-tests/string-charat/test.kt, java/ql/test/kotlin/library-tests/string-charat/test.ql
In the Kotlin universe this is called `get` so that Kotlin programmers can use the `[]` operator on `String`s.
=> Kotlin: Special-case String.charAt naming

java/ql/lib/change-notes/2022-05-12-get-underlying-expr.md, java/ql/lib/semmle/code/java/Expr.qll, java/ql/lib/semmle/code/java/security/CleartextStorageSharedPrefsQuery.qll, java/ql/lib/semmle/code/java/security/UnsafeAndroidAccess.qll, java/ql/test/query-tests/security/CWE-312/CleartextStorageSharedPrefsTestKt.kt, java/ql/test/query-tests/security/CWE-312/options, java/ql/test/query-tests/security/CWE-749/AndroidManifest.xml, java/ql/test/query-tests/security/CWE-749/UnsafeActivityKt.kt, java/ql/test/query-tests/security/CWE-749/options
Adds a predicate to look through casts and not-null expressions to obtain the underlying expression. Uses this new predicate in a couple of queries that need it to work properly in Kotlin codebases.
=> Java: Add Expr::getUnderlyingExpr predicate

java/ql/lib/change-notes/2022-07-27-nullness-junit5.md, java/ql/lib/semmle/code/java/frameworks/Assertions.qll
JUnit5 `AssertNotNull` was not recognized since the package name had changed from JUnit4.
Fixes https://github.com/github/codeql/issues/9901
=> Java: Add support for JUnit5 assertions in the nullness queries.

csharp/ql/lib/semmle/code/csharp/controlflow/internal/ControlFlowGraphImplShared.qll, ruby/ql/lib/codeql/ruby/controlflow/internal/ControlFlowGraphImplShared.qll, swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImplShared.qll
In Swift we encountered a situation where ordering of nodes and edges in the control flow graph was not stable between test runs.
This patch:
* adds the successor string representation to the edge ordering
* adds an overridable `getOrderDisambiguation` method to both node and edge orderings
This is used in https://github.com/github/codeql/pull/9891
This is currently only used in tests.
=> Control Flow: extend ordering

swift/integration-tests/create_database_utils.py
This enables having more information in the DB check results.
=> Swift: add `--no-cleanup` to integration tests

swift/extractor/infra/SwiftDispatcher.h
File extraction was not using named trap keys, and `emitDebugInfo` was
using `std::forward` when it should not.
=> Swift: small dispatcher fixes

swift/extractor/SwiftExtractor.cpp
This removes duplicated TRAPs for precompiled clang modules.
=> Swift: put all the PCM traps into the same place

java/ql/test/TestUtilities/InlineExpectationsTestPrivate.qll, java/ql/test/library-tests/xml/Test.java, java/ql/test/library-tests/xml/XMLTest.expected, java/ql/test/library-tests/xml/XMLTest.ql, java/ql/test/library-tests/xml/test.xml
This will help write tests for Android queries with results in `AndroidManifest.xml`.
=> Java: Add support for XML InlineExpectationsTest

.github/actions/fetch-codeql/action.yml, .github/workflows/check-qldoc.yml, .github/workflows/csv-coverage-metrics.yml, .github/workflows/csv-coverage-pr-artifacts.yml, .github/workflows/csv-coverage-timeseries.yml, .github/workflows/csv-coverage-update.yml, .github/workflows/csv-coverage.yml, .github/workflows/go-tests.yml, .github/workflows/js-ml-tests.yml, .github/workflows/mad_regenerate-models.yml, .github/workflows/query-list.yml, .github/workflows/ruby-build.yml, .github/workflows/ruby-qltest.yml, .github/workflows/swift-codegen.yml, .github/workflows/swift-integration-tests.yml, .github/workflows/swift-qltest.yml, .github/workflows/validate-change-notes.yml
Many of the CI jobs download a copy of the CodeQL CLI. However, they were using different ways of doing that:
* through the `fetch-codeql` action
* using `gh codeql`
* dowloading and unzipping release artifacts from the codeql-cli-binaries repo
This PR refactors the workflows to all use the `fetch-codeql` Action. The `fetch-codeql` action itself is re-implemented using `gh codeql`
The workflows affected by this change are:
```
.github/workflows/check-qldoc.yml
.github/workflows/csv-coverage-metrics.yml
.github/workflows/js-ml-tests.yml
.github/workflows/mad_modelDiff.yml
.github/workflows/mad_regenerate-models.yml
.github/workflows/qhelp-pr-preview.yml
.github/workflows/query-list.yml
.github/workflows/ruby-dataset-measure.yml
.github/workflows/ruby-qltest.yml …
```
=> CI: make all jobs that fetch a CodeQL CLI use the fetch-codeql action

cpp/ql/src/Likely Bugs/Likely Typos/IncorrectNotOperatorUsage.ql, cpp/ql/src/Likely Bugs/Likely Typos/UsingStrcpyAsBoolean.ql, cpp/ql/src/Likely Bugs/Likely Typos/inconsistentLoopDirection.ql, cpp/ql/src/Security/CWE/CWE-253/HResultBooleanConversion.ql, cpp/ql/src/Security/CWE/CWE-428/UnsafeCreateProcessCall.ql, cpp/ql/src/Security/CWE/CWE-704/WcharCharConversion.ql, cpp/ql/src/Security/CWE/CWE-732/UnsafeDaclSecurityDescriptor.ql
This PR removes the internal `microsoft` tags on the remaining seven queries. Now, `grep`'ing for `"external/microsoft"` gives no more results in `.ql` files.
=> C++: Remove internal `microsoft` tags from queries

java/ql/src/Violations of Best Practice/Naming Conventions/SameNameAsSuper.ql
Easy fix for a very bad join-order.
=> Java: Fix join-order in SameNameAsSuper.

python/ql/test/query-tests/Security/CWE-022-TarSlip/TarSlip.expected
Changed after merging https://github.com/github/codeql/pull/9579, which improved our handling of `not` for guards.
=> Python: Accept `.expected` for TarSlip

cpp/ql/lib/change-notes/2022-08-02-must-flow-local-only-flow.md, cpp/ql/lib/semmle/code/cpp/ir/dataflow/MustFlow.qll, cpp/ql/src/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql, cpp/ql/test/query-tests/Likely Bugs/Memory Management/ReturnStackAllocatedMemory/ReturnStackAllocatedMemory.expected
When we created the `MustFlow` library in https://github.com/github/codeql/pull/8368 we added a somewhat ugly check in `cpp/return-stack-allocated-memory` to prevent FPs from occurring when we flow into callables.
However, this condition was only checked _after_ the dataflow graph had been computed. This meant that lots of edges was added even though they were immediately thrown out by the `var.getEnclosingFunction() = sink.getNode().getEnclosingCallable()` conjunct in the `select` body.
The problem can be seen on this snapshot:
```ql
Evaluated relational algebra for predicate MustFlow::MustFlowConfiguration::hasFlowPath#dispred#f0820431#fff#cpe#23@0c7142k3 with tuple counts:
6911  ~0%   {2} r1 = JOIN MustFlow::MustFlowConfiguration::hasFlowPath#dispred#f0820431#fff#cpe#23#higher_order_bod …
```
=> C++: Speedup `cpp/return-stack-allocated-memory`

ruby/ql/lib/codeql/ruby/printAst.qll, ruby/ql/test/library-tests/ast/AstDesugar.expected
My experimental PR https://github.com/github/codeql/pull/9936 indicates that there is likely to be a [test failure](https://github.com/github/codeql/runs/7634387028?check_suite_focus=true#step:5:131) in the future caused by differences in AstNode ordering. 
This PR ensures that the AstDesugar tests pass with both the current and the nightly release.
@hvitved
=> Ruby: PrintAST: more stable order for synthesized nodes

java/ql/lib/semmle/code/java/Type.qll, java/ql/src/Likely Bugs/Collections/ContainsTypeMismatch.ql, java/ql/src/Likely Bugs/Collections/RemoveTypeMismatch.ql, java/ql/src/Likely Bugs/Comparison/IncomparableEquals.ql
This effectively pulls the functional `erase(..)` calls out of the negation context, which improves the join-order, as we'll then end up with a simple filter `not erasedHaveIntersection(e1, e2)`. Prior to this the negation body would order the predicates `erase; erasedHaveIntersection; erase`, which was fairly bad.
Also, drive-by changed a couple of `.getAnAncestor().getSourceDeclaration()` to `.getASourceSupertype*().getSourceDeclaration()` as the latter performed better.
=> Java: Improve join-order for `not haveIntersection`.

java/ql/lib/semmle/code/java/dispatch/WrappedInvocation.qll
Minor join-order improvement. This was taking a lot of slots in the join-order badness reports.
=> Java: Improve join-order.

java/ql/src/Violations of Best Practice/Naming Conventions/ConfusingOverloading.ql
The
```
exists(RefType commonSubtype | hasSubtypeOrInstantiation*(t1, commonSubtype) |
hasSubtypeOrInstantiation*(t2, commonSubtype)
)
```
construction is very expensive, so this change magics that as much as possible, including by noting that the above snippet implies `haveIntersection(t1, t2)` (the converse doesn't hold).
There's also a minor bugfix to account for `t1 = t2` for primitive types.
=> Java: Improve performance of ConfusingOverloading.

.github/actions/fetch-codeql/action.yml
This pull request changes the default CodeQL version used by CI jobs to be the `nightly` release. Before we used the latest stable release which could lag behind the bleeding edge main branch of CodeQL quite a bit causing friction.
=> Use 'gh codeql' with the nightly release for CI jobs

config/identical-files.json, swift/ql/lib/codeql/swift/elements/Comment.qll, swift/ql/test/TestUtilities/InlineExpectationsTest.qll, swift/ql/test/TestUtilities/InlineExpectationsTestPrivate.qll
Now that we have [comment extraction](https://github.com/github/codeql/pull/9977) we can start to make use of the `InlineExpectationsTest` framework. This PR adds the framework and instantiates it for Swift, but it doesn't actually _use_ it for anything yet.
Once we've merged this PR we can start to make use of it for writing dataflow tests.
=> Swift: Add InlineExpectationsTest framework

swift/ql/lib/codeql/swift/controlflow/CfgNodes.qll, swift/ql/lib/codeql/swift/dataflow/internal/FlowSummaryImplSpecific.qll, swift/ql/src/queries/Security/CWE-079/UnsafeWebViewFetch.ql
The `getCallTarget` predicate in our flow summary instantiation was suffering from the same problem as the one I described [here](https://github.com/github/codeql/pull/9673#discussion_r905171464): The call to `init(contentsOf:)` is really two calls (one providing the qualifier, and another one providing the `contentsOf` argument. Prior to this PR, the `getCallTarget` predicate was giving us the function that provided the qualifier.
cc @geoffw0.
Note: Once we merge https://github.com/github/codeql/pull/9891 this class of issues will be gone (since we can provide a much better API for function calls then)
=> Swift: Fix flow summaries for methods

javascript/extractor/src/com/semmle/js/extractor/AutoBuild.java, javascript/extractor/src/com/semmle/js/extractor/ExtractorOptionsUtil.java, javascript/extractor/src/com/semmle/js/extractor/Main.java, javascript/extractor/src/com/semmle/js/extractor/trapcache/DefaultTrapCache.java, javascript/extractor/src/com/semmle/js/extractor/trapcache/ITrapCache.java
This PR refactors how we configure the TRAP cache for the JavaScript extractor. Previously, we had two different mechanisms:
1. In the autobuilder, via the `LGTM_TRAP_CACHE` environment variables.
2. In a direct invocation of the extractor, via the `--trap-cache` flags.
As far as I can tell, neither of these mechanisms is actually in use at the moment. So, before we create new uses for it, let's take the opportunity to refactor both those code paths to flow through the same place, and be configured by the new extractor options functionality documented [here](https://codeql.github.com/docs/codeql-cli/extractor-options/), which is how the Action's upcoming TRAP caching feature will configure the cache.
As part of this, I've also added a new option that configures whether the cache should be …
=> JS: Change how TRAP cache is configured

.github/workflows/csv-coverage-timeseries.yml, .github/workflows/csv-coverage-update.yml, .github/workflows/csv-coverage.yml
This PR fixes the path of `.github/actions/fetch-codeql` where the CodeQL `actions/checkout@v3` is using a custom `path`.
=> Fix path of `fetch-codeql`

javascript/ql/lib/semmle/javascript/JSON.qll, javascript/ql/lib/semmle/javascript/NodeModuleResolutionImpl.qll, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialBackTracking.expected, javascript/ql/test/query-tests/Performance/ReDoS/PolynomialReDoS.expected, javascript/ql/test/query-tests/Performance/ReDoS/lib/subLib5/feature.js, javascript/ql/test/query-tests/Performance/ReDoS/lib/subLib5/main.js, javascript/ql/test/query-tests/Performance/ReDoS/lib/subLib5/package.json
drive-by binding of the result in `JsonValue::getBooleanValue` (the IDE was complaining about unbound value).  
Refs: 
- https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#package-json-exports-imports-and-self-referencing 
- https://nodejs.org/api/packages.html#packages_exports 
[Evaluation was uneventful](https://github.com/github/codeql-dca-main/tree/data/PR-9548-0-javascript__1/reports).
=> JS: support the "exports" property in a package.json

swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowGraphImpl.qll, swift/ql/test/library-tests/controlflow/graph/Cfg.expected, swift/ql/test/query-tests/Security/CWE-079/UnsafeWebViewFetch.expected, swift/ql/test/query-tests/Security/CWE-079/UnsafeWebViewFetch.swift
We were not constructing CFGs for `any!` expressions. This led to unreachable CFG nodes, which led to missing dataflow nodes (as observed by @geoffw0).
=> Swift: CFG for `any!`

ruby/ql/lib/codeql/ruby/frameworks/core/Hash.qll, ruby/ql/test/library-tests/dataflow/hash-flow/hash-flow.expected, ruby/ql/test/library-tests/dataflow/hash-flow/hash_flow.rb
The existing summaries could be simplified using the models-as-data token `Argument[hash-splat]`, which refers to both keyword arguments wrapped in an implicit hash, as well as explicit hash splat arguments.
=> Ruby: Simplify flow summaries for hash literals

python/ql/lib/semmle/python/essa/Essa.qll
Before:
```
Tuple counts for Essa::EssaEdgeRefinement::getInput#dispred#f0820431#ff/2@b84afc77 after 20.3s:
873421    ~0%     {3} r1 = JOIN Essa::TEssaEdgeDefinition#24e22a14#ffff_31#join_rhs WITH Essa::TEssaEdgeDefinition#24e22a14#ffff_30#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.0 'this'
181627951 ~0%     {3} r2 = JOIN r1 WITH Essa::EssaDefinition::getSourceVariable#dispred#f0820431#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'result', Lhs.1, Lhs.2 'this'
873418    ~0%     {2} r3 = JOIN r2 WITH Essa::EssaDefinition::reachesEndOfBlock#dispred#f0820431#ff ON FIRST 2 OUTPUT Lhs.2 'this', Lhs.0 'result'
return r3
```
It's perhaps not immediately obvious what's going on here (because of the `...join_rhs` indirection), but basically we're joining together `this` and `def` and their …
=> Python: Fix bad join in ESSA `getInput`

csharp/tools/tracing-config.lua
This PR moves logic for handling `dotnet exec csc.dll` and friends from [the extractor](https://github.com/github/codeql/blob/main/csharp/extractor/Semmle.Extraction.CSharp.Driver/Driver.cs#L18) into the new Lua tracer spec. The benefit of doing so is that we can avoid unnecessary process creations, and logically doing compiler matching belongs to the tracer spec, and not the extractor.
Note that the logic has not yet been removed from the extractor; we will do so once the legacy tracer is retired.
Thanks to @criemen for helping out.
=> C#: Handle `dotnet exec csc.dll` and the likes in the Lua tracer

java/ql/lib/semmle/code/java/security/SensitiveLoggingQuery.qll, java/ql/src/change-notes/2022-08-10-sensitive-log-dedup.md
This query was particularly prone to source-to-source flow due to its heuristic nature of its source definition. So adding an `inBarrier` will remove a lot of results that are effectively useless duplicates. In one observed case this removed several thousand results.
=> Java: Remove SensitiveLoggingQuery results that flow through a source.

swift/ql/lib/codeql/swift/elements/typerepr/ArrayTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/AttributedTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/CompileTimeConstTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/CompoundIdentTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/DictionaryTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/FunctionTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/GenericIdentTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/ImplicitlyUnwrappedOptionalTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/InOutTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/IsolatedTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/MetatypeTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/OptionalTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/OwnedTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/ProtocolTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/SharedTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/SilBoxTypeRepr.qll, swift/ql/lib/codeql/swift/elements/typerepr/TupleTypeRepr.qll
It looks like https://github.com/github/codeql/pull/9805 forgot to delete some files, and those files don't compile 
(QL-for-QL didn't like that). 
So I deleted them.
=> delete the dead TypeRepr files

python/ql/lib/semmle/python/pointsto/Base.qll
How it started:
```
Tuple counts for Base::BaseFlow::scope_entry_value_transfer_from_earlier#f76ef5bb#ffff/4@f2af49f5 after 18s:
1526390  ~0%     {3} r1 = JOIN Base::BaseFlow::scope_entry_value_transfer_from_earlier#f76ef5bb#ffff#shared WITH Essa::EssaVariable::getScope#dispred#f0820431#ff ON FIRST 1 OUTPUT Rhs.1 'pred_scope', Lhs.0 'pred_var', Lhs.1
7798319  ~0%     {4} r2 = JOIN r1 WITH Scope::Scope::precedes#dispred#f0820431#ff ON FIRST 1 OUTPUT Rhs.1 'succ_scope', Lhs.1 'pred_var', Lhs.2, Lhs.0 'pred_scope'
5427334  ~0%     {4} r3 = JOIN Base::BaseFlow::scope_entry_value_transfer_from_earlier#f76ef5bb#ffff#shared#1 WITH Scope::Scope::precedes#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.1 'pred_var', Lhs.2, Lhs.0 'pred_scope', Rhs.1 'succ_scope'
5426883  ~0%     {4} r4 = r3 AND NOT …
```
=> Python: Fix bad join in scope entry transfer

cpp/ql/src/Metrics/Internal/IRConsistency.ql
Turns out there were more of these than I expected. So, for DCA we might still sum these up to a single number.
This is internal, so I do not think a change note is required.
=> C++: Add internal metrics query for IR consistency

csharp/ql/lib/semmle/code/csharp/security/dataflow/UnsafeDeserializationQuery.qll, csharp/ql/src/change-notes/2022-08-11-unsafe-deserialization.md, csharp/ql/test/query-tests/Security Features/CWE-502/UnsafeDeserializationUntrustedInputNewtonsoftJson/Test.cs, csharp/ql/test/query-tests/Security Features/CWE-502/UnsafeDeserializationUntrustedInputNewtonsoftJson/UnsafeDeserializationUntrustedInput.expected, csharp/ql/test/query-tests/Security Features/CWE-502/UnsafeDeserializationUntrustedInputNewtonsoftJson/UnsafeDeserializationUntrustedInput.qlref, csharp/ql/test/query-tests/Security Features/CWE-502/UnsafeDeserializationUntrustedInputNewtonsoftJson/options, csharp/ql/test/resources/stubs/Newtonsoft.Json/13.0.1/Newtonsoft.Json.cs
This PR is fixing a false positive in `UnsafeDeserializationUntrustedInput.ql`. Namely the check is not going to report on all calls of `JsonConvert.DeserializeObject`, only on the ones where explicitly unsafe serialization settings are used.
Additionally, the `Newtonsoft.Json` test stubs are regenerated to include enum constant values, which are needed for the check to work.
=> C#: Fix unsafe deserialization with `JsonConvert.DeserializeObject`

javascript/ql/lib/semmle/javascript/NPM.qll, javascript/ql/lib/semmle/javascript/NodeModuleResolutionImpl.qll, javascript/ql/lib/semmle/javascript/PackageExports.qll
https://github.com/github/codeql/pull/9548 caused problems for generated typings, since it does not distinguish between the main entry point of a package, versus a file that is exported under a non-trivial relative path.
For example, with these exports
```
{
"exports": {
".": "./main.js",
"./foo": "./foo.js"
}
}
```
the typings for `foo.d.ts` would be incorrectly merged with those from `main.d.ts`.
=> JS: More precise handling of "exports"

go/ql/lib/change-notes/2022-08-12-cross-thread-flow.md, go/ql/lib/semmle/go/controlflow/ControlFlowGraph.qll, go/ql/lib/semmle/go/dataflow/internal/ContainerFlow.qll, go/ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll, go/ql/lib/semmle/go/dataflow/internal/DataFlowPrivate.qll, go/ql/test/library-tests/semmle/go/dataflow/FlowSteps/LocalFlowStep.expected
Steps into captured variables are moved into jumpStep where they always should have been, and the store/load step implementation for channels is completed.
For the time being this takes a very conservative approach to identify channels that are likely connected: if there is exactly one receive site and one send site for a field, the two are presumed connected.
=> Go: implement conservative cross-thread dataflow

java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/kotlin-extractor/src/main/kotlin/utils/List.kt
They can throw if their argument is null, so we should explicitly check for null ourselves so that we can recover as well as possible.
=> Kotlin: Remove not-null-expressions from KotlinUsesExtractor

python/ql/lib/semmle/python/essa/Essa.qll
Before:
```
Tuple counts for Essa::ScopeEntryDefinition#class#24e22a14#f/1@45e0d8dh after 10.5s:
2133368   ~1%     {2} r1 = Essa::TEssaNodeDefinition#24e22a14#ffff_03#join_rhs AND NOT Essa::ImplicitSubModuleDefinition#class#24e22a14#f(Lhs.1 'this')
534478950 ~0%     {2} r2 = JOIN r1 WITH Definitions::SsaSourceVariable::getScopeEntryDefinition#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.1 'this', Rhs.1
581249    ~4%     {1} r3 = JOIN r2 WITH Essa::EssaNodeDefinition::getDefiningNode#dispred#f0820431#ff ON FIRST 2 OUTPUT Lhs.0 'this'
return r3
```
Let's see if pushing the `getDefiningNode` join further up improves the number of intermediary tuples. (Intuitively it should, since there should only be one defining node for any given `EssaNodeDefinition`.)
To do this, we unbind the …
=> Python: Fix bad join in `ScopeEntryDefinition`

python/ql/lib/semmle/python/types/ImportTime.qll
Much sadness:
```
Tuple counts for ImportTime::ImportTimeScope::getOuterVariable#dispred#f0820431#fff/3@64d04d33 after 7.6s:
19624    ~1%     {1} r1 = SCAN py_Classes OUTPUT In.0 'this'
19531    ~1%     {1} r2 = JOIN r1 WITH ImportTime::ImportTimeScope#class#7851b601#f ON FIRST 1 OUTPUT Lhs.0 'this'
19531    ~0%     {2} r3 = JOIN r2 WITH Scope::Scope::getEnclosingModule#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.0 'this', Rhs.1
296389   ~0%     {3} r4 = JOIN r3 WITH Variables::Variable::getScope#dispred#f0820431#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'var', Lhs.0 'this', Lhs.1
296389   ~0%     {3} r5 = JOIN r4 WITH Variables::LocalVariable#3aa06bbf#f ON FIRST 1 OUTPUT Lhs.0 'var', Lhs.1 'this', Lhs.2
296389   ~1%     {4} r6 = JOIN r5 WITH Variables::Variable::getId#dispred#f0820431#ff ON …
```
=> Python: Fix bad join in `getOuterVariable`

cpp/ql/src/Likely Bugs/OO/NonVirtualDestructorInBaseClass.qhelp, cpp/ql/src/jsf/4.10 Classes/AV Rule 78.qhelp, java/ql/src/Metrics/Files/FNumberOfClasses.qhelp, java/ql/src/Security/CWE/CWE-113/ResponseSplitting.qhelp, javascript/ql/src/LanguageFeatures/ConditionalComments.qhelp, javascript/ql/src/Metrics/FUseOfES6.qhelp, python/ql/src/Security/CWE-295/RequestWithoutValidation.qhelp
This PR eliminates some broken HTTP links in *.qhelp files. The PR focuses specifically on `qhelp` files to ensure the changes are low-risk doc changes. 
This PR takes a (very) small step towards eliminating some of the http links throughout this repo, as mentioned in [this issue](https://github.com/github/codeql/issues/5163). Before we do a simple search and replace, I thought a good start would be to remove the broken (HTTP status 403 / 404) links.
Just make sure the new links work, and are appropriate for the context in which they are being used. Best reviewed one commit at a time 🍻 🍕 
```sh
grep -Eo "http://[a-zA-Z0-9./?=_-]*" -r --no-filename --include \*.qhelp . | sort -u > httpUrls.txt
```
```js
import fetch, { AbortError } from 'node-fetch';
import fs from 'fs';
const …
```
=> Docs: Replace HTTP broken links to equivalent HTTPS resources

cpp/ql/lib/semmle/code/cpp/ir/implementation/aliased_ssa/IRConsistency.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/raw/IRConsistency.qll, cpp/ql/lib/semmle/code/cpp/ir/implementation/unaliased_ssa/IRConsistency.qll, cpp/ql/src/Metrics/Internal/IRConsistency.ql, csharp/ql/src/experimental/ir/implementation/raw/IRConsistency.qll, csharp/ql/src/experimental/ir/implementation/unaliased_ssa/IRConsistency.qll
The `toString` implementtion that `PresentIRFunction` uses may result in very long strings that may crash the evaluator. Overriding allows is to limit the string size and still suffices when just counting the number of inconsistencies.
=> C++: Expose `PresentIRFunction` and override in `cpp/count-ir-inconsistencies`

.github/workflows/ql-for-ql-tests.yml, ql/Cargo.lock, ql/extractor/Cargo.toml, ql/generator/Cargo.toml, ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/codeql_ql/ast/internal/AstNodes.qll, ql/ql/src/codeql_ql/ast/internal/Module.qll, ql/ql/src/codeql_ql/ast/internal/TreeSitter.qll, ql/ql/src/ql.dbscheme, ql/ql/test/callgraph/ParamSig.qll, ql/ql/test/callgraph/callgraph.expected
See the test-case for an example.  
The syntax is not yet supported in the latest version of CodeQL, but that will happen soon. 
(See the backref).  
I don't quite like how the grammar is done, but I don't see a better way. 
I can't in the grammar always determine if something is a reference to a module, or to some other type.  
One solution would just be to combine it all into one big `TypeExpr`.  
But in some places we know that the reference cannot be a module, so I want to keep those grammar rules separate.   
In the QL side it all becomes a `TypeRef`, so it all ends up working, even though some references to modules might be parsed as a `TypeExpr` instead of a `ModuleExpr`.  
A review of https://github.com/tree-sitter/tree-sitter-ql/pull/18 would also be nice 🥺
=> QL: support signature parameters in QL-for-QL

ruby/ql/lib/codeql/ruby/ast/internal/Synthesis.qll, ruby/ql/test/library-tests/ast/AstDesugar.ql
I assume deprecation and changenote are not required, since this is in an internal module.
=> Ruby: fix typo: s/Desugered/Desugared

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt, java/kotlin-extractor/src/main/kotlin/KotlinUsesExtractor.kt, java/kotlin-extractor/src/main/kotlin/TrapWriter.kt, java/kotlin-extractor/src/main/kotlin/utils/TypeResults.kt
We statically know when we expect to have no signature, so now we tell the type system what we know, rather than having signature always be nullable.
=> Kotlin: Refactor TypeResults

javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingFunction/PrototypePollutingFunction.expected, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingFunction/tests.js
Fixes #9869 
[Evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-10046-14cfe2__nightly-old__code-scanning/reports).
=> JS: generalize `BarrierGuardFunction`to work on function that have multiple parameters

ruby/ql/lib/codeql/ruby/security/LogInjectionQuery.qll, ruby/ql/src/change-notes/2022-08-10-log-injection-query.md, ruby/ql/src/queries/security/cwe-117/LogInjection.qhelp, ruby/ql/src/queries/security/cwe-117/LogInjection.ql, ruby/ql/src/queries/security/cwe-117/examples/log_injection_bad.rb, ruby/ql/src/queries/security/cwe-117/examples/log_injection_good.rb, ruby/ql/test/query-tests/security/cwe-117/LogInjection.expected, ruby/ql/test/query-tests/security/cwe-117/LogInjection.qlref, ruby/ql/test/query-tests/security/cwe-117/app/controllers/users_controller.rb
Detects some cases where a logging call may allow a malicious user to forge new log entries. The concrete implementation is mostly identical to the JS version of this query.
=> Ruby: Add `rb/log-injection` query 

python/ql/lib/semmle/python/pointsto/PointsTo.qll
The culprit:
```
Tuple counts for PointsTo::InterProceduralPointsTo::scope_entry_value_transfer_from_earlier#741b54e2#ffff#join_rhs/5@eb1340iv after 12.6s:
72973    ~3%     {2} r1 = JOIN PointsToContext::TImportContext#cf3039a0#f WITH Definitions::NonEscapingGlobalVariable#class#486534ab#f CARTESIAN PRODUCT OUTPUT Rhs.0, Lhs.0 'arg1'
537932   ~0%     {3} r2 = JOIN r1 WITH Essa::EssaDefinition::getSourceVariable#dispred#f0820431#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'arg2', Lhs.1 'arg1', Lhs.0
982333   ~0%     {4} r3 = JOIN r2 WITH Essa::EssaVariable::getAUse#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.2, Lhs.1 'arg1', Lhs.0 'arg2', Rhs.1 'arg0'
37029774 ~0%     {4} r4 = JOIN r3 WITH Essa::TEssaNodeDefinition#24e22a14#ffff ON FIRST 1 OUTPUT Rhs.3 'arg3', Lhs.1 'arg1', Lhs.2 'arg2', Lhs.3 …
```
=> Python: Fix another bad "value transfer" join

java/ql/lib/semmle/code/java/security/SensitiveLoggingQuery.qll, java/ql/src/change-notes/2022-08-18-sensitive-log-sanitizer.md
The source definition is rather ad-hoc in this query, so filtering nodes based on some safe types can help remove FPs.
=> Java: Add some type-based sanitizers to SensitiveInfoLog.ql.

ruby/ql/lib/codeql/ruby/ApiGraphs.qll
Fixes https://github.com/github/codeql-team/issues/929.
=> Ruby: Get rid of warning in `getUnknownMember`

ruby/ql/lib/change-notes/2022-08-16-action-controller-response-body.md, ruby/ql/lib/codeql/ruby/frameworks/ActionController.qll, ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll, ruby/ql/test/library-tests/frameworks/ActionController.expected, ruby/ql/test/library-tests/frameworks/ActionView.expected, ruby/ql/test/library-tests/frameworks/ActionView.ql, ruby/ql/test/library-tests/frameworks/app/controllers/foo/bars_controller.rb
What it says on the tin. We now recognise calls to `render`, `render_to_string` and `render_to_body` such as
```rb
def show
render json: { some: "data" }
render @user
render html: "<p>hello</p>"
end
```
as instances of `HTTP::Server::HttpResponse`.
@nickrolfe hopefully this will be useful for you!
=> Ruby: Recognise Rails render calls as HTTP responses

csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll, csharp/ql/lib/semmle/code/csharp/dataflow/internal/DataFlowPublic.qll, csharp/ql/lib/semmle/code/csharp/exprs/Call.qll, csharp/ql/src/utils/model-generator/internal/CaptureModelsSpecific.qll
As discussed with @aschackmull offline, it makes sense to include source code also when there is a manually written flow summary, since there might be a source or a sink in the source code that was not modeled.
=> C#: Include both source code and hand-written summaries in data flow

ruby/ql/lib/codeql/ruby/dataflow/internal/DataFlowPrivate.qll, ruby/ql/src/queries/security/cwe-116/IncompleteSanitization.ql, ruby/ql/test/library-tests/dataflow/type-tracker/TypeTracker.expected
Alternative to https://github.com/github/codeql/pull/9175.
I have verified, locally, that the analysis is now able to run on https://github.com/rapid7/metasploit-framework without timing out.
=> Ruby: Reduce size of `isLocalSourceNode`

go/ql/lib/semmle/go/controlflow/ControlFlowGraph.qll, go/ql/lib/semmle/go/dataflow/internal/ContainerFlow.qll, go/ql/lib/semmle/go/dataflow/internal/DataFlowNodes.qll, go/ql/test/library-tests/semmle/go/dataflow/ChannelField/test.expected, go/ql/test/library-tests/semmle/go/dataflow/ChannelField/test.go, go/ql/test/library-tests/semmle/go/dataflow/ChannelField/test.ql
I overlooked the fact that this has a WriteInstruction, which wasn't bound in the channel-write case, but somehow the evaluator discarded the implied cartesian product until last night's performance evaluation.
Rather than try to cram channel writes into WriteInstruction, just handle them as their own beast.
=> Go: don't use WriteNode for channel writes

java/ql/src/Security/CWE/CWE-681/NumericCastTainted.ql
The exclusion of right-shifted variables on sinks is probably better as a sanitizer, so move it there. That should help performance a bit and possibly also remove some FPs.
Also, there was a somewhat arbitrary-looking restriction that the sink has to be a variable access. I'm not going to consider whether that restriction ought to lifted (it's probably fine to keep), but we might as well make it explicit and move it into the configuration to gain some performance.
=> Java: Move sink-constraints into the configuration in NumericCastTainted.ql.

ql/ql/src/codeql_ql/ast/Ast.qll, ql/ql/src/queries/style/ConsistentAlertMessage.ql, ql/ql/src/queries/style/docs/ClassDocs.ql, ql/ql/src/queries/style/docs/PredicateDocs.ql
And drive-by remove some alerts on deprecated predicates/classes.  
[I got a WIP branch were I've fixed most of the alerts introduced by the new query](https://github.com/github/codeql/pull/9816).
=> QL: add ql/consistent-alert-message

csharp/ql/lib/semmle/code/csharp/frameworks/microsoft/AspNetCore.qll, csharp/ql/lib/semmle/code/csharp/security/dataflow/flowsources/Remote.qll, csharp/ql/src/change-notes/2022-08-16-aspnetcore-remoteflowsources.md, csharp/ql/test/library-tests/dataflow/flowsources/aspremote/AspRemoteFlowSource.cs, csharp/ql/test/library-tests/dataflow/flowsources/aspremote/aspRemoteFlowSource.expected
Parameters of delegates passed to routing endpoint calls like `MapGet` in ASP.NET Core are now considered remote flow sources.
=> C#: ASP.NET MapGet Routing endpoints (Remote Flow Sources)

cpp/ql/src/Security/CWE/CWE-078/ExecTainted.ql
Prior to this PR, the sink in `ExecTaintConfiguration` was a cartesian product between all concatenation-like functions and all shell-command executing functions (😱) This PR introduces another taint tracking configuration that limits the possible flow states to only those that are relevant for a given sink.
Here are some numbers from Samate:
On `main`:
```
Tuple counts for DataFlowImpl#9021cc4c::sinkNode#fff/3@1ba010mo after 17.3s:
48709004  ~6%     {3} r1 = SCAN num#DataFlowImpl#9021cc4c::TNodeNormal#ff OUTPUT In.0, "ExecTaintConfiguration", In.1 'node'
10846     ~0%     {2} r2 = JOIN r1 WITH ExecTainted#91000ffb::ExecTaintConfiguration::isSink#dispred#cpe#2#f ON FIRST 1 OUTPUT "ExecTaintConfiguration", Lhs.2 'node'
235097896 ~0%     {3} r3 = JOIN r2 WITH …
```
=> C++: Remove CP in `cpp/command-line-injection`

python/ql/lib/semmle/python/Exprs.qll
This makes the AST viewer (which annotates string constant nodes as `Str`, and not `StrConst`) a bit more consistent.
Fixes #9833. 
It might be even better to instead flip the inheritance and make `Str` the lowest class in the hierarchy. That way, it would have access to all of the methods on `StrConst` (and indeed, we might consider just deprecating that class).
---
This is a very minor change, so I don't think a change note is required.
=> Python: Add `Str` class

cpp/ql/lib/change-notes/2022-08-22-link-targets-for-variables.md, cpp/ql/lib/semmle/code/cpp/Linkage.qll, cpp/ql/lib/semmle/code/cpp/Variable.qll
This can be safely merged before the internal PR. The new predicates will just be no-ops as long as the internal PR isn't merged. DCA ran on internal PR.
=> C++: Support link targets for global and namespace variables

java/ql/lib/change-notes/2022-08-19-androidx-fragments.md, java/ql/lib/semmle/code/java/frameworks/android/Fragment.qll, java/ql/test/library-tests/frameworks/android/fragments/TestFragment.java, java/ql/test/library-tests/frameworks/android/fragments/options, java/ql/test/library-tests/frameworks/android/fragments/test.expected, java/ql/test/library-tests/frameworks/android/fragments/test.ql, java/ql/test/library-tests/frameworks/android/sources/TestActivityAndFragment.java, java/ql/test/query-tests/security/CWE-470/MainActivity.java, java/ql/test/stubs/google-android-9.0.0/androidx/core/app/ActivityCompat.java, java/ql/test/stubs/google-android-9.0.0/androidx/core/app/SharedElementCallback.java, java/ql/test/stubs/google-android-9.0.0/androidx/core/content/ContextCompat.java, java/ql/test/stubs/google-android-9.0.0/androidx/core/view/DragAndDropPermissionsCompat.java, java/ql/test/stubs/google-android-9.0.0/androidx/fragment/app/BackStackRecord.java, java/ql/test/stubs/google-android-9.0.0/androidx/fragment/app/Fragment.java, java/ql/test/stubs/google-android-9.0.0/androidx/fragment/app/FragmentActivity.java, java/ql/test/stubs/google-android-9.0.0/androidx/fragment/app/FragmentFactory.java, java/ql/test/stubs/google-android-9.0.0/androidx/fragment/app/FragmentManager.java, java/ql/test/stubs/google-android-9.0.0/androidx/fragment/app/FragmentTransaction.java, java/ql/test/stubs/google-android-9.0.0/androidx/lifecycle/HasDefaultViewModelProviderFactory.java, java/ql/test/stubs/google-android-9.0.0/androidx/lifecycle/Lifecycle.java, java/ql/test/stubs/google-android-9.0.0/androidx/lifecycle/LifecycleObserver.java, java/ql/test/stubs/google-android-9.0.0/androidx/lifecycle/LifecycleOwner.java, java/ql/test/stubs/google-android-9.0.0/androidx/lifecycle/ViewModel.java, java/ql/test/stubs/google-android-9.0.0/androidx/lifecycle/ViewModelProvider.java, java/ql/test/stubs/google-android-9.0.0/androidx/lifecycle/ViewModelStore.java, java/ql/test/stubs/google-android-9.0.0/androidx/lifecycle/ViewModelStoreOwner.java, java/ql/test/stubs/google-android-9.0.0/androidx/loader/app/LoaderManager.java, java/ql/test/stubs/google-android-9.0.0/androidx/savedstate/SavedStateRegistry.java, java/ql/test/stubs/google-android-9.0.0/androidx/savedstate/SavedStateRegistryOwner.java
`android.app.Fragment` is [deprecated](https://developer.android.com/reference/android/app/Fragment). This PR adds support for the new version, [`androidx.fragment.app.Fragment`](https://developer.android.com/reference/androidx/fragment/app/Fragment.html), which should help with our Android analysis by detecting more fragments.
=> Java: Add support for androidx.fragment.app.Fragment

.github/workflows/ql-for-ql-build.yml, .github/workflows/ql-for-ql-dataset_measure.yml, .github/workflows/ql-for-ql-tests.yml
The previous version was from back in March. 
The updated version of `codeql-action` is the latest `main` + a commit that adds `ql` as a supported language. 
I had to update how we do the config file to support the changes that has happened in `codeql-action`.
=> QL: update codeql-action in QL-for-QL

cpp/ql/src/Security/CWE/CWE-311/CleartextBufferWrite.ql, cpp/ql/src/change-notes/2022-08-22-cleartext-buffer-write-sanitizer.md
This is the easy part of https://github.com/github/codeql/pull/10117:
> The second performance fix is to block flow through integral typed expressions in the query. We have used similar sanitizers in other queries to fix FPs, so this is a natural thing to do in this query as well, and it seems to dramatically improve the query's performance.
I pulled this out to a separate PR so it's not needlessly delayed by the unrelated `jumpStep` change.
=> C++: Add a sanitizer to `cpp/cleartext-storage-buffer`

java/ql/src/Security/CWE/CWE-730/PolynomialReDoS.ql, java/ql/src/Security/CWE/CWE-730/ReDoS.ql, java/ql/src/change-notes/2022-08-23-redos-cwe-1333.md
All ReDoS queries in other languages had this tag, so it makes sense for the Java versions to have it too.
=> Java: Add CWE-1333 tag to Java ReDoS queries

swift/ql/test/library-tests/dataflow/dataflow/DataFlow.ql, swift/ql/test/library-tests/dataflow/dataflow/DataFlowInline.ql, swift/ql/test/library-tests/dataflow/dataflow/FlowConfig.qll, swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected, swift/ql/test/library-tests/dataflow/dataflow/test.swift
I also took the liberty of adding a bunch of field-flow tests which will be helpful for https://github.com/github/codeql-c-team/issues/903.
=> Swift: Use `InlineExpectationsTest` for dataflow tests

go/codeql-tools/tracing-config.lua
This should fix errors like:
```
[T 17:40:07 5848] Unable to invoke extractor using command line ""C:\hostedtoolcache\windows\CodeQL\0.0.0-20220811\x64\codeql\go\tools\win64\go-extractorgo-extractor.exe" --mimic "c:\hostedtoolcache\windows\go\1.19.0\x64\bin\go.exe" build main.go".
```
=> Go: fix tracing spec for windows

java/kotlin-extractor/src/main/kotlin/KotlinExtractorExtension.kt, java/ql/integration-tests/posix-only/kotlin/trap_compression/test.kt, java/ql/integration-tests/posix-only/kotlin/trap_compression/test.py
The Kotlin extractor can now be told to write TRAP with no compression, gzip compression or Brotli compression - although Brotli is not yet supported and it will fall back to gzip.
The invocation TRAP file is a bit more complicated, as it's already been started before the extractor starts. For now that continues to always be uncompressed.
=> Kotlin: Add support for TRAP compression

javascript/ql/lib/semmle/javascript/Arrays.qll, javascript/ql/lib/semmle/javascript/PackageExports.qll, javascript/ql/lib/semmle/javascript/dataflow/Configuration.qll, javascript/ql/lib/semmle/javascript/dataflow/DataFlow.qll, javascript/ql/lib/semmle/javascript/dataflow/Sources.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/DataFlowNode.qll, javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSteps.qll, javascript/ql/lib/semmle/javascript/security/dataflow/PrototypePollutingAssignmentCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeCodeConstructionCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeHtmlConstructionCustomizations.qll, javascript/ql/lib/semmle/javascript/security/dataflow/UnsafeShellCommandConstructionCustomizations.qll, javascript/ql/lib/semmle/javascript/security/regexp/PolynomialReDoSCustomizations.qll, javascript/ql/test/library-tests/DataFlow/tests.expected, javascript/ql/test/library-tests/InterProceduralFlow/tests.expected, javascript/ql/test/library-tests/TaintTracking/BasicTaintTracking.expected, javascript/ql/test/library-tests/TaintTracking/DataFlowTracking.expected, javascript/ql/test/library-tests/TaintTracking/arrays-init.js, javascript/ql/test/library-tests/TaintTracking/call-apply.js, javascript/ql/test/library-tests/frameworks/Collections/test.expected, javascript/ql/test/library-tests/frameworks/Collections/tst.js, javascript/ql/test/library-tests/frameworks/HTTP-heuristics/UnpromotedRouteHandlerCandidate.expected, javascript/ql/test/library-tests/frameworks/HTTP-heuristics/tests.expected, javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialBackTracking.expected, javascript/ql/test/query-tests/Security/CWE-400/ReDoS/PolynomialReDoS.expected, javascript/ql/test/query-tests/Security/CWE-400/ReDoS/lib/lib.js, javascript/ql/test/query-tests/Security/CWE-915/PrototypePollutingAssignment/PrototypePollutingAssignment.expected
For some context see this external contribution that never got merged: https://github.com/github/codeql/pull/6559 
The [improve performance of global dataflow by inlining a step predicate](https://github.com/github/codeql/commit/354eca001fa2715e62b0fb8c09e3273ff669d5c1) commit got the predicate from 4m8s to 1m36s on `bwip-js`.  
[An evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/myApply__nightly-old__code-scanning/reports). There are a few new results, and the performance looks good.  
(The new `js/unsafe-jquery-plugin` results are from the new `arguments` node, the others are from the improved flow through arrays).  
In an earlier evaluation I did a comparison where I disabled `ReflectiveParametersNode`: …
=> JS: precise flow through calls to `.apply()`

swift/ql/lib/codeql/swift/controlflow/CfgNodes.qll, swift/ql/lib/codeql/swift/controlflow/internal/ControlFlowElements.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowDispatch.qll, swift/ql/lib/codeql/swift/dataflow/internal/DataFlowPrivate.qll, swift/ql/test/library-tests/dataflow/dataflow/DataFlow.expected, swift/ql/test/library-tests/dataflow/dataflow/LocalFlow.expected, swift/ql/test/query-tests/Security/CWE-135/StringLengthConflation.expected
(Part of https://github.com/github/codeql-c-team/issues/903.)
This is the first of two dataflow PRs for field flow for Swift. It models property getters, setters, and observers as callables in the dataflow library. At the moment, this doesn't give us any field flow, but once we add read and store steps the dataflow library will see these getters and setters as read and writes steps.
Note that there's a slight error in the way we model the arguments to a `didSet` observer: we're passing the new value as an argument to the `didSet` observer, but the `didSet` observer actually takes the _old_ value as an argument. I plan on fixing this in a later PR.
Finally, this PR also fixes an issue with multiple `toString`s. The `toString` predicate had multiple results because `NormalParameterNode` was …
=> Swift: Model property getters, setters and observers as callables

ruby/ql/lib/codeql/ruby/ApiGraphs.qll
Let's see if this does the trick. The problem was the following join-order:
```
Evaluated recursive predicate ApiGraphs#3116a2f3::API::Impl::trackUseNode#2#fff@ce9ac9do in 51821ms on iteration 43 (delta size: 4222306).
Evaluated relational algebra for predicate ApiGraphs#3116a2f3::API::Impl::trackUseNode#2#fff@ce9ac9do on iteration 43 running pipeline standard with tuple counts:
3770177   ~0%    {3} r1 = SCAN ApiGraphs#3116a2f3::API::Impl::trackUseNode#2#fff#prev_delta OUTPUT In.2, In.0, In.1
461567525  ~64%    {5} r2 = JOIN r1 WITH ApiGraphs#3116a2f3::API::Impl::trackUseNode#2#fff#join_rhs ON FIRST 1 OUTPUT Lhs.2, Rhs.3, Rhs.2, Rhs.1, Lhs.1
10791924  ~66%    {5} r3 = JOIN r2 WITH TypeTracker#6f8aa30b::Cached::append#2#fff ON FIRST 3 OUTPUT Lhs.3, Lhs.1, Lhs.4, Lhs.1, Lhs.2
4936050  ~21% …
```
=> Ruby: Perf fix for trackUseNode.

java/kotlin-extractor/src/main/kotlin/KotlinFileExtractor.kt
Also refactored `writeUpdateInPlaceExpr` and one of its users so that we don't write any TRAP before we know that we are going to succeed.
=> Kotlin: Remove the last not-null-expressions
